### ISSUE TITLE
Use proper wagner-fisher like algorithm for fuzzy search

### ISSUE THREAD

**Issue by sman908** [withfig/fig#100]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When I typed `fig settings az` `fig` should've shown `autocomplete.fuzzySearch`, but instead it shown nothing.

I suggest you use this already well working library hhttps://github.com/jhawthorn/fzy.git

### Details:
|macOS|Fig|Shell|
|----|----|----|
|11.3.1|Version 1.0.42 (B207)|/usr/local/bin/fish|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.42 (B207) 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/m/.fig/bin/fig
Accessibility: true
Number of specs: 107
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/m/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/fish/3.2.2/bin/fish (28823) - ttys006
Current working directory: /Users/m
Current window identifier: 18689/29209365E-259B-47DD-B832-308E365FCD2C% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mattschrage** [comment]
This is a good idea. The current implementation uses a regex - updating to wagner-fisher is probably the right call.

**Comment by brendanfalk** [comment]
we will change the functionality of fuzzy search to be this implementation

**Comment by mschrage** [comment]
This is implemented as of v1.0.55 :)
