### ISSUE TITLE
After the update, the auto-complete feature and showing available keyword is not working.

### ISSUE THREAD

**Issue by Pavelbure34** [withfig/fig#1003]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I am using zsh.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B383) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/dongbinsuh/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/anaconda3/bin:/opt/anaconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/dongbinsuh/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (980) - /dev/ttys001
Current working directory: /Users/dongbinsuh/Desktop/hwk/DBMSs/DBMSsAssignment1
Current window identifier: 105/% (com.apple.Terminal)
Path: /opt/anaconda3/bin:/opt/anaconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/dongbinsuh/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=38E90973-2A15-4715-AAD6-408B9D7A8B22
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM=1
  - FIG_TERM_VERSION=4.0.10
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB</pre>
</p>
</details>

**Comment by chaynabors** [comment]
@Pavelbure34 Sorry for the delay on this. Just a few questions.
- Does Fig work for you with the latest update?
- Is autocomplete just not popping up?
- What happens when you run `fig doctor`?
