### ISSUE TITLE
Fig stopped working, even reinstalled it

### ISSUE THREAD

**Issue by benwk** [withfig/fig#1006]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

It hasn't worked for a few days.

I've tried reinstalling fig and it still doesn't work. It only worked for a while in the tutorial after reinstallation.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B383) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/benjamin/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/benjamin/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/benjamin/.fig/bin:/Users/benjamin/.tools
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (18993) - /dev/ttys002
Current working directory: /Users/benjamin
Current window identifier: 61205/% (com.googlecode.iterm2)
Path: /Users/benjamin/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/benjamin/.fig/bin:/Users/benjamin/.tools
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:2FA46723-43F7-4CDB-B6CA-699F0FD408EA
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM=1
  - FIG_TERM_VERSION=4.0.10
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB</pre>
</p>
</details>

**Comment by benwk** [comment]
finally found out that it was caused by the emoji 🥷, everything works fine after removing emoji at the start of the prompt

- not work:
![unknown](https://user-images.githubusercontent.com/26141189/159052883-a5d3fc5a-729d-459e-a298-4ead08f7e378.png)

- working:
![image](https://user-images.githubusercontent.com/26141189/159053134-e920784a-ec71-4912-b0c2-5e9a27c8aa88.png)

Hope it helps.

**Comment by grant0417** [comment]
@benwk, I will investigate!
