### ISSUE TITLE
Accessibility is disabled, even if accessibility is already enabled

### ISSUE THREAD

**Issue by arfajarsetiaji** [withfig/fig#1007]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/arfajarsetiaji/.fig/bin/fig
Accessibility: false
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: installed!
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installed via Brew: true
Installation Script: true
PseudoTerminal Path: /Users/arfajarsetiaji/.pyenv/bin:/Users/arfajarsetiaji/.nvm/versions/node/v16.13.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/arfajarsetiaji/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/arfajarsetiaji
Current window identifier: ???
Path: /Users/arfajarsetiaji/.pyenv/bin:/Users/arfajarsetiaji/.nvm/versions/node/v16.13.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/arfajarsetiaji/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=7D03B701-3B59-4CA8-A614-6546C56CBBCD
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @arfajarsetiaji,

Try opening System Preferences > Privacy & Security > Accessibility, and then pressing the "-" button to remove Fig from the list. Afterwards, press the "+" button and manually add the Fig.app

This should resolve the issues. If not, try restarting your computer.

**Comment by brendanfalk** [comment]
Running `fig debug accessibility refresh` should fix!
