### ISSUE TITLE
关于 fig 的意外退出

### ISSUE THREAD

**Issue by GnaixEuy** [withfig/fig#1011]
#### 当我通过 fig 的提示进入中文路径的文件夹中时，fig 出现了意外退出 100%出现
"When I entered the folder of the Chinese path through the prompt of fig, fig unexpectedly exited 100%"
--- 
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.55 (B383)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B383) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/gnaixeuy/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /usr/local/opt/python@3.10/bin:/usr/local/opt/ruby/bin:/usr/local/bin/flutter/bin:/usr/local/opt/node@14/bin:/usr/local/opt/libpq/bin:/usr/local/opt/curl/bin:/usr/local/opt/m4/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/gnaixeuy/.fig/bin:/Users/gnaixeuy/Library/apache-tomcat-8.5.69/bin:/Users/gnaixeuy/.rvm/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by brendanfalk** [comment]
@GnaixEuy Thanks for reporting. Would you please be able to share a video of this happening? Would be great if you could share the text above so we can reproduce.

@grant0417 Will investigate.

Thanks for reporting!

**Comment by GnaixEuy** [comment]
Does the report refer to the crash log in the console? I'm not sure what information you need

**Comment by grant0417** [comment]
Hey @GnaixEuy, this should be fixed on the latest version of Fig v1.0.56!

**Comment by GnaixEuy** [comment]
This problem has indeed been improved in the new version, thank you for your efforts, but it takes a lot of time to wait after manually entering the Chinese folder, I hope to see better performance in the next version :)

**Comment by grant0417** [comment]
> This problem has indeed been improved in the new version, thank you for your efforts, but it takes a lot of time to wait after manually entering the Chinese folder, I hope to see better performance in the next version :)

Are you able to record a video to show the performance issue?
