### ISSUE TITLE
Fig doesn't initialize

### ISSUE THREAD

**Issue by spaceinvadev** [withfig/fig#1013]
### Description:
> Hi, fig won't start on my Mac anymore. I'm using a MacBook Pro (13-inch, M1, 2020).

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.53|/bin/zsh|

Here's the output of both `fig doctor` and `fig diagnostic`:

<details><summary><code>fig doctor</code></summary>
<p>
<pre>Let's make sure Fig is running...

✅ Fig bin exists
✅ Fig in PATH
✅ Fig is running

Let's check your dotfiles...

✅ Fig ENV variables are in ~/.profile
✅ Fig ENV variables are in ~/.zprofile
✅ Fig ENV variables are in ~/.bash_profile
✅ Fig ENV variables are in ~/.bashrc
✅ Fig ENV variables are in ~/.zshrc

Let's check if your system is compatible...

✅ Running macOS
✅ macOS version is 11.x or higher

Let's check what fig diagnostic says...

✅ Installation script
✅ Shell /bin/zsh is compatible
✅ Fig is installed in /Applications/Fig.app
✅ Autocomplete is enabled
✅ CLI tool path
✅ Accessibility is enabled
✅ PATH and PseudoTerminal PATH match
✅ Secure keyboard input

Let's check your integration statuses...

✅ iTerm integration is enabled
✅ VSCode integration is enabled

Fig still not working?
Run fig issue to let us know!
Or, email us at hello@fig.io!
</pre>
</p>
</details>

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.53 (B339) [ABC]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/spaceinvadev/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/spaceinvadev/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (54832) - /dev/ttys002
Current working directory: /Users/spaceinvadev/Development/freelance/legend-store
Current window identifier: 246/% (com.googlecode.iterm2)
Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/spaceinvadev/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:24B7FD86-DB74-42EB-8727-D60EA44582EC
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
We've made a lot of improvements - going to close this but if it's still broken let me know!

**Comment by tkoehlerlg** [comment]
Same Problem with same MacBook Pro (13-inch, M1, 2020).

```
❯ fig doctor

● /Users/torbenkoehler/.bashrc does not source pre integration
● /Users/torbenkoehler/.bash_profile does not source pre integration
✘ Daemon diagnostics: Daemon websocket error

  Websock next error: Io(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })
Attempting to fix automatically...
Re-running check...

✔ Daemon diagnostics

✔ Everything looks good!
```

**Comment by giedriusr** [comment]
Same here, getting that error from time to time.

**Comment by thewormman1961** [comment]
Used to work great on my Macbook air, stopped loading a day or so ago. Restarted Mac and reinstalled Fig but still not loading.
