### ISSUE TITLE
Launch on restart v/s Install on restart 

### ISSUE THREAD

**Issue by vinaya-devopsnow** [withfig/fig#1016]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Goto Settings --> Applications --> Launch on Start 
every-time mac os restarts, Fig try's to reinstall into application directory and not actually start the fig service
This is annoying actually.

### Details:
|macOS|Fig|Shell| 
|-|-|-|
|12.1.0|Version 1.0.53 (B339)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.53 (B339) [ABC – India]
 1.0.53
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/vkt/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/vkt/.fig/bin:
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by vinaya-devopsnow** [comment]
1. Let me update my fig and retry 

Every-time my machine restarts, i get below screen . If fig is already installed, i should not get the below screen, right ?

<img width="658" alt="Screenshot 2022-03-03 at 12 06 45 PM" src="https://user-images.githubusercontent.com/91895173/156510282-6d6e3ef4-1ead-447e-8d5f-563b2aa2b099.png">

and 

<img width="424" alt="Screenshot 2022-03-03 at 12 06 29 PM" src="https://user-images.githubusercontent.com/91895173/156510347-66c093ee-e36a-4a66-a255-60d06f930441.png">

**Comment by mschrage** [comment]
Try uninstalling Fig and then reinstalling. Make sure that you don't launch Fig directly from the DMG. Instead, move it to /Applications and launch it from there.
