### ISSUE TITLE
fig cannot connect to app.withfig.com/login

### ISSUE THREAD

**Issue by Sharvin26** [withfig/fig#1018]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:

I have installed fig terminal from https://fig.io/ and now I am getting following error:

<img width="1031" alt="Screenshot 2022-03-02 at 1 58 24 PM" src="https://user-images.githubusercontent.com/17084209/156323934-3568bfc9-b100-447b-8ff1-3b6435f580bb.png">

I have access to public internet and not using any vpn.

### Environment

```bash
OS: Mac OS Big Sur ( 11.6 )
Processor: Intel i7
```

**Comment by mschrage** [comment]
Hey @Sharvin26, if you go to https://app.withfig.com/login from the same device what do you see in the console?

**Comment by Sharvin26** [comment]
Hey @mschrage I get following response when I go to https://app.withfig.com/login. 

I didn't get anything on console so i have attached snapshot of network tab. Might be it would help you to debug the issue.

<img width="2555" alt="Screenshot 2022-03-03 at 12 14 40 PM" src="https://user-images.githubusercontent.com/17084209/156511606-b1469726-a8df-4a8d-86a9-ba7fdddba7cf.png">

**Comment by mschrage** [comment]
Can you try hotspotting on your phone and go to the same URL? This will remove your network as a potential source of error.
