### ISSUE TITLE
Did not work OSX 12.01.1

### ISSUE THREAD

**Issue by hardcore** [withfig/fig#1019]
### Description:
Tryed to use fig with git <tab-tab> (autocomplete) or other applications. Did not work in macOS Terminal or iTerm.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1 21A559|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B383) [German] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/sash/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/sash/.nvm/versions/node/v14.19.0/bin:/Users/sash/opt/anaconda3/bin:/Users/sash/opt/anaconda3/condabin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sash/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (98775) - /dev/ttys005
Current working directory: /Users/sash
Current window identifier: 8799/% (com.apple.Terminal)
Path: /Users/sash/.nvm/versions/node/v14.19.0/bin:/Users/sash/opt/anaconda3/bin:/Users/sash/opt/anaconda3/condabin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sash/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=4EF4805C-3F30-40A4-94C6-FED3EFA941D5
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM=1
  - FIG_TERM_VERSION=4.0.10
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.0.1 21A559
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @hardcore, can you run `fig doctor` and share the output here?

**Comment by hardcore** [comment]
Hi @mschrage,

I've did a reboot and now it works fine.

`➜  ~ fig doctor

✅ Everything looks good!

Fig still not working?
Run fig issue to let us know!
Or, email us at hello@fig.io!`

**Comment by hardcore** [comment]
Thank you for your message!
