### ISSUE TITLE
Unable to get fig in iTerm2

### ISSUE THREAD

**Issue by Auratelience** [withfig/fig#1020]
### Description:
Hello Fig team,
I find Fig a really good product and I have successfully (I hope) got it working in Terminal, I am unable to get it working in iTerm2. If I could have some help with the installation that would be great. Thanks, Auratelience.

#### `fig doctor` output
❌ Fig not in PATH
❌ Figterm socket does not exist at /tmp/figterm-14FCE25C-93D6-4526-BE70-93FB7CD3DD4B.socket
❌ Could not get iTerm version

❌ Doctor found errors. Please fix them and try again.

|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|-zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B383) [Beta] [Australian] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Utilities/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/zimmylevi/.dotnet/tools:/Users/zimmylevi/.nimble/bin:/usr/local/opt/fzf/bin:/Users/zimmylevi/.cargo/binexport:/usr/local/bin/python3:/Library/Frameworks/Python.framework/Versions/3.10/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/zimmylevi
Current window identifier: 45277/% (com.apple.Terminal)
Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Utilities/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/zimmylevi/.dotnet/tools:/Users/zimmylevi/.nimble/bin:/usr/local/opt/fzf/bin:/Users/zimmylevi/.cargo/binexport:/usr/local/bin/python3:/Library/Frameworks/Python.framework/Versions/3.10/bin
Fig environment variables:
  - TERM_SESSION_ID=14FCE25C-93D6-4526-BE70-93FB7CD3DD4B
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Weird, not sure what could be happening to make it fail in iTerm but not Terminal. Does updating to beta fix this? `fig settings app.beta true`

**Comment by mschrage** [comment]
Hey @Auratelience, sorry to hear that Fig isn't working in iTerm for you!

Can you also run `defaults read com.googlecode.iterm2`?

**Comment by brendanfalk** [comment]
@Auratelience Sorry about the issues. Hopefully this will be fixed in our newest build (being pushed next week). If it still doesn't, we will have better debug logging and can re-assess then. Thanks!

**Comment by Auratelience** [comment]
Am using zsh-autocomplete now
