### ISSUE TITLE
Breaks Jest Runner in VS Code

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1022]
> It doesn’t work with Jest Runner in VS Code on Windows 11. When you run Jest test by clicking on ’Test’ button, Fig tries to autofill and breaks path.

Could be related to #446

**Comment by mschrage** [comment]
https://user-images.githubusercontent.com/3155109/157563204-364dd88c-e12b-4c43-a2df-065d36b64390.mov


https://user-images.githubusercontent.com/3155109/157563219-311f0705-7ac9-4b01-a45d-362b121f4223.mov
