### ISSUE TITLE
❌ PATH and PseudoTerminal PATH do not match

### ISSUE THREAD

**Issue by fergusmeiklejohn** [withfig/fig#1023]
### Description:
fig doctor failed on ❌ PATH and PseudoTerminal PATH do not match

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1.21D62|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B322) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: AutoLaunch script does not exist at /Users/fergusmeiklejohn/Library/Application Support/iTerm2/Scripts/AutoLaunch/fig-iterm-integration.scpt.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/fergusmeiklejohn/.fig/bin:/Users/fergusmeiklejohn/dev/flutter/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (43932) - /dev/ttys001
Current working directory: /Users/fergusmeiklejohn/dev/evesa-proj/evesa
Current window identifier: 4558/code:43923% (com.microsoft.VSCode)
Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/fergusmeiklejohn/.fig/bin:/Users/fergusmeiklejohn/dev/flutter/bin:/Users/fergusmeiklejohn/dev/flutter/bin</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @fergusmeiklejohn, besides this warning does Fig work?

**Comment by fergusmeiklejohn** [comment]
yes it works again now. I uninstalled iTerm and Fig stopped working in other terminals. I ran fig doctor, it failed on that last stage and prompted me to report it. But Fig does now work :-)

**Comment by brendanfalk** [comment]
Glad it's working! Going to close the issue. Thanks for reporting @fergusmeiklejohn
