### ISSUE TITLE
Installation Error: Fig Socket

### ISSUE THREAD

**Issue by alessandroDeIturbe** [withfig/fig#1025]
### Description:
> Installing Fig via brew, it doesn't work
> I've tried all the Fig program tells to do for resolve, but nothing, always say `Fig socket does not exist at /var/folders/p7/qnnf5mpj05v7_0nyqt4qz59w0000gn/T/fig.socket`

<img width="1550" alt="Schermata 2022-03-04 alle 08 44 10" src="https://user-images.githubusercontent.com/63016931/156720888-d6134806-0859-417c-ae21-4c0b7a71f3dc.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/usr/local/Cellar/fish/3.3.1/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>
It looks like Fig is not running.
Try running: fig restart

</pre>
</p>
</details>

**Comment by brendanfalk** [comment]
Did you try running `fig restart`? That should likely fix it!
