### ISSUE TITLE
Autocomplete doesn't work

### ISSUE THREAD

**Issue by DiogoM14** [withfig/fig#1027]
### Description:

I had some "Secure Keyboard Entry" problems (even after disable it). After that I restarted my mac and now I don't have that problem anymore. However my autocomplete doesn't work at all.

As you guys can see in print when I ran `fig doc` everything seems to be good. It's not the first time I have this issue.

<img width="579" alt="Screenshot 2022-03-05 at 8 18 33 PM" src="https://user-images.githubusercontent.com/53921606/156898740-d08486e1-3f73-4beb-854f-f7e80d442cfb.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B383) [Portuguese] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/diogomartins/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/diogomartins/.local/share/zinit/polaris/bin:/Users/diogomartins/.nvm/versions/node/v16.14.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/diogomartins/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (1071) - /dev/ttys002
Current working directory: /Users/diogomartins
Current window identifier: 36/% (com.apple.Terminal)
Path: /Users/diogomartins/.local/share/zinit/polaris/bin:/Users/diogomartins/.nvm/versions/node/v16.14.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/diogomartins/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=126080EC-7831-4569-A8F1-4FF75D9352A6
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM=1
  - FIG_TERM_VERSION=4.0.10
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
thanks for reporting this @DiogoM14! Can you take a screen recording while running `fig debug logs` in one terminal and then typing “git commit” into a separate terminal?
