### ISSUE TITLE
Terminal or shell crashing

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1035]
Please comment info if your terminal / shell is crashing - we'd like to know:
* Your shell
* Your dotfiles (eg. bashrc, zshrc)
* Any other relevant info 🙂

**Comment by SeparateRecords** [comment]
> I was trying to load iterm. When I opened a new terminal it would crash as soon as I typed any letter.

**Comment by grant0417** [comment]
No more placeholders!
