### ISSUE TITLE
Kitty terminal at 0.24, Fig refuses to work with it

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1039]
> kitty terminal was updated to 0.24.4 and fig was not installing the integration because "0.23.X" was not supported.

If you're also having this issue, please comment your:
* Fig version (`fig --version`)
* `fig diagnostic`
* Kitty version

**Comment by mschrage** [comment]
There was an issue with the semvar check logic. This should be resolved in the latest version.

**Comment by SeparateRecords** [comment]
Fantastic. Will close this issue then
