### ISSUE TITLE
Daemon socket does not exist

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1040]
If anyone is running into this issue, please let us know your fig version and any other information you think is relevant!

Fig version can be found in the ◧ Fig menu:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/52195359/157123446-177e25d6-82aa-4889-b0ae-ec0a69b2781d.png">

**Comment by jsheffers** [comment]
I'm having this issue when running `fig doctor`.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/656483/159072378-aa2bc0ac-cb56-4ede-a0b6-15436666cef1.png">

**Comment by jsheffers** [comment]
Restarting fig fixed this issue.
