### ISSUE TITLE
Change default tab keybinding

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1042]
_Couldn't find the issue that I'm certain we had about the tab keybinding._

Currently, tab behaves as "insert common prefix" which is the same behavior as bash. Related: #897 

The tab keybind can be changed by going to the "keybindings" tab in `fig settings`.

We're all in favor of changing the default here. Please let us know what you'd prefer to use as the default.

VSCode: change to "Insert selected"
ZSH / Fish / Vim: change to "Insert common prefix or navigate"

**Comment by grant0417** [comment]
We have better onboarding for this now!
