### ISSUE TITLE
Multiword aliases are not recognized

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#105]
### Description:
> Fig doesn't seem to be picking up on multi word aliases well. I have aliased `git st` to `git status`, but Fig doesn't recognize it, which is very annoying.

**Comment by dfreilich** [comment]
I am on a Mac (Intel), using `zsh` on `iTerm2`

**Comment by brendanfalk** [comment]
@dfreilich Just to clarify - are you using git aliases or normal aliases? Either way, would you be able to comment the bash script you wrote to create the aliases below? 

Thanks for your help

**Comment by dfreilich** [comment]
I'm using git aliases, in `~/.gitconfig`
```
[alias]
st = status
ci = commit --signoff
...
```

**Comment by mschrage** [comment]
@dmarkow based on your description, it sounds like you were running into a known issue where Fig's pseudoterminal would intermittently hang. 

Updating to the latest version by running `fig update` should fix this, but definitely let me know if you're still running into issues.

**Comment by dmarkow** [comment]
@mschrage Still very much an issue with the latest Fig (1.0.52 B310). Alias was working fine all morning and stopped working out of nowhere. Restarting fig fixed it.

**Comment by mschrage** [comment]
@dmarkow just seeing your response now! We spent a ton of time improving the stability of the pseudo-terminal. It should be much more robust now, however if you're still experiencing this then we should jump on a call and debug together!

**Comment by parssak** [comment]
This is now fixed!
