### ISSUE TITLE
getting the following error on running fig doctor

### ISSUE THREAD

**Issue by sampath-paravasthu** [withfig/fig#1051]
### Error : 

```
❌ Insertion lock does not exist: Insertion lock exists
Attempting to fix automatically...
Re-running check...

✅ Insertion lock does not exist
❌ Fig CLI path: Fig CLI must be in /Users/saparavasthu/.fig/bin/fig


❌ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

```

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.6.0 (20G165)|1.0.55|zsh|
<details><summary>Fig Diagnostic</summary>
<p>

# Fig Diagnostics

## Fig details:

  - Fig version: Version 1.0.55 (B396) [Beta] [ABC - India]

  - Bundle path: /Applications/Fig.app

  - Autocomplete: true

  - Settings.json: true

  - Accessibility: true

  - Number of specs: 200

  - Symlinked dotfiles: false

  - Only insert on tab: false

  - Keybindings path: 

  - Installation Script: true

  - PseudoTerminal Path: /Users/saparavasthu/.nvm/versions/node/v10.24.0/bin:/Users/saparavasthu/.rvm/gems/ruby-2.3.7/bin:/Users/saparavasthu/.rvm/gems/ruby-2.3.7@global/bin:/Users/saparavasthu/.rvm/rubies/ruby-2.3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/saparavasthu/.rvm/gems/ruby-2.3.7/bin:/Users/saparavasthu/.rvm/gems/ruby-2.3.7@global/bin:/Users/saparavasthu/.rvm/rubies/ruby-2.3.7/bin:/Users/saparavasthu/.local/bin:/Users/saparavasthu/.fig/bin:/Users/saparavasthu/.rvm/bin:/Users/saparavasthu/.local/bin:/Users/saparavasthu/.local/bin:/Users/saparavasthu/.local/bin:/Users/saparavasthu/.local/bin

  - SecureKeyboardInput: false

  - SecureKeyboardProcess: <none>

## Hardware Info:

  - Model Name: MacBook Pro

  - Model Identifier: MacBookPro16,1

  - Chip: 

  - Cores: 6

  - Memory: 16 GB

## OS Info:

  - macOS 11.6.0 (20G165)

## Environment:

  - User Shell: /bin/zsh

  - Current Directory: /Users/saparavasthu/dev/freshsales/frontend/app

  - CLI Installed: true

  - Executable Location: /usr/local/bin/fig

  - Current Window ID: 220/% (com.microsoft.VSCode)

  - Active Process: zsh (67019) - /dev/ttys021

  - Environment Variables:

    - PATH=/Users/saparavasthu/.nvm/versions/node/v10.24.0/bin:/Users/saparavasthu/.rvm/gems/ruby-2.3.7/bin:/Users/saparavasthu/.rvm/gems/ruby-2.3.7@global/bin:/Users/saparavasthu/.rvm/rubies/ruby-2.3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/saparavasthu/.rvm/gems/ruby-2.3.7/bin:/Users/saparavasthu/.rvm/gems/ruby-2.3.7@global/bin:/Users/saparavasthu/.rvm/rubies/ruby-2.3.7/bin:/Users/saparavasthu/.local/bin:/Users/saparavasthu/.fig/bin:/Users/saparavasthu/.rvm/bin:/Users/saparavasthu/.local/bin:/Users/saparavasthu/.local/bin:/Users/saparavasthu/.local/bin:/Users/saparavasthu/.local/bin

    - TERM=xterm-256color

    - TERM_SESSION_ID=742D8BD1-DF6E-4B64-982B-5BEA024E25BB

    - FIG_INTEGRATION_VERSION=7

    - FIG_TERM=1

    - FIG_TERM_VERSION=4.1.2

    - FIG_CHECKED_PROMPTS=1

## Integrations:

  - SSH: false

  - TMUX: false

  - iTerm: installed!

  - Hyper: application is not present.

  - Visual Studio Code: installed!

  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
@sampath-paravasthu this seems like an issue on beta. We will investigate and fix before pushing live.

**Comment by SeparateRecords** [comment]
Hey @sampath-paravasthu! Is this issue fixed for you? Should be working now - you might need to reinstall.

Let us know how you go!

**Comment by SeparateRecords** [comment]
Didn't mean to close it 😅
