### ISSUE TITLE
Fig Problem - Daemon is running: Daemon is not running

### ISSUE THREAD

**Issue by timscodebase** [withfig/fig#1052]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

✅ Fig bin exists
✅ Fig in PATH
✅ Fig is running
✅ Fig socket exists
❌ Daemon is running: Daemon is not running
  Init system: Launchd
Attempting to fix automatically...
Failed to fix...

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E5227a)|1.0.55|/bin/zsh|
<details><summary>Fig Diagnostic</summary>
<p>

# Fig Diagnostics

## Fig details:

  - Fig version: Version 1.0.55 (B388) [Beta] [U.S.]

  - Bundle path: /Applications/Fig.app

  - Autocomplete: true

  - Settings.json: true

  - Accessibility: true

  - Number of specs: 0

  - Symlinked dotfiles: false

  - Only insert on tab: false

  - Keybindings path: 

  - Installation Script: false

  - PseudoTerminal Path: /Users/timsmit/Library/pnpm:/Users/timsmit/.local/bin:/Users/timsmit/.nvm/versions/node/v14.18.1/bin:/Users/timsmit/.deno/bin:/Users/timsmit/Library/Python/3.8/bin:/usr/local/bin:/usr/bin:/sbin:/bin:/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/timsmit/.cargo/bin:/Users/timsmit/.fig/bin

  - SecureKeyboardInput: false

  - SecureKeyboardProcess: <none>

## Hardware Info:

  - Model Name: MacBook Pro

  - Model Identifier: MacBookPro16,1

  - Chip: 

  - Cores: 8

  - Memory: 16 GB

## OS Info:

  - macOS 12.3.0 (21E5227a)

## Environment:

  - User Shell: /bin/zsh

  - Current Directory: /Users/timsmit

  - CLI Installed: true

  - Executable Location: /Users/timsmit/.local/bin/fig

  - Current Window ID: 11077/% (com.googlecode.iterm2)

  - Active Process: zsh (49570) - /dev/ttys002

  - Environment Variables:

    - TERM_SESSION_ID=w0t0p0:9C4CE01E-2B76-4A30-8A6F-393083F71FFD

    - PATH=/Users/timsmit/Library/pnpm:/Users/timsmit/.local/bin:/Users/timsmit/.nvm/versions/node/v14.18.1/bin:/Users/timsmit/.deno/bin:/Users/timsmit/Library/Python/3.8/bin:/usr/local/bin:/usr/bin:/sbin:/bin:/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/timsmit/.cargo/bin:/Users/timsmit/.fig/bin

    - TERM=xterm-256color

    - FIG_INTEGRATION_VERSION=6

    - FIG_TERM=1

    - FIG_TERM_VERSION=4.1.2

    - FIG_ENV_VAR=1

    - FIG_CHECKED_PROMPTS=1

## Integrations:

  - SSH: false

  - TMUX: false

  - iTerm: installed!

  - Hyper: installed!

  - Visual Studio Code: application is not present.

  - Docker: true

</p>
</details>

**Comment by grant0417** [comment]
This should be fixed on the stable build of Fig.

Run `fig update` or go into the Fig menu an click `Check for Updates...`

Also make sure to run `fig doctor` after you update to ensure Fig is working correctly.
