### ISSUE TITLE
敲空格不出列表。有时候软件直接就退出去了

### ISSUE THREAD

**Issue by magicer0126** [withfig/fig#1054]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B383) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/mahuiying/depot_tools:/opt/MonkeyDev/bin:/usr/local/bin/node:/usr/local/bin/npm:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/mahuiying/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/mahuiying
Current window identifier: ???
Path: /Users/mahuiying/depot_tools:/opt/MonkeyDev/bin:/usr/local/bin/node:/usr/local/bin/npm:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/mahuiying/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:5580DC5B-63A1-4F9E-BD3D-DEC6DD87C9E9
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM=1
  - FIG_TERM_VERSION=4.0.10
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @magicer0126, this should be fixed on Fig Version 1.0.56.
