### ISSUE TITLE
File / folder suggestions should be ordered differently

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1056]
> Tab completes for folders should be ordered differently. 9/10 times tab complete should allow selecting a folder instead of the root folder

**Comment by WardsParadox** [comment]
I'm not sure if the title is accurate. I'd think it should be configurable.

Currently Fig just lists the folder expected. If I hit tab to list the folders, it just goes red. I have to wait, then move my hand to the arrow keys to select. If I start typing, it doesn't detect folders where as zsh's auto complete does.

**Comment by SeparateRecords** [comment]
@WardsParadox This sounds more like a bug actually, not entirely sure what's happening for you.

You can move up/down the suggestions with <kbd>control</kbd>+<kbd>j/k</kbd>, and insert with <kbd>return</kbd>. There's also a fuzzy search option, and you can choose to order alphabetically or by recency.

I bind my <kbd>tab</kbd> to "Insert selected", which makes it behave like an IDE. The default is to behave like bash (see #1042)

Here's a quick video demoing the correct behavior - is yours different?

https://user-images.githubusercontent.com/52195359/157789351-d58bda92-d309-407b-864f-880f85240dd8.mov

**Comment by SeparateRecords** [comment]
@WardsParadox following up on this - is this the behavior you're seeing? Could you give some more info on what you'd like to have happen?
