### ISSUE TITLE
asciinema doesn't record fig output

### ISSUE THREAD

**Issue by cfsmp3** [withfig/fig#1063]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
When recording a session with asciinema, fig doesn't appear in the recording.

Of course this could be something from asciinema to fix. 

![image](https://user-images.githubusercontent.com/5949913/157514405-5bc5e9bc-541c-437e-b0b9-11c2ec5dbe02.png)

### Environment

```bash
❯ fig diagnostic
Fig Version: Version 1.0.55 (B383) [Spanish - ISO]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path:
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/cf668x/google-cloud-sdk/bin:/Users/cf668x/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/cf668x/.cargo/bin:/Users/cf668x/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (6988) - /dev/ttys002
Current working directory: /Users/cf668x
Current window identifier: 779/% (io.alacritty)
Path: /Users/cf668x/google-cloud-sdk/bin:/Users/cf668x/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/cf668x/.cargo/bin:/Users/cf668x/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=8F581A42-C5A7-4FD1-8661-F88FF72C5BFF
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM=1
  - FIG_TERM_VERSION=4.0.10
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 11.6.4 20G417
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip:
  - Cores: 6
  - Memory: 16 GB
```
Using alacritty
```

**Comment by mschrage** [comment]
Hey @cfsmp3, thanks for raising this issue!
 
`asciinema` records everything that appears 'inside' of your terminal emulator. It captures the raw ANSI characters that are written of stdin and stdout and then plays them back later.
 
While Fig _feels_ like a native part of your terminal, in reality, it is a separate application. The autocomplete UI is rendered in an entirely different window.
 
I'm going to close this issue for now as out of scope, but I'd love to understand more about your use-case? Are you trying to write up a tutorial using Fig?

**Comment by cfsmp3** [comment]
> I'm going to close this issue for now as out of scope, but I'd love to understand more about your use-case? Are you trying to write up a tutorial using Fig?

Just wanted to prepare a short demo to pitch Fig to my team :-) No big deal.

**Comment by mschrage** [comment]
Ah thank you so much! 🤩 I would just use a normal screen recording for that!
