### ISSUE TITLE
Git unusable command autocomplete appears.

### ISSUE THREAD

**Issue by seonggwonyoon** [withfig/fig#107]
### Description:
First, save projects on icloud.
If there is a problem during synchronization, the git ref is broken.

![image](https://user-images.githubusercontent.com/37574822/120421867-12a73b80-c3a2-11eb-8681-9786adc1b58c.png)

At this time, if you enter the `git branch` command, it will appear as in the image above.
 
![image](https://user-images.githubusercontent.com/37574822/120422209-bd1f5e80-c3a2-11eb-96b0-1262434ff267.png)
![image](https://user-images.githubusercontent.com/37574822/120422222-c7415d00-c3a2-11eb-9b4b-109b60dcb2a0.png)

At this time, autocomplete appears when you type `git branch`
Commands that cannot be used are recommended even by `warning`.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.42 (B207)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.42 (B207) 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/seonggwonyoon/.fig/bin/fig
Accessibility: true
Number of specs: 107
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/seonggwonyoon/.fig/user/keybindings
iTerm Integration: false
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mattschrage** [comment]
Hey @seonggwonyoon, thanks for reporting this. Can you clarify what the expected behavior would be in this case?

**Comment by seonggwonyoon** [comment]
I think it should ignore unusable command.
Just showing branch list not `warning` or `error`.

**Comment by mattschrage** [comment]
This is an issue with the `git.ts` completion spec in the [withfig/autocomplete](https://github.com/withfig/autocomplete) repo. The generator that provides the branch suggestions should filter out anything starting with `error` or `warning`.

This is a pretty easy tweak! Would you be interested in contributing?

**Comment by seonggwonyoon** [comment]
@mattschrage Thank you for telling me!
I'm interested in contributing and I'll fix it.

**Comment by seonggwonyoon** [comment]
I made a pull request.
You can check it out here.
https://github.com/withfig/autocomplete/pull/252

**Comment by mattschrage** [comment]
Thanks so much for contributing!
