### ISSUE TITLE
Conflict when "broadcasting input" using iTerm

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#1073]
<blockquote>
Fig does not work well with broadcast input when using iTerm

![image](https://user-images.githubusercontent.com/3155109/157574423-57deb105-4def-4cae-be02-6cdffed6d1fe.png)

The workflow is I will open 3 ~ 4 terminals and go to the same folder. Each one will do different job but I need to look and compare all of them.

When use Fig to move around; command like cd will only put folder in a single terminal. 

![image](https://user-images.githubusercontent.com/3155109/157574461-29733bd3-0e22-44bb-8c08-c0f31f2e012e.png)

</blockquote>

**Comment by brendanfalk** [comment]
Realistically this is a low priority but please comment if you face this issue
