### ISSUE TITLE
Three errors after updating to v1.0.56

### ISSUE THREAD

**Issue by GamaG27** [withfig/fig#1075]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

<img width="851" alt="Screenshot 2022-03-10 at 03 45 52" src="https://user-images.githubusercontent.com/56368966/157578278-90471bb7-22fb-4174-ac24-15008e6e3209.png">

error: Found argument 'completion' which wasn't expected, or isn't valid in this context

USAGE:
    fig [SUBCOMMAND]

For more information try --help

❯ fig doctor

✘ Figterm socket: Figterm socket did not read buffer correctly: "\\Testing figterm...\n"

✘ Doctor found errors. Please fix them and try again

tried using settings the this appears 

<img width="942" alt="Screenshot 2022-03-10 at 03 48 42" src="https://user-images.githubusercontent.com/56368966/157578663-67a6427b-de1f-40ea-afc8-a8d3c7012333.png">

what do i do ?

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.56 (B401)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B401) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: false
Settings.json: true
CLI installed: true
CLI tool path: /Users/occ/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by oorzc** [comment]
Mac 10.14.6 cannot be used

**Comment by GamaG27** [comment]
ok.. ? there seams to be a misunderstanding i am using macOS 12.2.1 .

**Comment by mschrage** [comment]
@GamaG27 thanks for reporting this! 


> `error: Found argument 'completion' which wasn't expected, or isn't valid in this context`

We've removed this subcommand from the `fig` CLI. Search your zshrc/zprofile for occurrences of `fig completion` and remove it.

> `✘ Figterm socket: Figterm socket did not read buffer correctly: "\Testing figterm...\n"`

Try opening a new terminal session and running `fig doctor`. Let me know if you still see the same warning and we can get @grant0417 involved.


> "Something went wrong :("

This was related to an issue on our backend. It has since been resolved. You should be able to edit settings as usual.

**Comment by GamaG27** [comment]
I followed everything you said and it was fixed ! Thank you very much!
