### ISSUE TITLE
Command not found after upgrade

### ISSUE THREAD

**Issue by liby** [withfig/fig#1076]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

<details>
<summary>Log</summary>

```
Last login: Wed Mar  9 09:28:21 on ttys001
Updating Fig to latest version...

~
❯

~
❯ /Users/user/.fig/tools/drip/prompt_to_update.sh: line 12: fig: command not found


~
❯

~
❯ fig doctor
zsh: command not found: fig

~
❯

~
❯ fig doctor

✘ Daemon is running: Daemon is not running
  Daemon status: 1
  Init system: Launchd
Attempting to fix automatically...
Re-running check...

✘ Daemon is running: Daemon socket does not exist


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```
</details>

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.2.1 (20D75)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B401) [Dev] [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: <generated dynamically>
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: iMac
  - Model Identifier: iMac20,1
  - Chip: 
  - Cores: 6
  - Memory: 32 GB
## OS Info:
  - macOS 11.2.1 (20D75)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/user/Code/Company/web
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 121745/% (com.googlecode.iterm2)
  - Active Process: zsh (27578) - /dev/ttys002
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:0E031731-45E1-4F63-9642-B328AA254636
    - PATH=/Users/user/.autojump/bin:/Users/user/n/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Users/user/.cargo/bin:/Users/user/.fig/bin:./node_modules/.bin:/Users/user/n/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=6
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.0.10
    - FIG_ENV_VAR=1
    - FIG_CHECKED_PROMPTS=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by oorzc** [comment]
Mac 10.14.6 cannot be used

**Comment by mschrage** [comment]
Hey @liby! Thanks for reporting this.

Make sure Fig is running and then restart your terminal. This should resolve the issue!

Let me know if you're still seeing error messages appear in your terminal after that.

**Comment by liby** [comment]
@mschrage 
Manually run fig, reopen a new window and it does work fine. But I had the same issue on another device, again after fig update.
<img width="663" alt="image" src="https://user-images.githubusercontent.com/38807139/157679245-a23df4fb-58ef-4c87-a957-65678d5d6c50.png">
