### ISSUE TITLE
command not found: __bp_install_after_session_init

### ISSUE THREAD

**Issue by Coder-ZJQ** [withfig/fig#1078]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

after upgrade to 1.0.56:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/15013685/157595186-373d2d80-6ea7-48c4-b426-09dd7c018642.png">

I've tried:
- [x] restart fig
- [x] reopen iTerm
- [x] reinstall fig  

but not fix :(

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B401) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: <generated dynamically>
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 32 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/Joker
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 88823/% (com.googlecode.iterm2)
  - Active Process: zsh (51166) - not a tty
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:466B3380-D506-4832-A57B-6AD891606834
    - PATH=/usr/local/opt/make/libexec/gnubin:/Users/Joker/.theos/bin:/opt/MonkeyDev/bin:/usr/local/sbin:/opt/local/sbin:/opt/local/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/usr/local/aria2/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/Joker/.local/bin:/Users/Joker/.fig/bin:/Users/Joker/.local/bin:/Users/Joker/.local/bin:/Users/Joker/.local/bin:/Users/Joker/Library/Android/sdk/tools:/Users/Joker/Library/Android/sdk/platform-tools:/Users/Joker/.rvm/bin:/Users/Joker/.flutter/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.2.0
    - FIG_CHECKED_PROMPTS=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by 1991wangliang** [comment]
yes i had this error.
```
Last login: Thu Mar 10 13:51:26 on ttys000
(eval):545: command not found: __bp_install_after_session_init
__fig_reset_hooks:16: command not found: __bp_sanitize_string
__fig_reset_hooks:26: bad substitution
lorne@mac ~ % 
```

**Comment by 1991wangliang** [comment]
i fix the error. i modify `~/.bashrc` and `~/.bash_profile`. 
```
# Fig post block. Keep at the bottom of this file.
# eval "$(fig init bash post)"
```
change to 
```
# Fig post block. Keep at the bottom of this file.
# eval $(fig init bash post)
```

remove "" flag.

**Comment by Coder-ZJQ** [comment]
> i fix the error. i modify `~/.bashrc` and `~/.bash_profile`.
> 
> ```
> # Fig post block. Keep at the bottom of this file.
> # eval "$(fig init bash post)"
> ```
> 
> change to
> 
> ```
> # Fig post block. Keep at the bottom of this file.
> # eval $(fig init bash post)
> ```
> 
> remove "" flag.

@1991wangliang You can execute `fig init bash post` in command line, that will output some script code.
I think if you remove the quotes, those script code will not execute, so the error will not throws.
(I'm not familiar with shell. This is just my assumption.)

If you want to downgrade to 1.0.55 you can download from [this](https://versions.withfig.com/fig%20383.dmg).
Then disable auto update by `fig settings app.disableAutoupdates true`.

**Comment by 1991wangliang** [comment]
remove quotes that can execute .
test code :

vim ~/hello.sh

```
#bin/bash
echo "123" > ~/hello.txt
```

then execute :
```
lorne@mac ~ % vim hello.sh
lorne@mac ~ % eval $(sh hello.sh)
lorne@mac ~ % ll | grep hello.txt
-rw-r--r--    1 wangliang  staff      4  3 10 16:54 hello.txt
```
of cause use  quotes still works.

```
lorne@mac ~ % rm -rf hello.txt
lorne@mac ~ % eval "$(sh hello.sh)"
lorne@mac ~ % ll | grep hello.txt  
-rw-r--r--    1 wangliang  staff      4  3 10 16:54 hello.txt
```

**Comment by mschrage** [comment]
We have a fix coming soon! The issue is due to sourcing your `~/.profile` from either `~/.zshrc` or `~/.zprofile`.
@Coder-ZJQ @1991wangliang 

A quick workaround is to edit `~/.profile` and comment out Fig's shell integration manually:
```bash
# Fig pre block. Keep at the top of this file.
export PATH="${PATH}:${HOME}/.local/bin"
# eval "$(fig init bash pre)"

...

# Fig post block. Keep at the bottom of this file.
# eval "$(fig init bash post)"
```
