### ISSUE TITLE
fig 1.0.56 issue: 'app:running' wasn't recognized, fig does not work | zsh

### ISSUE THREAD

**Issue by ShawnCockburn** [withfig/fig#1081]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

every time I login I get this error:

<img width="799" alt="Screenshot 2022-03-10 at 09 29 00" src="https://user-images.githubusercontent.com/60285801/157632786-6ecd8ca4-33ad-4889-aa57-1496dd61f087.png">

fig itself does not input auto complete and the fig cli won't take any commands:

<img width="1904" alt="Screenshot 2022-03-10 at 09 36 02" src="https://user-images.githubusercontent.com/60285801/157633965-bba0979d-043d-4d84-91e1-860ce2ce7ec9.png">

fig doctor doesn't detect any issues on the first account and doesn't work on the logged in account.

https://user-images.githubusercontent.com/60285801/157634612-4df52ce0-72b0-49a3-b2cc-4a168cf45e3a.mov

these don't fix this issue:
https://github.com/withfig/fig/issues/987
https://github.com/withfig/fig/issues/476#issuecomment-934680931

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.56 (B401)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B401) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Work/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: true
iTerm Integration: false 
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hey Shawn! I think this is a new bug popping up, probably unrelated to those.

`app:running` is a subcommand from a _really old_ version of Fig, the script that it's in isn't used anymore so I have no clue why it's being sourced...

Would you be able to send us your dotfiles? Either here or on discord (or as a DM!) 🙂

**Comment by ShawnCockburn** [comment]
@SeparateRecords let's jump on discord!

**Comment by ShawnCockburn** [comment]
thanks @SeparateRecords
