### ISSUE TITLE
Daemon socket does not exist.

### ISSUE THREAD

**Issue by thedanielfactor** [withfig/fig#1084]
### Description:
> Fig is not working, when I run `fig doctor` it is telling me 'Daemon socket does not exist'. I have included a link to a video of the issue.

video:  https://cln.sh/kOqLS1

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|-zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,2
  - Chip: 
  - Cores: 4
  - Memory: 32 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/raymonddoran/Development/l1/l1-recruitment-backend
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: <unknown>
  - Active Process: <unknown>
  - Environment Variables:
    - FIG_ENV_VAR=1
    - FIG_PTY=1
    - FIG_SHELL_VAR=1
    - FIG_SOCKET=/var/folders/q_/2sjc_1355yv1s2w7czdlvvjm0000gn/T
    - FIG_TERM=1
    - PATH=/Users/raymonddoran/.asdf/shims:/usr/local/opt/asdf/libexec/bin:/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.0.0/bin:/Users//.gem/ruby/3.1.0/bin:/usr/local/opt:/usr/local/opt/python/libexec/bin:/Users/raymonddoran/.sdkman/candidates/java/current/bin:/usr/local/opt/openssl@1.1/bin:/Users/raymonddoran/.serverless/bin:/Users/raymonddoran/.nvm/versions/node/v16.13.2/bin:/usr/local/opt/libpq/bin:/usr/local/bin/jdk8u212-b04/Contents/Home/bin:/usr/local/sbin:/Users/raymonddoran/go/bin:./bin:/usr/local/bin:/usr/local/sbin:/Users/raymonddoran/.oh-my-zsh/bin:/Users/raymonddoran/.rbenv/shims:/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:./bin:/usr/local/sbin:/Users/raymonddoran/.oh-my-zsh/bin:/Users/raymonddoran/.rbenv/shims:/go/bin:/Users/raymonddoran/.local/bin:/Users/raymonddoran/.fig/bin:/Users/raymonddoran/.local/bin:/Users/raymonddoran/.local/bin:/usr/local/bin:/Users/raymonddoran/bin:/Users/raymonddoran/Library/Python/2.7/bin:/Users/raymonddoran/Library/Python/3.9/bin:/usr/local/mongodb/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
    - TERM=screen-256color
    - FIG_CHECKED_PROMPTS=1
## Integrations:

</p>
</details>

**Comment by thedanielfactor** [comment]
I am not sure about the `Integrations` section being empty.  When I run it from the terminal in vs code I get the following.

## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

I ran the original using iterm and i do use tmux inside my iterm.

**Comment by mschrage** [comment]
Hey @thedanielfactor! It seems like fig's shell integrations are not set up correctly.

Can you run `fig doctor --verbose --no-early-exit` and share the output. Also would you mind sharing your `~/.zshrc`?

**Comment by thedanielfactor** [comment]
![CleanShot 2022-03-12 at 08 23 57](https://user-images.githubusercontent.com/448370/158021857-93f0ee91-f668-4aab-a1df-82afc8f7848b.png)

[zshrc.txt](https://github.com/withfig/fig/files/8237777/zshrc.txt)

**Comment by SeparateRecords** [comment]
Is this working in the latest version? Try running `fig update`, then restart your terminal and re-run `fig doctor` 🙂
