### ISSUE TITLE
Auto complete doesn’t  insert the selected option when "Tab" pressed

### ISSUE THREAD

**Issue by 88kiwan** [withfig/fig#1086]
Hello,
After updating from (1.0.55,383) to the current version pressing the "Tab" key doesn’t insert the selected option. I have tried to change the insert key to another key and restart Fig unfortunately that didn’t help. Removing the old configurations and letting Fig create new ones also didn’t solve the issue. when I press the "Tab" the options shaking 

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.56 (B401)|/bin/zsh|

**Update:**
Uninstalling the current version and reinstalling (1.0.55,383) via Homebrew works just fine. 

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B401) [Dutch] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/wael/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/me/.local/share/n/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/wael/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/me/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hey there @88kiwan! Sorry for this issue. Build 401 had a lot of problems. Does this work in the latest version? (B414)

**Comment by 88kiwan** [comment]
Hey @SeparateRecords! Yes (B414) works like a charm. Thank you.
