### ISSUE TITLE
console.log does not support variadic arguments

### ISSUE THREAD

**Issue by drukepple** [withfig/fig#1087]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
When writing something like `console.log('one', 'two')`in a spec, I only see `'one'` in the console.

Example code:

```ts
        generators: {
          script: context => {
            console.log('script', context);
            return 'ls'
          },
          postProcess: files => {
            console.log('postProcess', files);
            return [
              {
                name: 'boom',
              }
            ]
          },
        }
```

But I only see this in the debugger (note I'm filtering on "SPEC LOG" to see just logs I've made...):
<img width="187" alt="image" src="https://user-images.githubusercontent.com/323519/157737486-f6269ba3-23ad-4018-adb3-197db5148b3e.png">

I would expect to see something like...
<img width="366" alt="image" src="https://user-images.githubusercontent.com/323519/157738117-55d8d8af-949f-4588-bfea-948cbdaea162.png">

I see the same thing in the terminal output where I'm running `npm run dev`, as well: just the first argument.

I've also noticed that every `SPEC LOG` seems to be a `console.warn', and so I tried `console.error` just to see what would happen, and it came out as a `warn` as well.

I do see some fig logs that appear to be `string - object` much like I'm trying to do; it seems this is possible but not from a spec. 

As requested, here's the console after typing `git `
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/323519/157736584-40ce4cd5-f94c-4444-8e50-6cb7139dd488.png">

### Environment

```bash
Fig Version: Version 1.0.55 (B383) [Dev] [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/dru/.asdf/shims:/usr/local/Cellar/asdf/0.9.0/libexec/bin:/usr/local/mysql/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/dru/.fig/bin:/usr/local/sbin:/Users/dru/Library/Python/3.9/bin:/Users/dru/Library/Mobile Documents/com~apple~CloudDocs/bin:/Users/dru/code/fitted/microservice-monorepo/bin:/Users/dru/bin/google-cloud-sdk/bin:/usr/local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (27748) - /dev/ttys053
Current working directory: /Users/dru/Library/Mobile Documents/com~apple~CloudDocs/_MovieRip/_Rented/KingRichard
Current window identifier: 9095/% (com.apple.Terminal)
Path: /Users/dru/.asdf/shims:/usr/local/Cellar/asdf/0.9.0/libexec/bin:/usr/local/mysql/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/dru/.fig/bin:/usr/local/sbin:/Users/dru/Library/Python/3.9/bin:/Users/dru/Library/Mobile Documents/com~apple~CloudDocs/bin:/Users/dru/code/fitted/microservice-monorepo/bin:/Users/dru/bin/google-cloud-sdk/bin:/usr/local/bin
Fig environment variables:
  - TERM_SESSION_ID=D8D27F43-D183-47DB-8542-A56ECA2FD8ED
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM=1
  - FIG_TERM_VERSION=4.0.10
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB
```

**Comment by mschrage** [comment]
@drukepple we override `console.log` so that it will also output logs to the terminal that is running `npm run dev`. It seems like our wrapper doesn't match the behavior of the default `console.log`!

As a workaround for the time being,  you can probably use template strings:
```
console.log(`script ${context}`);
```

@fedeci can you take a look at this. (Not urgent)

**Comment by fedeci** [comment]
Fixed, it will be out in the next AE release!
