### ISSUE TITLE
Autocomplete `execute` action runs all but the last token

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1090]
```
cd|         -> cd
cd abc|     -> cd
cd abc |    -> cd abc
```

The default behaviour of enter is to execute the command anyway, so `ignore` works fine for this at least.

https://user-images.githubusercontent.com/52195359/157776330-2367aa46-a722-4b35-8b44-b2e8d5b7c069.mov

**Comment by SeparateRecords** [comment]
Context: #951

**Comment by brendanfalk** [comment]
This is seems like an autocomplete bug. @sullivan-sean will investigate

**Comment by fedeci** [comment]
PR to fix opened!

**Comment by SeparateRecords** [comment]
🙌 @fedeci thank you for implementing this!
