### ISSUE TITLE
iTerm integration script failed to launch Fig (no such file or directory)

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1091]
![image](https://user-images.githubusercontent.com/52195359/157779614-a70a5a76-14b3-4f50-a383-e992b59202b6.png)

**Comment by ednaaaj** [comment]
I have the same error

**Comment by SeparateRecords** [comment]
Think you might have to reinstall to fix this. @grant0417 is there another solution?

If you installed through homebrew:
1. Quit the Fig app and run `brew reinstall fig`
2. Open the Fig app (`/Applications/Fig.app`)
3. Go through installation process
