### ISSUE TITLE
Can't run fig in mac terminals

### ISSUE THREAD

**Issue by akkikumar72** [withfig/fig#1093]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B401) [Beta] [Dev] [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/akashpathak/.cabal/bin:/Users/akashpathak/.ghcup/bin:/Users/akashpathak/.nvm/versions/node/v16.6.1/bin:/Applications/flutter/bin:/Users/akashpathak/.local/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/akashpathak/.local/bin:/Users/akashpathak/.fig/bin:/Users/akashpathak/.local/bin:/Users/akashpathak/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/akashpathak
  - CLI Installed: true
  - Executable Location: /Users/akashpathak/.local/bin//fig
  - Current Window ID: 109/% (com.googlecode.iterm2)
  - Active Process: zsh (10307) - /dev/ttys011
  - Environment Variables:
    - TERM_SESSION_ID=w0t4p0:E67EDB24-DBAB-4E75-A151-17B82AC89DF5
    - PATH=/Users/akashpathak/.cabal/bin:/Users/akashpathak/.ghcup/bin:/Users/akashpathak/.nvm/versions/node/v16.6.1/bin:/Applications/flutter/bin:/Users/akashpathak/.local/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/akashpathak/.local/bin:/Users/akashpathak/.fig/bin:/Users/akashpathak/.local/bin:/Users/akashpathak/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.2.0
    - FIG_CHECKED_PROMPTS=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: true

</p>
</details>

**Comment by mschrage** [comment]
Hey @akkikumar72! I'm not totally sure what is going on based on your issue. Can you elaborate on what's not working?

If the `fig` executable is not found, please launch Fig and then open a new terminal session.

If that doesn't resolve the issue, can you perform some additional diagnostics for me?
- Run `fig doctor` and share the output here?
- Can you share a screen recording of the behavior?
- Can you type "cd " and then take a screenshot of the debugger menu (click the Fig icon in the menubar)

**Comment by akkikumar72** [comment]
Machine restart helped
