### ISSUE TITLE
Fig socket doesn't exist

### ISSUE THREAD

**Issue by rayyan** [withfig/fig#1094]
rayyan@Rayyans-iMac ~ % fig doctor
❌ Fig socket does not exist at /var/folders/b0/z4gjbm4n2g3_wztk6yfv7x1c0000gn/T/fig.socket
❌ Unable to get diagnostics
   Try restarting Fig by running: fig restart

If you are still running into this error:

Run fig issue to let us know about this error!
Or, email us at hello@fig.io!

rayyan@Rayyans-iMac ~ % fig issue

→ Opening GitHub...

rayyan@Rayyans-iMac ~ % 
rayyan@Rayyans-iMac ~ % 
rayyan@Rayyans-iMac ~ % fig issue

→ Opening GitHub...

rayyan@Rayyans-iMac ~ %

**Comment by mschrage** [comment]
Hey @rayyan! Thanks for reporting this.

Can you confirm that the Fig app is running? Try launching it directly from Finder rather than using the CLI.
