### ISSUE TITLE
Incompatibility with the terminal extension of PHPStorm

### ISSUE THREAD

**Issue by taophp** [withfig/fig#1095]
### Description:

Fig does not work well with the terminal tab of PhpStorm. First, Fig seems to not work at all (no autocomplete when typing), but the worst is that the terminal configuration made by PhpStorm is gone (local history is gone, only the global history is available) and even reloading .bash_profile does not help (the prompt is the default one, not mine).

Stop Fig and re open the PhpStorm windows is enough to solve the issue temporally. 

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.56 (B403)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B403) [French - PC] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/smo/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @taophp - thanks so much for reporting this!  Can you elaborate on what you mean by "terminal configuration made by PhpStorm"? Where in PhpStorm did you enable these settings?

**Comment by taophp** [comment]
Hi @²mschrage ,

Sorry, this is the default PhpStorm behavior, I'm not aware of any configuration linked to this - but, sure, there should be one somewhere.

There two things I have noted:

- first, my .bash_profile seems to be ignored in PhpStorm console tab ;
- second, PhpStorm manage a "local" history in each tab: each tab has its own history of command, which is really useful to use a tab for each context ; wtih Fig, the command of history is the global one...

As far as I know, Fig did not fire any error.

**Comment by mschrage** [comment]
@taophp this is resolved in the next release.

#1069
