### ISSUE TITLE
it keeps asking me to turn on accessibility even if its on , gone after restart the fig app

### ISSUE THREAD

**Issue by avsavani** [withfig/fig#1096]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.56 (B403)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B403) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ashish/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @avsavani! Can you share a screen recording of this behavior?

Based on the diagnostic output, you've shared it looks like Fig has already been granted accessibility permissions. If you are still seeing a warning, try restarting your mac.

**Comment by SeparateRecords** [comment]
Fixed! Just run `fig debug accessibility reset` or if you don't have fig installed run `tccutil reset Accessibility com.mschrage.fig`
