### ISSUE TITLE
fig autocomplete doesn't show up with aliased commands

### ISSUE THREAD

**Issue by a-rose** [withfig/fig#110]
I use a `cd` alias (to print pwd before changing to a new directory) and it prevents autocomplete from working for this specific command.

It worked after I did the following:

* closed Fig
* removed the alias
* restarted my terminal
* started Fig: autocomplete works (awesomely so !).

Explanation from mattschrage (on Discord):

> The alias list is cached every time Fig loads autocomplete. The issue here is the alias. If you get rid of it, cd should start working.
> The real fix is for us to add a setting that allows you to ignore certain aliases

**Comment by brendanfalk** [comment]
We expand the alias at runtime. 

If your alias is something like alias ls=`ls -l` and you type `ls[space]` we will provide completions as if you typed `ls -l[space]`

So if your alias was a function like `cd () { pwd; cd $1;}` we would try and provide autocomplete suggestions based on our parsing of that full function (which would confuse the hell out of Fig and yes we would abstain from making suggestions...)

We should probably add an alias override for functions... I will create an issue for this idea and will close this issue

**Comment by jonatan-ivanov** [comment]
@brendanfalk Could you please link the issue here that you created?

**Comment by RyKilleen** [comment]
Also unexpectedly ran into this today, was hoping aliases would auto-complete. Is there an open issue?

**Comment by uncenter** [comment]
Is that issue still open? I couldn't find any other issues related to this! It would be great to be able to toggle normal autocompletion for a command even if it is aliased!

**Comment by dserodio** [comment]
FWIW, I also have `cd` as a function, and Fig autocompletion works fine:
```
# Extended cd #0: if $1 is a file, change to dir containing file
# http://www.zshwiki.org/home/examples/functions
function cd () {
if [[ -z $2 ]]; then
  if [[ -f $1 ]]; then
    builtin cd $1:h
  else
    builtin cd $1
  fi
else
  if [[ -z $3 ]]; then
    builtin cd $1 $2
  else
    echo cd: too many arguments
  fi
fi
}
```
