### ISSUE TITLE
I cannot run fig

### ISSUE THREAD

**Issue by nitronaj** [withfig/fig#1104]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|-zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B403) [Australian]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: false
  - PseudoTerminal Path: /Users/<username>/.nvm/versions/node/v16.14.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 32 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/cnader
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 2759/% (com.googlecode.iterm2)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:86A495DC-E986-4340-8781-B11D97D95A0F
    - PATH=/Users/cnader/.nvm/versions/node/v16.14.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    - TERM=xterm-256color
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Can you run `fig doctor` and share the output here? It looks like Fig's shell integrations are not set up correctly.

**Comment by nitronaj** [comment]
what I get from running `fig doctor`
```
✘ Fig in PATH: Path does not contain ~/.fig/bin


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

I already added the path in zshrc
`[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh`

**Comment by nitronaj** [comment]
I install fig on another machine and everything went smoothly, but for this one, the install script is not running.

**Comment by nitronaj** [comment]
> Can you run `fig doctor` and share the output here? Based on the output from `fig diagnostic`, it looks like Fig's shell integrations are not set up correctly.

**Comment by SeparateRecords** [comment]
Where is saying the install script isn't running? And are the `eval "$(fig init <SHELL> <PRE|POST>)"` lines in your config? (fig doesn't use `source ~/.fig/fig.sh` anymore)

**Comment by nitronaj** [comment]
> `eval "$(fig init <SHELL> <PRE|POST>)"`

no it's not

**Comment by SeparateRecords** [comment]
That's strange... in your zshrc, add this line at the top:
```zsh
fig init zsh pre
```

And this line at the bottom:

```zsh
fig init zsh post
```

These lines _must_ be the first and last thing to execute in your config to get fig working.

**Comment by nitronaj** [comment]
I did,
run the `fig doctor`
```
fig doctor                                                                                                         ✔

● Pre shell integration not sourced first in /Users/cnader/.bashrc
● /Users/<username>/.profile does not exist. Run fig install --dotfiles to reinstall shell integrations for bash
● /Users/<username>/.zprofile does not exist. Run fig install --dotfiles to reinstall shell integrations for zsh
● /Users/<username>/.config/fish/conf.d/00_fig_pre.fish does not exist. Run fig install --dotfiles to reinstall shell integrations for fish
● /Users/<username>/.config/fish/conf.d/99_fig_post.fish does not exist. Run fig install --dotfiles to reinstall shell integrations for fish
✘ Installation script: Intall script not run
Attempting to fix automatically...
Re-running check...

✘ Installation script: Intall script not run


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

**Comment by mschrage** [comment]
It seems like you're on the beta. Is autocomplete working otherwise?

**Comment by nitronaj** [comment]
Yes, it's working

**Comment by nitronaj** [comment]
> It seems like you're on the beta. Is autocomplete working otherwise?

Yes, it's working
