### ISSUE TITLE
Unable to Configure Fig

### ISSUE THREAD

**Issue by samgaudet** [withfig/fig#1105]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

After downloading and installing Fig, I am unable to use it as I see the message: `~/.fig directory is misconfigured`. I received this message in my first time opening the application, and have tried the following ways to resolve it:

### Attempted Resolution:

1. Pressing `Re-run Install Script`, which I am prompted to do under the debugger, but which seemingly does nothing.
2. Restarting my Terminal, as well as restarting my computer.
3. Reinstalling the application, as well as installing `fig` via `brew install fig`.

I will additionally note that the [documentation here](https://fig.io/support/troubleshooting/debug-fig#fig-directory-misconfigured) recommends running:

```sh
~/.fig/tools/install_and_upgrade.sh
```

However, I noticed that this file is not present in my local `~/.fig` directory.

### Image:

<img width="455" alt="Screen Shot 2022-03-13 at 9 29 41 PM" src="https://user-images.githubusercontent.com/32820645/158089861-254f9d51-e076-4e1c-83d1-031ebc06ad3e.png">

### Details:

_I know this lists a beta version, however, I saw the same thing on the latest stable version as well before switching to the beta version._

|macOS|Fig|Shell|
|-|-|-|
|11.6.4|Version 1.0.56 (B403)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B403) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/sgaudet/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: false
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: 13655/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by ewauq** [comment]
I have exactly le the same issue, there is no `install_and_upgrade.sh` file located in `.fig/tools`:

```shell
~/.fig/tools/install_and_upgrade.sh
zsh: no such file or directory: /Users/.../.fig/tools/install_and_upgrade.sh
```

|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|-zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B403) [French]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: false
  - PseudoTerminal Path: /Users/emilien/opt/anaconda3/bin:/Users/emilien/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/emilien/.fig/bin:/Users/emilien/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/emilien
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 436/% (com.googlecode.iterm2)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p2:7FB82CE5-54E4-491A-8C09-C3FE279077E2
    - PATH=/Users/emilien/opt/anaconda3/bin:/Users/emilien/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/emilien/.fig/bin:/Users/emilien/.local/bin
    - TERM=xterm-256color
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by mschrage** [comment]
@samgaudet @ewauq this documentation is actually out of date. 

Can you both run the following commands:
-`ls ~/.fig`
-`fig doctor --verbose`

To attempt to reinstall, please run `fig install`

**Comment by samgaudet** [comment]
Hey Matt, thanks for looking into this. `ls ~/.fig` returns:

```
apps		bin		logs		settings.json	ssh		themes		tmux		tools		user
```

**Comment by samgaudet** [comment]
Hey Matt, thanks for looking into this. `ls ~/.fig` returns:

```
apps		bin		logs		settings.json	ssh		themes		tmux		tools		user
```

And for `fig doctor --verbose`, it seems that I need to add something to my path potentially?

```
zsh: command not found: fig
```

Is `fig` not automatically exported after installation?

**Comment by mschrage** [comment]
Hey @samgaudet! Are you free to get on a debugging call quickly? https://us06web.zoom.us/j/84904904358?pwd=TU5aamI5T3hpRGthMjNNOW5CbE9RZz09

**Comment by samgaudet** [comment]
Hey Matt, sorry&mdash;currently at work so can't hop on a call at the moment. That said, I added the path to `~/.fig/bin` to my `.zshrc` file and was able to run `fig doctor --verbose` with this output:

```
Let's make sure Fig is running...
✔ Fig bin exists
✘ Fig in PATH: Path does not contain ~/.local/bin


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

After adding that to my `$PATH` as well, I am now seeing this:

```
Let's make sure Fig is running...
✔ Fig bin exists
✔ Fig in PATH
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✘ Figterm socket: No file at path /tmp/figterm-F54F3917-E266-4D63-8DDC-BF8C2E6F2C2C.socket


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

**Comment by mschrage** [comment]
No worries! We can debug async as well.

Can you run `fig doctor --verbose --no-early-exit`? My suspicion is that your shell integrations are not set up correctly. 

Running `fig install` should resolve the issue, but before you run the command can you share your zshrc/bashrc so I can see what it looks like right now?

**Comment by samgaudet** [comment]
Sure thing, and thanks for the help!

```
% fig doctor --verbose --no-early-exit
Let's make sure Fig is running...
✔ Fig bin exists
✔ Fig in PATH
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✘ Figterm socket: No file at path /tmp/figterm-F54F3917-E266-4D63-8DDC-BF8C2E6F2C2C.socket
✔ Insertion lock does not exist
✔ PATH and PseudoTerminal PATH match

Let's check your dotfiles...
✔ /Users/sgaudet/.bashrc contains valid fig hooks
● Pre shell integration not sourced first in /Users/sgaudet/.bash_profile
✘ /Users/sgaudet/.zshrc contains valid fig hooks: Pre shell integration not sourced first in /Users/sgaudet/.zshrc
  In order for autocomplete to work correctly, Fig's shell integration must be sourced first.
  Top of /Users/sgaudet/.zshrc:
  1 export PATH="/usr/local/opt/openssl@3/bin:$PATH"
  2 export PATH="/Users/sgaudet/.fig/bin:$PATH"
  3 export PATH="/Users/sgaudet/.local/bin:$PATH"
  4 if [ -f '/Users/sgaudet/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/sgaudet/google-cloud-sdk/path.zsh.inc'; fi
  5 if [ -f '/Users/sgaudet/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/sgaudet/google-cloud-sdk/completion.zsh.inc'; fi
  6 zstyle ':completion:*:*:git:*' script ~/.git-completion.bash
  7 fpath=(~/.zsh/functions $fpath)
  8 autoload -Uz compinit && compinit
  9 autoload -U +X bashcompinit && bashcompinit
  10 complete -o nospace -C /usr/local/bin/vault vault
✘ /Users/sgaudet/.zprofile contains valid fig hooks: Pre shell integration not sourced first in /Users/sgaudet/.zprofile
  In order for autocomplete to work correctly, Fig's shell integration must be sourced first.
  Top of /Users/sgaudet/.zprofile:
● /Users/sgaudet/.config/fish/conf.d/00_fig_pre.fish does not exist. Run fig install --dotfiles to reinstall shell integrations for fish
● /Users/sgaudet/.config/fish/conf.d/99_fig_post.fish does not exist. Run fig install --dotfiles to reinstall shell integrations for fish

Let's check if your system is compatible...
✔ OS is supported

Let's check fig diagnostic...
✘ Installation script: Intall script not run
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled
✔ Secure keyboard input disabled

Let's check your terminal integrations...
✔ VSCode integration is enabled

Let's check if you're logged in...
✔ Logged into Fig


Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!
```

And here are the contents of my `zshrc` (with a few work things scrubbed for security):

```
export PATH="/usr/local/opt/openssl@3/bin:$PATH"
export PATH="/Users/sgaudet/.fig/bin:$PATH"
export PATH="/Users/sgaudet/.local/bin:$PATH"


# git autocomplete stuff
zstyle ':completion:*:*:git:*' script ~/.git-completion.bash
# `compinit` scans $fpath, so do this before calling it.
fpath=(~/.zsh/functions $fpath)
autoload -Uz compinit && compinit

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/vault vault

# nvm
source ~/.nvm/nvm.sh
```

**Comment by mschrage** [comment]
Yeah @samgaudet, it seems like for whatever reason Fig's shell integration has not been installed correctly.

Running `fig install --dotfiles` should fix this.

**Comment by samgaudet** [comment]
Thanks, Matt! Just ran the install command and it seems to all be working now! I wonder if it may have been a permissions issue because it seems that Fig does not have permissions to adjust my `.zshrc`. If anybody comes across this thread in the future, I was able to mitigate this issue by adding this to my `.zshrc`:

```sh
export PATH="/Users/sgaudet/.fig/bin:$PATH"
export PATH="/Users/sgaudet/.local/bin:$PATH"
```

Once I had added those, _then_ I was able to actually use `fig doctor` and whatnot to diagnose/install.

One other thing I'd mention is that even with Fig now working, I still don't see `install_and_upgrade.sh` in the `tools` directory.

**Comment by mschrage** [comment]
I think your diagnosis is spot on. Fig didn't have permissions to write to your dotfiles and couldn't complete the installation manually.

We may add a file permission check to `fig doctor` to catch issues.

**Comment by mschrage** [comment]
I'm going to close this issue but let me know if you're still running into issues @ewauq and I can reopen?

**Comment by ewauq** [comment]
I followed your instructions and it is working now, thank you!
