### ISSUE TITLE
Settings from Menubar icon  are not displayed : "Something went wrong :("

### ISSUE THREAD

**Issue by fabrom** [withfig/fig#1106]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Error message "Something went wrong :(" appears when selecting settingq-><any option>.

![Capture d’écran 2022-03-14 à 10 10 32](https://user-images.githubusercontent.com/5261331/158140499-0c54a091-96c0-405d-8f80-e8df62ee8c70.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.56 (B403)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B403) [French] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/fabrom/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Applications/ARX-3.9.0.app/Contents/bin:/Users/fabrom/.nvm/versions/node/v16.14.0/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/python/libexec/bin:/opt/subversion/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/git/bin:/Users/fabrom/.local/bin:/Users/fabrom/.fig/bin:/Users/fabrom/.local/bin:/Users/fabrom/go/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @fabrom! Can you right click the window and then press "Inspect elements"? Very curious to see if there are any error messages in the console right now?

Also can we report errors messages directly on this page @phuctm97?

**Comment by SeparateRecords** [comment]
The alternative to reporting error messages directly (for a nicer UX) would be having a "create issue on GitHub" button that pre-fills the error message

**Comment by mschrage** [comment]
Oh that's even better @SeparateRecords!

**Comment by fabrom** [comment]
Hi, screencopy of the console 
![Capture d’écran 2022-03-15 à 08 43 46](https://user-images.githubusercontent.com/5261331/158330072-6aa61727-9e43-4bd9-a8f8-255d53a58814.png)

**Comment by abraxxas** [comment]
I have the exact same error with the same error message in the console

**Comment by mschrage** [comment]
@abraxxas @fabrom how long have you been using Fig for? Did this happen right after installation?

**Comment by phuctm97** [comment]
This error in the old version of Fig, can you @abraxxas @fabrom right click -> inspect element -> go to Network tab and disable resource cache, then right click on Fig app -> reload

**Comment by abraxxas** [comment]
I have been using fig for roughly a month. In the beginning the settings worked but i havent checked them for quite a while so hard to tell when it stopped. 

I just tried what you suggested and i am still getting ` Failed to authenticate: could not find user`

**Comment by fabrom** [comment]
same error
![Capture d’écran 2022-03-16 à 08 39 28](https://user-images.githubusercontent.com/5261331/158540271-6880d2b0-7fff-479f-861d-c8ebcf463541.png)
![Capture d’écran 2022-03-16 à 08 39 55](https://user-images.githubusercontent.com/5261331/158540291-2cd90a58-f399-4539-9b6f-6d3cde766a53.png)

**Comment by mschrage** [comment]
Try running `fig login`? This should resolve the issue. If not, please let me know and we should schedule a 1:1 debugging call.

https://calendly.com/mschrage/30min

**Comment by abraxxas** [comment]
Hey matt, i tried both fig login and a complete reinstall nothing changed :/ Scheduled a call via calendly hope that works for you

**Comment by fabrom** [comment]
yesterday i did the same actions without any change but today settings works !
Have you done any fixes  about access to api.fig.io ?
