### ISSUE TITLE
No filepaths suggestions

### ISSUE THREAD

**Issue by paullongtan** [withfig/fig#1107]
### Description:
After trying to fix the issue through running fig settings pty.path "$PATH" and restarting autocomplete (even tried to restart terminal and fig), fig still doesn't recommend file path.
This is a bit bothering since I really do need this. 
I do sync my desktop with iCloud. Does that affect autocomplete?

<img width="664" alt="截圖 2022-03-14 下午8 29 40" src="https://user-images.githubusercontent.com/47477883/158172421-b02b133d-8342-4d49-8b41-7a54fae0f3a3.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.56 (B403)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B403) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/wangyanpu/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/wangyanpu/opt/anaconda3/bin:/Users/wangyanpu/opt/anaconda3/condabin:/Users/wangyanpu/.pyenv/shims:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/Users/wangyanpu/.local/bin:/Users/wangyanpu/.fig/bin:/Users/wangyanpu/.local/bin:/Users/wangyanpu/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (89860) - not a tty
Current terminal session: w2t0p0:E0F93EA5-7E88-4CAE-AD10-4E4A272E44DC
Current working directory: /Users/wangyanpu/Desktop/友達產學合作專案
Current window identifier: 17157/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by paullongtan** [comment]
Hi, thanks for the reply. But I do not use zplug.
I will provide my .vimrc do bellow for more information.

  1 # Fig pre block. Keep at the top of this file.
  2 export PATH="${PATH}:${HOME}/.local/bin"
  3 eval "$(fig init zsh pre)"
  4
  5
  6
 12 fi
 13 # If you come from bash you might have to change your $PATH.
 14 # export PATH=$HOME/bin:/usr/local/bin:$PATH
 15
 16 # Path to your oh-my-zsh installation.
 19 # Set name of the theme to load --- if set to "random", it will
 20 # load a random theme each time oh-my-zsh is loaded, in which case,
 21 # to know which specific one was loaded, run: echo $RANDOM_THEME
 22 # See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
 23 ZSH_THEME="powerlevel10k/powerlevel10k"
 24
 25 # Set list of themes to pick from when loading at random
 26 # Setting this variable when ZSH_THEME=random will cause zsh to load
 27 # a theme from this variable instead of looking in $ZSH/themes/
 28 # If set to an empty array, this variable will have no effect.
 29 # ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )
 30
 31 # Uncomment the following line to use case-sensitive completion.
 32 # CASE_SENSITIVE="true"
 33
 34 # Uncomment the following line to use hyphen-insensitive completion.
 39 # zstyle ':omz:update' mode disabled  # disable automatic updates
 42
 47 # DISABLE_MAGIC_FUNCTIONS="true"
 48
 49 # Uncomment the following line to disable colors in ls.
 52 # Uncomment the following line to disable auto-setting terminal title.
 53 # DISABLE_AUTO_TITLE="true"
 54
 55 # Uncomment the following line to enable command auto-correction.
 56 # ENABLE_CORRECTION="true"
 57
 60 # e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
 62 # COMPLETION_WAITING_DOTS="true"
 63
 66 # much, much faster.
 67 # DISABLE_UNTRACKED_FILES_DIRTY="true"
 68
 70 # stamp shown in the history command output.
 71 # You can set one of the optional three formats:
 72 # "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
 73 # or set a custom format using the strftime function format specifications,
 74 # see 'man strftime' for details.
 75 # HIST_STAMPS="mm/dd/yyyy"
 76
 77 # Would you like to use another custom folder than $ZSH/custom?
 78 # ZSH_CUSTOM=/path/to/new-custom-folder
 79
 80 # Which plugins would you like to load?
 81 # Standard plugins can be found in $ZSH/plugins/
 82 # Custom plugins may be added to $ZSH_CUSTOM/plugins/
 83 # Example format: plugins=(rails git textmate ruby lighthouse)
 84 # Add wisely, as too many plugins slow down shell startup.
 85 plugins=(git brew zsh-autosuggestions zsh-syntax-highlighting autojump)
 86
 88 source $ZSH/oh-my-zsh.sh
 89
 90 # User configuration
 91
 92 # export MANPATH="/usr/local/man:$MANPATH"
 93
 96
 97 # Preferred editor for local and remote sessions
 98 # if [[ -n $SSH_CONNECTION ]]; then
 99 #   export EDITOR='vim'
100 # else
101 #   export EDITOR='mvim'
102 # fi
103
104 # Compilation flags
105 # export ARCHFLAGS="-arch x86_64"
106
107 # Set personal aliases, overriding those provided by oh-my-zsh libs,
108 # plugins, and themes. Aliases can be placed here, though oh-my-zsh
109 # users are encouraged to define aliases within the ZSH_CUSTOM folder.
110 # For a full list of active aliases, run `alias`.
111 #
112 # Example aliases
113 # alias zshconfig="mate ~/.zshrc"
114 # alias ohmyzsh="mate ~/.oh-my-zsh"
115
116 # >>> conda initialize >>>
117 # !! Contents within this block are managed by 'conda init' !!
118 __conda_setup="$('/Users/wangyanpu/opt/anaconda3/bin/conda' 'shell.zsh' 'hoo    k' 2> /dev/null)"
119 if [ $? -eq 0 ]; then
120     eval "$__conda_setup"
121 else
122     if [ -f "/Users/wangyanpu/opt/anaconda3/etc/profile.d/conda.sh" ]; then
123         . "/Users/wangyanpu/opt/anaconda3/etc/profile.d/conda.sh"
124     else
125         export PATH="/Users/wangyanpu/opt/anaconda3/bin:$PATH"
126     fi
127 fi
128 unset __conda_setup
129 # <<< conda initialize <<<
130
131 # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
132 [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
133
134
135
136 eval "$(pyenv init -)"
137
138 # Fig post block. Keep at the bottom of this file.
139 eval "$(fig init zsh post)"

**Comment by mschrage** [comment]
Hey @paullongtan! Sorry for the slow response.

Can you run `mkdir -p ~/test-fig/{a,b,c}/{1,2,3}`

Do filepath suggestions work for these folders? (If so, this might be a unicode issue)

**Comment by paullongtan** [comment]
I tested the directories made and path suggestion do work in them.
I have further tested fig in other folders and for the ones that has (traditional) chinese character in the path, path suggestion generally doesn't work properly. I think it might be a unicode issues as you suggested.

Is there any thing I can do to fix this issue?

**Comment by mschrage** [comment]
Can you share some of the paths so I can try to reproduce?

Also make sure you have updated to the latest version.

**Comment by paullongtan** [comment]
The version I am using is 1.0.56 (the newest one).

Some path examples are:

cd /Users/wangyanpu/Desktop/台灣大學/
cd /Users/wangyanpu/Desktop/實習申請/
For these paths the autosuggestion generally load for a few second then give up.
<img width="660" alt="截圖 2022-03-27 下午2 58 35" src="https://user-images.githubusercontent.com/47477883/160270451-a52b460f-b78f-4cd7-8c32-76852452ae7c.png">

cd /Users/wangyanpu/Desktop/專案及活動/
For some others, they do load but suggests folders that are not under the current working directory.
<img width="664" alt="截圖 2022-03-27 下午3 02 16" src="https://user-images.githubusercontent.com/47477883/160270572-46fc1d47-cd0e-48fe-a409-163c7c636360.png">

Thanks for the help!
