### ISSUE TITLE
.fig/tools/prompts.sh: line 60: fig: command not found

### ISSUE THREAD

**Issue by Bakhtiyar-Garashov** [withfig/fig#1109]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
Hi there. Since the last week I am having `/Users/bakhtiyar/.fig/tools/prompts.sh: line 60: fig: command not found` in my MacBook pro (monterey v12.2.1
<img width="570" alt="Screenshot 2022-03-14 at 20 43 39" src="https://user-images.githubusercontent.com/48382094/158239775-e72c030f-8225-4620-a357-9a0fd4e01291.png">)

### Environment

```bash
fig: command not found
```

**Comment by felixgeissler** [comment]
> 

Unfortunatley this won't resolve the issue for me.

**Comment by Bakhtiyar-Garashov** [comment]
Hey @mschrage  thanks for swift response. Launching the Fig manually did the trick for me.

**Comment by SeparateRecords** [comment]
@felixgeissler is this fixed by updating to the latest version? (B414)

**Comment by felixgeissler** [comment]
> 

Yes. I reinstalled the whole application (B414) which resolved the issue for me. 🙂
Thanks!
