### ISSUE TITLE
Fig window should be titled "Fig" not "fig"

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1111]
In all the official copy, the title of the app is "Fig", not "fig". The lower case looks more like a bug than an intentional choice

<img width="373" alt="image" src="https://user-images.githubusercontent.com/52195359/158302468-755fce2e-e6c6-4e72-b22d-083e94cf706f.png">

**Comment by chaynabors** [comment]
The rust app now does this. Should be fixed by default when we convert.
