### ISSUE TITLE
Startup error "Found argument 'completion' which wasn't expected"

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1112]
![image](https://user-images.githubusercontent.com/52195359/158311932-3da0bc5c-a9f9-47bd-938a-a1163a0837e9.png)

Waiting for more info. Might be a bug with an older fig version?

If you're also running into this problem, add `setopt -x` at the **very top** of your zshrc, before the fig lines. Then, run this command:
```
zsh -ic 'exit' 2>&1 | grep 'fig completion'
```

Please leave the output in a comment 🙂

**Comment by CharlieDixon** [comment]
### Description:
When I opened up a new terminal session (iTerm or Terminal), I got the error message in the screenshot below. I just installed Fig so it's the latest version and I tried running `fig doctor` and `fig -- completion` as the prompt suggested. Doctor said everything looks good and `fig -- completion` returns `error: The subcommand 'completion' wasn't recognized`. I tried restarting my machine but was still getting the error. I tried the solution mentioned above but just got a string of errors in my terminal. I found that commenting out/removing the oh-my-zsh fig plugin in my .zshrc file resolved this issue for me.

<img width="822" alt="Screenshot 2022-03-15 at 10 38 38" src="https://user-images.githubusercontent.com/58493339/158360041-d455843b-86f1-4b75-929a-e91c630764da.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B405) [British]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/csd/.nvm/versions/node/v17.1.0/bin:/Users/csd/.local/bin:/Users/csd/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/csd/PycharmProjects/tracer_pools/geckodriver:/Users/csd/.fig/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/csd
  - CLI Installed: true
  - Executable Location: /Users/csd/.local/bin/fig
  - Current Window ID: 1871/% (com.googlecode.iterm2)
  - Active Process: zsh (47515) - /dev/ttys004
  - Environment Variables:
    - TERM_SESSION_ID=w1t0p0:AD089E36-2AE7-4F01-BD27-25A2089CEA00
    - PATH=/Users/csd/.nvm/versions/node/v17.1.0/bin:/Users/csd/.local/bin:/Users/csd/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/csd/PycharmProjects/tracer_pools/geckodriver:/Users/csd/.fig/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.2.0
    - FIG_CHECKED_PROMPTS=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Fig is not a zsh plugin and should not be included in the oh-my-zsh `plugins` array! (There is also a typo in the Fig CLI which is trigger this behavior, but either way, you shouldn't try to add it as a plugin).

**Comment by grant0417** [comment]
Fig can now be a zsh plugin!

Fig will correctly handle being added to the `plugins` array, but this is not too useful and is not any core functionality of Fig.

**Comment by skwaugh** [comment]
Hi @SeparateRecords.  Yes, I have had fig installed as a plugin in OMZ.  After adding `setopt -x` -
` ~  zsh -ic 'exit' 2>&1 | grep 'fig completion' `
`+/Users/sawyer/.oh-my-zsh/plugins/fig/fig.plugin.zsh:13> fig completion zsh`

Removing fig as a plugin from my .zshrc has eliminated the issue.  Thanks!
