### ISSUE TITLE
Deamon: Deamon is not running - error when running fig doctor after initial install

### ISSUE THREAD

**Issue by fabiankaegy** [withfig/fig#1116]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Deamon: Deamon is not running - error when running fig doctor after initial install

```
✘ Daemon: Daemon is not running
  Daemon status: 1
  Init system: Launchd
Attempting to fix automatically...
Re-running check...

✘ Daemon: Daemon is not running
  Daemon status: 1
  Init system: Launchd


✘ Doctor found errors. Please fix them and try again.
```

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B405) [German]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: <generated dynamically>
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /Users/fabiankaegy
  - CLI Installed: true
  - Executable Location: /Users/fabiankaegy/.local/bin/fig
  - Current Window ID: 6971/% (com.apple.Terminal)
  - Active Process: zsh (41837) - /dev/ttys010
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=C187FBB9-F034-4E6E-8681-935461CD0A72
    - PATH=/opt/homebrew/bin:/Users/fabiankaegy/.nvm/versions/node/v16.13.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/fabiankaegy/.local/bin:/Users/fabiankaegy/.fig/bin:/Users/fabiankaegy/.local/bin:/Users/fabiankaegy/.local/bin:/Users/fabiankaegy/.composer/vendor/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.2.0
    - FIG_CHECKED_PROMPTS=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by grant0417** [comment]
Hey @fabiankaegy, could you send me the output of `~/.fig/logs/daemon.log`

**Comment by grant0417** [comment]
Hey @fabiankaegy, could you send me the output of `~/.fig/logs/daemon.log`

**Comment by victorrodrigues** [comment]
I have the same problem and running `fig daemon` outputs:

```2022-03-16T13:25:21.500108Z  INFO fig::daemon: 435: Starting daemon...
2022-03-16T13:25:22.156592Z  WARN hyper_rustls::connector: 39: Could not load all certificates: Custom { kind: InvalidData, error: Custom { kind: InvalidData, error: BadDER } }
Could not connect to websocket

Caused by:
    0: TLS error: webpki error: MissingOrMalformedExtensions
    1: webpki error: MissingOrMalformedExtensions
    2: MissingOrMalformedExtensions
```

**Comment by grant0417** [comment]
@victorrodrigues we should be pushing a build soon that updates to use internal certs so this wont happen

**Comment by grant0417** [comment]
This should be fixed on the stable build of Fig.

Run `fig update` or go into the Fig menu an click `Check for Updates...`

Also make sure to run `fig doctor` after you update to ensure Fig is working correctly.
