### ISSUE TITLE
fig stopped integrating with terminals

### ISSUE THREAD

**Issue by axlotl** [withfig/fig#1117]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

fig stopped connecting to terminals, possibly upon a reboot of this machine. I noticed it wasn't running and restarted it and was walked through what looked like a reinstall, including retrieving a new six digit code emailed to me. It is running, and none of the "Integrations" are disabled in the settings. It thinks it is missing a socket?
<img width="900" alt="Screen Shot 2022-03-15 at 6 50 10 PM" src="https://user-images.githubusercontent.com/1850652/158486942-414d3ba9-bd72-405f-a338-82fa42100e83.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 10.15.7 (19H1715)|1.0.56|-fish|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B405) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: <generated dynamically>
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro10,1
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 10.15.7 (19H1715)
## Environment:
  - User Shell: /usr/local/bin/fish
  - Current Directory: /Users/cwf/htdocs/moovlah-awake
  - CLI Installed: true
  - Executable Location: /Users/cwf/.fig/bin/fig
  - Current Window ID: 134/% (com.apple.Terminal)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - FIG_ENV_VAR=1
    - TERM_SESSION_ID=C0B65C5F-6BD9-4383-9862-FAF4B3AC730C
    - PATH=/usr/local/opt/php@7.4/sbin:/usr/local/opt/php@7.4/bin:/usr/local/opt/libiconv/bin:/usr/local/mysql/bin:/Users/cwf/.composer/vendor/bin:/Users/cwf/.fig/bin:/Users/cwf/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.composer/vendor/bin:/opt/X11/bin:/usr/local/go/bin:/Applications/Wireshark.app/Contents/MacOS
    - TERM=xterm-256color
    - FIG_CHECKED_PROMPTS=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @axlotl! Thanks for reporting this.

Can you run `fig doctor --verbose`? My sense is that Fig's shell integration may not have been set up correctly.

You can fix this by running `fig install --dotfiles`, but please run the other script first! :)

**Comment by axlotl** [comment]
Hi! Thanks. Tried both of these, output from latter below. The latter still reports that it is missing its socket file, I think (red x's!)

```
cwf@axlbook ~/h/moovlah-awake (master)> fig install --dotfiles
✔ Do you want fig to modify your shell config (you will have to manually do this otherwise)? · yes
cwf@axlbook ~/h/moovlah-awake (master)> fig doctor --verbose
Let's check your dotfiles...
✔ /Users/cwf/.bashrc contains valid fig hooks
✔ /Users/cwf/.profile contains valid fig hooks
✔ /Users/cwf/.bash_profile contains valid fig hooks
✔ /Users/cwf/.zshrc contains valid fig hooks
✔ /Users/cwf/.zprofile contains valid fig hooks
✔ /Users/cwf/.config/fish/conf.d/00_fig_pre.fish contains valid fig hooks
✔ /Users/cwf/.config/fish/conf.d/99_fig_post.fish contains valid fig hooks

Let's make sure Fig is running...
✔ Fig bin exists
✔ Fig in PATH
✔ Fig is running
✔ Fig socket exists
✘ Daemon: Daemon socket exists but could not connect
  Socket path: /var/folders/cc/krlfc4w54jq08pb0q0_y2t4c0000gn/T/fig/daemon.sock
✘ Figterm socket: No file at path /tmp/figterm-C0B65C5F-6BD9-4383-9862-FAF4B3AC730C.socket
✔ Insertion lock does not exist
✔ PATH and PseudoTerminal PATH match

Let's check if your system is compatible...
✔ OS is supported

Let's check fig diagnostic...
✔ Installation script
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled
✔ Secure keyboard input disabled

Let's check your terminal integrations...
✔ iTerm integration is enabled
✔ VSCode integration is enabled

Let's check if you're logged in...
✔ Logged into Fig


Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!

cwf@axlbook ~/h/moovlah-awake (master)> 
```

**Comment by mschrage** [comment]
Can you open a new terminal and run `fig doctor --verbose` again? Also would you mind sharing your bashrc/zshrc?

**Comment by axlotl** [comment]
Hm, I generally use fish shell. switched to bash and fig started working immediately. switched to zsh and it worked there too. went to other fish shells and switched to bash and back to fish and fig worked again (in fish). Which is interesting, but I appear to be good. Any other info I can provide you fwiw? I still have some fish shells open that I have not cycled to bash and back where fig still doesn't work but they look like the screenshot above. I just opened some new terms and fig works there. *sorry!*

To answer your q, my .bashrc and .zrc are uninteresting as is my fish config, which just points at aliases and funtions:
```
. "$HOME/.config/fish/aliases.fish"
. "$HOME/.config/fish/functions.fish"
```
