### ISSUE TITLE
Remove legacy SSH integrations on install, uninstall, or update

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1118]
> I have spent the last day or two setting up a new computer. As part if that, I migrated some config files from my old machine, including my ssh config. I have had Fig on that machine for quite a while and never uninstalled it there, so I still had the legacy ssh integration in my ssh config, but that configuration was no longer supported, leading to the original invalid argument warning with Fig enabled and the “not a command” error without it. 
> 
> After removing the integration from my ssh config all is well and Fig is reinstalled. It’s probably a fringe case, but if it’s worth the effort, one thing that would have prevented it would be to check for that integration on installation, so it would have been caught when I installed Fig on my new machine.

This could be part of an overall update to the update flow?

**Comment by brendanfalk** [comment]
This is likely a really really old integration where we actually edited the SSH config directly as opposed to linking to our `.fig` directory. 

If this is happening with you, please remove anything inside the fig integration comment block, including the fig cli command from the local command line (e.g. `fig bg ssh init`)
