### ISSUE TITLE
Error message when enter is hit too quickly

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1119]
> Error message when hit enter key quickly 12:09:31    ~/devLocal/GitProd/RunBatch/LDAP   Feature-FDP ⇡8 !1 ?2  thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', [library/std/src/io/stdio.rs:1187:9](http://library/std/src/io/stdio.rs:1187:9) note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by jmuncaster** [comment]
I got this error too.

Ran with RUST_BACKTRACE=1

```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1164:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: std::io::stdio::_print
   3: fig_cli::cli::internal::InternalSubcommand::execute::{{closure}}
   4: fig_cli::cli::Cli::execute::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: tokio::park::thread::CachedParkThread::block_on
   7: tokio::runtime::thread_pool::ThreadPool::block_on
   8: tokio::runtime::Runtime::block_on
   9: fig_cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Running in iTerm with fish shell

Hold down Return key a few seconds. Release. Hold down again a few seconds. Repeat and eventually this happens on occasion.

![CleanShot 2022-06-07 at 11 39 39](https://user-images.githubusercontent.com/2768145/172458069-2fb32565-ce39-4be2-a5d4-7169d5e22ace.gif)
