### ISSUE TITLE
Settings Error

### ISSUE THREAD

**Issue by Dadox** [withfig/fig#1121]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
When I click on settings, window is opening but "Something went wrong :("

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.0|Version 1.0.56 (B405)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B405) [French] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/xxx/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Applications/MAMP/bin/php/php7.4.21/bin:/Users/xxx/.composer/vendor/bin:/Applications/MAMP/bin/php/php7.4.27/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/xxx/.local/bin:/Users/xxx/.fig/bin:/Users/xxx/.local/bin:/Users/xxx/.local/bin:/Users/xxx/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @Dadox, could you right click on the window and click `Inspect Element` then send use the output in the tab `Console`.

**Comment by Dadox** [comment]
Hey @grant0417 

I saw the same issue on https://github.com/withfig/fig/issues/1106

fig login in terminal solved the problem

Thank's
