### ISSUE TITLE
.zshrc:127: command not found: fig after updating to macOS 12.3.0 update

### ISSUE THREAD

**Issue by XAER** [withfig/fig#1123]
### Description:
Right after the macOS 12.3.0 update Fig stopped working from startup.
Each time I open a new terminal I get an error saying that the command fig is not found and, of course, fig autocomplete doesn't work.

`/Users/xaer/.zshrc:127: command not found: fig`

- I tried every step from the common issues on the support page.
- I also tried Uninstalling fig and fresh installing it with the default settings
- Last thing I tried is edit the ~/.zshrc file manually adding ~/.fig/bin and ~/.local/bin to the path using:
`export PATH=$PATH:~/.fig/bin`

But nothing did work. I was able to run `fig doctor` and `fig issue` directly using the fig file installation on my terminal (iTerm2): `~/.fig/bin/fig doctor` and `~/.fig/bin/fig issue`

- Output for where fig:
`where fig`
`fig not found`

If needed I can also provide my ~/.zshrc file content.

Before the update fig was running just fine, I don't know if the things are related.

Thanks for helping me!

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B405) [Italian]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/xaer/.rvm/gems/ruby-3.0.3/bin:/Users/xaer/.rvm/gems/ruby-3.0.3@global/bin:/Users/xaer/.rvm/rubies/ruby-3.0.3/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/xaer/Documents/Dev/flutter/bin:/Users/xaer/.rvm/bin:/usr/local/go/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: Mac mini
  - Model Identifier: Macmini9,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/xaer
  - CLI Installed: true
  - Executable Location: /Users/xaer/.fig/bin/fig
  - Current Window ID: 2806/% (com.googlecode.iterm2)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:A09977B1-8342-4240-9958-81EC4555D7AB
    - PATH=/Users/xaer/.rvm/gems/ruby-3.0.3/bin:/Users/xaer/.rvm/gems/ruby-3.0.3@global/bin:/Users/xaer/.rvm/rubies/ruby-3.0.3/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/xaer/Documents/Dev/flutter/bin:/Users/xaer/.rvm/bin:/usr/local/go/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.2.0
    - FIG_CHECKED_PROMPTS=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @XAER! Try quitting the Fig app then launch it manually, either through spotlight, `open -a Fig.app` or double clicking it 🙂

Let us know if that works!

**Comment by mschrage** [comment]
Hey @XAER! I just looked at the output from `fig diagnostic` (thank you for attaching it btw) and this seems to be an issue with your `PATH`.

```
PATH=/Users/xaer/.rvm/gems/ruby-3.0.3/bin:/Users/xaer/.rvm/gems/ruby-3.0.3@global/bin:/Users/xaer/.rvm/rubies/ruby-3.0.3/bin:/opt/homebrew/bin:
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/xaer/Documents/Dev/flut>ter/bin:/Users/xaer/.rvm/bin:/usr/local/go/bin
```

Your `PATH` does not contain either `~/.fig/bin` or `~/.local/bin`. Would you mind sharing your zshrc/zprofile? My suspicion is that you may be accidentally overwriting the `PATH` variable.

**Comment by XAER** [comment]
Thanks for the replies! I tried quitting the Fig app and launching it manually as advised, but unfortunately it didn't solve the issue for me!

@mschrage Here are both my .zshrc and .zprofile (idk if its fine to have both)

[**.zshrc**](https://pastebin.com/a3XfLjb9)

[**.zprofile**](https://pastebin.com/cjwqaf2S)

I'm sorry I used pastebin, hope it isn't a problem to show the files.

Thanks again!

**Comment by mschrage** [comment]
You are overriding your PATH variable on line 117.
```
export PATH=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/xaer/Documents/Dev/flutter/bin
```

Please change it to this:
```
export PATH="${PATH}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/xaer/Documents/Dev/flutter/bin"
```

This should resolve your issue, but it makes me think we should change our shell integration back to being a file (or at least an absolute path)...
