### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1124]
> My settings are not saved

Waiting for more info. If you're also having this issue, please comment:
* The setting you were trying to edit
* What you were trying to set it to (eg. enabled, disabled, "400")
* Whether you have an internet connection - I'm assuming the answer is yes, but it can't hurt to make sure.

**Comment by grant0417** [comment]
We had an issue where setting might be reset on reinstall, this is fixed, unsure if it is related

**Comment by grant0417** [comment]
This should be fixed!
