### ISSUE TITLE
No completions for binaries prefixed with a path

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1126]
Completions should work based on the basename of the first token. For example, the following should all resolve to `deno`:
```
deno                                      -- currently, only this one works
.deno/bin/deno
./.deno/bin/deno
~/.deno/bin/deno
/Users/robert/.deno/bin/deno
```
I use this frequently since I'm often testing stuff in shells without my $PATH set up correctly, so a lot of `/opt/homebrew/bin/...` going on...

`token.slice(token.lastIndexOf("/") + 1)` is always guaranteed to get the last segment, and work if there are no slashes (since -1 + 1 is 0)

**Comment by fedeci** [comment]
It should be pretty easy!

**Comment by fedeci** [comment]
All the paths with a slash are currently being parsed as a `Local` spec and we try to load the spec file from the `.fig` folder in the same dirname of the file.
e.g. for `.deno/bin/deno` we try to load the spec from `.deno/bin/.fig/autocomplete/build/deno.js`. If no spec could be found we do not fallback on a global spec.

**Comment by SeparateRecords** [comment]
cc @sullivan-sean 

I think falling back to the global spec is _probably_ the correct behavior? It's really hard to say for sure. You're right that it should be easy to test out!

One thing to test (if it's implemented as a fallback) is that `isScript` doesn't inherit the same behavior, that should still only use local suggestions. Not sure if it uses the same code path for its lookup, so just making sure it's noted 😄
