### ISSUE TITLE
Fig error about `completion` when added as an Oh-My-Zsh plugin

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1127]
## If you're encountering this error, remove `fig` from your plugins array

This is with the latest build:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/52195359/158760898-d9828878-0ff7-402e-99b0-49e9c9ee4efb.png">

Fig is not a shell plugin, it's a separate app that adds its own shell integrations. A lot of people try to enable it as a shell plugin - it should fail silently instead of printing an error. `fig completion` should either no-op or produce actual completions.

**Comment by grant0417** [comment]
This should no longer be an issue as Fig now supports ohmyzsh compleations!

![Screen Shot 2022-03-17 at 7 47 04 PM](https://user-images.githubusercontent.com/7355421/158927970-fd25bc5a-cbb5-470e-ae22-1aa9468ed065.png)
