### ISSUE TITLE
Installation fails if editing dotfiles requires root permissions

### ISSUE THREAD

**Issue by CalebDu** [withfig/fig#1128]
### Description:
> my macbook pro 14 with m1 pro installs fig successfully. but after installing, iterm is opend automatically and no script and example runs,fig cannot autocomplete. I uninstall fig and reinstall it again. it does not work again. I'm confused.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.56 (B405)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B405) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/caleb/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: false
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by CalebDu** [comment]
<img width="1352" alt="Screen Shot 2022-03-17 at 21 14 23" src="https://user-images.githubusercontent.com/59528230/158816307-00bb9ba7-8ea8-4ac1-a705-2ab5298d7b2f.png">

**Comment by CalebDu** [comment]
i click "rerun install script". no respose
![Uploading Screen Shot 2022-03-17 at 21.16.47.png…]()

**Comment by CalebDu** [comment]
i click "rerun install script". but not response
<img width="1352" alt="Screen Shot 2022-03-17 at 21 16 47" src="https://user-images.githubusercontent.com/59528230/158816754-5ffc7ecc-7355-431a-8b42-d5353f56cd07.png">

**Comment by mschrage** [comment]
Hey @CalebDu! Thanks for reporting this. Can you run the following commands for me:

- `ls ~/.fig`
- `which fig`
- `/Applications/Fig.app/Contents/MacOS/fig-darwin-universal install --dotfiles`

**Comment by CalebDu** [comment]
>  i try to run the commands. But "cmd not found:fig". and then i run `/Applications/Fig.app/Contents/MacOS/fig-darwin-universal install --dotfiles` but failed. i manually add ` eval "$(fig init zsh post/pre)"` in `/zshrc` and source .zshrc.  Iterms show "cmd not found fig " again.

<img width="1352" alt="Screen Shot 2022-03-18 at 14 11 54" src="https://user-images.githubusercontent.com/59528230/158948642-93ac1cd0-bb68-4d36-a631-60589ca8c9ca.png">

<img width="1352" alt="Screen Shot 2022-03-18 at 14 28 00" src="https://user-images.githubusercontent.com/59528230/158949228-fdf8a46d-41bf-4ef5-b361-44dc1505c152.png">

**Comment by grant0417** [comment]
@CalebDu, can you update with `fig update` and try running `/Applications/Fig.app/Contents/MacOS/fig-darwin-universal install --dotfiles` again?
