### ISSUE TITLE
Fig in PATH: Path does not contain ~/.local/bin

### ISSUE THREAD

**Issue by bruno-smartpension** [withfig/fig#1129]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.0.1 (21A559)|1.0.56|-zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B405) [British]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: false
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/CyberArk EPM.app/Contents/Helpers
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.0.1 (21A559)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/bruno.crosier
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 158/% (com.googlecode.iterm2)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:19F92A02-98DD-440F-AEAC-28D286899030
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/CyberArk EPM.app/Contents/Helpers
    - TERM=xterm-256color
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @bruno-smartpension,

You are likely clobbering your PATH variables in your zshrc/zprofile. Make sure every time you are setting the PATH variable, you are including the existing value. 

eg. `export PATH=$PATH:/my/new/value` rather than `export PATH=/my/new/value`
