### ISSUE TITLE
iterm instructions unclear

### ISSUE THREAD

**Issue by himat** [withfig/fig#113]
I just installed Fig, and on the last screen it says

```
Fig can't distinguish between iTerm tabs by default
   and requires the use of a plugin.
```

But I don't actually understand what this means. I have a few tabs open in iTerm right now and the Fig autocomplete menu pops up as expected in any tab I try it in.
So why do I need to install install the iTerm plugin?

**Comment by mattschrage** [comment]
This is no longer required.
