### ISSUE TITLE
fig settings crashes after updating to the latest beta

### ISSUE THREAD

**Issue by scoop** [withfig/fig#1131]
### Description:

> Please include a detailed description of the issue (and an image or screen recording, if applicable)
![CleanShot 2022-03-17 at 22 21 26](https://user-images.githubusercontent.com/502/158897262-1280856b-0e9a-459d-9b37-3d4f5b66b5f6.gif)

Is there anything else I can provide?

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.56 (B409)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B409) [Beta] [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/patrick/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: 7710/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by grant0417** [comment]
@scoop can you right click and press "Inspect Element" and give the output of the console

**Comment by grant0417** [comment]
@scoop, a new stable build is available that you should try updating to as well.

**Comment by scoop** [comment]
It's fixed with the new stable build. Thanks!
