### ISSUE TITLE
Panic with unknown proxy scheme error

### ISSUE THREAD

**Issue by zoubingwu** [withfig/fig#1133]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I have a `export http_proxy=socks5://xxxxx` env in my `.zshrc`, and fig will panic for that, remove it then start a new session the error no longer shows up.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: "unknown proxy scheme" }', /Users/ciaccount/.cargo/registry/src/github.com-1ecc6299db9ec823/sentry-0.25.0/src/transports/reqwest.rs:36:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: "unknown proxy scheme" }', /Users/ciaccount/.cargo/registry/src/github.com-1ecc6299db9ec823/sentry-0.25.0/src/transports/reqwest.rs:36:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B414) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/zou/.pyenv/shims:/Users/zou/.pyenv/bin:/Users/zou/.krew/bin:/Users/zou/homebrew/opt/openjdk/bin:/Users/zou/go/bin:/Users/zou/.deno:/User/zou/.tiup:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/zou/.cargo/bin:/Applications/kitty.app/Contents/MacOS:/Users/zou/.local/bin:/Users/zou/.fig/bin:/Users/zou/.local/bin:/Users/zou/.local/bin:/Users/zou/homebrew/bin:/Users/zou/.nvm/versions/node/v16.13.1/bin::/Users/zou/homebrew/opt/mysql@5.7/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/zou
  - CLI Installed: true
  - Executable Location: /Users/zou/.local/bin/fig
  - Current Window ID: 39590/% (com.apple.Terminal)
  - Active Process: zsh (91903) - /dev/ttys018
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=F202A3B2-ED68-497D-85CB-70E3AE6A0CB8
    - PATH=/Users/zou/.pyenv/shims:/Users/zou/.pyenv/bin:/Users/zou/.krew/bin:/Users/zou/homebrew/opt/openjdk/bin:/Users/zou/go/bin:/Users/zou/.deno:/User/zou/.tiup:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/zou/.cargo/bin:/Users/zou/.local/bin:/Users/zou/.fig/bin:/Users/zou/.local/bin:/Users/zou/.local/bin:/Users/zou/homebrew/bin:/Users/zou/.nvm/versions/node/v16.13.1/bin::/Users/zou/homebrew/opt/mysql@5.7/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by grant0417** [comment]
@zoubingwu a temporary fix for this so you can use your proxy is to add `export FIG_DISABLE_SENTRY=1` to your dotfiles.
