### ISSUE TITLE
Fig doesn't see that it is running

### ISSUE THREAD

**Issue by wdg** [withfig/fig#1135]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig does not work/start after restarting terminal
```bash
Updating Fig to latest version...

Unable to Connect to Fig:
Fig might not be running to launch Fig run: fig launch


~ main*
❯ fig launch

→ Fig is already running.

~/Cloud/WDG main*
❯ fig doctor

✘ Fig socket exists: No file at path /var/folders/ny/4nl9w81x57n6mh5sg4mcnwdh0000gn/T/fig.socket

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

~/Cloud/WDG main*
❯ sudo fig doctor
Password:

✘ Daemon: Daemon is not running
  Init system: Launchd
Attempting to fix automatically...
Failed to fix: Could not start daemon: Warning: Expecting a LaunchDaemons path since the command was ran as root. Got LaunchAgents instead.
`launchctl bootstrap` is a recommended alternative.
/Users/wesley/Library/LaunchAgents/io.fig.dotfiles-daemon.plist: Path had bad ownership/permissions
Load failed: 122: Path had bad ownership/permissions



✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

```

To fix this, I need to uninstall and re install.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/wesley/Cloud
  - CLI Installed: true
  - Executable Location: /Users/wesley/.local/bin/fig
  - Current Window ID: <unknown>
  - Active Process: <unknown>
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=DF26DDF9-782E-4CFC-8088-2288542B65E6
    - PATH=/usr/local/php5/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/wesley/.local/bin:/Users/wesley/.fig/bin:/Users/wesley/.local/bin:/Users/wesley/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.2.0
    - FIG_CHECKED_PROMPTS=1
    - FIG_ENV_VAR=1
## Integrations:

</p>
</details>

**Comment by wdg** [comment]
Got it working this time to run (3 times):

```bash
❯ /Applications/Fig.app/Contents/MacOS/fig
Not showing menubarIcon because of app.hideMenubarIcon
227 bytes
Accessibility: permission remains enabled.
1647621896426 | windowserver [AXWindowServer.swift:108] | DEBUG | Window = 0; App = <none>; pid = 0

1647621896426 | windowserver [AXWindowServer.swift:108] | DEBUG | fromActivation!

1647621896449 | windowserver [AXWindowServer.swift:108] | DEBUG | Began tracking 'com.apple.Terminal'

1647621896462 | windowserver [AXWindowServer.swift:108] | DEBUG | Began tracking 'com.apple.loginwindow'

1647621896462 | windowserver [AXWindowServer.swift:108] | DEBUG | cannot register to observe window events on com.apple.notificationcenterui
```

**Comment by brendanfalk** [comment]
@wdg Not 100% sure what's going on here, Would you be open to jumping on a really quick call to debug this with us? calendly.com/withfig/debugging


We'd love to work out what the hell is going on and get this fixed for you!

**Comment by jermudgeon** [comment]
I had the same issue. No combination of checking/unchecking the Accessibility setting in Privacy helped. I ended up installing the latest app, deleting the entry from Accessibility, and launching again. That fixed it.

**Comment by wdg** [comment]
After the latest run (what I described) it works as expected!
