### ISSUE TITLE
installation script

### ISSUE THREAD

**Issue by axldmg** [withfig/fig#1136]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

installation script

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.6.5 (20G527)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B414) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: false
  - PseudoTerminal Path: /Users/axldmg/opt/anaconda3/bin:/Users/axldmg/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin:/Users/axldmg/.local/bin:/Users/axldmg/.fig/bin:/Users/axldmg/.local/bin:/Users/axldmg/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro11,3
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 11.6.5 (20G527)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/axldmg
  - CLI Installed: true
  - Executable Location: /Users/axldmg/.local/bin/fig
  - Current Window ID: 4576/% (com.apple.Terminal)
  - Active Process: zsh (7656) - /dev/ttys002
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=F60790E4-594C-48B0-96DD-F7252D11BD70
    - PATH=/Users/axldmg/opt/anaconda3/bin:/Users/axldmg/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin:/Users/axldmg/.local/bin:/Users/axldmg/.fig/bin:/Users/axldmg/.local/bin:/Users/axldmg/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by brendanfalk** [comment]
Could you please run `fig doctor --verbose` and copy the output below?

**Comment by axldmg** [comment]
Hey Brendan, I got all fixed and green "Everything looks good!" flag now, cheers (I had a conflict with Conda settings within bash_profile file, which is sorted now).
You diligence is much appreciated!

**Comment by brendanfalk** [comment]
Thanks @axldmg !! Glad it's working

Interesting to hear we had a conflict w Conda. Could you please share your `.bash_profile` with and tell us what conda settings you changed? We'd love to try and fix this pre-emptively

**Comment by eglassman** [comment]
I'm having the same issue!
