### ISSUE TITLE
Fig not recognizing Accessibility settings in Security & Privacy

### ISSUE THREAD

**Issue by adampatterson** [withfig/fig#1137]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig won't seem to recognize the Accessibility preferences.

Running `fig doctor` shows an issue ` Fig socket exists: No file at path /var/tmp/fig/adam/fig.socket`.

![image](https://user-images.githubusercontent.com/31537/159056765-bfa5f219-e4ba-4b0f-a832-0a02918fdcae.png)

![image](https://user-images.githubusercontent.com/31537/159056806-80277af4-088d-4638-be78-d1307488b91c.png)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro14,1
  - Chip: 
  - Cores: 2
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/adam
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: <unknown>
  - Active Process: <unknown>
  - Environment Variables:
    - TERM_SESSION_ID=w1t0p0:B988F001-35A7-44F2-AE42-8880F6475DC4
    - PATH=/usr/local/opt/mysql-client/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/ncurses/bin:~/.composer/vendor/bin:/usr/local/opt/php@7.4/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Utilities/Privileges.app/Contents/Resources:/Users/adam/.local/bin:/Users/adam/.fig/bin:/Users/adam/.local/bin:/Users/adam/.local/bin:/Users/adam/.composer/vendor/bin:/usr/local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.2.0
## Integrations:

</p>
</details>

**Comment by mschrage** [comment]
Try manually removing the Fig app using the "-" button and then add it back with the "+" button. 

Then restart Fig. If Accessibility permissions still haven't been granted, try restarting your computer.

**Comment by M4rteaga** [comment]
Had the same problem with that version and for me removing it manually and then adding it back worked perfectly. 
Thanks @mschrage  👍

**Comment by M4rteaga** [comment]
> Try manually removing the Fig app using the "-" button and then add it back with the "+" button.

Had the same problem with that version and for me removing it manually and then adding it back worked perfectly.
Thanks @mschrage 👍

**Comment by brendanfalk** [comment]
Running `fig debug accessibility refresh` should fix!

**Comment by amirtal-cp** [comment]
issue still exist. mac OS 12.6, fig 1.5.0
> Running fig debug accessibility refresh should fix!

it is not a fix, its basically the same as re-installing...
what it does is to reset the accessibility back to disabled, and also closes fig...
you then need to re-run fig, it will launch its ui windows with a warning that accessibility is disabled, and you will need to re-enable it again manually.
it will not even pop up as an app requiring permission, so you will need to open finder and manually locate fig to add to accessibility list.

this will then need to be repeated on next issue occurrence, already went through this process four times.

**Comment by vorillaz** [comment]
Kind of same as @amirtal-cp mentioned, the fig app does not get added to the accessibility apps.
macOS 12.3, Monterey, fig 1.5.0
