### ISSUE TITLE
SSH and docker exec, fig integration fails

### ISSUE THREAD

**Issue by baragona** [withfig/fig#114]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

SSH into remote server, then open a shell inside a docker container,  docker exec -it containername sh

And the fig completions reflect the remote server but not inside the container.

### Details:
|macOS|Fig|Shell|
|----|----|----|
|10.15.7|Version 1.0.42 (B207)|/bin/bash|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.42 (B207) 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/kevin/.fig/bin/fig
Accessibility: true
Number of specs: 107
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/kevin/.fig/user/keybindings
iTerm Integration: false
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/bash (32175) - ttys011
Current working directory: /Users/kevin
Current window identifier: 106503/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mattschrage** [comment]
Fig autocomplete currently works with SSH sessions and inside Docker containers running locally on your machine. 

Getting autocomplete working inside of containers on a remote machine over SSH is going to be very tricky to do.

**Comment by mschrage** [comment]
Closing as stale!
