### ISSUE TITLE
Fig doesn't work with multiple user accounts

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1140]
> I use my laptop with multiple user accounts (personal, work, guest, sandbox, etc) and i initially installed fig in my personal account. I quite liked it so I decided to also use it in my work account. I double clicked fig and went through the setup. Everything seemed to go well, but the autocomplete did not run in the terminal. Trying to run fig from the terminal from my work account returns a: "Could not launch fig" message. Even executing it directly: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal does not work anymore, in any of my accounts. Another thing I noticed is that once I opened fig in my work account (with fig already installed in my system, from my personal account) was that it asked me to update fig (even though it was already up to date) and it downloaded an update.

Version 1.0.56 (B414)

(I haven't tested this myself)

**Comment by pilang** [comment]
Workaround that fixed the problem for me (fixing a directory with users name in /var/tmp/fig with correct owner):
`sudo mkdir /var/tmp/fig/$(whoami)`
`sudo chown $(whoami): /var/tmp/fig/$(whoami)`

**Comment by SeparateRecords** [comment]
cc @grant0417 @mschrage this seems like an easy fix!

**Comment by ShawnCockburn** [comment]
> The problem seems to be that a certain directory for the unix-socket is made just for the user that installs the app.
> Workaround that fixed the problem for me (fixing a directory with users name in /var/tmp/fig with correct owner):
> `sudo mkdir /var/tmp/fig/$(whoami)`
> `sudo chown $(whoami): /var/tmp/fig/$(whoami)`

this fixed my issue, thank you!

**Comment by grant0417** [comment]
@mschrage any insight on the solution to do this automatically?

**Comment by mschrage** [comment]
Probably requires a change to how the macOS app creates the `/var/tmp/fig` folder to ensure all users have read/write permissions.

**Comment by brendanfalk** [comment]
This is live
