### ISSUE TITLE
TLS error: webpki error

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1142]
Seen this happen twice now:
1. > ✘ Daemon: TLS error: webpki error: MissingOrMalformedExtensions
2. > ✘ Daemon: TLS error: webpki error: UnsupportedCriticalExtension

If this is happening to you, please let us know:
* If you're on a work network or using a VPN
* If you're using a work-managed device
* If you're doing something interesting with your network configuration

**Comment by j9ac9k** [comment]
Hello @SeparateRecords 

I just got he first error.  To answer your questions

- I am WFH, and while I have WireGuard installed, it is not currently active
- This is a work device, but there is no "management" software on here
- Network configuration is that I have my laptop connected to a thunderbolt 3 dock (WD19TB), and using the wired LAN connection from there.  The WiFi device is also connected.

Let me know if I can provide any additional helpful information

**Comment by SeparateRecords** [comment]
@j9ac9k thank you for the details! In the ◧ Fig menu, what version does it say you're on? Would love to know if this is fixed for you on v1.0.56 B421 🙂

**Comment by j9ac9k** [comment]
> @j9ac9k thank you for the details! In the ◧ Fig menu, what version does it say you're on? Would love to know if this is fixed for you on v1.0.56 B421 🙂

I'm on that version, and no longer seeing that error with `fig doctor`; I think an update got applied since I opened the issue (silly me for not putting version info in the issue).

**Comment by SeparateRecords** [comment]
Great! I'll close this issue since it seems to be properly resolved, if it ever happens again definitely comment (or just make a new issue)
