### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by alexmatute** [withfig/fig#1146]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.1.0 (21C52)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B414) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alexmatute/.local/bin:/Users/alexmatute/.fig/bin:/Users/alexmatute/.local/bin:/Users/alexmatute/.local/bin:/Users/alexmatute/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.1.0 (21C52)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/alexmatute
  - CLI Installed: true
  - Executable Location: /Users/alexmatute/.local/bin/fig
  - Current Window ID: 1135/% (com.apple.Terminal)
  - Active Process: zsh (52729) - /dev/ttys004
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=A81454E0-6A0F-415D-936C-C10D363E939D
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alexmatute/.local/bin:/Users/alexmatute/.fig/bin:/Users/alexmatute/.local/bin:/Users/alexmatute/.local/bin:/Users/alexmatute/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @alexmatute! Can you add any details on what is going wrong?

**Comment by alexmatute** [comment]
was solved thx, I just try reinstall with brew and this fixed the issue.

**Comment by mschrage** [comment]
Glad to hear that everything is working now! Out of curiosity, what was the issue @alexmatute?

**Comment by alexmatute** [comment]
The issue was when I try to launch fig terminal got a error that said it doesn’t install properly, like it isn’t a global install, so I try reinstall again with brew and the problem is solved
