### ISSUE TITLE
not working from yesterday

### ISSUE THREAD

**Issue by piorkowski** [withfig/fig#1147]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B414) [Polish]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/sbin:/Users/pawelpiorkowski/opt/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/pawelpiorkowski/.local/bin:/Users/pawelpiorkowski/.fig/bin:/Users/pawelpiorkowski/.local/bin:/Users/pawelpiorkowski/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/pawelpiorkowski
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 412/% (co.zeit.hyper)
  - Active Process: zsh (2538) - /dev/ttys001
  - Environment Variables:
    - PATH=/usr/local/sbin:/Users/pawelpiorkowski/opt/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/pawelpiorkowski/.local/bin:/Users/pawelpiorkowski/.fig/bin:/Users/pawelpiorkowski/.local/bin:/Users/pawelpiorkowski/.local/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=9CF9C982-30AA-41E4-AA60-0059D94E0EC2
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: installed!
  - Visual Studio Code: application is not present.
  - Docker: true

</p>
</details>

**Comment by mschrage** [comment]
Hey @piorkowski! Thanks for letting us know. Can you run `fig doctor --verbose` and share the output here?
