### ISSUE TITLE
Can't log into my Mac via SSH

### ISSUE THREAD

**Issue by Tekl** [withfig/fig#1149]
### Description:
When I try to connect to my Mac where Fig is installed via SSH I get this Error:

```
Enter passphrase for key '/Users/*/.ssh/id_rsa': 

Unable to Connect to Fig:
Fig might not be running to launch Fig run: fig launch


Caused by:
    Failed to connect to "/var/folders/tp/wmthcyhx7cl5wpfs7q3rmcxm0000gp/T/fig.socket": Connection refused (os error 61)
```

Fig doctor does not find any issues.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.56 (B414)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B414) [German] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/*/.fig/bin/fig
Accessibility: true
SSH Integration: true
Tmux Integration: true
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/sphinx-doc/bin:/usr/local/opt/sphinx-doc/bin:/usr/local/sbin:/Users/*/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/sphinx-doc/bin:/usr/local/opt/sphinx-doc/bin:/usr/local/sbin:/Users/*/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/sphinx-doc/bin:/usr/local/opt/sphinx-doc/bin:/usr/local/sbin:/Users/*/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/*/.local/bin:/Users/*/.fig/bin:/Users/*/.local/bin:/Users/*/go/bin:/Users/*/.local/bin:/Users/*/go/bin:/Users/*/.local/bin:/Users/*/go/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (12209) - /dev/ttys004
Current terminal session: 25ECDB75-84FE-4C34-AC53-44967FDAC7C9
Current working directory: /Users/*
Current window identifier: 561/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Tekl! Thanks for reporting this. I would recommend editing your `~/.ssh/config` to remove the Fig integration. I think this will resolve the issue.

Let me know if now and I will reopen it!

**Comment by Tekl** [comment]
Thanks for helping. That was not the solution but gave me the hint to look into the .ssh folder. There I did some tests with rsync and the file "authorized_keys". Deleting it was the solution.
