### ISSUE TITLE
Fig is not detecting the 'Accessibility' setting

### ISSUE THREAD

**Issue by Dhaiwat10** [withfig/fig#1150]
### Description:
I recently updated Fig and it hasn't been working since. It keeps telling me to enable 'Accessibility` even though I have already enabled that. I tried toggling the setting too. Also tried re-installing. No luck.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B414) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: false
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/dhaiwat/.nvm/versions/node/v16.13.2/bin:/Users/dhaiwat/.yarn/bin:/Users/dhaiwat/.config/yarn/global/node_modules/.bin:/Users/dhaiwat/.local/share/solana/install/active_release/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/dhaiwat/.cargo/bin:/Users/dhaiwat/.local/bin:/Users/dhaiwat/.fig/bin:/Users/dhaiwat/.local/bin:/Users/dhaiwat/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/dhaiwat/code
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: ???
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=CAFE3505-5276-4463-B889-4B37F7CADEC6
    - PATH=/Users/dhaiwat/.nvm/versions/node/v16.13.2/bin:/Users/dhaiwat/.yarn/bin:/Users/dhaiwat/.config/yarn/global/node_modules/.bin:/Users/dhaiwat/.local/share/solana/install/active_release/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/dhaiwat/.cargo/bin:/Users/dhaiwat/.local/bin:/Users/dhaiwat/.fig/bin:/Users/dhaiwat/.local/bin:/Users/dhaiwat/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @Dhaiwat10! Open System Preferences > Privacy & Security > Accessibility and then press the "-" to remove Fig. Afterwards, try adding it back by pressing the "+" button.

This should resolve the issue. (You may need to restart your computer as well)
