### ISSUE TITLE
Dynamic suggestions for `cd` do not work

### ISSUE THREAD

**Issue by ZilvinasKucinskas** [withfig/fig#1152]
### Description:

After working with PC for a while, fig gets stuck. It is not able to provide paths for `cd` command or grasp `git` shortcuts (provide autocomplete for custom `git co`). Fig getting stuck looks like this:

![Screenshot 2022-03-22 at 15 43 56](https://user-images.githubusercontent.com/3614693/159495421-770ed08f-0654-448a-a752-240038840a90.png)

Restarting fig helps and it starts working normally again. It would be great that Fig keeps always working as intended.

Let me know if I can give you any more useful information about this bug. Maybe `fig` has some kind of log file where we could see the crash message.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.56 (B414)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B414) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/zil/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/Users/zil/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/zil/.local/bin:/Users/zil/.asdf/shims/terraform:/Users/zil/.fig/bin:/Users/zil/.local/bin:/Users/zil/.asdf/shims/terraform
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @ZilvinasKucinskas! Thanks for reporting this. Can you share your zshrc/zprofile with me?

And we do have logging that might shed some light on what's going on. Can you upload the contents or `~/.fig/logs/pty_c.log`?

**Comment by ZilvinasKucinskas** [comment]
Hey @mschrage,

> Can you share your zshrc/zprofile with me?

<details>
  <summary>`~/.zprofile`</summary>

```
# Fig pre block. Keep at the top of this file.
export PATH="${PATH}:${HOME}/.local/bin"
eval "$(fig init zsh pre)"



# Fig post block. Keep at the bottom of this file.
eval "$(fig init zsh post)"
```
</details>

and 

<details>
  <summary>`~/.zshrc`</summary>

```
# Fig pre block. Keep at the top of this file.
export PATH="${PATH}:${HOME}/.local/bin"
eval "$(fig init zsh pre)"

export PATH="${PATH}:${HOME}/.asdf/shims/terraform"

. /opt/homebrew/opt/asdf/libexec/asdf.sh

# ENVIRONMENT VARIABLES

export HOMEBREW_CASK_OPTS="--appdir=~/Applications --fontdir=/Library/Fonts"
export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"

# SOME CUSTOM SCRIPTS

eval "$(/opt/homebrew/bin/brew shellenv)"

# Fig post block. Keep at the bottom of this file.
eval "$(fig init zsh post)"

```
</details>

> Can you upload the contents or ~/.fig/logs/pty_c.log?

Unfortunately, `~/.fig/logs/c_pty.log` contains PII so I cannot share it. I could search the file myself if you are looking for specific messages.

**Comment by mschrage** [comment]
Hey @ZilvinasKucinskas! Without more information it's hard for me to help debug.

Can you schedule some time on my calendar so we can investigate this together? https://calendly.com/mschrage/30min

**Comment by ZilvinasKucinskas** [comment]
Thanks, @mschrage. It seems this problem does not happen anymore 🤷 , so I will go ahead and close the issue.
