### ISSUE TITLE
Settings > General > Application > "Hide Icon" is not working

### ISSUE THREAD

**Issue by JohnnyTheTank** [withfig/fig#1153]
### Description:
> Settings > General > Application > "Hide Icon" is not working for me. Anyone else?

<img width="215" alt="image" src="https://user-images.githubusercontent.com/6803264/159564320-18422b1c-2831-41e1-b588-8b97cda9f379.png">

<img width="827" alt="image" src="https://user-images.githubusercontent.com/6803264/159564367-ddbcf263-c724-49c0-ada2-99aa8cd2df08.png">

<img width="204" alt="image" src="https://user-images.githubusercontent.com/6803264/159564394-f4c89451-8a5f-4a53-9db5-0bd832e13cad.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.56 (B414)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B414) [German] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jonathanhornung/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Do any of the settings work? (Try checking by switching the theme in the Autocomplete tab and seeing if the appearance of autocomplete changes).

Also can you run `fig doctor --verbose` and share the output here?

**Comment by JohnnyTheTank** [comment]
For some reason its working now

**Comment by dotlouis** [comment]
Had the same issue.

Had the toggle "Hide Icon" turned on but it only got applied when I changed another setting (namely Appearance -> Theme).

Maybe the event handler for the "Hide Icon" setting is not properly triggered?

**Comment by mschrage** [comment]
I think the underlying issue here has to do with debouncing the settings updates that are sent to the client - @sean.s @grant0417 is anyone working on this?

**Comment by grant0417** [comment]
> I think the underlying issue here has to do with debouncing the settings updates that are sent to the client - @sean.s @grant0417 is anyone working on this?

This should hopefully be resolved on the new build 1.0.57 which is coming very soon, as well as the beta currently.

**Comment by MadhavVij** [comment]
@th0th Thanks! I am having the same issue. That workaround works.

**Comment by th0th** [comment]
> @th0th Thanks! I am having the same issue. That workaround works.

💐

**Comment by grant0417** [comment]
It looks like we were having an issue with syncing between the app and settings file that should be resolved now. You can also run `fig settings sync` to update the file with the latest values.

I'm going to close this issue because I believe it is fixed.
