### ISSUE TITLE
Fig can't update or launch

### ISSUE THREAD

**Issue by greenbicycle** [withfig/fig#1154]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
When I launch a terminal window, I get a weird error message from Fig that says that fig update:app is not a command and that I should try "fig update". I type "fig update" and hit enter and it tells me that fig is not running. If I type "fig launch" it says that fig is already running.  "Fig doctor" returns this: Fig socket exists: No file at path /var/folders/ll/clr_rl111cz6fgw_bfg31q_40000gr/T/fig.socket

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /Users/jeffreydavis
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: <unknown>
  - Active Process: <unknown>
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:05C9569F-5C60-417E-B116-A5549930C59A
    - PATH=~$/Library/Python/3.9/bin:/Users/jeffreydavis/.nvm/versions/node/v14.16.1/bin:~$/Library/Python/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/jeffreydavis/.fig/bin:/Users/jeffreydavis/bin:/Users/jeffreydavis/.composer/vendor/bin:/Users/jeffreydavis/.local/bin:/Users/jeffreydavis/bin:/Users/jeffreydavis/.composer/vendor/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=6
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.0.10
    - FIG_ENV_VAR=1
    - FIG_CHECKED_PROMPTS=1
## Integrations:

</p>
</details>

**Comment by greenbicycle** [comment]
I tried `brew reinstall --cask fig` but I am still getting the following:

![image](https://user-images.githubusercontent.com/3146643/159620205-7ef9749f-d1c6-4144-bbd5-c96a4096e41f.png)

**Comment by brendanfalk** [comment]
> User Shell: Unknown UserShell
So this is super strange...

Will leave to @mschrage to ask follow ups

**Comment by mschrage** [comment]
Try running `fig quit` and then relaunch Fig manually using Spotlight.

A few questions:
- Share your bashrc/zshrc?
- Run `fig doctor --verbose` and share the output here.
- Do you see the Fig icon appear in your menu bar? If yes, please click on it an share a screenshot of the "Debugger"

It seems like you might have multiple versions of Fig running simultaneously or have an old version of the shell integration still installed.

**Comment by SeparateRecords** [comment]
Should be fixed in the latest version!
