### ISSUE TITLE
Terminal Launch from Menu Bar App

### ISSUE THREAD

**Issue by ggarnhart** [withfig/fig#116]
**Is your feature request related to a problem? Please describe.**
I usually launch apps with [Alfred](https://www.alfredapp.com). With terminals, however, I don't have a default way. I use the VSCode terminal so much that I don't have a habitual way of opening it.

**Describe the solution you'd like**
l've started associating Fig with the Terminal more and more (nicely done!). It would be cool if I could click on the Fig menubar app and choose a menu item that would open a new terminal for me to use. Sure, it's a two-step process, but it might be beneficial.

**Describe alternatives you've considered**
Opening with Alfred/dock/etc.

**Additional context**
I don't think this a great feature, necessarily, but I was surprised I didn't see it. Figured it might be worth throwing out there.

**Comment by parssak** [comment]
This has been fixed!
