### ISSUE TITLE
Endless validation loop

### ISSUE THREAD

**Issue by Jim-Horn** [withfig/fig#1162]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

`> fig settings`

Enter email address
Enter emailed code
Rinse and repeat - endless loop

Can't access the settings via terminal or menu item - same result

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.0|Version 1.0.56 (B416)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B416) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jim.horn/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Jim-Horn! Are you using a corporate VPN? We've seen this effect login before. #1134

**Comment by mschrage** [comment]
@Jim-Horn we've pushed a hot fix for this. If you reopen the Fig window and login on last time, everything should work normally going forward.
