### ISSUE TITLE
Daemon: TLS error: webpki error: MissingOrMalformedExtensions

### ISSUE THREAD

**Issue by sflory94566** [withfig/fig#1165]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When I run fig doctor I get the following message that I would appreciate some guidance on how to fix:

Daemon: TLS error: webpki error: MissingOrMalformedExtensions

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B414) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/stephen/.local/bin:/Users/stephen/.fig/bin:/Users/stephen/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,4
  - Chip: 
  - Cores: 8
  - Memory: 64 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/stephen
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 1753/% (com.googlecode.iterm2)
  - Active Process: bash (94856) - /dev/ttys003
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=w1t0p0:470E4C14-B721-4CC8-8330-97AD1E470BF1
    - PATH=/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/stephen/.local/bin:/Users/stephen/.fig/bin:/Users/stephen/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @sflory94566! Are you using a VPN?

**Comment by SeparateRecords** [comment]
Related placeholder: #1142

**Comment by grant0417** [comment]
Fixed on beta
