### ISSUE TITLE
Use full/absolute path to `fig` executable instead of relying on `$PATH`

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1167]
Currently the shell integrations rely on `fig` being in your $PATH. This is fine for most configs, but some people unintentionally clobber their path in the middle of their config.

This config will cause errors:
```bash
# Fig pre block. Keep at the top of this file.
export PATH="${PATH}:${HOME}/.local/bin"
eval "$(fig init zsh pre)"

export PATH="/usr/bin:/usr/sbin:/bin:/sbin"

# Fig post block. Keep at the bottom of this file.
eval "$(fig init zsh post)"
```

Instead, we could do as follows, and ensure the fig binary is in the path in the post block (which I think it already does?)

```bash
eval "$(~/.local/bin/fig init zsh pre)"


eval "$(~/.local/bin/fig init zsh post)"
```

**Comment by felix-schaipp** [comment]
This fixed my issue not being able to run fig entirely. Thank you @SeparateRecords 😍

**Comment by mschrage** [comment]
Yeah, using the `fig` executable to add the shell integration is nice in theory but has proven more fragile.

I think we might revert to using files. Maybe something like:
```
. ~/.fig/zsh/pre

. ~/fig/zsh/post
```

**Comment by SeparateRecords** [comment]
Reverting to files would also allow us to also use early returns / exits since it wouldn't be evaluated in the same context.

Another thing I wanted to bring up would be to use process substitution with an absolute path, that way we can still get early exits:
```zsh
# zsh, bash
source <(~/.local/bin/fig init zsh pre)
```
```fish
# fish
source (~/.local/bin/fig init fish pre | psub)
```

**Comment by mschrage** [comment]
@SeparateRecords @sullivan-sean is working on this migration now. Any qualms about switching back to files?

**Comment by SeparateRecords** [comment]
No problem with files! The nice thing about the binary is that it can do stuff like produce entirely different config depending on the environment, but plain-old-text-files are much simpler and users can modify them too if theres a bug

**Comment by mschrage** [comment]
I think we are going to split the difference.

The idea is that `~/.fig/zsh/pre` will contains the following:
```
eval $(~/.local/bin/fig init zsh pre)
```

This lets us not worry about the user's `PATH` while still producing the configuration at runtime.

**Comment by mschrage** [comment]
This should be fixed as of the latest build!
