### ISSUE TITLE
MissingOrMalformedExtensions

### ISSUE THREAD

**Issue by CrazyCarl12** [withfig/fig#1168]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

✘ Daemon: TLS error: webpki error: MissingOrMalformedExtensions
Attempting to fix automatically...
Re-running check...

✘ Daemon: TLS error: webpki error: MissingOrMalformedExtensions

✘ Doctor found errors. Please fix them and try again.

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/31351505/159854231-d4c70b42-d025-4d56-9c94-b7891a80af11.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B416) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/epuasbrp/.local/bin:/Users/epuasbrp/.fig/bin:/Users/epuasbrp/.local/bin:/Users/epuasbrp/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,4
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/epuasbrp/.ssh
  - CLI Installed: true
  - Executable Location: /Users/epuasbrp/.local/bin/fig
  - Current Window ID: 38257/% (com.googlecode.iterm2)
  - Active Process: zsh (72211) - /dev/ttys003
  - Environment Variables:
    - TERM_SESSION_ID=w0t2p0:7DBF182E-0851-4D2C-B1D3-9D045D5A08DD
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/epuasbrp/.local/bin:/Users/epuasbrp/.fig/bin:/Users/epuasbrp/.local/bin:/Users/epuasbrp/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
This should be fixed in the next release cc @grant0417

**Comment by grant0417** [comment]
@CrazyCarl12, this should be on beta now!

**Comment by mschrage** [comment]
FYI you can update to the beta by running `fig settings app.beta true` @CrazyCarl12

**Comment by CrazyCarl12** [comment]
@mschrage The beta fixed it!

**Comment by mschrage** [comment]
Great to hear! I'll close this issue now.
