### ISSUE TITLE
`fig diagnostic` displays wrong path to ZSH

### ISSUE THREAD

**Issue by NickSdot** [withfig/fig#1170]
### Description:
I am using ZSH via Homebrew. In my environment the correct $SHELL is loaded. However, `fig diagnostic` still shows `/bin/zsh` as User Shell. Not sure if this a display issue only or if something is wrong in general. There is no real issues and fig works as expected. I thought that I should report it anyway.

**Command:** 
`ps -p $$`

```
# output shows correct shell
PID TTY           TIME CMD
18625 ttys004    0:00.42 /XXXXXX/Stockpile/homebrew/brew/Cellar/zsh/5.8.1/bin/zsh --login
```

**Command:** 
`which zsh`

```
# output shows correct shell
/XXXXXX/Stockpile/homebrew/brew/bin/zsh
```

**Command:** 
`echo $SHELL`

```
# output shows correct shell
/XXXXXX/Stockpile/homebrew/brew/bin/zsh
```

**Command:** 
`fig diagnostic`

```
# output (Fig Diagnostics > Environment > User Shell) shows WRONG shell:
/bin/zsh
```

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|/XXXXXX/Stockpile/homebrew/brew/Cellar/zsh/5.8.1/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B416) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 176
  - Symlinked dotfiles: true
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /XXXXXX/Stockpile/homebrew/brew/opt/curl/bin:/XXXXXX/Stockpile/homebrew/brew/bin:/XXXXXX/Stockpile/homebrew/brew/sbin:/XXXXXX/Stockpile/Dotfiles/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/XXXXXX/.local/bin:/XXXXXX/.fig/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro14,3
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /XXXXXX
  - CLI Installed: true
  - Executable Location: /XXXXXX/.local/bin/fig
  - Current Window ID: 60782/% (com.googlecode.iterm2)
  - Active Process: zsh (18625) - /dev/ttys004
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:23E1C3A7-CA19-4A1A-9F60-0EA00463E518
    - PATH=/XXXXXX/Stockpile/homebrew/brew/opt/curl/bin:/XXXXXX/Stockpile/homebrew/brew/bin:/XXXXXX/Stockpile/homebrew/brew/sbin:/XXXXXX/Stockpile/Dotfiles/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/XXXXXX/.local/bin:/XXXXXX/.fig/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Don't worry @NickSdot! This is not an issue. `userShell` is your login shell. 

It is the output of running the following command:
```
dscl . -read ~ UserShell
```

**Comment by NickSdot** [comment]
Thanks for your answer @mschrage! But, I can't confirm what you say. The command you mentioned gives me also the correct output and not the wrong output which fig is showing.

**Command:**
`dscl . -read ~ UserShell`
```
UserShell: /XXXXXX/Stockpile/homebrew/brew/bin/zsh
```

Cheers and thanks for this great tool! ❤️

**Comment by mschrage** [comment]
Hmm interesting. Perhaps an old value was stored before you `brew` installed the new version of zsh?
