### ISSUE TITLE
Keep asking for Enable Accessibility Permission

### ISSUE THREAD

**Issue by mohandev** [withfig/fig#1172]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

After Update,

1. Even after turning off accessibility and turn it back on, it keeps showing the dialog.
2. I've to press `-` and add `Fig` again and then turn on the accessibility to move forward..

![Screenshot 2022-03-24 at 3 49 48 PM](https://user-images.githubusercontent.com/5886607/159895598-c40678fd-744f-4835-ac69-275c4cbbb56e.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.56 (B416)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B416) [ABC – India] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/mohanrajkr/.fig/bin/fig
Accessibility: false
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hmm @mohandev! Thanks for reporting this. 

If you use the "-" to remove Fig and then reenable it with the "+", does this resolve your issue? 

We should probably document this workaround somewhere...

**Comment by mohandev** [comment]
> Hmm @mohandev! Thanks for reporting this. 
> 
> 
> 
> If you use the "-" to remove Fig and then reenable it with the "+", does this resolve your issue? 
> 
> 
> 
> We should probably document this workaround somewhere...

Yes it works once I've removed Fig using "-". Thanks..
