### ISSUE TITLE
Keeps asking for email address

### ISSUE THREAD

**Issue by ReneKrewinkel** [withfig/fig#1173]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When clicking on "Settings", the dialog keeps asking to "Login into Fig", when entering my email I get a code in my mail box, when entering the code, it keeps coming back with "Login into Fig"

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.56 (B416)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B416) [Dev] [Dutch] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/rene/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: true
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by golergka** [comment]
I'm having the same issue. There's no error message or anything, it just asks for my email again.

Also, the interface is unclear.

1. Is providing me email necessary for fig to work, or is it just an extra option?

2. Why do you ask for work email? What about people who are not employees, or prefer to use work tools on their personal accounts, not connected to their employers?

3. What exactly is the mechanism by which you want to connect people with their teammates? What does this connection entail?

4. How will this email address be used, what is your privacy policy on this information?

Overall, it feels like a very rough feature that was very rushed in development. We should be able to opt out of it at least.

**Comment by mschrage** [comment]
@golergka @ReneKrewinkel are either of you free to jump on a call? https://calendly.com/mschrage/30min

**Comment by jwebbstevens** [comment]
same thing I experienced. try `fig doctor` quit the application, restart.

_Login with Fig Failure/Infinite Loop_ https://github.com/withfig/fig/issues/1134

**Comment by mschrage** [comment]
@jwebbstevens we have just pushed a hotfix for this! Close the Fig window and login in one last time.

**Comment by ReneKrewinkel** [comment]
@mschrage Yes works! Thanks. 

Sorry, I was offline when you asked for the call otherwise I'd participated
