### ISSUE TITLE
Shell integration uses syntax which is unsupported on older versions of `fish`

### ISSUE THREAD

**Issue by FrimJo** [withfig/fig#1174]
### Description:
Get this error every time I open the iTerm2 and fish shell:
```
killpg(88299, Hangup: 1): Operation not permitted
- (line 103): Expected end of the statement, but instead found a redirection
  if command -v fig &>/dev/null
                     ^
from sourcing file -
	called on line 61 of file /usr/local/share/fish/functions/eval.fish

in function 'eval'
	called on line 3 of file ~/.config/fish/conf.d/99_fig_post.fish

from sourcing file ~/.config/fish/conf.d/99_fig_post.fish
	called on line 305 of file /usr/local/share/fish/config.fish

from sourcing file /usr/local/share/fish/config.fish
	called during startup

source: Error while reading file '-'
```
works in regular Terminal though.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.4.0 (20F71)|1.0.56|/usr/local/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B414) [Swedish - Pro]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/frim/Library/Flutter/sdk/bin:/Users/frim/.deno/bin:/Users/frim/.n/bin:/Users/frim:/Users/frim/.fig/bin:/Users/frim/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/frim/Library/Android/sdk/platform-tools:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 6
  - Memory: 32 GB
## OS Info:
  - macOS 11.4.0 (20F71)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/frim
  - CLI Installed: true
  - Executable Location: /Users/frim/.fig/bin/fig
  - Current Window ID: 182120/% (com.googlecode.iterm2)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - PATH=/Users/frim/Library/Flutter/sdk/bin:/Users/frim/.deno/bin:/Users/frim/.n/bin:/Users/frim:/Users/frim/.fig/bin:/Users/frim/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/frim/Library/Android/sdk/platform-tools:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
    - TERM=xterm-256color
    - TERM_SESSION_ID=w0t0p0:7815C361-E111-4FE3-99AF-7AEE236E632D
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @FrimJo! What version of `fish` are you using? The latest versions of fish support this syntax. https://github.com/fish-shell/fish-shell/issues/6192

**Comment by ThnxFredrik** [comment]
> Hey @FrimJo! What version of `fish` are you using?
> 
> The latest versions of fish support this syntax. [fish-shell/fish-shell#6192](https://github.com/fish-shell/fish-shell/issues/6192)

I probably have an older version, installed it quite some time ago. I’ll make an update and get back to you. Ty

**Comment by mschrage** [comment]
Can you share the output of `fish --version`?

**Comment by ThnxFredrik** [comment]
> Can you share the output of `fish --version`?
```
$ fish --version
fish, version 3.0.0
```

**Comment by mschrage** [comment]
Great to hear! I'll close this issue for now, but we should add some documentation indicating the oldest version of `fish` that we support.
