### ISSUE TITLE
Daemon: IO error: The Trust Settings Record was corrupted

### ISSUE THREAD

**Issue by acarpe** [withfig/fig#1175]
### Description:
result of fig doctor:

✘ Daemon: IO error: The Trust Settings Record was corrupted.
Attempting to fix automatically...
Re-running check...

✘ Daemon: IO error: The Trust Settings Record was corrupted.

✘ Doctor found errors. Please fix them and try again.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.1.0 (21C52)|1.0.56|/usr/local/Cellar/zsh/5.8_1/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B416) [U.S. International – PC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: true
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/myuser/.opam/default/bin:/Users/myuser/.jenv/shims:/Users/myuser/.jenv/bin:/usr/local/opt/node@10/bin:/usr/local/var/rbenv/shims:/usr/local/opt/imagemagick@6/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:.git/safe/../../bin:.git/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/myuser/.jenv/shims:/Users/myuser/.jenv/bin:/usr/local/opt/node@10/bin:/usr/local/var/rbenv/shims:/usr/local/opt/imagemagick@6/bin:/usr/local/opt/coreutils/libexec/gnubin:/Users/myuser/Library/Android/sdk/emulator:/Users/myuser/Library/Android/sdk/tools:/Users/myuser/Library/Android/sdk/platform-tools:/usr/local/opt/go/libexec/bin:/Users/myuser/work/go-workspace/bin:/Users/myuser/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/opt/fzf/bin:/Users/myuser/.fig/bin:/Users/myuser/.local/bin:/Users/myuser/.local/bin:/usr/local/sbin:/Users/myuser/.rvm/bin:/Users/myuser/Library/Android/sdk/emulator:/Users/myuser/Library/Android/sdk/tools:/Users/myuser/Library/Android/sdk/platform-tools:/usr/local/opt/go/libexec/bin:/Users/myuser/work/go-workspace/bin:/Users/myuser/.local/bin:/usr/local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro14,3
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.1.0 (21C52)
## Environment:
  - User Shell: /usr/local/bin/zsh
  - Current Directory: /Users/myuser
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 7689/% (com.googlecode.iterm2)
  - Active Process: zsh (34934) - /dev/ttys015
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w2t0p0:E8348709-C645-4509-901E-4BA4D55AB8AA
    - PATH=/Users/myuser/.opam/default/bin:/Users/myuser/.jenv/shims:/Users/myuser/.jenv/bin:/usr/local/opt/node@10/bin:/usr/local/var/rbenv/shims:/usr/local/opt/imagemagick@6/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:.git/safe/../../bin:.git/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/myuser/.jenv/shims:/Users/myuser/.jenv/bin:/usr/local/opt/node@10/bin:/usr/local/var/rbenv/shims:/usr/local/opt/imagemagick@6/bin:/usr/local/opt/coreutils/libexec/gnubin:/Users/myuser/Library/Android/sdk/emulator:/Users/myuser/Library/Android/sdk/tools:/Users/myuser/Library/Android/sdk/platform-tools:/usr/local/opt/go/libexec/bin:/Users/myuser/work/go-workspace/bin:/Users/myuser/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/opt/fzf/bin:/Users/myuser/.fig/bin:/Users/myuser/.local/bin:/Users/myuser/.local/bin:/usr/local/sbin:/Users/myuser/.rvm/bin:/Users/myuser/Library/Android/sdk/emulator:/Users/myuser/Library/Android/sdk/tools:/Users/myuser/Library/Android/sdk/platform-tools:/usr/local/opt/go/libexec/bin:/Users/myuser/work/go-workspace/bin:/Users/myuser/.local/bin:/usr/local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Related to https://github.com/cloudflare/wrangler/issues/1656#issuecomment-985521466

cc @grant0417 


It seems like you may have some expired certificates in you Keychain @acarpe

**Comment by grant0417** [comment]
It looks like we were use native certs for the websocket connection, I am going to switch these over to using vendered `webpki-roots`

**Comment by mschrage** [comment]
@acarpe is this fixed for you on the latest version?

**Comment by acarpe** [comment]
yes, it is.
thank you.
