### ISSUE TITLE
Brew reinstalls fig on update

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1179]
> I install fig via homebrew and when a new update comes out brew removes and installs again, having to do the how to process again

**Comment by mschrage** [comment]
Hey @SeparateRecords can you investigate this? Does Homebrew run our uninstall script whenever the user updates?

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/fig.rb

**Comment by SeparateRecords** [comment]
I _think_ this is actually working as intended. My hunch is that people habitually run `brew upgrade --greedy` or use a script copied from somewhere that does this. That will uninstall and reinstall casks.

---

If this is happening to you and you _don't_ use `--greedy`, let us know and we'll reopen the issue!
