### ISSUE TITLE
Figterm socket did not read buffer correctly

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1182]
> ![image](https://user-images.githubusercontent.com/52195359/160057600-be77ea4c-c7e7-41f8-84e8-64279f207600.png)

There was nothing indicative of an error in the associated diagnostic output.

If you're also having this error, try restarting Fig completely (quit from the ◧ Fig menu, relaunch the app) and restart your terminal completely. If that doesn't help, leave a comment and let us know so we can debug!

**Comment by grant0417** [comment]
Make this a warning not error and tell not to touch keys
