### ISSUE TITLE
Prompt displaying incorrectly

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1183]
> since the latest update a few weeks or so ago, my terminal isn't displaying properly. I know it's caused by fig because I uninstalled it, and then it was displaying properly. The issue is this:
> 
>  ![image](https://user-images.githubusercontent.com/52195359/160070738-b73a08ee-f1c6-4d41-baa4-cbd0831fdc2e.png)
> 
> The cursor is at the wrong place, it shows up too much to the left (in the current folder instead of right next to it). When I type a command, the text gets replaced 1 by 1 by the command.
>
> ![image](https://user-images.githubusercontent.com/52195359/160070777-6f233ae4-49d8-43bb-9efb-8418864f9dbd.png)
> 
> It's also showing this weird %{ on the right side.
>
> I have this problem in the integrated mac terminal, and also in VSCode. I've tried fig doctor, reinstalling etc, but it's still not working. My OS: macOs Monterey 12.2.1.

**Comment by grant0417** [comment]
I will look into

**Comment by grant0417** [comment]
@SeparateRecords, can you tell what theme this is

**Comment by chaynabors** [comment]
@SeparateRecords
