### ISSUE TITLE
`webpki error: BadDer` when running `fig doctor`

### ISSUE THREAD

**Issue by kbick675** [withfig/fig#1188]
### Description:
I ran `fig doctor` after initial setup and got the following:   

✘ Daemon: TLS error: webpki error: BadDer
Attempting to fix automatically...
Re-running check...

✘ Daemon: TLS error: webpki error: BadDer

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 10.15.7 (19H1715)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B416) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/opt/puppetlabs/bin:/opt/puppetlabs/pdk/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/kbickmore/.local/bin:/Users/kbickmore/.fig/bin:/Users/kbickmore/.local/bin:/Users/kbickmore/.local/bin:/Users/kbickmore/Library/Python/3.9/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB
## OS Info:
  - macOS 10.15.7 (19H1715)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/kbickmore
  - CLI Installed: true
  - Executable Location: /Users/kbickmore/.local/bin/fig
  - Current Window ID: 36524/% (com.googlecode.iterm2)
  - Active Process: zsh (64216) - /dev/ttys002
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:7B3884AC-341E-457A-8299-DF4981F0F049
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/opt/puppetlabs/bin:/opt/puppetlabs/pdk/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/kbickmore/.local/bin:/Users/kbickmore/.fig/bin:/Users/kbickmore/.local/bin:/Users/kbickmore/.local/bin:/Users/kbickmore/Library/Python/3.9/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @kbick675! Thanks for reporting this.

Can you try updating to the beta and see if this issue persists? (Run `fig settings app.beta true`)

**Comment by kbick675** [comment]
I tried updating to the beta as requested and that didn't seem to matter. Updated to latest stable today and now get the following error.

`Daemon: IO error: invalid peer certificate contents: invalid peer certificate: UnknownIssuer`

This is likely related to this being on my work MBP and their use of n+∞ security tools. I'll test on a personal machine when I get a chance.

**Comment by kbick675** [comment]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)



### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 10.15.7 (19H1824)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/opt/puppetlabs/bin:/opt/puppetlabs/pdk/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/kbickmore/.local/bin:/Users/kbickmore/.fig/bin:/Users/kbickmore/.local/bin:/Users/kbickmore/.local/bin:/Users/kbickmore/Library/Python/3.9/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB
## OS Info:
  - macOS 10.15.7 (19H1824)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/kbickmore
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 223/% (com.googlecode.iterm2)
  - Active Process: zsh (8026) - /dev/ttys002
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:BB745208-C291-48A4-AD40-B860B36A4059
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/opt/puppetlabs/bin:/opt/puppetlabs/pdk/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/kbickmore/.local/bin:/Users/kbickmore/.fig/bin:/Users/kbickmore/.local/bin:/Users/kbickmore/.local/bin:/Users/kbickmore/Library/Python/3.9/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Thanks for letting us know @kbick675 

Any ideas @grant0417?
