### ISSUE TITLE
Huge "figterm_dev_ttys001.log" Log File (523.6GB) in MacOS

### ISSUE THREAD

**Issue by dnrm** [withfig/fig#1189]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hello, today i got a notificatino from MacOS stating my disk was full. This was weird since I have little to no files. I diagnosed the problem and eventually pointed out a log file from the `.fig` directory. There was a 500+ gigabyte log file called "figterm_dev_ttys001.log"
<img width="467" alt="image" src="https://user-images.githubusercontent.com/49281837/160179415-c3298a45-a08d-4e6e-a330-c968649f9a92.png">
I dont have a screenshot of the file since I deleted it but here is a terminal screenshot of the `du` command.

I suppose this is a bug in a new version of Fig since I recently updated it.

### Environment

```bash
2020 m1 macbook pro 1tb storage, macos monterey
```

**Comment by mschrage** [comment]
Hey @dnrm! Woah, that is definitely not expected behavior.

Quit all terminal sessions and then delete this file. We have a hotfix in the works. cc @grant0417

**Comment by grant0417** [comment]
I believe this should already be fixed on stable, make sure you are updated to the latest version. I'll check out the logic again to make sure it's all good.

**Comment by dnrm** [comment]
Thank you! I'll make sure to update

**Comment by dnrm** [comment]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/49281837/160181831-ab3fece6-68f7-427a-a457-7088831a391f.png">
I'm in the latest version.

**Comment by SeparateRecords** [comment]
Going to close this issue for now but @dnrm please let us know if it happens again! We'll reopen and fix 🙂
