### ISSUE TITLE
App Wont Reopen Once Hidden from Menu Bar

### ISSUE THREAD

**Issue by browneye1826** [withfig/fig#1193]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
After enabling `app.hideMenubarIcon` in the app (limited bar space given the new MBP notch), I am unable to reopen the app again.
Fig itself still works fine (terminals/VS Code) but the app is gone. 
I tried spotlight/finder, and running `fig app launch` in terminal returns: `→ Fig is already running.`.

In general, it would be awesome for `app.hideMenubarIcon` to be toggleable from the CLI.

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B416) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/eliostreicher/.local/bin:/Users/eliostreicher/.fig/bin:/Users/eliostreicher/.local/bin:/Users/eliostreicher/.local/bin:/opt/homebrew/opt/fzf/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,4
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/eliostreicher/Documents/github/practice_v2/scratchpad
  - CLI Installed: true
  - Executable Location: /Users/eliostreicher/.local/bin/fig
  - Current Window ID: 6635/% (com.microsoft.VSCode)
  - Active Process: zsh (88272) - /dev/ttys002
  - Environment Variables:
    - PATH=/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/eliostreicher/.local/bin:/Users/eliostreicher/.fig/bin:/Users/eliostreicher/.local/bin:/Users/eliostreicher/.local/bin:/opt/homebrew/opt/fzf/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=A96A009A-4848-4B23-93DB-FBC5D1C59BAE
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
@browneye1826 are you trying to open this page?
<img width="942" alt="Screen Shot 2022-03-26 at 5 50 46 PM" src="https://user-images.githubusercontent.com/3155109/160261905-2e3d5273-ca3d-40f6-88df-3065898c0fe7.png">

If so, you can just run `fig` and that will open this window!

(PS. All of these `app` subcommands are more or less internal and probably should be hidden)

**Comment by browneye1826** [comment]
Haha bravo, that did it! In a million years I wouldn't have thought of just 'running `fig`' 
But what do you mean though by 'more or less internal'?! These settings are super useful. 
P.S. I'm in love with Fig! I recommend it to EVERYONE!

**Comment by SeparateRecords** [comment]
> what do you mean though by 'more or less internal'?! These settings are super useful

Agreed! That's why the useful ones have top-level counterparts, basically everything under `fig app` is really plumbing.
* `fig app install` → `fig install`
* `fig app uninstall` → `fig uninstall`
* `fig app quit` → `fig quit`
* `fig app restart` → `fig restart`
* `fig app launch` → `fig launch`
