### ISSUE TITLE
Not working with starship

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1198]
If you use starship and Fig isn't working for you, please let us know!

* Do you use any other plugins?
* Have you customized starship at all?
* Does it only fail in _some_ directories or all of them?
* How is it broken? Not showing up? Prompt is gibberish?

**Comment by brendanfalk** [comment]
May be related to emojis...

**Comment by 0x219** [comment]
<img width="769" alt="image" src="https://user-images.githubusercontent.com/50414099/179160915-cda21a46-d401-4af4-af2c-5b1571f5676c.png">
They both want the last line!!!

**Comment by grant0417** [comment]
No more placeholder, also it should work...
