### ISSUE TITLE
Sign in not working

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1199]
Please leave a comment if you're unable to sign in. We'll follow up to understand what's happening and get it fixed!

**Comment by doozMen** [comment]
after first install I cannot sign in with this the message too many request
<img width="553" alt="Screenshot 2022-07-07 at 10 52 53" src="https://user-images.githubusercontent.com/686038/177733530-53f7ab20-f583-47a0-bea1-adf6359db521.png">

The sign in seams to be mandatory too for fig to work? This seams like not needed if I l just want to use fig on one device no?

**Comment by grant0417** [comment]
This should be fix!
