### ISSUE TITLE
Ignore fig autocomplete on certain commands/refine auto-detect

### ISSUE THREAD

**Issue by bengry** [withfig/fig#1200]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
Fig does a great job at figuring out what cli is being used for the most part, but there are times where it doesn't detect the correct one. One such case is for the `task` cli - which fig assumes is https://taskwarrior.org which in practice I'm using https://taskfile.dev. Each has very different usages, and thus different arguments - so the suggestions that fig makes don't make any sense to me.

I think an ideal solution would be to detect the command (and cache it probably, but I'm getting ahead of myself) using something like `task --help` and try to match it to the known one. Alternatively, let the user disable/override which suggestions are shown for each command.

For now, this is very annoying, but I didn't find a way to disable fig for just `task` in my case. If this is possible please let me know and I'll edit the issue as well.

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B417) [Beta] [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/bengr/Library/Caches/fnm_multishells/99863_1648119240251/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/opt/fzf/bin:/Users/bengr/Library/Python/3.8/bin:/Users/bengr/.cargo/bin:/Users/bengr/bin:/Users/bengr/.local/bin:/Users/bengr/.fig/bin:/Library/Apple/usr/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /opt/homebrew/bin/fish
  - Current Directory: /Users/bengr/projects/wiz__second
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 119/% (com.googlecode.iterm2)
  - Active Process: fish (892) - /dev/ttys003
  - Installed via Brew: true
  - Environment Variables:
    - FIG_TERM=1
    - FIG_INTEGRATION_VERSION=8
    - TERM=xterm-256color
    - FIG_TERM_VERSION=4.3.0
    - TERM_SESSION_ID=w0t0p0:A92BF364-45E2-4859-A246-05AADD5484C8
    - PATH=/opt/homebrew/sbin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/opt/fzf/bin:/Users/bengr/Library/Python/3.8/bin:/Users/bengr/.cargo/bin:/Users/bengr/bin:/Users/bengr/.local/bin:/Users/bengr/.fig/bin:/Users/bengr/Library/Caches/fnm_multishells/945_1648389800821/bin:/Users/bengr/Library/Caches/fnm_multishells/921_1648389800788/bin:/Library/Apple/usr/bin
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
Should be resolved by this PR: https://github.com/withfig/autocomplete/pull/1036
