### ISSUE TITLE
Cannot enabled Accessibility permissions 

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#1205]
> Somehow it is stuck at enabling 'accessibility'. I did indeed reinstall and turn the toggle on and off. Still doesn't work. Makes me sad, as I really enjoy using Fig.

**If you are running into this issue, please do the following:**
1. Quit Fig
2. Run `tccutil reset Accessibility com.mschrage.fig`
3. Relaunch Fig (you will be prompted to grant accessibility permissions again).

**Comment by alexreardon** [comment]
I ran into this problem too. The suggested fix worked great 👍

**Comment by brendanfalk** [comment]
To fix:
Run `fig debug accessibility refresh` and follow the prompts

**Comment by Alainmma** [comment]
> > Somehow it is stuck at enabling 'accessibility'. I did indeed reinstall and turn the toggle on and off. Still doesn't work. Makes me sad, as I really enjoy using Fig.
> 
> **If you are running into this issue, please do the following:**
> 
> 1. Quit Fig
> 2. Run `tccutil reset Accessibility com.mschrage.fig`
> 3. Relaunch Fig (you will be prompted to grant accessibility permissions again).

Scam
