### ISSUE TITLE
fig

### ISSUE THREAD

**Issue by orirori512** [withfig/fig#1209]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B414) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/janghoonseok/.rbenv/shims:/Users/janghoonseok/.rbenv/bin:/Users/janghoonseok/.nvm/versions/node/v17.6.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/janghoonseok/.local/bin:/Users/janghoonseok/.fig/bin:/Users/janghoonseok/.local/bin:/Users/janghoonseok/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/janghoonseok
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 18444/% (com.googlecode.iterm2)
  - Active Process: zsh (38800) - not a tty
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w1t0p0:061F7369-6CFA-4D66-B949-1BCE8D52210F
    - PATH=/Users/janghoonseok/.rbenv/shims:/Users/janghoonseok/.rbenv/bin:/Users/janghoonseok/.nvm/versions/node/v17.6.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/janghoonseok/.local/bin:/Users/janghoonseok/.fig/bin:/Users/janghoonseok/.local/bin:/Users/janghoonseok/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @orirori512 - is something not working with Fig? If so, please add some additional information explaining what is going wrong.
