### ISSUE TITLE
TTY Error in bash_profile after including Fig in .bash_profile

### ISSUE THREAD

**Issue by ginsoul** [withfig/fig#1213]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Hello, 
my bash_profile is sourcing different scripts. I wrote a check before sourcing to prevent it from sourcing scripts with errors.
So this check is saying:
Failed at /Users/cegin/.bash_profile >> 1565: tty

Which is strange because my bash_profile only has  1180 lines. The last lines are:

Fig post block. Keep at the bottom of this file.
eval "$(fig init bash post)"

The missing 390 lines are comming from your script. So I looked in your script coming from the command "fig init bash post" and on line 390 there is "export TTY=$(tty)" which is matching my error.

I think something like
export TTY=$(tty 2>/dev/null || echo "/dev/tty$(w -h|grep $USER|tail -1|awk '{print $2}')" )
could fix it...
But I didn't had the time to test it.

best regards
Egin

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.56 (B416)|/usr/local/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B416) [German] 
UserShell: /usr/local/bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/cegin/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: false
PseudoTerminal Path: /usr/local/opt/coreutils/libexec/gnubin:/usr/local/sbin:/usr/local/bin:/usr/local/:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/apache-maven/apache-maven-3.5.4/bin:~/Documents/script/plugins/ImageMagick-7.0.7/bin:~/Documents/Android/platform-tools/:~/Documents/Development/flutter/bin:~/Documents/script/ceginBin:/Users/cegin/n/bin:/Users/cegin/.fig/bin:/Users/cegin/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Can you share your bash_profile?
