### ISSUE TITLE
Toggling the accessibility setting on update

### ISSUE THREAD

**Issue by rockymontana** [withfig/fig#1217]
### Description:
When fig self updates it wants me to enable accessibility just when installing it. If it's already enabled I'm asked to toggle the setting. This literally never works but I have to remove fig from that setting and then restart fig. I'd rather just get that check if it's not already checked. Is it not possible to store whether or not that has been set in a config, or even better - check the settings if it's already checked?

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.56 (B416)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B416) [Swedish] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: ~/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: 149273/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Unfortunately there's not a lot we can do about this since it's a macOS thing - it's rather finicky with permissions. #1205 has the workaround 🙂

>  **If you are running into this issue, please do the following:**
> 1. Quit Fig
> 2. Run `tccutil reset Accessibility com.mschrage.fig`
> 3. Relaunch Fig (you will be prompted to grant accessibility permissions again).

**Comment by brendanfalk** [comment]
To fix run `fig debug accessibility refresh`
