### ISSUE TITLE
Figterm socket: No file at path ...

### ISSUE THREAD

**Issue by pcrandall** [withfig/fig#1221]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

![image](https://user-images.githubusercontent.com/45416860/160821303-af5f9fa6-c871-4b63-8e18-ca2477d74f6f.png)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|-zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B416) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/feel/.nvm/versions/node/v16.5.0/bin:/opt/homebrew/Cellar/zplug/2.4.2/bin:/opt/homebrew/opt/zplug/bin:/Users/feel/go/pkg:/Users/feel/go/bin:/Users/feel/bin:/Users/feel/Library/Python/3.8/bin:/Users/feel/.zplug:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/feel/.cargo/bin:/opt/homebrew/opt/fzf/bin:/Users/feel/zk/bin:/Users/feel/code/Nim/bin:/Users/feel/.local/bin:/Users/feel/.fig/bin:/opt/homebrew/opt/zplug/repos/kazhala/dotbare
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: 
  - Cores: 8
  - Memory: 8 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/feel
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 4628/% (com.apple.Terminal)
  - Active Process: ??? (???) - ???
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=28F9454A-F948-499E-AA7B-43228933A4AD
    - PATH=/Users/feel/.nvm/versions/node/v16.5.0/bin:/opt/homebrew/Cellar/zplug/2.4.2/bin:/opt/homebrew/opt/zplug/bin:/Users/feel/go/pkg:/Users/feel/go/bin:/Users/feel/bin:/Users/feel/Library/Python/3.8/bin:/Users/feel/.zplug:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/feel/.cargo/bin:/opt/homebrew/opt/fzf/bin:/Users/feel/zk/bin:/Users/feel/code/Nim/bin:/Users/feel/.local/bin:/Users/feel/.fig/bin:/opt/homebrew/opt/zplug/repos/kazhala/dotbare
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @pcrandall! We should improve this error message. Based on the output from `fig diagnostic`, it seems like the underlying issue is that Fig's shell integration is not set up correctly.

Can you run `fig doctor --verbose` and share the output here?

Could you also post your zshrc/zprofile?
