### ISSUE TITLE
No clear way to quit

### ISSUE THREAD

**Issue by ex-nerd** [withfig/fig#1223]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [ ] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:

When you open the desktop app, it opens a terminal window. I had no idea `fig` was not a standalone app so I thought this we a weird mistake and closed the window.  Since "nothing happened" when I opened `fig`, I tried to open it again. Nothing happened (it didn't even open a new terminal window this time).

Decided that something must be wrong with the standalone app so I decided to remove it and reinstall via `brew` MacOS told me the app was still running and couldn't be removed.  Eventually, I figured out that I had to open a new terminal window on my own to , and then took a wild guess to find `fig quit` on the command line (it's not in the `-h`) to kill the daemon and allow me to delete the app (I have about 30 little icons across the top of my screen so totally missed that there might have been a new one from Fig ... a little onboarding tour at first-launch might help there).

You also messed with my `.bashrc` and `.bash_profile` without even informing me. Serious bad form.

### Environment

```bash
sorry, the app is no longer installed
```

**Comment by mschrage** [comment]
Hey @ex-nerd, thank you for the feedback. This is definitely not the experience that we want our users to have.

In fact, we're in the process of completely redoing the onboarding so that it is CLI first and gives more control about writing to dotfiles.

If you'd like, I can jump on a 1:1 call with you right now to help make sure Fig is installed/uninstalled correctly? (I'll be in this Zoom for the next 30min) https://zoom.us/j/94538156166?pwd=VnZGRFp2ZVFXL2QyUkpQWU5BSlhEUT09

**Comment by mschrage** [comment]
Also clearly, we should add `fig quit` and `fig uninstall` to the CLI help text.

**Comment by ex-nerd** [comment]
> If you'd like, I can jump on a 1:1 call with you right now to help make sure Fig is installed/uninstalled correctly?

I'm good.  Eventually found the uninstall docs (which is how I learned about Fig's menu item) ... though I think those might need to mention `rm -rf ~/.fig.dotfiles.bak/` as well.
