### ISSUE TITLE
Post init should be guarded (breaks emacs, securecrt, warp prompt in fish)

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1224]
Solution: we need to guard the post init with a check for `test "$TERM_PROGRAM" = WarpTerminal`. This will also allow us to better fix the SecureCRT and Emacs weirdness (figterm is no longer launched but escape codes are still printed)

<img width="616" alt="image" src="https://user-images.githubusercontent.com/52195359/160947215-81ba497f-1ab0-40fb-a7e0-492be9cd7e58.png">

**Comment by brendanfalk** [comment]
@SeparateRecords are you able to fix this for us?

**Comment by SeparateRecords** [comment]
Will do! o7

**Comment by grant0417** [comment]
@tdyer

**Comment by sullivan-sean** [comment]
This should be fixed in the latest version of fig.
