### ISSUE TITLE
Add requiresSeparator

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1226]
An expansion of `requiresEquals?: boolean | undefined`

`requiresSeparator?: boolean | string | undefined` would allow for options such as [Clojure's `-X:<name>`](https://clojure.org/reference/deps_and_cli#_execute_a_function)

We could keep `requiresEquals` but deprecate it, since `requiresSeparator` can entirely replace it. `requiresSeparator: true` should be equivalent to `requiresEquals: true`

**Comment by fedeci** [comment]
I like this expansion! I'm implementing it later.

**Comment by fedeci** [comment]
This may require extra work and I need to discuss with sean the best way to implement it since currently we rely on the fact that `=` is the separator when we parse options. Does adding a new prop to `parserDirectives` seem a viable alternative to you?
e.g.
```js
// parserDirectives can be specified in each subcommand
parserDirectives: {
  optionArgSeparator: ':'
}
```

**Comment by SeparateRecords** [comment]
> Does adding a new prop to `parserDirectives` seem a viable alternative to you?

Genuinely can't imagine a time when one option would use `:` and another would use something else, so this would almost certainly be fine! We'll take this up on discord to discuss implementation (and by we I mean mostly you and sean 😄)

**Comment by fedeci** [comment]
It is pretty easy to change that using `parserDirectives`, I'll just open a PR and see if sean has suggestions!
