### ISSUE TITLE
Pre shell integration not sourced error when running fig doctor

### ISSUE THREAD

**Issue by robinsimonklein** [withfig/fig#1231]
### Description:
Hi,
I just installed **fig** on my Mac, but after following the onboarding bash tutorial, when I run `fig doctor` I get an error message. Here is the full log :

```shell
● Pre shell integration not sourced first in /Users/robinsimonklein/.bash_profile
✘ Installation script: Install script not run
Attempting to fix automatically...
Re-running check...

✘ Installation script: Install script not run


✘ Doctor found errors. Please fix them and try again.
```

For more context, I am using iTerm2 with OhMyZsh.
My `.bash_profile` looks like that :

```
# DBngin exports
export PATH=/Users/Shared/DBngin/mysql/8.0.12/bin:$PATH

if [ -f ~/.ssh/id_rsa ]; then
    ssh-add -K ~/.ssh/id_rsa 2>/dev/null
fi
```

I tried to add `source ~/.iterm2_shell_integration.bash` as first line following iTerm2's documentation, but nothing changed.

Any kind of help would be appreciated :)
Thanks

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B416) [French]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: false
  - PseudoTerminal Path: /usr/local/sbin:/Users/robinsimonklein/.nvm/versions/node/v16.14.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/robinsimonklein/.local/bin:/Users/robinsimonklein/.fig/bin:/Users/robinsimonklein/.local/bin:/Users/robinsimonklein/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro14,1
  - Chip: 
  - Cores: 2
  - Memory: 8 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/robinsimonklein
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 28176/% (com.googlecode.iterm2)
  - Active Process: zsh (40467) - /dev/ttys003
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w1t0p0:5FBEA3E5-77AA-4CAA-BB9F-87B86AF813EA
    - PATH=/usr/local/sbin:/Users/robinsimonklein/.nvm/versions/node/v16.14.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/robinsimonklein/.local/bin:/Users/robinsimonklein/.fig/bin:/Users/robinsimonklein/.local/bin:/Users/robinsimonklein/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false

</p>
</details>

**Comment by robinsimonklein** [comment]
Also when I open the fig menu in the menu bar, I get those warnings. If I click on "Rerun install script", nothing happens :/

**Comment by mschrage** [comment]
Hey @robinsimonklein! Thanks for reporting this.

It seems like Fig's shell integration isn't being added to `~/.bash_profile`. 

Can you run `ls -l ~/.bash_profile` and share the output here?

Also, besides these warnings, is autocomplete working for you?
