### ISSUE TITLE
Setup error in MacOS

### ISSUE THREAD

**Issue by sanjay75409** [withfig/fig#1238]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.4|Version 1.0.56 (B416)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B416) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/sanpate/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>
<img width="316" alt="image" src="https://user-images.githubusercontent.com/12906245/161137265-d80432a3-e7cb-4ca7-a186-7435f97c8af5.png">

**Comment by mschrage** [comment]
Hey @sanjay75409, thanks for reporting this error. 

When exactly did it appear? Had you logged in already? Also are you using a VPN? I can't reproduce this.
