### ISSUE TITLE
Fig is not working on my mac... its just stoped working

### ISSUE THREAD

**Issue by Vofchuk** [withfig/fig#1245]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B416) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/dani/.local/bin:/Users/dani/.fig/bin:/Users/dani/.local/bin:/Users/dani/.local/bin:/Users/dani/Development/flutter/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/dani
  - CLI Installed: true
  - Executable Location: /Users/dani/.local/bin/fig
  - Current Window ID: 6038/% (com.googlecode.iterm2)
  - Active Process: zsh (16458) - /dev/ttys009
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:EB211A61-0E59-4EC2-A6CC-59FA62172325
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/dani/.local/bin:/Users/dani/.fig/bin:/Users/dani/.local/bin:/Users/dani/.local/bin:/Users/dani/Development/flutter/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Can you run `fig doctor —verbose` and share the output?
