### ISSUE TITLE
postProcess in generators can't get the output of script

### ISSUE THREAD

**Issue by Rhythmicc** [withfig/fig#1247]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I'm trying develop the completion plugin of fig for my own command line script, when I use the generators like `bat.ts` did, postProcess can't get the output of the script.

here's the code:
![image](https://user-images.githubusercontent.com/29839231/161367417-7eb2b6ad-57b5-4b86-a187-c7f3353aa628.png)

here's the output of the script:
![image](https://user-images.githubusercontent.com/29839231/161367429-69dc52cd-eaaa-4e47-9e9a-ea0005890c21.png)

here's the performance of fig:
![image](https://user-images.githubusercontent.com/29839231/161367475-7be0e212-f4a5-4c01-843b-59a22595f90f.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.56 (B421)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B421) [搜狗拼音] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/lianhaocheng/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hey there! Try right clicking the fig popup, then click "Inspect element", then go to the console tab and watch what happens as you type. If there's an error it'll show up in the logs.
<img width="946" alt="image" src="https://user-images.githubusercontent.com/52195359/161464644-7b52521a-41f7-4b6b-a161-6ece01e04406.png">

It's possible that it's just not able to find your CLI in your path (like this):
<img width="829" alt="image" src="https://user-images.githubusercontent.com/52195359/161464664-f2f36590-edfc-4aaf-ae19-818d7e748b95.png">

Usually this can be fixed by restarting fig: `fig restart`

**Comment by Rhythmicc** [comment]
Can FIG can customize the Python third-party library location? It has been positioning the third party library through the Python3.9 installed by Homebrew. . So can't find the relevant library when `qrun` .

**Comment by Rhythmicc** [comment]
But I solved my problem through your method.. Tks!

**Comment by SeparateRecords** [comment]
> Can FIG can customize the Python third-party library location? It has been positioning the third party library through the Python3.9 installed by Homebrew. . So can't find the relevant library when `qrun` .

Not 100% sure I follow, is the issue that your python 3.9 installation doesn't have some libraries you need to run the script?

Fig copies your $PATH variable to run commands, so it should execute programs exactly like how you would. Note that if the `eval "$(fig init zsh post)"` line isn't the final line in your config, this may not work right.

**Comment by Rhythmicc** [comment]
Tks! It was my fault, and I solved. 🙏🏻
