### ISSUE TITLE
Fig doesn't work on 10.13

### ISSUE THREAD

**Issue by ellizonn** [withfig/fig#1250]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 10.13.6 (17G14042)|1.0.56|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [Italian]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ellizonn/.local/bin:/Users/ellizonn/.fig/bin:/Users/ellizonn/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro8,1
  - Chip: 
  - Cores: 2
  - Memory: 8 GB
## OS Info:
  - macOS 10.13.6 (17G14042)
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /Users/ellizonn
  - CLI Installed: true
  - Executable Location: /Users/ellizonn/.local/bin/fig
  - Current Window ID: 2691/% (com.apple.Terminal)
  - Active Process: bash (25967) - /dev/ttys001
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=323D370C-5AB1-487D-A407-B9965DD11DF3
    - PATH=/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ellizonn/.local/bin:/Users/ellizonn/.fig/bin:/Users/ellizonn/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
![image](https://user-images.githubusercontent.com/3155109/161854277-706b8e03-446e-4bab-bb0f-31a28f49450e.png)

Seems like the underlying issue here has to do with a missing polyfill for `globalThis`. Should be a quick fix.

Can you take a look @fedeci?

**Comment by ellizonn** [comment]
> `globalThis` is available since safari 12.1, @ellizonn can you confirm you have a lower version of safari? I also believe you can upgrade safari to 13.x on High Sierra, right? @mschrage can we add a fig diagnostic with the installed webkit version?

![Schermata 2022-04-05 alle 23 28 16](https://user-images.githubusercontent.com/73301705/161932653-7c42fb7d-0e16-4c97-a8b3-3b4da77cea3c.png)
Safari is 13.1.2

**Comment by fedeci** [comment]
That's really strange.

**Comment by ellizonn** [comment]
> That's really strange.

Hope we can try to solve this

**Comment by ellizonn** [comment]
As I reported on Discord to @mschrage , when I try "git co" the fig debugger output is:
![Schermata 2022-04-06 alle 11 32 43](https://user-images.githubusercontent.com/73301705/161945241-1a4cb514-83dc-422f-9d3a-3646f5756770.png)

Meanwhile, the globalThis error occur doing "fig debug autocomplete-window" > it appear a red box > "inspect elements" > it open Web Inspector, and here we can see the error.

**Comment by ellizonn** [comment]
In every condition I inspect the red box, it appear the error.
When I'm typing `git co`, when I'm typing `cd Desk`, and so on

**Comment by ellizonn** [comment]
@fedeci have you any idea to solve this issue?

**Comment by fedeci** [comment]
I have no clue honestly and I hadn't had a change to look deeper into this, sorry!

**Comment by ellizonn** [comment]
> I have no clue honestly and I hadn't had a change to look deeper into this, sorry!

No worry!

**Comment by mschrage** [comment]
Hey @ellizonn, if this is not a quick fix, I think we may just drop support for High Sierra ('officially' we already don't support it).

Sorry that we couldn't get this working for you.
