### ISSUE TITLE
Suggest top level commands

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1253]
> You need to write the whole first command (without using tab) to get the suggestion for “up” which is only a small part of the whole command. I could save a lot more time if Fig could give me suggestions for the first statement

**Comment by mschrage** [comment]
We actually already have support for this but it's been hidden behind a beta flag. We will add it to the settings.

**Comment by sullivan-sean** [comment]
This is now included in settings under `Autocomplete > General > First Token Completion`
