### ISSUE TITLE
Autocomplete keybinding not working

### ISSUE THREAD

**Issue by mlego** [withfig/fig#1256]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
I have my settings to insert a common prefix via the `tab` key and insert selected via the `enter` key. Neither are working. The autocomplete shows a list of suggested commands, but they do not get inserted. This was definitely working before and I have not changed any settings. 

Thank you for your help!

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 200
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/martinlegowiecki/.nvm/versions/node/v14.18.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/martinlegowiecki/.fig/bin:/Users/martinlegowiecki/.local/bin:/Users/martinlegowiecki/.local/bin:/Users/martinlegowiecki/Documents/Code/flutter/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: iMac
  - Model Identifier: iMac20,2
  - Chip: 
  - Cores: 10
  - Memory: 128 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/martinlegowiecki
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 8017/% (com.googlecode.iterm2)
  - Active Process: zsh (27805) - /dev/ttys001
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:A0555DF8-DD4C-4F21-B049-112C58692D2F
    - PATH=/Users/martinlegowiecki/.nvm/versions/node/v14.18.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/martinlegowiecki/.fig/bin:/Users/martinlegowiecki/.local/bin:/Users/martinlegowiecki/.local/bin:/Users/martinlegowiecki/Documents/Code/flutter/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=6
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_ENV_VAR=1
    - FIG_CHECKED_PROMPTS=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @mlego, it looks like your shell integration is out of date. Can you share your zshrc and zprofile here?

**Comment by mlego** [comment]
Thanks @mschrage. Here is my .zshrc (blocked out some sensitive entries)
![image](https://user-images.githubusercontent.com/736880/161835237-b05d9d78-c08c-48c3-8439-0a3f1514436b.png)

And my .zprofile
![image](https://user-images.githubusercontent.com/736880/161835158-2188a449-8d87-489d-9320-6ca89673b90f.png)

**Comment by mlego** [comment]
@mschrage Just noticed something additional - on terminal launch I am getting:

`No such file or directory .fig/bin/fig_get_shell`

**Comment by mschrage** [comment]
Hmm interesting. Thanks for sharing these details. 

Can you try uninstall and reinstalling Fig? (Run `fig uninstall`)

**Comment by mlego** [comment]
Fixed! I am not sure why it worked this time - I tried reinstalling it before. Thank you for your help!
