### ISSUE TITLE
Fig issue:  Secure keyboard input disabled: Secure keyboard input is on

### ISSUE THREAD

**Issue by KamalMicheal** [withfig/fig#1260]
### Description:
> $ fig doctor
> 
> ✘ Secure keyboard input disabled: Secure keyboard input is on
>   Secure keyboard process is Hyper - co.zeit.hyper 
> 
> 
> ✘ Doctor found errors. Please fix them and try again.
> 
> If you are not sure how to fix it, please open an issue with fig issue to let us know!
> Or, email us at hello@fig.io!

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.6.5 (20G527)|1.0.56|/bin/zsh|
<p>

**Comment by mschrage** [comment]
Hey @KamalMicheal! 

Check out [this guide](https://fig.io/docs/support/secure-keyboard-input) on turning off Secure Keyboard Entry for instructions on how to get Fig working.

I am going to close this issue but let me know if you are struggling to disable Secure Keyboard Entry.
