### ISSUE TITLE
I don't get get any suggestion in iTerm right now, can anybody help?

### ISSUE THREAD

**Issue by zyflovelam** [withfig/fig#1264]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/zyf/.npm-global/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/zyf/.local/bin:/Users/zyf/.fig/bin:/Users/zyf/.local/bin:/Users/zyf/.local/bin:/Users/zyf/.local/bin:/usr/local/mysql/bin:/Users/zyf/bin:/Users/zyf/maven/bin:/usr/local/mongodb/bin:/Users/zyf/flutter/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: Mac mini
  - Model Identifier: Macmini9,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/zyf
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 21401/% (com.googlecode.iterm2)
  - Active Process: zsh (86061) - /dev/ttys010
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:0241F69A-CAF5-425C-A525-FCB43BDA10C8
    - PATH=/Users/zyf/.npm-global/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/zyf/.local/bin:/Users/zyf/.fig/bin:/Users/zyf/.local/bin:/Users/zyf/.local/bin:/Users/zyf/.local/bin:/usr/local/mysql/bin:/Users/zyf/bin:/Users/zyf/maven/bin:/usr/local/mongodb/bin:/Users/zyf/flutter/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

---

I ran the command: `fig doctor`, it's showing like this:
![Xnip2022-04-06_17-09-24](https://user-images.githubusercontent.com/19360803/161939675-6b6c5e9e-c177-4e62-8b8b-c2cc3384027c.png)
it's looks like correct for all settings, but when I type any code in iTerm, I don't get any suggestion in there.
![WechatIMG342](https://user-images.githubusercontent.com/19360803/161940182-1c8713e6-50ee-4919-9b4e-510b52c5e517.png)

Can anybody help?

**Comment by mortezasabihi** [comment]
The same problem

**Comment by mschrage** [comment]
@mortezasabihi do you use the same prompt?

Can both of you type `git co` and then take a screenshot of the Fig debugger (click the Fig icon in the macOS menu bar).

**Comment by zyflovelam** [comment]
Like this?

https://user-images.githubusercontent.com/19360803/162094848-52ceb2eb-0660-42de-a120-fef0d5e74a59.mov

**Comment by zyflovelam** [comment]
> Like this?
> 
>  screenshot.mov

@mschrage

**Comment by mschrage** [comment]
Type `git co` but don't press enter. I want to understand if the macOS app is getting events from the shell.

**Comment by mschrage** [comment]
@zyflovelam @mortezasabihi also is this only true in iTerm? Does Fig work in other Terminal apps?

**Comment by zyflovelam** [comment]
Sure, here it is, Iterm2 and Terminal, both not working.

https://user-images.githubusercontent.com/19360803/162101130-d4266a71-4cfc-4b85-8a3a-5e500717c560.mov


https://user-images.githubusercontent.com/19360803/162101136-1c4274c6-2323-4ae6-b94c-30447118930a.mov

**Comment by mschrage** [comment]
Can you run `fig debug autocomplete-window`. You should see a red rectangle popup. Can you right click it (control+click) and then press "Inspect Elements"?

**Comment by zyflovelam** [comment]
@mschrage  Sure, and I got some error message, see the picture:
![Xnip2022-04-07_14-14-24](https://user-images.githubusercontent.com/19360803/162132455-5e9c970d-f6cc-49d4-bfed-a0e50c3f1d77.png)
![Xnip2022-04-07_14-14-41](https://user-images.githubusercontent.com/19360803/162132459-f7d5d0fb-7b63-4fe9-b160-aba46ad97c17.png)

**Comment by mortezasabihi** [comment]
@mschrage 

> @mortezasabihi do you use the same prompt?
> 
> @zyflovelam Can both of you type `git co` and then take a screenshot of the Fig debugger (click the Fig icon in the macOS menu bar).

https://user-images.githubusercontent.com/35567646/162143330-043c51ba-fc2d-4f5c-ab38-9f8560497295.mov

**Comment by mortezasabihi** [comment]
> @zyflovelam @mortezasabihi also is this only true in iTerm? Does Fig work in other Terminal apps?

I use the default mac terminal :)

**Comment by zyflovelam** [comment]
Any updates on this issue?  @mschrage

**Comment by zyflovelam** [comment]
Looks like just us met this issue? @mortezasabihi

**Comment by mortezasabihi** [comment]
> Looks like just us met this issue? @mortezasabihi

Yes

**Comment by zyflovelam** [comment]
@mortezasabihi  I just found this [page](https://forum.withfig.com/t/figs-autocomplete-popup-is-not-showing-up/43/4) to describe why the fig doesn't work, looks like it is correct, in the folder "~/.fig/autocomplete/", there is just a README.md file in there, no any js files.
![Xnip2022-04-18_09-20-24](https://user-images.githubusercontent.com/19360803/163740134-50dba708-cd04-4038-a2ec-d4785a7e3553.png)
Then I follow this guide and click the "Run Install/Update Script" button, but I get nothing, no window to show, and no toast, the autocomplete folder is still empty, even I restart fig. you can try it, check the folder.

**Comment by mschrage** [comment]
Hey @zyflovelam @mortezasabihi! Would either of you be free to get on a 1:1 debugging  all?

https://calendly.com/mschrage/30min

**Comment by zyflovelam** [comment]
Sorry, I don't have any free time for it lately, but maybe next week or the day after May 1st. how about you? @mortezasabihi

**Comment by mschrage** [comment]
@zyflovelam can you reopen the web inspector and run `enableFigDebugging()`. Then take a screen recording of the web console while you type "git com" into the terminal.

**Comment by zyflovelam** [comment]
> @zyflovelam can you reopen the web inspector and run `enableFigDebugging()`. Then take a screen recording of the web console while you type "git com" into the terminal.


https://user-images.githubusercontent.com/19360803/163899686-c178b326-9df9-47ad-8820-3134b87e2262.mov

@mschrage  Sure, here it is, it looks weird, last time I enable it, the big red window will show, but now, it is just a line, and in the console, I get the correct suggestion commands, but not show in the red window.
and in the `>functions:` mode after I ran `enableFigDebugging()`, the tokens are null.

**Comment by mschrage** [comment]
Hmmm what's strange is that all the suggestions seems to be calculated correctly. @fedeci any ideas on what's happening here?

**Comment by fedeci** [comment]
> @mschrage Sure, here it is, it looks weird, last time I enable it, the big red window will show, but now, it is just a line, and in the console, I get the correct suggestion commands, but not show in the red window. and in the `>functions:` mode after I ran `enableFigDebugging()`, the tokens are null.

Hi @zyflovelam `enableFigDebugging()` must be used in the web inspector console, not in the terminal, see the image below.

<img width="1912" alt="Schermata 2022-04-19 alle 18 54 56" src="https://user-images.githubusercontent.com/38510000/164055992-9a88846f-7991-4f08-9215-44b8b009a6ff.png">

**Comment by zyflovelam** [comment]
Haha, sorry for that, here is the new video, btw, I just updated the latest version 1 min ago, the big red window show again. and is this video correct?

https://user-images.githubusercontent.com/19360803/164126979-e6a52b99-d383-4645-903a-2314fa259150.mov

**Comment by mschrage** [comment]
This video is exactly correctly. It is not obvious to me why autocomplete isn't showing up here. It looks like the suggestions are generated correctly and the window positioned in the correct location.

**Comment by mschrage** [comment]
Could you open then "state" and "updatedState" fields after you've typed "git co"?

**Comment by zyflovelam** [comment]
> Could you open then "state" and "updatedState" fields after you've typed "git co"?

@mschrage  Sure, here it is:

https://user-images.githubusercontent.com/19360803/164128680-dc415ab4-032a-4cd4-8f03-481a1bd4908e.mov

**Comment by mschrage** [comment]
Can you run `cat ~/.fig/setting.json`?

**Comment by zyflovelam** [comment]
> Can you run `cat ~/.fig/setting.json` and share the output here?
> 
> And then can you run this command as well `fig settings autocomplete.onlyShowOnTab`?

OK, here it is, you mean `~/.fig/settings.json`? 
![Xnip2022-04-20_09-38-35](https://user-images.githubusercontent.com/19360803/164129555-838f5ed4-0101-4cf2-b620-aced10804d07.png)

**Comment by mschrage** [comment]
Running `fig settings autocomplete.onlyShowOnTab --delete` will resolve the issue.

You have autocomplete configured to only appear when explicitly triggered by pressing the tab key.

**Comment by zyflovelam** [comment]
![Xnip2022-04-20_14-44-30](https://user-images.githubusercontent.com/19360803/164166922-a1ad35ef-bd6e-49b5-a94e-7770825652cd.png)

OMG, thanks, so silly am I, haha @mschrage
