### ISSUE TITLE
not work. why?

### ISSUE THREAD

**Issue by EmilioVar** [withfig/fig#1266]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 10.13.6 (17G14042)|1.0.56|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [Spanish - ISO]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/emiliovm/.local/bin:/Users/emiliovm/.fig/bin:/Users/emiliovm/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro8,1
  - Chip: 
  - Cores: 2
  - Memory: 8 GB
## OS Info:
  - macOS 10.13.6 (17G14042)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/emiliovm
  - CLI Installed: true
  - Executable Location: /Users/emiliovm/.local/bin/fig
  - Current Window ID: 153/% (com.apple.Terminal)
  - Active Process: bash (3084) - /dev/ttys001
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=F31D6380-5109-4FFB-9A65-8ACEFB66ADEE
    - PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/emiliovm/.local/bin:/Users/emiliovm/.fig/bin:/Users/emiliovm/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Hi @EmilioVar - sorry it's not working. Was it just not showing up for you? Did you get to run `fig doctor`?

Looks like you're on an old macOS version which may be the reason why. As far as I'm aware the oldest version we test on is macOS 10.14 (from 2018) - you're running 10.13?

@mschrage can you confirm if Fig should be running on this version?

**Comment by EmilioVar** [comment]
ok it seems that the problem is that I have an old version of macos. Thank you very much for answering!
