### ISSUE TITLE
`fig install --dotfiles` doesn't work for Fish shell

### ISSUE THREAD

**Issue by NV** [withfig/fig#1267]
```
$ fig doctor

✘ 00_fig_pre.fish contains valid fig hooks: /Users/nv/.config/fish/conf.d/00_fig_pre.fish does not exist. Run fig install --dotfiles to reinstall shell integrations for fish


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
$fig install --dotfiles
✔ Do you want fig to modify your shell config (you will have to manually do this otherwise)? · yes
Could not automatically install:
 00_fig_pre.fish: No such file or directory (os error 2)
99_fig_post.fish: No such file or directory (os error 2)

To install fig manually you will have to add the following to your rc files

At the top of your .bashrc or .zshrc or .config/fish/conf.d/00_fig_pre.fish file:
bash:    eval "$(fig init bash pre)"
zsh:     eval "$(fig init zsh pre)"
fish:    eval "$(fig init fish pre)"

At the bottom of your .bashrc or .zshrc or .config/fish/conf.d/99_fig_post.fish file:
bash:    eval "$(fig init bash post)"
zsh:     eval "$(fig init zsh post)"
fish:    eval "$(fig init fish post)"
```

I manually added `eval "$(fig init fish pre)"` to ~/.config/fish/config.fish, but it doesn't seem to be a valid fish code.

```
-: Command substitutions not allowed
from sourcing file -
	called on line 61 of file /usr/local/share/fish/functions/eval.fish

in function 'eval'
	called on line 10 of file ~/.config/fish/config.fish
```

https://fishshell.com/docs/current/cmds/eval.html#cmd-eval

---

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.x.x (x)|1.0.56|-fish|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [Colemak]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 151
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/nv/.bin:/usr/local/bin:/usr/local/opt/:/opt/local/bin:/Users/nv/.fig/bin:/usr/bin:/bin:/usr/sbin:/sbin:[reducted]
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: iMac Pro
  - Model Identifier: iMacPro1,1
  - Chip: 
  - Cores: 10
  - Memory: 64 GB
## OS Info:
  - macOS 12.x.x
## Environment:
  - User Shell: /usr/local/bin/fish
  - Current Directory: /Users/nv/Code
  - CLI Installed: true
  - Executable Location: /Users/nv/.fig/bin/fig
  - Current Window ID: 1417/% (com.apple.Terminal)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - PATH=/Users/nv/.bin:/usr/local/bin:/usr/local/opt/:/opt/local/bin:/Users/nv/.fig/bin:/usr/bin:/bin:/usr/sbin:/sbin:[reducted]
    - TERM=xterm-256color
    - TERM_SESSION_ID=EF138C20-B58A-4089-BE78-E4A2A3EAB14B
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by NV** [comment]
`eval (fig init fish pre)` appears to be valid Fish code, but adding it to `~/.config/fish/config.fish` doesn't change anything, as far I could see.

**Comment by mschrage** [comment]
Hey @NV! What version of fish are you using? (`fish --version`)

Also can you run `ls ~/.config/fish/conf.d` and share the output here?

**Comment by NV** [comment]
Hey @mschrage! My bad, I was running fish 3.0.2 (from 2019!) on that machine. I updated fish to 3.4.1, and `fig install --dotfiles` worked fine!
