### ISSUE TITLE
resolving environment variables when loading suggestions based on generators

### ISSUE THREAD

**Issue by RinkiyaKeDad** [withfig/fig#1277]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
> Please include a detailed description of the feature (and an image or screen recording, if applicable)

Would be useful if Fig could resolve the environment variables in a command like `cd` and then run the generators. The attached screenshot should make it more clear:
<img width="1105" alt="Screenshot 2022-04-07 at 5 42 38 PM" src="https://user-images.githubusercontent.com/56963264/162196587-54c08e88-7b00-4c5d-a3cc-17ca65a658c6.png">

**Comment by mschrage** [comment]
Hey @RinkiyaKeDad! This is a great suggestion. Slightly tricky to implement but I have some idea on how we can make it work.

**Comment by SeparateRecords** [comment]
> 2. Send environment on fig init CLI invocation

Might be good to piggy-back on other fig commands such as `fig doctor` or `fig source`. I think this coupled with `fig init` would work well enough. I don't change my env vars very often once everything is set up how I like it. Definitely not once per session, and certainly not ever few mins.

Also: #620 #741

**Comment by mschrage** [comment]
This is supported in the latest version of Fig!
