### ISSUE TITLE
Documentation: CONTRIBUTING.md refers to a withfig/docs repository, which apparently does not exist.

### ISSUE THREAD

**Issue by clonezone** [withfig/fig#1279]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [ ] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:

https://github.com/withfig/fig/blob/main/CONTRIBUTING.md refers to https://github.com/withfig/docs, which leads to a 404 page.

### Environment

```bash
Not applicable.
```

**Comment by mschrage** [comment]
Hey @clonezone, are you interested in contributing to Fig's documentation? Or are you just requesting that we remove this stale link?

**Comment by clonezone** [comment]
Sorry, I've got too much on my plate as it is. 😄

Just mentioning a documentation bug; I'm not volunteering.

**Comment by mschrage** [comment]
Either way, thanks for reporting. I'll fix this right now.
