### ISSUE TITLE
Add documentation for users installing via `brew`

### ISSUE THREAD

**Issue by clonezone** [withfig/fig#1280]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [ ] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:

The documentation is completely lacking.  If you install via `brew install fig`, then run `fig --help`, you’re pretty much at a loss as to what's supposed to happen.

For something that interacts with the command-line, the idea that you need to run an app first is not at all clear.

The main docs at https://fig.io/docs are all about extending Fig, without anything about basic usage.

### Environment

```bash
Not applicable.
```

**Comment by mschrage** [comment]
@clonezone thanks for reporting this. Where did you expect further documentation? 

The CLI help text is one location we definitely can add more information. Anywhere else? Also what type of information are you looking for?

**Comment by clonezone** [comment]
In `README.md` would be good.

If you install via Homebrew, you run the installation, then you’ve basically got the `fig` command, and, if you aren’t paying attention to messages that go by, don't realize that a GUI app has been installed. The docs should say to run the GUI app prior to attempting to use anything.

It would be helpful if the `fig` command would, on first run, if setup hasn’t happened, say something about setup being required first.

**Comment by mschrage** [comment]
> It would be helpful if the fig command would, on first run, if setup hasn’t happened, say something about setup being required first.

This makes a lot of sense. Will add in to the next release.
