### ISSUE TITLE
Fig attempts to modify dot files without asking permission first.

### ISSUE THREAD

**Issue by clonezone** [withfig/fig#1281]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [ ] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Issue Details

In my case, because I'm using zsh, it wrote to `~/.zshrc`. That did no good because I set `ZDOTDIR` to point elsewhere.

But nothing should attempt to modify a person's dot files without their permission first.

### Environment

```bash
Not applicable.
```

**Comment by mschrage** [comment]
Completely agree @clonezone. We have a new installation flow landing in an upcoming release that should address this.

**Comment by pilif** [comment]
Also, as I have my `.zshrc` synced via Dropbox but I don’t have fig installed in all machines, it should not unconditionally source its init code. 

Worse, when I edited .zshrc to add a check for the files existence, next time I installed fig on another machine where the file was synced to, the installer left .zshrc with broken syntax
