### ISSUE TITLE
Github not registering my contributions after using Fig

### ISSUE THREAD

**Issue by yuff1006** [withfig/fig#1287]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Ever since I installed fig, when I make commits and use git push, the GitHub page is not registering the commits displayed on that green lit up commit tree. It shows up on the repo pages but it won't show on the green lit up commit tree.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.56 (B421)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B421) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/yuffiehu/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/yuffiehu/.local/bin:/Users/yuffiehu/.fig/bin:/Users/yuffiehu/.local/bin:/Users/yuffiehu/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by fedeci** [comment]
This seems to be unrelated to Fig, I'd suggest you to check out https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile

**Comment by mschrage** [comment]
Hey @yuff1006! 

Can you run `fig _ local-state shell-integrations.enabled false` and then open a new terminal, make a commit and push to Github? This will turn off Fig and we will be able to see if the issue still occurs.

**Comment by yuff1006** [comment]
It might not have been fig but in the end, I found that the email that I was committing to git with was changed somehow and that happened after I installed fig. I have fixed it with git since. Thank you for your help!
