### ISSUE TITLE
Shell integration should not run on unsupported platforms

### ISSUE THREAD

**Issue by harjotgill** [withfig/fig#1289]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
I share my dotfiles across machines (macOS and Linux). It would be nice if the fig pre/post blocks could be enclosed in a conditional statement that runs only on Darwin architecture. Also, it would be better to use the `test` command to check for the presence of `fig` binary and `~/.local` path before exporting it. 

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/gillh/.asdf/shims:/Users/gillh/.asdf/bin:/Users/gillh/sw/bin:/Users/gillh/go/bin:/Users/gillh/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/opt/X11/bin:/Users/gillh/.local/bin:/Users/gillh/.fig/bin:/Users/gillh/.antigen/bundles/zsh-users/zsh-completions:/Users/gillh/.antigen/bundles/scriptingosx/mac-zsh-completions:/Users/gillh/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/gillh/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/Users/gillh/.antigen/bundles/zsh-users/zsh-autosuggestions
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/gillh
  - CLI Installed: true
  - Executable Location: /Users/gillh/.local/bin/fig
  - Current Window ID: 48/% (com.googlecode.iterm2)
  - Active Process: zsh (1000) - /dev/ttys001
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:41292991-9563-43E0-94B3-25B2D3D5087A
    - PATH=/Users/gillh/.asdf/shims:/Users/gillh/.asdf/bin:/Users/gillh/sw/bin:/Users/gillh/go/bin:/Users/gillh/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/opt/X11/bin:/Users/gillh/.local/bin:/Users/gillh/.fig/bin:/Users/gillh/.antigen/bundles/zsh-users/zsh-completions:/Users/gillh/.antigen/bundles/scriptingosx/mac-zsh-completions:/Users/gillh/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/gillh/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/Users/gillh/.antigen/bundles/zsh-users/zsh-autosuggestions
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @harjotgill! This totally makes sense. We are currently working on Fig for Linux (#34), so hopefully won't be an issue for too much longer.

**Comment by grant0417** [comment]
Our shell integrations and dotfiles do support cross-platform filtering now!
