### ISSUE TITLE
Archive fig-issues repo

### ISSUE THREAD

**Issue by Tyriar** [withfig/fig#129]
Doesn't seem like you want any interaction on https://github.com/withfig/fig-issues anymore. You can archive repos on GH in settings to make this more obvious and make the repo readonly:

![image](https://user-images.githubusercontent.com/2193314/121359836-bc2d8600-c8e8-11eb-8d94-e56df8d5ddc9.png)

**Comment by QuiiBz** [comment]
Thanks! Just archived the repo.
