### ISSUE TITLE
Why fig-darwin-universal process running even when I closed app?

### ISSUE THREAD

**Issue by MaxVynohradov** [withfig/fig#1290]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Issue Details

Hi! Awesome project.
But I just noticed that fig-darwin-universal process running even when I closed app.
Why does it work so? What does it do in background.
Not sure that it's okay
<img width="802" alt="Screenshot 2022-04-09 at 23 03 59" src="https://user-images.githubusercontent.com/13771219/162590021-2bcdb6c1-9287-4630-abc4-29b090111b93.png">
.

### Environment

```bash
MacBook Pro (16-inch, 2021)
Apple M1 Pro
```

**Comment by mschrage** [comment]
Hey @MaxVynohradov! Great question. This is a background agent that handles settings and dotfiles syncing.

We could probably change the behavior so that quitting the app also kills the daemon.

**Comment by MaxVynohradov** [comment]
Not sure that it's good that smth running even when I exit the program.  Dotfiles sync disabled.
For instance Figma runs in background to - but anyway will be nice to understand what Fig does.

**Comment by grant0417** [comment]
Going to close this as it was answered by Matt, but yes the process is the daemon which handles some background processes, you can quit it but running `launchctl stop <fig-daemon-name>` you can find the name by running `launchctl list | grep -i fig`
