### ISSUE TITLE
Integrate autocomplete with OpenAI Codex

### ISSUE THREAD

**Issue by harjotgill** [withfig/fig#1292]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
> Please include a detailed description of the feature (and an image or screen recording, if applicable)
E.g. see https://github.com/tom-doerr/zsh_codex

**Comment by grant0417** [comment]
Hey @harjotgill we do support codex via Fig AI and are looking to expand our offering there!

https://fig.io/user-manual/ai
