### ISSUE TITLE
Lock screen, no autocompletion

### ISSUE THREAD

**Issue by mv-stns** [withfig/fig#1299]
### Description:
> I've tried reloading since autocompletion didn't work. After that the Lock Screen Modal appears and nothing works to re-enable autocompletion

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/marcusvaitschulis
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: <unknown>
  - Active Process: <unknown>
  - Environment Variables:
    - TERM_SESSION_ID=w0t1p0:C20B6ACF-CF2D-4398-AC06-8C8B32BA98CE
    - PATH=/Users/marcusvaitschulis/.nvm/versions/node/v14.19.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin:/Users/marcusvaitschulis/.local/bin:/Users/marcusvaitschulis/.fig/bin:/Users/marcusvaitschulis/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/marcusvaitschulis/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:

</p>
</details>

**Comment by mschrage** [comment]
Hey @mv-stns! Sorry that Fig isn't working for you. 

Have you check out this [guide](https://fig.io/docs/support/secure-keyboard-input) on resolving issues related to secure keyboard entry?  ?

**Comment by mv-stns** [comment]
Yes, I've managed to solve it. 1Password 8 (Beta) was causing the issue. After closing it completely, everything worked fine. Thanks alot!
