### ISSUE TITLE
Unable to access settings after "something went wrong" error

### ISSUE THREAD

**Issue by andrerfcsantos** [withfig/fig#1301]
### Description:

I tried to login into fig. It asked for my work email to connect with my colleagues:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/6928620/162843087-29dcb961-652b-43bf-a5c2-c859b7305e11.png">

It sent an email with a code to insert. I inserted the code and apparently, nothing happened, so I decided to try the process again. It sent a second code to my email, which I also inserted into fig. But this time I got the "something went wrong" error (see print below). I restarted Fig, and every time I tried to access the settings, I kept getting this screen:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/6928620/162841375-899552cd-7212-42e5-9dea-915fda614b6e.png">

I was able to fix this by running `fig logout` in the terminal, but this flow should be improved. I still don't know what I did wrong exactly in the whole process - I was only following the instructions. And if the problem is with the login, it should be fixable in the UI directly and not using the CLI. Using the CLI worked because I assumed the problem was with the login and a logout would fix it, but it was a complete shot in the dark as I still don't know why the login failed exactly.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [Portuguese]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/andre/.rvm/gems/ruby-3.1.1/bin:/Users/andre/.rvm/gems/ruby-3.1.1@global/bin:/Users/andre/.rvm/rubies/ruby-3.1.1/bin:/Users/andre/.nvm/versions/node/v16.14.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/andre/.cargo/bin:/Users/andre/.local/bin:/Users/andre/.fig/bin:/Users/andre/.local/bin:/Users/andre/Library/Application Support/Coursier/bin:/Users/andre/.local/bin:/Users/andre/.rvm/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/andre
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 653/% (com.googlecode.iterm2)
  - Active Process: zsh (21249) - /dev/ttys002
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:4372C33B-D422-4A49-B30B-40146814BA29
    - PATH=/Users/andre/.rvm/gems/ruby-3.1.1/bin:/Users/andre/.rvm/gems/ruby-3.1.1@global/bin:/Users/andre/.rvm/rubies/ruby-3.1.1/bin:/Users/andre/.nvm/versions/node/v16.14.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/andre/.cargo/bin:/Users/andre/.local/bin:/Users/andre/.fig/bin:/Users/andre/.local/bin:/Users/andre/Library/Application Support/Coursier/bin:/Users/andre/.local/bin:/Users/andre/.rvm/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @andrerfcsantos! Thanks so much for reporting this. I'm really sorry you run into this issue. 

We will investigate this tomorrow.

**Comment by mschrage** [comment]
@andrerfcsantos can you let me know if this issue occurs again? If so, let's jump on a call and debug together.

**Comment by andrerfcsantos** [comment]
@mschrage The issue still happens. However, I think I know what might have caused it.

When I signed up with Fig, I used my personal email. I installed Fig and I used it for a few weeks. I don't remember logging in at any time during this period. But on the day I opened this issue, I think the login screen appeared when I tried to access the "Settings" menu. Since the wording in the screen was to insert "my work email" and not "the email you have associated with fig" or something, I didn't see this as a login screen and more as a screen to find colleagues from my work email. But I don't think I've associated my work email with Fig at any time. I understand now that it was a login screen and I probably shouldn't put my work email there, but the email I registered with Fig, which was my personal email, and not the work one. The login worked when I put my personal email there, so I assume this was the issue?

The steps to reproduce are then something like:

1. Make sure you are logged out of Fig, running `fig logout` if necessary.
2. Try accessing the Fig "Settings" from the Fig icon in the taskbar.
3. In the screen that appears asking for the login, insert an email that is not associated with Fig.
4. Fig will tell you that it sent an email with the code and will ask you to put that code
5. Check your email and see that the code is there.
6. Copy/paste the code to the Fig interface.
7. Get the "Something went wrong" screen

What I think Fig should do differently here:

1. Make it clear that you have to log in with the email you gave Fig when accessing the settings. The wording "sign in with your work email" is confusing because one might be tempted to put the work email there, even if it is not the one they have with Fig.
2. The wording "to connect with your colleagues" makes this not sound like a login in screen, but one of those screens where you give your email or your socials to see which friends/colleagues also use Fig.
3. If the email a user puts there is not registered with Fig, why send a login code if the whole process is going to fail?
4. If the problem is the user not having that email registered with Fig, you can say that in the error message after the user puts the login code, instead of a generic "something went wrong" message.

If you still think a call is necessary after this information, I can help you debug this.

**Comment by Christopher-Hayes** [comment]
I just had this issue as well. It randomly asked me to log in when I tried to access the settings.

It would help if there was a message _why_ I suddenly now need to log in. Seemed weird that I was using Fig, updating the settings and then suddenly using the settings are gated by a login. (Logging in without an email would not work, probably because I put in my email at one point).

As @andrerfcsantos warned about, I had put in my work email instead of my personal email. I can't remember if I put in my personal email or if Fig grabbed it from GitHub. Using the wrong email just returns you back to the sign-on, so an error message could help there. I also agree on point 2, if the email is the system it _is_ smart not to tell the user for abuse reasons; however, don't send the email because it made me think I was entering the correct email.

So, fully agree on all 4 of André's proposals. Btw, André I couldn't help noticing you like Exercism, F1, and OW. 👍👍👍 
 from me.

**Comment by mschrage** [comment]
@Christopher-Hayes @andrerfcsantos this was related to an issue with our refresh tokens expiring prematurely. We believe we have pushed a fix. Please let me know if you run into this issue again.
