### ISSUE TITLE
Autocomplete is showing a very narrow list

### ISSUE THREAD

**Issue by dsnovaes** [withfig/fig#1302]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Autocomplete feature is showing a very narrow list.. on Terminal and VS Code, zsh or bash...

<img width="388" alt="image" src="https://user-images.githubusercontent.com/67075160/162869620-e2b22bd0-7c06-4737-b55b-05d51e0dfc10.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [U.S. International – PC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/diegonovaes/.local/bin:/Users/diegonovaes/.fig/bin:/Users/diegonovaes/.local/bin:/Users/diegonovaes/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/diegonovaes
  - CLI Installed: true
  - Executable Location: /Users/diegonovaes/.local/bin/fig
  - Current Window ID: 3901/% (com.apple.Terminal)
  - Active Process: zsh (94781) - /dev/ttys006
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=31C04DB7-BF14-4B51-904B-CE202FF024D9
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/diegonovaes/.local/bin:/Users/diegonovaes/.fig/bin:/Users/diegonovaes/.local/bin:/Users/diegonovaes/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @dsnovaes my guess is that somehow your settings got misconfigured. 

Try running `fig settings autocomplete.width --delete` to restore the default.

**Comment by dsnovaes** [comment]
@mschrage nailed it! restoring the default settings made it work perfectly again
