### ISSUE TITLE
unix socket

### ISSUE THREAD

**Issue by intersides** [withfig/fig#1304]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.56 (B421)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B421) [Swiss French] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/marco/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @intersides! Can you elaborate on what isn't working? I don't have much to go on from this.

Have you tried running `fig doctor`?

**Comment by mschrage** [comment]
Check out the workaround here: #492 

This should be fixed in the next updated :)

**Comment by kn0wn** [comment]
Hey @mschrage, I'm still having this issue and the workaround did not work, what do you need from me to help with debugging?

**Comment by mschrage** [comment]
Hey @kn0wn! I linked the wrong issue. I meant #1140.

Here is the workaround:
> sudo mkdir /var/tmp/fig/$(whoami)
> sudo chown $(whoami): /var/tmp/fig/$(whoami)
