### ISSUE TITLE
Requested but did not find extension point

### ISSUE THREAD

**Issue by smlombardi** [withfig/fig#1306]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Lately the first time I start terminal I see this
<img width="850" alt="st016lo — st016lo@US-ST016LO-MLT — ~ — zsh (figterm) ▸ zsh-20220412_084338@2x" src="https://user-images.githubusercontent.com/835148/162965165-ee68f627-9732-4776-b6be-53e494546711.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.56 (B421)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B421) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/st016lo/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @smlombardi! Hmm that's strange. Fig doesn't use watchOS or Xcode.IDEKit. Do you do iOS development? Is it possible this logging is coming from somewhere else?
