### ISSUE TITLE
Issue with iTerm (hotkey window, term window forced to stay on top)

### ISSUE THREAD

**Issue by darrenburns** [withfig/fig#131]
### Description:
Fig is appearing behind my terminal window.

I have iTerm configured to open when I press `Option + Space` (hotkey window feature).

iTerm is configured to stay in front of other windows:

![](https://user-images.githubusercontent.com/5740731/121542958-75cb4a80-ca00-11eb-873c-2165ca0bb96e.png)

Here's what it looks like in practice:

![image](https://user-images.githubusercontent.com/5740731/121542647-3997ea00-ca00-11eb-9bd2-6775166cdde4.png)

Is there some way I can force the z-ordering such that Fig appears on top? I'd like for my terminal window to remain floating, but for Fig to have priority and always appear on top of it.

### Details:
|macOS|Fig|Shell|
|----|----|----|
|10.15.7|Version 1.0.42 (B207)|/usr/local/bin/fish|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.42 (B207) [Debug] 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/darrenburns/.fig/bin/fig
Accessibility: true
Number of specs: 107
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/darrenburns/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/darrenburns/.pyenv/shims:/Users/darrenburns/.poetry/bin:/Users/darrenburns/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/fish/3.1.2/bin/fish (70919) - ttys004
Current working directory: /Users/darrenburns/Code/ward
Current window identifier: 501/389098967-8203-4083-AC72-17A07CBBBEA7% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mattschrage** [comment]
Hey @darrenburns! Thanks so much for creating this issue.

A few other people have mentioned this #19. I am looking into a fix.

We've found a workaround you can use for the time being. Check out this [post](https://forum.withfig.com/t/iterm2-make-autocomplete-work-in-hotkey-visor-floating-quake-mode-terminal/61/2) on the forum.


PS. You seem to have the "Force Popup to Appear" setting turned on. I would recommend disabling this as it is just meant to be used when debugging. (The option to toggle it off can be found under the Developer menu).

<img width="503" alt="Screen Shot 2021-06-10 at 12 57 54 PM" src="https://user-images.githubusercontent.com/3155109/121589159-9b018e00-c9eb-11eb-8cbf-15043c28ea2e.png">

**Comment by HSalaila** [comment]
The workaround mentioned in #135 does not work when the window is in floating mode. See also [Google Drive Video](https://drive.google.com/file/d/1tPjoU6xytRRNHiQNrtS9PTHg6gw0Dz15/view?usp=sharing)

**Comment by Nutlope** [comment]
Hey @mschrage, can you check out @HSalaila's issue? It seems like the workaround isn't working for him.

**Comment by aSapien** [comment]
Yep, same here. The Fig suggestions pane appears behind the hotkey floating window

**Comment by mschrage** [comment]
I will investigate the floating window issue further this week!

**Comment by mschrage** [comment]
This should be fixed as of v1.0.49.

**Comment by manishprivet** [comment]
This issue seems to be still there for Floating Windows

iTerm2: Build 3.4.19
MacOS: 13.2.1

![image](https://user-images.githubusercontent.com/54291836/223350776-9d380046-1227-420f-8f5e-b3291838e80c.png)

The workaround option mentioned above also seems to be gone now @mschrage
