### ISSUE TITLE
Internationalize Fig app user interface

### ISSUE THREAD

**Issue by LanYunDev** [withfig/fig#1311]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### 描述：>请附上对该功能的详细说明（以及图像或屏幕录制，如果适用）
There are many programmers in China, if this program supports Simplified Chinese, there will be more promoters and users.
Thanks to the developer for listening to a Chinese programmer.
Thank you!

**Comment by mschrage** [comment]
Hey @LanYunDev! Thanks for this request. We definitely want Fig to work for international/non-english speaking users. 🌏

When you talk about adding support for Simplified Chinese, are you referring to the completions specs: eg. the description for the "git commit" subcommand. Or something else?

**Comment by LanYunDev** [comment]
It mainly refers to the FIg software interface. It is convenient for users to view or modify the setting options. But if the future can support the description of the command, I believe Fig will receive a lot of welcome and support!
<img width="830" alt="image" src="https://user-images.githubusercontent.com/95263282/163332576-07bead7f-0294-40af-b83f-f4c5ea5c66ff.png">

**Comment by cycle2zhou** [comment]
<img width="419" alt="image" src="https://user-images.githubusercontent.com/33155330/221123102-9d67b546-d22a-4ae4-b437-bddad7a261cb.png">
It's better to support internationalization as well
