### ISSUE TITLE
unable to view autocomplete when iterm is opened in full/maximized window screen

### ISSUE THREAD

**Issue by vivekVells** [withfig/fig#1313]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Context: using Dual Monitor setup

Replication Steps:
- With fig installed & integrated with iterm, open iterm in "Full screen" -> type any autocomplete word

Issue: The autocomplete is not shown inline in the iterm; but it pops up on my another monitor screen

Note: Issue is not happening when iterm is not in "Full screen" maximized window view

(attaching video & screenshot for reference)

https://user-images.githubusercontent.com/25471383/163240073-a4ec9b10-5d86-44f0-80f9-5663e84fb405.mov

<img width="301" alt="Screen Shot 2022-04-13 at 12 46 03 PM" src="https://user-images.githubusercontent.com/25471383/163240092-a613c949-fcf1-4d61-ae35-8f0924bb1dfd.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.6.1 (20G224)|1.0.56|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/vsurulimuthu/.pyenv/bin:/Users/vsurulimuthu/.nvm/versions/node/v12.22.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/vsurulimuthu/.local/bin:/Users/vsurulimuthu/.fig/bin:/Users/vsurulimuthu/.local/bin:/Applications/apache-maven-3.6.1/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 32 GB
## OS Info:
  - macOS 11.6.1 (20G224)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/vsurulimuthu
  - CLI Installed: true
  - Executable Location: /Users/vsurulimuthu/.local/bin/fig
  - Current Window ID: 2981/% (com.googlecode.iterm2)
  - Active Process: bash (15526) - /dev/ttys006
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=w0t0p0:DC16C69B-11A3-4F9B-BD32-B4B2A5885A59
    - PATH=/Users/vsurulimuthu/.pyenv/bin:/Users/vsurulimuthu/.nvm/versions/node/v12.22.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/vsurulimuthu/.local/bin:/Users/vsurulimuthu/.fig/bin:/Users/vsurulimuthu/.local/bin:/Applications/apache-maven-3.6.1/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

P.S.: just want to say, thank you to the folks for creating fig; its super cool & really liked using it

**Comment by mschrage** [comment]
Hey @vivekVells! Thanks so much for reporting this. It is a regression that slipped in with the last update. #1229 

It should be fixed in the next release. You can try it out now by running `fig settings app.beta true`. 

I will close this issue for now, but please let me know if the problem persists after updating!
