### ISSUE TITLE
Fig it's not working at all

### ISSUE THREAD

**Issue by m-alama** [withfig/fig#1314]
### Description:
it's simply not working like it's not installed

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.1.0 (21C52)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/sbin:/usr/local/bin:/Users/mohammedalama/.yarn/bin:/Users/mohammedalama/.config/yarn/global/node_modules/.bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/sqlite/bin:/Users/mohammedalama/Library/Python/3.9/bin:/Users/mohammedalama/Library/Python/3.8/bin:/Users/mohammedalama/Library/Python/2.7/bin:/usr/local/go/bin:/usr/local/bin/python3:/usr/local/opt/ruby/bin:/usr/local/opt/php@8.0/bin:/Users/mohammedalama/.composer/vendor/bin:/Users/mohammedalama/.npm-global/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/mohammedalama/.fig/bin:/Users/mohammedalama/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: 
  - Cores: 10
  - Memory: 16 GB
## OS Info:
  - macOS 12.1.0 (21C52)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/mohammedalama/Code/Spryker/robot-tests
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 19343/% (com.microsoft.VSCode)
  - Active Process: zsh (55226) - /dev/ttys001
  - Environment Variables:
    - PATH=/usr/local/sbin:/usr/local/bin:/Users/mohammedalama/.yarn/bin:/Users/mohammedalama/.config/yarn/global/node_modules/.bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/sqlite/bin:/Users/mohammedalama/Library/Python/3.9/bin:/Users/mohammedalama/Library/Python/3.8/bin:/Users/mohammedalama/Library/Python/2.7/bin:/usr/local/go/bin:/usr/local/bin/python3:/usr/local/opt/ruby/bin:/usr/local/opt/php@8.0/bin:/Users/mohammedalama/.composer/vendor/bin:/Users/mohammedalama/.npm-global/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/mohammedalama/.fig/bin:/Users/mohammedalama/.local/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=7C0B4393-436B-4775-8AD2-D28451B91931
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by mschrage** [comment]
Hey @m-alama! I'm so sorry to hear that Fig isn't working for you.

Can you run `fig doctor --verbose` and share the output here?

**Comment by m-alama** [comment]
Here is it

<img width="1419" alt="Screen Shot 2022-04-14 at 8 04 17 AM" src="https://user-images.githubusercontent.com/97005260/163323828-c65ae470-aba6-4af5-814f-1fa0003a617f.png">

**Comment by mschrage** [comment]
Hmm @m-alama that's confusing...

What prompt are you using? Can you share you zshrc file here?

Can you also run `fig debug autocomplete-window on`. A red box should appear, can you go to the "Console" tab and then take a screenshot.

**Comment by m-alama** [comment]
I have run `fig debug autocomplete-window on` this is what I got

<img width="662" alt="Screen Shot 2022-04-14 at 8 21 30 AM" src="https://user-images.githubusercontent.com/97005260/163325942-0662df46-32e5-4e25-bc97-86a51416f31f.png">
 
start of my zshrc
<img width="1419" alt="Screen Shot 2022-04-14 at 8 24 44 AM" src="https://user-images.githubusercontent.com/97005260/163326381-ea859cf8-f791-471c-95bf-c0a7a18f4ceb.png">

end of my zshrc
<img width="1419" alt="Screen Shot 2022-04-14 at 8 26 50 AM" src="https://user-images.githubusercontent.com/97005260/163326556-054c61ee-5898-4e2b-a737-cc4cdf785070.png">

**Comment by m-alama** [comment]
what do you mean by the "Console" tab ..?

**Comment by SeparateRecords** [comment]
If you right click the popup (it's very hard because it's only 1px wide), you'll see two options - reload, and inspect. Click inspect, then go to the console tab 🙂

**Comment by m-alama** [comment]
here is it
<img width="1031" alt="Screen Shot 2022-04-14 at 8 57 37 AM" src="https://user-images.githubusercontent.com/97005260/163331045-de5d7728-1c6e-4693-b368-9867fdb56148.png">

**Comment by mschrage** [comment]
Hey @m-alama! Are you using a VPN? It seems like some JavaScript modules that need to be loaded are missing.

**Comment by m-alama** [comment]
No, I'm not

**Comment by mschrage** [comment]
Can you try reloading the web view from the inspector by pressing command + R?

**Comment by m-alama** [comment]
This is the results
![Screen Shot 2022-04-15 at 8 39 30 PM](https://user-images.githubusercontent.com/97005260/163608512-da32a383-0f03-495c-849e-00855a8e07f0.png)
