### ISSUE TITLE
ZSH precommand modifiers are not ignored

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1317]
See zshmisc(1) for more details (under heading "PRECOMMAND MODIFIERS")

These are "precommand modifiers" that affect the way the command is parsed and executed. These should actually be ignored by the parser. We can either build these into the parser to emulate the shell's behavior, or create some very simple completion specs for them `{ name: "...", args: { isCommand: true } }`

- `-`
- `nocorrect`
- `noglob`

Interestingly, `builtin` and `command` are precommand modifiers, but they also have flags and exist in fish and zsh, so it makes sense to have them in https://github.com/withfig/autocomplete instead of built in to the parser.

**Comment by mschrage** [comment]
Hey @SeparateRecords! It seems like creating completion specs for these shell builtins is the easiest solution. Can you take lead on this?
