### ISSUE TITLE
Autocompletion stopped working - Restart of App also doesn't work

### ISSUE THREAD

**Issue by crebuh** [withfig/fig#1319]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hi, today out of the sudden fig stopped working. No autocompletion in the terminal. I also can not start the application so that it is shown in the menu bar. Very weird. But running fig doctor, tells me that everything is fine.

Anybody else having similar issues?

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/crebuh/.nvm/versions/node/v17.8.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/crebuh/.local/bin:/Users/crebuh/.fig/bin:/Users/crebuh/.local/bin:/Users/crebuh/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/crebuh
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 200366/% (com.googlecode.iterm2)
  - Active Process: zsh (85940) - /dev/ttys001
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:48A95AB9-14C0-4A70-8A7F-97AB32FAC451
    - PATH=/Users/crebuh/.nvm/versions/node/v17.8.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/crebuh/.local/bin:/Users/crebuh/.fig/bin:/Users/crebuh/.local/bin:/Users/crebuh/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by mschrage** [comment]
Hey @crebuh! Sorry to hear that Fig stopped working for you...

If you run `fig` does a window appear?

Can you run `fig debug autocomplete-window`, then right click on the red box and finally press "Inspect Elements"?

This will bring you into the Web Inspector. If you can take a screenshot of the console tab, that would be super helpful! ❤️

----
PS. Also are you working in terminal application? Could be related to #1229

**Comment by crebuh** [comment]
@mschrage 

It's weird, after I updated to macOS Monterey 12.3.1 + rebooting everything was working again 😅. I will reopen this one if this happens again.
