### ISSUE TITLE
Despite being connected to the internet, autocomplete won't work. 

### ISSUE THREAD

**Issue by nikisaku** [withfig/fig#1320]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Hi, pretty much what's in the title.
If I type for example
`> fig `
I see for a split second that autocomplete tries to work, but it disappears instantly.
Info from fig:
<img width="512" alt="Screenshot 2022-04-14 at 23 23 37" src="https://user-images.githubusercontent.com/10388916/163479375-da9a1d65-2b2c-48b0-9854-1af8a0c92945.png">
Running fig doctor didn't help.
I tried updating fig, restarting it and rebooting my machine, none of which helped.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [Polish]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 188
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/opt/curl/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/nikisaku/.local/bin:/Users/nikisaku/.fig/bin:/Users/nikisaku/.local/bin:/Users/nikisaku/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir8,1
  - Chip: 
  - Cores: 2
  - Memory: 8 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/nikisaku
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 46/% (com.googlecode.iterm2)
  - Active Process: zsh (562) - not a tty
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:4E1B66F4-332B-4BDC-A188-58A9A5BE3E88
    - PATH=/usr/local/opt/curl/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/nikisaku/.local/bin:/Users/nikisaku/.fig/bin:/Users/nikisaku/.local/bin:/Users/nikisaku/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @nikisaku! Thanks so much for reporting this. Does this behavior only occur when attempting to load completions for "fig" or does it happen for all CLI tools?

**Comment by mschrage** [comment]
This might be worth poking around at @fedeci - maybe related to versioned specs? Idk.

**Comment by nikisaku** [comment]
Thank you for reply, @mschrage!
All CLI tools won't autocomplete, but only "fig" blinked that autocomplete field briefly.
It occurs only on that one MacBook.

**Comment by mschrage** [comment]
Can you run `fig debug autocomplete-window`? You should see a red box appear, right-click it and then press “Inspect Elements”.

This will open the Safari web inspector. Can you take a screenshot of the “console” tab?

**Comment by nikisaku** [comment]
Sure, here:
![image](https://user-images.githubusercontent.com/10388916/163644518-98c0e057-0158-4953-85ba-34389abe4abb.png)

**Comment by fedeci** [comment]
@nikisaku I thing the problem was related with the `fig` spec not being loaded correctly. Is it still not working? The `fig` spec is now fixed.

**Comment by nikisaku** [comment]
@fedeci, I updated fig on my personal machine, rebooted it, and now it's working like a charm. Thank you very much!
