### ISSUE TITLE
Autocompletion won't work after the last update

### ISSUE THREAD

**Issue by joerg2503** [withfig/fig#1322]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

after the last update fig don't work anymore.
no autocomplete suggestions where show.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.56|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B436) [German]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin/:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/joerg/.fig/bin:/Users/joerg/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/joerg
  - CLI Installed: true
  - Executable Location: /Users/joerg/.fig/bin/fig
  - Current Window ID: 164/% (com.googlecode.iterm2)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=w1t0p0:E941B162-813C-4BD5-92ED-7A4E1282256F
    - PATH=/usr/local/bin/:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/joerg/.fig/bin:/Users/joerg/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by enesdindas** [comment]
can you try running `fig debug accessibility refresh` in your terminal pls ?

**Comment by joerg2503** [comment]
same problem :(

**Comment by joerg2503** [comment]
i have also reinstalled fig but without success

**Comment by ramet** [comment]
same problem

**Comment by robrichardson13** [comment]
same problem for me

**Comment by joerg2503** [comment]
i have changed my default shell from bash to zsh and fig works again.

**Comment by grant0417** [comment]
Hey @joerg2503 @robrichardson13 @ramet @enesdindas, are you able to get on a debugging call? https://calendly.com/withfig/debugging-not-linking

In the meantime can you provide the following:

- The output of `ls -al $HOME`
- The contents of `~/.bashrc` and `~/.bash_profile`
- The output of `ls ~/.fig/shell/`
- And run `fig doctor --verbose`
- And output of `fig init bash post` and `fig init bash pre`

**Comment by ramet** [comment]
I am not available for a debugging call this week.

For information, with zsh it works perfectly, but I need to keep bash shell.

I fix the issue by sharing the same configuration for both .bash_profile and .bashrc.

I used to set my .bashrc empty (except the 2 lines added by Fig for pre and post block). All my configuration was defined in .bash_profile and Fig was not connected to my shell since the last update.
So I move my configuration in .bashrc and add the following lines in my .bash_profile :
```sh
# Fig pre block. Keep at the top of this file.
. "$HOME/.fig/shell/bashrc.pre.bash"

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

# Fig post block. Keep at the bottom of this file.
. "$HOME/.fig/shell/bashrc.post.bash"
```

Fig is now able to connect and works perfectly.

**Comment by grant0417** [comment]
This is likely an issues that was fixed back in April, Fig is a lot more stable now and less likely to have issues like this!
