### ISSUE TITLE
fig autocomplete not popping up at all

### ISSUE THREAD

**Issue by anoushk1234** [withfig/fig#1323]
### Description:
> tried fig doctor, tried restart and updating, doctor shows everything is good and restart does nothing so dont know whats wrong

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.1.0 (21C52)|1.0.56|/opt/homebrew/Cellar/bash/5.1.16/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B436) [ABC – India]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/anoushkkharangate/.local/share/solana/install/active_release/bin:/Users/anoushkkharangate/.cargo/bin:/Users/anoushkkharangate/.pyenv/shims:/Users/anoushkkharangate/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/anoushkkharangate/.fig/bin:/Users/anoushkkharangate/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.1.0 (21C52)
## Environment:
  - User Shell: /opt/homebrew/bin/bash
  - Current Directory: /Users/anoushkkharangate/.fig
  - CLI Installed: true
  - Executable Location: /Users/anoushkkharangate/.fig/bin/fig
  - Current Window ID: 1029/% (com.googlecode.iterm2)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - TERM_SESSION_ID=w0t0p0:8EF1CBBE-2B15-442B-AF05-D6085C8487E4
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - TERM=xterm-256color
    - PATH=/Users/anoushkkharangate/.local/share/solana/install/active_release/bin:/Users/anoushkkharangate/.cargo/bin:/Users/anoushkkharangate/.pyenv/shims:/Users/anoushkkharangate/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/anoushkkharangate/.fig/bin:/Users/anoushkkharangate/.local/bin
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by grant0417** [comment]
Hey @anoushk1234, are you able to get on a debugging call? https://calendly.com/withfig/debugging-not-linking

In the meantime can you provide the following:

- The output of `ls -al $HOME`
- The contents of `~/.bashrc` and `~/.bash_profile`
- The output of `ls ~/.fig/shell/`
- And run `fig doctor --verbose`
- And output of `fig init bash post` and `fig init bash pre`

**Comment by anoushk1234** [comment]
Hey @grant0417 after updating fig to the latest release it seems to work now, a suggestion i have is to make it easier to revert to older versions of fig since this issue came up when it updated to a version of fig that had this bug
