### ISSUE TITLE
Not linked to terminal session

### ISSUE THREAD

**Issue by Phat0M** [withfig/fig#1325]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.0 (21D49)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B436) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/share/npm/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/phatom/.fig/bin:/Users/phatom/.local/bin:/Users/phatom/Documents/sdk/flutter/bin:/Users/phatom/.pub-cache/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.0 (21D49)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/phatom
  - CLI Installed: true
  - Executable Location: /Users/phatom/.fig/bin/fig
  - Current Window ID: 514/% (com.apple.Terminal)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=6FC3276F-22C4-4AC3-BD83-D6FDBB764DFB
    - PATH=/usr/local/share/npm/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/phatom/.fig/bin:/Users/phatom/.local/bin:/Users/phatom/Documents/sdk/flutter/bin:/Users/phatom/.pub-cache/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
<img width="431" alt="Снимок экрана 2022-04-15 в 23 53 57" src="https://user-images.githubusercontent.com/52571416/163631005-4833ea12-cab7-44fa-b154-b8d48cf285ba.png">

  - Docker: false

</p>
</details>

**Comment by ramet** [comment]
same issue for me with last update and iTerm. Completion is no longer working. Need to launch 'figterm' by hand...

**Comment by grant0417** [comment]
Hey @Phat0M and @ramet, are you able to get on a debugging call? https://calendly.com/withfig/debugging-not-linking

In the meantime can you provide the following:

- The output of `ls -al $HOME`
- The contents of `~/.bashrc` and `~/.bash_profile`
- The output of `ls ~/.fig/shell/`
- And run `fig doctor --verbose`
- And output of `fig init bash post` and `fig init bash pre`

**Comment by DefiCake** [comment]
I don't know if this might be the issue or related in some form but some problems found as well when trying to run git commit with signed messages that rely on gpg. Caching is not working, so everytime I try to sign a commit I 'm getting prompted with the PIN to unlock the keys and the passphrase to unlock SSH.

**Comment by grant0417** [comment]
This issue was resolved back in April, also with gpg caching we run commands in the background for fig so it is possible that these invalidate your gpg cache.
