### ISSUE TITLE
Fig Not Working - No such file or directory (os error 2)

### ISSUE THREAD

**Issue by robrichardson13** [withfig/fig#1327]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
Fig is not working at all after the latest update.

When running `fig source` as suggested in this article: https://fig.io/support/troubleshooting/debug-fig

It returns this error:
```
~ $ fig source
No such file or directory (os error 2)
```

![image](https://user-images.githubusercontent.com/9492530/163681142-9bfdb494-9959-4b95-ad0e-ff8fcd7e58f1.png)

### Environment

```bash
~ $ fig diagnostic
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B436) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 1
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/robertrichardson/go/bin:/Users/robertrichardson/.nvm/versions/node/v12.22.5/bin:/Users/robertrichardson/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/robertrichardson/.fig/bin:/Users/robertrichardson/.local/bin:/Users/robertrichardson/.composer/vendor/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 32 GB
## OS Info:
  - macOS 11.6.0 (20G165)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/robertrichardson
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 2894/% (com.apple.Terminal)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=E5B992D0-13C3-4DC8-A102-024F74821065
    - PATH=/Users/robertrichardson/go/bin:/Users/robertrichardson/.nvm/versions/node/v12.22.5/bin:/Users/robertrichardson/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/robertrichardson/.fig/bin:/Users/robertrichardson/.local/bin:/Users/robertrichardson/.composer/vendor/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true
```

**Comment by mschrage** [comment]
Hey @robrichardson13! Thanks for reporting this. Can you run `fig doctor --verbose` and share the output with me?

I think that updating to the latest version may also resolve your issue (we pushed a hotfix).

**Comment by robrichardson13** [comment]
Hi @mschrage , I just updated to the newest version and it did resolve the problem! Thank you.

**Comment by mschrage** [comment]
Great to hear! Please let me know if run into any other issues @robrichardson13.

**Comment by StoneRen** [comment]
![iShot2022-07-07_00 47 46](https://user-images.githubusercontent.com/2187168/177602413-a3f9a407-2567-4f94-bbf8-029431d85372.jpg)
![iShot2022-07-07_00 49 27](https://user-images.githubusercontent.com/2187168/177602500-dc90c1fc-1d05-4749-a7e6-d0c02282e3e6.jpg)
