### ISSUE TITLE
Debugger ????

### ISSUE THREAD

**Issue by temrb** [withfig/fig#1328]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
<img width="187" alt="Screen Shot 2022-04-16 at 2 04 30 PM" src="https://user-images.githubusercontent.com/22056864/163688184-30bbd1f7-8c78-456d-9776-4f56fbd80d9b.png">

Autocomplete not working. Tried normal steps to fix.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.56 (B436)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B436) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/temurbakhridddinov/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: 205/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @temrb, are you able to get on a debugging call? https://calendly.com/withfig/debugging-not-linking

In the meantime can you provide the following:

- The output of `ls -al $HOME`
- The contents of `~/.bashrc` and `~/.bash_profile`
- The output of `ls ~/.fig/shell/`
- And run `fig doctor --verbose`
- And output of `fig init bash post` and `fig init bash pre`

**Comment by temrb** [comment]
I think this issue got solved through the recent update

**Comment by grant0417** [comment]
Sounds good!
