### ISSUE TITLE
Keyboard focus jumps to first panel when inserting text using Fig in `tmux` 

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#133]
If you're running into this issue, please share your `tmux.conf` file below!

**Comment by mattschrage** [comment]
> I briefly tried Fig and figured it is not quite ready for me. My setup is a tmux session via ssh from iTerm on a Mac to a home dev server running Ubuntu, with multiple tmux windows and panes on the Ubuntu server (I fully realise it must be not the most popular setup :)) The issue I ran into is when I submit a Fig-autocompleted command in a tmux pane, the command is not executed, and instead the cursor just jumps to a different tmux pane. But not 100% of time, sometimes it works, sometimes it does not.

**Comment by mattschrage** [comment]
When I hit enter with autocomplete `cd`, I get moved to another tmux window: 
![screen-2021-06-05@17-17-55](https://user-images.githubusercontent.com/3155109/121964938-1e3f1e80-cd21-11eb-88ba-28e57d413029.gif)

cc: @awinecki

**Comment by mattschrage** [comment]
<details>
<summary>
<code>tmux.conf</code>
</summary>
<pre>
set-option -g default-shell $SHELL

set -g status-left-length 50

set -g status-right "#(date '%b %d - %I:%M') "

set -g history-limit 20000

unbind C-b

set-option -g prefix C-s

bind -r C-s send-prefix

bind -n C-b command-prompt -kp key 'send %%%'

set-window-option -g mode-keys vi

set-window-option -g automatic-rename
bind r source-file ~/.tmux.conf ';' display-message "~/.tmux.conf reloaded"
bind C command-prompt -p "Name of new window: " "new-window -n '%%'"

bind - split-window -v -c '#{pane_current_path}'
bind '\' split-window -h -c '#{pane_current_path}'
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

bind -n S-Left resize-pane -L 5
bind -n S-Right resize-pane -R 5
bind -n S-Down resize-pane -D 5
bind -n S-Up resize-pane -U 5

bind c new-window -c '#{pane_current_path}'
set -g base-index 1

bind b break-pane -d

bind h split-window -h "htop"

bind C-j split-window -v "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

bind j command-prompt -p "join pane from: " "join-pane -h -s '%%'"

bind C-b send-keys 'tm && exit' 'C-m'

bind K run-shell 'tmux switch-client -n \; kill-session -t "$(tmux display-message -p "#S")" || tmux kill-session'

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection

set -g mouse on
show-options -g -s set-clipboard

set -g @continuum-restore 'on'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-copycat'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-open'

run '~/.tmux/plugins/tpm/tpm'

source-file ~/.fig/tmux
</pre>

</details>


> I don’t use other tmux tools, though I restore sessions with tmux-continuum.

**Comment by mattschrage** [comment]
<details>
<summary>
<code>tmux.conf</code>
</summary>
<pre>
# Desktop only settings

# Copy-paste integration
# set-option -g default-command "reattach-to-user-namespace -l bash"
# TODO: comment out these 2 lines for SERVER usage!!!
set -g default-shell $SHELL
set -g default-command "reattach-to-user-namespace -l ${SHELL}"

# Leave these 10 lines here (or expand); installation script will remove first 10 lines from the config!!!
##########################

# set -g utf8
# set-window-option -g utf8 on

# Prefix key -> CTRL+q
unbind C-b
set -g prefix C-q
bind C-q send-prefix
bind @ command-prompt -I "#W" "rename-window -- '%%'"

# Switching
bind "'" switch-client -l # prefix + '  - switch to `last` session

# Add truecolor support
# set-option -ga terminal-overrides ",xterm-256color:Tc"
# Default terminal is 256 colors
# set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

#bind -n C-\ run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys 'C-\\') || tmux select-pane -l"

# set scrollback history to 10000 (10k)
set -g history-limit 40000

# From tmux-sensible
set -g focus-events on
setw -g aggressive-resize on

# shorten command delay
set -sg escape-time 0

# reload ~/.tmux.conf using PREFIX r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# ----------------------
# Status Bar
# -----------------------
set-option -g status on                # turn the status bar on
# set -g status-utf8 on                  # set utf-8 for the status bar
set -g status-interval 5               # set update frequencey (default 15 seconds)
#set -g status-justify centre           # center window list for clarity
set-option -g status-position bottom    # position the status bar at top of screen

# visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on

# Mouse events
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
# bind-key -T copy-mode-vi v begin-selection
# bind-key -T copy-mode-vi y copy-pipe "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
# unbind -T copy-mode-vi Enter
# bind-key -T copy-mode-vi Enter copy-pipe "reattach-to-user-namespace pbcopy"

# Bind ']' to use pbpaste
bind ] run "reattach-to-user-namespace pbpaste | tmux load-buffer - && tmux paste-buffer"
# bind-key -n C-Tab next-window

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
  | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
is_fzf="ps -o state= -o comm= -t '#{pane_tty}' \
  | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?fzf$'"
bind -n C-h run "($is_vim && tmux send-keys C-h) || \
                 tmux select-pane -L"
bind -n C-j run "($is_vim && tmux send-keys C-j)  || \
                 ($is_fzf && tmux send-keys C-j) || \
                 tmux select-pane -D"
bind -n C-k run "($is_vim && tmux send-keys C-k) || \
                 ($is_fzf && tmux send-keys C-k)  || \
                 tmux select-pane -U"
bind -n C-l run "($is_vim && tmux send-keys C-l) || \
                 tmux select-pane -R"
# bind -n C-n run "($is_vim && tmux send-keys C-n) || \
#                  tmux next-window"
# bind -n C-p run "($is_vim && tmux send-keys C-p) || \
#                  tmux previous-window"

bind -n C-n run "tmux next-window"
bind -n C-p run "tmux previous-window"

bind -n C-x run "($is_vim && tmux send-keys C-x)"

# Session finder key bindings - see https://github.com/siadat/session-finder
#bind -n C-f neww       '~/.tmux/session-finder/session-finder.bash finder'


# #################
# #################
# ### THEME #######
# #################
# #################
###############################################################################
############# Date/Time values that can be displayed in the status line
###############################################################################

# $(echo $USER) - shows the current username
# %a --> Day of week (Mon)
# %A --> Day of week Expanded (Monday)

# %b --> Month (Jan)
# %d --> Day (31)
# %Y --> Year (2017)

# %D --> Month/Day/Year (12/31/2017)
# %v --> Day-Month-Year (31-Dec-2017)

# %r --> Hour:Min:Sec AM/PM (12:30:27 PM)
# %T --> 24 Hour:Min:Sec (16:30:27)
# %X --> Hour:Min:Sec (12:30:27)
# %R --> 24 Hour:Min (16:30)
# %H --> 24 Hour (16)
# %l --> Hour (12)
# %M --> Mins (30)
# %S --> Seconds (09)
# %p --> AM/PM (AM)


set -g status-bg default
set -g status-fg white

# ----------------------
# set some pretty colors
# ----------------------
# set pane colors - hilight the active pane
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour238

# colorize messages in the command line
set -g message-style fg=brightred,bg=default

# For a more complete list view: https://linux.die.net/man/3/strftime
# set color for status bar
set -g status-style fg=colour96,bg=default

# set window list colors - red for active and cyan for inactive
set -g window-status-style fg=colour241,bg=default
set -g window-status-format '#W'

set -g window-status-current-style fg=colour74,bg=default
set -g window-status-current-format '#W'

# show host name and IP address on left side of status bar
set -g status-left-length 70
set -g status-left "#[fg=colour74] ▸ #S #[bg=default]#[fg=colour241]⫍⫎  "
# ⫍⫎  ⩎ ⨅ ⟤ ⊑ ⊐ ⌗ ⎅ ⎡ ⎣⎤ ⬔ ‖ ‗ ⌇ ⦚⨒ ﹏〷✮ ꭍ

# show session name, window & pane number, date and time on right side of
# status bar
set -g status-right-length 120
set -g status-right "#{?window_zoomed_flag, 🔍 ,} #[fg=colour241]⫍⫎  #h ⫍⫎  %a %Y-%m-%d %H:%M ⫍⫎  #[fg=colour74]#{online_status} #{battery_percentage}"
set -g @online_icon "▲"
set -g @offline_icon "OFFLINE!"

# #################


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'awinecki/session-finder'

# Tmux-resurrect settings
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes 'ssh'
# set -g @resurrect-save-shell-history 'on'


# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
</pre>
</details>

**Comment by mschrage** [comment]
The underlying issue here has to do with how Fig insert's text into the terminal and how this interacts `with` tmux.

This will not occur with `zsh` since we insert using a ZLE widget. I think the long term fix here is bi-directional communication between figterm and the macOS app that allows us to insert directly using the pty. cc @sullivan-sean

**Comment by mschrage** [comment]
Closing as we know use `figterm` to handle text insertion.
