### ISSUE TITLE
Autocomplete not working in WebStorm and running fig doctor output Figterm socket: No file at path

### ISSUE THREAD

**Issue by rluvaton** [withfig/fig#1331]
### Description:

fig did not open the autocomplete in iTerm so I ran `fig doctor` but no output, so I quit fig and relaunch it, and it worked but when opening WebStorm the autocomplete in the terminal did not work (yesterday it worked)

running `fig doctor` in the WebStorm terminal output:
```
❯ fig doctor

✘ Figterm socket: No file at path /tmp/figterm-5752ccb4-543e-402f-aeba-c82f2bb3c438.socket


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B436) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: ./node_modules/.bin:/Users/me/.nvm/versions/node/v14.19.0/bin:/Users/me/.pyenv/shims:/Users/me/dev/open-source/v8/depot_tools:/Users/me/.asdf/shims:/Users/me/.asdf/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/Library/Apple/usr/bin:/Users/me/.sdkman/candidates/java/current/bin:/Users/me/.sdkman/candidates/gradle/current/bin:./node_modules/.bin:/Users/me/.nvm/versions/node/v14.19.0/bin:/Users/me/.pyenv/shims:/Users/me/dev/open-source/v8/depot_tools:/opt/homebrew/bin:/Users/me/.fig/bin:/Users/me/.local/bin:/Users/me/Library/Python/3.8/bin/:/opt/homebrew/opt/libpq/bin:/Users/me/.bin:/Users/me/Library/Python/3.8/bin/:/opt/homebrew/opt/libpq/bin:/Users/me/.bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/me/dev/work/
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 566/% (com.jetbrains.WebStorm)
  - Active Process: ??? (???) - ???
  - Installed via Brew: true
  - Environment Variables:
    - PATH=./node_modules/.bin:/Users/me/.nvm/versions/node/v14.19.0/bin:/Users/me/.pyenv/shims:/Users/me/dev/open-source/v8/depot_tools:/Users/me/.asdf/shims:/Users/me/.asdf/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/Library/Apple/usr/bin:/Users/me/.sdkman/candidates/java/current/bin:/Users/me/.sdkman/candidates/gradle/current/bin:./node_modules/.bin:/Users/me/.nvm/versions/node/v14.19.0/bin:/Users/me/.pyenv/shims:/Users/me/dev/open-source/v8/depot_tools:/opt/homebrew/bin:/Users/me/.fig/bin:/Users/me/.local/bin:/Users/me/Library/Python/3.8/bin/:/opt/homebrew/opt/libpq/bin:/Users/me/.bin:/Users/me/Library/Python/3.8/bin/:/opt/homebrew/opt/libpq/bin:/Users/me/.bin
    - FIG_PID=6187
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
    - TERM_SESSION_ID=5752ccb4-543e-402f-aeba-c82f2bb3c438
    - TERM=xterm-256color
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by mykhaliuk** [comment]
Guess it's linked to https://github.com/withfig/fig/issues/1088

**Comment by mykhaliuk** [comment]
Have the same symptoms.

| OS | Fig | Shell | Integration |
|---|---|---|---|
|macOS 12.4 (21F79)| 1.0.57 | fish | WS-221.5591.52 |

**Comment by dlinaressaab** [comment]
Try running _brew upgrade_ and then reinstall _fig brew reinstall --cask fig_.

After this, you need to configure fig again adding it as an input method. 

This worked for me.

**Comment by grant0417** [comment]
I believe this should be fixed now, please let us know if not and the issue can be reopened.
