### ISSUE TITLE
Conflict with `zsh-autosuggest`

### ISSUE THREAD

**Issue by KenWuqianghao** [withfig/fig#1334]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Issue Details

Popup only shows for an instant when I press the spacebar. 
https://user-images.githubusercontent.com/20444505/163882364-07575c0a-4d6c-4f37-aa82-5848ff0a4fc6.mov

https://user-images.githubusercontent.com/20444505/163886208-76ec8466-f113-4588-a2ac-c074e4e9d44f.mp4

<img width="1512" alt="Screen Shot 2022-04-18 at 23 42 33" src="https://user-images.githubusercontent.com/20444505/163882438-8bfc6c96-b417-446f-8e3b-0c0e8d8ac82f.png">

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B436) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/Caskroom/miniforge/base/condabin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/Users/kenwu/.cargo/bin:/Users/kenwu/.fig/bin:/Users/kenwu/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/kenwu
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 252/% (com.googlecode.iterm2)
  - Active Process: zsh (5871) - /dev/ttys001
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:19185BD9-F83C-4911-ABF8-BC5EC1574E3A
    - PATH=/opt/homebrew/Caskroom/miniforge/base/condabin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/Users/kenwu/.cargo/bin:/Users/kenwu/.fig/bin:/Users/kenwu/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=5871
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
Hey @KenWuqianghao! It looks like the `zsh-autocomplete` plugin that you are using conflicts with Fig's shell integrations.

If you disable `zsh-autocomplete`, Fig will work as expected. Please let me know if you need help figuring out how to disable `zsh-autocomplete` :)

**Comment by KenWuqianghao** [comment]
> Hey @KenWuqianghao! It looks like the `zsh-autocomplete` plugin that you are using conflicts with Fig's shell integrations.
> 
> If you disable `zsh-autocomplete`, Fig will work as expected. Please let me know if you need help figuring out how to disable `zsh-autocomplete` :)

Thank you, that solved the issue.
