### ISSUE TITLE
Unix socket does not exist when Fig is installed by multiple users

### ISSUE THREAD

**Issue by Asdougl** [withfig/fig#1336]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Getting error from fig doctor: ✘ Fig socket exists: No file at path /var/tmp/fig/cameron/fig.socket
<img width="563" alt="image" src="https://user-images.githubusercontent.com/25199427/163940804-6fee6232-cb86-4a1f-98a1-74c26f80589d.png">

Getting error inside of fig debugger: "Unix socket does not exist"
<img width="399" alt="image" src="https://user-images.githubusercontent.com/25199427/163940912-c197f2b9-b5d3-4ec1-be4b-d44a74b60729.png">

Important note, I previously installed fig on another user on this mac, and then tried to use it on this user, getting the above errors. Have tried re-installing fig and still no luck.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.1.0 (21C52)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.1.0 (21C52)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/cameron
  - CLI Installed: true
  - Executable Location: /Users/cameron/.fig/bin/fig
  - Current Window ID: <unknown>
  - Active Process: <unknown>
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=236CB967-A18F-4508-8707-1C83A4075B31
    - PATH=/Users/cameron/.nvm/versions/node/v16.13.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/cameron/.fig/bin:/Users/cameron/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=31364
## Integrations:

</p>
</details>

**Comment by mschrage** [comment]
The issue here is that when you run Fig on the other account it created the folder where the socket is stored. Now the application on this account is unable to create the socket. 

Check out the workaround in this issue #492 - I think this should resolve the problem for you. Let me know if that's not the case.

**Comment by mschrage** [comment]
@grant0417 can you add a `fig doctor` check for this?
