### ISSUE TITLE
Sourcing scripts for macs

### ISSUE THREAD

**Issue by georgefromohio** [withfig/fig#1338]
### Description:

The following line that's added to `.zshrc` during updates does not fire for certain setups and ends up throwing an error on new terminal window.

```bash
# Fig post block. Keep at the bottom of this file.
. "$HOME/.fig/shell/zshrc.post.zsh"
```

I have to manually replace it with

```bash
# Fig post block. Keep at the bottom of this file.
source "$HOME/.fig/shell/zshrc.post.zsh"
```
And then on the next update it keeps adding lines since it can't find the changed line.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.57 (B437)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B437) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/oommen.6/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (14150) - /dev/ttys005
Current terminal session: w0t1p0:340D5023-9C71-432E-927D-F2669D548A8C
Current working directory: /Volumes/Vault/Code/code.osu.edu/osg-ohioseagrant/framework
Current window identifier: 248/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @georgefromohio! Can you elaborate on the cases where it doesn't fire? 

I'd love to understand how your dotfiles are configured. Would you mind sharing your zshrc as well as any other relevant information?

**Comment by georgefromohio** [comment]
Okay... After much searching, I realized this is not a bug, please close or ignore this post. I had inherited an alias list that had an alias for "."... And that's why it didn't work... My bad!

**Comment by mschrage** [comment]
Ah! That's tricky. Thanks for letting us know @georgefromohio

**Comment by jachinfrancke** [comment]
Hi, I also have an alias `.` (and `..` and `...`) to traverse my directories quickly and stumbled upon the some issue. Thanks for the response, but I'm curious: what's the difference between them `source`-command and the `.`-command?

**Comment by georgefromohio** [comment]
From my understanding, for bash both can be used interchangeably. I've almost always used `source`, and that's why it took a while for me to figure out what was going on.

**Comment by mschrage** [comment]
Yeah, they are virtually identical. I think we may ultimately migrate back to using source to avoid edge cases like this.

**Comment by jachinfrancke** [comment]
Thanks for the heads up!
