### ISSUE TITLE
RubyMine still not supporting autocomplete

### ISSUE THREAD

**Issue by AdamLeMmon01** [withfig/fig#1344]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Still no autocomplete in Ruby Mine. Enabled the input method and restarted, but still no autocomplete in RubyMine.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B437) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 1
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/adamlemmon/.asdf/shims:/usr/local/Cellar/asdf/0.8.1/bin/../bin:/Users/adamlemmon/.nvm/versions/node/v14.18.3/bin:/Users/adamlemmon/google-cloud-sdk/bin:/usr/local/opt/asdf/bin:/Users/adamlemmon/Library/Python/2.7/bin:.:/Users/adamlemmon/Documents/tools/scripts/setdb/bin:/Users/adamlemmon/Documents/tools/scripts/switchto/bin:/Users/adamlemmon/Documents/tools/scripts/startlatestapp/bin:/Users/adamlemmon/Documents/tools/scripts/startapp/bin:/Users/adamlemmon/Documents/tools/scripts/pull/bin:/Users/adamlemmon/Documents/tools/scripts/jump_to/bin:/Users/adamlemmon/Documents/tools/scripts:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/adamlemmon/Documents/GitHub/spiff_rb/node_modules/.bin:/Users/adamlemmon/.fig/bin:/Users/adamlemmon/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 32 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/adamlemmon/Documents/GitHub/spiff_rb
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: ???
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - PATH=/Users/adamlemmon/.asdf/shims:/usr/local/Cellar/asdf/0.8.1/bin/../bin:/Users/adamlemmon/.nvm/versions/node/v14.18.3/bin:/Users/adamlemmon/google-cloud-sdk/bin:/usr/local/opt/asdf/bin:/Users/adamlemmon/Library/Python/2.7/bin:.:/Users/adamlemmon/Documents/tools/scripts/setdb/bin:/Users/adamlemmon/Documents/tools/scripts/switchto/bin:/Users/adamlemmon/Documents/tools/scripts/startlatestapp/bin:/Users/adamlemmon/Documents/tools/scripts/startapp/bin:/Users/adamlemmon/Documents/tools/scripts/pull/bin:/Users/adamlemmon/Documents/tools/scripts/jump_to/bin:/Users/adamlemmon/Documents/tools/scripts:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/adamlemmon/Documents/GitHub/spiff_rb/node_modules/.bin:/Users/adamlemmon/.fig/bin:/Users/adamlemmon/.local/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=afdf2199-00c5-4bc2-bb87-0de7039531ef
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=7879
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by AdamLeMmon01** [comment]
```
fig doctor --verbose
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ /Users/adamlemmon/.bashrc contains valid fig hooks
✔ /Users/adamlemmon/.profile contains valid fig hooks
✔ /Users/adamlemmon/.zshrc contains valid fig hooks
✔ /Users/adamlemmon/.zprofile contains valid fig hooks

Let's make sure Fig is running...
✔ Fig bin exists
✔ PATH contains ~/.local/bin and ~/.fig/bin
✔ Fig Integration
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Figterm socket
✔ Insertion lock does not exist
✔ PATH and PseudoTerminal PATH match
✔ Autocomplete dev mode
✔ Plugin dev mode

Let's check if your system is compatible...
✔ OS is supported

Let's check fig diagnostic...
✔ Installation script
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled
✘ Secure keyboard input disabled: Secure keyboard input is on
  Secure keyboard process is RubyMine - com.jetbrains.rubymine 

Let's check your terminal integrations...
✔ VSCode integration is enabled
✔ Input Method


Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!

```

**Comment by mschrage** [comment]
Hey @AdamLeMmon01. It looks like you have _Secure Keyboard Entry_ enabled. Check out [this guide](https://fig.io/docs/support/secure-keyboard-input) for tips on how to turn it off.

I will close this issue for now, but please let me know if you're having trouble disabling it.

**Comment by AdamLeMmon01** [comment]
I was able to disable the secure entry, but still no autocomplete in Jetbrains RubyMine

 fig doctor --verbose
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ /Users/adamlemmon/.bashrc contains valid fig hooks
✔ /Users/adamlemmon/.profile contains valid fig hooks
✔ /Users/adamlemmon/.zshrc contains valid fig hooks
✔ /Users/adamlemmon/.zprofile contains valid fig hooks

Let's make sure Fig is running...
✔ Fig bin exists
✔ PATH contains ~/.local/bin and ~/.fig/bin
✔ Fig Integration
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Figterm socket
✔ Insertion lock does not exist
✔ PATH and PseudoTerminal PATH match
✔ Autocomplete dev mode
✔ Plugin dev mode

Let's check if your system is compatible...
✔ OS is supported

Let's check fig diagnostic...
✔ Installation script
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled
✔ Secure keyboard input disabled

Let's check your terminal integrations...
✔ VSCode integration is enabled
✔ Input Method


Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!

**Comment by mschrage** [comment]
Looks like I fat fingered the bundle identifier for RubyMine #1345 

Will be fixed when we push the next release (in a couple of days).

**Comment by AdamLeMmon01** [comment]
Thanks. I appreciate the quick turnaround
