### ISSUE TITLE
Fig does not appear in RubyMine

### ISSUE THREAD

**Issue by CoderMiguel** [withfig/fig#1345]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I have stalled Fig from the website / download, then ran fig install --input-method enabled permissions and then restarted my machine, and the RubyMine terminals are non-responsive to Fig, but the normal MacOS terminals are responsive.

As part of the troubleshooting I uninstalled and reinstalled from HomeBrew, but with the same results.  Fig working in the MacOS terminals but not RubyMine.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.0 (21D49)|1.0.57|zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B437) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/michaelnewman/.fig/bin:/Users/michaelnewman/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.0 (21D49)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/michaelnewman/Projects/rentometer2
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: ???
  - Active Process: ??? (???) - ???
  - Installed via Brew: true
  - Environment Variables:
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/michaelnewman/.fig/bin:/Users/michaelnewman/.local/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=10c6ccb4-ce8b-4985-8536-7f190a3c6989
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=1059
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @CoderMiguel, can you run `fig doctor --verbose` inside of the RubyMine terminal?

**Comment by CoderMiguel** [comment]
```
 % fig doctor --verbose
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ /Users/michaelnewman/.bashrc contains valid fig hooks
✔ /Users/michaelnewman/.profile contains valid fig hooks
✔ /Users/michaelnewman/.zshrc contains valid fig hooks
✔ /Users/michaelnewman/.zprofile contains valid fig hooks

Let's make sure Fig is running...
✔ Fig bin exists
✔ PATH contains ~/.local/bin and ~/.fig/bin
✔ Fig Integration
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Figterm socket
✔ Insertion lock does not exist
✔ PATH and PseudoTerminal PATH match
✔ Autocomplete dev mode
✔ Plugin dev mode

Let's check if your system is compatible...
✔ OS is supported

Let's check fig diagnostic...
✔ Installation script
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled
✔ Secure keyboard input disabled

Let's check your terminal integrations...
✔ Input Method


Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!
```

**Comment by CoderMiguel** [comment]
Side Note:
I am now getting the following warning any time I close a terminal in RubyMine
```
Process 'Terminal Local' Is Running
Do you want to terminate the process 'Terminal Local'?
```

Not sure if that adds any context / insight, or if this is an intended side effect

**Comment by mschrage** [comment]
We are at the mercy of macOS when it comes to the installation of the input method. This API is pretty finicky. 

It may be worth running through the `fig install --input-method` process again to ensure everything worked. 

Also try restarting Fig and restarting RubyMine.

Before you do that however, can you click the Fig menubar icon and take a screenshot of the debugger while you are in the RubyMine terminal?

**Comment by CoderMiguel** [comment]
Looks like the Debugger is not supported

![Screen Shot 2022-04-20 at 4 59 47 PM](https://user-images.githubusercontent.com/52347827/164321936-236e85bb-e08b-4ceb-a9bb-72a15b810de3.png)

**Comment by mschrage** [comment]
Interesting, can you run `echo $__CFBundleIdentifier` in the RubyMine terminal?

**Comment by CoderMiguel** [comment]
```
% echo $__CFBundleIdentifier
com.jetbrains.rubymine
```

**Comment by mschrage** [comment]
Perfect! Thanks so much. This is an issue with the macOS app, which was matching against the wrong bundle identifier. 

I'm fixing this right now. It will be go live in the next release.
