### ISSUE TITLE
JetBrains IDE integration not working

### ISSUE THREAD

**Issue by linkurzweg** [withfig/fig#1349]
### Description:
Hello, I was very happy to see that Fig can now be used inside of JetBrains IDEs. However I can not get it to work on my computer. I installed the input method with `fig install --input-method` and activated the integrations in Fig's menu:

![image](https://user-images.githubusercontent.com/4902517/164417047-8c4c0c5a-c152-4ad2-b0f8-af7d3ee42095.png)

I am using WebStorm (221.5080.193) and Rider (221.5080.236) and the latest version of Fig.

I tried restarting Fig, the IDEs and my system several times but it's still not working in both IDEs.
Any ideas how to fix this?

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B437) [German]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: <generated dynamically>
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/lin.kurzweg/dev/RMV
  - CLI Installed: true
  - Executable Location: /Users/lin.kurzweg/.fig/bin/fig
  - Current Window ID: 1929/% (com.jetbrains.WebStorm)
  - Active Process: zsh (85489) - /dev/ttys009
  - Environment Variables:
    - PATH=/Users/lin.kurzweg/.nvm/versions/node/v16.13.1/bin:/Users/lin.kurzweg/.yarn/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/lin.kurzweg/dev/RMV/node_modules/.bin:/Users/lin.kurzweg/.fig/bin:/Users/lin.kurzweg/.local/bin:/Users/[username]/.npm-packages/bin:/Users/lin.kurzweg/.rvm/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=a2936324-03a4-46d6-be32-18fae4a5003b
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=85489
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by linkurzweg** [comment]
@mschrage Thanks for looking into it! Here's the screenshot
![image](https://user-images.githubusercontent.com/4902517/164677203-f1c7d283-e905-4393-810e-81761e5d0bdf.png)

**Comment by mschrage** [comment]
Does Fig work in other terminals? (eg. the native macOS terminal?)

**Comment by linkurzweg** [comment]
It does work fine in iTerm, but not in the native macOS terminal (which I never used, just tested this now).

**Comment by linkurzweg** [comment]
@mschrage I found out it does work when I switch the shell to bash in the terminal settings of WebStorm. But I want to keep using zsh. When I switch back to zsh, fig will stop working again.

**Comment by linkurzweg** [comment]
It works now! :) I had to remove the zsh-autosuggestions plugin from my .zshrc. After that it worked immediately. I liked having both zsh-autosuggestions and fig enabled as sometimes it was quicker to just quickly tab into the suggested command from zsh-autosuggestions. Weird that I could use both at the same time in iTerm though. @mschrage maybe this is something you can look into?

**Comment by chaig15** [comment]
I am having this same issue. Is there anyway, we can use autosuggestions with fig in goland or jetbrains IDE's. Not sure if this is a known problem @mschrage

**Comment by mschrage** [comment]
@chaig15 can you run `fig doctor` in GoLand?
