### ISSUE TITLE
zshrc.post.zsh doesn't work

### ISSUE THREAD

**Issue by AdirYad** [withfig/fig#1350]
### Description:
I've tried to reinstall fig since it didn't work for me. Once I run Iterm, it says `.zshrc:pwd:98: too many arguments`, which is the end of the file (runs `zshrc.post.zsh`), if I try to change `. "$HOME/.fig/shell/zshrc.post.zsh"` to `source "$HOME/.fig/shell/zshrc.post.zsh"`, it works perfectly but once I run `fig doctor` it returns to its default which is period.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B437) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/adiryad/Library/Caches/fnm_multishells/6992_1650533288087/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/adiryad/.cargo/bin:/Users/adiryad/.fig/bin:/Users/adiryad/.local/bin:/Users/adiryad/Library/Python/3.8/bin:/Users/adiryad/.composer/vendor/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/adiryad/Dev/cortex/plugins/gui/frontend
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 165/% (com.jetbrains.pycharm)
  - Active Process: zsh (7509) - /dev/ttys004
  - Installed via Brew: true
  - Environment Variables:
    - PATH=/Users/adiryad/Library/Caches/fnm_multishells/7546_1650533341468/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/adiryad/.cargo/bin:/Users/adiryad/.fig/bin:/Users/adiryad/.local/bin:/Users/adiryad/Library/Python/3.8/bin:/Users/adiryad/.composer/vendor/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=f1fd0665-a226-4bc4-a725-603ca89f433a
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=7509
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
It seems like you might have “.” aliased. Removing that alias will resolve the issue!

**Comment by AdirYad** [comment]
Isn't it possible to change it to `source` without issues instead of `.`?

**Comment by mschrage** [comment]
What does the “.” alias do? We might be able to change to use `source` instead.

**Comment by AdirYad** [comment]
It does `cd ..`, I'm using it on an hourly rate

**Comment by mschrage** [comment]
I’d recommend changing that alias from “.” to “,” or some other character that is not already a shell-built in.

That will resolve the issue!

**Comment by AdirYad** [comment]
I have several aliases that are almost the same, like `..` for cd ../.., and `...` and etc.
I'm unsure if I'll change it since I don't really use the `.` command as it originates. I think `source` might be the best solution.

**Comment by mschrage** [comment]
Okay well I will close this issue for now, since we've identified a fix. If other users report similar issues, perhaps we can update how we source the shell integrations.

Doing these migrations are a bit of a pain, since we need to modify users' dotfiles - that's why I'm slightly hesitant to update the sourcing of integration for everyone.
