### ISSUE TITLE
Not working after initial install bash

### ISSUE THREAD

**Issue by prenagha** [withfig/fig#1353]
### Description:

fig not working. Tried commenting out prompt and iTerm shell integration, still could not get anything to work

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/opt/homebrew/Cellar/bash/5.1.16/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B438) [Beta] [Debug] [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/prenagha/Documents/Mac:/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components:/Users/prenagha/.fig/bin:/Users/prenagha/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /opt/homebrew/bin/bash
  - Current Directory: /Users/prenagha/Code
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 12408/% (com.googlecode.iterm2)
  - Active Process: ??? (???) - ???
  - Installed via Brew: true
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - TERM_SESSION_ID=w0t0p0:B5322CA0-06C1-4310-92D5-9550F0EBEA53
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - TERM=xterm-256color
    - PATH=/Users/prenagha/Documents/Mac:/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components:/Users/prenagha/.fig/bin:/Users/prenagha/.local/bin
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @prenagha! Can you run `fig doctor --verbose` and share the output here?

**Comment by prenagha** [comment]
```
14:25 $ fig doctor --verbose
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ .bashrc exists
✔ .zshrc exists
✔ ~/.bashrc contains valid fig hooks
✔ ~/.bash_profile contains valid fig hooks
✔ ~/.zshrc contains valid fig hooks
✔ ~/.zprofile contains valid fig hooks

Let's make sure Fig is running...
✔ Fig bin exists
✔ PATH contains ~/.local/bin and ~/.fig/bin
✔ Fig Integration
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Figterm socket
✔ Insertion lock does not exist
✔ PATH and PseudoTerminal PATH match
✔ Autocomplete dev mode
✔ Plugin dev mode

Let's check if your system is compatible...
✔ OS is supported

Let's check fig diagnostic...
✔ Installation script
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled
✔ Secure keyboard input disabled

Let's check your terminal integrations...
✔ iTerm integration is enabled


Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!

✔ ~
```

**Comment by mschrage** [comment]
Hey @prenagha! Can you type (but not execute) `git com` in your terminal and then take a screenshot of the Fig debugger. (Click the Fig icon in the menubar and the go to the first tab.)

**Comment by prenagha** [comment]
Fig menu icon says "Debugger(???)" -> Not linked to terminal session

**Comment by mschrage** [comment]
Can you share your zshrc/bashrc file here?

**Comment by prenagha** [comment]
### ~/.bashrc

```
# Fig pre block. Keep at the top of this file.
. "$HOME/.fig/shell/bashrc.pre.bash"

# Fig post block. Keep at the bottom of this file.
. "$HOME/.fig/shell/bashrc.post.bash"
```
### ~/.bash_profile

```
# Fig pre block. Keep at the top of this file.
. "$HOME/.fig/shell/bash_profile.pre.bash"
export ENV_HOME="$HOME/Documents/Mac/env"
if [ -f "$ENV_HOME/profile" ]
then
  . "$ENV_HOME/profile"
fi

# Fig post block. Keep at the bottom of this file.
. "$HOME/.fig/shell/bash_profile.post.bash"
```

### ENV_HOME/profile

```
# Fig pre block. Keep at the top of this file.
. "$HOME/.fig/shell/bash_profile.pre.bash"

for file in $ENV_HOME/{prompt,export,alias,function}; do
	[ -r "$file" ] && source "$file"
done
unset file

# Unhide library folder
chflags nohidden ~/Library

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Homebrew bash completions
source $(brew --repository)/completions/bash/brew

# Homebrew packages bash completion
source $(brew --prefix)/etc/bash_completion
    
# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh

if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR="$(brew --prefix)/opt/bash-git-prompt/share"
  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
fi
  
if [ -f "$HOME/.iterm2_shell_integration.bash" ]
then
  source "$HOME/.iterm2_shell_integration.bash"
fi

# Fig post block. Keep at the bottom of this file.
. "$HOME/.fig/shell/bash_profile.post.bash"

```

**Comment by mschrage** [comment]
Hmm nothing looks too out of the ordinary.

Can you open two terminal sessions and take a screen recording. In the first, run `FIG_LOG_LEVEL=DEBUG` and then in the second, run `fig debug logs`.

Then can you just type a few commands into the first terminal sessions. It seems like events aren't being sent from Fig's shell integrations to the desktop app.

**Comment by prenagha** [comment]
[Screen recording](https://cln.sh/GhS7XKC3R2WYpMWel4Co)
