### ISSUE TITLE
Changing font doesn't work

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1356]
> changing the font family for autocomplete does not take effect. I see the default monospace font

**Comment by mschrage** [comment]
Hey @gsshiva! This seems like an issue with your proxy settings. Can you share more details about how your network is configured?

It seems like you might need to add something like this to your bashrc/zshrc:

```
export http_proxy='your_proxy_url'
export https_proxy='your_proxy_url'
```

**Comment by grant0417** [comment]
Proxies should work better now and @mschrage comment is correct about how you can configure them
