### ISSUE TITLE
can't install Fig tool over PyCharm 2021.3.3 CE

### ISSUE THREAD

**Issue by Tamimi360** [withfig/fig#1360]
### Description:
I am trying to install Fig tool over PyCharm 2021.3.3 (Community Edition) and keeps failing.
I have tried to restart fig and reinstall multiple times but it keeps failing.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.57 (B439)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B439) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/basel/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: true
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: 1736/% (com.jetbrains.pycharm.ce)</pre>
</p>
</details>

**Comment by fedeci** [comment]
Can you run `echo $__CFBundleIdentifier` in the pycharm terminal?

**Comment by mschrage** [comment]
Run `fig install --input-method` and follow the instructions. You will need to restart your computer.

**Comment by SeparateRecords** [comment]
Just following this up @Tamimi360 - did you have any success?

**Comment by grant0417** [comment]
Going to close this as @Tamimi360 never responded.
