### ISSUE TITLE
Installation script: Install script not run

### ISSUE THREAD

**Issue by isagarkanojia** [withfig/fig#1362]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B439) [ABC – India]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: false
  - PseudoTerminal Path: /opt/apache-maven-3.6.3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sagarkanojia/.fig/bin:/Users/sagarkanojia/.local/bin:/opt/gradle/gradle-6.8.3/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/sagarkanojia
  - CLI Installed: true
  - Executable Location: /Users/sagarkanojia/.fig/bin/fig
  - Current Window ID: 220/% (com.googlecode.iterm2)
  - Active Process: zsh (1393) - /dev/ttys003
  - Environment Variables:
    - TERM_SESSION_ID=w1t0p0:98F381E7-F402-480B-9735-5D342E0168E5
    - PATH=/opt/apache-maven-3.6.3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sagarkanojia/.fig/bin:/Users/sagarkanojia/.local/bin:/opt/gradle/gradle-6.8.3/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=1393
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Can you run `fig doctor --verbose` and share the output here?

**Comment by isagarkanojia** [comment]
Last login: Sat Apr 23 21:48:31 on console
➜  ~ fig doctor --verbose
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ .bashrc exists
✔ .zshrc exists
● /Users/sagarkanojia/.bashrc is not accessible
✔ ~/.bash_profile contains valid fig hooks
✔ ~/.zshrc contains valid fig hooks
✔ ~/.zprofile contains valid fig hooks

Let's make sure Fig is running...
✔ Fig bin exists
✔ PATH contains ~/.local/bin and ~/.fig/bin
✔ Fig Integration
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Figterm socket
✔ Insertion lock does not exist
✔ PATH and PseudoTerminal PATH match
✔ Autocomplete dev mode
✔ Plugin dev mode

Let's check if your system is compatible...
✔ OS is supported

Let's check fig diagnostic...
✘ Installation script: Install script not run
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled
✔ Secure keyboard input disabled

Let's check your terminal integrations...
✔ iTerm integration is enabled
✔ VSCode integration is enabled


Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!

➜  ~

**Comment by mschrage** [comment]
This issue here is that `fig` is unable to install shell integrations for bash. This is why the app thinks that the install script didn't run. 

You can ignore this error or you can resolve it by running `chmod 777 ~/.bashrc` and then rerunning `fig doctor`!
