### ISSUE TITLE
Zsh Autosuggestions  plugin and Autocomplete plugin can't work together 

### ISSUE THREAD

**Issue by cnfzg** [withfig/fig#1364]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Zsh Autosuggestions  plugin and Autocomplete plugin can't work together friendly when I enable both of them. 

<img width="471" alt="image" src="https://user-images.githubusercontent.com/35858039/164965655-598ae790-9dfb-4178-8290-2c6c096f9765.png">
<img width="462" alt="image" src="https://user-images.githubusercontent.com/35858039/164965690-ee1a6671-38f9-4fa7-a903-ef19aaba8f50.png">
<img width="812" alt="image" src="https://user-images.githubusercontent.com/35858039/164965785-4f1ef087-98bf-4ca1-93db-32992add7a98.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.57 (B439)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B439) 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/prz007/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /usr/local/opt/grep/libexec/gnubin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/prz007/.fig/bin:/Users/prz007/.local/bin:/Users/prz007/tools/apache-maven-3.6.3/bin:/Users/prz007/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (49326) - not a tty
Current terminal session: w0t0p0:4490FAB2-79D3-4415-B125-0F6D1798BEA0
Current working directory: /Users/prz007
Current window identifier: 8180/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @cnfzg! Thanks for reporting this. Can you share your full zshrc?

I use this setup (fig + zsh-autosuggest) and have no issues.

**Comment by grant0417** [comment]
It looks like the highlight color is not what we would expect, could you run `echo $ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE` and see what the output is

**Comment by idoberko2** [comment]
```
❯ echo $ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE
fg=8
```
I do notice something weird with the autocomplete color, it used to be more grayish and now it looks the same as regular text (white)

**Comment by mschrage** [comment]
@idoberko2 that is the issue. If the color is the same, Fig can’t distinguish between a suggestion and text that you’ve typed.

I don’t know why this would be happening but that’s the underlying issue!

**Comment by idoberko2** [comment]
After some digging, I was finally able to resolve the issue. Apparently `zsh-syntax-highlighting` plugin was preventing me from changing the autosuggest highlight color which in turn, messed up fig's functionality.
I updated `zsh-syntax-highlighting` plugin to the latest version and all issues are resolved!
