### ISSUE TITLE
Popup doesn't render

### ISSUE THREAD

**Issue by rusakov92** [withfig/fig#1367]
### Description:
The autosuggestion popup doesn't render properly. I can see that it is trying to render something but it is a 1 px line. Trying out the autocomplete it does work when I hit enter. Any suggestions on what can cause this?
![Screenshot 2022-04-25 at 0 12 31](https://user-images.githubusercontent.com/7600983/164997008-f3da04b9-a34e-464e-a600-bc07c0d4639a.jpg)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.6.5 (20G527)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B439) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: true
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/sbin:/Users/aleksandar.rusakov/bin:/Users/aleksandar.rusakov/.composer/vendor/bin:/Users/aleksandar.rusakov/.symfony/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/aleksandar.rusakov/.fig/bin:/Users/aleksandar.rusakov/.local/bin:/Users/aleksandar.rusakov/.composer/vendor/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 11.6.5 (20G527)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/aleksandar.rusakov
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 878/% (com.googlecode.iterm2)
  - Active Process: zsh (15138) - /dev/ttys002
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:574E543C-8008-4A2D-B0DA-AFB14B674592
    - PATH=/usr/local/sbin:/Users/aleksandar.rusakov/bin:/Users/aleksandar.rusakov/.composer/vendor/bin:/Users/aleksandar.rusakov/.symfony/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/aleksandar.rusakov/.fig/bin:/Users/aleksandar.rusakov/.local/bin:/Users/aleksandar.rusakov/.composer/vendor/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=15138
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @rusakov92! I haven't seen this before - thanks for reporting.

 Can you try running `fig debug autocomplete-window on`. Then right click the red window, click "inspect elements" and take a screenshot of the "Console" tab.

**Comment by rusakov92** [comment]
So the tokens are there but the window is 1px. Changing the window to 1000px does not show the text for some reason.
![Screenshot 2022-04-26 at 10 15 27](https://user-images.githubusercontent.com/7600983/165243377-9b264884-e30c-421b-a4ad-599eeaadfba2.jpg)
![Screenshot 2022-04-26 at 10 17 30](https://user-images.githubusercontent.com/7600983/165243843-04f7ee21-f8b9-430e-90bd-a874f88fe7f9.jpg)

**Comment by mschrage** [comment]
Can you run `fig settings all` and share the output here?

**Comment by rusakov92** [comment]
Hello, I've stopped the app and after work, I've started it again, this time it is loading the popup without any issues. Not sure what fixed it. Here are the settings:
```
autocomplete.disable = false
autocomplete.theme = "dark"
```

Looks like this can be closed? Are there any recent changes?
