### ISSUE TITLE
PATH contains ~/.local/bin and ~/.fig/bin: Path does not contain ~/.local/bin

### ISSUE THREAD

**Issue by nssherif** [withfig/fig#1370]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig doesn't work once I restart my laptop. I mostly have to uninstall and install fig to get it to work on both Zsh and VSCode terminals for some reason. 

<img width="907" alt="Screen Shot 2022-04-25 at 10 51 22 AM" src="https://user-images.githubusercontent.com/78966535/165136270-eaabcbf5-05a4-44b6-9b08-b6c720c6c6f1.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|-zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B439) [Canadian English]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/mysql/bin:/Library/Apple/usr/bin:/Users/negibsherif/Library/Android/sdk/emulator:/Users/negibsherif/Library/Android/sdk/tools:/Users/negibsherif/Library/Android/sdk/tools/bin:/Users/negibsherif/Library/Android/sdk/platform-tools
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/negibsherif
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 3206/% (com.apple.Terminal)
  - Active Process: ??? (???) - ???
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=C11DF41B-5D13-4D54-91E4-01A24803C9AE
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/mysql/bin:/Library/Apple/usr/bin:/Users/negibsherif/Library/Android/sdk/emulator:/Users/negibsherif/Library/Android/sdk/tools:/Users/negibsherif/Library/Android/sdk/tools/bin:/Users/negibsherif/Library/Android/sdk/platform-tools
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: Extension is not installed.
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
@nssherif it looks like your shell integrations were not set up correctly. 

Can you run `fig doctor --verbose` and share the output here? Also would you mind sharing your `~/.zshrc`?

**Comment by nssherif** [comment]
Sure here are the requested images. 

<img width="649" alt="Screen Shot 2022-04-26 at 3 17 37 PM" src="https://user-images.githubusercontent.com/78966535/165393938-621d9712-7942-4746-9ca5-5eec733c7fd8.png">

<img width="682" alt="Screen Shot 2022-04-26 at 3 19 25 PM" src="https://user-images.githubusercontent.com/78966535/165394161-c17bc883-838d-4005-8114-f09df7d0b03c.png">

**Comment by nssherif** [comment]
@mschrage ^

**Comment by mschrage** [comment]
@nssherif do you have an alias for "."? 

Can you run `which .` and share the output here?

**Comment by nssherif** [comment]
@mschrage Nope, I don't have an alias for "."
Here is the output. 
<img width="263" alt="Screen Shot 2022-04-27 at 5 29 02 PM" src="https://user-images.githubusercontent.com/78966535/165647560-14efa58a-3543-4739-a33e-4acc0702395c.png">

**Comment by mschrage** [comment]
Can you try updating to the latest version of Fig? Run `fig update`.

**Comment by nssherif** [comment]
@mschrage That didn't seem to work. I even deleted fig and reinstalled it and I noticed that I see this when starting the terminal. 
<img width="566" alt="Screen Shot 2022-04-27 at 6 40 11 PM" src="https://user-images.githubusercontent.com/78966535/165653603-b4d639ef-8364-4f3d-adf6-909453a3ee9a.png">

**Comment by mschrage** [comment]
Can you run `fig doctor` again? Also worth running `fig install` if that doesn't resolve the issue.

**Comment by nssherif** [comment]
Yeah fig doctor is still outputting the "PATH contains ~/.local/bin and ~/.fig/bin: Path does not contain ~/.local/bin" error even after running fig install. 
<img width="563" alt="Screen Shot 2022-04-27 at 8 19 50 PM" src="https://user-images.githubusercontent.com/78966535/165663397-2349647f-3003-47e3-bf37-759b7e478e93.png">
Not sure how to get this to work now as even uninstalling and installing isn't fixing the errors now.

**Comment by nssherif** [comment]
@mschrage So I found this other similar issue and this seemed to have fixed it. 
https://github.com/withfig/fig/issues/1104#issuecomment-1069765878

However, I still get errors when I run fig doctor and the vs code extension is not being installed even though I install it. 
<img width="838" alt="Screen Shot 2022-04-27 at 8 36 23 PM" src="https://user-images.githubusercontent.com/78966535/165665418-efad01ff-0a78-4833-b02c-ab5ffcdd3edb.png">
<img width="796" alt="Screen Shot 2022-04-27 at 8 36 58 PM" src="https://user-images.githubusercontent.com/78966535/165665476-7617a14d-b394-410a-9f7e-e98c051b9307.png">

**Comment by skilletti** [comment]
@nssherif You can change the path in /Users/<user>/.fig/shell/<yourbash> pre and post files:
eval "$(~/.fig/bin/fig init bash pre --rcfile bash_profile)" instead of eval "$(~/.local/bin/fig init bash pre --rcfile bash_profile)"
It worked for me

**Comment by mschrage** [comment]
@SeparateRecords can you look into this?

**Comment by SeparateRecords** [comment]
@mschrage we got this figured out! Thanks again @nssherif 🙂

For anyone wondering what our fix was:
```
sudo chown -R $(id -un) ~/.local
```

How this issue occurred:
* Fig was installed for a while
* After using Fig for a while, somehow the ownership of ~/.local changed to `root` (possibly related to bower)
* We migrated the shell config to use ~/.local/bin/fig
* Fig failed to set up correctly!
* Fig was already in the path because of ~/.fig/bin, so the CLI was still accessible

Moving forward I think there's a couple of things we can action to prevent this.
* `fig doctor` check for ownership of .local
* Show permission errors in the menubar debugger
* The `pre` script files should also show a warning and print the command to fix it

**Comment by yusufozcan** [comment]
`sudo nano /etc/paths`

add the following lines to the end

```
/.local/bin
/.fig/bin
```

restart terminal and run `fig doctor --verbose`. Path errors must be resolved.

**Comment by zyads** [comment]
> sudo chown -R $(id -un) ~/.local
@SeparateRecords 

Hey Im just wondering what does this do? 

I thought I had the same error as discussed in the thread but the mentioned script didn't seem to fix anything. Could you explain what the script did and how to reverse its (possibly adverse) effects since it did not seem to fix my issue. Thanks!

I also attached an image of the error I am getting. If anyone has any suggestions on how to fix it I would appreciate it. I am using Ubuntu on WSL by the way.
<img width="630" alt="image" src="https://user-images.githubusercontent.com/71473362/188028585-0fe33f82-f0df-4550-9ef2-40844c39e035.png">

**Comment by zyads** [comment]
> `sudo nano /etc/paths`

@yusufozcan 

Does this only work on mac?

**Comment by SeparateRecords** [comment]
> Hey Im just wondering what does this do?

No adverse effects there! All that script does is set the owner of your ~/.local folder (and everything inside it) to your current user, which it should already be - it's probably a bug if it isn't owned by you. I don't know if `id` is available on Linux so you might have to replace `id -un` with `whoami`

**Comment by SeparateRecords** [comment]
As for the bug itself, looks like something @chaynabors might want to look into

**Comment by iamyeizi** [comment]
> > @nssherif You can change the path in /Users/"user"/.fig/shell/ pre and post files:
> > `eval "$(~/.fig/bin/fig init bash pre --rcfile bash_profile)" ` instead of `eval "$(~/.local/bin/fig init bash pre --rcfile bash_profile)"` It worked for me
> 
> I made this modification, reinstalled, updated, I still have the same error <img alt="Capture d’écran 2022-06-15 à 12 02 19" width="1440" src="https://user-images.githubusercontent.com/1110693/173801705-b6825ad0-f98d-4b85-90e6-9d565bfa0fc2.png">

You need to add the missing path to the variable `$PATH`
In this way, you first have to know the content of your current **PATH**, with:
`echo $PATH`

Example:
`/Users/miuser/miniconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

Then you should only add at the end of that **PATH** what is missing, which would be:
`:~/.fig/bin` and `:~/.local/bin`

Then adding this to what is already in the **PATH** would be:
`/Users/miuser/miniconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.fig/bin:~/.local/bin`

Now, you add to the variable:
`PATH=/Users/miuser/miniconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.fig/bin:~/.local/bin`

Finally, you run: `fig doctor` and it should be solved!

(Sorry for my english)

**Comment by iamyeizi** [comment]
> facing the same error here on MacBook(silicon) with macOS 13.1.0 (22C5059b). install using brew and also dmg but nothing worked. Tried the comment [#1370 (comment)](https://github.com/withfig/fig/issues/1370#issuecomment-1219265675) but did not help. Got the below error after trying that.
> 
> ` ✘ Fig Integration: Figterm is not running in this terminal, please try restarting your terminal FIG_TERM=`

To solve this, you still need to configure Fig in your terminal.

Once the `fig doctor` doesn't give any errors except the Fig Integration.

You need to do this, being active in your terminal, you go to the Fig icon in the **statusbar**, click on **Integrations** and then on your **Terminal name** (in my case it is iTerm), then a menu will appear _to restart that terminal_ and the Fig configuration will open where you will go through the tutorial, after that you will no longer have any other error.

![83 13](https://user-images.githubusercontent.com/37552350/206068932-85e0d274-4263-4481-a930-ecdc07e67af3.png)

Cheers!

**Comment by nivesh2** [comment]
> > > @nssherif You can change the path in /Users/"user"/.fig/shell/ pre and post files:
> > > `eval "$(~/.fig/bin/fig init bash pre --rcfile bash_profile)" ` instead of `eval "$(~/.local/bin/fig init bash pre --rcfile bash_profile)"` It worked for me
> > 
> > 
> > I made this modification, reinstalled, updated, I still have the same error <img alt="Capture d’écran 2022-06-15 à 12 02 19" width="1440" src="https://user-images.githubusercontent.com/1110693/173801705-b6825ad0-f98d-4b85-90e6-9d565bfa0fc2.png">
> 
> You need to add the missing path to the variable `$PATH` In this way, you first have to know the content of your current **PATH**, with: `echo $PATH`
> 
> Example: `/Users/miuser/miniconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
> 
> Then you should only add at the end of that **PATH** what is missing, which would be: `:~/.fig/bin` and `:~/.local/bin`
> 
> Then adding this to what is already in the **PATH** would be: `/Users/miuser/miniconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.fig/bin:~/.local/bin`
> 
> Now, you add to the variable: `PATH=/Users/miuser/miniconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.fig/bin:~/.local/bin`
> 
> Finally, you run: `fig doctor` and it should be solved!
> 
> (Sorry for my english)

This worked for me may thanks!

**Comment by Tenkaklet** [comment]
Fixed this by re doing the homebrew commands ( uninstall / install ), made sure to open fig dashboard when finished installing ( comes up as a dialog box ) and closed my terminal and open again, this worked.

**Comment by avfigueredo** [comment]
I got this error when I’ve installed using brew. I’ve fixed this issue, removing fig using brew uninstall, after I downloaded the app from the site.

**Comment by tallesairan** [comment]
> @nssherif You can change the path in /Users/"user"/.fig/shell/ pre and post files:
> 
> `eval "$(~/.fig/bin/fig init bash pre --rcfile bash_profile)" ` instead of `eval "$(~/.local/bin/fig init bash pre --rcfile bash_profile)"` It worked for me

worked for me thanks 🗡️

**Comment by mikailbala** [comment]
> Fixed this by re doing the homebrew commands ( uninstall / install ), made sure to open fig dashboard when finished installing ( comes up as a dialog box ) and closed my terminal and open again, this worked.

This worked for me as well. I made sure to run this command after i reinstalled fig through brew: eval "$(~/.fig/bin/fig init bash pre --rcfile bash_profile)" . Thanks
