### ISSUE TITLE
Sign-up workflow loops back to email confirmation

### ISSUE THREAD

**Issue by adamegyed** [withfig/fig#1371]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When going through the sign-up workflow, upon progressing past the email sign-up and "How did you hear about Fig" dialog boxes, the window loops back to the email confirmation screen. This is still working and interactive, and sends another confirmation code to the email address. When force-quitting Fig and restarting, it appears like Fig is set up properly.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.57 (B440)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B440) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/adam/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @adamegyed! This is very strange. Could you run `fig doctor --verbose` and share the output here?

Then try running `fig login --refresh`

**Comment by grant0417** [comment]
We have a new onboarding now which should fix this issue
