### ISSUE TITLE
fig not working in bash, built in terminal, macos 10.14.6

### ISSUE THREAD

**Issue by theconsultant** [withfig/fig#1372]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Opened Terminal today and fig no longer works. Restarted it, reinstalled it, updated it, nothing I can find changes it. Debugger shows 'not linked to terminal session'.

Suggestions welcome!

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 10.14.6 (18G9323)|1.0.57|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B439) [Canadian English]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/davidr/.poetry/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/opt/php@7.3/sbin:/usr/local/opt/php@7.3/bin:/Users/davidr/.poetry/bin:/usr/local/bin:/usr/local/sbin:/Users/davidr/bin:/Users/davidr/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/davidr/.fig/bin:/Users/davidr/.local/bin:/Users/davidr/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: Mac mini
  - Model Identifier: Macmini6,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 10.14.6 (18G9323)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/davidr
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 21296/% (com.apple.Terminal)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=AE8A871B-DD71-436F-919F-A0A1AC097D49
    - PATH=/Users/davidr/.poetry/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/opt/php@7.3/sbin:/usr/local/opt/php@7.3/bin:/Users/davidr/.poetry/bin:/usr/local/bin:/usr/local/sbin:/Users/davidr/bin:/Users/davidr/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/davidr/.fig/bin:/Users/davidr/.local/bin:/Users/davidr/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false

</p>
</details>

**Comment by theconsultant** [comment]
So I dug through some issues, found #1333 and did some digging in my old .profile (thank you for making backups in ~/.fig !) and changed the last line in my .profile:

was:
`# . "$HOME/.fig/shell/profile.post.bash"`

to
`eval "$(fig init bash post)"`

and now fig works. I did not touch the pre line at the top of .profile.

**Comment by theconsultant** [comment]
`fig doctor` complains.. but it works!
![Screen Shot 2022-04-25 at 8 16 56 PM](https://user-images.githubusercontent.com/1421526/165194678-f03235b4-2798-465d-9a16-7e9334779eed.png)

**Comment by grant0417** [comment]
Hey @theconsultant, can you try running `fig update` and reverting the change you made, we pushed out a new build today that should have fixed that issue.

**Comment by theconsultant** [comment]
Awesome. It's all good now. ;-)
