### ISSUE TITLE
debugger red dot/error loading spec

### ISSUE THREAD

**Issue by Buzzraider** [withfig/fig#1375]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

After newest update debugger shows with the red dot and info showed in the screenshot.
restarting fig and terminals didn't help. And im obviously connected to the internet so to be clear on that ;)

![Screenshot 2022-04-26 at 10 08 46](https://user-images.githubusercontent.com/69143224/165253981-24cef24c-3bab-4074-8f70-c5b8c79422f9.png)

After running fig doctor I have this.

![Screenshot 2022-04-26 at 10 13 23](https://user-images.githubusercontent.com/69143224/165254080-2ce68eb3-8af5-4652-8d64-08f549ff14e9.png)

Worth to point out that Im using Visual Studio Code Insiders and fig works there. (Im assuming its looking for regular VSCode, not finding it and displays this msg.)

Also worth a note is that fig works in terminals, im getting popup window with commands etc.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.57 (B439)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B439) [Polish] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Michal/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: true
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Michal/.fig/bin:/Users/Michal/.local/bin:/opt/homebrew/opt/fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (89615) - not a tty
Current terminal session: 7DDCC149-1B10-4067-9181-6CB4AAF0BB66
Current working directory: /Users/Michal
Current window identifier: 4717/% (co.zeit.hyper)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Buzzraider! Thanks for reporting this. Just want to confirm that other than this error message, Fig appears to be working normally? (For instance, the autocomplete popup appears when you type "git co"?)

Have you noticed if there is a specific CLI tool that causes this warning to show up? 

PS. You're exactly right. The VSCode warning is a bug with our `doctor` logic and not related to this issue.

**Comment by Buzzraider** [comment]
Yes autocomplete works as usual, this is "git co" results:

![Screenshot 2022-04-26 at 19 25 02](https://user-images.githubusercontent.com/69143224/165357678-2d9b1bf8-2c7f-405a-852a-824603a4747d.png)
 
No, im using; Hyper.app, iterm.app, tabby.app, VSCode Insiders terminal and default macOS terminal.app every single of them starts with yellow dot "not linked to terminal session..." and then red dot with "no internet connection etc" 🤷‍♂️

**Comment by mschrage** [comment]
Hmm strange. Can you share a screen recording of...
1. launching a new terminal
2. Checking the Fig debugger
3. Typing `git co`
4. Checking the Fig debugger

**Comment by Buzzraider** [comment]
This is hyper.app terminal

https://user-images.githubusercontent.com/69143224/165384537-40e4e747-7d71-4070-8f3b-5f7bf963a019.mov

Notice that it instantly showed red debugger, but with tabby as it loads slower it shows the yellow dot for a brief sec. then red. Probably related (the yellow dot in debug) to loading time of tabby.app

**Comment by mschrage** [comment]
This is likely an issue with the autocomplete-engine. @fedeci can you look into why this warning might be appearing?

**Comment by Buzzraider** [comment]
Hmm, it looks it fixed itself, I didn't do anything. There was an Apple update for developer tools or something like that along the way and thats about it. So either you guys did something on backend or some other magic happened ;)

P.S. Timeframe when or how it fixed itself is unfortunatelly unknown to me.

**Comment by mschrage** [comment]
We've updated the autocomplete engine to be more resilient in cases where specs couldn't be loaded! Will close this issue for now.
