### ISSUE TITLE
Fig cant link to the current terminal

### ISSUE THREAD

**Issue by tuananh2508** [withfig/fig#1380]
### Description:

Sometime Fig just can't link to the current terminal session. I have try `fig source` and `fig doctor` but nothing worked so far. 

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/opt/homebrew/Cellar/bash/5.1.16/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B439) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tuananhvu/.fig/bin:/Users/tuananhvu/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /opt/homebrew/bin/bash
  - Current Directory: /Users/tuananhvu
  - CLI Installed: true
  - Executable Location: /Users/tuananhvu/.fig/bin/fig
  - Current Window ID: 18385/% (com.googlecode.iterm2)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - TERM_SESSION_ID=w0t0p0:6ADCE5BE-7ABC-4FAC-9B5B-A1892446C69E
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - TERM=xterm-256color
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tuananhvu/.fig/bin:/Users/tuananhvu/.local/bin
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Run `fig update`! This issue is resolved on the latest version :)
