### ISSUE TITLE
Autocomplete and suggestions stopped working

### ISSUE THREAD

**Issue by thebigsweatshirt** [withfig/fig#1385]
### Description:
I downloaded Fig and used it a bit without problem. However, today the autocomplete and the suggestions stopped working (in the terminal and in VS Code as well). 

### Screenshot
<img width="1002" alt="2022-04-27 -Terminal-julien — julien@Juliens-MBP-2 — ~ — zsh (figterm) ▸ zsh — One Dark — 80×31@2x" src="https://user-images.githubusercontent.com/17908630/165606819-a460ec41-70c0-4108-9d6e-242d78dc5539.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.0.1 (21A559)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B439) [Dev] [ABC – QWERTZ]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 1
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/julien/opt/anaconda3/bin:/Users/julien/opt/anaconda3/condabin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/julien/.pyenv/shims:/Users/julien/.nvm/versions/node/v12.14.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/julien/.fig/bin:/Users/julien/.local/bin:/Users/julien/.fzf/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.0.1 (21A559)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/julien
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 185/% (com.apple.Terminal)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=89B1EECE-C80C-456A-84BA-DD5D68BB0BBE
    - PATH=/Users/julien/opt/anaconda3/bin:/Users/julien/opt/anaconda3/condabin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/julien/.pyenv/shims:/Users/julien/.nvm/versions/node/v12.14.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/julien/.fig/bin:/Users/julien/.local/bin:/Users/julien/.fzf/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
This issue is fixed on the latest version! Please run `fig update` :)

**Comment by thebigsweatshirt** [comment]
@mschrage installed the latest version and it works 🙌  Thanks a lot
