### ISSUE TITLE
Fig app displays "Something went wrong :("

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1389]
This is a very generic issue. If this is happening for you, can you:
1. Right click the window
2. Click "inspect element"
3. Click on the console tab
4. Take a screenshot, and post it in a comment

**Comment by maxsky** [comment]
I found this problem was from domain: cdn.jsdelivr.net

In some case this domain will be resolved to: 0.0.0.0

<img width="260" alt="QQ20220513-103218@2x" src="https://user-images.githubusercontent.com/7405522/168200084-f7480476-eff3-4593-855c-683dc0b8e0c4.png">

**Comment by grant0417** [comment]
This should be improved now!
