### ISSUE TITLE
/.zshrc does not source post integration last | Path does not contain~/. local/bin | fig modifying zshrc file infinitely 

### ISSUE THREAD

**Issue by PatGBull** [withfig/fig#1393]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

**Very new to Fig after I installed it everything seemed fine when I ran the fig doctor these errors came up so i ran the 'fig install --dotfiles' and it did nothing. tried changing directories and running the --dotfiles still did nothing.**

<img width="743" alt="Screenshot 2022-04-28 at 19 17 45" src="https://user-images.githubusercontent.com/10012356/165822769-497041e4-e28e-4e4f-b331-d88009aac3a1.png">

**Opened my ~/.zshrc file hoping to see this.**

<img width="406" alt="Screenshot 2022-04-28 at 19 37 56" src="https://user-images.githubusercontent.com/10012356/165823379-e5adca37-0dab-483a-92ef-8a7c1d37beb0.png">

**but instead got this and it's just constantly adding and modifying so when I edit and save the file it's already begun modifying itself again.**

<img width="672" alt="Screenshot 2022-04-28 at 19 23 09" src="https://user-images.githubusercontent.com/10012356/165823451-ad8653ae-7fcf-450c-bd98-b999eeac63d0.png">

**when i restart and open a new terminal these are the errors i get.**

<img width="815" alt="Screenshot 2022-04-28 at 19 37 11" src="https://user-images.githubusercontent.com/10012356/165823505-89a6ab53-69a2-4b0f-ab15-c931ba0ebc72.png">

**despite the fact that file is in the shell folder.**

<img width="677" alt="Screenshot 2022-04-28 at 19 37 41" src="https://user-images.githubusercontent.com/10012356/165823560-e0df6097-cd2b-4786-9295-a820a50aa347.png">

**I've tried completely uninstalling fig deleting all files related to it and starting again and it just does the same thing.**

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [British]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin#
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/patrickbull/webcodes
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 2318/% (co.zeit.hyper)
  - Active Process: zsh (85179) - 
  - Installed via Brew: true
  - Environment Variables:
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin#
    - TERM=xterm-256color
    - TERM_SESSION_ID=EC88176C-C2B3-42CA-8DAD-18D13D59082D
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=85179
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: installed!
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
This line is the culprit: `cat ~/.bash_profile >> ~/.zshrc`

This is running every time you open a new shell. I am not sure why you'd want this in your zshrc file, but removing it (and deleting all the duplication) should resolve the issue.

**Comment by PatGBull** [comment]
Nope sadly not doing anything, Fig is writing that cat ~/.bash_profile line and then duplicating. 

I've tried removing that line and deleting everything several times. 

I've tried copying the lines from the dotfiles.bak copy into the zshrc file in my home directory and it starts doing it again.

I've tried moving the dotfiles.bak copy into home directory to overwrite the bad zshrc and it starts doing it again.

I've tried deleting the zshrc in home directory and it creates a new zshrc by itself.

The moment I completely uninstall fig it stops the infinite loop and starts back up as soon as i redownload it which i've done through the website dmg and through brew.

So unsure what else i could try.

**Comment by mschrage** [comment]
Can you share all of your dotfiles? I'm pretty sure that `cat ~/.bash_profile >> ~/.zshrc` this line is ultimately the culprit (or if you have a similar line in other files)?

**Comment by JVSFlipped** [comment]
Just give it a try. After the first installation (not available), check fig and terminal for Accessibility and Full Disk Access rights in the system settings, then reinstalling fig, try to start fig first and then start the terminal. It is work for me. @mschrage , maybe it has something to do with Apple's security strategy?
