### ISSUE TITLE
CD command is slow and sometimes doesn't work in Mac - ZSH

### ISSUE THREAD

**Issue by czegarram** [withfig/fig#1394]
### Description:

https://user-images.githubusercontent.com/4095996/165827723-5b005722-0e63-420f-a6fd-a3e4f7f21b0b.mov

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.6.4 (20G417)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [Spanish - ISO]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/opt/postgresql@10/bin:/Users/czegarra/.sdkman/candidates/maven/current/bin:/Users/czegarra/.sdkman/candidates/java/current/bin:/Users/czegarra/.sdkman/candidates/gradle/current/bin:/Users/czegarra/.nvm/versions/node/v14.17.6/bin:/Users/czegarra/.rbenv/shims:/Users/czegarra/.pyenv/plugins/pyenv-virtualenv/shims:/Users/czegarra/.pyenv/shims:/Users/czegarra/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/tcl-tk/bin:/opt/homebrew/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/czegarra/.fig/bin:/Users/czegarra/.local/bin:/Users/czegarra/Library/Android/sdk/platform-tools/:/usr/local/Cellar/postgresql@10/10.17/bin:/Users/czegarra/.local/bin:/Users/czegarra/.rvm/bin:/Users/czegarra/.local/bin:/Users/czegarra/flutter/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB
## OS Info:
  - macOS 11.6.4 (20G417)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/czegarra
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 13149/% (com.apple.Terminal)
  - Active Process: zsh (10976) - not a tty
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=DD4E6130-3E86-4E66-AF29-2B8BEAAC1E32
    - PATH=/usr/local/opt/postgresql@10/bin:/Users/czegarra/.sdkman/candidates/maven/current/bin:/Users/czegarra/.sdkman/candidates/java/current/bin:/Users/czegarra/.sdkman/candidates/gradle/current/bin:/Users/czegarra/.nvm/versions/node/v14.17.6/bin:/Users/czegarra/.rbenv/shims:/Users/czegarra/.pyenv/plugins/pyenv-virtualenv/shims:/Users/czegarra/.pyenv/shims:/Users/czegarra/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/tcl-tk/bin:/opt/homebrew/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/czegarra/.fig/bin:/Users/czegarra/.local/bin:/Users/czegarra/Library/Android/sdk/platform-tools/:/usr/local/Cellar/postgresql@10/10.17/bin:/Users/czegarra/.local/bin:/Users/czegarra/.rvm/bin:/Users/czegarra/.local/bin:/Users/czegarra/flutter/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=10976
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by czegarram** [comment]
This happens after some days of a fresh installation.

**Comment by mschrage** [comment]
That means that some command that is being executed that causes the psuedoterminal to break. Next time it happens, can you run `fig debug log c_pty` and then type "cd " a few times.

**Comment by czegarram** [comment]
Sure, I'll send you the log next time.
