### ISSUE TITLE
Terminal VS Code - Bash terminal

### ISSUE THREAD

**Issue by a-figueiredo-campos** [withfig/fig#1395]
### Description:
Fig doesn't seem to be working when i type in terminal of VS Code.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.0 (21D49)|1.0.57|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B439) [Portuguese]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/runtime/.rvm/gems/ruby-3.0.2/bin:/Users/runtime/.rvm/gems/ruby-3.0.2@global/bin:/Users/runtime/.rvm/rubies/ruby-3.0.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runtime/.rvm/gems/ruby-3.0.2/bin:/Users/runtime/.rvm/gems/ruby-3.0.2@global/bin:/Users/runtime/.rvm/rubies/ruby-3.0.2/bin:/Users/runtime/.fig/bin:/Users/runtime/.local/bin:/Users/runtime/.rvm/bin:/Users/runtime/.rvm/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.0 (21D49)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/runtime/core-ui
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 32345/% (com.microsoft.VSCode)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=959828C6-03BA-487D-A0B8-1A612BA7917D
    - PATH=/Users/runtime/.rvm/gems/ruby-3.0.2/bin:/Users/runtime/.rvm/gems/ruby-3.0.2@global/bin:/Users/runtime/.rvm/rubies/ruby-3.0.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runtime/.rvm/gems/ruby-3.0.2/bin:/Users/runtime/.rvm/gems/ruby-3.0.2@global/bin:/Users/runtime/.rvm/rubies/ruby-3.0.2/bin:/Users/runtime/.fig/bin:/Users/runtime/.local/bin:/Users/runtime/.rvm/bin:/Users/runtime/.rvm/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by chaynabors** [comment]
Hey @a-figueiredo-campos! Can you run `fig doctor --verbose` in the VSCode terminal and share the output here?
