### ISSUE TITLE
Fig not showing suggestions anymore

### ISSUE THREAD

**Issue by aaguilerav** [withfig/fig#1396]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|fish|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [Australian]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,4
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/aaguilerav
  - CLI Installed: true
  - Executable Location: /Users/aaguilerav/.fig/bin/fig
  - Current Window ID: 3691/% (com.googlecode.iterm2)
  - Active Process: fish (56893) - /dev/ttys008
  - Installed via Brew: true
  - Environment Variables:
    - FIG_PID=56893
    - FIG_TERM=1
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - TERM=xterm-256color
    - TERM_SESSION_ID=w1t0p0:3B0B07FB-D428-401D-A701-F739E894199D
    
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by chaynabors** [comment]
Hey @aaguilerav! Can you try updating to the latest version of Fig? We've pushed a new build that may resolve this issue.

I'm going to close this for now, but please let me know if you're still running into problems and I will reopen it.
