### ISSUE TITLE
Crash blank screen after then Customize Theme during MacOS installation

### ISSUE THREAD

**Issue by zhy1** [withfig/fig#1397]
### Description:
> Unable to complete the installation, whether downloading dmg or brew

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.56 (B414)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B414) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/z/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by chaynabors** [comment]
Hey @zhy1 are you potentially using a VPN? Try running `fig login` and this may resolve your issue.

**Comment by zhy1** [comment]
> Hey @zhy1 are you potentially using a VPN? Try running `fig login` and this may resolve your issue.

I have tried changing the network environment but the problem still occurs

**Comment by grant0417** [comment]
We have changed our on boarding so this should no longer happen for new users.
