### ISSUE TITLE
`brew uninstall` script deletes too much

### ISSUE THREAD

**Issue by GBrachetta** [withfig/fig#1398]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:

For the 4th time, after installing and cutomising Fig, it uninstalls itself after a few days of normal and correct use.

The uninstall screen pops up:

<img width="471" alt="Screenshot 2022-05-01 at 19 35 32" src="https://user-images.githubusercontent.com/57924268/166157567-b210410a-fc8e-435c-ba44-08f4f1fcde9e.png">

And Fig is gone, together with my .fig folder and all custom settings.

I have no idea about what could be triggering this uninstall.

### Environment

```bash
MacBook Pro M1 Max.
MacOs 12.3.1
```

**Comment by mschrage** [comment]
Did you install Fig using `brew`?

**Comment by GBrachetta** [comment]
Yes, indeed I installed it with homebrew.

**Comment by mschrage** [comment]
I think this is triggered when you upgrade `brew` packages. Brew apparently runs the uninstall script defined in the formula. (We are pushing a workaround in the next release.)

**Comment by GBrachetta** [comment]
Is installing from the dmg the solution for now, or rather wait a bit for the fix? (I prefer to manage all installs with Homebrew whenever possible because of dotfiles).

**Comment by SeparateRecords** [comment]
@GBrachetta You're correct installing via the DMG is the workaround. Next release should be out soon though!

**Comment by rahulsarathy** [comment]
Closing this issue. Feel free to re-contact us if you're still running into problems!
