### ISSUE TITLE
Auto Complete is not working after pushing commands dynamically to additionalSuggestions prop

### ISSUE THREAD

**Issue by nathan5x** [withfig/fig#1401]
### Description:
I'm auto-generating commands by parsing an array of scripts that I added through the TS file and pushing them through `additionalSuggestions`. I re-verified that the commands are generated correctly as expected.  However, the autocomplete is not displaying anything. It is blank.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.6.2 (20G314)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [Dev] [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB
## OS Info:
  - macOS 11.6.2 (20G314)
## Environment:
  - User Shell: /bin/zsh
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 77/% (com.googlecode.iterm2)
  - Active Process: zsh (1762) - /dev/ttys012
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t2p0:7F5F5150-6831-4CCF-B22D-5421BA89403D
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=1762
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

Sample Code here
```
const completionSpec: Fig.Spec = {
  name: "_shortcuts",
  description: "App Shortcuts ....",
  additionalSuggestions: [
    {
      icon: "🛠",
      name: "Start dev server",
      insertValue: "\b\bnpm run dev",
      description: "Start the dev server",
    }
  ],
  subcommands: [],
};

//----------------------------------------------------------
// Create suggestions for App and library Scripts
//----------------------------------------------------------
[appScripts].forEach((scripts: ScriptItem[]) => {
  scripts.forEach((script) => {
    script.commands.forEach((command: ScriptCommand) => {
      insertCommand(script, command);
    });
  });
});

export default completionSpec;
```

`insertCommand` - Generates Fig.Suggestion

**Comment by fedeci** [comment]
Hey @nathan5x have you followed this guide? https://fig.io/docs/guides/project-shortcuts

**Comment by nathan5x** [comment]
Yes I followed the exact same page.

**Comment by nathan5x** [comment]
Figured out the issue and resolved it. 

Somehow, _shortcuts.ts file doesn't like the scripts to be added directly. I wrapped my command generation scripts inside a function and called it just before the export. And it worked!
