### ISSUE TITLE
Daemon error

### ISSUE THREAD

**Issue by hefferbub** [withfig/fig#1403]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Fig seems to work, but fig doctor gives:

```
✘ Daemon: Daemon is not running
  Init system: Launchd
Attempting to fix automatically...
Failed to fix: Could not start daemon: Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.

```
I'm on MacOS 12.3.1 on Intel

I have installed the following plugins

<img width="151" alt="image" src="https://user-images.githubusercontent.com/1672667/166235717-558387b9-6e8b-48bf-8e39-4a772e781f64.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.57 (B440)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B440) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Volumes/FW_SSD/home/jgilmore/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @hefferbub!

Can you run `plutil ~/Library/LaunchAgents/io.fig.dotfiles-daemon.plist` and share the output here?

If the plist is valid, try to...
**Unload and reload the service:**
```
launchctl unload ~/Library/LaunchAgents/io.fig.dotfiles-daemon.plist
launchctl load ~/Library/LaunchAgents/io.fig.dotfiles-daemon.plist
```
**Force load in case your job has been disabled:** 
```
 launchctl load -w ~/Library/LaunchAgents/com.appleseed.runthings.plist
 ```

**Comment by rahulsarathy** [comment]
Closing this for now. Feel free to reach out if you're still running into errors!

**Comment by mmachatschek** [comment]
> Can you run plutil ~/Library/LaunchAgents/io.fig.dotfiles-daemon.plist and share the output here?

```
/Users/xx/Library/LaunchAgents/io.fig.dotfiles-daemon.plist: OK
```

@mschrage unloading and loading the services as suggested by you fixed the issue for me. Isn't this something that `fig doctor` should fix automatically?

**Comment by hefferbub** [comment]
Hi Matt,

Here is the output:

/Volumes/FW_SSD/home/jgilmore/Library/LaunchAgents/io.fig.dotfiles-daemon.plist: OK

launchctl unload ~/Library/LaunchAgents/io.fig.dotfiles-daemon.plist
Unload failed: 5: Input/output error
Try running `launchctl bootout` as root for richer errors.

 sudo launchctl unload ~/Library/LaunchAgents/io.fig.dotfiles-daemon.plist
Warning: Expecting a LaunchDaemons path since the command was ran as root. Got LaunchAgents instead.
`launchctl bootout` is a recommended alternative.
/Volumes/FW_SSD/home/jgilmore/Library/LaunchAgents/io.fig.dotfiles-daemon.plist: Could not find specified service
Unload failed: 113: Could not find specified service

launchctl load ~/Library/LaunchAgents/io.fig.dotfiles-daemon.plist
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.

launchctl load -w ~/Library/LaunchAgents/com.appleseed.runthings.plist
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.


One thing unusual on my system—my home directory is not on the Boot volume.  I don’t know if that has any relevance.

Jeff
