### ISSUE TITLE
getting error 'fig_precmd:1: permission denied:'

### ISSUE THREAD

**Issue by tuckpuck** [withfig/fig#1404]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
Any time I start my terminal or type any command, I get an error 'fig_precmd:1: permission denied:' followed by a file path to a pCloud folder on my computer. Fig doctor says everything is fine, as does the debugger on the menu bar. If I try to autocomplete that folder it says: 

`(eval):4: permission denied: /Users/tbtriggs/pCloud Local
 (eval):8: permission denied: /Users/tbtriggs/pCloud Local
 (eval):9: permission denied: /Users/tbtriggs/pCloud Local
 (eval):10: permission denied: /Users/tbtriggs/pCloud Local`

Otherwise, everything seems to be working ok. But just can't figure out what that error is or remove it. 

<img width="542" alt="CleanShot 2022-05-02 at 22 19 18@2x" src="https://user-images.githubusercontent.com/16181700/166319822-bc48f8ad-0f62-46c8-9167-c42dac239d84.png">

### Environment

```bash
## Fig details:
  - Fig version: Version 1.0.57 (B440) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/tbtriggs/.cabal/bin:/Users/tbtriggs/.ghcup/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tbtriggs/.fig/bin:/Users/tbtriggs/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/tbtriggs
  - CLI Installed: true
  - Executable Location: /Users/tbtriggs/.fig/bin/fig
  - Current Window ID: 165/% (com.apple.Terminal)
  - Active Process: zsh (2676) - /dev/ttys006
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=B25F5ACB-36C3-40F6-B8C6-E00BBEFDED1C
    - PATH=/Users/tbtriggs/.cabal/bin:/Users/tbtriggs/.ghcup/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tbtriggs/.fig/bin:/Users/tbtriggs/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=2676
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
Hey @tuckpuck! Do you have any aliases/shell functions defined?

**Comment by tuckpuck** [comment]
Yep I have a lot of aliases and functions set up in .zshrc. I removed this one: `alias local="~/pCloud\ Local"`
and the error is gone! Not sure exactly why that worked but it seems to fix the issue.

**Comment by mschrage** [comment]
Hey @tuckpuck. `local` is actually a keyword in bash/zsh! Since we use it in our scripts, when it is redefined, everything breaks in mysterious ways.
