### ISSUE TITLE
Completion doesn't work correctly in folder whose name contains Japanese characters

### ISSUE THREAD

**Issue by MasatoshiTada** [withfig/fig#1406]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Take a look at the screenshot below:

<img width="903" alt="スクリーンショット 2022-05-03 11 20 31" src="https://user-images.githubusercontent.com/7044137/166396038-71e36bad-4588-45e9-9631-b6bf26e882f0.png">

In spite of under `マイドライブ/` directory, Fig shows directories under `~` directory.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/opt/python@3.10/bin:/Users/tada/apache-maven-3.8.3/bin:/opt/homebrew/opt/postgresql@13/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/tada/.fig/bin:/Users/tada/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/tada/マイドライブ
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 597/% (com.googlecode.iterm2)
  - Active Process: zsh (2915) - /dev/ttys003
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w1t0p0:C767244F-DE98-4090-B25F-73147CDF7643
    - PATH=/opt/homebrew/opt/python@3.10/bin:/Users/tada/apache-maven-3.8.3/bin:/opt/homebrew/opt/postgresql@13/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/tada/.fig/bin:/Users/tada/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=2915
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by SeparateRecords** [comment]
Looks like it's working fine for me, so it's strange that it's broken for you. Would you be able to try running `env` and send us the output so we can see if there's anything in your environment that could cause this?

<img width="489" alt="Screen Shot 2022-05-13 at 10 55 47 am" src="https://user-images.githubusercontent.com/52195359/168190385-4637fa3c-6b6f-4a52-80b6-d6fabe75427f.png">

**Comment by chaynabors** [comment]
Hey @MasatoshiTada are you able to reproduce? We are unable to recreate this locally.

**Comment by MasatoshiTada** [comment]
@SeparateRecords @chaynabors Sorry for my late reply!

```bash
$ env
TERM_SESSION_ID=w0t0p0:91AC8F4A-874F-4555-900C-06B3896A827E
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.MWl5v9p8qs/Listeners
LC_TERMINAL_VERSION=3.4.15
COLORFGBG=7;0
ITERM_PROFILE=Default
XPC_FLAGS=0x0
LANG=ja_JP.UTF-8
PWD=/Users/tada
SHELL=/bin/zsh
__CFBundleIdentifier=com.googlecode.iterm2
SECURITYSESSIONID=186aa
TERM_PROGRAM_VERSION=3.4.15
TERM_PROGRAM=iTerm.app
PATH=/usr/local/opt/postgresql@13/bin:/Users/tada/apache-maven-3.8.2/bin:/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/tada/.fig/bin:/Users/tada/.local/bin
LC_TERMINAL=iTerm2
COLORTERM=truecolor
COMMAND_MODE=unix2003
TERM=xterm-256color
HOME=/Users/tada
TMPDIR=/var/folders/_p/sldnd5gx23b0h2nqm2qcqg9c0000gn/T/
USER=tada
XPC_SERVICE_NAME=0
LOGNAME=tada
LaunchInstanceID=EBEA881B-A39D-4731-BBEE-10C511FF5B72
__CF_USER_TEXT_ENCODING=0x1F5:0x1:0xE
ITERM_SESSION_ID=w0t0p0:91AC8F4A-874F-4555-900C-06B3896A827E
SHLVL=1
OLDPWD=/Users/tada
FIG_INTEGRATION_VERSION=8
FIG_TERM=1
FIG_TERM_VERSION=4.4.0
TTY=/dev/ttys006
FIG_PID=38411
AWS_PROFILE=***************
_=/usr/bin/env
```

**Comment by grant0417** [comment]
I would try updating and seeing if it works on the most recent version, we were unable to reproduce + this is stale so going to close.
