### ISSUE TITLE
Fig does not autocomplete "npm run" commands from the correct package.json-file

### ISSUE THREAD

**Issue by Damiqib** [withfig/fig#1407]
### Description:

Using VSCode / zsh.

I have multiple projects with `package.json` -files and they all have their own scripts. Fig's autocomplete for `npm run`-command seems to always suggest commands from the wrong project. Suggestions are wrong even if running commands from the project root, ie. where the project's `package.json` -file is.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.57 (B440)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B440) [Finnish] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/xxx/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by fedeci** [comment]
That's really strange. Have you tried restarting fig?

**Comment by chaynabors** [comment]
@Damiqib can you share the folder structure? Which package.json's scripts are being displayed? (Is it at the top level of the project?)

**Comment by rishavbhowmik** [comment]
@chaynabors 
It's easy to reproduce.

1. Create 2 project with npm in separate folder.

```sh
cd your/dir
mkdir proj1
mkdir proj2
cd proj1
npm init
cd ../proj2
npm init
```

2. In 1st project open package.json, add new scripts

```json
{
 "scripts": {
   "build-proj-1": "echo Project1Builds",
   "run-proj-1": "echo Project1Runs"
 }
}
```

In 2nd project open package.json, add new scripts

```json
{
 "scripts": {
   "build-proj-2": "echo Project2Builds",
   "run-proj-2": "echo Project2Runs"
 }
}
```

3. Now open 2 new terminal windows.

Navigate to both the project in each terminal window.

```sh
# Terminal 1
cd your/dir/proj1

# Try npm run with fig
npm run # Fig results: ["build-proj-1", "run-proj-1"] as expected
```

Everything is fine till this point

```sh
# Terminal 2
cd your/dir/proj2

# Try npm run with fig
npm run # Fig results: ["build-proj-1", "run-proj-1"] this is Not expected

# 10-15 seconds later
npm run # Fig results: ["build-proj-2", "run-proj-2"] as expected
```

Now if you go back to project1's terminal you will get result's of project2's package.json for few seconds

So I guess fig does not handle autocomplete for multiple project simultaneously. It relies on parsing the package.json when user starts typing in the terminal.

**Comment by lukebars** [comment]
Same with `yarn` scripts from `package.json`

**Comment by fedeci** [comment]
It should have been fixed a while ago, but I am giving a look into this!

**Comment by lukebars** [comment]
@fedeci is this issue fixed? Probably should be reopened

**Comment by lukebars** [comment]
@mschrage it self closed again 😄

**Comment by mschrage** [comment]
I'm just fighting the bot now!

**Comment by lukebars** [comment]
Looks to be working on `fig_cli 1.4.11`

**Comment by fedeci** [comment]
It has been fixed a while ago!

**Comment by lukebars** [comment]
Thanks @fedeci ❤️
