### ISSUE TITLE
Changing directory with alias causes hang

### ISSUE THREAD

**Issue by OneUpWallStreet** [withfig/fig#1408]
### Description:

I have a few aliases that I use to navigate the terminal , but when I use them with fig, my terminal + the fig application freezes. Than after a few seconds (around 5?) everything becomes normal.

Alias example
`alias dev="/Users/Arteezy/Developer"`

Terminal -> [iTerm2](https://iterm2.com/) + [ohmyzsh](https://github.com/ohmyzsh/ohmyzsh)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.57 (B440)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B440) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Arteezy/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/Arteezy/.fig/bin:/Users/Arteezy/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (18606) - /dev/ttys004
Current terminal session: w1t0p0:83383922-EAC2-46B3-A082-83640937C346
Current working directory: /Users/Arteezy/Developer
Current window identifier: 7872/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by OneUpWallStreet** [comment]
Delay is more like 15 seconds, and my mac also starts freezing.

**Comment by SeparateRecords** [comment]
Hey! Sorry for the delay @OneUpWallStreet - could you record a video of this happening? And would you be able to send your zshrc/zprofile?

**Comment by OneUpWallStreet** [comment]
> @OneUpWallStreet are you still running into this issue? I haven't been able to reproduce on my end so hopefully it's fixed -- but if it's still happening for you your zsh config would be super helpful to understand the root cause.

Hey, sorry for being unresponsive, I must have missed the notification for the previous comment. 

The issue was solved in one of the updates, because now I can cd using aliases without fig crashing. 

If you are still interested in my zsh config file please let me know otherwise we can close this issue :D
