### ISSUE TITLE
Figterm socket: Socket exists but could not connect

### ISSUE THREAD

**Issue by derektruong** [withfig/fig#1412]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|-zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/opt/python@3.8/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/opt/homebrew/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/derektruong/.nvm/versions/node/v10.24.1/bin:/Users/derektruong/.fig/bin:/Users/derektruong/.local/bin:/usr/local/mysql/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/derektruong
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 32184/% (com.googlecode.iterm2)
  - Active Process: ??? (???) - ???
  - Installed via Brew: true
  - Environment Variables:
    - FIG_PID=88953
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - PATH=/usr/local/opt/python@3.8/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/opt/homebrew/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/derektruong/.nvm/versions/node/v10.24.1/bin:/Users/derektruong/.fig/bin:/Users/derektruong/.local/bin:/usr/local/mysql/bin
    - TERM=xterm-256color
    - FIG_TERM=1
    - TERM_SESSION_ID=w0t1p0:B96AC9C2-AE67-4C7F-988F-0C934C0ABC6F
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Hey @derektruong! Is this error happening when you run `fig doctor`? Does Fig work otherwise or is something visibly broken.

**Comment by derektruong** [comment]
> Hey @derektruong! Is this error happening when you run `fig doctor`? Does Fig work otherwise or is something visibly broken.

Thank @mschrage I have already fixed this error after running `fix doctor` one more time. Close issue.
