### ISSUE TITLE
Increased memory usage?

### ISSUE THREAD

**Issue by Yousri** [withfig/fig#1414]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

![image](https://user-images.githubusercontent.com/110524/166853772-adcbd543-fd4c-4bf9-9087-363c371eb011.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.57 (B440)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B440) [搜狗拼音] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/yousri/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hi @Yousri - this is definitely a memory leak. I can't reproduce this but we've seen reports of similar memory usage. Are you using any particular CLIs? Has Fig been running for a while?

@mschrage @fedeci do you have any debugging tips for this?

(Referencing #1208 so that this issue gets linked)

**Comment by Yousri** [comment]
Fig takes up so much memory as soon as it starts up and hasn't been running for a while.
specific CLI? For example, which ones are specific, they are all CLIs that are used on a daily basis.

**Comment by SeparateRecords** [comment]
> Fig takes up so much memory as soon as it starts up and hasn't been running for a while
Could be an issue with history parsing or aliases... to rule out aliases as an issue, can you send the output of running `alias`?

> For example, which ones are specific, they are all CLIs that are used on a daily basis.
I mean to ask what CLIs you use. Standard stuff like git, yarn, ssh, ...? What are your most common tools? (don't need all of them, just your most frequent)

**Comment by Yousri** [comment]
alias:
![image](https://user-images.githubusercontent.com/110524/166864516-4e1e20a9-8ce8-4970-945c-8e34f4bbe294.png)

and the more commonly used CLI mainly include like kubectl,git,helm,ssh,terraform,docker and so on

**Comment by SeparateRecords** [comment]
Definitely seems like an issue with history parsing then. We'll look into this ASAP 🙂

**Comment by fedeci** [comment]
Since safari does not provide any memory leak debugging tool what I used last time was to try to isolate the leak.

**Comment by Yousri** [comment]
> 

@SeparateRecords So there is no other solution to deal with this now, just wait?

**Comment by SeparateRecords** [comment]
@fedeci is there a quick workaround? Which history files could this be? We'd want to keep a backup so that we can debug later, but definitely need fig to now be using this much RAM day to day.

**Comment by mschrage** [comment]
@sullivan-sean is adding a feature to disable history loading. 

@Yousri are you free for a debugging call? https://calendly.com/mschrage/30min

**Comment by chaynabors** [comment]
@Yousri did you ever manage to book a call with Matt? We'd love to figure out what's going on here!

**Comment by SeparateRecords** [comment]
Just so it's public, the setting to disable history loading is this:
```
fig settings autocomplete.history.disableLoading true
```

**Comment by rahulsarathy** [comment]
Closing this for now. Feel free to reach out if you're still running into errors!
