### ISSUE TITLE
bash: trap: __bp_install: invalid signal specification

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1415]
> I tested a bit in Iterm2 and things seem to be working, except that I have an error message printing after each command: "bash: trap: __bp_install: invalid signal specification".

Waiting for more info. If this is also happening to you, please let us know!

**Comment by mschrage** [comment]
This is likely a versioning conflict with  the`bash_preexec` library. If you are experiencing this, please download the latest version of the iTerm shell integration.

**Comment by faithoflifedev** [comment]
I'm experiencing the exact same issue.  I'm using iTerm2 3.4.16, which I believe is the most current version available at this time.  I see the above error when running `fig doctor`
