### ISSUE TITLE
Fig is not working

### ISSUE THREAD

**Issue by enrique-rga** [withfig/fig#1419]
### Description:
> After update fig, it no longer work. Fig doctor doesn't show any problem. 

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B439) [Spanish]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/enriquef/.amplify/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/enriquef/Documents/scripts:/usr/local/laps:/Users/enriquef/.cargo/bin:/Users/enriquef/.amplify/bin:/Users/enriquef/.fig/bin:/Users/enriquef/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/enriquef/dev/hawke/hawke-ibd-components
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 459/% (com.microsoft.VSCode)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=5053CD0A-5C80-4BAC-91CC-AD5DCF28346C
    - PATH=/Users/enriquef/.amplify/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/enriquef/Documents/scripts:/usr/local/laps:/Users/enriquef/.cargo/bin:/Users/enriquef/.amplify/bin:/Users/enriquef/.fig/bin:/Users/enriquef/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @enrique-rga, sorry it's not working for you.

Does this persist after completely restarting vscode and fig? And does it show in other terminal apps? (eg. iTerm, Terminal)

**Comment by enrique-rga** [comment]
Hi Robert! it’s not working in any terminal and y just complete restarted my mac.

From: Robert ***@***.***>
Date: Friday, 6 May 2022, 01:18
To: withfig/fig ***@***.***>
Cc: Enrique Fiorucci ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [withfig/fig] Fig is not working (Issue #1419)

Hey @enrique-rga<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fenrique-rga&data=05%7C01%7Cenrique.fiorucci%40rga.com%7Cead60b35aeb743b8654308da2f17701e%7C9725079efc4f44a4b797aa982bff3996%7C0%7C0%7C637874074971686756%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PecZVjQQMGxoy%2BKFBz1Jv7%2FQiWefGBzK0iTIxXrdPRs%3D&reserved=0>, sorry it's not working for you.

Does this persist after completely restarting vscode and fig? And does it show in other terminal apps? (eg. iTerm, Terminal)

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwithfig%2Ffig%2Fissues%2F1419%23issuecomment-1119246023&data=05%7C01%7Cenrique.fiorucci%40rga.com%7Cead60b35aeb743b8654308da2f17701e%7C9725079efc4f44a4b797aa982bff3996%7C0%7C0%7C637874074971686756%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bLzbi6J8dpQ7K%2FfkjTYwCsghBBwzk6p6X%2B3yFREId0k%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWEYAWQ5FPAWD7Q5BNRGQEDVISMQJANCNFSM5VFV5RSQ&data=05%7C01%7Cenrique.fiorucci%40rga.com%7Cead60b35aeb743b8654308da2f17701e%7C9725079efc4f44a4b797aa982bff3996%7C0%7C0%7C637874074971686756%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZNsKcXWJgZSwQXP%2FzH8rCwoY1G%2BvBa8K%2BBFjFEK5Hiw%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

R/GA
We design businesses and brands for a more human future

Uriarte 1572 (C1414DAP), Ciudad de Buenos Aires, Argentina
www.rga.com<http://www.rga.com> www.twitter.com/rga<http://www.twitter.com/rga> www.facebook.com/rga<http://www.facebook.com/rga>

________________________________

This message contains information which may be confidential and privileged. Unless you are the intended recipient (or are authorized to receive this message on behalf of the intended recipient), you may not copy, disseminate, or disclose this message or any information contained in this message. If you have received this message in error, please notify the sender by reply e-mail or forward the message to ***@***.*** and delete the message. Thank you very much.

**Comment by chaynabors** [comment]
Hey @enrique-rga, could you update to the latest version and let us know if that fixes your issue?

**Comment by enrique-rga** [comment]
Now it's working! Thanks

Enrique Fiorucci
________________________________
From: Chay Nabors ***@***.***>
Sent: Thursday, May 19, 2022 9:57:16 PM
To: withfig/fig ***@***.***>
Cc: Enrique Fiorucci ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [withfig/fig] Fig is not working (Issue #1419)


Hey @enrique-rga<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fenrique-rga&data=05%7C01%7Cenrique.fiorucci%40rga.com%7Ccf9111e47bda4339e3f908da39fbafae%7C9725079efc4f44a4b797aa982bff3996%7C0%7C0%7C637886050432596050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KAq28gOeMR9SISXDoMrJvfSOg%2B84XWc6FA4jrZEzeAU%3D&reserved=0>, could you update to the latest version and let us know if that fixes your issue?

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwithfig%2Ffig%2Fissues%2F1419%23issuecomment-1132338645&data=05%7C01%7Cenrique.fiorucci%40rga.com%7Ccf9111e47bda4339e3f908da39fbafae%7C9725079efc4f44a4b797aa982bff3996%7C0%7C0%7C637886050432596050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ahRZV9CPkRQ2ZrU5fwu4Zk8aaxxGQtJCnxlLOca%2FnFA%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWEYAWXNJSFSUNFYIDEKQQLVK3POZANCNFSM5VFV5RSQ&data=05%7C01%7Cenrique.fiorucci%40rga.com%7Ccf9111e47bda4339e3f908da39fbafae%7C9725079efc4f44a4b797aa982bff3996%7C0%7C0%7C637886050432596050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3K%2Fejz%2BMw5DZEcF1yk3JiKS%2BaHVc62Wj6qfAw0jam20%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

R/GA
We design businesses and brands for a more human future

Uriarte 1572 (C1414DAP), Ciudad de Buenos Aires, Argentina
www.rga.com<http://www.rga.com> www.twitter.com/rga<http://www.twitter.com/rga> www.facebook.com/rga<http://www.facebook.com/rga>

________________________________

This message contains information which may be confidential and privileged. Unless you are the intended recipient (or are authorized to receive this message on behalf of the intended recipient), you may not copy, disseminate, or disclose this message or any information contained in this message. If you have received this message in error, please notify the sender by reply e-mail or forward the message to ***@***.*** and delete the message. Thank you very much.

**Comment by rahulsarathy** [comment]
Closing this for now. Feel free to reach out if you're still running into errors!
