### ISSUE TITLE
Script run by double clicking doesn't execute, just opens terminal

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1423]
I think this is related to #446 but not 100% sure since that should be resolved now.

> I installed and was fine until I tried to double click a .sh script from my desktop. It just didn’t run the commands
> 
> It would open terminal and run .sh code. It just seem to skip right over it. (It opened and did nothing). It was some ssh and git commands)
>
> Zsh native terminal app

I can't reproduce this with zsh/Terminal, but can with fish/iTerm

**Comment by grant0417** [comment]
Going to close as we do not have details and can not repo
