### ISSUE TITLE
fig report error on lauching

### ISSUE THREAD

**Issue by nicolas-peridont** [withfig/fig#1424]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

fig report error on lauching  : 
→ Launching Fig...

Unable to finish launching Fig properly

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.57 (B440)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B440) [French] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/nicolasperidont/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @nicolas-peridont! What happens if you launch Fig from Spotlight search or directly from /Applications?

**Comment by rahulsarathy** [comment]
Closing this for now. Feel free to reach out if you're still running into errors!
