### ISSUE TITLE
Fig popup does not open even like everything looks like is working properly

### ISSUE THREAD

**Issue by icastillejogomez** [withfig/fig#1425]
### Description:

Fig popup does not open even if I use iTerm2 or VSCode terminal or default built-in OSX terminal. I ran `fig doctor` but it's still not working checking out everything apparently works as expected.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [Spanish]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/nacho/.nvm/versions/node/v16.15.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/nacho/.fig/bin:/Users/nacho/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro14,3
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/nacho
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 566/% (com.googlecode.iterm2)
  - Active Process: zsh (5540) - not a tty
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:14721E59-C908-4DA5-AEEF-5FD2372FB954
    - PATH=/Users/nacho/.nvm/versions/node/v16.15.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/nacho/.fig/bin:/Users/nacho/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=5540
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Very strange @icastillejogomez can you share your dotfiles here?

Also can you type "git com" (don't press enter) and then take a screenshot of the Fig debugger? It's found by pressing the Fig icon in the menu bar.

**Comment by SeparateRecords** [comment]
Just wanted to follow up on this @icastillejogomez 🙂 Would you be able to send that screenshot?
