### ISSUE TITLE
SSH connections from remote to machine with Fig are slower since installing Fig

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1426]
> I make a lot of ssh connections from remote servers to my workstation - those connections are slower since installing Fig (due to Fig auto-complete setup scripts from what I could see)

Not quite sure what could be happening here, need to do some testing

**Comment by cngarrison** [comment]
Fig wasn't the culprit, slow connections were due to networking (or something that was fixed with a restart).
