### ISSUE TITLE
Fig removes entries from $PATH

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1427]
Some people report that Fig changes their $PATH. This shouldn't be the case, but if this is happening for you we'd like to debug and figure out what could be causing this 🙂

**Comment by cngarrison** [comment]
When connecting to my workstation via ssh to run a single command (not a full login shell), I get this error:

`/Users/charlie/.local/share/fig/plugins/kube-aliases_Dbz/kube-aliases.plugin.zsh: line 8: kubectl: command not found`

My machine has `kubectl`:

```
$ which kubectl
/usr/local/bin/kubectl
```

If I edit `kube-aliases.plugin.zsh` with this at the top, then there is no error when connecting via ssh. 

`PATH=/usr/local/bin:$PATH`

The ssh `authorized_keys` on my workstation has the relevant keys/users set to a restricted script `command`:

`command="~/bin/restricted.sh",no-port-forwarding,no-X11-forwarding ssh-rsa AAAAB...blc= root@awshost`

**Comment by SeparateRecords** [comment]
@cngarrison thanks for the follow up! Would you be able to send your zshrc so I can try to repro? Happy to receive by email if you don't want to post it publicly.

Another thing to test, if you put `echo $PATH` _right before_ the final line of your config (which should be `fig init zsh post`), is /usr/local/bin included?

**Comment by cngarrison** [comment]
My shell is bash, do you want bashrc or zshrc? My bash_profile has this:

```
echo $PATH | grep -q -s "/usr/local/bin"
if [ $? -eq 1 ] ; then
    PATH=/usr/local/bin:$PATH
    export PATH
else
    PATH=${PATH/\/usr\/local\/bin\:}
    PATH=/usr/local/bin:$PATH
    export PATH
fi
```

**Comment by SeparateRecords** [comment]
My mistake - so many people use ZSH that I just assume that as the default 😅

Doesn't seem like the issue is with your config then. What is the contents of `~/bin/restricted.sh`?

**Comment by cngarrison** [comment]
Your query about `zsh` got me thinking about `.bashrc` vs `.bash_profile`. `PATH` was being updated with `/usr/local/bin` in `.bash_profile`. Moving that code block to `.bashrc` fixed the error reported. 

The relevant clue being that `.bash_profile` is only used for full login session, not just running a restricted command via ssh, which only uses `.bashrc`. I should have remembered that before reporting this error. 🤦
