### ISSUE TITLE
fig not work on MacOs Monterey 

### ISSUE THREAD

**Issue by runforprogram** [withfig/fig#1429]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.1.0 (21C52)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/run/.sdkman/candidates/gradle/current/bin:/opt/homebrew/opt/binutils/bin:/Users/run/tool/depot_tools_run:/Users/run/bin:/Users/run/Library/Android/sdk/platform-tools:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Applications/Wireshark.app/Contents/MacOS:/Users/run/.fig/bin:/Users/run/.local/bin:/Users/run/.fzf/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.1.0 (21C52)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/run/work/dev_next_android
  - CLI Installed: true
  - Executable Location: /Users/run/.fig/bin/fig
  - Current Window ID: 14578/% (com.googlecode.iterm2)
  - Active Process: zsh (97785) - /dev/ttys002
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:886BF04D-FA6C-47CD-9AF1-A6F417DB5076
    - PATH=/Users/run/.sdkman/candidates/gradle/current/bin:/opt/homebrew/opt/binutils/bin:/Users/run/tool/depot_tools_run:/Users/run/bin:/Users/run/Library/Android/sdk/platform-tools:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Applications/Wireshark.app/Contents/MacOS:/Users/run/.fig/bin:/Users/run/.local/bin:/Users/run/.fzf/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=97785
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false

</p>
</details>

**Comment by chaynabors** [comment]
Hey @runforprogram, thanks for reporting this! Would it be possible to share your `~/.zshrc` file here?
Also, could you run `fig doctor --verbose` and share the output here?

**Comment by rahulsarathy** [comment]
Closing this for now. Feel free to reach out if you're still running into errors!
