### ISSUE TITLE
Autocomplete not showing up at all

### ISSUE THREAD

**Issue by BrennerSpear** [withfig/fig#1430]
### Description:
Fig Autocomplete not showing up at all. when I type something like `git` or `gh` the fig window doesn't show up anymore

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.57|zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: true
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/brenner/.nvm/versions/node/v16.12.0/bin:/usr/local/bin:/usr/local/sbin:/Users/brenner/.nvm/versions/node/v16.12.0/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Users/brenner/.cargo/bin:/Users/brenner/.fig/bin:/Users/brenner/.local/bin:/Users/brenner/.yarn/bin:/Users/brenner/.yarn/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/brenner/repos/repo
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 9557/% (com.googlecode.iterm2)
  - Active Process: zsh (33599) - not a tty
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:B4487B8C-2E38-440A-99E2-48B6683C5878
    - PATH=/Users/brenner/.nvm/versions/node/v16.12.0/bin:/usr/local/bin:/usr/local/sbin:/Users/brenner/.nvm/versions/node/v16.12.0/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Users/brenner/.cargo/bin:/Users/brenner/.fig/bin:/Users/brenner/.local/bin:/Users/brenner/.yarn/bin:/Users/brenner/.yarn/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=33599
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
@BrennerSpear can you run `fig doctor --verbose`

**Comment by rahulsarathy** [comment]
Closing this for now. Feel free to reach out if you're still running into errors!
