### ISSUE TITLE
fig stucked when I finished the survey

### ISSUE THREAD

**Issue by crimson-gao** [withfig/fig#1432]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
I downloaded and installed fig on my mac, followed the installation instructions.
When configuring settings fro dot files, I saw the trial plan for syncing dot files.
After finished serveral qustions, I saw the thank you page below.
After I clicked the `Create a typeform` button, it stucked.
Closing the window, re input the command `fig` does not help. 

<img width="830" alt="image" src="https://user-images.githubusercontent.com/39024757/167697901-8874b199-d855-4b2a-ad49-2ec11dde33d0.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: <generated dynamically>
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 32 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/bytedance
  - CLI Installed: true
  - Executable Location: /Users/bytedance/.fig/bin/fig
  - Current Window ID: 10419/% (org.tabby)
  - Active Process: zsh (8692) - /dev/ttys008
  - Environment Variables:
    - PATH=/Users/bytedance/.nvm/versions/node/v16.14.2/bin:/Users/bytedance/.gvm/pkgsets/go1.16/global/bin:/Users/bytedance/.gvm/gos/go1.16/bin:/Users/bytedance/.gvm/pkgsets/go1.16/global/overlay/bin:/Users/bytedance/.gvm/pkgsets/go1.16/global/bin:/Users/bytedance/.gvm/bin:/Users/bytedance/.gvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/puppetlabs/bin:/Users/bytedance/.cargo/bin:/Users/bytedance/.fig/bin:/Users/bytedance/.local/bin:/usr/local/Cellar/mysql/8.0.28_1/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=039558EA-6443-4E89-8F9C-7E06E31A5CC2
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=8692
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Just press the "x" at the top!
