### ISSUE TITLE
Autocomplete Error loading spec ..  while in zsh, testing git completions

### ISSUE THREAD

**Issue by jbeimler** [withfig/fig#1437]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I get in Debugger (zsh) -> Autocomplete Error loading spec .. Make sure you're connected to the internet.

from the shell:

❯ fig doctor

✔ Everything looks good!

Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!

Please let me know if there is anything I can do to help troubleshoot.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/usr/local/Cellar/zsh/5.8_1/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [Dev] [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/jobeim/.local/share/virtualenvs/names-vV_zaHOp/bin:/usr/local/sbin:/Users/jobeim/.asdf/shims:/usr/local/opt/asdf/libexec/bin:/usr/local/opt/krb5/sbin:/usr/local/opt/krb5/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/sqlite/bin:/Users/jobeim/.asdf/installs/python/3.10.2/bin:/usr/local/sbin:/usr/local/opt/krb5/sbin:/usr/local/opt/krb5/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/sqlite/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/opt/X11/bin:/Library/Apple/usr/bin:/Users/jobeim/.fig/bin:/Users/jobeim/.local/bin:/Users/jobeim/.krew/bin:/usr/local/opt/fzf/bin:/Users/jobeim/.krew/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /usr/local/bin/zsh
  - Current Directory: /Users/jobeim/Projects/names
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 16651/% (com.googlecode.iterm2)
  - Active Process: zsh (42097) - /dev/ttys000
  - Environment Variables:
    - PATH=/Users/jobeim/.local/share/virtualenvs/names-vV_zaHOp/bin:/usr/local/sbin:/Users/jobeim/.asdf/shims:/usr/local/opt/asdf/libexec/bin:/usr/local/opt/krb5/sbin:/usr/local/opt/krb5/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/sqlite/bin:/Users/jobeim/.asdf/installs/python/3.10.2/bin:/usr/local/sbin:/usr/local/opt/krb5/sbin:/usr/local/opt/krb5/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/sqlite/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/opt/X11/bin:/Library/Apple/usr/bin:/Users/jobeim/.fig/bin:/Users/jobeim/.local/bin:/Users/jobeim/.krew/bin:/usr/local/opt/fzf/bin:/Users/jobeim/.krew/bin
    - FIG_PID=42097
    - TERM=xterm-256color
    - TERM_SESSION_ID=w1t0p0:8523BBF0-CFD6-40F5-960E-F7A3C10B2357
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by bramsmulders** [comment]
I have the same error, my diagnostics: 

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [Dutch]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/bram/.nvm/versions/node/v16.15.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/bram/.fig/bin:/Users/bram/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /Users/bram
  - CLI Installed: true
  - Executable Location: /Users/bram/.fig/bin/fig
  - Current Window ID: 103/% (co.zeit.hyper)
  - Active Process: zsh (688) - /dev/ttys001
  - Environment Variables:
    - PATH=/Users/bram/.nvm/versions/node/v16.15.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/bram/.fig/bin:/Users/bram/.local/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=C14BAAE3-C1B8-4BC1-A9AE-5AF8C26CD9E5
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=688
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: installed!
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by delysh** [comment]
Same here. Just stoped working. 

- macOS 12.3.1
- Fig version: Version 1.0.57 (B440) [ABC] 
- User Shell: /bin/zsh

**Comment by FraWolf** [comment]
Same for me, today Fig is not working.

<details>
  <summary></summary>

  # Fig Diagnostics
  ## Fig details:
    - Fig version: Version 1.0.57 (B440) [Italian]
    - Bundle path: /Applications/Fig.app
    - Autocomplete: true
    - Settings.json: true
    - Accessibility: true
    - Number of specs: 0
    - Symlinked dotfiles: false
    - Only insert on tab: false
    - Keybindings path: 
    - Installation Script: true
    - PseudoTerminal Path: /Users/francesco/.nvm/versions/node/v16.15.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/francesco/.fig/bin:/Users/francesco/.local/bin
    - SecureKeyboardInput: false
    - SecureKeyboardProcess: <none>
  ## Hardware Info:
    - Model Name: MacBook Air
    - Model Identifier: MacBookAir10,1
    - Chip: Apple M1
    - Cores: 8 (4 performance and 4 efficiency)
    - Memory: 16 GB
  ## OS Info:
    - macOS 12.3.1 (21E258)
  ## Environment:
    - User Shell: /bin/zsh
    - Current Directory: /Users/francesco/Desktop
    - CLI Installed: true
    - Executable Location: /Users/francesco/.fig/bin/fig
    - Current Window ID: 286/% (com.apple.Terminal)
    - Active Process: zsh (9502) - /dev/ttys002
    - Environment Variables:
      - TERM=xterm-256color
      - TERM_SESSION_ID=872533F0-B047-4F94-A7BC-FD3945788603
      - PATH=/Users/francesco/.nvm/versions/node/v14.19.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/francesco/.fig/bin:/Users/francesco/.local/bin
      - FIG_INTEGRATION_VERSION=8
      - FIG_TERM=1
      - FIG_TERM_VERSION=4.3.0
      - FIG_PID=9502
  ## Integrations:
    - SSH: false
    - TMUX: false
    - iTerm: application is not present.
    - Hyper: application is not present.
    - Visual Studio Code: installed!
    - Docker: false
 </details>

**Comment by joerg2503** [comment]
same for me

**Comment by Puppo** [comment]
Same for me

**Comment by conblem** [comment]
Same for me

**Comment by DavidKrenekCZ** [comment]
Same for me

**Comment by ajatkj** [comment]
Update: it's working now.

**Comment by SeparateRecords** [comment]
Hey everyone! Really sorry about this. CDN issue, so specs failed loading. It's fixed now and we've implemented a better fallback loading strategy to prevent this from happening in the future. Run `fig restart` if you're still having the issue. If that doesn't fix it, let us know and we'll reopen this issue.
