### ISSUE TITLE
my fig is not working

### ISSUE THREAD

**Issue by sinhadeepak1115** [withfig/fig#1438]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.57|/opt/homebrew/Cellar/zsh/5.8_1/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [ABC – India]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/deepak/.nvm/versions/node/v16.14.0/bin:/Users/deepak/opt/anaconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/deepak/.fig/bin:/Users/deepak/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /opt/homebrew/bin/zsh
  - Current Directory: /Users/deepak
  - CLI Installed: true
  - Executable Location: /Users/deepak/.fig/bin/fig
  - Current Window ID: 45117/% (com.googlecode.iterm2)
  - Active Process: zsh (49385) - /dev/ttys002
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:A2367326-BADC-4D04-B598-2A69D839AC4F
    - PATH=/Users/deepak/.nvm/versions/node/v16.14.0/bin:/Users/deepak/opt/anaconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/deepak/.fig/bin:/Users/deepak/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=49385
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Hi @sinhadeepak1115! I think this might have been the CDN issue we had yesterday, it's fixed now - just run `fig restart` and it should work. If it doesn't, let me know and I'll reopen the issue
