### ISSUE TITLE
[BASH] - Init script contains trailing `fi`

### ISSUE THREAD

**Issue by JanDeDobbeleer** [withfig/fig#1439]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/2492783/167997899-81505dd0-5625-40df-a5a8-2b14fbc3722c.png">

The init script coming from `~/.local/bin/fig init bash post --rcfile bashrc` contains a trailing `fi` at the end.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.57 (B446)|/usr/local/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B446) [Beta] [Dev] [ABC] 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jan/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /usr/local/opt/fzf/bin:/Users/jan/.local/bin:/Users/jan/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Worth noting that this is on the beta - highly reproducible. Still working fine on stable!

**Comment by grant0417** [comment]
A new beta should be available in the next hour or so with a fix for this!
