### ISSUE TITLE
Unable to use on vs-code terminal

### ISSUE THREAD

**Issue by Mohammed-Yasin-Mulla** [withfig/fig#1441]
### Description:
> I cannot use fig autocomplete on vs-code,  a msg saying connect to the internet.

### Details:
|macOS|Fig|Shell|
|-|-|-|
![Screenshot 2022-05-12 at 11 49 43 AM](https://user-images.githubusercontent.com/55092280/168004714-fcc13ed6-dccf-4516-b1f6-2064266ac4c0.png)

|12.3.1|Version 1.0.57 (B440)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B440) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/silver/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (1311) - /dev/ttys002
Current terminal session: 19D2E2E1-614C-48D9-BCAA-D0F596BAB833
Current working directory: /Users/silver/Documents/Flurn/React-Native/saturn
Current window identifier: 104/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @Mohammed-Yasin-Mulla, so sorry for the trouble. This was a CDN issue, but it's fixed now and we've implemented a fallback loading strategy so this doesn't happen again.
Run `fig restart` and it should work fine! Let us know if it doesn't and we'll reopen the issue.

**Comment by Mohammed-Yasin-Mulla** [comment]
Thank You!
