### ISSUE TITLE
Currently unable to load Fig in iTerm

### ISSUE THREAD

**Issue by LockedDB** [withfig/fig#1442]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B446) [Beta] [Spanish]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/danibenet/.fig/bin:/Users/danibenet/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: 
  - Cores: 8
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/danibenet/Desktop/svd-mobile-app
  - CLI Installed: true
  - Executable Location: /Users/danibenet/.fig/bin/fig
  - Current Window ID: 13498/% (com.googlecode.iterm2)
  - Active Process: zsh (21994) - /dev/ttys006
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p1:EE78161F-B3A9-4987-A2BF-9B3D2C8B4B5A
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/danibenet/.fig/bin:/Users/danibenet/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=21994
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by ajatkj** [comment]
Update: it's working now.

**Comment by SeparateRecords** [comment]
@LockedDB this was an issue with the CDN, but it's fixed now. If it's still not working, run `fig restart` and it should start fine. If that doesn't help let us know and we'll debug 🙂
