### ISSUE TITLE
Welp! Something broke on version 1.0.57

### ISSUE THREAD

**Issue by girishk21** [withfig/fig#1444]
### Description:

![image](https://user-images.githubusercontent.com/61074716/168019951-dd53b280-ef64-4ebd-8792-c97ba0b78da3.png)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.0.1 (21A559)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [ABC – India]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 198
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/opt/mysql-client/bin:/opt/homebrew/opt/sqlite/bin:/Users/girish/.nvm/versions/node/v14.17.6/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/girish/.cargo/bin:/Users/girish/.fig/bin:/Users/girish/.local/bin:/Users/girish/Library/flutter/flutter/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB
## OS Info:
  - macOS 12.0.1 (21A559)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/girish/Work/idatagenie/src/frontend
  - CLI Installed: true
  - Executable Location: /Users/girish/.fig/bin/fig
  - Current Window ID: 428002/% (com.apple.Terminal)
  - Active Process: zsh (21794) - not a tty
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=E3E151A3-AE92-4680-A4A0-9CF23FF20F1A
    - PATH=/opt/homebrew/opt/mysql-client/bin:/opt/homebrew/opt/sqlite/bin:/Users/girish/.nvm/versions/node/v14.17.6/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/girish/.cargo/bin:/Users/girish/.fig/bin:/Users/girish/.local/bin:/Users/girish/Library/flutter/flutter/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=21794
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by ajatkj** [comment]
Update: it's working now.

**Comment by girishk21** [comment]
it looks like it is working now 🪄
