### ISSUE TITLE
fig run but I have no autocompletion

### ISSUE THREAD

**Issue by Vimeux** [withfig/fig#1449]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hello,

Fig works, but when I type a command like "cd" I have no autocompletion.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [French]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/admin/.fig/bin:/Users/admin/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: iMac
  - Model Identifier: iMac17,1
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/admin
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 3600/% (com.googlecode.iterm2)
  - Active Process: zsh (7000) - /dev/ttys002
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:76165319-65F6-4EEF-8F2F-FA488095B12B
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/admin/.fig/bin:/Users/admin/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=7000
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @Vimeux, sorry about the inconvenience. CDN went down and specs couldn't be loaded. Run `fig restart` and it should restore functionality 🙂

If it's still broken, let me know and I'll reopen the issue!
