### ISSUE TITLE
Fig autocomplete suddenly broken

### ISSUE THREAD

**Issue by n3akr** [withfig/fig#1451]
### Description:
All of a sudden **fig** autocompletion stopped working.
`fig doctor` says everything is ok (as you can see on screenshot).
Reinstalling **fig** didn't help. Autocomplete doesn't work with bash/zsh in iterm.app and in terminal.app

Please ping me if I can help with reproducing the issue.

### Details:
|MacOS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh master (4674384d)|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mykolazakroishchykov/.fig/bin:/Users/mykolazakroishchykov/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/mykolazakroishchykov
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 305/% (com.googlecode.iterm2)
  - Active Process: zsh (5700) - /dev/ttys001
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:05CF55C3-C2AA-4FA0-BD50-212769533935
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mykolazakroishchykov/.fig/bin:/Users/mykolazakroishchykov/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=5700
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: true

</p>
</details>

![](https://i.imgur.com/UYyXKIi.png)

**Comment by SeparateRecords** [comment]
Hey @n3akr - this is fixed now! Sorry for the trouble. We've implemented a fix that should prevent this from happening in the future. Running `fig restart` should restore functionality. Let us know if that doesn't work and we'll debug with you 🙂
