### ISSUE TITLE
Fig Error: Autocomplete: Error loading spec index. Make sure you're connected to the internet

### ISSUE THREAD

**Issue by Mhairi-Helen** [withfig/fig#1452]
### Description:

- Fig not working in terminal both iTerm and VS code
- Ran `fig doctor` which prompted me to log in with a one time code and fixed my auth token
- `fig doctor` now reports that everything looks good but debugger says "Autocomplete: Error loading spec index. Make sure you're connected to the internet" - as i can raise this bug you can see that I'm connected to the internet
- When I disabled/reenabled autocomplete the error then read "Not tracking window"
- After following the instructions to navigate away and back to the terminal window the error returned to "Autocomplete: Error loading spec index. Make sure you're connected to the internet"
- I have tried restarting both Fig and my terminals

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.57 (B440)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B440) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/mhairi/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mhairi/.fig/bin:/Users/mhairi/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by gerjunior** [comment]
Same happening here!

**Comment by ayoush-wal** [comment]
same happening here!

**Comment by lz397548123** [comment]
Same happening here!

**Comment by ajatkj** [comment]
Update: it's working now.

**Comment by SeparateRecords** [comment]
Hey! So sorry about this incident. Our CDN went down so specs couldn't be loaded. Running `fig restart` should restore autocomplete. If not, please let me know and I'll reopen this issue.

(@ajatkj -- I am so sorry about all the notifications you're getting from me! 😅)

**Comment by Mhairi-Helen** [comment]
Thank you!
