### ISSUE TITLE
Autocomplete: Error loading spec index. Make sure you're connected to the internet

### ISSUE THREAD

**Issue by ayoush-wal** [withfig/fig#1453]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [ABC – India]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: <generated dynamically>
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/ayoushchourasia
  - CLI Installed: true
  - Executable Location: /Users/ayoushchourasia/.fig/bin/fig
  - Current Window ID: 99/% (com.apple.Terminal)
  - Active Process: zsh (4712) - /dev/ttys002
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=85885568-F5EE-4B28-89E3-2D5DC8ED7AF2
    - PATH=/opt/miniconda3/bin:/opt/miniconda3/condabin:/Users/ayoushchourasia/.nvm/versions/node/v11.10.1/bin:/usr/local/opt/libpq/bin:/Users/ayoushchourasia/.asdf/shims:/Users/ayoushchourasia/.asdf/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/ayoushchourasia/.fig/bin:/Users/ayoushchourasia/.local/bin:/usr/local/sbin:/usr/local/mysql-8.0.28-macos11-arm64/bin:/Users/ayoushchourasia/Work/Developer/flutter/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=4712
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by radzio** [comment]
Same to me. 

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [Polish Radek]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/radek/.fig/bin:/Users/radek/.local/bin:/Users/radek/Library/Android/sdk/emulator:/Users/radek/Library/Android/sdk/tools:/Users/radek/Library/Android/sdk/tools/bin:/Users/radek/Library/Android/sdk/platform-tools
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/radek
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 696/% (com.googlecode.iterm2)
  - Active Process: zsh (2225) - not a tty
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:EA519C5F-3192-4244-B76E-E2064A38CA66
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/radek/.fig/bin:/Users/radek/.local/bin:/Users/radek/Library/Android/sdk/emulator:/Users/radek/Library/Android/sdk/tools:/Users/radek/Library/Android/sdk/tools/bin:/Users/radek/Library/Android/sdk/platform-tools
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=2225
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by ajatkj** [comment]
Update: it's working now.

**Comment by SeparateRecords** [comment]
Hi @ayoush-wal, sorry for this! Running `fig restart` should bring back autocomplete. It was an issue with the CDN and we've got it fixed now. If that doesn't help, let us know and we'll reopen this issue 🙂

**Comment by radzio** [comment]
Works now, thx :)
