### ISSUE TITLE
error loading spec index

### ISSUE THREAD

**Issue by indrapalijama** [withfig/fig#1454]
### Description:
fig autocomplete not working (error loading spec index), 
it says that i didn't connect to internet even tho my internet is on.
picture attached : 
![Screen Shot 2022-05-12 at 11 39 13 PM](https://user-images.githubusercontent.com/33986004/168125908-1245015a-7713-452e-b27e-9541f702853f.png)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 206
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home/bin:/Users/fulk/.nvm/versions/node/v12.20.2/bin:/usr/local/mysql/bin:/opt/anaconda3/bin:~/Library/Android/sdk/platform-tools:/Users/fulk/bin:/usr/local/bin:/Users/fulk/.spicetify:/Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home/bin:/Users/fulk/.nvm/versions/node/v10.23.0/bin:/usr/local/mysql/bin:/opt/anaconda3/bin:/Users/fulk/Library/Android/sdk/platform-tools:/Users/fulk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/fulk/.fig/bin:/Users/fulk/Library/flutter/bin:/Users/fulk/.local/bin:/Users/fulk/Library/flutter/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro14,1
  - Chip: 
  - Cores: 2
  - Memory: 8 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/fulk/Documents/Freelance/Polda Maluku/sdm-polda-mobile-flutter
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 24894/% (com.microsoft.VSCode)
  - Active Process: zsh (96563) - /dev/ttys007
  - Environment Variables:
    - PATH=/Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home/bin:/Users/fulk/.nvm/versions/node/v12.20.2/bin:/usr/local/mysql/bin:/opt/anaconda3/bin:~/Library/Android/sdk/platform-tools:/Users/fulk/bin:/usr/local/bin:/Users/fulk/.spicetify:/Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home/bin:/Users/fulk/.nvm/versions/node/v10.23.0/bin:/usr/local/mysql/bin:/opt/anaconda3/bin:/Users/fulk/Library/Android/sdk/platform-tools:/Users/fulk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/fulk/.fig/bin:/Users/fulk/Library/flutter/bin:/Users/fulk/.local/bin:/Users/fulk/Library/flutter/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=7B334B92-5E5F-48B3-B1DF-88DCE1C66FBF
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=96563
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @indrapalijama! Sorry about this incident. We've fixed it and implemented a fallback loading strategy so this doesn't happen again. Running `fig restart` should bring back autocomplete if it's not working for you yet. If not, let me know and I'll reopen the issue 🙂

**Comment by indrapalijama** [comment]
> Hey @indrapalijama! Sorry about this incident. We've fixed it and implemented a fallback loading strategy so this doesn't happen again. Running `fig restart` should bring back autocomplete if it's not working for you yet. If not, let me know and I'll reopen the issue 🙂

it's working now, thanks!
