### ISSUE TITLE
Fig is not working

### ISSUE THREAD

**Issue by araqelyanedgar** [withfig/fig#1455]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/edgararakelyan/.fig/bin:/Users/edgararakelyan/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/edgararakelyan/Desktop/Swift Homework/Zoo
  - CLI Installed: true
  - Executable Location: /Users/edgararakelyan/.fig/bin/fig
  - Current Window ID: 9788/% (com.apple.Terminal)
  - Active Process: zsh (56857) - /dev/ttys005
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=B70EC459-8B1C-4F03-BEF6-52F7B4043C93
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/edgararakelyan/.fig/bin:/Users/edgararakelyan/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=56857
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by lowercase00** [comment]
Same here
<details>
  <summary>fig diagnostic</summary>
  
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B446) [Beta] [Brazilian - Pro]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: <generated dynamically>
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: iMac Pro
  - Model Identifier: iMacPro1,1
  - Chip: 
  - Cores: 6
  - Memory: 32 GB
## OS Info:
  - macOS 11.6.5 (20G527)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/carvalho/Documents/Develop/Compass/compass-back
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 89/% (com.microsoft.VSCode)
  - Active Process: zsh (3322) - /dev/ttys001
  - Environment Variables:
    - PATH=/Users/carvalho/Documents/Develop/Compass/compass-back/.venv/bin:/Users/carvalho/.krew/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/carvalho/.pyenv/shims:/Users/carvalho/.nvm/versions/node/v17.4.0/bin:/Users/carvalho/.pyenv/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/carvalho/.fig/bin:/Users/carvalho/.local/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=9ABDF0B3-62E8-467B-9A1F-814281FCF554
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=3322
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
 </details>

**Comment by SeparateRecords** [comment]
Hey @araqelyanedgar @lowercase00 ! We've fixed the issue now, it was a problem with the cdn. Restart fig with `fig restart` and it should resume working. If that doesn't help, let me know and we'll reopen the issue!
