### ISSUE TITLE
"Autocomplete: error loading spec index. Make sure you are connected to the internet."

### ISSUE THREAD

**Issue by TrentHurlbut** [withfig/fig#1456]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I am connected to the internet. 

Here is what the debugger is saying:

![Screen Shot 2022-05-12 at 9 52 26 AM](https://user-images.githubusercontent.com/75756310/168127961-2ef2b406-36ac-41af-a0c9-1533fc3122a0.png)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/boxert86/.nvm/versions/node/v12.22.3/bin:/opt/homebrew/opt/postgresql@13/bin:/Users/boxert86/.rbenv/shims:/opt/homebrew/opt/ruby/bin:/Users/boxert86/.pyenv/shims:/Library/Frameworks/Python.framework/Versions/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/boxert86/.fig/bin:/Users/boxert86/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/boxert86
  - CLI Installed: true
  - Executable Location: /Users/boxert86/.fig/bin/fig
  - Current Window ID: 104162/% (com.googlecode.iterm2)
  - Active Process: zsh (44271) - not a tty
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:7E53246E-3C20-42EB-A5A8-9B9E493A8B41
    - PATH=/Users/boxert86/.nvm/versions/node/v12.22.3/bin:/opt/homebrew/opt/postgresql@13/bin:/Users/boxert86/.rbenv/shims:/opt/homebrew/opt/ruby/bin:/Users/boxert86/.pyenv/shims:/Library/Frameworks/Python.framework/Versions/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/boxert86/.fig/bin:/Users/boxert86/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=44271
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Hi @TrentHurlbut - sorry about this! We've fixed the problem and implemented a more resilient loader so this doesn't happen again. Run `fig restart` to bring back autocomplete. Let us know if it's still not working and we'll look into it!

**Comment by TrentHurlbut** [comment]
Worked like a charm! Thanks, @SeparateRecords... I didn't realize how much I used AutoComplete until it was gone!
