### ISSUE TITLE
Fig not providing auto-complete, settings window crashes and shows "Something went wrong :(".

### ISSUE THREAD

**Issue by tom-cline** [withfig/fig#1459]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Fig autocomplete is not working, and when I open the settings window it crashes to "Something went wrong :(".  I've reinstalled Fig and am still seeing the same issues.

I've run `fig doctor` and all of the checks passed. 

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.57 (B440)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B440) [Beta] [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/tom/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by tom-cline** [comment]
Might be duplicate of https://github.com/withfig/fig/issues/1419

**Comment by mschrage** [comment]
Hey @tom-cline! Try running `fig login` in the terminal and then restart the Fig app.

**Comment by DonPwrShellHunt** [comment]
I was experiencing the same symptoms on MacOS Catalina, using zsh and with Fig version 1.0.57 installed via brew. I followed the instructions @mschrage provided, and it cleared up my problem with the settings crashing. Thanks!

**Comment by rahulsarathy** [comment]
Hi @tom-cline, thanks for reporting this issue

Could you try:

1. Right clicking the window
2. Clicking Inspect Element
3. Sending us a screenshot of the console output?

**Comment by rahulsarathy** [comment]
Closing this for now. Feel free to reach out if you're still running into errors!
