### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by Sohampatra1** [withfig/fig#1460]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.57 (B440)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B440) [ABC – India] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/soham/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (26091) - not a tty
Current terminal session: D1823D9D-3B7D-43CC-9242-4874B1DD4E75
Current working directory: /Users/soham
Current window identifier: 1659/% (io.alacritty)</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @Sohampatra1, could you give us more details on what is going on for you? A screen recording would be good!

**Comment by Sohampatra1** [comment]
Issue was already fixed, Thank you
