### ISSUE TITLE
Custom CSS in autocomplete

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1464]
Adding a proper, fully-featured theme system would be good but adding the ability for people that want to live on the edge to insert custom CSS would be a quick solution that gives more flexibility overall, at the cost of breaking occasionally.

**Comment by HomemadeToast57** [comment]
Exactly. I think this would really improve the experience, allowing users to make it "their own." If it breaks, they should be able to click a simple reset/restore in the fig app.

**Comment by SeparateRecords** [comment]
Hey @HomemadeToast57! Just got this implemented.

I don't want to document it publicly because it's more of a workaround to a _lack_ of feature, than a feature itself. But here's the basics:

## Docs

The setting is named `autocomplete.userStyles`. It takes a string.

You can use the following command to write to it:
```bash
fig settings autocomplete.userStyles "YOUR CSS HERE"
```

To delete your styles, use this command:
```bash
fig settings autocomplete.userStyles --delete
```

### Useful IDs and classes

* `#suggestionsContainer` is the main container, this is what the shadow, margin, background-color, and border-radius is applied to
* `.suggestion` is the div containing the suggestion, it has 2 children, a div (icon) and span (text)
* `.active-item` is the blue suggestion, in fig nomenclature the "selected" item

You can inspect the markup by right clicking on the popup and choosing "Inspect Element".

## Editing your styles

My workflow is to use a file to edit, then the command below to save. Note that the file is _totally arbitrary_, it's purely just so I can use Vim 😛

```bash
fig settings autocomplete.userStyles "$(cat ~/.config/fig.css)"
```

## Example

Here's how mine is customized right now. Note the more subtle border and shadow - the CSS is included in the screenshot (and also below).

<img width="741" alt="Screenshot of Autocomplete showing a light border and subtle shadow" src="https://user-images.githubusercontent.com/52195359/174222192-4b8ab8a9-45c6-48ad-8c98-02e0b70d89b3.png">

<detail>
<summary>My CSS</summary>

```css
#suggestionsContainer {
  box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.2), 0 2px 4px -2px rgb(0 0 0 / 0.1);
  border: rgba(255, 255, 255, 0.1) 1px solid;
  margin: 3px 3px 6px;
}
```

</detail>
