### ISSUE TITLE
autocomplete not working

### ISSUE THREAD

**Issue by bjornole-kodehode** [withfig/fig#1465]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
So the fig doctor says everything is fine, but when I ex use cd it wont give me the autocomplete.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.5.1 (20G80)|1.0.57|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [Dev] [Norwegian]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/bjornole/.fig/bin:/Users/bjornole/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro14,1
  - Chip: 
  - Cores: 2
  - Memory: 8 GB
## OS Info:
  - macOS 11.5.1 (20G80)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/bjornole
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 20589/% (com.apple.Terminal)
  - Active Process: bash (15151) - /dev/ttys008
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=2C006B4D-C711-438C-8858-603F52419EC1
    - PATH=/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/bjornole/.fig/bin:/Users/bjornole/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Hey! Thanks for raising this. Would you be able to type out `git commit` (don't press enter) then send a screenshot of the debugger again?

**Comment by SeparateRecords** [comment]
That's also helpful! Rules out at least one thing that it could be. This is the debugger I was meaning:

<img width="612" alt="Screen Shot 2022-05-20 at 7 42 37 pm" src="https://user-images.githubusercontent.com/52195359/169501458-718719d4-52c0-4b43-9512-b2a60839397c.png">

**Comment by bjornole-kodehode** [comment]
ohh of course, my bad haha

<img width="917" alt="image" src="https://user-images.githubusercontent.com/93578742/169508006-d04a9211-50f5-42a0-9da7-7772629ac0b5.png">

**Comment by SeparateRecords** [comment]
Fantastic! Any idea what fixed it?
