### ISSUE TITLE
Background cpu usage/energy impact

### ISSUE THREAD

**Issue by sanarena** [withfig/fig#1468]
### Description:
When a fig is not even in use (terminal in background etc..), it uses CPU and impacts energy usage.
It is expected when the fig-enabled window is in the background, it should remain on 0 energy impact.

![image](https://user-images.githubusercontent.com/1212959/168579088-2567b9e2-50c5-4e25-b339-5db580b923bc.png)
![image](https://user-images.githubusercontent.com/1212959/168579570-f7fefd0b-92bb-4ef0-ad61-7b967264ee7a.png)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B440) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: <generated dynamically>
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/armin
  - CLI Installed: true
  - Executable Location: /Users/armin/.fig/bin/fig
  - Current Window ID: 36775/% (com.apple.Terminal)
  - Active Process: zsh (66505) - /dev/ttys015
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=17233209-251D-4BAE-9AF9-E7BA7D4307FC
    - PATH=/opt/homebrew/opt/php@7.4/sbin:/opt/homebrew/opt/php@7.4/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/Users/armin/.fig/bin:/Users/armin/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=66505
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by rahulsarathy** [comment]
Hi @sanarena, 

We need to run fig in the background to determine the current active application. The energy usage is actually pretty normal if you look at the 12 hour power usage. 

Let us know if you have any other issues!
