### ISSUE TITLE
unable to access settings

### ISSUE THREAD

**Issue by fredol** [withfig/fig#1471]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Trying to display my settings, "Something went wrong :(" appears and I can't go on. I tried to restart, same result

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.57 (B450)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B450) [French – Numerical] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/frederic/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/frederic/.local/bin:/Users/frederic/.fig/bin:/Users/frederic/.local/bin:/Users/frederic/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by rahulsarathy** [comment]
Could you try:
1. Right clicking the window
2. Clicking Inspect Element
3. Sending us a screenshot of the console output

**Comment by nc-kaos** [comment]
I know I did not report this issue, but I have exactly same problem: please find screenshot below.

![image](https://user-images.githubusercontent.com/84022649/184142812-c995f8f3-30c3-4b89-9d0d-ec21e136d89c.png)

**Comment by nc-kaos** [comment]
To add to things, I recreated API request using Postman and it was successful - it returned my ID and access_token.

**Comment by rahulsarathy** [comment]
This looks like it was an issue with our backend uptime at the time of this issue creation. Can you let me know if this error persists?
