### ISSUE TITLE
Maintain version release notes or changelog

### ISSUE THREAD

**Issue by natelandau** [withfig/fig#1474]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Feature Details

Perhaps I've missed something completely obvious but I can't find release notes for Fig.  Today Homebrew notified me that Fig was ready to be updated on my Mac.  As I always do, I searched for release notes to understand what has changed since my previously installed version and I couldn't find them anywhere.  

Considering the technical nature of most (if not all) users of Fig, I believe maintaining a public changelog on Github that users could review prior to updating would greatly benefit the community.

**Comment by grant0417** [comment]
Hey @natelandau, this is definitely something we want to improve on, curious what type of changes are you looking for? We usually post change logs in our discord on major release but where would be most convenient for you?

**Comment by natelandau** [comment]
@grant0417 , I'm very glad that the change log is available on your Discord and, honestly, that does technically solve the issue I am referring to.  

That said, I am old and cranky and set in my ways and don't use Discord often.  I am a believer in publicly available information that doesn't require a username/pass to access and would love to see your changelog available on the web.  It could be available in [your documentation](https://fig.io/docs/getting-started) or as a CHANGELOG.md in this Github repository.  

Doing so would allow automations to be built off of tracking changes to the file, Google searches for changes to bring up results, and generally be useful for the three people in the world like myself who don't like change.  Ha!

Thanks for the great software.  Very excited to see this continue to evolve.

**Comment by SeparateRecords** [comment]
I think a changelog.md file here and a blog post on https://fig.io/blog would be good! We'll try to have this done for the next release 🙂

**Comment by rahulsarathy** [comment]
Closing this for now. Feel free to reach out if you're still running into errors!
