### ISSUE TITLE
Fig didn't work, tried restarting Fig, terminal

### ISSUE THREAD

**Issue by LanYunDev** [withfig/fig#1475]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig didn't work, tried restarting Fig, terminal
<img width="744" alt="image" src="https://user-images.githubusercontent.com/95263282/169006204-e0aef279-5a5d-4acd-9875-d1452ba17ecf.png">
<img width="745" alt="image" src="https://user-images.githubusercontent.com/95263282/169006213-df36fb7e-7a8f-40f5-b78a-65119fcc3e96.png">
<img width="745" alt="image" src="https://user-images.githubusercontent.com/95263282/169006501-c2b4f9c3-5704-4338-aa09-d7ff5ba9a35f.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.57 (B450)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B450) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/lanyun/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /opt/local/sbin:/opt/local/bin:/Users/lanyun/.oh-my-zsh/custom/plugins/git-open:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/lanyun/.pyenv/shims:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/aria2/bin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/lanyun/.fig/bin:/Users/lanyun/.local/bin:/Users/lanyun/.fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by rahulsarathy** [comment]
Hi @LanYunDev, thanks for sharing this issue

1. Could you share a screen recording with the command `fig debug logs` open
2. If the issue persists, feel free to sign up for a slot at https://calendly.com/withfig/debugging

**Comment by LanYunDev** [comment]
The problem still exists.
![2022-05-20 09 19 53](https://user-images.githubusercontent.com/95263282/169430066-29ee659f-350b-4db8-b009-cf2b86d02f39.gif)

**Comment by rahulsarathy** [comment]
Closing this for now. Feel free to reach out if you're still running into errors!
