### ISSUE TITLE
Confirmation email never comes

### ISSUE THREAD

**Issue by marcelo-tm** [withfig/fig#1476]
I'm trying to setup Fig on my macbook pro 2017 (intel), so I get to the step that I need an confirmation code sent by email, but the email never comes...

**Comment by rahulsarathy** [comment]
Hi @marcelo-tm, thanks for reporting this issue

Two things to follow up here:

1. Can you try running `fig login` in your terminal?

2. Can you check your spam folder and see if the email was sent there?

**Comment by GuoXiaoyang** [comment]
It is the same here. I have tried many times and have checked my spam folder, but haven't received the confirmation email.

**Comment by aliazani** [comment]
Same problem here.

**Comment by SimpelMe** [comment]
Updated fig to newest version in brew but still no confirmation email. Spam folder checked. Why to login? I can't remember I had done this before?

**Comment by rahulsarathy** [comment]
We were having some issues with our authentication server during the time of this creation, but they have since been fixed. Are you still running into this issue?

**Comment by rahulsarathy** [comment]
Thanks for submitting this report and helping us out!

**Comment by odonckers** [comment]
Unfortunately, this issue is present again now. I am unable to login into my account since no email ever comes.
