### ISSUE TITLE
Fig has no permission after switch to a new created system user

### ISSUE THREAD

**Issue by visla-jiaozebo** [withfig/fig#1478]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

<img width="465" alt="image" src="https://user-images.githubusercontent.com/105836705/169218943-0e0080c8-d4f5-4fba-b82d-7827c07a566d.png">

### Fig Doctor:
```
fig doctor

● /Users/visla/.bashrc does not source post integration last
✘ Fig socket exists: Fig socket parent directory does not exist
  Path: /var/tmp/fig/visla/fig.socket
Attempting to fix automatically...
Failed to fix: Permission denied (os error 13)


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!

```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.57 (B450)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B450) [搜狗拼音] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/visla/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/visla/.fig/bin:/Users/visla/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: 19769/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @visla-jiaozebo! Can you share the output of `ls -l /tmp/fig/*`?

**Comment by SeparateRecords** [comment]
Following up on this, @visla-jiaozebo would you be able to send the output of that command? That way we can understand better what's happening here :)

**Comment by rahulsarathy** [comment]
Closing this for now. Feel free to reach out if you're still running into errors!
