### ISSUE TITLE
Autocomplete popup appears in wrong terminal

### ISSUE THREAD

**Issue by jessgoldq4** [withfig/fig#1480]
### Description:
> When writing command in macos zsh terminal, and vscode terminal is open as well, the autocomplete popup appears in the wrong terminal (vscode), and sometimes doesn't work at all

Vscode onscreen:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/90337173/169355599-236932fa-eb6f-4e72-ba61-9f3c373a1757.png">

Vscode offscreen:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/90337173/169355783-0bdf7896-acb6-4ac8-ad80-58cc30ab1c4a.png">

Fig not working at all (seems unrelated as this still occurs even when vscode is closed):
<img width="354" alt="image" src="https://user-images.githubusercontent.com/90337173/169355987-444362e3-f3e1-44f0-8c3f-3ea70327d3e5.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [Canadian English]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/jessicagold/bin/Sencha/Cmd:/Users/jessicagold/.nvm/versions/node/v14.19.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/jessicagold/.rover/bin:/Users/jessicagold/.fig/bin:/Users/jessicagold/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/jessicagold
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 41400/% (com.microsoft.VSCode)
  - Active Process: zsh (94496) - /dev/ttys006
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=DBA233B1-6D03-4E75-B70F-042274BD3ABA
    - PATH=/Users/jessicagold/bin/Sencha/Cmd:/Users/jessicagold/.nvm/versions/node/v14.19.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/jessicagold/.rover/bin:/Users/jessicagold/.fig/bin:/Users/jessicagold/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=94496
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by mschrage** [comment]
Hey @jessgoldq4! Thanks for reporting this. Would you be open to jumping on a call with me to debug?

https://calendly.com/mschrage/30min

**Comment by jessgoldq4** [comment]
@mschrage Sure! Let me know when you have some time

**Comment by jessgoldq4** [comment]
Seems like it's working now, haha. Had to flip the accessibility permissions on and off :)
