### ISSUE TITLE
Fig App wont start when opening.

### ISSUE THREAD

**Issue by Gustafssonz** [withfig/fig#1481]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When Cmd+Space bar to open Fig, the desktop application will not open when clicked. I have to force quit it in activity monitor.

I have icon hidden in bar but now I have to show it since otherwise I can't access fig. 

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.57 (B450)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B450) [Swedish] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/niklas/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/niklas/.nvm/versions/node/v16.15.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/niklas/.fig/bin:/Users/niklas/.local/bin:/Users/niklas/Library/Android/sdk/emulator:/Users/niklas/Library/Android/sdk/platform-tools
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mattstein** [comment]
@rahulsarathy Just ran into this myself with 1.0.61 on macOS 12.6 (M1). Fig does its autocompletion in iTerm2, but the app icon and main window never appear. Works to force quit from Activity Monitor.app and re-launch.
