### ISSUE TITLE
Fig sometimes ignores aliases within autocomplete

### ISSUE THREAD

**Issue by hamlim** [withfig/fig#1482]
### Description:

I have a few aliases for git operations that seem to trip up fig's autocomplete but only sometimes 🤔 

Example:

- `git co` is an alias for `git checkout`
- `git br` is an alias for `git branch`

Typing `git co <start of branch name here>` fig seems to get hung up on trying to autocomplete to `git commit` instead. Typing `git br` fig will try to autocomplete to `git branch`.

This mainly prevents fig from working to autocomplete other values later (e.g. branch names for the above examples), and I usually need to hit `Esc` to prevent fig from attempting to insert the `commit` or `branch` parts of the command.

I'm not sure I know why, but sometimes this isn't an issue and fig properly understands these custom aliases.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B453) [Beta] [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/mhamlin/google-cloud-sdk/bin:/Users/mhamlin/.bun/bin:/Users/mhamlin/Library/Caches/fnm_multishells/72940_1651580504932/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mhamlin/.fig/bin:/Users/mhamlin/.local/bin:/Users/mhamlin/.scripts
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/mhamlin/dev/snippets
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 1897787/% (com.apple.Terminal)
  - Active Process: zsh (72887) - /dev/ttys001
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=3ABC5321-6667-4EEA-8C33-DE63144C1A12
    - PATH=/Users/mhamlin/google-cloud-sdk/bin:/Users/mhamlin/.bun/bin:/Users/mhamlin/Library/Caches/fnm_multishells/72940_1651580504932/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mhamlin/.fig/bin:/Users/mhamlin/.local/bin:/Users/mhamlin/.scripts
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
    - FIG_PID=72887
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: true

</p>
</details>

**Comment by hamlim** [comment]
Restarting fig seems to make it work again 🤔

**Comment by rahulsarathy** [comment]
Closing this for now. Feel free to reach out if you're still running into errors!

**Comment by jyaoma** [comment]
I was running into this issue as well. It worked earlier today for me and then this evening it stopped working. `fig restart` fixed it though. I'm wondering how the aliases stopped working to begin with.
