### ISSUE TITLE
fig doctor: iTerm bash integration configured

### ISSUE THREAD

**Issue by mamercad** [withfig/fig#1483]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
```bash
❯ fig doctor

✘ iTerm bash integration configured: iTerm Bash Integration is out of date. Please update in iTerm's menu by selecting "Install Shell Integration".

✘ Doctor found errors. Please fix them and try again.
```

I've (re)installed the iTerm2 shell integrations many times just in case...

```bash
❯ grep -i iTerm ~/.zshrc
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

❯ file "${HOME}/.iterm2_shell_integration.zsh"
/Users/mark/.iterm2_shell_integration.zsh: ASCII text, with very long lines (605)
```

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.57|/usr/local/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/mark/.rbenv/shims:/Users/mark/.pyenv/bin:/Users/mark/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/mark/.cargo/bin:/Users/mark/.fig/bin:/Users/mark/.local/bin:/Users/mark/bin:/usr/local/sbin:/usr/local/opt/fzf/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro11,4
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /usr/local/bin/zsh
  - Current Directory: /Users/mark
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 66269/% (com.googlecode.iterm2)
  - Active Process: zsh (73870) - /dev/ttys001
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:BADDB06C-E295-4238-8C20-38218C640739
    - PATH=/Users/mark/.rbenv/shims:/Users/mark/.pyenv/bin:/Users/mark/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/mark/.cargo/bin:/Users/mark/.fig/bin:/Users/mark/.local/bin:/Users/mark/bin:/usr/local/sbin:/usr/local/opt/fzf/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=73870
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by cornips** [comment]
I have this exact problem too.

<details>
<summary>fig diagnostic</summary>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.59 (B489) [Dutch]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: /Users/martijn/Library/pnpm:/Users/martijn/.nvm/versions/node/v16.16.0/bin:/Users/martijn/Library/Java/Extensions/maven/bin:/Users/martijn/.yarn/bin:/Users/martijn/.config/yarn/global/node_modules/.bin:/Users/martijn/bin:/usr/local/bin:/Users/martijn/.gem/ruby/2.6.0/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/martijn/Library/pnpm:/Users/martijn/Library/Java/Extensions/maven/bin:/Users/martijn/.yarn/bin:/Users/martijn/.config/yarn/global/node_modules/.bin:/Users/martijn/bin:/Users/martijn/.gem/ruby/2.6.0/bin:/usr/local/opt/openssl@1.1/bin:/Users/martijn/.fig/bin:/Users/martijn/.local/bin:/usr/local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro13,3
  - Chip:
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.5.0 (21G72)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/martijn/Development/GOPACS/idcons/front-end
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 1009/% (com.googlecode.iterm2)
  - Active Process: zsh (27039) - /dev/ttys001
  - Terminal: iterm
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:919BCFB1-EB35-4EF6-9020-A9D416C4098B
    - PATH=/Users/martijn/Library/pnpm:/Users/martijn/.nvm/versions/node/v16.16.0/bin:/Users/martijn/Library/Java/Extensions/maven/bin:/Users/martijn/.yarn/bin:/Users/martijn/.config/yarn/global/node_modules/.bin:/Users/martijn/bin:/usr/local/bin:/Users/martijn/.gem/ruby/2.6.0/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/martijn/Library/pnpm:/Users/martijn/Library/Java/Extensions/maven/bin:/Users/martijn/.yarn/bin:/Users/martijn/.config/yarn/global/node_modules/.bin:/Users/martijn/bin:/Users/martijn/.gem/ruby/2.6.0/bin:/usr/local/opt/openssl@1.1/bin:/Users/martijn/.fig/bin:/Users/martijn/.local/bin:/usr/local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.2
    - FIG_PID=27039
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: true
</details>

**Comment by cornips** [comment]
Is it fixed for you @mamercad? I still have the issue. How did you fix it?

**Comment by mamercad** [comment]
Yep, I can't remember what it took though, I'm guessing an update.
