### ISSUE TITLE
Fig inconsistently autocompletes for me

### ISSUE THREAD

**Issue by marcandre** [withfig/fig#1493]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [ ] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:

Just starting with fig.

It sometimes, and inconsistently, autocompletes for me.
1) I don't want that, ever
2) I _definitely_ do not want it to be unpredictable.

Example (see video): I type "g<space>s<space>". `g` is an alias for `git`, `s` is a git alias for "status". For some (bad) reason, I type an extra space.
* In the same session, it will sometimes list a list of files, sometime not (inconsistently)
* If I simply press `<return>`, it adds the first choice. If I don't press `<tab>` or the arrow keys, I don't want fig do affect what I am doing, absolutely *never*, *ever*.  I just want to press return. If it's deemed a "feature", is there a setting for that?

https://user-images.githubusercontent.com/33770/170551993-cdb0c63a-b904-40e7-8d27-b7e263270251.mov

### Environment

```bash
$ fig diagnostic
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: true
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: /Users/mal/.asdf/shims:/usr/local/opt/asdf/libexec/bin:/usr/local/Cellar/asdf/0.9.0/libexec/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users/mal/.rbenv/shims:/usr/local/opt/postgresql@9.6/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mal/.fig/bin:/Users/mal/.local/bin:/Users/mal/.ec2/api/bin:/Users/mal/ruby/dev/spec/mspec/bin:/Users/mal/.bin:/Users/mal/.cargo/bin::/usr/local/Cellar/node/6.8.1/bin:/usr/local/bin:/usr/local/opt/fzf/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook
  - Model Identifier: MacBook10,1
  - Chip:
  - Cores: 2
  - Memory: 16 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /usr/local/bin/bash
  - Current Directory: /Users/mal/super-pas
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 80/% (com.googlecode.iterm2)
  - Active Process: bash (635) - /dev/ttys001
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - TERM_SESSION_ID=w0t0p0:1CDFD29A-CCC6-42B7-84AD-F72789AFC015
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - TERM=xterm-256color
    - PATH=/Users/mal/.asdf/shims:/usr/local/opt/asdf/libexec/bin:/usr/local/Cellar/asdf/0.9.0/libexec/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users/mal/.rbenv/shims:/usr/local/opt/postgresql@9.6/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mal/.fig/bin:/Users/mal/.local/bin:/Users/mal/.ec2/api/bin:/Users/mal/ruby/dev/spec/mspec/bin:/Users/mal/.bin:/Users/mal/.cargo/bin::/usr/local/Cellar/node/6.8.1/bin:/usr/local/bin:/usr/local/opt/fzf/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```
```

**Comment by marcandre** [comment]
The video shows clearly how the first few times it shows list of files and autocompletes, then twice it doesn't, then it does it again.

**Comment by marcandre** [comment]
Sometimes when I go fast, it autocompletes in really bad fashion.
I typed `g cad` at some point. Later I type `g<space>s<return>` and instead of doing `g s`, the terminal is now showing `g scad` which is not any alias I have.

**Comment by SeparateRecords** [comment]
> I just want to press return. If it's deemed a "feature", is there a setting for that?

Absolutely. I think for you what you want is to make fig ignore enter:
```
fig settings autocomplete.keybindings.enter ignore
```

You could instead allow it to execute after space:
```
fig settings autocomplete.immediatelyExecuteAfterSpace true
```

As for why it shows up inconsistently, that's _very_ weird. I think it might have to do with the way the autocomplete engine parses alias suggestions..? @fedeci do you have any idea where to begin debugging this? I can't reproduce it.

**Comment by fedeci** [comment]
@SeparateRecords I'm not sure what could be but the most obvious step to reproduce is to completely copy the bash configuration along with aliases and the fig config.

**Comment by marcandre** [comment]
@fedeci 
[.bash_profile](https://gist.github.com/marcandre/1206eb1e305f806098aad57ab164c9e9)
[.gitconfig](https://gist.github.com/marcandre/b3ddaa7463b8a7254e5164b1367c509d)
[.bin/git-completion.bash](https://gist.github.com/marcandre/c6185f8cb4b3c7721331582ef400457c)
Fig config is default one.

**Comment by SeparateRecords** [comment]
I've tried to reproduce this bug and I honestly can't get it to fail! Possibly an issue fixed in the latest beta... could you try running `fig settings app.beta true` and see if that helps? May need to restart your terminal session since it'll upgrade figterm, which is our shell wrapper.

**Comment by rahulsarathy** [comment]
Closing this for now. Feel free to reach out if you're still running into errors!
