### ISSUE TITLE
Fig wont show folder options

### ISSUE THREAD

**Issue by MaltheGram** [withfig/fig#1496]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.0.1 (21A559)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [Danish]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/malthegram/.local/share/fig/plugins/git-open:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Library/Apple/usr/bin:/Users/malthegram/.fig/bin:/Users/malthegram/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.0.1 (21A559)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/malthegram
  - CLI Installed: true
  - Executable Location: /Users/malthegram/.fig/bin/fig
  - Current Window ID: 27761/% (com.googlecode.iterm2)
  - Active Process: zsh (88113) - /dev/ttys002
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:80ABEDFA-039D-4EF8-8465-645492FBCE73
    - PATH=/Users/malthegram/.local/share/fig/plugins/git-open:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Library/Apple/usr/bin:/Users/malthegram/.fig/bin:/Users/malthegram/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=88113
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

I am running oh my zsh. Dont know if thats any issue

**Comment by SeparateRecords** [comment]
Just to make sure we're on the same page, you mean it doesn't show you suggestions for files/folders like in the image below?

<img width="409" alt="Screen Shot 2022-06-02 at 7 34 48 pm" src="https://user-images.githubusercontent.com/52195359/171601406-d79ff80f-b8e4-44bb-b75d-4344e59a1632.png">

OMZ shouldn't be an issue - usually this is caused by something in your config causing the pseudoterminal to misbehave. Would you be able to send your zshrc/zprofile so we can debug this?

**Comment by MaltheGram** [comment]
issue has been resolved!
