### ISSUE TITLE
Theme cannot be change with Oh my ZSH plugin

### ISSUE THREAD

**Issue by mariobkpr** [withfig/fig#1497]
### Description:
Changing the theme with the "Oh my ZSH" plugin doesn't seem to get applied/persisted. When closing/re-opening fig-settings>My plugins>Oh my ZSH>Configuration, the selected theme is back to default setting "robbyrussel".

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [Swiss German]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mario_zumbuhl/.fig/bin:/Users/mario_zumbuhl/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/mario_zumbuhl/
  - CLI Installed: true
  - Executable Location: /Users/mario_zumbuhl/.fig/bin/fig
  - Current Window ID: 1056/% (com.googlecode.iterm2)
  - Active Process: zsh (96704) - /dev/ttys009
  - Environment Variables:
    - TERM_SESSION_ID=w2t0p0:AE2EB2F8-6791-421C-87BA-EBA13694F954
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mario_zumbuhl/.fig/bin:/Users/mario_zumbuhl/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=96704
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: Extension is not installed.
  - Docker: false

</p>
</details>

**Comment by SimonMacIntyre** [comment]
Likely [related](https://github.com/withfig/fig/issues/1511)

**Comment by SeparateRecords** [comment]
Closing in favor of https://github.com/withfig/fig/issues/1489
