### ISSUE TITLE
Timeout waiting for Input Method status.

### ISSUE THREAD

**Issue by jokerwking** [withfig/fig#1498]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [ ] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
> when I try enable fig on the appcode, I encountered a mistake。
<img width="450" alt="image" src="https://user-images.githubusercontent.com/20392904/171070106-30b3b031-cfbe-4ac1-8f5a-61c8661ad82a.png">

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [搜狗拼音]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/itms/bin:/Users/weij/.pyenv/shims:/Users/weij/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/weij/.fig/bin:/Users/weij/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,4
  - Chip: 
  - Cores: 4
  - Memory: 8 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/weij
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 375/% (com.apple.Terminal)
  - Active Process: zsh (1995) - /dev/ttys002
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=5FF3351D-802D-4BC5-8C88-01B5E28BAD22
    - PATH=/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/itms/bin:/Users/weij/.pyenv/shims:/Users/weij/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/weij/.fig/bin:/Users/weij/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=1995
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by SeparateRecords** [comment]
Hi @jokerwking! Sorry for this issue. Could you try running `fig restart` then run `fig install --input-method` once it starts again? Then you'll need to follow the prompts and restart your mac. Let us know how you go!

**Comment by jokerwking** [comment]
I've tried the above steps many times, but when I clicked the enable button, it didn't pop up with any prompts and reported an error like the one shown above

**Comment by jokerwking** [comment]
> Hi @jokerwking! Sorry for this issue. Could you try running `fig restart` then run `fig install --input-method` once it starts again? Then you'll need to follow the prompts and restart your mac. Let us know how you go!

I've tried the above steps many times, but when I clicked the enable button, it didn't pop up with any prompts and reported an error like the one shown above

**Comment by SeparateRecords** [comment]
@mschrage do you know what could be happening here? Would `fig debug ime enable` be the next thing to try?

**Comment by jokerwking** [comment]
> @mschrage do you know what could be happening here? Would `fig debug ime enable` be the next thing to try?

<img width="586" alt="image" src="https://user-images.githubusercontent.com/20392904/171526860-0b59c0d2-2d34-47ee-9353-a6089e95c76f.png">
`fig debug ime enable` No reaction

**Comment by Ademord** [comment]
what is the update on this? it's september

**Comment by GroovinChip** [comment]
I'm also having this issue

**Comment by Sunnova-ahmedrezk** [comment]
Same here

**Comment by ahmed-rezk-dev** [comment]
Same here!!

**Comment by ahmed-rezk-dev** [comment]
It works for after following these steps. But It works when I did step 3 before 2 and then 2 lol

**Comment by Ademord** [comment]
> It works for after following these steps. But It works when I did step 3 before 2 and then 2 lol

can you explicitly list your steps ? 
```
1. 
2.
3. 
``` 
?

**Comment by grant0417** [comment]
We have rewritten the full app since this was posted, I would encourage you to try Fig again if it didn't work for you a year ago.
