### ISSUE TITLE
fig in vscode terminal: Debugger (zsh) Autocomplete: Error loading spec export.

### ISSUE THREAD

**Issue by GOWxx** [withfig/fig#1500]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

![image](https://user-images.githubusercontent.com/12870715/171080028-f016df49-b267-4595-8c17-b19c6e55f380.png)

**BUT, I can actually get hints in vscode terminal**

![image](https://user-images.githubusercontent.com/12870715/171080707-169a1f98-c937-43f3-9e5e-46b5188cc422.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.57 (B450)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B450) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/gowxx/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (82348) - /dev/ttys007
Current terminal session: D64E9815-7E12-4831-AAE9-D1D0E4AC5699
Current working directory: /Users/gowxx/code/work-yunding/H5
Current window identifier: 14381/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
If everything is loading correctly then nothing to worry about! What likely happened here is that, for some reason, the spec called `export` ([here](https://github.com/withfig/autocomplete/blob/master/src/export.ts)) failed to load. This will likely go away if you click the restart menu item under the ◧ Fig menu

**Comment by GOWxx** [comment]
> If everything is loading correctly then nothing to worry about! What likely happened here is that, for some reason, the spec called `export` ([here](https://github.com/withfig/autocomplete/blob/master/src/export.ts)) failed to load. This will likely go away if you click the restart menu item under the ◧ Fig menu

You're right, My mac came back from sleep mode, or other reasons, the Fig prompts correctly.
The next time I'm in this situation, I'll try restart Fig.
I newed this issue to see if the experience here can be enhanced.
Fig has improved my experience in Terminal for me, thank you! nice work ^ ^
