### ISSUE TITLE
fig disturb me to type git oh-my-zsh aliases, such as "gst"

### ISSUE THREAD

**Issue by davidmeirlevy** [withfig/fig#1501]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Every time I want to command the most common git command (`gst`), fig "disturbs" me by suggesting `gstat`.
so I need to type `esc` to close the fig bubble and then `enter`.

I would prefer that fig won't interfere on those cases, or at least to suggest to me my (probably) most-used command as a first suggestion (you do that git `git checkout`).

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.57 (B450)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B450) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/davidlevy/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hi @davidmeirlevy - thanks for reporting. Not entirely clear on what's happening here, a screen recording would help a lot. My understanding is that you have an alias in your shell called `gst`, and when you type `gst` Fig replaces `gst` with `gstat`?

Do you have the first-token completions option turned on? (you can check by running `fig settings autocomplete.firstTokenCompletion`)

**Comment by davidmeirlevy** [comment]
regarding the `fig settings autocomplete.firstTokenCompletion` - it says `true`.

regarding my issue - yes.
I have git aliases such as `gst` and `gcsmg`. they are very common commands, but fig doesn't suggest them to me at all.

**Comment by SeparateRecords** [comment]
Thanks for that! I can repro. This is actually a really easy fix, submitted a PR internally - once it's merged (not sure when but it shouldn't take long) it should update automatically after restarting fig 🙂

**Comment by SeparateRecords** [comment]
Closing for now since the PR is merged, waiting on next release.

**Comment by davidmeirlevy** [comment]
Yay!
thrilled to see the update!
