### ISSUE TITLE
Autocomplete not using my input

### ISSUE THREAD

**Issue by rluvaton** [withfig/fig#1502]
### Description:

Autocomplete not using my input

`fig doctor` output _ Everything looks good!_

#### In `rm`

https://user-images.githubusercontent.com/16746759/171135019-17b2ed24-83ca-4ddd-99ed-c40f0fe2c1e4.mov

#### In `mkdir`

https://user-images.githubusercontent.com/16746759/171135891-1cf0840b-8ec3-4667-974a-ebacfdf88ffe.mov

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/username/.sdkman/candidates/java/current/bin:/Users/username/.sdkman/candidates/gradle/current/bin:./node_modules/.bin:/Users/username/.nvm/versions/node/v14.19.0/bin:/Users/username/.pyenv/shims:/Users/username/dev/open-source/v8/depot_tools:/Users/username/.asdf/shims:/Users/username/.asdf/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/username/.fig/bin:/Users/username/.local/bin:/Users/username/Library/Python/3.8/bin/:/opt/homebrew/opt/libpq/bin:/Users/username/.bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/username/dev/playing-around/git-hooks
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 185/% (com.googlecode.iterm2)
  - Active Process: zsh (2187) - not a tty
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:43D6298E-846B-40BA-BC92-48A83B5EE5FD
    - PATH=/Users/username/.sdkman/candidates/java/current/bin:/Users/username/.sdkman/candidates/gradle/current/bin:./node_modules/.bin:/Users/username/.nvm/versions/node/v14.19.0/bin:/Users/username/.pyenv/shims:/Users/username/dev/open-source/v8/depot_tools:/Users/username/.asdf/shims:/Users/username/.asdf/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/username/.fig/bin:/Users/username/.local/bin:/Users/username/Library/Python/3.8/bin/:/opt/homebrew/opt/libpq/bin:/Users/username/.bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=2187
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by SeparateRecords** [comment]
Closing in favor of #1503 since I think this is a different flavor of the same bug

**Comment by rluvaton** [comment]
Thanks!, I had:

_Automatically Insert Space For Subcommands/Options that take Arguments_ ON

is this may be related?
