### ISSUE TITLE
Fig doesn't reliably honor the "Hide Icon in Menu Bar" setting 

### ISSUE THREAD

**Issue by ehahn9** [withfig/fig#1510]
### Description:
I have the "hide icon in menu bar" set but still see the fig icon every time I login/restart.
Toggling the setting (unhide/hide) DOES suppress the icon.

<img width="954" alt="Screen Shot 2022-05-31 at 3 21 45 PM" src="https://user-images.githubusercontent.com/299134/171293863-6360914f-547a-4339-997b-6e6e7b4b91fe.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.57 (B450)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B450) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/eric/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by ehahn9** [comment]
thanks!

____________________________________
Eric Hahn
***@***.***

**Comment by qusc** [comment]
still experiencing this issue on 1.0.61

**Comment by permpkin** [comment]
same issue here, since last update ( above doesn't fix for me ), Seems to be a few options that aren't honoured, for me it's same as above as well as "Launch on Start", tried changing a few others all of which aren't doing anything by the looks of it

**Comment by BUYRAK** [comment]
I getting same error 
<img width="469" alt="Ekran Resmi 2022-12-20 16 32 03" src="https://user-images.githubusercontent.com/49075211/208704551-aa078224-3bb8-46d5-af2e-c92723b7ce3a.png">
<img width="781" alt="Ekran Resmi 2022-12-20 16 32 47" src="https://user-images.githubusercontent.com/49075211/208704612-0676274b-0055-4650-af87-edc35c9ab3cf.png">
<img width="365" alt="Ekran Resmi 2022-12-20 16 33 08" src="https://user-images.githubusercontent.com/49075211/208704682-25b8f6dd-77c3-4c77-9aed-aae7e749ff0e.png">

**Comment by mauriciocrecencio** [comment]
still experiencing this issue, MacOS and Fig updated for the last version

**Comment by Joao-Marques** [comment]
This also happens to me on MacOS.

**Comment by matteo-pupa** [comment]
Same issue here, **Fig 2.16.0 (Beta)** and **MacOS Ventura 13.4**.

**Comment by myarovenko** [comment]
Hey, same issue on MacOS Ventura 13.4.1
