### ISSUE TITLE
fig doesn't work with IntelliJ Ultimate 2022.2 EAP

### ISSUE THREAD

**Issue by andrashatvani** [withfig/fig#1513]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

No autocompletion will be shown in terminal; in the menu accessible via the macOS toolbar the IntelliJ integration is shown orange instead of green.
IntelliJ version: Build #IU-222.2680.4, built on May 25, 202 
IntelliJ with the new preview UI of IDEA.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.57 (B453)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B453) [Beta] [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/work/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (11931) - /dev/ttys001
Current terminal session: 0C8E1126-575C-4538-B284-B1F863C7EEA9
Current working directory: /Users/work
Current window identifier: 5437/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hi @andrashatvani! Were you able to run `fig install --input-method`? Did that fail at some point?

From inside your IDE's terminal could you run `fig diagnostic` and send the output here?

I don't think we've had the opportunity to test with the new UI, so I can't 100% confirm that it works, but it _should_ so I just want to make sure all bases are covered :)

**Comment by andrashatvani** [comment]
fig install --input-method, then restart, then restart of IDEA did indeed help, thanks, this issue can be closed I suppose.

**Comment by andrashatvani** [comment]
Hm, apparently it only worked with a release version of IDEA, in the macOS Toolbar it still displays that IDEA EAP is not supported 🤔

**Comment by Atomzwieback** [comment]
Same for Goland EAP

**Comment by kabiroberai** [comment]
I think this issue should be reopened, since afaict EAP builds are still not supported. The cause might be that these builds have a different bundle identifier: e.g. `com.jetbrains.intellij-EAP` instead of `com.jetbrains.intellij`.
