### ISSUE TITLE
Latency causing extraneous characters being inserted

### ISSUE THREAD

**Issue by forcey** [withfig/fig#1516]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

If I type "git status &lt;enter&gt;" reasonably quickly (but not insanely quickly), more than 50% of the times, fig will insert another "s" or "us" at the end of the command and making it invalid.

https://user-images.githubusercontent.com/4744406/171943902-70246553-7c14-4b49-83cb-3a3ef04ec92e.mov

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.57 (B450)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B450) [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/todd/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: true
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: true
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by forcey** [comment]
This seems to happen at slow speeds as well. Below is showing `git status <enter>` and `ls -l <enter>` as intended commands. Fig showed different prompts but both added a character at the end.

https://user-images.githubusercontent.com/4744406/171947672-8bb48bdc-8017-4e2a-a1fa-ec033f9be1cc.mov

**Comment by SeparateRecords** [comment]
Hi @forcey - so sorry for this bug! Going to close this issue to consolidate in #1520. Thank you for the videos, that helps a _lot_.

Would you be able to send your shell config so we can try to reproduce the bug? Feel free to email us if you want to keep it private, hello [at] fig [dot] io 🙂
