### ISSUE TITLE
Fig uninstall doesn't remove `LocalCommand fig bg:ssh` line from SSH config

### ISSUE THREAD

**Issue by EthanStandel** [withfig/fig#1518]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
> After uninstalling, it seems like there's a global Git hook that was not removed properly.

<img width="591" alt="image" src="https://user-images.githubusercontent.com/16840301/172032168-f023332f-5528-43f4-a0ab-39f4e7d559f8.png">

### Environment

```bash
Can't add an image to this section, but environment is described above. Can't run `fig diagnostic` because... well, it's uninstalled. Because of this I also didn't _actually_ do those second two checkboxes.
```

**Comment by EthanStandel** [comment]
Looks like `~/.ssh/config` had a left over line from after the uninstall. What is the purpose of this line?

```sh
LocalCommand fig bg:ssh ~/.ssh/%C &
```

Leaving this ticket up because this needs to be removed on uninstall.

**Comment by SeparateRecords** [comment]
Looks like you've been using fig for a while! That's a really old integration with ssh that no longer does anything, that actually should have been removed many months ago. Safe to remove entirely of course :)

@grant0417 is it worth adding a check for this in the uninstall? I don't think there would be that many current installs with this line but it would definitely improve the experience

**Comment by SeparateRecords** [comment]
Renaming the issue to be clearer to the team but adding the text here because it's still a good search term:

> Uninstalled and now every git command is prefaced with "zsh:1: command not found: fig"
