### ISSUE TITLE
Shake when multiple prefix options

### ISSUE THREAD

**Issue by emilte** [withfig/fig#1519]
### Sanity checks

- [x] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
Option to shake when `Insert common prefix` keybind is selected and there are multiple options available.
Not sure if this is a good idea, I'd like to hear your thoughts.

I found https://github.com/withfig/fig/issues/667 which seems to request the opposite, so maybe a suboption is suitable to toggle this on or off.

<img width="403" alt="image" src="https://user-images.githubusercontent.com/22004178/172075639-71d7681f-bbfa-4da7-8474-b59f51431088.png">

**Comment by SeparateRecords** [comment]
Hi @emilte :) I think this is the default behavior - in the exact situation you're showing there, when using `fig settings autocomplete.keybindings.tab insertCommonPrefix`, the popup shakes for me. Is it not doing that for you? (there's also a good chance I've misunderstood 😅)

**Comment by emilte** [comment]
Standby on this :) I might have had conflicting keybinds causing inconsistent behaviour. I'll follow-up after I've tested some more.

**Comment by SeparateRecords** [comment]
Going to close this for now but definitely let us know what you find! Happy to reopen if there is indeed a bug :)
