### ISSUE TITLE
Fig not working "trying to cd"

### ISSUE THREAD

**Issue by Berend-Kalberg** [withfig/fig#1532]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.57|/usr/local/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B453) [Beta] [U.S. International – PC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/berend/.nvm/versions/node/v12.18.1/bin:/usr/local/sbin:/Users/berend/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/berend/.fig/bin:/Users/berend/.local/bin:/Users/berend/Library/Android/sdk/emulator:/Users/berend/Library/Android/sdk/tools:/Users/berend/Library/Android/sdk/tools/bin:/Users/berend/Library/Android/sdk/platform-tools
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /usr/local/bin/zsh
  - Current Directory: /Users/berend/workspace
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 2200/% (com.googlecode.iterm2)
  - Active Process: zsh (4693) - not a tty
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:2A87A247-092A-4595-8E3B-CEF312DBB208
    - PATH=/Users/berend/.nvm/versions/node/v12.18.1/bin:/usr/local/sbin:/Users/berend/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/berend/.fig/bin:/Users/berend/.local/bin:/Users/berend/Library/Android/sdk/emulator:/Users/berend/Library/Android/sdk/tools:/Users/berend/Library/Android/sdk/tools/bin:/Users/berend/Library/Android/sdk/platform-tools
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=4693
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by rahulsarathy** [comment]
Thanks for sending us this bug report. Closing this for now since it seems to be resolved. 

Making fig automatically restart after running `fig doctor` is a great idea!
