### ISSUE TITLE
Bad contrast on authors

### ISSUE THREAD

**Issue by emilte** [withfig/fig#1534]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

<img width="212" alt="image" src="https://user-images.githubusercontent.com/22004178/173207811-dda9d2c9-f817-4f53-a668-fe17ae887702.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.57|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [Norwegian]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/sbin:/Users/emil/.pyenv/shims:/Users/emil/.pyenv/bin:/Users/emil/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/munki:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/emil/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/Users/emil/.fig/bin:/Users/emil/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 64 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/emil/my-projects/html-workshop
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 22884/% (com.googlecode.iterm2)
  - Active Process: bash (90628) - /dev/ttys013
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=w1t0p0:F31D9907-F32F-429D-A541-DFA77CFE7497
    - PATH=/usr/local/sbin:/Users/emil/.pyenv/shims:/Users/emil/.pyenv/bin:/Users/emil/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/munki:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/emil/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/Users/emil/.fig/bin:/Users/emil/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.4.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by rahulsarathy** [comment]
This should be fixed now!
