### ISSUE TITLE
dotfiles group deletion UX

### ISSUE THREAD

**Issue by emilte** [withfig/fig#1535]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Dotfiles group/block deletes everything at the click of the `x` button. Maybe ask for confirmation to prevent major losses.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.57|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [Norwegian]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/sbin:/Users/emil/.pyenv/shims:/Users/emil/.pyenv/bin:/Users/emil/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/munki:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/emil/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/Users/emil/.fig/bin:/Users/emil/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 64 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/emil/my-projects/html-workshop
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 22884/% (com.googlecode.iterm2)
  - Active Process: bash (41731) - /dev/ttys020
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=w1t2p0:398DB9DE-D801-4221-9AC0-451B4D236A48
    - PATH=/usr/local/sbin:/Users/emil/.pyenv/shims:/Users/emil/.pyenv/bin:/Users/emil/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/munki:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/emil/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/Users/emil/.fig/bin:/Users/emil/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.4.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Just gave this a go myself and the behavior I expected was to delete the _grouping_, not the entire group itself. I think deleting the group shouldn't be the little [x] button, instead select the group and open a `***` menu like everything else.

**Comment by SeparateRecords** [comment]
This is fixed now!
