### ISSUE TITLE
error: Found argument 'pre' which wasn't expected

### ISSUE THREAD

**Issue by StuartMorrisDF** [withfig/fig#1538]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Issue Details

When starting iTerm the following error is displayed from fig.

error: Found argument 'pre' which wasn't expected, or isn't valid in this context

USAGE:
    Fig [SUBCOMMAND]

---

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [British]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: <generated dynamically>
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/stuart.morris
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 17966/% (com.googlecode.iterm2)
  - Active Process: zsh (36091) - /dev/ttys001
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:AD0CB454-A441-4E54-B131-2D4428B012EE
    - PATH=/opt/homebrew/bin:/Users/stuart.morris/.nvm/versions/node/v14.19.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/CyberArk EPM.app/Contents/Helpers:/Users/stuart.morris/.fig/bin:/Users/stuart.morris/.local/bin:/Users/stuart.morris/.rvm/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=36091
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true
```

**Comment by SeparateRecords** [comment]
Hi @StuartMorrisDF !

Sorry for the issue. Seems like the fig lines at the start/end of your zshrc may be incorrect, should look something like this:
<img width="480" alt="Screen Shot 2022-06-15 at 1 10 37 am" src="https://user-images.githubusercontent.com/52195359/173612666-260a79dd-3b16-4a31-8186-512d8f4d9a54.png">


Can you confirm if it looks like this for you?

If not, you can remove the `fig` lines that are already there, and run this command:
```
fig install
```

**Comment by SeparateRecords** [comment]
Also, if that is correct, the shell init files themselves might be wrong. Not sure how that would have happened...
Could you run `cat ~/.fig/shell/zshrc.pre.zsh` and send the output here?

**Comment by SeparateRecords** [comment]
If you run that command yourself is the output the same? Trying to figure out if it's something about the way it's being invoked, or may the CLI binary is somehow the wrong version.

If it still fails when you invoke it yourself, could you try updating to the beta to see if that helps?
```bash
fig settings app.beta true
```

**Comment by StuartMorrisDF** [comment]
That looks like the problem...
```
zsh: permission denied: /Users/***/.fig/shell/zshrc.pre.zsh
```

Do you know what the required perms will be?

**Comment by SeparateRecords** [comment]
Weird that you don't have permission for it. Not sure the minimum permissions but I'd be safe and give your current user read/write/execute
```
sudo chmod u+rwx ~/.fig/shell/*
```

If the issue is that it isn't owned by your user (backed up using chezmoi?)
```
sudo chown $(id -un) ~/.fig/shell/*
```

Let me know how you go with that!
