### ISSUE TITLE
Fig autocomplete local completion specs have stopped working after last update (1.0.57)

### ISSUE THREAD

**Issue by ShawnCockburn** [withfig/fig#1539]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
Using scripts in a project generated with `@withfig/autocomplete-tools` specifically `yarn copy-to-global` and that would put the generated scripts in `~/.fig/autocomplete/build/` and that would allow any CLI/tools that I make to have autocomplete locally.

this has stopped working after updating, fig.

this is probably meant to be done via fig teams but I did like the ability to have a local completion spec.

<img width="469" alt="Screenshot 2022-06-15 at 09 35 52" src="https://user-images.githubusercontent.com/60285801/173782374-17ed2366-398c-4a64-b1d4-21f8b7f049b6.png">

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B457) [Beta] [British]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/Work/.deno/bin:/Users/Work/Library/Android/sdk/platform-tools:/Users/Work/Library/Android/sdk/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/Work/.local/bin:/Users/Work/.fig/bin:/Users/Work/.local/bin:/Users/Work/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,4
  - Chip: 
  - Cores: 8
  - Memory: 32 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/Work/.fig/autocomplete
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 296/% (co.zeit.hyper)
  - Active Process: zsh (1840) - /dev/ttys006
  - Installed via Brew: true
  - Environment Variables:
    - PATH=~/.pyenv/versions/2.7.18/bin/python:/usr/bin/python3:/Users/Work/.deno/bin:/Users/Work/Library/Android/sdk/platform-tools:/Users/Work/Library/Android/sdk/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/Work/.fig/bin:/Users/Work/.local/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=2090D897-E24E-44D2-8530-750B1061ACD3
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=1840
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: installed!
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by SeparateRecords** [comment]
Hey @ShawnCockburn!

This was something I noticed too - definitely need to make an announcement or something about this but it's hard to actually get it in front of the right people.

Local specs are now hosted, using the (imo poorly named) `@fig/publish-spec-to-team` tool. If you don't specify `--team` then it's uploaded as a personal spec:
```bash
npx @fig/publish-spec-to-team --spec-name YOUR_CLI.ts
```
I'm pushing to have this changed to `@fig/publish` or even merged into the fig cli proper.

You can manage your specs in the mission control UI:

<img width="1226" alt="Screen Shot 2022-06-16 at 3 47 02 pm" src="https://user-images.githubusercontent.com/52195359/174009335-49cc06d7-719e-4943-baa0-8db8d7c274ed.png">

Currently they can't be deleted but the infrastructure is in place, UI just isn't hooked up yet.

Let me know if you need a hand with any of this! I'm currently migrating my specs to this too so happy to compare notes if you have any pain points :)
