### ISSUE TITLE
Hex Publish briefly displays characters before clearing line

### ISSUE THREAD

**Issue by yordis** [withfig/fig#1540]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hey peeps, I recently ran a command [`mix hex.publish`](https://hex.pm/docs/publish) that ask me to enter my computer password, while I was doing this, I notice that there were some millisecond delays and every keystroke character was shown for few milliseconds, something that you could definitely read if you paid attention.

https://user-images.githubusercontent.com/4237280/173815588-9ea7cd95-b9b6-48ee-8c0f-f334e5e370c3.mov

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.57 (B450)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/ubi/.fig/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## OS Info:
  - macOS 12.4.0
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: .....
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 11669/% (com.jetbrains.intellij)
  - Active Process: zsh (62127) - /dev/ttys012
  - Installed via Brew: true
  - Environment Variables:
    - PATH=/Users/ubi/.fig/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=8e6ed74f-9782-4994-853c-58848439c988
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=62127
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: installed!
  - Visual Studio Code: installed!
  - Docker: true
</details>

**Comment by SeparateRecords** [comment]
This is actually a super interesting case. Normally the way you'd disable input is by using something like `getpass(3)` which disables echoing inputs to the terminal. This is how sudo works, and how higher-level languages also tend to do it (or they reimplement something similar -- but either way, echoing is disabled at the terminal level).

The method used by Hex seems... less than optimal:

<a href="https://github.com/hexpm/hex/blob/089ca70a06717b09d6ffb5725483420f2f469ba9/lib/mix/tasks/hex.ex#L360-L380"><img width="445" alt="Screen Shot 2022-06-16 at 11 57 27 am" src="https://user-images.githubusercontent.com/52195359/173974749-64ffbd06-6812-4309-b732-8d1a55d0e6d3.png"></a>

Figterm sits between your terminal and shell, looks like there's some kind of weird interaction between it and this program.

**Comment by SeparateRecords** [comment]
Another thing, I'd be super curious to find out if the same problem occurs in another terminal eg. iTerm or Kitty. The IntelliJ terminal is painfully slow as a terminal emulator so if you could test in something else that would help narrow down where in the code the bottleneck might be

**Comment by yordis** [comment]
Only IntelliJ as far as I know, I use iTerm, and doesn't happen

**Comment by SeparateRecords** [comment]
So we've discussed this internally, going to close this issue since it's actually an issue with hex but is just made more obvious with a tiny amount of additional latency. The actual fix is for them to enable "raw" mode in the terminal.

Would you be able to open an issue for this in the hex repo? https://github.com/hexpm/hex

You can link to this issue in it, we're happy to discuss further there. Would love to make sure this gets resolved properly since there's nothing we can do on our end :)
