### ISSUE TITLE
iTerm integration is enabled: fig-iterm-integration.scpt is missing.

### ISSUE THREAD

**Issue by Casper-Guo** [withfig/fig#1544]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [Canadian English]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/Caskroom/miniconda/base/bin:/opt/homebrew/Caskroom/miniconda/base/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/dev/bin/user:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/casperguo/.fig/bin:/Users/casperguo/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/casperguo
  - CLI Installed: true
  - Executable Location: /Users/casperguo/.fig/bin/fig
  - Current Window ID: 29383/% (com.googlecode.iterm2)
  - Active Process: zsh (31368) - /dev/ttys003
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:DC1BC60F-D56E-4A97-94CE-A9AF53CF70C4
    - PATH=/opt/homebrew/Caskroom/miniconda/base/bin:/opt/homebrew/Caskroom/miniconda/base/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/dev/bin/user:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/casperguo/.fig/bin:/Users/casperguo/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=31368
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: AutoLaunch script does not exist at /Users/casperguo/Library/Application Support/iTerm2/Scripts/AutoLaunch/fig-iterm-integration.scpt.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by Casper-Guo** [comment]
@SeparateRecords Hello! Thanks for getting back to me. I just checked that I am running version 3.4.15 and running `fig doctor` shows the same error

**Comment by cemore2048** [comment]
I'm running into the same issue. On 3.4.16 and getting the same script not found error

**Comment by SeparateRecords** [comment]
Can you confirm if you see this below the debugger?
<img width="728" alt="Screen Shot 2022-07-27 at 1 07 53 pm" src="https://user-images.githubusercontent.com/52195359/181152220-17b4b3a8-29b5-4921-ab7c-f8f8c75c18a2.png">


Clicking the "install integration" button should fix it.

**Comment by jessicakryan** [comment]
Hey @SeparateRecords I have the same issue and have just tried to run the "install iTerm Integration" and I just get this popup
![fig-iterm](https://user-images.githubusercontent.com/6989779/181153952-31999121-8718-4cfd-a8b6-14ed22253163.png)

**Comment by SeparateRecords** [comment]
Strange! Can you run `ls -l ~/Library/Application\ Support | grep iTerm2` and send the output? If it contains your username you can censor it - my suspicion is that for some reason your config might be owned but another user account

**Comment by jessicakryan** [comment]
Yes - it looks to be owned by the root rather than myself
![Screenshot 2022-07-27 at 2 29 15 pm](https://user-images.githubusercontent.com/6989779/181161755-0bb7765c-b9ae-4800-861b-81c000d34e34.png)

**Comment by SeparateRecords** [comment]
@jessicakryan Any idea how that could have happened? I've seen this a couple of times now and still no idea _why_ this happens in the first place.

> I don't see the fig popup in either iterm2 or vscode it just never appears

Maybe there are other files owned by root...? Here's a couple of places to check:
* ~/.fig
* ~/local/bin

If the directory is owned by root it might not be writable for you user account, so fig might not have been able to install correctly and silently failed.

Here's mine for comparison again:
<img width="755" alt="Screen Shot 2022-07-27 at 4 29 05 pm" src="https://user-images.githubusercontent.com/52195359/181176969-f28b350e-2e86-4d94-b98d-23acd4336233.png">

**Comment by SeparateRecords** [comment]
Also for anyone in this thread: if you're stuck and want to debug 1:1, feel free to pick a time with me! https://calendly.com/robert-fig/support

**Comment by jessicakryan** [comment]
Hi @SeparateRecords, no clue. I have run the above and files in those directories are owned by myself so all good there

**Comment by SeparateRecords** [comment]
Annoying. Definitely would suggest picking a time on my calendar - should take <15 mins to sort out :)

**Comment by jessicakryan** [comment]
Hey @SeparateRecords this seems to have resolved itself now - am on the below versions and everything working as expected.
MacOS: 12.5.1
Fig version: 1.0.60

**Comment by rahulsarathy** [comment]
This looks like it's fixed, so closing this.
