### ISSUE TITLE
It is not working after re-wake up my Mac

### ISSUE THREAD

**Issue by zyflovelam** [withfig/fig#1546]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I never shut down my Mac in the night, I noticed when I re-wake up my Mac next morning and keep focus in WebStorm, and it was not working when I type the command in the terminal, and it was not working too in iTerm2, even I reopen iTerm2. But it's working after I restart fig, I guess it is an issue.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.57 (B450)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B450) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/zyf/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/zyf/.npm-global/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/zyf/.local/bin:/Users/zyf/.fig/bin:/Users/zyf/.local/bin:/Users/zyf/.local/bin:/Users/zyf/.local/bin:/usr/local/mysql/bin:/Users/zyf/bin:/Users/zyf/maven/bin:/usr/local/mongodb/bin:/Users/zyf/flutter/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (14195) - /dev/ttys001
Current terminal session: f9c098f1-03b8-4903-89b8-ebe014a2d462
Current working directory: /Users/zyf/Workspace/tunekey-firebase/Functions/functions
Current window identifier: 11064/% (com.jetbrains.WebStorm)</pre>
</p>
</details>

**Comment by rahulsarathy** [comment]
This should be fixed - thanks for submitting!
