### ISSUE TITLE
fig autocomplete is not appear in my terminal (vscode, terminal, hyper)

### ISSUE THREAD

**Issue by tirajetw** [withfig/fig#1549]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

fig autocomplete is not appear in my terminal (vscode, terminal, hyper)
<img width="1027" alt="Screen Shot 2565-06-18 at 11 27 22" src="https://user-images.githubusercontent.com/25123311/174422704-bda8bf79-4ea7-491c-b079-2c11b05fb14a.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/tirajetw/opt/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/tirajetw/.fig/bin:/Users/tirajetw/.local/bin:/Users/tirajetw/.yarn/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/tirajetw
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 6872/% (co.zeit.hyper)
  - Active Process: zsh (28004) - not a tty
  - Environment Variables:
    - PATH=/Users/tirajetw/opt/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/tirajetw/.fig/bin:/Users/tirajetw/.local/bin:/Users/tirajetw/.yarn/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=DE2AB214-5BAB-44FB-A477-5FC2B5A0CE7F
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=28004
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: installed!
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by rahulsarathy** [comment]
@tirajetw are you still experiencing this issue?
