### ISSUE TITLE
spec in ~/.fig/autocomplete/build didn't load

### ISSUE THREAD

**Issue by gogoyqj** [withfig/fig#1558]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

```shell
MacBook-Pro-2:~ skipper$ ls ~/.fig/autocomplete/build
kgit.js		ks-git.js
```

seems both kgit and ks-git didn't load, there's no autocompletion when type "kgit "

but spec in ~/.fig/user/autocomplete/build/git.js did load and merged

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.57 (B450)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B450) [搜狗拼音] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/skipper/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by gogoyqj** [comment]
i got it, it's not a free feature now

**Comment by SeparateRecords** [comment]
Hey @gogoyqj! Loading specs is still available, but they just need to be uploaded with `npx @fig/publish-spec-to-team` -- you can just omit `--team <name>` to save them personally :)

**Comment by gogoyqj** [comment]
> Hey @gogoyqj! Loading specs is still available, but they just need to be uploaded with `npx @fig/publish-spec-to-team` -- you can just omit `--team <name>` to save them personally :)

it finally works again! Will this feature always be available? since i've  meet several changes caused problems.

**Comment by SeparateRecords** [comment]
> Will this feature always be available? since i've meet several changes caused problems.

Yes! We'll be keeping this free for individual users, teams of >4 people will have to pay for sharing. This way is simpler internally, easier to use externally, and much more flexible for the future 🙂

**Comment by SeparateRecords** [comment]
Oh I just want to add another thing, the name of the CLI (`upload-spec-to-team`) is misleading, we'll be changing it very soon. It's named that because it was built for uploading to a "team namespace" -- internally your completions belong to a team with only one member (you).

**Comment by fedeci** [comment]
The name of the misleading CLI is `@fig/publish-spec-to-team` and I have just renamed it to `@fig/publish-spec`!

**Comment by gogoyqj** [comment]
it seems that fig autocomplete changes quite often and brings in some break down changes...

<img width="567" alt="image" src="https://user-images.githubusercontent.com/1776278/176997456-dcaf5016-303a-4c05-bce0-00512a37ef4e.png">

in older versions, there's a way to trigger custom generators(maybe set cache ttl to 0 or trigger always return true) while input changing just like google search input suggestion, but now it doesn't work any more.

```
{
    cache: {
      ttl: 0,
      cacheByDirectory: false,
    },
    // 暂时通过这个配置实现 fuzzy search
    getQueryTerm: (token) => "",
    trigger: (newToken) => newToken.indexOf('#') !== -1 || newToken.indexOf('/') !== -1,
}
```

these changes really upset me a litlle. cc @SeparateRecords

**Comment by fedeci** [comment]
I know it may be annoying to have breaking changes sometimes, but versioning autocomplete-engine changes using semver would be really expensive and is not on our current target.

**Comment by fedeci** [comment]
Trigger should still work there was no recent change to it, are you using the fuzzy search setting?

**Comment by gogoyqj** [comment]
> Trigger should still work there was no recent change to it, are you using the fuzzy search setting?

fuzzy search is off. I found it didn't work since July 1st. 

```
$ fig settings all
app.disableAutoupdates = true
autocomplete.devCompletionsFolder = "/Users/skipper/.fig/autocomplete/build"
autocomplete.developerMode = false
autocomplete.developerModeNPM = false
autocomplete.developerModeNPMInvalidateCache = false
autocomplete.disable = false
autocomplete.firstTokenCompletion = false
autocomplete.fuzzySearch = false
autocomplete.immediatelyRunGitAliases = true
autocomplete.insertSpaceAutomatically = true
cli.tips.disabled = false
```

**Comment by gogoyqj** [comment]
@fedeci it's works in developer mode but not in normal mode. there must be some differences.

in developer mode, scripts got arguments:
```
["kgit","checkout","-b","23344","--team","sql"]
```

but in normal mode, scripts only got arguments:
```
["kgit","checkout","-b","23344","--team",""]
```

seem chars after "--team" weren't passed to scripts in normal mode.

**Comment by fedeci** [comment]
I'm giving a look into this in the next days!

**Comment by fedeci** [comment]
Maybe CDN problems. We have just pushed a fix for a CDN issue that should go live in the next hours!
