### ISSUE TITLE
Red color box around fix suggestions

### ISSUE THREAD

**Issue by haquezameer** [withfig/fig#1560]
### Description:

There is a red colour box on the terminal when typing commands. I have not updated my terminal recently. It started happening after fig prompted me for some accessibility setting which I did.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/20766601/175476836-3389fc9a-f04a-4920-9311-c4634f931ffe.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B463) [Debug] [ABC – India]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/zameerhaque/.nvm/versions/node/v16.14.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/zameerhaque/.fig/bin:/Users/zameerhaque/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/zameerhaque
  - CLI Installed: true
  - Executable Location: /Users/zameerhaque/.fig/bin/fig
  - Current Window ID: 21634/% (com.googlecode.iterm2)
  - Active Process: zsh (39294) - /dev/ttys003
  - Environment Variables:
    - TERM_SESSION_ID=w0t1p0:0DA55C8D-6574-4790-BC54-47CE14DC64F8
    - PATH=/Users/zameerhaque/.nvm/versions/node/v16.14.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/zameerhaque/.fig/bin:/Users/zameerhaque/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=39294
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @haquezameer ! Sorry for the delay. This is due to the debugging options. Run `fig debug autocomplete-window` to fix 🙂
