### ISSUE TITLE
Daemon: URL error: TLS support not compiled in

### ISSUE THREAD

**Issue by Redst0neFlux** [withfig/fig#1563]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

This is the output of fig doctor, I am running fig on ubuntu linux using gnome-console and zsh
```
✘ Daemon: URL error: TLS support not compiled in
Attempting to fix automatically...
Re-running check...

✘ Daemon: URL error: TLS support not compiled in


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

```

### Details:
|OS|Fig|Shell|
|-|-|-|
|Linux 5.15.0-40-generic||/usr/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Hardware Info:
  - Model Name: cpu0
  - Model Identifier: GenuineIntel
  - Chip: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  - Cores: 8
  - Memory: 16729546 KB
## OS Info:
  - Linux 5.15.0-40-generic
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /home/redstoneflux
  - CLI Installed: true
  - Executable Location: /usr/bin/fig
  - Current Window ID: <unknown>
  - Active Process: <unknown>
  - Environment Variables:
    - PATH=/home/redstoneflux/.local/bin:/home/redstoneflux/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/lib/jvm/java-16-oracle/bin:/usr/lib/jvm/java-16-oracle/db/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=286aa67e-c7ab-40d7-b24e-0c4504004496
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_PID=14728
## Integrations:

</p>
</details>

**Comment by grant0417** [comment]
Hey @Redst0neFlux, this should be fixed on the latest alpha, thanks for the report!
