### ISSUE TITLE
Autocomplete stops working

### ISSUE THREAD

**Issue by Skywt2003** [withfig/fig#1568]
### Description:

Autocomplete stops working...

Tried `fig doctor` but it said "Everything looks good".

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B463) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/skywt/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/skywt/.fig/bin:/Users/skywt/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/skywt
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 189473/% (com.apple.Terminal)
  - Active Process: zsh (57779) - not a tty
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=42CB5BB0-DB4C-4501-BAEB-08C12DDBF30F
    - PATH=/Users/skywt/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/skywt/.fig/bin:/Users/skywt/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=57779
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @Skywt2003, sorry about the error. Does this continue after completely restarting your terminal (⌘Q) and restarting fig? (`fig restart`)

Another thing to try:
1. Type out something in the terminal, eg. `git commit`, and **don't press enter**
2. Click the ◧ Fig menubar icon, hover over debugger
3. Is the text you wrote shown in the debugger?

<img width="666" alt="Screen Shot 2022-06-09 at 5 53 48 pm" src="https://user-images.githubusercontent.com/52195359/176363255-98e2f6b3-6136-4196-a27e-73c6741ba7ab.png">
