### ISSUE TITLE
Imported dotfiles blocks not working

### ISSUE THREAD

**Issue by gilbitron** [withfig/fig#1572]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:

I ran the dotfiles import to set up my Fig dotfiles. However, no matter what I do any blocks that were part of the original import are not enabled in any shells/os. None of my aliases work. When I click configure and tick the checkboxes, the next time I click configure they are unselected again. 

Note: Manually adding new blocks seems to work ok.

![CleanShot 2022-06-29 at 5 31 27@2x](https://user-images.githubusercontent.com/203882/176488896-cda8ca4c-02ed-4dc4-8e71-8bbbf80bbff6.png)

<img width="483" alt="CleanShot 2022-06-29 at 5 33 09@2x" src="https://user-images.githubusercontent.com/203882/176489064-b65dc014-96bd-454d-9a13-64dc10479e66.png">

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B463) [British]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/Users/gilbitron/.fig/bin:/Users/gilbitron/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /Users/gilbitron
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 385/% (com.googlecode.iterm2)
  - Active Process: zsh (31734) - /dev/ttys001
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:B4D9F224-8602-4AFD-9CEB-9E3D899BA544
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/Users/gilbitron/.fig/bin:/Users/gilbitron/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=31734
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mvgijssel** [comment]
Just ran into this as well! The import looks like it worked, but the environment variables aren’t added to the terminal (iTerm2) after running `fig source` and once I reboot Fig the imported dotfile blocks are all gone from the UI.

**Comment by grant0417** [comment]
This is a very old bug with dotfiles, it should be resolved now and this issue is very stale!
