### ISSUE TITLE
Cannot Select autocomplete options

### ISSUE THREAD

**Issue by adunham95** [withfig/fig#1574]
### Description:
In VSCode and the Mac Terminal I cannot select autocomplete options with either the enter or tab key. 
I ran `fig update` and I am still having the issue

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7 19H1922|1.0.54|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.54 (B359) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/adriandunham/.rbenv/shims:/usr/local/opt/postgresql@11/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/adriandunham/.rbenv/shims:/usr/local/opt/postgresql@11/bin:/Users/adriandunham/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (63141) - /dev/ttys007
Current working directory: /Users/adriandunham/workspace/memoe-web
Current window identifier: 2829/% (com.microsoft.VSCode)
Path: /Users/adriandunham/.rbenv/shims:/usr/local/opt/postgresql@11/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/adriandunham/.rbenv/shims:/usr/local/opt/postgresql@11/bin:/Users/adriandunham/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=59AAE933-07BA-449E-8764-2BDA0E24C4F2
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 10.15.7 19H1922
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @adunham95! You are on a very old version of Fig. Try updating by running `fig update`.
