### ISSUE TITLE
Fig autocomplete not working

### ISSUE THREAD

**Issue by Nicolanz** [withfig/fig#1575]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 10.13.6 (17G14042)|1.0.58|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B463) [Spanish - ISO]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/nicolaszarate/.fig/bin:/Users/nicolaszarate/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: iMac
  - Model Identifier: iMac12,1
  - Chip: 
  - Cores: 4
  - Memory: 4 GB
## OS Info:
  - macOS 10.13.6 (17G14042)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/nicolaszarate/Desktop/projects/seeed/di-contest-client-app
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 4412/% (com.apple.Terminal)
  - Active Process: bash (72949) - /dev/ttys001
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=ECBE8D08-6840-4A07-BD20-BCF0FAB7E0D3
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/nicolaszarate/.fig/bin:/Users/nicolaszarate/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.4.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Try running `fig doctor` and share the output here?
