### ISSUE TITLE
Fish shell repeatedly shows error `bind: No binding found for sequence 'fig-open-workflows'`

### ISSUE THREAD

**Issue by giancarlo88** [withfig/fig#1579]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hello there! 

Since the latest update my shell (Fish) repeatedly shows the message `bind: No binding found for sequence 'fig-open-workflows'` upon session startup and on every new terminal line.

(It's worth noting that Fig still works fine!)

![image](https://user-images.githubusercontent.com/17690720/176869764-c25410f4-286f-4575-bd87-591325386e48.png)

I had a look in my `config.fish` to see if there was a stray line there but I haven't found anything.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.58 (B467)|/opt/homebrew/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.58 (B467) [British] 
UserShell: /opt/homebrew/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/giancarlo.galliani/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: fish (896) - /dev/ttys001
Current terminal session: w0t0p0:22253691-50CD-41FA-B472-34DA6257D5BC
Current working directory: /Users/giancarlo.galliani/Code
Current window identifier: 114/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by widyakumara** [comment]
same thing, but for me the warning only showed once every new session

- macOS 12.4.0
- iTerm2 3.4.15
- fish 3.5.0
- starship 1.9.1
- Fig 1.0.58

@giancarlo88 maybe something on your prompt setting?

**Comment by loyio** [comment]
the same problem
```
bind: No binding found for sequence 'fig-open-workflows'
```

**Comment by MateoCerquetella** [comment]
Same for me

<details>
<summary>fig diagnostic</summary>

```properties
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B467) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/sbin:/Users/mateocerquetella/.local/bin:/Users/mateocerquetella/.fig/bin:/var/folders/zg/d9rvyr8x11x25m8f4091lhy80000gn/T/fnm_multishell_14149_1656688699547/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/latest/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /usr/local/bin/fish
  - Current Directory: /Users/mateocerquetella
  - CLI Installed: true
  - Executable Location: /Users/mateocerquetella/.local/bin/fig
  - Current Window ID: 1516/% (com.apple.Terminal)
  - Active Process: fish (14787) - /dev/ttys004
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - TERM=xterm-256color
    - FIG_TERM_VERSION=4.4.1
    - TERM_SESSION_ID=7ECA40F5-B9F7-4B12-BEB8-471C46642ABE
    - PATH=/usr/local/sbin:/Users/mateocerquetella/.local/bin:/Users/mateocerquetella/.fig/bin:/var/folders/zg/d9rvyr8x11x25m8f4091lhy80000gn/T/fnm_multishell_14797_1656688772500/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/latest/bin
    - FIG_PID=14787
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

```
</details>

**Comment by ajagelund** [comment]
d:o

fig diagnostics
```markdown
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B467) [U.S. International – PC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/andreas/.fig/bin:/Users/andreas/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/andreas/workspace/stena/payment/backoffice/frontend
  - CLI Installed: true
  - Executable Location: /Users/andreas/.fig/bin/fig
  - Current Window ID: 7764/% (com.apple.Terminal)
  - Active Process: fish (30410) - /dev/ttys008
  - Installed via Brew: true
  - Environment Variables:
    - FIG_PID=30410
    - FIG_TERM=1
    - FIG_INTEGRATION_VERSION=8
    - TERM_SESSION_ID=53ABC285-D638-4232-B121-8E693248DDC8
    - PATH=/Users/andreas/.local/share/nvm/v16.15.0/bin:/Users/andreas/.jetbrains:/Users/andreas/.fig/bin:/Users/andreas/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
    - TERM=xterm-256color
    - FIG_TERM_VERSION=4.4.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

```

**Comment by hadnet** [comment]
Same thing here. Fig is driving me crazy, so many errors all the time, specially when updating.

**Comment by gustavoabell** [comment]
fig is compatible on tabby terminal?

**Comment by mschrage** [comment]
Thanks for letting us know!

A fix should go live next week. In the meantime, updating to the beta should resolve this issue:
```
fig settings app.beta true
fig update
```

**Comment by keramzyt** [comment]
I can confirm that the beta upgrade has fixed the problem.

**Comment by Mambatukaa** [comment]
Same for me.

**Comment by Mambatukaa** [comment]
> Thanks for letting us know!
> 
> A fix should go live next week. In the meantime, updating to the beta should resolve this issue:
> 
> ```
> fig settings app.beta true
> fig update
> ```

Thanks it worked for me.

**Comment by max003003003** [comment]
> > Thanks for letting us know!
> > A fix should go live next week. In the meantime, updating to the beta should resolve this issue:
> > ```
> > fig settings app.beta true
> > fig update
> > ```
> 
> Thanks it worked for me.

Thank it's worked for me.
