### ISSUE TITLE
Fig doesn't work properly when installing plugin in tabby terminal

### ISSUE THREAD

**Issue by gustavoabell** [withfig/fig#1581]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Issue Details

![image](https://user-images.githubusercontent.com/69880411/176980696-102445a1-91b1-4a50-999c-a536e83f8d54.png)

### Environment

```bash
OS, Linux, Kubuntu KDE LTS.
```

**Comment by mschrage** [comment]
@gustavoabell are you using macOS? It doesn't seem like it. Please report issues with the Linux alpha in the [Discord](https://fig.io/community)!
