### ISSUE TITLE
[workflow] how to disable build-in workflow shortcut  

### ISSUE THREAD

**Issue by colinlabs** [withfig/fig#1584]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
I am used to using emacs shortcuts, such as `ctr- f` to move the mouse in a string, but in the latest version of fig, `ctr- f` is forcibly bound to **workflow** feature. How to disable this shortcut?

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B467) 
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: true
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
## Hardware Info:
  - Model Name: MacBook Pro
## OS Info:
  - macOS 12.4.0 (21F79)
```

**Comment by aparajita** [comment]
Hey @fig-io, how could you steal a keystroke like this without any way to change or disable it? Ctrl-f is the standard keystroke for moving forward a character on macOS. And I mean at the system level.

In general it's extremely unfriendly to steal keystrokes without offering a way to disable/change it. Not sure what you were thinking.

**Comment by aparajita** [comment]
Here's the fix, change the fig stanza at the bottom of .zshrc to this:

```shell
# Fig post block. Keep at the bottom of this file.
# Set the workflows keybinding here:
export FIG_WORKFLOWS_KEYBIND="^\\"
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && . "$HOME/.fig/shell/zshrc.post.zsh"

# Reset ^F keybinding to what you want
bindkey "^F" forward-char
```

**Comment by mschrage** [comment]
Closing as duplicates of #1583
