### ISSUE TITLE
fig login fails

### ISSUE THREAD

**Issue by acgetchell** [withfig/fig#1592]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
![Screen Shot 2022-07-04 at 1 33 03 PM](https://user-images.githubusercontent.com/434849/177213941-21a9f686-5eea-4dd7-bbc1-3b4e7be1aaba.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.58 (B467)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.58 (B467) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/adam/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /opt/homebrew/Caskroom/miniforge/base/bin:/opt/homebrew/Caskroom/miniforge/base/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/adam/Library/Python/3.10/bin:/opt/homebrew/opt/python@3.10/bin:/opt/homebrew/opt/llvm/bin:/Users/adam/projects/vcpkg:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/adam/.fig/bin:/Users/adam/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @acgetchell 🙂 Issue is totally on our side. We implemented a fix but it'll take some time to roll out. For now, just keep trying and it'll work eventually!
