### ISSUE TITLE
不出提示

### ISSUE THREAD

**Issue by magicer0126** [withfig/fig#1593]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B468) [Beta] [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/mahuiying/depot_tools:/opt/MonkeyDev/bin:/usr/local/bin/node:/usr/local/bin/npm:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/mahuiying/.fig/bin:/Users/mahuiying/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/mahuiying
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 6380/% (com.googlecode.iterm2)
  - Active Process: zsh (15261) - /dev/ttys002
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:8B7466B5-8A4C-4589-8056-0B3FCCB0A6E6
    - PATH=/Users/mahuiying/depot_tools:/opt/MonkeyDev/bin:/usr/local/bin/node:/usr/local/bin/npm:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/mahuiying/.fig/bin:/Users/mahuiying/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=15261
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @magicer0126 - going to close this issue for now. Would help us a lot if you could provide some more info :)
