### ISSUE TITLE
Suggestion not inserted after pressing Enter in Terminal

### ISSUE THREAD

**Issue by nkehoe03** [withfig/fig#1596]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [ ] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Issue Details

When typing in terminal or iTerm2, the autocomplete appears but when I press enter the autocomplete does not fill the line.

I've seen this discussed and closed elsewhere with no fix I could find. (https://github.com/withfig/fig/issues/617)

### Environment

```bash
I recently updated to macOS 12.4 so this may be causing it.


Fig Version: Version 1.0.53 (B339) [Irish] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/niall/.amplify/bin:/Users/niall/opt/anaconda3/bin:/Users/niall/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin:/Users/niall/.composer/vendor/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/niall/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: bash (891) - /dev/ttys004
Current working directory: /Users/niall/Downloads
Current window identifier: 106/% (com.apple.Terminal)
Path: /Users/niall/.amplify/bin:/Users/niall/opt/anaconda3/bin:/Users/niall/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin:/Users/niall/.composer/vendor/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/niall/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=6C2DEB11-FAC7-4968-BD57-B51AE391C2C5
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM_VERSION=3
  - FIG_TERM=1
```

**Comment by mschrage** [comment]
Hey @nkehoe03 can you run `fig doctor` and share the output here?

**Comment by nkehoe03** [comment]
Let's make sure Fig is running...
                                 
✅ Fig bin exists
✅ Fig in PATH
✅ Fig is running
                            
Let's check your dotfiles...
                            
✅ Fig ENV variables are in ~/.profile
✅ Fig ENV variables are in ~/.bash_profile
✅ Fig ENV variables are in ~/.bashrc
✅ Fig ENV variables are in ~/.zshrc
                                           
Let's check if your system is compatible...
                                           
✅ Running macOS
✅ macOS version is 11.x or higher
                 
Let's check what fig diagnostic says...
        
✅ Installation script
✅ Shell /bin/bash is compatible
✅ Fig is installed in /Applications/Fig.app
✅ Autocomplete is enabled
✅ CLI tool path
✅ Accessibility is enabled
✅ PATH and PseudoTerminal PATH match
✅ Secure keyboard input
                                        
Let's check your integration statuses...
                                        
❌ Could not get iTerm version
✅ VSCode integration is enabled

Fig still not working?
Run fig issue to let us know!
Or, email us at hello@fig.io!

**Comment by conorstrejcek** [comment]
I want to mention that this got resolved for me after updating fig. Something I noticed before I updated was that the debugger indicated that text would not be insertable into the shell (something about not finding a terminal session). I wish I had taken a screenshot, but I'm glad it's working for me now.

**Comment by nkehoe03** [comment]
Updating worked for me, after I turned autocomplete off and then back on.
