### ISSUE TITLE
Could not sync remote dotfiles

### ISSUE THREAD

**Issue by jag-k** [withfig/fig#1597]
### Description:
I can't using dotfiles and plugins witch installed from fig

```bash
$ fig source
Could not sync remote dotfiles
```

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B468) [Beta] [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/pozdnyakov/.fig/bin:/Users/pozdnyakov/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/pozdnyakov
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 53679/% (com.apple.Terminal)
  - Active Process: zsh (45403) - /dev/ttys002
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=D7DC11C6-2BD3-4313-B57E-0B2B7D33363E
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/pozdnyakov/.fig/bin:/Users/pozdnyakov/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=45403
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Should be fixed now! Going to close but please let me know if it's not working for you still :)
