### ISSUE TITLE
Fig not opening when pressing space

### ISSUE THREAD

**Issue by jvzaniolo** [withfig/fig#1604]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig not opening when pressing space. https://share.cleanshot.com/gU5vj5

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.6.7 (20G630)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [Brazilian - Pro]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/opt/openjdk@8/bin:/Users/joao.zaniolo/Library/Caches/fnm_multishells/1287_1657223892971/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/joao.zaniolo/.fig/bin:/Users/joao.zaniolo/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,2
  - Chip: 
  - Cores: 4
  - Memory: 32 GB
## OS Info:
  - macOS 11.6.7 (20G630)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/joao.zaniolo
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 172/% (com.googlecode.iterm2)
  - Active Process: zsh (1231) - not a tty
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:E9527E14-D3A3-4577-A3ED-666C8DF1AA75
    - PATH=/usr/local/opt/openjdk@8/bin:/Users/joao.zaniolo/Library/Caches/fnm_multishells/1287_1657223892971/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/joao.zaniolo/.fig/bin:/Users/joao.zaniolo/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=1231
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @jvzaniolo ! Looks like you might be running an older version of zsh-autosuggestions? Try updating that through whatever package manager you used to install it and see if that helps :)

**Comment by jvzaniolo** [comment]
@SeparateRecords Upgrading did not solve the problem but removing it did. Which plugin manager do you use? I'm using zinit

**Comment by jvzaniolo** [comment]
Yes! I changed my zsh plugin manager to one that I can upgrade the plugins, and now it's working fine!!

**Comment by SeparateRecords** [comment]
Sorry, this got buried in my notifications! I get notified for literally _hundreds_ of them in this repo (and PRs in [withfig/autocomplete](https://github.com/withfig/autocomplete)) so sometimes I miss one.

Yes as @parssak said I do manage all my plugins through Fig, it handles updating automatically - so nice to never have to think about it 😄

If all your plugins are available on Fig I'd suggest giving it a try! If not, which aren't available? I'll add them.

**Comment by jvzaniolo** [comment]
> Hey @jvzaniolo ! Looks like you might be running an older version of zsh-autosuggestions? Try updating that through whatever package manager you used to install it and see if that helps :)

Marking this one as the answer!
