### ISSUE TITLE
can I unbind fig-open-workflows from ctrl+f ?

### ISSUE THREAD

**Issue by elzup** [withfig/fig#1605]
### Discussed in https://github.com/withfig/fig/discussions/1600

<div type='discussions-op-text'>

<sup>Originally posted by **elzup** July  6, 2022</sup>
### Description:

I need `forward-char` in `^F`
but It's replaced to `fig-open-workflows` (by fig app?).

this config not found in `fig settings > Shortcuts`.

<img width="556" alt="Screen Shot 2022-07-06 at 16 40 06" src="https://user-images.githubusercontent.com/2284908/177498421-3a14cf7e-9f4c-4b22-9156-b8f7dbcd65b7.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.58 (B467)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.58 (B467) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/hiro/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: ***
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

</div>

**Comment by brendanator** [comment]
Yes please! This has broken how I use the CLI

**Comment by brendanator** [comment]
Temporary work around is to add `bindkey "^F" forward-char` at end of `.zshrc`/`.bashrc`

**Comment by mschrage** [comment]
A fix for this should be live shortly! Sorry for the inconvenience @elzup  @brendanator

**Comment by SeparateRecords** [comment]
This is fixed: you can set `FIG_WORKFLOWS_KEYBIND` to any value now! I use `'\ew'` (esc+w) 🙂
