### ISSUE TITLE
Fig does not find options

### ISSUE THREAD

**Issue by henriquepe** [withfig/fig#1607]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

https://user-images.githubusercontent.com/62850277/178042315-88c943d3-76c2-43e0-b932-bb5c6a5023a1.mov

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.1 (21E258)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B467) [Brazilian]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/henrique/.rvm/gems/ruby-3.0.0/bin:/Users/henrique/.rvm/gems/ruby-3.0.0@global/bin:/Users/henrique/.rvm/rubies/ruby-3.0.0/bin:/Users/henrique/.nvm/versions/node/v14.18.1/bin:/Users/henrique/.local/share/zinit/polaris/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/henrique/.fig/bin:/Users/henrique/.local/bin:/Users/henrique/.rvm/bin:/Users/henrique/Android/sdk/emulator:/Users/henrique/Android/sdk/tools:/Users/henrique/Android/sdk/tools/bin:/Users/henrique/Android/sdk/platform-tools
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/henrique
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 3393/% (com.googlecode.iterm2)
  - Active Process: zsh (91282) - /dev/ttys004
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w1t0p0:ED355336-32D3-469B-BCEF-77748FEB0F17
    - PATH=/Users/henrique/.rvm/gems/ruby-3.0.0/bin:/Users/henrique/.rvm/gems/ruby-3.0.0@global/bin:/Users/henrique/.rvm/rubies/ruby-3.0.0/bin:/Users/henrique/.nvm/versions/node/v14.18.1/bin:/Users/henrique/.local/share/zinit/polaris/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/henrique/.fig/bin:/Users/henrique/.local/bin:/Users/henrique/.rvm/bin:/Users/henrique/Android/sdk/emulator:/Users/henrique/Android/sdk/tools:/Users/henrique/Android/sdk/tools/bin:/Users/henrique/Android/sdk/platform-tools
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=91282
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by fedeci** [comment]
In these cases running `fig restart` in the terminal may help.
