### ISSUE TITLE
Fig suggestions for cd not working

### ISSUE THREAD

**Issue by rajdtta** [withfig/fig#1608]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig suggestions do not show up for using `cd` to navigate between folders, but shows up for things like `git` or `fig`. 

[git example](https://i.raj.wtf/imgs/GAGBPbrQmClXVE7kZXuezxemDm8.png)
[cd example](https://i.raj.wtf/imgs/a5ErD509TfVaNirQVV4YNsdRVkt.png)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 13.0.0 (22A5295h)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [Beta] [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/rajdatta/.local/share/fig/plugins/git-open:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/rajdatta/.fig/bin:/Users/rajdatta/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 13.0.0 (22A5295h)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/rajdatta/Documents/Coding Projects/React/NextJS/nextjs-blog
  - CLI Installed: true
  - Executable Location: /Users/rajdatta/.fig/bin/fig
  - Current Window ID: 1314/% (com.apple.Terminal)
  - Active Process: zsh (33656) - not a tty
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=9BED8AF5-B63F-4331-AFD9-8A917D397973
    - PATH=/Users/rajdatta/.local/share/fig/plugins/git-open:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/rajdatta/.fig/bin:/Users/rajdatta/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=33656
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by parssak** [comment]
this should be fixed now!
