### ISSUE TITLE
Secure keyboard input disabled: Secure keyboard input is on   Secure keyboard process is ターミナル - com.apple.Terminal (via Settings)

### ISSUE THREAD

**Issue by torish14** [withfig/fig#1609]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.6.7 (20G630)|1.0.58|/usr/local/Cellar/fish/3.4.1/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [Beta] [Alphanumeric (Google)]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: true
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/user/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/Users/user/.cargo/bin:/usr/local/opt/binutils/bin:/Users/user/.nimble/pkgs/inim-0.6.1/bin:/Users/user/.nimble/bin:/Users/user/.volta/bin:/Users/user/.pyenv/bin:/Users/user/.local/share/fig/plugins/git-flow:/usr/local/opt/python@3.10/bin:/usr/local/opt/python@3.8/bin:/usr/local/sbin:/usr/local/opt/llvm/bin:/usr/local/bin:/Users/user/.local/bin:/Users/user/.fig/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin
  - SecureKeyboardInput: true
  - SecureKeyboardProcess: ターミナル - com.apple.Terminal (via Settings)
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir6,2
  - Chip: 
  - Cores: 2
  - Memory: 8 GB
## OS Info:
  - macOS 11.6.7 (20G630)
## Environment:
  - User Shell: /usr/local/bin/fish
  - Current Directory: /Users/user/ghq/github.com/torish14/connpass-nuxt3-handson
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 1180/% (com.apple.Terminal)
  - Active Process: fish (26608) - /dev/ttys004
  - Installed via Brew: true
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - TERM_SESSION_ID=45EA850C-336A-4D75-BDCE-A6A6DC783F05
    - TERM=xterm-256color
    - FIG_PID=26608
    - FIG_TERM_VERSION=4.4.1
    - PATH=/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/user/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/Users/user/.cargo/bin:/usr/local/opt/binutils/bin:/Users/user/.nimble/pkgs/inim-0.6.1/bin:/Users/user/.nimble/bin:/Users/user/.volta/bin:/Users/user/.pyenv/bin:/Users/user/.local/share/fig/plugins/git-flow:/usr/local/opt/python@3.10/bin:/usr/local/opt/python@3.8/bin:/usr/local/sbin:/usr/local/opt/llvm/bin:/usr/local/bin:/Users/user/.local/bin:/Users/user/.fig/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Did you try following this guide on[ "Fig and Secure Keyboard Entry"](https://fig.io/docs/support/secure-keyboard-input)?

Try that and then let me know if you're still running into issue!
