### ISSUE TITLE
Red artifact border(?) around fig popup menue

### ISSUE THREAD

**Issue by trinkel** [withfig/fig#1610]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
On one of the three Macs on which I am running fig, there is what I think is a red border around the auto-complete menu (see attached screenshots). When the menu is not populated, it presents as a single vertical line. This happens in both terminal.app and the VSCode integrated terminal. I believe this happened after a recent update. I am guessing it's a config thing rather than a bug since it is only happening on one computer, and that it is related to Fig because it happens in two different programs (unless VSCode is just a window for terminal.app).

I have tried
- restarting Fig
- restarting the computer
- renaming the `~/.fig` folder
- renaming the `~/Library/Preferences/com.mschrage.fig*` folders
- reinstalling Fig

None of these steps have resolved the problem. Any thoughts of where else to look would be appreciated.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [Debug] [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 199
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/trinkel/.fig/bin:/Users/trinkel/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/trinkel/Development/DevOps/_Training/ZellLiew/My Rewatch Stacks/build-and-deploy-workshop3.stack
  - CLI Installed: true
  - Executable Location: /Users/trinkel/.fig/bin/fig
  - Current Window ID: 26143/% (com.apple.Terminal)
  - Active Process: zsh (63616) - /dev/ttys006
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=C33BFB25-A281-4C62-AA31-E5B248C8A994
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/trinkel/.fig/bin:/Users/trinkel/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=63616
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>
![FigExample1](https://user-images.githubusercontent.com/35429283/178158899-bd67a75e-bde2-47cb-acb5-bcd9ac80262b.png)
![FigExample2](https://user-images.githubusercontent.com/35429283/178158900-7c92a2bc-4b33-492f-974c-d79438f40541.png)

**Comment by fedeci** [comment]
Hey @trinkel, It seems you have inadvertently enabled autocomplete window debug. You can disable it running "fig debug autocomplete-window false" in a Terminal!

**Comment by trinkel** [comment]
Wow, that was easy ... and fast. Thanks!

For posterity, the command was 
`fig debug autocomplete-window off`

**Comment by fedeci** [comment]
> Wow, that was easy ... and fast. Thanks!
> 
> For posterity, the command was `fig debug autocomplete-window off`

Oops!
