### ISSUE TITLE
Autocomplete is loading, Make sure you're connected to the internet and try again

### ISSUE THREAD

**Issue by Yuanruikang** [withfig/fig#1613]
### Description:
Autocomplete does not work in Iterm2, VS Code and macOS built-in terminal. 

<img width="1160" alt="Screen Shot 2022-07-13 at 9 56 56 AM" src="https://user-images.githubusercontent.com/35033310/178634690-d36bfc89-b410-48a6-8ebe-1e0d8c5fea21.png">

I have tried some options to fix this problem such as `Reload Autocomplete`, `fig restart`, `fig doctor`, but these methods could not fix this bug.

<img width="744" alt="Screen Shot 2022-07-13 at 9 52 22 AM" src="https://user-images.githubusercontent.com/35033310/178634770-e03b4521-15ce-430d-bb2b-57e9e6df5deb.png">

What's more, I notice that other users provided feedback about the internet unavailability two months ago.They [said](https://github.com/withfig/fig/issues/1437#issue-1233121540) Fig showed **Autocomplete Error loading spec .. Make sure you're connected to the internet** in Debugger (zsh). I came cross this prompt yesterday but today it has changed to this issue's title `Autocomplete is loading, Make sure you're connected to the internet and try again`

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/connor/.local/share/fig/plugins/git-open:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/connor/.fig/bin:/Users/connor/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/connor
  - CLI Installed: true
  - Executable Location: /Users/connor/.fig/bin/fig
  - Current Window ID: 357/% (com.googlecode.iterm2)
  - Active Process: zsh (1598) - not a tty
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:B38F8D7D-C0BF-4441-B7D0-21209B3E9FDA
    - PATH=/Users/connor/.local/share/fig/plugins/git-open:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/connor/.fig/bin:/Users/connor/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=1598
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
@Yuanruikang are you using a VPN or otherwise have an unusual internet connection?

**Comment by Yuanruikang** [comment]
Yes, but the problem seems to have disappeared.Thanks for your reply and I am gonna close the issue.
