### ISSUE TITLE
Fig is not popping up on terminal or vscode for me

### ISSUE THREAD

**Issue by amir-faliam** [withfig/fig#1618]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/amirhajimirsadeghi/.nvm/versions/node/v16.16.0/bin:/Users/amirhajimirsadeghi/.amplify/bin:/Users/amirhajimirsadeghi/.airplane/bin:/Users/amirhajimirsadeghi/.poetry/bin:/usr/local/bin/aws_completer:/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/amirhajimirsadeghi/.fig/bin:/Users/amirhajimirsadeghi/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,3
  - Chip: 
  - Cores: 4
  - Memory: 8 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/amirhajimirsadeghi
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 58995/% (com.apple.Terminal)
  - Active Process: zsh (39423) - /dev/ttys002
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=D60F5F83-91F5-47BC-852E-9D10D99F7162
    - PATH=/Users/amirhajimirsadeghi/.nvm/versions/node/v16.16.0/bin:/Users/amirhajimirsadeghi/.amplify/bin:/Users/amirhajimirsadeghi/.airplane/bin:/Users/amirhajimirsadeghi/.poetry/bin:/usr/local/bin/aws_completer:/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/amirhajimirsadeghi/.fig/bin:/Users/amirhajimirsadeghi/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=39423
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment]
Can you both run `fig doctor --verbose` and share the output here?

**Comment by amir-faliam** [comment]
```
➜ fig doctor --verbose
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ ~/.bashrc contains valid fig hooks
✔ ~/.profile contains valid fig hooks
✔ ~/.zshrc contains valid fig hooks
✔ ~/.zprofile contains valid fig hooks

Let's make sure Fig is running...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ PATH contains ~/.fig/bin
✔ Fig Integration
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Figterm socket
✔ Insertion lock does not exist
✔ PATH and PseudoTerminal PATH match
✔ Autocomplete dev mode
✔ Plugin dev mode

Let's check if your system is compatible...
✔ OS is supported

Let's check fig diagnostic...
✔ Installation script
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled
✔ Secure keyboard input disabled

Let's check your terminal integrations...
✔ VSCode integration is enabled


Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!


20:47:10 in ~ via 🐍 system took 2s 
➜        
```

**Comment by fedeci** [comment]
Same here and I am getting `ReferenceError: Can't find variable: fig`.
@amir-faliam can you do the follwoing steps please?
- Run `fig debug autocomplete-window on`
- A red window should pop out
- Right click the window and choose `Inspect Element`
- Then go to the "Console" tab at the top of the inspector window and share what you see there

**Comment by fedeci** [comment]
It is still not working I suppose?

**Comment by fedeci** [comment]
Are you under a VPN or some particular connection?

**Comment by amir-faliam** [comment]
no VPN or particular connection conditions that I'm aware of. Just went to that URL on my browser and it loaded the JS just fine

**Comment by amir-faliam** [comment]
okay probably should have done this before creating the issue, but quit and restarted fig now it works
