### ISSUE TITLE
Hover over autocomplete suggestion to "select" it

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1621]
Should be simple enough! Currently you can click on a suggestion to insert it, but this is unclear. Showing that it's the selected item is much clearer, plus lets you use `insertSelected` on it

**Comment by fedeci** [comment]
Is this just a visual improvement I suppose?

**Comment by mschrage** [comment]
Since the autocomplete window is "technically" not focused, I'm not sure if the `:hover` selector will work. If it does, then this should be pretty easy!

**Comment by fedeci** [comment]
Let's add raytracing to detect if the cursor position is above one of the suggestions😆

**Comment by SeparateRecords** [comment]
Looked into this, not possible. The window doesn't get hover events :(

@fedeci if you want to implement raytracing then go right ahead haha
