### ISSUE TITLE
autocomplete dropdown not showing anymore

### ISSUE THREAD

**Issue by augusto-camiletti-lrn** [withfig/fig#1622]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I used to see the autocompleted, now the dropdown does not appear anymore.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [Australian]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/gucci/work/lde/bin:/Users/gucci/.fig/bin:/Users/gucci/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/gucci
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 2464/% (com.googlecode.iterm2)
  - Active Process: zsh (29128) - /dev/ttys001
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:17C66F11-10EF-4510-8951-5CBB28405CD0
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/gucci/work/lde/bin:/Users/gucci/.fig/bin:/Users/gucci/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=29128
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by mschrage** [comment]
Try running `fig doctor` and share the output here?

**Comment by SeparateRecords** [comment]
@augusto-camiletti-lrn quick follow up, could you share the output of `fig doctor`?

**Comment by augusto-camiletti-lrn** [comment]
I've seen this a couple of timess
---
✘ Daemon: Websock next error: Io(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })
Attempting to fix automatically...
Re-running check...

✔ Daemon

✔ Everything looks good!

Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!
---
but the issue persist
