### ISSUE TITLE
Fig - High Memory Usage

### ISSUE THREAD

**Issue by alpercoskun** [withfig/fig#1625]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig consumes more than 1.3 GB memory (Mac Mini 2020 M1):

<img width="951" alt="Screen Shot 2022-07-20 at 13 56 12" src="https://user-images.githubusercontent.com/3060567/179965820-e61d2169-507f-4818-ad16-1f8dbaafce72.png">

If I restart Fig, it starts to use 1.3 GB memory again, is it normal ?

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.58 (B472)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.58 (B472) [Turkish Q – Legacy] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/alperc/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin:/Users/alperc/local_release/external/apache/ant/1.9.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/alperc/.fig/bin:/Users/alperc/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by fedeci** [comment]
Here we go again :)

**Comment by fedeci** [comment]
Can you share your bash config and anything that could help me recreate your setup to try reproducing the issue?

**Comment by SeparateRecords** [comment]
@alpercoskun Are you able to schedule a very quick debugging call with me https://calendly.com/robert-fig/support
We've seen this pop up before but haven't been able to nail down what's happening :( would love you help in fixing it!!

**Comment by SeparateRecords** [comment]
@alpercoskun could you privately share you history file with us so we can debug this? Can send it to `hello@fig.io` 🙂

You can also run this command: `fig settings autocomplete.history.disableLoading true` then run `fig restart` and see if that helps!

**Comment by alpercoskun** [comment]
> @alpercoskun could you privately share you history file with us so we can debug this? Can send it to `hello@fig.io` 🙂
> 
> You can also run this command: `fig settings autocomplete.history.disableLoading true` then run `fig restart` and see if that helps!

this command really fixed the issue. now memory usage is about 34 MB!

i sent my history to hello@fig.io

**Comment by fedeci** [comment]
I can assume the issue is related to history loading?

**Comment by parssak** [comment]
We believe the underlying issue here has been resolved. Can you confirm?

**Comment by alpercoskun** [comment]
enabled history loading, unfortunately memory usage is again about 1.4g. fig version is 1.0.61 (B520). should i reset or clean up my history?

**Comment by SeparateRecords** [comment]
@alpercoskun Latest (I think it's a beta??) is B523, can you run `fig settings app.beta true` then `fig restart`?

**Comment by alpercoskun** [comment]
first, I tried to install beta (B525 is installed), but memory usage was still high (1.8g)... after that, I uninstalled fig (brew uninstall fig) and installed it again (B523 is installed), memory usage is 50m now :) I tried to use the terminal for a couple of minutes and memory usage is still low... maybe we can close this issue, and I will open a new issue if it will reoccur.

**Comment by SeparateRecords** [comment]
Sounds good! Alternatively you can comment here, will reopen if it's an issue 🙂

**Comment by cvolzer3** [comment]
> @alpercoskun could you privately share you history file with us so we can debug this? Can send it to `hello@fig.io` 🙂
> 
> You can also run this command: `fig settings autocomplete.history.disableLoading true` then run `fig restart` and see if that helps!

This reduced my memory consumption for the `https://autocomplete.fig.io` process from 1.5 GB to 25.0 MB. `https://desktop.fig.io` held at 130 MB for both.

**Comment by fedeci** [comment]
@cvolzer3 Can you share the result of `fig settings all` and of `fig diagnostics`

**Comment by al-bur** [comment]
@cvolzer3 me too :)

thanx i dont know reason though

**Comment by baotran2207** [comment]
Me too, 2.5GB ram usage is really high

**Comment by AdamGerthel** [comment]
This seems a bit excessive: 
<img width="542" alt="Screenshot 2023-10-12 at 10 11 09" src="https://github.com/withfig/fig/assets/1490370/b645aca1-431b-42a4-a881-2763328e1c95">

Fig settings all:

```
autocomplete.fuzzySearch = false
integrations.hyper.disabled = true
integrations.iterm.disabled = true
integrations.vscode.disabled = true
```
Fig diagnostics:
```
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 24.00 GB
os-info:
  - macOS 13.5.0 (22G74)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/insats
  - exe-path: /Users/insats/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 49fd2f06-8907-4e1c-ab24-038176fc60c5
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/insats/.yarn/bin:/Users/insats/.config/yarn/global/node_modules/.bin:/opt/homebrew/opt/imagemagick@6/bin:/usr/local/opt/openssl/bin:/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin:/Users/insats/Library/Android/sdk/platform-tools:/Users/insats/Library/Android/sdk/emulator:/Applications/Genymotion.app/Contents/MacOS/tools:/opt/homebrew/opt/mongodb-community@4.2/bin:/Users/insats/.rbenv/shims:/opt/homebrew/bin:/Users/insats/.yarn/bin:/Users/insats/.config/yarn/global/node_modules/.bin:/opt/homebrew/opt/imagemagick@6/bin:/usr/local/opt/openssl/bin:/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin:/Users/insats/Library/Android/sdk/platform-tools:/Users/insats/Library/Android/sdk/emulator:/Applications/Genymotion.app/Contents/MacOS/tools:/Users/insats/.nvm/versions/node/v18.17.1/bin:/opt/homebrew/opt/mongodb-community@4.2/bin:/Users/insats/.rbenv/shims:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/insats/.fig/bin:/Users/insats/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 49631
    - FIG_SET_PARENT: 49fd2f06-8907-4e1c-ab24-038176fc60c5
```

Am currently running:

- React Native Metro bundler
- Webpack
- Node server

**Comment by calmack0x401b** [comment]
Same problem here...

![messageImage_1698630687927](https://github.com/withfig/fig/assets/88265025/a1f43aaa-f83e-4e99-b920-036de2b3b14c)

**Comment by calmack0x452** [comment]
Same problem here...

![messageImage_1698630687927](https://github.com/withfig/fig/assets/9415204/f3e1ed1e-4aa5-4669-b4be-34fcbbee5ac7)

**Comment by AdamGerthel** [comment]
As Fig seems abandoned, I've switched to Warp.

**Comment by clo4** [comment]
@AdamGerthel I’ve been pretty inactive in these issues because I no longer work for Fig, but I can tell you with 100% certainty that it is not abandoned! Brendan has shared more details in the Discord community.

**Comment by AdamGerthel** [comment]
> @AdamGerthel I’ve been pretty inactive in these issues because I no longer work for Fig, but I can tell you with 100% certainty that it is not abandoned! Brendan has shared more details in the Discord community.

I've seen their reply regarding this issue and their recommendation is to turn off path autocompletion (one of the main reasons to use Fig in the first place) until they've settled with AWS and started working on the product again. Most of the time, when a tool like this is acquired, it nothing but bad news for the users. Let's hope that's not going to be the case this time around, but I've still switched to Warp because I need a working tool _now_, not some time in the future.

**Comment by krushiraj** [comment]
![image](https://github.com/withfig/fig/assets/19507241/1b20d145-30a9-4448-b9e7-cdaef917ac33)

Same here

**Comment by ToyYan** [comment]
![image](https://github.com/withfig/fig/assets/508968/d70e6983-d2bb-4f63-8fe9-1a40544a98dd)
This happened to me too

**Comment by anwarulislam** [comment]
On Activity Monitor I see `Fig Graphics and Media` consumed `71GB`
This is really bad. I have uninstalled Fig immediately

**Comment by pulpdood** [comment]
<img width="423" alt="image" src="https://github.com/withfig/fig/assets/13587944/e8e8b0e5-cbc0-4d9c-899e-98d6ba489c56">

**Comment by satejbidvai** [comment]
In activity monitor, Fig was taking ~150 GB. My swap used was around ~100GB due to this. Don't know what caused this. Happened for the first time. Did not capture a screenshot this time. 

Any specific things you want me to capture if this happens again?

**Comment by baygeldin** [comment]
Same thing happened to me, `Fig` process ate all my RAM and I had to kill it. I'm on the latest version (`2.17.1`). Not sure if it was a one time thing, but I'll keep an eye on it.

**Comment by richterd** [comment]
Same here, not sure why this ticket is closed, the problem definitely persists...

**Comment by gthomson31** [comment]
Just had the same thing Fig Wrecking my memory

**Comment by shuyi3** [comment]
Same here and it took around 20G mem
