### ISSUE TITLE
Custom completions stop working

### ISSUE THREAD

**Issue by GBrachetta** [withfig/fig#1626]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

After creating my own spec as described [here](https://fig.io/docs/getting-started), that spec works for a period of time (cannot tell for how long, but maybe one or two hours) and then it just stops working.

I need to re-run `npm run dev` inside `/fig-autocomplete/` in order to be able to use it again, and then after another period of time it stops working again.

![Screenshot 2022-07-20 at 17 00 56](https://user-images.githubusercontent.com/57924268/180016706-fa2cfb87-6aee-463c-9d2e-c064b17eaa07.png)

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: true
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: /Users/guille/.nvm/versions/node/v16.14.2/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/guille/.fig/bin:/Users/guille/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/guille
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 49/% (com.googlecode.iterm2)
  - Active Process: zsh (780) - not a tty
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:44165D92-8D34-4DBB-9708-F610F9BEE83F
    - PATH=/Users/guille/.nvm/versions/node/v16.14.2/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/guille/.fig/bin:/Users/guille/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=780
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: installed!
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by SeparateRecords** [comment]
Hey @GBrachetta! That's actually the contributing guide for [withfig/autocomplete](https://github.com/withfig/autocomplete) -- for personal completions, check this out:
https://fig.io/docs/guides/autocomplete-for-internal-tools

**Comment by GBrachetta** [comment]
Thank you for your response.
I have created the specs as per your link, they indeed show up in the settings now:

![Screenshot 2022-07-21 at 15 18 00](https://user-images.githubusercontent.com/57924268/180223281-4d6d767c-f29c-4b79-8615-8516af93c9c6.png)


But my two specs still behave the same way: they work for a little while and then stop working. Not even restarting Fig brings them back.

I'm really confused about this behaviour.

Additionally very often Fig stops working whatsoever, although in this case a restart usually solves the issue.
