### ISSUE TITLE
ctrl-f shortcut key should be reserved to system

### ISSUE THREAD

**Issue by TonnyXu** [withfig/fig#1627]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Shortcut key for creating new workflow, should not bind to `ctrl-f`, `ctrl-f` is the default shortcut key for cursor movement in mac terminal.
![image](https://user-images.githubusercontent.com/211446/180262608-67b89647-094a-4416-9291-be3b8afc50d0.png)

I tried to move the cursor to the start of the commend line, but fig intercepted the shortcut and showed me this create workflow UI. 

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.7|Version 1.0.58 (B472)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.58 (B472) [Romaji] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/tonny/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (13395) - /dev/ttys001
Current terminal session: w0t0p0:BE43FC17-0934-4F6C-99C6-287F72CD8576
Current working directory: /Users/tonny
Current window identifier: 3236/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hi @TonnyXu - this can be fixed by setting `FIG_WORKFLOWS_KEYBIND` to any value, or an empty string to disable entirely
