### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by maximeromain** [withfig/fig#1628]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.5.0 (21G72)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [French]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/maxime.romain/.fig/bin:/Users/maxime.romain/.local/bin
  - SecureKeyboardInput: true
  - SecureKeyboardProcess: iTerm2 - com.googlecode.iterm2 
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.5.0 (21G72)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/maxime.romain
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 2408/% (com.googlecode.iterm2)
  - Active Process: zsh (71992) - not a tty
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:8632B1C0-DC66-416D-A3BB-C53AEB968C95
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/maxime.romain/.fig/bin:/Users/maxime.romain/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=71992
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: Could not read Hyper settings file (/Users/maxime.romain/.hyper.js)
  - Visual Studio Code: application is not present.
  - Docker: false

</p>
</details>

**Comment by fedeci** [comment]
Can you provide some details about what happened please? I am going to close this issue in the meanwhile, please open a new one or reply hereby.
