### ISSUE TITLE
hi!

### ISSUE THREAD

**Issue by SinhTNgoc** [withfig/fig#1630]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.6.0 (20G165)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/sinhtran/.fig/bin:/Users/sinhtran/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,3
  - Chip: 
  - Cores: 4
  - Memory: 8 GB
## OS Info:
  - macOS 11.6.0 (20G165)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/sinhtran
  - CLI Installed: true
  - Executable Location: /Users/sinhtran/.fig/bin/fig
  - Current Window ID: 1291/% (com.apple.Terminal)
  - Active Process: zsh (5282) - /dev/ttys005
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=50DAB01D-0C2E-489D-95D5-86F46624714E
    - PATH=/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/sinhtran/.fig/bin:/Users/sinhtran/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=5282
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by fedeci** [comment]
Hi!
