### ISSUE TITLE
Duplicate branch name suggestions

### ISSUE THREAD

**Issue by azherf** [withfig/fig#1632]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

<img width="955" alt="image" src="https://user-images.githubusercontent.com/1712622/180442202-f225cf69-e8e7-4bdd-82c4-bd525cb73cc1.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.58 (B463)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.58 (B463) [ABC – India] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/azher/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (733) - /dev/ttys001
Current terminal session: w0t0p0:798AE0DB-AD39-4D45-BADB-D8ECE13CF8A6
Current working directory: /Users/azher/momentumio/momentum-fe-app
Current window identifier: 34569/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
https://github.com/withfig/autocomplete/pull/1364
