### ISSUE TITLE
auto completion stops working occasionally. Need to restart 2-3 times a day.

### ISSUE THREAD

**Issue by akshaykrjain** [withfig/fig#1633]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.58 (B472)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.58 (B472) [Norwegian] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/akshayjain/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: bash (1021) - /dev/ttys002
Current terminal session: w0t0p0:AD463963-E82C-4005-9447-9F6F94E44020
Current working directory: /Users/akshayjain/github
Current window identifier: 74/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @akshaykrjain! Sorry for the delay - could we schedule a call so we can debug? https://calendly.com/robert-fig/support This is high priority to get fixed!

**Comment by akshaykrjain** [comment]
@SeparateRecords This issue is no longer reproducible after upgrading to the latest version for fig. Pls, close this. I will raise a new one if it happens again.
