### ISSUE TITLE
Hide icon on MacOS's Menu Bar is not working

### ISSUE THREAD

**Issue by 0xPhong** [withfig/fig#1635]
### Description:
Hide icon on MacOS's Menu Bar is not working, even I toggled "Hide Icon"
I have also restarted Fig and MacOS as well.

<img width="1142" alt="Screen Shot 2022-07-23 at 09 30 01" src="https://user-images.githubusercontent.com/18575253/180587263-5111169d-094f-4906-a0ae-27584a98b7a0.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.58 (B472)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.58 (B472) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/phong/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by MadhavVij** [comment]
I am having the same issue.

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/madhavvij/.fig/bin:/Users/madhavvij/.local/bin:/Users/madhavvij/.fig/bin:/Users/madhavvij/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: Mac14,2
  - Chip: Apple M2
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.5.0 (21G72)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/madhavvij
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 1322/% (com.googlecode.iterm2)
  - Active Process: zsh (26032) - not a tty
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:802135DA-CA39-4A8B-A512-2426966BBC0E
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/madhavvij/.fig/bin:/Users/madhavvij/.local/bin:/Users/madhavvij/.fig/bin:/Users/madhavvij/.local/bin:/Users/madhavvij/.fig/bin:/Users/madhavvij/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=26032
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false

**Comment by SeparateRecords** [comment]
This is fixed now! You can run `fig settings sync` and try again :)
