### ISSUE TITLE
Fig breaks Alfred's 1password workkflow

### ISSUE THREAD

**Issue by JonCrawford** [withfig/fig#1637]
### Description:
Hi, I've been a long-time user of [Alfred](https://alfredapp.com/) and [1Password](https://1password.com/) and [the Alfred workflow](https://github.com/alfredapp/1password-workflow) that enables fast access to saved passwords. After installing Fig, the workflow no longer works due to changes to the shell prompt. It [attempts to execute a command](https://github.com/alfredapp/1password-workflow/blob/353b79e6d814a6311eed2d6981d8749a8de8d291/Workflow/info.plist#L1158) that returns and writes JSON but all the `preexec` stuff pollutes the response and creates a parsing error.

[Issue on the 1password Alred workflow repo.](https://github.com/alfredapp/1password-workflow/issues/27)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|13.0.0|Version 1.0.58 (B472)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.58 (B472) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jon/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Going to close this since I've followed up in the 1password alfred issue - nothing we can really do about this since it seems to be reading from the terminal, but if you can find a workaround given the information in that issue I'll definitely put it here and in the known issues doc!
