### ISSUE TITLE
Duplicate PATH entries for '$HOME/.fig/bin'

### ISSUE THREAD

**Issue by Divkix** [withfig/fig#1639]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Path Contains duplicate entries of '/Users/divkix/.fig/bin'
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/23524935/180829521-43b9ae5d-019a-43f2-b122-d65e8122d240.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.5.0 (21G72)|1.0.58|/opt/homebrew/Cellar/fish/3.5.1/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/Users/divkix/.local/bin:/Users/divkix/.fig/bin:/Users/divkix/.local/bin:/opt/homebrew/opt/openjdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Users/divkix/.fig/bin:/Users/divkix/.fig/bin:/Users/divkix/.fig/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.5.0 (21G72)
## Environment:
  - User Shell: /opt/homebrew/bin/fish
  - Current Directory: /Users/divkix
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 7258/% (com.googlecode.iterm2)
  - Active Process: fish (77017) - /dev/ttys003
  - Installed via Brew: true
  - Environment Variables:
    - FIG_TERM=1
    - TERM_SESSION_ID=w0t0p0:CB734C86-20EB-48AE-8E82-81AF8D07E248
    - TERM=xterm-256color
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/Users/divkix/.local/bin:/Users/divkix/.fig/bin:/Users/divkix/.local/bin:/opt/homebrew/opt/openjdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Users/divkix/.fig/bin:/Users/divkix/.fig/bin:/Users/divkix/.fig/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.4.1
    - FIG_PID=77017
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Thankfully doesn't cause any errors but definitely should get fixed. In Fish I'm actually seeing this _three_ times, not just two.

_sigh_ I wish paths were deduped by default 😭

**Comment by parssak** [comment]
This should be fixed in the newest version!
