### ISSUE TITLE
Hide icon does not work

### ISSUE THREAD

**Issue by daryll-swer** [withfig/fig#1641]
### Description:
> Hiding icon option in the settings does [absolutely nothing](https://twitter.com/DaryllSwer/status/1551650747624091648?s=20&t=l1kotfm1leh_sV_hiWThjg) on macOS 12.5.

![image](https://user-images.githubusercontent.com/80836254/180950511-1c0f1549-e50c-48f4-9c69-eabb8b71c6fc.png)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.5.0 (21G72)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/daryllswer/.fig/bin:/Users/daryllswer/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.5.0 (21G72)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/daryllswer
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 134/% (com.apple.Terminal)
  - Active Process: zsh (3207) - /dev/ttys002
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=C475D5EF-455F-40DA-BE12-03BD888CFE1F
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/daryllswer/.fig/bin:/Users/daryllswer/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=3207
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @daryll-swer ! We're investigating this at the moment. Will close this issue in favor of #1635
