### ISSUE TITLE
Debugger (???) status

### ISSUE THREAD

**Issue by AlfinIndrawan** [withfig/fig#1642]
### Description:
after instlaling fig .autocomplete dont appear and fig doctor also is fine. but my debugger status in icon is Debugger(???).my computer have oh-my-zsh and pk10 theme. disabling zsh-autocomplete plugin doesnt work. using both iterm and terminal also doesnt work any of them

<img width="501" alt="Screenshot 2022-07-27 at 14 25 31" src="https://user-images.githubusercontent.com/77723289/181187241-f6b47216-31c7-44d1-99c4-ca5465dcc678.png">

<img width="426" alt="Screenshot 2022-07-27 at 14 25 56" src="https://user-images.githubusercontent.com/77723289/181187313-4d2bc222-b243-4bcd-9793-e1513c825d16.png">

<img width="376" alt="Screenshot 2022-07-27 at 14 27 37" src="https://user-images.githubusercontent.com/77723289/181187643-9748bf5f-1a9c-4925-a030-81df5b0a2523.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.58 (B472)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.58 (B472) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/a1234/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/a1234/.pyenv/shims:/usr/local/sbin:/Users/a1234/.nvm/versions/node/v16.14.2/bin:/Users/a1234/.composer/vendor/bin:/usr/local/Cellar/postgresql/14.3/bin:/Users/a1234/Documents/Flutter/flutter/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.composer/vendor/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/a1234/.zsh/misc:/Users/a1234/.fig/bin:/Users/a1234/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by pzgz** [comment]
Same experience on my setup, also with on-my-zsh and powerlevel10k, fig cannot show on most of situations, but sometime can show up pop window for paths, for example, if start with double quote and /, then path will show. The status pop showed Debugger (???)  as well. 

Tried to comment out `source ohmyzsh` line in .zshrc, and can see status pop was green with right key buffers, but autocomplete prompt still not show up.

One thing, I am with macOS ventura, not sure if it's due to this reason or not.

**Comment by AlfinIndrawan** [comment]
Well using brew install command fix this idk what happen with the original download

**Comment by trieulh-ict** [comment]
I also use oh-my-zsh and pk10 same as you, but installing from brew still produces this issue. I tried to disable all `source` commands related to ohmyzsh and It runs smoothly. 
Any recommendations to make it work with ohmyzsh?

**Comment by AlfinIndrawan** [comment]
> I also use oh-my-zsh and pk10 same as you, but installing from brew still produces this issue. I tried to disable all `source` commands related to ohmyzsh and It runs smoothly. 
> Any recommendations to make it work with ohmyzsh?

Restart fig from menu bar it works
