### ISSUE TITLE
Fig has stopped working (MacOS 12.4.0)

### ISSUE THREAD

**Issue by admmasters** [withfig/fig#1643]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Fig used to work, but has stopped working full stop. Trying to change directory, trigger any kind of autocompletion and no feedback (iTerm2 and IntelliJ 2022.2).

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)||/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [British]
  - Bundle path: /Users/<username>/Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/<username>/.sdkman/candidates/java/current/bin:/Users/<username>/.bun/bin:/opt/homebrew/bin:/Users/<username>/Library/pnpm:/opt/homebrew/Cellar/go/1.18.3/bin:/Users/<username>/.pyenv/shims:/Users/<username>/.pyenv/bin:/Users/<username>/local/bin:/Users/<username>/.volta/bin:/opt/openssl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/homebrew/bin:/Library/Apple/usr/bin:/Users/<username>/.fig/bin:/Users/<username>/.local/bin:/Users/<username>/Library/Application Support/JetBrains/Toolbox/scripts
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/<username>
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 1085/% (com.googlecode.iterm2)
  - Active Process: zsh (10659) - not a tty
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:64CD487E-3CAD-4120-9733-568424047B35
    - PATH=/Users/<username>/.sdkman/candidates/java/current/bin:/Users/<username>/.bun/bin:/opt/homebrew/bin:/Users/<username>/Library/pnpm:/opt/homebrew/Cellar/go/1.18.3/bin:/Users/<username>/.pyenv/shims:/Users/<username>/.pyenv/bin:/Users/<username>/local/bin:/Users/<username>/.volta/bin:/opt/openssl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/homebrew/bin:/Library/Apple/usr/bin:/Users/<username>/.fig/bin:/Users/<username>/.local/bin:/Users/<username>/Library/Application Support/JetBrains/Toolbox/scripts
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=10659
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by admmasters** [comment]
[Maybe related?](https://github.com/withfig/fig/issues/1633) restarting fig manually through the terminal has re-activated completion, but seems to have got a lot buggier recently.

**Comment by SeparateRecords** [comment]
What's the output of `fig doctor`? Does `fig restart` help?
