### ISSUE TITLE
Starting on startup even when it's disabled.

### ISSUE THREAD

**Issue by sylrs** [withfig/fig#1644]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig is starting on startup, even when "Launch on Start" is disabled in its settings.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.0|Version 1.0.58 (B472)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.58 (B472) [Dutch] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/*user*/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @sylrs! This should be fixed now, run `fig settings sync` and you should be good to go
