### ISSUE TITLE
(eval): alias:40: bad option: -=

### ISSUE THREAD

**Issue by Coder-ZJQ** [withfig/fig#1646]
### Description:

> When I open iTerm or create a new tab, always displays an error message.
> ``` bash
> (eval): alias:40: bad option: -=
> ```
> I try to figure out what's the problem
> I have tried uninstall fig, the error message disappeared.
> But when I reinstall the fig, the error message comes back.
<img width="810" alt="QQ20220728-143530@2x" src="https://user-images.githubusercontent.com/15013685/181438614-c5ed7fc4-7686-466b-bb39-c247e1d67519.png">

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.5.0 (21G72)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [搜狗拼音]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: true
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/Joker/.pyenv/shims:/Users/Joker/.oclint/bin:/usr/local/opt/gnupg@2.2/bin:/usr/local/opt/make/libexec/gnubin:/Users/Joker/.theos/bin:/opt/MonkeyDev/bin:/usr/local/sbin:/opt/local/sbin:/opt/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/usr/local/aria2/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/Joker/.fig/bin:/Users/Joker/.local/bin:/Users/Joker/Library/Android/sdk/tools:/Users/Joker/Library/Android/sdk/platform-tools:/Users/Joker/.flutter/bin::
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 32 GB
## OS Info:
  - macOS 12.5.0 (21G72)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/Joker
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 3572/% (com.googlecode.iterm2)
  - Active Process: zsh (46876) - not a tty
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w1t0p0:C39D6383-FE9C-434C-8F13-0C67C68BB03A
    - PATH=/Users/Joker/.pyenv/shims:/Users/Joker/.oclint/bin:/usr/local/opt/gnupg@2.2/bin:/usr/local/opt/make/libexec/gnubin:/Users/Joker/.theos/bin:/opt/MonkeyDev/bin:/usr/local/sbin:/opt/local/sbin:/opt/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/usr/local/aria2/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/Joker/.fig/bin:/Users/Joker/.local/bin:/Users/Joker/Library/Android/sdk/tools:/Users/Joker/Library/Android/sdk/platform-tools:/Users/Joker/.flutter/bin::
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=46876
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by Coder-ZJQ** [comment]
I have tried comment & uncomment the pre&post block in `.zshrc` file when i create a new tab:

- `.zshrc` with pre & post block:  displays `(eval): alias:40: bad option: -=`
![QQ20220728-150429](https://user-images.githubusercontent.com/15013685/181442652-899dc777-7078-4019-8e58-eeeb0f68c271.gif)

- `.zshrc` without pre & post block: no error message
![QQ20220728-150220](https://user-images.githubusercontent.com/15013685/181442682-3a830fac-2b01-4969-a2c3-2f705ee7ed0d.gif)

**Comment by mschrage** [comment]
Thanks for reporting this! Can you run `alias` and share the output here? @Coder-ZJQ

**Comment by Coder-ZJQ** [comment]
> Thanks for reporting this! Can you run `alias` and share the output here? @Coder-ZJQ
- `alias` output:
``` text 
-='cd -'
...=../..
....=../../..
.....=../../../..
......=../../../../..
1='cd -1'
2='cd -2'
3='cd -3'
4='cd -4'
5='cd -5'
6='cd -6'
7='cd -7'
8='cd -8'
9='cd -9'
_='sudo '
afind='ack -il'
egrep='egrep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
fgrep='fgrep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
g=git
ga='git add'
gaa='git add --all'
gam='git am'
gama='git am --abort'
gamc='git am --continue'
gams='git am --skip'
gamscp='git am --show-current-patch'
gap='git apply'
gapa='git add --patch'
gapt='git apply --3way'
gau='git add --update'
gav='git add --verbose'
gb='git branch'
gbD='git branch -D'
gba='git branch -a'
gbd='git branch -d'
gbda='git branch --no-color --merged | command grep -vE "^([+*]|\s*($(git_main_branch)|$(git_develop_branch))\s*$)" | command xargs git branch -d 2>/dev/null'
gbl='git blame -b -w'
gbnm='git branch --no-merged'
gbr='git branch --remote'
gbs='git bisect'
gbsb='git bisect bad'
gbsg='git bisect good'
gbsr='git bisect reset'
gbss='git bisect start'
gc='git commit -v'
'gc!'='git commit -v --amend'
gca='git commit -v -a'
'gca!'='git commit -v -a --amend'
gcam='git commit -a -m'
'gcan!'='git commit -v -a --no-edit --amend'
'gcans!'='git commit -v -a -s --no-edit --amend'
gcas='git commit -a -s'
gcasm='git commit -a -s -m'
gcb='git checkout -b'
gcd='git checkout $(git_develop_branch)'
gcf='git config --list'
gcl='git clone --recurse-submodules'
gclean='git clean -id'
gcm='git checkout $(git_main_branch)'
gcmsg='git commit -m'
'gcn!'='git commit -v --no-edit --amend'
gco='git checkout'
gcor='git checkout --recurse-submodules'
gcount='git shortlog -sn'
gcp='git cherry-pick'
gcpa='git cherry-pick --abort'
gcpc='git cherry-pick --continue'
gcs='git commit -S'
gcsm='git commit -s -m'
gcss='git commit -S -s'
gcssm='git commit -S -s -m'
gd='git diff'
gdca='git diff --cached'
gdct='git describe --tags $(git rev-list --tags --max-count=1)'
gdcw='git diff --cached --word-diff'
gds='git diff --staged'
gdt='git diff-tree --no-commit-id --name-only -r'
gdup='git diff @{upstream}'
gdw='git diff --word-diff'
gf='git fetch'
gfa='git fetch --all --prune --jobs=10'
gfg='git ls-files | grep'
gfo='git fetch origin'
gg='git gui citool'
gga='git gui citool --amend'
ggpull='git pull origin "$(git_current_branch)"'
ggpur=ggu
ggpush='git push origin "$(git_current_branch)"'
ggsup='git branch --set-upstream-to=origin/$(git_current_branch)'
ghh='git help'
gignore='git update-index --assume-unchanged'
gignored='git ls-files -v | grep "^[[:lower:]]"'
git-svn-dcommit-push='git svn dcommit && git push github $(git_main_branch):svntrunk'
gk='\gitk --all --branches &!'
gke='\gitk --all $(git log -g --pretty=%h) &!'
gl='git pull'
glg='git log --stat'
glgg='git log --graph'
glgga='git log --graph --decorate --all'
glgm='git log --graph --max-count=10'
glgp='git log --stat -p'
glo='git log --oneline --decorate'
globurl='noglob urlglobber '
glod='git log --graph --pretty='\''\'\'\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'\''\'
glods='git log --graph --pretty='\''\'\'\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'\''\'\'\'' --date=short'
glog='git log --oneline --decorate --graph'
gloga='git log --oneline --decorate --graph --all'
glol='git log --graph --pretty='\''\'\'\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\''\'
glola='git log --graph --pretty='\''\'\'\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\''\'\'\'' --all'
glols='git log --graph --pretty='\''\'\'\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\''\'\'\'' --stat'
glp=_git_log_prettily
glum='git pull upstream $(git_main_branch)'
gm='git merge'
gma='git merge --abort'
gmom='git merge origin/$(git_main_branch)'
gmtl='git mergetool --no-prompt'
gmtlvim='git mergetool --no-prompt --tool=vimdiff'
gmum='git merge upstream/$(git_main_branch)'
gp='git push'
gpd='git push --dry-run'
gpf='git push --force-with-lease'
'gpf!'='git push --force'
gpoat='git push origin --all && git push origin --tags'
gpr='git pull --rebase'
gpristine='git reset --hard && git clean -dffx'
gpsup='git push --set-upstream origin $(git_current_branch)'
gpu='git push upstream'
gpv='git push -v'
gr='git remote'
gra='git remote add'
grb='git rebase'
grba='git rebase --abort'
grbc='git rebase --continue'
grbd='git rebase $(git_develop_branch)'
grbi='git rebase -i'
grbm='git rebase $(git_main_branch)'
grbo='git rebase --onto'
grbom='git rebase origin/$(git_main_branch)'
grbs='git rebase --skip'
grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
grev='git revert'
grh='git reset'
grhh='git reset --hard'
grm='git rm'
grmc='git rm --cached'
grmv='git remote rename'
groh='git reset origin/$(git_current_branch) --hard'
grrm='git remote remove'
grs='git restore'
grset='git remote set-url'
grss='git restore --source'
grst='git restore --staged'
grt='cd "$(git rev-parse --show-toplevel || echo .)"'
gru='git reset --'
grup='git remote update'
grv='git remote -v'
gsb='git status -sb'
gsd='git svn dcommit'
gsh='git show'
gsi='git submodule init'
gsps='git show --pretty=short --show-signature'
gsr='git svn rebase'
gss='git status -s'
gst='git status'
gsta='git stash push'
gstaa='git stash apply'
gstall='git stash --all'
gstc='git stash clear'
gstd='git stash drop'
gstl='git stash list'
gstp='git stash pop'
gsts='git stash show --text'
gstu='gsta --include-untracked'
gsu='git submodule update'
gsw='git switch'
gswc='git switch -c'
gswd='git switch $(git_develop_branch)'
gswm='git switch $(git_main_branch)'
gtl='gtl(){ git tag --sort=-v:refname -n -l "${1}*" }; noglob gtl'
gts='git tag -s'
gtv='git tag | sort -V'
gunignore='git update-index --no-assume-unchanged'
gunwip='git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'
gup='git pull --rebase'
gupa='git pull --rebase --autostash'
gupav='git pull --rebase --autostash -v'
gupom='git pull --rebase origin $(git_main_branch)'
gupomi='git pull --rebase=interactive origin $(git_main_branch)'
gupv='git pull --rebase -v'
gwch='git whatchanged -p --abbrev-commit --pretty=medium'
gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign -m "--wip-- [skip ci]"'
history=omz_history
l='ls -lah'
la='ls -lAh'
ll='ls -lh'
ls='ls -G'
lsa='ls -lah'
md='mkdir -p'
rd=rmdir
run-help=man
which-command=whence
```
- I'm using [ohmyzsh](https://github.com/ohmyzsh/ohmyzsh), I found that the alia `-='cd -'` may set by ohmyzsh in [this](https://github.com/ohmyzsh/ohmyzsh/blob/8362ae285a5c227cb20387543483a3597fa31931/lib/directories.zsh#L11)
``` bash
alias -- -='cd -'
```
- I have run this code in terminal, it's work. But when it remove the double dash, the error message shows:
<img width="296" alt="QQ20220729-085918@2x" src="https://user-images.githubusercontent.com/15013685/181662325-3ed8c18f-364e-4494-a395-e00783c43607.png">

**Comment by Coder-ZJQ** [comment]
@mschrage 
You can reproduce this problem by add an alia in fig setting:
<img width="995" alt="image" src="https://user-images.githubusercontent.com/15013685/181876858-6d485746-2a1b-4552-91b1-edcaf00c24a7.png">
then, run `fig source`:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/15013685/181876891-fdbcd57a-bb1a-4e79-a504-d7185de07901.png">

**Comment by hanslemm** [comment]
Hi! I had the same problem. I've removed the ALIAS and the problem has stopped.

**Comment by SeparateRecords** [comment]
Seems like an easy enough fix! Have to switch to using `alias -- '{name}={value}'`

**Comment by Coder-ZJQ** [comment]
> Hi! I had the same problem. I've removed the ALIAS and the problem has stopped. Yet ideally, it would be good to have the alias without the error message.

@hanslemm For the temporary use, you can add the ALIAS like this: 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/15013685/183228261-9f841e27-8cd8-4133-85c9-d6fd0abb2990.png">
(replace it when this issue fixed)
