### ISSUE TITLE
Installed Powerlevel10k Theme For Oh-My-Zsh

### ISSUE THREAD

**Issue by pasp94** [withfig/fig#1652]
### Description:
Fig stopped working after the installation of `powerlevel10k` theme for `Oh-My-Zsh`.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.5.0 (21G72)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B472) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/pasqualespisto/.rvm/gems/ruby-3.0.2/bin:/Users/pasqualespisto/.rvm/gems/ruby-3.0.2@global/bin:/Users/pasqualespisto/.rvm/rubies/ruby-3.0.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/pasqualespisto/.fig/bin:/Users/pasqualespisto/.local/bin:/Users/pasqualespisto/.rvm/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.5.0 (21G72)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/pasqualespisto/Developer
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 2356/% (com.googlecode.iterm2)
  - Active Process: ??? (???) - ???
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:2C563D6D-AE6D-40F7-94A5-1BE318F704D1
    - PATH=/Users/pasqualespisto/.rvm/gems/ruby-3.0.2/bin:/Users/pasqualespisto/.rvm/gems/ruby-3.0.2@global/bin:/Users/pasqualespisto/.rvm/rubies/ruby-3.0.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/pasqualespisto/.fig/bin:/Users/pasqualespisto/.local/bin:/Users/pasqualespisto/.rvm/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.1
    - FIG_WORKFLOWS_KEYBIND=^f
    - FIG_PID=45653
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by berkeatalay1** [comment]
Can you try to install fig plugins for these two 
fig plugins add "Oh My Zsh"
fig plugins add Powerlevel10k

**Comment by happysathya** [comment]
try running this, if it helps. 

`tccutil reset Accessibility com.mschrage.fig`

**Comment by happysathya** [comment]
Yes, it worked.
