### ISSUE TITLE
After enter  login code have error

### ISSUE THREAD

**Issue by netergart** [withfig/fig#1654]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.0|Version 1.0.59 (B486)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.59 (B486) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/netergart/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by juftin** [comment]
Same for me as well. This [comment](https://github.com/withfig/fig/issues/1655#issuecomment-1201281610) was able to get me going in the meantime, although the GUI part of fig is still buggy 
```
fig login
```

**Comment by grant0417** [comment]
Hey @netergart , sorry for the issue. Our server provider was having issues so we have switched to a new one and this should no longer happen!
