### ISSUE TITLE
Fig set up failing

### ISSUE THREAD

**Issue by everuribe** [withfig/fig#1656]
### Description:
After entering code send to email for verification, reached a `Load failed` state. This occurred consistently with different emails and attempting multiple re-installations using `brew` and the manual way

<img width="364" alt="image" src="https://user-images.githubusercontent.com/47759786/182179132-445cae1e-e2ee-4a08-abdf-1e528c4264cc.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.0|Version 1.0.59 (B486)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.59 (B486) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: false
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by Spielboerg** [comment]
Maybe related: https://github.com/withfig/fig/issues/1602

**Comment by SeparateRecords** [comment]
Fixed now! Had some issues with our backend, switched hosting providers so all is resolved and we won't have the same issue in the future :)
