### ISSUE TITLE
Figterm: Failed to recieve figterm diagnostics: Timeout while receiving message

### ISSUE THREAD

**Issue by yandatou** [withfig/fig#1659]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
<img width="890" alt="image" src="https://user-images.githubusercontent.com/21006814/182249537-de4627a0-e81d-49bf-9c56-17d57738504d.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.0|Version 1.0.59 (B486)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.59 (B486) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/pty/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/pty/.local/share/fig/plugins/git-open:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/Users/pty/.fig/bin:/Users/pty/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @yandatou! Looks like the app may not have been running - could you try `fig launch`?

**Comment by yandatou** [comment]
working now.
