### ISSUE TITLE
Fish error on 99_fig_post.fish - (line 8): 'end' outside of a block

### ISSUE THREAD

**Issue by elas7** [withfig/fig#1664]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

Immediately after installing Fig, I get this error on my fish terminal:

```
~/.config/fish/conf.d/99_fig_post.fish (line 8): 'end' outside of a block                                                                                             
end
^
from sourcing file ~/.config/fish/conf.d/99_fig_post.fish
	called on line 246 of file /usr/local/Cellar/fish/3.5.1/share/fish/config.fish
from sourcing file /usr/local/Cellar/fish/3.5.1/share/fish/config.fish
	called during startup
```

<img width="738" alt="Screenshot 2022-08-03 at 18 49 45" src="https://user-images.githubusercontent.com/7537033/182664711-8a6fc9e6-6f7d-4964-9ede-a29690832d5f.png">

Here's the offending line from the output of `~/.local/bin/fig init fish post --rcfile 99_fig_post`:

<img width="364" alt="line" src="https://user-images.githubusercontent.com/7537033/182665608-252e2d58-9caa-4a7d-9cdc-3bd859b4d41c.png">

Have a nice day, Fig team

### Environment

```bash
### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.5.0 (21G72)|1.0.59|/usr/local/Cellar/fish/3.5.1/bin/fish|
fig diagnostic

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.59 (B489) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/elas/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/elas/.fig/bin:/Users/elas/.local/bin:/Users/elas/.fig/bin:/Users/elas/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro13,3
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.5.0 (21G72)
## Environment:
  - User Shell: /usr/local/bin/fish
  - Current Directory: /Users/elas
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: ???
  - Active Process: ??? (???) - ???
  - Terminal: iterm
  - Installed via Brew: true
  - Environment Variables:
    - PATH=/Users/elas/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/elas/.fig/bin:/Users/elas/.local/bin:/Users/elas/.fig/bin:/Users/elas/.local/bin
    - TERM_SESSION_ID=w0t0p0:36B375E3-6D68-44CD-B4F5-31916BDA0BF7
    - FIG_INTEGRATION_VERSION=8
    - TERM=xterm-256color
    - FIG_TERM_VERSION=4.4.2
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: installed!
  - Visual Studio Code: installed!
  - Docker: true
```

**Comment by SeparateRecords** [comment]
Hey @elas7 ! Looks like you created a function in your fig dotfiles but didn't give it a name or body - my guess is if you fix that up or delete it, it will continue working :)

**Comment by elas7** [comment]
That fixed it. Thanks!

**Comment by harrisrobin** [comment]
Same happened to me because I accidentally clicked on "new function" without filling out anything in the Fig UI. I think Fig should remove it if it's clearly empty, it took me a while to figure out how I did that.

For anyone wondering, make sure you didn't create an empty entry here: 
![CleanShot 2022-09-24 at 14 37 48@2x](https://user-images.githubusercontent.com/3880008/192113620-a7dff78b-9a8c-46a9-8f1b-23f45aa82d15.png)

**Comment by elas7** [comment]
That's exactly what happened to me. I agree that Fig should remove the function if it's clearly empty.

**Comment by SeparateRecords** [comment]
Agreed. If the block is empty, we can skip compiling it to shell code cc @rahulsarathy

**Comment by SeparateRecords** [comment]
Btw @harrisrobin, if you like you can now use `$HOME` or `~` for your paths instead of the full `/Users/harris`! Variables and subshells are now fully supported
