### ISSUE TITLE
Transaction API error

### ISSUE THREAD

**Issue by tuytoosh** [withfig/fig#1665]
#### I get this error while installing:

```
Fig is almost set up.
Uh oh -- something went wrong:
Transaction API error: Transaction already closed: A query cannot be executed on a closed transaction... Sentry ID: undefined.

Please try again (right click + reload). If this problem persists, please contact hello@fig.io.
```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.0|Version 1.0.59 (B489)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.59 (B489) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/hamid/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @tuytoosh! Are you able to try running `fig login` and try again? Not sure what was happening here...

**Comment by tuytoosh** [comment]
Maybe it caused by some network restrictions. I tried some ways like using VPN but still it was there and finally the problem fixed by a system reboot! 

By the way thank you for your nice tool.

**Comment by mschrage** [comment]
Thanks! We were running into some backend stability issues a few days ago. This might have been a downstream bug.
