### ISSUE TITLE
New Mac, Autocomplete only shows loading animation

### ISSUE THREAD

**Issue by smlombardi** [withfig/fig#1670]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

On my home mac I just bought an 14" M1 MBP.  I migrated my content from my old i7 2013 MBP.

Now when I use the Terminal, Fig only shows the animated ellipses.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.0|Version 1.0.59 (B489)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.59 (B489) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/stevel/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (26090) - not a tty
Current terminal session: D6DDEAE9-2747-4CB4-8C13-AE51E615C80D
Current working directory: /Users/stevel/github
Current window identifier: 10114/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Can you run `fig doctor` and share the output here?

**Comment by SeparateRecords** [comment]
@smlombardi just bumping this issue! Can you run `fig doctor`? Will help us a lot for debugging 🙂

**Comment by smlombardi** [comment]
Apparently I was not logged in, something I only discovered when trying to run `fig doctor`.  It works now.

Perhaps you need a more in-your-face way to notify users that they are not logged in.
