### ISSUE TITLE
cannot see auto complete

### ISSUE THREAD

**Issue by Zeebradoom** [withfig/fig#1671]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.57|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B439) [Canadian English]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:Users/derrickcuiisawesome/Desktop/Comstruct/flutter/bin:$PATH :/Users/derrickcuiisawesome/Desktop/Comstruct/flutter/bin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:Users/derrickcuiisawesome/Desktop/Comstruct/flutter/bin:$PATH :/Users/derrickcuiisawesome/Desktop/Comstruct/flutter/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/derrickcuiisawesome/.fig/bin:/Users/derrickcuiisawesome/.local/bin :/Users/derrickcuiisawesome/.fig/bin:/Users/derrickcuiisawesome/.local/bin:/Users/derrickcuiisawesome/cs61b-software/bin:/Users/derrickcuiisawesome/cs61b-software/bin:/Users/derrickcuiisawesome/cs61b-software/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro14,1
  - Chip: 
  - Cores: 2
  - Memory: 8 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/derrickcuiisawesome/Desktop
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 2681/% (com.apple.Terminal)
  - Active Process: ??? (???) - ???
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=FFF42FAD-7022-450D-B00D-F88C911C643A
    - PATH=/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:Users/derrickcuiisawesome/Desktop/Comstruct/flutter/bin:$PATH :/Users/derrickcuiisawesome/Desktop/Comstruct/flutter/bin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:Users/derrickcuiisawesome/Desktop/Comstruct/flutter/bin:$PATH :/Users/derrickcuiisawesome/Desktop/Comstruct/flutter/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/derrickcuiisawesome/.fig/bin:/Users/derrickcuiisawesome/.local/bin :/Users/derrickcuiisawesome/.fig/bin:/Users/derrickcuiisawesome/.local/bin:/Users/derrickcuiisawesome/cs61b-software/bin:/Users/derrickcuiisawesome/cs61b-software/bin:/Users/derrickcuiisawesome/cs61b-software/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @Zeebradoom! What exactly was happening? Could your provide some more info + the debugging steps you took? Can you show a screenshot of the debugger while you have something typed out in your terminal?

<img width="826" alt="Screen Shot 2022-08-02 at 10 44 18 am" src="https://user-images.githubusercontent.com/52195359/183549268-c9fc8374-7f76-4065-8264-4eb9c337c5dc.png">

**Comment by SeparateRecords** [comment]
Just bumping this quickly @Zeebradoom, are you still able to reproduce the bug? Does running `fig doctor` show anything?

**Comment by Zeebradoom** [comment]
Hi!
Thanks so much.

Not sure why, but it just doesn’t show the autocomplete?

It used to work, but after I didn’t use it for like a month (just didn’t really use terminal for a month), it no longer links idk why.

Thanks so much,
Derrick : )
