### ISSUE TITLE
Sessions starts in home directory with Fig, even if other specified

### ISSUE THREAD

**Issue by rouse-billy-herren** [withfig/fig#1672]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

When starting the terminal with Fig enabled, the session starts in my home directory, regardless of what is configured in my terminal emulator.   Screen cap below:

https://user-images.githubusercontent.com/96081611/183470126-7f789ea8-5e94-43f8-8beb-ee7e898a1af4.mp4

The same behavior occurs with the PyCharm integration - integrated terminals start in $HOME rather than the directory of the current project.

### Environment

```bash
### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.5.0 (21G72)|1.0.59|/bin/zsh|
fig diagnostic

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.59 (B492) [Beta] [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/billyherren/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/billyherren/.local/bin:/opt/homebrew/bin,:/opt/homebrew/libpq/bin:/opt/homebrew/openssl@3/bin:/Users/billyherren/.local/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/billyherren/.cargo/bin:/Users/billyherren/.fig/bin:/Users/billyherren/Library/Application Support/JetBrains/Toolbox/scripts
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.5.0 (21G72)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/billyherren
  - CLI Installed: true
  - Executable Location: /Users/billyherren/.local/bin/fig
  - Current Window ID: 596/% (com.googlecode.iterm2)
  - Active Process: zsh (13612) - /dev/ttys008
  - Terminal: iterm
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.2
    - PATH=/opt/homebrew/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/billyherren/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/billyherren/.local/bin:/opt/homebrew/bin,:/opt/homebrew/libpq/bin:/opt/homebrew/openssl@3/bin:/Users/billyherren/.local/google-cloud-sdk/bin:/Users/billyherren/.cargo/bin:/Users/billyherren/.fig/bin:/Users/billyherren/Library/Application Support/JetBrains/Toolbox/scripts
    - TERM=xterm-256color
    - TERM_SESSION_ID=w0t0p0:77D474A3-4503-4CF1-8A65-AD03D8F7A925
    - FIG_PID=13612
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false
```

**Comment by fedeci** [comment]
This is a known issue we hope to have solved in the next beta which will be released later today!

**Comment by alexwilkerson** [comment]
i think i'm having a similar issue after the update. all of my terminal windows are now redirecting to my home directory. all of my integrated terminals redirect to the home directory. :(

**Comment by rouse-billy-herren** [comment]
I’m continuing to see this issue after upgrading to B493.

From: Alex Wilkerson ***@***.***>
Date: Monday, August 8, 2022 at 12:47 PM
To: withfig/fig ***@***.***>
Cc: Billy Herren ***@***.***>, Author ***@***.***>
Subject: Re: [withfig/fig] Sessions starts in home directory with Fig, even if other specified (Issue #1672)

CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

i think i'm having a similar issue after the update. all of my terminal windows are now redirecting to my home directory. all of my integrated terminals redirect to the home directory. :(

**Comment by fedeci** [comment]
Fixed in latest beta!
