### ISSUE TITLE
Add `version` as a subcommand

### ISSUE THREAD

**Issue by mamercad** [withfig/fig#1676]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
> Please include a detailed description of the feature (and an image or screen recording, if applicable)

For consistency with the rest of the `fig` subcommands, add `fig version` please.

**Comment by grant0417** [comment]
This will be in the next release :+1:
