### ISSUE TITLE
I can't finish the Fig setup

### ISSUE THREAD

**Issue by daniloapr** [withfig/fig#1677]
### Description:
I can't finish the Fig setup. It only goes until this white screen. I have just downloaded the latest version.

It happened downloading the image in the website. Then, I uninstalled and tried again using `brew install fig` and it works!

<img width="826" alt="image" src="https://user-images.githubusercontent.com/31525418/184038453-8f5d52b1-a1ac-44c0-bbee-95ed2fc5231b.png">

BTW, thanks for this tool! I've been using it for a while and It's amazing!

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.60 (B502)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.60 (B502) [Brazilian] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/danilorego/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @daniloapr! Thanks for reporting this. We are investigating some issues with our backend that may be related.

**Comment by SeparateRecords** [comment]
Should be fixed now!
