### ISSUE TITLE
Settings does not open.

### ISSUE THREAD

**Issue by OlehPetrykUA** [withfig/fig#1678]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
When I want to take a look at settings it shows always this screen.

![image](https://user-images.githubusercontent.com/32721202/184152600-98722076-b28b-45a2-9920-f6ceb97c5ff9.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.0|Version 1.0.59 (B489)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.59 (B489) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/olehpetryk/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/olehpetryk/Stuff/react-test/node_modules/.bin:/Users/olehpetryk/.fig/bin:/Users/olehpetryk/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by LucaPipolo** [comment]
Same same here, we have 2 different machines not able to see settings. Aside from this, activation last step in which you have to enter code receive by email is not working.

**Comment by mschrage** [comment]
Hey @LucaPipolo @OlehPetrykUA can you confirm that this is still not working? Seems like we are having some issues with our backend - thank you for reporting!

**Comment by cojoj** [comment]
It works now, @mschrage 😉 It Seems like you had some issues with your CDN, but it's solved now.

**Comment by LucaPipolo** [comment]
Yep, confirm it's now working. Thanks! 🙏🏼
