### ISSUE TITLE
Fig causes ssh tunnels to be killed instantly

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#168]
> There's one point of attention with Fig that I'd like to raise to you - apart from that, the experience has been super great. Apparently, Fig causes ssh tunnels to be instantly killed - I have a set of ssh tunnel commands that I run on my day-to-day to connect to private services in private clouds. Everything has worked very well until I installed Fig - I noticed that the ssh tunnel commands would complete and not report any errors, but the port to which the connection should have kept active was closed. This happened repeatedly until I decided to uninstall Fig - after that, my tunnels worked again as usual. I'm happy to provide more feedback on this to you, unfortunately, I had to stop using Fig in the meantime as this affected my workday. Please do let me know how I can help :)

**Comment by felipefrancisco** [comment]
Thank you very much for capturing my feedback @mattschrage

**Comment by brendanfalk** [comment]
For better searchability, I am adding these keywords:

Localforward, local port forwarding, RemoteForward, remote port forwarding

**Comment by brendanfalk** [comment]
Here is an example SSH config
```
Host *

  ForwardAgent yes
  ServerAliveInterval 120
  AddKeysToAgent yes
  UseKeychain yes

Host dev
  User root
  HostName ***
  IdentityFile ~/.ssh/abc123
  LocalForward localhost:8000 localhost:8000
  LocalForward localhost:5000 localhost:5000
  LocalForward localhost:1234 localhost:1234
```

**Comment by mattschrage** [comment]
```
Host plat-eu
    IdentityFile [key path here]
    HostName [hostname here]
    User devops
    ForwardAgent yes
    ServerAliveInterval 180
```
```
alias tunnel-analytics-db-production="ssh -4 -L 5439:[redshift cluster http host here]:5439 plat-eu -fN -vvv"
```

**Comment by felipefrancisco** [comment]
Thanks for adding the details of our call here @mattschrage, I validated the issue with the other teammates and commenting out that `Include` line from fig on the `~/.ssh/config` file does indeed solve the problem for them as well

**Comment by mattschrage** [comment]
So the underlying issues has to do with `ControlPersist 1` - when we removed this line, the SSH tunnel remained open. Need to investigate this further.

**Comment by mschrage** [comment]
Linking this with #709

**Comment by parssak** [comment]
SSH is now supported!
