### ISSUE TITLE
"Join Fig Community" button opens up wrong url

### ISSUE THREAD

**Issue by Bberky** [withfig/fig#1680]
### Description

As described in the title. The button **Join Fig Community** in the menu bar app, which should presumably take you to the Fig discord server does instead open up this link: <https://node-backend-mkoj.onrender.com/community>

### Details

|macOS|Fig|Shell|
|-|-|-|
|12.5.0|Version 1.0.60 (B502)|/bin/zsh|

**Comment by brendanfalk** [comment]
<img width="213" alt="CleanShot 2022-08-11 at 13 54 14@2x" src="https://user-images.githubusercontent.com/4949076/184240427-edd0b7d4-d7a6-408b-8383-882d25a91354.png">

@mschrage @sullivan-sean @grant0417 

1. Can we please update to https://fig.io/community
2. Can we make sure we remove all references to https://node-backend-mkoj.onrender.com and replace with api.fig.io? or api.withfig.com - whichever it is?

**Comment by brendanfalk** [comment]
Thanks for flagging @Bberky - for now you can go to fig.io/community to join!

**Comment by mschrage** [comment]
This is fixed!
