### ISSUE TITLE
Seeing red block and border across popup window

### ISSUE THREAD

**Issue by adit-shah-devrev** [withfig/fig#1683]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
<img width="1512" alt="Screenshot 2022-08-12 at 4 05 38 PM" src="https://user-images.githubusercontent.com/96164230/184337716-0ef487a7-6dd8-4847-ac05-24623fae3be4.png">
<img width="1512" alt="Screenshot 2022-08-12 at 4 05 46 PM" src="https://user-images.githubusercontent.com/96164230/184337733-c624f867-9857-46dd-a40d-813f4e3d5233.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.0|Version 1.0.60 (B502)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.60 (B502) [Beta] [Debug] [ABC – India] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/aditshah/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (4924) - /dev/ttys002
Current terminal session: C2CEDE75-D471-4795-9169-9AA4DB237B8A
Current working directory: /Users/aditshah
Current window identifier: 1221/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @adit-shah-devrev! This happens if you've turned on debugging mode for autocomplete.

Try running `fig debug autocomplete-window` to toggle it off!
