### ISSUE TITLE
Fig is eating my computer space beacuse of logs

### ISSUE THREAD

**Issue by pitops** [withfig/fig#1687]
### Description:

![Screenshot 2022-08-13 at 11 09 10 AM](https://user-images.githubusercontent.com/9624361/184475172-b59c4766-7ed9-41db-8a73-e7f48304fe3c.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.59 (B489)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.59 (B489) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/pitops/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Woah! That’s a lot of logs. We’ve pushed a fix and it should go live soon.

In the meantime, you can just delete that logs folder as a workaround!

**Comment by mschrage** [comment]
This should be fixed now. Run `fig update` to download the latest version.

I'm going to close this issue but please let me know if you are still seeing large log files, and I'll reopen it.
