### ISSUE TITLE
Settings app scroll height is not reset on view change

### ISSUE THREAD

**Issue by Addeuz** [withfig/fig#1692]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

So basically what happens is if I'm in the settings app and for example is on the `Autocomplete/General` tab and I scroll to the absolute bottom. Then change the `Autocomplete/Appearance` tab (with no scrollbar). I can't see any of the settings because it seems to be scrolled to the bottom (remembering the scroll I had on general). And I can't scroll up because the view isn't scrollable.
And similarly if I scroll down in the general tab. Then go to the keybindings tab it is already scrolled down.

See the video for both of these issues:

https://user-images.githubusercontent.com/12641358/184713916-7be83787-7c75-40ab-a58f-12011c748851.mov

I noticed while recording that it happens for all tabs that don't have enough settings to warrant a scrollbar.

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.60 (B502) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/andreas/.cargo/bin:/Users/andreas/.fig/bin:/Users/andreas/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip:
  - Cores: 8
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/andreas/dev
  - CLI Installed: true
  - Executable Location: /Users/andreas/.fig/bin/fig
  - Current Window ID: 111740/% (com.googlecode.iterm2)
  - Active Process: zsh (29477) - /dev/ttys002
  - Terminal: iterm
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:A706FC84-DD1C-4F2B-9844-577E530ACAE0
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/andreas/.cargo/bin:/Users/andreas/.fig/bin:/Users/andreas/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.2
    - FIG_PID=29477
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
Hey @Addeuz! Thanks for reporting this. Should be a relatively quick fix (I think). cc @rahulsarathy

**Comment by rahulsarathy** [comment]
Just fixed this! thanks for helping out with the detailed report
