### ISSUE TITLE
"Developer mode enabled" popup in iTerm2/Terminal

### ISSUE THREAD

**Issue by igr** [withfig/fig#1695]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

There is an orange popup that says "Developer mode enabled" that appears in iTerm2 for _anything_ I type. I checked the config, dev mode is off:

![185155436-92181f6e-6247-4afc-ae46-7ff2cb7e3f4d](https://user-images.githubusercontent.com/2280001/185173979-edb1e2fc-5c73-4a61-bca1-40f403330eb3.png)

I just want this popup to disappear. How to do that? I followed the instructions, and nothing worked.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.0|Version 1.0.60 (B507)|/opt/homebrew/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.60 (B507) [SRB] 
UserShell: /opt/homebrew/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ispasic/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: fish (21837) - /dev/ttys001
Current terminal session: w0t0p0:E3B9CB0F-805E-41B8-AA34-6A5D9DFBB1E5
Current working directory: /Users/ispasic
Current window identifier: 877/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mechanizzed** [comment]
I have a same problem in my term on mac

**Comment by atomasaltes** [comment]
Same problem here!

**Comment by mscherr-fastspot** [comment]
Same, I have also clicked on the "Click to disable" button in that prompt and nothing seems to happen:

![CleanShot 2022-08-17 at 09 06 40](https://user-images.githubusercontent.com/61987508/185142059-90d0a941-0517-4a89-b627-5f1ad3accbdc.gif)

**Comment by bradenpowers** [comment]
same here

**Comment by igr** [comment]
https://github.com/withfig/fig/issues/1696

**Comment by thomazrb** [comment]
Same!

**Comment by pedrossdemelo** [comment]
time to disable auto update =/

**Comment by chrisponton** [comment]
Same here :(

**Comment by berkeatalay1** [comment]
Same here 👍

**Comment by KacperMalachowski** [comment]
Same here; reinstall, restart and enable dev mode restart then disable back again doesn't help.

**Comment by wamarra** [comment]
Same here :(

**Comment by DenisLanz** [comment]
Same for me, super annoying…

**Comment by flzpenteado** [comment]
Same :(

**Comment by vitormalencar** [comment]
don't want to spam but the same issue on my side

**Comment by xiaoouwang** [comment]
Same, very annoying

**Comment by simonwarchol** [comment]
+1

**Comment by franck-mahieu** [comment]
+1

**Comment by theAdhocracy** [comment]
+1

**Comment by jgtvares** [comment]
+1

**Comment by jgtvares** [comment]
Hitting `Quit Fig` from the Mac's menu bar and starting `fig` from terminal made the warning disappear for me.

**Comment by loyio** [comment]
same

**Comment by bradenpowers** [comment]
> Hitting `Quit Fig` from the Mac's menu bar and starting `fig` from terminal made the warning disappear for me.

This worked for me as well. Thanks!

**Comment by charlene1804** [comment]
> Hitting `Quit Fig` from the Mac's menu bar and starting `fig` from terminal made the warning disappear for me.

Hero of the day! Thank you!

**Comment by SeparateRecords** [comment]
Hey all! This is fixed now, apologies for the bug 🙂 Will make sure this doesn't happen again.
For anyone reading this: just run `fig restart` and it will be fixed!
