### ISSUE TITLE
[FEATURE] navigate through autocomplete using ctrl+n / ctrl+p

### ISSUE THREAD

**Issue by ygaitonde** [withfig/fig#17]
It's can be awkward to switch to the arrow keys to use autocomplete.

It would be great if one could navigate through the autocomplete options using ctrl+n / ctrl+p

Initially considered vim-style navigation but there will be UX problems if letter keys without modifiers are used to navigate the menu.

**Comment by mattschrage** [comment]
I think we should be able to get this out in the next build! Thanks for creating the issue.

**Comment by mattschrage** [comment]
Added in v1.0.33
