### ISSUE TITLE
Failed to install Fig in Fedora 36 

### ISSUE THREAD

**Issue by Anifyuli** [withfig/fig#1701]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

I try to install with command from Fig documentation. But it can't execute flawlessly. I don't understand how that problem appear on my devices. What should I do? I attach this screenshot to help explain my problem.
![image](https://user-images.githubusercontent.com/73734843/185340470-f3fbccfd-db4b-4b68-92b6-0823a0b85f53.png)
 

### Environment

```bash
.',;::::;,'.                anifyuli@x441uv 
         .';:cccccccccccc:;,.            --------------- 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 36 (Workstation Edition) x86_64
    .:cccccccccccccccccccccccccc:.       Host: X441UV 1.0 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 5.18.17-200.fc36.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 3 days, 8 hours, 53 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 2063 (rpm) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: bash 5.1.16 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 1366x768 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: GNOME 42.4 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: Mutter 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Adwaita 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: adw-gtk3-dark [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Papirus-Dark [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: gnome-terminal 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: Intel i3-6006U (4) @ 2.000GHz 
:cccccccccccccccccccccccccccc:'.         GPU: Intel Skylake GT2 [HD Graphics 52 
.:cccccccccccccccccccccc:;,..            GPU: NVIDIA GeForce 920MX 
  '::cccccccccccccc::;,.                 Memory: 3215MiB / 11862MiB
```

**Comment by mschrage** [comment]
It looks like we our install script has a dependency on `lsb_release`. You could try installing that and then rerunning the script.

cc @squili

**Comment by squili** [comment]
I see what caused this and am pushing an update to our package servers now

**Comment by Anifyuli** [comment]
Ok everyone, my problem is solved. Thanks for your help. Only install `redhat-lsb-core` this problem solved
