### ISSUE TITLE
Not Loading Suggestions

### ISSUE THREAD

**Issue by Hugo-Pereira-98** [withfig/fig#1703]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

Hi guys, my Fig suggestions are not working anymore, for some reason it just show the loading icon and the suggestion never appear on my terminal. I've reloaded it already and still doesn't work. (i don't know if this is related with that previous 'Dev Enviroment' annoying box error).

Any of the suggestions appear anymore.

### Environment

```bash
- Fig version: Version 1.0.60 (B507) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: /Users/hugo/.local/share/zinit/polaris/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hugo/.fig/bin:/Users/hugo/.local/bin:/Users/hugo/Library/Application Support/JetBrains/Toolbox/scripts
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: Mac mini
  - Model Identifier: Macmini9,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB
## OS Info:
  - macOS 12.5.1 (21G83)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/hugo
  - CLI Installed: true
  - Executable Location: /Users/hugo/.fig/bin/fig
  - Current Window ID: 80/% (com.googlecode.iterm2)
  - Active Process: zsh (3163) - /dev/ttys002
  - Terminal: iterm
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=5.1.0
    - PATH=/Users/hugo/.local/share/zinit/polaris/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hugo/.fig/bin:/Users/hugo/.local/bin:/Users/hugo/Library/Application Support/JetBrains/Toolbox/scripts
    - TERM=xterm-256color
    - TERM_SESSION_ID=w0t0p0:D4496C65-0ABA-43CF-B829-5679C885472D
    - FIG_PID=3163
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by joaquimsantiago** [comment]
Same here!

**Comment by Hugo-Pereira-98** [comment]
Another observation, sometimes it shows some suggestions, but it forces on my real command. For example, I just want to run 'yarn dev' I just write 'yarn dev' and when I press enter, it forces 'yarn --node-node-version-check'

**Comment by mschrage** [comment]
Can you run `fig debug autocomplete-window`, right+click the red box and the press "Inspect Elements". Very curious what appears in the Console. Could you share a screenshot?

**Comment by Hugo-Pereira-98** [comment]
![image](https://user-images.githubusercontent.com/82890773/185511077-e51126e8-fbdb-4216-aa90-afdb408bcbe7.png)

**Comment by Hugo-Pereira-98** [comment]
Now it has a red line hahaha
![image](https://user-images.githubusercontent.com/82890773/185511168-467db6c4-83ed-4bdc-97b6-b733fdb27703.png)

**Comment by Hugo-Pereira-98** [comment]
Don't know what this command do, but it stoped having this problem
![image](https://user-images.githubusercontent.com/82890773/185511305-f3a28aa5-a745-4ca3-ad71-29794bba4163.png)
