### ISSUE TITLE
Could not launch fig (No such file or directory os error 2)

### ISSUE THREAD

**Issue by MaxC0d3** [withfig/fig#1711]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

I cannot run fig due to errors appearing in console

![Screenshot_2022-08-21-22-25-38_1920x1080](https://user-images.githubusercontent.com/43556246/185832594-892f40c6-3e69-47e1-a823-d841b773a444.png)

![Screenshot_2022-08-21-22-26-15_1920x1080](https://user-images.githubusercontent.com/43556246/185832639-2292cce7-def1-4eab-aa7a-9a5f47af57db.png)

### Environment

```bash
### Details:
|OS|Fig|Shell|
|-|-|-|
|Linux 5.19.2-arch1-2|fig_desktop 2.3.7
|/usr/bin/zsh|
fig diagnostic

# Fig Diagnostics
## NOTE: Fig is not running, run `fig launch` to get the full diagnostics
## Fig details:
## Hardware Info:
  - Model Name: cpu0
  - Model Identifier: AuthenticAMD
  - Chip: AMD Ryzen 5 PRO 4650G
  - Cores: 8
  - Memory: 16558219 KB
## OS Info:
  - Linux 5.19.2-arch1-2
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /home/max
  - CLI Installed: true
  - Executable Location: /usr/bin/fig
  - Current Window ID: <unknown>
  - Active Process: <unknown>
  - Terminal: <unknown>
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=5.1.0
    - PATH=/home/max/.volta/bin:/usr/share/archcraft/scripts:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/max/.local/bin:/home/max/.fig/bin
    - TERM=alacritty
    - TERM_SESSION_ID=cafc4496-c672-4ffa-a4c2-e00c2183949b
    - FIG_PID=22641
## Integrations:
```

**Comment by grant0417** [comment]
Hey, @MaxC0d3 could you try running the desktop app directly via `FIG_LOG_LEVEL=warn fig_desktop` and see if there are any errors

**Comment by grant0417** [comment]
Can you also run `fig doctor --verbose` on the new version and send the result.

**Comment by MaxC0d3** [comment]
Hi grant, I managed to solve it that same day. Thank you very much

**Comment by fzdwx** [comment]
I have the same problem, also on arch. What should I do?

```
❯ fig doctor --verbose
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ ~/.bashrc contains valid fig hooks
✔ ~/.profile contains valid fig hooks
✔ ~/.bash_profile contains valid fig hooks
✔ ~/.zshrc contains valid fig hooks
✔ ~/.zprofile contains valid fig hooks

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ Fig Integration

Let's make sure Fig is running...
✔ Daemon

Let's see if Fig is in a working state
✔ Figterm
✔ Insertion lock does not exist
✔ PATH and PseudoTerminal PATH match
✔ Autocomplete dev mode
✔ Plugin dev mode
✔ Mission Control is loading from the correct URL

Let's check if your system is compatible...
● Fig's support for Linux 5.19.7-arch1-1 - "Arch Linux" is in development. It may not work properly on your system.


Let's check fig diagnostic...
Failed to get context:
   0: No such file or directory (os error 2)

Location:
   fig_cli/src/cli/diagnostics.rs:238
```

**Comment by MrMaverick-Dev** [comment]
> I have the same problem, also on arch. What should I do?
> 
> ```
> ❯ fig doctor --verbose
> Let's check if you're logged in...
> ✔ Logged into Fig
> 
> Let's check your dotfiles...
> ✔ ~/.bashrc contains valid fig hooks
> ✔ ~/.profile contains valid fig hooks
> ✔ ~/.bash_profile contains valid fig hooks
> ✔ ~/.zshrc contains valid fig hooks
> ✔ ~/.zprofile contains valid fig hooks
> 
> Let's make sure Fig is setup correctly...
> ✔ Fig bin exists
> ✔ PATH contains ~/.local/bin
> ✔ Fig Integration
> 
> Let's make sure Fig is running...
> ✔ Daemon
> 
> Let's see if Fig is in a working state
> ✔ Figterm
> ✔ Insertion lock does not exist
> ✔ PATH and PseudoTerminal PATH match
> ✔ Autocomplete dev mode
> ✔ Plugin dev mode
> ✔ Mission Control is loading from the correct URL
> 
> Let's check if your system is compatible...
> ● Fig's support for Linux 5.19.7-arch1-1 - "Arch Linux" is in development. It may not work properly on your system.
> 
> 
> Let's check fig diagnostic...
> Failed to get context:
>    0: No such file or directory (os error 2)
> 
> Location:
>    fig_cli/src/cli/diagnostics.rs:238
> ```
> 
> ```
> ❯ FIG_LOG_LEVEL=warn fig_desktop
> Fig is already running: /usr/bin/fig_desktop (17396)
> Opening Fig Window...
> 2022-09-12T11:28:17.054938Z ERROR fig_ipc::unix_socket: 21: Failed to connect err=No such file or directory (os error 2) socket="/var/tmp/fig/like/fig.socket"
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Connect(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))', fig_desktop/src/main.rs:120:34
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> edit:
> 
> ok, after reboot to solve it. because i switch `fcitx` to `ibus`.

Hi, I have the exactly same issue of you. 

It seems that you resolve it from switching "fcitx" to "ibus". 

Don't know whats is it and if it safe to do it. 

Can you or someone help me please ? 

Thanks in advance

**Comment by fzdwx** [comment]
> > I have the same problem, also on arch. What should I do?
> > ```
> > ❯ fig doctor --verbose
> > Let's check if you're logged in...
> > ✔ Logged into Fig
> > 
> > Let's check your dotfiles...
> > ✔ ~/.bashrc contains valid fig hooks
> > ✔ ~/.profile contains valid fig hooks
> > ✔ ~/.bash_profile contains valid fig hooks
> > ✔ ~/.zshrc contains valid fig hooks
> > ✔ ~/.zprofile contains valid fig hooks
> > 
> > Let's make sure Fig is setup correctly...
> > ✔ Fig bin exists
> > ✔ PATH contains ~/.local/bin
> > ✔ Fig Integration
> > 
> > Let's make sure Fig is running...
> > ✔ Daemon
> > 
> > Let's see if Fig is in a working state
> > ✔ Figterm
> > ✔ Insertion lock does not exist
> > ✔ PATH and PseudoTerminal PATH match
> > ✔ Autocomplete dev mode
> > ✔ Plugin dev mode
> > ✔ Mission Control is loading from the correct URL
> > 
> > Let's check if your system is compatible...
> > ● Fig's support for Linux 5.19.7-arch1-1 - "Arch Linux" is in development. It may not work properly on your system.
> > 
> > 
> > Let's check fig diagnostic...
> > Failed to get context:
> >    0: No such file or directory (os error 2)
> > 
> > Location:
> >    fig_cli/src/cli/diagnostics.rs:238
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > ❯ FIG_LOG_LEVEL=warn fig_desktop
> > Fig is already running: /usr/bin/fig_desktop (17396)
> > Opening Fig Window...
> > 2022-09-12T11:28:17.054938Z ERROR fig_ipc::unix_socket: 21: Failed to connect err=No such file or directory (os error 2) socket="/var/tmp/fig/like/fig.socket"
> > thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Connect(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))', fig_desktop/src/main.rs:120:34
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > edit:
> > ok, after reboot to solve it. because i switch `fcitx` to `ibus`.
> 
> Hi, I have the exactly same issue of you.
> 
> It seems that you resolve it from switching "fcitx" to "ibus".
> 
> Don't know whats is it and if it safe to do it.
> 
> Can you or someone help me please ?
> 
> Thanks in advance

I think if I rebooted directly at that time, I would have solved the problem without the need for the latter operation.
