### ISSUE TITLE
Fig not working on Linux 5.15.60-1-MANJARO

### ISSUE THREAD

**Issue by thangho98** [withfig/fig#1715]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

When I run the command `env RUST_BACKTRACE=full fig doctor` and see the log image below:

![image](https://user-images.githubusercontent.com/33411543/186066704-a08ff11a-a7cc-43cb-8b1e-00d9ecbf9c00.png)

### Environment

```bash
### Details:
|OS|Fig|Shell|
|-|-|-|
|Linux 5.15.60-1-MANJARO|fig_desktop 2.3.7
|/usr/bin/zsh|
fig diagnostic

# Fig Diagnostics
## NOTE: Fig is not running, run `fig launch` to get the full diagnostics
## Fig details:
## Hardware Info:
  - Model Name: cpu0
  - Model Identifier: GenuineIntel
  - Chip: 12th Gen Intel(R) Core(TM) i5-12400
  - Cores: 6
  - Memory: 16540848 KB
## OS Info:
  - Linux 5.15.60-1-MANJARO
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /home/thawng
  - CLI Installed: true
  - Executable Location: /usr/bin/fig
  - Current Window ID: <unknown>
  - Active Process: <unknown>
  - Terminal: <unknown>
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=5.1.0
    - PATH=/home/thawng/.yarn/bin:/home/thawng/.config/yarn/global/node_modules/.bin:/usr/lib/jvm/java-8-openjdk/bin:/home/thawng/Android/Sdk/platform-tools:/home/thawng/Android/Sdk/tools:/home/thawng/.yarn/bin:/home/thawng/.config/yarn/global/node_modules/.bin:/usr/lib/jvm/java-8-openjdk/bin:/home/thawng/Android/Sdk/platform-tools:/home/thawng/Android/Sdk/tools:/home/thawng/.nvm/versions/node/v14.19.3/bin:/home/thawng/.local/bin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/thawng/.fig/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=6a4d4c89-e64c-43b9-8793-a0d4d4060bd1
    - FIG_PID=291305
## Integrations:
```

**Comment by brendanfalk** [comment]
@grant0417

**Comment by grant0417** [comment]
Hey @thangho98, can you try updating to the latest version, there were some issues with doctor on that version

**Comment by thangho98** [comment]
Hey @grant0417, I have just updated the new version 2.3.10. But the bug still remains. You can see the image below.
![image](https://user-images.githubusercontent.com/33411543/186363969-43998a08-46f9-48a2-8578-7d12b0fc865d.png)

**Comment by thangho98** [comment]
@grant0417 I update the new fig version, and it's working well. Thanks for fixing this.
```
fig-details:
  - cli-version: 1.4.11
  - desktop-version: 2.3.17
  - figterm-version: 5.2.0
```

**Comment by grant0417** [comment]
Yay! Let us know if you have any other issues @thangho98!
