### ISSUE TITLE
Linux install script failing on Ubuntu 18

### ISSUE THREAD

**Issue by msscaroso** [withfig/fig#1717]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

I've run  `curl -SsL https://pkg.fig.io/install.sh | bash`

and got the message

`Unknown distribution bionic. Manually specify using the $DIST variable.`

and fig is not installed.

I've tried setting some values for DIST but I didn't manage to find one that could work.

I'm using Ubuntu 18

### Environment

```bash
I was not able to install the fig CLI
```

**Comment by grant0417** [comment]
Hey @msscaroso, we don't currently have a build for Ubuntu 18.04 `bionic`, the earliest version we support is 20.04 (focal). We should provide a better error there however. Is there any reason you are using 18.04 `bionic`?

**Comment by msscaroso** [comment]
Hey @grant0417 thank you for the reply
Oh Ok. That makes sense!
No specific reason to still be on 18, I'll probably be updating in the near future.

` We should provide a better error there however.`

I think you're right there as well ! 

Thank you !

**Comment by squili** [comment]
@msscaroso We should support bionic now! Could you try again?

**Comment by msscaroso** [comment]
@squili I was able to install now on bionic.

Thank you !!
