### ISSUE TITLE
[Windows]: Help & Support link is broken

### ISSUE THREAD

**Issue by florian-lefebvre** [withfig/fig#1719]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

![image](https://user-images.githubusercontent.com/69633530/186381176-15f42aa5-d583-4b87-b219-95d7b312357b.png)

It currently opens https://fig.io/user-manual/troubleshooting/debug-fig, I don't know what's the good path

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version:
## Hardware Info:
  - Model Name: CPU 1
  - Model Identifier: GenuineIntel
  - Chip: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  - Cores: 4
  - Memory: 17125371 KB
## OS Info:
  - Windows 10.0.19043 N/A Build 19043
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: C:\Users\Admin
  - CLI Installed: true
  - Executable Location: C:\Users\Admin\AppData\Local\Fig\latest\fig.exe
  - Current Window ID:
  - Active Process:
  - Terminal: <unknown>
  - Environment Variables:
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: Unknown command
  - Hyper: Unknown command
  - Visual Studio Code: Unknown command
  - Docker:
```

**Comment by grant0417** [comment]
@rahulsarathy are you also able to resolve this?

**Comment by rahulsarathy** [comment]
Fixed this, thanks for flagging!
