### ISSUE TITLE
Communicate correct way to uninstall Fig more clearly

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#172]
Some users drag Fig to trash rather than running uninstall flow. This leaves the shell hooks installed and results in errors messages in the terminal.

* Can we detect when user drags app to Trash and instead prompt them to click uninstall button?
* Can we detect errors in the shell and print out a more helpful error message (rather than a generic `command not found: fig`)?

**Comment by mattschrage** [comment]
Potentially run uninstall script using launch agents? See this [stackoverflow](https://stackoverflow.com/questions/21794748/detect-mac-application-moved-to-trash-folder-using-launch-agents) post.
