### ISSUE TITLE
Fig not displaying on gnome wayland (nvidia)

### ISSUE THREAD

**Issue by tmuird** [withfig/fig#1724]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

● Fig's support for Linux 5.18.17-200.fc36.x86_64 is in development. It may not work properly on your system.

Let's check fig diagnostic...
✘ Autocomplete is active: Autocomplete is currently disabled. Your desktop integration(s) may be broken!

Let's check your terminal integrations...

Let's check Linux integrations
✔ IBus Env Check
✘ IBus Check: ibus engine is not fig
✘ Desktop Compatibility Check: unknown desktop `gnome`
  
   0: unknown desktop `gnome`

Location:
   fig_cli/src/cli/doctor.rs:155

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

### Environment

```bash
### Details:
|OS|Fig|Shell|
|-|-|-|
|Linux 5.18.17-200.fc36.x86_64|fig_desktop 2.3.7
|/usr/bin/bash|
fig diagnostic

# Fig Diagnostics
## Fig details:
  - Fig version: 
## Hardware Info:
  - Model Name: cpu0
  - Model Identifier: GenuineIntel
  - Chip: Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
  - Cores: 6
  - Memory: 16713875 KB
## OS Info:
  - Linux 5.18.17-200.fc36.x86_64
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /home/tommuir
  - CLI Installed: true
  - Executable Location: /usr/bin/fig
  - Current Window ID: 
  - Active Process: 
  - Terminal: <unknown>
  - Environment Variables:
    - FIG_WORKFLOWS_KEYBIND=^f
    - TERM=xterm-256color
    - PATH=/home/tommuir/.local/bin:/home/tommuir/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/tommuir/.local/bin:/home/tommuir/.fig/bin:/home/tommuir/.spicetify
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: Unknown command
  - Hyper: Unknown command
  - Visual Studio Code: Unknown command
  - Docker:
```

**Comment by grant0417** [comment]
Hey @tmuird, I believe this is an issue with us not detecting that Ubuntu uses gnome, a fix should be out later today

**Comment by grant0417** [comment]
Hey @tmuird, could you try Fig again, if it doesn't work I am available to debug with https://calendly.com/grant-fig/linux-debugging
