### ISSUE TITLE
BlackBox Terminal support

### ISSUE THREAD

**Issue by lucasvsr** [withfig/fig#1725]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
I use a terminal called [BlackBox](https://flathub.org/apps/details/com.raggesilver.BlackBox) which is installed via flatpak and I can't use fig with it. I tried with Gnome Terminal, that's not installed via flatpak and works fine.

I don't know if the installation via flatpak is the cause of the problem, but searching for supported terminals [here](https://fig.io/user-manual/other/linux#supported-terminals), it not there. So...

If you do this I will appreciate a lot. (And I hope you understand my english as well hahaha)

**Comment by grant0417** [comment]
@squili would you be able to look into this!

**Comment by squili** [comment]
It looks like Black Box does not correctly report relative cursor position data to IBus, so this will take an upstream fix to work. I'll add it to my TODO.
