### ISSUE TITLE
Latency causes Fig to insert duplicate characters

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#173]
> There's an issue with latency that causes characters to sometimes be entered twice if typed fast enough.

>I've attached a quick screen recording of the issue; what you see is the result of me pressing "c" and "enter" in quick succession.

https://user-images.githubusercontent.com/3155109/121964397-5abe4a80-cd20-11eb-8ba1-bfae9038c667.mov

**Comment by brendanfalk** [comment]
Adding some more key words for better search: typing too quickly fast delay

**Comment by peterkhayes** [comment]
Hi - just wanted to bump on this. This is still a major issue for me; I really want to like Fig but currently I get duplicated text from Fig about as much as I use the autocomplete :(

In the following video, I'm trying to type `git fresh`, an alias I have to return to the master branch and pull remote changes for a repo. Every time I type it, Fig adds an extra `sh` or `h`.

https://user-images.githubusercontent.com/3714569/142701007-aeeec56c-9e75-43f1-8c57-227589c4241c.mp4

Is there anything I can do in the short term to mitigate this, other than enabling "Show on Tab"?

**Comment by mschrage** [comment]
<blockquote>
Hi there! I’m a long time Fig user and recently installed it on my new, shiny 14” MacBook Pro. I love Fig and think it's a great addition to my workflow. I have run into a bug fairly infrequently, but still a number of times in the past couple days.

I’m having a hard time capturing entire example, but I was able to screen record the actual behavior (but not the setup). 

Here is a description of the bug that I’ve experienced:
- I begin to type in a command or portion of a command (video had subdirectory in cd)
- I see the correct autocomplete
- I press Enter to select this autocomplete
- I press Enter thinking that it will commit and execute my command
- However, it appends some portion of the end of whatever I just autocompleted (not necessarily the remainder that was autocompleted)

My speculation of what might be going wrong:
- It seems that Fig’s idea of what I’ve typed into the Terminal sometimes gets out of sync with what I’ve actually typed
- This would cause Fig to believe that I haven’t type some portion of the previous autocomplete, so it suggests the “ip” of “apprenticeship” in the video

Here’s a description of my setup:
- 2021 14” MacBook Pro (M1 Pro)
- Using iTerm2
- Has occurred in both my persistent hotkey window (used in video) and a more transient, one-time window
- I have Oh My ZSH installed and am using Powerlevel10k as my ZSH theme

I believe that I have experienced this bug with both subdirectory autocompletes (such as with cd) and also using more general commands (like npm or something). But they always take the form of `cd …./-apprenticeship/ip/` or `npm install express —saveave`.

I do not know if the appended suffix is always of the same length, though.
</blockquote>

**Comment by zidik** [comment]
Experiencing this when I type "too fast" for fig.

Example: `> git log --oneline[enter]`
I would expect this just to execute the command, but instead fig autocompletes by adding an extra `e`. So in the end I just have `> git log --onelinee` unexecuted in terminal.

Using zsh. Happens both in iTerm2 and in VS Code terminal.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/usr/local/Cellar/zsh/5.8.1/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B416) [Estonian]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: --removed--
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: --removed--
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 4424/% (com.microsoft.VSCode)
  - Active Process: zsh (13682) - /dev/ttys004
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - PATH=--removed--
    - FIG_TERM_VERSION=4.3.0
    - FIG_INTEGRATION_VERSION=8
    - TERM_SESSION_ID=42CD2C65-9CB8-4F58-8683-D714F67FE3A8
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by patric-eberle** [comment]
Happens for me too when using the PhpStorm terminal.

**OS**
- macOS 12.4
- macBook Pro M1 Pro

**Fig**
10.0.57

**Shell**
/bin/zsh

**Comment by mschrage** [comment]
Thanks for the additional details @patric-eberle! We have a fix in mind for this.

**Comment by mieszko4** [comment]
Happens to me, too. Using `iTerm 2` with `zsh`, `fig_cli 1.4.0`, `macOS 12.3.1`

**Comment by SeparateRecords** [comment]
As far as we can tell, this is fixed now! Definitely comment if it's still happening, but this _should_ be resolved :)
