### ISSUE TITLE
Fig's layer truncate the paste values 

### ISSUE THREAD

**Issue by ChowRex** [withfig/fig#1730]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

After some hours diagnosis, I found the layer which in `$HOME/.fig/bin/zsh\ \(figterm\)`(by default) has a bug when paste some lines into iTerm2, I have recorded it to a gif, see below.

http://7niu.chowrex.com/pictures/202208261602463.gif

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.1|Version 1.0.60 (B507)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.60 (B507) [搜狗拼音] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: false
CLI tool path: <none>
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: false
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by ChowRex** [comment]
![image](https://user-images.githubusercontent.com/30169860/186855486-43b70b6a-d032-45d5-82c7-9a08667941ff.png)

Some info of this layer

**Comment by ChowRex** [comment]
Maybe same with [Pasting large commands of text into fig enabled fish terminal breaks CLI · Issue #1673 · withfig/fig](https://github.com/withfig/fig/issues/1673)

**Comment by rcousens** [comment]
This is the same error I am experiencing in #1673 but with fish instead :)

**Comment by ChowRex** [comment]
> This is the same error I am experiencing in #1673 but when using zsh instead of fish :) I see the same behaviour!

Emmmm, I have read all the content of your post, there is nothig we can do to dig out the reaseon of this case, all error raise by the binary middle layer. So I will colsed this issue and watch on yours.
