### ISSUE TITLE
Fig GUI opens whenever suggestion is selected

### ISSUE THREAD

**Issue by Connor-Bernard** [withfig/fig#1734]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

Whenever I try to complete a command using fig, the GUI pops up making the plugin unusable.  Moreover, this happens even after disabling auto-launch fig on new window.  The video below uses Hyper as that is my primary emulator, but the same thing happens in basic terminal.

https://user-images.githubusercontent.com/78193645/187055371-f9111ab5-8849-4611-b423-302af43d0ebf.mov

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.60 (B513) [Beta] [U.S.]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro18,2
  - chip-id: Apple M1 Max
  - cores: 10 (8 performance and 2 efficiency)
  - mem: 32 GB
os-info:
  - macOS 13.0.0 (22A5321d)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/cr16/labs/lab01/exercise1
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.XQ1suczIE2/org.xquartz:0
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.1.0
    - PATH: /Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/cr16/.fig/bin:/Users/cr16/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 5533729B-E201-47EC-9D58-58B5CD391E18
    - FIG_PID: 21936
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: installed!
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
Does this happen even when the Fig Dashboard is closed?

**Comment by Connor-Bernard** [comment]
> Does this happen even when the Fig Dashboard is closed?

Yes.  Interacting with fig at all causes this issue even after closing out of it.  It also seems like it pops up when first generating suggestions.  Even after running "killall fig" typing anything that would generate suggestions triggers this issue.

**Comment by mschrage** [comment]
How are you inserting suggestions? Are you pressing enter, tab or clicking the item?

**Comment by Connor-Bernard** [comment]
I was pressing enter.  I was able to fix the issue by removing all fig entries on my .zprofile, .zshrc, .bash_profile, and .bashrc and running fig doctor to repair.
