### ISSUE TITLE
Delete autocomplete keybinding

### ISSUE THREAD

**Issue by cjimmy** [withfig/fig#1735]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

How do you delete a keybinding for autocomplete? 🤔 

<img width="800" alt="Screen Shot 2022-08-29 at 11 14 52 AM" src="https://user-images.githubusercontent.com/700885/187234782-1365b7cb-f3b3-40a3-b809-0a0fffbdba16.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.0|Version 1.0.60 (B507)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.60 (B507) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jchion/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (21108) - /dev/ttys008
Current terminal session: w0t1p0:A22A81A9-5B8F-4ACA-8FE4-A092DD0A0D6C
Current working directory: /Users/jchion/Documents/hidrb/shared/e2e
Current window identifier: 55/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by grant0417** [comment]
I believe to delete a key binding all you need to do is hover over it and click the `x` that appears. You can also run `fig settings "autocomplete.keybindings.*" --delete` to reset all of your keybindings.

**Comment by cjimmy** [comment]
Thanks @grant0417 . The CLI command sorta worked. I had to run each key separately. In between these commands restarted Fig, thinking that might be necessary.

<img width="798" alt="Screen Shot 2022-08-29 at 9 40 48 PM" src="https://user-images.githubusercontent.com/700885/187328984-8b4fb0f7-c012-4240-8a02-07f95930e00f.png">

As for the settings UI, there's no `x` that appears.

https://user-images.githubusercontent.com/700885/187329135-c4aca503-087a-428b-94e5-56fbd5619dea.mov

**Comment by cjimmy** [comment]
Whoops. I'll let you close if you wish

**Comment by grant0417** [comment]
Ah yeah that is definitely a bug! @rahulsarathy any idea on what the issue is here?

**Comment by mschrage** [comment]
This has been resolved!
