### ISSUE TITLE
figdome

### ISSUE THREAD

**Issue by hailan20191230** [withfig/fig#1738]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.1|Version 1.0.60 (B507)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.60 (B507) [搜狗五笔] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/huqingye/.fig/bin/fig
Accessibility: false
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hey @hailan20191230! What was going on with Fig? Was it not working? Looks like the app wasn't running, could you try `open -a Fig` then after a few seconds retry `fig doctor`?

Need a little more info to debug this, would help us a lot if you could describe the problem 🙂
