### ISSUE TITLE
Fig Support for DataSpell

### ISSUE THREAD

**Issue by eraygokgor** [withfig/fig#1741]
### Sanity checks

- [x] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Environment

```yaml
Almost any other IDEs from JetBrains are supported by Fig, but DataSpell is not. I do not think the integration would be hard. When will it come?
```

**Comment by mschrage** [comment]
Can you determine the bundle identifier for the DataSpell application and share it here?

**Comment by mschrage** [comment]
@eraygokgor we actually already support DataSpell! Just run `fig install --input-method` to enable it!

Let me know if you're having any issues.
