### ISSUE TITLE
yarn jest completion

### ISSUE THREAD

**Issue by mathieug** [withfig/fig#1742]
### Description:
`yarn jest` completion not appearing

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.0|Version 1.0.60 (B507)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.60 (B507) [French] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: ~/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: false
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/mathieughennassia/.nvm/versions/node/v16.17.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Applications/Privileges.app/Contents/Resources:/Users/mathieughennassia/.fig/bin:/Users/mathieughennassia/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (59580) - /dev/ttys002
Current terminal session: 753DA722-9106-4AE8-A495-ECB86F056E02
Current working directory: ~/work
Current window identifier: 77255/% (com.microsoft.VSCodeInsiders)</pre>
</p>
</details>

**Comment by squili** [comment]
@mathieug Are other completions appearing?

**Comment by mathieug** [comment]
Yes
<img width="222" alt="image" src="https://user-images.githubusercontent.com/951183/190345786-0f1fdd43-b8aa-4b72-9c87-5c44d77a7d7b.png">

**Comment by mathieug** [comment]
It seems to work now.
