### ISSUE TITLE
Login Problem - UI only shows "Something went wrong :("

### ISSUE THREAD

**Issue by MunsMan** [withfig/fig#1748]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

Currently I can't use the Dashboard or the Settings, because I always receive a
```
Something went wrong :(
Unexpected Server Error: [object Object]. Sentry ID: d230b13e243d4d729e9e193e60e46707.
```

When I inspect the App I receive a 500 from the `https://api.fig.io/user/login`. When I try the login in the terminal or doctor everything work like expected.

![Bildschirmfoto 2022-09-05 um 11 42 53](https://user-images.githubusercontent.com/48153666/188419756-5ae64f2a-0bab-46c7-bc21-73b6f343bcfb.png)

Currently autocompletion works and all tested cli commands as well. I think just the failed login response is blocking the UI.

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.61 (B518) [Austrian]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro15,2
  - chip-id: 
  - cores: 4
  - mem: 16 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/munsman
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/munsman/.fig/bin:/Users/munsman/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 9B6BC908-FE82-49DA-BD35-57C0EC1E7ACB
    - FIG_PID: 5979
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by MunsMan** [comment]
Now it started working. I don't know if the login server was just slow or the account creation was the bottleneck.

**Comment by CoderAnchel** [comment]
i have the same problem now

**Comment by MunsMan** [comment]
@CoderAnchel If you want, you can reopen the issue. Do you still have the problem?
