### ISSUE TITLE
Autocomplete does not appear

### ISSUE THREAD

**Issue by sudhamjayanthi** [withfig/fig#1759]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

https://www.loom.com/share/5ca9e638fe19441bb11924fa96b1a1df

doesn't seem to work, `fig restart didn't help`

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.61 (B518) [U.S. International – PC]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro18,3
  - chip-id: Apple M1 Pro
  - cores: 8 (6 performance and 2 efficiency)
  - mem: 16 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/sdm/Desktop/code/rotary-privellege-access/frontend
  - exe-path: /Users/sdm/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_PID: 6721
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Users/sdm/.fig/bin:/Users/sdm/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 38cea4af-1fed-4940-8151-8279d14caa29
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
Hey @sudhamjayanthi can you run `exec bash` and see autocomplete appears in a different shell?

Also would you mind sharing your zshrc?

**Comment by benthecoder** [comment]
so I'm also facing the same issue, and after running exec bash, I see the autocomplete now.

**Comment by sudhamjayanthi** [comment]
hey, it's working today!

was not sure what made it work, but closing the issue for now.
