### ISSUE TITLE
SSH authentication error when running git pull on private repo after adding Fig SSH integration

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#176]
<blockquote>
So the issue was I was unable to checkout a github-hosted private git repo and I figured last change was fig's update of SSH config.

I mentioned briefly in the feedback form, but will try to give better reproduce steps here.

Prerequisites:

* freshly booted MacOS Catalina
* iTerm2, zsh/oh-my-zsh, brew-installed git
* password-protected SSH key
* private GitHub repo with the SSH key added

Trying `git pull` resulted in auth error, no password prompt. Fair enough, `ssh-add` I go. However, result was the same auth error. Not sure what the exact error was, but sure it was the same before and after (several) `ssh-add`. That hasn't happened to me before.
</blockquote>

**Comment by brendanfalk** [comment]
Similar to https://github.com/withfig/fig/issues/189

**Comment by mschrage** [comment]
Closing as stale.
