### ISSUE TITLE
jsurasak009@gmail.com

### ISSUE THREAD

**Issue by jsurasak** [withfig/fig#1761]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

**Comment by mschrage** [comment]
Hey @jsurasak, can you expand on what issues you're experiencing?

**Comment by yajozwamajoz** [comment]
MY Team need backup to my gmail.com
