### ISSUE TITLE
Choose dropdown options by pressing TAB button

### ISSUE THREAD

**Issue by milanzmitrovic** [withfig/fig#1769]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

Choosing dropdown option by pressing TAB does not work.

Even though it is set to be working.

<img width="790" alt="Screenshot 2022-09-10 at 00 12 03" src="https://user-images.githubusercontent.com/58112365/189452777-bdbb689e-9385-426f-bcce-96cd40801117.png">

### Environment

```yaml
> Environment

fig-details:
  - desktop-version: Version 1.0.61 (B519) [Beta] [ABC]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro15,4
  - chip-id: 
  - cores: 4
  - mem: 8 GB
os-info:
  - macOS 12.5.0 (21G72)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/milanmitrovic
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/milanmitrovic/.fig/bin:/Users/milanmitrovic/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: F39957DF-D616-4117-8CC2-3E15C8FF5779
    - FIG_PID: 1772
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

milanmitrovic@Milans-MacBook-Pro ~ % fig settings 
milanmitrovic@Milans-MacBook-Pro ~ % fig settings all
app.beta = true
autocomplete.disable = false
autocomplete.keybindings.insertCommonPrefixOrNavigateDown = "tab"
autocomplete.keybindings.insertSelected = "tab"
autocomplete.keybindings.tab = "insertCommonPrefix"
autocomplete.theme = "dark"
cli.tips.disabled = false
integrations.SSH = true
integrations.experimental = true
integrations.iterm.disabled = true
integrations.ssh = true
plugins.beta = true
```

**Comment by kjkent** [comment]
This may be related to https://github.com/withfig/fig/issues/1762

**Comment by mac-h95** [comment]
I'm also experiencing this issue on macOS Monterey

**Comment by mschrage** [comment]
Hey @mac-h95 @kjkent @milanzmitrovic! Thanks for reporting.

Can you run `fig settings all` and share the output here?

**Comment by milanzmitrovic** [comment]
app.beta = true
autocomplete.disable = false
autocomplete.keybindings.insertCommonPrefixOrNavigateDown = "tab"
autocomplete.keybindings.insertSelected = "tab"
autocomplete.keybindings.tab = "insertCommonPrefix"
autocomplete.theme = "dark"
cli.tips.disabled = false
integrations.SSH = true
integrations.experimental = true
integrations.iterm.disabled = true
integrations.ssh = true
plugins.beta = true

**Comment by mschrage** [comment]
What do you want tab to do @milanzmitrovic ?

**Comment by milanzmitrovic** [comment]
I want TAB button to have same functionality as ENTER button.

When I press TAB, dropdown is shaking. When I press ENTER, dropdown is chosen.

TAB button is more 'natural' for me, I use TAB in PyCharm for choosing autocomplete options.

Please see short video demonstrating 'shaking' after pressing TAB button.

https://user-images.githubusercontent.com/58112365/189994551-8ca226bc-c83d-4a50-99d4-2b193b955a60.mov

**Comment by nvuhung** [comment]
I have the same issue. When press Tab, it always shake. I want to choose the autocomplete options but cannot.

**Comment by mac-h95** [comment]
> Hey @mac-h95 @kjkent @milanzmitrovic! Thanks for reporting.
> 
> Can you run `fig settings all` and share the output here? You might also try running `fig doctor`.

This issue seems to have fixed itself since then. It seems as though sometimes my settings don't update instantly after changing them even if I run fig source.

For example I created an alias today, ran `fig source` and the alias still wouldn't work, until later in the day when I tried the alias again and it did work.

**Comment by milanzmitrovic** [comment]
Hey @mac-h95 you can see settings here.

app.beta = true
autocomplete.disable = false
autocomplete.keybindings.insertCommonPrefixOrNavigateDown = "tab"
autocomplete.keybindings.insertSelected = "tab"
autocomplete.keybindings.tab = "insertCommonPrefix"
autocomplete.theme = "dark"
cli.tips.disabled = false
integrations.SSH = true
integrations.experimental = true
integrations.iterm.disabled = true
integrations.ssh = true
plugins.beta = true

**Comment by jeffmon** [comment]
I have the same settings as everyone else listed above, but running `fig settings all`, I only get this:

```
autocomplete.disable = false
```

Pressing the tab button to choose a dropdown is not working for me as well, it only shakes. Running `fig source` or `fig restart` doesn't help, I even restarted the terminal multiple times.

I'm on Monteray as well, with an M1 chip.

**Comment by mschrage** [comment]
Can everyone try running `fig settings sync`?

**Comment by milanzmitrovic** [comment]
I tried, nothing has changed.

Btw I realised one thing, if there is only one option in dropdown, then TAB works. If there are two or more options, TAB doesn't work.

https://user-images.githubusercontent.com/58112365/191600769-c285bd49-b7d0-4b1e-8887-2f3ecdd259f4.mov

**Comment by jeffmon** [comment]
Thank you, @mschrage, that worked!

I used these settings:
![Screen Shot 2022-09-21 at 2 06 07 PM](https://user-images.githubusercontent.com/18548300/191630820-d68c590d-1376-4e77-8b3b-a2343a7f754a.png)
Then ran `fig settings sync` and the tab-to-choose dropdown option is working.

**Comment by milanzmitrovic** [comment]
@jeffmon @mschrage Thanks for advice! After doing 'fig settings sync; and making TAB into 'Insert common prefix or navigate' instead of only 'Insert common prefix', it works now on my machine :)

This issue can be closed.

**Comment by mschrage** [comment]
We realized that our settings syncing infra had gone down. This should be resolved for everyone going forward. You may need to run `fig doctor` once to apply the fix but, after that, settings should be applied correctly.

So sorry for the inconvenience here. Thanks again for bearing with us and reporting this.

**Comment by kjkent** [comment]
hey @mschrage, sounds pretty promising! However I still seem to have the bug. 

In this example:
![image](https://user-images.githubusercontent.com/96310790/192115572-4eecf97e-dbb3-459e-bace-22260228c7ec.png)
I would think that hitting tab here would navigate down as Fig can't insert any more common chars. However, Fig shakes instead.

The Fig settings GUI still seems to re-select the defaults. For example, I've just set my settings.json to this:
```JSON
{
  "app.beta": true,
  "app.hideMenubarIcon": true,
  "app.launchOnStartup": true,
  "app.preferredTerminal": "Alacritty",
  "autocomplete.firstTokenCompletion": false,
  "autocomplete.keybindings.command+-": "ignore",
  "autocomplete.keybindings.command+=": "ignore",
  "autocomplete.keybindings.command+i": "ignore",
  "autocomplete.keybindings.control+-": "decreaseSize",
  "autocomplete.keybindings.control+=": "increaseSize",
  "autocomplete.keybindings.control+i": "toggleDescription",
  "autocomplete.keybindings.control+j": "ignore",
  "autocomplete.keybindings.control+k": "ignore",
  "autocomplete.keybindings.control+n": "ignore",
  "autocomplete.keybindings.control+p": "ignore",
  "autocomplete.keybindings.down": "navigateDown",
  "autocomplete.keybindings.enter": "insertSelectedAndExecute",
  "autocomplete.keybindings.shift+tab": "ignore",
  "autocomplete.keybindings.tab": "insertCommonPrefixOrNavigateDown",
  "autocomplete.keybindings.up": "navigateUp",
  "autocomplete.preferVerboseSuggestions": false,
  "autocomplete.scrollWrapAround": true,
  "autocomplete.theme": "dracula",
  "integrations.experimental": true,
  "plugins.beta": true
}
```
And my GUI to this:
![image](https://user-images.githubusercontent.com/96310790/192115704-e9aa1e28-bc3d-4540-b103-cef684988a6c.png)

After running various combinations of `fig sync`, `fig source`, `fig doctor`, and `fig restart`, my settings file is identical; however, the GUI looks like this:
![image](https://user-images.githubusercontent.com/96310790/192116713-d9b0b1cd-a880-400c-9a8d-cfea939b7290.png)

And fig shakes if I push tab while looking at this:
![Screenshot_20220924_211227](https://user-images.githubusercontent.com/96310790/192116732-ec606c20-7212-4101-afa2-f3d4673b9ed3.png)
