### ISSUE TITLE
Allow Fig to run as `root` user on Linux

### ISSUE THREAD

**Issue by SupianIDz** [withfig/fig#1779]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

Thanks in advance for bringing FIG into the Linux ecosystem, it's really cool.

But there is a problem that may be big enough for some people, myself included.

FIG Linux runs flawlessly on **Zorin OS 16.1** (_**and maybe on other types of Linux with root user instead of regular user.**_) for normal users, but not for `root` users. It doesn't work. 

```
Running doctor as root is not supported.
If you know what you're doing, run the command again with --verbose.
```

```
$ fig doctor --verbose

Running doctor as root is not supported.
Let's check if you're logged in...
Logged into Fig

Let's check your dotfiles...
~/.bashrc contains valid fig hooks
~/.profile contains valid fig hooks
~/.zshrc contains valid fig hooks
~/.zprofile contains valid fig hooks

Let's make sure Fig is setup correctly...
Fig bin exists
PATH contains ~/.local/bin
Fig Integration: Figterm is not running
  FIG_INTEGRATION_VERSION=None

Let's make sure Fig is running...
Daemons

Let's see if Fig is in a working state...
Figterm: No TERM_SESSION_ID
  
   0: No TERM_SESSION_ID
   1: environment variable not found

Locations:
   fig_cli/src/cli/doctor.rs:577

Backtrace committed. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Insertion lock does not exist
PATH and PseudoTerminal PATH match
Autocomplete dev mode
dev mode plugin
Mission Control is loading from the correct URL

Let's check if your system is compatible...
Fig's support for Linux 5.15.0-46-generic - "Zorin OS 16.1" is in development. It may not work properly on your system.


Let's check the diagnostic fig...
Filed to get context:
   0: No such file or directory (os error 2)

Locations:
   fig_cli/src/cli/diagnostics.rs:271

Backtrace committed. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

Why does it have to be `root` ? there are some people who are more comfortable using `root` directly than using a regular account and using `sudo`.

I've tried restarting several times but to no avail.

### Environment

```yaml
fig-details:
  - cli-version: 1.5.0
  - desktop-version: 2.4.6
  - figterm-version: 5.2.0
hardware-info:
  - chip-id: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
  - cores: 2
  - mem: 7734.34 GB
os-info:
  - kernel: 5.15.0-46-generic
  - distro: "Zorin OS 16.1"
  - distro-version: "16.1"
environment:
  - shell: /usr/bin/zsh
  - terminal: <unknown>
  - cwd: /root
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - XDG_CURRENT_DESKTOP: zorin:GNOME
    - SHELL: /usr/bin/zsh
    - QT_IM_MODULE: ibus
    - GTK_IM_MODULE: ibus
    - XDG_SESSION_DESKTOP: zorin
    - PATH: /root/.composer/vendor/bin:/root/.nvm/versions/node/v18.8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/root/.local/bin:/root/.fig/bin:/usr/local/bin
    - XMODIFIERS: @im=ibus
    - XDG_SESSION_TYPE: x11
    - GLFW_IM_MODULE: ibus
    - TERM: xterm-256color
    - DISPLAY: :0
    - FIG_PID: 77296
```

**Comment by mschrage** [comment]
We'll investigate whether this is possible. cc @grant0417 @squili

**Comment by grant0417** [comment]
Looks like you might need to run `fig install --force` as `root` to install our integrations.

Just curious why you want to use fig as `root`? Is there some specific use case there?

**Comment by SupianIDz** [comment]
> Just curious why you want to use fig as `root`? Is there some specific use case there?

I usually at work often deal with services / programs that need root privileges to do something, it's annoying every time commanding the service has to use `sudo` and enter the password over and over again, it's boring.

So since 2011 always login to my Linux always with root user to save a lot of time and the health of my fingers. While most people are against this, I've never had any damage issues with the `root` user so far.

**Comment by SupianIDz** [comment]
> Looks like you might need to run `fig install --force` as `root` to install our integratio

Work as expected, thank you.
