### ISSUE TITLE
`Option::unwrap()` on a `None` value', rust-lib/fig_color/src/color.rs:199:18`

### ISSUE THREAD

**Issue by androchentw** [withfig/fig#1780]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

I'm facing an issue when opening new iTerm2 tab with the following error message

```sh
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', rust-lib/fig_color/src/color.rs:199:18
         note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This happens whenever I open a new tab, and thus I could not create any new tabs or windows, unless I commented out the fig part `~/.zshrc` like this: 

```sh
# Fig post block. Keep at the bottom of this file.
# [[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
```

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.61 (B520) [Beta] [ABC]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro18,3
  - chip-id: Apple M1 Pro
  - cores: 8 (6 performance and 2 efficiency)
  - mem: 16 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/AndroChen
  - exe-path: /Users/AndroChen/.local/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /Users/AndroChen/.pyenv/shims:/opt/homebrew/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/AndroChen/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/AndroChen/.fig/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: w0t0p0:FF552850-D92E-41CC-A0F8-75A1B376F595
    - FIG_PID: 681
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
We have a fix for this coming out on beta ASAP. In the meantime, you could try downgrading to the current stable version. (Just uninstall the beta and reinstall stable).

**Comment by androchentw** [comment]
@mschrage Thanks for the advice!
I've managed to work around this by downgrading to the stable version.

1. Settings > General > Beta > off
2. Terminal: 
```sh
brew uninstall fig
brew install fig
fig version
> fig_cli 1.5.0
```

**Comment by mschrage** [comment]
We should have pushed a new build to the beta that resolves this. Would you mind upgrading again and confirming that this bug has been squashed?

**Comment by SeparateRecords** [comment]
Going to close for now since this issue should be fixed. Let us know if it happens again 🙂
