### ISSUE TITLE
Fig unable to find socket file

### ISSUE THREAD

**Issue by ammarlakho** [withfig/fig#1784]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

Fig isn't working after multiple restarts and this is the error message I receive on running `fig doctor`. Something to do with it not being able to find the socket file. 

![Screenshot 2022-09-14 at 2 19 24 PM](https://user-images.githubusercontent.com/50075749/190114862-5aedba18-5263-455d-ae37-476729816d6f.png)

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.61 (B520) [ABC]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro17,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 8 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/ammarlakho/Documents
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_PID: 23721
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: F30956A0-AE86-4BFD-8284-AFD424261A9B
    - PATH: /Users/ammarlakho/.nvm/versions/node/v16.17.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ammarlakho/.ebcli-virtual-env/executables:/Users/ammarlakho/.fig/bin:/Users/ammarlakho/.local/bin:/Users/ammarlakho/Library/Android/sdk/emulator:/Users/ammarlakho/Library/Android/sdk/platform-tools
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM_VERSION: 5.2.0
    - FIG_TERM: 1
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
Hey @ammarlakho! Does opening a new terminal resolve this issue?

**Comment by ammarlakho** [comment]
Not at that moment but now it's working. Still fig keeps giving this error randomly and sometimes has to be restarted.

**Comment by mschrage** [comment]
We have a beta coming out in the next 30min or so that may resolve this.

Can you update by running `fig settings app.beta true` and report whether you're still experiencing this bug?
