### ISSUE TITLE
Fig breaks Contexts macOS app

### ISSUE THREAD

**Issue by zardoy** [withfig/fig#1786]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hey! I really really autocompletions! But unfortunately, popup window breaks [Contexts](https://contexts.co/) app. I'm not sure, but I think previous updates didn't have this impact.

![Sep-15-2022 03-36-53](https://user-images.githubusercontent.com/46503702/190286697-6c5cb99c-b6be-4d78-8c64-52b6e26da24f.gif)

Str:

1. Fire autocomplete popup in any app
2. Do cmd+tab with contexts, it shows you!

Expected: fig is not visible
Actual: Fig is a window that can receive focus

After fig is focused, no window receive focus.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.61 (B520)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.61 (B520) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/vitaly/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by zardoy** [comment]
Oh, I completely forgot that it has rules, where I can just ignore fig app, but I still thing would be better provide better UX by default, if possible.

**Comment by SeparateRecords** [comment]
Unfortunately there's not a lot we can do about this :( I've actually looked into it before. Best option is to use a rule in Contexts to ignore Fig as you're doing right now.
