### ISSUE TITLE
Completion does not work under certain circumstances

### ISSUE THREAD

**Issue by yiluoegit** [withfig/fig#1788]
If I don't connect to the internet in time after powering on it disables the completion and I have to turn on the vpn and restart the fig.

<details><summary>Original</summary>

如果我开机后没有及时连接到互联网则会使补全功能失效，我必须打开vpn并重新启动fig.

</details>

**Comment by SeparateRecords** [comment]
Hi @yiluoegit, sorry for the issue! Can you run `fig doctor` and `fig diagnostic` when it's not working so we can debug? We need as much info as you can give us 🙂

**Comment by yiluoegit** [comment]
@SeparateRecords, My Chinese is not good, look at my eyes, fig doctor: 
<img width="395" alt="截屏2022-09-16 14 14 57" src="https://user-images.githubusercontent.com/76962284/190569814-43a76eac-9e2b-4696-b516-17a94693af83.png">
fig diagnostic: 
<img width="1728" alt="截屏2022-09-16 14 15 07" src="https://user-images.githubusercontent.com/76962284/190569915-8e4e8f2f-77ba-4003-a0fc-ac5cf09dfca9.png">
This can't be completed if I don't connect to the Internet for the first time after starting the computer
