### ISSUE TITLE
Seems that fig can't always recognise subdirectories when trying to cd into multiple paths

### ISSUE THREAD

**Issue by noamh-lin** [withfig/fig#179]
When I try to CD to a subdirectory of a subdirectory it seems that fig can't show me the list of the 2nd level of subdirectories.
Might relate to some of my added extensions but it looks like this:
![image](https://user-images.githubusercontent.com/58387017/122010692-05d41000-cdc4-11eb-9ce6-6f7af5f037cf.png)
As you can see by my "shadow command" extension I have a `local-deploy` folder (amongst others) and it seems that fig can't show me the 2nd level of subdirectories

**Comment by mattschrage** [comment]
Hey @noamh-lin! Thanks for opening this issue.

First off, are you sure that the `local-deploy` directory exists? Zsh-autosuggest uses your history to provide suggestions and sometimes can be incorrect.

Assuming that the directory does exist, do you have a custom `CDPATH` or anything fancy like that?

**Comment by noamh-lin** [comment]
I don't have any fancy `CDPATH` though now I will probably check this 😅 
Regardless, it seems that fig only suggests a single hierarchy of folders, if I write for example:
`cd ~/` it will complete the `proj` folder but it won't then complete the `linops` folder :)

**Comment by noamh-lin** [comment]
After some further looking about, it seems that it won't display sub directories since I didn't put a `/` 😭
