### ISSUE TITLE
Could not load URL...

### ISSUE THREAD

**Issue by phuctm97** [withfig/fig#1801]
### Description:
Every time I open fig settings, I get this.

<img width="1030" alt="CleanShot 2022-09-20 at 11 56 49@2x" src="https://user-images.githubusercontent.com/25026967/191164173-6a011d5c-53a7-4533-b4a6-4ba2cfca7358.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.6.0|Version 1.0.61 (B528)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.61 (B528) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/phuctm97/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/phuctm97/.nvm/versions/node/v14.19.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/phuctm97/.fig/bin:/Users/phuctm97/.local/bin:/Users/phuctm97/Library/Android/sdk/emulator:/Users/phuctm97/Library/Android/sdk/tools:/Users/phuctm97/Library/Android/sdk/tools/bin:/Users/phuctm97/Library/Android/sdk/platform-tools:/Users/phuctm97/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/phuctm97/.antigen/bundles/dracula/zsh
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @phuctm97! Can you run `fig settings all`? My guess is that this either has to do with internet connectivity or some strange internal developer setting that you still have turned on. :)

**Comment by phuctm97** [comment]
Oh fixed it now by deleting developer host 😁. Thank you!
