### ISSUE TITLE
Auto complete wizard crashed

### ISSUE THREAD

**Issue by fishtankmike** [withfig/fig#1802]
### Description:
> I turned on my mac this morning and Fig had the app was in my dock and it was some kind of auto complete settings wizard but after selecting the first option it asked a second similar question but I could not proceed from there. I clicked all 3 options but no joy. It looked like there was some writing underneath the gif/animation but I could not read it. Not complaining just letting you know :)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.1|Version 1.0.61 (B526)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.61 (B526) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/mike/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Thanks for reporting @fishtankmike! This issue has been resolved. Please restart Fig do pull the latest version of Dashboard.
