### ISSUE TITLE
"Report a bug..." doesn't work if a user with 2FA tries to report a bug when logged out of GitHub

### ISSUE THREAD

**Issue by timmattison** [withfig/fig#1804]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

GitHub's login process fails for logged out users that have 2FA enabled that try to use the Fig "Report a bug..." menu item.

To reproduce:
- Make sure 2FA is enabled
- Log out of GitHub
- Click "Report a bug..." in Fig
- Log in to GitHub
- You will get a 500 error

Video 

https://user-images.githubusercontent.com/300258/191325376-5102f6a4-4e2d-43ef-855a-0cde024af599.mp4

FYI, e-mail address and password manager popup hidden with a black box

### Details:

|macOS|Fig|Shell|
|-|-|-|
|12.6.0|Version 1.0.61 (B528)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.61 (B528) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/timmattison/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/timmattison/.fig/bin:/Users/timmattison/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @timmattison, like I mentioned on Twitter. I think this is a GitHub bug. Unfortunately, not much we can do about it. 

We fixed the other issue you brought up (#1802)  :)
