### ISSUE TITLE
Fig window menu opens every time at start even if option is disabled!!!

### ISSUE THREAD

**Issue by juanitorduz** [withfig/fig#1807]
Fig window menu opens every time at start even if option is disabled!!! Super frustrating. Mac OS

**Comment by juanitorduz** [comment]
**Update: ** I had to manually remove Launch Daemons and Launch Agents in Finder following https://www.drbuho.com/how-to/disable-startup-items-mac

Not the nicest user experience ...

**Comment by mschrage** [comment]
This was an issue with our settings syncing. See #1769 for more details. Underlying issue should be resolved now.

**Comment by prameshbajra** [comment]
Running
```
fig settings sync
fig doctor
```
did the job 👍🏼 

MacOS Monterey
