### ISSUE TITLE
apperance and "tab" navigation not working

### ISSUE THREAD

**Issue by jmac05r1** [withfig/fig#1812]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

![Screen Shot 2022-09-21 at 8 54 59 PM](https://user-images.githubusercontent.com/2049166/191641186-4130d6a8-2cf9-4f82-bb8e-bb09f4311fe8.png)

Theme difference is pretty noticeable from whats actually showing in my terminal.  
Also when I try to use fig and "tab" INSTEAD of down arrow, it does not work.  I want to navigate down with "tab" not the down arrow as that slows down my productivity 

Any help is greatly appreciated 

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.61 (B528) [U.S.]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro17,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 16 GB
os-info:
  - macOS 12.2.1 (21D62)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/jmac
  - exe-path: /Users/jmac/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /Users/jmac/.pyenv/shims:/Users/jmac/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin:/Users/jmac/.fig/bin:/Users/jmac/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: w0t0p0:21ECCA81-55DD-4A21-8FAF-7F4F91A94856
    - FIG_PID: 94402
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
Hey @jmac05r1! We had an issue with our settings sync. This should be resolved now. Thanks for reporting.

**Comment by jmac05r1** [comment]
Thank you
