### ISSUE TITLE
Can't remove the fig icon from menu bar.

### ISSUE THREAD

**Issue by AnjanJ** [withfig/fig#1814]
### Description:
Can't remove the fig icon from the menu bar after setting the same in settings
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Please see below screenshot I have turned on hide fig icon, but still its present in menu bar.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/1040247/191761085-7d2b322f-d52d-4174-9c65-3976fea17acf.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.6.0|Version 1.0.61 (B528)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.61 (B528) [ABC – India] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/anjan/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/anjan/.nvm/versions/node/v18.9.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/anjan/.fig/bin:/Users/anjan/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Run `fig settings sync` and then `fig settings all`.

**Comment by mschrage** [comment]
We had some issues with our settings infra. Should be resolved now. Let me know if you are still running into issues here and I'll reopen.

**Comment by AnjanJ** [comment]
@mschrage This worked. Thanks a ton
