### ISSUE TITLE
Daemon: Daemon settings watcher error

### ISSUE THREAD

**Issue by milanzmitrovic** [withfig/fig#1846]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

Fig just stopped working.

I restarted Fig, restarted Mac, but it still does not work.

fig doctor gives me:

✘ Daemon: Daemon settings watcher error
  No such file or directory (os error 2)
Attempting to fix automatically...
Re-running check...

✘ Daemon: Daemon settings watcher error
  No such file or directory (os error 2)

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.61 (B532) [Beta] [ABC]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro15,4
  - chip-id: 
  - cores: 4
  - mem: 8 GB
os-info:
  - macOS 12.5.0 (21G72)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/milanmitrovic
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/milanmitrovic/.fig/bin:/Users/milanmitrovic/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 89E97732-DB8E-4DDD-B44A-F240D96CFECC
    - FIG_PID: 717
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
Hey @milanzmitrovic! We pushed a bad beta build. This is fixed on the latest release. You should be able to update by clicking the Fig menubar icon and then "Check for updates".

Once you update, you'll need to restart all running terminal sessions and then autocomplete will start to work again.

**Comment by beauwilliams** [comment]
I don't have a fig menubar icon. Is there a way to enable it?

**Comment by mschrage** [comment]
@beauwilliams is everything working for you now?

**Comment by beauwilliams** [comment]
> @beauwilliams is everything working for you now?

All good 👍
