### ISSUE TITLE
It always doesn't work

### ISSUE THREAD

**Issue by zongzheng123** [withfig/fig#1854]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.5.1|Version 1.0.61 (B528)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.61 (B528) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/zongzheng/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/zongzheng/.nvm/versions/node/v16.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/zongzheng/.fig/bin:/Users/zongzheng/.local/bin:/Users/zongzheng/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/zongzheng/.antigen/bundles/jamesob/desk/shell_plugins/zsh:/Users/zongzheng/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/zongzheng/.antigen/bundles/zsh-users/zsh-history-substring-search:/Users/zongzheng/.antigen/bundles/zsh-users/zsh-completions:/Users/zongzheng/.antigen/bundles/zsh-users/zsh-autosuggestions:/Users/zongzheng/.antigen/bundles/b4b4r07/enhancd:/Users/zongzheng/.antigen/bundles/b4b4r07/enhancd/functions:/Users/zongzheng/.antigen/bundles/wfxr/forgit:/Users/zongzheng/.antigen/bundles/romkatv/powerlevel10k:/opt/homebrew/opt/fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @zongzheng123 are you able to give us any more details about what isnt working?

**Comment by SeparateRecords** [comment]
@zongzheng123 just following up, can you clarify what was happening? Would love to get it fixed. Looks like maybe the Mac app wasn't running, can you try `open -a Fig` and see if it works?
