### ISSUE TITLE
Inserting text into the terminal will fail

### ISSUE THREAD

**Issue by helbing** [withfig/fig#1859]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

<img width="717" alt="image" src="https://user-images.githubusercontent.com/7275620/193370202-efa0a324-ee12-4eec-8c0b-3e218ec0936c.png">

Sometimes it is working, sometimes it is not.

<img width="975" alt="image" src="https://user-images.githubusercontent.com/7275620/193371598-032d0801-4dc2-4a5f-9ca3-af4e0435612b.png">

<img width="973" alt="image" src="https://user-images.githubusercontent.com/7275620/193371678-08b49d6d-d9aa-4929-8b90-f4023c4d0b87.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.6.0|Version 1.0.61 (B528)|/usr/local/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.61 (B528) [ABC] 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/helbing/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /usr/local/Caskroom/miniconda/base/bin:/usr/local/Caskroom/miniconda/base/condabin:/Users/helbing/.local/share/node/bin:/Users/helbing/go/bin:/usr/local/bin:/usr/local/sbin:.:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:/Users/helbing/.fig/bin:/Users/helbing/.local/bin:/Users/helbing/.local/bin:/Users/helbing/.krew/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: fish (804) - /dev/ttys007
Current terminal session: w0t0p0:34648E1E-4FD6-4252-A181-B840462C0499
Current working directory: /Users/helbing
Current window identifier: 225/% (com.googlecode.iterm2)</pre>
</p>
</details>

<details><summary><code>fig doctor</code></summary>
<p>
<pre>
✔ Everything looks good!

  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!
</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @helbing, thanks for reporting this. Can you try updating to the beta and see if this issue persists?

Run `fig settings app.beta true` to update.

**Comment by helbing** [comment]
Hey @mschrage, It's fixed. Thx.

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/7275620/193393283-f8924f17-e777-44d0-91f3-23923d4cb01d.png">
