### ISSUE TITLE
Installation script: Install script not run

### ISSUE THREAD

**Issue by fromadhana** [withfig/fig#1864]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

when I run fig doctor it shows Installation script: Install script not run. please help. I just want to check using fig doctor to ensure everything is okay. I'd appreciate any help. thanks!

Here's my screen recording when I run fig doctor.
https://user-images.githubusercontent.com/102403632/193537110-1db8c601-23fb-4cac-a08d-e5c3a0e71881.mov

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.61 (B528) [ABC]
hardware-info:
  - model: MacBook Air
  - model-id: MacBookAir10,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 8 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/fromadhana
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/fromadhana/.fig/bin:/Users/fromadhana/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: w0t1p0:D9447620-5A3C-4CAC-B4D7-FF20DC5AA7DC
    - FIG_PID: 5348
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by grant0417** [comment]
We have rewritten the full app since this was posted, I would encourage you to try Fig again if it didn't work for you a year ago.
