### ISSUE TITLE
Cannot enable Accessibility

### ISSUE THREAD

**Issue by OlivierPerdrix** [withfig/fig#1871]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

In the settings window, I can't find FIG in Accessibility settings. So I can't enabled it.
<img width="831" alt="image" src="https://user-images.githubusercontent.com/911332/193692954-5cc3e69d-9340-4ec9-9cc5-5b6705c52fdb.png">
<img width="571" alt="image" src="https://user-images.githubusercontent.com/911332/193693181-390196f2-0b5e-428d-be40-ebbb9f9d9bc1.png">

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.61 (B528) [French – Numerical]
hardware-info:
  - model: MacBook Air
  - model-id: MacBookAir10,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 8 GB
os-info:
  - macOS 13.0.0 (22A5358e)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/olivier
  - exe-path: /Users/olivier/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/olivier/.cargo/bin:/Users/olivier/.fig/bin:/Users/olivier/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: BA20CEA1-878B-46DA-B199-30FE8B101215
    - FIG_PID: 8445
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
Try running `fig debug accessibility prompt`?
