### ISSUE TITLE
need to press three spaces to be prompte

### ISSUE THREAD

**Issue by shuifa** [withfig/fig#1880]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

https://user-images.githubusercontent.com/53784478/194249227-c9c6d083-ca74-4f43-8273-9aa5d7596e0c.mp4

just like the video show

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B539) [ABC]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro18,3
  - chip-id: Apple M1 Pro
  - cores: 8 (6 performance and 2 efficiency)
  - mem: 16 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/shuifa/workspace
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /opt/homebrew/opt/openssl@3/bin:/opt/homebrew/opt/libpcap/bin:/opt/homebrew/opt/openssl@3/bin:/Users/shuifa/.nvm/versions/node/v17.3.0/bin:/opt/homebrew/opt/openssl@3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/shuifa/.fig/bin:/Users/shuifa/.local/bin:/Users/shuifa/Library/Application Support/JetBrains/Toolbox/scripts:/Users/shuifa/go/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: cf27d99c-eeeb-4914-b3ba-6e97bec05393
    - FIG_PID: 30919
    - FIG_PARENT: cf27d99c-eeeb-4914-b3ba-6e97bec05393
    - FIG_SET_PARENT: cf27d99c-eeeb-4914-b3ba-6e97bec05393
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true
```
```

**Comment by mschrage** [comment]
Can you open two terminal windows:
1. In the first, run `FIG_LOG_LEVEL=debug` in 
2. In the second, separate terminal window run `fig debug logs`
3. Take a screen recording reproducing this behavior in the first terminal session

**Comment by shuifa** [comment]
> Can you open two terminal windows:
> 
> 1. In the first, run `FIG_LOG_LEVEL=debug` in
> 2. In the second, separate terminal window run `fig debug logs`
> 3. Take a screen recording reproducing this behavior in the first terminal session
> 
> Also could you share your `.zshrc` file?

This is the output of the `fig debug logs` command executed in the steps above

[fig-debug.log](https://github.com/withfig/fig/files/9739582/fig-debug.log)

and this is my `.zshrc` file

[zshrc.txt](https://github.com/withfig/fig/files/9739585/zshrc.txt)

**Comment by mschrage** [comment]
Looks like this may be a conflict with Powerlevel10k. To confirm, can you switch to a different ZSH theme (and remove p10k from your zshrc) and then see if the issue persists? @shuifa @mekhovov
