### ISSUE TITLE
I can't sign in to Fig on fresh install (thus accessing Dashboard or settings)?

### ISSUE THREAD

**Issue by alanristic** [withfig/fig#1881]
### Description:
It's a fresh install.

I tried via .dmg download & via Homebrew. No bueno 🤷‍♂️

Should I create account somewhere or something?

I attached error when trying to login via terminal.

NOTE: I did had Fig installed some time ago and removed it...like a 1-2 months back. Are there any configs left behind or something? 

Please advise 🙏

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.6.0|Version 1.0.62 (B539)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.62 (B539) [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ar/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: false
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>
<img width="1073" alt="Screen Shot 2022-10-06 at 11 21 31" src="https://user-images.githubusercontent.com/476253/194276242-6ecf5bd6-669c-4ee6-b436-37b11863ffdd.png">
<img width="1029" alt="Screen Shot 2022-10-06 at 11 26 15" src="https://user-images.githubusercontent.com/476253/194277459-e58dc73b-59ba-4913-9907-7d69b9f0e11a.png">

**Comment by mschrage** [comment]
@alanristic what happens when you submit your email to the sign in form? Do you receive a login code in your inbox?

**Comment by alanristic** [comment]
Nope. 

I only got one the first time I installed Fig on September 15th.

After that I removed it and was without for a 
"month".

**Comment by mschrage** [comment]
So to confirm, you've tried typing your email into the Email Address field and you _do not_ receive an email?

Can you open the web inspector by right-clicking the window and share a screenshot of the "Console"? I'm curious if there are any errors since it looks like you might have invalid certs in your keychain.
