### ISSUE TITLE
Tiny fig icon stuck in dock.

### ISSUE THREAD

**Issue by vektroi-d** [withfig/fig#1886]
### Description:
Tiny fig icon stuck in dock.

`https://imgur.com/a/hDQfZEo`

### Details:
|macOS|Fig|Shell|
|-|-|-|
|13.0.0|Version 1.0.61 (B528)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.61 (B528) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/michaelkusmierowicz/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: true
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @vektroi-d! I have no idea what would trigger this behavior. Do you use any apps that customize your Dock?

If you quit Fig and restart is this reproducible?

**Comment by luosheng** [comment]
Same here. 

I have been using Fig for quite a long time and this occurs recently. Restarting the app didn't help. I don't know if it's OS-related but I'm using Ventura 13.0.

<img width="111" alt="截屏2022-11-03 10 33 57" src="https://user-images.githubusercontent.com/47009/199638078-8fe6b762-3bc0-4314-b90e-e671b8da27df.png">

<details><summary>fig diagnostic</summary>

```bash
fig-details:
  - 2.7.2-beta.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/luosheng
  - exe-path: /Users/luosheng/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 10aaab07-a1c5-435c-8936-ff8a199172f4
    - FIG_HOSTNAME: LuodeMacBook-Pro-M1-Max.local
    - FIG_TERM: 2.7.2-beta.1
    - PATH: /Users/luosheng/.rbenv/shims:/Users/luosheng/.nvm/versions/node/v16.13.2/bin:/opt/local/bin:/opt/local/sbin:/Users/luosheng/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/luosheng/.cargo/bin:/Users/luosheng/.fig/bin:/Users/luosheng/.local/bin:/Users/luosheng/.local/bin:/Users/luosheng/Library/Application Support/JetBrains/Toolbox/scripts:/Users/luosheng/Library/Android/sdk/platform-tools/:/Users/luosheng/Library/Android/sdk/platform-tools/::/Users/luosheng/.bun/bin:/Users/luosheng/Library/pnpm:/Users/luosheng/.local/share/fig/plugins/forgit/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 54113
    - FIG_PARENT: 10aaab07-a1c5-435c-8936-ff8a199172f4
    - FIG_SET_PARENT: 10aaab07-a1c5-435c-8936-ff8a199172f4
```

</details>

**Comment by mschrage** [comment]
Try running `killall Dock` and see if that fixed the issue?

**Comment by vektroi-d** [comment]
Issue seems to have resolved itself for me on the latest MacOS Beta 13.1 Beta (22C5033e)

**Comment by luosheng** [comment]
> Try running `killall Dock` and see if that fixed the issue?

That did help!

**Comment by VityaSchel** [comment]
Hahahaha this is so funny
<img width="291" alt="image" src="https://github.com/withfig/fig/assets/59040542/64be40a8-d8a1-47fd-bae6-1171d493488f">

little tiny cute fig icon :)
