### ISSUE TITLE
Fig - BSPWM.

### ISSUE THREAD

**Issue by igorcguedes** [withfig/fig#1888]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Feature Details

Please, support it for BSPWM!

**Comment by grant0417** [comment]
How does adding the config of `bspc rule -a Fig state=floating` work? This should make the window float, if you look at the [additional config](https://fig.io/user-manual/linux#additional-configs) section of our Linux docs you can see other examples.

**Comment by mschrage** [comment]
Closing as duplicate of #1791. See the suggestions there for advice on how you might be able to get autocomplete working with BSPWM.
