### ISSUE TITLE
Running `fig update` shows message about reinstalling headless

### ISSUE THREAD

**Issue by febycloud** [withfig/fig#1896]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:
run command fig update
it shows error: Please remove `~/.local/bin/fig` and reinstall Fig with `curl -fSsL https://fig.io/install-headless.sh | bash`

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B541) [ABC]
hardware-info:
  - model: iMac
  - model-id: iMac21,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 16 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/feiyun
  - exe-path: /Users/feiyun/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/feiyun/.fig/bin:/Users/feiyun/.local/bin:/Users/feiyun/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: eeec5886-85a2-4967-bb2d-120aa9637d30
    - FIG_PID: 5312
    - FIG_PARENT: eeec5886-85a2-4967-bb2d-120aa9637d30
    - FIG_SET_PARENT: eeec5886-85a2-4967-bb2d-120aa9637d30
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mbd-s** [comment]
I was having a similar issue with both an M1 and Intel-based Mac, and running `fig doctor` and `fig restart` didn't help. (One note: I have `Disable AutoUpdate` turned off, not sure if you do too.)

 Here's what fixed it for me in the end:
- Open the fig app (you can launch it by running `fig settings`)
- Under `General`, turn off `Disable AutoUpdate`
- Launch a new terminal session. Fig should start auto-updating.
- Turn `Disable AutoUpdate` back on (if you wish)
- Launch a new terminal session and run `fig update`. Fig shouldn't complain.

**Comment by weilderbeast** [comment]
https://github.com/withfig/fig/issues/1896#issuecomment-1274561201 worked for me to fix the update issue.

**Comment by chaynabors** [comment]
Some users got locked into a bad update some time ago. This issue has been resolved for the foreseeable future, and uninstalling and reinstalling will certainly do the trick. Let me know if you encounter any other issues in the future.
