### ISSUE TITLE
UI is sluggish when using eGPU

### ISSUE THREAD

**Issue by ebarti** [withfig/fig#1897]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

The fig UI is unusable: it is sluggish to hte point of making it unusable. I have been experiencing this  issue for a few weeks now.

Here's a recording:

https://user-images.githubusercontent.com/38191745/194934972-fa6426fc-e96e-4c89-8eac-ffdc56dc3ab8.mov

I am clicking and scrolling throughout the video. 

Restarting does not help. I tried all the basic troubleshooting (turn off/on, etc.) 

The only thing that is particular on my environment is that I am using an e-GPU that drives an external display. Fig is **not** configured to prefer the external GPU.

### Environment

```yaml
The only thing that is particular on my environment is that I am using an e-GPU that drives an external display. Fig is **not** configured to prefer the external GPU.

Fig diagnostic output:

fig-details:
  - desktop-version: Version 1.0.62 (B541) [ABC]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro16,1
  - chip-id: 
  - cores: 6
  - mem: 32 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/eloibarti
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /usr/local/opt/openssl@1.1/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/eloibarti/.pyenv/shims:/Users/eloibarti/.pyenv/bin:/usr/local/sbin:/Users/eloibarti/.rbenv/shims:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users/eloibarti/.nvm/versions/node/v16.14.2/bin:/Users/eloibarti/go/bin:/Users/eloibarti/go/go1.18/bin:/Users/eloibarti/ngrok_dir:/Users/eloibarti/.sdkman/candidates/java/current/bin:/Users/eloibarti/.sdkman/candidates/gradle/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/eloibarti/.cargo/bin:/Users/eloibarti/.fig/bin:/Users/eloibarti/.local/bin:/Users/eloibarti/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 27fd08bf-29f7-48bd-ae63-0878adaea486
    - FIG_PID: 3431
    - FIG_PARENT: 27fd08bf-29f7-48bd-ae63-0878adaea486
    - FIG_SET_PARENT: 27fd08bf-29f7-48bd-ae63-0878adaea486
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false
```

**Comment by mschrage** [comment]
Hey @ebarti! Wow that performance looks very unusual. Can you go to [app.fig.io](https://ap.fig.io) in Safari and see if the UI is sluggish there as well?

**Comment by ebarti** [comment]
Hey @mschrage somehow the performance has been fixed automatically 😄 I will close this issue as it no longer applies.
