### ISSUE TITLE
Unable to remove cli alias after update

### ISSUE THREAD

**Issue by theelderbeever** [withfig/fig#1899]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

I installed `fig` a few weeks ago and it has been great. When I installed it (I don't know the version at the time) I had a few aliases in my `.zshrc` that I had to duplicate in `fig` for them to autocomplete properly. ie `alias "dbx=docker buildx"` and `alias "k=kubectl"`. There was a menu under autocomplete in `fig settings` where I was able to fill these in. However, I now need to remove one of the names do to a conflict with another cli. I removed the alias from my `.zshrc` however, it is still present in my terminal due to `fig` and the menu to change these aliases has seemingly been removed during one of the recent updates.

My apologies if this isn't a bug and I just can't find then menu but, I am pretty confident I have clicked through each setting to no avail....

FWIW I can remove the alias in the active terminal session with `unalias <alias-name>`.

### Environment

```yaml
❯ fig diagnostic

fig-details:
  - desktop-version: Version 1.0.62 (B542) [U.S.]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro18,2
  - chip-id: Apple M1 Max
  - cores: 10 (8 performance and 2 efficiency)
  - mem: 64 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/taylorbeever/.fig
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /Users/taylorbeever/.nvm/versions/node/v16.15.1/bin:/opt/homebrew/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/taylorbeever/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/taylorbeever/.git-tools:/Users/taylorbeever/.pyenv/bin:/Users/taylorbeever/.poetry/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/taylorbeever/.kube/tools__kubectl--plugins/plugins:/Users/taylorbeever/.krew/bin:/Users/taylorbeever/bin:/Users/taylorbeever/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/bin:/bin:/usr/sbin:/sbin:/Users/taylorbeever/.cache/zsh4humans/v5/fzf/bin:/Users/taylorbeever/.fig/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: fc42c243-704d-4fa5-8d04-52d3f2edb9ab
    - FIG_PID: 19485
    - FIG_PARENT: fc42c243-704d-4fa5-8d04-52d3f2edb9ab
    - FIG_SET_PARENT: fc42c243-704d-4fa5-8d04-52d3f2edb9ab
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true
```
```

**Comment by mschrage** [comment]
<img width="1026" alt="Screen Shot 2022-10-11 at 12 30 46 PM" src="https://user-images.githubusercontent.com/3155109/195181830-1ad650ce-165c-47c3-933c-41d97997708b.png">

Run `fig` and then go to the Dotfiles tab. You should be able to delete this alias there. :)

**Comment by theelderbeever** [comment]
Ugh thanks @mschrage... One of those days I guess... Closing....
