### ISSUE TITLE
[BUG] Autocomplete suggestion box appears underneath floating iTerm window

### ISSUE THREAD

**Issue by jayrhynas** [withfig/fig#19]
**Summary:**
Autocomplete suggestion box appears underneath floating iTerm window

**Steps to Reproduce:**
1. Create an iTerm hotkey window profile
2. In iTerm preferences, under Profile > Keys > Configure Hotkey Window, enable the **Floating window** setting
3. Trigger the hotkey window, then start typing a command that triggers the Fig autocomplete suggestion box.

**Expected Results:**
Autocomplete suggestion box appears on top of iTerm window.

**Actual Results:**
Autocomplete suggestion box appears under iTerm window (although it remains interactive).
Autocomplete suggestion box also does not dismiss when dismissing hotkey window.

**System information:**
OS: MacOS Big Sur 11.1
Terminal: iTerm2 (3.4.3)
Version of Fig: 1.0.32 (B80)

**Additional Notes:**
<img width="420" alt="Screen Shot 2021-01-25 at 10 07 55 AM" src="https://user-images.githubusercontent.com/1088234/105739608-4828ad80-5f06-11eb-8800-39caa8951d66.png">

**Comment by falky97** [comment]
Hey Jayson - thanks so much for this detailed issue report.

We are aware of this issue. However, if you *enable* a hotkey window but *disable* the floating window setting, Fig works just fine.

We couldn't find any difference in our workflow between having floating window enabled versus disabled. Have you found any difference? If so, please share below.

If not, for the moment, please just disable the floating window setting and we will update you when we have properly fixed this

Brendan Falk
Co-founder & CEO @ Fig
brendan@withfig.com
(857) 800-1383

**Comment by jayrhynas** [comment]
The main difference is with Floating window turned on, you can open the hotkey window over full screen applications. If it's turned off, triggering the hotkey while in a full screen app will change your space to a non-full screen one before showing the hotkey window.

For now I have disabled the setting though to try out Fig.

**Comment by falky97** [comment]
Ah. I see. Yes this is annoying. We will fix.

I realised why I didn't see this: if you just toggle floating window off, it still opens above full screen apps. But after restarting iTerm, it does not.

Brendan Falk
Co-founder & CEO @ Fig
brendan@withfig.com
(857) 800-1383

**Comment by jayrhynas** [comment]
Ah yes it doesn't take effect until restarting, I ran into the opposite issue when I enabled it in the first place.

**Comment by mattschrage** [comment]
This will be fixed in the next build!

**Comment by mattschrage** [comment]
Fixed in v1.0.33
