### ISSUE TITLE
COULD NOT LOAD URL....

### ISSUE THREAD

**Issue by mkd1521** [withfig/fig#1903]
Hey guys i am a new fig user, after a recent update my fig app showing blank interface with "Could not load URL..." message. Reinstall did not work. Any solution?
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/93447783/195407421-10d4dfbc-8b18-4b5e-a0f1-8cfbd19d0783.png">

**Comment by mschrage** [comment]
Hey @mkd1521! Can you share what version you are on by running `fig diagnostic`?

Also try quitting and restarting the app.

**Comment by mkd1521** [comment]
i tried quitting and restarting but nothing worked. so i for frustrated and uninstalled. Today after seeing ur message i installed again and everything back to normal. I have no idea whats happening
