### ISSUE TITLE
can't load the dashboard

### ISSUE THREAD

**Issue by lnjpbhr** [withfig/fig#1904]
![Xnip2022-10-13_10-40-05](https://user-images.githubusercontent.com/53263452/195486328-2f8e92ed-2c7d-4a7b-97a0-1ff1e3240b77.jpg)
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.6.0|Version 1.0.60 (B502)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.60 (B502) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/bihaoran/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /usr/local/sbin:/Users/bihaoran/.nvm/versions/node/v16.13.0/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/bihaoran/.fig/bin:/Users/bihaoran/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Try quitting Fig and restarting! Also to confirm, do you have internet access?

**Comment by lnjpbhr** [comment]
> Try quitting Fig and restarting! Also to confirm, do you have internet access?

thanks. Im sure i have the internet access.This issue persists even after I uninstalled fig several times.
Every time when i click the settings or dashboard.The window is always in the state of my uploaded pictures.
Autocomplete still works, but I can't open the settings screen to update my settings or download plugins

I don't know what other details I need to provide. But I personally think it might be related to my Mac being an Intel chip?

**Comment by mschrage** [comment]
Can you run `fig doctor` and `fig diagnostic`?

**Comment by lnjpbhr** [comment]
> Can you run `fig doctor` and `fig diagnostic`?

The result is as follows:
```
 bihaoran@MacBook-Pro  ~  fig doctor


✔ Everything looks good!

  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!

bihaoran@MacBook-Pro  ~  fig diagnostic

fig-details:
  - desktop-version: Version 1.0.62 (B542) [ABC]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro16,1
  - chip-id:
  - cores: 8
  - mem: 32 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/bihaoran
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /usr/local/sbin:/Users/bihaoran/.nvm/versions/node/v16.13.0/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/bihaoran/.fig/bin:/Users/bihaoran/.local/bin:/Library/TeX/texbin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: b65eb640-ad9e-4681-a856-e41932d46012
    - FIG_PID: 65138
    - FIG_PARENT: b65eb640-ad9e-4681-a856-e41932d46012
    - FIG_SET_PARENT: b65eb640-ad9e-4681-a856-e41932d46012
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

It seems that all CLI commands work, but I cannot open the GUI interface.

**Comment by mschrage** [comment]
Can you right+click the window and share a screenshot of the console?

**Comment by lnjpbhr** [comment]
> Can you right+click the window and share a screenshot of the console?

![fig issue1](https://user-images.githubusercontent.com/53263452/195765891-3d922880-f491-4206-b2c5-793b00c46262.jpg)
![fig issue2](https://user-images.githubusercontent.com/53263452/195765896-4685bbb4-cd6b-45cb-aee0-3e618a573a3f.jpg)
