### ISSUE TITLE
ssh ubuntu 

### ISSUE THREAD

**Issue by milanzmitrovic** [withfig/fig#1910]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Mac

### Expected behaviour

1. Fig autocomplete does not work properly. It can't recognise existence of folders that I created. It only recognises folders that are build into remote linux server.

2. Autocomplete options can't be chosen using shift/enter button.

*** Everything works fine on my local machine.

### Actual behaviour

Described in previous box.

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B541) [Beta] [ABC]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro15,4
  - chip-id: 
  - cores: 4
  - mem: 8 GB
os-info:
  - macOS 12.5.0 (21G72)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/milanmitrovic
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/milanmitrovic/.fig/bin:/Users/milanmitrovic/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 77a483bd-b376-4b5b-ba52-4206b18b66d7
    - FIG_PID: 20543
    - FIG_PARENT: 77a483bd-b376-4b5b-ba52-4206b18b66d7
    - FIG_SET_PARENT: 77a483bd-b376-4b5b-ba52-4206b18b66d7
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

Here is screen recording:
https://user-images.githubusercontent.com/58112365/196060336-a2263013-dd27-49eb-ab44-52516ebdf07c.mov

**Comment by milanzmitrovic** [comment]
Here is screen recording:
https://user-images.githubusercontent.com/58112365/196060352-1bbf283a-dc0f-4ceb-a5dc-d5f55312ecee.mov

**Comment by mschrage** [comment]
Can you run `fig doctor` in the remote terminal session?

**Comment by milanzmitrovic** [comment]
No, I can't do it.

'Fig doctor' command returns this error:
root@ubuntu-s-1vcpu-512mb-10gb-fra1-01:~# fig doctor
Running doctor as root is not supported.
If you know what you're doing, run the command again with --verbose.
root@ubuntu-s-1vcpu-512mb-10gb-fra1-01:~# 


But, I run 'fig doctor --verbose'. It returns:
root@ubuntu-s-1vcpu-512mb-10gb-fra1-01:~# fig doctor --verbose
Running doctor as root is not supported.
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ ~/.bashrc contains valid fig hooks
✔ ~/.profile contains valid fig hooks

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ Fig Integration

Let's see if Fig is in a working state...
✔ Figterm
✔ Insertion lock does not exist
✔ PATH and PseudoTerminal PATH match
✔ Autocomplete dev mode
✔ Plugin dev mode
✔ Mission Control is loading from the correct URL

Let's check if your system is compatible...
● Fig's support for Linux 5.15.0-41-generic - "Ubuntu" is in development. It may not work properly on your system.



  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!

root@ubuntu-s-1vcpu-512mb-10gb-fra1-01:~#

**Comment by milanzmitrovic** [comment]
Today, I got automatic install of fig_cli 2.5.8-beta.14 .

Now it works fine.

This issue can be closed.
