### ISSUE TITLE
Support default values and descriptions for suggestions in Workflows

### ISSUE THREAD

**Issue by zxpzdtom** [withfig/fig#1911]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/22407004/196103741-139cade9-cc34-4a04-92eb-684d42b2a72a.png">

I need to set a default value and can set a specific description.

**Comment by zxpzdtom** [comment]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/22407004/196104823-cc7781c8-1365-4620-9371-066266b4e4cb.png">

**Comment by mschrage** [comment]
Thanks for this feedback @zxpzdtom! I've added it to our workflows roadmap :)

**Comment by zxpzdtom** [comment]
Hello, when will this be supported? 👀

**Comment by zxpzdtom** [comment]
I have noticed that you already support default values, but you have not yet implemented support for option descriptions. Currently, I concatenate the options and descriptions using spaces and then use a script to separate them.

![image](https://github.com/withfig/fig/assets/22407004/3ceeccb7-f96e-4bfa-b357-be66feb9a0d5)

![image](https://github.com/withfig/fig/assets/22407004/dcb3da88-7b7f-48b0-9832-1f45867977a6)
