### ISSUE TITLE
Accessibility enabled: Accessibility is disabled

### ISSUE THREAD

**Issue by subskill-tsoulier** [withfig/fig#1923]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Mac Mini (MacOs Mojave) - 2014 i5 8go

### Expected behaviour

Fig application don't want open and I login in iTerms2 but after my login, he said me 'Accessibility enabled: Accessibility is disabled'.
Btw, sorry for my bad english, I'm french.

### Actual behaviour

~ fig doctor

● /Users/canette/.bash_profile does not source post integration last
✘ Accessibility enabled: Accessibility is disabled
Attempting to fix automatically...

Re-running check...

✘ Accessibility enabled: Accessibility is disabled

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B542) [French - Numerical]
hardware-info:
  - model: Mac mini
  - model-id: Macmini7,1
  - chip-id: 
  - cores: 2
  - mem: 8 GB
os-info:
  - macOS 10.14.6 (18G103)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /
  - exe-path: /Users/canette/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /Applications/MAMP/bin/php/php7.4.21/bin:/Applications/MAMP/bin/php/php7.4.21/bin:/Applications/MAMP/bin/php/php7.4.21/bin:/Applications/MAMP/bin/php/php7.4.21/bin:/Applications/MAMP/bin/php/php7.4.21/bin:/Applications/MAMP/bin/php/php7.4.21/bin:/Applications/MAMP/bin/php/php7.4.21/bin:/Applications/MAMP/bin/php/php7.4.21/bin:/Applications/MAMP/bin/php/php7.4.21/bin:/usr/local/opt/php@7.4/sbin:/usr/local/opt/php@7.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/canette/.fig/bin:/Users/canette/.local/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 73603fa6-cb5b-46a5-839c-dac143997cf4
    - FIG_PID: 50593
    - FIG_PARENT: 73603fa6-cb5b-46a5-839c-dac143997cf4
    - FIG_SET_PARENT: 73603fa6-cb5b-46a5-839c-dac143997cf4
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false
```

**Comment by SeparateRecords** [comment]
Hey @subskill-tsoulier! Sorry for the bug. Could you try out our Rust build and see if the same thing happens? https://withfig.notion.site/Getting-Setup-with-our-new-Rust-based-Fig-app-e41115459178463c898f1281303d9f08

**Comment by subskill-tsoulier** [comment]
Hey @SeparateRecords , I have reinstall my computer, the problem is about my oS, I have updated Mojave to Monterey, and the compatibility is broken, sorry and thank you for your help ^^
