### ISSUE TITLE
bug: Workflow does not support Chinese

### ISSUE THREAD

**Issue by zxpzdtom** [withfig/fig#1924]
### Checks

- [x] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macos Monterey 12.2

### Expected behaviour

I hope I can input in Chinese. Thanks

### Actual behaviour

https://user-images.githubusercontent.com/22407004/196920745-4fbbef9e-c365-40ba-9554-8b29a7390a36.mov

When I input Chinese, the program will throw an error and cannot finish the command

### Steps to reproduce

You can see the video above.

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B542) [搜狗拼音]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro16,2
  - chip-id: 
  - cores: 4
  - mem: 16 GB
os-info:
  - macOS 12.2.0 (21D49)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/alsc/Desktop/gitlab/xy-m-todo
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_PARENT: cf104e7d-9704-4bc1-84e9-7b87e1f7fde6
    - FIG_PID: 41516
    - FIG_SET_PARENT: 74c1898b-03c6-4b25-b560-204cd1395ec8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /Users/alsc/.bun/bin:/Users/alsc/.nvm/versions/node/v14.6.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/alsc/.bun/bin:/Users/alsc/.nvm/versions/node/v14.6.0/bin:/Users/alsc/.fig/bin:/Users/alsc/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 74c1898b-03c6-4b25-b560-204cd1395ec8
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
Hey @zxpzdtom we have a fix for this coming soon! cc @chaynabors 

Thanks for your patience!

**Comment by zxpzdtom** [comment]
Hello, when will this be repaired? 👀

**Comment by chaynabors** [comment]
@zxpzdtom It's not perfect, but you should be able to do (at least) some amount of what you're trying to do in newer versions of Fig. Feel free to bring up any other issues you encounter separately.
