### ISSUE TITLE
Command not found and parse error

### ISSUE THREAD

**Issue by PeterOlsenTrifork** [withfig/fig#1925]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOs

### Expected behaviour

Starting term without any console logs

### Actual behaviour

When I start iterm, I get the following messages in my console.

/Users/XXX/.local/share/fig/plugins/oh-my-zsh-flow-plugin_sandstorm/flow.plugin.zsh:5: command not found: ^M
/Users/XXX/.local/share/fig/plugins/oh-my-zsh-flow-plugin_sandstorm/flow.plugin.zsh:306: parse error near `\n'

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B542) [U.S.]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro13,3
  - chip-id: 
  - cores: 4
  - mem: 16 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/xxx
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.fQx2imzjCY/org.macosforge.xquartz:0
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /Users/xxx/.rvm/gems/ruby-2.2.2/bin:/Users/xxx/.rvm/gems/ruby-2.2.2@global/bin:/Users/xxxx/.rvm/rubies/ruby-2.2.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/xxx/.fig/bin:/Users/xxx/.local/bin:/Users/xxx/.local/bin:/Users/xxx/.rvm/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: e41e56ba-fce8-426d-b597-8e0fe6768a01
    - FIG_PID: 7665
    - FIG_PARENT: e41e56ba-fce8-426d-b597-8e0fe6768a01
    - FIG_SET_PARENT: e41e56ba-fce8-426d-b597-8e0fe6768a01
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: installed!
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
This looks like an issue with the flow plugin! I’d recommend uninstalling it for the time being — you can also contribute a fix upstream at https://github.com/withfig/plugins
