### ISSUE TITLE
Even though I have set fig to start on boot, i have to manually restart it to get it working.

### ISSUE THREAD

**Issue by HarshitRV** [withfig/fig#1930]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.6.0|Version 1.0.62 (B542)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.62 (B542) [ABC – India] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/harshitkrvishwakarma/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (907) - not a tty
Current terminal session: d1d3fefd-9754-44b4-8de6-8aa0bf9e9b53
Current working directory: /Users/harshitkrvishwakarma
Current window identifier: 216/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Can you run `ls ~/Library/Launch\ Agents` and share the output here?

**Comment by HarshitRV** [comment]
```bash
com.google.keystone.agent.plist       io.fig.launcher.plist
com.google.keystone.xpcservice.plist  io.fig.uninstall.plist
homebrew.mxcl.mongodb-community.plist org.sdg.xdman.plist
io.fig.dotfiles-daemon.plist
```

**Comment by HarshitRV** [comment]
I am expecting these suggestions but i am not getting it until I manually restart fig

<img width="567" alt="Screenshot 2022-10-31 at 18 53 00" src="https://user-images.githubusercontent.com/66301404/199018032-53a5179c-7b49-436b-8fbf-c515829f69e7.png">

**Comment by mschrage** [comment]
What version of macOS are you on @HarshitRV? Have you disabled any "Background Items" in system preferences?

**Comment by HarshitRV** [comment]
I am on macOS Ventura version 13.0

Here are the background settings
<img width="485" alt="Screenshot 2022-10-31 at 22 58 13" src="https://user-images.githubusercontent.com/66301404/199071184-27ffc7c7-112d-4abb-b93e-aeababd5efcb.png">

**Comment by mschrage** [comment]
Can you run `ls ~/Library/LaunchAgents`?

**Comment by HarshitRV** [comment]
```bash
com.google.keystone.agent.plist       io.fig.launcher.plist
com.google.keystone.xpcservice.plist  io.fig.uninstall.plist
homebrew.mxcl.mongodb-community.plist org.sdg.xdman.plist
io.fig.dotfiles-daemon.plist
```

**Comment by HarshitRV** [comment]
I don't know how but fig is working perfectly now. You can close this issue. Really appreciate all the help 😊.
