### ISSUE TITLE
bug: cmd+Enter: Invalid key combination

### ISSUE THREAD

**Issue by hacker-DOM** [withfig/fig#1942]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS

### Expected behaviour

I would like to set `cmd+enter` as a keybinding for "Execute" (Execute current command).

### Actual behaviour

When I enter that keymap, I get Invalid key combination

![Kapture 2022-10-24 at 20 42 56](https://user-images.githubusercontent.com/18601956/197601769-e5336860-3a1d-4f8d-b14b-a43791dafc66.gif)

### Environment

```yaml
I am using kitty


fig-details:
  - desktop-version: Version 1.0.62 (B542) [U.S.]
hardware-info:
  - model: MacBook Air
  - model-id: MacBookAir10,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 16 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: <unknown>
  - cwd: /Users/dteiml/p
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: [redacted]
    - SHELL: /bin/zsh
    - TERM: xterm-kitty
    - TERM_SESSION_ID: 4d62aae1-bd82-47a6-b239-7834a277a8c0
    - FIG_PID: 22096
    - FIG_PARENT: 4d62aae1-bd82-47a6-b239-7834a277a8c0
    - FIG_SET_PARENT: 4d62aae1-bd82-47a6-b239-7834a277a8c0
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: installed!
  - Visual Studio Code: installed!
  - Docker: false
```
```

**Comment by mschrage** [comment]
Hey @hacker-DOM! Our keybinding logic is handled by code running inside of the terminal and doesn't not have access to raw keypress events from the OS. 

You can using "control" as a modifier, but not "command" since most terminals don't support it. Out of curiosity, what terminal do you use?

**Comment by hacker-DOM** [comment]
I am using Kitty terminal, which does provide access to events like this [see Kitty keyboard protocol]
