### ISSUE TITLE
Secure Keyboard Entry - 1Password Conflict

### ISSUE THREAD

**Issue by rcoundon** [withfig/fig#1944]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
There seems to be a conflict between 1Password and Fig. After a period (or maybe certain actions, hard to say) Fig stops working and reports that Secure Keyboard Entry is enabled when it isn't in iTerm.
If I quit 1Password, Fig starts working again. I can then start up 1Password and Fig will continue to work for a period and then stop and I have to go through the process of killing 1Password again. This is on Mac OS Monterey.
Is there any way to get these two very useful tools to play together nicely all the time or only temporarily (much like my kids)?

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.6.1|Version 1.0.62 (B542)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.62 (B542) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/rosscoundon/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/rosscoundon/.nvm/versions/node/v16.16.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/rosscoundon/.fig/bin:/Users/rosscoundon/.local/bin
SecureKeyboardInput: true
SecureKeyboardProcess: iTerm2 - com.googlecode.iterm2 
Current active process: zsh (59361) - not a tty
Current terminal session: 13a35c68-37be-4906-a32a-fa25c221dad4
Current working directory: /Users/rosscoundon
Current window identifier: 1232/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by grant0417** [comment]
The next version of Fig will no longer prevent secure keyboard entry, you can try it now by enabling the beta with `fig settings app.beta true`

**Comment by rcoundon** [comment]
Excellent, I'll give that a go. Thank you
