### ISSUE TITLE
bug: macOS Ventura 13.0 Support

### ISSUE THREAD

**Issue by secondmanveran** [withfig/fig#1945]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [ ] I have run `fig restart` and replicated the issue again

### Operating system

macOS Ventura 13.0

### Expected behaviour

Expect Fig application to complete initial set up.

### Actual behaviour

When using the Fig app in macOS Ventura 13.0 the first time, the app becomes non-responsive after adding Fig privacy in the newly designed System Settings in Ventura.

Quitting the app and restarting will take you past this section to register ... so it appears that the privacy settings are indeed saved ... but the app isn't receiving anything ... it simply continues to prompt to Check Privacy Settings or whatever the verbiage is.

### Steps to reproduce

Im not able to reproduce since the app has the privacy setting stored it doesn't return to this prompt after being restarted.

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B542) [U.S.]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro16,1
  - chip-id: 
  - cores: 8
  - mem: 16 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/vince
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: NOT DISCLOSED PUBLICLY
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 7a00394d-ca70-4197-b34f-858bca06d256
    - FIG_PID: 46400
    - FIG_PARENT: 7a00394d-ca70-4197-b34f-858bca06d256
    - FIG_SET_PARENT: 7a00394d-ca70-4197-b34f-858bca06d256
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
Can you share a screen recording @secondmanveran ?

**Comment by mschrage** [comment]
Ah so everything did work for you ultimately?

**Comment by garbi** [comment]
I have exactly the same problem here: it seems to be due to the fact that in Ventura (macOS 13) the application for controlling system preferences (now called system settings) have been deeply revamped. 

Because of this, the step consisting in installing the third-party input method "FigInputMethod" blocks the setup process.

My guess is that you did not test Fig on Ventura at all because you would definitively stumble on that problem immediately. 

So I suggest you do.

And I agree: Fig is a very nice addition to many context, so keep up with the good work.

**Comment by 0scarecrow0** [comment]
The same thing happened to me

**Comment by AngeloKreienbuehl** [comment]
Same 🥲

**Comment by mschrage** [comment]
@0scarecrow0 @AngeloKreienbuehl had you just downloaded Fig for the first time or were you upgrading from a previous version?

**Comment by 0scarecrow0** [comment]
I've upgraded from a prior installation, not a fresh one.

**Comment by mschrage** [comment]
Can you take a screenshot of the screen where you are being prompted to install the input method?

**Comment by 0scarecrow0** [comment]
![CleanShot 2022-11-08 AM 10 51 45@2x](https://user-images.githubusercontent.com/45458124/200463518-50dcfe16-de0a-4417-8558-53fe85a3267f.png)
When I enter the third space, it will appear

**Comment by 0scarecrow0** [comment]
![CleanShot 2022-11-08 AM 10 54 46@2x](https://user-images.githubusercontent.com/45458124/200463884-b8cd5046-2cf0-45ca-8786-b3ca031a4457.png)
Installation is normal

**Comment by themashcodee** [comment]
in my case it is working but not visible in the vscode, but when I have opening vscode not in fullscreen mode it is visible so basically modal is not able come on the top of vscode

Fig Version: 2.7.5
Mac Version: Ventura
VS Code version: 1.73.0 (Universal)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/50915748/200484590-e0dd7a5c-e9d1-4cf6-9cb9-26decbd71468.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/50915748/200484603-1880df10-d54c-45d0-b7eb-0ced256504f9.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/50915748/200484720-6c518953-1dcc-4044-b3cb-4dda88225669.png">

**Comment by victor-paumier** [comment]
same as @themashcodee, the modal is not visible on fullscreen mode

Fig Version: 2.7.5
Mac Version: Ventura
PhpStorm: 2022.2.2

**Comment by mschrage** [comment]
@victor-paumier @themashcodee the autocomplete window is correctly positioned in the latest beta. See this issue for details. #1964

**Comment by victor-paumier** [comment]
> @victor-paumier @themashcodee the autocomplete window is correctly positioned in the latest beta. See this issue for details. #1964

👌 I confirm that everything is working properly now, thank you!
