### ISSUE TITLE
fig hangs when running `git checkout -- .`

### ISSUE THREAD

**Issue by kevinebaugh** [withfig/fig#1946]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0 (22A380) (though it was occurring pre-Ventura)

### Expected behaviour

`git checkout -- .` should restore all files.

### Actual behaviour

fig tries to autocomplete, then hangs. Sometimes it shows output similar to https://github.com/withfig/fig/issues/1866.

![Uploading 2022-10-25 15.09.17.gif…]()

### Steps to reproduce

I can reproduce it with `git checkout -- .` each time.

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B542) [U.S.]
hardware-info:
  - model: MacBook Air
  - model-id: MacBookAir10,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 16 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/bash
  - terminal: terminal
  - cwd: /Users/ke/ifttt/web
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_PID: 17822
    - TERM: xterm-256color
    - SHELL: /bin/bash
    - TERM_SESSION_ID: cd36f2dc-500e-4f21-bd87-90bb324a2ac2
    - PATH: /opt/homebrew/opt/kubernetes-cli@1.22/bin:~/ifttt/ifttt_k8s/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ke/.cargo/bin:/Users/ke/.sdkman/candidates/sbt/current/bin:/Users/ke/.rbenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/ke/.fig/bin:/Users/ke/.local/bin:~/bin:/usr/local/dev-env/bin:~/ifttt/jenkins-shared-libraries/bin
    - FIG_WORKFLOWS_KEYBIND: ^f
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM_VERSION: 2.5.3
    - FIG_TERM: 1
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true
```

**Comment by SeparateRecords** [comment]
Hey! I think #1947 is the exact same bug. And we received an email about this earlier today too so it's not just you. What's really strange is we haven't updated the autocomplete engine with anything that could cause this, but we're only just seeing it now...

Could you try updating to the Rust beta? Follow the guide here: https://withfig.notion.site/Getting-Setup-with-our-new-Rust-based-Fig-app-e41115459178463c898f1281303d9f08

Please let me know if that fixes for you!

**Comment by kevinebaugh** [comment]
@SeparateRecords Thanks! Same issue after updating to the Rust beta, unfortunately:

<img width="1106" alt="Screenshot 2022-10-27 at 9 54 44 AM" src="https://user-images.githubusercontent.com/3092522/198304077-35326dbf-b799-4d45-a2a1-c41dafd4a28f.png">

**Comment by SeparateRecords** [comment]
cc @grant0417 - looks like the ^H^H^H^H^H^H^H bug again too

**Comment by grant0417** [comment]
Strange to see it in the new rust beta, will have to investigate more and see if I can reproduce.

**Comment by SeparateRecords** [comment]
@kevinebaugh could you grab a time on my calendar? Would love to look at the logs live while this bug is occurring - seems like you can repro pretty reliably. My hunch was that the engine was choking on large numbers of suggestions, but I couldn't get it to fail even in torvalds/linux

**Comment by SeparateRecords** [comment]
https://calendly.com/robert-fig/support

**Comment by SeparateRecords** [comment]
The main issue should be resolved now! Think we found the cause of the hanging

**Comment by kevinebaugh** [comment]
Thanks! This is fixed for me 👍

Now I'm running into https://github.com/withfig/fig/issues/1964 and I'll follow along there.
