### ISSUE TITLE
Incorrect/Slow autocomplete for branch names

### ISSUE THREAD

**Issue by ford-carta** [withfig/fig#1947]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Noticeable decrease in performance, completely inaccurate autocomplete for branch checking out. Please help I love fig, but I'm about to /unistall for warp

![fig-issue](https://user-images.githubusercontent.com/88899271/198095492-0b85c930-d207-48b8-b892-5f2b45183fc7.gif)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.5|Version 1.0.62 (B542)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.62 (B542) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/fordneild/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/fordneild/.nvm/versions/node/v16.13.2/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/fordneild/.pyenv/shims:/usr/local/opt/libpq/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/fordneild/.fig/bin:/Users/fordneild/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (38554) - /dev/ttys001
Current terminal session: 58868337-a088-4527-857e-062e6804cb32
Current working directory: /Users/fordneild/projects/fund-admin
Current window identifier: 254/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @ford-carta! So to confirm, the issue is the latency when listing git branches? Is this reproducible in other projects?

**Comment by mschrage** [comment]
I've been able to repro myself and we are investigating! Thanks for reporting

**Comment by mschrage** [comment]
Try restarting Fig! This issue should be resolved now but I will keep this open until you can confirm.
