### ISSUE TITLE
Workflows not saving after update

### ISSUE THREAD

**Issue by codeninja55** [withfig/fig#1948]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS Ventura 13.0

### Expected behaviour

Autosave or having somewhere to press save when editing workflows.

### Actual behaviour

I've found that when editing my workflows, the top right status continues to show `saving` but no changes are actually saved. After restarting fig, the workflow goes back to the default `echo Hello World` when creating the workflow.

Have not been able to make any workflows as yet. Attached is an image of the current state: 

![Screenshot 2022-10-27 at 4 34 33 pm](https://user-images.githubusercontent.com/24749967/198201068-20ec6989-1e59-4b8c-8298-a6c26b099554.png)

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B542) [Australian]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro17,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 16 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /opt/homebrew/Cellar/zsh/5.9/bin/zsh
  - terminal: iterm
  - cwd: /Users/codeninja/
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /Users/codeninja/.krew/bin:/opt/homebrew/opt/openssl@3/bin:/Users/codeninja/go/bin:/opt/homebrew/opt/go@1.16/bin:/Users/codeninja/.krew/bin:/Users/codeninja/.krew/bin:/opt/homebrew/opt/openssl@3/bin:/Users/codeninja/.nvm/versions/node/v18.11.0/bin:/Users/codeninja/go/bin:/opt/homebrew/opt/go@1.16/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/codeninja/.fig/bin:/Users/codeninja/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/codeninja/bin:/Users/codeninja/bin:/Users/codeninja/bin:/Users/codeninja/.krew/bin:/Users/codeninja/bin:/Users/codeninja/bin:/Users/codeninja/bin:/Users/codeninja/.krew/bin:/Users/codeninja/bin:/Users/codeninja/bin:/Users/codeninja/bin:/Users/codeninja/.krew/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 62fa6555-23a5-4710-a891-bacbed7762e1
    - FIG_PID: 15983
    - FIG_PARENT: 62fa6555-23a5-4710-a891-bacbed7762e1
    - FIG_SET_PARENT: 62fa6555-23a5-4710-a891-bacbed7762e1
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by parssak** [comment]
Hey! Can you give it a shot now? I pushed a PR that should fix this.

**Comment by codeninja55** [comment]
> Hey! Can you give it a shot now? I pushed a PR that should fix this.

Sorry, been away for a few days. Working now. Thanks for the quick fix.
