### ISSUE TITLE
Accessibility disabled (for fig) but it is on

### ISSUE THREAD

**Issue by FabrizioInfante** [withfig/fig#1949]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Mac Os Ventura 13.0

### Expected behaviour

I expected that Fig recognize accessibility permission

### Actual behaviour

As you can see in the screenshot:

<img width="1401" alt="Screenshot 2022-10-27 alle 10 07 42" src="https://user-images.githubusercontent.com/520172/198227909-41d762c8-76e4-49ed-be18-c0b767f9eace.png">

accessibility is on but Fig doesn't recognize it

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B542) [Italian]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro17,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 8 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/xxx
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /opt/homebrew/bin/brew:/Users/xxx/.composer/vendor/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/xxx/.fig/bin:/Users/xxx/.local/bin:/Users/xxx/development/flutter/bin:/Users/xxx/.pub-cache/bin:/Users/xxx/fvm/default/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 802f96c3-57db-447d-8820-592d25367951
    - FIG_PID: 2760
    - FIG_PARENT: 802f96c3-57db-447d-8820-592d25367951
    - FIG_SET_PARENT: 802f96c3-57db-447d-8820-592d25367951
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: Extension is not installed.
  - Docker: false
```

**Comment by mschrage** [comment]
Hey @FabrizioInfante! Click the "+" button and navigate to select /Applications/Fig.app from the file picker window. This should resolve the issue.

**Comment by FabrizioInfante** [comment]
Hello @mschrage, it works thanks! I needed to remove Fig with "-" button and renable with "+" button.
