### ISSUE TITLE
Fig cross-platform image render

### ISSUE THREAD

**Issue by Milo123459** [withfig/fig#195]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. (e.g. I'm always frustrated when [...])
No
**Describe the solution you'd like**
A way of rendering PNGs/JPGs/GIFs in the terminal. Just makes some sort of request code and Fig interprets it and renders it as an image / gif / xyz.
**Describe alternatives you've considered**
Using ascii art / unicode blocks
**Additional context**
n/a

**Comment by mschrage** [comment]
Closing as this is currently out of scope.
