### ISSUE TITLE
bug: The Fig popup window opens in the wrong screen

### ISSUE THREAD

**Issue by MatteoGauthier** [withfig/fig#1954]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.5.1 (21G83)

### Expected behaviour

The fig popup open in the current screen next to the terminal cursor

### Actual behaviour

The Fig popup window opens on my second screen
![Capture d’écran 2022-10-28 à 12 57 17](https://user-images.githubusercontent.com/32040951/198571536-5baf41c9-20b3-485a-bced-f6e264490817.png)

### Environment

```yaml
fig-details:
  - desktop-version: 
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro18,1
  - chip-id: Apple M1 Pro
  - cores: 10 (8 performance and 2 efficiency)
  - mem: 16 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh
```

**Comment by mschrage** [comment]
Thanks for reporting this @MatteoGauthier! This should be fixed shortly.

**Comment by wxh06** [comment]
I can confirm that both iTerm2 and VSCode have experienced the same issue beginning from today with Fig `2.7.2` or `2.7.4-beta.0` installed on macOS 13.0.0 (22A380)

The autocomplete popup only appears on the first screen.

### Environment

```yaml
fig-details:
  - 2.7.4-beta.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /opt/homebrew/bin/zsh
```

![Screenshot 2022-11-04 at 16.19.02.png](https://user-images.githubusercontent.com/29367025/199928209-0755b034-7628-413c-aeb7-981c0fe58cac.png)

![Screenshot 2022-11-04 at 16.19.36.png](https://user-images.githubusercontent.com/29367025/199928034-aaeab86e-df27-4715-95b9-4aa80e34acc3.png)

**Comment by wxh06** [comment]
I can confirm that both iTerm2 and VSCode have experienced the same issue beginning from today with Fig `2.7.2` or `2.7.4-beta.0` installed on macOS 13.0.0 (22A380)

The autocomplete popup only appears on the first screen.

### Environment

```yaml
fig-details:
  - 2.7.4-beta.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /opt/homebrew/bin/zsh
```

![Screenshot 2022-11-04 at 16.19.02.png](https://user-images.githubusercontent.com/29367025/199928209-0755b034-7628-413c-aeb7-981c0fe58cac.png)

![Screenshot 2022-11-04 at 16.19.36.png](https://user-images.githubusercontent.com/29367025/199928034-aaeab86e-df27-4715-95b9-4aa80e34acc3.png)

**Comment by MatteoGauthier** [comment]
> Thanks for reporting this @MatteoGauthier! This should be fixed in the next release.

Hey, as @wxh06 said the latest beta don't fix the issue.

**Comment by mschrage** [comment]
@wxh06 @MatteoGauthier are you using iTerm in full screen?

**Comment by wxh06** [comment]
> @mschrage
> are you using iTerm in full screen?

Yes. The issue occurred when VSCode and iTerm2 entered full screen.

**Comment by wxh06** [comment]
I noticed that those should actually be two separate issues. @MatteoGauthier's issue occurs when an external monitor is plugged in; mine occurs when the terminal enters full screen in macOS 13 Ventura, which is tracked in #1989 and #1964

**Comment by MatteoGauthier** [comment]
> I noticed that those should actually be two separate issues. @MatteoGauthier's issue occurs when an external monitor is plugged in; mine occurs when the terminal enters full screen in macOS 13 Ventura, which is tracked in #1989 and #1964

Yes I'm using VSCODE terminal autocompletion with Fig, and I got the bug using an external display

**Comment by mschrage** [comment]
@wxh06 @MatteoGauthier 

Both of these issues are fixed on `2.7.6-beta.2`.  You can update to the beta by running `fig settings app.beta true`.

Thank you for your patience.

**Comment by mschrage** [comment]
The fix for this is live in 2.7.6! To upgrade to the latest version, run click the Fig icon in the menubar and then "Check for updates"

**Comment by MatteoGauthier** [comment]
Hey thanks for the fix, but I keep having the problem...

```
fig-details:
  - 2.7.9-beta.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh
```

**Comment by darthlite** [comment]
I'm having a similar issue that I cannot resolve. Using VS Codium's integrated terminal, fig's autocomplete popup appears in a very different place (screenshot attached). I think what is happening in my case is that the autocomplete popup is appearing wherever my iTerm hotkey window was, so it appears at the correct position for a different terminal.

![Screenshot 2022-12-25 at 7 30 21 PM](https://user-images.githubusercontent.com/116678368/209475594-1bb6cae9-66b6-4f73-aa21-fc1e4d78583b.jpg)
