### ISSUE TITLE
bug: Post script overwrites conflicting aliases in .zshrc

### ISSUE THREAD

**Issue by nskobelevs** [withfig/fig#1957]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS Ventura 13.0

### Expected behaviour

Aliases defined before the post script should exist in the shell

### Actual behaviour

Aliases get overwritten to their original value

### Steps to reproduce

* Use zsh shell
* Install .oh-my-zsh
* Define an alias (that conflicts with a .oh-my-zsh alias) before fig post block
* Open terminal
* Run `which <alias>` to see that alias was overwritten

I initially thought this might be an issue with my `.zshrc` config or oh-my-zsh but I have narrowed down the issue the fig specifically at the post block seems to be causing it.

oh-my-zsh has various aliases defined for efficiency and possibly other reasons. The one we will look at is `ls` which is aliases to `ls -G` (I can't tell you why).

Personally I prefer `exa` to `ls` so I usually alias ls to exa in my `.zshrc`. All is good and dandy but since uploading to MacOS Ventura, the alias hasn't been working.

The alias is defined correctly but when the fig post block is executed, it reverts back to it's `oh-my-zsh` alias.

sample `.zshrc`:

```bash
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"

# Other stuff here

# oh-my-zsh loaded
source $ZSH/oh-my-zsh.sh

# Other stuff here

echo "$(alias ls)"
alias ls=exa
echo "$(alias ls)"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"

echo "$(alias ls)"
```

When opening a terminal I get the following output:
```
ls='ls -G'
ls=exa
ls='ls -G'
➜  ~ 
```

Something is clearly happening during the post block execution to overwrite the aliases back to their original state.

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B542) [Irish]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro17,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 16 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/nskobelevs
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: ~/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/nskobelevs/.cargo/bin:/Users/nskobelevs/.fig/bin:/Users/nskobelevs/.local/bin:/Users/nskobelevs/.local/share/fig/plugins/git-flow
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 40f8d03b-6422-4704-9766-40f4d0128af3
    - FIG_PID: 39051
    - FIG_PARENT: 40f8d03b-6422-4704-9766-40f4d0128af3
    - FIG_SET_PARENT: 40f8d03b-6422-4704-9766-40f4d0128af3
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: installed!
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment]
Have you configured any aliases in Fig Dotfiles @nskobelevs?

**Comment by nskobelevs** [comment]
> Have you configured any aliases in Fig Dotfiles @nskobelevs?

While I have not configured any aliases in Fig Dotfiles, looking through that menu has showed me that I have the oh-my-zsh plugin installed. Uninstalling the plugin has resolved the issue. I believe I misunderstood what that plugin actually did and looks like it added oh-my-zsh functionality on top of my local oh-my-zsh installation re-defining the aliases.

I apologise for the oversight.

**Comment by mschrage** [comment]
No worries! Glad I could help.

**Comment by nskobelevs** [comment]
> No worries! Glad I could help.

I understand this is a completely irrelevant question but it might be worth asking since I can't find anything similar and I rather not embarrass myself by opening another ticket in case there's a trivial solution.

Am I missing a plugin or a setting here for it to autocomplete the script file? `fig doctor` isn't reporting any problems and execute bit is set. Everything worked prior to my Ventura setup - just can't remember if I setup fig differently. 

<img width="443" alt="image" src="https://user-images.githubusercontent.com/34107736/199134902-74a1007f-0edb-4fe0-8dd5-930caa13b8e4.png">

<img width="463" alt="image" src="https://user-images.githubusercontent.com/34107736/199135274-123d69f1-89f0-4cf2-8891-a117a596314c.png">

**Comment by mschrage** [comment]
Thanks for reporting this @nskobelevs! Definitely not an irrelevant question: this is a bug that should be fixed now, if you restart Fig.
