### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by yysofiyan** [withfig/fig#1959]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Mac OS Ventura

### Expected behaviour

Autocomplete not run

### Actual behaviour

Autocomplete not run

### Steps to reproduce

Autocomplete not run

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B542) [ABC]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro17,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 8 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/yysofiyan/Desktop/untitled folder 2/SIBW-B
  - exe-path: /Users/yysofiyan/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_PID: 11600
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/yysofiyan/.fig/bin:/Users/yysofiyan/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 8155427d-68c6-432f-824f-4d4d2b9b6d99
    - FIG_PARENT: 8155427d-68c6-432f-824f-4d4d2b9b6d99
    - FIG_SET_PARENT: 8155427d-68c6-432f-824f-4d4d2b9b6d99
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by ayoush-wal** [comment]
Same issue with macOS Monterey. It used to show git branches and automatically remembers my last hit path but now all those features are not working anymore

**Comment by mschrage** [comment]
Can you run `fig doctor` and share the output here?

**Comment by ayoush-wal** [comment]
Here :-

`
✔ Everything looks good!

  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!
`

**Comment by grant0417** [comment]
Can you update to the latest version (2.7.2) and check if this still happens?

**Comment by redx3091** [comment]
Still happens i have the last version (2.7.2) and not working

**Comment by grant0417** [comment]
If you have time here is a link to schedule a debugging call: https://calendly.com/grant-fig/debugging

**Comment by yysofiyan** [comment]
Thanks. Solved
