### ISSUE TITLE
MacOS 10.13.6 Fig showing black screen

### ISSUE THREAD

**Issue by Colman-Delaroziere** [withfig/fig#1960]
### Description:
When launching fig, a black window appears and no matter how long I wait, no content appears.

![Fig window preview](https://user-images.githubusercontent.com/111461260/198878731-2b12de16-1118-479f-927a-5c7251bc1cfa.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.13.6|Version 1.0.62 (B542)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.62 (B542) [French] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/colman/.fig/bin/fig
Accessibility: false
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Are you using a VPN or or on a slow internet connection @Colman-Delaroziere?

**Comment by SeparateRecords** [comment]
@Colman-Delaroziere is there anything showing in the console? Right click → Inspect Element → Console

**Comment by Colman-Delaroziere** [comment]
Sorry I couldn't reply earlier but here is the console @SeparateRecords :
![Fig console](https://user-images.githubusercontent.com/111461260/199185650-2454814a-ae69-44f7-8aa5-79b7be9e1ca1.png)

And yes I am on a pretty slow internet connection @mschrage ...

**Comment by mschrage** [comment]
It looks like this is actually an issue with the version of macOS that you are on. It looks like `globalThis` is not supported on High Sierra. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

cc @parssak

**Comment by parssak** [comment]
Just pushed a polyfill, can you try now? @Colman-Delaroziere

**Comment by Colman-Delaroziere** [comment]
Well now when running `brew install` i get the error: `macOS Catalina or newer is required for this software.`

**Comment by chaynabors** [comment]
Looks like we've bumped our version requirements to MacOS 10.13. I'm not certain what it was, but a feature was introduced in Catalina which we were unable to work around. Best advice I can offer is to upgrade your MacOS version.
