### ISSUE TITLE
JavaScript support for Workflows

### ISSUE THREAD

**Issue by vinimdocarmo** [withfig/fig#1963]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
I'd love to be able to write JavaScript code for a Workflow script. I could achieve way more by using a language like JavaScript other than Bash. I like [scriptkit](https://www.scriptkit.com/)  because of that.

**Comment by chaynabors** [comment]
This is supported. Let me know if you have any other issues.
