### ISSUE TITLE
fig doctor shows no problems but fig ui shows shell integration error

### ISSUE THREAD

**Issue by sriramr98** [withfig/fig#1966]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Mac OS Ventura 13.0

### Expected behaviour

I expected that the fig dashboard shows no error since `fig doctor` has no errors, but the dashboard shows an error

<img width="839" alt="Screenshot 2022-11-01 at 2 55 01 PM" src="https://user-images.githubusercontent.com/21296041/199202397-02012b72-04db-4874-af47-ce22d6a0eee7.png">
<img width="905" alt="Screenshot 2022-11-01 at 2 55 15 PM" src="https://user-images.githubusercontent.com/21296041/199202445-848f16b1-6775-423c-806d-23e7a7ddef7a.png">

### Actual behaviour

The dashboard shows no error or `fig doctor` shows an error depending on which shows wrong info

### Steps to reproduce

* Install FIG

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B542) [ABC – India]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro17,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 16 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/sriram-r/fonts
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/bin/:/Users/sriram-r/.fig/bin:/Users/sriram-r/.local/bin:/opt/homebrew/bin/:/opt/homebrew/bin/:
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 51adff99-855f-4187-a73d-f9fcaa563b46
    - FIG_PID: 15555
    - FIG_PARENT: 51adff99-855f-4187-a73d-f9fcaa563b46
    - FIG_SET_PARENT: 51adff99-855f-4187-a73d-f9fcaa563b46
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false
```

**Comment by Thebassplayer** [comment]
Have the same issue in an equal evironment

**Comment by mschrage** [comment]
This issue should be resolved. Please restart Fig.
