### ISSUE TITLE
bug: fig thinks latest integration isn't running

### ISSUE THREAD

**Issue by Integralist** [withfig/fig#1967]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6

### Expected behaviour

`fig doctor` to be successful and to have no errors.

### Actual behaviour

Fig menu bar app shows the latest version is installed, while the output suggests an environment variable is not up to date (I'm not sure where `FIG_TERM` is set, but I guess in the scripts you source in my `.zshrc` file).

The following screenshot shows I'm what I'm doing to work-around the error...

<img width="1573" alt="Screenshot 2022-11-01 at 09 57 33" src="https://user-images.githubusercontent.com/180050/199208493-e127c2c1-d0e4-4f78-a3d3-b8fc455faee7.png">

### Steps to reproduce

See screenshot above. I'm using Alacritty terminal with Zsh shell.

### Environment

```yaml
fig-details:
  - 2.7.1-beta.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /opt/homebrew/Cellar/zsh/5.9/bin/zsh
  - terminal: alacritty
  - cwd: /Users/integralist
  - exe-path: /Users/integralist/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.fj6lvy7Vi2/org.xquartz:0
    - FIGTERM_SESSION_ID: 259ffe85-a776-40fc-8103-78da659e2c12
    - FIG_HOSTNAME: D3496LK9V7
    - FIG_TERM: 2.7.0-beta.2
    - PATH: /Users/integralist/.yarn/bin:/Users/integralist/.config/yarn/global/node_modules/.bin:/Users/integralist/.goenv/versions/1.18.5/bin:/Users/integralist/.goenv/shims:/Users/integralist/.goenv/bin:/Users/integralist/Library/Caches/fnm_multishells/63186_1667296962119/bin:/Users/integralist/bin:/opt/homebrew/opt/ruby/bin:/Users/integralist/.cargo/bin:/Users/integralist/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/integralist/.fig/bin:/Users/integralist/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/integralist/go/1.18.5/bin
    - SHELL: /opt/homebrew/bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 63115
    - FIG_SET_PARENT: 259ffe85-a776-40fc-8103-78da659e2c12
```
```

**Comment by mschrage** [comment]
Thanks for reporting @Integralist - this should be resolved in the next release (coming out in an hour or so)

**Comment by mschrage** [comment]
Closing this issue since the fix should be live! Let me know if you're still running into issues @Integralist :0
