### ISSUE TITLE
Installation Check - Install Integrations via help & support does nothing when install is clicked

### ISSUE THREAD

**Issue by jrizz922** [withfig/fig#1969]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS 13

### Expected behaviour

Fig operates as expected with no errors.

### Actual behaviour

Fig app shows red message box with "Fig hasn't been installed correctly." Clicking Fix Installation Issues does not appear to fix issue. Clicking on message box shows Install shell integrations dialog, clicking Install button does not appear to do anything.

### Steps to reproduce

Open Fig dashboard

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B542) [U.S.]
hardware-info:
  - model: iMac
  - model-id: iMac19,1
  - chip-id: 
  - cores: 8
  - mem: 32 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/buffer
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/buffer/.fig/bin:/Users/buffer/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 784ab6e1-3484-4eea-b8f4-9be9eb085f4d
    - FIG_PID: 1204
    - FIG_PARENT: 784ab6e1-3484-4eea-b8f4-9be9eb085f4d
    - FIG_SET_PARENT: 784ab6e1-3484-4eea-b8f4-9be9eb085f4d
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false
```

**Comment by jrizz922** [comment]
<img width="513" alt="CleanShot 2022-11-01 at 06 12 05@2x" src="https://user-images.githubusercontent.com/73837747/199229759-c0c47709-5e84-4e5b-84ac-a5d395864878.png">

**Comment by jrizz922** [comment]
<img width="539" alt="CleanShot 2022-11-01 at 06 12 56@2x" src="https://user-images.githubusercontent.com/73837747/199229950-ead0d845-ff67-4221-8197-d3b6e3ebbb73.png">
<img width="659" alt="CleanShot 2022-11-01 at 06 14 18@2x" src="https://user-images.githubusercontent.com/73837747/199230161-089e04db-ecf0-4bfa-8f06-92b028209c3b.png">

**Comment by drewipson** [comment]
Commenting for follow as I have experienced the same issue.

**Comment by mschrage** [comment]
cc @rahulsarathy

**Comment by mschrage** [comment]
This should be fixed now @drewipson @jrizz922 . Make sure to restart Fig.

**Comment by jrizz922** [comment]
Looks good! Thank you @mschrage !
