### ISSUE TITLE
Autocomplete doesn't display on the correct screen when multiple monitors are connected

### ISSUE THREAD

**Issue by KirdesMF** [withfig/fig#1975]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.0 (22A380)

### Expected behaviour

In vscode, fig autocomplete screen should open correctly inside the terminal

### Actual behaviour

Actually, using vscode terminal and multiple screen, the autocomplete fig window will open in an other window and not inside vscode terminal.
I tried with one screen and it happens that the autocomplete appears also outside of vscode

### Steps to reproduce

Open vscode
use terminal

### Environment

```yaml
fig-details:
  - 2.7.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/kirdes/Dev/invite-dashboard
  - exe-path: /Users/kirdes/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: f772aba2-e330-452a-acf7-9802c5e2fdb2
    - FIG_HOSTNAME: Kirdes-macbook.local
    - FIG_PID: 1482
    - FIG_TERM: 2.7.2
    - PATH: /Users/kirdes/.rd/bin:/opt/podman/bin:/Users/kirdes/Library/pnpm:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kirdes/.rd/bin:/opt/podman/bin:/Users/kirdes/Library/pnpm:/Users/kirdes/.fig/bin:/Users/kirdes/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PARENT: f772aba2-e330-452a-acf7-9802c5e2fdb2
    - FIG_SET_PARENT: f772aba2-e330-452a-acf7-9802c5e2fdb2
```

**Comment by Thebassplayer** [comment]
Same thing also. 
![Screenshot 2022-11-03 at 15 10 47](https://user-images.githubusercontent.com/85585907/199801898-9cf6faf3-2d70-46cc-a7c8-eeacea9cb107.jpg)

**Comment by mlalitthapa** [comment]
Same issue on MacOS 13

https://user-images.githubusercontent.com/6380157/199887846-48dab2cf-0521-44f2-9ad4-9c271cc93aa8.mov

**Comment by mschrage** [comment]
It looks like there may be two distinct issues here:

1. Autocomplete does not appear in non-fullscreen VSCode windows. 

> If this is your issue, can you please share the version of VSCode you are using and run `echo $__CFBundleIdentifier` in the VSCode integrated terminal?

2. Autocomplete does not appear in fullscreen windows (potentially, limited to macOS Ventura)

> This is a known issue that we are investigating. If you are using Ventura, can you confirm that autocomplete does not work in any full screen terminal? If you are on a different version of macOS, can you confirm that autocomplete does appear in fullscreen terminals?

**Comment by mlalitthapa** [comment]
1. Autocomplete works in non-fullscreen VSCode windows.
2. Yes, I am using Ventura, and autocomplete does not work in any full-screen terminal, VSCode or iterm2.

**Comment by KirdesMF** [comment]
I can confirm 

2. Autocomplete works in non-fullscreen VSCode windows.
3. `Ventura 13.0` autocomplete does not work in any full-screen terminal

**Comment by mschrage** [comment]
We've figured out the underlying issues with autocomplete not appearing in full screen on Ventura.

**Comment by mschrage** [comment]
This is live on beta `2.76.-beta.2`. Run `fig settings app.beta true` to try it out now.

**Comment by KirdesMF** [comment]
Seems to be good. Thanks for the work
