### ISSUE TITLE
Setting blank white screen

### ISSUE THREAD

**Issue by tanduong** [withfig/fig#1979]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.0 (22A380)

### Expected behaviour

Show settings screen

### Actual behaviour

Show blank screen
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/7553677/199791105-c1c46ad7-3b0e-4bbe-9a9c-e1cbb2601e28.png">

### Steps to reproduce

Run `fig settings` or open fig app

### Environment

```yaml
fig-details:
  - 2.7.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/tanduong/Documents/code
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 099205f4-6408-4fe5-b6dd-cc4c15350aa4
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /Users/tanduong/.bin:/opt/homebrew/opt/openjdk/bin:/Users/tanduong/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tanduong/.fig/bin:/Users/tanduong/.local/bin:/Users/tanduong/Library/Application Support/JetBrains/Toolbox/scripts:/opt/homebrew/opt/fzf/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 1892
    - FIG_PARENT: d90e406e-00a0-40b0-9ca6-62d78c6665d3
    - FIG_SET_PARENT: d90e406e-00a0-40b0-9ca6-62d78c6665d3
```

**Comment by mschrage** [comment]
Hey @tanduong can you right click the window and press "Inspect Elements". Then share a screenshot of the console?

**Comment by tanduong** [comment]
It has an error saying that `https://desktop.fig.io/onboarding/welcome` is unreachable.
<img width="587" alt="image" src="https://user-images.githubusercontent.com/7553677/199797344-4974c8ab-00d0-4316-b357-ef1bcc760086.png">

**Comment by mschrage** [comment]
@tanduong do you have an internet connection? Are you using a VPN or an app like Little Snitch that blocks network connections?

**Comment by mschrage** [comment]
Where are you located? Perhaps our domain is blocked for some reason.

**Comment by tanduong** [comment]
I am in Vietnam.

**Comment by mschrage** [comment]
i'm going to close this issue for now. We've added a better "offline" page.

**Comment by duylinhng95** [comment]
Good day @mschrage,

I'm also from Vietnam and encounter this issue just like @tanduong . Could you help us to verify this issue again?

**Comment by GMoon777** [comment]
Same issue here. it doesn't just stop the settings from working, fig stops working in the terminal completely, like its hard locked up, only fig restart in terminal resolves this

**Comment by gitSambhal** [comment]
It was the vpn for me, after turning off the vpn I am able to see the dashboard. Also I ran `fig doctor` for it to work in the terminal after opening the dashboard.
