### ISSUE TITLE
bug: fig integrations status cmd is missing in suggestions

### ISSUE THREAD

**Issue by andriilive** [withfig/fig#1980]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS Version 13.0 (22A380)

### Expected behaviour

Expecting `status` to be presented as  `fig integrations` autocompletion

### Actual behaviour

status item is missing

<img width="630" alt="CleanShot 2022-11-03 at 23 39 53@2x" src="https://user-images.githubusercontent.com/43708848/199847881-5de13109-ba9b-4d5b-b549-84ad25818c3a.png">

### Steps to reproduce

`fig integrations `

### Environment

```yaml
fig-details:
  - 2.7.2
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/andy
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 29ee9b76-2d78-4727-be2d-2cf24c1d91c1
    - FIG_HOSTNAME: Andriis-MacBook-Pro.local
    - FIG_TERM: 2.7.2
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/andy/.fig/bin:/Users/andy/.local/bin:/Users/andy/Library/Application Support/JetBrains/Toolbox/scripts:vendor/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 71683
    - FIG_PARENT: 29ee9b76-2d78-4727-be2d-2cf24c1d91c1
    - FIG_SET_PARENT: 29ee9b76-2d78-4727-be2d-2cf24c1d91c1
```

**Comment by grant0417** [comment]
This is an issue with our spec not being update, @fedeci are you able to generate a 2.0.0 version of the fig spec?

**Comment by SeparateRecords** [comment]
I'll do this today @grant0417

**Comment by grant0417** [comment]
Thanks @SeparateRecords

**Comment by fedeci** [comment]
Thanks @SeparateRecords!

**Comment by grant0417** [comment]
This should be fixed by https://github.com/withfig/autocomplete/pull/1695 which will be live in the next day or so!
