### ISSUE TITLE
Wont start automatically

### ISSUE THREAD

**Issue by nautonk** [withfig/fig#1981]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.0 (22A380)

### Expected behaviour

Run automatically after i run terminal

### Actual behaviour

Wont start automatically, and thereis no debugger menu on fig
![Screenshot 2022-11-04 at 07 10 29](https://user-images.githubusercontent.com/3839865/199858284-f8038881-d10a-4668-bc86-e82489dbb740.jpg)

### Environment

```yaml
fig-details:
  - 2.7.3
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/qaila/Documents/MacDocs/MAMP/www_node/crossBroker
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 4377b2ee-f2dd-47ff-b8d1-aab542f6f874
    - FIG_HOSTNAME: Qailas-MacBook-Pro-2.local
    - FIG_TERM: 2.7.3
    - PATH: /Users/qaila/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/qaila/.fig/bin:/Users/qaila/.local/bin:/Users/qaila/.composer/vendor/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 718
    - FIG_PARENT: 4377b2ee-f2dd-47ff-b8d1-aab542f6f874
    - FIG_SET_PARENT: 4377b2ee-f2dd-47ff-b8d1-aab542f6f874
```
Thank you so much

**Comment by mschrage** [comment]
Hey @nautonk, when you say it doesn't "start automatically" are you talking about the Desktop app or about the autocomplete window?

**Comment by nautonk** [comment]
> Hey @nautonk, when you say it doesn't "start automatically" are you talking about the Desktop app or about the autocomplete window?

Desktop app, autocomplete window works fine but I have to run the app manually. Previously when I opened iterm2, the fig app automatically opened but now it doesn't.

**Comment by mschrage** [comment]
Try enabling this setting: `fig settings app.launchOnStartup true`

**Comment by nautonk** [comment]
> Try enabling this setting: `fig settings app.launchOnStartup true`

It works, but what i need is to automatic start fig when launching a new shell session. Btw at the moment i will use "launch on startup" feature. Thank you
![Screenshot 2022-11-09 at 12 46 42](https://user-images.githubusercontent.com/3839865/200749339-6e68f6a6-40f4-40d3-a63e-3214328f9bac.jpg)
