### ISSUE TITLE
Fig autocomplete doesn't work after update to 2.7.4 via Brew

### ISSUE THREAD

**Issue by imanAzi** [withfig/fig#1991]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.0 (21G115)

### Expected behaviour

Autocomplete still be working in Iterm2 with an update to version 2.7.4

### Actual behaviour

After updating Fig via Brew to version 2.7.4, auto-complete doesn't work anymore. 

I tried with no success: 
1) ![image](https://user-images.githubusercontent.com/25829454/200062857-b8b53b7c-d378-447d-a5ef-a13943410296.png)

2) fig restart
3) MacBook restart didn't help
4) Checked if Fig AutoComplete was turned on and also turned on for Iterm2 terminal (same behavior in VScode terminal)
5) Opening 'Autocomplete DevTools' shows the following errors:
![image](https://user-images.githubusercontent.com/25829454/200064371-58935fc5-1175-4946-be5b-516b31cba9dc.png)
![image](https://user-images.githubusercontent.com/25829454/200064392-5d79c33e-a2ec-463c-81cf-c0697b5ce56a.png)
6) Checked if the Fig pre and post-block are still in my .zshrc ==> yes

### Steps to reproduce

1) Upgrade Fig to 2.7.4 via Brew
2) Start mew Iterm2 session and try git or aws commands

### Environment

```yaml
fig-details:
  - 2.7.4
hardware-info:
  - model: Apple
  - model-id: MacBook
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/iazimnia
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 2ce05aed-e858-441c-a6ec-c710556fe5fb
    - FIG_HOSTNAME: BEG2N52LV45C
    - FIG_TERM: 2.7.4
    - PATH: /Users/iazimnia/go/bin:/opt/homebrew/bin:/usr/local/sbin:/usr/local/bin/brew:/usr/local/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/iazimnia/.fig/bin:/Users/iazimnia/.local/bin:/Users/iazimnia/Library/Application Support/JetBrains/Toolbox/scripts:~/.local/bin/:/Users/iazimnia/.local/bin:/Users/iazimnia/Library/Python/3.9/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 3738
    - FIG_PARENT: 2ce05aed-e858-441c-a6ec-c710556fe5fb
    - FIG_SET_PARENT: 2ce05aed-e858-441c-a6ec-c710556fe5fb
```

**Comment by mschrage** [comment]
@imanAzi is your terminal in full screen?

**Comment by imanAzi** [comment]
@mschrage yes both full screen and not in full screen it doesn't auto-complete, I get the following screen:
![image](https://user-images.githubusercontent.com/25829454/200080394-7e5697c3-d9bf-46c0-9850-bd4820768f88.png)

Where after my first command a line appears under the command, I don't see the suggestions but if I move around with the arrow keys and press 'Enter' it selects one of the suggestions that normally should be shown.

**Comment by mschrage** [comment]
Can you run `fig debug autocomplete-window`

**Comment by imanAzi** [comment]
I get this now:
![image](https://user-images.githubusercontent.com/25829454/200082830-a50930e8-123e-4bc3-9856-5dab0cf192bf.png)

**Comment by mschrage** [comment]
It looks like you are running in developer mode - I think that is the issue here.

Run `fig settings all`

**Comment by imanAzi** [comment]
I disabled the developer mode, shut down Iterm2, and started a new session but still no luck:
![image](https://user-images.githubusercontent.com/25829454/200083594-513cbcba-a040-486b-aa5f-a1618828b940.png)

**Comment by grant0417** [comment]
Might be your fontsize being = 0, try `fig settings --delete autocomplete.fontSize`

**Comment by natuan62** [comment]
> fig settings all

it's worked. thanks!!

**Comment by daolou** [comment]
I meet same: not work in iterm2

iterm2:
![image](https://user-images.githubusercontent.com/22312092/201003546-a047341c-2514-4462-916d-7eab2d87c5f6.png)

fig: 
![image](https://user-images.githubusercontent.com/22312092/201003409-bd67f6e9-fd71-491d-a5e4-b7ff97bea023.png)


![image](https://user-images.githubusercontent.com/22312092/201003040-22c8f26d-18eb-4d81-a1fa-61df0b17c0a0.png)

![image](https://user-images.githubusercontent.com/22312092/201003093-1b1163f1-c019-4dad-beb3-35d5aecb26f6.png)

![image](https://user-images.githubusercontent.com/22312092/201003209-9705709b-6643-4f0b-9462-e335396b007b.png)

There is a red point.

**Comment by mschrage** [comment]
Hey @daolou would you mind creating a new issue? Just run `fig issue`
