### ISSUE TITLE
bug: Linux always complains about pre-cmd when sshing

### ISSUE THREAD

**Issue by a1ecbr0wn** [withfig/fig#1998]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Ubuntu 22.04

### Expected behaviour

I would expect to be able to start and to not print the warning on every remote shell.

### Actual behaviour

When sshing to the linux box, it always shows the warning whether the machine that you  are SSHing from has fig installed or not.  One thing to note(I don't know if it is relevant) I do have starship installed.  I suspect that this is something left over in a script that I got from an early beta.  Error message _after_ the execution of any command:

```
error: Found argument 'pre-cmd' which wasn't expected, or isn't valid in this context

USAGE:
    fig internal <SUBCOMMAND>

For more information try --help
```

### Steps to reproduce

It happens after the execution of any command.  I did raise this in the `user-help` Discord but got no solutions.

I have tried uninstalling fig, deleting all .fig* directories in my home, and reinstalling, it still happens and now the fig user interface never actually starts up, I get the logon webpage and when I enter my code I get another page that tells me to install fig.

Here is some fig output that may be of interest:

```
 ⌚︎16:45:25 
 ultron  alecbrown  ~   fig doctor
⠋ Running checks...
→ Launching Fig...


✘ Fig Integration: Figterm is not running
  FIG_INTEGRATION_VERSION=None


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

error: Found argument 'pre-cmd' which wasn't expected, or isn't valid in this context

USAGE:
    fig internal <SUBCOMMAND>

For more information try --help

 ⌚︎16:47:47 
 ultron  alecbrown  ~   fig launch

→ Launching Fig...

error: 
Unable to finish launching Fig properly

error: Found argument 'pre-cmd' which wasn't expected, or isn't valid in this context

USAGE:
    fig internal <SUBCOMMAND>

For more information try --help

 ⌚︎16:49:18 
 ultron  alecbrown  ~ ❯ fig restart

→ Launching Fig...

error: 
Unable to finish launching Fig properly

error: Found argument 'pre-cmd' which wasn't expected, or isn't valid in this context

USAGE:
    fig internal <SUBCOMMAND>

For more information try --help
 ⌚︎16:51:36 
 ultron  alecbrown  ~ ❯ fig issue

→ Fig is not running.
  Please launch Fig with fig launch or run fig issue --force to create the issue anyways
error: Found argument 'pre-cmd' which wasn't expected, or isn't valid in this context

USAGE:
    fig internal <SUBCOMMAND>

For more information try --help
 ⌚︎17:03:55 
 ultron  alecbrown  ~   fig issue --force
### Details:
|OS|Fig|Shell|
|-|-|-|
|Linux 5.15.0-52-generic|fig_desktop 2.5.3
|/usr/bin/bash|
fig diagnostic

# Fig Diagnostics
## NOTE: Fig is not running, run `fig launch` to get the full diagnostics
## Fig details:
## Hardware Info:
  - Model Name: cpu0
  - Model Identifier: GenuineIntel
  - Chip: Intel(R) Core(TM) i3-4170T CPU @ 3.20GHz
  - Cores: 2
  - Memory: 8267776 KB
## OS Info:
  - Linux 5.15.0-52-generic
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /home/alecbrown
  - CLI Installed: true
  - Executable Location: /home/alecbrown/.local/bin/fig
  - Current Window ID: <unknown>
  - Active Process: <unknown>
  - Terminal: <unknown>
  - Environment Variables:
    - FIG_WORKFLOWS_KEYBIND=^f
    - TERM=xterm-256color
    - FIG_PID=2854
    - PATH=/home/alecbrown/.cargo/bin:/home/alecbrown/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/alecbrown/.local/bin:/home/alecbrown/.fig/bin:/home/alecbrown/.local/bin:/home/alecbrown/scripts:/home/alecbrown/.cargo/bin:/Users/a1ecbr0wn/.vim:/Users/a1ecbr0wn/.vimrc:/Users/a1ecbr0wn/.fig/bin:/Users/a1ecbr0wn/.git
## Integrations:

→ Opening GitHub...

error: Found argument 'pre-cmd' which wasn't expected, or isn't valid in this context

USAGE:
    fig internal <SUBCOMMAND>

For more information try --help
```

### Environment

```yaml
It won't start up since I reinstalled!!


 ⌚︎17:04:21 
 ultron  alecbrown  ~   fig diagnostic

→ Fig is not running.
  Please launch Fig with fig launch or run fig diagnostic --force to get limited diagnostics.
error: Found argument 'pre-cmd' which wasn't expected, or isn't valid in this context

USAGE:
    fig internal <SUBCOMMAND>

For more information try --help
```
```

**Comment by squili** [comment]
@a1ecbr0wn Please run the following to try a complete purge of Fig:
1. Uninstall Fig normally
2. Delete `~/.fig*` and `~/.local/share/fig` (if it exists)
3. Run `grep '\.fig/shell' ~/.* 2>/dev/null` and delete any lines that show up
4. Run `sudo rm -f $(which fig)`, `sudo rm -f $(which figterm)`, and `sudo rm -f $(which fig_desktop` to make sure the binaries are gone
And then perform a normal installation

**Comment by a1ecbr0wn** [comment]
Thank you @squili.

That seemed to remove everything for sure, but then an install, reboot and try to run `fig` in my terminal (hyper), the gui starts, but it won't get past the screen below  where the `enable` button doesn't seem to work.  WhenI ssh in, it no longer compains about pre-cmd so the underlying issue was sorted.  Perhaps I just have a bad build and need to wait a few days and try the install again.  If you agree I will close the issue and wait a bit.

![Screenshot from 2022-11-09 22-16-43](https://user-images.githubusercontent.com/12213854/200955615-a5afb9f6-d3fb-416c-b9ca-767bc263bc39.png)

**Comment by squili** [comment]
It definitely shouldn't be getting to that page on Linux. I talked with the systems engineering team lead and he says to spam click the enable button. Could you try that? If that doesn't fix it, I'm working on getting a new Linux build out soon, and that should fix all your problems!

**Comment by a1ecbr0wn** [comment]
When I press enable I get the next screen with "Checking Accessibility Permissions" and then gnome locks up, and through htop Insee something called "WebKitProcess" maxing out a few of my cores.

**Comment by squili** [comment]
While you wait, you can run `fig _ local-state desktop.completedOnboarding true` to bypass the window for now

**Comment by a1ecbr0wn** [comment]
That works, thank you.


One more thing, how do I solve the `FIG_INTEGRATION_VERSION=None` issue
```
> fig doctor

● /home/alecbrown/.zshrc does not source pre integration
● /home/alecbrown/.zprofile does not source pre integration
✘ Fig Integration: Figterm is not running
  FIG_INTEGRATION_VERSION=None


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

**Comment by a1ecbr0wn** [comment]
Ah, just noticed that this is a recognised bug #1955 so I will close this as the main issue is resolved.   Thank you for your help @squili
