### ISSUE TITLE
Add "How to uninstall Fig" to the docs

### ISSUE THREAD

**Issue by shinokada** [withfig/fig#2]
HI,

I am not able to find how to uninstall Fig from my terminal.

What is the best way to uninstall it?

And please add it to the doc, https://docs.withfig.com/

Thanks.

**Comment by falky97** [comment]
Added! https://docs.withfig.com/other/faq

Thanks @shinokada !!

**Comment by shinokada** [comment]
@falky97 
Thanks.
I think you need to remove ~/.fig directory and lines relating to find from a config file (~/.bashrc or~/.zshrc).

**Comment by falky97** [comment]
Hmmm I thought we were already doing that. I will reopen this now and test tomorrow

**Comment by falky97** [comment]
Uninstall is in our newest docs too: https://withfig.com/docs/support/faq

Uninstall also removes fig from your dot files etc

**Comment by snoblenet** [comment]
both of the above links are dead

**Comment by brendanfalk** [comment]
The most up to date uninstall link (and will be from now on) is [this github discussion](https://github.com/withfig/fig/discussions/140): https://github.com/withfig/fig/discussions/140

**Comment by kimbang89** [comment]
sudo apt-get remove fig-headless . I'm from Vietnamese

**Comment by lokzz** [comment]
that link is now also dead & fig cant properly remove itself for me, had to manually remove it from my dotfiles & delete the .fig folder because it kept popping up during ssh

**Comment by Tetonne** [comment]
delete cd /usr/local/Caskroom/fig
