### ISSUE TITLE
Switching windows from terminal in SSH session to chrome then back pastes ansi escape codes

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#200]
Bug:

1. Have iTerm open
1. SSH into a remote machine
1. Click on chrome and scroll a little bit
1. Click back on the terminal

It then pastes weird ANSI escape codes e.g. `0;41;16M0;41;16`

This only happens under certain conditions and we cannot accurately reproduce just yet

**Comment by quackduck** [comment]
Do you think this could help: https://unix.stackexchange.com/questions/568423/disable-mouse-codes-passing-to-terminal-once-it-was-turned-on-by-application

**Comment by mattschrage** [comment]
Great suggestion @quackduck! This seems like it might be the culprit since I'm not sure how Fig would be sending this.

**Comment by mattschrage** [comment]
For more details, check out this page on VT100 [Mouse Tracking](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking).

A few other suggestions on how to fix:
- Run `stty sane` 
or
- Run `reset` (this might be overkill)
