### ISSUE TITLE
bug: Autocomplete pupup always in top left corner of Alacritty

### ISSUE THREAD

**Issue by H4ckint0sh** [withfig/fig#2000]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Mac OSX 12.6

### Expected behaviour

Aotocomplete box in expected position.

### Actual behaviour

Then box always appear in top left corner if there is just one monitor. If two or  more monitors will the autocomplete box appear in the monitor before the active one in top right corner.

### Steps to reproduce

run alacritty and write something to trigger autocomplete box.

### Environment

```yaml
fig-details:
  - 2.7.5
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: alacritty
  - cwd: /Users/ali/.dotfiles
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 985423ac-9f92-4a2d-ad22-9f7cefc23945
    - FIG_HOSTNAME: MacBook Dries
    - FIG_PARENT: 6c3e79e7-d345-4f00-87c8-5b844c173279
    - FIG_PID: 8819
    - FIG_SET_PARENT: 985423ac-9f92-4a2d-ad22-9f7cefc23945
    - FIG_TERM: 2.7.5
    - FIG_TERM_TMUX: 2.7.5
    - PATH: /Users/ali/bin:/usr/local/sbin:/Users/ali/.nvm/versions/node/v14.17.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/ali/bin:/usr/local/sbin:/Users/ali/.nvm/versions/node/v14.17.5/bin:/Users/ali/.cargo/bin:/Users/ali/.fig/bin:/Users/ali/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
```

**Comment by SeparateRecords** [comment]
Just to check, have you added the input method integration? Double check by running `fig integrations install input-method

**Comment by SeparateRecords** [comment]
Actually, I can reproduce. Only happens with alacritty. Weird.

**Comment by H4ckint0sh** [comment]
@SeparateRecords It does answer installed so i must have installed it.

**Comment by mschrage** [comment]
This is a change in behavior in the latest version of Alacritty. If you downgrade to a previous version of Alacritty, Fig will determine the caret position directly.

I'm investigating this currently.

**Comment by H4ckint0sh** [comment]
Downgrading Alacritty is unfortunately not an option for me, hope to see a solution soon.

**Comment by mschrage** [comment]
Figured out a workaround. Fix should go live to beta later this evening. Thanks for reporting @H4ckint0sh .

**Comment by SeparateRecords** [comment]
Woo! Go @mschrage!

@H4ckint0sh You can upgrade to beta by running `fig settings app.beta true` 🙂

**Comment by H4ckint0sh** [comment]
@mschrage Thanks for the effort but this is still a problem for me, now it is always shown in first monitor att bottom left corner.

**Comment by SeparateRecords** [comment]
Hmm, still broken for me too. One of those really pesky bugs...

**Comment by H4ckint0sh** [comment]
@mschrage @SeparateRecords I dont know why but it just started to work as expected! Very strange bug indeed!

**Comment by mschrage** [comment]
I think the logic that resolves this bug is live in the beta, however it might require restarting your computer (or at a minimum, restarting Alacritty, to be applied). I'll see if I can make the update a bit smoother before we push to stable.
