### ISSUE TITLE
Something went wrong :( Error: Failed setting user_id: EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by BlackMoonWolf** [withfig/fig#2005]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.0 (22A380)

### Expected behaviour

New user. First time verifying code by email, the app froze. I killed the process and started Fig again. I repeated email verification but, now, I only get this:

```
Something went wrong :(
Error: Failed setting user_id: EOF while parsing a value at line 1 column 0
```

Using "fig doctor" doesn't help.

```
user@macbook ~ % fig doctor

✘ PATH contains ~/.local/bin: Path does not contain ~/.local/bin


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

### Actual behaviour

![Screenshot 2022-11-06 at 18 44 31](https://user-images.githubusercontent.com/16857362/200205278-cd636175-31f6-44e8-b09e-09d950b96090.png)

### Steps to reproduce

Close and re-open. Nothing changes.

### Environment

```yaml
fig-details:
  - 2.7.5
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/coryk
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /bin/zsh
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin
    - TERM: xterm-256color
```

**Comment by brendanfalk** [comment]
Try `fig logout` then `fig login`

**Comment by SeparateRecords** [comment]
Hey @BlackMoonWolf! Thanks for opening the issue 🙂 Going to close as dup of #1997, same root cause (not sure what it is yet though)

**Comment by AMaNong** [comment]
Wow, me too. 😢

**Comment by SeparateRecords** [comment]
@AMaNong I posted a solution in that issue I linked!
