### ISSUE TITLE
bug: generated suggestions do not appear for `cd`

### ISSUE THREAD

**Issue by jesalrathooddd** [withfig/fig#2007]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.0 (22A380)

### Expected behaviour

after space auto options should populate and it's not populating

### Actual behaviour

Nothing is happening if I type cd space in the current directory

### Environment

```yaml
fig-details:
  - 2.7.5
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh
```

**Comment by mschrage** [comment]
Hey @jesalrathooddd, if you open a new terminal session does the issue persist?

**Comment by jesalrathooddd** [comment]
Hey @mschrage 

I just uninstalled Fig & again installed the same.

I just tried and when my terminal is minimised, it's working. But if I make my terminal to Full Screen it's not auto populating.

Any specific configuration needs to be changed for Full Screen in the latest release 2.7.5 ??

**Comment by blakemorgan** [comment]
I can confirm I have the same issue. Typing `git co` or `cd` will display autocomplete options only when the terminal is not full screen.

**Comment by mschrage** [comment]
This is fixed in the latest beta. See #1964 for details. @blakemorgan @jesalrathooddd
