### ISSUE TITLE
bug: No Confirmation Email with Token Arrives

### ISSUE THREAD

**Issue by odonckers** [withfig/fig#2009]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0

### Expected behaviour

To receive an email with the 6 digit token to login into my personal Fig account.

### Actual behaviour

Nothing. Absolutely nothing happens.

### Steps to reproduce

I was attempting to log in on a new device, and the code wasn't being received. So I went to my personal machine and attempted to log in. It to was unable to receive a confirmation email.

### Environment

```yaml
fig-details:
  - 2.7.5
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/odonckers
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 8b6fa827-0a16-4f6e-a0ee-3d9b99957987
    - FIG_HOSTNAME: Owens-MacBook-Pro.local
    - FIG_TERM: 2.7.5
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/odonckers/.fig/bin:/Users/odonckers/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/homebrew/Cellar/openjdk@11/11.0.12/libexec/openjdk.jdk/Contents/Home/bin:/platform-tools:/Users/odonckers/Library/Application Support/JetBrains/Toolbox/scripts:/opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 50070
    - FIG_PARENT: 8b6fa827-0a16-4f6e-a0ee-3d9b99957987
    - FIG_SET_PARENT: 8b6fa827-0a16-4f6e-a0ee-3d9b99957987
```

**Comment by mschrage** [comment]
Hey @odonckers, if you try now is the confirmation email sent?

**Comment by coryroyce** [comment]
I had a similar issue, when trying to setup Fig for the first time. Any suggestions other than re-trying?
