### ISSUE TITLE
bug: incompatibility with `oh-my-zsh` plugin breaks terminal

### ISSUE THREAD

**Issue by nandorojo** [withfig/fig#2012]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

I didn't run these commands ^ because my terminal was entirely unusable.

### Operating system

Mac 12.4 (21F79)

### Expected behaviour

My terminal should be functional.

### Actual behaviour

The terminal is unusable on Warp, VSCode, etc. after Fig launches. It shows the same error, and I can't `ctrl + c` out of it.

![image](https://user-images.githubusercontent.com/13172299/200427285-56311188-d2b2-41f5-bbf5-2394421f661c.png)

![image](https://user-images.githubusercontent.com/13172299/200427343-ba893bf3-f035-415d-9cdc-e06aaf5b1a38.png)

### Steps to reproduce

Not sure honestly.

### Environment

```yaml
I uninstalled `fig` and this fixed the issue for me. So I can't run `fig diagnostic`. That said, I wasn't able to run any commands with this bug.
```

**Comment by mschrage** [comment]
Did you install oh-my-zsh through the Fig plugin store? It looks like this may have caused some issues. 

It would be really helpful if you could reinstall Fig (without adding any plugins) and check if the issue presists?

**Comment by nandorojo** [comment]
Thanks for the quick response. Just reinstalled. Looks like I see this warning for `oh-my-zsh` still, I don't believe I installed it through Fig:

```sh

   One last thing...

   Run fig doctor right now. 
   This checks for common bugs and fixes them!

[oh-my-zsh] plugin 'git,' not found
┌─[fernandorojo@MacBook-Pro-5] - [~] - [Mon Nov 07, 17:41]
└─[$]> 
```

**Comment by mschrage** [comment]
Ah interesting. Do you still have the same issue is before or has that been resolved?

**Comment by nandorojo** [comment]
Looks like reinstalling with a new account fixed it!
