### ISSUE TITLE
FR: Optionally inject the "placeholder" value in a workflow if not specified

### ISSUE THREAD

**Issue by polds** [withfig/fig#2016]
I was directed here from [Discord](https://discord.com/channels/837809111248535583/839904509466640434/1039669348224213042). 

It'd be nice if there was a checkbox or something that allowed you to inject the Placeholder value into the workflow if not otherwise set.

For example, even as something as simple as the "Forward requests from local to remote server" workflow in the workflow store, it'd be nice to just leave _everything_ empty and automatically use what ever is in the placeholder so you could set up a common bastion host, or a developer workstation or something.

**Comment by mschrage** [comment]
Hey @polds! Really appreciate this feedback. I think we can add support for adding "default" values to parameters. 👍

**Comment by chaynabors** [comment]
We have support for default parameters now. It's a little quirky at the moment but should fit your use case here. Thanks for the request!

**Comment by polds** [comment]
I tried this out and it works pretty well. The only feedback I have is that it'd be nice to still open the fig prompt if I have placeholders for everything so I can swap things in and out. Right now if you set placeholders for everything it just executes the command.
