### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by UltramanLeo** [withfig/fig#2019]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.0 (22A380)

### Expected behaviour

✘ Settings Corruption: Fig state file is corrupted
Attempting to fix automatically...
Re-running check...

✔ Settings Corruption
✘ PATH and PseudoTerminal PATH match: paths do not match
Attempting to fix automatically...
Re-running check...

✘ PATH and PseudoTerminal PATH match: paths do not match

✘ Doctor found errors. Please fix them and try again.

### Actual behaviour

一直报错，没法正常使用

### Steps to reproduce

fig doctor

### Environment

```yaml
fig-details:
  - 2.7.5
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/nexus
  - exe-path: /Users/nexus/.fig/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 6774384d-0f48-4779-b81c-5a20310a44e3
    - FIG_HOSTNAME: NexusMacPro.local
    - FIG_TERM: 2.7.5
    - PATH: /Users/nexus/.local/share/fig/plugins/git-open:/opt/homebrew/bin:/opt/homebrew/sbin:/Applications/Yunshu.app/Contents/Public:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/nexus/.fig/bin:/Users/nexus/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 74010
    - FIG_PARENT: 6774384d-0f48-4779-b81c-5a20310a44e3
    - FIG_SET_PARENT: 6774384d-0f48-4779-b81c-5a20310a44e3
```

**Comment by grant0417** [comment]
Hey @UltramanLeo can you run `fig doctor --verbose`, we actually do not use the "PATH and PseudoTerminal PATH match" check anymore and should remove it.

**Comment by mschrage** [comment]
@UltramanLeo this should be fixed on the latest version!
