### ISSUE TITLE
fig not working in vscode integrated terminal FULL-SCREEN

### ISSUE THREAD

**Issue by imflash217** [withfig/fig#2021]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.0 (22A380)

### Expected behaviour

`fig` should work in `vscode` integrated terminal after I have enabled it in `fig-settings`.

### Actual behaviour

I have enabled `vscode` integration but it **does not work** in the integrated `vscode` terminal.
<img width="1025" alt="Screenshot 2022-11-09 at 12 15 27 PM" src="https://user-images.githubusercontent.com/12234745/200896684-8da6f7b2-209c-4d2c-bca9-0c0dafa62b08.png">

### Steps to reproduce

1. Enable `vscode` integration in `fig` settings.
3. Open `vscode` and make it to FULL-SCREEN
4. Start writing any command (like `cd` or something`).
5. At this point we expect `fig` to show its UI but it does not show when `vscode` is in full-screen. Rather it shows in the Desktop (not on top of my vscode terminal UI.

Works in non-full-screen mode of `vscode`.
https://user-images.githubusercontent.com/12234745/200899285-d0e15ddf-c9d1-47e5-a72a-0b26a741ccf7.mov

Does not work properly in full-screen mode of `vscode`
https://user-images.githubusercontent.com/12234745/200899307-ca674572-5807-493c-98f9-6264972c9c0d.mov

### Environment

```yaml
fig-details:
  - 2.7.5
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  - cores: 4
  - mem: 8.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /usr/local/Cellar/zsh/5.9/bin/zsh
  - terminal: vscode
  - cwd: /Users/imflash217/Desktop/flashAI/Jobs@USA/BoomAI
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 703eba38-2c4b-4e8d-8fae-e81ea7d20099
    - FIG_HOSTNAME: Vinays-MBP-5.nc.rr.com
    - FIG_TERM: 2.7.5
    - PATH: /usr/local/opt/llvm/bin:/opt/anaconda3/envs/boom/bin:/opt/anaconda3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/imflash217/.fig/bin:/Users/imflash217/.local/bin:/usr/local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 95610
    - FIG_PARENT: 703eba38-2c4b-4e8d-8fae-e81ea7d20099
    - FIG_SET_PARENT: 703eba38-2c4b-4e8d-8fae-e81ea7d20099
```

**Comment by moratojoan** [comment]
The same thing happens to me. I was going to open an issue but I saw this one.

**Comment by mschrage** [comment]
We are pushing a fix live in the next hour or so. In the meantime, update to the beta. See this issue for details #1964

**Comment by mschrage** [comment]
2.7.6 is live! To upgrade to the latest version, run `fig update`.
