### ISSUE TITLE
bug: Fig doesn't launch on start with the turned on setting

### ISSUE THREAD

**Issue by danulqua** [withfig/fig#2029]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS Ventura 13.0.1

### Expected behaviour

If the `Launch on Start` is turned on, Fig should launch on the system startup.

### Actual behaviour

Fig doesn't launch on the system startup. Auto launch setting is turned on.  

![CleanShot 2022-11-10 at 22 11 34@2x](https://user-images.githubusercontent.com/38916225/201196146-916b03ef-eda0-47bf-bd06-6f5d98b80ab9.jpg)

### Steps to reproduce

1. Turn on the `Launch on Start`
2. Restart computer
3. After restart, notice that Fig didn't launch

### Environment

```yaml
fig-details:
  - 2.7.7
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/danil0110
  - exe-path: /Users/danil0110/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 9c20bed7-9bf8-4d80-a8f6-e9c4cfbda637
    - FIG_HOSTNAME: Danil-MBP.local
    - FIG_TERM: 2.7.7
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/Users/danil0110/.oh-my-zsh/custom/plugins/git-open:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/danil0110/.fig/bin:/Users/danil0110/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 8299
    - FIG_PARENT: 9c20bed7-9bf8-4d80-a8f6-e9c4cfbda637
    - FIG_SET_PARENT: 9c20bed7-9bf8-4d80-a8f6-e9c4cfbda637
```

**Comment by mschrage** [comment]
Does anything come up if you run `fig doctor` ?

**Comment by danil0110** [comment]
@mschrage 
![CleanShot 2022-11-11 at 09 40 18@2x](https://user-images.githubusercontent.com/38916225/201290644-696cbbcd-a0b1-4c2e-9a02-04b10a0c1cab.jpg)
