### ISSUE TITLE
Accessibility enabled: Accessibility is disabled when Fig is given permission in system preferences Ventura 13.0.1

### ISSUE THREAD

**Issue by Mhairi-Helen** [withfig/fig#2035]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.1 (22A400)

### Expected behaviour

Fig to run normally once

### Actual behaviour

Fig not working as it doesn't recognise that it has the accessibility permisions

✘ Accessibility enabled: Accessibility is disabled
Attempting to fix automatically...

Re-running check...

✘ Accessibility enabled: Accessibility is disabled

✘ Doctor found errors. Please fix them and try again.

### Steps to reproduce

- Accessibility permisions switched on and off:
- <img width="470" alt="Screenshot 2022-11-11 at 21 04 19" src="https://user-images.githubusercontent.com/24223078/201430388-26bce0ba-08f8-43e9-8a75-cee9867216cc.png">
- Ran `fig restart`
- Still get the following error and fig doesn't work
- <img width="495" alt="Screenshot 2022-11-11 at 21 05 29" src="https://user-images.githubusercontent.com/24223078/201430544-0b069fbb-da0e-43ff-bd7d-d886a5061d13.png">
- Run `fig doctor` and get the following error

✘ Accessibility enabled: Accessibility is disabled
Attempting to fix automatically...

Re-running check...

✘ Accessibility enabled: Accessibility is disabled

✘ Doctor found errors. Please fix them and try again.

### Environment

```yaml
fig-details:
  - 2.7.7
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /usr/local/Cellar/zsh/5.9/bin/zsh
  - terminal: iterm
  - cwd: /Users/mhairihislop
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: efb30eaf-d4b7-4495-b0c1-82fe1ed82ca4
    - FIG_HOSTNAME: Mhairis-MacBook-Pro-2.local
    - FIG_TERM: 2.7.7
    - PATH: /Users/mhairihislop/opt/anaconda3/bin:/Users/mhairihislop/opt/anaconda3/condabin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/mysql/bin:/usr/local/opt/php/bin:/usr/local/bin/brew/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/Users/mhairihislop/.bin:/Users/mhairihislop/.composer/vendor/bin:/usr/local/opt/ruby/bin:/Users/mhairihislop/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/gems/2.7.0:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/Users/mhairihislop/.fig/bin:/Users/mhairihislop/.local/bin:/Users/mhairihislop/.composer/vendor/bin:/Users/mhairihislop/flutter/bin:/Users/mhairihislop/.composer/vendor/bin
    - SHELL: /usr/local/bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 21800
    - FIG_PARENT: efb30eaf-d4b7-4495-b0c1-82fe1ed82ca4
    - FIG_SET_PARENT: efb30eaf-d4b7-4495-b0c1-82fe1ed82ca4
```

**Comment by drooJohnson** [comment]
+1, experiencing this as well in Ventura 13.1 Beta 2

**Comment by leforgedroid** [comment]
+1, experiencing the same mac os Monterey 12.6

**Comment by hmps** [comment]
I had this too (Ventura 13.0) and was able to fix it. Steps below.

1. Quit Fig
2. Open Privacy → Accessibility pref pane
3. Remove Fig from the list by clicking the "-" button and the bottom of the list
4. Start Fig
5. Give Fig permissions in the pref pane
6. Restart Fig

**Comment by grant0417** [comment]
@Mhairi-Helen @drooJohnson @leforgedroid 

Can you try following the instructions @hmps gave and see if that resolves the issue?

>   1. Quit Fig
>   2. Open Privacy → Accessibility pref pane
>   3. Remove Fig from the list by clicking the "-" button and the bottom of the list
>   4. Start Fig
>   5. Give Fig permissions in the pref pane
>   6. Restart Fig

**Comment by fmonsalvo** [comment]
I'm sorry I'm re-opening this issue, but it does not work for me and it never did. Tried reinstalling, tried disabling and re-enabling, but nothing seems to work.

**Comment by Ezku** [comment]
These steps worked for me (based on https://github.com/withfig/fig/issues/2035#issuecomment-1314630642):

1. `fig doctor` (Accessibility pane opens up) ⇒ `✘ Doctor found errors.`
2. Click on *Fig* in Accessibility; click *-* on the bottom to remove *Fig* from the list
3. `fig restart`; observe *Fig* inserting itself back on the list
4. `fig doctor` ⇒ `✘ Doctor found errors. Please fix them and try again.`
5. enable *Fig* in Accessibility
6. `fig doctor` ⇒ `✔ Everything looks good!`

(MacOS Ventura 13.2.1)

**Comment by dotlouis** [comment]
Worked for me too but if this issue is common, it should be mentioned in the fig interface

**Comment by gimnathperera** [comment]
I had the same issue with `macOS Sonoma 14.1.1 ` and solved this by doing the following.
![image](https://github.com/withfig/fig/assets/55834384/9f287e61-5f5d-4cc3-b8e9-7afe53e161ae)
