### ISSUE TITLE
how to use fig in pycharm

### ISSUE THREAD

**Issue by wnmentau** [withfig/fig#2037]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.1 (22A400)

### Expected behaviour

i can install input method in my macbookpro, my system is mac OS 13.0.1

### Actual behaviour

i can't install input method in my macbookpro, my system is mac OS 13.0.1

### Environment

```yaml
fig-details:
  - 2.7.8
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: pycharm
  - cwd: /Users/dududu/PycharmProjects/python
  - exe-path: /Users/dududu/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 36bd67a3-9054-4d60-9738-281e04ebee5a
    - FIG_HOSTNAME: dudududeMacBook-Pro.local
    - FIG_TERM: 2.7.7
    - PATH: /Users/dududu/.local/share/virtualenvs/python-YLQCN7Ta/bin:/Users/dududu/.local/share/fig/plugins/git-open:/Users/dududu/opt/anaconda3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dududu/.fig/bin:/Users/dududu/.local/bin:/Users/dududu/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 26242
    - FIG_PARENT: 36bd67a3-9054-4d60-9738-281e04ebee5a
    - FIG_SET_PARENT: 36bd67a3-9054-4d60-9738-281e04ebee5a
```

**Comment by mschrage** [comment]
@wnmentau what happens when you try to install the input method? 

Can you run `fig doctor` inside of PyCharm?
