### ISSUE TITLE
fig not working well

### ISSUE THREAD

**Issue by RostyslavDzhohola** [withfig/fig#2039]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.0 (22A380)

### Expected behaviour

Regular prompt option should appear in the same window 

### Actual behaviour

the prompt appears in the different desktop 

### Steps to reproduce

it is default behaviour

### Environment

```yaml
fig-details:
  - 2.7.7
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/Rostyslav
  - exe-path: /Users/Rostyslav/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 5385bd7b-dffd-43b1-be99-9d498e959975
    - FIG_HOSTNAME: Rostyslav-2.local
    - FIG_TERM: 2.7.7
    - PATH: /opt/homebrew/opt/node@16/bin:/Users/Rostyslav/.yarn/bin:/Users/Rostyslav/.config/yarn/global/node_modules/.bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/Rostyslav/.fig/bin:/Users/Rostyslav/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 85615
    - FIG_PARENT: 5385bd7b-dffd-43b1-be99-9d498e959975
    - FIG_SET_PARENT: 5385bd7b-dffd-43b1-be99-9d498e959975
```

**Comment by mschrage** [comment]
Hey @RostyslavDzhohola, make sure you update to the latest version by running `fig update`. This issue should be resolved on v2.8.0.
