### ISSUE TITLE
autocomplete window is shown outside of the terminal in Goland IDE

### ISSUE THREAD

**Issue by vlad-diachenko** [withfig/fig#2051]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.1 (22A400)

### Expected behaviour

autocomplete window is shown inside of the terminal in Goland IDE near the cursor

### Actual behaviour

autocomplete window is shown outside of the terminal in Goland IDE
<img width="778" alt="image" src="https://user-images.githubusercontent.com/82767850/201883010-b7f4474e-f4a9-41b2-9f87-f0bc033bedba.png">

### Steps to reproduce

similar issue but IDE was installed directly without Toolbox

### Environment

```yaml
fig-details:
  - 2.7.8
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: goland
  - cwd: /Users/vdiachenko/projects/loki
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 42f7a6fd-dde9-4ad8-8891-a359ed306c0e
    - FIG_HOSTNAME: Vladyslavs-MacBook-Pro.local
    - FIG_TERM: 2.7.8
    - PATH: <HIDDEN>
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 76318
    - FIG_PARENT: 42f7a6fd-dde9-4ad8-8891-a359ed306c0e
    - FIG_SET_PARENT: 42f7a6fd-dde9-4ad8-8891-a359ed306c0e
```

**Comment by SimFG** [comment]
I have the same problem, and look forward to solving the problem. 🤩

**Comment by grant0417** [comment]
This should be resolved now in Fig 2.10, let me know if you continue to have any issues!

**Comment by SimFG** [comment]
@grant0417 If I has upgraded to the Fig 2.10, what I need to do for the goland. because I try to use the inner terminal in the goland, and I find the fig doesn't work.
![image](https://user-images.githubusercontent.com/21985684/207757936-023ba1e2-4a37-40ff-85ad-d472894713a5.png)
![image](https://user-images.githubusercontent.com/21985684/207757721-ccc6162a-905f-4a3c-91e7-4577a4b8c3eb.png)
![20221215102518_rec_](https://user-images.githubusercontent.com/21985684/207757783-3d14f129-30b2-43db-8ad8-50be9eb612c2.gif)

**Comment by grant0417** [comment]
Are you able to restart Golang? Also try running `fig integrations install intellij`

**Comment by SimFG** [comment]
Yes, I have restarted. And I get an error when running `fig integrations install intellij`.
![image](https://user-images.githubusercontent.com/21985684/207758912-60f906bc-3270-4d02-bd25-662cfcf2f603.png)

**Comment by grant0417** [comment]
Can you run `FIG_LOG_LEVEL=debug fig integrations install intellij`

**Comment by SimFG** [comment]
![image](https://user-images.githubusercontent.com/21985684/207761868-f03c2a7e-f3ab-4a01-a5aa-bc56aa625947.png)

**Comment by grant0417** [comment]
Weird, can you run `fig debug list-intelli-j-variants`

**Comment by SimFG** [comment]
![image](https://user-images.githubusercontent.com/21985684/207763708-be09cad0-6d4e-437d-a30b-bec2fd641a17.png)

**Comment by grant0417** [comment]
Are they installed via toolbox?

**Comment by SimFG** [comment]
No, I install these by downloading the dmg from the official website.

**Comment by grant0417** [comment]
Hmm, not sure how else I can debug this, adding some more logging in the next version to help

**Comment by SimFG** [comment]
Thanks 🤩
