### ISSUE TITLE
fig not working in iterm w/ rosetta2 iterm, while it does in "normal" iterm

### ISSUE THREAD

**Issue by JappaB** [withfig/fig#2053]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.3.0 (21E230)

### Expected behaviour

no autocomplete suggestions

### Actual behaviour

it does run fig doctor though, it recognizes the fig command. Just isn't doing the suggestions.

### Steps to reproduce

I even uninstalled fig, installed it again under my x86 installed version of homebrew from within the rosetta emulated terminal. No success though. It just doesn't do the autocomplete. 

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 12.3.0 (21E230)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/jasper.bakker
  - exe-path: /Users/jasper.bakker/.local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 198af81e-eea6-48a0-9952-615ceca4176c
    - FIG_HOSTNAME: TW7GWL694R
    - FIG_TERM: 2.7.9
    - PATH: /Users/jasper.bakker/.local/bin:/Users/jasper.bakker/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Users/jasper.bakker/.fig/bin:/Users/jasper.bakker/.local/bin:/Users/jasper.bakker/kafka_2.12-3.3.1/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 33285
    - FIG_PARENT: 198af81e-eea6-48a0-9952-615ceca4176c
```

**Comment by grant0417** [comment]
The binaries should be compiled for both architectures, are you able to run `file /Applications/Fig.app/Contents/MacOS/{fig-darwin-universal,fig_desktop,figterm}` and share the output

**Comment by JappaB** [comment]
Strangely enough, it started running again. I have no clue why it stopped working nor why it started working again.
