### ISSUE TITLE
no sudo privs for install on remote for ssh

### ISSUE THREAD

**Issue by ccpalmer** [withfig/fig#2057]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.0 (22A380)

### Expected behaviour

Can't install remote end of `fig ssh` setup as I lack privs there.

### Actual behaviour

priv error

### Steps to reproduce

follow instructions to run curl on remote

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /usr/local/Cellar/bash/5.2.9/bin/bash
  - terminal: iterm
  - cwd: /Users/ccpalmer/Downloads
  - exe-path: /Users/ccpalmer/.local/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /usr/local/bin/bash
    - FIGTERM_SESSION_ID: 84d6ffc1-bffe-4b26-8aa3-02b0bf134b26
    - FIG_WORKFLOWS_KEYBIND: ^f
    - FIG_TERM: 2.7.8
    - TERM: xterm-256color
    - FIG_PID: 99895
    - DISPLAY: /private/tmp/com.apple.launchd.4veQAbxjxV/org.xquartz:0
    - PATH: /Users/ccpalmer/opt/miniconda3/bin:/Users/ccpalmer/opt/miniconda3/condabin:/usr/local/opt/ruby@2.7/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/Users/ccpalmer/.gem/ruby/2.7.0/bin:.:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/ccpalmer/.local/bin:/Users/ccpalmer/.cargo/bin:/Users/ccpalmer/gems/bin:/usr/local/opt/make/libexec/gnubin:/usr/local/mysql/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/ccpalmer/.fig/bin:/Users/ccpalmer/.local/bin:~/Library/Python/2.7/bin:/Developer/NVIDIA/CUDA-8.0/bin
    - FIG_HOSTNAME: Bayou.local
```

**Comment by grant0417** [comment]
This is a limitation right now of our SSH integrations, we are working on providing a root-less option but it isn't available at the moment for autoupdating. You can download the `.tar.xz` directly and place the binaries in `~/.local/bin` but this is not fully supported by us yet: https://repo.fig.io/generic/stable/asset/2.7.8/x86_64/fig_headless.tar.xz
