### ISSUE TITLE
Fig doesn't recognise custom keybindings from bindkey

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#206]
For instance, a user had the '^o' set up to select and execute zsh-autosuggest. After typing `cd[space]` Fig shows suggestions. After hitting the `^o` keybinding, the greyed out suggestion from zsh-autosuggest would be inserted and then go to a new empty line. However, Fig wouldn't register this and the autocomplete window would just be showing at the start of the new empty line

The specific bindkey in question is:

```
bindkey '^o' autosuggest-execute
```

**Comment by mschrage** [comment]
The workaround for this is to create a custom shell function

**Comment by mschrage** [comment]
This should be resolved now that we use `figterm` to determine the edit buffer in ZSH.
