### ISSUE TITLE
Cannot close "Try Fig Pro for Free" window

### ISSUE THREAD

**Issue by ooleem** [withfig/fig#2065]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.5.1 (21G83)

### Expected behaviour

When I click the "Maybe Later" button, it should close the subscription window.

### Actual behaviour

It doesn't close the window.
And when I restart fig program and open it again, the subscription window keep opening.
So I cannot change any other setting.

### Steps to reproduce

I clicked the subscription button from settings.

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/ooleem/Works/peak_aws_cdk
  - exe-path: /Users/ooleem/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 6f69b0da-e325-4d22-b1bd-64e416b95c09
    - FIG_HOSTNAME: macmini.local
    - FIG_TERM: 2.7.9
    - PATH: /Users/ooleem/.nvm/versions/node/v16.18.0/bin:/Users/ooleem/.nvm/versions/node/v16.18.0/bin:/bin:/usr/local/bin:/usr/bin:/Users/ooleem/bin:/Users/ooleem/.nvm/versions/node/v16.18.0/bin:/Users/ooleem/.nvm/versions/node/v16.18.0/bin:/bin:/usr/local/bin:/usr/bin:/Users/ooleem/bin:/Users/ooleem/.nvm/versions/node/v16.18.0/bin:/bin:/usr/local/bin:/usr/bin:/Users/ooleem/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/ooleem/.fig/bin:/Users/ooleem/.local/bin:/Users/ooleem/Library/Python/3.8/bin:/Users/ooleem/Library/Python/3.8/bin:/Users/ooleem/Library/Python/3.8/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 67868
    - FIG_PARENT: 6f69b0da-e325-4d22-b1bd-64e416b95c09
    - FIG_SET_PARENT: 6f69b0da-e325-4d22-b1bd-64e416b95c09
```

**Comment by pix3lize** [comment]
Yeah having the same problem

**Comment by ooleem** [comment]
Somehow it is closed when I reloaded from the right click menu.
It didn't work when I tried it before.

**Comment by mschrage** [comment]
Hey @ooleem @pix3lize! Thanks for reporting. This should be fixed if you quit and restart the app.

**Comment by pix3lize** [comment]
😂 nice, something must have changed. Good job
