### ISSUE TITLE
cd still doesn't working (v2.7.9)

### ISSUE THREAD

**Issue by Grzechu335** [withfig/fig#2068]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.1 (22A400)

### Expected behaviour

Cd autocompletion doesn't work. I tried beta version but it's still doesn't work. I tried reinstall fig, iterm and zsh.

### Actual behaviour

![SCR-20221118-1ty](https://user-images.githubusercontent.com/95315359/202587965-4924ad3b-570b-48d7-b15d-3d3531630af0.png)
![SCR-20221118-1t5](https://user-images.githubusercontent.com/95315359/202587968-1fb5dd4a-e6e3-491a-8b08-91236f615205.png)

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/grzegorz
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 4953e3db-789c-430a-824f-8ae1e7aa4aae
    - FIG_HOSTNAME: MacBook-Air-Grzegorz.local
    - FIG_TERM: 2.7.9
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/grzegorz/.fig/bin:/Users/grzegorz/.local/bin:/Users/grzegorz/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 34146
    - FIG_PARENT: 4953e3db-789c-430a-824f-8ae1e7aa4aae
    - FIG_SET_PARENT: 4953e3db-789c-430a-824f-8ae1e7aa4aae
```

**Comment by mschrage** [comment]
Run `which cd` - you may have it aliases to another command.

**Comment by Grzechu335** [comment]
When i ran `which cd` i got `cd is an alias for __enhancd::cd`.

**Comment by Grzechu335** [comment]
Sometimes it's appear for few seconds and disappear.

**Comment by Grzechu335** [comment]
https://user-images.githubusercontent.com/95315359/202912440-70b34e52-052d-4576-8774-7638b6720d4c.mov

**Comment by Grzechu335** [comment]
Reinstalling plugins helped.
