### ISSUE TITLE
Figterm: No FIGTERM_SESSION_ID

### ISSUE THREAD

**Issue by miheuer** [withfig/fig#2070]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.1 (22A400)

### Expected behaviour

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ PATH contains ~/.fig/bin
✔ Settings Corruption
✔ State Corruption
✔ Fig Integration

Let's make sure Fig is running...
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Daemon diagnostics

Let's see if Fig is in a working state...

### Actual behaviour

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ PATH contains ~/.fig/bin
✔ Settings Corruption
✔ State Corruption
✘ Fig Integration: Figterm is not running in this terminal, please try restarting your terminal
  FIG_TERM=

Let's make sure Fig is running...
✔ Fig is running
✔ Fig socket exists
✘ Daemon: Daemon is not running
✘ Daemon diagnostics: Daemon socket exists but could not connect
  Socket path: /var/tmp/fig/myuser/daemon.socket
  Io(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })

Let's see if Fig is in a working state...
✘ Figterm: No FIGTERM_SESSION_ID
  
   0: No FIGTERM_SESSION_ID
   1: environment variable not found

Location:
   fig_cli/src/cli/doctor.rs:655

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/bash
  - terminal: terminal
  - cwd: /Users/miheuer
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /opt/homebrew/bin/bash
    - TERM: xterm-256color
    - PATH: /Library/Frameworks/Python.framework/Versions/3.11/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/.local/bin:/.fig/bin:/usr/local/munki
```

**Comment by grant0417** [comment]
Hey @miheuer, can you try running `fig integration install dotfiles`
