### ISSUE TITLE
Navigation with arrow keys for auto suggestion is not working

### ISSUE THREAD

**Issue by sampath-paravasthu** [withfig/fig#2076]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.0 (21G115)

### Expected behaviour

Navigation of auto suggestions should work with up and down arrow keys.

Ran `fig doctor`  and `fig restart` too, but still the issue persists.

### Actual behaviour

Navigation is not working with arrow keys. 

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/saparavasthu
  - exe-path: /Users/saparavasthu/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 0c735620-b39b-45bd-a531-b31612ca321b
    - FIG_HOSTNAME: FWS-CHE-LT-4906.local
    - FIG_TERM: 2.7.9
    - PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/saparavasthu/.fig/bin:/Users/saparavasthu/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 5804
    - FIG_PARENT: 0c735620-b39b-45bd-a531-b31612ca321b
    - FIG_SET_PARENT: 0c735620-b39b-45bd-a531-b31612ca321b
```

**Comment by sampath-paravasthu** [comment]
Attaching a gif of the issue

![ezgif com-gif-maker](https://user-images.githubusercontent.com/78723233/202866615-ded4555b-980a-470a-8de2-c7909329defa.gif)

**Comment by grant0417** [comment]
Hey @sampath-paravasthu, could you run `fig debug key-tester` and press down arrow/up arrow and share the output

**Comment by sampath-paravasthu** [comment]
Hi @grant0417 , i was able to resolve it by changing the configs inside `.fig/settings.json`. 

Got it working by changing the values to the below one

```json
{
"autocomplete.keybindings.up": "navigateUp",
"autocomplete.keybindings.down": "navigateDown"
}

```

**Comment by sampath-paravasthu** [comment]
I'm facing the issue again since today morning. Sharing the output of `fig debug key-tester`.
`.fig/settings.json` remains intact though. Fig was logged out automatically and i logged in back today morning and since then this issue has come up.

```
Testing Key Input (use ctrl-d to quit)
3 bytes : "\x1b[A" : [1b, 5b, 41]
3 bytes : "\x1b[B" : [1b, 5b, 42]
3 bytes : "\x1b[A" : [1b, 5b, 41]
3 bytes : "\x1b[A" : [1b, 5b, 41]
3 bytes : "\x1b[B" : [1b, 5b, 42]
3 bytes : "\x1b[B" : [1b, 5b, 42]
1 bytes : "\x01" : [1]

```

**Comment by sampath-paravasthu** [comment]
@grant0417 
Any updates on this? I'm still stuck with this.

**Comment by sampath-paravasthu** [comment]
Hi @mschrage 
Here is the video of debug logs when running fig,
https://user-images.githubusercontent.com/78723233/211164109-5d09a758-e167-4349-9294-d90dcc9e91fd.mp4

**Comment by mschrage** [comment]
Can you record the same video but this time run `FIG_LOG_LEVEL=trace` in the terminal where you'll be typing?

**Comment by sampath-paravasthu** [comment]
@mschrage after running `FIG_LOG_LEVEL=trace`, fig did not work at first place. when i tried to launch it, was getting error (attached screenshot)

![Uploading image.png…]()

**Comment by sampath-paravasthu** [comment]
@mschrage  any updates on the issue ?

**Comment by pettomartino** [comment]
👍 same issue here

**Comment by pettomartino** [comment]
Actually I just realised that `.fig/settings` had this config added for some reason:

```
  "autocomplete.keybindings.down": "ignore",
  "autocomplete.keybindings.up": "ignore",
```

I removed it and it's working now

**Comment by sampath-paravasthu** [comment]
Thank you, it worked !

**Comment by rodperottoni** [comment]
For whatever reason my settings file had the same as @pettomartino. So weird!

**Comment by tanvirrb** [comment]
Facing the same issue. Tried everything from the comment section but nothing is working.

**Comment by Sissing** [comment]
@tanvirrb, try to update some random keystroke settings within the Fig desktop app. Then these `ignore` items + others will probably show up in `.fig/settings `.
