### ISSUE TITLE
bug: Fig uses above 200MB RAM

### ISSUE THREAD

**Issue by connor-circle** [withfig/fig#2079]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS Ventura 13.0.1

### Expected behaviour

 I think when Fig(UI) is closed, its process should be stopped. 

### Actual behaviour

When I don't open up Fig(UI), the RAM consumed by Fig looks normal, at about lower than 100 RAM.

But When Fig(UI) was opened up and then closed. I find that a process called **`https://desktop.fig.io`** run in background and it consumes approximately 120 RAM.
<img width="944" alt="P 2022-11-21 at 12 51 10" src="https://user-images.githubusercontent.com/35033310/202968871-b15d86c4-de88-4cfb-a1c6-9e8dbb53c01c.png">
However I still can use Fig in iTerm terminal with the process stopped, .Fig works perfectly.
<img width="1013" alt="P 2022-11-21 at 13 10 00" src="https://user-images.githubusercontent.com/35033310/202970293-a74466c9-b4ab-4c31-a50a-b5b176b4525c.png">

So Is It normal behaviour of `https://desktop.fig.io` staying at background?

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/connor
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 1bf79759-006d-40b4-96c4-6405fc028735
    - FIG_HOSTNAME: Connor.local
    - FIG_TERM: 2.7.9
    - PATH: /Users/connor/.local/share/fig/plugins/git-open:/Users/connor/.bun/bin:/opt/homebrew/opt/python@3.10/bin/:/Users/connor/.nvm/versions/node/v19.0.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/connor/.fig/bin:/Users/connor/.local/bin:/opt/homebrew/opt/fzf/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 46202
    - FIG_PARENT: 1bf79759-006d-40b4-96c4-6405fc028735
    - FIG_SET_PARENT: 1bf79759-006d-40b4-96c4-6405fc028735
```

**Comment by chaynabors** [comment]
The first time Fig dashboard is opened up, we initialize an OS native web-view. What we've measured is pretty similar to what electron apps consume. If you think there's something specific and actionable that we're doing that would account for this then feel free to let us know. I'd love to really minimize memory usage if we had the bandwidth but the memory we consume is comparable to other apps besides.

Eventually, we will provide a way to use everything but autocomplete with nothing but the CLI.

**Comment by connor-circle** [comment]
> The first time Fig dashboard is opened up, we initialize an OS native web-view. What we've measured is pretty similar to what electron apps consume. If you think there's something specific and actionable that we're doing that would account for this then feel free to let us know. I'd love to really minimize memory usage if we had the bandwidth but the memory we consume is comparable to other apps besides.
> 
> Eventually, we will provide a way to use everything but autocomplete with nothing but the CLI.

Thanks for your detailed explanation. I have no further questions

**Comment by AdrianFahrbach** [comment]
My fig is using a lot more ram than in the screenshots above. For an app that basically always sits in the background this is way too much.
<img width="732" alt="screenshot 2023-03-07 at 10 59 23@2x" src="https://user-images.githubusercontent.com/45072099/223389967-281f3201-a007-4fc0-ad63-0cb6791d8fcc.png">

After a restart of the app I'm down to 40mb again, which is fine for me:
<img width="736" alt="screenshot 2023-03-07 at 11 06 38@2x" src="https://user-images.githubusercontent.com/45072099/223390492-8947537d-5f9c-49e5-81ae-07ffeb2b6634.png">

Maybe there is something going wrong with the web-view? Does the web-view have to be initialized even though 99,9% of the time I'm not even using it?
