### ISSUE TITLE
bug: Workflow not found

### ISSUE THREAD

**Issue by chungweileong94** [withfig/fig#2080]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS 13.0.1 (22A400)

### Expected behaviour

Run the workflow as expected.

### Actual behaviour

It shows "Workflow not found".

### Steps to reproduce

- Run `fig run XXXXX`, and I have make sure the workflow is in the dashboard.
- Then it shows "Workflow not found"

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
  - cores: 4
  - mem: 8.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/chungwei
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: ea854feb-076d-403f-a703-82800a673869
    - FIG_HOSTNAME: White-Room-Chung-Weis-Mac-mini.local
    - FIG_TERM: 2.7.9
    - PATH: /Users/chungwei/.nvm/versions/node/v16.18.1/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/flutter/bin:/Library/Apple/usr/bin:/Users/chungwei/.fig/bin:/Users/chungwei/.local/bin:/Users/chungwei/Library/Android/sdk/emulator:/Users/chungwei/Library/Android/sdk/tools:/Users/chungwei/Library/Android/sdk/tools/bin:/Users/chungwei/Library/Android/sdk/platform-tools
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 59780
    - FIG_PARENT: ea854feb-076d-403f-a703-82800a673869
    - FIG_SET_PARENT: ea854feb-076d-403f-a703-82800a673869
```

**Comment by mschrage** [comment]
If you run `fig run` without any parameters, do you see the workflow appear in the list?

**Comment by chungweileong94** [comment]
@mschrage It's not. However, after I shut down my computer and restarted on the next day, it seems to be fine now. Not sure if this is a bug or it's just my computer is was being slow or something 🤷

**Comment by chungweileong94** [comment]
Off-topic, interestingly, when I run `fig run`, it still shows the list from my old username namespace, it there any way for me to remove those?
![Screenshot 2022-11-22 at 10 31 31 AM](https://user-images.githubusercontent.com/15154097/203205942-417fd6e3-b8e7-4192-a364-3e14c549f0ca.png)

**Comment by chaynabors** [comment]
We've made changes to the caching of scripts which will help a lot here. If at any point you find your scripts out of sync, feel free to run `fig scripts refresh` and that will update your cache manually. If caching is failing, it's possible that your daemon isn't running which can be fixed with `fig doctor`. If you notice any significant issues around this in the future, feel free to reopen to make another issue.
