### ISSUE TITLE
Mixins doesn't show up after adding a new mixin

### ISSUE THREAD

**Issue by chungweileong94** [withfig/fig#2082]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.1 (22A400)

### Expected behaviour

The new mixin should show up after adding a new mixin.

### Actual behaviour

None of the mixins is showing.

### Steps to reproduce

- Add a new mixing from the Fig mixins dashboard
- Test it in the terminal.

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
  - cores: 4
  - mem: 8.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/chungwei
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 4f582bef-2f1b-4420-81b1-4f9d8ddb1919
    - FIG_HOSTNAME: White-Room-Chung-Weis-Mac-mini.local
    - FIG_TERM: 2.7.9
    - PATH: /Users/chungwei/.nvm/versions/node/v16.18.1/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/flutter/bin:/Library/Apple/usr/bin:/Users/chungwei/.fig/bin:/Users/chungwei/.local/bin:/Users/chungwei/Library/Android/sdk/emulator:/Users/chungwei/Library/Android/sdk/tools:/Users/chungwei/Library/Android/sdk/tools/bin:/Users/chungwei/Library/Android/sdk/platform-tools
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 7763
    - FIG_PARENT: 4f582bef-2f1b-4420-81b1-4f9d8ddb1919
    - FIG_SET_PARENT: 4f582bef-2f1b-4420-81b1-4f9d8ddb1919
```

**Comment by grant0417** [comment]
Not too sure what is going on here, can you try restarting Fig and see if they appear?

**Comment by chungweileong94** [comment]
@grant0417 It actually fixed itself after one or two days, I am not sure what's going on, maybe it has something to do with the server side? But feel free to close this issue if necessary.
