### ISSUE TITLE
bug: Install script is producing corrupt sources.list file

### ISSUE THREAD

**Issue by Im-Fran** [withfig/fig#2086]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux fran-popos 6.0.6-76060006-generic #202210290932~1667401208~22.04~d2df702 SMP PREEMPT_DYNAMIC Wed N x86_64 x86_64 x86_64 GNU/Linux

### Expected behaviour

The script should automatically install fig.

### Actual behaviour

Instead is producing a corrupt sources.list file

![image](https://user-images.githubusercontent.com/30329003/203341950-2ab52025-b7ff-4108-bb83-c0d2fae938e9.png)

### Steps to reproduce

Run `curl -fSsL https://repo.fig.io/scripts/install.sh | CHANNEL=nightly bash` in the terminal

**Comment by Im-Fran** [comment]
the issue is inside the function run_root
this was producing a corrupt sources.list file without the channel. After adding CHANNEL="$CHANNEL" to the line 20 and 23 before bash the install script worked.

**Comment by Im-Fran** [comment]
Just want to report that this also happens with headless setup.

**Comment by grant0417** [comment]
This is fixed now, thanks for reporting 👍

**Comment by Im-Fran** [comment]
Awesome!
