### ISSUE TITLE
No context popup while in SSH session

### ISSUE THREAD

**Issue by emilime** [withfig/fig#209]
hello, connecting with my server with iTerm2/ssh with fig installed I see this message after login:

zsh:1: command not found: fig

if I type cd I get:

![image](https://user-images.githubusercontent.com/47943/123226097-a10b6a80-d4d3-11eb-9e11-5133d0a14ecb.png)

and hitting Enter:

![image](https://user-images.githubusercontent.com/47943/123226220-bed8cf80-d4d3-11eb-9787-bbab38a8140f.png)

and fig does not work as expected

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.45 (B218)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.45 (B218) [Italian] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/earmellin/.fig/bin/fig
Accessibility: true
Number of specs: 126
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/earmellin/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/earmellin/.local/bin:/Users/earmellin/.fig/bin:/Users/earmellin/Apache/apache-maven-3.6.3/bin:/Users/earmellin/sviluppo/flutter/bin:/Users/earmellin/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 23808/94B36111-B5BF-41A9-8949-EA2CC6F5275C% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mattschrage** [comment]
Hey @emilime! Thanks for reporting this. It makes sense that the `fig` CLI isn't installed on the remote machine, however we shouldn't be prompting you to run this command while in an SSH session.

Has Fig every worked in an SSH for you? Did Fig work in your local terminal before you connected to a remote machine?

**Comment by emilime** [comment]
Yes fig is non installed on the remote machine, I'm not the server administrator.
Fig has never worked in an SSH session but works in my local terminal.

**Comment by mattschrage** [comment]
I think your best bet for the time being is just turning the SSH integration off. Then Fig should refrain from showing suggestions at all and you won't have this annoying popup!

**Comment by mschrage** [comment]
Closing as stale.
