### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by andresfdel17** [withfig/fig#2092]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 10.15.7 (19H2026)

### Expected behaviour

Work normally

### Actual behaviour

Don´t work

### Steps to reproduce

![Captura de Pantalla 2022-11-24 a la(s) 10 13 44 a  m](https://user-images.githubusercontent.com/53264064/203817435-dcc4a9ae-95dc-4969-85ab-58c5739fb192.png)

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  - cores: 2
  - mem: 16.00 GB
os-info:
  - macOS 10.15.7 (19H2026)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.JBUW0kZGEz/org.xquartz:0
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh
```

**Comment by grant0417** [comment]
Hey @andresfdel17, do you have any more details on what was going on here? The logs don't really help as these are not a real error and will be resolved in the next version.

**Comment by andresfdel17** [comment]
Hi @grant0417 , actually my fig app is working normally. I don´t know what happened. You can close this issue
