### ISSUE TITLE
bug: workflow input type selector not working

### ISSUE THREAD

**Issue by kryonai** [withfig/fig#2094]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Mac 13.0.1

### Expected behaviour

I should be able to select branch names as input value for my workflow. I'm trying to create workflow to delete the branch but I can't create it because `selector` type input is not saving. After refresh I still see the input type as `text`

### Actual behaviour

After refresh I still see the input type as `text`

### Steps to reproduce

Create simple workflow
Add input
choose input type as selector
(Wait for autosave)
Reload the the dashboard
See the input type remain selector or text

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/<username>
  - exe-path: /Users/<username>/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 3f180db7-e141-4b6b-969f-9c617556dffc
    - FIG_HOSTNAME: <username>-MacBook-Air.local
    - FIG_TERM: 2.7.9
    - PATH: /Users/<username>/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/Users/<username>/.fig/bin:/Users/<username>/.local/bin:/Users/<username>/go/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 73995
    - FIG_PARENT: 3f180db7-e141-4b6b-969f-9c617556dffc
    - FIG_SET_PARENT: 3f180db7-e141-4b6b-969f-9c617556dffc
```

**Comment by grant0417** [comment]
Hey @kryonai, can you try to update to the beta with `fig settings app.beta true` and see if it is fixed there, we just did a big rewrite of the workflow interface that resolved a lot of bugs!
