### ISSUE TITLE
fig's popup appears far from the cursor position (iterm2)

### ISSUE THREAD

**Issue by ehahn9** [withfig/fig#2097]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.0 (22A380)

### Expected behaviour

iterm2: fig prompts appear reasonable near the source (e.g. normal fig behavior)

### Actual behaviour

iterm2: fig prompt appears far from the custor:

<img width="1339" alt="Screenshot 2022-11-25 at 5 07 15 AM" src="https://user-images.githubusercontent.com/299134/203992721-7a413399-ab36-4f59-8a39-b894b2c0b0ae.png">

### Steps to reproduce

1. use fig + iterm2 without issue 
2. close iterm2, leave work
3. return the next day, open iterm2
4. use fig + iterm2 WITH issue

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/eric/Dropbox/calcium
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 8bf4bd3c-bd5b-4e2b-8df7-87b64d45e65c
    - FIG_HOSTNAME: Basement-Mac-Studio.local
    - FIG_TERM: 2.7.9
    - PATH: /Users/eric/Dropbox/shell-scripts:/usr/local/sbin:/Users/eric/.nvm/versions/node/v16.17.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/eric/.fig/bin:/Users/eric/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 58021
    - FIG_PARENT: 8bf4bd3c-bd5b-4e2b-8df7-87b64d45e65c
    - FIG_SET_PARENT: 8bf4bd3c-bd5b-4e2b-8df7-87b64d45e65c
```

**Comment by pettomartino** [comment]
Same issue here

`macOS 12.6` and webstorm


<img width="248" alt="image" src="https://user-images.githubusercontent.com/101433/203993823-478b662c-7dfc-4bfd-a93f-4ec2331b994e.png">

**Comment by mschrage** [comment]
@ehahn9 @pettomartino if you navigate to a different window and then go back to iTerm does the autocomplete window get positioned directly.

**Comment by hacker-DOM** [comment]
Same issue here, running Kitty terminal. Works fine in Terminal.app, `fig doctor` gives no warnings.
 
<img width="798" alt="image" src="https://user-images.githubusercontent.com/18601956/205137831-806b1816-680c-4ccc-bff6-1f0abac3b4cd.png">

**Comment by mhuggins7278** [comment]
happening to me as well https://github.com/withfig/fig/issues/2150
