### ISSUE TITLE
fig doctor: "iTerm Bash Integration is out of date." while updated

### ISSUE THREAD

**Issue by cornips** [withfig/fig#2104]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.1 (21G217)

### Expected behaviour

`fig doctor` should not show errors on iTerm Bash Integration when I updated it.

### Actual behaviour

Got an error message about iTerm Bash Integration being out of date:
```console
✘ iTerm bash integration configured: iTerm Bash Integration is out of date. Please update in iTerm's menu by selecting "Install Shell Integration".


✘ Doctor found errors. Please fix them and try again.
```

### Steps to reproduce

- Open iTerm2 (v3.4.18)
- Click on "Install Shell Integration" and follow the steps.
- Restart iTerm
- Run `fig doctor`
- See the error message

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/martijn/
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: db7c2b90-62e8-448d-a2ff-0598c8d09f24
    - FIG_HOSTNAME: Appelflap.local
    - FIG_TERM: 2.7.9
    - PATH: /Users/martijn/.bun/bin:/Users/martijn/Library/pnpm:/Users/martijn/Library/Java/Extensions/maven/bin:/Users/martijn/.yarn/bin:/Users/martijn/.config/yarn/global/node_modules/.bin:/Users/martijn/bin:/usr/local/bin:/Users/martijn/.gem/ruby/2.6.0/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/martijn/.fig/bin:/Users/martijn/.local/bin:/Users/martijn/.yarn/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 41067
    - FIG_PARENT: db7c2b90-62e8-448d-a2ff-0598c8d09f24
    - FIG_SET_PARENT: db7c2b90-62e8-448d-a2ff-0598c8d09f24
```

**Comment by grant0417** [comment]
You need to update your iterm integrations you, you can see how to here: https://iterm2.com/documentation-shell-integration.html

Will include this in the error in future version of Fig!

**Comment by cornips** [comment]
The problem is that I executed this command multiple times.
```
curl -L https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | bash
source ~/.iterm2_shell_integration.zsh
```

and in my ~/.zshrc I can find a line added to it:
```
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
```

But even after this, the response of `fig doctor` is as described.

**Comment by cornips** [comment]
I solved my case by wiping and reinstalling my system.
