### ISSUE TITLE
auto complete tab not working

### ISSUE THREAD

**Issue by mmmurphy4** [withfig/fig#2105]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.0 (21G115)

### Expected behaviour

The arrow keys should allow me to choose between the auto complete options and tab and enter should allow me to follow the auto complete path

### Actual behaviour

None of the keys function at all

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /usr/local/Cellar/bash/5.0.11/bin/bash
  - terminal: iterm
  - cwd: /Users/michaelmurphy
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /usr/local/bin/bash
    - FIGTERM_SESSION_ID: bc050128-b39d-46ea-9492-214e036ecabb
    - FIG_WORKFLOWS_KEYBIND: ^f
    - FIG_TERM: 2.7.9
    - TERM: xterm-256color
    - FIG_PID: 28235
    - PATH: /usr/bin/python3:/Users/michaelmurphy/.sdkman/candidates/java/current/bin:/usr/local/sbin:/Users/michaelmurphy/.jenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/michaelmurphy/.fig/bin:/Users/michaelmurphy/.local/bin:/Users/michaelmurphy/Documents/devStuff/cloud_sql_proxy:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/michaelmurphy/go/bin
    - FIG_HOSTNAME: F0268.local
```

**Comment by mschrage** [comment]
Hey @mmmurphy4! Can you share a screen recording? Also what happens if you open a new terminal session?

**Comment by mmmurphy4** [comment]
The same thing happens if I open up a new terminal.

https://user-images.githubusercontent.com/5483972/204380287-f217b74f-9e23-4c94-9f34-94327a4c5951.mov

**Comment by mmmurphy4** [comment]
hmm, after multiple restarts of fig and turn autocomplete off/on it has decided to work. Unsure why
