### ISSUE TITLE
What does (eval):3: no such file or directory: #!/bin/zsh tell me?

### ISSUE THREAD

**Issue by pitosalas** [withfig/fig#2107]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.1 (22A400)

### Expected behaviour

Whenever my shell launches I get

(eval):3: no such file or directory: #!/bin/zsh

I know I do have a file at /bin/zsh

To debug the problem, how can i find line 3, so that i can determine what shell command is leading to the error?

### Actual behaviour

Whenever my shell launches I get

(eval):3: no such file or directory: #!/bin/zsh

I know I do have a file at /bin/zsh

To debug the problem, how can i find line 3, so that i can determine what shell command is leading to the error?

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/pitosalas/mydev/questionanswer
  - exe-path: /Users/pitosalas/.fig/bin/fig
  - install-method: brew
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.VIRoQMOe6Z/org.xquartz:0
    - FIGTERM_SESSION_ID: 42ea7c0e-87ce-4bb7-81e5-ae3aa891d6ad
    - FIG_HOSTNAME: rpsmacbookpro13.dyn.brandeis.edu
    - FIG_TERM: 2.7.9
    - PATH: /Users/pitosalas/.rbenv/shims:/Users/pitosalas/.pyenv/shims:/Users/pitosalas/.rbenv/shims:/Users/pitosalas/.rbenv/shims:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/pitosalas/.fig/bin:/Users/pitosalas/.local/bin:/usr/local/sbin:/usr/local/sbin:/Users/pitosalas/.rbenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/pitosalas/.rbenv/bin:/opt/homebrew/opt/libpq/bin:/Users/pitosalas/.pyenv/bin:/Users/pitosalas/.rbenv/bin:/usr/local/sbin:/Users/pitosalas/.rbenv/shims:/opt/homebrew/bin:/opt/homebrew/opt/libpq/bin:/Users/pitosalas/.pyenv/bin:/opt/homebrew/sbin:/Users/pitosalas/.rbenv/bin:/usr/local/sbin:/Users/pitosalas/.rbenv/shims:/opt/homebrew/bin:/opt/homebrew/opt/libpq/bin:/Users/pitosalas/.pyenv/bin:/opt/homebrew/sbin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 37141
    - FIG_PARENT: 42ea7c0e-87ce-4bb7-81e5-ae3aa891d6ad
    - FIG_SET_PARENT: 42ea7c0e-87ce-4bb7-81e5-ae3aa891d6ad
```

**Comment by mschrage** [comment]
Have you added anything to your Fig Dotfiles?

**Comment by pitosalas** [comment]
Yes. And I think I figured it out. The actual script file had a weird order and so it was just a metter of reordering. 

Still it would help for debugging if I could somehow see what command was generating the error, i.e. what the line:3 corresponded to.

Anyway, my immediate problem was solved.

Thanks

- Pito
