### ISSUE TITLE
Fig doesn't work when you have multiple SSH connections to the same remote machine

### ISSUE THREAD

**Issue by jakobgilbert99** [withfig/fig#211]
You can check if this issue is affecting you by runing `ps -e -o pid,tty,comm | grep -v "?" | grep 'zsh\|bash\|fish'`

If there is more than 1 unique value in the second column, Fig will unfortunately break.

We are working on resolving this bug ASAP!

**Comment by mschrage** [comment]
We are reworking our SSH integration. See #709
