### ISSUE TITLE
bug: Not working

### ISSUE THREAD

**Issue by andresfdel17** [withfig/fig#2113]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 10.15.7 (19H2026)

### Expected behaviour

Autocomplete working

### Actual behaviour

Not working

### Steps to reproduce

Same case than https://github.com/withfig/fig/issues/2028 
After last update 2.8.0

### Environment

```yaml
fig-details:
  - 2.8.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  - cores: 2
  - mem: 16.00 GB
os-info:
  - macOS 10.15.7 (19H2026)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: iterm
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: brew
  - env-vars:
    - FIG_TERM: 2.8.0
    - FIG_SET_PARENT_CHECK: 1
    - TERM: xterm-256color
    - PATH: /Users/andresfdel13/.nvm/versions/node/v16.17.0/bin:/Users/andresfdel13/google-cloud-sdk/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/andresfdel13/.fig/bin:/Users/andresfdel13/.local/bin:/usr/local/mysql/bin
    - DISPLAY: /private/tmp/com.apple.launchd.EgoIpCBk4s/org.xquartz:0
    - FIG_SET_PARENT: 2cc4ce60-7e06-4092-90a3-e6834d0c9a95
    - FIGTERM_SESSION_ID: 2cc4ce60-7e06-4092-90a3-e6834d0c9a95
    - SHELL: /bin/zsh
    - FIG_PID: 1426
    - FIG_HOSTNAME: andresfdel13-MacBook-Pro.local
```

**Comment by 0xced** [comment]
This problem was fixed in Fig 2.7.9 but it's back in Fig 2.8.0. Getting this error the first time Fig is opened:
<img width="532" src="https://user-images.githubusercontent.com/51363/205154289-b9101209-dbee-4e05-8f3b-ffacfee41432.png">

Reinstalling Fig 2.7.9 is hopeless since the first thing it does upon launching is automatically updating to the latest (currently broken) version. 🙁

**Comment by mschrage** [comment]
@grant0417

**Comment by sowizz** [comment]
Looks like it's fixed in 2.9.0.  @mschrage is there a changelog anywhere?

**Comment by mschrage** [comment]
Yes! https://fig.io/changelog

**Comment by grant0417** [comment]
@andresfdel17 @0xced are you still getting this issue?
