### ISSUE TITLE
Fig isn't working when your remote machine uses an asynchronous prompt (e.g. powerlevel10k or bullet train)

### ISSUE THREAD

**Issue by jakobgilbert99** [withfig/fig#212]
When you are SSHed into a remote machine using an asynchronous prompt (like powerlevel10k, bullet train, starship), there's a chance that Fig won't work as expected. Fortunately, this is an issue we can fix for you via support / one-on-one debugging — email us at hello@fig.io any time!

**Comment by sullivan-sean** [comment]
We have revamped our SSH implementation. Closing outdated issues.
