### ISSUE TITLE
PATH issue with fig doctor

### ISSUE THREAD

**Issue by matthewwf2001** [withfig/fig#2122]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.1 (21G217)

### Expected behaviour

Just installed fig. Expected "fig doctor" to show no issues. 

### Actual behaviour

✘ PATH contains ~/.local/bin: Path does not contain ~/.local/bin

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

### Steps to reproduce

fig restart
fig doctor

### Environment

```yaml
fig-details:
  - 2.9.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/mwfong
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: com.apple.Terminal
    - TERM: xterm-256color
    - SHELL: /bin/zsh
    - PATH: /Library/Frameworks/Python.framework/Versions/3.8/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/dcv:/Users/mwfong/.toolbox/bin
```

**Comment by mschrage** [comment]
Hey @matthewwf2001, this is actually an issue with your shell dotfiles, I think. 

You should have `~/.local/bin` in your `$PATH` but based on the output from `fig diagnostic` it doesn't seem to be there.

Can you share the ~/.zshrc file here?
