### ISSUE TITLE
Add optional input for scripts

### ISSUE THREAD

**Issue by simon-milleto** [withfig/fig#2130]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
Currently it's not possible to have an optional input in a script, if I try to leave an input empty I have the following error
`error: Missing required arguments: INPUT_NAME`.

I wanted to improve the ***git commit and push*** script with a "scope" input which, when it's filled, it's added to the commit message, but it can also be left blank if I don't want a "scope" in my commit message.

It will look like this:

```bash
git add .

if [ -z {{scope}} ]
then
    git commit -m "{{type}}: {{msg}}"

else
    # with scope
    git commit -m "{{type}}({{scope}}): {{msg}}"
fi

git push
```

Is there a way to achieve this with the current script in Fig ? 
Else it would be great to have optional input so we can leave them empty.

## Side note:
If I fill my input with `""`, I do not have error and the script run well (it evaluates the value falsy, which is good), but I have to type `""` in the field

**Comment by chaynabors** [comment]
Optional is now supported. Let me know if you have any issues with it after updating, and create another issue for any feedback/feature requests. Thanks!
