### ISSUE TITLE
PATH contains ~/.local/bin: Path does not contain ~/.local/bin

### ISSUE THREAD

**Issue by cactus-yz** [withfig/fig#2134]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.1 (22A400)

### Expected behaviour

to have no errors found by fig doctor 

### Actual behaviour

youssefzouay@MBA-YZ ~ % fig doctor

✘ PATH contains ~/.local/bin: Path does not contain ~/.local/bin

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

youssefzouay@MBA-YZ ~ % fig issue
✔ Issue Title · PATH contains ~/.local/bin: Path does not contain ~/.local/bin
Heading over to GitHub...
youssefzouay@MBA-YZ ~ % fig issue
✔ Issue Title · PATH contains ~/.local/bin: Path does not contain ~/.local/bin
Heading over to GitHub...
youssefzouay@MBA-YZ ~ %

### Steps to reproduce

fig doctor 
fig restart

### Environment

```yaml
fig-details:
  - 2.9.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/youssefzouay
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /bin/zsh
    - __CFBundleIdentifier: com.googlecode.iterm2
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
    - TERM: xterm-256color
```

**Comment by michaelfransen** [comment]
I have the same issue.

**Comment by grant0417** [comment]
@cactus-yz It looks like your `PATH` does not contain `$HOME/.local/bin`, you may have in your dotfiles somewhere a line that looks like `PATH="..."` but it is not appending to the path like you need to, you can do this with `PATH="...:$PATH". If you share your `.zshrc` and `.zprofile` I can help debug further.

@michaelfransen I suspect the same is true for you, also free to help debug that if you want to share.

**Comment by michaelfransen** [comment]
I confirmed this was the issue for me. I added it my dotfiles and was good. Thanks.

**Comment by cactus-yz** [comment]
It's all fixed now! Thanks for your support.
