### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by BlackOpsCoding** [withfig/fig#2137]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.1 (22A400)

### Expected behaviour

I am getting this error message. Fig Doctor says everything is ok. I restarted, updated, etc. Message is still there. I using Iterm2 and Terminal.

### Actual behaviour

<img width="512" alt="2022-12-08_22-02-38" src="https://user-images.githubusercontent.com/17202409/206627878-24a96cf1-139c-4070-aae8-4c6de6ad44fa.png">

### Steps to reproduce

yes, message won't go away

### Environment

```yaml
fig-details:
  - 2.9.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 24.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/johnmurraymba
  - exe-path: /Users/johnmurraymba/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: b6a819d7-d3a5-4f10-8fbf-5469444b59d9
    - FIG_HOSTNAME: Johns-Air-M2
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.9.0
    - PATH: /opt/anaconda3/bin:/opt/anaconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin:/Users/johnmurraymba/.fig/bin:/Users/johnmurraymba/.local/bin:/Users/johnmurraymba/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 45798
    - FIG_SET_PARENT: b6a819d7-d3a5-4f10-8fbf-5469444b59d9
```

**Comment by mschrage** [comment]
Can you run `fig doctor` and share the output here?

**Comment by BlackOpsCoding** [comment]
Hi Matt,

Here it is...

Thanks,
John

**Comment by grant0417** [comment]
Hey @BlackOpsCoding, there does not appear to be any text here are you able to comment it directly on Github?
