### ISSUE TITLE
cannot paste into scripts text input

### ISSUE THREAD

**Issue by banjo** [withfig/fig#2139]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.4.0 (21F79)

### Expected behaviour

You should be able to paste text into a text input field in a script.

### Actual behaviour

Nothing happens. In this GIF you cannot see me pressing paste because it is out of view, but you can see that it works as usual when pasting out of the script view.

![CleanShot 2022-12-09 at 10 41 17](https://user-images.githubusercontent.com/21983557/206673011-5c053152-7d51-40a2-a636-54d756008966.gif)

### Steps to reproduce

* create a script with a text input
* Try to paste something in to it

### Environment

```yaml
fig-details:
  - 2.9.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.4.0 (21F79)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/antonodman/.ssh
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: bef47da5-d7c2-480e-94b5-35e0547a4a05
    - FIG_HOSTNAME: Antons-MacBook-Pro.local
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.8.0
    - PATH: /opt/homebrew/opt/libpq/bin:/Users/antonodman/Library/Caches/fnm_multishells/92394_1670326540173/bin:/opt/homebrew/opt/libpq/bin:/Users/antonodman/Library/Caches/fnm_multishells/11065_1670173928066/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/antonodman/.fig/bin:/Users/antonodman/.local/bin:/Users/antonodman/code/workspaces:/opt/homebrew/opt/fzf/bin:/Users/antonodman/code/workspaces
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 11006
    - FIG_SET_PARENT: bef47da5-d7c2-480e-94b5-35e0547a4a05
```

**Comment by grant0417** [comment]
This should be fixed now!
