### ISSUE TITLE
Fig doesn't work when you SSH into another machine from an already remote server

### ISSUE THREAD

**Issue by jakobgilbert99** [withfig/fig#214]
Clarify: Fig isn't working when I SSH into one machine, then SSH from that machine to another. This is something we're working on getting fixed but do not currently support. If Fig is causing issues for you in this case, you can disable SSH Integration by navigating to the Fig icon in your menu bar -> Integrations -> unchecking SSH integration.

**Comment by sullivan-sean** [comment]
We have revamped our SSH implementation. Closing outdated issues.
