### ISSUE TITLE
Fig is not working :(

### ISSUE THREAD

**Issue by ArAsHCoding** [withfig/fig#2141]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS Monterey 12.6.1

### Expected behaviour

The Fig was working perfectly, but after updating to the latest version, it is not working on iTerm2 and also works on macOS Terminal on and off.

### Actual behaviour

![Screen Shot 2022-12-09 at 15 26 37](https://user-images.githubusercontent.com/77899651/206790488-fa0aa2d7-f486-4809-b226-bf2936af6746.png)

### Environment

```yaml
fig-details:
  - 2.9.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  - cores: 2
  - mem: 8.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/arash
  - exe-path: /Users/arash/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 39ed3af0-f1fe-4f36-8026-1a046a9d34da
    - FIG_HOSTNAME: ArAsHs-MacBook-Air.local
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.9.0
    - PATH: /Users/arash/.pyenv/shims:/Users/arash/.pyenv/bin:/Users/arash/.nvm/versions/node/v19.0.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/arash/.fig/bin:/Users/arash/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 1093
    - FIG_SET_PARENT: 39ed3af0-f1fe-4f36-8026-1a046a9d34da
```

**Comment by mschrage** [comment]
If you run `fig doctor`, what shows up?

**Comment by ArAsHCoding** [comment]
![Screen Shot 2022-12-10 at 16 21 01](https://user-images.githubusercontent.com/77899651/206875690-0b071e4a-26e4-4127-aa5c-d1b3ab6b3fa6.png)

**Comment by Sneaken** [comment]
me too

**Comment by AIRpwnz** [comment]
I have this problem too

**Comment by emewjin** [comment]
same problem after update latest version 😱

**Comment by Sneaken** [comment]
just reinstall !!! everything is ok !!!

**Comment by gabri3l0** [comment]
Same problem

**Comment by grant0417** [comment]
Anyone on this thread who is experiencing the problem here is a link to schedule a debugging call with me: https://calendly.com/grant-fig/debugging
