### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by AmogDP** [withfig/fig#2142]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.1 (22A400)

### Expected behaviour

To autocomplete commands and show suggestions

### Actual behaviour

Not showing any recommendations,

### Steps to reproduce

Show required autocomplete and greyed out text to complete, Show relevant options drop down bar.

### Environment

```yaml
fig-details:
  - 2.9.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/th3g3ntl3man
  - exe-path: /opt/homebrew/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 8035dddb-2989-405e-bd69-e89e3d010fd4
    - FIG_HOSTNAME: Lyrics-MacBook-Pro
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.9.0
    - PATH: /Users/th3g3ntl3man/opt/anaconda3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/usr/local/go/bin:/usr/local/decred:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/th3g3ntl3man/.cargo/bin:/Users/th3g3ntl3man/.fig/bin:/Users/th3g3ntl3man/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 5800
    - FIG_SET_PARENT: 8035dddb-2989-405e-bd69-e89e3d010fd4
```

**Comment by turannul** [comment]
Same issue reinstalling works for a moment.
fig-details:
  - 2.9.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/turannul
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: aa6b0a4f-6a7e-43aa-9ea1-240d2091a165
    - FIG_HOSTNAME: Turanns-MacBook-Pro.local
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.9.0
    - PATH: /usr/local/opt/libxml2/bin:/usr/local/opt/make/libexec/gnubin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/turannul/.fig/bin:/Users/turannul/.local/bin:
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 11565
    - FIG_SET_PARENT: aa6b0a4f-6a7e-43aa-9ea1-240d2091a165

**Comment by grant0417** [comment]
Anyone on this thread who is experiencing the problem here is a link to schedule a debugging call with me: https://calendly.com/grant-fig/debugging
