### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by christianguettler** [withfig/fig#2144]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.1 (21G217)

### Expected behaviour

solve problems with fig doctor 

### Actual behaviour

"Failed to fix: IO Error: No such file or directory (os error 2)"

### Steps to reproduce

"fig Doctor"

### Environment

```yaml
fig-details:
  - 2.9.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  - cores: 4
  - mem: 32.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /usr/local/Cellar/zsh/5.9/bin/zsh
  - terminal: iterm
  - cwd: /Users/CG
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.jHBNuH2Ogh/org.xquartz:0
    - FIGTERM_SESSION_ID: 626b57a6-18e8-4d1e-98d8-f59b11d5a574
    - FIG_HOSTNAME: i5
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.9.0
    - PATH: /usr/local/Cellar/zplug/2.4.2/bin:/Users/CG/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/Users/CG/.fig/bin:/Users/CG/.local/bin
    - SHELL: /usr/local/bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 1614
    - FIG_SET_PARENT: 626b57a6-18e8-4d1e-98d8-f59b11d5a574
```

**Comment by grant0417** [comment]
Hey @christianguettler, could you share a screenshot or output of `fig doctor --verbose`
