### ISSUE TITLE
WEBSTORM Plugin Error on init

### ISSUE THREAD

**Issue by volo4dev** [withfig/fig#2145]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.0 (21G115)

### Expected behaviour

I want to open web storm without any errors from Fig.io.

### Actual behaviour

1. Open the Webstorm project
2. Get an error
<img width="325" alt="image" src="https://user-images.githubusercontent.com/98762181/207088590-a1555047-ec31-49e4-a971-7342e2080e91.png">

### Steps to reproduce

1. Open the Webstorm project
2. Get an error

### Environment

```yaml
fig-details:
  - 2.9.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: WebStorm
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 4e0e618d-4527-40aa-9abf-fe096975bcaa
    - FIG_HOSTNAME: MacBook-Pro-Vladimir.local
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.9.0
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.WebStorm
    - FIG_PID: 24049
    - FIG_SET_PARENT: 4e0e618d-4527-40aa-9abf-fe096975bcaa
```

**Comment by grant0417** [comment]
This should be resolved now in Fig 2.10, let me know if you continue to have any issues!

**Comment by Strajk** [comment]
I had the same error so I wanted to re-install the plugin.
I uninstalled it, but now I cannot find it anymore on the plugin store

![Screen 2022-12-15 at 12 03 12](https://user-images.githubusercontent.com/697301/207843472-de75d8a1-381d-4617-8ba3-8becd6853492.png)

And it's not possible to install neither from Fig Dashboard

![Screen 2022-12-15 at 12 04 52](https://user-images.githubusercontent.com/697301/207843566-075a75d8-af83-4be3-8945-3181309fe67b.png)

**Comment by grant0417** [comment]
We actually bundle it with the Fig application, you can install it with `fig integrations install intellij`

**Comment by Strajk** [comment]
@grant0417 thx 🙏 

![Screen 2022-12-16 at 11 05 27](https://user-images.githubusercontent.com/697301/208074524-52625884-0b6f-4a26-a888-6e9ab23a721d.png)

**Comment by volo4dev** [comment]
@grant0417 Looks like that my problem is solved. Thanks!

But when I entered the command `fig integrations install intellij` I got the new one 
<img width="342" alt="image" src="https://user-images.githubusercontent.com/98762181/208087986-e4916f89-6e84-446b-aaf9-6f8e8dbee81d.png">
