### ISSUE TITLE
Auto complete widget is not aligned on the cursor

### ISSUE THREAD

**Issue by Sagar-Chudamani** [withfig/fig#2147]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.1 (22A400)

### Expected behaviour

The input widget to appear over the cursor

### Actual behaviour

The autocomplete widget is aligned at the beginning of the screen

### Environment

```yaml
fig-details:
  - 2.9.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/sagarchudamani/Oslash/0/packages/core
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: a40947a7-84e1-4fed-a85d-0a8bec8c8cb7
    - FIG_HOSTNAME: Sagar-Chudamanis-MacBook-Pro-K99V5X2WDL.local
    - FIG_PID: 52774
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.9.0
    - PATH: /opt/homebrew/opt/openssl@3/bin:/Users/sagarchudamani/.nvm/versions/node/v16.15.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/opt/openssl@3/bin:/Users/sagarchudamani/.nvm/versions/node/v16.15.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/sagarchudamani/.cargo/bin:/Users/sagarchudamani/.fig/bin:/Users/sagarchudamani/.local/bin:
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/sagarchudamani
    - __CFBundleIdentifier: com.microsoft.VSCode
    - FIG_SET_PARENT: a40947a7-84e1-4fed-a85d-0a8bec8c8cb7
```

**Comment by grant0417** [comment]
Hey @Sagar-Chudamani what terminal are you using and could you share a video of the behavior?

**Comment by ashrafuzzaman** [comment]
![image](https://user-images.githubusercontent.com/46159/219405567-a2c1e874-6d4a-43c3-9c7d-e7a155eab66d.png)
I am using pop os 22.04 and and fig_cli version 2.14.2
