### ISSUE TITLE
IO Error with SSH integration

### ISSUE THREAD

**Issue by slugiscool99** [withfig/fig#2148]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.0 (21G115)

### Expected behaviour

Expected `fig doctor` to succeed

### Actual behaviour

Got this error when running `fig doctor --verbose`

```
✘ SSH integration: Integration not installed: /Users/adam/.ssh/config does not exist.
  
   0: Integration not installed: /Users/adam/.ssh/config does not exist.

Location:
   fig_cli/src/cli/doctor.rs:1234

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

```

### Steps to reproduce

`fig doctor`

### Environment

```yaml
fig-details:
  - 2.10.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/adam/Documents/GitHub/VibeCheck
  - exe-path: /Users/adam/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: e6b2256c-b594-40cf-92fd-c004e252884e
    - FIG_HOSTNAME: Adams-MBP.hsd1.ca.comcast.net
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.10.1
    - PATH: /Users/adam/.rvm/gems/ruby-3.1.1/bin:/Users/adam/.rvm/gems/ruby-3.1.1@global/bin:/Users/adam/.rvm/rubies/ruby-3.1.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/adam/.fig/bin:/Users/adam/.local/bin:/Users/adam/.rvm/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 58696
    - FIG_SET_PARENT: e6b2256c-b594-40cf-92fd-c004e252884e
```

**Comment by grant0417** [comment]
We install a ssh integration by default now, can you try running `fig integrations install ssh`

**Comment by sidhanthp** [comment]
Hey @grant0417, I just ran into the same issue, tried running `fig integrations install ssh`, and got this as the output

```bash
➜  ~ fig integrations install ssh
error: IO Error: No such file or directory (os error 2)
```

**Comment by Subho-codegeek** [comment]
> 

I'm having this same issue as well

**Comment by m600x** [comment]
The issue is that on a fresh installation, the `.ssh` folder doesn't exist. You can fix it using `mkdir -p ~/.ssh`

Such as:
```
m600@MBP ~ % fig integrations install ssh
error: IO Error: No such file or directory (os error 2)

m600@MBP ~ % mkdir -p ~/.ssh

m600@MBP ~ % fig integrations install ssh
Installed!

m600@MBP ~ % fig doctor
✔ Everything looks good!
  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!
`
``

**Comment by hidragos** [comment]
> The issue is that on a fresh installation, the `.ssh` folder doesn't exist. You can fix it using `mkdir -p ~/.ssh`
> 
> Such as:
> 
> ```
> m600@MBP ~ % fig integrations install ssh
> error: IO Error: No such file or directory (os error 2)
> 
> m600@MBP ~ % mkdir -p ~/.ssh
> 
> m600@MBP ~ % fig integrations install ssh
> Installed!
> 
> m600@MBP ~ % fig doctor
> ✔ Everything looks good!
>   Fig still not working? Run fig issue to let us know!
>   Or, email us at hello@fig.io!
> ```

Running `mkdir -p ~/.ssh` did work for me. Thank you!
