### ISSUE TITLE
bug: Error: IO Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Hugo-Pereira-98** [withfig/fig#2152]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS Ventura 13.1

### Expected behaviour

Installation should work smoothly

### Actual behaviour

I am getting an error in the begging and it is not installing. Fig is asking me to open an issue on github

**Comment by grant0417** [comment]
Hey @Hugo-Pereira-98 can you share the output of `fig doctor --verbose`

**Comment by Hugo-Pereira-98** [comment]
I just uninstalled and installed again and it worked. Closing issue right now. Thx
