### ISSUE TITLE
ShellHistory app does not work with Fig

### ISSUE THREAD

**Issue by cheuk-cheng** [withfig/fig#2161]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.0

### Expected behaviour

ShellHistory can save typed command lines in zsh and bash shell in the app's history log.

### Actual behaviour

When invoking bash shell by opening a new terminal I see a "shhist could not parse inserted string" error and no run command lines are saved by ShellHistory app.

### Steps to reproduce

Install ShellHistory app by Denis Gladkikh in macOS AppStore when Fig is running.  Then open a new bash shell session and enter some command lines.  Launch ShellHistory app and no recently run command lines are shown.

### Environment

```yaml
fig-details:
  - 2.9.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 13.3.0
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /private/var/tmp
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: d80c3d6a-cfbd-4e50-bb6a-df91038dc113
    - FIG_HOSTNAME: MacBook-Pro-CC.local
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.9.0
    - PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/Users/cc/.fig/bin:/Users/cc/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Applications/ShellHistory.app/Contents/Helpers:/Users/cc/.resh/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 9500
    - FIG_SET_PARENT: d80c3d6a-cfbd-4e50-bb6a-df91038dc113
```

**Comment by grant0417** [comment]
Hey @cheuk-cheng, did you make sure to install the `shhist` integrations ShellHistory provides? If you already did I might check with them to see what the issues is since we don't do anything that should affect your history.

**Comment by cheuk-cheng** [comment]
Hi @grant0417 Yes.  I had installed the integration shell script from ShellHistory app.
