### ISSUE TITLE
SSH integration: Integration not installed:

### ISSUE THREAD

**Issue by Sulcalibur** [withfig/fig#2163]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

✘ SSH integration: Integration not installed: /Users/{{username}}/.ssh/config does not exist.
Attempting to fix automatically...
Failed to fix: IO Error: No such file or directory (os error 2)

✘ Doctor found errors. Please fix them and try again.

### Actual behaviour

✘ SSH integration: Integration not installed: /Users/suleimanleadbitter/.ssh/config does not exist.
Attempting to fix automatically...
Failed to fix: IO Error: No such file or directory (os error 2)

✘ Doctor found errors. Please fix them and try again.

### Steps to reproduce

When running `fig doctor`

### Environment

```yaml
fig-details:
  - 2.10.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/suleimanleadbitter
  - exe-path: /Users/suleimanleadbitter/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 985e80be-4679-447a-bfe4-da15712f0ba6
    - FIG_HOSTNAME: Suleimans-MBP.broadband
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.10.1
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/suleimanleadbitter/.fig/bin:/Users/suleimanleadbitter/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: co.zeit.hyper
    - FIG_PID: 10136
    - FIG_SET_PARENT: 985e80be-4679-447a-bfe4-da15712f0ba6
```

**Comment by grant0417** [comment]
I believe the solution is running:

```bash
mkdir -p ~/.ssh && fig integrations install ssh
```
