### ISSUE TITLE
Error: Failed setting user_id: settings file is not a json object

### ISSUE THREAD

**Issue by imjennyli** [withfig/fig#2167]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.0 (21G115)

### Expected behaviour

I expect to be able to use fig

### Actual behaviour

fig doctor

✘ PATH and PseudoTerminal PATH match: Could not get PseudoTerminal PATH
  settings file is not a json object

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

settings.json is a json object, and I've also tried renaming it to settings.json.bak to see if it would create a blank settings object

### Environment

```yaml
fig-details:
  - 2.7.1-beta.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/bash
  - terminal: iterm
  - cwd: /Users/jennyli/dev/Server
  - exe-path: /Users/jennyli/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_PID: 2505
    - TERM: xterm-256color
    - SHELL: /bin/bash
    - FIGTERM_SESSION_ID: 54878020-573a-4edf-8914-598055c303ea
    - PATH: /usr/local/share/dotnet/x64/:/opt/homebrew/opt/mysql@5.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/jennyli/.fig/bin:/Users/jennyli/.local/bin
    - FIG_HOSTNAME: jennyli-mojo
    - FIG_WORKFLOWS_KEYBIND: ^f
    - FIG_TERM: 2.7.1-beta.1
```

**Comment by grant0417** [comment]
Hey @imjennyli, looks like you are running quite an old version of Fig. 

Can you reinstall and this should be resolved.

**Comment by imjennyli** [comment]
@grant0417 cool, will give that a try. I see you are on brew now so I removed my installation and am running brew install fig 🤞🏽

**Comment by grant0417** [comment]
Going to close this, let us know if you have any other issues!
