### ISSUE TITLE
bug: Cannot change and execute scripts command

### ISSUE THREAD

**Issue by Blinks44** [withfig/fig#2168]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6

### Expected behaviour

Allow to change script command and execute script with ```fig run <script>```

### Actual behaviour

![Recording 2022-12-21 at 11 10 38](https://user-images.githubusercontent.com/8570193/208856251-b89ef343-7d75-478f-a633-e0657f2f94f4.gif)

![2022-12-21_11-22-06](https://user-images.githubusercontent.com/8570193/208856341-bb21a24b-384c-4e85-9274-13dd44f141a7.png)

Tried to reinstall fig, nothing changed

### Environment

```yaml
fig-details:
  - 2.10.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  - cores: 2
  - mem: 8.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /bin/zsh
  - terminal: <unknown>
  - cwd: /Users/sergejvrenev/Desktop
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - PATH: /usr/local/opt/php/sbin:/usr/local/opt/php/bin:/usr/local/opt/node@18/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sergejvrenev/.fig/bin:/Users/sergejvrenev/.local/bin:/Users/sergejvrenev/.composer/vendor/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: dev.warp.Warp-Stable
    - FIG_SET_PARENT_CHECK: 1
    - FIG_PID: 4595
    - FIG_SET_PARENT:
```

**Comment by grant0417** [comment]
@mschrage @parssak 

Looks like there is an issue with change name that causes spaces to get added, this will never be able to get invoked due to how the script names are parsed in the CLI

**Comment by Blinks44** [comment]
> Looks like there is an issue with change name that causes spaces to get added, this will never be able to get invoked due to how the script names are parsed in the CLI

it doesn't change name at all, i can change name to ```foobar```, but name still remains with original...

**Comment by chaynabors** [comment]
This is fixed. Let me know if you still have this issue.
