### ISSUE TITLE
ssh integration

### ISSUE THREAD

**Issue by lazharkarem** [withfig/fig#2173]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

ssh integration

### Actual behaviour

✘ SSH integration: Integration not installed: /Users/admin/.ssh/config does not exist.
Attempting to fix automatically...
Failed to fix: IO Error: No such file or directory (os error 2)

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

### Environment

```yaml
fig-details:
  - 2.10.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  - cores: 2
  - mem: 8.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/admin
  - exe-path: /Users/admin/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 710bd664-93cd-46aa-bfcf-64ca440fe510
    - FIG_HOSTNAME: MacBook-Air-de-admin.local
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.10.1
    - PATH: /Users/admin/Documents/tools/flutter_SDK/bin:/usr/local/opt/openjdk@11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/admin/.fig/bin:/Users/admin/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 55612
    - FIG_SET_PARENT: 710bd664-93cd-46aa-bfcf-64ca440fe510
```

**Comment by grant0417** [comment]
Hey @lazharkarem, the solution here is:

```bash
mkdir ~/.ssh && fig integration install ssh
```

This should be resolved in 2.11 when it is release as well

**Comment by lazharkarem** [comment]
Thanks

**Comment by grant0417** [comment]
2.11 is live, this issues should be resolved
