### ISSUE TITLE
Can't fix Fig installation / Doesn't uninstall or reinstall

### ISSUE THREAD

**Issue by ferrreira** [withfig/fig#2174]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.0 (21G115)

### Expected behaviour

I expected Fig to NOT show me a "Fix installation issues" message all the time.

### Actual behaviour

It stopped working suddenly, and the proposed solutions for fixing the problem (install shell integrations / run fig doctor / run fig restart) don't work. It also shows me an error when I try to uninstall it via brew, or reinstall it.

### Steps to reproduce

- Open Fig > Fix Installation issues > Install Shell Integrations > Install: Doesn't work.
- Run fig doctor > Nothing changes.
- Run fig restart > Nothing changes
- Run brew uninstall fig > Error: error: IO Error: Permission denied (os error 13)
Error: Failure while executing; `/Applications/Fig.app/Contents/MacOS/fig-darwin-universal app uninstall` exited with 1. Here's the output:
error: IO Error: Permission denied (os error 13)

### Environment

```yaml
fig-details:
  - 2.10.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/andre
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 073198b6-c1b7-40ad-82e9-1fa062f4a643
    - FIG_HOSTNAME: AndreFerreiraMBP.local
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.10.1
    - PATH: /Users/andre/.nvm/versions/node/v16.15.0/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/Users/andre/.fig/bin:/Users/andre/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - DISPLAY: :0
    - FIG_PID: 53562
    - FIG_SET_PARENT: 073198b6-c1b7-40ad-82e9-1fa062f4a643
```

**Comment by grant0417** [comment]
Hey @ferrreira, seems like there might be an issue with the ownership or permissions of some of your dotfiles.

I would recommend running the following and sharing the output:
- `ls -al $HOME`
- `fig integration install dotfiles`

**Comment by Tetonne** [comment]
brew uninstall --cask fig
==> Uninstalling Cask fig
==> Removing launchctl service io.fig.launcher
Password:
==> Removing launchctl service io.fig.uninstall
==> Removing launchctl service io.fig.dotfiles-daemon
==> Running uninstall script /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
Error: uninstall script /Applications/Fig.app/Contents/MacOS/fig-darwin-universal does not exist.



Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  fig

**Comment by beanlee** [comment]
> brew uninstall --cask fig ==> Uninstalling Cask fig ==> Removing launchctl service io.fig.launcher Password: ==> Removing launchctl service io.fig.uninstall ==> Removing launchctl service io.fig.dotfiles-daemon ==> Running uninstall script /Applications/Fig.app/Contents/MacOS/fig-darwin-universal Error: uninstall script /Applications/Fig.app/Contents/MacOS/fig-darwin-universal does not exist.
> 
> Warning: Some installed casks are deprecated or disabled. You should find replacements for the following casks: fig

same to u

**Comment by niceguydave** [comment]
> brew uninstall --cask fig ==> Uninstalling Cask fig ==> Removing launchctl service io.fig.launcher Password: ==> Removing launchctl service io.fig.uninstall ==> Removing launchctl service io.fig.dotfiles-daemon ==> Running uninstall script /Applications/Fig.app/Contents/MacOS/fig-darwin-universal Error: uninstall script /Applications/Fig.app/Contents/MacOS/fig-darwin-universal does not exist.
> 
> Warning: Some installed casks are deprecated or disabled. You should find replacements for the following casks: fig

Hi @Tetonne.

I was in a similar situation to you.  I'd upgraded from the now deprecated `fig` to `Q` and my Homebrew install was constantly telling me that I needed to find a replacement for the `fig` cask (which I'd uninstalled)

I've just used the instructions at https://www.youtube.com/watch?v=knsbdncmWTg to help me get my machine back to stop telling me to find a replacement for `fig`.  **This isn't tested code, so please use at your own risk**.

In brief, I'm using a Silicon M2 chip, and the following helped me to stop the fig warning from appearing:
```shell
rm -rf /opt/homebrew/Caskroom/fig/
```
On removing this directory, I no longer get warned about finding a replacement for my non-existent `fig` application.

Again, please use with care.
