### ISSUE TITLE
Pasting and then hitting tab makes fig think there's nothing present

### ISSUE THREAD

**Issue by polds** [withfig/fig#2175]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.1 (21G217)

### Expected behaviour

I expect to be able to paste, hit tab, proceed with input and for fig to pick up the input.

NOTE: If I hit space and backspace or something, fig notices.

### Actual behaviour

Hitting tab with pasted content to move to the next field causes fig to think the field is missing.

![text-input](https://user-images.githubusercontent.com/2372558/209370597-594945b4-e643-4de3-8cc1-72a94555e5db.gif)

### Steps to reproduce

- Create a script with at least two inputs, the text input should not necessarily be the last field
- Paste text into the field and hit tab to go to the next field
- eventually hit enter, see it fail due to missing text

### Environment

```yaml
fig-details:
  - 2.10.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/oldpeter
  - exe-path: /Users/oldpeter/.local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: d1f7dc22-c977-4257-992f-a2e3aa2a4a58
    - FIG_HOSTNAME: <redacted>
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.10.1-beta.0
    - PATH: /Users/oldpeter/go/bin:/Users/oldpeter/.local/bin:/Users/oldpeter/Library/Python/3.8/bin:/Users/oldpeter/.toolbox/bin:/Users/oldpeter/go/bin:/Users/oldpeter/.local/bin:/Users/oldpeter/Library/Python/3.8/bin:/Users/oldpeter/.toolbox/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/oldpeter/.fig/bin:/Users/oldpeter/.local/bin:/usr/local/bin:/Users/oldpeter/.fig/bin:/Users/oldpeter/.toolbox/bin:/Users/oldpeter/Library/Python/3.8/bin:/Users/oldpeter/.local/bin:/Users/oldpeter/go/bin:/usr/local/go/bin:/Users/oldpeter/.toolbox/bin:/Users/oldpeter/Library/Python/3.8/bin:/Users/oldpeter/go/bin:/Users/oldpeter/.local/bin:/Users/oldpeter/.fig/bin:/Users/oldpeter/.toolbox/bin:/Users/oldpeter/Library/Python/3.8/bin:/Users/oldpeter/.local/bin:/Users/oldpeter/go/bin:/usr/local/go/bin:/Users/oldpeter/.toolbox/bin:/Users/oldpeter/Library/Python/3.8/bin:/Users/oldpeter/go/bin:/Users/oldpeter/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 19829
    - FIG_SET_PARENT: d1f7dc22-c977-4257-992f-a2e3aa2a4a58
```

**Comment by grant0417** [comment]
@chaynabors are you able to investigate this?

**Comment by chaynabors** [comment]
Already know what this would be. Will get a fix on nightly by Monday. For now, removing and inserting a space at the end of pasted content will update the state.

**Comment by chaynabors** [comment]
This is fixed. Let me know if you still have this issue after updating.
