### ISSUE TITLE
command not found: starship on launch or terminal session

### ISSUE THREAD

**Issue by dwhoban** [withfig/fig#2185]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

Starship theme loads correctly via appropriate eval script for each shell when opening a new terminal session (opening the app, window or tab)

### Actual behaviour

When zsh is set to be the default shell, `(eval):4: command not found: starship` is returned and then a default prompt is returned.

When fish is used to be the default shell the following is returned: 
``` shell
fish: Unknown command: starship
~/.config/fish/conf.d/99_fig_post.fish (line 4):
  starship init fish | source
  ^
from sourcing file ~/.config/fish/conf.d/99_fig_post.fish
	called on line 246 of file /opt/homebrew/Cellar/fish/3.5.1/share/fish/config.fish
from sourcing file /opt/homebrew/Cellar/fish/3.5.1/share/fish/config.fish
	called during startup
```

However running `which starship` correct returns `/opt/homebrew/bin/starship`

Running fig source correctly loads the terminal.

### Steps to reproduce

1. Install `starship, fish, zsh, bash` via homebrew
3. add `eval "$(starship init bash)"` and limit to bash
4. add `eval "$(starship init zsh)"` and limit to zsh
5. add `starship init fish | source` and limit to fish
6. Open new terminal session
7. run `fig source`

### Environment

```yaml
fig-details:
  - 2.10.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /opt/homebrew/Cellar/zsh/5.9/bin/zsh
  - terminal: iterm
  - cwd: /Users/dan
  - exe-path: /Users/dan/.fig/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: a0397a8f-0c51-44c1-adea-09ebc3f84e9d
    - FIG_HOSTNAME: Dans-MacBook-Air.local
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.10.1
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dan/.fig/bin:/Users/dan/.local/bin:/opt/homebrew/bin:/Users/dan/.config/op/plugins.sh
    - SHELL: /opt/homebrew/bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 2523
    - FIG_SET_PARENT: a0397a8f-0c51-44c1-adea-09ebc3f84e9d
```

**Comment by dwhoban** [comment]
Fish version of `fig diagnostics`

```
fig-details:
  - 2.10.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /opt/homebrew/Cellar/fish/3.5.1/bin/fish
  - terminal: iterm
  - cwd: /Users/dan
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_PID: 3690
    - FIG_HOSTNAME: Dans-MacBook-Air.local
    - FIG_TERM: 2.10.1
    - FIG_SET_PARENT: w0t0p0:C9994345-35BD-47B6-BD10-4E577E9ECC45
    - SHELL: /opt/homebrew/bin/fish
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIGTERM_SESSION_ID: 95d199e9-dda6-476b-8bbc-f28fa08c5883
    - FIG_PARENT:
    - TERM: xterm-256color
    - PATH: /opt/homebrew/bin:/opt/homebrew/bin/starship:/Users/dan/.config/op/plugins.sh:/opt/homebrew/bin/:/opt/homebrew/bin/starship:/Users/dan/.config/op/plugins.sh:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dan/.fig/bin:/Users/dan/.local/bin
```

**Comment by basola21** [comment]
having the same problem here 

<img width="666" alt="Screenshot 2023-04-01 at 11 40 55 PM" src="https://user-images.githubusercontent.com/63477635/229315375-db002918-27a6-44e3-985b-7cb4d3046068.png">

even though I think I have the correct command in the correct place in my .bashrc file 

<img width="686" alt="Screenshot 2023-04-01 at 11 42 40 PM" src="https://user-images.githubusercontent.com/63477635/229315453-97f80c2e-c7cb-498f-87aa-f2cd92881b99.png">

note : I am new to this if there is something I am doing wrong please correct me and if it is truly a bug I would be happy if there is any kind of help I can offer.

**Comment by looterz** [comment]
Same issue on macOS Ventura 13.3.1, only fix I found was moving my startup commands and aliases from `.zprofile` to `.zshrc` .

**Comment by basola21** [comment]
yep changing the startup commands from `.bashrc` to `.zshrc` worked thanks

**Comment by devdthird** [comment]
I faced this issue when I installed starship from bash and then switched to zsh and tried to update .zshrc with eval line.
Issue got fixed after installing from zsh.

**Comment by mavandeh** [comment]
Had this issue in bash. Installed in ~/.local/bin, and the export PATH statement in .bash_profile was executed AFTER the source .bashrc line in .bash_profile. Moving the export PATH statement above source .bashrc fixed it for me. My circumstances may be unique, but it's a good basic spot to check, easier than changing shells.

**Comment by KRIISHSHARMA** [comment]
- > had the same problem
- > wanted to delete starship from system but even after removing starhip along with all dependencies , 'starship:command not found' kept on showing on opening the terminal 
-> deleting the eval "$(starship init bash)" from .bashrc file worked for me

**Comment by jonas-frey** [comment]
I had the same problem, and it turned out that the `eval "$(starship init bash)"` was in my `.bashrc` before the command adding the `brew` binaries to the path. So just move `eval "$(starship init bash)"` to the end of the file and it should be fine!
