### ISSUE TITLE
Path not being set for MacOS

### ISSUE THREAD

**Issue by jay-bourland** [withfig/fig#2186]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.2 (21G320)

### Expected behaviour

I expect to fig to initialize when I start a new shell

### Actual behaviour

Fig is not starting up properly in Terminal or Hyper. The pre and post scripts are referenced in the .zprofile and .zshrcI get the following when I run in Hyper:
➜  ~ [[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && echo "found it"
found it
but fig doctor reports
➜  ~ fig doctor

✘ PATH contains ~/.local/bin: Path does not contain ~/.local/bin

The PATH variable is
➜  ~ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

### Steps to reproduce

Start a new shell

### Environment

```yaml
fig-details:
  - 2.10.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  - cores: 4
  - mem: 32.00 GB
os-info:
  - macOS 12.6.2 (21G320)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/jay
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: co.zeit.hyper
    - PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
```

**Comment by grant0417** [comment]
Hey @jay-bourland, could you share your `.zshrc`, you are likely overriding your `PATH` at some point in it.

**Comment by jay-bourland** [comment]
Hey Grant - thanks for getting back to me. I just figured this out this morning. The .local/bin/fig executable was symlinked to an old installation that didn't exist. I deleted the .local directory and re-installed, and everything is working now.
