### ISSUE TITLE
Autocomplete not showing

### ISSUE THREAD

**Issue by augustocheme** [withfig/fig#2188]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.2.1 (21D62)

### Expected behaviour

Start typing and autocomplete should popup

### Actual behaviour

Everything was running fine but out of the blue autocomplete stopped working.

<img width="693" alt="Screen Shot 2022-12-29 at 14 27 56" src="https://user-images.githubusercontent.com/5859963/209988231-1a5a654d-3ea7-4f12-89ae-8f7ac10e3759.png">

### Environment

```yaml
fig-details:
  - 2.10.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 12.2.1 (21D62)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/augustocheme/Developer
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: ebb90fe0-5910-4175-8ddf-cfc01a5a8d1a
    - FIG_HOSTNAME: Augustos-MacBook-Pro.local
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.10.1
    - PATH: /Users/augustocheme/.nvm/versions/node/v19.2.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/augustocheme/.fig/bin:/Users/augustocheme/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 8873
    - FIG_SET_PARENT: ebb90fe0-5910-4175-8ddf-cfc01a5a8d1a
```

**Comment by augustocheme** [comment]
Removing all plugins and reinstalling made it work ✨

**Comment by nevertoday** [comment]
so , remove all ohmyzsh plugin ?

**Comment by codrkoaz** [comment]
yes remove everything that you installed and completely close your terminal you're using see if it works. if it does install everything back one by one.

**Comment by danndz** [comment]
Hello, the completion works after removing all plugins. However, the issue came back when I reinstalled them.

**Comment by codrkoaz** [comment]
it might one of the plugins that's messing up with your problem i found out my issue was from one plugin. These are the plugin I have running and I haven't had that problem anymore.
![image](https://user-images.githubusercontent.com/51058620/233871302-a472d852-ab64-47f1-98fc-cbf89f1c607e.png)
