### ISSUE TITLE
sizing issue

### ISSUE THREAD

**Issue by alenguler** [withfig/fig#2197]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.2.1 (21D62)

### Expected behaviour

fig without resizing issue.

### Actual behaviour

Sometimes, when I resize my terminal (iTerm) my cursor is showed somewhere is not actual place of it. You can see below video, cursor is not its own place.

### Steps to reproduce

Here is me bash_profile:

# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/bash_profile.pre.bash" ]] && builtin source "$HOME/.fig/shell/bash_profile.pre.bash”

# Fig post block. Keep at the bottom of this file.
[[ -f "[$HOME/.fig/shell/bash_profile.post.bash](http://%24home/.fig/shell/bash_profile.post.bash)" ]] && builtin source "[$HOME/.fig/shell/bash_profile.post.bash](http://%24home/.fig/shell/bash_profile.post.bash)"

### Environment

```yaml
fig-details:
  - 2.10.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 12.2.1 (21D62)
environment:
  - shell: /bin/bash
  - terminal: iterm
  - cwd: /Users/alenguler
  - exe-path: /Users/alenguler/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_PID: 29402
    - TERM: xterm-color
    - SHELL: /bin/bash
    - FIGTERM_SESSION_ID: 52deb383-5e15-4d88-9b03-08ee0a19ed42
    - FIG_SET_PARENT_CHECK: 1
    - PATH: /Users/alenguler/.krew/bin:/Users/alenguler/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alenguler/.fig/bin:/Users/alenguler/.local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
    - FIG_HOSTNAME: Ozan-AlenGuler
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_TERM: 2.10.1
```

**Comment by mschrage** [comment]
There is no video attached @alenguler?

**Comment by alenguler** [comment]
@mschrage 
here you can see some of examples.
in the first one, i am deleting some characters but some unexpected characters appears on the right when i delete any letter. 

https://user-images.githubusercontent.com/24495280/211484736-ab8882c2-ca84-46a9-a707-48eabde5b139.mov


in the second one, when i go up or down, there are some appears on screen.

https://user-images.githubusercontent.com/24495280/211484761-e4daf7ff-0ef0-47e3-b56e-2fb2eb6567cc.mov

**Comment by sullivan-sean** [comment]
@mschrage @grant0417 any ideas what might be going wrong here?

**Comment by grant0417** [comment]
No idea, @alenguler do you have any plugins installed?

**Comment by alenguler** [comment]
<img width="797" alt="Screen Shot 2023-02-04 at 22 06 41" src="https://user-images.githubusercontent.com/24495280/216785202-8e7d6112-8c33-491e-9bef-4f41786fe180.png">
No plugin installed. 

Btw, there is no issue on default terminal of Mac.
