### ISSUE TITLE
Show Fig status in menu bar

### ISSUE THREAD

**Issue by LinusS1** [withfig/fig#22]
It's sometimes hard to tell when Fig has stopped working, and what I need to do to fix it. It's be nice if the menu bar icon could be badged a color depending on the status. It'd also be nice if there was a setting to turn the badging and coloring on and off.

**Comment by falky97** [comment]
We can add a status symbol to your terminal window title and a little ✅ or ❌. We also integrated with zsh so Fig should be far more consistent now and you shouldn't need this...

Will keep issue open regardless

![image](https://user-images.githubusercontent.com/4949076/110187441-38399e80-7dcd-11eb-978b-3e2822447dd9.png)

**Comment by mschrage** [comment]
Closing this issue now that Fig works more consistently to get the users' edit buffer across shells (as of v1.0.46)!
