### ISSUE TITLE
Unable to Install fig on MacOS Ventura. Permission Denied errors.

### ISSUE THREAD

**Issue by benrfairless** [withfig/fig#2200]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

It should be possible to install fig by running `brew install fig` and `fig install`

### Actual behaviour

I am unable to get fig installed, even after multiple attempts to install by using `fig doctor`, `fig install`, and by updating the `~/.zshrc` file manually. Please see below for exact steps and for multiple outputs of each command and ~/.zshrc file.

### Steps to reproduce

1. Install fig using `brew install fig`
2. Run `fig install` - Output is [here](https://gist.github.com/benrfairless/55d73ba3154894821c89915d84e07cc5)
4. My ~/.zshrc file looks like [this](https://gist.github.com/benrfairless/fa0f1f89edf598e0c85e21965cbd8406) after installation.
5. I then add the requested entires in step 2 to make my ~/.zshrc look like [this](https://gist.github.com/benrfairless/3287ff1db4042dfc8884ab8d955cff1a)
6. I restart the terminal. Whenever I open the terminal from this point on I get the error mentioned [here](https://gist.github.com/benrfairless/2cdd1a87415deaff494ee6c1f7521a1c)
7. I restart fig using `fig restart` and get told I still have installation errors
8. I run `fig doctor` and I get [this output](https://gist.github.com/benrfairless/3b0c94f9184b4b4efcc5f9853ce78c12)
9. I update my ~/.zshrc and it now looks like [this](https://gist.github.com/benrfairless/2cdc5d81242ea45898bade513127a13f)
10. I restart the terminal and I restart fig. I am still seeing the "access denied" errors mentioned in step 6.
11. I run `fig doctor` for a second time and get [this error](https://gist.github.com/benrfairless/2cdc40b4381e2af9b85a87d649eae46f)
12. I update my ~./zshrc file to look [like this](https://gist.github.com/benrfairless/edfeb4534cca53698202b39f46512748)
13. I restart the terminal and I restart fig. I am still seeing the "access denied" errors mentioned in step 6.
14. I run `fig doctor` and I get [this output](https://gist.github.com/benrfairless/add8007953bdc29e344ed761978e2424).
15. I run fig diagnostic and have uploaded the results to Environment below

### Environment

```yaml
fig-details:
  - 2.10.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/benfairless
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: com.apple.Terminal
    - TERM: xterm-256color
    - SHELL: /bin/zsh
    - PATH: /opt/homebrew/opt/php@7.4/sbin:/opt/homebrew/opt/php@7.4/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/benfairless/.local/bin:/Users/benfairless/.fig/bin
```

**Comment by mschrage** [comment]
Can you run `ls -l $HOME/.fig/shell/zshrc.pre.zsh` and `ls -l ~/.zshrc` and share the output here?

**Comment by benrfairless** [comment]
Hi @mschrage here's the output for you:

```
ls -l $HOME/.fig/shell/zshrc.pre.zsh
-rw-r--r--  1 benfairless  staff  81  8 Jan 16:33 /Users/benfairless/.fig/shell/zshrc.pre.zsh
```

```
ls -l ~/.zshrc
-rw-r--r--@ 1 benfairless  staff  539  8 Jan 16:39 /Users/benfairless/.zshrc
```

**Comment by benrfairless** [comment]
I have spent some more time on this, and the solution mentioned [here](https://github.com/withfig/fig/issues/1370#issuecomment-1175605715) resolved the issue:
```
sudo chown -R $(id -un) ~/.local
```
