### ISSUE TITLE
Stuck on username

### ISSUE THREAD

**Issue by mroberts1** [withfig/fig#2206]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.2 (21G320)

### Expected behaviour

First-time setup to work properly.

### Actual behaviour

- Launched Fig desktop app.
- Received first-time user request to choose username
- Entered username
- Received request to install CLI
- Clicked Install button
- Nothing happened - button flashed but did nothing
- Quit app, restarted
- Received first-time user request to choose username
- Entered previous username
- Received message that the username I'd entered was taken
- As a result, unable to launch app and stuck on username choice screen
- QUESTION: How do I reset the app and/or my account so that I can login with the username that I originally entered, and want?

### Steps to reproduce

None - you would have to launch the app on my computer.

### Environment

```yaml
fig-details:
  - 2.11.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
  - cores: 2
  - mem: 8.00 GB
os-info:
  - macOS 12.6.2 (21G320)
environment:
  - shell: /usr/local/Cellar/fish/3.6.0/bin/fish
  - terminal: tabby
  - cwd: /Users/dokoissho/GitHub/jekyll/9dream
  - exe-path: /Users/dokoissho/.fig/bin/fig
  - install-method: brew
  - env-vars:
    - TERM: xterm-256color
    - SHELL: /usr/local/bin/zsh
    - __CFBundleIdentifier: org.tabby
    - FIG_SET_PARENT: 
    - FIG_TERM: 2.11.0
    - DISPLAY: /private/tmp/com.apple.launchd.MGamOcQs1O/org.xquartz:0
    - FIG_PARENT: 
    - FIG_PID: 46543
    - FIGTERM_SESSION_ID: ca035b91-ecd4-4b0d-910a-7c3120cd34da
    - PATH: /Users/dokoissho/.gem/ruby/2.7.6/bin:/Users/dokoissho/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/bin:/Users/dokoissho/.rubies/ruby-2.7.6/bin:/usr/local/bin:/usr/local/sbin:/Users/dokoissho/.nodenv/shims:/Users/dokoissho/.cargo/bin:/Users/dokoissho/perl5/perlbrew/bin:/opt/local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/opt/devkitpro/tools/bin:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/munki:/Applications/Racket/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:/Users/dokoissho/.fig/bin:/Users/dokoissho/.local/bin
```

**Comment by mschrage** [comment]
Hey @mroberts1, what was the username? We can delete the other account cc @grant0417

**Comment by danielbayley** [comment]
I think I have the same/similar problem (username is _this_ GitHub account…) @mschrage What can I do?
