### ISSUE TITLE
Fig doesn't respect custom keybindings with karabiner or hammerspoon

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#221]
e.g. the user has mapped the caps lock character to the escape key. However, when they press caps lock to hide fig, Fig does not register it.

**Comment by brendanfalk** [comment]
This should be fixed when we push our new integration with the shell with pseudoterminals in v1.0.46 of v1.0.47

**Comment by brendanfalk** [comment]
@mattschrage do we have any temporary fixes for this?

**Comment by mattschrage** [comment]
Unfortunately, not that I can think of.

**Comment by parssak** [comment]
This has been fixes
