### ISSUE TITLE
Unable to Link Domain to Team Account

### ISSUE THREAD

**Issue by partydrone** [withfig/fig#2211]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS Ventura 13.1

### Expected behaviour

I created a team account in the Fig app on my computer. Under the Members tab for the team, I added our company domain to the "Allowed Domains" section (so anyone with an email address at that domain can sign up for this team).

I received an email from Fig to finish linking our domain. When I click the "Link Domain" button in the email, my browser opens up to a page that completes the process.

### Actual behaviour

When I click the "Link Domain" button in the email, my browser opens up to a 404 error page.

**Comment by chaynabors** [comment]
Howdy, the domain was linked but there wasn't a page at the redirect until now. Let me know if you still have any issues!
