### ISSUE TITLE
Suggestions dont come often

### ISSUE THREAD

**Issue by chirayu2001** [withfig/fig#2217]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

suggestions for auto complete should come always 

### Actual behaviour

Suggestions dont come always, especially when I open iterm2

### Steps to reproduce

yes, just whenever I open item after some time, autosuggestions dont come.

### Environment

```yaml
fig-details:
  - 2.11.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/chirayu
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 19d22a94-ada0-46f7-b3e2-6659e13abef7
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.11.0
    - PATH: /usr/local/sbin:/usr/local/Cellar/zplug/2.4.2/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Library/Apple/usr/bin:/Users/chirayu/.fig/bin:/Users/chirayu/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 15338
    - FIG_SET_PARENT: 19d22a94-ada0-46f7-b3e2-6659e13abef7
```

**Comment by mschrage** [comment]
I could not repro based on the information provided. If you can determine how to reproduce this issue, please let me know and I will reopen it!
