### ISSUE TITLE
scripts - choosing an item with mouse on a selector causes application to panic

### ISSUE THREAD

**Issue by polds** [withfig/fig#2220]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.1 (21G217)

### Expected behaviour

No panic when choosing an item from a list with mouse and pressing enter.

### Actual behaviour

the script crashes:

The application panicked (crashed).                                          
 Message:  index out of bounds: the len is 0 but the index is 1
 Location: lib/tui/src/component/select.rs:161
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.

### Steps to reproduce

- Create a new script that has a selector with some items
- Run script
- Use mouse to select an item and press enter

### Environment

```yaml
fig-details:
  - 2.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: <censored>
  - exe-path: /Users/oldpeter/.local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 84f8ef17-1bfe-42fd-8d87-f207631d18b5
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.12.0
    - PATH: /Users/oldpeter/go/bin:/Users/oldpeter/.local/bin:/Users/oldpeter/Library/Python/3.8/bin:/Users/oldpeter/.toolbox/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/oldpeter/.fig/bin:/Users/oldpeter/.local/bin:/usr/local/bin:/Users/oldpeter/.fig/bin:/Users/oldpeter/.toolbox/bin:/Users/oldpeter/Library/Python/3.8/bin:/Users/oldpeter/.local/bin:/Users/oldpeter/go/bin:/usr/local/go/bin:/Users/oldpeter/.toolbox/bin:/Users/oldpeter/Library/Python/3.8/bin:/Users/oldpeter/go/bin:/Users/oldpeter/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 63270
    - FIG_SET_PARENT: 84f8ef17-1bfe-42fd-8d87-f207631d18b5
```

**Comment by chaynabors** [comment]
This is fixed. Let me know if you still have this issue.
