### ISSUE TITLE
Error on setting up Fig

### ISSUE THREAD

**Issue by towoju5** [withfig/fig#2221]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

File does not exist: /Users/user/.bashrc
● /Users/user/.bash_profile does not source pre integration
✘ PATH contains ~/.local/bin: Path does not contain ~/.local/bin

### Actual behaviour

<img width="1440" alt="Screenshot 2023-01-15 at 11 52 50" src="https://user-images.githubusercontent.com/40261626/212536544-b297cfb1-a66d-4639-8037-9502b0fd2622.png">

### Steps to reproduce

A pure installation on Mac OS ventura

### Environment

```yaml
fig-details:
  - 2.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  - cores: 2
  - mem: 8.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/user
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: com.apple.Terminal
    - TERM: xterm-256color
    - SHELL: /bin/zsh
    - PATH: /Applications/XAMPP/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by naderalfares** [comment]
After updating fig, I'm facing the same problem.
