### ISSUE TITLE
Conventional commit script crashes when typing Æ,Ø,Å

### ISSUE THREAD

**Issue by RHellenes** [withfig/fig#2227]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.0.1 (21A559)

### Expected behaviour

- I expect the conventional commit' should be able to receive the characters ÆØÅ

- I expect fig doctor to fix install issues.  

### Actual behaviour

- When I type the character ÆØÅ while commiting a conventional commit it chrashes. In the picture below I tried the character æ
<img width="1291" alt="Screenshot 2023-01-16 at 12 51 09" src="https://user-images.githubusercontent.com/16990441/212671908-9a840c4a-221a-424b-ab38-1246f06b74ef.png">

 - The Fig application says "Fig hasn't been installed properly" and running fig doctor results in everything looks good. 
<img width="538" alt="Screenshot 2023-01-16 at 12 52 12" src="https://user-images.githubusercontent.com/16990441/212672081-df1d8143-4cf6-49ed-b850-5d4d151edacb.png">

### Steps to reproduce

Install the extension conventional commit and type either ÆØÅ for it to fail. 

### Environment

```yaml
fig-details:
  - 2.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 12.0.1 (21A559)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/user/repo
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 89ffb985-6c79-4f58-a8b5-b49298c169ed
    - FIG_PID: 61138
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.12.0
    - PATH: /Users/user/.nvm/versions/node/v16.14.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/user/.nvm/versions/node/v16.14.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/user/.cargo/bin:/Users/user/.fig/bin:/Users/user/.local/bin:/Users/user/.npm-gloabl/bin:/Users/user/.npm-gloabl/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/user
    - __CFBundleIdentifier: com.microsoft.VSCode
    - FIG_SET_PARENT: 89ffb985-6c79-4f58-a8b5-b49298c169ed
```

**Comment by chaynabors** [comment]
Fixed in next build
