### ISSUE TITLE
fig is looking for .bashrc

### ISSUE THREAD

**Issue by Dodi71** [withfig/fig#2229]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

fig to work normally as zsh is installed and bash is not installed

### Actual behaviour

fig is showing File does not exist: /Users/khalid/.bashrc when I run fig doctor though bash is not installed on my machine

### Steps to reproduce

fig doctor

### Environment

```yaml
fig-details:
  - 2.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/khalid
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: dbdbd163-c5c5-4afb-ab60-bb0661f3e95f
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.12.0
    - PATH: /Users/khalid/.pyenv/shims:/Users/khalid/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/Applications/Little Snitch.app/Contents/Components:/opt/X11/bin:/Library/Apple/usr/bin:/Users/khalid/.fig/bin:/Users/khalid/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: co.zeit.hyper
    - FIG_PID: 5647
    - FIG_SET_PARENT: dbdbd163-c5c5-4afb-ab60-bb0661f3e95f
```

**Comment by mschrage** [comment]
This is the expected behavior. I'd just create an empty file to satisfy the check.
