### ISSUE TITLE
Fig DashBoard: Something went wrong :( Error: Bad credentialsFig Dashboard

### ISSUE THREAD

**Issue by PALHASSAN** [withfig/fig#2230]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

I Can't Open Fig Dashboard...

### Actual behaviour

<img width="704" alt="Screenshot 1444-06-24 at 1 31 50 PM" src="https://user-images.githubusercontent.com/122810924/212875976-19574a8a-dbba-4a85-8b99-e8e38c13b405.png">

### Environment

```yaml
fig-details:
  - 2.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/alhassan
  - exe-path: /Users/alhassan/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 55b951e9-a33f-4b08-bbd4-dd83f8f48fe8
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.12.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/alhassan/.fig/bin:/Users/alhassan/.local/bin:/Users/alhassan/Library/Application Support/JetBrains/Toolbox/scripts:code/lar:
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 3518
    - FIG_SET_PARENT: 55b951e9-a33f-4b08-bbd4-dd83f8f48fe8
```

**Comment by chebread** [comment]
I am the same macOS 13.1.0 (22C65) operating system.
I am experiencing the same phenomenon.
This is my first time using Fig, but I can't use it because of this bug.
I did a fig logout and a fig login. It shouldn't though.

**Comment by PALHASSAN** [comment]
@chebread 
I solved the problem, just logout and login back..
in the terminal type: fig logout, then type: fig login..

Have a Nice Day

**Comment by enisze** [comment]
Does not solve the problem for me. @PALHASSAN.

**Comment by zhusupq** [comment]
error: Signups are currently disabled (status: 400 Bad Request)
