### ISSUE TITLE
Datagrip Terminal Issue

### ISSUE THREAD

**Issue by agitrubard** [withfig/fig#2232]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.1 (21G217)

### Expected behaviour

(eval):source:87: no such file or directory: /Users/agitrubardemir/Applications/DataGrip.app/Contents/plugins/terminal/.zshenv

DataGrip Terminal Plugin Issue

### Actual behaviour

<img width="1440" alt="Screen Shot 2023-01-17 at 7 33 11 PM (2)" src="https://user-images.githubusercontent.com/61833677/212958214-4c71b028-dead-4970-a9f2-4271d5231c73.png">

### Steps to reproduce

Download DataGrip and Install Terminal Plugin then open Terminal, this issue will be find you :))

### Environment

```yaml
fig-details:
  - 2.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /bin/zsh
  - terminal: intellij
  - cwd: /Users/agitrubardemir/WorkSpace/abc
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: f0f83ad6-6741-45a9-909e-09c6b8e861e1
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.12.0
    - PATH: /Applications/apache-maven-3.6.3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/agitrubardemir/.fig/bin:/Users/agitrubardemir/.local/bin:/Users/agitrubardemir/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.datagrip
    - FIG_PID: 57739
    - FIG_SET_PARENT: f0f83ad6-6741-45a9-909e-09c6b8e861e1
```

**Comment by mschrage** [comment]
Can you check to see where DataGrip is installed?

**Comment by agitrubard** [comment]
**DataGrip Installing Path :** `/Users/agitrubard/Library/Application Support/JetBrains/Toolbox/apps/datagrip/ch-0/223.8214.62/DataGrip.app`

**Comment by steveswing** [comment]
I reported this same issue with IntelliJ IDEA as [IDEA-314726](https://youtrack.jetbrains.com/issue/IDEA-314726) `(eval):source:87: no such file or directory: /Applications/IntelliJ IDEA 2023.1 EAP.app/Contents/plugins/terminal/.zshenv` however, I eliminated the display of the message by disabling the Fig plugin in IntelliJ IDEA. I did use the recommended Fig quick fix to repair the installation/configuration issue identified/described in Fig settings. This began to appear for me with 2023.1 EAP 6 and 2023.1 Beta.

`Contents/plugins/terminal/.zshenv` doesn't exist however, `Contents/plugins/terminal/zsh/.zshenv` does.

**Comment by heychazza** [comment]
> I reported this same issue with IntelliJ IDEA as [IDEA-314726](https://youtrack.jetbrains.com/issue/IDEA-314726) `(eval):source:87: no such file or directory: /Applications/IntelliJ IDEA 2023.1 EAP.app/Contents/plugins/terminal/.zshenv` however, I eliminated the display of the message by disabling the Fig plugin in IntelliJ IDEA. I did use the recommended Fig quick fix to repair the installation/configuration issue identified/described in Fig settings. This began to appear for me with 2023.1 EAP 6 and 2023.1 Beta.
> 
> `Contents/plugins/terminal/.zshenv` doesn't exist however, `Contents/plugins/terminal/zsh/.zshenv` does.

Annoyingly I don't even have the plugin installed for PHPStorm and facing the same issue. Very frustrating and just drives me to want to uninstall Fig.

**Comment by monsterhxw** [comment]
same issue

**Comment by asterixcode** [comment]
Same issue after updating to the latest version of IntelliJ IDEA 2023.1 (231.8109.175) with JetBrains Toolbox App version 1.27.3.14493

Operating system: macOS Ventura Version 13.2.1 (22D68).

`(eval):source:87: no such file or directory: /Users/username/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app/Contents/plugins/terminal/.zshenv`

**Comment by edeandrea** [comment]
Same issue here too, & like @heychazza mentioned I don't even have the Fig plugin installed into IntelliJ

**Comment by VikalpRusia** [comment]
Vey annoying have to uninstall fig due to this

**Comment by CharleeWa** [comment]
same issue

**Comment by fabio-alkimia** [comment]
Same issue, just copied `Contents/plugins/terminal/zsh/.zshenv` file also into the `Contents/plugins/terminal` directory (it's a temporary workaround, but now the message disappears).  👍

**Comment by SebiBasti** [comment]
same issue here

**Comment by Enivel** [comment]
+1

**Comment by mboyov** [comment]
Same issue !!!

**Comment by Ossama9** [comment]
thank @mboyov  it's working

**Comment by mschrage** [comment]
This should be resolved in the latest update.
