### ISSUE TITLE
windterm show bad strings

### ISSUE THREAD

**Issue by yaoyi2008** [withfig/fig#2237]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
> Please include a detailed description of the feature (and an image or screen recording, if applicable)

<img width="966" alt="image" src="https://user-images.githubusercontent.com/5906825/213106276-b90a0e7c-24c0-4623-888f-7ed6a194bdb3.png">

**Comment by mschrage** [comment]
Can you run `echo $__CFBundleIdentifier` and share the output here?
