### ISSUE TITLE
`fig settings pty.env` sets shell variables, should set environment variables

### ISSUE THREAD

**Issue by wilhelmklopp** [withfig/fig#224]
### Making sure DJANGO_SECRET_KEY is set (in my terminal)
```zsh
Current active process: /usr/local/Cellar/zsh/5.8/bin/zsh (20457) - ttys017
(simplepoll) ➜  simplepoll git:(main) echo $DJANGO_SECRET_KEY
test-secret
(simplepoll) ➜  simplepoll git:(main) env | grep DJANGO_SECRET_KEY
DJANGO_SECRET_KEY=test-secret
(simplepoll) ➜  simplepoll git:(main) python -c "import os; print(os.environ['DJANGO_SECRET_KEY'])"
test-secret
(simplepoll) ➜  simplepoll git:(main) 
```

### Using fig settings pty.env (in my terminal)

```zsh
simplepoll) ➜  simplepoll git:(main) fig settings pty.env '["DJANGO_SECRET_KEY"]'            
(simplepoll) ➜  simplepoll git:(main) fig settings pty.env                                    
DJANGO_SECRET_KEY
(simplepoll) ➜  simplepoll git:(main) fig source

fig is now connected to this terminal session. (/dev/ttys017)

```

### Reading DJANGO_SECRET_KEY (in the pseudo terminal)
_with the safari devtools console_

![image](https://user-images.githubusercontent.com/7718702/123508899-23c62e00-d66a-11eb-9a74-eb2b2ed68682.png)

**Expected Results:**
DJANGO_SECRET_KEY should show up when running `env` and should be available to child processes, like `python`

**Actual Results:**
DJANGO_SECRET_KEY is available via `echo $DJANGO_SECRET_KEY`, but does not show up when running `env`. It's not available to child processes like `python`.

**System information:**
OS: MacOS Big Sur 11.4
Version 1.0.45 (B218) [Dev] [British] 

**Additional Notes:**
Continuing on from the reproductions steps, If I do the following in the pseudo terminal, I can get it to work:

`await ptyexecute("export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY")`

![image](https://user-images.githubusercontent.com/7718702/123508971-a2bb6680-d66a-11eb-8ab9-39bee86c5258.png)

---

This DO article Brendan posted in #dev-help gives a good overview: https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-linux

Relevant screenshot:
![image](https://user-images.githubusercontent.com/7718702/123508593-40616680-d668-11eb-998c-6b7bbc58e8f1.png)

cc @brendanfalk @mattschrage

**Comment by mattschrage** [comment]
Thanks for reporting @wilhelmklopp! This will be fixed in `v1.0.46`.
