### ISSUE TITLE
bug: binary invoked does not reside in a valid app bundle.

### ISSUE THREAD

**Issue by anz-ryu** [withfig/fig#2241]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

mac os

### Expected behaviour

failed to update fig: `binary invoked does not reside in a valid app bundle.` Error ID: 2e6eb2a7-0513-4c5b-995a-cae6ebb96d6c

```
Restarting Fig
error: Failed to open dashboard
```

```
fig doctor

✘ zsh ~/.zshrc integration check: /Users/user2/.zshrc does not source pre integration first

  Run fig integrations install dotfiles to reinstall shell integrations for zsh
Attempting to fix automatically...
Re-running check...

✔ zsh ~/.zshrc integration check
✘ Fig Integration: This terminal is not running with the latest Fig integration, please restart your terminal

  FIG_TERM=2.10.1


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

### Actual behaviour

![スクリーンショット 2023-01-19 10 16 15](https://user-images.githubusercontent.com/96708931/213332747-6d36fd58-4c9d-4444-a259-e0e0b2d59d57.png)

**Comment by mschrage** [comment]
I'd recommend uninstalling and reinstalling the application.
