### ISSUE TITLE
Can't install shell integrations

### ISSUE THREAD

**Issue by flokamps** [withfig/fig#2244]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

I just bought a new mac. The first thing I did was to install fig with homebrew. Only, I can't finish the installation of fig, because the button "Install shell integrations" in the "Fix Installation issues" part doesn't work

<img width="512" alt="image" src="https://user-images.githubusercontent.com/58564956/213525829-c3fa234e-9ccd-483b-92b1-5dc7e6e3761f.png">

<img width="560" alt="image" src="https://user-images.githubusercontent.com/58564956/213525945-3acb4943-8e66-49f7-af01-d0f3b5b4e6b3.png">

### Actual behaviour

Unable to install fig correctly, the "Install" button for "Install Shell Integration".

<img width="474" alt="image" src="https://user-images.githubusercontent.com/58564956/213526228-c54357c5-b25e-4167-8de2-0563627be9ee.png">

My .zshrc:

```
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
```

My .profile is empty

### Steps to reproduce

- Install fig from brew

- Try to fix errors from dashboard

### Environment

```yaml
fig-details:
  - 2.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/dolor3sh4ze
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: bf2e7423-f4aa-4bc9-b399-b38c620f32db
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.12.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dolor3sh4ze/.fig/bin:/Users/dolor3sh4ze/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 1038
    - FIG_SET_PARENT: bf2e7423-f4aa-4bc9-b399-b38c620f32db
```

**Comment by Coordinate-Cat** [comment]
I have the same problem.
In my case, after installing with dmg instead of brew, I could not get a good setup.

**Comment by kunaaal13** [comment]
yeah I installed it using dmg and it's not giving good setup, on clicking install nothing happens in fix installation issues.

**Comment by kunaaal13** [comment]
> I have the same problem. In my case, after installing with dmg instead of brew, I could not get a good setup.

is fig command working in your case

**Comment by Coordinate-Cat** [comment]
@kunaaal13 
Progress has been made in my environment.

After doing fig doctor, I got an error asking me to type the following command, so I typed it, and the GUI error disappeared.

- `sudo chown $USER /Users/YOUR NAME/.zshrc && sudo chmod 644 /Users/YOUR NAME/.zshrc`
- `sudo fig integrations install dotfiles`

<img width="561" alt="スクリーンショット 2023-01-20 11 47 33" src="https://user-images.githubusercontent.com/42393004/213607257-4e9d2671-781d-4632-94c8-2c387e0f4ee5.png">

<img width="1142" alt="スクリーンショット 2023-01-20 11 47 44" src="https://user-images.githubusercontent.com/42393004/213607286-49808311-fee4-4a93-aa29-2cdc20d1cbad.png">
