### ISSUE TITLE
Extension host terminated unexpectedly while fig is running in Vscode

### ISSUE THREAD

**Issue by safethecode** [withfig/fig#2246]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 11.2.3 (20D91)

### Expected behaviour

Although no behavior is expected, all extensions must run originally. However, as Fig goes down, all the extensions are also terminated.

### Actual behaviour

<img width="665" alt="Screen Shot 2023-01-20 at 2 29 16 PM" src="https://user-images.githubusercontent.com/59228569/213624047-09790e58-29a9-4758-9ec0-2dd599f9258d.png">

+ Command failed: fig hook keyboard-focus-changed vscode 19180

However, if 'fig' enters a command, it works fine.

### Steps to reproduce

Shortly after running Vscode, all extensions are terminated with a warning message **'Extension host terminated unexpected 3 times with the last 5 minutes.'**

### Environment

```yaml
fig-details:
  - 2.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 11.2.3 (20D91)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/jam/Desktop
  - exe-path: /Users/jam/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: fe412bda-66f5-4ba2-9680-bef9f2ece6a7
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.12.0
    - PATH: /Users/jam/.bun/bin:/Users/jam/.bun/bin:/Users/jam/.gem/bin:/Users/jam/.nvm/versions/node/v16.18.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/Users/jam/.cargo/bin:/Users/jam/.fig/bin:/Users/jam/.local/bin:/Users/jam/.local/share/fig/plugins/git-flow
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/jam
    - __CFBundleIdentifier: com.microsoft.VSCode
    - FIG_PID: 5943
    - FIG_SET_PARENT: fe412bda-66f5-4ba2-9680-bef9f2ece6a7
```

**Comment by SaudElabdullah** [comment]
Is there any update on this?

**Comment by safethecode** [comment]
@mschrage remained

**Comment by tobsn** [comment]
I installed fig, tried to open it but it told me sign ups are closed.
Ever since I'm getting this stupid error and I can't get rid of it.

Has anyone found out how to resolve this? I'm trying not to use strong language to explain what I think about a company that has all its downloads open to the world but restricts sign ups, the usage of said app, AFTER installing all its hooks into the system.

**Comment by tobsn** [comment]
`rm -rf /Users/youruser/.vscode/withfig.fig-0.0.7`

**Comment by keithgibson** [comment]
@tobsn thank you, removing that file did the trick. i used find any file to get to it, as for some reason running the command itself didn’t get it (probably user error on my part).

**Comment by ma2bara** [comment]
I was also experiencing the same issue.
In my environment, `rm -rf /Users/{username}/.vscode/extensions/withfig.fig-0.0.7` worked.
