### ISSUE TITLE
no popout appear

### ISSUE THREAD

**Issue by nevertoday** [withfig/fig#2248]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

I hope there will be a pop-up box, but there is no, after I uninstall it, there is no reinstallation, it is really strange! I checked that too, and everything is fine with the naming hint!

### Actual behaviour

have auto suggestion menu

### Steps to reproduce

anytime

### Environment

```yaml
fig-details:
  - 2.12.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/ifxl
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 2a935bd1-0fd2-4e6b-81fa-5fc6acb8fa20
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.12.0
    - PATH: /Users/ifxl/miniconda3/bin:/Users/ifxl/miniconda3/condabin:/Users/ifxl/.cargo/bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/ifxl/.fig/bin:/Users/ifxl/.local/bin:/Users/ifxl/.fzf/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 88605
    - FIG_SET_PARENT: 2a935bd1-0fd2-4e6b-81fa-5fc6acb8fa20
```

**Comment by mschrage** [comment]
I suggest running `fig doctor` and seeing if this helps.
