### ISSUE TITLE
bug: SSH from Linux to Mac and fig.io initialises and displays autocomplete popup on Mac

### ISSUE THREAD

**Issue by octomancer** [withfig/fig#2253]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS 13.1

### Expected behaviour

I expect that fig.io does not initialise itself when I SSH from a Linux machine with fig.io NOT installed to my Mac that has fig.io installed.

### Actual behaviour

I SSH from Linux to Mac and the fig autocomplete window incorrectly appears on my Mac when I type a command
![linux-term-ssh-to-mac](https://user-images.githubusercontent.com/123418347/214172350-166d8737-22e5-4dbb-991b-247b0f1b2205.png)
<img width="860" alt="autocompletion-on-mac-wrong" src="https://user-images.githubusercontent.com/123418347/214172374-1cf22a91-1f55-4497-b36e-a3082fcde093.png">

### Steps to reproduce

Yes, it happens every time I SSH from Linux to Mac.

Actually, I can stop it from happening by testing for $SSH_TTY like so

`[[ -f "$HOME/.fig/shell/bashrc.pre.bash" ]] && [[ -z "$SSH_TTY" ]] && builtin source "$HOME/.fig/shell/bashrc.pre.bash"`

but then fig reports that the installation is broken and will add the fig blocks to the top and bottom of my bash init files again.

While I'm on the subject, rigid checks for exact strings at specific locations in bash init files is very, very broken behaviour. At the absolute minimum you should have a flag to allow the user to tell fig that "my bash init files are way more complicated than a simple install script can understand so just tell me what needs doing and i'll sort it out".

I am an example of another edge case ... I have this at the top of all of my .bashrc files:

`# If not running interactively, don't do anything`
`case $- in`
`	*i*) ;;`
`	*) return;;`

or at least I used to until fig.io forced me not to :/

### Environment

```yaml
$ fig diagnostic
fig-details:
  - 2.12.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /usr/local/Cellar/bash/5.2.15/bin/bash
  - terminal: <unknown> ( It's actually iTerm2 v3 ... ofc it is )
  - cwd: /Users/username
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /usr/local/bin/bash
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: 9edfe712-a6cb-40a5-bd4a-48cd968a43bc
    - FIG_TERM: 2.12.0
    - TERM: xterm-256color
    - FIG_PID: 11400
    - PATH: /Users/username/venv/p-3.10/bin:/Users/username/bin:/Users/username/code/go/bin:/usr/local/opt/gnupg@2.2/bin:/opt/local/bin:/usr/local/bin:/usr/bin:/bin:/opt/local/sbin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/Users/username/.fig/bin:/Users/username/.local/bin:/usr/local/opt/fzf/bin:/Users/username/.local/share/fig/plugins/tumult.plugin.zsh_unixorn/bin
```

**Comment by brunos3d** [comment]
Up, same here! 👍

**Comment by brunos3d** [comment]
Tested with WSL (Ubuntu 22.04) and PowerShell (Windows 11)

<p float="left" align="center">
<img width="50%" alt="image" src="https://user-images.githubusercontent.com/21183964/214579353-0d61b291-b96c-4f58-b7e3-882c4b197304.png">
<img width="43%" alt="image" src="https://user-images.githubusercontent.com/21183964/214579114-9a83dc61-7f9f-4656-a1b9-3b5cba50ccaf.png">
</p>

**Comment by mschrage** [comment]
This will be fixed in the next release! Thanks for your patience.
