### ISSUE TITLE
ssh error when using git

### ISSUE THREAD

**Issue by michaelwschultz** [withfig/fig#2255]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

No error message to be thrown when using git.

### Actual behaviour

When running `git pull` for example, I get this error. I can't see to find this file though.

`error: unexpected argument '/Users/michael/.ssh/7d4bfe5ee644b8d383fc019f4c532ab28aa48784' found`

<img width="785" alt="CleanShot 2023-01-24 at 13 51 33@2x" src="https://user-images.githubusercontent.com/57668/214429074-b7fa50ad-240d-472e-aa11-146ac4beed1a.png">

### Steps to reproduce

Open terminal, run git pull in any git repo directory.

### Environment

```yaml
fig-details:
  - 2.13.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/michael/Dev/sensible-app
  - exe-path: /Users/michael/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: dc8d28c9-667c-4cab-aa24-43357ddba63b
    - FIG_PID: 5588
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.13.0
    - PATH: /Users/michael/Library/pnpm:/Users/michael/.nvm/versions/node/v16.15.1/bin:/Users/michael/.nvm/versions/node/v16.15.1/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/michael/Library/pnpm:/Users/michael/.nvm/versions/node/v16.15.1/bin:/Users/michael/.fig/bin:/Users/michael/.local/bin:/Users/michael/go/bin:/opt/homebrew/opt/go/libexec/bin:/Users/michael/Dev/sensible/node_modules/.bin:/Users/michael/go/bin:/opt/homebrew/opt/go/libexec/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/michael
    - __CFBundleIdentifier: com.microsoft.VSCode
    - FIG_SET_PARENT: dc8d28c9-667c-4cab-aa24-43357ddba63b
```

**Comment by dlawson-tw** [comment]
I had the same issue while setting up a new system (copied over stuff from the old one) and fixed it. The bg:ssh is a legacy thing:

https://fig.io/manual/fig/bg:ssh

I commented out this line in my `~/.ssh/config` file:
`LocalCommand fig bg:ssh ~/.ssh/%r@%h:%p &`

Working again, no error!

**Comment by mschrage** [comment]
@dlawson-tw this is the correct solution! Thanks for documenting.
