### ISSUE TITLE
bug: Issue hiding the autocomplete suggestions when  pressed the "esc" button.

### ISSUE THREAD

**Issue by pradip-pdl** [withfig/fig#2259]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

mac os monterey v12.2

### Expected behaviour

I expected the pressing of the esc button to hide the autocomplete suggestions in my terminal.

### Actual behaviour

When the `esc` button is pressed, the autocomplete suggestions do not hide and remain visible on the screen.

https://user-images.githubusercontent.com/102576038/214816163-e14f3deb-c491-4775-a942-9df3cb1fdafa.mov

### Steps to reproduce

1. With `Fig` running in the background, open up `iTerm2` or `Terminal`.
2. Type `git` (an autocomplete menu should appear)
3. Press `esc` (Expected the menu to disappear but it doesn't)

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 12.2.0 (21D49)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/xxx/xxx/xxx
  - exe-path: /Users/xxx/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: b1e3c579-eaca-4dc0-98da-6699278e1357
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.13.1
    - PATH: /Users/xxx/.nvm/versions/node/v17.8.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/xxx/.fig/bin:/Users/xxx/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 1687
    - FIG_SET_PARENT: b1e3c579-eaca-4dc0-98da-6699278e1357
```

**Comment by OriBenHur-akeyless** [comment]
I am experiencing the same problem

**Comment by rickysullivan** [comment]
I too am experiencing a similar behavior, except _only_ in Webstorm. iTem integration is fine.

**Comment by rickysullivan** [comment]
My bad. Turns out Webstorm had other ideas:

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/437480/228028981-a67321c5-1037-45f6-a56f-12aa77eee5b8.png">

Unassinging shortcut helped me.

**Comment by mschrage** [comment]
I am going to close this issue for now. @OriBenHur-akeyless suggestion is the correct approach. If `esc` isn't working and the value is set to "hideAutocomplete" it is possible that another app (the terminal emulator or IDE) is intercepting the keypress before it is processed by Fig.
