### ISSUE TITLE
Remote install failing on linux server when I ssh to the server.

### ISSUE THREAD

**Issue by thedanielfactor** [withfig/fig#2261]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Ubuntu 22.10 (GNU/Linux 5.19.0-29-generic x86_64)

### Expected behaviour

Fig autocomplete to start working.  

### Actual behaviour

Fig Autocomplete is not working.

### Steps to reproduce

fig ssh @thedanielfactor/tdfprojects 

When I first installed fig remote on these 2 machines they had an error, so I ran `fig doctor` and it said SSH was not configured or something but it auto-fixed the first issue and then it said I was missing some values from my `sshd_config`.  I modified the file according to what it told me and then I restarted my ssh service (`sudo systemctl restart ssh`).  I exited and ssh'd back using the fig ssh command.

Once connected there is an error that shows up which was not there when I first installed fig remotely.  And if I run `fig doctor` it says `Everything looks good!` but I am still not getting the autocomplete window.

![CleanShot 2023-01-26 at 07 51 56](https://user-images.githubusercontent.com/448370/214861559-d4fdc383-94b5-4faf-9ad1-b45626a56ade.png)
![CleanShot 2023-01-26 at 08 23 34](https://user-images.githubusercontent.com/448370/214861605-609ad2ad-19b4-47ff-9fb9-d60925e069bf.png)

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model:
  - model-id:
  - chip-id: AMD EPYC-Rome Processor
  - cores: 1
  - mem: 1.93 GB
os-info:
  - kernel: 5.19.0-29-generic
  - distro: "Ubuntu"
  - distro-version: "22.10 (Kinetic Kudu)"
environment:
  - shell: /usr/bin/bash
  - terminal: <unknown>
  - cwd: /home/raymonddoran
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /bin/bash
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: 7d8b3aec-1e08-4713-98f6-dcd4514e8c2b
    - XDG_SESSION_TYPE: tty
    - FIG_TERM: 2.13.1
    - TERM: xterm-256color
    - PATH: /home/raymonddoran/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/raymonddoran/.local/bin:/home/raymonddoran/.fig/bin
    - FIG_PARENT: 09d74a18-76c0-45fd-bf4d-c449b9597828
```

**Comment by mschrage** [comment]
Try connecting directly via `ssh` without using `fig ssh`? Does this help?
