### ISSUE TITLE
not working in Nushell

### ISSUE THREAD

**Issue by cyg056** [withfig/fig#2264]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.0 (22D49)

### Expected behaviour

fig not working in Nushell

### Actual behaviour

fig not working in Nushell

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /opt/homebrew/Cellar/nushell/0.74.0/bin/nu
  - terminal: iterm
  - cwd: /Users/chenyonggang
  - exe-path: /Users/chenyonggang/.local/bin/fig
  - install-method: brew
  - env-vars:
    - PATH: /Users/chenyonggang/.local/bin:/Users/chenyonggang/.fig/bin:/opt/homebrew/bin:/Users/chenyonggang/.fig/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /opt/homebrew/bin/nu
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
```

**Comment by mschrage** [comment]
Closing as duplicate #879
