### ISSUE TITLE
Autocomplete stuck in top-left

### ISSUE THREAD

**Issue by J-Luckas** [withfig/fig#2266]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 5.15.0-58-generic - "Linux Mint 21.1"

### Expected behaviour

I expect that autocomplete is set under the line.

### Actual behaviour

The autocomplete keeps in the top-left of my window.

![image](https://user-images.githubusercontent.com/52499442/215227520-815a5356-55af-4ca0-9414-1964706b2ae5.png)

### Steps to reproduce

- Open the GNOME Terminal
- Type any command to autocomplete shows

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: AMD Ryzen 5 5500U with Radeon Graphics
  - cores: 6
  - mem: 6.64 GB
os-info:
  - kernel: 5.15.0-58-generic
  - distro: "Linux Mint 21.1"
  - distro-version: "21.1 (Vera)"
environment:
  - shell: /usr/bin/zsh
  - terminal: <unknown>
  - cwd: /home/luckas
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: :0
    - FIGTERM_SESSION_ID: a62e55ad-0247-40c4-bdbb-a8824bf1ec90
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.13.1
    - GTK_IM_MODULE: ibus
    - PATH: /home/luckas/.local/share/pnpm:/home/luckas/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/luckas/.local/bin:/home/luckas/.fig/bin
    - QT_IM_MODULE: ibus
    - SHELL: /usr/bin/zsh
    - TERM: xterm-256color
    - XDG_CURRENT_DESKTOP: X-Cinnamon
    - XDG_SESSION_DESKTOP: cinnamon
    - XDG_SESSION_TYPE: x11
    - XMODIFIERS: @im=ibus
    - FIG_PID: 2810
    - FIG_SET_PARENT: a62e55ad-0247-40c4-bdbb-a8824bf1ec90
```

**Comment by J-Luckas** [comment]
I've already tried to do the solutions to others issues with the same problem, but it didn't work for me.

**Comment by ebdurrehm** [comment]
The same problem happened to me, I can't change the positions of the autocomplete.

**Comment by junaidP7** [comment]
The same happened to me

**Comment by Warmachine13** [comment]
same problem on pop os, just work when I run `'fig restart'` some times

**Comment by mschrage** [comment]
Closing since Autocomplete on Linux is not currently supported.

**Comment by cleyton1986** [comment]
I don't know if it's a solution, but for me it worked like this:
✅ -  fig restart
✅ - Open Fig Dashboard > Autocomplete > General
✅ - I clicked on the "Fig AutoComplete no....." area
✅ - will process a bit (loading...)
✅ - then just test in the terminal.

I'm use: 
Linux Mint 21.2 Cinnamon
Fig Version: 2.15.0
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)
Terminal (native)
Terminal Tilix
Terminal Hyper


![Captura de tela de 2023-07-24 13-35-48](https://github.com/withfig/fig/assets/10548219/3f50e82a-cd19-45cb-a50f-ca59a2a5a754)
