### ISSUE TITLE
Repeatedly getting "Install shell integrations" advice

### ISSUE THREAD

**Issue by timfee** [withfig/fig#2268]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.0 (22D49)

### Expected behaviour

I ran `fig doctor` and it went away, but came back on restart

### Actual behaviour

Repeatedly advising me I need to fix my shell

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Max
  - cores: 12
  - mem: 32.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/timfee
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: d88e49dc-7765-4a49-9654-a2f418b32dc4
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.13.1
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/timfee/Library/pnpm:/Users/timfee/.fig/bin:/Users/timfee/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/timfee/.config/zsh
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 1274
    - FIG_SET_PARENT: d88e49dc-7765-4a49-9654-a2f418b32dc4
```

**Comment by LasseMacchiato** [comment]
fig ignores your `$ZDORDIR` environment variable and expects your `.zshrc` in  `/Users/timfee/` instead.

A temporary solution would be to create a symbolic link with `ln -s ~/.config/zsh/.zshrc ~/.zshrc`. This should make the message disappear, though it defeats the purpose of the ZDOTDIR.

**Comment by mschrage** [comment]
This is a good suggestion @LasseMacchiato! We cannot honor `ZDOTDIR` because the context where the check is performed does not have access to this environment variable.

Closing as out of scope for now.
