### ISSUE TITLE
iTerm: Fig appears under the floating hotkey window

### ISSUE THREAD

**Issue by iamakulov** [withfig/fig#2271]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.0 (22D49)

### Expected behaviour

Fig autocomplete should appear above iTerm’s floating window, at all times.

### Actual behaviour

Fig appears below iTerm’s floating window in half of the cases.

<img width="395" alt="Screenshot 2023-01-28 at 1 05 49 PM" src="https://user-images.githubusercontent.com/2953267/215265544-1ebafe9c-896e-47a8-882a-cf08b5d47345.png">

### Steps to reproduce

I can reliably reproduce the issue with the following steps:

1. Make the Hotkey Window profile the default profile
2. Close all iTerm tabs. Then, quit iTerm
3. Launch iTerm by clicking the iTerm icon in the doc
4. Type `code `. Autocomplete appears above the iTerm window (as intended):

   <img width="857" alt="Screenshot 2023-01-28 at 1 08 22 PM" src="https://user-images.githubusercontent.com/2953267/215265724-7e995bbf-1663-490d-beed-8401bdf54070.png">

5. Erase what you typed and press ⌘W to close the tab
6. Press the iTerm hotkey and open the floating window. Type `code `. Autocomplete appears below the iTerm window:

    <img width="858" alt="Screenshot 2023-01-28 at 1 10 06 PM" src="https://user-images.githubusercontent.com/2953267/215265786-cea2cd8c-71f3-481d-b72a-2c731a78a9ea.png">

My iTerm floating window is configured as follows:

<img width="1128" alt="Screenshot 2023-01-28 at 1 12 27 PM" src="https://user-images.githubusercontent.com/2953267/215265833-1d6b0db2-221e-45bc-895f-f59990d2325b.png">

The “Show in All Spaces” workaround from https://github.com/withfig/fig/discussions/135 is enabled and doesn’t help. (I did relaunch the app after enabling it.)

Attaching the exported iTerm profile below (you can import it by going to Profiles → Import JSON Profiles): [Hotkey Window.json.zip](https://github.com/withfig/fig/files/10527213/Hotkey.Window.json.zip)

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 12
  - mem: 32.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /opt/homebrew/Cellar/fish/3.6.0/bin/fish
  - terminal: iterm
  - cwd: /Users/iamakulov
  - exe-path: /Users/iamakulov/.local/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_SET_PARENT: w1t1p0:34079FB1-B846-4E5C-AE83-ADDA19C67125
    - FIG_TERM: 2.13.1
    - FIG_PARENT: 
    - TERM: xterm-256color
    - PATH: /Users/iamakulov/Library/pnpm:/Users/iamakulov/.local/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/iamakulov/.fig/bin
    - SHELL: /opt/homebrew/bin/fish
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIGTERM_SESSION_ID: f3c81ac2-0c76-4e79-8856-91aa1e709dc3
    - FIG_PID: 21290

iTerm version: Build 3.4.19
```

**Comment by eness** [comment]
facing same issue here.

**Comment by grant0417** [comment]
Hey, do you use any window managers such as Rectangle or Amethyst?

**Comment by iamakulov** [comment]
Hey! No, I don’t.

**Comment by thongnguyen-ct** [comment]
i'm facing this issue too

**Comment by NickVCBS** [comment]
This is a persistent issue for myself as well

**Comment by mschrage** [comment]
Okay I can reproduce this! Thanks for the very clear instructions @iamakulov, sorry it took me so long to get around to it.

I'm investigating now.

**Comment by mschrage** [comment]
@grant0417 has found the root cause. This should be live in v2.16.0
