### ISSUE TITLE
error: unrecognized subcommand 'bg:prompt'

### ISSUE THREAD

**Issue by shamimulalam** [withfig/fig#2272]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

I'm not expecting those texts.

### Actual behaviour

error: unrecognized subcommand 'bg:prompt'

Usage: fig [COMMAND]

For more information, try '--help'.

This command may be valid in newer versions of the Fig CLI. Try running fig update.
 shawon@Shamimuls-MBP  ~  fig doctor                                                                                                                  ✔  1003  15:21:57
error: unrecognized subcommand 'bg:exec'

Usage: fig [COMMAND]

For more information, try '--help'.

This command may be valid in newer versions of the Fig CLI. Try running fig update.

✔ Everything looks good!

  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!

error: unrecognized subcommand 'bg:prompt'                                                                                                                                   

Usage: fig [COMMAND]

For more information, try '--help'.

This command may be valid in newer versions of the Fig CLI. Try running fig update.

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: intellij-phpstorm
  - cwd: /Users/shawon
  - exe-path: /Users/shawon/.local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 85725bd6-0aa1-4a93-9fff-f32cdda2461d
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.13.1
    - PATH: /Users/shawon/google-cloud-sdk/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/shawon/.fig/bin:/Users/shawon/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.PhpStorm
    - FIG_PID: 33908
    - FIG_SET_PARENT: 85725bd6-0aa1-4a93-9fff-f32cdda2461d
```

**Comment by grant0417** [comment]
Hey @shamimulalam, we have not used `bg:prompt` or `bg:exec` in over a year, it might you have old files around with it. I would recommend uninstalling fig and reinstalling.
