### ISSUE TITLE
fig creating .bashrc and .profile files when they don't exist

### ISSUE THREAD

**Issue by codyw912** [withfig/fig#2277]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.0 (22D49)

### Expected behaviour

Expect fig to add necessary edits to .zsh and .zprofile files.

### Actual behaviour

Fig is creating and adding pre and post blocks to .bashrc and .profile. Is it necessary to create these files if I'm not using bash and didn't previously have these files?

Deleting these manually makes the fig GUI / fig doctor throw errors and recreate.

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Max
  - cores: 12
  - mem: 64.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/$USERNAME
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: ccb4d0f2-c2b0-46b3-967c-fbd0507123da
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.13.1
    - PATH:
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 74179
    - FIG_SET_PARENT: ccb4d0f2-c2b0-46b3-967c-fbd0507123da
```

**Comment by mschrage** [comment]
This is the expected behavior.
