### ISSUE TITLE
Fig's icon is slightly too big and does not conform to Big Sur standards

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#228]
Fig's icon is slightly bigger than the other apps in Launchpad mode and the dock (although Fig should not be showing in the Dock)

### Launchpad
![image](https://user-images.githubusercontent.com/4949076/123582672-10fb4880-d793-11eb-8a82-e4a7e58cf448.png)

### Docker
![image](https://user-images.githubusercontent.com/4949076/123582747-3ab46f80-d793-11eb-997e-75a7af02a6f2.png)

**Comment by MatejaSrejic** [comment]
Here are 2 ICNS that follow Big Sur's design guidelines:
1) fig logo with a white background - [preview](https://i.imgur.com/0HiEcS6.jpg)
2) fig logo scaled in - [preview](https://i.imgur.com/t6xgYXv.png)

rounded corners and stuff are fixed in the final icns files

https://1drv.ms/u/s!AgjBSc2AbRXWsCsKhnGl1ELuhnNL?e=6BhEeh

**Comment by Nutlope** [comment]
Thanks so much @MatejaSrejic! Hey @mschrage, can we update the fig icon on the macos app?

**Comment by mschrage** [comment]
Hey @MatejaSrejic! Thanks for this. Can you point me to the guidelines on Big Sur icon sizes?

**Comment by MatejaSrejic** [comment]
@mschrage I’m not sure about the sizes, but the ICNS I provided are ready to be imported as an icon.

**Comment by MatejaSrejic** [comment]
I used an app called Image2Icon to transform a PNG into a Big Sur-friendly ICNS

**Comment by MatejaSrejic** [comment]
Here's an iconset (I'm not sure if it works 100%, so backup before importing :) but I didn't see any issues with it)

https://1drv.ms/u/s!AgjBSc2AbRXWsC6OxYH29xlgg2zx?e=1wE6Ks

**Comment by mschrage** [comment]
Amazing!

**Comment by mschrage** [comment]
This will be fixed as of v1.0.47! Thanks again for contributing the icon @MatejaSrejic. I really appreciate it :)
