### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by TheBox193** [withfig/fig#2283]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Ventura 13.0 (22A8380)

### Expected behaviour

App is able to complete onboarding.

### Actual behaviour

Crashes with error: `IntegrationError: Invalid value for elements(): clientSecret should be a client secret of the form ${id}_secret_${secret}. You specified: .`

### Steps to reproduce

1. Install fig
2. Login with github
3. Create a team
4. App briefly shows "choose your plan" then crashes

![image](https://user-images.githubusercontent.com/220755/215886858-cd984cfa-66b4-42fa-9d3f-3cf4badbc113.png)
![image](https://user-images.githubusercontent.com/220755/215886843-41e0a4e9-5727-44d8-ab18-e3e8070ea506.png)

### Environment

```yaml
n/a Fix won't load and `fig` is unavailable in any terminals.
```

**Comment by grant0417** [comment]
Hey @TheBox193 when did this happen for you?

**Comment by TheBox193** [comment]
A couple hours ago when I was setting up things for the first time. Never did make into the app or finish signup. When I restart the app I see it say "choose your plan" but then it crashes.

Fresh computer too. 😜

**Comment by corsen55** [comment]
I have the same issue.  New install via brew.

**Comment by corsen55** [comment]
> I have the same issue. New install via brew.

I fixed by deleting the JSON files and restarting the configuration.

**Comment by Landon-Alo** [comment]
@corsen55 which JSON files did you delete?

**Comment by corsen55** [comment]
> @corsen55 which JSON files did you delete?
> 
> Edit: Nevermind. Found them. They are in the .fig in $HOME.

I'm on a Mac and the files that I removed were from <home_dir>/Library/Application Support/fig
I deleted the credentials.json and state.json so that I could restart from scratch

HTH

**Comment by HendersonTyler** [comment]
The same issue on an m1 mac, just installed via brew and had the error after being prompted to invite team members.

**Comment by kevindees** [comment]
I got the same issue/error after being prompted to invite team members too:

```
IntegrationError: Invalid value for elements(): clientSecret should be a client secret of the form ${id}_secret_${secret}. You specified: .
```

I resolved the issue by removing the `credentials.json` file under `<home_dir>/Library/Application Support/fig`.

<img width="592" alt="Screenshot 2023-02-08 at 8 49 27 AM" src="https://user-images.githubusercontent.com/348368/217548677-c5f79c09-12e1-4c84-89c0-a3f72225413f.png">

**Comment by alirezaopmc** [comment]
Same issue on Macbook Air M2. I just fixed that by following the @kevindees solution:
```bash
cd ~/Library/Application\ Support/fig && rm credentials.json
```

**Comment by mschrage** [comment]
This should be resolved now!
