### ISSUE TITLE
Ctrl-J when bound to 'scroll down' inserts the suggestion rather scrolling down

### ISSUE THREAD

**Issue by mieubrisse** [withfig/fig#2288]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.5.0 (21G72)

### Expected behaviour

1. Bind `ctrl-j` to "scroll down"
2. Press `ctrl-j` in the popup and the selection scrolls down

### Actual behaviour

Pressing `ctrl-j` inserts the current selection

https://www.loom.com/share/7fb73f478452427aabdbe4a46bff4751

NOTES:
- I bound `ctrl-k` to scroll up and this works just fine (in video)
- #2287 is preventing me from getting a passing `fig doctor`, though the Fig popup works normally.

### Steps to reproduce

AFAICT, simply bind `ctrl-j` to "Scroll down" and then try to use it

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 12.5.0 (21G72)
environment:
  - shell: /opt/homebrew/Cellar/bash/5.2.15/bin/bash
  - terminal: iterm
  - cwd: /Users/argos
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /opt/homebrew/bin/bash
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: 175557e0-7eb3-4926-8310-c9d0ab91e2cd
    - FIG_TERM: 2.13.1
    - TERM: xterm-256color
    - FIG_PID: 19819
    - PATH: /Applications/SnowSQL.app/Contents/MacOS:/Users/argos/.nvm/versions/node/v16.13.0/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/argos/.fig/bin:/Users/argos/.local/bin:/usr/local/opt/go@1.13/bin
```

**Comment by mschrage** [comment]
Can you run `fig settings all`?
