### ISSUE TITLE
bug: Permission denied when installing shell integrations

### ISSUE THREAD

**Issue by Mulsi** [withfig/fig#2289]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

M13.1 (22C65)

### Expected behaviour

I expected it to work. I get the following error:
Error: bash (/Users/Miha/.bashrc): IO Error: Permission denied (os error 13)

### Actual behaviour

https://user-images.githubusercontent.com/58010034/216003119-be3e2e36-5cc5-48ce-bc95-ff1e37336cf4.png

### Steps to reproduce

1. Installed fig
2. Moved fig to applications
3. Launched fig
4. Logged in with github profile
5. Immediately get the Installation issue -> fig is not installed correctly.

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/Miha
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 2d5bdde5-c437-4aab-89e4-4dbc58ff09ea
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.13.1
    - PATH: /Users/Miha/.nvm/versions/node/v14.20.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Miha/.fig/bin:/Users/Miha/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 79371
    - FIG_SET_PARENT: 2d5bdde5-c437-4aab-89e4-4dbc58ff09ea
```

**Comment by grant0417** [comment]
Hey @Mulsi, your `.bashrc` probably has permission issues, please run `sudo chown $USER ~/.bashrc` to fix it and then run `fig doctor`
