### ISSUE TITLE
Fig Integration: Figterm is not running in this terminal

### ISSUE THREAD

**Issue by benrfairless** [withfig/fig#2290]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.0 (22D49)

### Expected behaviour

After the installation of fig, I would expect that figterm would start when Terminal was started.

### Actual behaviour

Figterm does not open when Terminal opens.

fig doctor --verbose
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ bash ~/.bashrc integration check
✔ bash ~/.profile integration check
✔ zsh ~/.zshrc integration check
✔ zsh ~/.zprofile integration check

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ PATH contains ~/.fig/bin
✔ Settings Corruption
✔ State Corruption
✘ Fig Integration: Figterm is not running in this terminal, please try restarting your terminal

  FIG_TERM=
✔ SSH integration

Let's make sure Fig is running...
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Daemon diagnostics

Let's see if Fig is in a working state...
✘ Figterm: No FIGTERM_SESSION_ID
  
   0: No FIGTERM_SESSION_ID
   1: environment variable not found

Location:
   fig_cli/src/cli/doctor.rs:649

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
✔ Insertion lock does not exist
✔ Autocomplete dev mode
✔ Plugin dev mode
✔ Dashboard is loading from the correct URL
✔ Autocomplete is loading from the correct URL

Let's check if your system is compatible...
✔ OS is supported
✔ Fish is up to date
✔ Jetbrains Toolbox Check

Let's check fig diagnostic...
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled

Let's check your terminal integrations...
✔ Terminal support

### Steps to reproduce

1. Install fig using brew
2. Run fig install
3. Run fig doctor
4. Run fig restart
5. Restart Terminal

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/benfairless
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: com.apple.Terminal
    - TERM: xterm-256color
    - SHELL: /bin/zsh
    - PATH: /opt/homebrew/opt/php@7.4/sbin:/opt/homebrew/opt/php@7.4/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/benfairless/.local/bin:/Users/benfairless/.fig/bin
```

**Comment by mschrage** [comment]
Try restarting your terminal!
