### ISSUE TITLE
'ApolloError: Bad Credentials' after github re-auth

### ISSUE THREAD

**Issue by arunsingh-me** [withfig/fig#2293]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.0 (22D49)

### Expected behaviour

Fig Dashboard 

### Actual behaviour

<img width="1142" alt="Untitled" src="https://user-images.githubusercontent.com/57107878/216429662-9d194b18-dfc1-4259-8106-1f917ce20b13.png">

### Steps to reproduce

I think doing Github reauth as in revoking the OAuth app's permission then reauthenticating will do. Have tried email auth also but that didn't work either.

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /opt/homebrew/Cellar/zsh/5.9/bin/zsh
  - terminal: iterm
  - cwd: /Users/arunsingh
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /opt/homebrew/bin/zsh
    - __CFBundleIdentifier: com.googlecode.iterm2
    - PATH: /Users/arunsingh/.sdkman/candidates/java/current/bin:/Users/arunsingh/.nvm/versions/node/v18.13.0/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin
    - DISPLAY: /private/tmp/com.apple.launchd.ZdJ8YkCkFv/org.xquartz:0
    - TERM: xterm-256color
```

**Comment by grant0417** [comment]
This should be resolved!
