### ISSUE TITLE
bug: Failed to get context 

### ISSUE THREAD

**Issue by YeeP79** [withfig/fig#2295]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 6.0.12-76060006-generic - "Pop!_OS 22.04 LTS"

### Expected behaviour

Attempted to run `fig doctor` to test setup

### Actual behaviour

`fig diagnostic

fig-details:
  - 2.13.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
  - cores: 8
  - mem: 15.50 GB
os-info:
  - kernel: 6.0.12-76060006-generic
  - distro: "Pop!_OS 22.04 LTS"
  - distro-version: "22.04 LTS"
environment:
  - shell: /usr/bin/bash
  - terminal: <unknown>
  - cwd: /home/yeep
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /bin/bash
    - GTK_IM_MODULE: ibus
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: 919b0272-9677-4e64-8916-f9ca6e598747
    - XMODIFIERS: @im=ibus
    - XDG_SESSION_DESKTOP: pop
    - XDG_SESSION_TYPE: x11
    - XDG_CURRENT_DESKTOP: pop:GNOME
    - FIG_TERM: 2.13.1
    - TERM: xterm-256color
    - FIG_PID: 19026
    - DISPLAY: :1
    - QT_IM_MODULE: ibus
    - PATH: /home/yeep/.nvm/versions/node/v18.9.0/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/yeep/.local/bin:/home/yeep/.fig/bin:/home/yeep/.local/bin:/home/yeep/.local/share/fig/plugins/forgit/bin`

`fig doctor --verbose
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ bash ~/.bashrc integration check
✔ bash ~/.profile integration check

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ Settings Corruption
✔ State Corruption
✔ Fig Integration
✔ SSH integration

Let's make sure Fig is running...
✔ Daemon
✔ Daemon diagnostics

Let's see if Fig is in a working state...
✔ Figterm
✔ Insertion lock does not exist
✔ Autocomplete dev mode
✔ Plugin dev mode
✔ Dashboard is loading from the correct URL
✔ Autocomplete is loading from the correct URL

Let's check if your system is compatible...
● Fig's support for Linux 6.0.12-76060006-generic - "Pop!_OS 22.04 LTS" is in development. It may not work properly on your system.

✔ Fish is up to date

Let's check fig diagnostic...
Failed to get context: 
   0: Connection refused (os error 111)

Location:
   fig_cli/src/cli/diagnostics.rs:87

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!`

Any help is much appreciated, I use fig daily on my work macbook pro, would love to get it working on my personal machine.

Thanks

**Comment by mschrage** [comment]
Autocomplete is not currently supported on Linux.
