### ISSUE TITLE
Autocomplete not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by muskScent** [withfig/fig#2298]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 5.15.0-58-generic - "Ubuntu"

### Expected behaviour

The autocomplete feature should work.

### Actual behaviour

It's not working.

Here is the result of the fig doctor --verbose command:

Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ bash ~/.bashrc integration check
✔ bash ~/.profile integration check
● /home/othmane/.zshrc does not source pre integration
✔ zsh ~/.zprofile integration check

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ Settings Corruption
✔ State Corruption
✔ Fig Integration
✔ SSH integration

Let's make sure Fig is running...
✔ Daemon
✔ Daemon diagnostics

Let's see if Fig is in a working state...
✔ Figterm
✔ Insertion lock does not exist
✔ Autocomplete dev mode
✔ Plugin dev mode
✔ Dashboard is loading from the correct URL
✔ Autocomplete is loading from the correct URL

Let's check if your system is compatible...
● Fig's support for Linux 5.15.0-58-generic - "Ubuntu" is in development. It may not work properly on your system.

✔ Fish is up to date

Let's check fig diagnostic...
✘ Autocomplete is active: Autocomplete is currently inactive. Your desktop integration(s) may be broken!

Let's check your terminal integrations...
✔ Terminal support

Let's check Linux integrations
✔ IBus Env Check
✔ IBus Check
✔ Fig is not running in a sandbox

  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  - cores: 2
  - mem: 7.62 GB
os-info:
  - kernel: 5.15.0-58-generic
  - distro: "Ubuntu"
  - distro-version: "22.04.1 LTS (Jammy Jellyfish)"
environment:
  - shell: /usr/bin/bash
  - terminal: hyper
  - cwd: /home/othmane/workspace/udemy-courses/ethereum-solidity/new-nft-marketplace
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /usr/bin/zsh
    - GLFW_IM_MODULE: ibus
    - GTK_IM_MODULE: ibus
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: f5ed2987-06ae-4c36-b4a1-3494d0529ad8
    - XMODIFIERS: @im=ibus
    - XDG_SESSION_DESKTOP: ubuntu
    - XDG_SESSION_TYPE: wayland
    - FIG_SET_PARENT: f5ed2987-06ae-4c36-b4a1-3494d0529ad8
    - XDG_CURRENT_DESKTOP: Unity
    - FIG_TERM: 2.13.1
    - TERM: xterm-256color
    - FIG_PID: 20398
    - DISPLAY: :0
    - QT_IM_MODULE: ibus
    - PATH: /home/othmane/go/bin:/usr/local/go/bin:/home/othmane/go/bin:/usr/local/go/bin:/home/othmane/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/othmane/.local/bin:/home/othmane/.fig/bin
```

**Comment by iblancoi** [comment]
Same problem here!
