### ISSUE TITLE
[BUG] Autocomplete does not work with certain external keyboards

### ISSUE THREAD

**Issue by falky97** [withfig/fig#23]
When Fig's autocomplete widget pops up, users are able to select suggestions using tab, enter, or clicking.

It seems like Fig does not pick up the `tab` or `enter` events from certain external keyboards. If a user with one of these keyboards tries `tab` or `enter` it will just close the popup but will not insert the selected text.

We are investigating the fix.

In the meantime, here are some of the keyboards we have heard don't work:
* [Das Model S](https://www.bhphotovideo.com/c/product/1353419-REG/das_keyboard_dask3proms1maccli_model_s_professional_for.html/?ap=y&msclkid=8fe2174f1558167b027e775c1e6fdbfb&smp=y)
* Keychron K2 (unsure of specific models)

Please share more keyboards and their versions below. Also subscribe to this issue so you can get notified when they have been fixed 😄

**Comment by thepeoplesbourgeois** [comment]
Possibly also the [Apple a1048](https://www.ifixit.com/Device/Apple_Keyboard_A1048)?

**Comment by falky97** [comment]
This bug should have been fixed. It turns out it wasn't a keyboard issue, but rather, an issue with the way Fig inserted text into the terminal... 

If you can use Fig with your mac Keyboard but not your external keyboard, please comment and we will reopen this issue.
