### ISSUE TITLE
Fig dashboard showing blurred and iTerm Bash Integration is out of date

### ISSUE THREAD

**Issue by raulperula** [withfig/fig#2300]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.3 (21G419)

### Expected behaviour

Issue 1. Fig Dashboard should be showing the window in a clear way.
Issue 2. `fig doctor` should not show errors on iTerm Bash Integration.

### Actual behaviour

Can't see in a clear way the Fig app window.

Also, got an error message about iTerm Bash Integration being out of date:

✘ iTerm bash integration configured: iTerm Bash Integration is out of date. Please update in iTerm's menu by selecting "Install Shell Integration". For more details see https://iterm2.com/documentation-shell-integration.html

✘ Doctor found errors. Please fix them and try again.

### Steps to reproduce

**Issue 1**

1. Open Fig Dashboard from bar menu or in a terminal by the `fig` command.

**Issue 2**

1. Open iTerm2 (Build 3.4.19)
2. Click on "Install Shell Integration" (from any different available option) and follow the steps.
3. Restart iTerm
4. Run `fig doctor`
5. See the error message

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
  - cores: 2
  - mem: 16.00 GB
os-info:
  - macOS 12.6.3 (21G419)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/raules
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 213a0742-be2e-4552-8e83-f38e9b3d7448
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.13.1
    - PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/raules/Library/Python/2.7/bin:/Library/TeX/texbin:/Users/raules/.fig/bin:/Users/raules/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 48113
    - FIG_SET_PARENT: 213a0742-be2e-4552-8e83-f38e9b3d7448
```

**Comment by raulperula** [comment]
I attach an image of how I see the Fig Dashboard.

<img width="1023" alt="Captura de Pantalla 2023-02-04 a las 15 09 21" src="https://user-images.githubusercontent.com/6907809/216772666-f0507dba-5d0a-4972-9593-6a6fa013e621.png">

**Comment by Gasman2014** [comment]
w.r.t. the 'iTerm2 bash integration is out of date' error. 

Fig only seems to check for the presence and currency of the **.bash** version of the integrations. The 'out of date' error goes away if you simply download and save (but don't even source) the _bash_ shell integration.

For instance, this eliminates the error

`curl -L https://iterm2.com/shell_integration/bash -o ~/.iterm2_shell_integration.bash`

Fig appears to expect that shell integration for _bash_ is required, however that may not be the shell actually in use - macOS has used _zsh_ as the standard shell for a few years now.

Fig doctor should check which shell is in play before marking this as an error - perhaps by checking the shell with` ps -o comm= $$  ` Additionally, it should check that the correct integration package for the shell is installed. i.e. `.iterm2_shell_integration.bash` for `bash`, `.iterm2_shell_integration.zsh` for `zsh` etc.

Generally `fig doctor` would be invoked from the same terminal that has the integrations installed. (Accepted that his could break if invoking a remote `ssh` terminal or `xterm` but this is pretty niche and could be addressed by a more explicit error message).

**Comment by stephenfeather** [comment]
@Gasman2014 Wow!  Thanks for the information! One problem down, a BUNCH more to solve.
