### ISSUE TITLE
bug: Why is the screen of the Fig Dashboard App covered by blur?

### ISSUE THREAD

**Issue by chebread** [withfig/fig#2303]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Bug
MacOS ventura 13.2

The Dashborad app is provided blurry and cannot be used properly.
I'm not sure how the hell to solve this. It doesn't seem like this issue has been reported anywhere.

<img width="760" alt="스크린샷 2023-02-05 오전 1 57 31" src="https://user-images.githubusercontent.com/83535893/216780128-99858576-94ab-4e0e-9389-0c942efbd9a2.png">

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/ihaneum
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 56cef3d0-8052-432a-972e-03f79dc5442f
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.13.1
    - PATH: (Private)
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 8377
    - FIG_SET_PARENT: 56cef3d0-8052-432a-972e-03f79dc5442f
```

**Comment by reno** [comment]
Same problem here with MacOS Monterey 12.5

**Comment by FrideyAlpha** [comment]
Yes, the Fig dashboard blurs for me as well.
Here is a short-term solution:
- Click the inspect element option from the context menu of the fig dashboard.
- Search for `<div class="h-full w-full flex transition-[filter] blur-sm" style="transform: translateZ(0px);">`  and uncheck —tw-blur
<img width="1723" alt="Screenshot 2023-02-05 at 23 23 06" src="https://user-images.githubusercontent.com/20950458/216831421-f513dd6d-1cf7-4853-8078-89578a1bfafd.png">

<img width="1723" alt="Screenshot 2023-02-05 at 23 21 40" src="https://user-images.githubusercontent.com/20950458/216831313-22cb8862-e67f-4f97-aba3-7a3a2ced0ec4.png">

This is what I did until a solution to the problem was found.

**Comment by mohammad-adk** [comment]
> Yes, the Fig dashboard blurs for me as well. Here is a short-term solution:
> 
> * Click the inspect element option from the context menu of the fig dashboard.
> * Search for `<div class="h-full w-full flex transition-[filter] blur-sm" style="transform: translateZ(0px);">`  and uncheck —tw-blur
> 
> <img alt="Screenshot 2023-02-05 at 23 23 06" width="1723" src="https://user-images.githubusercontent.com/20950458/216831421-f513dd6d-1cf7-4853-8078-89578a1bfafd.png">
> 
> <img alt="Screenshot 2023-02-05 at 23 21 40" width="1723" src="https://user-images.githubusercontent.com/20950458/216831313-22cb8862-e67f-4f97-aba3-7a3a2ced0ec4.png">
> 
> This is what I did until a solution to the problem was found.

Worked for me, Thanks

**Comment by chebread** [comment]
Since sometime this bug has been fixed.
Are other people like that too?
I will close this issue if other people have also solved this issue.

**Comment by chebread** [comment]
Is there anyone here who only shows script and settings in Fig Dashboard App sidebar? I don't see anything like the plugin store.
I'm not sure why this is!

**Comment by pimmee** [comment]
I downloaded Fig for the first time on a MacOS Ventura 13.1 today (`brew install fig`) and it is blurry for me.

```bash
➜  ~ fig --version
fig_cli 2.13.1
```

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/33460567/217083546-eb315458-3ea8-49e8-8819-0ee648090706.png">

**Comment by chebread** [comment]
> 오늘( ) MacOS Ventura 13.1에서 처음으로 Fig를 다운로드 했는데 흐릿합니다.`brew install fig`
> 
> ```shell
> ➜  ~ fig --version
> fig_cli 2.13.1
> ```
> 
> <img alt="영상" width="1025" src="https://user-images.githubusercontent.com/33460567/217083546-eb315458-3ea8-49e8-8819-0ee648090706.png">
> 
> 관련이 있는지는 모르겠지만 회원가입 `email`+ 코드입력시 와 같은 에러가 뜨고 이후 화면이 흐릿하게 표시됩니다.`"Database error, Sentry ID: ***"`

See @FrideyAlpha's answer above for this error.
> Click the inspect element option from the context menu of the fig dashboard.
> Search for <div class="h-full w-full flex transition-[filter] blur-sm" style="transform: translateZ(0px);"> and uncheck —tw-blur

**Comment by chebread** [comment]
> I downloaded Fig for the first time on a MacOS Ventura 13.1 today (`brew install fig`) and it is blurry for me.
> 
> ```shell
> ➜  ~ fig --version
> fig_cli 2.13.1
> ```
> 
> <img alt="image" width="1025" src="https://user-images.githubusercontent.com/33460567/217083546-eb315458-3ea8-49e8-8819-0ee648090706.png">
> 
> I don't know if it's related, but when signing up with `email` + entering code I got an error saying something like `"Database error, Sentry ID: ***"`, after that the blurry screen was displayed.

Are you having the same problem I'm having?
> Is there anyone here who only shows script and settings in Fig Dashboard App sidebar?
> I don't see anything like the plugin store.

**Comment by pimmee** [comment]
@chebread I have the same problem as @FrideyAlpha, i.e. blurry Fig application. The `Inspect element` + remove style workaround worked for me. I would assume the blurriness is due to the same core issue as what you encountered.

**Comment by grant0417** [comment]
Think I have found the issue here and resolved it, please let me know if its resolved for you!

**Comment by chebread** [comment]
That issue of blurring has been resolved. However, there is a new problem with essential elements not appearing in the sidebar. This issue will create a new issue.
