### ISSUE TITLE
Open CLI Tools

### ISSUE THREAD

**Issue by alejss** [withfig/fig#2307]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.0 (22D49)

### Expected behaviour

Open my scripts inside a CLI Tools.

### Actual behaviour

Closes the selected CLI tool and indicates an error message.

<img width="690" alt="Captura de pantalla 2023-02-06 a la(s) 09 48 52" src="https://user-images.githubusercontent.com/35987478/217018228-6e16448d-5b6e-4ee2-8baa-20f3590b42d3.png">

### Steps to reproduce

1. Open any CLI tool
2. Click to any script or edit script
3 .I am re sent to home and it shows the error message

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/alejss
  - exe-path: /Users/alejss/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: ec2761e2-8054-4f72-b317-bcecb9131a9f
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.13.1
    - PATH: /Users/alejss/.nvm/versions/node/v19.1.0/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alejss/.fig/bin:/Users/alejss/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 2961
    - FIG_SET_PARENT: ec2761e2-8054-4f72-b317-bcecb9131a9f
```

**Comment by grant0417** [comment]
Hey @alejss this should be resolved now, sorry for the trouble!
