### ISSUE TITLE
Can't access dashboard anymore

### ISSUE THREAD

**Issue by Tooommm** [withfig/fig#2310]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.0 (22D49)

### Expected behaviour

See dashboard and other menu in fig UI

### Actual behaviour

Only 2 tabs in the UI Script & CLI's and Settings

### Environment

```yaml
fig-details:
  - 2.14.0-beta.6
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/thomas
  - exe-path: /Users/thomas/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: f047140a-a343-4c89-baee-91bd34ad4433
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.0-beta.6
    - PATH: /Users/thomas/.docker/bin:/Users/thomas/Library/pnpm:/Users/thomas/.pyenv/shims:/Users/thomas/Library/Caches/fnm_multishells/758_1675710615393/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/thomas/.fig/bin:/Users/thomas/.local/bin:/Users/thomas/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 684
    - FIG_SET_PARENT: f047140a-a343-4c89-baee-91bd34ad4433
```

**Comment by grant0417** [comment]
Hey @Tooommm, we are doing a launch for our scripts product soon so we reorganized the dashboard, if you dont see everything please run `fig settings app.showAllProducts true`
