### ISSUE TITLE
Not working after installation

### ISSUE THREAD

**Issue by xentenario** [withfig/fig#2314]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 5.15.0-58-generic - "Ubuntu"

### Expected behaviour

I was expecting to see the autocomplete. 

### Actual behaviour

nothing happen.

### Steps to reproduce

install fig
run any command
ls or cd

I ran fig restart  and got the following. 
**failed to launch fig: `launching Fig from headless installs is not yet supported`**

### Environment

```yaml
fig-details:
  - 2.14.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: 
  - cores: 2
  - mem: 18.20 GB
os-info: Ubuntu
  - kernel: 5.15.0-58-generic
  - distro: "Ubuntu"
  - distro-version: "22.04.1 LTS (Jammy Jellyfish)"
environment:
  - shell: /usr/bin/bash
  - terminal: <unknown>
  - cwd: /home/parallels/code
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /bin/bash
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: 9969f076-1639-44e8-9e0d-7f4349779349
    - XMODIFIERS: @im=ibus
    - XDG_SESSION_DESKTOP: ubuntu
    - XDG_SESSION_TYPE: wayland
    - XDG_CURRENT_DESKTOP: ubuntu:GNOME
    - FIG_TERM: 2.14.0
    - TERM: xterm-256color
    - FIG_PID: 4367
    - DISPLAY: :0
    - QT_IM_MODULE: ibus
    - PATH: /home/parallels/.nvm/versions/node/v19.2.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/parallels/.local/bin:/home/parallels/.fig/bin
```

**Comment by grant0417** [comment]
Hey @xentenario, we don't currently support Linux for autocomplete, we only install the CLI which allows you to use our other products, if you interested in it still fill out the survey on this page: https://fig.io/download
