### ISSUE TITLE
bug: Bug where features such as plugin store are not displayed in sidebar of Fig Dashboard App

### ISSUE THREAD

**Issue by chebread** [withfig/fig#2315]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS ventura 13.2

### Bug

As said in the middle of  [#2303](https://github.com/withfig/fig/issues/2303#issuecomment-1419295734), The Fig Dashboard App sidebar only shows scripts and settings, no other features (plugin store, etc.).

Can anyone help me solve this?

### Environment

```yaml
fig-details:
  - 2.13.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/ihaneum
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 56cef3d0-8052-432a-972e-03f79dc5442f
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.13.1
    - PATH: (Private)
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 8377
    - FIG_SET_PARENT: 56cef3d0-8052-432a-972e-03f79dc5442f```

**Comment by grant0417** [comment]
Hey @chebread, this isn't a bug, we are launching on ProductHunt soon and wanted to focus everyone to scripts, you can show all the products by running `fig settings app.showAllProducts true`

**Comment by brendanfalk** [comment]
You'll also probably have to run `fig restart` to make sure it works

**Comment by brendanfalk** [comment]
https://github.com/withfig/fig/issues/2316 Should explain everything in more depth! Sorry about this issue
