### ISSUE TITLE
Unable to access Dotfiles, Autocomplete, Plugin Store, and Servers in Fig Dashboard Sidebar

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#2316]
### Summary
The Fig team is currently running an experiment where we are only showing the [Fig Scripts](https://fig.io/scripts) product to new users in the Fig Dashboard. ie New users are temporarily not able to access Fig [Autocomplete](https://fig.io/user-manual/autocomplete), [Access](https://fig.io/user-manual/access), [Plugins](https://fig.io/user-manual/plugins), or [Dotfiles](https://fig.io/user-manual/dotfiles) from the Dashboard.

### Who is affected?
All users who sign up for the first time after 12:01am Monday Feb 6th are part of the experiment. Existing users are not affected.

### How long will it last?
Currently the experiment is planned for Mon Feb 6th - Sunday Feb 13th.

### Why are you doing this?
We are really doubling down on Fig Scripts. In fact, [we just launched it on Product Hunt](https://producthunt.com/posts/fig-scripts). It is our first major product geared towards teams and want to get as much feedback as possible as quickly as possible. We build a LOT of stuff. We are a small team and temporarily limiting the surface area of what we build will help us greatly.

### Can I still enable these products during experiment?
Yes! If you're particularly eager, running the following will re-enable all hidden products. 
```
fig settings app.showAllProducts true;
fig restart
```
Please comment and questions below or give a 👍 if this helped you!

**Comment by grant0417** [comment]
This experiment is now done, closing the issue
