### ISSUE TITLE
Fig is not working imeediately after launch iTerm2

### ISSUE THREAD

**Issue by teziovsky** [withfig/fig#2321]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.0 (22D49)

### Expected behaviour

Fig autocompletions runs immediately all the time.

### Actual behaviour

I need to run `fig doctor` and `fig restart` to make fig autocompletions work properly after every restart of `iTerm2` and `VS Code`

### Steps to reproduce

Just open `iTerm2` and type `cd `.

### Environment

```yaml
fig-details:
  - 2.14.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/kuba/.vscode-insiders
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 27414fb8-d720-4573-a88b-24c8566635f5
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.0
    - PATH: /Users/kuba/.nvm/versions/node/v18.12.1/bin:/Users/kuba/Library/pnpm:/usr/local/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/sbin:/usr/local/opt/ruby@2.7/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/.local/bin:/.fig/bin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/kuba/.cargo/bin:/Users/kuba/.fig/bin:/Users/kuba/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 2000
    - FIG_SET_PARENT: 27414fb8-d720-4573-a88b-24c8566635f5
```

**Comment by danielhalasz** [comment]
I have the same issue on an M1

**Comment by eness** [comment]
I have same issue. Fig is great but kind of buggy on iTerm and zsh.

**Comment by chebread** [comment]
I don't have this bug. How should I reproduce it?

**Comment by teziovsky** [comment]
> I don't have this bug on my M1 Mac. How should I reproduce it?

I don't know. All I did was install fig via homebrew with the command `brew install fig`. That's all.

**Comment by genshinw** [comment]
I have same issue. Is there any solution?

**Comment by rbullers** [comment]
Same issue here, Autocomplete dropdown just doesn't appear anymore

**Comment by emewjin** [comment]
Same issue here

fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 12.2.1 (21D62)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh

**Comment by chebread** [comment]
@teziovsky, I didn't have this problem originally. However, recently this bug has occurred. However, when I replaced the zsh plugin inside Fig with a Zsh plugin, this bug disappeared. I believe this bug is a Zsh plugin error.
I didn't have this problem originally. However, recently this bug has occurred. However, when I replaced the zsh plugin inside Fig with a Zsh plugin, this bug disappeared. I believe this bug is a Zsh plugin error.

**Comment by teziovsky** [comment]
@chebread I don't have any plugin which is installed with Fig. I just installed fig by `brew install fig` and nothing else 🤔
But It's weird because one day it works properly and at another not 🤔

**Comment by klimov-ankr** [comment]
I have the same issue on an M1

**Comment by easylee1996** [comment]
I have the same issue on mac

**Comment by Karan-S-Mittal** [comment]
I am facing the same issue on my M1 Mac. I used brew to install fig and expected it to work in my iterm2 and terminal but it doesn't work even after restarting the shell.

**Comment by EugenEistrach** [comment]
Same issue on m2 mac. It works in webstorm, and vscode. But iterm2 is really unreliable. Sometimes it works (right after pc restart) but after some time it stops working.

**Comment by rbullers** [comment]
I'm using iTerm Build 3.4.19. Fig seems to work correctly if I enter a space before typing any command, 



![output](https://github.com/withfig/fig/assets/88460527/4f74b0a3-2a3f-4948-804b-b5aaec15318a)

**Comment by grant0417** [comment]
Can anyone here share their prompt.

**Comment by Karan-S-Mittal** [comment]
So, I reinstalled fig, restarted the laptop once, and it started working for me in iterm2 and terminal on my m1 mac.

**Comment by Kevin-Shiuan** [comment]
I have same problem on m1 Macbook air

**Comment by simplenotezy** [comment]
Hey @teziovsky why was this issue closed? It's not really working for me either

**Comment by teziovsky** [comment]
I closed this issue because I'm no longer using fig 🤷🏼‍♂️ But I can leave it opened if you want 🤔

**Comment by y3llow-flash** [comment]
Mine wasn't working either and I'm on a 2019 Mac. In iTerm2 type fig restart if you're having this issue. That fixed it for me.

**Comment by BILDIT-LLC** [comment]
fig restart fixed it for me.
