### ISSUE TITLE
bug: Headless installs not supported

### ISSUE THREAD

**Issue by diego-rapoport** [withfig/fig#2323]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

ArchLabs Linux

### Expected behaviour

Should run fig

### Actual behaviour

Outputs: `error: failed to launch fig: 'launching Fig from headless installs is not yet supported'`

### Steps to reproduce

Just ran fig and fig restart and got the same output. I'm using qtile as my window manager. Tried with both alacritty and wezterm.

### Environment

```yaml
fig-details:
  - 2.12.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  - cores: 2
  - mem: 23.34 GB
os-info:
  - kernel: 6.1.9-zen1-2-zen
  - distro: "ArchLabs Linux"
  - distro-version: 2020.05.04
environment:
  - shell: /usr/bin/bash
  - terminal: <unknown>
  - cwd: /home/dinhego
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /bin/bash
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: 998e0d11-eafb-4f1f-8a55-cdda1b868740
    - XDG_SESSION_TYPE: tty
    - FIG_TERM: 2.12.0
    - TERM: xterm-256color
    - FIG_PID: 42131
    - DISPLAY: :0
    - PATH: /usr/share/pyenv/plugins/pyenv-virtualenv/shims:/home/dinhego/.pyenv/shims:/home/dinhego/.cargo/bin:/home/dinhego/.sdkman/candidates/java/current/bin:/usr/share/pyenv/plugins/pyenv-virtualenv/shims:/home/dinhego/.nvm/versions/node/v16.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/dinhego/.fzf/bin:/home/dinhego/Programação/Scripts:/home/dinhego/.local/bin:/home/dinhego/go/bin:/home/dinhego/.fig/bin
```

**Comment by sksoumik** [comment]
Same issue on Ubuntu 20.04.3 LTS

**Comment by amitkarpe** [comment]
Same issue on "VERSION="20.04.5 LTS (Focal Fossa)""

**Comment by mschrage** [comment]
Launching the Fig Dashboard from headless installs is not currently supported.
