### ISSUE TITLE
cd Issue

### ISSUE THREAD

**Issue by galenqq** [withfig/fig#233]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hey guys!

Fig didn't work when I changed my directory to desktop and then tried to see autocomplete options for cd:
<img width="565" alt="Screen Shot 2021-06-29 at 3 45 58 PM" src="https://user-images.githubusercontent.com/7072714/123818886-f8884c80-d8be-11eb-9d2e-ccd51f1af131.png">

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.45 (B218)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.45 (B218) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Galen/.fig/bin/fig
Accessibility: true
Number of specs: 126
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/Galen/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mattschrage** [comment]
Can you run `fig diagnostic` in the terminal where this is happening? This issue can occur if the shell integration isn't set up properly.

**Comment by EmilePerron** [comment]
Hey folks! 

I just downloaded Fig and ran into the same issue. Here's a screen recording of the issue happening:

![2021-07-01 11 17 03](https://user-images.githubusercontent.com/9383532/124148804-02948180-da5e-11eb-98ed-fd0c1db74aaa.gif)


Here are the diagnostics result:
```
Version 1.0.45 (B218) [Canadian French - CSA] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/emile/.fig/bin/fig
Accessibility: true
Number of specs: 129
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/emile/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (10939) - ttys003
Current working directory: /Users/emile/Desktop/tmp/figtest
Current window identifier: 7033/% (com.apple.Terminal)
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
FIG_INTEGRATION_VERSION: ???
```

Seems like the current working directory isn't being updated when changing directory.

**Comment by mattschrage** [comment]
Hey @EmilePerron thanks for reporting!

Something that is standing out to me based on the output from the diagnostic is that `FIG_INTEGRATION_VERSION` is not set. This is an environment variable that is set when Fig's shell integration is loaded. It seems like this isn't happening.

Can you run `env | grep FIG` in your terminal and share the output?

**Comment by EmilePerron** [comment]
Hey @mattschrage,

The output is nothing at all: there are no environment variables with FIG in the name.

**Comment by mattschrage** [comment]
Can you share your .zshrc? Do you see the following line:
```
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
```

If not, try running `fig util:install-script` and then restart your terminal.

**Comment by EmilePerron** [comment]
I don't have a `.zshrc`.
I tried running `fig util:install-script` and restarting the terminal, but the issue remained.

Creating an empty `.zshrc` file (`touch ~/.zshrc`), running the command again and restarting my terminal did fix the issue, however. 👍

**Comment by mattschrage** [comment]
That's correct, we don't create a `.zshrc` file when one doesn't exist. Would you expect us to create it for you automatically? 

I think we used to create dotfiles but depending on the user's existing config files, this could [change behavior](https://blog.flowblok.id.au/2013-02/shell-startup-scripts.html). For instance, when we created `.bashrc` that could prevent `.bash_profile` from running.

PS. Do you have a `.zprofile` file?

**Comment by mschrage** [comment]
We now create `.zshrc` and `.bashrc` files (if they don't exist) as part of our install script!
