### ISSUE TITLE
bug: compatibility issue with fnm

### ISSUE THREAD

**Issue by jwyce** [withfig/fig#2331]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS Ventura M1

### Expected behaviour

With fnm (https://github.com/Schniz/fnm) and fig latest version installed and configured. fnm should be able to switch versions of node with `fnm use <version>`. More specifically fnm should be evaluated in my .zshrc by the time I use the `use` function even when surrounded by fig's pre and post blocks.

### Actual behaviour

See cross-issue to fnm's repo here: https://github.com/Schniz/fnm/issues/927

Essentially, `fnm use <version>` breaks because fnm is not evaluated despite it being configured in my .zshrc. If I manually evaluate it with `eval "$(fnm env --use-on-cd)"` before using `fnm use` it works just fine. Also, if I remove fig's pre and post blocks from my .zshrc and .profile fnm behaves as expected so I'm led to believe whatever magic is going on in my .zshrc fig config isn't playing nice with fnm. 

my trimmed down .zshrc looks like this 
```shell
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
# Load Antigen
source "$HOME/antigen.zsh"

# Load Antigen configurations
antigen init ~/.antigenrc

export DOT=$HOME/.dotfiles
export ZSHRC=$DOT/.zshrc
export BIN=$DOT/bin/scripts
export PATH="$BIN:$PATH"

eval "$(fnm env --use-on-cd)"
eval "$(starship init zsh)"

# Enable vi mode
bindkey -v

# rebind atuin
ATUIN_NOBIND=1 eval "$(atuin init zsh)"
bindkey '^r' _atuin_search_widget

export PATH="$PATH:/Users/wabamn/.bin"
# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
```

and I have the following .zprofile

```shell
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zprofile.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zprofile.pre.zsh"
eval "$(/opt/homebrew/bin/brew shellenv)"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zprofile.post.zsh" ]] && builtin source "$HOME/.fig/shell/zprofile.post.zsh"
```

### Steps to reproduce

1. install and configure the latest version of fig
2. install and configure the latest version of fnm
3. install 2 different versions of node through fnm
4. navigate to a node project
5. attempt to switch version of node with `fnm use <version>`

![image](https://user-images.githubusercontent.com/16946573/218330513-f015996e-4df3-4fee-8f5d-59e3b873972a.png)

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/wabamn/dev/playground/t3-app
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: fd8cbeed-4b29-4065-8aec-2fd647a12aac
    - FIG_PID: 8226
    - FIG_SET_PARENT: fd8cbeed-4b29-4065-8aec-2fd647a12aac
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.0
    - FIG_TERM_TMUX: 2.14.0
    - PATH: /Users/wabamn/Library/Caches/fnm_multishells/8237_1676226441668/bin:/Users/wabamn/.dotfiles/bin/scripts:/Users/wabamn/.deno/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Applications/flameshot.app//Contents/MacOS/:/Users/wabamn/Library/Caches/fnm_multishells/62689_1676128194430/bin:/Users/wabamn/.dotfiles/bin/scripts:/Users/wabamn/Library/Caches/fnm_multishells/60381_1676128062046/bin:/Users/wabamn/Library/Caches/fnm_multishells/21353_1676087461348/bin:/Users/wabamn/Library/Caches/fnm_multishells/20599_1676087427057/bin:/Users/wabamn/Library/Caches/fnm_multishells/20374_1676087415858/bin:/Users/wabamn/Library/Caches/fnm_multishells/16049_1676087255907/bin:/Users/wabamn/Library/Caches/fnm_multishells/13836_1676087220674/bin:/Users/wabamn/Library/Caches/fnm_multishells/5472_1676086652885/bin:/Users/wabamn/Library/Caches/fnm_multishells/5392_1676086650710/bin:/Users/wabamn/Library/Caches/fnm_multishells/1027_1676086537689/bin:/Users/wabamn/Library/Caches/fnm_multishells/1010_1676086537683/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/wabamn/Library/Caches/fnm_multishells/487_1676086523762/bin:/Users/wabamn/Library/Caches/fnm_multishells/448_1676086523754/bin:/Users/wabamn/Library/Caches/fnm_multishells/399_1676086518883/bin:/Users/wabamn/Library/Caches/fnm_multishells/340_1676086518874/bin:/Users/wabamn/Library/Caches/fnm_multishells/92537_1676086254022/bin:/Users/wabamn/Library/Caches/fnm_multishells/92512_1676086254015/bin:/Users/wabamn/Library/Caches/fnm_multishells/88713_1676086154898/bin:/Users/wabamn/Library/Caches/fnm_multishells/78485_1676085856129/bin:/Users/wabamn/Library/Caches/fnm_multishells/77418_1676085827959/bin:/Users/wabamn/Library/Caches/fnm_multishells/3161_1675950191341/bin:/Users/wabamn/.cargo/bin:/Users/wabamn/.fig/bin:/Users/wabamn/.local/bin:/Users/wabamn/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/wabamn/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/Users/wabamn/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/Users/wabamn/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker:/Users/wabamn/.antigen/bundles/zsh-users/zsh-completions:/Users/wabamn/.antigen/bundles/zsh-users/zsh-autosuggestions:/Users/wabamn/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/wabamn/.bin:/opt/homebrew/bin/brew:/Users/wabamn/.bin
    - SHELL: /bin/zsh
    - TERM: screen-256color
    - __CFBundleIdentifier: co.zeit.hyper
```

**Comment by jwyce** [comment]
Going to paste my comment from https://github.com/Schniz/fnm/issues/927 in case someone comes here looking for an answer or if the fig team thinks this warrants looking into further

> So I think I found my issue. fig does some weird tracking of your shell environment and caches it in /Users/<name>/Libray/Application Support/fig/shells and the state.json file one directory up.
> 
> I found this out when setting up a new computer with a different username and when I ran fnm env the user for my old computer was in the FNM_DIR. Manually doing a find a replace for the new user name fixed it for my new computer, but I'm thinking maybe doing a reinstall of fnm got out of sync with fig's caching.

**Comment by mschrage** [comment]
It looks like you imported environment variables into Fig's dotfiles product and these are overriding values set by `fnm`.

If you remove `FNM_*` environment variables from Fig's Dotfiles, `fnm` should work as expected.
