### ISSUE TITLE
Fig desktop is throwing transaction finished after changing Team Username

### ISSUE THREAD

**Issue by maciejpigulski** [withfig/fig#2335]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.0 (22D49)

### Expected behaviour

After changing Team Username I was expecting that subcommand will be added.

### Actual behaviour

An error keeps being shown to me and change is not applied:

![image](https://user-images.githubusercontent.com/7657893/218420046-c6f5723c-da72-4349-a05a-dac92f852da2.png)

Command line returns this `error: Graphql error: namespace/commandlineTool/flattenedCommands/0/subcommands:31:5: Transaction API error: Transaction already closed: Could not perform operation.`

### Steps to reproduce

1. Create a Team, create a new CLI, add some scripts.
2. Change Team name.
3. Try to add a subcommand to existing command.

This should be reproducible with other editing actions as well.

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/mpi/.fig/logs
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 2acb3588-3f67-4caf-a106-a22d11489fb0
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /Users/mpi/Library/Android/sdk/cmdline-tools/latest/bin:/Users/mpi/Library/Android/sdk/tools/bin:/Users/mpi/Library/Android/sdk/platform-tools/:/Users/mpi/Library/Android/sdk/emulator/:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/mpi/.fig/bin:/Users/mpi/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 13840
    - FIG_SET_PARENT: 2acb3588-3f67-4caf-a106-a22d11489fb0
```

**Comment by grant0417** [comment]
Hey @maciejpigulski, is this still happening for you?

**Comment by maciejpigulski** [comment]
It has been resolved it seems, now I am able to edit the commands without the issues mentioned.
