### ISSUE TITLE
Fig stops working, when Raycast triggers while Fig is active

### ISSUE THREAD

**Issue by geggo98** [withfig/fig#2339]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.2 (21G320)

### Expected behaviour

I still can still use Fig completion, after opening and closing a Raycast launcher window.

### Actual behaviour

When I open [Raycast](https://www.raycast.com/), while the Fig completion window is still open, I cannot trigger any other Fig completion anymore, until I restart Fig.

### Steps to reproduce

1. Open the terminal
2. Trigger a completion
3. The Fig completion window appears
4. Triggers the [Raycast](https://www.raycast.com/) launcher window (e.g. pressing Alt+Space)
5. At the same time, the Fig completion window disappears
6. Close the Raycast window and go back to the terminal
7. Try to trigger another completion

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.6.2 (21G320)
environment:
  - shell: /nix/store/g0hnxj2wyn07gfd9svbrh4wsb9g5wxql-fish-3.5.1/bin/fish
  - terminal: iterm
  - cwd: /Users/stefan.schwetschke/tmp
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - TERM: xterm-256color
    - SHELL: /bin/zsh
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_SET_PARENT: w0t7p0:A6EF349C-5032-45A8-90D3-612CBF597F22
    - PATH: /Users/stefan.schwetschke/.rd/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/stefan.schwetschke/.deno/bin:/run/current-system/sw/bin:/Users/stefan.schwetschke/.iterm2:/Users/stefan.schwetschke/.fig/bin:/Users/stefan.schwetschke/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/run/current-system/sw/bin/:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/stefan.schwetschke/.nix-profile/bin:/nix/var/nix/profiles/default/bin
    - FIG_PARENT: 
    - FIG_TERM: 2.14.2
    - FIG_PID: 54186
    - FIGTERM_SESSION_ID: 68210bb9-3009-4f6f-bcf6-51bfd5bc9e48
```

**Comment by mschrage** [comment]
I believe this is resolved on macOS Ventura. If you can still reproduce it there, I will reopen this ticket.
