### ISSUE TITLE
bug: Terminal cursor positioned over current Path

### ISSUE THREAD

**Issue by sanderjn** [withfig/fig#2341]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1

### Expected behaviour

I expected the cursor to show after the current path

### Actual behaviour

The cursor is located about 10 characters to the left, and is placed on the current path. When typing, the path disappears and the command is shown over the path

### Steps to reproduce

- Install Fig
- Problem occurs in Terminal and VScode
- Uninstall/reinstall Fig
- Problem still occurs

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/sander/projects
  - exe-path: /Users/sander/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: da55ac29-9226-4080-a092-ff0e2a14e522
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /Users/sander/.nvm/versions/node/v18.9.1/bin:/Users/sander/.npm-global/bin:/usr/local/bin:/Users/sander/.rvm/gems/ruby-2.4.2/bin:/Users/sander/.rvm/gems/ruby-2.4.2@global/bin:/Users/sander/.rvm/rubies/ruby-2.4.2/bin:/Users/sander/.npm-global/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sander/.fig/bin:/Users/sander/.local/bin:/Users/sander/.rvm/bin:/Users/sander/.composer/vendor/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 87339
    - FIG_SET_PARENT: da55ac29-9226-4080-a092-ff0e2a14e522
```

### Screenshots

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/32776165/218743780-bfab6e78-d6a6-4cba-a91c-ee2389f6006e.png">

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/32776165/218744073-6d33722c-615b-4767-911c-49aa0636defa.png">

**Comment by mschrage** [comment]
It looks like there is a bug with your prompt (see the trailing `%{`).

Try again using a different prompt.

**Comment by sanderjn** [comment]
It turned out to be an issue with Oh My Zsh configuration. I uninstalled it, reinstalled it and all was fine again. Wasn't a Fig issue.
