### ISSUE TITLE
Import dotfiles window disappears immediately after opening

### ISSUE THREAD

**Issue by hangrymuppet** [withfig/fig#2342]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

- Click "Import" in Dotfiles menu
- Display a window with items to import
- Wait for user input

### Actual behaviour

- Click on "Import" in Dotfiles menu
- Display a window with items to import
- The window with items closes immediately after being displayed

### Steps to reproduce

see https://youtu.be/V9jTlyWtn2U

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/harishbajaj
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: f4243647-eeeb-4a72-8066-e5b3a4a2e761
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /opt/homebrew/opt/findutils/libexec/gnubin:/Users/harishbajaj/.rd/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Applications/Little Snitch.app/Contents/Components:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/harishbajaj/.fig/bin:/Users/harishbajaj/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 18391
    - FIG_SET_PARENT: f4243647-eeeb-4a72-8066-e5b3a4a2e761
```

**Comment by adamlwatson** [comment]
I also have this issue.

**Comment by immayurpanchal** [comment]
I'm also facing the same issue

**Comment by chriswubbels** [comment]
Same issue.

**Comment by timfee** [comment]
+1 #2373

**Comment by mschrage** [comment]
I believe this issue has been resolved. Please let me know if your are still experiencing this.
