### ISSUE TITLE
unsupported terminal for terminator

### ISSUE THREAD

**Issue by yairshp** [withfig/fig#2343]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 5.15.0-58-generic - "Ubuntu"

### Expected behaviour

to pass 'fig doctor' check

### Actual behaviour

'fig doctor' failed - unsupported terminal. although from your website it is clear that 'terminator' is supported

### Steps to reproduce

run 'fig doctor' on terminator.

additional info:
I run terminator with oh-my-zsh.

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  - cores: 4
  - mem: 15.35 GB
os-info:
  - kernel: 5.15.0-58-generic
  - distro: "Ubuntu"
  - distro-version: "22.04.1 LTS (Jammy Jellyfish)"
environment:
  - shell: /usr/bin/zsh
  - terminal: <unknown>
  - cwd: /home/yair
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: :0
    - FIGTERM_SESSION_ID: 17b44012-f040-4d5c-8c65-3284bb915955
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /home/yair/miniconda3/condabin:/home/yair/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/yair/.fig/bin:/home/yair/.fzf/bin
    - QT_IM_MODULE: ibus
    - SHELL: /usr/bin/zsh
    - TERM: xterm-256color
    - XDG_CURRENT_DESKTOP: ubuntu:GNOME
    - XDG_SESSION_DESKTOP: ubuntu-xorg
    - XDG_SESSION_TYPE: x11
    - XMODIFIERS: @im=ibus
    - FIG_PID: 235659
    - FIG_SET_PARENT: 17b44012-f040-4d5c-8c65-3284bb915955
    - GTK_IM_MODULE: ibus
    - GLFW_IM_MODULE: ibus
```

**Comment by mschrage** [comment]
Currently autocomplete is not supported on Linux.
