### ISSUE TITLE
bug: Fig Desktop App loads blank screen

### ISSUE THREAD

**Issue by enuchi** [withfig/fig#2348]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 10.14.6 Mojave

### Expected behaviour

Selecting Dashboard or Settings from Menubar opens the respective pages in the desktop app after installing

### Actual behaviour

I get a blank screen.

CLI seems to work fine, and the instructions to add Fig to accessibility settings work fine, but when loading the desktop app I get a blank screen.

Desktop app console shows the error: `SyntaxError: Unexpected token '?'`.

<img width="1491" alt="Screen Shot 2023-02-16 at 3 41 48 PM" src="https://user-images.githubusercontent.com/31550519/219483450-0a94c78a-b951-4f31-a1c4-7dffe78a00d3.png">

### Steps to reproduce

I think the error is due to the desktop app trying to parse the nullish coalescing operator (`??`), but not running the right version of Safari. I know I'm running an older OS, but what's weird is both regular Safari and Chrome on this machine are able to parse ?? just fine. Do you know why the desktop app may be running an older version of Safari?

I can load these pages in a separate browser session. Are there any differences between the desktop app and just loading https://desktop.fig.io/scripts in a browser? Would like to be able to try running it from the menubar in the standalone desktop app if possible. Thanks for the help with this.

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  - cores: 4
  - mem: 8.00 GB
os-info:
  - macOS 10.14.6 (18G9323)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/elisha/Library/Preferences
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 317ebfe0-8bb6-4d11-8096-89ee4e858126
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: [...]
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 17323
    - FIG_SET_PARENT: 317ebfe0-8bb6-4d11-8096-89ee4e858126fig-details:
  - 2.14.2
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  - cores: 4
  - mem: 8.00 GB
os-info:
  - macOS 10.14.6 (18G9323)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/elisha/Library/Preferences
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 317ebfe0-8bb6-4d11-8096-89ee4e858126
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: [...]
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 17323
    - FIG_SET_PARENT: 317ebfe0-8bb6-4d11-8096-89ee4e858126
```

Removed my PATH but let me know if that's helpful.
```

**Comment by webgururobin** [comment]
I was facing the same issue, doing a ``` fig restart ``` worked for me.

**Comment by dikaio** [comment]
Nice, worked thanks @webgururobin 😉
