### ISSUE TITLE
fig autocomplete always display at top left at screen.

### ISSUE THREAD

**Issue by TranTrungTien** [withfig/fig#2349]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 5.15.0-60-generic - "Ubuntu"

### Expected behaviour

Show autocomplete under input.

### Actual behaviour

Awalys display at top-left screen

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: 12th Gen Intel(R) Core(TM) i7-1255U
  - cores: 10
  - mem: 15.27 GB
os-info:
  - kernel: 5.15.0-60-generic
  - distro: "Ubuntu"
  - distro-version: "22.04.1 LTS (Jammy Jellyfish)"
environment:
  - shell: /usr/bin/zsh
  - terminal: <unknown>
  - cwd: /home/strawberry
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: :0
    - FIGTERM_SESSION_ID: 2fdd6c8f-fcd9-4981-8816-152aac872955
    - FIG_PID: 12855
    - FIG_SET_PARENT: 2fdd6c8f-fcd9-4981-8816-152aac872955
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - GLFW_IM_MODULE: ibus
    - GTK_IM_MODULE: ibus
    - PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/strawberry/.local/bin:/home/strawberry/.fig/bin
    - QT_IM_MODULE: ibus
    - SHELL: /usr/bin/zsh
    - TERM: xterm-256color
    - XDG_CURRENT_DESKTOP: ubuntu:GNOME
    - XDG_SESSION_DESKTOP: ubuntu
    - XDG_SESSION_TYPE: wayland
    - XMODIFIERS: @im=ibus
```

**Comment by ManuelAngel99** [comment]
I have been experiencing the same issue in PopOS when running fig with zsh

**Comment by sdwood** [comment]
Same issue here on Pop!_OS 22.04 LTS

**Comment by ilhamsyaputra** [comment]
> 

Same here, using PopOS and the autocomplete stuck at top left corner. Have you solved the problem?

**Comment by fb-smit** [comment]
Also in Manjaro with zsh and it is placed at another screen, not the screen where my shell is active.

```
5.15.94-1-MANJARO
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
zsh 5.9 (x86_64-pc-linux-gnu)
plasmashell 5.26.5
Qt: 5.15.8
KDE Frameworks: 5.103.0
kf5-config: 1.0
fig_cli 2.14.2
```

**Comment by EriikGabriel** [comment]
Same here, using Ubuntu 22.04.1 LTS too.

**Comment by gustavoclay** [comment]
Same here

OS: Ubuntu 22.04.2 LTS x86_64 
Kernel: 5.19.0-35-generic
Shell: zsh 5.8.1
DE: GNOME 42.5

2 monitors

**Comment by henil0604** [comment]
Same Here

**Comment by josiah34** [comment]
Same here also using zsh

**Comment by nitec427** [comment]
Same here on Ubuntu 22.04 LTS with Gnome-Fig integration.

**Comment by coding404life** [comment]
+1

**Comment by mschrage** [comment]
Currently Autocomplete is unsupported on Linux. #34
