### ISSUE TITLE
Allow for Fig menu bar icon to be disabled in System Preferences

### ISSUE THREAD

**Issue by jakobgilbert99** [withfig/fig#235]
User's thoughts below — suggesting an enhancement that would add a Fig system preferences panel which contains many of the menu bar settings as well as the ability to disable the menu bar icon.
> As a wish, I would like to see the Fig icon in the OS settings instead of the menu bar. No need to remove all functionality from the Fig menu. Let's say a menu bar can be an option. I mean, if the Fig will be integrated into the System Preference, "Show Fig in menu bar" checkbox can be added as an option. Just take a look at the Bluetooth settings “Show Bluetooth in menu bar” in the MacOs. It can be enabled by default.

**Comment by mattschrage** [comment]
Do they know that they can hide the menubar icon in  Fig's settings?

`fig settings app.hideMenubarIcon true`

**Comment by ivandata** [comment]
Hey Jakob! Thanks for the ticket, didn't suspect that a simple suggestion could open an issue. 😅
A couple of words from the instigator.

This improvement mostly user-friendly enhancement. Terminal commands works convinced for developers only if a tool fully controlled by the terminal. In case GUI available, terminal commands seem to be inconsistent. I mean for debugging we have a special GUI interface, but for such a simple action as hiding/showing the icon you should use the terminal command. At the same time, if the tool is controlled via a terminal, this is very cool.

I don't know the Fig user statistics. For me personally, the simpler the interface the more convenient it is. Better if tool doing a job invisible for me. In real life, I personally use this great tool mostly for autocomplete, and for me, the icon has no useful. 

BTW I've tried run `fig settings app.hideMenubarIcon true` in the terminal, but it didn't help. 😅

**Comment by mattschrage** [comment]
@ivandata when you say that `fig settings app.hideMenubarIcon true` didn't help, is that because the icon is still there? Or something else?

**Comment by ivandata** [comment]
@mattschrage exactly, Fig icon still in the menu bar. 
Fig version is 1.0.39

**Comment by mattschrage** [comment]
Oh wow! You're on a very old version. Go to the menubar icon and click "Check for updates...". 

You should be prompted to update to the newest version (1.0.45). The `fig settings app.hideMenubarIcon true` command will work on newer builds.

**Comment by ivandata** [comment]
Well, after updating the Fig doesn’t run anymore :cry:

**Comment by mattschrage** [comment]
This is the behavior you want, correct? Autocomplete functionality but without the menubar icon?

**Comment by ivandata** [comment]
Yes, my issue solved the terminal command. Thank you!

**Comment by ivandata** [comment]
I'm sorry, for disrupting, but now is another bug reproducing. The command works fine. But now I noticed that the Fig does not work after quitting the terminal. It does not happen after each exit, only sometimes. I have to run fig every time again. 

I use zsh if its matters...

**Comment by mschrage** [comment]
Can you open a new issue for this? Run `fig issue` in your terminal!

**Comment by ivandata** [comment]
Done https://github.com/withfig/fig/issues/302
