### ISSUE TITLE
Autocomplete keeps being inactive

### ISSUE THREAD

**Issue by calii23** [withfig/fig#2363]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 5.19.0-32-generic - "Ubuntu"

### Expected behaviour

Autocomplete to be working.

### Actual behaviour

The autocomplete popup doesn't show up. When I run `fig doctor` I get these outputs:
```
● Fig's support for Linux 5.19.0-32-generic - "Ubuntu" is in development. It may not work properly on your system.

✘ Autocomplete is active: Autocomplete is currently inactive. Your desktop integration(s) may be broken!


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

`fig restart` did not change anything about that. Unfortunately I couldn't really figure out how to get more detailed information or log files. So please feel free to ask me about them.

### Steps to reproduce

I have a Ubuntu Linux OS. I have tried the xcfe terminal and the default GNOME terminal emulator. Same result. Normally I use `tmux` with also same result with and without. Tried it with my preferred `fish` shell, but `bash` gave the same result either.

I am using GNOME desktop manager with Wayland. Please ask if I am missing some info here.

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  - cores: 4
  - mem: 15.35 GB
os-info:
  - kernel: 5.19.0-32-generic
  - distro: "Ubuntu"
  - distro-version: "22.04.1 LTS (Jammy Jellyfish)"
environment:
  - shell: /usr/bin/fish
  - terminal: <unknown>
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: :0
    - FIGTERM_SESSION_ID: 6e3e6871-3709-4004-9335-128a3441e7cc
    - FIG_PARENT: 
    - FIG_PID: 828277
    - FIG_SET_PARENT: 
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - FIG_TERM_TMUX: 2.14.2
    - QT_IM_MODULE: ibus
    - SHELL: /usr/bin/fish
    - XDG_SESSION_DESKTOP: ubuntu
    - XDG_CURRENT_DESKTOP: ubuntu:GNOME
    - XMODIFIERS: @im=ibus
    - TERM: screen-256color
    - XDG_SESSION_TYPE: wayland
```

**Comment by mschrage** [comment]
Autocomplete is not currently supported on Linux.
