### ISSUE TITLE
Dotfiles are not being sourced when opening a new terminal

### ISSUE THREAD

**Issue by jnegara** [withfig/fig#2365]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

I added some aliases & variables to my dotfiles configuration via the fig dashboard.

I expected these aliases/variables to be present when opening a new terminal.

### Actual behaviour

On opening a new terminal, the aliases/variables are not available.

I have to run `fig source` each time I open a terminal.

### Steps to reproduce

1. Add aliases+variables to dotfiles config.
2. Open a new terminal

**Comment by mschrage** [comment]
Try running `fig doctor` to make sure the daemon is running.
