### ISSUE TITLE
Fig autocomplete window showing only with prepended periods (.) or spaces to terminal command

### ISSUE THREAD

**Issue by jarrahffe** [withfig/fig#2369]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.0.0 (22A380)

### Expected behaviour

Auto complete window should show up after appending a space to a terminal command

eg: 
ls Documents
shows no window

### Actual behaviour

The autocomplete window does not show up after appending a space. It ONLY shows up when I add prepend a space to the terminal command or a period . to the command.

eg: 
 ls Documents
shows the window (space before "ls")

. cd Documents 
shows the window (period before "cd")

### Steps to reproduce

not sure how to reproduce since it just randomly started happening

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/jarjar/.config/nvim
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: d269013f-9d4b-417a-9f69-b21e91beed7a
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jarjar/.fig/bin:/Users/jarjar/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 76489
    - FIG_SET_PARENT: d269013f-9d4b-417a-9f69-b21e91beed7a
```

**Comment by mschrage** [comment]
This likely has to do with the prompt that you have set currently. Can you share your zshrc file?
