### ISSUE TITLE
Support for PowerShell

### ISSUE THREAD

**Issue by alm0st907** [withfig/fig#237]
This looks like a really cool tool. 

Now that PowerShell is cross platform, it would be really cool if this was supported as well.

It would be even more cool if this was cross platform (Linux/Windows)😅

**Comment by sheldonhull** [comment]
I ran into this issue today on macOS. I thought Fig wasn't working, but turns out my pwsh didn't recognize. As soon as I manually entered into `zsh` the intellisense showed up.

**Comment by mschrage** [comment]
In order to add support for `pwsh`, we need to:
1. Rewrite our shell integrations in powershell
2. Update our tokenizer to support powershell syntax
3. Add completions for powershell builtins (and add a way indicating what shells are supported by a completion spec)
