### ISSUE TITLE
Duplicate/Copy Script in CLI Tools

### ISSUE THREAD

**Issue by jonbackhaus-mt** [withfig/fig#2370]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
CLI Tools currently includes the ability to "Move" a command (i.e. "Script") but doesn't include the ability "Duplicate" or copy that command. Since many commands are similar, this would dramatically cut down on the time it takes to create a new command that's a variant of an existing one.

**Comment by grant0417** [comment]
Hey @jonbackhaus-mt, just added this option, just refresh and there should be a new "Duplicate" option.

**Comment by jonbackhaus-mt** [comment]
Amazing! Thanks @grant0417

**Comment by jonbackhaus-mt** [comment]
@grant0417 -- I see the merged change but I'm running into two issues with the new feature: 

1. the "Duplicate" seems to always place the script in the root of the Organization, which is fine but not the behavior I would expect. (All things being equal, I would expect it to put the script in the same location as the original.) 
2. duplicated scripts don't appear to have the "Move" option in the hamburger menu, so I can't figure out how to move them to the proper subcommand after they have been created.

Any thoughts/ideas?
