### ISSUE TITLE
Import screen for dotfiles instacloses

### ISSUE THREAD

**Issue by timfee** [withfig/fig#2373]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

I'd be able to select aliases/paths to add

### Actual behaviour

Screen closes immediately:

https://user-images.githubusercontent.com/3246342/221324163-e088c032-dd5a-4f59-9bca-0a1db8758059.mov

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/timfee
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: b35b815e-3b99-4474-98d3-4bbda73dd4cf
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/timfee/.fig/bin:/Users/timfee/.local/bin:/Users/timfee/.local/bin:/Users/timfee/.fig/bin:/Users/timfee/Library/pnpm
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 50040
    - FIG_SET_PARENT: b35b815e-3b99-4474-98d3-4bbda73dd4cf
```

**Comment by timfee** [comment]
The underlying use case here:

I was trying to mass import aliases 

```
# Aliases

alias p='pnpm'

# Dependencies
alias pa='pnpm add'
alias pad='pnpm add --save-dev'
alias pap='pnpm add --save-peer'
alias prm='pnpm remove'
alias pin='pnpm install'
alias pls='pnpm list'
alias pu='pnpm update'
alias puil='pnpm update --interactive --latest'

# Global dependencies
alias pga='pnpm add --global'
alias pgls='pnpm list --global'
alias pgrm='pnpm remove --global'
alias pgu='pnpm update --global'

# Run scripts
alias pr='pnpm run'
alias prun='pnpm run'
alias pd='pnpm run dev'
alias pb='pnpm run build'
alias psv='pnpm run serve'
alias pst='pnpm start'
alias pt='pnpm test'
alias ptc='pnpm test --coverage'
alias pln='pnpm run lint'
alias pdocs='pnpm run docs'
alias pex='pnpm exec'
alias pdx='pnpm dlx'

# Misc
alias pi='pnpm init'
alias ppub='pnpm publish'
alias pc='pnpm create'

# Monorepo
alias pf='pnpm -r --filter'
```

without having to type them line by line into Fig. I'd rather just be able to paste in this block somewhere, but I thought the best workaround was to just add it to any of the existing dotfiles. 

But even without any of these custom aliases, this screen closes right away it seems

**Comment by timfee** [comment]
Also the contents of my alias file:

```
❯ alias
-='cd -'
...=../..
....=../../..
.....=../../../..
......=../../../../..
1='cd -1'
2='cd -2'
3='cd -3'
4='cd -4'
5='cd -5'
6='cd -6'
7='cd -7'
8='cd -8'
9='cd -9'
_='sudo '
diff=color-diff
egrep='grep -E --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
fgrep='grep -F --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
globurl='noglob urlglobber '
grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
history=omz_history
l='ls -lah'
la='ls -lAh'
ll='ls -lh'
ls='ls -G'
lsa='ls -lah'
md='mkdir -p'
rd=rmdir
run-help=man
which-command=whence
```

**Comment by immayurpanchal** [comment]
> Also the contents of my alias file:
> 
> ```
> ❯ alias
> -='cd -'
> ...=../..
> ....=../../..
> .....=../../../..
> ......=../../../../..
> 1='cd -1'
> 2='cd -2'
> 3='cd -3'
> 4='cd -4'
> 5='cd -5'
> 6='cd -6'
> 7='cd -7'
> 8='cd -8'
> 9='cd -9'
> _='sudo '
> diff=color-diff
> egrep='grep -E --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
> fgrep='grep -F --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
> globurl='noglob urlglobber '
> grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
> history=omz_history
> l='ls -lah'
> la='ls -lAh'
> ll='ls -lh'
> ls='ls -G'
> lsa='ls -lah'
> md='mkdir -p'
> rd=rmdir
> run-help=man
> which-command=whence
> ```

Where does this alias file is located?

**Comment by timfee** [comment]
No idea! I removed everything but the fig generated config files — maybe it’s an OMZ thing?

I wasn’t sure if some of the stranger commands (“-“ or “_” was throwing it off, but it didn’t seem to make a difference)

**Comment by grant0417** [comment]
@parssak is investigating this

**Comment by mschrage** [comment]
I believe this has been resolved.
