### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by elsayed85** [withfig/fig#2379]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 5.19.0-32-generic - "Ubuntu"

### Expected behaviour

autocomplete menu list show

### Actual behaviour

autocomplete not working

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: AMD Ryzen 7 3700X 8-Core Processor
  - cores: 8
  - mem: 15.57 GB
os-info:
  - kernel: 5.19.0-32-generic
  - distro: "Ubuntu"
  - distro-version: "22.04.2 LTS (Jammy Jellyfish)"
environment:
  - shell: /usr/bin/fig_desktop
  - terminal: <unknown>
  - cwd: /home/elsayed
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - PATH: /home/elsayed/.local/bin:/home/elsayed/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/elsayed/.local/bin:/home/elsayed/.fig/bin
    - SHELL: /bin/bash
    - GTK_IM_MODULE: ibus
    - QT_IM_MODULE: ibus
    - XMODIFIERS: @im=ibus
    - GLFW_IM_MODULE: ibus
    - DISPLAY: :0
    - FIG_SET_PARENT_CHECK: 1
    - XDG_CURRENT_DESKTOP: ubuntu:GNOME
    - XDG_SESSION_DESKTOP: ubuntu
    - XDG_SESSION_TYPE: wayland
```

**Comment by grant0417** [comment]
Hey @elsayed85 could you give some more details here? I'm not 100% clear on our support of Wayland at the moment, could you try X11?

**Comment by elsayed85** [comment]
when i disable Wayland my screen turns on yellow .. so i keep everything as it is . 
but if forget to tell that fig now working but .. the suggestions menu is in the wrong place out of the terminal window in the top left of my screen , how to solve this please @grant0417

**Comment by mschrage** [comment]
We do not currently support Autocomplete on Linux.
