### ISSUE TITLE
`osqueryd` takes a lot of cpu

### ISSUE THREAD

**Issue by JasonMore** [withfig/fig#238]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
with fig running, my computer feels slow, and `osqueryd` takes a lot of cpu. When I disable fig my computer speeds up again. I'm assuming its partially due to the fact my work has Bit defender running on my laptop as well and they are colliding in some bad way? 

With fig running
![image](https://user-images.githubusercontent.com/383719/124291609-595f9100-db1a-11eb-84e8-e05a24e3c286.png)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.45 (B218)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.45 (B218) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/enroll/.fig/bin/fig
Accessibility: true
Number of specs: 131
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/enroll/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/enroll/.nvm/versions/node/v14.17.0/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/enroll/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mattschrage** [comment]
I'm not familiar with `osqueryd` or Bit Defender. Have you seen this happen with other apps you've used on your work machine?

**Comment by JasonMore** [comment]
@mattschrage thanks for the tips, I gave it a shot, here are my results:

> 1. Did you install osqueryd directly or is this a dependency of Bit Defender?

I didn't install this myself, I'm assuming it came with the security software on my work machine.

> 2. Have you seen this happen with other apps you've used on your work machine?

I have not, it only seems to happen with Fig

> 3. Could you run osqueryd in verbose mode (osqueryd --ephemeral --disable_database --disable_logging). This might help us narrow down what causing it to eat up all of this CPU!

It looks like I'm not allowed to see whats going on 😓 

> ➜  ~ osqueryd --ephemeral --disable_database --disable_logging
> I0707 13:18:33.827306 236477952 database.cpp:563] Checking database version for migration
> I0707 13:18:33.828114 236477952 database.cpp:587] Performing migration: 0 -> 1
> I0707 13:18:33.828436 236477952 database.cpp:619] Migration 0 -> 1 successfully completed!
> I0707 13:18:33.828455 236477952 database.cpp:587] Performing migration: 1 -> 2
> I0707 13:18:33.828470 236477952 database.cpp:619] Migration 1 -> 2 successfully completed!
> I0707 13:18:33.829761 236477952 config.cpp:762] update
> I0707 13:18:33.829859 236477952 events.cpp:658] Event publisher not enabled: openbsm: Publisher disabled via configuration
> I0707 13:18:33.829879 236477952 events.cpp:658] Event publisher not enabled: scnetwork: Publisher not used
> I0707 13:18:33.829890 236477952 events.cpp:658] Event publisher not enabled: event_tapping: Publisher disabled via configuration
> libc++abi: terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::remove: Permission denied: "/var/osquery/osquery.db/events/_FR_diskarbitration.disk_events_0"
> I0707 13:18:39.825372 282717696 database.cpp:563] Checking database version for migration
> I0707 13:18:39.825975 282717696 database.cpp:587] Performing migration: 0 -> 1
> I0707 13:18:39.825996 282717696 database.cpp:619] Migration 0 -> 1 successfully completed!
> I0707 13:18:39.826006 282717696 database.cpp:587] Performing migration: 1 -> 2
> I0707 13:18:39.826016 282717696 database.cpp:619] Migration 1 -> 2 successfully completed!
> I0707 13:18:39.826687 282717696 config.cpp:762] update
> I0707 13:18:39.826846 282717696 events.cpp:658] Event publisher not enabled: openbsm: Publisher disabled via configuration
> I0707 13:18:39.826908 282717696 events.cpp:658] Event publisher not enabled: scnetwork: Publisher not used
> I0707 13:18:39.826942 282717696 events.cpp:658] Event publisher not enabled: event_tapping: Publisher disabled via configuration
> libc++abi: terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::remove: Permission denied: "/var/osquery/osquery.db/events/_FR_diskarbitration.disk_events_0"

**Comment by mattschrage** [comment]
Thanks for letting me know. I'll install `osqueryd` myself and try to reproduce.

**Comment by JasonMore** [comment]
@mattschrage my gut says looking at how osqueryd works, there is probably some query running as part of bitdefender that is being obnoxious, so it might be hard to repo

**Comment by mschrage** [comment]
Alright. I am going to close this issue, but will reopen if other people run into it.
