### ISSUE TITLE
Unable to use fig with neovim toggleterm plugin 

### ISSUE THREAD

**Issue by Royal-lobster** [withfig/fig#2380]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

fig to be able to use in toggleterm in neovim.

### Actual behaviour

fig autocomplete not working

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/srujangurram/Projects/university/student-records
  - exe-path: /Users/srujangurram/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /bin/zsh
    - __CFBundleIdentifier: com.googlecode.iterm2
    - PATH: /Users/srujangurram/.local/share/nvim/mason/bin:/Users/srujangurram/.nvm/versions/node/v16.15.1/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/node@16/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/srujangurram/.cargo/bin:/Users/srujangurram/.fig/bin:/Users/srujangurram/.local/bin:/Users/srujangurram/.foundry/bin:/Users/srujangurram/.spicetify:/Users/srujangurram/.foundry/bin:/Users/srujangurram/.spicetify
    - TERM: xterm-256color
    - FIGTERM_SESSION_ID: a70936ba-423b-4a34-aaa4-35e38df26365
    - FIG_TERM: 2.14.2
    - FIG_SET_PARENT: a70936ba-423b-4a34-aaa4-35e38df26365
    - FIG_PID: 82769
    - FIG_SET_PARENT_CHECK: 1
```

**Comment by grant0417** [comment]
Is the issue that Fig does not show up in `toggleterm`? Could you share the output of `fig _ should-figterm-launch`?

**Comment by Royal-lobster** [comment]
> Is the issue that Fig does not show up in `toggleterm`? Could you share the output of `fig _ should-figterm-launch`?

True. Executed  `fig _ should-figterm-launch` this is the output -

<img width="737" alt="CleanShot 2023-03-01 at 05 21 23@2x" src="https://user-images.githubusercontent.com/52039218/222009536-f8bc85b7-5043-4348-ad2e-7178e14c6e81.png">

**Comment by grant0417** [comment]
The issues is we rely on the `FIG_TERM` environment variable to determine if our integration should launch in a shell. There are quick 2 fixes for this:

- Add a line to your neovim config unsetting `FIG_TERM`
	- I think in lua it should be: `vim.fn.setenv("FIG_TERM", nil)`
	- Docs: https://neovim.io/doc/user/eval.html

- Manually run `figterm` in the shell

**Comment by Royal-lobster** [comment]
> * rm

Thanks ! this works.
