### ISSUE TITLE
Alacritty support - Linux

### ISSUE THREAD

**Issue by Aur0nd** [withfig/fig#2384]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 6.2.1-arch1-1 - "Arch Linux"

### Expected behaviour

Integration for Alacritty - linux

### Actual behaviour

There's no support, the popup - pops up in random locations

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: 12th Gen Intel(R) Core(TM) i9-12900K
  - cores: 16
  - mem: 62.55 GB
os-info:
  - kernel: 6.2.1-arch1-1
  - distro: "Arch Linux"
  - distro-build: rolling
environment:
  - shell: /usr/bin/zsh
  - terminal: <unknown>
  - cwd: /home/aurond
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: :0
    - FIG_PID: 8243
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - GLFW_IM_MODULE: ibus
    - GTK_IM_MODULE: ibus

    - QT_IM_MODULE: ibus
    - SHELL: /bin/zsh
    - TERM: alacritty
    - XDG_CURRENT_DESKTOP: KDE
    - XDG_SESSION_DESKTOP: KDE
    - XDG_SESSION_TYPE: x11
    - XMODIFIERS: @im=ibus
```

**Comment by mschrage** [comment]
Currently, autocomplete on Linux is not supported.
