### ISSUE TITLE
bug: Unable to focus Gnome Terminal window above Chrome while in maximize window mode

### ISSUE THREAD

**Issue by hahunavth** [withfig/fig#2385]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Manjaro Linux x86_64

### Expected behaviour

The user should be able to interact with the Gnome Terminal window even when Google Chrome is in maximize window mode.

### Actual behaviour

When using Google Chrome in maximize window mode and Gnome Terminal, it becomes impossible to focus on the Gnome Terminal window in the same workspace. Even though the terminal window is open and visible, clicking on it does not bring it to the front. Instead, Chrome remains in focus, making it impossible to interact with the terminal window. 
Output of `fig doctor`:
```shell
$fig doctor    

● Fig's support for Linux 6.1.12-1-MANJARO - "Manjaro Linux" is in development. It may not work properly on your system.
Autocomplete is currently in alpha for Linux, other products should work as expected.
● Unsupported terminal, if you believe this is a mistake or would like to see support for your terminal, run `fig issue`

✔ Everything looks good!

  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!

```

### Steps to reproduce

1. Open Google Chrome and Gnome Terminal in the same workspace
2. Maximize Google Chrome window
3. Use the Super + S shortcut to open the workspace overview.
4. Try to interact with the Gnome Terminal window by clicking on it.

### Environment

```yaml
fig-details:
  - 2.15.0-nightly.20230302
hardware-info:
  - model: 
  - model-id: 
  - chip-id: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  - cores: 4
  - mem: 7.49 GB
os-info:
  - kernel: 6.1.12-1-MANJARO
  - distro: "Manjaro Linux"
  - distro-build: rolling
environment:
  - shell: /usr/bin/zsh
  - terminal: <unknown>
  - cwd: /home/kryo
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: :0
    - FIGTERM_SESSION_ID: df0bc81c-047b-4714-985a-cd7f85d89e43
    - FIG_PID: 136382
    - FIG_SET_PARENT: df0bc81c-047b-4714-985a-cd7f85d89e43
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0-nightly.20230302
    - GLFW_IM_MODULE: ibus
    - GTK_IM_MODULE: ibus
    - PATH: /home/kryo/.fly/bin:/home/kryo/.rbenv/bin:/home/kryo/.nvm/versions/node/v18.14.2/bin:/opt/miniconda3/condabin:/home/kryo/miniconda3/bin:/home/kryo/.local/bin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/kryo/.fig/bin:/home/kryo/.local/share/JetBrains/Toolbox/scripts:/home/kryo/.yarn/bin
    - QT_IM_MODULE: ibus
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - XDG_CURRENT_DESKTOP: GNOME
    - XDG_SESSION_DESKTOP: gnome
    - XDG_SESSION_TYPE: wayland
    - XMODIFIERS: @im=ibus
```

**Comment by mschrage** [comment]
Autocomplete in not supported on Linux right now.
