### ISSUE TITLE
bug: Fig stops working when clicking more button on side panel and when trying to go to Autocomplete in settings

### ISSUE THREAD

**Issue by Max-Gouliaev** [withfig/fig#2388]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 6.2.2-arch1-1 - EndeavourOS

### Expected behaviour

I expected it to behave like web-client

### Actual behaviour

Fig stops working when clicking **more button on side panel** and when trying to access **Autocomplete in settings**

video:
https://user-images.githubusercontent.com/68902211/223403909-1466e8cb-9f22-4798-85ec-28f6ad1a4c22.mp4

### Steps to reproduce

click **more button on side panel** or try to access **Autocomplete in settings**

### Environment

```yaml
{x} means i added smth


fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
  - cores: 8
  - mem: 31.14 GB
os-info:
  - kernel: 6.2.2-arch1-1
  - distro: EndeavourOS
  - distro-build: rolling
environment:
  - shell: /usr/bin/fig_desktop
  - terminal: <unknown> {konsole}
  - cwd: /home/max
  - exe-path: /usr/bin/fig
  - install-method: unknown {pacman}
  - env-vars:
    - PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/home/max/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
    - SHELL: /bin/bash
    - GTK_IM_MODULE: ibus
    - QT_IM_MODULE: ibus
    - XMODIFIERS: @im=ibus
    - GLFW_IM_MODULE: ibus
    - DISPLAY: :0
    - XDG_CURRENT_DESKTOP: KDE
    - XDG_SESSION_DESKTOP: KDE
    - XDG_SESSION_TYPE: x11
```

**Comment by mschrage** [comment]
This is very strange behavior. Not sure what is going on here, but Linux is not officially support so I'm going to close this issue for now.
