### ISSUE TITLE
bug: Uninstalling Fig from WSL not working and keeps returns errors

### ISSUE THREAD

**Issue by DoctorScorpion** [withfig/fig#2391]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Windows 10 -wsl

### Expected behaviour

Installation of fig didnt work, I tried to uninstall and keeps getting the following error when switching user (su)
Command 'fig' not found, did you mean:
  command 'wig' from deb wig (0.6-2)
  command 'fio' from deb fio (3.28-1)
  command 'xfig' from deb xfig (1:3.2.8b-1)
  command 'tig' from deb tig (2.5.1-1)
  command 'fim' from deb fim (0.5.3-9)
  command 'kig' from deb kig (4:21.12.3-0ubuntu1)
  command 'dig' from deb bind9-dnsutils (1:9.18.1-1ubuntu1.3)
  command 'fid' from deb id-utils (4.6.28-20200521ss15dab)
  command 'fis' from deb redboot-tools (0.7build4)
  command 'pig' from deb bsdgames (2.17-29)
  command 'rig' from deb rig (1.11-1.1)
Try: apt install <deb name>
Command 'fig' not found, did you mean:
  command 'fid' from deb id-utils (4.6.28-20200521ss15dab)
  command 'tig' from deb tig (2.5.1-1)
  command 'wig' from deb wig (0.6-2)
  command 'fim' from deb fim (0.5.3-9)
  command 'fis' from deb redboot-tools (0.7build4)
  command 'xfig' from deb xfig (1:3.2.8b-1)
  command 'fio' from deb fio (3.28-1)
  command 'dig' from deb bind9-dnsutils (1:9.18.1-1ubuntu1.3)
  command 'rig' from deb rig (1.11-1.1)
  command 'pig' from deb bsdgames (2.17-29)
  command 'kig' from deb kig (4:21.12.3-0ubuntu1)
Try: apt install <deb name>

### Actual behaviour

Command 'fig' not found, did you mean:
  command 'wig' from deb wig (0.6-2)
  command 'fio' from deb fio (3.28-1)
  command 'xfig' from deb xfig (1:3.2.8b-1)
  command 'tig' from deb tig (2.5.1-1)
  command 'fim' from deb fim (0.5.3-9)
  command 'kig' from deb kig (4:21.12.3-0ubuntu1)
  command 'dig' from deb bind9-dnsutils (1:9.18.1-1ubuntu1.3)
  command 'fid' from deb id-utils (4.6.28-20200521ss15dab)
  command 'fis' from deb redboot-tools (0.7build4)
  command 'pig' from deb bsdgames (2.17-29)
  command 'rig' from deb rig (1.11-1.1)
Try: apt install <deb name>
Command 'fig' not found, did you mean:
  command 'fid' from deb id-utils (4.6.28-20200521ss15dab)
  command 'tig' from deb tig (2.5.1-1)
  command 'wig' from deb wig (0.6-2)
  command 'fim' from deb fim (0.5.3-9)
  command 'fis' from deb redboot-tools (0.7build4)
  command 'xfig' from deb xfig (1:3.2.8b-1)
  command 'fio' from deb fio (3.28-1)
  command 'dig' from deb bind9-dnsutils (1:9.18.1-1ubuntu1.3)
  command 'rig' from deb rig (1.11-1.1)
  command 'pig' from deb bsdgames (2.17-29)
  command 'kig' from deb kig (4:21.12.3-0ubuntu1)
Try: apt install <deb name>

### Steps to reproduce

sudo su / su USER

**Comment by mschrage** [comment]
Autocomplete is not currently supported on Windows.
