### ISSUE TITLE
Support for Zed terminal

### ISSUE THREAD

**Issue by KenzoBenzo** [withfig/fig#2393]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

That Fig auto complete works with Zed terminal

### Actual behaviour

It's unsupported.

### Environment

```yaml
fig-details:
  - 2.14.0-beta.7
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
  - cores: 8
  - mem: 40.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: <unknown>
  - cwd: /Users/makennasmutz/Documents/GitHub/fe-monorepo
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 548a9382-3dd9-45c8-b8b0-f2b9de886f13
    - FIG_PID: 29141
    - FIG_SET_PARENT: 548a9382-3dd9-45c8-b8b0-f2b9de886f13
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.0-beta.7
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/makennasmutz/.fig/bin:/Users/makennasmutz/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: dev.zed.Zed
```

**Comment by Moshyfawn** [comment]
🎉🥳
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16290753/228567882-5c695861-f429-43d9-a481-e0c1ae38f2cd.png">
