### ISSUE TITLE
Doesn't work on ubuntu 22

### ISSUE THREAD

**Issue by erobakiewicz** [withfig/fig#2395]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Ubuntu 22.04.2 LTS

### Expected behaviour

Working

### Actual behaviour

nothing works

### Steps to reproduce

Just try run it, nothing works

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  - cores: 4
  - mem: 15.51 GB
os-info:
  - kernel: 5.19.0-35-generic
  - distro: "Ubuntu"
  - distro-version: "22.04.2 LTS (Jammy Jellyfish)"
```

**Comment by mschrage** [comment]
Autocomplete is not currently supported on Linux.
