### ISSUE TITLE
Fig disconnecting from terminal

### ISSUE THREAD

**Issue by manofab** [withfig/fig#2397]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

Fig is always working and I don't need to be restarting it all the time.

### Actual behaviour

It happens quite often that you are working on a terminal and Fig suddenly stops working. Restarting fig fix the issue but its quite annoying the need to restart fig almost everyday and several times during a day. 

### Steps to reproduce

It happens randomly, I haven't identify any pattern

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 24.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 862ab6b3-ebc4-48a2-8904-a2e02391e3c8
    - FIG_PID: 20177
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.microsoft.VSCode
    - FIG_SET_PARENT: 862ab6b3-ebc4-48a2-8904-a2e02391e3c8
```

**Comment by mschrage** [comment]
Hmm this is very hard to reproduce. I will close the issue for now, but will reopen if I figure out what is going on.

**Comment by SaaberDev** [comment]
Any update on this issue. Same is happening with me.
