### ISSUE TITLE
why i can't close this window?

### ISSUE THREAD

**Issue by Kun8018** [withfig/fig#2403]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
> Please include a detailed description of the feature (and an image or screen recording, if applicable)

I close this window and it appears again and again. I can't config fig and fig doesn't work . My Desktop is M1 pro, Mac os 13.2.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/41263766/226090979-98cfe053-643e-4625-b1bf-3bfdbab06e22.png">

**Comment by thl-sz** [comment]
English for me, but issue is the same

**Comment by Kun8018** [comment]
> English for me, but issue is the same

sorry, i change my system language and try again.

**Comment by pfurini** [comment]
Same for me, since this morning I have an infinite loop of "FigInputMethod" authorisation request, tried everything but to no avail.
In addition after a while the fig window closes unexpectedly with an error. Had to uninstall fig completely.

**Comment by sergiuwaxmann** [comment]
+1

**Comment by cfurrow** [comment]
Related: #2405 #2402

**Comment by virezox** [comment]
+1

**Comment by rolcho** [comment]
I could solve the problem temporarily by copying the /Applications/Fig.app/Contents/Helpers/FigInputMethod.app into the ~/Library/Input Methods folder

**Comment by sergiuwaxmann** [comment]
Duplicates #2402

**Comment by grant0417** [comment]
This should be resolved now, just restart Fig and it will work

**Comment by Kun8018** [comment]
Actually it is solved now, i can use it, thanks a lot.  Your product and your teams are excellent. Thanks again.
