### ISSUE TITLE
Fig doctor returns Unsupported terminal on xterm-256color ubunt

### ISSUE THREAD

**Issue by Dorkn123** [withfig/fig#2404]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 5.19.0-26-generic - "Ubuntu"

### Expected behaviour

Autocomplete needs to work

### Actual behaviour

Fig Autocomplete is not working
Due to terminal integrations failure 

❯ fig doctor --verbose
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ ~/.bashrc contains valid fig hooks
✔ ~/.profile contains valid fig hooks
✔ ~/.bash_profile contains valid fig hooks
✔ ~/.zshrc contains valid fig hooks
✔ ~/.zprofile contains valid fig hooks

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ Settings Corruption
✔ State Corruption
✔ Fig Integration
✔ SSH integration

Let's make sure Fig is running...
✔ Daemon
✔ Daemon diagnostics

Let's see if Fig is in a working state...
✔ Figterm
✔ Insertion lock does not exist
✔ Autocomplete dev mode
✔ Plugin dev mode
✔ Dashboard is loading from the correct URL
✔ Autocomplete is loading from the correct URL

Let's check if your system is compatible...
● Fig's support for Linux 5.19.0-26-generic - "Ubuntu" is in development. It may not work properly on your system.

✔ Fish is up to date

Let's check fig diagnostic...
✘ Autocomplete is active: Autocomplete is currently inactive. Your desktop integration(s) may be broken!

Let's check your terminal integrations...
● Unsupported terminal, if you believe this is a mistake or would like to see support for your terminal, run `fig issue`

Let's check Linux integrations
✔ IBus Env Check
✔ IBus Check
✔ Fig is not running in a sandbox

  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!

### Steps to reproduce

fig doctor --verbose

### Environment

```yaml
fig-details:
  - 2.10.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  - cores: 6
  - mem: 15.45 GB
os-info:
  - kernel: 5.19.0-26-generic
  - distro: "Ubuntu"
  - distro-version: "22.10 (Kinetic Kudu)"
environment:
  - shell: /usr/bin/zsh
  - terminal: <unknown>
  - cwd: /home/dor_knafo
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: :0
    - FIGTERM_SESSION_ID: f956bb9f-7406-4cb3-a371-039df730403c
    - FIG_HOSTNAME: Dor-Knafo-Msi-Ubuntu
    - FIG_PID: 44618
    - FIG_SET_PARENT: f956bb9f-7406-4cb3-a371-039df730403c
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.10.2
    - GLFW_IM_MODULE: ibus
    - GTK_IM_MODULE: ibus
    - PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/dor_knafo/.local/bin:/home/dor_knafo/.fig/bin:/home/dor_knafo/.local/share/fig/plugins/git-flow
    - QT_IM_MODULE: ibus
    - SHELL: /usr/bin/zsh
    - TERM: xterm-256color
    - XDG_CURRENT_DESKTOP: ubuntu:GNOME
    - XDG_SESSION_DESKTOP: ubuntu
    - XDG_SESSION_TYPE: wayland
    - XMODIFIERS: @im=ibus
```

**Comment by mschrage** [comment]
Autocomplete is not currently supported on Linux.
