### ISSUE TITLE
Fig wants to activate the third-party input method “FigInputMethod” doesn't  work

### ISSUE THREAD

**Issue by VictorDeGallegos** [withfig/fig#2405]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

I've seen the "allow" window pop up for the "FigInputMethod" and clicked "OK" there, but no changes in the Keyboard settings and nothing happens, **When I start my Macbook this message appears all time**

### Actual behaviour

**When I start my Macbook this message appears all time** `Fig wants to activate the third-party input method “FigInputMethod” `

![Captura de pantalla 2023-03-18 a la(s) 2 49 12 p m](https://user-images.githubusercontent.com/41756950/226138691-879492e2-295b-4061-b477-9d95e83d6fd6.png)

## Commands

```bash
❯ fig debug input-method                                                     ─╯
Installed? true
TISInputSource {
    bundle_id: Some(
        "io.fig.cursor",
    ),
    input_source_id: Some(
        "io.fig.cursor",
    ),
    input_source_category: Some(
        "TISCategoryPaletteInputSource",
    ),
    input_source_is_enabled: Some(
        true,
    ),
    input_source_is_selected: Some(
        true,
    ),
    localized_name: Some(
        "FigInputMethod",
    ),
    input_mode_id: None,
    category_keyboard: None,
}

```

I tried uninstall input-method and install it again but it is the same

## Input source 

![Captura de pantalla 2023-03-18 a la(s) 3 07 24 p m](https://user-images.githubusercontent.com/41756950/226140156-75e1457a-7086-4fe6-9f2a-f2baf01064b5.png)

**If I try manual I suppose that There is no request to permit fig.**

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/victor
  - exe-path: /Users/victor/.local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 1dc04c0f-11c0-4c7d-993a-524999fae13f
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /opt/homebrew/opt/curl/bin:/Users/victor/.local/bin:/Users/victor/micromamba/condabin:/Users/victor/.sdkman/candidates/scala/current/bin:/Users/victor/.sdkman/candidates/kotlin/current/bin:/Users/victor/.sdkman/candidates/java/current/bin:/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin:/Users/victor/.cabal/bin:/Users/victordegallegos/.ghcup/bin:/opt/homebrew/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/victor/.fig/bin:/Users/victor/.local/bin:/Users/victor/Downloads/flutter/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/victor/.rvm/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 1211
    - FIG_SET_PARENT: 1dc04c0f-11c0-4c7d-993a-524999fae13f
```

**Comment by bEDROch** [comment]
the exact same for me. I can't do anything on the dashboard of fig. Only by clicking somewhere, it starts the popup again....

**Comment by Jesse0716** [comment]
I had the same problem

**Comment by neo-cheung** [comment]
I have the same problem. 

It prompts when

1. restarting fig app
2. clicking anywhere in the dashboard.

---

```yml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 3621
```

**Comment by antony-frolov** [comment]
Same thing

**Comment by Bellisario** [comment]
Same thing here: #2406.

**Comment by sergiuwaxmann** [comment]
+1

**Comment by ArkoSno** [comment]
same here

**Comment by nautonk** [comment]
same here

**Comment by virezox** [comment]
+1

**Comment by monsterhxw** [comment]
same issue.

**Comment by rolcho** [comment]
same

**Comment by ballcs** [comment]
same

**Comment by rolcho** [comment]
I could solve the problem by copying the `/Applications/Fig.app/Contents/Helpers/FigInputMethod.app` into the `~/Library/Input Methods` folder

**Comment by hofgaert** [comment]
Great tip @rolcho, removing the symlink `~/Library/Input Methods` and copying it instead seems to do the trick.

**Comment by bkaplowitz** [comment]
deleting the symlink first seems to work, even without copying over. After toggling input within fig app, the FigInputMethod.app file is automatically replaced in the folder and there are no remaining issues.

**Comment by Shaurya50211** [comment]
I tried what @rolcho said but it still didn't work, Fig needs to fix this.

**Comment by yomni** [comment]
@hofgaert The workaround you told me works fine. thank you :)

**Comment by Shaurya50211** [comment]
I deleted the  `~/Library/Input Methods` completely and it seems to work fine

**Comment by tulioac** [comment]
@Shaurya50211 Did you deleted the folder or only the `FigInputMethod.app`?

**Comment by Shaurya50211** [comment]
I deleted the `FigInputMethod.app` only

**Comment by Shaurya50211** [comment]
If you delete it, the file will re-generate but it should solve the issue. If the issue is still there try running `fig doctor` if you haven't already. Whatever errors I had I pasted in ChatGPT and the answers it gave seems to do the magic!

**Comment by sergiuwaxmann** [comment]
Duplicates #2402

**Comment by gitmurali** [comment]
just click do not allow 😀

**Comment by Shaurya50211** [comment]
I did that multiple times but it still popped up

**Comment by simplg** [comment]
The solution provided by @Shaurya50211 fixed my issue. Thanks!

**Comment by alakshmeesh** [comment]
Gents - Similar issue reported in #2156

**Comment by luisinder** [comment]
> I deleted the `~/Library/Input Methods` completely and it seems to work fine

This works! 

Thanks!

**Comment by Shaurya50211** [comment]
> I deleted the `FigInputMethod.app` only
Glad to see this solution is working

**Comment by VictorDeGallegos** [comment]
If you keep getting that annoying notification, just follow @Shaurya50211 advice 

> I deleted the FigInputMethod.app only

Apparently the fig team has fixed it, I haven't done anything until today and the problem no longer persists. Whatever, I'll close this issue Nice day devs 👨🏻‍💻

**Comment by t-my** [comment]
For the frustrated how to get the dialog removed: `unlink ~/Library/Input Methods/FigInputMethod.app`

**Comment by grant0417** [comment]
This should be resolved now, just restart Fig and it will work

**Comment by Stoppels** [comment]
Luckily, it was only bothering me whenever I changed between light and dark themes (so usually twice a day), as I don't spend a lot of time in the app.

It has indeed solved itself now.
