### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by WaldoDoesTech** [withfig/fig#2410]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.2.1 (21D62)

### Expected behaviour

Usually starts up no without the request

### Actual behaviour

When I start Fig It opens System Preferences > Keyboard and request the following: “Fig” would like to enable third-party input method “FigInputMethod”. But I am unable to complete the request

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.2.1 (21D62)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh
```

**Comment by sooohka** [comment]
dup. https://github.com/withfig/fig/issues/2405

**Comment by sergiuwaxmann** [comment]
Duplicates #2402

**Comment by grant0417** [comment]
This should be resolved now, just restart Fig and it will work
