### ISSUE TITLE
multiple zsh(figterm) processes running 

### ISSUE THREAD

**Issue by ArkoSno** [withfig/fig#2413]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

I would expect less than 3 of the same processing running.

### Actual behaviour

too many zsh(figterm) processes running taking up cpu
![Screenshot 2023-03-20 at 20 54 49](https://user-images.githubusercontent.com/126357558/226464687-0799edf5-3b89-492b-bbea-1e1b4be44106.jpg)

![Screenshot 2023-03-20 at 20 56 37](https://user-images.githubusercontent.com/126357558/226464865-9b61ae55-2aa2-47b5-a06d-ce204c3bffd8.jpg)

### Steps to reproduce

open vs code or any other terminal running fig
open and close a couple of terminals
check activity monitor
expect at least 5 of the same process running

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/snowman/Downloads/Matrix
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: be2ff080-f001-44d5-a3a4-e30441b9ad2a
    - FIG_PID: 13207
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /Users/snowman/.pyenv/shims:/Users/snowman/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/snowman/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/snowman/.fig/bin:/Users/snowman/.local/bin:/opt/homebrew/opt/fzf/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/snowman
    - __CFBundleIdentifier: com.microsoft.VSCode
    - FIG_SET_PARENT: be2ff080-f001-44d5-a3a4-e30441b9ad2a
```

**Comment by ArkoSno** [comment]
2 questions guys 
Is this normal fig behaviour?
If not how do I fix it without manually force quitting every extra process?

**Comment by mschrage** [comment]
This is expected behavior. These are wrapper processes that handle communication between the shell and the Fig autocomplete UI.
