### ISSUE TITLE
bug: sys tray icon is duplicated in the wrong position

### ISSUE THREAD

**Issue by keul** [withfig/fig#2418]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.3 (21G419)

### Expected behaviour

Fig sys tray icon should be placed _only_ on tray area

### Actual behaviour

Sometimes the Fig system stray icon is duplicated in the same screen, on both the tray area *and* on the left side.
The alien icon is fully working: if I click it, the fig menu opens, but in the left side of the screen (where I have the Dock menu icons).

### Steps to reproduce

Is not easy to reproduce. The issue seems to happens when I plug/remove the secondary monitor.
In my case the secondary monitor is the main screen (the one with the systray bar)

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  - cores: 2
  - mem: 16.00 GB
os-info:
  - macOS 12.6.3 (21G419)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: brew
  - env-vars:
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/bash
```

**Comment by mschrage** [comment]
I cannot reproduce. Please share a screen recording capturing how to reproduce this behavior if possible.
