### ISSUE TITLE
404 on docs site 

### ISSUE THREAD

**Issue by xlanex6** [withfig/fig#242]
# Improve documentation

## Link 

In option page 
https://fig.io/docs/reference/option

## Describe the problem

Lots of 404 on 
```
Description:

See Suggestion
```
actual , wrong url path 
```
https://fig.io/docs/autocomplete/schemas/suggestion
```

## Describe the improvement

it should be 

```
https://fig.io/docs/reference/suggestion
```

## Additional context

![Markup 2021-07-05 at 08 43 49](https://user-images.githubusercontent.com/13418668/124558068-7fe33c00-de3a-11eb-9275-d494c37074d2.png)

**Comment by fwesss** [comment]
Suggestion links are now fixed throughout docs.
