### ISSUE TITLE
Problem with autocomplete in VS code

### ISSUE THREAD

**Issue by LucasLpc** [withfig/fig#2422]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS Ventura 13.2.1

### Expected behaviour

Autocomplete to appear in the terminal of VS Code on a project that use GIT.

### Actual behaviour

Autocomplete doesn't appear in the terminal of VS Code on a project that use GIT.

### Steps to reproduce

Go in VS Code and open a terminal in a project that use GIT.

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/lucaslaplanche
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 461b898a-bba9-409a-8cd8-15d9143702cd
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/lucaslaplanche/.fig/bin:/Users/lucaslaplanche/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 11969
    - FIG_SET_PARENT: 461b898a-bba9-409a-8cd8-15d9143702cd
```

**Comment by LucasLpc** [comment]
I think the problem is due to the size of my terminal.
<img width="568" alt="Capture d’écran 2023-03-24 à 16 09 32" src="https://user-images.githubusercontent.com/36164636/227564620-732cf5f1-58de-4981-95cf-f907fa9a67ce.png">
<img width="329" alt="Capture d’écran 2023-03-24 à 16 09 52" src="https://user-images.githubusercontent.com/36164636/227564642-9de18172-71f3-4836-85ee-6b67ca8b5a10.png">

**Comment by LucasLpc** [comment]
It seems to be also a problem from the theme I had because now it works... I had "Spaceship Prompt"

**Comment by hongkiulam** [comment]
Likewise, same issue with VSCode and spaceship prompt - I switched to using Starship instead

**Comment by JaccoGoris** [comment]
For me, the autocomplete window appears on my laptop monitor, after plugging in another monitor and moving vscode to the new one.

**Comment by mschrage** [comment]
It seems like Spaceship prompt was the culprit here. Closing this issue. If you are still running into issues, please open a new ticket.
