### ISSUE TITLE
Cannot delete script

### ISSUE THREAD

**Issue by nagman** [withfig/fig#2425]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

When I delete a Fig script, I wan't it to be deleted.

### Actual behaviour

The script is removed, then put back again with the error message `Cannot delete protected script`.

I've searched for a checkbox that sets the script as protected, but haven't found any.

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/quint/Downloads
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.aCf9CpwZHa/org.xquartz:0
    - FIGTERM_SESSION_ID: 3891cb32-f9a5-4263-b083-a075b655b92c
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /Users/quint/.yarn/bin:/Users/quint/.config/yarn/global/node_modules/.bin:/Users/quint/.krew/bin:/Users/quint/.npm-global/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/quint/.fig/bin:/Users/quint/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 10063
    - FIG_SET_PARENT: 3891cb32-f9a5-4263-b083-a075b655b92c
```

**Comment by ctafts** [comment]
I having the same issue. The script I am unable to remove is the `@docker/remove` from the scripts store, when I try to delete it I receive the error `Cannot delete protected script`. I duplicated it just to see if the duplicate could be removed and it has the same issue.

![Screenshot 2023-04-10 at 3 08 55 PM](https://user-images.githubusercontent.com/782892/230976792-1037949e-d353-47a0-a28d-ab47e98da71d.png)

![Screenshot 2023-04-10 at 3 12 10 PM](https://user-images.githubusercontent.com/782892/230978031-f6f24cf0-b696-42f6-b712-099283a9447b.png)

![Screenshot 2023-04-10 at 3 12 43 PM](https://user-images.githubusercontent.com/782892/230978228-dfb6b9ff-56c1-43a1-8733-a90af6355b9f.png)

**Comment by mschrage** [comment]
Hmm it seems like an admin permission is being copied from the template script. We will get this fixed.

**Comment by mschrage** [comment]
Pushed a fix to the backend now. Should be resolved going forward.

**Comment by nagman** [comment]
Still can't delete script

**Comment by ctafts** [comment]
@mschrage Do you know what version will include the fix? 2.16.0 still has this issue.

**Comment by mschrage** [comment]
Can you post the `@username/script` slug that you want to delete and I'll do it for you?

**Comment by nagman** [comment]
Sure, there are `@el-quinto/impossible-a-supprimer` and `@el-quinto/top-k8s`

**Comment by ctafts** [comment]
@mschrage The script I am unable to delete is in the screenshots I provided above 
![image](https://github.com/withfig/fig/assets/782892/c551bf27-b8bf-4c0b-ae1f-3ba02da1fcb2)
