### ISSUE TITLE
Fig would like to enable third-party input method FigInputMethod

### ISSUE THREAD

**Issue by algoad** [withfig/fig#2426]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

When clicking "OK" on 'Fig would like to enable third-party input method FigInputMethod' in mac keyboard system preference. The message should go away and not ask again.

### Actual behaviour

Every day the message reappears and asks me to confirm again and again.
If the fig GUI is open then the bug persists such that every time you click 'ok' the prompt immediately reopens and asks again. This happens endlessly.

### Steps to reproduce

Either
1) Open your macbook first thing and the prompt should automatically pop up in system preferences. Or,
2) Open fig GUI and the prompt will appear over and over

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/<name>
  - exe-path: /Users/<name>/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 21e2d965-2415-443d-9a41-b2a5c6fe0564
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /Users/<name>/Library/pnpm:/Users/<name>/.pyenv/shims:/Users/<name>/.sdkman/candidates/java/current/bin:/Users/<name>/.nvm/versions/node/v18.12.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/<name>/.fig/bin:/Users/<name>/.local/bin:/Users/<name>/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 10557
    - FIG_SET_PARENT: 21e2d965-2415-443d-9a41-b2a5c6fe0564
```

**Comment by grant0417** [comment]
Hey @algoad, I think this might have been a bug that was around at this time. This should have been fixed back in march, going to mark this as stale unless you or anyone else can confirm this is still an issue.

**Comment by chungweileong94** [comment]
This issue is happening again today, on version 2.16.0. The fig app is pretty much unusable.
