### ISSUE TITLE
Allow for wrapped text in autocomplete pop-up

### ISSUE THREAD

**Issue by jakobgilbert99** [withfig/fig#243]
User said:
> One UX nitpick I have about the popup window is that the documentation is a single line of horizontally scrolling text. The contextual docs are one of the best things about IDEs! Unless the reason is some technical hurdle, I’d much prefer a larger documentation section with wrapped text.

Proposal: Allow for the option to have wrapped text instead of scrolling in pop-up windows, regardless of their height and width.

**Comment by AndrewPrifer** [comment]
If the documentation section is completely dynamic and is allowed to take on any size, I can see this getting out of hand. Maybe there could be a separately specified max-height for the documentation section to fix this.

I can also imagine there might be people who don't want to see the docs at all, for whom the section could be hidden.
