### ISSUE TITLE
Fig is trying to add things to .bashrc but I use ZSH

### ISSUE THREAD

**Issue by LapsTimeOFF** [withfig/fig#2433]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

To not have any error.

### Actual behaviour

I get a `/Users/<redacted>/.bashrc is not read or writable` error I use ZSH though. Note: Fig does work though, just anoying to have the "Fig not working?" thing

### Environment

```yaml
fig-details:
  - 2.15.0-beta.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/<redacted>/<redacted project>
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 9b87425d-6645-45c1-b043-0ea178e0d441
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0-beta.1
    - PATH: /Users/<redacted>/.nvm/versions/node/v18.12.1/bin:/Users/<redacted>/Library/pnpm:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin:/Applications/VMware Fusion.app/Contents/Public:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/<redacted>/.fig/bin:/Users/<redacted>/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 12176
    - FIG_SET_PARENT: 9b87425d-6645-45c1-b043-0ea178e0d441
```

**Comment by mschrage** [comment]
Adding the shell integration to all supported shells is the expected behavior. 

Have you modified the permissions on your `.bashrc`?

**Comment by LapsTimeOFF** [comment]
Nope, it's using this permission `-rw-r--r--`

**Comment by philcruz** [comment]
I manage dot files for shells in source control using nix/nix-home manager. so the dot files are generated and set to read only but Fig complains the file are not writable and says "Fig is not working" even though it is. Could that be improved?

**Comment by LapsTimeOFF** [comment]
okay I just found a solution, ```
sudo chmod 775 .bashrc
``` and tada
