### ISSUE TITLE
bug: autocompletion insist on "autocompleting"

### ISSUE THREAD

**Issue by TinLe** [withfig/fig#2434]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

Autocompletion should not "autocomplete" when I did not TAB or 'space'.

### Actual behaviour

Autocompletion insists on autocompleting no matter what.

### Steps to reproduce

Create a file foo.tf.not

Try to rename it from foo.tf.not to foo.tf and autocompletion kept on insisting on changing the 'foo.tf' to 'foo.tf.not'.

E.g.

mv foo.tf.not foo.tf          <<< at this point autocompletion insists on adding the '.not' to the foo.tf, even if I did not SPACE nor TAB.

I ended up turning off autocompletion so I can get some work done.

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 12
  - mem: 32.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: iterm
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: com.mschrage.fig
    - PATH: /opt/homebrew/opt/postgresql@15/bin:/Users/tinle/bin:/Users/tinle/bin/aws:/Users/tinle/bin/gcp:/Users/tinle/.pyenv/shims:/opt/homebrew/opt/postgresql@15/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
    - TERM: xterm-256color
    - SHELL: /bin/zsh
```

**Comment by mschrage** [comment]
This is the expected behavior. You can change this in setting by modify the "Only show on Tab" option.
