### ISSUE TITLE
autocomplete not working on iTerm2

### ISSUE THREAD

**Issue by conikeec** [withfig/fig#2448]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.0 (22E252)

### Expected behaviour

To Autocomplete 

### Actual behaviour

Auto complete does not work despite trying many options

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 13.3.0 (22E252)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/chetanconikee
  - exe-path: /Users/chetanconikee/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: b1f1ff52-1fda-425c-b742-f9a24fc2c1d1
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/chetanconikee/.cargo/bin:/Users/chetanconikee/.fig/bin:/Users/chetanconikee/.local/bin:/Users/chetanconikee/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 26110
    - FIG_SET_PARENT: b1f1ff52-1fda-425c-b742-f9a24fc2c1d1
```

**Comment by mschrage** [comment]
Did you try running `fig doctor`?

**Comment by OrganicCat** [comment]
I ran into the same issue, but the suggestion `fig restart` got it to work. This is NOT suggested in the app, and the only reason I even found it was here in this issue. Fig autocomplete will popup, but tab and enter do nothing (no sounds, no errors, nothing). You can also not move up and down in the selection of the autocomplete list.

This is all fixed after running `fig restart` however
