### ISSUE TITLE
bug: PiOS Can't Install - Unable to locate package fig-headless

### ISSUE THREAD

**Issue by zlehnherr1** [withfig/fig#2449]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Raspbian GNU/Linux 11 (bullseye) aarc

### Expected behaviour

able to install using the provided command:
bash <(curl -fSsL https://fig.io/headless.sh) && exec $SHELL

### Actual behaviour

Runs but gets error "Unable to locate package fig-headless"

![image](https://user-images.githubusercontent.com/122128543/230499608-b9401a30-487a-42fb-b3c5-adc88ce9778f.png)

**Comment by nf-projects** [comment]
Same issue on Ubuntu 22.04

**Comment by dppeak** [comment]
Same on Raspberry Pi
