### ISSUE TITLE
When Firewall is enabled, login box does not appear

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#245]
![FJogSOQ7](https://user-images.githubusercontent.com/3155109/124858451-ebc0c400-df62-11eb-9a9a-df82b651dd4a.gif)

> MacOS default Firewall. It was on with no additional config (Stealth Mode off)
> I turned it off using System Preferences

**Comment by geenva** [comment]
MacOS 11.4 on an Intel MacBook

**Comment by parssak** [comment]
This has been fixed
