### ISSUE TITLE
bug: Fig command line autocomplete modifies original Bash prompt input colour to the PS1 colour

### ISSUE THREAD

**Issue by ziranjameshe** [withfig/fig#2454]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MAC OS

### Expected behaviour

Bash prompt colour should stay white

### Actual behaviour

but now it is the same as the PS1 colour (yellow) after installing fig

**Comment by mschrage** [comment]
Closing because not enough information was provided on for me to reproduce.
