### ISSUE TITLE
Fig iTerm integration gives an error when opening iterm  

### ISSUE THREAD

**Issue by Joachimzeelmaekers** [withfig/fig#246]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When opening iterm for the first time, I get a pop-up with a script error:
Could not create symlink to '/Users/joachimzeelmaekers/Library/Application Support/iTerm2/Scripts/AutoLaunch/fig-iterm-integration.scpt'

I checked the path, and the file fig-iterm-integration is available in that directory.

https://user-images.githubusercontent.com/22617224/124869377-69b3b800-dfc1-11eb-99db-0b18aa0393a1.mov

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.45 (B218)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.45 (B218) [Belgian] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/joachimzeelmaekers/.fig/bin/fig
Accessibility: true
Number of specs: 134
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/joachimzeelmaekers/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/joachimzeelmaekers/miniconda3/condabin:/Users/joachimzeelmaekers/google-cloud-sdk/bin:/Users/joachimzeelmaekers/.nvm/versions/node/v10.13.0/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/joachimzeelmaekers/.fig/bin:/Users/joachimzeelmaekers/.fig/autocomplete/flutter/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 1764/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mattschrage** [comment]
Thanks for reporting this @Joachimzeelmaekers!

Can you run `readlink ~/Library/Application Support/iTerm2/Scripts/AutoLaunch/fig-iterm-integration.scpt` to see the destination of the symlink? 

I've seen this issue occur if you launched Fig directly from the DMG before moving it the Applications folder.

**Comment by Joachimzeelmaekers** [comment]
Any time! I've been enjoying this tool a lot! 

I ran the command, but it seems like I don't get any output.
<img width="646" alt="Screenshot 2021-07-08 at 12 50 14" src="https://user-images.githubusercontent.com/22617224/124909691-0d658e00-dfeb-11eb-90b2-b5988c9504eb.png">

I ran it once from DMG, but it's moved into the Applications folder now.

**Comment by mattschrage** [comment]
Try deleting (click the Fig menubar icon > Integrations > Uninstall Fig) and then reinstalling Fig. I think this should fix the issue.

**Comment by mschrage** [comment]
@Joachimzeelmaekers did this fix the issue for you? If not, let's jump on a call https://calendly.com/mschrage/30min.

**Comment by Joachimzeelmaekers** [comment]
@mschrage sorry for the late answer. The problem seems to be solved now! Thanks alot!

**Comment by mschrage** [comment]
Great to hear! :)
