### ISSUE TITLE
`zshenv` was sourced twice (zprofile.pre.zsh & zprofile.post.zsh)

### ISSUE THREAD

**Issue by kayx23** [withfig/fig#2461]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS Catalina 10.15.7

### Description

I have ASCII art in `.zshenv` which prints a greeting whenever I open a terminal. After installing fig, I noticed the ASCII art is always printed twice. 

I noticed the reason might be fig is sourcing `zprofile.pre.zsh` and `zprofile.post.zsh`.

`$ cat ~/.zprofile`: 
```
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zprofile.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zprofile.pre.zsh"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zprofile.post.zsh" ]] && builtin source "$HOME/.fig/shell/zprofile.post.zsh"
```
`$ cat $HOME/.fig/shell/zprofile.post.zsh`:
```
[ -x ~/.local/bin/fig ] && eval "$(~/.local/bin/fig init zsh post --rcfile zprofile)"%                                                                          
```

`$ cat $HOME/.fig/shell/zprofile.pre.zsh`:
```
[ -x ~/.local/bin/fig ] && eval "$(~/.local/bin/fig init zsh pre --rcfile zprofile)"%
```

However I'm not sure what to modify so that .zshenv is only sourced once and prints only a greeting. 

### Steps to reproduce

* echo some greetings in `~/.zshenv` which should be printed on every terminal session
* `brew install fig` on Mac
* `fig login`
* enable autocomplete following steps in fig dashboard

**Comment by mschrage** [comment]
Sourcing `.zshenv` twice is the expected behavior when using Fig.

If you move your ASCII art inside of of your zshrc or zprofile, the issue should be resolved.
