### ISSUE TITLE
Fig doesn't work on linux

### ISSUE THREAD

**Issue by barbaat** [withfig/fig#2462]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 5.19.0-38-generic - "Ubuntu"

### Expected behaviour

I read all the issues exposed but I can't find the solution in the way to get fig working well. Autocomplete does't work at my terminal. Thank you for this amazing project.

### Actual behaviour

Autocomplete doesn't work.

![image](https://user-images.githubusercontent.com/101475909/231552818-dea1829c-393d-45ef-b1e1-377eb763ab9f.png)

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  - cores: 4
  - mem: 15.47 GB
os-info:
  - kernel: 5.19.0-38-generic
  - distro: "Ubuntu"
  - distro-version: "22.04.2 LTS (Jammy Jellyfish)"
environment:
  - shell: /usr/bin/bash
  - terminal: <unknown>
  - cwd: /home/barbaat_
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /bin/bash
    - GLFW_IM_MODULE: ibus
    - GTK_IM_MODULE: ibus
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: 57c97407-9d22-490a-bcca-1afe6b4df15e
    - XMODIFIERS: @im=ibus
    - XDG_SESSION_DESKTOP: ubuntu
    - XDG_SESSION_TYPE: wayland
    - XDG_CURRENT_DESKTOP: ubuntu:GNOME
    - FIG_TERM: 2.15.0
    - TERM: xterm-256color
    - FIG_PID: 11132
    - DISPLAY: :0
    - QT_IM_MODULE: ibus
    - PATH: /home/barbaat_/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/barbaat_/.local/bin:/home/barbaat_/.fig/bin:/home/barbaat_/.local/share/JetBrains/Toolbox/scripts
```

**Comment by mschrage** [comment]
Autocomplete is not currently supported on Linux.
