### ISSUE TITLE
fig source error - plugins function definitions not found

### ISSUE THREAD

**Issue by jrizz922** [withfig/fig#2463]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E261)

### Expected behaviour

running 'fig source' updates aliases 

### Actual behaviour

fig source

✅ Dotfiles sourced!

(eval):60: add-zsh-hook: function definition file not found
(eval):61: add-zsh-hook: function definition file not found
/Users/user/Documents/Git/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:105: is-at-least: function definition file not found
/Users/user/Documents/Git/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:420: is-at-least: function definition file not found
zsh-syntax-highlighting: Failed to load add-zsh-hook. Some speed optimizations will not be used.
zsh-syntax-highlighting: failed loading add-zsh-hook.
/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh:859: is-at-least: function definition file not found
/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh:864: add-zsh-hook: function definition file not found
/Users/user/.local/share/fig/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh:859: is-at-least: function definition file not found
/Users/user/.local/share/fig/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh:864: add-zsh-hook: function definition file not found
disable_you_should_use:1: add-zsh-hook: function definition file not found
disable_you_should_use:2: add-zsh-hook: function definition file not found
disable_you_should_use:3: add-zsh-hook: function definition file not found
disable_you_should_use:4: add-zsh-hook: function definition file not found
enable_you_should_use:2: add-zsh-hook: function definition file not found
enable_you_should_use:3: add-zsh-hook: function definition file not found
enable_you_should_use:4: add-zsh-hook: function definition file not found
enable_you_should_use:5: add-zsh-hook: function definition file not found
/Users/user/.local/share/fig/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:105: is-at-least: function definition file not found
/Users/user/.local/share/fig/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:420: is-at-least: function definition file not found
zsh-syntax-highlighting: Failed to load add-zsh-hook. Some speed optimizations will not be used.
zsh-syntax-highlighting: failed loading add-zsh-hook.

### Steps to reproduce

fig source

### Environment

```yaml
fig-details:
  - 2.15.0-beta.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 13.3.1 (22E261)
environment:
  - shell: /usr/local/Cellar/zsh/5.9/bin/zsh
  - terminal: iterm
  - cwd: /Users/user
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 21ad110f-d1ff-4cdd-840f-762c03efecfe
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0-beta.1
    - PATH: /opt/local/bin:/opt/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Little Snitch.app/Contents/Components:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/user/.fig/bin:/Users/user/.local/bin:/usr/local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 63351
    - FIG_SET_PARENT: 21ad110f-d1ff-4cdd-840f-762c03efecfe
```

**Comment by mschrage** [comment]
Shell plugins are built and maintained by the community and are not guaranteed to work.
