### ISSUE TITLE
Cannot signin

### ISSUE THREAD

**Issue by ZanetaK** [withfig/fig#2470]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E261)

### Expected behaviour

I expect to be able to login to the dashboard of from the console via github, but the redirection always fails and I am never really able to login.

~ % fig login
✔ Select action · Sign in with GitHub
error: Reqwest error: error sending request for url (https://api.fig.io/auth/github/device-code): error trying to connect: tls handshake eof 

### Actual behaviour

Login into the dashboard of Fig

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.3.1 (22E261)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/zaneta
  - exe-path: /Users/zaneta/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 92424546-d3f8-4d6f-bfae-0beb3aaec3ab
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0
    - PATH: /Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/zaneta/.fig/bin:/Users/zaneta/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 3110
    - FIG_SET_PARENT: 92424546-d3f8-4d6f-bfae-0beb3aaec3ab
```

**Comment by GorkemGuray** [comment]
I also cannot log in.

**Comment by mykytastatiev** [comment]
Same error type after login too. It says Apollo error. Looks like fig API servers are not responding (overload idk)

**Comment by ZanetaK** [comment]
It is fine today. No action has been done on my side. Closing.
