### ISSUE TITLE
[Kitty] fig runs a process or subshell that makes kitty warn me before exiting

### ISSUE THREAD

**Issue by kevcube** [withfig/fig#2474]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E261)

### Expected behaviour

With the fig integration installed, I expect that there will be no additional subshells or processes, and if there must be, that they will be completely transparent to me

### Actual behaviour

kitty reports that there is one program running if I attempt to close a window/tab
https://user-images.githubusercontent.com/716806/232586104-0449d07e-48cd-44d9-b161-a7d44f74bdf0.mov

### Steps to reproduce

yes

- download kitty
- enable fig
- start new shell, cmd+w

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.3.1 (22E261)
environment:
  - shell: /bin/zsh
  - terminal: kitty
  - cwd: /Users/masterpoint
  - exe-path: /Users/masterpoint/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 44cba9c9-c54f-4f90-afbc-05fa7e7fa688
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0
    - PATH: /Users/masterpoint/.local/share/zinit/plugins/starship---starship:/Users/masterpoint/.local/share/zinit/polaris/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/kitty.app/Contents/MacOS:/Users/masterpoint/.fig/bin:/Users/masterpoint/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-kitty
    - __CFBundleIdentifier: net.kovidgoyal.kitty
    - FIG_PID: 19183
    - FIG_SET_PARENT: 44cba9c9-c54f-4f90-afbc-05fa7e7fa688
```

**Comment by kevcube** [comment]
Seems related to #1332, can't tell if it's a duplicate.

**Comment by kevcube** [comment]
re: above - appears unrelated, this problem is present with kitty's shell_integration disabled.

**Comment by kevcube** [comment]
Ah. Re: re: above, it looks like this IS a problem with the shell integration not working. Because this "one program running" seems to be the login shell.

**Comment by mschrage** [comment]
In order to provide autocomplete, Fig launches a pseudoterminal process called `figterm`.

This is a core requirement for our tool to work as expected. Perhaps this can be fixed upstream or in settings by whitelisting the figterm process.

**Comment by kevcube** [comment]
@mschrage is that the same reason that #1332 is not working? I think it is hard to fix upstream without that issue being validated first
