### ISSUE TITLE
Autocomplete wrong position

### ISSUE THREAD

**Issue by P4uloBrandao** [withfig/fig#2479]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 6.1.11-76060111-generic - "Pop!_OS 22.04 LTS"

### Expected behaviour

The autocomplete window on my terminal

### Actual behaviour

The autocomplete window is on the corner of the screen

### Steps to reproduce

Type something on terminal and let autocomplete appear

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  - cores: 8
  - mem: 30.99 GB
os-info:
  - kernel: 6.1.11-76060111-generic
  - distro: "Pop!_OS 22.04 LTS"
  - distro-version: "22.04 LTS"
environment:
  - shell: /usr/bin/bash
  - terminal: vscode
  - cwd: /home/vnuts/Desktop/ProjetosVN/campaigns
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /bin/bash
    - GTK_IM_MODULE: ibus
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: 65b3f666-7948-40d1-838b-316c214c9add
    - XMODIFIERS: @im=ibus
    - XDG_SESSION_DESKTOP: pop
    - XDG_SESSION_TYPE: x11
    - XDG_CURRENT_DESKTOP: Unity
    - FIG_TERM: 2.15.0
    - TERM: xterm-256color
    - FIG_PID: 136356
    - DISPLAY: :0
    - QT_IM_MODULE: ibus
    - PATH: /home/vnuts/.local/bin:/home/vnuts/.nvm/versions/node/v14.20.1/bin:/home/vnuts/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/vnuts/.fig/bin
```

**Comment by P4uloBrandao** [comment]
![image](https://user-images.githubusercontent.com/99819758/233294567-557d96e6-fa4d-4155-acbb-1d12777282e5.png)

**Comment by mschrage** [comment]
Currently we don't support autocomplete on Linux.

**Comment by metebyte** [comment]
The issue has also been detected on macOS.

<img width="602" alt="Screenshot 2023-08-01 at 09 21 55" src="https://github.com/withfig/fig/assets/92409276/88ade253-ce3c-4328-a18f-828102651755">
