### ISSUE TITLE
Fig is conflicting with UniKey typing

### ISSUE THREAD

**Issue by jakobgilbert99** [withfig/fig#248]
Fig is interfering with the use of UniKey, specifically in its use as a popular Vietnamese keyboard software. The first character of every word is being removed, as the user says here:
> Most of the Vietnamese use this tool to enter Vietnamese unicode typing https://evkeyvn.com. (Hế lô đây là tiếng Việt).
Fig did not break but it makes cutoff the text somehow:
> - Without Fig: Hế lô đây là tiếng Việt 
> - With Fig: ế ô ây là iếng Việt

**Comment by mattschrage** [comment]
Does this happen in all apps or is it limited just to the terminal?

**Comment by conanak99** [comment]
Hi, it happens in all apps.

**Comment by parssak** [comment]
This has been fixed
