### ISSUE TITLE
fig fails to launch error 10810 on macOS 10.13.6

### ISSUE THREAD

**Issue by 1000000000000000000000000000000** [withfig/fig#2483]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 10.13.6 (17G14042)

### Expected behaviour

I ran fig login and logged in successfully. I then ran fig launch and I expected it to launch. It did not.

### Actual behaviour

I ran command 'fig launch' and it failed. I ran fig doctor and no clear solution was presented.

### Steps to reproduce

fig launch yields this message:

$ fig launch
Launching Fig...
error: failed to launch fig: `LSOpenURLsWithRole() failed for the application /Applications/Fig.app with error -10810.

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz
  - cores: 4
  - mem: 8.00 GB
os-info:
  - macOS 10.13.6 (17G14042)
environment:
  - shell: /usr/local/Cellar/bash/5.2.15/bin/bash
  - terminal: terminal
  - cwd: /Users/richardpearson/Applications
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /usr/local/bin/bash
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: 5d54ac53-c4bf-4741-a861-3eeb86ad5acb
    - FIG_TERM: 2.15.0
    - TERM: xterm-256color
    - FIG_PID: 27864
    - DISPLAY: /private/tmp/com.apple.launchd.IjmwnRa6Le/org.xquartz:0
    - PATH: /Users/richardpearson/perl5/perlbrew/bin:/Users/richardpearson/perl5/perlbrew/perls/perl-5.28.0/bin:/Users/richardpearson/.cargo/bin:/Users/richardpearson/miniconda3/bin:/Users/richardpearson/miniconda3/condabin:/Users/richardpearson/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Users/richardpearson/.fig/bin:/Users/richardpearson/.local/bin:/Users/richardpearson/Applications/sratoolkit.2.10.9-mac64/bin:/Users/richardpearson/Applications/SPAdes-3.15.1-Darwin/bin:/Users/richardpearson/Applications/Trimmomatic-0.39/trimmomatic-0.39.jar
```

**Comment by mschrage** [comment]
It looks like you are using an unsupported version of macOS. Please upgrade and see if the issue still persists.
