### ISSUE TITLE
iconv: conversion from -t unsupported

### ISSUE THREAD

**Issue by srxavi** [withfig/fig#2484]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E261)

### Expected behaviour

This error not appearing

### Actual behaviour

Every time I input a command in the command line I get this output:
```
iconv: conversion from -t unsupported
iconv: try 'iconv -l' to get the list of supported encodings
Error converting string from  to UTF-8
```

### Steps to reproduce

When

```
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
``` 
is added at the end of `.zshrc`, this error appears.

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.3.1 (22E261)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/xavier.francisco
  - exe-path: /Users/xavier.francisco/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: ae2eeec6-36d4-4133-981d-9bb09a1c8e28
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0
    - PATH: /Users/xavier.francisco/.nvm/versions/node/v16.13.1/bin:/opt/homebrew/opt/python@3.11/libexec/bin:/usr/local/bin:/Users/xavier.francisco/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/xavier.francisco/.fig/bin:/Users/xavier.francisco/.local/bin:/Users/xavier.francisco/Library/Application Support/JetBrains/Toolbox/scripts:/System/Cryptexes/App/usr/bin:/opt/homebrew/opt/python/libexec/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 17241
    - FIG_SET_PARENT: ae2eeec6-36d4-4133-981d-9bb09a1c8e28
```

**Comment by mschrage** [comment]
This is not a command we use internally. You likely have installed a shell plugin that requires this. I'd recommend uninstalling all plugins and seeing if this resolves the issue.

**Comment by mschrage** [comment]
@iRenadMB do you have any plugins installed via Fig?

**Comment by iRenadMB** [comment]
I think no, just I download (oh my zsh)

**Comment by iRenadMB** [comment]
iconv: conversion from -t unsupported
iconv: try 'iconv -l' to get the list of supported encodings
Error converting string from  to UTF-8

This is the last message shown, I cannot write any command.

**Comment by srxavi** [comment]
To fix it I had to add export LANG="en_US@UTF-8" to my .zshrc

**Comment by iRenadMB** [comment]
ok I will try

**Comment by iRenadMB** [comment]
its the same, not working

**Comment by acernar** [comment]
It worked for me by adding export LANG="en_US@UTF-8" then I had to restart and that's it

**Comment by BrodaNoel** [comment]
This is back after the upgrade of iTerm 3.5.0.

**Comment by marvin-min** [comment]
> This is back after the upgrade of iTerm 3.5.0.

reproduced the issue upgrade to 3.5.0 this morning. :(

**Comment by tubzby** [comment]
Please reopen this, happened to me this morning after upgrading to 3.5.0.

**Comment by rick20** [comment]
Same here....the issue appears again after upgrading to 3.5.0

**Comment by congnd** [comment]
Happened to me as well. 
But luckily, `export LANG=en_US@UTF-8` does fix the issue.

**Comment by sreenivasulu-paruchuri** [comment]
after adding export LC_ALL="en_US.UTF-8" in .zshrc, i am not seeing the issue

https://groups.google.com/g/iterm2-discuss/c/X5Gma8XRVyw?pli=1

after adding we can check by typing "locale" in item2

**Comment by tubzby** [comment]
> after adding export LC_ALL="en_US.UTF-8" in .zshrc, i am not seeing the issue
> 
> https://groups.google.com/g/iterm2-discuss/c/X5Gma8XRVyw?pli=1
> 
> after adding we can check by typing "locale" in item2

Not working for me.

**Comment by bozd4g** [comment]
thanks @congnd , that worked to me.

> Happened to me as well. But luckily, `export LANG=en_US@UTF-8` does fix the issue.

**Comment by bozd4g** [comment]
thanks @sreenivasulu-paruchuri , that worked to me.

> after adding export LC_ALL="en_US.UTF-8" in .zshrc, i am not seeing the issue

**Comment by hovanhoa** [comment]
the issue appears again after upgrading iTerm terminal to 3.5.0

**Comment by lucadamo** [comment]
This solved the issue:

1. Open .zshrc
2. Add the line:
export LC_ALL="en_US.UTF-8"
3. Save .zshrc
4. Restart Terminal

**Comment by newTypeGeek** [comment]
> > This solved the issue:
> > 
> > 1. Open .zshrc
> > 2. Add the line:
> >    export LC_ALL="en_US.UTF-8"
> > 3. Save .zshrc
> > 4. Restart Terminal
> 
> This works on my iterm2 3.5.0

Thanks, it works for me as well - iTerm2 3.5.0

**Comment by Elfsong** [comment]
> This solved the issue:
> 
> 1. Open .zshrc
> 2. Add the line:
>    export LC_ALL="en_US.UTF-8"
> 3. Save .zshrc
> 4. Restart Terminal

It works for me. Be careful to set 'LC_ALL' instead of 'LANG'.

**Comment by peiel** [comment]
try `export LC_ALL="en_US.UTF-8"`

**Comment by cloudofgeorge** [comment]
Using of `export LC_ALL="en_US.UTF-8"` in `.zshrc` works pretty well and solves the problem

**Comment by anicarrr** [comment]
> This solved the issue:
> 
> 1. Open .zshrc
> 2. Add the line:
>    export LC_ALL="en_US.UTF-8"
> 3. Save .zshrc
> 4. Restart Terminal

instead of restarting you can just run `source $HOME/.zshrc`

**Comment by shivendra-ntnx** [comment]
Add this is .zshrc: 
export LANG=en_US.UTF-8

**Comment by Star1er** [comment]
> Если вы видите это в iTerm2, пожалуйста, ознакомьтесь с этой проблемой: https://gitlab.com/gnachman/iterm2/-/issues/11484

the only thing that helped, thank you
