### ISSUE TITLE
bug: Inconsequential error appears in PyCharm Terminal after installing `--with-input` integration

### ISSUE THREAD

**Issue by evictor** [withfig/fig#2486]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Ventura 13.2.1 (22D68)

### Expected behaviour

PyCharm terminal opens without any errors straight to the input line/cursor. Like this for me:

<img width="267" alt="image" src="https://user-images.githubusercontent.com/1620156/233759019-f4ceb370-1a02-4cab-abde-84d00d03fac7.png">

### Actual behaviour

An error occurs during terminal loading:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/1620156/233759033-b49cacd1-27ad-454c-8990-1176241569f0.png">

The error text is:

```bash: /Contents/plugins/terminal/jediterm-bash.in: No such file or directory```

### Steps to reproduce

Every time I open a new terminal in PyCharm—whether that be several in a row, the first one in a session, the first one after restart of IDE, etc.—this error occurs at the beginning.

This began immediately after running `fig install --input-method` to get fig into PyCharm.

### Environment

```yaml
# Some information redacted

fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 32.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/bash
  - terminal: intellij-pycharm
  - cwd: /Users/zeke/<redacted>
  - exe-path: /Users/zeke/.local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_PID: 1941
    - TERM: xterm-256color
    - SHELL: /bin/bash
    - FIGTERM_SESSION_ID: <redacted>
    - FIG_SET_PARENT_CHECK: 1
    - PATH: <redacted>
    - __CFBundleIdentifier: com.jetbrains.pycharm
    - FIG_TERM: 2.15.0
```

**Comment by mschrage** [comment]
Related #2499

**Comment by chaynabors** [comment]
You should no longer see this error once Fig version 2.16.0 releases.
