### ISSUE TITLE
intellij terminal not opening while starting intellij

### ISSUE THREAD

**Issue by chandan-codeprism** [withfig/fig#2487]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E261)

### Expected behaviour

when I starting intellij or opening it should open terminal like normally

### Actual behaviour

But when i click on terminal button but again i have to click on + icon to open new tab of terminal and also one irritating line printing on terminal like (eval):source:87: no such file or directory: /Applications/IntelliJ IDEA.app/Contents/plugins/terminal/.zshenv
plz fix this

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.3.1 (22E261)
environment:
  - shell: /bin/zsh
  - terminal: intellij-idea-ultimate
  - cwd: /Volumes/workspace/work/heartfulness/heartfulness-backend
  - exe-path: /Users/codeprismtechnologies/.local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 230158d9-0653-4138-89a0-ad3b9e225e05
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0
    - PATH: /Users/codeprismtechnologies/.docker/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/openjdk@11/bin:/Users/codeprismtechnologies/bin:/Users/codeprismtechnologies/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/codeprismtechnologies/.cache/zsh4humans/v5/fzf/bin:/Users/codeprismtechnologies/.fig/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.intellij
    - FIG_PID: 8738
    - FIG_SET_PARENT: 230158d9-0653-4138-89a0-ad3b9e225e05
```

**Comment by mschrage** [comment]
Related #2499

**Comment by chaynabors** [comment]
You shouldn't see this warning once we release Fig version 2.16.0 but ping me if your terminal still isn't opening up right away and I'll reopen.

**Comment by chandan-codeprism** [comment]
Thank you for letting me know about the upcoming update for Fig version
2.16.0. I appreciate your attention to this matter. I will keep an eye out
for the release and let you know if I encounter any further issues. Thanks
again for your support!
