### ISSUE TITLE
Fig autocomplete doesn't work on Fedora 38 - ❌ figterm (128213) <- ✅ bash (128257)

### ISSUE THREAD

**Issue by piotrowskiadam** [withfig/fig#2489]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux Fedora 38 

### Expected behaviour

There are no autocomplete suggestions and `fig _ should-figterm-launch` outputs `❌ figterm (128213) <- ✅ bash (128257)`

### Actual behaviour

![image](https://user-images.githubusercontent.com/55131509/234125428-62f32c3b-62c6-42c2-863d-9376761168af.png)

### Steps to reproduce

`fig`
Trying to `cd` into some folders. No autosuggestion
`Fig doctor`
`fig _ should-figterm-launch`
outputs: `❌ figterm (128213) <- ✅ bash (128257)`

### Environment

```yaml
fig-details:
  - 2.16.0-nightly.20230413
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  - cores: 4
  - mem: 15.37 GB
os-info:
  - kernel: 6.2.11-300.fc38.x86_64
  - distro: "Fedora Linux 38 (Workstation Edition)"
  - distro-version: "38 (Workstation Edition)"
  - distro-variant: "Workstation Edition"
environment:
  - shell: /usr/bin/bash
  - terminal: hyper
  - cwd: /home/adampiotrowski
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /bin/bash
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: a8df45b0-e88e-482c-ab5f-0ec3beba4bb5
    - XMODIFIERS: @im=ibus
    - XDG_SESSION_DESKTOP: gnome
    - XDG_SESSION_TYPE: wayland
    - XDG_CURRENT_DESKTOP: GNOME
    - FIG_TERM: 2.16.0-nightly.20230413
    - TERM: xterm-256color
    - FIG_PID: 128257
    - DISPLAY: :0
    - QT_IM_MODULE: ibus
    - PATH: /home/adampiotrowski/.local/bin:/home/adampiotrowski/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin:/home/adampiotrowski/.fig/bin
```

**Comment by mschrage** [comment]
Autocomplete on Linux is currently not supported.
