### ISSUE TITLE
Detect new aliases without requiring autocomplete to be restarted

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#249]
This could be accomplished using the shell integration. We could update the list of aliases for a given TTY every time the prompt returned.

**Questions**
Performance: would this slow down the prompt? 

Codebase: where should the mapping between aliases and TTYs be stored? (macOS vs autocomplete-engine)

**Comment by QuiiBz** [comment]
This could also be done completely inside autocomplete-engine. When the user `source` his shellrc, we can reload the aliases. This can be detected when pressing "Enter" and having a branch starting with `source`.

Not sure about this, but is there a hook called when the user changes its focused terminal? If so, it can be used to also reload the aliases, so both sourcing and opening a new terminal would works.
