### ISSUE TITLE
bug: zshrc.pre.zsh stops and makes the zsh startup cycle restart

### ISSUE THREAD

**Issue by sanderbongers** [withfig/fig#2496]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1

### Expected behaviour

I expect Fig to load once, not twice; efficiently with the least overhead realistically possible. This issue doubles the load time of every shell tab. It happens on both of my laptops so there will probably be more users affected.

### Actual behaviour

`~/.fig/shell/zshrc.pre.zsh` makes the 'zsh startup cycle' restart, loading all startup files twice. It's unclear if it's Fig silently crashing or a wrong initialization of Fig. The next cycle everything works.

### Steps to reproduce

1. Set `setopt source_trace` in `/etc/zshenv`. This will show the sourced files as they are loaded:
```bash
+/etc/zprofile:1> <sourcetrace>
+/etc/zshrc:1> <sourcetrace>
+/Users/sander/.zshrc:1> <sourcetrace>
+/Users/sander/.fig/shell/zshrc.pre.zsh:1> <sourcetrace>
+/etc/zprofile:1> <sourcetrace>
+/etc/zshrc:1> <sourcetrace>
+/Users/sander/.zshrc:1> <sourcetrace>
+/Users/sander/.fig/shell/zshrc.pre.zsh:1> <sourcetrace>
+/Users/sander/.fig/shell/zshrc.post.zsh:1> <sourcetrace>
```
After `zshrc.pre.zsh`, `/etc/zprofile` and all following files are loaded another time, and so is `zshrc.pre.zsh`, after which `zshrc.post.zsh` finishes the cycle.

By setting `setopt xtrace` it becomes more clear. I've cleared the entire `.zshrc`except for Fig's pre and post scripts to rule out any third party plugins being the cause, here is the result: [xtrace.txt](https://github.com/withfig/fig/files/11360818/xtrace.txt).

As you can see, after line 132 Fig stops and `/etc/zprofile` is loaded again. There is no visual indication, I found out after digging into zsh's internal architecture to see what is actually going on in the background.

What's remarkable is, deleting `~/.local/bin/zsh` solves the problem, but there's probably a reason why both paths are deliberately loaded?

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 13.3.1 (22E261)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/sander
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: d486d515-9e69-4e26-be12-0cfb53766b07
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/sander/.fig/bin:/Users/sander/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 59773
    - FIG_SET_PARENT: d486d515-9e69-4e26-be12-0cfb53766b07
```

**Comment by mschrage** [comment]
This is actually not a bug. The first time `zshrc.pre.zsh` is sourced we exec into a separate process called `figterm` which wraps the shell in a psuedoterminal so we can determine the commands by typed and provide autocompletion.

This is why we recommend keeping our init script at the top of both your zprofile and your zshrc.
