### ISSUE TITLE
bug: commit lockfile

### ISSUE THREAD

**Issue by happysalada** [withfig/fig#2498]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

all

### Expected behaviour

Would it be possible to commit the lockfille to the repo ? (package-lock.json, yarn.lock, or which ever you use ?).
The reason is that this would make it a lot easier to package this for different linux distribution.
(in particular I would like to package this for nixos)

### Actual behaviour

Without a lockfile, packaging is not reproducible and so it makes things much harder for maintainers

**Comment by mschrage** [comment]
If you are looking for the source of truth for the current version of Fig Desktop, you could use this: https://repo.fig.io/generic/stable/index.json

**Comment by happysalada** [comment]
@mschrage thank you for your response!

I'm looking for the package-lock.json or the yarn.lock inside the github repo in order to be able to build this from source. Some linux distributions prefer to have a build from source. The problem with the source of truth, is that without a lockfile, the build on another machine will lead to a different sha256 that the one in the source of truth. So there is no way to verify the source of truth.

Is there a reason you prefer not to commit the lockfile ? Maybe because it changes too much ?
