### ISSUE TITLE
Integrate Autocomplete with IntelliJ

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#25]
The title says it all.

Please subscribe to this issue to get an update when the autocomplete integration with IntelliJ is ready :smile:

**Comment by maksnester** [comment]
Fig is not so useful for my daily work without it :(

**Comment by mschrage** [comment]
Duplicate of #49

**Comment by SeparateRecords** [comment]
Closing in favor of issue 49 - check it out for details and updates!

**Comment by brendanfalk** [comment]
(And if you want to test our experimental integration with JetBrains, please use: https://fig.io/docs/support/enabling-input-method)

**Comment by TapaiBalazs** [comment]
@brendanfalk I tried, but sadly it doesn't work if you use JetBrains toolbox and install the IDE in a different folder. It fails at the second step not finding the IDE. Could it be somehow set to be configurable where to look for the IDE? 🤔

**Comment by TapaiBalazs** [comment]
Okay, the error was that it did not find the folder under `~/Library/Application Support/JetBrains/WebStorm2021.3/`. I created that folder manually, then copied the installed contents to my custom plugins library `~/devtools/plugins/` (in my case). After that I needed to follow the above link and do the things. Now it works I have fig autocomplete in my Webstorm. :)
