### ISSUE TITLE
Strange characters appear in name of `figterm` process

### ISSUE THREAD

**Issue by sullivan-sean** [withfig/fig#251]
<img width="399" alt="Screen Shot 2021-07-09 at 11 48 41 AM" src="https://user-images.githubusercontent.com/22581534/125122488-5b8d9680-e0aa-11eb-9686-8b68dd44afc2.png">

As far as I can tell it seems like the issue is that `exec -a $VARIABLE /bin/process/to/run` doesn't expand environment variables...?

Happens on:
macOS Mojave 10.14.6
```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by mschrage** [comment]
Closing as stale
