### ISSUE TITLE
auto-comletion for the `cd` shows only absolute paths from the root directory.

### ISSUE THREAD

**Issue by anis00723** [withfig/fig#2510]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E261)

### Expected behaviour

I expect the auto-completion to show me the directories under the `pwd`

### Actual behaviour

It shows directories under `/`:

![CleanShot 2023-05-04 at 17 39 45](https://user-images.githubusercontent.com/7860023/236269517-11be3989-d801-438d-a023-c442a881fc56.png)

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.3.1 (22E261)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/mac
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 651a1c39-2312-4981-b590-86b86cd2d612
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0
    - PATH: /Users/mac/.emacs.d/bin:/opt/homebrew/opt/llvm/bin:/Users/mac/Library/pnpm:/Users/mac/.poetry/bin:/opt/homebrew/opt/python@3.10/bin:/Users/mac/.nvm/versions/node/v18.16.0/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Applications/Little Snitch.app/Contents/Components:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/mac/.cargo/bin:/Users/mac/.fig/bin:/Users/mac/.local/bin:/Users/mac/Library/Application Support/JetBrains/Toolbox/scripts:/Users/mac/fvm/default/bin:/Users/mac/.bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 60640
    - FIG_SET_PARENT: 651a1c39-2312-4981-b590-86b86cd2d612
```

**Comment by mschrage** [comment]
Hey @anis00723, I cannot reproduce this. Based on the diagnostic output, Fig thinks you are in the `/Users/mac` directory.

You might try commenting out other plugins from your zshrc to isolate if something else is causing the issue.

**Comment by anis00723** [comment]
@mschrage I tried removing oh-my-zsh and powerlevel10k and all the plugins and it still thinks that I'm in /Users/mac

**Comment by mschrage** [comment]
Do you have other shell integrations in your .zshrc?

**Comment by mschrage** [comment]
Also can you ru `which cd`? That doesn't look like the normal completions for `cd`.

**Comment by mschrage** [comment]
My guess if that you have `cd` aliased to `z`, so you are seeing different completions.

**Comment by anis00723** [comment]
I have `z` installed but it was working before, also I uninstalled everything and tried with minimal `.zshrc` but `fig` still behaves the same.

**Comment by mschrage** [comment]
Please run `which cd`? We respect aliases configured by the user so you are getting suggestions associated with `z` not `cd`. If you remove that alias, you'll get the default `cd` suggestions.

**Comment by anis00723** [comment]
```
❯ which cd
cd: aliased to z
```

![CleanShot 2023-05-06 at 15 40 50](https://user-images.githubusercontent.com/7860023/236630881-e5e7d9ac-a5c7-41f0-97f1-acebd63bc2f4.png)

```
❯ which cd
cd: shell built-in command
```

![CleanShot 2023-05-06 at 15 42 27](https://user-images.githubusercontent.com/7860023/236630972-2452f5f2-96a5-420c-9ae0-e86d98162ed6.png)

As I told you it doesn't make a difference.

**Comment by anis00723** [comment]
Any ideas to try?
