### ISSUE TITLE
Add support for Warp Terminal

### ISSUE THREAD

**Issue by amponce** [withfig/fig#2512]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:

Please add support for [Warp Terminal](https://www.warp.dev/) support (warp.dev). Warp has a growing user base and I feel like a fig integration be an amazing addition.

**Comment by mschrage** [comment]
Closing as duplicate of #785
