### ISSUE TITLE
Using fig with nix home-manager

### ISSUE THREAD

**Issue by szicari-farmobile** [withfig/fig#2515]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E261)

### Expected behaviour

Ability for Fig to be able to bootstrap itself in a situation where `.zshrc` is not writable.

### Actual behaviour

Fig either sets itself up or simply does not work. It is not clear how to bootstrap Fig outside the fully guided process.

### Steps to reproduce

- Ensure ZSH is your default shell.
- Install Nix home-manager (easiest via [Fleek](https://getfleek.dev)).
- Attempt to install Fig.
- Note the error related to `.zshrc`:

```
❯ fig doctor

✘ zsh ~/.zshrc integration check: /Users/seanzicari/.zshrc is not read or writable

  To fix run the following commands:
      1. sudo chown $USER /Users/seanzicari/.zshrc && sudo chmod 644 /Users/seanzicari/.zshrc
      2. fig integrations install dotfiles
      3. fig doctor


✘ Doctor found errors. Please fix them and try again.
```

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.3.1 (22E261)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/seanzicari
  - exe-path: /Users/seanzicari/.local/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /bin/zsh
    - __CFBundleIdentifier: com.googlecode.iterm2
    - PATH: /opt/homebrew/Cellar/pyenv-virtualenv/1.2.1/shims:/Users/seanzicari/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/seanzicari/bin:/Users/seanzicari/.local/bin:/Users/seanzicari/.local/confluent/bin:/opt/homebrew/bin:/Users/seanzicari/.pyenv/shims
    - DISPLAY: /private/tmp/com.apple.launchd.bEMCndP4pK/org.xquartz:0
    - TERM: xterm-256color
```

**Comment by mschrage** [comment]
If you run the install script on a machine with writable dotfiles, you can just copy those additions into your nix configuration.

**Comment by szicari-farmobile** [comment]
I don't need to concern over `fig doctor`'s warnings?

**Comment by grant0417** [comment]
If the warnings are just about your config file you should be fine.

You can check for other issues with `fig doctor --verbose`.
