### ISSUE TITLE
Autocompletions are not suggested

### ISSUE THREAD

**Issue by sheriffderek** [withfig/fig#2519]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.4.0 (21F79)

### Expected behaviour

type 
`git ` (with space)
and then see command suggestions

(I looked over all of the settings but everything I saw made me expect it to work out of the box)

### Actual behaviour

type 
`git ` (with space)
No suggestions are brought up. Everything is as if Fig was not installed.

### Steps to reproduce

Install Fig. Try and use it.

In my case, I tried it with Terminal, iTerm, and Hyper. I restarted them all doctored them up, and generally everything I could think of to make sure I wasn't crazy.

Found this but it was closed: https://github.com/withfig/fig/issues/2419 

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.4.0 (21F79)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/sheriffderek/Sites
  - exe-path: /Users/sheriffderek/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: badfd591-0437-4ea5-b1d3-50fa38a0e231
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/sheriffderek/Library/pnpm:/Users/sheriffderek/.nvm/versions/node/v19.0.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sheriffderek/.fig/bin:/Users/sheriffderek/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 2954
    - FIG_SET_PARENT: badfd591-0437-4ea5-b1d3-50fa38a0e231
```

**Comment by mschrage** [comment]
Does autocomplete work for other commands?

What is the output of running `fig doctor` in Terminal.app?

**Comment by emewjin** [comment]
Same issue here.
I tried `fig restart`, but it didn't work.

`fig doctor` says everything looks good.
![image](https://github.com/withfig/fig/assets/89953090/70c3fab0-9e81-4368-8333-f64f815447f0)

env:
```
fig-details:
  - 2.16.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 12.2.1 (21D62)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/emewjin
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 494d7f62-c8da-47fe-98f7-085279f72ee0
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/emewjin/.nvm/versions/node/v16.18.1/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/emewjin/.fig/bin:/Users/emewjin/.local/bin:/Users/emewjin/.yarn/bin:/Users/emewjin/Library/Android/sdk/emulator:/Users/emewjin/Library/Android/sdk/platform-tools:/opt/homebrew/opt/fzf/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 32215
    - FIG_SET_PARENT: 494d7f62-c8da-47fe-98f7-085279f72ee0
```

**Comment by bennyk8y** [comment]
same issue here

**Comment by duyhunter1001** [comment]
me too same issue

**Comment by nateshmbhat** [comment]
same issue. i'm using Mac os 13.0.1 (22A400)

**Comment by sheriffderek** [comment]
> Does autocomplete work for other commands?

Not that I've been able to see. I tried all the normal commands I use.

> What is the output of running `fig doctor` in Terminal.app?
<img width="400" alt="CleanShot 2023-05-11 at 16 30 50@2x" src="https://github.com/withfig/fig/assets/2066617/b6491994-9dfe-4953-b1b4-d59d5cbe56bd">

**Comment by mschrage** [comment]
Can you run `fig debug devtools autocomplete` and share the output from your console?

**Comment by roderik** [comment]
I've got the same thing, other things like the dotfiles do work, but nothing that uses the popup

<img width="2231" alt="CleanShot 2023-05-23 at 07 49 31@2x" src="https://github.com/withfig/fig/assets/16780/9b98bc60-e389-4759-889a-8ad786278ebb">
