### ISSUE TITLE
bug: autosuggest ignores first character if prompt is empty

### ISSUE THREAD

**Issue by that70schris** [withfig/fig#2520]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS/zsh

### Expected behaviour

fig autosuggest should be triggered after first character typed

### Actual behaviour

it's ignoring the first character typed and considering the second character typed

### Steps to reproduce

1. include this in `~/.zshrc`
```
NEWLINE=$'\n'
PROMPT="$PROMPT$NEWLINE"
```
2. type a character at the prompt
3. type a second character at the prompt

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 13.3.1 (22E772610a)
environment:
  - shell: /opt/homebrew/Cellar/zsh/5.9/bin/zsh
  - terminal: iterm
  - cwd: /Users/chris
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: eed2e369-2c27-418f-b97a-6830eefda7d3
    - FIG_SET_PARENT_CHECK: 1
    - TERM: xterm-256color
    - FIG_SET_PARENT: eed2e369-2c27-418f-b97a-6830eefda7d3
    - FIG_TERM: 2.15.0
    - FIG_PID: 33577
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/chris/.fig/bin:/Users/chris/.local/bin
    - __CFBundleIdentifier: com.googlecode.iterm2
    - SHELL: /bin/zsh
```

**Comment by that70schris** [comment]
same thing occurs in `fish` with this code:```
functions -c fish_prompt dostuff
function fish_prompt
  dostuff
  echo
end
```

**Comment by mschrage** [comment]
@that70schris I can't seem to reproduce this.

Can you run `fig doctor`?

**Comment by that70schris** [comment]
ok, string, i restarted my terminal and now it's fine 🤷🏻‍♂️
