### ISSUE TITLE
`fig integrations install input-method` disables keyboard input on macos for Alacritty

### ISSUE THREAD

**Issue by timTonelli** [withfig/fig#2527]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.5.1 (21G83)

### Expected behaviour

On a fresh install of Alacritty, I ran `fig doctor`, and it told me to run `fig integrations install input-method`. Once I did, I was told to restart my terminal to complete the install. Expected behavior was that this would allow fig to be integrated with Alacritty.

### Actual behaviour

Actual behavior was that keyboard input no longer worked with Alacritty. Other terminals continued to work fine. I used another terminal to uninstall input-method and then restarted Alacritty, and the problem went away.

### Steps to reproduce

* install latest Alacritty from their site (0.12.0 at time of writing this)
* run `fig integrations install input-method`
* restart Alacritty

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /bin/zsh
  - terminal: alacritty
  - cwd: /Users/timtonelli
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 0339ee52-7fba-4119-874b-36e21175f27a
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/timtonelli/Library/Caches/fnm_multishells/46098_1683852417839/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/timtonelli/.cargo/bin:/Users/timtonelli/.fig/bin:/Users/timtonelli/.local/bin:/Users/timtonelli/Library/Android/sdk/platform-tools
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: org.alacritty
    - FIG_PID: 46076
    - FIG_SET_PARENT: 0339ee52-7fba-4119-874b-36e21175f27a
```

**Comment by mschrage** [comment]
This is due to an upstream bug in Alacritty. It’s been patched in the next version of Alacritty. In the meantime, try downgrading.
