### ISSUE TITLE
✘ PATH contains ~/.local/bin: Path does not contain ~/.local/bin

### ISSUE THREAD

**Issue by BJW333** [withfig/fig#2528]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.5 (21G531)

### Expected behaviour

to work lol

### Actual behaviour

this what happened

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 12.6.5 (21G531)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/blakeweiss
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: com.apple.Terminal
    - TERM: xterm-256color
    - SHELL: /bin/zsh
    - PATH: /Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by mschrage** [comment]
Can you run `fig doctor --verbose`?
