### ISSUE TITLE
Bug: Delete Account fails with Database Error P2003

### ISSUE THREAD

**Issue by ArthurMatta** [withfig/fig#2529]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS Ventura 13.3.1 (a)

### Expected behaviour

Clicking "Delete Account" and entering your username correctly will delete your account.

### Actual behaviour

Clicking "Delete Account" and entering the correct username will result in an error message: "Database Error: P2003. Sentry ID: 0cf17a2955d647deb26121dec2adec65".

![CleanShot 2023-05-12 at 23 39 17](https://github.com/withfig/fig/assets/26387768/c30feec6-3a53-41a3-b963-796756f1bac9)

### Steps to reproduce

1. Launch Fig.
2. Navigate to the Settings tab.
3. Select My Profile.
4. Press the Delete Account button.
5. Enter your username.
6. Confirm by pressing the Delete Account button.

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  - cores: 4
  - mem: 8.00 GB
os-info:
  - macOS 13.3.1 (22E772610a)
environment:
  - shell: /bin/zsh
  - terminal: <unknown>
  - cwd: /Users/arthurmatta
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - PATH: /Users/arthurmatta/anaconda3/condabin:/Users/arthurmatta/.nvm/versions/node/v19.8.1/bin:/Users/arthurmatta/.pyenv/shims:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/arthurmatta/.cargo/bin:/Users/arthurmatta/.fig/bin:/Users/arthurmatta/.local/bin:/Users/arthurmatta/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: dev.warp.Warp-Stable
    - FIG_SET_PARENT_CHECK: 1
    - FIG_PID: 89414
    - FIG_SET_PARENT:
```

**Comment by grant0417** [comment]
Hey @ArthurMatta, not too sure what is going on here, just tested it my self it worked. Can you try again and send the "Sentry ID" at the bottom.

**Comment by ArthurMatta** [comment]
Hi @grant0417, thank you for the reply.

That's weird, I've tried again and the issue persists. Sentry ID is now e5d406c91fd64db5a51e32741e0ef15e.

**Comment by grant0417** [comment]
Hey @ArthurMatta, the issue is now resolved, you should be able to delete you account now.

**Comment by grant0417** [comment]
Actually your account is deleted, so no action needed from you.

**Comment by ArthurMatta** [comment]
Excellent, thank you!
