### ISSUE TITLE
support vscode insider

### ISSUE THREAD

**Issue by Rhythmicc** [withfig/fig#2533]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
> Just support vscode insider, and I can use newest features.

**Comment by mschrage** [comment]
VSCode insiders should be supported.

**Comment by rhlsthrm** [comment]
Fig is not working in VS Code insiders for me. Can anyone help me get it set up?
