### ISSUE TITLE
fig does not work 

### ISSUE THREAD

**Issue by ortalYadayev** [withfig/fig#2534]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E261)

### Expected behaviour

Ran in the terminal fig and fig doctor.

### Actual behaviour

The message was sent to me ' Input Method: Not enabled for WebStorm

  Restart WebStorm [89415] to enable autocomplete in this terminal.

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
'

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.3.1 (22E261)
environment:
  - shell: /bin/zsh
  - terminal: intellij-webstorm
  - cwd: /Users/ortalyadayev/Desktop/Projects
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: ed9fd2d1-2121-4f8b-853c-d83e068bcfc8
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/ortalyadayev/.fig/bin:/Users/ortalyadayev/.local/bin:/Users/ortalyadayev/.fig/bin:/Users/ortalyadayev/.local/share/fig/plugins/git-flow
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.WebStorm
    - FIG_PID: 15182
    - FIG_SET_PARENT: ed9fd2d1-2121-4f8b-853c-d83e068bcfc8
```

**Comment by SawingJeracsus** [comment]
Try run `fig install --input-method`

**Comment by mschrage** [comment]
Did you you restart WebStorm as the error message suggested?
