### ISSUE TITLE
[ENG-1108] Set up shellcheck

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#254]
[https://www.shellcheck.net/](https://www.shellcheck.net/)

___

Automatically created from [Linear (#1108)](https://linear.app/fig/issue/ENG-1108/set-up-shellcheck)

*via LinearSync*

**Comment by mattschrage** [comment]
Comment from [Linear (#1108)](https://linear.app/fig/issue/ENG-1108/set-up-shellcheck)

Only works for bash scripts, so not as useful to us as I hoped

---
*via LinearSync*
