### ISSUE TITLE
.bashrc does not source pre integration .profile does not source pre integration

### ISSUE THREAD

**Issue by chein01** [withfig/fig#2542]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

I always got this error. I have a Macbook m1 and just bought new Mac mini and install Fig but still got this error.
Can u guys fix this error help me?

### Actual behaviour

![image](https://github.com/withfig/fig/assets/53501591/2a421e4b-72f6-4c40-a4b3-23fc05e9218f)

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/chienpham
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: f9937b31-6aa9-415c-b622-cf95d7da3cb5
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /opt/homebrew/sbin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/chienpham/.foundry/bin:/Users/chienpham/.fig/bin:/Users/chienpham/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 9968
    - FIG_SET_PARENT: f9937b31-6aa9-415c-b622-cf95d7da3cb5
```

**Comment by grant0417** [comment]
Hey @chein01, these are just warnings and can be ignored if Fig is working with zsh, reopen the issue if you are still having issues.
