### ISSUE TITLE
Autocomplete pops up in wrong place

### ISSUE THREAD

**Issue by melkerdbt** [withfig/fig#2544]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E772610a)

### Expected behaviour

![Screenshot 2023-05-16 at 16 39 24](https://github.com/withfig/fig/assets/132666292/27c27ee3-6f5e-4c50-85b6-2572c8bf83e6)

### Actual behaviour

![Screenshot 2023-05-16 at 16 39 40](https://github.com/withfig/fig/assets/132666292/9e667a8b-ac1a-40d0-bc16-93a9e108d8db)

### Steps to reproduce

open any jetbrains terminal and try to use fig. For instance intellij or webstorm

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.3.1 (22E772610a)
environment:
  - shell: /bin/zsh
  - terminal: intellij-webstorm
  - cwd: /Users/melkerforssell/Code/db-service/serve
  - exe-path: /Users/melkerforssell/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 06395063-7c5d-42b8-a0ed-87eb7741acd4
    - FIG_JETBRAINS_SHELL_INTEGRATION: 1
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /opt/homebrew/opt/node@16/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/melkerforssell/.fig/bin:/Users/melkerforssell/.local/bin:/Users/melkerforssell/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.WebStorm
    - FIG_PID: 15862
    - FIG_SET_PARENT: 06395063-7c5d-42b8-a0ed-87eb7741acd4
```

**Comment by grant0417** [comment]
Did you run `fig doctor` inside WebStorm? Did it have any warnings or errors?
