### ISSUE TITLE
bug: The-Unnamed theme looks broken

### ISSUE THREAD

**Issue by vuolter** [withfig/fig#2545]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS

### Expected behaviour

<img width="431" alt="Screenshot 2023-05-16 at 21 20 23" src="https://github.com/withfig/fig/assets/1221092/df37b80b-088f-48eb-9685-bf2fb8fcf030">

### Actual behaviour

Selected text is no longer readable:

<img width="396" alt="Screenshot 2023-05-16 at 21 14 11" src="https://github.com/withfig/fig/assets/1221092/f0b12ac7-a4a1-4f46-9798-302a10ac61fe">

### Steps to reproduce

Update fig_cli to v2.16.0 .

**Comment by mschrage** [comment]
Maybe an issue with the new theming system cc @grant0417

**Comment by katikap** [comment]
It happens to me too. I noticed that it happened after updating oh-my-zsh.

**Comment by nilshiroqaq** [comment]
Seems I've found a temporary solution
#565861
The theme's json files are locate in $HOME/Library/Application Support/fig/themes/themes
and edit the The-Unnamed theme file on
```
    "selection": {
      "textColor": "#F3EFF5",
      "backgroundColor": "#F3EFF550"
    },
```
it's ```"backgroundColor": "#F3EFF550"``` to ```"backgroundColor": "#565861"```
save it and change theme to any others and change it to The-Unnamed again, to fix this.

**Comment by grant0417** [comment]
This should be fixed now, just restart Fig!

A little more on what happened, the theme used opacity which our new theme code did not take into account, it should work now though. Thanks to @nilshiroqaq for figuring out what was going on!
