### ISSUE TITLE
not working on my mac machine 

### ISSUE THREAD

**Issue by bmanikantareddy** [withfig/fig#2548]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

fig dashboard is fully white and didn't display anything
launching ITerm taking taking to get the prompt
my macterminal default shell is bash, after installing fig , if fig is unable to launch in terminal in terminal its changing the shell to zsh

### Actual behaviour

fig should not change the shell
fig dashboard should display the things
fig should work and get the autopopulate functionality
auto populate

### Steps to reproduce

it's direct way. there is no separate steps to reproduce

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  - cores: 4
  - mem: 32.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/bash
  - terminal: iterm
  - cwd: /Users/bmanikantareddy
  - exe-path: /Users/bmanikantareddy/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_PID: 30985
    - TERM: xterm-256color
    - SHELL: /bin/bash
    - FIGTERM_SESSION_ID: 813309f9-2312-4373-b127-0d3584da2934
    - FIG_SET_PARENT_CHECK: 1
    - PATH: /Users/bmanikantareddy/anaconda3/bin:/Users/bmanikantareddy/anaconda3/condabin:/Users/bmanikantareddy/.rd/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/bmanikantareddy/.fig/bin:/Users/bmanikantareddy/.local/bin:/Users/bmanikantareddy/work/apache-maven-3.8.5/bin:/Applications/jdk-11.0.16.1.jdk/Contents/Home/bin:/Users/bmanikantareddy/Library/Python/3.8/bin:/Users/bmanikantareddy/.krew/bin:/Users/bmanikantareddy/google-cloud-sdk/bin
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_TERM: 2.16.0
```

**Comment by grant0417** [comment]
Hey @bmanikantareddy, did you run `fig doctor` in your terminal? Can you share the output here?
