### ISSUE TITLE
Fig on Jetbrains IDE (webstorm)

### ISSUE THREAD

**Issue by tutods** [withfig/fig#2549]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E772610a)

### Expected behaviour

Fig works normally

### Actual behaviour

The fig box dont' appear:

✘ Figterm: Figterm socket write timed out after 1s

✘ Doctor found errors. Please fix them and try again.

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz
  - cores: 6
  - mem: 32.00 GB
os-info:
  - macOS 13.3.1 (22E772610a)
environment:
  - shell: /usr/local/Cellar/fish/3.6.1/bin/fish
  - terminal: hyper
  - cwd: /Users/tutods/Developer/courses/rocketseat/nlw/nlw-12/packages/web
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_TERM: 2.16.0
    - PATH: /Users/tutods/.nvm/versions/node/v18.16.0/bin:/Users/tutods/fvm/default/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/tutods/Library/pnpm:/Users/tutods/.nvm/versions/node/v18.16.0/bin:/Users/tutods/.fig/bin:/Users/tutods/.local/bin:/Users/tutods/Developer/courses/rocketseat/nlw/nlw-12/node_modules/.bin
    - FIG_SET_PARENT: b9b917cd-9d44-4ec8-b8eb-9e4d3b54a3cd
    - FIGTERM_SESSION_ID: 848e3807-5f5b-4601-abea-85990371b731
    - SHELL: /usr/local/bin/fish
    - __CFBundleIdentifier: com.jetbrains.WebStorm
    - TERM: xterm-256color
    - FIG_JETBRAINS_SHELL_INTEGRATION: 1
    - FIG_PID: 78303
    - FIG_PARENT:
```

**Comment by grant0417** [comment]
Hey @tutods, did you launch WebStorm from hyper? Also did you run `fig issue` from within WebStorm? Just trying to understand you environment output to help debug here.

**Comment by tutods** [comment]
Yes, it’s launched from hyper (`webstorm .`) and the fig issue from WebStorm.

**Comment by grant0417** [comment]
Can you try launching webstorm from the app launcher and see if Fig works?
