### ISSUE TITLE
bug: Font Size setState loop

### ISSUE THREAD

**Issue by quentinlintz** [withfig/fig#2552]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS / Chrome

### Expected behaviour

When backspacing the Font Size form on [autocomplete settings](https://app.fig.io/settings/products/autocomplete/appearance), I should be able to clear the form without an error.

### Actual behaviour

An error is displayed:

> Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

### Steps to reproduce

See clip below:

https://github.com/withfig/fig/assets/98997219/0240fb8c-ef67-474e-86f3-ea4c6018ccb0

**Comment by grant0417** [comment]
Hey @quentinlintz, thanks for the report! This should be fixed now, you can restart fig and it should work.
