### ISSUE TITLE
dotFIle PATH manage support select Software

### ISSUE THREAD

**Issue by vaynevayne** [withfig/fig#2556]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Feature Details

When I want to add vscode's code to path, but I don't know how to get PATH, I want to provide the function of software choice. After I select the environment, I list the supported instructions. I can check code so that I can use code. To open the file.

<img width="786" alt="image" src="https://github.com/withfig/fig/assets/124666577/942b140f-7932-421f-a573-d1ba29255f46">

**Comment by grant0417** [comment]
The path should probably be like: `/Applications/Visual Studio Code.app/Contents/Resources/app/bin`

But this is out of scope of our support so I am going to close the issue
