### ISSUE TITLE
bug: dbt autocomplete throws an error instead of model name suggestion

### ISSUE THREAD

**Issue by alexnikitchuk** [withfig/fig#2561]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.4.0 (22F66)

### Expected behaviour

Model name suggestion shows up

### Actual behaviour

An error shows up:
```
compgen:14: bad option: +q
```

### Steps to reproduce

1. Install fig and dbt
2. Run the terminal and type `dbt run -s +q`
3. Hit Tab button

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: Macbook Pro
  - model-id: 16 inches, 2021
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.4.0 (22F66)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: IntelliJ Idea
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - __CFBundleIdentifier: com.mschrage.fig
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - DISPLAY: /private/tmp/com.apple.launchd.I8CZzkNv5F/org.xquartz:0
    - SHELL: /bin/zsh
```

**Comment by grant0417** [comment]
Hey @alexnikitchuk, can you share a screenshot of the issue?

This might not be Fig causing it and could be a native ZSH issue.

**Comment by alexnikitchuk** [comment]
here it is 
<img width="505" alt="image" src="https://github.com/withfig/fig/assets/8694829/0dca117a-27c1-460e-aaa3-3bf24d8b738e">

**Comment by mschrage** [comment]
This looks like it is unrelated to Fig (`compgen` is a completion utility for zsh)
