### ISSUE TITLE
Command not found for custom CLI. 

### ISSUE THREAD

**Issue by cooperfdiv** [withfig/fig#2566]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.1 (21G217)

### Expected behaviour

i have a custom CLI named lcl-cmd with a script named display-name which has one input called name and then a script to display hello then what was entered in the name input field. I have tried this with several variation. I can create just a custom script and it work fine. just not CLI. 

### Actual behaviour

I was expecting the script to run, ask me for a name and then display that message in the terminal window. 

### Steps to reproduce

I have deconstructed and recreated several variations of this scenario to no avail. I've reinstalled fig a couple of time, and nothing. I am running this in iTerm2 and the integration in fid is configured for that. As i mentioned before, scripts work fine, just not CLI. 

### Environment

```yaml
fig-details:
<img width="1572" alt="Screen Shot 2023-05-24 at 11 34 42 AM" src="https://github.com/withfig/fig/assets/12153497/34638779-96b8-4fbe-b2d6-b07e107e16ca">

<img width="807" alt="Screen Shot 2023-05-24 at 11 33 51 AM" src="https://github.com/withfig/fig/assets/12153497/eac7bc83-b1c1-4b66-91ed-301eaea88fd5">

  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/xhic013
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 3bb610ee-9a47-4fff-81af-ce4bd0be6f51
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/sbin:/usr/local/share/dotnet:/Users/xhic013/.cargo/bin:/Users/xhic013/.fig/bin:/Users/xhic013/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 1752
    - FIG_SET_PARENT: 3bb610ee-9a47-4fff-81af-ce4bd0be6f51
```

**Comment by cooperfdiv** [comment]
Also, i am using zsh inside iTerm2 with OMZ.

**Comment by grant0417** [comment]
Can you try running `fig scripts refresh` and see if it works?

**Comment by cooperfdiv** [comment]
BINGO!!! Thank you so much!! Working after running fig scripts refresh. Very much appreciated!
