### ISSUE TITLE
It doesnt word, have no prompt

### ISSUE THREAD

**Issue by Adophlidu** [withfig/fig#2567]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

It should give me some prompts when i typing in the command

### Actual behaviour

It doesnt word, have no prompt. 
And told me there is no problem when i run fig doctor

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/adolph/mine/D
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 599243c5-86ce-44d0-a9fb-2bf9d3d2125d
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/adolph/.nvm/versions/node/v16.19.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/adolph/.fig/bin:/Users/adolph/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 61721
    - FIG_SET_PARENT: 599243c5-86ce-44d0-a9fb-2bf9d3d2125d
```

**Comment by mschrage** [comment]
Can you run `fig debug diagnostics --watch` and share a screen recording while typing into a separate terminal session?
