### ISSUE TITLE
Constant ssh breakage

### ISSUE THREAD

**Issue by woodrowpearson** [withfig/fig#2569]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E772610a)

### Expected behaviour

The expected behavior is that when I use ssh it actually works and I am not troubleshooting my bastion server when it turns out my dotfiles manager is the culprit..

### Actual behaviour

This is a deal breaker if it can't get fixed. Multiple times a day the ssh integration craps out. Please advise..

### Steps to reproduce

No idea.

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 13.3.1 (22E772610a)
environment:
  - shell: /opt/homebrew/Cellar/zsh/5.9/bin/zsh
  - terminal: terminal
  - cwd: /Users/woodrowpearson/code/provisioning/packer
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 77e688de-685c-4497-8b94-185275517a07
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/woodrowpearson/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:/Users/woodrowpearson/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/woodrowpearson/.fig/bin:/Users/woodrowpearson/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 59195
    - FIG_SET_PARENT: 77e688de-685c-4497-8b94-185275517a07
```

**Comment by grant0417** [comment]
It might be out ssh integrations, can you try running `fig integrations uninstall ssh` and see if it resolves your issues?
