### ISSUE TITLE
DOCTOR not working issue

### ISSUE THREAD

**Issue by helmet2009** [withfig/fig#2573]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Windows 11

### Expected behaviour

asd

### Actual behaviour

asd

### Steps to reproduce

asd

### Environment

```yaml
fig-details:
  - cli-version: 1.5.0
  - desktop-version: 2.5.3
  - figterm-version: 5.2.0
hardware-info:
  - chip-id: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
  - cores: 4
  - mem: 16226.301 GB
os-info:
  - Windows 10 Pro for Workstations (or newer) - build 22000
environment:
  - shell: C:\Program Files\WindowsApps\Microsoft.PowerShell_7.2.6.0_x64__8wekyb3d8bbwe\pwsh.exe
  - terminal: <unknown>
  - cwd: C:\Users\CAPTAIN AKUMA AK 47
  - exe-path: C:\Users\CAPTAIN AKUMA AK 47\AppData\Local\Fig\latest\fig.exe
  - install-method: unknown
  - env-vars:
```

**Comment by mschrage** [comment]
Fig is not currently supported on Windows.
