### ISSUE TITLE
PATH contains ~/.local/bin: Path does not contain ~/.local/bin

### ISSUE THREAD

**Issue by send2manoo** [withfig/fig#2574]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.4.0 (22F66)

### Expected behaviour

 PATH contains ~/.local/bin: Path does not contain ~/.local/bin

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

### Actual behaviour

 PATH contains ~/.local/bin: Path does not contain ~/.local/bin

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

### Steps to reproduce

 PATH contains ~/.local/bin: Path does not contain ~/.local/bin

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.4.0 (22F66)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/manohar
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: co.zeit.hyper
    - PATH: /Users/manohar/.rbenv/shims:/Users/manohar/.rbenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/manohar/.fzf/bin
    - DISPLAY: /private/tmp/com.apple.launchd.NE4MWcKS6b/org.xquartz:0
    - SHELL: /bin/zsh
    - TERM: xterm-256color
```

**Comment by mschrage** [comment]
Can you run `fig doctor -- verbose`
