### ISSUE TITLE
bug: Unable to Change Oh My Zsh Theme Reliably

### ISSUE THREAD

**Issue by OceanTrader1** [withfig/fig#2578]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS

### Expected behaviour

I'm experiencing a similar issue to #1489 but the workaround of enabling/disabling the plugin does not appear to work reliably. Sometimes, the theme change will be applied but, most often, it is not. Oh My Zsh is the only plugin that I currently have installed. All other plugins were uninstalled to test this issue.

### Actual behaviour

<details><summary>Install Plugin</summary>
<br></br>
<p>
After installing, I expect the default robbyrussell theme to load but after running <code>fig source</code> the prompt stays the same.
<img src="https://github.com/withfig/fig/assets/69881238/69121343-6822-47e9-b083-305d7933ddc8" alt="Install Oh My Zsh Plugin">
</p>
</details> 

<details>
<summary>Changing themes in GUI does not properly reflect in terminal</summary>
<br></br>

After changing the theme, I expect for the new theme to load in the terminal after running `fig source` but is not always the case.

![fig_change_themes_not_working](https://github.com/withfig/fig/assets/69881238/0d5a0eed-4308-4a18-b3eb-7c7673372ca8)

</details>

<details>
<summary>Disabling and re-enabling plugin does not guarantee a theme change</summary>
<br></br>
After disabling and then enabling the plugin (e.g., the proposed workaround), the proposed fix does not guarantee a theme change.

![fig_change_theme_after_reenable](https://github.com/withfig/fig/assets/69881238/cec846f7-211b-44fa-ae31-b579cdd95716)

</details>

### Environment

<details><summary><code>fig diagnostic</code></summary>
<p>

```shell
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Max
  - cores: 12
  - mem: 32.00 GB
os-info:
  - macOS 13.4.0 (22F66)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/ocean_trader/.local/share/fig/plugins
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 2b02406a-283c-4274-be21-adcbca080eb6
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /opt/homebrew/Caskroom/miniconda/base/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/ocean_trader/.fig/bin:/Users/ocean_trader/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 1102
    - FIG_SET_PARENT: 2b02406a-283c-4274-be21-adcbca080eb6
```

</p>
</details>

<details>

<summary><code>~/.zshrc</code></summary>

```shell
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# PROMPT='%~ %% '

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
```

</details>

**Comment by mschrage** [comment]
What happens if your run `fig source`? Does this consistently trigger and update?

**Comment by OceanTrader1** [comment]
> What happens if your run `fig source`? Does this consistently trigger and update?

I believe the videos that I included videos under the expandable tabs section 'Actual Behavior' may provide the best example of what occurs after running `fig source`.  Consistently? No. Sometimes the theme will change; other times it will not. There doesn't appear to be a pattern of predictability to suggest what sequence of steps will lead to a theme change.
