### ISSUE TITLE
PATH contains ~/.local/bin: Path does not contain ~/.local/bin

### ISSUE THREAD

**Issue by Pathik25** [withfig/fig#2583]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.5 (21G531)

### Expected behaviour

I have this type of issue in fig ? 
plz any one can steps to solve this .

PATH contains ~/.local/bin: Path does not contain ~/.local/bin

### Actual behaviour

I have this type of issue in fig ? 
plz any one can steps to solve this .

PATH contains ~/.local/bin: Path does not contain ~/.local/bin

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  - cores: 2
  - mem: 8.00 GB
os-info:
  - macOS 12.6.5 (21G531)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/apple
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: com.apple.Terminal
    - TERM: xterm-256color
    - SHELL: /bin/zsh
    - PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/mongodb-community@4.4/bin:/usr/local/mongodb/bin:/Library/Apple/usr/bin
```

**Comment by mschrage** [comment]
You can manually add `~/.local/bin` to your PATH.
