### ISSUE TITLE
Fig Integration: Figterm is not running in this terminal, please try restarting your terminal

### ISSUE THREAD

**Issue by Mustafaa71** [withfig/fig#2588]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E261)

### Expected behaviour

$ fig doctor

✔ Everything looks good!

Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!

### Actual behaviour

➜  ~ fig doctor

✘ Fig Integration: Figterm is not running in this terminal, please try restarting your terminal

  FIG_TERM=

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.3.1 (22E261)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/mustafa
  - exe-path: /Users/mustafa/.fig/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /bin/zsh
    - __CFBundleIdentifier: com.googlecode.iterm2
    - PATH: /Users/mustafa/.rvm/gems/ruby-3.0.0/bin:/Users/mustafa/.rvm/gems/ruby-3.0.0@global/bin:/Users/mustafa/.rvm/rubies/ruby-3.0.0/bin:/opt/homebrew/bin:/Users/mustafa/.fig/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/.local/bin:/.fig/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/mustafa/.rvm/bin
    - TERM: xterm-256color
```

**Comment by mschrage** [comment]
Have you tried restarting your terminal?
