### ISSUE TITLE
bug: Cannot delete certain scripts from script store

### ISSUE THREAD

**Issue by ctafts** [withfig/fig#2590]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Mac OS 13.4 (22F66)

### Expected behaviour

The script should delete when I select delete.

### Actual behaviour

When I select delete to remove the added script an error is displayed stating `Cannot delete protected script`.
The script I am having issues with is called `@docker/remove`, I tried duplicating the script and the duplicate can also not be deleted.

This issue was previously [reported](https://github.com/withfig/fig/issues/2425) but closed stating the issue has been resolved, but it still persists. 

### Steps to reproduce

![image](https://github.com/withfig/fig/assets/782892/d6e511e2-2cd9-4553-a397-9f0c6c4e2295)
![image](https://github.com/withfig/fig/assets/782892/8572f229-1ee1-4179-8c96-1a7e8e26c4d2)
![image](https://github.com/withfig/fig/assets/782892/e01f30a6-dc0b-492e-91a9-cdaedf5c9869)

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.4.0 (22F66)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/tafts
  - exe-path: /Users/tafts/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 4ef5ae86-3977-4717-a923-9d052ce05ad7
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/tafts/.local/share/fig/plugins/git-open:/Users/tafts/.pyenv/shims:/Users/tafts/.nvm/versions/node/v18.16.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/tafts/.fig/bin:/Users/tafts/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 24865
    - FIG_SET_PARENT: 4ef5ae86-3977-4717-a923-9d052ce05ad7
```

**Comment by mschrage** [comment]
@grant0417 perhaps we can remove retroactively remove protected status for all scripts that match the name of a public script?

**Comment by grant0417** [comment]
This should be fixed, you should be able to delete them now.

**Comment by ctafts** [comment]
@grant0417 @mschrage I was able to delete them, thank you so much!
