### ISSUE TITLE
No Autocomplete for kubectl command

### ISSUE THREAD

**Issue by erikciortan-lvs** [withfig/fig#2593]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.4.0 (22F66)

### Expected behaviour

when I write kubectl i expect the fig to do Autocomplete like in other commands

### Actual behaviour

nothing happens after writing Kubectl command (with other commands it's working without a problem)

### Steps to reproduce

write Kubectl - nothing happens - no autocomplete

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.4.0 (22F66)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 9ad156bc-10a7-4bc0-a437-cef64dac5b5b
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/erik.ciortan/.fig/bin:/Users/erik.ciortan/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 84604
    - FIG_SET_PARENT: 9ad156bc-10a7-4bc0-a437-cef64dac5b5b
```

**Comment by mschrage** [comment]
`kubectl` is supported by Fig autocomplete.

<img width="422" alt="Screenshot 2023-07-17 at 2 59 31 PM" src="https://github.com/withfig/fig/assets/3155109/505ccc3c-2be3-49b2-b6bd-1281970a4049">


It seems like you may have `kubectl` aliased to some other command. Can you share the output of`which kubectl`?
