### ISSUE TITLE
Cannot click anything in desktop application

### ISSUE THREAD

**Issue by zakpucci** [withfig/fig#2594]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.4.0 (22F66)

### Expected behaviour

Click any element or call to action in Fig desktop and corresponding action should occur.

### Actual behaviour

Click any element or call to action in Fig Desktop and the window flashes as if losing and then regaining focus, clicking on any item, ie: a script, flashes and loses focus. The only way to access the script would be to double click quickly, in which case, it doesn't solve the problem but at least allows progression. Cannot edit anything, cannot keep window focus. Waiting hours seems to solve the issue.

### Steps to reproduce

Open Fig desktop, click anything, including the window.

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  - cores: 4
  - mem: 64.00 GB
os-info:
  - macOS 13.4.0 (22F66)
environment:
  - shell: /bin/bash
  - terminal: terminal
  - cwd: /Users/trueconnect/Library/Mobile Documents/com~apple~CloudDocs/Management/Application/core/frontend/client
  - exe-path: /Users/trueconnect/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_PID: 2035
    - TERM: xterm-256color
    - SHELL: /bin/bash
    - FIGTERM_SESSION_ID: 6c749e81-0d44-4a86-8af0-17f5db242b58
    - FIG_SET_PARENT_CHECK: 1
    - PATH: /usr/local/git/bin:/usr/local/git/bin:/usr/local/git/bin:/Users/trueconnect/.nvm/versions/node/v16.17.0/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/trueconnect/.fig/bin:/Users/trueconnect/.local/bin
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_TERM: 2.16.0
```

**Comment by mschrage** [comment]
This is very strange. Is this issue reproducible for you?
