### ISSUE TITLE
Build%20Colt

### ISSUE THREAD

**Issue by Joker-commits** [withfig/fig#2596]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 5.15.0-75-generic - "Linux Mint 21.1"

### Expected behaviour

I could not find saved scripts under my CLO/Build Colt. It is showing 3 commands but they are not visible inside of my Build Colt folder.

### Actual behaviour

![Screenshot from 2023-06-17 04-40-37](https://github.com/withfig/fig/assets/55637028/65f4ebe9-f19c-40a9-9a21-3424bd1a3fc0)
![Screenshot from 2023-06-17 04-39-57](https://github.com/withfig/fig/assets/55637028/d955eba6-1a58-4671-9c70-8f76b74dfd93)

### Steps to reproduce

no

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 31.19 GB
os-info:
  - kernel: 5.15.0-75-generic
  - distro: "Linux Mint 21.1"
  - distro-version: "21.1 (Vera)"
environment:
  - shell: /usr/bin/bash
  - terminal: <unknown>
  - cwd: /home/mani/colt
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /bin/bash
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: 844905de-8d78-4ac3-ae78-0042150ee4fd
    - XDG_SESSION_DESKTOP: cinnamon
    - XDG_SESSION_TYPE: x11
    - XDG_CURRENT_DESKTOP: X-Cinnamon
    - FIG_TERM: 2.15.0
    - TERM: xterm-256color
    - FIG_PID: 6416
    - DISPLAY: :0
    - PATH: /home/mani/.local/bin:/home/mani/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/mani/.fig/bin
```

**Comment by mschrage** [comment]
Think of CLI tools as folders for scripts. You need to move scripts you want to be accessible via the CLI tool into it.

Also, I think that using "Build Colt" as the name of your CLI tool may result in undefined behavior. I'd rename it to something without a space.
