### ISSUE TITLE
Auto Suggestions not loading after system restart

### ISSUE THREAD

**Issue by azherf** [withfig/fig#2597]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.4.0 (22F66)

### Expected behaviour

fig auto suggestions should come up seamlessly.

### Actual behaviour

fig auto suggestions do not show up on the terminal after restarting the system. It requires us to quit fig and restart it.

### Steps to reproduce

1. Restart MacBook Pro
2. Launch the terminal
3. Start typing `cd...` and other commands. 

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.4.0 (22F66)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/azher
  - exe-path: /Users/azher/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 9c2168b7-aad8-45a7-88a0-0788157c0e05
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/azher/google-cloud-sdk/bin:/Users/azher/.nvm/versions/node/v16.17.0/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/azher/.fig/bin:/Users/azher/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 3648
    - FIG_SET_PARENT: 9c2168b7-aad8-45a7-88a0-0788157c0e05
```

**Comment by mschrage** [comment]
@azherf is this consistently reproducible for you? Next time this happens can you run `fig doctor`?
