### ISSUE TITLE
Autocomplete is not popping up

### ISSUE THREAD

**Issue by sean12-2007** [withfig/fig#2598]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

I expected the autocomplete to work after running fig doctor multiple times

### Actual behaviour

It still doesn't work

### Steps to reproduce

I dunno. Sometimes it works and sometimes it doesn't

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/seanho
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: c2b00499-0fe4-42b2-b935-828a1a65e2bb
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/seanho/.rbenv/shims:/Users/seanho/.rbenv/shims:/Users/seanho/opt/anaconda3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/seanho/.fig/bin:/Users/seanho/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 76643
    - FIG_SET_PARENT: c2b00499-0fe4-42b2-b935-828a1a65e2bb
```

**Comment by sean12-2007** [comment]
Ok
I restarted it yet again and now it works.
For now

**Comment by Sunbridger** [comment]
I have a similar problem, which is not solved.

**Comment by Matthewctk** [comment]
Same issue. It works again after reinstalling fig

**Comment by sean12-2007** [comment]
> 

Maybe restart?

**Comment by sbuys** [comment]
Same issue. `fig restart` fixes the issue for a minute or so, but then fig stops working again.

**Comment by chunghwa-1990** [comment]
I meet the same problem

**Comment by sean12-2007** [comment]
Guys I think y'all could just restart it and it'll probably be good. I think most people here who've solved it like I did either restarted it or reinstalled it. Just try those two methods and it'll most probably work. If not, maybe try consulting Fig documentation.

**Comment by grant0417** [comment]
This should be fixed, relaunch Fig and it would appear.
