### ISSUE TITLE
Integrate Autocomplete with Kitty Terminal

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#26]
The title says it all.

Please subscribe to this issue to get an update when the autocomplete integration with Kitty Terminal is ready :smile:

**Comment by mattschrage** [comment]
Some helpful links to Kitten API:
- [Remote Control](https://sw.kovidgoyal.net/kitty/remote-control.html#documentation-for-the-remote-control-protocol)

**Comment by mschrage** [comment]
Alright I think I've figured out a way to get the information we need without polling!
1. Update the user's kitty config to set `allow_remote_control true`
2. Add `--watcher ~/.fig/tools/kitty-integration.py` to [`~/.config/kitty/macos-launch-services-cmdline`](https://sw.kovidgoyal.net/kitty/faq/#how-do-i-specify-command-line-options-for-kitty-on-macos)
3. Write a [watcher](https://sw.kovidgoyal.net/kitty/launch/#watching-launched-windows) in `kitty-integration.py` that notifies the macOS app when the focus changes.
```
def on_resize(boss, window, data):
    # Here data will contain old_geometry and new_geometry

def on_focus_change(boss, window, data):
    # Here data kill contain focused

def on_close(boss, window, data):
    # called when window is closed, typically when the program running in
    # it exits.
```

**Comment by mschrage** [comment]
Ah so close! This automatically sets up the watcher for the first window, but doesn't for subsequent tabs and sessions. We could potentially define a custom `startup_session` for this? (I think this is more likely to collide with user's existing customizations.)

**Comment by mschrage** [comment]
Support for kitty is landing in v1.0.49!

**Comment by magus** [comment]
Any update on when this is going to land?

**Comment by risc12** [comment]
The other day a mailing got sent out that there is beta Kitty-support. How can one enable this? I've already set Fig to download the Beta-versions.

This is what was in the email:
<img width="433" alt="Screenshot 2021-11-22 at 11 30 29" src="https://user-images.githubusercontent.com/4367772/142845763-0bc0c74a-7625-4732-9af8-143bdb8df408.png">

**Comment by mschrage** [comment]
We are waiting for the next release of Kitty since our integration require a kitty.conf parameter ([`watcher`](https://github.com/kovidgoyal/kitty/commit/166ea9deb9638bc34bcea2c95b95f440d016f92d) that is not supported currently. 

I misjudged how long this build would be take to be released. Everything else is ready to go for the Fig to work with Kitty.

**Comment by kovidgoyal** [comment]
Yes, this release of kitty is delayed because of waiting for
https://github.com/kovidgoyal/kitty/issues/3948  to mature.

But, note that nightly builds of kitty are available if needed.

**Comment by mschrage** [comment]
Thanks again for helping adding the `watcher` parameter to Kitty @kovidgoyal. It makes our integration much more robust.

**Comment by kovidgoyal** [comment]
You are welcome!

**Comment by chrismilleruk** [comment]
FYI, the Kitty dependency mentioned above was closed and released earlier today:

https://github.com/kovidgoyal/kitty/issues/3948#issuecomment-1004497672

**Comment by mschrage** [comment]
Thanks for letting me know @chrismilleruk

**Comment by jim-at-jibba** [comment]
Hey,

Now that this is done show Fig work in Kitty? I still get told its not suported

**Comment by mschrage** [comment]
We still need to push a new build!

**Comment by jim-at-jibba** [comment]
Ace, sorry for jumping the gun. Just wanted to check I had not missed anything.

Thanks

**Comment by Liquidmantis** [comment]
Looks like I found fig just at the right time!

Thanks for the work on this, @kovidgoyal @mschrage

**Comment by sandangel** [comment]
hi, I updated to beta version, and saw an option for kitty integration. but it's saying that could not install the input method. could you let us know what should we do?

**Comment by mschrage** [comment]
Run `fig debug ime status` and share the output here?

**Comment by tomsvogel** [comment]
i also tried the kitty nightly with the beta of fig and no success,
```
$ fig debug ime status
input method is not running.
```

**Comment by mschrage** [comment]
@tomsvogel can you try running the following commands one at a time and share the output here?

```
fig debug ime register
fig debug ime enable
fig debug ime select
```

**Comment by tomsvogel** [comment]
``` 
$ fig debug ime register
Registered input method!

$ fig debug ime enable
Enabled input method!

$ fig debug ime select
An error occured when selecting input method: The operation couldn’t be completed. (OSStatus error -50.)

$ fig debug ime status
input method is not running.


```

**Comment by mschrage** [comment]
Could you try restarting the macOS app and then running `fig debug ime select` again? @tomsvogel

**Comment by tomsvogel** [comment]
```
$ fig debug ime select              
Selected input method!
```

**Comment by sandangel** [comment]
```sh
~/.dotfiles on  master [✘!+] took 14s  76%
λ fig debug ime select
Input method is already selected!

~/.dotfiles on  master [✘!+]  76%
λ fig debug ime status
Input source is not enabled
```

**Comment by tomsvogel** [comment]
i reinstalled fig, after that it was possible to install the plugin for kitty, it works now 🎉

**Comment by mschrage** [comment]
Seems like there is still some room to improve the install process - the TextInputServices APIs are super finicky.

**Comment by kingluddite** [comment]
I followed all the instructions above but fig still says kitty is not supported. I upgraded kitty with brew to latest version. I reinstalled fig. No luck. Fig works in iTerm but wish I could get it working in Kitty (FYI - fig also not working in Alacritty)

**Comment by tomsvogel** [comment]
@kingluddite you tried kitty knightly and fig beta?

**Comment by mschrage** [comment]
We are going to do a sprint on this next week. I believe that I've figured out a reliable way install (and enable) the input method.

**Comment by matsdahlin** [comment]
> We are going to do a sprint on this next week. I believe that I've figured out a reliable way install (and enable) the input method.

That sounds promising! Thanks for all your hard work ❤️

**Comment by kingluddite** [comment]
> @kingluddite you tried kitty knightly and fig beta?

Not yet. @tomsvogel Is there a link to the fig beta install? Can't seem to locate it. 

I found that the kitty nighly can be installed with:

```
$ curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin \
    installer=nightly
```
[source](https://sw.kovidgoyal.net/kitty/binary/)

**Comment by mschrage** [comment]
Instructions for those who are brave enough to attempt it:

1. Run `fig settings integrations.experimental true` and then restart the Fig app
2. Click the Fig menubar icon > Integrations > Kitty > "Attempt to Install"
3. Go to a terminal and run `fig debug ime enable`. A System Preferences window will appear and prompt you to install a third party Input Method.
4. Run `fig debug ime select`
5. Restart Kitty and autocomplete should appear🤞

**Comment by matsdahlin** [comment]
@mschrage the instructions worked fine for me! Seems to be working as expected so far 👌🏻
Thank you!

**Comment by kingluddite** [comment]
@mschrage You rock! Works like a charm!!!

**Comment by dbowling** [comment]
I got a "Learn More" button on a message when running the debug command, which gave me a 404 on the fig site.

Other than that, following the instructions was easy and everything is working as expected. I'm really happy to be able to use this with Kitty!

**Comment by liby** [comment]
@mschrage 
> A System Preferences window will appear and prompt you to install a third party Input Method.

I have some questions about this. After downloading the third-party input method, don't you need to apply it? I don't see it in the list.
<img width="780" alt="image" src="https://user-images.githubusercontent.com/38807139/160250761-105d1aa9-437c-45a6-8369-af2d5960ef0e.png">

**Comment by pistazie** [comment]
Worked well for a few days and then stopped. tried repeating with no success :(

**Comment by mschrage** [comment]
@pistazie run `fig doctor --verbose`

**Comment by pistazie** [comment]
thanks @mschrage in my case the issue was that `Secure keyboard input disabled` was not disabled. 
I fixed it using your documentation and `fig+kitty` are awesome again.

**Comment by smileart** [comment]
Here's the output of my `fig doctor --verbose` and still, it does not work in kitty:

````
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ .bashrc contains valid fig hooks
✔ .profile contains valid fig hooks
✔ .zshrc contains valid fig hooks
✔ .zprofile contains valid fig hooks

Let's make sure Fig is running...
✔ Fig bin exists
✔ PATH contains ~/.local/bin and ~/.fig/bin
✔ Fig Integration
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Figterm socket
✔ Insertion lock does not exist
✔ PATH and PseudoTerminal PATH match

Let's check if your system is compatible...
✔ OS is supported

Let's check fig diagnostic...
✔ Installation script
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled
✔ Secure keyboard input disabled

Let's check your terminal integrations...
✔ VSCode integration is enabled


Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!
````

**Comment by mschrage** [comment]
@smileart have you followed the steps outlined here? https://github.com/withfig/fig/issues/26#issuecomment-1022537900

**Comment by smileart** [comment]
@mschrage as I understood, it's not supposed to be experimental any more. Although I did not try enabling/installing Kitty support as per the instruction you're referring to, it started working out of nowhere. Before I surely tried reloading terminal, shell, tmux, laptop, triple checked all the .zshrc and such, it did not work, but yesterday it just suggested me some autocomplete. So, it'll remain a mystery why it did not start right away.  🤷

**Comment by mschrage** [comment]
For those who find this in the future, the command to enable Fig autocomplete in Alacritty is `fig install --input-method`

**Comment by ST33LDI9ITAL** [comment]
Do you collect and send ANY data from third party input?
