### ISSUE TITLE
auto complete doesn't appear in the script-src directive of the Content Security Policy

### ISSUE THREAD

**Issue by amrography** [withfig/fig#2604]
The app doesn't work at all, with any command. This is the error I am getting:

> Refused to load https://unpkg.com/@withfig/autocomplete@^2.0.0/build/index.js?date=1687437306088 because it does not appear in the script-src directive of the Content Security Policy.

![fig](https://github.com/withfig/fig/assets/9614340/d255b421-2378-45b3-bcf3-1b2308b61521)

**Comment by batout** [comment]
I have the same issue here 

`fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.4.1 (22F82)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/amrzaghloul
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 0644efde-632e-4e6a-9363-30fb6c8e9b30
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/amrzaghloul/.nvm/versions/node/v18.13.0/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/.local/bin:/.fig/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/amrzaghloul/.fig/bin:/Users/amrzaghloul/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 21342
    - FIG_SET_PARENT: 0644efde-632e-4e6a-9363-30fb6c8e9b30`

**Comment by AhmedElywa** [comment]
i have the same issue 

```
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 13.4.1 (22F770820d)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/ahmedelywa
  - exe-path: /Users/ahmedelywa/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: d97e277e-14de-4ba0-b6dc-473f11cce82c
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/ahmedelywa/.nvm/versions/node/v18.15.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/ahmedelywa/Library/Android/sdk/platform-tools:/Users/ahmedelywa/.cargo/bin:/Users/ahmedelywa/.fig/bin:/Users/ahmedelywa/.local/bin:/Users/ahmedelywa/.yarn/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: co.zeit.hyper
    - FIG_PID: 88522
    - FIG_SET_PARENT: d97e277e-14de-4ba0-b6dc-473f11cce82c
```

**Comment by AhmedElywa** [comment]
It's working fine in the dev mode if I run the autocomplete into my local with yarn dev

**Comment by grant0417** [comment]
The script-src should now include unpkg.com, so that should be resolved.

**Comment by AhmedElywa** [comment]
fixed for me thanks

**Comment by HossamHoussien-adeva** [comment]
@grant0417 I can still reproduce the issue.

<img width="1000" alt="image" src="https://github.com/withfig/fig/assets/95684011/025f6c47-9d1e-4b9b-a36a-63cbb5132de4">

<img width="348" alt="image" src="https://github.com/withfig/fig/assets/95684011/d99bace1-082f-4c92-b357-399c49730d60">

**Comment by grant0417** [comment]
@HossamHoussien-adeva have you tried restarting Fig?

**Comment by HossamHoussien-adeva** [comment]
@grant0417 Yes, I did. Restart didn't do it for me. I had to reset the scripts cache, it's working now. Thanks!

**Comment by amrography** [comment]
There's no app issue here. It's working with VPN.
