### ISSUE TITLE
bug: functions require two calls

### ISSUE THREAD

**Issue by tlambert03** [withfig/fig#2609]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macos 12.6.6

### Expected behaviour

I have defined some functions in my fig dotfiles.  I expect to be able to enter their name in my terminal, but it always requires me to enter the name twice.  The first time it does nothing, the second (and all subsequent) time it works:

### Actual behaviour

functions require two invokations

### Steps to reproduce

1. add a function
<img width="543" alt="Screen Shot 2023-06-25 at 10 21 08 AM" src="https://github.com/withfig/fig/assets/1609449/c299e75d-94bb-4f2a-80f6-0417fac119b4">

2. open terminal and `fig source` just to be sure.  Then call the function.  It takes two tries
<img width="205" alt="Screen Shot 2023-06-25 at 10 22 52 AM" src="https://github.com/withfig/fig/assets/1609449/39243087-3acf-43ab-abd3-909a7d8e7c13">

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  - cores: 4
  - mem: 64.00 GB
os-info:
  - macOS 12.6.6 (21G646)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /home
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 8c0b2bf9-c201-4a92-8249-c4891732d264
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:~/.fig/bin:
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 30559
    - FIG_SET_PARENT: 8c0b2bf9-c201-4a92-8249-c4891732d264
```

**Comment by grant0417** [comment]
It seems like you defined the function incorrectly.

The left cell should just have the name `sayhi` and the right cell should have the function content `echo hi`
