### ISSUE TITLE
Fig does not start on m2pro chip

### ISSUE THREAD

**Issue by Miguitian** [withfig/fig#2616]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

fig works fine

### Actual behaviour

When using iterm2, there is no problem in starting fig and running the fig doctor command, but when entering the shell, the command cannot be loaded at three points
![image](https://github.com/withfig/fig/assets/81501401/1de1e819-5cdf-4da0-a785-5db4eb8c8e32)

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/gtm
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: de951937-c7f2-4e50-94b6-3885c6b33c92
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/gtm/.fig/bin:/Users/gtm/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 88609
    - FIG_SET_PARENT: de951937-c7f2-4e50-94b6-3885c6b33c92
```

**Comment by builpro** [comment]
It's working at mac terminal app. I can use fig with no probs on my mac mini m2 pro.
<img width="440" alt="image" src="https://github.com/withfig/fig/assets/63128886/bb13bd59-919a-48bf-841e-07b00e5b1dab">
