### ISSUE TITLE
Doesn't work in Warp

### ISSUE THREAD

**Issue by girisenji** [withfig/fig#2617]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.4.1 (22F2083)

### Expected behaviour

Don't tell me use different terminal

### Actual behaviour

Tells me to use different terminal

### Steps to reproduce

Use warp

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.4.1 (22F2083)
environment:
  - shell: /bin/bash
  - terminal: <unknown>
  - cwd: /Users/girisenji/Developer/girisenji/spring-crud-rest-generator
  - exe-path: /Users/girisenji/.fig/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_PID: 8573
    - SHELL: /bin/bash
    - TERM: xterm-256color
    - FIG_SET_PARENT_CHECK: 1
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/girisenji/Developer/tools/pidcat:/usr/local/bin:/Users/girisenji/android-sdks/platform-tools:/Users/girisenji/android-sdks/tools:/opt/homebrew/opt/gradle/bin:/usr/local/bin/maven/bin:/usr/local/opt/python/libexec/bin:/usr/local/opt/ruby/bin:/usr/local/opt/docker/bin:/opt/homebrew/opt/ant/bin:/Users/girisenji/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/girisenji/.fig/bin:/Users/girisenji/.local/bin:/usr/local/opt/hadoop/sbin:/usr/local/opt/hadoop/bin
    - __CFBundleIdentifier: dev.warp.Warp-Stable
```

**Comment by kristianw** [comment]
It is not supported yet @girisenji but should absolutely be implemented. Warp is the new standard now, so Fig integration would be great.

**Comment by raydot** [comment]
I see a lot of these comments on the Warp repo, and they basically say "not doing it."  I don't know enough about how the two would integrate to comment further but these are two platforms that _absolutely_ belong together.
