### ISSUE TITLE
Plugins -> Installed -> Manage Plugin Menu Item is Broken

### ISSUE THREAD

**Issue by pbr0ck3r** [withfig/fig#2618]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.4.1 (22F82)

### Expected behaviour

Plugins -> Installed -> Click Plugin Menu -> Manage -> Takes me to plugin page to manage installation/configuration/extras/

### Actual behaviour

Does nothing

### Steps to reproduce

Plugins -> Installed -> Click Plugin Menu  -> Mange -> does nothing

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.4.1 (22F82)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/pbrocker
  - exe-path: /Users/pbrocker/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 6e84151f-239a-4363-bc4c-b45171edadcc
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 41258
    - FIG_SET_PARENT: 6e84151f-239a-4363-bc4c-b45171edadcc
```

**Comment by grant0417** [comment]
This should be fixed now, thanks for reporting!
