### ISSUE TITLE
Autocomplete popup appearance

### ISSUE THREAD

**Issue by jamalalayeq** [withfig/fig#2624]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.4.0 (22F66)

### Expected behaviour

The autocomplete popup appears while writing commands

### Actual behaviour

It appears but in a very small size although I set width = 400 and height = 200 plus font size = 15 and the font family is Fira Code.  

### Steps to reproduce

Suddenly occurred, the Last thing that has been done is the popup size, font size, and font family.

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.4.0 (22F66)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/{USER_NAME}
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 4a719c86-808c-4fca-a0ff-8b91536e04f6
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/{USER_NAME}/.fig/bin:/Users/{USER_NAME}/.local/bin:/Users/{USER_NAME}/Development/flutter/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 41904
    - FIG_SET_PARENT: 4a719c86-808c-4fca-a0ff-8b91536e04f6
```

**Comment by grant0417** [comment]
Could you make some video to show what is going on?
