### ISSUE TITLE
Fig suggestions aren't showing up

### ISSUE THREAD

**Issue by chasrmartin** [withfig/fig#2630]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.7 (21G651)

### Expected behaviour

I can run fig, I get the fig popup (which I kind of hate by the way) but fig isn't interacting with me in the terminal at all.

Terminal is up-to-date iterm, using zsh with oh-my-zsh.

### Actual behaviour

No apparent fig-ness on the command line at all.

### Steps to reproduce

run fig. No fig interaction.

### Environment

```yaml
fig-details:
  - 2.16.0-beta.3
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
  - cores: 2
  - mem: 16.00 GB
os-info:
  - macOS 12.6.7 (21G651)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/chasrmartin/Dropbox/Etudes/Sandbox
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.970f1br5IT/org.xquartz:0
    - FIGTERM_SESSION_ID: b385d66d-0c36-4a64-a962-d1a331ed1bad
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0-beta.3
    - PATH: /Users/chasrmartin/.rvm/gems/ruby-3.0.0/bin:/Users/chasrmartin/.rvm/gems/ruby-3.0.0@global/bin:/Users/chasrmartin/.rvm/rubies/ruby-3.0.0/bin:/Users/chasrmartin/anaconda3/bin:/Users/chasrmartin/anaconda3/condabin:/Users/chasrmartin/Library/Caches/activestate/bin:/Users/chasrmartin/.local/ActiveState/StateTool/release/bin:/usr/local/smlnj/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/quarto/bin:/Users/chasrmartin/.cargo/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/chasrmartin/.fig/bin:/Users/chasrmartin/.local/bin:/Users/chasrmartin/ch-darwin-amd64:/usr/local/bin:/Users/chasrmartin/ch-darwin-amd64:/usr/local/opt/fzf/bin:/Users/chasrmartin/.rvm/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 2400
    - FIG_SET_PARENT: b385d66d-0c36-4a64-a962-d1a331ed1bad
```

**Comment by blairham** [comment]
This is only recent to add to this, I noticed it's only aliases (at least for me) stopped working.

**Comment by shaiu** [comment]
Same here

**Comment by CarlosZiegler** [comment]
For me too, not works more

**Comment by alimagedayad** [comment]
This happens to me as well,

**Comment by ktika** [comment]
For me, it doesn't show up after booting my Macbook M1 machine. I tried the `fig doctor` command but don't see any errors. I have to run `fig restart` to make it work.

macOS version: `Ventura 13.4.1`
fig version: `2.16.0`

**Comment by grant0417** [comment]
Can you try restating Fig now? Does it work?

**Comment by alimagedayad** [comment]
@grant0417 I didn't work when restarting Fig but it did work when I restarted my mac.

Terminal: macOS native terminal (zsh)
macOS version: Venture 13.4.1
fig version: 2.16.0
machine: MBP M1

**Comment by bobcolner** [comment]
fig stopped working for me in all terminals (fig doctor says "Everything looks good!"). macos 13.4.1 (22F82)
