### ISSUE TITLE
Error with ssh integration

### ISSUE THREAD

**Issue by pedrolucascaratti** [withfig/fig#2632]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.0 (22D49)

### Expected behaviour

Run "fig doctor" and all be OK...
Expected to fix with "fig integrations install ssh"...

### Actual behaviour

* fig doctor
✘ SSH integration: /Users/pedro/.fig/ssh does not exist.
Attempting to fix automatically...
Failed to fix: Permission denied: /Users/pedro/.fig/ssh

✘ Doctor found errors. Please fix them and try again.

* fig integrations install ssh
error: Permission denied: /Users/pedro/.fig/ssh

![image](https://github.com/withfig/fig/assets/44215751/cc0cd9fc-0c4b-4976-92e4-422c7acbb95d)
![image](https://github.com/withfig/fig/assets/44215751/5a70bdc8-0529-4f30-b525-d2810812a93a)
![image](https://github.com/withfig/fig/assets/44215751/5a6c6b15-f42b-4550-b88d-e0d0c7cbfcd0)
![image](https://github.com/withfig/fig/assets/44215751/447fc2ae-7e4f-433e-9805-293f1f625744)
![image](https://github.com/withfig/fig/assets/44215751/3ff86081-75bf-49e4-839d-dad0507ce6ef)

### Steps to reproduce

* Download Fig
* Copy to applications
* Run fig
* Login
* Make the step-by-step
* Run fig doctor
* Try to run fig integrations install ssh

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/pedro
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.3YmBbjopxc/org.xquartz:0
    - FIGTERM_SESSION_ID: c01635de-1b10-43a8-8268-d603e43788d0
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/pedro/.local/share/zinit/polaris/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/pedro/.fig/bin:/Users/pedro/.local/bin:/Users/pedro/Library/Application Support/JetBrains/Toolbox/scripts:/Users/pedro/flutter/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 6671
    - FIG_SET_PARENT: c01635de-1b10-43a8-8268-d603e43788d0
```

**Comment by grant0417** [comment]
Can you check the permissions of the `~/.ssh` folder with `ls -al ~/.ssh`

**Comment by pedrolucascaratti** [comment]
![image](https://github.com/withfig/fig/assets/44215751/3dc33e29-eab5-485e-95be-e25653a47ea2)

**Comment by grant0417** [comment]
Hmm, actually could you try running `rm -rf ~/.fig/ssh` and run `fig integrations install ssh` again.

**Comment by pedrolucascaratti** [comment]
It worked!!!
Thank you so much!
![Uploading image.png…]()
