### ISSUE TITLE
Not warp compatible

### ISSUE THREAD

**Issue by builpro** [withfig/fig#2634]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.0.0 (23A5286i)

### Expected behaviour

works with warp terminal app

### Actual behaviour

✘ Fig Integration: WarpTerminal is not supported
✘ Doctor found errors. Please fix them and try again.

### Steps to reproduce

> fig doctor

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.0.0 (23A5286i)
environment:
  - shell: /bin/zsh
  - terminal: <unknown>
  - cwd: /Users/buil
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - PATH: /Users/buil/.local/share/fig/plugins/git-open:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/buil/.fig/bin:/Users/buil/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: dev.warp.Warp-Stable
    - FIG_SET_PARENT_CHECK: 1
    - FIG_PID: 4768
    - FIG_SET_PARENT:
```

**Comment by alimagedayad** [comment]
Check this https://github.com/withfig/fig/issues/785

**Comment by grant0417** [comment]
We cant integrate as explained in #785

**Comment by Tom-Ainsworth** [comment]
@grant0417 What is the explanation for not supporting it? I can't see anything on the #785 issue
