### ISSUE TITLE
Error listing saved scripts in the dashboard

### ISSUE THREAD

**Issue by acid113** [withfig/fig#2643]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.4.1 (22F770820d)

### Expected behaviour

Saved scripts are listed

### Actual behaviour

Saved scripts are not listed. Getting error message: _fc6417515ee54858b0a6830cadf878f7_

### Steps to reproduce

1. Open Fig dashboard
2. Go to Scripts

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 13.4.1 (22F770820d)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/{user}
  - exe-path: /Users/{user}/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 13b6e1e8-91ca-4b97-bca7-40fc3cfeb1c6
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/{user}/.nvm/versions/node/v19.6.1/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/laps:/usr/local/share/dotnet:~/.dotnet/tools:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/{user}/.fig/bin:/Users/{user}/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 4054
    - FIG_SET_PARENT: 13b6e1e8-91ca-4b97-bca7-40fc3cfeb1c6
```

**Comment by acid113** [comment]
I can still run the saved scripts

**Comment by kramerlee** [comment]
I've got the same issue.
I cannot modify the saved scripts. Apparently, I can still use it

**Comment by grant0417** [comment]
Hey, this was an error with updating one of our dependencies, it is fixed now!

**Comment by acid113** [comment]
Nice! I can see my scripts again. Thank you!
