### ISSUE TITLE
Issue：.zshrc file content is deleted by fig

### ISSUE THREAD

**Issue by nenhall** [withfig/fig#2653]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS13.4

### Expected behaviour

Don't delete the contents of my .zshrc file;
Don't delete the contents of my .zshrc file;
Don't delete the contents of my .zshrc file.

### Actual behaviour

Today, after my computer restarted, fig also started automatically, and then a dialog box popped up, and I replaced and deleted all the contents in my `.zshrc` file. After being replaced, only the following contents were found:

1. Issue 1
Regardless of whether I click Don’t Allow or OK, when I switch to the application window of fig, it will always pop up repeatedly
<img width="715" alt="image" src="https://github.com/withfig/fig/assets/19990465/bd24ebb3-799f-4d22-bcaf-67bcea884225">

2.  issue 2
```
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
```

### Steps to reproduce

The bullet box problem has always been there, as long as the fig application is started

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M2
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.4.0 (22F66)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/meitu
  - exe-path: /Users/meitu/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: e77f421b-b2e9-4e00-9417-95c95a825747
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/Applications/Yunshu.app/Contents/Public:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/meitu/.fig/bin:/Users/meitu/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 1479
    - FIG_SET_PARENT: e77f421b-b2e9-4e00-9417-95c95a825747
```

**Comment by grant0417** [comment]
Hey, sorry this issue should be resolved if you restart Fig, let us know if the issue persists

**Comment by grant0417** [comment]
Hey, also so sorry about the .zshrc being deleted, I thought this was just the FigInputMethod popup. Do you have a backup of the old file in `~/.fig.dotfiles.bak/`. Happy to give as much support as I can!
