### ISSUE TITLE
bug: FIG app configure error in macos m1

### ISSUE THREAD

**Issue by 2beetle** [withfig/fig#2654]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.4.1 (22F770820d)

### Expected behaviour

when i launch the app and configure it correctly, the permission enable window should be close

### Actual behaviour

when i launch the app and configure it correctly, the permission enable window keep openning and i can't close it
![image](https://github.com/withfig/fig/assets/74488739/e99fc427-092b-4e8d-88c4-e3d94edff8f1)

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.4.1 (22F770820d)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - __CFBundleIdentifier: com.mschrage.fig
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh
```

**Comment by grant0417** [comment]
Hey, sorry this issue should be resolved if you restart Fig, let us know if the issue persists

**Comment by 2beetle** [comment]
I already restart the fig, event my mac but when i open the fig app again, the error happen again

**Comment by 2beetle** [comment]
> Hey, sorry this issue should be resolved if you restart Fig, let us know if the issue persists

I already restart the fig, event my mac but when i open the fig app again, the error happen again
