### ISSUE TITLE
Fig autocomplete window not shown

### ISSUE THREAD

**Issue by 101sam** [withfig/fig#2659]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.5.0 (22G74)

### Expected behaviour

fig auto-complete does not show the window
fig restart all works for the first part
then stop again after 2nd/3rd command 

We re-install a few times fig.

### Actual behaviour

We attached a screen recording to show the issue. 
[Attached screen record](https://drive.google.com/file/d/1JmigHBF7R7W3FXrgJycZE8AaTK2NhiOm/view?usp=drivesdk)

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.5.0 (22G74)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/101sam
  - exe-path: /Users/101sam/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 2683fa80-6759-40a3-a63e-e45cdcfbbfd6
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /opt/homebrew/opt/curl/bin:/Users/101sam/.nvm/versions/node/v18.16.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/101sam/.fig/bin:/Users/101sam/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 8748
    - FIG_SET_PARENT: 2683fa80-6759-40a3-a63e-e45cdcfbbfd6
```

**Comment by 101sam** [comment]
Any update?

**Comment by Masonwabe** [comment]
facing the same issue as well.

**Comment by chaynabors** [comment]
Fig can't determine what you've typed because of your shell-native autocomplete. It's why the window shows up briefly before your native completions show up. There's no way around this that we know of and so I can only unfortunately say that we don't support the plugin.
