### ISSUE TITLE
`fig install --input-method` is not working

### ISSUE THREAD

**Issue by Spielboerg** [withfig/fig#2665]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.5.0 (22G74)

### Expected behaviour

The Script is running and enabling fig in Webstorm.

### Actual behaviour

Terminal log:
```
fig install --input-method

For Fig to support some terminals like Kitty, Alacritty, and Wezterm
you must enable our Input Method integration.

To enable the integration, select "yes" below and then click Ok in the popup.

✔ Do you want to enable support for input method backed terminals? · Yes

```
After the last line, the OS keyboard settings open but nothing happens afterward.

When I run `fig restart` a banner in the UI is asking to enable autocomplete, but when I click on the "Enable" button in the opened "Help & Support" modal nothing happens, too.

### Steps to reproduce

See "Actual behavior" section above.

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.5.0 (22G74)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/steffen.wilking
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: afd7ab70-0067-4c32-8943-133926f42b95
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/steffen.wilking/.fig/bin:/Users/steffen.wilking/.local/bin:/Users/steffen.wilking/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 9994
    - FIG_SET_PARENT: afd7ab70-0067-4c32-8943-133926f42b95
```

**Comment by Spielboerg** [comment]
Today I tired again and it worked.

**Comment by dcoferraz** [comment]
> Today I tired again and it worked.

What did you do different?

Mine just opens up the settings on Keyboard and it's stuck there

**Comment by Spielboerg** [comment]
@dcoferraz to be honest, I'm not 100% sure, but if I remember correctly I solved it by having admin rights at that moment. But maybe it was fixed by a restart of the Mac or an update of fig.
