### ISSUE TITLE
Deamon is not running

### ISSUE THREAD

**Issue by MrZhenShen** [withfig/fig#2667]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.5.0 (22G74)

### Expected behaviour

after executing `fig doctor` get output that "Daemon: Daemon is running"

### Actual behaviour

/Users/user/.bash_profile is not read or writable
Daemon: Daemon is not running
Attempting to fix automatically...
Failed to fix: Failed to run 'launchctl load -F '/Users/user/Library/LaunchAgents/io.fig.dotfiles-daemon.plist'' (signal: 9 (SIGKILL)): 

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.5.0 (22G74)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/user
  - exe-path: /Users/user/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: e0c1393f-5dbc-406c-bfc1-e48267da9c28
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/usr/local/opt/liquibase:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/user/.fig/bin:/Users/user/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 8532
    - FIG_SET_PARENT: e0c1393f-5dbc-406c-bfc1-e48267da9c28
```

**Comment by kamil-hammouche** [comment]
Hello @MrZhenShen, I encountered the same issue.
Doing "sudo chown $USER ~/.bash_profile" and running "fig doctor" again fixed this for me.

**Comment by chaynabors** [comment]
Seems like this might just be misconfigured permissions on your bash profile. Try what Kamil mentioned and let me know if you can reproduce otherwise and I'll check it out.
