### ISSUE TITLE
theme not working

### ISSUE THREAD

**Issue by rajamani-s-1007581** [withfig/fig#2675]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E261)

### Expected behaviour

I have changed my theme to light. it should change to light theme

### Actual behaviour

The theme never changes from dark mode

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 13.3.1 (22E261)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/rs/Freshchat/unity_backend
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 23d8234b-716c-40d5-8552-a63b1f7d565b
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Library/Frameworks/Python.framework/Versions/3.11/bin:/Users/rs/Downloads/Apps/gradle-5.6.4/bin :/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/rs/.fig/bin:/Users/rs/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 42494
    - FIG_SET_PARENT: 23d8234b-716c-40d5-8552-a63b1f7d565b
```

**Comment by chaynabors** [comment]
How did you change the theme? Was it through the UI? Does the command `fig theme light` work for you? Have you attempted to restart Fig since changing the theme? Just trying to gauge what works and doesn't work here.
