### ISSUE TITLE
Keypress lag when typing in any app, not just a terminal

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#270]
> I've noticed that when Fig is running typing on other apps (Chrome for instance) becomes pretty laggy and misses some key presses. Is that a known issue?

Fig intercepts certain keystrokes (like enter, tab, and the arrow keys) while you're in the terminal. We've optimised the crap out of this so it never slows you down, however, it is still an extra process than is always going to have a cost. We are hoping to refactor part of this code soon such that there would never be any lag outside of a terminal application.

**Comment by mschrage** [comment]
This is fixed as of v1.0.46!
