### ISSUE TITLE
Fig breaks my agnoster configuration

### ISSUE THREAD

**Issue by Konixy** [withfig/fig#2700]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 11.7.8 (20G1351)

### Expected behaviour

I have [omz](https://ohmyz.sh/) installed with the [agnoster](https://github.com/agnoster/agnoster-zsh-theme) theme and i don't wanted agnoster to show the cwd like the following screenshot

<img width="305" alt="Screenshot 2023-08-24 at 18 47 09" src="https://github.com/withfig/fig/assets/66780340/47280ef2-4522-4485-94d4-c232199f95cf">

So i wrote a little configuration that disable it that i put in the `~/.zshrc` file (like in the agnoster documentation):
```zsh
prompt_context() {}
```

That give me the following prompt:

<img width="170" alt="Screenshot 2023-08-24 at 18 52 29" src="https://github.com/withfig/fig/assets/66780340/116ea999-5991-42e9-8860-d92e47c72806">

### Actual behaviour

Since I installed fig, my agnoster configuration don't work.

Here is my `~/.zshrc` file:
```zsh
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

plugins=(
   git
   zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Remove agnoster display cwd a the begining of the prompt

prompt_context() {}

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
```

I tried to put my configuration before the `source $ZSH/oh-my-zsh.sh` line but it didn't work anymore.

### Steps to reproduce

Install omz with the following `.zshrc`:
```zsh
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

plugins=(
   git
   zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Remove agnoster display cwd a the begining of the prompt

prompt_context() {}

```

then install fig

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: MacBook Pro mid-2014
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  - cores: 2
  - mem: 8.00 GB
os-info:
  - macOS 11.7.8 (20G1351)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: ~
  - exe-path: ~/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 07ef59ab-88dc-45e3-b8bc-b038cc945902
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.fig/bin:~/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 46415
    - FIG_SET_PARENT: 07ef59ab-88dc-45e3-b8bc-b038cc945902
```

**Comment by mschrage** [comment]
Can you share a screenshot of the prompt that is displayed?
