### ISSUE TITLE
Unable to Install "fig" Using Homebrew and Registration Issue

### ISSUE THREAD

**Issue by jh-leong** [withfig/fig#2702]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.4.1 (22F82)

### Expected behaviour

install via Homebrew

### Actual behaviour

1. Installation Problem with Homebrew:

I had a problem when I was trying to install "fig" using Homebrew (brew install fig). The installation process gave me this error:

```
==> Downloading https://versions.withfig.com/fig%20311.dmg
curl: (6) Could not resolve host: versions.withfig.com
Warning: Problem : timeout. Will retry in 1 seconds. 3 retries left.
curl: (6) Could not resolve host: versions.withfig.com                        
Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
curl: (6) Could not resolve host: versions.withfig.com                        
Warning: Problem : timeout. Will retry in 4 seconds. 1 retries left.
curl: (6) Could not resolve host: versions.withfig.com                        

Error: Download failed on Cask 'fig' with message: Download failed: https://versions.withfig.com/fig%20311.dmg
```

2. Registration Issue with Fig Dashboard:

Also, when I tried using the Fig Dashboard, I ran into some trouble while trying to sign up. I'm not sure if this problem is because of my internet or if there's something going on with the Fig Dashboard itself.

Here's a screenshot for reference:

<img width="1030" alt="image" src="https://github.com/withfig/fig/assets/52022476/5a088d88-a4cb-4dba-a5a4-33748b020213">

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 13.4.1 (22F82)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - __CFBundleIdentifier: com.mschrage.fig
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh
```

**Comment by masoudinejad** [comment]
I am dealing with the same issue

**Comment by sedeeman** [comment]
I am dealing with the same issue. Mac OS Ventura 13.5 (22G74)

**Comment by akhilkathuria** [comment]
same issue

**Comment by Daniil-Borisov** [comment]
I have same issue too. Could you provide how I can fix this?

**Comment by JackFannon** [comment]
@brendanfalk said this in the Fig discord on 24/08:
> Hey guys - we've made a temporary change that disables new user sign ups as we push out some new functionality. Should have communicated this better. We should have it back online soon. Existing users are not affected. Really really sorry about this!
and then on 25/08 said they would have more updates on Monday (28/08).

**Comment by mschrage** [comment]
Hi all, we announced that [Fig joining AWS](https://fig.io/blog/post/fig-joins-aws). We're working with internal security teams to reenable new logins. I know it is frustrating to need to wait, but we'll hopefully have exciting updates to share soon.

**Comment by eliazoura** [comment]
Same trouble ... Fig is a great tool, I hope it will be fied soon. Thank you to all the fIG TEAM
(is there an equivalent for Windows / Linux ?)
