### ISSUE TITLE
Can not Install Fig in Mac OS Ventura 13.5: bug

### ISSUE THREAD

**Issue by sedeeman** [withfig/fig#2704]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.5.0 (22G74)

### Expected behaviour

Should be able to sign up and integrate with Hyper.js

### Actual behaviour

Can't signup and  can not proceed further. 
`PATH ~ % fig doctor

● PATH/.bashrc does not source pre integration
● PATH.bash_profile does not source pre integration
✘ zsh ~/.zshrc integration check: PATH/.zshrc does not source pre integration

  Run fig integrations install dotfiles to reinstall shell integrations for zsh
Attempting to fix automatically...
Re-running check...

✔ zsh ~/.zshrc integration check
✘ zsh ~/.zprofile integration check: File does not exist: PATH/.zprofile

  Run fig integrations install dotfiles to reinstall shell integrations for zsh
Attempting to fix automatically...
Re-running check...

✔ zsh ~/.zprofile integration check
✘ PATH contains ~/.local/bin: Path does not contain ~/.local/bin

✘ Doctor found errors. Please fix them and try again.
<img width="1031" alt="can not sign up" src="https://github.com/withfig/fig/assets/119731054/bb383859-40c5-46a0-8064-6d14ca04a6d2">
`

### Steps to reproduce

Mac OS version :  Ventura 13.5
Install Fig using  via brew command or .dmg and try to use with  Hyper or  default terminal.

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.5.0 (22G74)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - __CFBundleIdentifier: com.mschrage.fig
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh
```

**Comment by vishalsaini26** [comment]
getting the same issue why is it closed?
