### ISSUE TITLE
bug: cannot delete my account

### ISSUE THREAD

**Issue by miclgael** [withfig/fig#2708]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS

### Expected behaviour

When visiting Settings > My Profile > Delete Account and typing my username, I expect my account to be deleted. T

### Actual behaviour

Displays a message:

```
Unexpected Server Error: DbError. Sentry ID: <redacted>.
```

### Steps to reproduce

In the macOS app, go to Settings > My Profile > Delete Account

In the web app, go to Settings > My Profile > Delete Account

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 12.2.1 (21D62)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: <redacted>.
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 6f1f6d20-fde6-45ca-9474-3a862f4ebb60
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: <redacted>.
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 69299
    - FIG_SET_PARENT: 6f1f6d20-fde6-45ca-9474-3a862f4ebb60
```

**Comment by mschrage** [comment]
Hey @miclgael! Thanks for flagging this. The team will investigate.
