### ISSUE TITLE
iterm locked. the terminal session is showing a lock image and won't let me run basic commands. the error says operation not permitted. please help

### ISSUE THREAD

**Issue by jotalp** [withfig/fig#2714]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.8 (21G725)

### Expected behaviour

i expect the commands to run without any issues. Even when I try running them as root they don't work.

### Actual behaviour

<img width="1440" alt="Screen Shot 2023-09-02 at 7 56 47 PM" src="https://github.com/withfig/fig/assets/28308860/8d0f0fc7-86fc-4b29-84ea-51a0622b58ea">

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 12.6.8 (21G725)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/jp
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 954ac19c-cf5e-475b-a017-8e520257e33d
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/jp/.rvm/gems/ruby-3.0.0/bin:/Users/jp/.rvm/gems/ruby-3.0.0@global/bin:/Users/jp/.rvm/rubies/ruby-3.0.0/bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/minicom/2.2/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jp/.fig/bin:/Users/jp/.local/bin:/Users/jp/.local/share/fig/plugins/git-extra-commands_unixorn/bin:/Users/jp/.local/share/fig/plugins/git-extra-commands_unixorn/bin:/Users/jp/.local/share/fig/plugins/tumult.plugin.zsh_unixorn/bin:/usr/local/share/npm/bin:/Users/jp/.rvm/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 41565
    - FIG_SET_PARENT: 954ac19c-cf5e-475b-a017-8e520257e33d
```

**Comment by miclgael** [comment]
Wow.

Something corrupting your `~/.zshrc` ? Could you try commenting out the fig lines at the top and bottom and see if it fixes?

**Comment by jotalp** [comment]
That didn't work... still saying "Operation not permitted"

**Comment by mschrage** [comment]
This is very strange! Can you share your `.zshrc`? What happens if your run `cd` or `ls`?
