### ISSUE TITLE
fig suggestions are disapperaing

### ISSUE THREAD

**Issue by noa-rm** [withfig/fig#2726]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.5.2 (22G91)

### Expected behaviour

I'll be able to scroll within fig suggested options.

### Actual behaviour

Options are presented but can't be accessed.
I've also have `source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh` in my zshrc which might override the fig autocomplete.

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 13.5.2 (22G91)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 3da43390-d7dc-4d12-9d6b-b42e04952474
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
```

**Comment by mschrage** [comment]
Let me make sure I am understanding your issue correctly:

You see the autocomplete window appear, but none of your keypresses are registered with the app. For instance, if you press the down arrow arrow, the selection state does not move down in response.

Can you share a screen recording of the behavior?

**Comment by AhmedCodeGuy** [comment]
I have the same issue

**Comment by noa-rm** [comment]
No option to scroll between suggestions with neither tab or with up and down buttons.
https://github.com/withfig/fig/assets/73590714/6d0ddafa-63a2-470d-9546-54acd979ad6e

**Comment by mschrage** [comment]
@noa-rm this is a compatibility issue with zsh-autocomplete. This is not something we can fix on our end unfortunately. You'll have to pick one or the other.
