### ISSUE TITLE
bug: PROJECT IS DEAD

### ISSUE THREAD

**Issue by andreieuganox** [withfig/fig#2734]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS

### Expected behaviour

Signup works

### Actual behaviour

Signup disabled

**Comment by akadori** [comment]
> [New users will not be able to sign up for Fig's products right now while we focus on optimizing them for existing customers and addressing some needs identified to integrate Fig with AWS.](https://fig.io/blog/post/fig-joins-aws#:~:text=New%20users%20will%20not%20be%20able%20to%20sign%20up%20for%20Fig%27s%20products%20right%20now%20while%20we%20focus%20on%20optimizing%20them%20for%20existing%20customers%20and%20addressing%20some%20needs%20identified%20to%20integrate%20Fig%20with%20AWS.)

**Comment by grant0417** [comment]
I promise we are not dead! We do not have signups enabled for now but are still working on improving the project.
