### ISSUE TITLE
tmux always shows zsh as pane_current_command

### ISSUE THREAD

**Issue by robertoplancarte** [withfig/fig#2736]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.4.1 (22F770820d)

### Expected behaviour

When running vim inside tmux if you run
 `<leader> run "(tmux display-message -p '#{pane_current_command}')"` 
the result should be `vim`

### Actual behaviour

When running vim inside tmux if you run
 `<leader> run "(tmux display-message -p '#{pane_current_command}')"` 
the result is `zsh`
<img width="1840" alt="Screenshot 2023-09-19 at 2 13 59" src="https://github.com/withfig/fig/assets/314050/3d8a8e39-aa8a-42ed-b722-363b11ace19b">
<img width="1840" alt="Screenshot 2023-09-19 at 2 13 53" src="https://github.com/withfig/fig/assets/314050/2149ec78-6639-42bb-9faf-667a097b1f5f">

### Steps to reproduce

Install tmux, vim and fig. run tmux and vim inside of it. run `<tmux-leader> run "(tmux display-message -p '#{pane_current_command}')"` and the output will be `zsh`. if you uninstall fig the output will be `vim`

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.4.1 (22F770820d)
environment:
  - shell: /bin/zsh
  - terminal: kitty
  - cwd: /Users/robertopancarte
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 6129fa27-f86d-4aca-b7ac-af43cba5a634
    - FIG_PID: 46616
    - FIG_SET_PARENT: 6129fa27-f86d-4aca-b7ac-af43cba5a634
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - FIG_TERM_TMUX: 2.16.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Applications/kitty.app/Contents/MacOS:/Users/robertopancarte/.fig/bin:/Users/robertopancarte/.local/bin
    - SHELL: /bin/zsh
    - TERM: screen-256color
    - __CFBundleIdentifier: net.kovidgoyal.kitty
```

**Comment by robertoplancarte** [comment]
https://github.com/christoomey/vim-tmux-navigator/issues/294#issuecomment-1005068393

**Comment by mschrage** [comment]
There are occasionally strange compatibility issues with tmux configurations. This are unfortunately out of our support matrix.
