### ISSUE TITLE
Can't sign up to fig

### ISSUE THREAD

**Issue by mansourshebli** [withfig/fig#2743]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS

### Expected behaviour

Signing up & creating an account at fig

### Actual behaviour

![fighelp](https://github.com/withfig/fig/assets/132643497/e32fd0d6-bc27-46b2-b034-cca90d72cdbb)

**Comment by mtariqsajid** [comment]
I had the same issue not able to sign up using git or email

**Comment by mtariqsajid** [comment]
did anyone resolve this issue ?

**Comment by mtariqsajid** [comment]
@mansourshebli @mathew-fleisch
