### ISSUE TITLE
fig doctor is not running

### ISSUE THREAD

**Issue by Ayush330** [withfig/fig#2744]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.0 (22E252)

### Expected behaviour

fig doctor should run

### Actual behaviour

PATH contains ~/.local/bin: Path does not contain ~/.local/bin

### Steps to reproduce

run fig doctor

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.3.0 (22E252)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/ayushanand
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /bin/zsh
    - __CFBundleIdentifier: com.googlecode.iterm2
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
    - TERM: xterm-256color
```

**Comment by mschrage** [comment]
Can you share your zshrc file?
