### ISSUE TITLE
Not able to signup

### ISSUE THREAD

**Issue by atulTiwari-dazn** [withfig/fig#2748]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.5.1 (22G90)

### Expected behaviour

I am a new user, I should be able signup.

### Actual behaviour

Trying to signup with my work mail, but it says signups are disabled

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.5.1 (22G90)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/atul.tiwari/Documents/event-service
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: com.apple.Terminal
    - TERM: xterm-256color
    - SHELL: /bin/zsh
    - PATH: /Users/atul.tiwari/.nvm/versions/node/v18.17.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/laps:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
```

**Comment by devansh-mohata** [comment]
They have disabled signups for now.

**Comment by mschrage** [comment]
Signups are unfortunately disable for the moment. We are working to turn access back on for new users.
