### ISSUE TITLE
bug: Cant able to load images on website

### ISSUE THREAD

**Issue by cha2hyun** [withfig/fig#2749]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOs, iPhone

### Expected behaviour

<img width="1000" alt="image" src="https://github.com/withfig/fig/assets/56015532/50e53c0c-6292-476c-8c60-c63867ec205b">

some images are not loaded on website

### Actual behaviour

-

**Comment by mschrage** [comment]
Thanks for reporting! We're looking into it.

**Comment by grant0417** [comment]
This should be fixed now @cha2hyun, thanks for reporting it!
