### ISSUE TITLE
fig don't wanna start

### ISSUE THREAD

**Issue by mrk088** [withfig/fig#2750]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.0.0 (23A344)

### Expected behaviour

❯ fig doctor

✔ Everything looks good!

  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!

❯ fig restart
Restarting Fig
❯ fig
❯ fig doctor

✔ Everything looks good!

  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!

❯ fig issue
✔ Issue Title · fig don't wanna start

and don't wanna autocomplete

### Actual behaviour

i restart i start doctor rstart and everithing is recommanted but it  not works i'm on mac os sonoma

### Steps to reproduce

i restart i start doctor rstart and everithing is recommanted but it  not works i'm on mac os sonoma

### Environment

```yaml
fig-details:%0A  - 2.16.0%0Ahardware-info%3A%0A  - model%3A %0A  - model-id%3A %0A  - chip-id%3A Apple M1 Pro%0A  - cores%3A 10%0A  - mem%3A 16.00 GB%0Aos-info%3A%0A  - macOS 14.0.0 (23A344)%0Aenvironment%3A%0A  - shell%3A /bin/zsh%0A  - terminal: iterm%0A  - cwd: /Users/bozzettomirko%0A  - exe-path: /Users/bozzettomirko/.fig/bin/fig%0A  - install-method: unknown%0A  - env-vars:%0A    - FIGTERM_SESSION_ID: c08ef902-ec71-45e4-a351-763c365ef0a3%0A    - FIG_SET_PARENT_CHECK: 1%0A    - FIG_TERM: 2.16.0%0A    - PATH: /Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/bozzettomirko/.cargo/bin:/Users/bozzettomirko/.fig/bin:/Users/bozzettomirko/.local/bin%0A    - SHELL: /bin/zsh%0A    - TERM: xterm-256color%0A    - __CFBundleIdentifier: com.googlecode.iterm2%0A    - FIG_PID: 15047%0A    - FIG_SET_PARENT: c08ef902-ec71-45e4-a351-763c365ef0a3
```

**Comment by mschrage** [comment]
Hmm this could be an issue with macOS Sonoma. Did this start after you upgraded?

**Comment by grant0417** [comment]
Can you run fig directly in the cli and give the output: `/Applications/Fig.app/Contents/MacOS/fig_desktop`

**Comment by mrk088** [comment]
It works now, it is maybe  update of Sonoma finally
