### ISSUE TITLE
Ctrl+C is sent as `^[[99;5u`

### ISSUE THREAD

**Issue by 5ouma** [withfig/fig#2751]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.9 (21G726)

### Expected behaviour

I can stop the running process with <kbd>Ctrl+C</kbd>.

### Actual behaviour

When I type <kbd>Ctrl+C</kbd>, it's sent as `^[[99;5u`.

### Steps to reproduce

When I run `zshrc.post.zsh` with [zsh-defer](https://github.com/romkatv/zsh-defer) loaded, the keystroke is sent as `^[[99;5u`.

This is the issue of zsh-defer I asked the author of it.
https://github.com/romkatv/zsh-defer/issues/12

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  - cores: 4
  - mem: 8.00 GB
os-info:
  - macOS 12.6.9 (21G726)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/souma
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: bc3451aa-97c1-4733-94f1-dd8dcd7f6e42
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/souma/.local/share/rtx/installs/node/20.7.0/bin:/Users/souma/.local/share/rtx/installs/go/1.21.1/go/bin:/Users/souma/.local/share/rtx/installs/go/1.21.1/packages/bin:/Users/souma/.local/share/sheldon/repos/github.com/wfxr/forgit/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/souma/.dotfiles:/usr/local/sbin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/souma/.orbstack/bin:/Users/souma/.fig/bin:/Users/souma/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/souma/.config/zsh
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 71283
    - FIG_SET_PARENT: bc3451aa-97c1-4733-94f1-dd8dcd7f6e42
```

**Comment by mschrage** [comment]
This sounds like a potential compatibility issue with your zsh configuration. 

Can you run `fig debug-keytester` and press ^C

**Comment by 5ouma** [comment]
Do you mean `fig debug key-tester`?

```shell
7 bytes : "\x1b[99;5u" : [1b, 5b, 39, 39, 3b, 35, 75]
```

**Comment by Kendarou** [comment]
I have the same problem too.

**Comment by cruzluna** [comment]
```
❯ fig debug-keytester
error: unrecognized subcommand 'debug-keytester'
```

**Comment by 5ouma** [comment]
Close this Issue since CodeWhisperer for Command Line solved this problem.

**Comment by cruzluna** [comment]
> Close this Issue since CodeWhisperer for Command Line solved this problem.

Does this mean I need to download Code Whisperer?

**Comment by 5ouma** [comment]
> > Close this Issue since CodeWhisperer for Command Line solved this problem.
> 
> Does this mean I need to download Code Whisperer?

I recommend you to use it. If you don’t use any features except Autocompletion or AI, CodeWhisperer CL is much more stable than Fig.
