### ISSUE TITLE
bug: Menubar icon duplicated in MacOS Sonoma

### ISSUE THREAD

**Issue by steveblue** [withfig/fig#2754]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.0.0 (23A344)

### Expected behaviour

Fig icon remains in specified menu bar location and doesn't obscure Apple logo.

### Actual behaviour

Fig icon is duplicated in menu bar and obscures Apple logo.
<img width="1728" alt="Screenshot 2023-09-27 at 10 58 45 AM" src="https://github.com/withfig/fig/assets/1171943/9ce39ffd-f0f6-422c-a126-6eeae833f4a7">

### Steps to reproduce

Upgraded to MacOS Sonoma 14.0 and restarted Macbook Pro M1 Max, ran fig doctor and fig restart. Issue remains.

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - __CFBundleIdentifier: com.mschrage.fig
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh
```

**Comment by KaoushikMurugan** [comment]
Just thought this would help:
For me the icons are supposed to be white and the duplication icon is black, this seems to be related to wallpaper background colors since they don't change when I switch between light mode and dark mode
![Screenshot 2023-09-27 at 16 06 13](https://github.com/withfig/fig/assets/63953483/9bcc6c94-8ea2-4e4c-9fbf-d94261ac9cbc)

**Comment by mschrage** [comment]
I have not been able to reproduce while testing on Sonoma. If you restart Fig, does this extra icon disappear?

**Comment by mschrage** [comment]
Very strange. Will see if I can reproduce.

**Comment by bigkahuna1uk** [comment]
I've reproduced this on Sonoma as we speak.

**Comment by yepengfan** [comment]
I encountered the same issue, do we have any updates or fixes?

**Comment by andreekeberg** [comment]
This happened to me as well as soon as I upgraded to Sonoma. The correct, black icon, shows in the right place, but a white version is shown on top on the Apple icon.

<img width="1792" alt="Skärmavbild 2023-11-25 kl  12 44 14" src="https://github.com/withfig/fig/assets/13151212/b4a53582-c781-44b5-bfe8-cdc30e28e6c7">
