### ISSUE TITLE
Autocomplete not working & Blank Fig Launch Screen on Startup

### ISSUE THREAD

**Issue by taylorlemk** [withfig/fig#2766]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.1.0 (23B5056e)

### Expected behaviour

On Launch, Fig Dashboard loads up properly and autocomplete/auto-suggestions work in the terminal. 

### Actual behaviour

Fig Dashboard loads up with a blank white screen. Force quitting and re-opening doesn't work (results in the same, blank white screen and autocomplete/auto-suggestions don't work). Running fig doctor, fig update, doesn't resolve the issue.

### Steps to reproduce

Restarting the computer doesn't properly launch fig. Only when running fig restart, does it temporarily fix things.

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.1.0 (23B5056e)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/taylorle
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.i4AVTAClHe/org.xquartz:0
    - FIGTERM_SESSION_ID: def711ce-5935-45a0-b343-6d1168adb0c3
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/taylorle/.fig/bin:/Users/taylorle/.local/bin:/Users/taylorle/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 1240
    - FIG_SET_PARENT: def711ce-5935-45a0-b343-6d1168adb0c3
```

**Comment by mschrage** [comment]
Interesting. Is there anything unusual about your network access?
