### ISSUE TITLE
It's not showing autocomplete

### ISSUE THREAD

**Issue by vishalramani** [withfig/fig#2773]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.0.0 (23A344)

### Expected behaviour

It should suggest commands automatically.

### Actual behaviour

not suggesting any commands

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/vishalramani
  - exe-path: /Users/vishalramani/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: cec4f1f6-5dae-49ec-9e34-2c3609f41227
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /Users/vishalramani/.nvm/versions/node/v20.5.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/vishalramani/.fig/bin:/Users/vishalramani/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 40910
    - FIG_SET_PARENT: cec4f1f6-5dae-49ec-9e34-2c3609f41227
```

**Comment by mschrage** [comment]
What is the output when you run `fig doctor`?

**Comment by DeanAmiridis** [comment]
I have this same issue, works sometimes, doesn't another. 
Using iTerm, also ran fig doctor.

```
✔ Logged into Fig

Let's check your dotfiles...
✔ bash ~/.bashrc integration check
✔ bash ~/.profile integration check
✔ zsh ~/.zshrc integration check
✔ zsh ~/.zprofile integration check

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ PATH contains ~/.fig/bin
✔ Settings Corruption
✔ State Corruption
✔ Fig Integration
✔ SSH integration

Let's make sure Fig is running...
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Daemon diagnostics

Let's see if Fig is in a working state...
✔ Figterm
✔ Insertion lock does not exist
✔ Autocomplete dev mode
✔ Plugin dev mode
✔ Dashboard is loading from the correct URL
✔ Autocomplete is loading from the correct URL

Let's check if your system is compatible...
✔ OS is supported
✔ Fish is up to date
✔ Jetbrains Toolbox Check

Let's check fig diagnostic...
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled

Let's check your terminal integrations...
✔ Terminal support


  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!

```

**Comment by NaotoKubota** [comment]
Same here. It is not showing any autocomplete at all. I am using iTerm and Terminal. OS is macOS 14.0. The output of `fig doctor` says it is working well but actually not:
```bash
$ fig doctor

✔ Everything looks good!

  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!

```

I tried restarting it many times but nothing changed.

**Comment by mschrage** [comment]
Does running `fig restart` have any effect?

**Comment by DeanAmiridis** [comment]
> Does running fig restart have any effect?

Unfortunately no, neither does completely quitting iTerm or restarting the entire machine. But it does magically start working again at some point, until it occurs again. This was happening to me before the Sonoma update as well as after. Currently it is working, but if there's anything I can collect for troubleshooting that may help you when it happens again; I'm here to help! :-)

**Comment by igorlanko** [comment]
Just happened to me again after restarting my Mac. `fig doctor` shows no errors, everything is OK. I tried restarting Fig with Cmd Q from the UI, but only `fig restart` in the Terminal helped. Seems to work now, but I agree with others—it just stops working randomly at some point, but then comes back 🤷
