### ISSUE TITLE
compdef error on mac

### ISSUE THREAD

**Issue by hmarinox** [withfig/fig#2779]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.0.0 (23A344)

### Expected behaviour

no errors

### Actual behaviour

✅ Dotfiles sourced!

/dev/fd/14:2: command not found: compdef
/dev/fd/14:18: command not found: compdef

[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

### Steps to reproduce

fig source

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /opt/homebrew/Cellar/zsh/5.9/bin/zsh
  - terminal: iterm
  - cwd: /Users/humberto.marino
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.CQaWPXyavZ/org.xquartz:0
    - FIGTERM_SESSION_ID: e8e80397-6c89-4dc8-b3a6-9202366c89da
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/humberto.marino/.virtualenvs/block-storage-backup-qegy/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/humberto.marino/.fig/bin:/Users/humberto.marino/.local/bin:::::::::
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 25450
    - FIG_SET_PARENT: e8e80397-6c89-4dc8-b3a6-9202366c89da
```

**Comment by mschrage** [comment]
Can you share our zshrc file here?

**Comment by hmarinox** [comment]
Hi Matt,

  Thank you for your help.
  
  I just uninstall and reinstall again and the problem as solved,

It looked like some issues with old omz and powerlevel settings. So I decided clean it and install all tools under Fig. 

Thank you again,

Humberto M.

**Comment by hmarinox** [comment]
Closed.
