### ISSUE TITLE
Fig is trying to install again after ssh to server

### ISSUE THREAD

**Issue by amrography** [withfig/fig#2792]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.4.0 (21F79)

### Expected behaviour

Don't interact with `ssh`

### Actual behaviour

```sh
curl -fSsL https://fig.io/install-headless.sh | bash; exec $SHELL
███████╗██╗ ██████╗
██╔════╝██║██╔════╝
█████╗  ██║██║  ███╗
██╔══╝  ██║██║   ██║
██║     ██║╚██████╔╝
╚═╝     ╚═╝ ╚═════╝.io
Performing compatibility checks
Executing https://repo.fig.io/scripts/yum/install.sh
Installing Fig repository
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0    511      0 --:--:-- --:--:-- --:--:--   511
```

### Steps to reproduce

`$ ssh myserver`

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: 12th Gen Intel(R) Core(TM) i5-12400
  - cores: 6
  - mem: 32.00 GB
os-info:
  - macOS 12.4.0 (21F79)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/user
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 5c1f69d6-dca2-421a-be94-93e589f35bb3
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 45994
    - FIG_SET_PARENT: 5c1f69d6-dca2-421a-be94-93e589f35bb3
```

**Comment by bgizdov** [comment]
I have the same issue: the fig autocomplete for SSH keeps trying to install repeatedly every time I log into my server.

**Comment by n3akr** [comment]
same for me, can't find how to prevent this install

**Comment by bgizdov** [comment]
It adds some commands in .bashrc
```
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/bashrc.pre.bash" ]] && builtin source "$HOME/.fig/shell/bashrc.pre.bash"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/bashrc.post.bash" ]] && builtin source "$HOME/.fig/shell/bashrc.post.bash"
```
but even you delete or comment these lines it still executes
```
curl -fSsL https://fig.io/install-headless.sh | bash; exec $SHELL
```
every time.

**Comment by ceramicwhite** [comment]
In `~/.fig/settings.json` change `"ssh.remote-prompt": "always"`


```
➜ cat ~/.fig/settings.json
{
  "autocomplete.ai.enabled": true,
  "autocomplete.hidePreviewWindow": true,
  "autocomplete.keybindings.control+a": "showAutocomplete",
  "autocomplete.theme": "system",
  "dotfiles.sourceImmediately": "always",
  "ssh.remote-prompt": "",
  "telemetry.disabled": true
}                                                                                                                                                                                                                                                                                           
```

**Comment by bgizdov** [comment]
I removed "always" and still not disabled.

**Comment by ceramicwhite** [comment]
Worked for me. Did you run 'fig source' afterwards?

**Comment by amrography** [comment]
@ceramicwhite Now it's showing this prompt

![screenshot 3](https://github.com/withfig/fig/assets/9614340/90c3726c-43b7-4d1b-89cb-9d5921162d95)

I chose `Never for this remote`, then it shows this message after each login

```sh
Warning: remote port forwarding failed for listen path /var/tmp/fig-parent-{xxxx}.socket
```

**Comment by amrography** [comment]
> @ceramicwhite Now it's showing this prompt
> 
> ![screenshot 3](https://user-images.githubusercontent.com/9614340/281061019-90c3726c-43b7-4d1b-89cb-9d5921162d95.png)
> 
> I chose `Never for this remote`, then it shows this message after each login
> 
> ```shell
> Warning: remote port forwarding failed for listen path /var/tmp/fig-parent-{xxxx}.socket
> ```

I commented out the code in `~/.fig/ssh` 

```sh
#Match exec="command -v fig && fig _ generate-ssh %r"
  #Include ~/.fig/ssh_inner
```

It's showing the prompt anymore

**Comment by chazchumley** [comment]
#Match exec="command -v fig && fig _ generate-ssh %r"
  #Include ~/.fig/ssh_inner

This fixes the issue with ssh and git, but bigger questions is why was this even introduced and does anybody test shit.  I just wasted 5 hours this morning trying to figure out why git pull was giving me a port forward error.  Do me a favor developers, test before you deploy.

**Comment by bgizdov** [comment]
I tried `fig source` and it didn't helped few days ago.

Today the menu appeared and I selected "Never for this remote".
I like the feature, but it installs fig on my remote every time even it is already installed,
and that is irritating.

```
user@myserver:~$ curl -fSsL https://fig.io/install-headless.sh | bash; exec $SHELL
███████╗██╗ ██████╗
██╔════╝██║██╔════╝
█████╗  ██║██║  ███╗
██╔══╝  ██║██║   ██║
██║     ██║╚██████╔╝
╚═╝     ╚═╝ ╚═════╝.io
Performing compatibility checks
Executing https://repo.fig.io/scripts/apt/install.sh
[sudo] password for user:
Installing repo dependencies
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
lsb-release is already the newest version (11.1.0ubuntu4).
ca-certificates is already the newest version (20230311ubuntu0.22.04.1).
gnupg is already the newest version (2.2.27-3ubuntu2.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Installing Fig repository
Installing Fig key
Updating apt
Hit:1 http://bg.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://bg.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://bg.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://bg.archive.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://repo.fig.io/apt stable InRelease
Get:6 https://deb.nodesource.com/node_14.x focal InRelease [4583 B]
Hit:7 https://esm.ubuntu.com/apps/ubuntu jammy-apps-security InRelease
Hit:8 https://esm.ubuntu.com/apps/ubuntu jammy-apps-updates InRelease
Hit:9 https://esm.ubuntu.com/infra/ubuntu jammy-infra-security InRelease
Hit:10 https://esm.ubuntu.com/infra/ubuntu jammy-infra-updates InRelease
Fetched 4583 B in 1s (5765 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
Installing Fig
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fig-headless is already the newest version (2.15.0).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Installing integrations
Installing dotfiles integration
Already installed
Installing daemon integration
Installed!
Installing ssh integration
Already installed

✨ Fig has been installed ✨

error: Already logged in as user@gmail.com, please logout first.
user@myserver:~$ exit
```

**Comment by rivasspro** [comment]
`~/.fig/ssh`
```
#Match exec="command -v fig && fig _ generate-ssh %r"
  #Include ~/.fig/ssh_inner
```

This is the solution.!
Perra perdidad de tiempo saber que pasaba con mi repo cuando hacia git fetch. jajaja

**Comment by OscarVanL** [comment]
This is unacceptable. I just SSHed into a production host and fig tried installing some random script off the internet without asking. This is borderline malware behaviour.

**Comment by amrography** [comment]
@OscarVanL I think this might be for their core feature `fig ssh`
![screenshot](https://github.com/withfig/fig/assets/9614340/88e39e27-eeec-4547-bf53-99e36641db3f)

**Comment by OscarVanL** [comment]
> @OscarVanL I think this might be for their core feature `fig ssh`
> 
> ![screenshot](https://github.com/withfig/fig/assets/9614340/88e39e27-eeec-4547-bf53-99e36641db3f)
> 
> 

I never switched this on. In the past it would ask and I would say no, but this time it straight  away started installing to my remote host.

**Comment by stephenjmcmahon** [comment]
> #Match exec="command -v fig && fig _ generate-ssh %r"
>   #Include ~/.fig/ssh_inner

This also worked for me. It is completely unacceptable that it attempts to curl a file on an enterprise server on login.

**Comment by amrography** [comment]
I also found `fig` config included in my ssh config file `~/.ssh/config`

```sh
# Fig ssh integration. Keep at the bottom of this file.
Match all
  Include ~/.fig/ssh
```

I just commented them out

**Comment by adiologydev** [comment]
I think you should keep this open, the prompt never shows.

**Comment by brendanfalk** [comment]
Hi all. Sorry about these issues and this confusion. 

**How do I remove Fig from my remote machine?**
Run `fig uninstall` on the remote machine

**How do I prevent Fig from installing itself on remote machines when I connect to them via SSH?**
1. Run `fig integrations uninstall ssh`
2. Make sure your `~/.ssh/config` no longer contains any reference to Fig such as

> #Match exec="command -v fig && fig _ generate-ssh %r"
> #Include ~/.fig/ssh_inner

or 

> \# Fig ssh integration. Keep at the bottom of this file.
> Match all
>  Include ~/.fig/ssh

3. Make sure your `~/.fig/settings.json` does not contain the following setting `"ssh.remote-prompt": "always"`
