### ISSUE TITLE
AutoComplete is not working on my machine

### ISSUE THREAD

**Issue by felippebutland** [withfig/fig#2798]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.1.0 (23B5067a)

### Expected behaviour

Use fig autocomplete

### Actual behaviour

My fig autocomplete is not working

when i run fig doctor: 
fig doctor
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ bash ~/.bashrc integration check
✔ bash ~/.profile integration check
✔ bash ~/.bash_profile integration check
✔ zsh ~/.zshrc integration check
✔ zsh ~/.zprofile integration check

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ PATH contains ~/.fig/bin
✔ Settings Corruption
✔ State Corruption
✔ Fig Integration
✔ SSH integration

Let's make sure Fig is running...
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Daemon diagnostics

Let's see if Fig is in a working state...
✔ Figterm
✔ Insertion lock does not exist
● autocomplete.developerMode is enabled
✔ Plugin dev mode
✔ Dashboard is loading from the correct URL
✔ Autocomplete is loading from the correct URL

Let's check if your system is compatible...
✔ OS is supported
✔ Fish is up to date
✔ Jetbrains Toolbox Check

Let's check fig diagnostic...
✔ Compatible shell
✔ Fig app installed in the right place
✔ Select an existing issue or create a new one · Create new issue
Heading over to GitHub...

~ took 20.2s
➜ fig doctor
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ bash ~/.bashrc integration check
✔ bash ~/.profile integration check
✔ bash ~/.bash_profile integration check
✔ zsh ~/.zshrc integration check
✔ zsh ~/.zprofile integration check

Let's make sure Fig is setup correctly...
✔ Fig bin exists
✔ PATH contains ~/.local/bin
✔ PATH contains ~/.fig/bin
✔ Settings Corruption
✔ State Corruption
✔ Fig Integration
✔ SSH integration

Let's make sure Fig is running...
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Daemon diagnostics

Let's see if Fig is in a working state...
✔ Figterm
✔ Insertion lock does not exist
● autocomplete.developerMode is enabled
✔ Plugin dev mode
✔ Dashboard is loading from the correct URL
✔ Autocomplete is loading from the correct URL

Let's check if your system is compatible...
✔ OS is supported
✔ Fish is up to date
✔ Jetbrains Toolbox Check

Let's check fig diagnostic...
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled

Let's check your terminal integrations...
✔ Terminal support

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.1.0 (23B5067a)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/felippebutland
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: dd4307de-e522-4c25-bdcf-39f23ba3b8b4
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /opt/homebrew/opt/node@18/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@18/bin:/Users/felippebutland/Library/Android/sdk/platform-tools:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@18/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@18/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@18/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@18/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@14/bin:/Users/felippebutland/.pyenv/shims:/Users/felippebutland/.bun/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@18/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@18/bin:/Users/felippebutland/Library/Android/sdk/platform-tools:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@18/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@18/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@18/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/opt/node@18/bin:/opt/homebrew/opt/node@14/bin:/opt/homebrew/opt/node@14/bin:/Users/felippebutland/.pyenv/shims:/Users/felippebutland/.bun/bin:/Users/felippebutland/.nvm/versions/node/v20.5.0/bin:/opt/homebrew/opt/node@16/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/Users/felippebutland/.fig/bin:/Users/felippebutland/.local/bin:/Users/felippebutland/Library/Application Support/JetBrains/Toolbox/scripts:/Users/felippebutland/Library/Android/sdk/emulator:/Users/felippebutland/Library/Android/sdk/platform-tools:/Users/felippebutland/Library/Android/sdk/emulator:/Users/felippebutland/Library/Android/sdk/platform-tools
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 46031
    - FIG_SET_PARENT: dd4307de-e522-4c25-bdcf-39f23ba3b8b4
```

**Comment by nephix** [comment]
Same for me after upgrading to macOS `14.1`. Worked before on `14.0`

**Comment by grant0417** [comment]
I have deployed a new version of Fig, can you restart and check if it works?

**Comment by nephix** [comment]
Works again on my side, thx

**Comment by nephix** [comment]
Same issue again after updating to macOS `14.1.1`

```
fig-details:
  - 2.17.0-beta.7
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.1.1 (23B81)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/XXXXXXX
  - exe-path: /Users/XXXXXXX/.local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 19665e84-fdbf-4efe-bae9-3f9cfd25228b
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0-beta.7
    - PATH: /Users/XXXXXXX/.fig/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 39845
    - FIG_SET_PARENT: 19665e84-fdbf-4efe-bae9-3f9cfd25228b
```
