### ISSUE TITLE
autocomplete doesnt work

### ISSUE THREAD

**Issue by products-datasparkx** [withfig/fig#2799]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.1.0 (23B5046f)

### Expected behaviour

I expected autocomplete to bring up something when I started with the git command.

### Actual behaviour

nothing happens.

### Steps to reproduce

type git
or 
type cd

nothing happens

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 14.1.0 (23B5046f)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/tonystark
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: com.apple.Terminal
    - TERM: xterm-256color
    - SHELL: /bin/zsh
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/bin:/Users/tonystark/Developer/flutter/bin
```

**Comment by grant0417** [comment]
I have deployed a new version of Fig, can you restart and check if it works?
