### ISSUE TITLE
Integrate Autocomplete with Alacritty Terminal

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#28]
The title says it all.

Please subscribe to this issue to get an update when Fig's autocomplete integration with the Alacritty terminal is ready :smile:

**Comment by mattschrage** [comment]
Important note: Alacritty [does not support tabs](https://github.com/alacritty/alacritty/issues/3129), so all that is required for the integration is some way of determining the cursor position.

**Comment by mschrage** [comment]
Better late than never! Support for Alacritty is coming soon... 🤩

<img width="714" alt="Screen Shot 2021-09-01 at 11 38 25 PM" src="https://user-images.githubusercontent.com/3155109/131794789-062be981-7b3f-4975-81d7-eac7ca7c371a.png">

**Comment by mschrage** [comment]
This is landing in v1.0.49 (coming out in next day or two)!!!

**Comment by Milo123459** [comment]
You guys never fail to amaze! 😌

**Comment by sullivan-sean** [comment]
We had to temporarily remove support for Alacritty due to issues with macOS Monterey. Luckily, we will be supporting it again soon.

Re-opening this for now for anyone who wants to subscribe for when we've re-integrated

**Comment by mschrage** [comment]
A preview of the Alacritty integration is available. However, currently the integration is a bit tricky to setup which is why it is hidden by default.

**Instructions for those who are brave enough to attempt it:**

1. Run `fig settings integrations.experimental true` and then restart the Fig app
2. Click the Fig menubar icon > Integrations > Alacritty > "Attempt to Install"
3. Go to a terminal and run `fig debug ime enable`. A System Preferences window will appear and prompt you to install a third party Input Method.
4. Run `fig debug ime select`
5. Restart Kitty and autocomplete should appear🤞

**Comment by Integralist** [comment]
Thanks @mschrage!

So interestingly, although I got the following error UI...

<img width="252" alt="Screenshot 2022-01-28 at 09 57 28" src="https://user-images.githubusercontent.com/180050/151526663-acf4bc7d-7f9d-4c17-bf56-88f6576a1c0c.png">

It looks like it still worked fine 🤷🏻 

<img width="611" alt="Screenshot 2022-01-28 at 10 06 06" src="https://user-images.githubusercontent.com/180050/151527843-cf8fce2d-6583-432b-ba15-e5dc5a8a2d05.png">

🎉 ❤️

**Comment by Integralist** [comment]
@mschrage I've just got a new MacBook Pro M1 and it seems the instructions above no longer apply 😞 
<img width="1512" alt="Screenshot 2022-04-07 at 23 19 18" src="https://user-images.githubusercontent.com/180050/162328925-6bf55d38-7057-411d-9fa5-0a9cba0a0187.png">

**Comment by mschrage** [comment]
Did you restart Fig @Integralist ?

**Comment by Integralist** [comment]
OK that is working now.

It took...

- Restart (x2, first time didn't indicate any difference, second time it did).
- Install of Alacritty integration plugin (x2, first time failed).
- Allow custom keyboard cursor (x2, first time failed).

**Comment by Integralist** [comment]
Just going to leave another update, which is it seems it's working BUT not when within a tmux shell.

Still debugging and will give an update if I find anything interesting.

**Comment by mschrage** [comment]
@Integralist can you run `fig doctor` and create a separate issue?

**Comment by mschrage** [comment]
Fig now fully supports Alacritty by default!

Run `fig install --input method` and follow the instructions to set it up.

**Comment by laffed** [comment]
`fig install --input-method`

**Comment by chrisgrieser** [comment]
`fig install --input-method` is not working for me. Popup appears, but does not enable completions in alacritty

**Comment by digika-ding** [comment]
> `fig install --input-method` is not working for me. Popup appears, but does not enable completions in alacritty

me too 
OS:  Ventrua 13.0.1
fig: 2.9.0
alacritty: 0.11.0

**Comment by mschrage** [comment]
The new command is `fig integrations install input-method`

**Comment by chrisgrieser** [comment]
> This is a big ask, but have you tried restarting your computer?

not that big an ask, all good!

I also tired restarting afterwards, and nothing changes, still not autocompletion, still nothing that has been added as input method

**Comment by Integralist** [comment]
Not going to open a new issue for this but will say that for the longest time fig has just not worked with Alacritty as far as the 'position' of the autocomplete menu. To be clear: I _do_ get autocomplete but the drop-down is always miles away from the actual prompt on screen (see screenshot below for an example, see if you can find the autocomplete drop-down).

<img width="1920" alt="Screenshot 2022-12-08 at 09 22 21" src="https://user-images.githubusercontent.com/180050/206409050-68acfd66-e1ff-41e3-9daa-4e5811d93a15.png">

**Comment by Integralist** [comment]
Oh, and that position was only from a few days ago. Before that, for the longest time (I honestly couldn't say how long exactly), the drop-down would appear on the far right-side of the screen (mostly top-right).

**Comment by digika-ding** [comment]
> Not going to open a new issue for this but will say that for the longest time fig has just not worked with Alacritty as far as the 'position' of the autocomplete menu. To be clear: I _do_ get autocomplete but the drop-down is always miles away from the actual prompt on screen (see screenshot below for an example, see if you can find the autocomplete drop-down).
> 
> <img alt="Screenshot 2022-12-08 at 09 22 21" width="1920" src="https://user-images.githubusercontent.com/180050/206409050-68acfd66-e1ff-41e3-9daa-4e5811d93a15.png">

@Integralist 
Can you post your fig details?

**Comment by Integralist** [comment]
@digika-ding 

Running `fig doctor` reports no issues, and running `fig diagnostic` reports:

```
fig-details:
  - 2.9.0-beta.5
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.1 (22A400)
environment:
  - shell: /opt/homebrew/Cellar/zsh/5.9/bin/zsh
  - terminal: alacritty
  - cwd: /Users/integralist/Code/test-projects/testing-cli-projects
  - exe-path: /Users/integralist/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.F66qL9mL1l/org.xquartz:0
    - FIGTERM_SESSION_ID: 1424db57-596c-44f6-ad33-6094494ecb2a
    - FIG_HOSTNAME: D3496LK9V7
    - FIG_PID: 13615
    - FIG_SET_PARENT: 1424db57-596c-44f6-ad33-6094494ecb2a
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.9.0-beta.5
    - PATH: /Users/integralist/.yarn/bin:/Users/integralist/.config/yarn/global/node_modules/.bin:/Users/integralist/.goenv/versions/1.18.5/bin:/Users/integralist/.goenv/bin:/Users/integralist/Library/Caches/fnm_multishells/13747_1670491302573/bin:/Users/integralist/bin:/opt/homebrew/opt/ruby/bin:/Users/integralist/.cargo/bin:/Users/integralist/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/integralist/.yarn/bin:/Users/integralist/.config/yarn/global/node_modules/.bin:/Users/integralist/.goenv/shims:/Users/integralist/Library/Caches/fnm_multishells/1241_1669889671084/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/integralist/.fig/bin:/Users/integralist/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/integralist/go/1.18.5/bin
    - SHELL: /opt/homebrew/bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: io.alacritty
```

**Comment by Integralist** [comment]
Well. Looks like I should have asked sooner 🤦🏻  because seeing in the above diagnostics `install-method: unknown` I decided to scroll back up this thread and run `fig integrations install input-method` which then asked me to restart my terminal, and since doing that it appears the autocomplete drop-down is starting to appear where it should be 🎉

**Comment by Integralist** [comment]
Don't get me wrong, it's not "great"...

<img width="722" alt="Screenshot 2022-12-08 at 10 26 01" src="https://user-images.githubusercontent.com/180050/206423239-35358ad0-6967-486b-b2c8-98dfc1d4563b.png">

But it seems to correct itself when you keep typing...

<img width="714" alt="Screenshot 2022-12-08 at 10 26 09" src="https://user-images.githubusercontent.com/180050/206423308-c87fdadf-c99a-4622-b783-a5e8b66d575d.png">

**Comment by digika-ding** [comment]
> > Thank you for your share. What's your alacritty version?
> 
> `0.10.1`
> 
> I can see there is now `0.11.0` so I'm going to bump to that shortly too.

https://github.com/withfig/fig/issues/2126
Maybe It's a bad idea to upgrade alacritty.

**Comment by chrisgrieser** [comment]
@mschrage 
here is the output of `env` from the Alacritty.app and from the binary
[app.txt](https://github.com/withfig/fig/files/10185065/app.txt)
[binary.txt](https://github.com/withfig/fig/files/10185066/binary.txt)
