### ISSUE TITLE
Can't use auto complete to show all of my local branch when I need to checkout other branch

### ISSUE THREAD

**Issue by TofuTseng** [withfig/fig#2801]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.5.0 (21G72)

### Expected behaviour

Can't use auto complete to show all of my local branch when I need to checkout other branch.
Another question is I can't type cd to show the recommend path, is it broken?
Please checkout the video below:

https://github.com/withfig/fig/assets/75705724/2662d5bc-df45-40cc-93ea-bbd88ee1d8cf

### Actual behaviour

Just not showing anything, I need to press Tab to know the path or branch.

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.5.0 (21G72)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/cengfujun/Desktop/commeet-client2
  - exe-path: /Users/cengfujun/.fig/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 90f57bbd-95a0-4549-984b-c79464a9ec65
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/cengfujun/Desktop/google-cloud-sdk/bin:/Users/cengfujun/.nvm/versions/node/v18.14.2/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/cengfujun/.fig/bin:/Users/cengfujun/.local/bin:
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 26911
    - FIG_SET_PARENT: 90f57bbd-95a0-4549-984b-c79464a9ec65
```

**Comment by KaiOelfke** [comment]
I have the same issue.

**Comment by Alchera-MLOps-Tim** [comment]
Me either. I have the same issue with iTerm2 + fish shell

**Comment by binarybamboo** [comment]
Me either. I have the same issue with iTerm2 + fish shell

**Comment by justnewbee** [comment]
It suddenly became a problem for me too..

**Comment by jacobbullock** [comment]
Also having this issue in iTerm.  Just started failing in the last 24 hours

**Comment by dylancl** [comment]
Having the same issue as well.

**Comment by rafaeleduardoteixeira** [comment]
Same issue here.

**Comment by brunoravizzinidev** [comment]
Same problem, since yesterday it no longer offers me local branches when doing git checkout... the branches do not appear. On Mac Sonoma, Fig 2.17

**Comment by grant0417** [comment]
I have deployed a new version of Fig, can you restart and check if it works?

**Comment by rafaeleduardoteixeira** [comment]
It works for me.

**Comment by jacobbullock** [comment]
worked for me. 👏 fast turn around, thanks y'all.

**Comment by TofuTseng** [comment]
Work for me!!!
