### ISSUE TITLE
Autocomplete not working for 'cd'

### ISSUE THREAD

**Issue by DavidHorvath** [withfig/fig#2803]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.0.0 (23A344)

### Expected behaviour

Autocomplete should work when navigating between directories with cd

### Actual behaviour

It worked before, but autocomplete for navigating with cd stopped working.
fig doctor is happy, it has all accesses, open command shows the folders & files but not cd.
Tried to reinstall but still the same

<img width="470" alt="Screenshot 2023-11-07 at 09 24 33" src="https://github.com/withfig/fig/assets/342890/61e871ab-709e-41fb-8949-fd235abd815c">
<img width="412" alt="Screenshot 2023-11-07 at 09 24 51" src="https://github.com/withfig/fig/assets/342890/fa4ade55-6f6f-4d27-8a50-ad93ab8e369d">
<img width="300" alt="Screenshot 2023-11-07 at 09 24 57" src="https://github.com/withfig/fig/assets/342890/01d3a5c4-a1f6-40d5-80bb-d33d5fa9db81">

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/david
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: e0a55c0e-a632-460c-8b6f-e692f29ed262
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /opt/homebrew/opt/openjdk/bin:/Users/david/.rbenv/plugins/ruby-build/bin:/Users/david/.rbenv/shims:/Users/david/.rbenv/bin:/Users/david/Devel/tools/sonar-scanner-4.7.0.2747-macosx/bin:/Users/david/Library/Python/3.8/bin:/opt/apache-maven-3.8.1/bin:/opt/homebrew/bin:/usr/local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/david/.fig/bin:/Users/david/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 1547
    - FIG_SET_PARENT: e0a55c0e-a632-460c-8b6f-e692f29ed262
```

**Comment by ErykKozyra** [comment]
Same problem here, it was working perfectly fine yesterday and I didn't change anything.

**Comment by wiseman71** [comment]
same problem here, after updating iTerm2, Fig doesn't work fine. cd command but also php artisan don't shows commands.

**Comment by metinsut** [comment]
same here

iTerm2 -> Build 3.4.22
Mac -> 14.0 (23A344)
Fig -> 2.17.0

**Comment by chrisponton** [comment]
Same here

**Comment by grant0417** [comment]
Can you try restarting the app?

**Comment by MarcelosWork** [comment]
It's not working here too. I restarted the app and the computer and just don't work using "cd" if I use "open" it works.

**Comment by MuhammedBuyukkinaci** [comment]
Having the same issue. It was working last week but stopped on Terminal.

My computer is Mac M1 Pro. Mac OS Ventura version is 13.5 (22G74).

It isn't specific to cd command. It is also not working for git commands.

**Comment by GBrachetta** [comment]
Same here since yesterday.
Not related to the update of iTerm2, since the same behaviour occurs in terminall.app.

**Comment by DavidHorvath** [comment]
@grant0417 
> Can you try restarting the app?

Restarted and reinstalled it multiple times. Also tried to clear the cache in ~/Library and deleted Fig directory in Application Support. Nothing helped

**Comment by szaflarskim** [comment]
Same here, autocomplete for `cd` worked fine yesterday and stopped tooday. `fig doctor` finds no issues. I tried reinstalling it multiple times. I also noticed running `fig run` does not show my scripts anymore.

**Comment by marco238** [comment]
Same here. Also failing with other commands like `git checkout ...` which should suggest branches

**Comment by grant0417** [comment]
I have deployed a new version of Fig, can you restart and check if it works?

**Comment by DavidHorvath** [comment]
@grant0417 Thanks, it's working now! 🚀

**Comment by vietstone-ng** [comment]
Hi, I'm facing this issue. I tried restarting, even reinstalling. Fig doctor shows everything ok.

**Comment by linahello** [comment]
Hi there ! 

Everything was working yesterday and the autocomplete is now not working at all on any command. 

I've restarted multiple times, updates but nothing. 
I'm on MacBook Air M1, Sonoma 14.1, iTerm2. 

Does someone have the issue again and know how to fix it? 

Thank you!
