### ISSUE TITLE
Autocomplete not working for cd and package.json scripts

### ISSUE THREAD

**Issue by ErykKozyra** [withfig/fig#2805]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.0.0 (23A344)

### Expected behaviour

Suggestions for commands like cd or package.json scripts should work like before.

### Actual behaviour

For some reason autocompletion stopped working as it should,
![image](https://github.com/withfig/fig/assets/57717933/b38fc319-aad1-4d37-9bb0-47f949db3e32)
![image](https://github.com/withfig/fig/assets/57717933/e4cf7256-277c-432a-ad0f-661489a39d11)

It is still working for open command:
![image](https://github.com/withfig/fig/assets/57717933/ec2a004e-1652-46cd-8dc3-57c7515cb7e6)

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Applications/Moje/xxx/xxx-components
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 8909ac15-ca9f-474a-b182-77a0eedbf8d3
    - FIG_PID: 3330
    - FIG_SET_PARENT: 8909ac15-ca9f-474a-b182-77a0eedbf8d3
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/erykkozyra/.pyenv/shims:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/erykkozyra/Library/pnpm:/Users/erykkozyra/.pyenv/shims:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/erykkozyra/.fig/bin:/Users/erykkozyra/.local/bin:/Users/erykkozyra/Library/Android/sdk/emulator:/Users/erykkozyra/Library/Android/sdk/tools:/Users/erykkozyra/Library/Android/sdk/tools/bin:/Users/erykkozyra/Library/Android/sdk/platform-tools:/Users/erykkozyra/Library/Android/sdk/emulator:/Users/erykkozyra/Library/Android/sdk/tools:/Users/erykkozyra/Library/Android/sdk/tools/bin:/Users/erykkozyra/Library/Android/sdk/platform-tools
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/erykkozyra
    - __CFBundleIdentifier: com.microsoft.VSCode
```

**Comment by alex93133** [comment]
same problem

**Comment by angeltonio** [comment]
the same here

**Comment by hugoewarrior** [comment]
Same here

**Comment by YiweiShen** [comment]
Same here. Clean install fig again fixed the issue.

**Comment by angeltonio** [comment]
> Same here. Clean install fig again fixed the issue.

I did that, but the problem continues

**Comment by SO-Eng** [comment]
Same here.
Complete reinstall tried, did not fix!
TBH I only check with 'cd', I thought complete fig is broken. First I read here, checked that only 'cd' is not working.

diagnostics:
fig-details:
  - 2.17.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /opt/homebrew/Cellar/bash/5.1.16/bin/bash
  - terminal: iterm
  - cwd: /Users/softwort
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /opt/homebrew/bin/bash
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: 3028fc0d-e11b-40ec-a864-18dba9b9f45e
    - FIG_TERM: 2.17.0
    - TERM: xterm-256color
    - FIG_PID: 9281

**Comment by grant0417** [comment]
Can you try restarting the app?

**Comment by angeltonio** [comment]
> Can you try restarting the app?

yes, but the same result

**Comment by YiweiShen** [comment]
> > Same here. Clean install fig again fixed the issue.
> 
> I did that, but the problem continues

What I did is using AppCleaner to uninstall and delete all fig related files. And then `brew reinstall fig`

It is working again so far.

**Comment by jasselmar** [comment]
What worked for me:

1. Delete the app
2. Redownload (didn't work with brew https://fig.io/download)
3. Log out -> Log in
4. run fig restart -> fig source

**Comment by natuan62** [comment]
@jasselmar it still not working for me

![image](https://github.com/withfig/fig/assets/10808157/435730ac-9a61-4f49-8304-42bd5dae898d)

**Comment by tamasfabi** [comment]
> What worked for me:
> 
> 1. Delete the app
> 2. Redownload (didn't work with brew https://fig.io/download)
> 3. Log out -> Log in
> 4. run fig restart -> fig source

this worked for me - but only had to do step 1 and 2.

**Comment by smg-kayle** [comment]
I had the same problem and `fig doctor` command gave me this
<img width="646" alt="image" src="https://github.com/withfig/fig/assets/98294270/f59e4805-12ba-49f5-9ec1-3280f276a1ff">

**Comment by tomchkk** [comment]
@smg-kayle I had the same and fixed it with `fig integrations install daemon` - though this hasn't fixed the autocompletion problems.

**Comment by angeltonio** [comment]
What worked for me:
1.- Reinstall app, using brew too
2. Log out, and Log in again

Maybe it´s only needed Log Out

**Comment by tomchkk** [comment]
I've tried a number of iterations of reinstalling, logging in and out. Still doesn't work.

**Comment by DavidHorvath** [comment]
Same problem, reinstall, logging in and out didn't help

**Comment by szaflarskim** [comment]
Same problem. Tried logout, login, reinstall with brew and dmg. 
`cd` doesn't show autocomplete-window, neither `npm run` or `fig run` finds the scripts.

**Comment by ErykKozyra** [comment]
Still nothing helps...

**Comment by ErykKozyra** [comment]
@mschrage @brendanfalk @fig-io @grant0417 @chaynabors 
Any info on a fix? It looks like a global problem, there are a lot of new issues about autocomplete in these 2 days.

**Comment by SO-Eng** [comment]
Update: It is not only 'cd' not working, also 'nx' commands are not suggested.
So I use nrwl NX in my coding projects, to start a project you use 'nx serve <project-name>' normally FIG does know keyword 'serve' and all projects are correct suggested. But this also does not working anymore.

**Comment by chaynabors** [comment]
There was a security vulnerability which we resolved that changed the way we handle some specs. I would reinstall since that seems to help others while we determine what's wrong besides. Ping me if a clean reinstall doesn't work for you.

**Comment by GBrachetta** [comment]
@chaynabors A clean reinstall didn't solve the issue.
What to do? Wait for an update and `fig update` it?

**Comment by chaynabors** [comment]
Did you run 'fig uninstall'? Double check 'fig doctor' output for me if you did just to make sure daemon is working. (Shouldn't matter much)

**Comment by szaflarskim** [comment]
> There was a security vulnerability which we resolved that changed the way we handle some specs. I would reinstall since that seems to help others while we determine what's wrong besides. Ping me if a clean reinstall doesn't work for you.

@chaynabors Tried uninstalling with cli and manually as per instructions on https://fig.io/user-manual/other/uninstall
Tried reinstalling with brew and tried re-installing with the downloaded dmg. Also tried deleting `~/Library/Caches/fig`
That didn't fix the problem.
I've noticed fig was logged in after re-installation if I didn't logout before uninstalling it. Is there some other location where fig stores some data?

**Comment by GBrachetta** [comment]
I didn't `fig uninstall` it. Honestly I'm not sure the impact that would have in all my created completions, dotfiles, and tweaking I've done over the last months.
I wouldn't want to start setting it all up from scratch...

**Comment by DavidHorvath** [comment]
@chaynabors uninstall didn't solve it. Doesn't matter if I re-install it with brew or from dmg. fig doctor output shows everything is good
<img width="422" alt="Screenshot 2023-11-08 at 17 26 10" src="https://github.com/withfig/fig/assets/342890/bd18912b-880b-4e0b-9937-670fdbe690ff">

@szaflarskim Library/ApplicationSupport/fig

**Comment by szaflarskim** [comment]
Thanks @DavidHorvath. Tried removing `Library/ApplicationSupport/fig` as well and reinstall again, still no difference
![image](https://github.com/withfig/fig/assets/22325359/077b9687-fdd9-4083-9b62-500f8700dcd3)

**Comment by GBrachetta** [comment]
There you go

![Screenshot 2023-11-08 at 18 11 05](https://github.com/withfig/fig/assets/57924268/00d50c8d-7162-4871-be30-dd0d712feb05)

**Comment by grant0417** [comment]
Did you make sure to restart first before opening the console?

**Comment by rubentemmerman** [comment]
This is my output:
<img width="1200" alt="Screenshot 2023-11-08 at 18 29 51" src="https://github.com/withfig/fig/assets/3438485/30b98fca-186e-4bd5-a3cd-6972e5d5e581">

**Comment by GBrachetta** [comment]
@grant0417 Maybe more interesting, with the devtools console open, this is what happens when I type `cd `.
The error pops up right when I type the space after `cd`

![Screenshot 2023-11-08 at 18 30 36](https://github.com/withfig/fig/assets/57924268/02ef9123-55c1-4e13-8165-f5aaa2e070ce)

**Comment by grant0417** [comment]
Okay, I deployed a new version, can you restart and see if there is any change?

**Comment by GBrachetta** [comment]
Yes, that's it. Seems to be working again!

Thank you!

**Comment by rubentemmerman** [comment]
After fig restart autocomplete works. Thanks!

**Comment by lpolon** [comment]
Hey. I have the same issues. I follow the thread along. My fig is up-to-date and I restarted it.
I run `fig debug dev tools autocomplete` and When I type: `yarn`, I expect to get autocomplete of my scripts:


![Screenshot 2023-11-10 at 15 54 54](https://github.com/withfig/fig/assets/14023054/866daf16-3d80-4052-86eb-1bd0df15607f)
