### ISSUE TITLE
autocomplete working incorrectly

### ISSUE THREAD

**Issue by AliSheyx-life** [withfig/fig#2806]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

path autocomplete is not working
incorrect autocomplete for all git commands

### Actual behaviour

path autocomplete is not working
incorrect autocomplete for all git commands

![Снимок экрана 2023-11-07 в 15 44 23](https://github.com/withfig/fig/assets/68541818/16604d47-3cfd-4acd-96e8-5908ad4a01f1)
![Снимок экрана 2023-11-07 в 15 44 32](https://github.com/withfig/fig/assets/68541818/93e90894-a93a-42fb-950b-7a24ed14f3b8)
![Снимок экрана 2023-11-07 в 15 44 43](https://github.com/withfig/fig/assets/68541818/7d46f4e8-e144-4631-a961-523808d5abcb)

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/alsiheyx/Documents/TENGE_MARKET/halyk-market-web
  - exe-path: /Users/alsiheyx/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: d972f938-68f3-4488-8aec-786dad5de6bf
    - FIG_PID: 6247
    - FIG_SET_PARENT: d972f938-68f3-4488-8aec-786dad5de6bf
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alsiheyx/.fig/bin:/Users/alsiheyx/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/alsiheyx
    - __CFBundleIdentifier: com.microsoft.VSCode
```

**Comment by grant0417** [comment]
Can you try restarting the app?

**Comment by Hwangseungwoo** [comment]
Same for me.

**Comment by grant0417** [comment]
I have deployed a new version of Fig, can you restart and check if it works?
