### ISSUE TITLE
Autocomplete for directory list not working on MacOS Ventura

### ISSUE THREAD

**Issue by andrewchandra-tiket** [withfig/fig#2811]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.6.1 (22G313)

### Expected behaviour

Fig able to give autocomplete of directory list when use command `cd`

### Actual behaviour

Fig able to give no autocomplete of directory list when use command `cd`, but it can give autocomplete for other command such as `fig` -> `fig doctor` or `fig restart`

### Steps to reproduce

1. Open terminal, type `cd`
2. Type some character of directory name
3. No autocompelete shown for directory list

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 13.6.1 (22G313)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/andrewchandra
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 9d1d13f2-ba49-4b49-a187-0cbb736c9fcf
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/andrewchandra/.rbenv/shims:/Users/andrewchandra/.fastlane/bin:/usr/local/opt/ruby/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/andrewchandra/.fig/bin:/Users/andrewchandra/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 25326
    - FIG_SET_PARENT: 9d1d13f2-ba49-4b49-a187-0cbb736c9fcf
```

**Comment by tungamiraimujuru** [comment]
Also experiencing the same behaviour. 

fig-details:
  - 2.17.0-beta.7
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: bad623a7-a29b-476e-acf5-57f02e4c1d57
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0-beta.7
    - PATH: /opt/homebrew/opt/openjdk@11/bin:/opt/homebrew/bin:/Users/gmujuru/Library/Android/sdk/platform-tools:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/gmujuru/.fig/bin:/Users/gmujuru/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 3581
    - FIG_SET_PARENT: bad623a7-a29b-476e-acf5-57f02e4c1d57

**Comment by grant0417** [comment]
I have deployed a new version of Fig, can you restart and check if it works?

**Comment by andrewchandra-tiket** [comment]
It works now
Thank you @grant0417
