### ISSUE TITLE
Git checkout doesn't show the branches

### ISSUE THREAD

**Issue by anhnamjr** [withfig/fig#2813]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.1.0 (23B74)

### Expected behaviour

When I command `git checkout`. I'd like to have all the branches of the repository like before.

### Actual behaviour

When I command `git checkout`. Instead of showing all the valid branches of the repository, it's showing the files of the repository. 
Here is my image
<img width="463" alt="image" src="https://github.com/withfig/fig/assets/57998176/9d679a1d-bd24-4610-85d9-84ff202bdf93">

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.1.0 (23B74)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/nguyenanhnam/Projects/sendo/farm-gamification
  - exe-path: /Users/nguyenanhnam/.fig/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 901e3064-d870-4916-98ef-39c5a2214acb
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/nguyenanhnam/.bun/bin:/opt/homebrew/opt/go@1.20/bin:/opt/homebrew/opt/libpq/bin:/Users/nguyenanhnam/.yarn/bin:/Users/nguyenanhnam/.config/yarn/global/node_modules/.bin:/Users/nguyenanhnam/.nvm/versions/node/v16.14.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/go/bin:/Users/nguyenanhnam/.fig/bin:/Users/nguyenanhnam/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 3151
    - FIG_SET_PARENT: 901e3064-d870-4916-98ef-39c5a2214acb
```

**Comment by grant0417** [comment]
I have deployed a new version of Fig, can you restart and check if it works?
