### ISSUE TITLE
Deamon is not running - socket doesnt exist

### ISSUE THREAD

**Issue by chess1** [withfig/fig#2814]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.1.0 (23B74)

### Expected behaviour

fig would run properly and show suggestions contextually.

### Actual behaviour

suggestions are not displayed.

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 14.1.0 (23B74)
environment:
  - shell: /opt/homebrew/Cellar/zsh/5.9/bin/zsh
  - terminal: vscode
  - cwd: /Users/idora/WebstormProjects/...
  - exe-path: /Users/idora/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: b5615ccd-a478-440a-9429-df4b15a79284
    - FIG_PID: 2953
    - FIG_SET_PARENT: b5615ccd-a478-440a-9429-df4b15a79284
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /usr/local/share/npm/bin:/Users/idora/Library/Python/3.9/bin:/Users/idora/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/go/bin:/usr/local/share/npm/bin:/Users/idora/Library/Python/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/idora/.fig/bin:/Users/idora/.local/bin:/Users/idora/.oh-my-zsh/custom/plugins/fzf-zsh-plugin/bin:/Users/idora/.fzf/bin:/Users/idora/.oh-my-zsh/custom/plugins/fzf-zsh-plugin/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/idora
    - __CFBundleIdentifier: com.microsoft.VSCode
```

**Comment by chrisponton** [comment]
I did the following commands to resolve my daemon issue but as per other issues it's still broken with a clean `fig doctor`.

`fig integrations install daemon`
`fig integrations status daemon`

**Comment by chess1** [comment]
> I did the following commands to resolve my daemon issue but as per other issues it's still broken with a clean `fig doctor`.
> 
> `fig integrations install daemon` `fig integrations status daemon`

unfortunately didn't help me, still having the same issue.

**Comment by cxen** [comment]
> > I did the following commands to resolve my daemon issue but as per other issues it's still broken with a clean `fig doctor`.
> > `fig integrations install daemon` `fig integrations status daemon`
> 
> Thanks! Unfortunately didn't help me, still having the same issue.

The following worked for me:

Completely exit the Fig Dashboard
Run `fig integrations uninstall daemon`
Run `fig integrations install daemon`
Restart terminal and Fig Dashboard
Check with `fig doctor`
