### ISSUE TITLE
Fig stops showing paths/branches/package.json commands

### ISSUE THREAD

**Issue by volo4dev** [withfig/fig#2815]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.0.0 (23A344)

### Expected behaviour

Fig shows the paths according to the commands
f.e. commands from package.json, branches, etc... 

### Actual behaviour

Fig does not show the paths and commands in terminal

### Steps to reproduce

1. Open the terminal
2. Write the commands
3. git push origin development <-- Fig does not show branch name
4. npm run start <-- Fig does not see commands in package.json file

https://github.com/withfig/fig/assets/98762181/40c79d6a-b951-4983-a372-962a9973a9dd

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /bin/zsh
  - terminal: intellij-webstorm
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 6e547a3c-eb42-4916-a9de-c9b96865d8b4
    - FIG_JETBRAINS_SHELL_INTEGRATION: 1
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.WebStorm
    - FIG_PID: 14996
    - FIG_SET_PARENT: 6e547a3c-eb42-4916-a9de-c9b96865d8b4
```

**Comment by turkhero** [comment]
I am experiencing the same issue on macOS Sonoma (14)

**Comment by volo4dev** [comment]
@turkhero Everything was working fine yesterday, no problems. But today - no... I haven't changed anything and I don't understand what happened.

**Comment by galzo** [comment]
Same here. fig suddenly stopped showing autocomplete for finder folders and git branches (Mac OS Sonoma)

**Comment by rutbergphilip** [comment]
Same issue for me, out of nowhere stopped working a couple of days ago.

**Comment by Abhishek765Flyfin** [comment]
same, facing issue with yarn working fine with npm ??

![image](https://github.com/withfig/fig/assets/88670079/76738351-c7b3-4de0-b450-d785e488e3ff)

![image](https://github.com/withfig/fig/assets/88670079/6ac2b7b2-7098-442c-9bea-64e9523a6d2d)

**Comment by grant0417** [comment]
I have deployed a new version of Fig, can you restart and check if it works?

**Comment by arishoham** [comment]
Works for me now with a `fig restart` thanks for fixing so quick!

**Comment by volo4dev** [comment]
@grant0417 works fine, thank you!

**Comment by turkhero** [comment]
Thanks
