### ISSUE TITLE
Cannot install fig. "Something went wrong. Signups are currently disabled."

### ISSUE THREAD

**Issue by falkolav** [withfig/fig#2816]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.5.0 (22G74)

### Expected behaviour

I was not able to complete installation of fig.

### Actual behaviour

<img width="1030" alt="image" src="https://github.com/withfig/fig/assets/47246161/568fcd68-5517-44ab-ae01-c4354aba9edb">

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Pro
  - cores: 12
  - mem: 32.00 GB
os-info:
  - macOS 13.5.0 (22G74)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/falkolavitt
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: com.apple.Terminal
    - TERM: xterm-256color
    - SHELL: /bin/zsh
    - PATH: /Users/falkolavitt/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
```

**Comment by Damecek** [comment]
same issue, both Email and GitHub login does not work. M2 Sonoma

**Comment by Damecek** [comment]
14.1 (23B74)

**Comment by grant0417** [comment]
See #2706
