### ISSUE TITLE
Fig is not working. It didn't give any suggestion

### ISSUE THREAD

**Issue by amitsingh44** [withfig/fig#2819]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.0.0 (23A344)

### Expected behaviour

Fig is not working. It didn't give any suggestion

### Actual behaviour

<img width="1546" alt="Screenshot 2023-11-09 at 12 42 27 PM" src="https://github.com/withfig/fig/assets/110447736/bebc2c85-ba91-40bd-916a-40dfe6cd9f3e">

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/amitsingh/Desktop/simplyjet-backend
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: bdc410b4-2a60-4485-9a4b-eaf729e47643
    - FIG_PID: 4441
    - FIG_SET_PARENT: bdc410b4-2a60-4485-9a4b-eaf729e47643
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/amitsingh/.bun/bin:/usr/local/opt/libpq/bin:/Users/amitsingh/.pyenv/shims:/Users/amitsingh/.nvm/versions/node/v19.1.0/bin:/Users/amitsingh/go/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/amitsingh/.bun/bin:/usr/local/opt/libpq/bin:/Users/amitsingh/.nvm/versions/node/v19.1.0/bin:/Users/amitsingh/go/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/amitsingh/.fig/bin:/Users/amitsingh/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/amitsingh
    - __CFBundleIdentifier: com.microsoft.VSCode
```

**Comment by brandonjcg** [comment]
I have the same problem, fig is updated and I've Mac 14.2

**Comment by jrosalesmeza** [comment]
I have the same problem, however I have Mac 13.1

**Comment by galzo** [comment]
same here. a few days ago fig stopped providing autocomplete for folders/git/commands
now it doesn't provide autocomplete for anything
i already tried `fig restart` and `fig doctor`, but nothing helps. it won't show autocomplete anymore at all

Mac OS 14.2, Macbook Pro M1

**Comment by DynamiteGoesBoom** [comment]
So I'm not going crazy nor am I the only one with this issue :)

**Comment by ZKuroeSamaZ** [comment]
same here

**Comment by michaeltroya** [comment]
Same issue here M1 Mac mini on MacOS 13.0

**Comment by BenSheridanEdwards** [comment]
Happening for me too, tried `fig restart` and `fig doctor`

**Comment by karol-f** [comment]
Same here but `fig restart` helped

**Comment by amitsingh44** [comment]
I just restarted my Mac and reinstalled Fig; now it's working for me.
