### ISSUE TITLE
Fig does not work with tilde

### ISSUE THREAD

**Issue by VityaSchel** [withfig/fig#2821]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.5.0 (22G74)

### Expected behaviour

When typing ~/ it should point to /Users/hloth (hloth is currently logged user's username in macOS)

### Actual behaviour

<img width="392" alt="image" src="https://github.com/withfig/fig/assets/59040542/5e6c6a55-eff8-4369-958c-2c22fbdfd634">

### Steps to reproduce

I restarted fig multiple times, gave it full access to disk, but it still points to current directory when using tilde. Other paths such as ../ work fine

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 13.5.0 (22G74)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/hloth/Documents/Freelance Projects/x5.io/admin-panel
  - exe-path: /Users/hloth/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 0edd864c-71bb-42c0-9074-dfd2b607acd2
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/hloth/Library/pnpm:/Users/hloth/.nvm/versions/node/v18.17.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/hloth/.fig/bin:/Users/hloth/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 18809
    - FIG_SET_PARENT: 0edd864c-71bb-42c0-9074-dfd2b607acd2
```

**Comment by mschrage** [comment]
We modified how commands are executed in the background and this was a regression. However, it should be resolved now.
