### ISSUE TITLE
Add autocomplete to local tool without dev mode

### ISSUE THREAD

**Issue by gavrilikhin-d** [withfig/fig#2836]
### Discussed in https://github.com/orgs/withfig/discussions/2723

<div type='discussions-op-text'>

<sup>Originally posted by **gavrilikhin-d** September 10, 2023</sup>
Is it possible to add/override autocomplete to local tool without downloading fig sources and running it in dev mode?</div>

**Comment by mschrage** [comment]
Yes, see this guide on building for an [internal CLI tool](https://fig.io/docs/guides/autocomplete-for-internal-tools)
