### ISSUE TITLE
bug: High CPU and memory usage

### ISSUE THREAD

**Issue by tchcxp** [withfig/fig#2837]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Mac OS 14.1.1 

### Expected behaviour

Fig uses reasonable system resources when it's running.

### Actual behaviour

Fig consumes a lot more CPU and memory than expected.

<img width="502" alt="image" src="https://github.com/withfig/fig/assets/5209926/bac4f098-b81d-4f4c-9f9b-e27b0c9c40da">

<img width="654" alt="image" src="https://github.com/withfig/fig/assets/5209926/b4db4886-ac3c-4dbe-8679-c396ad69c140">

### Environment

```yaml
❯ fig diagnostic

fig-details:
  - 2.17.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M2 Pro
  - cores: 12
  - mem: 32.00 GB
os-info:
  - macOS 14.1.1 (23B81)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/ch
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 5476a482-0899-415f-adfd-fa43a9b01aaa
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/ch/.nvm/versions/node/v18.15.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/ch/.fig/bin:/Users/ch/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 31230
    - FIG_SET_PARENT: 5476a482-0899-415f-adfd-fa43a9b01aaa
```
```

**Comment by igr** [comment]
See https://github.com/withfig/fig/issues/2577 for non-solution. Fig developers are not able to fix this issue for some time now.

**Comment by chaynabors** [comment]
Closing in favor of https://github.com/withfig/fig/issues/2577
