### ISSUE TITLE
Daemon diagnostics: Daemon socket exists but could not connect

### ISSUE THREAD

**Issue by sivajayaraman** [withfig/fig#2841]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.0.0 (23A344)

### Expected behaviour

Wanted to load Fig, But it showed login restricted. So, ran fig doctor . It showed few issues which I fixed and there are few which I could not fix.  Accessibility is actually enabled, but it shows it is disabled.

### Actual behaviour

✘ Daemon: Daemon is not running
✘ Daemon diagnostics: Daemon socket exists but could not connect
.
.
.
✘ Accessibility enabled: Accessibility is disabled

### Steps to reproduce

1. Install fig.
2. Run fig login
3. Run fig doctor

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.0.0 (23A344)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/siva-10348
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.k4f59Aydx4/org.xquartz:0
    - FIGTERM_SESSION_ID: 3a196207-5e3e-4442-9a78-92f6ed18d0fc
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/siva-10348/.cargo/bin:/Users/siva-10348/.fig/bin:/Users/siva-10348/.local/bin:/Application/Postgres.app/Contents/Versions/9.5/bin:/Applications/Postgres.app/Contents/Versions/9.5/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 58623
    - FIG_SET_PARENT: 3a196207-5e3e-4442-9a78-92f6ed18d0fc
```

**Comment by mschrage** [comment]
We've closed sign ups for new users, so if you're unable to login - that is likely the underlying issue.
