### ISSUE TITLE
fig ai failed with status code 429 (status: 500 Internal Server Error, error_id: bb1a972b21b9483b903ec071294fbfd3)

### ISSUE THREAD

**Issue by Sang-it** [withfig/fig#2842]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.7.1 (21G920)

### Expected behaviour

fig ai should run.

### Actual behaviour

fig ai doesn't run.
<img width="1243" alt="Screen Shot 2023-11-30 at 3 29 50 PM" src="https://github.com/withfig/fig/assets/79345518/5662e7a8-1d48-4bec-9117-f5e23cbf2e55">

### Steps to reproduce

- just run fig ai on anything

**Comment by mschrage** [comment]
Thanks for reporting! This issue should be resolved.

**Comment by victornitu** [comment]
Hi @mschrage,

Unfortunately, I have been having the same issue for a  few days now, here is one example:
```zsh
➜ fig ai

Translate Text to Bash

  Text · list files
error: failed to generate suggestions: Request failed with status code 429 (status: 500 Internal Server Error, error_id: ade912bc1e9d4ff98c7d26cf229317ec)
```
I'm on macOS 14.1.2 (23B92), M1 chip
I have `fig: 2.17.0`

Thanks for the help
