### ISSUE TITLE
Not working even though fig doctor checks all boxes

### ISSUE THREAD

**Issue by robertoshimizu** [withfig/fig#2844]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.1.0 (23B2073)

### Expected behaviour

Snippets showing in my terminal when typing commands.
Fig Dashboard opening normally.

### Actual behaviour

Snippets not showing in my terminal when typing commands.
Fig Dashboard opens but stays with a blank screen.

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M3 Max
  - cores: 14
  - mem: 36.00 GB
os-info:
  - macOS 14.1.0 (23B2073)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/robertoshimizu
  - exe-path: /Users/robertoshimizu/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 45a7cd8b-94f3-4cfa-b27f-241cc191e9a4
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /opt/homebrew/opt/openjdk/bin:/Users/robertoshimizu/.nvm/versions/node/v20.10.0/bin:/Users/robertoshimizu/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/robertoshimizu/.fig/bin:/Users/robertoshimizu/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 1072
    - FIG_SET_PARENT: 45a7cd8b-94f3-4cfa-b27f-241cc191e9a4
```

**Comment by mschrage** [comment]
This sounds like an internet connectivity issue. If you run `fig restart` does this resolve the issue?

**Comment by hedenica** [comment]
> This sounds like an internet connectivity issue. If you run `fig restart` does this resolve the issue?

This solved my issue, thanks :)
