### ISSUE TITLE
Not able to login with existing account

### ISSUE THREAD

**Issue by vishal-roy** [withfig/fig#2857]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS Sonoma

### Expected behaviour

With Sign In with email, I should be able to login with my existing account.

### Actual behaviour

- When I try logging in with fig dashboard, it gets stuck at sending login link.
- When I try with fig cli, this is the error message I get `Failed to initiate auth: DefineAuthChallenge invocation failed due to error AccessDeniedException.: Failed to initiate auth: DefineAuthChallenge invocation failed due to error AccessDeniedException.. Sentry ID: bf587cdb456146bfa13a7c89a014dfd5.`

### Steps to reproduce

1. Signout of fig.
2. Reinstall fig.
3. Try logging in using email as the option.

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M2 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.2.0 (23C64)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/zoro/area51
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /bin/zsh
    - __CFBundleIdentifier: com.googlecode.iterm2
    - PATH: /Users/zoro/Library/pnpm:/Users/zoro/.pyenv/shims:/Users/zoro/.nvm/versions/node/v20.8.0/bin:/opt/homebrew/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/zoro/.cargo/bin:/Users/zoro/.orbstack/bin
    - TERM: xterm-256color
```

**Comment by ptg251294** [comment]
+1. I too am facing this exact problem

**Comment by donydonald1** [comment]
facing the same problem too

`Please check your email for the code
error: Failed to initiate auth: DefineAuthChallenge invocation failed due to error AccessDeniedException.: Failed to initiate auth: DefineAuthChallenge invocation failed due to error AccessDeniedException. (status: 500 Internal Server Error, error_id: d304324311314e8286f8bf1bc6030507)`

**Comment by AndreyKovanov** [comment]
same issue
`
Failed to initiate auth: DefineAuthChallenge invocation failed due to error AccessDeniedException.: Failed to initiate auth: DefineAuthChallenge invocation failed due to error AccessDeniedException. (status: 500 Internal Server Error, error_id: 88287254272f4c91817515db4aa05220)
`

**Comment by mschrage** [comment]
Hi @vishal-roy @AndreyKovanov @ptg251294  @donydonald1! Thanks for reporting this. We've resolved the underlying issue.
