### ISSUE TITLE
Possible to remove the fig from Linux 

### ISSUE THREAD

**Issue by xushijie** [withfig/fig#2863]
IN my ubuntu, I installed fig using script: `install-headless.sh`, but no surprised, it shows "error: Signups are currently disabled (status: 400 Bad Request)" when I register using my github account. So I would like to have a try after registration is open again. 
So is it possible to uninstall it? Or can i just remove the /usr/bin/fig directly?

**Comment by Ananyapam7** [comment]
I have the same question

**Comment by mschrage** [comment]
Try running `fig uninstall`
