### ISSUE TITLE
bug: code whisper does not work with just (fig works ok)

### ISSUE THREAD

**Issue by igr** [withfig/fig#2864]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

osx

### Expected behaviour

automcomplete just receipts

### Actual behaviour

nothing

**Comment by mschrage** [comment]
Hi @igr! Can you elaborate on this?

**Comment by igr** [comment]
Working scenario using `fig`:

I have a project and a `justfile` in it. When I type `just`, the autocomplete popup appears so I can choose a receipt to run.

Not working: `code whisper`

When I go to the very same project (or any other), and type `just`, the popup appears for a brief moment and then disappears. It is replaced with moving dots (like it is loading or something like that). I cannot use autocomplete on `ustfiles

**Comment by mschrage** [comment]
Hmm this is interesting. Would you mind opening an issue [here](https://github.com/aws/codewhisperer-command-line-discussions/discussions/categories/bug-report).
