### ISSUE TITLE
We're rolling out a closed alpha/prototype of Fig on Windows to a few users in the next week or so -- if you're on Windows and interested in getting early access, fill out the typeform here: https://withfig.typeform.com/to/n58Z7ciy

### ISSUE THREAD

**Issue by 10of10wouldban** [withfig/fig#2865]
We're rolling out a closed alpha/prototype of Fig on Windows to a few users in the next week or so -- if you're on Windows and interested in getting early access, fill out the typeform here: https://withfig.typeform.com/to/n58Z7ciy

_Originally posted by @sullivan-sean in https://github.com/withfig/fig/issues/35#issuecomment-1169400805_
            

Is there any possibility that you need more alpha testers for windows & linux?

**Comment by Suhaybu** [comment]
I don't know how to report this but isn't this OP blatantly advertising with a throwaway account? The link doesn't seem to have to do anything Fig

**Comment by mschrage** [comment]
We conducted a limited beta testing Fig autocomplete support on Windows/Linux. Stay tuned for updated from Amazon CodeWhisperer about this. 👀
