### ISSUE TITLE
bug: It isn't letting me sign in to my account

### ISSUE THREAD

**Issue by aidan-gibson** [withfig/fig#2868]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS

### Expected behaviour

Site will not let me log in to authenticate.

### Actual behaviour

My email with fig is tronicdude@gmail.com
It hangs on "Signing in..." when I try to log in to https://app.fig.io/login

**Comment by mschrage** [comment]
This issue should be resolved.
