### ISSUE TITLE
Bitwarden triggers Secure Keyboard Input

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#287]
Provide warning to user in debugger that quitting Bitwarden might solve the issue. (Check if the app is installed and running first.)

**Comment by mschrage** [comment]
Possibly related issue on Bitwarden's end: https://github.com/bitwarden/desktop/issues/991

**Comment by fwesss** [comment]
Added check for this in `fig tools doctor`

Bitwarden release 1.28.2 fixes this issue entirely.

**Comment by ShikiSuen** [comment]
Now this BitWarden issue comes again with Safari 17.
https://github.com/bitwarden/clients/issues/6646
