### ISSUE TITLE
Not working on Termius Terminal

### ISSUE THREAD

**Issue by rayaanr** [withfig/fig#2872]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.2.1 (23C71)

### Expected behaviour

Working on Termius Terminal

### Actual behaviour

Let's check your terminal integrations...
✘ Terminal support: Unsupported terminal, if you believe this is a mistake or would like to see support for your terminal, run `fig issue`

  __CFBundleIdentifier: com.termius-dmg.mac

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: <unknown>
  - cwd: /Users/rayaan
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 86cf5514-368d-479e-9357-d5c93fce2ef0
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/rayaan/.fig/bin:/Users/rayaan/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.termius-dmg.mac
    - FIG_PID: 18804
    - FIG_SET_PARENT: 86cf5514-368d-479e-9357-d5c93fce2ef0
```

**Comment by mschrage** [comment]
Hi @rayaanr, it looks like Termius changed their bundle ID. I will try to get this updated in the next release.
