### ISSUE TITLE
Autocomplete not working for AWS CLI

### ISSUE THREAD

**Issue by hainghia** [withfig/fig#2877]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.2.1 (23C71)

### Expected behaviour

I proceed to type the commands `aws s3` or `aws sso` or `aws lambda`... and I would like to see a suggestion for the next action such as:
- aws s3 ls
- aws sso login
...

### Actual behaviour

I proceed to type `aws s3` or `aws sso` or `aws lambda`... But it doesn't show any suggestions for next action.
<img width="230" alt="image" src="https://github.com/withfig/fig/assets/38345392/82909b9d-8f97-4888-ac10-f3067f61ff47">

### Steps to reproduce

- Open terminal
- start fig
- Type `aws s3` into the terminal

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/hainghia
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 89ac9a74-7da7-43ff-9c00-af07df8b4e1f
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /opt/homebrew/opt/postgresql@16/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin/pip3.12:/Library/Frameworks/Python.framework/Versions/3.12/bin:/usr/local/opt/curl-openssl/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/go/bin:/Users/hainghia/.cargo/bin:/Users/hainghia/.fig/bin:/Users/hainghia/.local/bin:/Users/hainghia/.docker/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 13920
    - FIG_SET_PARENT: 89ac9a74-7da7-43ff-9c00-af07df8b4e1f
```

**Comment by mschrage** [comment]
Thanks for reporting @hainghia! This issue was resolved last week.
