### ISSUE TITLE
Autosuggestions not populating

### ISSUE THREAD

**Issue by kevmul** [withfig/fig#2891]
I am using Wezterm and iTerm2. Both worked with auto suggestions, but recently the autocompletions stopped populating. I get a `pipe` icon that appears that looks like the auto completion is attempting to give me some options, but nothing appears.

![image](https://github.com/withfig/fig/assets/5790104/b4510359-cccc-4a67-a3d4-b5cffdd51d68)

Here is the image with the `pipe` that appears where the auto completion would populate.

I am using zshell

**Comment by danielweck** [comment]
Duplicate of https://github.com/withfig/fig/issues/2885

**Comment by kevmul** [comment]
I don't know if anything updated, but after the weekend ( Jan 27 ) Fig is working for me now. I did nothing that would have changed and didn't manually update. 🤷‍♂️ 
Marking this as closed

**Comment by kevmul** [comment]
I don't know if anything updated, but after the weekend ( Jan 27 ) Fig is working for me now. I did nothing that would have changed and didn't manually update. 🤷‍♂️ 
Marking this as closed
