### ISSUE TITLE
Fig autocomplete pop-up shows up in iTerm even after deletion.

### ISSUE THREAD

**Issue by advxrsary** [withfig/fig#2894]
Hi. 

I am struggling with Fig autocomplete. I can not remove it by any means.
I have tried:

- Manual removal described on http://fig.io/user-manual/other/uninstall
- Reinstalling with Brew and then `brew rm fig` 
- Reinstalling Fig and disabling autocompletions. Tried to keep it, but no good.
- Enabling/Disabling iTerm intergration in Fig settings. Before and after disabling autocompletions.

Steps to reproduce:
- type some command
- press TAB two times
- dropdown appears
![image](https://github.com/withfig/fig/assets/26182157/26b9a90b-d6ed-4223-87f7-4c7c24c30ab1)

OS: MacOS 13.3.1 Ventura
iTerm2: Build 3.4.23

**Comment by mschrage** [comment]
Hi @advxrsary! That is not Fig, but rather a similar [autocomplete](https://iterm2.com/features.html) functionality built into iTerm.
