### ISSUE TITLE
Fig setting to disable autocomplete for scripts

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#290]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Issue Details

Create a fig setting that allows users to disable autocomplete for scripts (ie any CLI command that contains a `/` in the first token)
![image](https://user-images.githubusercontent.com/4949076/126241816-89dd1420-901f-462d-8f57-4c178ca52f4f.png)

### Environment

```bash
n/a
```

### Is this issue related to the docs?

- [ ] Yes
- [X] No

**Comment by SeparateRecords** [comment]
I think this is either implemented now with `autocomplete.disableForCommands` or is no longer relevant
