### ISSUE TITLE
fig won't start

### ISSUE THREAD

**Issue by reedhyde** [withfig/fig#2901]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.3.0 (23D56)

### Expected behaviour

expected fig to open screen
window appears to initialize then goes blank with the message: 

Something went wrong :(
Error: Missing submessage

### Actual behaviour

window appears to initialize then goes blank with the message: 

Something went wrong :(
Error: Missing submessage

### Steps to reproduce

open terminal
type `fig` 

### Environment

```yaml
fig-details:
  - 2.17.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 14.3.0 (23D56)
environment:
  - shell: /usr/local/Cellar/bash/5.2.26/bin/bash
  - terminal: terminal
  - cwd: /Users/reed
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /usr/local/bin/bash
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_SET_PARENT_CHECK: 1
    - FIGTERM_SESSION_ID: fa990f1c-99bc-4368-a725-835d41bb9f7c
    - FIG_TERM: 2.17.1
    - TERM: xterm-256color
    - FIG_PID: 1535
    - PATH: /Users/reed/miniforge3/bin:/Users/reed/miniforge3/condabin:/usr/local/opt/openssl/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin://Applications/Topaz Photo AI.app/Contents/Resources/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/reed/.fig/bin:/Users/reed/.local/bin
```

**Comment by naveenreddevils** [comment]
I am seeing the same issue after upgrading to macOS 14.3.0 (23D56). 
<img width="237" alt="image" src="https://github.com/withfig/fig/assets/26938024/fb26f497-bc9b-4fb6-85fe-a25e82a6c999">

**Comment by kev2480** [comment]
Having the same issue, fig not working in terminal either
![Screenshot 2024-02-01 at 11 53 59](https://github.com/withfig/fig/assets/2478058/2f4078fb-4541-4277-abc0-ae39d02c562b)

**Comment by ben-girardet** [comment]
Same issue on my side

**Comment by dmpsupport** [comment]
Same issue on my side
![image](https://github.com/withfig/fig/assets/99958866/f38b8bc5-1d4c-44ad-abbd-9f117c89bfea)

**Comment by naveenreddevils** [comment]
https://github.com/withfig/fig/issues/2885#issuecomment-1915357652 -- there is a quick fix suggested here.

**Comment by wltrallen2** [comment]
Same here. Ran the fix suggested above with no luck. Here's a screenshot of the console errors:
<img width="1067" alt="Screenshot 2024-02-02 at 9 41 30 AM" src="https://github.com/withfig/fig/assets/19161613/21227b63-5770-406d-8905-2b52db6087a6">

**Comment by Saisreenivas** [comment]
facing same issue

**Comment by billgertz** [comment]
Same here - deleted fig. Was nice until they broke it.

**Comment by awkiamaru** [comment]
Same issue in my fig 😞

**Comment by toni1703** [comment]
same here

**Comment by radualexe32** [comment]
+1

**Comment by codeime** [comment]
Same issue on my side

**Comment by kazundo** [comment]
me to

**Comment by JohnyWills1** [comment]
+1

**Comment by taba-sukosuko** [comment]
+1

**Comment by VitalijOd** [comment]
Same here

**Comment by PhillipMwaniki** [comment]
+1

**Comment by vdurante** [comment]
I don't even care about using fig anymore. My issue is that all my environment is configured through fig and right now I have no way of accessing them to migrate to another tool

**Comment by grant0417** [comment]
Sorry about this issue, a fix has been deployed. Open the dashboard and hit `⌘+r` and the new version should load which will resolve the issue.
