### ISSUE TITLE
bug: "Signups are currently disabled"

### ISSUE THREAD

**Issue by ArthurBook** [withfig/fig#2912]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS

### Expected behaviour

Allow sign in (I already have an account)

### Actual behaviour

"Signups are currently disabled"

### Steps to reproduce

It's immediately when I open the app.

### Environment

```yaml
❯ fig diagnostic

fig-details:
  - 2.17.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M2
  - cores: 8
  - mem: 24.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/arthur
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /bin/zsh
    - __CFBundleIdentifier: com.googlecode.iterm2
    - PATH: /Users/arthur/Downloads/google-cloud-sdk/bin:/opt/homebrew/bin:~/.modular/pkg/packages.modular.com_mojo/bin:/opt/homebrew/opt/sphinx-doc/bin:~/.local/share/bob/nvim-bin:/usr/local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/TeX/texbin
    - TERM: xterm-256color
```

**Comment by peon-pasado-zeitnot** [comment]
I had the same problem.
Answer are here: https://fig.io/blog/post/fig-joins-aws and here: https://aws.amazon.com/codewhisperer/

It would be awesome if installation doc was updated.

**Comment by ArthurBook** [comment]
got it!
Now it worked when I installed it via amazon codewhisperer
