### ISSUE TITLE
login to existing account fails

### ISSUE THREAD

**Issue by RChenoweth** [withfig/fig#2922]
I understand not accepting new accounts, but the interface, its processes to login to an existing account are a struggle to deal with. I'd expect some sort of "If you already have an account..." to lead to a simpler auth or at least one that validates.

**Comment by grant0417** [comment]
Make sure the email address is the exact same as you logged into, we should still allow you to login to existing accounts.

**Comment by RChenoweth** [comment]
Moved on to CloudWhisperer

Richard Chenoweth
***@***.***
