### ISSUE TITLE
not support Fleet.app yet!

### ISSUE THREAD

**Issue by dauden** [withfig/fig#2924]
it did not work with Fleet.app
<img width="1215" alt="Screenshot 2024-03-01 at 15 34 54" src="https://github.com/withfig/fig/assets/1849379/108a7b51-a939-42a5-8c11-0241f7bacc3a">

**Comment by grant0417** [comment]
We are only supporting Fig for existing user, if you want support for Fleet can you make an issue at https://github.com/aws/codewhisperer-command-line-discussions/discussions which is the relaunched version of Fig.
