### ISSUE TITLE
CodeWhisperer not work with intel chip (Sonoma 14.1.1)

### ISSUE THREAD

**Issue by lyk1576070851** [withfig/fig#2940]
I can't click the Install button even though I have the following settings turned on:

```yml
System settings / Privacy and security / Accessibility / CodeWhisperer (Enable the app)
```

<img width="960" alt="Snipaste_2024-03-19_10-29-36" src="https://user-images.githubusercontent.com/35001769/313893837-104f55f5-33fd-4ea2-929c-aa5ae8f2171f.png">

Anyone has the same problem?

**Comment by SupianIDz** [comment]
It seems like you're the only one, Fig or CodeWishperer works fine on my Mac M2.

**Comment by bryntendoswitch** [comment]
Sorry about that! 

We just pushed a bugfix for this yesterday. If you can update to the latest version, you should be good to go.

**Comment by superbryntendo** [comment]
Sorry about that!

We just pushed a fix for this yesterday. If you upgrade to the latest version, you should be good to go!

**Comment by lyk1576070851** [comment]
Thinkyou，I get it.
