### ISSUE TITLE
installing fig 

### ISSUE THREAD

**Issue by MAUMAU101** [withfig/fig#2947]
Signups are currently disabled

Opening https://app.fig.io in browser...
┌[insane☮sicksinthead]-(~)
└> ssh -T git@github.com
Enter passphrase for key '/home/insane/.ssh/id_rsa': 
Hi MAUMAU101! You've successfully authenticated, but GitHub does not provide shell access.
┌[insane☮sicksinthead]-(~)
└> fig                  
Opening https://app.fig.io in browser...
┌[insane☮sicksinthead]-(~)
└> fig doctor

✘ Fig Integration: Figterm is not running in this terminal, please try restarting your terminal

  FIG_TERM=

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

┌[insane☮sicksinthead]-(~)
└> 
┌[insane☮sicksinthead]-(~)
└> fig issue

→ Fig is not running.
  Please launch Fig with fig launch or run fig issue --force to create the issue anyways
┌[insane☮sicksinthead]-(~)
└> fig launch
Opening https://app.fig.io in browser...
┌[insane☮sicksinthead]-(~)
└> 
┌[insane☮sicksinthead]-(~)
└> 
┌[insane☮sicksinthead]-(~)
└> fig launch
Opening https://app.fig.io in browser...
┌[insane☮sicksinthead]-(~)
└> fig issue --force
✔ Issue Title · installing fig 
Heading over to GitHub...

**Comment by mschrage** [comment]
Hi @MAUMAU101, new sign ups to Fig are disabled. But I'd recommend trying [Amazon Q for command line](https://repo.fig.io/generic/stable/asset/latest/universal/fig.dmg), which offers a similar experience.
