### ISSUE TITLE
Fig does not work with Pure Shell

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#297]
### Sanity checks

- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)
- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Issue Details

Fig doesn't appear to be working for users of Pure shell: 
https://github.com/sindresorhus/pure

### Environment

```bash
n/a
```

### Is this issue related to the docs?

- [ ] Yes
- [ ] No

**Comment by mschrage** [comment]
Closing since Fig currently works with Pure shell AFAIK.
