### ISSUE TITLE
Using the option app.hideMenubarIcon true terminates the fig process after exiting the terminal 

### ISSUE THREAD

**Issue by ivandata** [withfig/fig#302]
#### Actual Behaviour

Using `app.hideMenubarIcon true` sometimes terminate the Fig process without any errors after the terminal closes and opens again. 
If you hide the icon using the command `app.hideMenubarIcon true` in the terminal, at some point after the next exit from the terminal, the Fig finishes its own process and you should run it again from the program folder. It happens sometimes, not after every exit. With visible icons, it's never happening.

#### Expected Behaviour
Using `app.hideMenubarIcon true` doesn't terminate the Fig process after the terminal closes and opens. 
In normal cases, when `app.hideMenubarIcon false` and the icon is visible, after closing the terminal the Fig icon remains in the top menu. It means the Fig remains in working condition and the process doesn’t close after the terminal closes or open.
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.45 (B218)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.45 (B218) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/imalov/.fig/bin/fig
Accessibility: true
Number of specs: 139
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/imalov/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/imalov/.volta/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/imalov/.fig/bin:/Users/imalov/Library/Android/sdk/emulator:/Users/imalov/Library/Android/sdk/tools:/Users/imalov/Library/Android/sdk/tools/bin:/Users/imalov/Library/Android/sdk/platform-tools:/Users/imalov/flutter/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (22710) - ttys011
Current working directory: /Users/imalov/
Current window identifier: 91267/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by fwesss** [comment]
@ivandata Are you still running into this?
If so and you haven't updated in a bit, can you run `fig update` to upgrade to 1.0.49 and let me know how that goes?

**Comment by fwesss** [comment]
Duplicate: https://github.com/withfig/fig/issues/532
