### ISSUE TITLE
Runbooks inserting commands locks up the terminal

### ISSUE THREAD

**Issue by raguay** [withfig/fig#312]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
Runbooks inserting commands locks up the terminal

### Steps to Reproduce
1. Open the AWSCommands runbook and fill out the inputs for uploading a directory of videos to S3
2. Click the arrow to execute the command in the terminal

### Expected Results

The command printed to the terminal and executed.

### Actual Results

The terminal locks up and I have to close it and start a new one.

### Environment

```bash
macOS Big Sur 11.5 on a MacBook Pro M1
iTerm2
```

### More Detail

terminal::iTerm2, shell::fish

### Is this issue related to the docs?

- [ ] Yes
- [X] No

**Comment by mschrage** [comment]
Closing this issue since runbooks are a legacy feature and have been deprecated.
