### ISSUE TITLE
VSCode integration indicator doesn't work for Insiders Edition

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#314]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
The menu item for VSCode integration will be unchecked if the insiders version of VSCode is installed.

### Steps to Reproduce
1. Install VSCode Insiders edition and VSCode integration.

### Expected Results
When the integration is installed, the menu item should be checked and fig diagnostic should report the installation.

### Actual Results
Even if the VSCode integration is installed and active, the Fig integrations menu and `fig diagnostic` will not show it.

### Environment

```bash
Version 1.0.46 (B250) [U.S.]

UserShell: /usr/local/bin/zsh

Bundle path: /Applications/Fig.app

Autocomplete: true

Settings.json: true

CLI installed: true

CLI tool path: /Users/MEstes/.fig/bin/fig

Accessibility: true

Number of specs: 146

SSH Integration: true

Tmux Integration: true

Keybindings path: /Users/MEstes/.fig/user/keybindings

iTerm Integration: true [Authenticated]

Hyper Integration: false

VSCode Integration: false

Docker Integration: true

Symlinked dotfiles: false

Only insert on tab: false

Installation Script: true

PseudoTerminal Path: Starting

SecureKeyboardInput: false

SecureKeyboardProcess: <none>

Current active process: /usr/local/Cellar/zsh/5.8_1/bin/zsh (27234) - ttys003

Current working directory: /Users/MEstes/bin

Current window identifier: 966/C7ADEB8B-62BC-4D02-B708-F59C15B8A0C3% (com.googlecode.iterm2)

PATH: /Users/MEstes/.oh-my-zsh/custom/plugins/git-open:/Users/MEstes/.composer/vendor/bin:/Users/MEstes/Projects/pihole/scripts:/Users/MEstes/bin/you-git-me:/Users/MEstes/bin:/usr/local/sbin:/usr/local/opt/ruby/bin:/usr/local/opt/php@7.4/sbin:/usr/local/opt/php@7.4/bin:/usr/local/opt/ruby/sbin:/usr/local/opt/ruby/bin:/usr/local/opt/gettext/sbin:/usr/local/opt/gettext/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/MEstes/.fig/bin

FIG_INTEGRATION_VERSION: 4
```

### More Detail

terminal::VSCode

### Is this issue related to the docs?

- [ ] Yes
- [X] No

**Comment by mschrage** [comment]
This will be fixed in the next release (v1.0.49). I've completely revamped how the integrations are presented and there will now by a separate entry for VSCode Insiders (if you have it installed).
