### ISSUE TITLE
Conflict with Keyboard Maestro

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#315]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
Keyboard Maestro is seeing the window name as fig@ssh

### Steps to Reproduce
Use Keyboard Maestro to assign commands based on window title.

### Expected Results
Only commands that are configured to be available based on a window's title are available.

### Actual Results
The visible window title may say "mailadmin@mailserver.com" but Keyboard Maestro will read the window title as "fig -- ssh". It is not able to provide access to the correct commands due to the overwritten title.

### Environment

```bash
N/A
```

### Is this issue related to the docs?

- [ ] Yes
- [X] No

### Anything else?

User description of problem:
I use Keyboard Maestro (https://www.keyboardmaestro.com/) and I've started adding some frequently used shell commands as KM macros. Keyboard Maestro can choose which macros to display based on the window (or tab) title. 

So, for example, I could have a set of macros configured to be available only when my iTerm 2 window has a title containing 'mailadmin@mailserver'. 

For some reason, however, when fig is running, iTerm might include the 'mailadmin@mailserver' string in the visible window title, but the _real_ name of the window -- as seen by Keyboard Maestro -- is 'fig@ssh'. As a result, Keyboard Maestro couldn't distinguish between sessions, and couldn't display the relevant command set.

**Comment by mschrage** [comment]
Closing since this is a relatively niche edge case that we can't support right now.
