### ISSUE TITLE
iTerm got an error: Can't continue << event ltrmrqck >>

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#316]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
An error dialog stating there was an issue installing the Fig iTerm integration pops up when opening iTerm. 

### Steps to Reproduce
1. Open iTerm

### Expected Results
No error dialog should appear.

### Actual Results
The error in this screenshot appears. Fig continues to work normally after closing the dialog.

![image](https://user-images.githubusercontent.com/10150898/126744699-3927d1ee-2cf6-4b51-b9e6-4225f304c016.png)

### Environment

```bash
N/A
```

### More Detail

terminal::iTerm2

### Is this issue related to the docs?

- [ ] Yes
- [X] No

**Comment by mschrage** [comment]
Fig only works with a certain version of iTerm (3.4.0 and above). We've updated the check we do before installing the iTerm integration to reflect this.

For the best experience using Fig with iTerm, please update to a more recent version :)
