### ISSUE TITLE
Sometimes Fig doesn't recognise switching to iTerm2 hotkey window

### ISSUE THREAD

**Issue by hayk-safaryan-epam** [withfig/fig#317]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
Sometimes Fig doesn't recognise switching to iTerm2 hotkey window. Thus autocomplete doesn't work.
If I click on the fig icon in the top menu bar it says previous active program (for example chrome) is not supported, but I switched to the iTerm hotkey window with the hotkey.

### Steps to Reproduce
1. Focus a window of some unsupported environment, for example chrome browser.
2. Switch to iTerm hotkey window with the hotkey
3. type a command that should have autocomplete, no autocomplete appears

### Expected Results
Autocomplete suggestion box should always pop up.

### Actual Results
Autocomplete doesn't appear. When clicking on Fig. It says `chrome is not supported`.

### Environment

```bash
Version 1.0.46 (B250) [ABC]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/hayk/.fig/bin/fig
Accessibility: true
Number of specs: 146
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/hayk/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hayk/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hayk/.fig/bin
FIG_INTEGRATION_VERSION: 4
```

### More Detail

terminal::iTerm2

### Is this issue related to the docs?

- [ ] Yes
- [X] No

**Comment by Nutlope** [comment]
Couldn't seem to reproduce this by the way

**Comment by mschrage** [comment]
@hayk-safaryan-epam check this guide out: https://github.com/withfig/fig/discussions/135

Does it resolve your issue?
