### ISSUE TITLE
"Launch Fig on Start" setting not working

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#318]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
Disabling Launch Fig on Start does not remove Fig from Login Items.

### Steps to Reproduce
1. Disable "Launch Fig on Start"
2. Quit Fig
3. Restart

### Expected Results
Fig should not be started or in Login Items

### Actual Results
Fig is started on restart and the application is still listed in Login Items

### Environment

```bash
N/A
```

### Is this issue related to the docs?

- [ ] Yes
- [X] No

### Anything else?

Login Items after restarting:
![image](https://user-images.githubusercontent.com/10150898/126802495-856dbb09-e2ea-4f9a-92a8-37e5e6bb4d12.png)

**Comment by mschrage** [comment]
This is fixed in v1.0.47!
