### ISSUE TITLE
Problem running script

### ISSUE THREAD

**Issue by thierrymichel** [withfig/fig#325]
### Description:

At startup (iTerm), I get a popup with this error message :

```
The script at "/Users/tm/Library/ApplicationSupport/iTerm2/Scripts/AutoLaunch/fig-iterm-integration.scpt" failed.
The error was: "iTerm got an error: Can’t continue «event Itrmrqck»."
The error starts at byte 0 of the script.
```

![image](https://user-images.githubusercontent.com/806883/127470168-a3d832bf-89b2-4ae0-a685-998a252e5414.png)

Debugger status is yellow and not connected

![image](https://user-images.githubusercontent.com/806883/127470434-7aa803d4-34f9-4337-93c6-30f8ee9ee299.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.0|Version 1.0.46 (B250)|/usr/local/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.46 (B250) [U.S.] 
UserShell: /usr/local/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/tm/.fig/bin/fig
Accessibility: true
Number of specs: 155
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/tm/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/tm/.nvm/versions/node/v14.8.0/bin:/Users/tm/.avn/bin:/Users/tm/.gem/ruby/2.6.0/bin:/Users/tm/.rbenv/shims:./bin:/usr/local/bin:/usr/local/sbin:/Users/tm/.dotfiles/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/tm/.fig/bin:/Users/tm/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/tm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/Users/tm/.antigen/bundles/mollifier/zload:/Users/tm/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/tm/.antigen/bundles/romkatv/powerlevel10k:/usr/local/bin:/Users/tm/Projects/bin:/Users/tm/Library/Android/sdk/platform-tools
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 659/% (com.googlecode.iterm2)</pre>
</p>
</details>

-----

When running `fig source`, everything seems ok (see details below)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.0|Version 1.0.46 (B250)|/usr/local/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.46 (B250) [U.S.] 
UserShell: /usr/local/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/tm/.fig/bin/fig
Accessibility: true
Number of specs: 155
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/tm/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/tm/.nvm/versions/node/v14.8.0/bin:/Users/tm/.avn/bin:/Users/tm/.gem/ruby/2.6.0/bin:/Users/tm/.rbenv/shims:./bin:/usr/local/bin:/usr/local/sbin:/Users/tm/.dotfiles/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/tm/.fig/bin:/Users/tm/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/tm/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/Users/tm/.antigen/bundles/mollifier/zload:/Users/tm/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/tm/.antigen/bundles/romkatv/powerlevel10k:/usr/local/bin:/Users/tm/Projects/bin:/Users/tm/Library/Android/sdk/platform-tools
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/zsh/5.8_1/bin/zsh (2036) - ttys002
Current working directory: /Users/tm
Current window identifier: 484/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by thierrymichel** [comment]
Oups! Probably a duplicate of https://github.com/withfig/fig/issues/316

**Comment by mschrage** [comment]
Hey @thierrymichel! Thanks for reporting this. Can you check which version of iTerm you're running and post it here?

It seems like Fig's iTerm integration doesn't work with the version you're on. The fix is to update iTerm to a newer version!

(And we should not install the integration unless iTerm exposes the AppleScript API hooks that we use!)

**Comment by thierrymichel** [comment]
Hi,

Thanks for your reply.
Problematic version : `Build 3.3.6`

I thought I had automatic updates 😅😬
It works like a charm. Thanks!
