### ISSUE TITLE
Directory autocompletion doesn't escape exclamation mark

### ISSUE THREAD

**Issue by Wevah** [withfig/fig#327]
### Description:
When autcompleting a directory name with an exclamation point in it, the exclamation mark isn't escaped, causing an error when return is pressed.

https://user-images.githubusercontent.com/130825/127561601-caae1cde-0c5c-4621-adab-238955c9995c.mov

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.46 (B250)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.46 (B250) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/wevah/.fig/bin/fig
Accessibility: true
Number of specs: 155
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/wevah/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/local/pgsql/bin:/usr/local/vagrant/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/wevah/.cargo/bin:/usr/ucb:/Users/wevah/ImageMagick-7.0.8/bin:/Users/wevah/bin:/Users/wevah/perl:/usr/local/mysql/bin:/usr/local/go/bin:/Users/wevah/.gem/ruby/2.0.0/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (2295) - ttys005
Current working directory: /Users/wevah/Projects/Paparazzi!
Current window identifier: 212/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Wevah! Thanks for reporting this. We'll get this fixed up ASAP! We're rolling out an update in the next few days and I'll make sure this is included.

**Comment by mschrage** [comment]
I forgot to close this issue, the rest assured that this has been fixed!
