### ISSUE TITLE
SSH integration in menu not checked after installation

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#328]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
SSH integration was installed in the config file, but the SSH integration button wasn't indicating this.

### Steps to Reproduce
1. Install SSH integration
2. Check SSH integration in Fig menu

### Expected Results
The SSH integration should be checked

### Actual Results
SSH integration is unchecked and must be clicked a few times before it actually registers.

### Environment

```bash
N/A
```

### More Detail

integration::ssh

### Is this issue related to the docs?

- [ ] Yes
- [X] No

### Anything else?
Label gets checked even if there is no .ssh/config. Once added and integration installed, we need to do the following to get the label to check:
- One click to SSH Integration to disable integration (label always unchecked)
- One click to SSH Integration to re-enable integration (label finally check)

**Comment by sullivan-sean** [comment]
We have revamped our SSH implementation. Closing outdated issues.
