### ISSUE TITLE
[BUG] iTerm warning dialog shown when using built-in password manager

### ISSUE THREAD

**Issue by jpuris** [withfig/fig#33]
**Summary:**
While Fig is running, iTerm2 complains when an entry from its built in password manager is to be filled in.

**Steps to Reproduce:**
1. Have an entry in iTerms password manager (Shortcut cmd + shift + f)
2. Type in `sudo su -` to bring up secure input
3. Try to fill in password from iTerms password manager (Shortcut cmd + shift + f)

**Expected Results:**
Password is filled in automatically when it is chosen in password manager window.

**Actual Results:**
Warning dialog is shown by iTerm. `Are you really at a password prompt? It looks like what you're typing is echoed to the screen.`

**System information:**
OS: MacOS 11.2.1 (20D74)
iTerm: Build 3.4.4
Version of Fig: 1.0.34 (B100)

**Comment by falky97** [comment]
Thanks for this really helpful description. We will look into this this week and try and get a fix in the new build.

As a side note, we hadn't tested this, but Fig doesn't appear to be working in `su`. We will look into this as well.

**Comment by mattschrage** [comment]
This is fixed in build v1.0.35. Thanks again for creating the issue.
