### ISSUE TITLE
Crash upon first keystroke in CLI onboarding

### ISSUE THREAD

**Issue by lowgos** [withfig/fig#330]
### Description:
First time using Fig, on first keystroke through the CLI onboarding process the iTerm crashed without any error.
The debugger didn't throw any error either.

Upon going to your troubleshooting page a suggestion about restarting arised (which I would've done). It worked absolutely great!

The only problem is that I know didn't try Fig through the CLI onboarding process which seemed cool.

It seems to me like an early beta bug so I checked for an already existing issue here but didn't find one that match quite well so sorry if this issue ends up being a duplicate.
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.46 (B250)|/usr/local/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.46 (B250) [U.S. International - PC] 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/gabriel/.fig/bin/fig
Accessibility: true
Number of specs: 157
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/gabriel/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/bin/fish (88355) - ttys021
Current working directory: /Users/gabriel
Current window identifier: 58805/% (com.googlecode.iterm2)</pre>
</p>
</details>

I'm excited to try Fig but it seems to work great now, I couldn't reproduce the bugged behavior for now.

Hope this helps

**Comment by nickcernis** [comment]
Seems to be fixed as of 1.0.48 (B264). 🥳
