### ISSUE TITLE
Open Fig window with keybinding

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#331]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
Fig should allow the setting of a keybinding to open the window. IDEs allow intellisense or similar windows to be opened or closed on key press. Example: ctrl + space or user defined keybinding would open autocomplete window rather than space after a command.

### Environment

```bash
N/A
```

### Is this issue related to the docs?

- [ ] Yes
- [X] No

**Comment by mschrage** [comment]
@fwesss this is currently the behavior when the tab key

**Comment by fwesss** [comment]
Introduced with custom keybindings feature.

**Comment by ELLIOTTCABLE** [comment]
How, exactly, does one do this? Right now, <key>⌃</key><key>N</key> / <key>⌃</key><key>P</key> works as I'd expect … *except* when I "<key>⌃</key><key>P</key> out" of the list entirely by going past the top item; then Fig closes, and a further <key>⌃</key><key>N</key> doesn't re-open it as I would expect from Vi/etc.

This should probably be the default behaviour …
