### ISSUE TITLE
Hangs forever

### ISSUE THREAD

**Issue by golergka** [withfig/fig#332]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

https://user-images.githubusercontent.com/929735/128009328-6060fc3e-574c-4b6a-854d-fd0e443ebb73.mov

Fig never displays any suggestion, and when I press tab, zsh doesn't use it's suggestions — I have to close Fig's autocomplete by pressing escape to do anything.
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.45 (B218)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.45 (B218) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/golergka/.fig/bin/fig
Accessibility: true
Number of specs: 126
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/golergka/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (4512) - ttys003
Current working directory: /Users/golergka/Projects/thrw
Current window identifier: 382/code:4512% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey there @golergka! So sorry you were running into this! We push a bad update to the autocomplete-engine - should be all fixed now. Try restarting Fig, if you're still running into issues. :)
