### ISSUE TITLE
Fig breaks iTerm "Send text at start" feature

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#337]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
If Fig is installed and iTerm is configured to send text at startup, the text will be displayed a but the command will not be executed on shell login.

Quitting Fig does not fix the issue. Fig must be uninstalled to use this iTerm feature.

### Steps to Reproduce
1. Configure iTerm to send the command `ls` to startup (see screenshot below)
2. Open a new iTerm window

### Expected Results
'ls' is output and then `ls` is executed after shell login

### Actual Results
'ls' is output but the command is not executed

### Environment

```bash
N/A
```

### More Detail

terminal::iTerm2

### Is this issue related to the docs?

- [ ] Yes
- [X] No

### Anything else?

<img width="577" alt="Screen Shot 2021-08-03 at 1 30 57 PM" src="https://user-images.githubusercontent.com/10150898/128082299-54180bd8-41b1-4a34-8cb9-90a9edcf9431.png">

**Comment by natterstefan** [comment]
Hi @fwesss,

can you tell me if it works when you enable "Disable AutoLaunch" in the settings of fig? I have a similar issue, as described in #339. I wonder if it's related (but it looks like it is to me).

**Comment by fwesss** [comment]
> can you tell me if it works when you enable "Disable AutoLaunch" in the settings of fig? I have a similar issue, as described in #339. I wonder if it's related (but it looks like it is to me).

I thought that would fix it on this issue too but it didn't. This still seems related though.

Either way, we'll work on making these work without disabling Fig.

**Comment by mschrage** [comment]
@sullivan-sean's working on a fix for this. Should go live with v1.0.47!

**Comment by fwesss** [comment]
Fixed in v1.0.47
