### ISSUE TITLE
Animated ellipsis - nothing works

### ISSUE THREAD

**Issue by adamzr** [withfig/fig#338]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Just shows animated ellipsis. Prevents any commands from working. Debugger says everything is fine. Works after restart.

<img width="596" alt="Screen Shot 2021-08-03 at 3 47 24 PM" src="https://user-images.githubusercontent.com/455518/128096153-31ada11b-3fc8-4116-8e81-17133fed6144.png">

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.0|Version 1.0.46 (B250)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.46 (B250) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/adamricheimer/.fig/bin/fig
Accessibility: true
Number of specs: 155
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/adamricheimer/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/adamricheimer/.nvm/versions/node/v14.10.1/bin:/Users/adamricheimer/.basher/cellar/bin:/Users/adamricheimer/.basher/bin:/Users/adamricheimer/google-cloud-sdk/bin:/Users/adamricheimer/.sdkman/candidates/java/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/adamricheimer/.fig/bin:/Applications/Postgres.app/Contents/Versions/latest/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (50381) - ttys008
Current working directory: /Users
Current window identifier: 43829/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
@adamzr thanks for reporting this! We pushed some changes to our autocomplete-engine which broke stuff. Try restarting Fig to pull a newer version - everything should be fixed :)
