### ISSUE TITLE
Fig & Alfred: "Open in Terminal" does not open chosen folder

### ISSUE THREAD

**Issue by natterstefan** [withfig/fig#339]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
Alfred's "Open Terminal here" feature does not work

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/1043668/128129582-e3093efa-f60c-4c31-8c63-086391a8f968.png)

1. Select any folder on your computer with Alfred
2. Open it with Alfred's "Open in Terminal Here" command

### Expected Results
iTerm opens selected folder and fig is ready

### Actual Results

![image](https://user-images.githubusercontent.com/1043668/128129691-6aab5c3c-285f-41d0-a350-8640f9311aa4.png)

iTerm never opens the folder, although I see the command on top of iTerm.

### Environment

```bash
Version 1.0.46 (B250) [ABC - QWERTZ]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/stefan/.fig/bin/fig
Accessibility: true
Number of specs: 153
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/stefan/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/stefan/.asdf/shims:/usr/local/opt/asdf/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/lib/ruby/gems/2.5.0/bin:/usr/local/opt/ruby/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/stefan/.fig/bin:/Users/stefan/Library/Android/sdk/tools:/Users/stefan/Library/Android/sdk/platform-tools:/Users/stefan/go/bin:/usr/local/opt/fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (48499) - ttys004
Current working directory: /Users/stefan/sandbox
Current window identifier: 235332/% (com.googlecode.iterm2)
PATH: /Users/stefan/.asdf/shims:/usr/local/opt/asdf/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/lib/ruby/gems/2.5.0/bin:/usr/local/opt/ruby/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/stefan/.fig/bin:/Users/stefan/Library/Android/sdk/tools:/Users/stefan/Library/Android/sdk/platform-tools:/Users/stefan/go/bin:/usr/local/opt/fzf/bin
FIG_INTEGRATION_VERSION: 4
```

### More Detail

terminal::iTerm2

### Is this issue related to the docs?

- [ ] Yes
- [X] No

### Anything else?

![image](https://user-images.githubusercontent.com/1043668/128129727-511c9fa5-4943-4f26-bb02-3c6fa88d296d.png)

When I enable "Disable AutoLaunch" in the settings, it works again. But not sure if that's the right solution for this case.

Maybe it's related to another issue that was reported a few hours ago https://github.com/withfig/fig/issues/337.

**Comment by mschrage** [comment]
Hey @natterstefan! Thanks for reporting this. I think I have an idea of what's going on.

@sullivan-sean I think we potentially need to initially mirror the `cwd` of the parent shell process. My guess is that iTerm spawns a shell in the correct working directory but when we launch `figterm` this isn't reflected.

**Comment by natterstefan** [comment]
Btw, this works by now.
