### ISSUE TITLE
Windows stays open after pressing submit

### ISSUE THREAD

**Issue by xyNNN** [withfig/fig#340]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
Windows stays open after pressing submit

### Steps to Reproduce
1. Open terminal (Hyper, iTerm, OS Terminal)
2. Use fig to navigate to some directories
3. Window stays open after pressing submit

### Expected Results
Disappearing the window after pressing submit.

### Actual Results
Windows stays open after pressing submit.

I've done a video with the actual behaviour:

https://user-images.githubusercontent.com/1929750/128144756-ab28238f-a882-4a95-9984-d8de7eb9805e.mov

### Environment

```bash
Version 1.0.46 (B250) [Debug] [German]
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/philipp/.fig/bin/fig
Accessibility: true
Number of specs: 155
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/philipp/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: true
VSCode Integration: false
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: false
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Little
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 39071/% (com.googlecode.iterm2)
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin
FIG_INTEGRATION_VERSION: ???
```

### More Detail

terminal::native macOS terminal, terminal::iTerm2, terminak::Hyper, shell::zsh

### Is this issue related to the docs?

- [ ] Yes
- [X] No

**Comment by mschrage** [comment]
@xyNNN it looks like you have the "Force Popup to appear" setting turned on.

You can disable it by clicking the Fig menubar icon > Integrations > Developer and then toggling it off.

<img width="544" alt="Screen Shot 2021-08-04 at 1 06 59 PM" src="https://user-images.githubusercontent.com/3155109/128247678-c3897abc-7d57-400c-be01-3c88388feb92.png">

cc @fwesss.

**Comment by xyNNN** [comment]
Thanks @mschrage! Solved!

But I didn't enable this option, is this enabled by default?
