### ISSUE TITLE
Modifier key to execute on insert

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#341]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
I would like to be able to assign a modifier key that when used in combination with enter or tab, executes the command with the selected suggestion.

### Current Behavior
I need to hit enter twice to execute the command with a suggestion unless the command has already been fully typed. 

For example:
1. `cd `
2. Navigate to suggested directory
3. Hit `enter` to add suggestion to buffer
4. Hit `enter` again to execute the full command

### Expected Behavior
An example of the feature would be:
1. `cd `
2. Navigate to suggested directory
3. Hit `shift` + `enter` to cd into that directory

### Environment

```bash
N/A
```

### Is this issue related to the docs?

- [ ] Yes
- [X] No

**Comment by mschrage** [comment]
@brendanfalk @sullivan-sean we could implement this pretty quickly as a setting, since we pass a `modifierFlags` object  in `fig.keypress` function.

**Comment by fwesss** [comment]
Introduced with  custom keybindings in v1.0.51.
