### ISSUE TITLE
Install script printed comment on the incorrect line & caused error

### ISSUE THREAD

**Issue by Nutlope** [withfig/fig#343]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
User got warning every time he opened a terminal.

### Steps to Reproduce
User got the following warning:

```
Last login: Wed Aug  4 14:02:08 on ttys000
/Users/branthardy/.zshrc:119: parse error near `\n'
➜  ~
```
He said all he did was drag the ` #### END FIG ENV VARIABLES ####` comment to a new line and it started working. Originally that comment was on line 117 for the user.
![image](https://user-images.githubusercontent.com/63742054/128258914-567c27b0-646b-499b-9c49-76d2153060ae.png)

### Expected Results
The install script should correctly place the Fig env variables one liner correctly in the user's .zshrc file.

### Actual Results
Did show that warning for the user

### Environment

```bash
NA
```

**Comment by mschrage** [comment]
I think the fix here is to prepend a newline character to the integration command.

**Comment by mschrage** [comment]
@fwesss can you create a PR fixing this?
