### ISSUE TITLE
Can't hide fig menu bar icon from app settings

### ISSUE THREAD

**Issue by silencesys** [withfig/fig#344]
### Description:
The checkbox in the app settings does not hide app icon in MacOS menu bar when checked. The only option to hide icon from menu bar is to use `fig settings app.hideMenubarIcon true`. 

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.1|Version 1.0.47 (B251)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B251) [Beta] [Czech - QWERTY] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/silencesys/.fig/bin/fig
Accessibility: true
Number of specs: 160
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/silencesys/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/sbin:/usr/local/sbin:/opt/homebrew/bin:/usr/local/bin:/Users/silencesys/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/silencesys/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (28365) - ttys001
Current working directory: /Users/silencesys
Current window identifier: 49085/C0E93A04-7657-44AD-857C-3302EA75183C% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by fwesss** [comment]
Hey @silencesys -- I'm getting something similar on 1.0.47. 

1. Open the settings app from the Fig menu
2. Check the button to hide Fig
3. The icon is still there
4. Uncheck the box to hide Fig
5. The icon is now hidden

Are you also experiencing steps 4 & 5? 
If so, looks like we've got our flag backwards and it's an easy fix. Just want to make sure there's not another issue in there though if you get different behavior.

**Comment by silencesys** [comment]
Hey @fwesss, thanks for reply. It seems to be fixed for me in 1.0.47 (B253). :)
