### ISSUE TITLE
Fig always shows beachball icon when I click on it on the menu bar, never got it to work on my M1 Mac air.  

### ISSUE THREAD

**Issue by why-not** [withfig/fig#345]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.46 (B250)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.46 (B250) [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/username/.fig/bin/fig
Accessibility: true
Number of specs: 155
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/username/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @why-not! Thanks for reporting this! Are you free to jump on a debugging call sometime next week? https://calendly.com/mschrage/30min
