### ISSUE TITLE
Support multiple versions for each CLI

### ISSUE THREAD

**Issue by EthanOrlander** [withfig/fig#346]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
Fig should support multiple versions of CLIs and make suggestions based on the version that is installed on the user's machine.

### Example
One user may be using yarn version 1, whereas another is using version 2. The CLIs for the two major yarn versions have some differences. For example, yarn 1 has the subcommand `yarn global`, whereas yarn 2 has removed this subcommand, and replaced it (more or less) with `yarn dlx`. Discrepancies between different versions applies to all CLIs. Fig needs to decide which commands, subcommands, options, and arguments to suggest based on the user's installed version of a CLI.

Let's open a discussion around how this should be implemented.

### Steps to Reproduce
1. Install yarn v2
2. In a terminal with fig enabled, type `yarn`
3. You will see that `global` is suggested
4. You will not see `dlx` as a suggestion

This is because the [current yarn spec in fig/autocomplete](https://github.com/withfig/autocomplete/blob/master/dev/yarn.ts) is for version 1.

### Expected Results
Autocomplete suggestions should reflect the CLI version installed on the machine.

### Actual Results
Autocomplete suggestions reflect the (sole) CLI version defined in the spec.

### Environment

```bash
Version 1.0.47 (B252) [Beta] [Dev] [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ethanorlander/.fig/bin/fig
Accessibility: true
Number of specs: 163
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/ethanorlander/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/ethanorlander/Library/Android/sdk/tools:/Users/ethanorlander/Library/Android/sdk/platform-tools:/Users/ethanorlander/.opam/default/bin:/bin:/Users/ethanorlander/.deno/bin:/Users/ethanorlander/opt/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamarin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (70829) - ttys011
Current working directory: /Users/ethanorlander/Documents/Professional/autocomplete
Current window identifier: 19071/code:70817% (com.microsoft.VSCode)
PATH: /Users/ethanorlander/.opam/default/bin:/Users/ethanorlander/Library/Android/sdk/tools:/Users/ethanorlander/Library/Android/sdk/platform-tools:/Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home/bin:/Users/ethanorlander/.deno/bin:/Users/ethanorlander/opt/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/ethanorlander/Library/Android/sdk/tools:/Users/ethanorlander/Library/Android/sdk/platform-tools:/Users/ethanorlander/.opam/default/bin:/Users/ethanorlander/.deno/bin:/Users/ethanorlander/opt/anaconda3/bin:/Users/ethanorlander/.fig/bin:/Users/ethanorlander/.yarn/bin:/Users/ethanorlander/.yarn/bin:/Users/ethanorlander/Library/Android/sdk/tools:/Users/ethanorlander/Library/Android/sdk/platform-tools
FIG_INTEGRATION_VERSION: 4
```

### Anything else?

For reference, the CLI subcommands used in the examples are:

[`yarn global` from yarn 1](https://classic.yarnpkg.com/en/docs/cli/global)

[`yarn dlx` from yarn 2](https://yarnpkg.com/cli/dlx)

**Comment by EthanOrlander** [comment]
Let's get some ideas going. Here's my first stab at this:

I like @mschrage's idea in [this tweet](https://twitter.com/MattSchrage/status/1424473009759399938).

Going off of it, say we put each CLI definition in a folder, and create a definition for each version where the CLI changes.

Suppose we define a spec for version 1 of a CLI. Then, version 1.1 is released, which adds a subcommand. The file structure could look something like this:

    .
    ├── ...
    ├── dev                   
    │   ├── mycli             # Folder containing mycli specs. Folder name matches cli name 
    │   │   ├── mycli@1.0.0.ts   # specs for mycli version 1.0.0
    │   │   └── mycli@1.1.0.ts   # specs for mycli version 1.1.0
    │   └── ...
    └── ...


`mycli@1.0.0.ts` contains the autocomplete definitions for version 1.0.0 of some CLI called "mycli".
`mycli@1.1.0.ts` contains the autocomplete definitions for version 1.1.0.

I think we have two options for how the spec of v1.1.0 could be defined:

1. Simply copy everything from `mycli@1.0.0.ts` into `mycli@1.1.0.ts` and make changes as needed.
2. Import the completionSpec from `mycli@1.0.0.ts` in `mycli@1.1.0.ts`, and make changes to a copy.

The first option is pretty straightforward. So, let's see what an implementation of option 2 could look like.

Since v1.1.0 only adds a single command, it's file contents could look something like this:

**<span>mycli</span>@1.1.0.ts:**
```TypeScript
import previous from "./mycli@1.0.0.ts";

const completionSpec: Fig.Spec = {
  ...previous,
   subcommands: [
      // Copy subcommands from the previous version
      ...previous.subcommands,
      // Add the new subcommand
      {
        name: "newSubcommand",
        description: "This subcommand was added in v1.1.0",
    },
  ],
}

export default completionSpec;
```

Now let's consider what it might look like when commands are removed, added, and modified all in a single release. The spec for mycli@2.0.0 might look something like this:

**<span>mycli</span>@2.0.0.ts:**
```TypeScript
import previous from "./mycli@1.1.0.ts";
import { remove, amend } from "../utils";

const completionSpec: Fig.Spec = {
    ...previous,
    subcommands: [
        // Remove subcommands that no longer exist in this version
        ...remove(previous.subcommands, ["aSubcommandName", "anotherSubcommandName"]),
        // Add a new subcommand
        {
            name: "newSubcommand",
            description: "This subcommand was added in v2.0.0",
        },
        // Change a subcommand from a previous version
        amend(previous.subcommands, "changedCommand")((subcommand) => ({
            // Only include changes in this object. Ie. let's say subcommands didn't change, we don't have
            // an entry for subcommands in this object.
            description: "This is an updated description",
            // Remove an arg
            args: remove(subcommand.args, ["argToRemove"]),
            options: [
                ...subcommand.options,
                // Amend an option
                amend(subcommand.options, "changedOption")((option) => ({
                    description: "Changing the description of the option"
                }))
            ]
        })),
    ],
}

export default completionSpec;
```

In this example, I have abstracted out a couple utility functions to make the code more readable:

**utils.ts**
```TypeScript
export function remove<T extends Array<Fig.Subcommand | Fig.Arg | Fig.Option> | Fig.Arg>(prev: T, blacklist: string[]): T {
    if (Array.isArray(prev))
        return prev.filter(item => {
            if (Array.isArray(item.name))
                return !blacklist.some(name => item.name.includes(name));
            else
                return !blacklist.includes(item.name);
        }) as T;
    else
        return blacklist.includes(prev.name) ? undefined : prev;
}

export function amend<T extends Fig.Subcommand | Fig.Option>(subcommandsOrOptions: Array<T>, name: string): (ammendmentDefinition: (subcommandOrOption: T) => Partial<T>) => T {
    const subcommandOrOption = subcommandsOrOptions.find(item => {
        if (Array.isArray(item.name))
            return item.name.includes(name);
        else return item.name === name;
    })
    if (!subcommandOrOption) throw Error(`There is no subcommand with the name ${name}`)
    return function (ammendmentDefinition: (subcommand: T) => Partial<T>): T {
        return {
            ...subcommandOrOption,
            ...ammendmentDefinition
        }
    }
}
```

Not sure where the best place to put these utils would be.

What I like about the second approach is that by building each version based on the previous version, the code semantically represents the progression of a CLI through its versions. Also, should a bug be found in an old version of a CLI, we only need to fix it where it was originally defined. In the case of option 1, we would have had to find every place the bug was copied and adjust each one.

There are some limitations to these utility functions at the moment. Currently, amend does not work for arguments. Since Subcommand.args can be either a single Argument or an array of Arguments, this complicates things for these utility functions. They're not meant to be complete, I just got some ideas flowing, and I thought I'd write them out and share them at this stage. Let me know what you think.

Another thing we need to consider is how to decide which spec to use, depending on the version a user has installed. Going to table that for now as we focus on how to do spec definitions.

PS: Why not just make args an array of Arguments?

**Comment by Nutlope** [comment]
Great thoughts @EthanOrlander! I think as an initial step, it may be easier to implement option 1 with the addition of a file that contains a generator that runs the version command and decides which version of the spec to load. 
    .
    ├── ...
    ├── dev                   
    │   ├── mycli.ts            # Spec containing the name & logic for what command to run & which version to load
    │   ├── mycli                # Folder containing mycli specs. Folder name matches cli name 
    │   │   ├── mycli@1.0.0.ts   # specs for mycli version 1.0.0
    │   │   └── mycli@1.1.0.ts   # specs for mycli version 1.1.0
    │   └── ...
    └── ...

I think this could be implemented right away without needing to change the API. Something like this:

```js
const completionSpec: Fig.Spec = {
  name: "yarn",
  description: "Manage packages and run scripts",
  generateSpec: async (tokens, executeShellCommand) => {

    if ((await executeShellCommand("yarn version")).includes("v1")) {
      return {
        name: "yarn",
        subcommands: [{ name: "yarn", loadSpec: "yarn@v1" }],
      };
    } else {
      return {
        name: "yarn",
        subcommands: [{ name: "yarn", loadSpec: "yarn@v2" }],
      };
    }
}
```

**Comment by EthanOrlander** [comment]
I think that's a great place to start @Nutlope. I'll open up a PR where we can play around with some ideas. It might make sense to come up with formal spec versioning conventions before making it official, so that people aren't redoing work.

**Comment by EthanOrlander** [comment]
I hadn't considered a hashmap. What would that look like?

**Comment by EthanOrlander** [comment]
I opened up a PR here so we can play around with some ideas: https://github.com/withfig/autocomplete/pull/458

@Nutlope I couldn't get it to play nice with loadSpec. Perhaps you can, I'm probably not as familiar with loadSpec as you are. From what I am seeing, is it possible that since we're loading a spec for the same top-level command, and not for different subCommands, that loadSpec doesn't work for this?

**Comment by Nutlope** [comment]
Thanks so much for the PR @EthanOrlander, you move fast! 

FYI make sure you're on beta by running `fig settings app.beta true` (we made some breaking changes to completion specs that are going to be deployed to prod soon)

Gonna play around with your PR tomorrow & see if I can get loadSpec working (it should work, even for top level commands).

**Comment by brendanfalk** [comment]
Like this thread a lot. Version controlling specs has been something we have been thinking about for a while. 

I think the end goal should to be to support CLI tools that want to have a different completion spec for every version if they want to, but not enforce it. I also think in the withfig/autocomplete repo, things should be more structured and standardised


I think the big questions here are:
1. How should we structure the withfig/autocomplete repo? This should be standardised.
    * We should allow CLI tools to provide a spec per major, minor, and/or patch version. e.g. we could have a specific spec for `yarn@1`, `yarn@1.2`, or even `yarn@1.2.3`. When a user requests the yarn spec, given their version, they should get the most recent spec that works given their version.
    * We should also allow CLI tools to just have the one spec. 
    * Where do we hold util scripts?
    * @EthanOrlander Your proposed structure seems pretty good, however, as you said, we should come up with a rigid standard that caters to everything and then enforce it. 
    2. How do we efficiently load specs?
    * Based on the standard we decide above, how do we make sure the actual loading of the specs is performant (running multiple shell commands is slow. Fortunately we have caching so I don't think this will be a huge issue, however, the structure will still have an impact).
3. Can Fig handle the spec loading logic in its engine as opposed to each CLI tool having to do it in its spec?
    * Hassan's implementation above is great, however, ideally Fig's engine handles all of this logic so the spec doesn't have to.  Your spec should just conform to the standard
4. How do we make sure the repo doesn't take up too much space?
    * The AWS + gcloud specs WITHOUT VERSIONING are already like 60mb... 
    * The diff strategy you implement above makes sense @EthanOrlander, however, I could still see it growing very quickly
5. How do we make sure the compiled files don't become massive? 
     * We don't want the user to have to download thousands of specs that are very very similar, but slightly different. This is a waste of space on the user's computer. How can we be efficient about pulling the exact spec the user needs?
6. How do we deal with generators?
    * This is probably the biggest question in my mind. Where are the generators written such that they can be re-used in all versions of a spec? Also, perhaps some generators are different for each version of a spec. My hunch is that CLI tools that will have versioned specs will likely have specs that were generated automatically using something like our [oclif plugin](https://github.com/withfig/oclif-plugin). The plugins generate the skeleton of the spec (subcommands, options, args), but not the arg suggestions (generators). We need an easy way to merge these into all versions of a tool. Perhaps a `generators.js` file in the subfolder of a specific CLI tool?

I think we temporarily go with Hassan's proposed implementation, however, quickly decide on a standard and then refactor Yarn accordingly.


I think the solution we come up with should be able to solve for:
* A new completion spec that comes out for each patch of AWS's CLI tool (maybe every two weeks)
* A new completion spec that comes out for each new version of a team's internal CLI tool
* A one off major change to yarn's CLI tool
* Your regular, run of the mill CLI tool that hasn't changed in centuries (`cd`, `ls`)

**Comment by fedeci** [comment]
What about a solution similar to `DefinitelyTyped` repo where each spec is a package and is released independently on a package manager (npm?). Each package should follow the versioning of the CLI tool and users are allowed to install/uninstall different versions or the entire spec. We would probably even make the spec loading faster since the user would only have the ones that he needs.

**Comment by Nutlope** [comment]
> What about a solution similar to `DefinitelyTyped` repo where each spec is a package and is released independently on a package manager (npm?). Each package should follow the versioning of the CLI tool and users are allowed to install/uninstall different versions or the entire spec. We would probably even make the spec loading faster since the user would only have the ones that he needs.
> 
> Consistency in the repo can surely be improved with a massive use of `eslint` because when reviewing thousands of lines of JS it's easy that something isn't catched by the reviewer.

Great suggestion, we've actually been looking into this over the past week! Specifically loading specs from https://www.skypack.dev/

I think we already use eslint to enforce styles, how would you propose we improve this?

**Comment by fedeci** [comment]
1. Loading specs from a CDN is definitely a possible solution, but I am not sure of how powerful it may be when versioning specs compared with a registry.🤔
2. We should continue to improve our `eslint` custom rules that satisfy pretty unique requirements.

**Comment by mschrage** [comment]
Closing as Fig specs can be versioned: https://fig.io/docs/handbook/versioning-completion-specs
