### ISSUE TITLE
Slows down computer a lot

### ISSUE THREAD

**Issue by rborn** [withfig/fig#348]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Hi, 

First of all thanks for the invite :)

After I installed Fig, the computer gets almost  unresponsive, with a big lag between typing and execute commands and even click events (opening apps/ menu etc)

<img width="370" alt="Screenshot 2021-08-09 at 16 33 14" src="https://user-images.githubusercontent.com/406409/128724327-f9a9c79a-fb12-425d-af38-d57b97988fd7.png">

I have a MPB 16", 2.6Ghz i7, 32G ram...

Thank you!

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.1.0|Version 1.0.46 (B250)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.46 (B250) [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/dan/.fig/bin/fig
Accessibility: true
Number of specs: 158
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/dan/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/dan/google-cloud-sdk/bin:/usr/local/opt/openssl/bin:/Users/dan/.gem/ruby/2.7.1/bin:/Users/dan/.rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/bin:/Users/dan/.rubies/ruby-2.7.1/bin:/Users/dan/.n/bin:~/Work/mine/baksmali:~/Work/sdks/android-sdk-macosx/platform-tools/:~/Work/sdks/android-sdk-macosx/tools/:~/Work/sdks/android-sdk-macosx/build-tools/21.1.2/:~/Work/sdks/apache-ant-1.9.4/bin:~/bin:/Users/Dan/.npm-packages/bin:~/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin:/Users/dan/.fig/bin:/Applications/Genymotion Shell.app/Contents/MacOS:/Applications/Genymotion.app/Contents/MacOS/player.app/Contents/MacOS:/Users/Dan/Library/Python/3.8/bin:/Users/Dan/Library/Python/3.9/bin:~/.npm-global/bin:~/.npm-packages/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/bash (30331) - ttys001
Current working directory: /Users/dan
Current window identifier: 202763/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by fwesss** [comment]
Hey @rborn -- can you make sure this setting is disabled?
<img width="413" alt="Screen Shot 2021-08-09 at 9 50 32 AM" src="https://user-images.githubusercontent.com/10150898/128743680-0437ee95-f3f5-4aae-b4c0-ab866a3f9a84.png">

We've had a bug with that setting causing some performance issues with bash.

**Comment by rborn** [comment]
Hi @fwesss 
At a first glance this did it, I'll keep an eye on it :)

Thanks

**Comment by mschrage** [comment]
I'm going to close this issue since this is fixed in v1.0.47!
