### ISSUE TITLE
"Updating Fig to latest version..." displaying every time new vscode window is opened

### ISSUE THREAD

**Issue by Nutlope** [withfig/fig#349]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
@sw-yx told me that "Updating Fig to latest version..." displayed every time he opened a new vscode window

![image](https://user-images.githubusercontent.com/63742054/128774436-f16be3e0-c360-4e42-8406-9b7c486ae0af.png)

### Expected Results
e.g. It should not display

### Actual Results
"Updating Fig to latest version..." displays

### Environment

```bash
N/A
```

**Comment by mschrage** [comment]
It seems like @sw-yx is on the build where the shell autoupdates fail. The fix is manually clicking "Checking for updates"

<img width="234" alt="Screen Shot 2021-08-10 at 2 23 56 PM" src="https://user-images.githubusercontent.com/3155109/128914333-b72c37b5-bb04-4d79-b5ac-ae9093766fa0.png">
