### ISSUE TITLE
Shell function completion

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#352]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
Fig should offer completions on aliases defined as zsh functions.

### Example

This works:

`alias g='git'`

This doesn't:

```
g () {
	if [[ $# -gt 0 ]]
	then
		git "$@"
	else
		git status
	fi
}
```

### Environment

```bash
N/A
```

### More Detail

shell::zsh

**Comment by SeparateRecords** [comment]
Fig can't parse shell functions, but you can now create personal shortcuts which gives the same functionality. We're also working on a UI for this!
