### ISSUE TITLE
fig --help should show settings as subcommand

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#353]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] My issue does not relate to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If it does, please create your issue here: [withfig/autocomplete](https://github.com/withfig/autocomplete/issues?q=)

### Summary
Running `fig --help` should show "settings" and a description under COMMANDS

### Environment

```bash
N/A
```

**Comment by mschrage** [comment]
Closing as the CLI has been rewritten and `--help` includes `settings` subcommand.
