### ISSUE TITLE
Support for `$GOPATH`

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#356]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
I want Fig to provide suggestions when navigating using $GOPATH.

For example: `cd $GOPATH/src/github.com`

Similar to CDPATH: https://github.com/withfig/fig/issues/170
More info on $GOPATH: https://golang.org/doc/gopath_code#GOPATH

**Comment by mschrage** [comment]
Similar to #468

**Comment by mschrage** [comment]
#1187
