### ISSUE TITLE
Fig making iterm opening take 3 seconds

### ISSUE THREAD

**Issue by Nutlope** [withfig/fig#359]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:

Whenever I open up iTerm on my personal laptop, it takes a whole 3 seconds to start (and terminal shows "zsh//figterm" in the title when this is happening). Uninstalling fig caused iterm to open instantly so it was definitely Fig. I had updated to the latest non-beta version and this was still happening.

### Environment

```bash
NA
```

**Comment by fwesss** [comment]
@Nutlope Was this something you personally ran into?

**Comment by Nutlope** [comment]
@fwesss Yep, it was. I'll re-install Fig and see if I run into the same issue.

**Comment by Nutlope** [comment]
Reinstalled and ran into the same issue.
