### ISSUE TITLE
"No such file or directory" on iterm-api-credentials

### ISSUE THREAD

**Issue by eaviles** [withfig/fig#360]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I just downloaded Fig, I installed it, gave text permissions, then now whenever I open iTerm this happens:

![image](https://user-images.githubusercontent.com/182510/129623327-f712907d-5822-4776-974d-a5d8fce9e6cc.png)
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.47 (B257)|/bin/sh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [Debug] [U.S.] 
UserShell: /bin/sh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/avilesle/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: /Users/avilesle/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: true
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: false
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 24573/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
It looks like the install script didn’t run properly. Try running `fig util:install-script` and see if this resolves the issue.

**Comment by mschrage** [comment]
PS. it seems like you have the “Force popup window to appear” setting turned on. This can cause unexpected behavior and can be disabled by clicking the Fig menu bar icon > Integrations > Developer.

**Comment by mschrage** [comment]
This is resolved as of v1.0.49.
