### ISSUE TITLE
Composer icon

### ISSUE THREAD

**Issue by duboiss** [withfig/fig#361]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Feature Details

Add the composer icon to avoid the hardcoded url in `composer` spec.
[https://getcomposer.org/img/logo-composer-transparent5.png](https://getcomposer.org/img/logo-composer-transparent5.png)

[https://github.com/withfig/autocomplete/blob/master/dev/composer.ts#L50](https://github.com/withfig/autocomplete/blob/master/dev/composer.ts#L50)

**Comment by mschrage** [comment]
Icons should be added to completion specs by referencing the URL directly!
