### ISSUE TITLE
Bash completions

### ISSUE THREAD

**Issue by japrozs** [withfig/fig#363]
Hi there,
I was thinking about making a pull request about baah specs to the repo. Any concerns or suggestions ??

**Comment by japrozs** [comment]
Btw I really like how you guys have made it so easier to add new features to the software. 😃

**Comment by mschrage** [comment]
Adding bash completions would be great!

**Comment by japrozs** [comment]
Currently I'm working for the specs of the mix CLI, but I'll implement these once I get the time.

**Comment by mschrage** [comment]
Thanks so much @japrozs! The `mix` spec looks great :)

**Comment by japrozs** [comment]
> Thanks so much @japrozs! The `mix` spec looks great :)

thanks so much
