### ISSUE TITLE
Confusing wording in settings

### ISSUE THREAD

**Issue by brianlovin** [withfig/fig#364]
### Description:

Hey team, just some drive-by feedback: the wording on this setting is really confusing. Generally it's weird to have a checkbox that, when enabled, turns _off_ a behavior. I think the correct behavior is for this checkbox to be default enabled, and the wording could be "Automatically update when launching a new shell session." – let me know if that makes sense, or maybe I've misread something 😊 

<img width="602" alt="Screen Shot 2021-08-17 at 20 23 25@2x" src="https://user-images.githubusercontent.com/1923260/129817445-df15b9b1-339a-4849-b573-6e7e7653c9df.png">

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.0|Version 1.0.47 (B257)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/brianlovin/.fig/bin/fig
Accessibility: true
Number of specs: 168
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/brianlovin/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/brianlovin/google-cloud-sdk/bin:/Users/brianlovin/.nvm/versions/node/v16.2.0/bin:/Users/brianlovin/.asdf/shims:/usr/local/opt/asdf/bin:/usr/local/opt/node@12/bin:/Users/brianlovin/Library/Android/sdk/platform-tools:/Users/brianlovin/.yarn/bin:/Users/brianlovin/.config/yarn/global/node_modules/.bin:/usr/local/opt/node@12/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/brianlovin/.fig/bin:/usr/local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by fedeci** [comment]
Not the only setting that has this "problem". Some of them has "If true" that does not sound that nice or negation at the beginning of the phrase.

**Comment by fwesss** [comment]
I've found myself re-reading certain settings occasionally and this must be why. I'll take a pass through the settings and see which ones we can make clearer.

If you see anything else that's worded strangely, post it here and I'll fix it up.

**Comment by grant0417** [comment]
This wording has been clarified in recent settings app
