### ISSUE TITLE
Hide popup after pressing right arrow to complete terminal suggestion

### ISSUE THREAD

**Issue by MikeYermolayev** [withfig/fig#366]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Hello,

I often use "Right Arrow" to complete suggestions from my terminal. The suggestions are coming from https://github.com/zsh-users/zsh-autosuggestions . So after I press right arrow Fig's popup still remains open and if I press enter it corrupts the command. 

Please see the video below

![video](https://user-images.githubusercontent.com/8783498/129934637-0ab9a330-b371-4056-8157-9b51211edd02.mov)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.2.3|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ermolaev/.fig/bin/fig
Accessibility: true
Number of specs: 168
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/ermolaev/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (18815) - ttys007
Current working directory: /Volumes/Workspace/work/fibery
Current window identifier: 110/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by fwesss** [comment]
@MikeYermolayev This looks like a bug because Fig should see that the edit buffer has changed and suggest based on what was added by zsh-autosuggestions. Does this only happen in VSCode?

Here's what it should look like. When I press right arrow, it adds that whole line up to --latest.

https://user-images.githubusercontent.com/10150898/130703285-a4a8a7c2-9754-40e8-8fc6-20acad593b9b.mov

Also, kind of funny that we use the same prompt, font, and colorscheme in our terminals.

**Comment by MikeYermolayev** [comment]
Nord is the best 😅

The same was happening to me in iterm too.
Let me re-check it tomorrow

**Comment by MikeYermolayev** [comment]
https://user-images.githubusercontent.com/8783498/130787825-23acd9f4-7e4e-471e-a730-27738143fa36.mov

This is from iTerm.

As you can see right arrow press is ignored by fig

**Comment by MikeYermolayev** [comment]
Hm, wait. Looks like I should've relaunch iTerm. 

After the restart everything works as expected
