### ISSUE TITLE
Background updates

### ISSUE THREAD

**Issue by Chriscbr** [withfig/fig#367]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
> Please include a detailed description of the feature (and an image or screen recording, if applicable)

As a user, I'd like to be able to have Fig auto-updated in the background (e.g. it could check in the background once a day) rather than whenever I open my shell.

I've personally disabled the AutoUpdate feature in Fig's settings since the "Updating Fig to latest version..." slows down the time it takes when I open new iTerm tabs. But I would still like to receive automatic updates. Plenty of other tools on macOS also update in the background.

**Comment by mschrage** [comment]
@Chriscbr I think you may have downloaded an old version where the auto update mechanism was broken.

It sounds like Fig has identified that an update is available (hence showing the prompt in your shell) but has not been able to apply it.

Manually updating to the newest version by clicking the Fig icon in your menu bar and then “Check for updates…" should fix the issue.
