### ISSUE TITLE
Fig somehow crashing Fish terminal on launch

### ISSUE THREAD

**Issue by brandonweiss** [withfig/fig#368]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Issue Details

I’m not exactly sure what happened, but I started a new terminal session and it crashed immediately (both in VSCode and Terminal.app). I can open a session if I switch my shell to Bash, then I can start my Fish shell with `/opt/homebrew/bin/fish` and everything is fine, but if I run the Fish executable in `/Users/brandon/.fig/bin` then I get “Killed 9”, which seems like it might be the problem.

### Environment

```bash
Version 1.0.47 (B257) [U.S.] 
UserShell: /opt/homebrew/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/brandon/.fig/bin/fig
Accessibility: true
Number of specs: 169
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/brandon/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/brandon/Code/dotfiles/bin:./bin:./node_modules/.bin:/Users/brandon/.asdf/shims:/opt/homebrew/opt/asdf/bin:/opt/homebrew/bin:/Users/brandon/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/bash (73897) - ttys001
Current working directory: /Users/brandon
Current window identifier: 57527/% (com.apple.Terminal)
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
FIG_INTEGRATION_VERSION: 4
```

**Comment by brendanfalk** [comment]
Hmmm. Super strange. @sullivan-sean @mschrage?

A couple of other users have faced similar issues with this build (v1.0.47). We will investigate. thanks so much for flagging

**Comment by fwesss** [comment]
@brandonweiss Are you still running into this?
Version 1.0.48 should have fixed this. Try running `fig update` if this is still happening.

**Comment by brandonweiss** [comment]
It’s fixed, thanks!
