### ISSUE TITLE
VS Code Terminal - public folder not listed in cd dropdown

### ISSUE THREAD

**Issue by nebrekab** [withfig/fig#369]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When I use the terminal in VS code, it's not listing a public folder in the directory.

If I manually type cd public it does change dir.

<img width="894" alt="Screenshot 2021-08-18 at 23 38 18" src="https://user-images.githubusercontent.com/841826/129976599-86ab5d20-8ac6-41ea-8155-48008a889da4.png">

In OSX Terminal it works, allowing me to select the public dir.

<img width="755" alt="Screenshot 2021-08-18 at 23 41 17" src="https://user-images.githubusercontent.com/841826/129976594-72630a76-8ecb-4415-a3ae-ad33166905fe.png">

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/neb/.fig/bin/fig
Accessibility: true
Number of specs: 168
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/neb/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/neb/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
This is quite weird. Is this the only folder where you've noticed this behavior? @nebrekab

**Comment by nebrekab** [comment]
I've been in touch with one of your time and this seems to have now come
right.

Possibly the glitch was addressed in an update. Feel free to close this ;)
