### ISSUE TITLE
Add Elixir icon

### ISSUE THREAD

**Issue by japrozs** [withfig/fig#370]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I have made a spec for the mix CLI which should have the elixir programming language logo next to it.

![image 1 elixir](https://user-images.githubusercontent.com/66138036/130006264-c7f88eb0-ba0d-4046-977e-61cd2ed5cace.png)

### Environment

```bash
[no description needed]
```

**Comment by mschrage** [comment]
Icons should now be included by using a URL reference in the completion spec!
