### ISSUE TITLE
Show autocomplete on Tab breaks tab indentation in vscode editor

### ISSUE THREAD

**Issue by MikeYermolayev** [withfig/fig#371]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hello👋🏻

I turned on "Show on tab" and now tab-presses can't be captured by vscode. As a result I can't indent using Tab.

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.2.3|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ermolaev/.fig/bin/fig
Accessibility: true
Number of specs: 168
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/ermolaev/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 110/code:26135% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by fwesss** [comment]
@MikeYermolayev Have you noticed if tab presses stopped working anywhere like `cmd`+`tab` to switch windows?

**Comment by MikeYermolayev** [comment]
When I'm not in vscode `cmd`+`tab` works OK. But in vscode it doesn't work

**Comment by mschrage** [comment]
This is fixed as of v1.0.49!
