### ISSUE TITLE
Install screen shows wrong setting name for Telemetry

### ISSUE THREAD

**Issue by ebarti** [withfig/fig#372]
### Description:

When installing for the first time, at the privacy step the app incorrectly indicates that, to disable telemetry, the user can use this command: `fig settings telemetry.disabled true` 

The variable name is not correct, as it currently is `app.disableTelemetry`
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.1|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: [DIR]/.fig/bin/fig
Accessibility: true
Number of specs: 168
SSH Integration: false
Tmux Integration: true
Keybindings path: [DIR]/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: [PATH]
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (30764) - ttys004
Current working directory: [DIR]
Current window identifier: 4549/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Thanks for reporting this. Actually `app.disableTelemetry` is the deprecated key (although both will disable telemetry).

Where did you see a reference to `app.disableTelemetry`? This should be updated.

**Comment by ebarti** [comment]
Oh, my bad! It is the first setting shown when fig autocompletes `fig settings`: 
<img width="567" alt="image" src="https://user-images.githubusercontent.com/38191745/130332697-51837741-ab6c-43df-beb7-178a724c878b.png">

**Comment by ebarti** [comment]
Closing as it is not an actual issue.

(Feat req.) Although you probably have it in mind, I think it would be nice to be able to flag suggestions as deprecated, and then have the suggestion be striked through
