### ISSUE TITLE
How to change font used in the menu?

### ISSUE THREAD

**Issue by Tekl** [withfig/fig#375]
### Description:
> I would like to use my own font in the auto-complete menu.

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [German] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/***/.fig/bin/fig
Accessibility: true
Number of specs: 171
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/***/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/openjdk@11/bin:/usr/local/sbin:/usr/local/opt/openjdk@11/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (9157) - ttys006
Current working directory: /Users/***
Current window identifier: 2603/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Tekl! @cstrnt added support for this recently!

You can specify a font by running `fig settings autocomplete.fontFamily <font-name>`!
