### ISSUE TITLE
Executing Custom Key Mapping On iTerm Breaks Autocompletions

### ISSUE THREAD

**Issue by JosephTLyons** [withfig/fig#376]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
Fig stops providing autocompletes when I use custom key mappings in iTerm.  Currently, I have:

<img width="665" alt="Screen Shot 2021-08-19 at 5 22 56 PM" src="https://user-images.githubusercontent.com/19867440/130146058-9680f944-4931-4374-9e82-3d93eb9c5203.png">

1. `option + delete` mapped to deleting a word
2. `cmd + delete` mapped to deleting a line.

Mapping number 2 doesn't seem to interfere with Fig, but 1 does.  Autocomplete stops working after I use this mapping.

https://user-images.githubusercontent.com/19867440/130146261-5dc01605-9947-4323-841c-e1ade06704b6.mov

`cmd + escape` does not fix the issue, but `ctrl + c` seems to restore the functionality.

### Environment

```bash
Version 1.0.47 (B257) [U.S.]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/josephlyons/.fig/bin/fig
Accessibility: true
Number of specs: 168
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/josephlyons/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: false
PseudoTerminal Path: /Users/josephlyons/.nvm/versions/node/v12.16.1/bin:/Users/josephlyons/.nimble/bin:/Users/josephlyons/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/josephlyons/.cargo/bin:/Users/josephlyons/.fig/bin:/Users/josephlyons/Programming/Libraries/flutter/bin:/Applications/Postgres.app/Contents/Versions/11/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (11315) - ttys014
Current working directory: /Users/josephlyons
Current window identifier: 82204/37331261-DB18-4116-84B4-6F01D9A31655% (com.googlecode.iterm2)
PATH: /Users/josephlyons/.nvm/versions/node/v12.16.1/bin:/Users/josephlyons/.nimble/bin:/Users/josephlyons/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/josephlyons/.cargo/bin:/Users/josephlyons/.fig/bin:/Users/josephlyons/Programming/Libraries/flutter/bin:/Applications/Postgres.app/Contents/Versions/11/bin
FIG_INTEGRATION_VERSION: 4
```

**Comment by mschrage** [comment]
This should be resolved as in recent version. (We've transitioned how we determine what text is in your shell's edit buffer)
