### ISSUE TITLE
Installing Fig deleted dotfile symlinks

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#378]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
> Fig ended up removing the symlinks for my dotfiles I had setup on my home directory.

### Environment

```bash
N/A
```

**Comment by mschrage** [comment]
This has been fixed. See [this commit](https://github.com/withfig/config/commit/37cf6f88781e75a0992708508b4815e4f5296bd6) in withfig/config.
