### ISSUE TITLE
Fig window theme to inherit from terminal colorscheme

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#379]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
My preferred theme isn't supported by Fig and I already have it as my colorscheme in the terminal. Fig should generate it's theme from my terminal color scheme.

**Comment by mschrage** [comment]
Duplicate of #412

**Comment by brendanfalk** [comment]
This is likely going to be be quite hard unfortunately :/

**Comment by mschrage** [comment]
Closing as out of scope.
