### ISSUE TITLE
[BUG] Fig crashes PyCharm's terminal, if used with ZSH + zsh-syntax-highlighting plugin

### ISSUE THREAD

**Issue by jpuris** [withfig/fig#38]
**Summary:**
PyCharm's (And most likely all other Intellij app) terminal windows crash, if Fig is used with ZSH + zsh-syntax-highlighting plugin. This happens even if Fig is disabled.

**Commenting following line in `~/.zshrc`, fixes the problem**
```zsh
#### FIG ENV VARIABLES ####
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
```

**Steps to Reproduce:**
1. Install fig
3. Use [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh)
4. Use [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) plugin
5. Open PyCharm
6. Open Terminal (ALT + F12)
7. Type something in terminal prompt

**Expected Results:**
Terminal window works as expected and the input is displayed.

**Actual Results:**
Terminal window will close (zsh crashes)

**System information:**
OS: MacOS Big Sur 11.2.2
Version of PyCharm 2020.3.3 (Professional Edition), Build #PY-203.7148.72, built on January 27, 2021
Version of Fig: 1.36 (B139)
Git commit of Oh-my-zsh 9a9f3831925432fdf4352c24a002506a06d329c1
Git commit of zsh-syntax-highlighting 205bc7ea199cfd4cded51d465baad63b3d7f3aad

**Additional Notes:**
Fig app can be shut down or running, this makes no difference.

I hope someone with similar setup will be able to reproduce the issue.

**Comment by falky97** [comment]
Crazy - let us look into it. Will try and push fix today!

**Comment by falky97** [comment]
Should've been fixed in build that went out today. Closing the issue, feel free to re-open if problem persists. Thanks so much for reporting :)

**Comment by bfelbo** [comment]
@brendanfalk I'm having this issue with WebStorm as well. Uncommenting the lines associated with Fig in `~/.bash_profile` solves the issue. It seems to have occurred out of nowhere as I couldn't get Fig to work with WebStorm earlier, but it didn't crash my terminal.

I've just tried reinstalling with Fig `1.0.55,383` from Homebrew, but doesn't seem to be solved in the latest version.
