### ISSUE TITLE
Navigate Fig suggestions with ctrl+j and ctrl+k

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#380]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
I wan to be able to navigate Fig suggestions with ctrl+j and ctrl+k. 

I have a similar workflow in vim and this would make using Fig a smoother experience for me.

**Comment by mschrage** [comment]
This will be included in the next version of Fig!
