### ISSUE TITLE
zsh got stuck after passing to root

### ISSUE THREAD

**Issue by Nimon77** [withfig/fig#381]
### Description:

-  When going into root and restart zsh got stuck due to `zsh (figterm)` owner passed from user to root and can't be deleted

![~/.fig/bin](https://i.ibb.co/zn2dqT7/Capture-d-e-cran-2021-08-20-a-15-30-38.png)

- When I restart i'm stuck and I need `ctrl+c` because he try to execute `rm ~/.fig/bin/'zsh (figterm)'` and is not the owner anymore 

![iterm restart](https://i.ibb.co/QQTq91T/Capture-d-e-cran-2021-08-20-a-15-32-15.png)

![iterm rm](https://i.ibb.co/DQp0bKR/Capture-d-e-cran-2021-08-20-a-15-35-52.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/nsimon/.fig/bin/fig
Accessibility: true
Number of specs: 168
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/nsimon/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (15128) - ttys002
Current working directory: /Users/nsimon/.fig/bin
Current window identifier: 3243/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by sullivan-sean** [comment]
Should be fixed now with https://github.com/withfig/config/commit/55d74f684418837719596e91fd074da6356dfedb - thanks for pointing this out :)

To hotfix this on your own machine you can make the same change to `~/.fig/shell/pre.sh` or you can run Fig's install and upgrade script to pull from the updated remote repo.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/22581534/130257096-f99135bb-1d6c-4328-af31-e2d180a8e21b.png">

**Comment by Nimon77** [comment]
That work perfectly, thanks !
