### ISSUE TITLE
Fig appears in VSCode editor

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#385]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
> Once in a while when coding in VSC, the Fig dropdown appears for no reason.
![image](https://user-images.githubusercontent.com/10150898/130504049-df40877d-d49b-48ea-bc46-0152337c217b.png)

### Environment

```bash
N/A
```

**Comment by fwesss** [comment]
@mschrage Had someone run into this issue today. No VSCode integrated terminal is open and pops up straight in the editor. This user uses Hyper separately.

**Comment by nicokvara** [comment]
Hyper was open and the hyper window was behind vsc. Happened twice when I wrote "import" in vsc.

**Comment by mschrage** [comment]
This will be fixed in the next release!
