### ISSUE TITLE
Figterm error when spawning multiple iTerm sessions simultaneously

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#386]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
I have iTerm configured to open a 2 x 2 window with 4 new sessions on startup. Occasionally, one of the sessions will end with:
> "/Users/.../.fig/shell/pre.sh:52: no such file or directory: /Users/.../.fig/bin/zsh (figterm)"

Sometimes the error isn't shown, I just have the "Session Ended" in iTerm.

### Environment

```bash
N/A
```

**Comment by mschrage** [comment]
This should be fixed in the next release (v1.0.48)!
