### ISSUE TITLE
Fig messes with GraphQL files

### ISSUE THREAD

**Issue by quinnvaughn** [withfig/fig#387]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

While trying to type in a graphql file (specifically I'm writing a fragment) Fig will do "Hit enter to regain context" and then add fig source text to my graphql file

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.0|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/quinnvaughn/.fig/bin/fig
Accessibility: true
Number of specs: 167
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/quinnvaughn/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/quinnvaughn/mambaforge/bin:/Users/quinnvaughn/.rbenv/shims:/Users/quinnvaughn/.nvm/versions/node/v16.4.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/quinnvaughn/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 954/code:5180% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @quinnvaughn! Thanks for reporting this. What application are you using to edit the graphql file?

**Comment by mschrage** [comment]
This should be fixed now!
