### ISSUE TITLE
iTerm2 SSH as a Profile does not disable Fig when SSH integration should be disabled

### ISSUE THREAD

**Issue by ChristinWhite** [withfig/fig#388]
### Description:
Due to Fig not adapting to the SSH host and trying to autocomplete using the client's context I decided to go ahead and disable SSH integartion for now, I unchecked `Integartions > SSH Integration` and modified my `~/.ssh/config` to the following:

```sh
# ControlPath ~/.ssh/%C
# ControlMaster auto
# ControlPersist 1
# PermitLocalCommand yes
# LocalCommand fig bg:ssh ~/.ssh/%C &

# Fig SSH Integration: Enabled
# 
# Include ~/.fig/ssh
# 
# End of Fig SSH Integration
```

This works fine if I start SSH manually in my iTerm session (`ssh user@host`) but it doesn't work with an iTerm2 *profile* that automatically launches SSH. I've tried it two ways:

![image](https://user-images.githubusercontent.com/1746405/130527722-14d032ab-b535-49a3-b04b-56ac650f58b7.png)

When I use the **Command** option with `ssh` command parameter Fig does remain active but does ask me to *Hit enter to regain context*.

I suspected the problem might be that using the **Command** version of the *profile*, since it never actually echoes the `ssh` command, might not give Fig any context to recognize that the terminal is in an SSH session so I then tried using a **Login Shell** with *Send text at start*. This does echo out the command at the beginning of the shell initialization.

![image](https://user-images.githubusercontent.com/1746405/130527311-a0b3cb4d-e02f-4a9e-959d-4bfa0063993a.png)

Unfortunately it gives me a very similar result, in this case Fig doesn't ask me to regain context but it does still show Fig with autocompletions from the client machine. 

Out of curiosity I did also try the **Custom shell** option with Bash (default & Homebrew) as well as Fish but neither seemed to actually execute *Send text at start* correctly and I didn't think it would be worth troubleshooting further.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.1|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/christin/.fig/bin/fig
Accessibility: true
Number of specs: 176
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/christin/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: true
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/christin/.pyenv/shims:/Users/christin/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/christin/.cargo/bin:/usr/ucb:/Users/christin/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
I'm going to close this issue as stale! We are reworking our SSH integration. See #709 for more details.
