### ISSUE TITLE
Disable '>' suggestion

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#395]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:

I would like the option to disable the suggestion that immediately executes what's in the edit buffer:

![image](https://user-images.githubusercontent.com/10150898/130998675-6a291ff3-90e6-48f1-9352-bba13c6aa4d9.png)

**Comment by mschrage** [comment]
@fedeci could you take a look at this?
