### ISSUE TITLE
onlyShowOnTab setting breaks tab in VSCode

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#397]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
onlyShowOnTab setting breaks tab in VSCode and Hyperswitch.

If I have that setting enabled, I will not be able to cmd + tab to another window.

I will also not be able to use the tab key in the VSCode editor.

### Environment

```bash
N/A
```

**Comment by mschrage** [comment]
This is fixed as of v1.0.49, which should go live this week!
