### ISSUE TITLE
Setting to add space after every suggestion

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#398]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
Fig will add a space after a suggestion that takes a mandatory argument. Other autosuggest tools will insert a space after every suggestion and I would like a setting to replicate that behavior.

**Comment by brendanfalk** [comment]
This was fixed quite a while ago... But I'm not sure why we never closed.

Update the following setting in your `fig settings`

<img width="778" alt="CleanShot 2022-01-10 at 16 44 20@2x" src="https://user-images.githubusercontent.com/4949076/148861598-bce52a90-3f62-4c3b-a4d4-2bd98c3693c9.png">
