### ISSUE TITLE
Deploy Fig as a universal app so it can run natively on new M1 (arm64) macs

### ISSUE THREAD

**Issue by vicentube** [withfig/fig#40]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. (e.g. I'm always frustrated when [...])
On M1 (arm64) macs, Fig runs under Rosetta. It works fine, but maybe performance is affected.
**Describe the solution you'd like**
Compile Fig as a universal app to run natively also for new M1 macs.
**Describe alternatives you've considered**

**Additional context**

**Comment by mattschrage** [comment]
Hey Vicente, this has been something I've been meaning to do for a while. I'm still running Catalina which means I don't have the newest version of Xcode and I don't think I can compile for M1 with the version that I'm on.

Rest assured, I will get this done in the next week or two.
