### ISSUE TITLE
Fig with ZSH + iTerm breaking terminal

### ISSUE THREAD

**Issue by koz** [withfig/fig#401]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hi!
When using fig, terminal keeps bugging. I use a zsh (this is the [config](https://gist.github.com/koz/ce42e88ab16eabcb8e33c8931878e131)), with tmux (this is the [conf](https://gist.github.com/koz/10d9c7b172947c0d9825bf330d7a1132)).
Can you guys spot what might be causing this problem:

https://user-images.githubusercontent.com/5442132/131105908-b4be5e7d-011e-4968-bb81-ed3785bec541.mp4

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [Brazilian - Pro] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/gkozlowaski/.fig/bin/fig
Accessibility: true
Number of specs: 185
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/gkozlowaski/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/gkozlowaski/.yvm/shim:/Users/gkozlowaski/.nvm/versions/node/v14.16.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/laps:/Users/gkozlowaski/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (94355) - ttys006
Current working directory: /Users/gkozlowaski
Current window identifier: 29297/5915A2BF-225E-46A6-AB47-EF8F9A79D11C% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by roitalpaz** [comment]
This is happening to me too.

When I exit tmux and create a new tmux shell it is working.

**Comment by parssak** [comment]
This is now fixed
