### ISSUE TITLE
Typing "too quickly" results in double characters.

### ISSUE THREAD

**Issue by warrickbayman** [withfig/fig#404]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I often get "double" characters if I type a little quickly and hit "Tab" when navigating directories. It definitely seems dependent on the speed I type because if I slow down, I don't see the problem.

So typing "/Vol" and hitting tab fairly quickly results in "/Vollumes" (double "l").

https://user-images.githubusercontent.com/856840/131337083-111abbe1-52cb-4cd2-a3fe-48007a7a0573.mp4

I'm using an iTerm2 hotkey window with fish shell and starship prompt.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.47 (B257)|/usr/local/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [ABC] 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/warrickbayman/.fig/bin/fig
Accessibility: true
Number of specs: 185
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/warrickbayman/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/warrickbayman/.composer/vendor/bin:/Users/warrickbayman/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @warrickbayman! Thanks for reporting this. This behavior is most prevalent in `fish` do to some limitations on how we can access the edit buffer. I think we have found a workaround and this issue should be fixed in the next update (v1.0.48).

**Comment by warrickbayman** [comment]
Thanks @mschrage. Otherwise, Fig is great.

**Comment by mschrage** [comment]
If you run `fig update` now, you should have access to the newest version!
