### ISSUE TITLE
Inserting single quote instead of selected text

### ISSUE THREAD

**Issue by eduzen** [withfig/fig#405]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I select update, and autocompletes with a single quotte 
<img width="514" alt="Screenshot 2021-08-30 at 21 18 48" src="https://user-images.githubusercontent.com/8366343/131393123-9348274d-00c5-4c7c-b643-5627ff910e21.png">

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/eduardoenriquez/.fig/bin/fig
Accessibility: true
Number of specs: 188
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/eduardoenriquez/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/libpq/bin:/Users/eduardoenriquez/.poetry/bin:/Users/eduardoenriquez/.pyenv/shims:/Users/eduardoenriquez/.pyenv/bin:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/eduardoenriquez/.pyenv/shims:/Users/eduardoenriquez/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/eduardoenriquez/.cargo/bin:/usr/ucb:/Users/eduardoenriquez/.fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/git/2.33.0/bin/git (4674) - ttys003
Current working directory: /Users/eduardoenriquez/Projects/private/filmer
Current window identifier: 382/2F583E67-F96D-4FE4-8591-AA2E43D5F94B% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @eduzen! Thanks for reporting this. I think that this issue has to do with how Fig inserts text in to a zsh session. 

We inject a unicode character ("◧") using the Accessibility API which is bound to a function in zsh using bindkey.

For some unknown reason, occasionally the shell will stop handling this keybinding correctly and just insert a single quote.

Can you run `bindkey | grep fig`? Also which version of iTerm are you on?

**Comment by eduzen** [comment]
@mschrage thanks! My iterm version is Build 3.4.8.

```
$ bindkey | grep fig
"\M-b\M-^W\M-'" fig_insert
"\M-b\M-^W\M-(" fig_insert_and_clear_autosuggestion
```

**Comment by mschrage** [comment]
@eduzen the fix for this is running `stty -istrip` in the affected terminal window!

**Comment by eduzen** [comment]
it works but only for a few times, after you use the autocompletion more often starts to behave bad again.

**Comment by jazzdan** [comment]
> the fix for this is running `stty -istrip` in the affected terminal window!

This changes the behavior for me, but doesn't fix it. After I run this command fig always autocompletes to the same thing, _regardless of which item is selected_:

This is what it looks like from my side https://www.loom.com/share/8c673605f8084164812492156a4fb64c

**Comment by jazzdan** [comment]
And now it's working again! 🤷

**Comment by jazzdan** [comment]
I ran in to the problem again in a new terminal window, running `stty -istrip` fixed it this time

https://www.loom.com/share/c3e6f91101d24fa98f202a0b3e26bd1e

Should I add that to my profile or something?

**Comment by mschrage** [comment]
It turns out this is due to a bug with `brew`.  We've just pushed a hotfix (v1.0.48) that adds a workaround for this issue.

**Comment by eduzen** [comment]
it's resolve after upgrading the package.
