### ISSUE TITLE
Make it easier to select a directory when using fish

### ISSUE THREAD

**Issue by j-f1** [withfig/fig#41]
**Is your feature request related to a problem? Please describe.**
Fish allows you to change directories by “executing” a directory (i.e. you can run `src/` to do the same thing as `cd src/`). However, the path autocomplete provided by Fig does not allow for this possibility (you have to hit `esc` to close the panel before hitting enter to cd.

**Describe the solution you'd like**
Add a “run” shortcut like the one produced by `cd`’s autocompletion.

**Describe alternatives you've considered**
Not sure there is one

**Additional context**

https://user-images.githubusercontent.com/25517624/112060530-adc69e00-8b33-11eb-82bb-1659e834bebb.mov

**Comment by mattschrage** [comment]
Didn't know that was possible with `fish` - I learned something new today. :)

I think this should be a pretty easy fix on our end. Thanks for reporting.

**Comment by mattschrage** [comment]
Hey Jed! You can update this behavior by editing the `~/.fig/autocomplete/dotslash.js`.

Just add the `"folders"` option to the list of templates, and the red insert option will appear for folders as well as files.

```
        template: ["filepaths", "folders"]
```
