### ISSUE TITLE
Fig doesn't respect existing zshrc setting

### ISSUE THREAD

**Issue by aneeskA** [withfig/fig#410]
### Description:
Without fig, my terminal shows me which branch I am on right now:
<img width="948" alt="image" src="https://user-images.githubusercontent.com/514419/131453030-7ee9898e-6d3e-4cba-bf79-c129b0b2cc5a.png">

When I start fig, that is absent.
<img width="966" alt="image" src="https://user-images.githubusercontent.com/514419/131453144-9224edab-e0f4-479f-aa02-9080282d17de.png">

Can you please fix this?
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/anees.a/.fig/bin/fig
Accessibility: true
Number of specs: 188
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/anees.a/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/anees.a/.fig/bin:/Users/anees.a/go/bin/:/Users/anees.a/Library/Python/3.7/bin/:/usr/local/opt/coreutils/libexec/gnubin:/Users/anees.a/Library/Python/3.8/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (39616) - ttys001
Current working directory: 
Current window identifier: 54714/4FD3C57F-1CC2-479C-A07E-D4DB030658C0% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by fwesss** [comment]
@mschrage This is similar to the bug with git_prompt in ZSH I brought up on Friday.

**Comment by mschrage** [comment]
@fwesss updated how we handle the right prompt being set in our shell integration! I think this issue will be fixed in the next release!

**Comment by aneeskA** [comment]
> @fwesss updated how we handle the right prompt being set in our shell integration! I think this issue will be fixed in the next release!

Excellent. Cant wait to try it out :) When is the next release?

**Comment by fwesss** [comment]
@aneeskA 1.0.49 is out now! Run `fig update` to get the fix.
