### ISSUE TITLE
Detect system theme

### ISSUE THREAD

**Issue by vvkh** [withfig/fig#412]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:

Currently there are only 2 theme options available: dark and light.
<img width="339" alt="image" src="https://user-images.githubusercontent.com/18095933/131465909-03b05557-a9d0-4b9e-939c-5c759ad8a401.png">

However, I (and I believe some users out there) use automatic native switching between dark and light themes.
<img width="351" alt="image" src="https://user-images.githubusercontent.com/18095933/131466325-af93443e-7792-46cc-8e20-356af67f233e.png">

Currently I must either switch themes manually every evening or stick with one and deal with inconsistent appearance.
<img width="494" alt="image" src="https://user-images.githubusercontent.com/18095933/131466680-1285947c-5a32-4294-9b66-830afc7c3bbb.png">

It would be nice if `fig` had `auto` just like in system preferences.

### Environment

```bash
Version 1.0.47 (B257) [English - Ilya Birman Typography]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/vvkhomutenko/.fig/bin/fig
Accessibility: true
Number of specs: 189
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/vvkhomutenko/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (88046) - ttys008
Current working directory: /Users/vvkhomutenko
Current window identifier: 412922/% (com.googlecode.iterm2)
PATH: /usr/local/opt/mysql-client/bin:/usr/local/opt/node@14/bin:/usr/local/Cellar/libpq/13.3/bin:GOPATH/bin:/Users/vvkhomutenko/go/bin:/Users/vvkhomutenko/.poetry/bin:/Users/vvkhomutenko/bin:/Users/vvkhomutenko/Library/Python/3.8/bin:/usr/local/bin:/Applications/kitty.app/Contents/MacOS/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/vvkhomutenko/.fig/bin
FIG_INTEGRATION_VERSION: 4
```
```

**Comment by mschrage** [comment]
@fedeci is working on this! Should be available soon :)

**Comment by fedeci** [comment]
👀
