### ISSUE TITLE
`fig docs` seems broken?

### ISSUE THREAD

**Issue by axhamre** [withfig/fig#416]
### Description:

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/1907343/131506630-eb53fe9d-e655-46d7-b338-7b9e14e8ef2f.png">

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [Swedish - Pro] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/lo/.fig/bin/fig
Accessibility: true
Number of specs: 190
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/lo/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/lo/.nvm/versions/node/v14.16.0/bin:/Users/lo/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/9.6/bin:/Users/lo/Library/Android/sdk/platform-tools:/usr/ucb
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/bash (10643) - ttys002
Current working directory: /Users/lo/.fig
Current window identifier: 20216/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by fedeci** [comment]
Have you tried just typing `fig`?

**Comment by mschrage** [comment]
This is confusingly worded in the onboarding. We should fix this because I think a lot of people get confused here. 

If anyone want to give this a shot, our shell onboarding script is open source: https://github.com/withfig/config/blob/main/tools/drip/fig_onboarding.sh

cc @brendanfalk @fwesss
