### ISSUE TITLE
no autocomplete in MacOS native Terminal with oh-my-zsh

### ISSUE THREAD

**Issue by marklabenski** [withfig/fig#418]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
The autocomplete is not showing in native MacOS terminal on zsh/oh-my-zsh
Even though the debugger in the task bar says "Everything should be working."

I tried restarting the terminal, restarting fig etc. 

Fig tools doctor output:
<code>Let's make sure Fig is running...

Fig bin exists: pass
Fig in path: pass
Fig running: pass

Fig ENV variables need to be at the very beginning and end of /Users/mlabenski/.profile

If you see the FIG ENV VARs in /Users/mlabenski/.profile, make sure they're at the very beginning (pre) and end (post). Open a new terminal then rerun the the doctor.

If you don't see the FIG ENV VARs in /Users/mlabenski/.profile, run 'fig util:install-script' to add them. Open a new terminal then rerun the doctor.

Fig ENV variables need to be at the very beginning and end of /Users/mlabenski/.zprofile

If you see the FIG ENV VARs in /Users/mlabenski/.zprofile, make sure they're at the very beginning (pre) and end (post). Open a new terminal then rerun the the doctor.

If you don't see the FIG ENV VARs in /Users/mlabenski/.zprofile, run 'fig util:install-script' to add them. Open a new terminal then rerun the doctor.

Fig ENV variables need to be at the very beginning and end of /Users/mlabenski/.bash_profile

If you see the FIG ENV VARs in /Users/mlabenski/.bash_profile, make sure they're at the very beginning (pre) and end (post). Open a new terminal then rerun the the doctor.

If you don't see the FIG ENV VARs in /Users/mlabenski/.bash_profile, run 'fig util:install-script' to add them. Open a new terminal then rerun the doctor.

Fig ENV variables need to be at the very beginning and end of /Users/mlabenski/.bashrc

If you see the FIG ENV VARs in /Users/mlabenski/.bashrc, make sure they're at the very beginning (pre) and end (post). Open a new terminal then rerun the the doctor.

If you don't see the FIG ENV VARs in /Users/mlabenski/.bashrc, run 'fig util:install-script' to add them. Open a new terminal then rerun the doctor.

Fig ENV variables need to be at the very beginning and end of /Users/mlabenski/.zshrc

If you see the FIG ENV VARs in /Users/mlabenski/.zshrc, make sure they're at the very beginning (pre) and end (post). Open a new terminal then rerun the the doctor.

If you don't see the FIG ENV VARs in /Users/mlabenski/.zshrc, run 'fig util:install-script' to add them. Open a new terminal then rerun the doctor.

Let's see what fig diagnostic tells us...

Compatible shell: pass
Bundle path: pass
Autocomplete enabled: pass
CLI installed: pass
CLI tool path: pass
Accessibility enabled: pass
Autocomplete specs installed: pass
grep: /Users/mlabenski/.ssh/config: No such file or directory
SSH config: fail

SSH config is missing Include ~/.fig/ssh

To fix: Re-enable SSH integration from the Fig menu
Tmux integration: pass
iTerm integration: fail

2021-08-31 15:45:03.620 defaults[73666:7202158] 
Domain com.googlecode.iterm2 does not exist

The iTerm API server is not enabled.

fig-iterm-integration.scpt is missing.
Hyper integration: fail

fig-hyper-integration plugin is missing!
grep: /Users/mlabenski/.hyper.js: No such file or directory

fig-hyper-integration plugin needs to be added localPlugins!
VSCode integration: pass
Installation script: pass
Secure keyboard input: pass
PATH and PseudoTerminal PATH match: pass
Fig integration version: fail
</code>

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [German] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/mlabenski/.fig/bin/fig
Accessibility: true
Number of specs: 206
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/mlabenski/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/curl/bin:/Users/mlabenski/.nvm/versions/node/v15.4.0/bin:/Users/mlabenski/.yarn/bin:~/go/bin:/usr/local/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/mlabenski/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (72906) - ttys004
Current working directory: /Users/mlabenski
Current window identifier: 68461/% (com.apple.Terminal)</pre>
</p>
</details>

### Environment

```bash
Version 1.0.47 (B257) [German] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/mlabenski/.fig/bin/fig
Accessibility: true
Number of specs: 206
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/mlabenski/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/curl/bin:/Users/mlabenski/.nvm/versions/node/v15.4.0/bin:/Users/mlabenski/.yarn/bin:~/go/bin:/usr/local/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/mlabenski/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (72906) - ttys004
Current working directory: /Users/mlabenski
Current window identifier: 68461/% (com.apple.Terminal)
PATH: /usr/local/opt/curl/bin:/Users/mlabenski/.nvm/versions/node/v15.4.0/bin:/Users/mlabenski/.yarn/bin:~/go/bin:/usr/local/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/mlabenski/.fig/bin
FIG_INTEGRATION_VERSION: ???
```

**Comment by mschrage** [comment]
Hey @marklabenski! Thanks for reporting this.

It looks like Fig's shell integration isn't being set up correctly. Would you mind sharing your .zshrc?

**Comment by marklabenski** [comment]
Here is my .zshrc 

<code>
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH=/Users/mlabenski/.oh-my-zsh


lolbanner () {
    figlet -f ~/figlet-fonts/3d.flf -c -w `tput cols` $1 | lolcat
}

generate-pw () {
    openssl rand -base64 12 | sed 's/[=/+]//'g | tee >(pbcopy) >(lolbanner)
}

freemem () {
    killall -KILL Dock
    killall Finder
    killall SystemUIServer
}  

ZSH_THEME="agnoster"

plugins=(git)

source $ZSH/oh-my-zsh.sh

export PATH="$HOME/.yarn/bin:~/go/bin:/usr/local/bin/:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/usr/local/opt/curl/bin:$PATH"
source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


#### FIG ENV VARIABLES ####
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
</code>

**Comment by marklabenski** [comment]
Nevermind, I used `fig util:install-script` again and it's now working. I missed the comment in the doctor tool
Thanks for you help anyways!
