### ISSUE TITLE
Completing with Fig inserts '(' or '

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#419]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
When I press enter on a suggestion, Fig will enter a '(' or "'" rather than the suggestion.

### Environment

```bash
N/A
```

**Comment by mschrage** [comment]
The fix for this is running `stty -istrip` in the affected terminal window.

**Comment by fwesss** [comment]
Duplicate of https://github.com/withfig/fig/issues/405
