### ISSUE TITLE
Improve fish completion support

### ISSUE THREAD

**Issue by j-f1** [withfig/fig#42]
**Is your feature request related to a problem? Please describe.**
As mentioned in Slack, Fig is currently unable to provide full support for Fish because it does not have a way of reading the current command. There actually is a way to do this!

**Describe the solution you'd like**

1. Ask the user to add a function to `config.fish` like this:
	  ```fish
	  function read_commandline --on-signal SIGUSR1
		  fig commandline:read $fish_pid (commandline) (commandline -C) 
	  end
	  function write_commandline --on-signal SIGUSR2
		  commandline (fig commandline:write $fish_pid)
		  commandline -C (fig commandline:write-cursor $fish_pid)
	  end
	  ```
2. when you detect keyboard input, run `kill -USR1 [shell pid]` from Fig
3. when the user accepts a suggestion, run `kill -USR2 [shell pid]` from Fig and provide the new command input and cursor position when requested

(it might be better to use other available signals).

**Comment by mattschrage** [comment]
Ah this is super interesting. I did know about `commandline` but was struggling to figure out a way to invoke it without doing something really hacky like simulating a keypress. This is a very clever approach that could potentially be ported over to `bash` as well.

Thanks so much for sharing this :)

**Comment by mattschrage** [comment]
Fish support is landing in v1.0.40 - thanks for giving me this tip!
