### ISSUE TITLE
Show suggestions even if there is environment variable before the command

### ISSUE THREAD

**Issue by christophe-petitjean** [withfig/fig#420]
`fig` doesn't trigger itself when I append environment variable before command, for example typing `VAR=1 npm run ...` doesn't show the autocomplete window

**Comment by mschrage** [comment]
<img width="494" alt="Screen Shot 2022-03-09 at 2 26 00 PM" src="https://user-images.githubusercontent.com/3155109/157549054-fe670509-04c1-4557-b9cd-8b1c86b10829.png">

Support for environment variable prefixes has been added!
