### ISSUE TITLE
can not show

### ISSUE THREAD

**Issue by baobao971213** [withfig/fig#421]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [搜狗拼音] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/caiyuanhang/.fig/bin/fig
Accessibility: true
Number of specs: 206
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/caiyuanhang/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/caiyuanhang/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: <Unknown Process> (???) - not
Current working directory: <Unknown Working Directory>
Current window identifier: 13046/78BF453B-DBE6-4785-A664-77FA198D18B1% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Can you try running `fig diagnostic` directly in your terminal and share the output here?

It seems like there may been an issue with the shell integration?

**Comment by fwesss** [comment]
@baobao971213 Are you still having trouble getting the autocomplete window to show?
Can you run `fig update` to upgrade to 1.0.49? Lots of fixes in the newest version that may fix the issue.

**Comment by mschrage** [comment]
Closing since we need more information to debug what's going on.
