### ISSUE TITLE
Autocomplete always results in single quote ( ' )

### ISSUE THREAD

**Issue by jazzdan** [withfig/fig#422]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

See video here: https://www.loom.com/share/e7bcbf5d6b914618a0e2a5b5bea29669

When I select an item from the autocomplete list, and press enter, it always results in a single quote, no matter what the item actually is.
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/dan/.fig/bin/fig
Accessibility: true
Number of specs: 190
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/dan/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/bison/bin:/Users/dan/.nvm/versions/node/v14.15.0/bin:/Users/dan/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/dan/.fig/bin:/Users/dan/.antigen/bundles/zsh-users/zsh-autosuggestions:/Users/dan/.antigen/bundles/joel-porquet/zsh-dircolors-solarized:/Users/dan/.antigen/bundles/softmoth/zsh-vim-mode
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (51838) - ttys013
Current working directory: /Users/dan/devel/log-viewer
Current window identifier: 270/1205E88567-F09F-444C-852D-BF33FD5A623A% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by fedeci** [comment]
Duplicate of #405

**Comment by jazzdan** [comment]
Whoops, sorry. I could have sworn that I searched for "quote" in the issues! Will close.
