### ISSUE TITLE
Popup in wrong terminal when both VSCode and Hyper open

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#424]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
Sometimes when both VSCode and Hyper are open side by side, the Fig popup will appear in the wrong app.

For example, I type `cd ` in VSCode terminal and the popup opens in Hyper.

### Environment

```bash
N/A
```

**Comment by mschrage** [comment]
This will be fixed in the next build (v1.0.491)
