### ISSUE TITLE
Fig is override the iterm smart history navigation (using the up arrow)

### ISSUE THREAD

**Issue by netanel0531** [withfig/fig#425]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
Iterm have this feature - When start typing in Iterm, and then look for history using the UP arrow it will only show history starting with the text typed. (e.g typing "fig" and pressing the UP arrow will navigate through commands in history that start with "fig" - like "fig --help", "fig source" and so on depends on the history).

The issue is that when using Fig on Iterm and pressing UP, the typed text is ignored and the action in cycling through recent history chronological without filtering.
I've looked a little and it seems that while using Fig I can get a similar, but more complex, action using typing and hitting ctrl+R (shows popup with history relevant to the text) - But I'm looking for the simple UP arrow functionality defaulted for Iterm. 

### Environment

```bash
Version 1.0.47 (B257) [ABC]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/nbrisk/.fig/bin/fig
Accessibility: true
Number of specs: 188
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/nbrisk/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/nbrisk/.jenv/shims:/Users/nbrisk/.jenv/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Users/nbrisk/.nvm/versions/node/v6.17.1/bin:/opt/apache-maven-3.5.4/bin:/opt/local/bin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/opt/local/sbin:~/work/akamai/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin:/Users/nbrisk/.fig/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/opt/fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???
PATH: /Users/nbrisk/.jenv/shims:/Users/nbrisk/.jenv/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Users/nbrisk/.nvm/versions/node/v6.17.1/bin:/opt/apache-maven-3.5.4/bin:/opt/local/bin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/opt/local/sbin:~/work/akamai/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin:/Users/nbrisk/.fig/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/opt/fzf/bin
FIG_INTEGRATION_VERSION: 4
```

**Comment by fwesss** [comment]
@netanel0531 Do you use oh-my-zsh? If so, try moving the line `source $ZSH/oh-my-zsh.sh` to the very end of your .zshrc.
