### ISSUE TITLE
Tabby (formerly Terminus) integration

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#429]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
I use tabby as my terminal and would love for Fig to work with it.
https://github.com/Eugeny/tabby

**Comment by mschrage** [comment]
Just wanted to give an update here.

The @Eugeny, the maintainer of Tabby, very helpfully put together an example plugin that we can use as a template for our own integration: https://github.com/Eugeny/tabby-event-demo/blob/master/src/index.ts

to get it running on a Mac:
```
yarn TABBY_PLUGINS=$(pwd)
/Applications/Tabby.app/Contents/MacOS/Tabby --debug
```

**Comment by brendanfalk** [comment]
Integration is live as of v1.0.54!

**Comment by mschrage** [comment]
A few tweaks still need to be made #798.
