### ISSUE TITLE
Fig pasting invalid input into tmux pane

### ISSUE THREAD

**Issue by bitterbit** [withfig/fig#433]
### Description:
was using: tmux, neovim, starship prompt inside iTerm2

fig connected to the tmux session with a smaller screen, causing the effect in the image.
Also the command in the bottom left is partially not mine, I was trying to move a file and I guess fig added some suffix to this command

<img width="1552" alt="Screen Shot 2021-09-03 at 22 15 39" src="https://user-images.githubusercontent.com/4591339/132055725-5f333250-16b2-4d18-b204-cd3d8a0bacf8.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/gal/.fig/bin/fig
Accessibility: true
Number of specs: 195
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/gal/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: fig
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/zsh/5.8_1/bin/zsh (23962) - ttys008
Current working directory: /Users/gal/dev/interneto/sites/website-galtashma
Current window identifier: 820/%1 (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by bitterbit** [comment]
It happened again today

<img width="1552" alt="Screen Shot 2021-09-04 at 14 55 06" src="https://user-images.githubusercontent.com/4591339/132093599-6139f4d7-95d9-41d8-b4f2-2fc1eb291b41.png">


```
zsh -lic 'fc -R; fc -ln 1' | /Users/gal/.fig/bin/fig_callback rwcGf
bash -lic 'fc -ln 1' | /Users/gal/.fig/bin/fig_callback BIgfA
fish -lic 'history search' | /Users/gal/.fig/bin/fig_callback eZfqd

website-galtashma/sanity-dashboard on  master [?] via  v14.17.6 took 1m12s
❯

website-galtashma/sanity-dashboard on  master [?] via  v14.17.6
❯ zsh -lic 'fc -R; fc -ln 1' | /Users/gal/.fig/bin/f
ig_callback rwcGf
```

**Comment by bitterbit** [comment]
It seems to happen once every 12-24 hours, pasting the a few callback lines into whatever tmux pane is focused.

The lines
```
zsh -lic 'fc -R; fc -ln 1' | /Users/gal/.fig/bin/fig_callback soVVJ
bash -lic 'fc -ln 1' | /Users/gal/.fig/bin/fig_callback IvGSB
fish -lic 'history search' | /Users/gal/.fig/bin/fig_callback WZVmA
```

**Comment by bitterbit** [comment]
After closing everything and reopening, then writing "ls -al"
 
<img width="1552" alt="Screen Shot 2021-09-05 at 12 36 46" src="https://user-images.githubusercontent.com/4591339/132122222-ec2b059c-d773-482a-9cfa-f70aa0c11468.png">

**Comment by bitterbit** [comment]
[Screen Recording 2021-09-05 at 12.39.50.zip](https://github.com/withfig/fig/files/7111346/Screen.Recording.2021-09-05.at.12.39.50.zip)
Zipped video

**Comment by SeparateRecords** [comment]
Should be fixed now!
