### ISSUE TITLE
After many white spaces continues offering autocomple

### ISSUE THREAD

**Issue by eduzen** [withfig/fig#438]
### Description:
Not only offers options that are rare and are obstacles for the usage of the terminal, also it doesn't disappear when you hit spaces for maybe doing a pipe

<img width="447" alt="Screenshot 2021-09-06 at 20 45 49" src="https://user-images.githubusercontent.com/8366343/132253673-964859cb-cacc-4622-b8fa-2ea6415d9df0.png">

maybe what I was expecting is that if I press two times the space bar is like pressing esc, or I'm expecting that from a whitespace doesn't offer autocompletion.

I hope it helps!

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.48 (B264)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.48 (B264) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/eduardoenriquez/.fig/bin/fig
Accessibility: true
Number of specs: 197
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/eduardoenriquez/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/libpq/bin:/Users/eduardoenriquez/.poetry/bin:/Users/eduardoenriquez/.pyenv/shims:/Users/eduardoenriquez/.pyenv/bin:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/eduardoenriquez/.pyenv/shims:/Users/eduardoenriquez/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/eduardoenriquez/.cargo/bin:/usr/ucb:/Users/eduardoenriquez/.fig/bin:/Users/eduardoenriquez/.fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/git/2.33.0/bin/git (99791) - ttys003
Current working directory: /usr/local/Homebrew
Current window identifier: 14158/E2878137-F644-41FA-B9A7-22E6750744F8% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
@eduzen this is currently the expected behavior but I like your suggestion that inserting multiple spaces could behave like escape! Seems like a good compromise.

**Comment by eduzen** [comment]
oki thanks for the response!
