### ISSUE TITLE
Adding a built-in "processor" icon

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#439]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description

I think it would be good to have a "processor" icon built in, since it's a pretty general concept. It would be useful in compilers (eg. `cargo`, `go`) and binary managers (eg. `rustup`). Probably more uses I can't think of off the top of my head.

### Motivation

While writing the spec for `deno`, I wanted to add an icon for the compilation targets. There's not really a fitting icon... "string" is the closest, but it's not great.

This is what I came up with as a stop-gap solution (it's supposed to look like a CPU, top-down)

![CPU Icon](https://user-images.githubusercontent.com/52195359/132280267-833df542-0cb9-41c4-a815-e982389f19e2.png)
![Icon in situ](https://user-images.githubusercontent.com/52195359/132280618-9f123c71-064f-4d57-96c9-601bf3aa4e57.png)

This icon is **not good**, but it's the best I can come up with 😆

**Comment by mschrage** [comment]
Good enough for me! We can always update it in the future :)

I've added it as `cpu` and it will be available in the next build (v1.0.49)!

**Comment by SeparateRecords** [comment]
If it's ever relevant, [here's the icon at 32x32, 64x64, and 512x512](https://drive.google.com/file/d/1ZpKBg5vqE0OOo0Cl3Qdn3PB_8oNsC7eD/view?usp=sharing).
