### ISSUE TITLE
Fig does not work after system restart

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#444]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
Fig will not work after a system restart unless Fig is manually restarted after startup.

#### Reproduce
1. Have Fig working in terminal
2. Restart computer
4. Fig will not popup in terminal
5. Restart Fig
6. Fig now works

### Environment

```bash
N/A
```

**Comment by mschrage** [comment]
@fwesss can you ask this user to see if Fig is included in their Login Items (in System Preferences)?

**Comment by fwesss** [comment]
@mschrage I can reproduce on my end and it is included in my Login Items

**Comment by mschrage** [comment]
Hmm, so if the Fig icon icon is in the menubar, then all of the Login Item stuff is working. Can you see if anything stands out in the logs if you run `fig debug logs`?
