### ISSUE TITLE
Fig deleting bg processes in bash

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#445]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
Background processes are deleted when bringing background processes to the foreground in bash.

#### To reproduce
```bash
$ vi &
[1] 8196
$ fg
bash: warning: deleting stopped job 1 with process group 8196
fg
$ jobs
```

Instead of bringing the process to the foreground, it's deleted. Running `jobs` will not show any bg processes.

### Environment

```bash
N/A
```

**Comment by SeparateRecords** [comment]
Fixed!
