### ISSUE TITLE
[BUG] Pressing tab replaces existing command with last word

### ISSUE THREAD

**Issue by yebrahim** [withfig/fig#45]
**Summary:**
When Fig shows multiple options as I type a prefix, if I press Tab, the last prefix replaces the entire command. Pressing Enter replaces the entire command with the first option instead.

**Steps to Reproduce:**
This doesn't seem to happen everywhere, but here are few reproducible steps for me:
Tab:

1. Type `cd /Us` (note uppercase U), Fig shows autocomplete menu with options: `Users` and `usr`.
1. Press Tab.

Enter:

1. This time, type `cd /us` (lowercase u), Fig shows autocomplete menu with the same two options.
1. Press Enter.

**Expected Results:**
I'm not sure what Fig's default behavior is, but it should either do nothing (which is what happens if I typed a lowercase U in step 1), or it should select the first highlighted option and continue.

**Actual Results:**
Tab:
Fig replaces the entire line with just `us`, and the keybuffer has `cd /us`.
Autocomplete is still open with the same options btw.

Enter:
Fig replaces the entire line with just `Users/`, and the keybuffer has `cd /Users/`.

**System information:**
OS: MacOS Big Sur 11.0.1
Terminal: (MacOS Terminal, iTerm2, etc)
Version of Fig: 1.0.39

**Comment by falky97** [comment]
Wow great catch! You can change the way tab and enter work in Fig's Settings: https://withfig.com/docs/support/settings (autocomplete.tab and autocomplete.enter).

This is an obvious bug with any prefix insert. We aren't accounting for capitalisation. I will fix!

**Comment by falky97** [comment]
This is fixed. Just right-click and reload Fig and it will work 😄 

![image](https://user-images.githubusercontent.com/4949076/113974811-6870c480-97f3-11eb-98c5-7e6eba135ff3.png)

Please keep reporting issues - we will fix them!!

**Comment by yebrahim** [comment]
Thanks for pushing out a fix so fast! The Tab bug is fixed, the Enter bug still persists.

**Comment by falky97** [comment]
Okay I will re-open.

I don't think I'm fully understanding the enter bug. Could you please explain it again?

**Comment by yebrahim** [comment]
It's basically the "insert" and "insertOrPrefix" behavior, now that I got some time to play with the settings. Both of these just cause Tab or Enter to replace the entire command to be replaced. This happens in Bash for me but not in zsh.
Type `cd /Us`, hit Tab or Enter with the "insert" or "insertOrPrefix" behavior, the entire line turns to `/Users` and is out of sync with the keybuffer.

**Comment by mschrage** [comment]
This seems like it was an issue with our bash integration, which has been rewritten as of v1.0.46. I'm closing this issue but will reopen if this behavior still occurs @yebrahim!
