### ISSUE TITLE
Fig nomore work on macOS Monterey

### ISSUE THREAD

**Issue by Faisal50x** [withfig/fig#452]
### Description:
> The script at “/Users/macbook/.config/iterm2/AppSupport/Scripts/AutoLaunch/fig-iterm-integration.scpt” failed:

> /Users/macbook/Library/Application Support/iTerm2/Scripts/AutoLaunch/fig-iterm-integration.scpt: execution error: sh:   > /Users/macbook/.fig/tools/iterm-api-credentials: No such file or directory (1)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.0|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/macbook/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: true
Keybindings path: <none>
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: false
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by jaenwawe** [comment]
Hi!  Did you get Fig working yet?
