### ISSUE TITLE
Red background

### ISSUE THREAD

**Issue by hedinne** [withfig/fig#453]
Hi,
Since last week (I think), there has been red background behind the Fig window. The background also bleeds out when the window isn't visible.

I'm using Zsh and this happens in iTerm, Terminal, and VS Code.

https://user-images.githubusercontent.com/7573694/133065530-0df0d848-0528-42ed-8502-d14138774e13.mp4

**Comment by mschrage** [comment]
Hey @hedinne! It looks like you have the "Force Popup to Appear" setting enabled. This is a developer setting used for debugging. 

You can toggle it off by clicking the Fig menubar icon > Integrations > Developer > Force Popup to Appear

**Comment by hedinne** [comment]
Thank you. That fixed it.
