### ISSUE TITLE
Whenever Fig is running my keyboard ALT+TAB no longer works

### ISSUE THREAD

**Issue by icampana** [withfig/fig#456]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Seems to be happening lately, had to disable Fig for it to work, I just quit Fig and the ALT+TAB combination works again.
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.48 (B264)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.48 (B264) [U.S. International - PC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/icampana/.fig/bin/fig
Accessibility: true
Number of specs: 197
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/icampana/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin:/tmp/fnm_multishells/52897_1630990369832/bin:/usr/local/sbin:/opt/homebrew/bin:/Users/icampana/.pyenv/shims:/Users/icampana/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/icampana/.fig/bin:/opt/homebrew/bin:/opt/homebrew/opt/fzf/bin:/Users/icampana/.composer/vendor/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (6215) - ttys002
Current working directory: /Users/icampana/Sites/kinja-mantle/kinja-magma
Current window identifier: 365/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Thanks for reporting this @icampana! This should be fixed in the next release v1.0.49!
