### ISSUE TITLE
Unexpected behavior with multiple VSCode windows

### ISSUE THREAD

**Issue by rk-yen** [withfig/fig#457]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
![Screen Shot 2021-09-15 at 7 37 15 PM](https://user-images.githubusercontent.com/4944665/133531178-5ef48ccd-12c9-47d3-8a47-82acf25d6dc8.png)
The completion hints are showing up in the wrong VSCode window. Attached is a screenshot. The left window is where I entered `git `, but the right window shows up the completion hints window/overlay.

### Environment

```bash
Version 1.0.48 (B264) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/raviy/.fig/bin/fig
Accessibility: true
Number of specs: 218
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/raviy/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/raviy/.nvm/versions/node/v12.20.1/bin:/Users/raviy/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/raviy/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (1861) - ttys008
Current working directory: <redacted>
Current window identifier: 101/% (com.apple.Terminal)
PATH: /Users/raviy/.nvm/versions/node/v12.20.1/bin:/Users/raviy/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/raviy/.fig/bin
FIG_INTEGRATION_VERSION: 4
```
```

**Comment by mschrage** [comment]
Thanks for reporting @rk-yen! This is fixed in the next release - v1.0.49 :)
