### ISSUE TITLE
Red background appearing even after restarting

### ISSUE THREAD

**Issue by RayKay91** [withfig/fig#458]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Red background appears for fig pop up, and a thin red line appears when there is no pop up

<img width="143" alt="Screenshot 2021-09-16 at 10 31 14" src="https://user-images.githubusercontent.com/61206305/133588093-c85f02b3-998a-46cf-9caf-0d43839c79d0.png">
<img width="683" alt="Screenshot 2021-09-16 at 10 31 07" src="https://user-images.githubusercontent.com/61206305/133588098-1bf6bcd6-3147-4c87-8187-424860fce5a1.png">

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.48 (B264)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.48 (B264) [Debug] [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ray/.fig/bin/fig
Accessibility: true
Number of specs: 196
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/ray/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/ray/Library/Android/sdk/tools:/Users/ray/Library/Android/sdk/platform-tools:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/ray/.cargo/bin:/usr/ucb:/Users/ray/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by fwesss** [comment]
@RayKay91 
Looks like debug mode is on. Did this start happening randomly?

To fix it, uncheck "Force Popup to Appear" in the Fig menu.

<img width="521" alt="Screen Shot 2021-09-16 at 12 19 09 PM" src="https://user-images.githubusercontent.com/10150898/133672365-83887d81-aead-494d-9525-5744b07b8cc5.png">

**Comment by RayKay91** [comment]
Ahh dope thanks!

No I think it was me that messed around with the settings when it wasn't popping up for some reason/was slow to pop up and I must've clicked it.
