### ISSUE TITLE
Check $ZDOTDIR for zsh config location

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#459]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
Our scripts have the zsh config location hardcoded to $HOME. It is possible to use another location and set it with $ZDOTDIR.

We should check for the existence of $ZDOTDIR then fallback to $HOME if unset when determining zsh dotfile locations.

### Environment

```bash
N/A
```

**Comment by grant0417** [comment]
We should now respect `$ZDOTDIR` across Fig, please open another issues if you run into it not being respected somewhere.
