### ISSUE TITLE
figterm integration does not work after rebooting in macOS

### ISSUE THREAD

**Issue by cheuk-cheng** [withfig/fig#461]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

figterm integration is not activated in the first terminal tab after rebooting on a Macbook Pro running Big Sur 11.5.1.  figterm integration works fine in other terminal tabs.  To reproduce this issue, open a new (bash) terminal window in Big Sur.  Then create a few terminal tabs in the same window and restart the Macbook Pro machine.  After rebooting, the terminal window will be relaunched automatically but figterm integration is not enabled in the first terminal tab.
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.48 (B264)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.48 (B264) [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/admin/.fig/bin/fig
Accessibility: true
Number of specs: 199
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/admin/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/admin/Library/Python/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/binutils/bin:/Applications/Visual
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @cheuk-cheng! Thanks for letting us now.

Can you elaborate on how you know `figterm` isn't working?

**Comment by cheuk-cheng** [comment]
Thanks.  If I switched between the relaunched terminal tabs I noticed that in one of the terminal tabs figterm would not show any auto completions in bash.  Auto completions worked fine in other tabs.

**Comment by mschrage** [comment]
Hmm very strange. Want to jump on a call this week to debug? https://calendly.com/mschrage/30min

**Comment by SeparateRecords** [comment]
Should be fixed now!
