### ISSUE TITLE
Allow generating dynamic options based on subcommands arguments

### ISSUE THREAD

**Issue by leosvelperez** [withfig/fig#463]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:

Currently, we can dynamically generate fulls specs or suggestions for arguments, but we don't have a way to generate dynamic options. This limits the ability to have options depending on the argument being passed to a subcommand.

Consider the following scenario:

Nx CLI allows us to [run many different generators provided by plugins](https://nx.dev/latest/react/generators/using-schematics#invoking-plugin-generators). For example:

```bash
nx generate @nrwl/workspace:library my-lib --buildable
```

Decomposing the previous example:

- `nx` is the command.
- `generate` is a subcommand.
- `@nrwl/workspace:library` is an argument for the subcommand. This is called a "generator" (do not confuse with Fig generators) and it represents what we are actually going to generate.
- `my-lib` (a positional argument matching the `--name` option) and `--buildable` are options.

Each Nx generator can have different options, therefore, based on the specified Nx generator (e.g. `@nrwl/workspace:library`), the options will be different. Also, there's not a fixed number of generators (more can be created by the community and individual Nx monorepos can have different sets of generators), so we can't just statically define their specs.

This is a perfect example where we can benefit from dynamic options. We need to resolve them based on the specified Nx generator (the argument for the `generate` subcommand).

### Alternatives

I tried to use the `generateSpec` option and dynamically generate the full spec for the `generate` subcommand, turning the above `@nrwl/workspace:library` into a subcommand instead of an argument, by doing:

- Added a `generateSpec` to the `generate` subcommand.
- In that function, resolved the list of installed plugins in the monorepo (user working directory) that contain generators. Running `nx list` and parsing the output to get the installed plugins that contain generators.
- Resolved the list of generators per resolved plugin. Running `nx list <plugin-name>` (per plugin) and parsing the output to get the generators.
- Resolved the list of options per resolved generator. Running `nx generate <generator-name> --help` (per generator in each plugin) and parsing the output to get the options.

As it can be seen in the above process, a lot needs to happen in order to get the full spec. A monorepo with just 3 plugins each containing 5 generators would require 19 different shell command executions and parsing to get what's needed for the spec. An average Nx monorepo would contain more than that.

I had no success with it (in a small monorepo with just a few plugins), the generation fails more often than not with a timeout error in the development environment. Having to load all the generators and their definition upfront is not performant.

By having the ability to dynamically generate options, we can lazy load parsing the options to when they are needed and only get the options for the specified generator.

**Comment by mschrage** [comment]
@leosvelperez thanks for writing this up. It seems like we could definitely do a better job handling dynamic options (maybe by introducing an API like `generateOptions).

**Comment by leosvelperez** [comment]
@mschrage as you suggested, something like `generateOptions` that receives the specified args and the `executeShellCommand` should do it. We should be able to configure it to be cached as well. There might be other needs I can't think of right now, but given we currently don't have the ability to do this and most specs are fine like that, this should be sufficient for the time being.

**Comment by SeparateRecords** [comment]
This will be fixed soon! We're adding subcommands and options to args through `loadSpec` on a `Fig.Arg`, and likely will add some sugar with `options` and `subcommands` on it too.
