### ISSUE TITLE
Add `$HOME` support

### ISSUE THREAD

**Issue by duboiss** [withfig/fig#468]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Feature Details

Currently autocompletion for `~` path seems to work properly.
But this is not the case for his alias `$HOME`.

![image](https://user-images.githubusercontent.com/29716703/134207527-9e40bc42-9ce6-4bad-96e6-3f5517f69a19.png)

![image](https://user-images.githubusercontent.com/29716703/134207577-9c1899ff-4bec-4005-a0df-884c7f9ad8d4.png)

It would be nice if `$HOME` is available and matches `~`, autocompletion is also active.

**Comment by mschrage** [comment]
We can do a naive match on the `$HOME` variable to provide the same behavior as `~`. I think the ideal solution would be for the autocomplete engine to expand the environment variables just like the shell does.

**Comment by mschrage** [comment]
This is supported in the latest version of Fig!
