### ISSUE TITLE
Show/Hide Fig in the Menu Bar

### ISSUE THREAD

**Issue by daanrongen** [withfig/fig#47]
As a user I would like to keep my menu bar clean and not have the icon displayed. The Fig icon in the menu bar only disappears when the user quits Fig, and it doesn't trigger an automatic reopen upon opening the command line app. I also think the interactions in the Fig menu could easily be moved elsewhere.

**Comment by mattschrage** [comment]
I've added this to the next build (v1.0.40)! Can be enabled by running `fig settings app.hideMenubarIcon true`.

**Comment by mattschrage** [comment]
Quick question: When you say ` it doesn't trigger an automatic reopen upon opening the command line app` is that the behavior you want? Should Fig automatically relaunch when you open iTerm or Terminal.app?
