### ISSUE TITLE
Fig closed after 7-10 mins on Mac M1

### ISSUE THREAD

**Issue by LarsMoran** [withfig/fig#470]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
Fig closing after 10 mins automatically without any errors. I didn't find any settings for it. Should it be the problem with m1 cpu or bug?

### Environment

```bash
M1
```

**Comment by mschrage** [comment]
Hey @LarsMoran! Thanks so much for reporting this. Have you been able to get Fig working again?

**Comment by danil0110** [comment]
I have the same issue, I have been noticing recently that my fig isn't running anymore. But I haven't measured the time when it closes.
And it's probably the fig's bug and not M1 CPU, because I am on Macbook Pro 16" with Intel CPU.

**Comment by mschrage** [comment]
I will check the crash reporting. We recently made some large changes and maybe something is breaking with the new update.

**Comment by mschrage** [comment]
@danil0110 @LarsMoran I have pushed a fix for this issue. Update to the latest version (v1.0.49 B270) by running `fig update` and the crashes should go away!

**Comment by danil0110** [comment]
@mschrage we'll see, thanks!
