### ISSUE TITLE
Fig extension in VSCodium

### ISSUE THREAD

**Issue by jiserra** [withfig/fig#473]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
The feature is simple: Make the VSCode extension to work in [VSCodium](https://vscodium.com). I tried to install the VSCode extension, but it doesn't let me install it because (of course) I don't have VSCode. VSCodium shares the same source code as VSCode but without any of the tracking, so I'm sure it should work with Fig.

Thanks!

**Comment by mschrage** [comment]
Thanks for letting us know @jiserra! This should be a really easy fix. :)
