### ISSUE TITLE
Auto quit sometimes

### ISSUE THREAD

**Issue by mopig** [withfig/fig#475]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.49 (B269)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.49 (B269) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/abc/.fig/bin/fig
Accessibility: true
Number of specs: 218
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/abc/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/sbin:/usr/local/opt/curl/bin:/Users/abc/.nvm/versions/node/v16.10.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/abc/.cargo/bin:/Users/abc/.fig/bin:/Users/abc/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/abc/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/Users/abc/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitignore:/Users/abc/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/heroku:/Users/abc/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:/Users/abc/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/lein:/Users/abc/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/Users/abc/.antigen/bundles/lukechilds/zsh-nvm:/Users/abc/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/abc/.antigen/bundles/zsh-users/zsh-completions:/Users/abc/.antigen/bundles/zsh-users/zsh-autosuggestions:/Users/abc/.antigen/bundles/romkatv/powerlevel10k
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 97/7CFD0D70-1B78-4100-A146-10C21E559800% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @mopig! Thanks for reporting this. It seems like a few other people have run into this as well (#470 #476). I'll investigate next week.

**Comment by mschrage** [comment]
@mopig I think I've figured out what was going wrong. Try updating the the most recent version of Fig (v1.0.49 B270). This should resolve the issue.

**Comment by mopig** [comment]
@mschrage Alread fixed.
