### ISSUE TITLE
Fig launch / crashing bug, version: 1.0.49 | macOS | zsh | hyper

### ISSUE THREAD

**Issue by ShawnCockburn** [withfig/fig#476]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

first of all, Fig is the best thing since sliced bread and mostly never had an issue with the tool that a restart wouldn't fix.

after the most recent update, the tool no longer works I have tried restarting it and the computer and it still won't autocomplete and crashes sometimes on any 'fig' CLI command.

video of the issue:
[Fig-Issue Youtube](https://youtu.be/j5z3BJx1f_o)
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.49 (B269)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.49 (B269) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/shawn/.fig/bin/fig
Accessibility: true
Number of specs: 208
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/shawn/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/shawn/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @ShawnCockburn! First off, thanks so much for the kind words. Glad to hear that when Fig is working, you enjoy using it! ❤️

From the video, it looks like you are running the `fig` CLI command when the host application is not running.  Try running `fig launch` instead? Then once you see the Fig icon in your menu bar, try running `fig diagnostic` or just `fig`. 

If this doesn't solve the issue, let's set up sometime to call next week: https://calendly.com/mschrage/30min

**Comment by ShawnCockburn** [comment]
> Hey @ShawnCockburn! First off, thanks so much for the kind words. Glad to hear that when Fig is working, you enjoy using it! ❤️
> 
> From the video, it looks like you are running the `fig` CLI command when the host application is not running. Try running `fig launch` instead? Then once you see the Fig icon in your menu bar, try running `fig diagnostic` or just `fig`.
> 
> If this doesn't solve the issue, let's set up sometime to call next week: https://calendly.com/mschrage/30min

Thanks @mschrage !

I tried launching the app both ways on version 1.0.49 but the only fix I could find was restarting the entire machine.
for more context I use fig across two accounts at the same time (personal and work) not sure if there is some sort of conflict issue there..?

just updated to the latest version today and will get back to you / book in a call if the issue persists!

**Comment by ShawnCockburn** [comment]
@mschrage the bug seems to happen less in this version, however it's still happening intermittently.
booked in a call on Monday 🤙.

**Comment by mschrage** [comment]
Sounds good! @ShawnCockburn. Can you also share the output of `fig diagnostic` here:

**Comment by ShawnCockburn** [comment]
Here you go:

Version 1.0.49 (B270) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/shawn/.fig/bin/fig
Accessibility: true
Number of specs: 208
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/shawn/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/shawn/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (74370) - ttys006
Current working directory: /Users/shawn
Current window identifier: 74394/hyper:1d7457f6% (co.zeit.hyper)
PATH: /Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/shawn/.fig/bin
FIG_INTEGRATION_VERSION: 4

**Comment by ShawnCockburn** [comment]
Thanks, @mschrage for the help diagnosing the issue!

As far as I understand Matt said it was most likely a permissions issue with a specific file.

The fix that works for me (_in version 1.0.49 (B270)_) is force closing all fig processes in activity monitor:
<img width="1035" alt="Screenshot 2021-10-05 at 19 39 59" src="https://user-images.githubusercontent.com/60285801/136083637-7deebd9f-5cef-412c-92fd-e1e9c3d2d381.png">

then running this command to remove the conflicting temp file (caution this will delete the target file make sure the path is correct):
`sudo rm /tmp/fig.socket`
<img width="888" alt="Screenshot 2021-10-05 at 19 45 54" src="https://user-images.githubusercontent.com/60285801/136084321-00ec5cb3-e3c0-4d3d-9497-5c35eab319b5.png">

then reopen your hyper terminal and fig _should_ now be working.

Restarting the machine also works.
