### ISSUE TITLE
Fig keeps silently quitting

### ISSUE THREAD

**Issue by golergka** [withfig/fig#477]
### Description:

As I work on my computer, I keep finding Fig to have silently quit. There's no alert, no error window, nothing — and I'm not sure how I could investigate this further.
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.49 (B269)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.49 (B269) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/golergka/.fig/bin/fig
Accessibility: true
Number of specs: 208
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/golergka/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by fwesss** [comment]
@golergka Does it silently quit immediately after launching?

Try downloading a new dmg [here](https://fig.io/welcome?code=sen73-z72m-wz89-x9456c) and dragging it into /Applications to replace the one that's already there.

**Comment by estruyf** [comment]
@fwesss same on my end.

When I run `fig`, it shows the following:

![Uploading Screenshot 2021-09-28 at 08.50.26.png…]()

Running `fig launch` is successful, but immediately after launch, it stops working.

Also downloaded a new dmg and replaced it. Still the same experience.

**Comment by golergka** [comment]
> @golergka Does it silently quit immediately after launching?

Not immediately, no — that's the frustrating part. It works for some time, a couple of minutes, may be. Then, I don't actually notice the exact moment, I suddenly realise that the app is closed.

I'll try to re-download the app as you suggested and see if it happens still.

**Comment by mschrage** [comment]
> @fwesss same on my end.
> 
> When I run `fig`, it shows the following:
> 
> ![Screenshot 2021-09-28 at 08 50 26](https://user-images.githubusercontent.com/2900833/135037861-34c90805-6e8c-41c8-9f08-11f35fd2f8d8.png)
> 
> Running `fig launch` is successful, but immediately after launch, it stops working.
> 
> Also downloaded a new dmg and replaced it. Still the same experience.

Can you run `fig debug app` - this should print out a bunch of logging that might narrow down the issue

**Comment by mschrage** [comment]
@golergka @estruyf I figured out what was going wrong. There was an issue with the beta that I had fixed last week, but it looks like the patch didn't make it into the final release.

Updating Fig to the latest version by running `fig update` should work!

**Comment by estruyf** [comment]
It seems this fixed it. `fig` is back up and running.
