### ISSUE TITLE
Hyper terminal integration not working  

### ISSUE THREAD

**Issue by ehsan2793** [withfig/fig#483]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

when opening three windows on the hyper terminal, fig can not detect the third window, and it keeps repeating everything two times.
for example, when I type cd desktop and see the fig suggestion desktop, when i press enter, I get  cd Desktop/Desktop/ back

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.49 (B269)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.49 (B269) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ehsan/.fig/bin/fig
Accessibility: true
Number of specs: 208
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/ehsan/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 339453/hyper:11807cb5% (co.zeit.hyper)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @ehsan2793! Thanks so much for reporting this.

Did you just download Fig or have you been using it for a while? You may need to restart Hyper for Fig to work correctly.

**Comment by ehsan2793** [comment]
Hi I have been using fig for last  2-3 weeks and I just love how easy it is to use however,

I don’t have this issue all the times but recently it started to show, fig auto connect stops working and I have to restart 
My other issue is that sometime when I'm cd into a file it repeats the file name 2 times , for example when i want to go to data folder, fig changes the  code  to  cd data/data

**Comment by ehsan2793** [comment]
This is my whole terminal

**Comment by mschrage** [comment]
@ehsan2793 it doesn't look like you attachment came through? You may need to upload it to Github directly.

What version of Hyper are you using? I can't seem to reproduce this.

Would you be open to jumping on a debugging call with me? https://calendly.com/mschrage/30min

**Comment by ehsan2793** [comment]
My hyper version is 3.1.3 and, and I set up an appointment for tomorrow

**Comment by mschrage** [comment]
Great! Talk then :)

**Comment by mschrage** [comment]
Closing this issue as Fig works with Hyper!
