### ISSUE TITLE
Fig interprets string literals in ZSH editbuffer

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#484]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Typing `cd hello\there` will result in a edit buffer that contains the a tab. "cd hello    here|"

<img width="791" alt="Screen Shot 2021-09-28 at 12 25 09 PM" src="https://user-images.githubusercontent.com/3155109/135152639-0ba97ddb-25e6-4fed-9447-1e714ada6a3a.png">

### Environment

```bash
n/a
```

**Comment by HaleTom** [comment]
Is this still reproducible?

I created a directory via `mkdir hellothere` and after typing (literals) `cd hello\t` I could select the suggestion and successfully change directory.

**Comment by mschrage** [comment]
I just checked and it looks like this issues is resolved as of v1.0.53 (if not earlier). Thanks for letting me know @HaleTom!
