### ISSUE TITLE
Breaks oh my fish agnoster theme

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#487]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
When using the agnoster theme from oh my fish, the prompt will be broken and only show 

<img width="259" alt="Screen Shot 2021-09-30 at 9 43 19 AM" src="https://user-images.githubusercontent.com/10150898/135496950-1e4d9d7e-6a13-4b2a-a007-df9bc58ddf49.png">

### Environment

```bash
N/A
```

**Comment by mschrage** [comment]
We've been unable to reproduce this. If you're still running into issues with `agnoster`, please open a new issue with your full fish config.
