### ISSUE TITLE
Multiple account issue?

### ISSUE THREAD

**Issue by shina** [withfig/fig#492]
### Description:

I'm a very new fig user. Installed it last night with my main MacOS user and everything worked as expected. This morning I switched to my work's user account and the app wasn't running there (as expected).

First I tried to just open the terminal and check if fig was running, but it wasn't.
Then I opened the app and started the setup for this account, when I clicked to open the settings, the app crashed.
I restarted and now it worked, however, I didn't have to give the permission again.
The onboarding ran but fig doesn't opened the suggestion box.

I hope this report is helpful o/

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.49 (B270)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.49 (B270) [U.S. International - PC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/leoshina/.fig/bin/fig
Accessibility: true
Number of specs: 213
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/leoshina/.deno/bin:/Users/leoshina/homebrew/opt/openjdk/bin:/Users/leoshina/homebrew/bin:/Users/leoshina/.nvm/versions/node/v14.17.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (14248) - ttys005
Current working directory: /Users/leoshina
Current window identifier: 44001/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by ShawnCockburn** [comment]
Hey @shina 

I had the exact same issue, see my issue (and the fix from @mschrage ): https://github.com/withfig/fig/issues/476#issuecomment-934680931

**Comment by grant0417** [comment]
I believe this should have been fixed a long time ago!
