### ISSUE TITLE
`cd ../` in a directory that has sibling directories not showing any autocomplete options

### ISSUE THREAD

**Issue by chadlavi-casebook** [withfig/fig#497]
### Description:

Note: this was only experienced in the VSCode integrated terminal, and quitting then re-opening VSCode resolved this issue. But I wanted to report it just so you all have the data.

Given a structure like this:

```
parent/
  child1/
  child2/
  child3/
  ...
  childN/
```

If I am in `parent/child1` and I type

```
cd ../
```

I am not getting the expected Fig autocomplete suggestions, i.e., 

```
child2/
child3/
...
childN/
```

instead, I'm just getting this, as if the pwd had no siblings:

<img width="378" alt="Screen Shot 2021-10-04 at 14 08 28" src="https://user-images.githubusercontent.com/45078010/135902080-ba135c01-4d39-468c-afc4-c9f5cca91940.png">

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.49 (B270)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.49 (B270) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Chad/.fig/bin/fig
Accessibility: true
Number of specs: 207
SSH Integration: false
Tmux Integration: true
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 🚧
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (2070) - ttys004
Current working directory: /Users/Chad/Dev/cbp-web-proxy
Current window identifier: 357/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
@chadlavi-casebook @raulcontrerasrubio it's been a while! Are you able to reproduce this now?

I think we might be able to close this issue.
