### ISSUE TITLE
cmd+delete leads to unexpected keybuffer state

### ISSUE THREAD

**Issue by siddseethepalli** [withfig/fig#5]
If I press cmd+backspace to delete the line before the cursor, it looks like the Fig context gets out of sync.

To repro, I can type `cd ` then `cmd+delete` followed by `cd ` and the second time the fig completion menu doesn't show up. The keybuffer context is `cd cd ` instead of the expected `cd `

**Comment by mattschrage** [comment]
Thanks for reporting this. This isn't a shell keybinding but a configuration in the terminal emulator you use. I think in the newest version (v1.0.32) we enable this by default. 

Let me know if you're still running into the issue. You can edit the Fig keybinding file directly in `~/.fig/user/keybindings`

**Comment by mattschrage** [comment]
For future reference, if you have the default command key bindings setup in iTerm or the Terminal.app, add the following to your `~/.fig/user/keybindings` file:

```
killWholeLine ⌘⌫
beginningOfLine ⌘←
endOfLine ⌘→
```
