### ISSUE TITLE
Fig spamming `nc` commands while typing

### ISSUE THREAD

**Issue by IamBlueSlime** [withfig/fig#50]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Every keystroke spawn a `nc` command, see the attached video. Latest iTerm2 and Fig.

https://user-images.githubusercontent.com/6763873/114852937-90f45200-9de3-11eb-8f5a-88e95229b494.mov

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.16.0|Version 1.0.40 (B188)|/usr/local/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.40 (B188)
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jeremy/.fig/bin/fig
Accessibility: true
Number of specs: 75
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/jeremy/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/python@3.8/bin:/usr/local/opt/gettext/bin:/usr/local/opt/binutils/bin:/usr/local/sbin:/Users/jeremy/.fig/bin:/Users/jeremy/.nvm/versions/node/v14.16.0/bin:/Users/jeremy/flutter/bin:/Users/jeremy/Library/Python/3.7/bin:/Users/jeremy/bin:/Users/jeremy/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/fish/3.2.2/bin/fish (16053) - ttys000
Current working directory: /Users/jeremy
Current window identifier: 170345/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mattschrage** [comment]
We switched out our IPC method from websockets to Unix sockets in the last build. Running `nc` on keypresses is the expected behavior. 

However, it seems like you might have a non-standard version of `nc`? Is that possible? Can you run `which nc` to verify?

---
In the meantime, you can fix this issue by opening `~/.config/fish/conf.d/fig.fish` and replacing the `nc` command with the following:

```
fig bg:fish-keybuffer (commandline -C) (commandline) 0 &
```

Here is a [snapshot](https://github.com/withfig/config/blob/v1.0.39/fig.fish) of the old version.

The reverts to using a websocket connection which is slightly slower, but should solve the issue.

**Comment by IamBlueSlime** [comment]
> We switched out our IPC method from websockets to Unix sockets in the last build. Running `nc` on keypresses is the expected behavior.
> 
> However, it seems like you might have a non-standard version of `nc`? Is that possible? Can you run `which nc` to verify?
> 
> In the meantime, you can fix this issue by opening `~/.config/fish/conf.d/fig.fish` and replacing the `nc` command with the following:
> 
> ```
> fig bg:fish-keybuffer (commandline -C) (commandline) 0 &
> ```
> 
> Here is a [snapshot](https://github.com/withfig/config/blob/v1.0.39/fig.fish) of the old version.
> 
> This reverts to using a websocket connection which is slightly slower, but should solve the issue until I can push a fix to the [withfig/config](https://github.com/withfig/config) repo.

```bash
❯ which nc
/usr/local/bin/nc
```

```
✦2 ❯ nc --version
netcat (The GNU Netcat) 0.7.1
Copyright (C) 2002 - 2003  Giovanni Giacobbi
```

It doesn't seems to be an override from an alternative `nc` from brew, could you confirm this?

**Comment by mattschrage** [comment]
I've pushed the [fix](https://github.com/withfig/config/commit/9008973916cc00925f9edb2d873fa16b43dc2bc0) to withfig/config.

If anyone else is having this issue, you can pull the latest version by rerunning the the "install/update script"
<img width="511" alt="Screen Shot 2021-04-15 at 8 36 30 AM" src="https://user-images.githubusercontent.com/3155109/114897018-b3777280-9dc5-11eb-8b73-fafc75c294dc.png">
