### ISSUE TITLE
PROMPT_COMMAND in bash breaks Fig

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#505]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
Many bash prompts and plugins utilize PROMPT_COMMAND. If such a plugin is installed, Fig will only work once per shell session.

Breaking prompts and plugins include:

- ohmybash prompts
- starship
- bash_it
- git-prompt.sh

### Environment

```bash
N/A
```

**Comment by RobertLowe** [comment]
Second, any change to PROMPT_COMMAND breaks fig

I was able to check it with `echo $PROMPT_COMMAND`

Works:

```bash
~ $ echo $PROMPT_COMMAND
__bp_precmd_invoke_cmd __iterm2_prompt_command __fig_post_prompt __bp_interactive_mode
```

It looks like __bp is iterm stuff

Doesn't work:

```bash
~ $ echo $PROMPT_COMMAND
custom_prompt
```

Works:

```bash
~ $ echo $PROMPT_COMMAND
__bp_precmd_invoke_cmd custom_prompt __fig_post_prompt
```

**Comment by mschrage** [comment]
See #888
