### ISSUE TITLE
zsh dirhistory plugin conflict

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#507]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
If the dirhistory zsh plugin is installed alongside Fig, pressing the up arrow will cause the shell to change directories.

https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/dirhistory/dirhistory.plugin.zsh

### Environment

```bash
N/A
```

**Comment by mschrage** [comment]
This should be fixed in v1.0.54 since we are changing how we get the editbuffer in zsh.
