### ISSUE TITLE
Cannot get matched last command when using up arrow

### ISSUE THREAD

**Issue by vernak2539** [withfig/fig#508]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When using ZSH, I used to be able to type something in, usually a partial command, and hit the up arrow. It would then give me commands that I'd previous run starting with the string inside of the command line. Since installing Fig this is no longer possible.

**Expected**
```
$ git checkout -b test-1234/testing-branch
// ... a while later
$ git check
// this the up arrow (after hitting escape to get fig to disappear)
$ git checkout -b test-1234/testing-branch
```

**Actual**
```
$ git checkout -b test-1234/testing-branch
// ... a while later
$ git check
// this the up arrow
$ git commit ...  // the last command I ran
```

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.50 (B274)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.50 (B274) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/alexvernacchia/.fig/bin/fig
Accessibility: true
Number of specs: 213
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/alexvernacchia/.gvm/bin:/Users/alexvernacchia/google-cloud-sdk/bin:/Users/alexvernacchia/.avn/bin:/Users/alexvernacchia/bin:/Users/alexvernacchia/deliveroo/executables:/Users/alexvernacchia/.rbenv/shims:/usr/local/opt/gettext/bin:/usr/local/opt/qt/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/alexvernacchia/.fig/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/alexvernacchia/go/bin:/Users/alexvernacchia/deliveroo/deliveroo-local/delos/exe:/Applications/Postgres.app/Contents/Versions/9.6/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (50808) - ttys005
Current working directory: /Users/alexvernacchia/xxxx
Current window identifier: 255458/1A3E6093-8D61-4D15-AFF8-2F6691E76CA0% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by Nick-SHM** [comment]
I would like to add that the issue seem to be introduced in a recent update, for I remember it worked fine previously with Fig.

**Comment by Nick-SHM** [comment]
@fwesss It's fixed!
