### ISSUE TITLE
Fig randomly stop

### ISSUE THREAD

**Issue by fabriceyopa** [withfig/fig#509]
### Description:
The Fig instance just stops alone without me making any actions. I need to restart it every 10min

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.49 (B269)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.49 (B269) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/fabrice/.fig/bin/fig
Accessibility: true
Number of specs: 214
SSH Integration: false
Tmux Integration: false
Keybindings path: /Users/fabrice/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (2615) - ttys001
Current working directory: /Volumes/Data/Labs/PHP/tezos
Current window identifier: 184/92798800-3A4D-46FE-90C8-142D71B64315% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by kurucu** [comment]
I'm pretty sure this affects me too. It's hard to replicate or know why/if it has happened, but I do often find myself "restart"ing Fig back into life.
