### ISSUE TITLE
Fig screen is shown somewhere else on VS Code terminal

### ISSUE THREAD

**Issue by jatinsandilya** [withfig/fig#51]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

This used to work before nicely. After the latest update, this got messed up. Added a screenshot as well.

![](https://user-images.githubusercontent.com/7681067/114859910-f7d83200-9e08-11eb-89b2-81604d72b546.png)

### Details:
|macOS|Fig|Shell|
|----|----|----|
|10.16.0|Version 1.0.40 (B188)|/bin/zsh|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.40 (B188)
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jatin/.fig/bin/fig
Accessibility: true
Number of specs: 75
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/jatin/.fig/user/keybindings
iTerm Integration: false
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/jatin/Downloads/google-cloud-sdk/bin:/usr/local/opt/openjdk/bin:/Users/jatin/.nvm/versions/node/v12.18.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/jatin/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mattschrage** [comment]
Definitely looks like something strange is going on. Does running `fig source` restore the normal behavior?

**Comment by jatinsandilya** [comment]
Yes, that worked! Could be due to the update happening in the background with fig open on VS Code I guess.

**Comment by falky97** [comment]
This actually happened to me today too. It happened after I opened a new VSCode window then switched to another one... It was like Fig thought your cursor was in the iTerm terminal I had open behind VSCode... Restarting Fig fixed. We made some major changes to how we get your cursor in VSCode. All coming out in the next build :)

**Comment by a-type** [comment]
I've also noticed this happens when typing a `/` character into the VS Code editor pane (not a terminal). If I have Hyper open anywhere, Fig will display the autocomplete prompt under the cursor in Hyper while I'm editing a file.

**Comment by mschrage** [comment]
This issue should be fixed in the next release (v10.49)
