### ISSUE TITLE
Duplicates selection Issue

### ISSUE THREAD

**Issue by haliltaskit** [withfig/fig#512]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hello.
When I write any path and clik Enter ->  fig autocomplete duplicates path.
![image](https://user-images.githubusercontent.com/44812001/136740175-055c00f2-e16f-4411-9a88-fdce2fc384bd.png)

![image](https://user-images.githubusercontent.com/44812001/136740231-b5649433-3cc1-4f5e-b836-36969e5b3c6e.png)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.50 (B274)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.50 (B274) [Turkish Q] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/hitaskit/.fig/bin/fig
Accessibility: true
Number of specs: 206
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/hitaskit/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/heroku-node/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hitaskit/Downloads/sonar-scanner-4.5.0.2216-macosx/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/hitaskit/.fig/bin:/Users/hitaskit/Library/Android/sdk/emulator:/Users/hitaskit/Library/Android/sdk/tools:/Users/hitaskit/Library/Android/sdk/tools/bin:/Users/hitaskit/Library/Android/sdk/platform-tools:/usr/local/sbin:/usr/local/mysql/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by fwesss** [comment]
@haliltaskit @Danielshow This issue should be fixed now. You'll just need to restart Fig from the macOS menu icon.
