### ISSUE TITLE
Fig not displaying auto-complete suggestions

### ISSUE THREAD

**Issue by AlexVPopov** [withfig/fig#513]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hello, for some reason fig doesn't work for me. It's displayed in the menu bar. The debugger says it should be working:
 
![Screenshot 2021-10-11 at 14 14 25](https://user-images.githubusercontent.com/3239252/136781187-c6191970-6006-4a84-b457-8f164a46210f.png)

However, when I type something into iTerm2 with zsh, it doesn't show any auto-completions. Even during the tutorial, when I typed `cd`, it didn't show me a drop down. I'm happy to provide any additional information required.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.50 (B274)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.50 (B274) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/al/.fig/bin/fig
Accessibility: true
Number of specs: 240
SSH Integration: false
Tmux Integration: true
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (55058) - ttys000
Current working directory: /Users/al
Current window identifier: 51281/EA14DD59-D539-4AAE-98D5-F56B1A79C0BE% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by AleksandarTokarev** [comment]
Getting the same error with same MacOS, ZSH and Fig 1.0.51 B294

**Comment by amazaheri** [comment]
+1 restarting Fig resolve the issue. but happens very frequently

**Comment by mschrage** [comment]
Hey @AlexVPopov @amazaheri @AleksandarTokarev! Sorry for the slow response here.

Try updating to the latest version (or reinstalling Fig by running `brew install fig`). We've spent a bunch of time focusing on stability and I think this issue has been resolved.
