### ISSUE TITLE
Alacritty integration installation fails silently

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#516]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
Attempting to install the Alacritty fails silently

1. Install Alacritty
2. Put default alacritty.yml in ~/.config/alacritty/alacritty.yml
2. Open Alacritty
3. Fig doesn't work
4. Check debugger
5. Click Install Alacritty Integration
6. Nothing happens
7. Reopen Alacritty and the debugger
8. Button to install integration is still available

### Environment

```bash
N/A
```

**Comment by DavSanchez** [comment]
Hi guys,

I'm having the same issue, but I'm not seeing any button/option to install integration that you mention. Could please you point me to where it is?

I have the latest version.

**Comment by gabroo** [comment]
Same issue as @DavSanchez

**Comment by grant0417** [comment]
Alacritty integration is no longer via this method
