### ISSUE TITLE
Add completion spec for a specific aliases

### ISSUE THREAD

**Issue by ido-vcita** [withfig/fig#518]
Hello,
I want to create a completionSpec for the following alias
`alias vmake="make -C /Users/<some_path>`

However, it seems like it completes commands for make and not my custom completionSpec.

Here is the code I have written:
```import { decodedTextSpanIntersectsWith } from "typescript";

const completionSpec: Fig.Spec = {
  name: "vmake",
  description: "Run services inside Docker",
  subcommands: [
    {
      name: "build",
      description: "Build the provided projects",      
    },
    {
      name: "restart",
      description: "Restart the provided services"
    },
    {
      name: "stop",
      description: "Stop the provided services"
    },
    {
      name: "rm",
      description: "Remove the container of the relvant service"
    },
    {
      name: "tail",
      description: "Tail container logs, default line count is 500",
      args:[
        {
          name: "service name",
          description: "The name of the service to tail its logs",
          isOptional: false
        },
        {
          name: "line count",
          description: "The number of lines to print, default is 500",
          isOptional: true
        }
      ]      
      
    },
    {
      name: "attach",
      description: "Conenct to current shell inside the container"
    },
    {
      name: "shell",
      description: "Open a new shell inside the container"
    }
],
  options: [
  ],
  // Only uncomment if vmake takes an argument
  // args: {}
};
export default completionSpec;
```
If it matters, the file name is vmake.ts

**Comment by mschrage** [comment]
@ido-vcita this is an interesting case! Fig actually is working as expected here. We detect your aliases and then try to map the underlying command (in this case `make -C /Users/<some_path>`) to a completion spec.

Luckily, we've just created a way of extending existing CLI tools with your own custom shortcuts. We call them mixins. You can check out the docs that @brendanfalk wrote up [here](https://fig.io/docs/guides/personal-mixins). 

That said, mixins might not work perfectly for this use-case. So it could make sense for us to add a setting that lets you specify aliases that you don't want expanded. Something like this `fig settings autocomplete.ignoreAliasExpansion '["vmake"]'`. cc @sullivan-sean
