### ISSUE TITLE
Npm scripts will not run in VSCode if default shell is fish

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#519]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
To reproduce:
1. Put `"terminal.integrated.defaultProfile.osx": "fish"` in VSCode settings
2. In a package.json file, hover over a script and click "Run Script"

The terminal will open and the prompt will load but the script will not be run.

### Environment

```bash
N/A
```

**Comment by andrei-zgirvaci** [comment]
Hey @fwesss, is there any news on this issue?

I hope I don't have to uninstall fig just because of this issue :(

**Comment by Calvin-LL** [comment]
Any update on this issue? I've been waiting for this problem to be solved since last summer. I love fig so much I've been reinstalling it once a while to see if this bug has been fixed.

**Comment by SeparateRecords** [comment]
Should be fixed now!
