### ISSUE TITLE
Autocomplete is inserting an unknown character ◧

### ISSUE THREAD

**Issue by bsime-gather** [withfig/fig#52]
### Description:
Autocomplete is inserting a weird character on enter keypress. The character looks like the fig logo.
![image](https://user-images.githubusercontent.com/49994297/115273393-7be23080-a10d-11eb-96b6-1484d7f136a2.png)
![image](https://user-images.githubusercontent.com/49994297/115273399-7dabf400-a10d-11eb-8d22-1d2243bd1022.png)

### Details:
|macOS|Fig|Shell|
|----|----|----|
|10.16.0|Version 1.0.40 (B188)|/bin/zsh|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.40 (B188)
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: false
Settings.json: true
CLI installed: true
CLI tool path: /Users/brookssime/.fig/bin/fig
Accessibility: true
Number of specs: 86
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/brookssime/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/brookssime/.bin:/Users/brookssime/.asdf/shims:/Users/brookssime/.asdf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/brookssime/.fig/bin:/usr/local/sbin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (9412) - ttys003
Current working directory: /Users/brookssime/Code/moments/server
Current window identifier: 4363/210E451F2-A91C-4C39-9229-0B772DC91BF3% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by bsime-gather** [comment]
No it didn't.

**Comment by mattschrage** [comment]
Hey @bsime-gather. Did this every get resolved or did you just uninstall Fig? I am reworking our ZSH integration right now and want to try to fix this.

**Comment by bsime-gather** [comment]
Yes, I solved my issue. There was some kind of conflict with a Vim binding I was using. Autocomplete doesn't work well if you configure the terminal to use Vim shortcuts as well.

**Comment by mschrage** [comment]
In previous versions of the zsh integration, we were only creating keybindings for the `emacs` keymap. This has been fixed as of v1.0.44!
