### ISSUE TITLE
Duplicate git command on autocomplete

### ISSUE THREAD

**Issue by Ivandotweb** [withfig/fig#522]
https://user-images.githubusercontent.com/40368223/137644533-3a0db502-d8f7-49a9-9068-8df47f2746a6.mov

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.50 (B274)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.50 (B274) [ABC] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
</p>
</details>

**Comment by mschrage** [comment]
Thanks for reporting this @Ivandotweb - so sorry you're running into this. Does restarting Fig resolve the issue for you?

We were running into a similar issue last week and you may have a stale version of autocomplete. It is also totally possible that we didn't fix the bug entirely! cc @sullivan-sean

**Comment by Ivandotweb** [comment]
I tried to restart fig and install new version but it did not help, it still appears time by time. 
I can reproduce it in VsCode integrated terminal only, in Iterm2 everything is fine. 
Anyway, fig is pretty cool autocomplete tool and i believe you fix this bug soon =)

**Comment by sullivan-sean** [comment]
Looks like somebody else had this issue and said the following:

> Hey everyone! I ran into a weird issue with VSCode where the autocomplete would duplicate/double the word like
> git commitcommit
> 
> 
> if anyone runs into this, it's because I noticed that in my vscode settings editor.accessibilitySupport was turned "off" - removed it all together and it worked!

Let me know if this fixes it for you

**Comment by mschrage** [comment]
@Ivandotweb we've figured out the root issue and will push a fix live tomorrow or early next week! Thanks for reporting this :)
