### ISSUE TITLE
File already exists: ~/.fig/logs/zsh.log

### ISSUE THREAD

**Issue by alasdairtran** [withfig/fig#524]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Issue Details

I get the following error when opening a new terminal with zsh:

```sh
/Users/<masked>/.fig/shell/zle.zsh:4: file exists: /Users/<masked>/.fig/logs/zsh.log
```

and fig autocompletion is not activated. The error seems self-explanatory. If I go to `~/.fig/shell/zle.zsh` and replace `2>"$HOME"/.fig/logs/zsh.log` with `2>>"$HOME"/.fig/logs/zsh.log`, the error disappears and autocompletion works.

I guess you might want to append to the error log or add a check to see if the log already exists.

### Environment

```bash
Not needed. See my suggested fix above.
```

**Comment by fwesss** [comment]
Fixed in v1.0.51
