### ISSUE TITLE
[Bug] Command History with custom keybinding

### ISSUE THREAD

**Issue by archcorsair** [withfig/fig#525]
# Summary
After setting `fig settings autocomplete.keybindings.up toggleHistoryMode` to trigger command substring history using the up arrow in the list of history does not work as expected.

# Expected
When presented with a list of command history, you should be able to scroll up with the up arrow

# Actual
Scrolling in the command history only works with down arrow since up arrow is bound to triggering the command history. Resulting in the list re-rendering and selection jumping back to top.

**Comment by SeparateRecords** [comment]
Fixed now! `fig settings autocomplete.navigateToHistory true` will give you the desired behavior.
