### ISSUE TITLE
nightowl theme does not show highlighted item with enough contrast

### ISSUE THREAD

**Issue by shadowspawn** [withfig/fig#527]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Using the nightowl theme with light system settings, I did not realised the item highlighting was working at all until I looked really closely. (In this screenshot it is the `Guest/` line.)

<img width="438" alt="Screen Shot 2021-10-20 at 20 09 10" src="https://user-images.githubusercontent.com/15719847/138045196-a9cca4b6-5058-4247-b527-85941e29e0b0.png">

### Environment

<details><summary><code>fig diagnostic</code></summary>
<p>

Version 1.0.51 (B285) [ABC - Extended] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/john/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/john/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (55119) - ttys002
Current working directory: /Users/john
Current window identifier: 42570/% (com.apple.Terminal)
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/john/.fig/bin
FIG_INTEGRATION_VERSION: 4
</pre>
</p>
</details>

**Comment by fwesss** [comment]
Darkened selection to #000C1D to increase contrast
