### ISSUE TITLE
Not showing candidate directories for cd

### ISSUE THREAD

**Issue by shadowspawn** [withfig/fig#529]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I am seeing appropriate candidates when I autocomplete from home directory, but no candidates except `../` from some other directories.

<img width="570" alt="Screen Shot 2021-10-20 at 20 34 54" src="https://user-images.githubusercontent.com/15719847/138049708-f74701ca-9e1a-472b-906c-595ccdaf0156.png">

### Environment

<details><summary><code>fig diagnostic</code></summary>
<p>

Version 1.0.51 (B285) [ABC - Extended] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/john/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/john/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (58207) - ttys001
Current working directory: /Users/john/Documents/Sandpits
Current window identifier: 42944/% (com.apple.Terminal)
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/john/.fig/bin
FIG_INTEGRATION_VERSION: 4
</pre>
</p>
</details>

**Comment by mschrage** [comment]
I'm going to close this issue as stale since we've improved the stability a lot! 

Please let me know if you are still running into this, and I'll reopen the issue!
