### ISSUE TITLE
Fig crashes when running `fig` with the menu icon hidden

### ISSUE THREAD

**Issue by JoeScho** [withfig/fig#532]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

#### Steps to recreate
- Run `fig`
- See menu open ✅
- Run `fig settings`
- Select the 'Hide icon' setting 
![image](https://user-images.githubusercontent.com/12475501/138109956-bc62abb3-dac2-449c-838f-18374b3df981.png)
- Run `fig` again
- See nothing happen ⚠️
- Run `fig` again
- See 'Could not connect to fig.app' error message ❌
![image](https://user-images.githubusercontent.com/12475501/138110119-59068226-3a2f-43ac-8681-b90590f15bcc.png)

### Environment

```bash
Version 1.0.51 (B285) [British]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/JSchofield/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/JSchofield/.nvm/versions/node/v12.14.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin:/Users/JSchofield/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (86340) - ttys005
Current working directory: /Users/JSchofield/Documents/projects
Current window identifier: 62952/% (com.googlecode.iterm2)
PATH: /Users/JSchofield/.nvm/versions/node/v12.14.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin:/Users/JSchofield/.fig/bin
FIG_INTEGRATION_VERSION: 4
```

**Comment by JoeScho** [comment]
Thanks @mschrage ! I'll keep an eye out for the update

**Comment by mschrage** [comment]
Sorry this took so long @JoeScho! But the fix is now live :)
