### ISSUE TITLE
VS Code Terminal Double Pasting Autocomplete

### ISSUE THREAD

**Issue by stranius** [withfig/fig#533]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When using the autocomplete feature in VS Code for checking out into a Github branch, the autocomplete I'm trying to achieve is pasted into the terminal twice and is overlapping. For example these are the following steps I performed and the result I achieved:

1. I typed 'git checkout' into the VS Code terminal (I'm using bash as my terminal here).
2. The autocomplete for my branch appears, in this case the branch was 'git checkout 295-implement-delivery-report-renderer'
3. After hitting enter, the text in my terminal now is 'git checkout 295-implem295-implement-delivery-report-rendererent-delivery-report-renderer

This behavior does not seem to happen when I'm in the regular Mac terminal and seems to function as desired. I'm only having this problem when using the terminal within VS Code.

Hope this helps!

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.50 (B274)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.50 (B274) [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/paytonfisher/.fig/bin/fig
Accessibility: true
Number of specs: 207
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/paytonfisher/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/Users/paytonfisher/.nvm/versions/node/v8.11.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/paytonfisher/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/bash (45642) - ttys013
Current working directory: /Users/paytonfisher/Documents/We Go Look/Repos/sendgrid-webhook
Current window identifier: 46278/code:36688% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @stranius! Really appreciate this bug report. Someone mentioned this same issue in our Discord and found that going to the VSCode settings and removing `editor.accessibilitySupport` fixed the problem.

<img width="651" alt="Screen Shot 2021-10-20 at 6 16 48 PM" src="https://user-images.githubusercontent.com/3155109/138193886-f07e65ff-acff-458f-a51e-01faa17c8e70.png">

I'm investigating this right now.

**Comment by stranius** [comment]
Matt,

Thanks for letting me know! This tool is great and I've loved using it.
Keep up the great work!

Thanks,
Payton
