### ISSUE TITLE
When initializing Fig env Variables it outputs a file exists log and Fig never starts to work.

### ISSUE THREAD

**Issue by karlringman** [withfig/fig#534]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When a new shell is started Fig outputs this log and it won't work in iTerm

`/Users/karlringman/.fig/shell/zle.zsh:4: file exists: /Users/karlringman/.fig/logs/zsh.log`

In the RC file `~/.zshrc` it is the FIG ENV VARIABLES that causes this output to happen.

```
#### FIG ENV VARIABLES ####
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
```

I have tried restarting iTerm, Fig and the computer as well as run install/update script and install CLI tools but nothing seems to work.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.51 (B285)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.51 (B285) [Debug] [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/karlringman/.fig/bin/fig
Accessibility: true
Number of specs: 208
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/karlringman/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/karlringman/google-cloud-sdk/bin:/Users/karlringman/.rbenv/shims:/Users/karlringman/.nvm/versions/node/v12.20.2/bin:/usr/local/opt/tcl-tk/bin:/Users/karlringman/.pyenv/shims:/Users/karlringman/.pyenv/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/karlringman/.fig/bin:/Users/karlringman/Library/Android/sdk/emulator:/Users/karlringman/Library/Android/sdk/tools:/Users/karlringman/Library/Android/sdk/tools/bin:/Users/karlringman/Library/Android/sdk/platform-tools
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (31324) - ttys003
Current working directory: /Users/karlringman
Current window identifier: 2989/34477BE4-0171-49F5-9E2A-BA5339525B66% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @karlringman! Thanks for reporting this.

I've just pushed a fix that should address the ` file exists:` error. 

Does Fig appear for you in other terminals? Based on the diagnostic, it looks like the iTerm integration is working properly but something else might be going on.

If you'd be open to jumping on a debugging call that might be the fastest way of figuring out what's going on: https://calendly.com/mschrage/30min

**Comment by twhitacre** [comment]
@karlringman I had the exact same problem with a similar CLI setup (zprezto, nvm, gcloud, etc). I saw the release above went out in beta, so enabled the beta updates in the settings and once updated, Fig is now working again for me.

**Comment by karlringman** [comment]
@twhitacre Thank you for the tip, I did the same and Fig works but it has a visual glitch now.

I'm now using Fig v1.0.51 (B286)

See screenshot where transparent background shows up as red

<img width="646" alt="Screen Shot 2021-10-21 at 12 06 36 PM" src="https://user-images.githubusercontent.com/777980/138341068-1fa2dbe4-ff66-4da4-9dee-b87a89e40bc8.png">

@mschrage Should I file a separate bug for this?
