### ISSUE TITLE
Image mismatch in getting started docs

### ISSUE THREAD

**Issue by zp4rker** [withfig/fig#535]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
Mistake on docs `getting-started/first-completion-spec` page: https://fig.io/docs/getting-started/first-completion-spec

The images under the lines `Here's how the argument we just added looks in Fig's autocomplete window.` are mixed up, should be switched to fix. Taking a look at the images below, you can see how the code snippet mismatches with the example screenshot.

![image](https://user-images.githubusercontent.com/13144755/138194832-2bbdc7d1-8062-4d9f-a114-c3c0673e0ed7.png)
![image](https://user-images.githubusercontent.com/13144755/138194941-a36d8598-16d5-4560-9eae-570e3e56aa22.png)

### Environment

```bash
n/a
```

**Comment by fwesss** [comment]
Just fixed!
