### ISSUE TITLE
Setup not completing after email verification. Error: TypeError: Preflight response is not successful

### ISSUE THREAD

**Issue by lewisvrobinson** [withfig/fig#536]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:

After installing and going through the setup wizard the setup fails, despite showing the "Success" message.

![image](https://user-images.githubusercontent.com/8475441/138380413-28d31c9b-ade3-40ba-bb62-10c383ec40a2.png)

Taking a look at the network activity it looks like there could be a CORS issue

![image](https://user-images.githubusercontent.com/8475441/138381004-8444db07-db58-4d04-9f86-fa4eef9370bf.png)

After uninstalling (to retry the setup) I also noticed that the feedback form at https://fig.io/uninstall also has a CORS related error on submit 😕 

### Environment

```bash
|11.6.0|Version 1.0.51 (B285)|/bin/zsh|

Version 1.0.51 (B285) [Australian] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/lewisrobinson/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Applications/Postgres.app/Contents/Versions/12/bin:/Users/lewisrobinson/.yarn/bin:/Users/lewisrobinson/.config/yarn/global/node_modules/.bin:/Users/lewisrobinson/.asdf/shims:/Users/lewisrobinson/.asdf/bin:/Users/lewisrobinson/.nvm/versions/node/v10.15.3/bin:/Users/lewisrobinson/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Caskroom/chromedriver/90.0.4430.24:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???
```

**Comment by mschrage** [comment]
Hey @lewisvrobinson thanks so much for reporting this. We're in the process of updating our backend and I think you might have caught us with our pants down.

The login flow should be working again! Let me know if you try again and are still running into issues.
