### ISSUE TITLE
Fig is creating ~/.zshrc instead of checking the current one

### ISSUE THREAD

**Issue by SebDanielsson** [withfig/fig#552]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Issue Details

I currently store my zsh files, including `.zshrc`, in ~/.config/zsh by putting `ZDOTDIR=$HOME/.config/zsh` in my `~/.zshenv`. After updating fig to the latest version it created a new `.zshrc` in my home directory even though zsh is configured to look for the config in `~/.config/zsh`. Is it possible to configure fig to look and edit `.zshrc` by first looking for it with the `ZDOTDIR` variable?

Also, is it really necessary for fig to recreate .bashrc and .profile when I'm using zsh?

### Environment

```bash
Version 1.0.51 (B293) [Swedish]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/sebastian/.fig/bin/fig
Accessibility: true
Number of specs: 208
SSH Integration: true
Tmux Integration: false
Keybindings path: /Users/sebastian/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin:/Users/sebastian/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (96361) - ttys002
Current working directory: /Users/sebastian
Current window identifier: 6180/4BC14051-6B43-4697-8EBB-0C1F73F4C673% (com.googlecode.iterm2)
PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin:/Users/sebastian/.fig/bin
FIG_INTEGRATION_VERSION: 5
```

**Comment by SebDanielsson** [comment]
Any progress on this?😇

**Comment by mschrage** [comment]
We've just rewritten our installation flow to give users more control over how their dotfiles are updated.

I will make sure that referencing `$ZDOTDIR` when determining the location of your `~/.zshrc` makes it into to the next release!

**Comment by grant0417** [comment]
I believe this should respect `$ZDOTDIR` currently
