### ISSUE TITLE
Settings: Keybindings layout broken when the window is too small

### ISSUE THREAD

**Issue by arnold-graf** [withfig/fig#554]
### Description:

Hi!

Thanks for making fig! The layout of the keybindings view in the settings window gets messy when the window height is very small:

<img width="813" alt="Bildschirmfoto 2021-10-29 um 15 36 56" src="https://user-images.githubusercontent.com/10359100/139445075-0c12a9a4-c0a0-40a7-a830-9933f2d9f180.png">

Thought I’d tell you!

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.51 (B294)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.51 (B294) [Austrian] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/arnoldgraf/.fig/bin/fig
Accessibility: true
Number of specs: 207
SSH Integration: false
Tmux Integration: false
Keybindings path: /Users/arnoldgraf/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/arnoldgraf/.nvm/versions/node/v14.17.6/bin:/Users/arnoldgraf/.asdf/shims:/usr/local/opt/asdf/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/arnoldgraf/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @arnold-graf! Thanks so much for reporting this. I can't seem to reproduce on Big Sur. 

Can you check Safari and see what version of WebKit you have running?

**Comment by fwesss** [comment]
Duplicate: https://github.com/withfig/fig/issues/576

**Comment by mschrage** [comment]
@arnold-graf this is fixed as of the latest build!
