### ISSUE TITLE
Tab behavior setting seems to have no effect

### ISSUE THREAD

**Issue by chkn** [withfig/fig#557]
### Description:

Under Settings -> General, I change Tab Behavior to "insert" or "insertOrPrefix" but it doesn't change the behavior; the completion list just shakes when I hit tab. I would expect that setting to cause it to insert the completion as that is more natural for me than hitting return to insert it.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.51 (B294)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.51 (B294) [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/alex/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/alex/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/bash (11472) - ttys002
Current working directory: /Users/alex
Current window identifier: 6238/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by chkn** [comment]
Just saw #540 and it looks related.. the suggested fix there (adding a keybinding) does work. So maybe the bug is that the General setting for "Tab Behavior" is obsolete and no longer works

**Comment by mschrage** [comment]
Yeah, we need to remove these settings! Thanks for the reminder :)

**Comment by mschrage** [comment]
This is fixed in v1.0.52.
