### ISSUE TITLE
Reinstalling Fig - can't get past setup.

### ISSUE THREAD

**Issue by SladtheLad** [withfig/fig#558]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Trying to reinstall Fig on a machine and I can't get past the Customize Theme section of the initial setup walkthrough. Trying to click the 'Continue' button does nothing.

![Screen Shot 2021-11-01 at 11 06 01 AM](https://user-images.githubusercontent.com/27019598/139702876-c0907285-ba13-47f1-9dee-4521384bfb78.png)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.50 (B274)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.50 (B274) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/nsladden/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: false
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @SladtheLad! So sorry you are running into this issue. I'm not sure exactly what's going on.

Can you right click the Fig window and then click "Inspect elements"? This will bring up the Web Inspector. Does anything appear in the console?


(Also it looks like you've downloaded an old version of Fig. You might also try redownloading!)

**Comment by SladtheLad** [comment]
Hello @mschrage! Sorry for just getting back to this!

I'm a bit stumped myself now, because I just went to inspect the fig setup window, but suddenly I could now get past the 'Customize Theme' screen when clicking continue? The only thing I can think is that this is for my work machine and I am usually behind a protected VPN/firewall. The following screen is for logging in/checking an email address. Perhaps my VPN was blocking this somehow?

In any case, I was able to properly finish setup and update Fig and it's working again.

**Comment by mschrage** [comment]
@SladtheLad thanks for letting me know. It is certainly possible that a VPN is responsible. 

Seems related to #569. This behavior is probably the result of lack of connectivity - either due to a firewall or bad internet connection.

**Comment by skratchdot** [comment]
@mschrage - Will there ever be an option for guest sign-in?  I see it was hinted at here:
https://github.com/withfig/autocomplete/issues/42#issuecomment-797141359

This app looks awesome, but I'd love a way to use it without giving out my work email :)

**Comment by mschrage** [comment]
In v1.0.54, I've added an error message when this happens so that users know what's going on!
