### ISSUE TITLE
Fig autocomplete not working

### ISSUE THREAD

**Issue by bechurch** [withfig/fig#559]
Running iterm2 on macos

heres the output of fig doctor
```sh
fig tools doctor

Let's make sure Fig is running...

Fig bin exists: pass
Fig in path: pass
Fig running: pass
macOS version: pass

Let's see what fig diagnostic tells us...

Compatible shell: pass
Bundle path: pass
Autocomplete enabled: pass
CLI installed: pass
CLI tool path: pass
Accessibility enabled: pass
Autocomplete specs installed: fail

I can fix this!


> /Users/ben/.fig/bin/fig update

Pulling most up-to-date completion specs...
Run fig docs to learn how to contribute your own!

tar: specs: Not found in archive
tar: Error exit delayed from previous errors.

Fix applied!


Let's restart our checks to see if the problem is resolved...

Let's make sure Fig is running...

Fig bin exists: pass
Fig in path: pass
Fig running: pass
macOS version: pass

Let's see what fig diagnostic tells us...

Compatible shell: pass
Bundle path: pass
Autocomplete enabled: pass
CLI installed: pass
CLI tool path: pass
Accessibility enabled: pass
Autocomplete specs installed: fail



Looks like we've already tried this fix before and it's not working.
```

**Comment by Codelica** [comment]
Just installed and have hit the same situation, with same output to `fig tools doctor`.    Things were working briefly then seemed to have stopped while using iTerm2 for some reason.

**Comment by mschrage** [comment]
@Codelica @bechurch thanks for reporting this. Can you share the output of `fig diagnostic`?

**Comment by Codelica** [comment]
```
Version 1.0.51 (B294) [U.S.]
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/james/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: true
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/james/Library/Android/sdk/platform-tools:/Users/james/.deno/bin:/usr/local/opt/curl/bin:/Users/james/.nvm/versions/node/v16.13.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Applications/Wireshark.app/Contents/MacOS:/Users/james/Library/Python/3.7/bin/:/sometest:/Users/james/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/bash (76693) - ttys017
Current working directory: /Users/james
Current window identifier: 31369/C3C124B1-17B1-452E-A073-A2CC05B54D70% (com.googlecode.iterm2)
PATH: /Users/james/Library/Android/sdk/platform-tools:/Users/james/.deno/bin:/usr/local/opt/curl/bin:/Users/james/.nvm/versions/node/v16.13.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Applications/Wireshark.app/Contents/MacOS:/Users/james/Library/Python/3.7/bin/:/Users/james/.fig/bin
FIG_INTEGRATION_VERSION: 5
```

**Comment by mschrage** [comment]
Hmm based on the diagnostic output everything looks okay.

Can you type `git co` in your terminal and then take a screenshot of the Fig debugger (the first item if you click the menubar icon)?

If you're free, we could also jump on a debugging call sometime this week: https://calendly.com/mschrage/30min

**Comment by Codelica** [comment]
yea... it did work briefly, so not sure what changed.  I thought it might be BTT (Better Touch Tool) which I used for triggering some macros, but exiting that didn't seem to help.  Here is the screenshot, but I won't be able to jump on anything until later this week.  Keybuffer seems a little suspect assuming that's supposed to be the last key logged or something, but you'll know more than me :)

<img width="886" alt="fig 2021-11-02 12-27-03" src="https://user-images.githubusercontent.com/386101/139924282-46c18f8a-d331-43e5-bd1f-177d5fe4a3fd.png">

**Comment by mschrage** [comment]
The keybuffer seems to be the issue. Fig isn't getting the text you've typed in your shell and so can't provide suggestions.

Can you run `ps` and share the output here?

**Comment by Codelica** [comment]
On fresh launch of iTerm2 with 1 shell window:

```
james@workaholic:~ ▸ ps
  PID TTY           TIME CMD
 4637 ttys000    0:00.05 /bin/sh
10874 ttys001    0:00.01 /bin/bash (figterm)
10883 ttys002    0:00.07 /bin/bash --login
11332 ttys002    0:00.00 /bin/bash --login
11333 ttys002    0:00.00 fig bg:exec 10883 /dev/ttys002
 9814 ttys013    0:00.01 /bin/sh
```

**Comment by mschrage** [comment]
So `figterm` is running, which is good.

Can you run `export FIG_LOG_LEVEL=DEBUG` in that terminal and then in another session run `fig debug logs`. 

Can you take a screen recording of you typing in the first terminal and have the logging visible as well?

**Comment by Codelica** [comment]
I think this is what you're after.  Seems to be capturing the keystroke events, but maybe not the actual characters?

Would it be worth me trying an un-install/install or would you rather see what state things are in?  Should have mentioned that I never tried that, and during the initial install I did have a lot up and running (many terms, vs code, docker, etc, etc.)

https://user-images.githubusercontent.com/386101/140086777-bcbcb02d-0909-43f0-9cae-c5f451ec6984.mp4

**Comment by Codelica** [comment]
Just a followup here.  I decided to uninstall and re-install.  It seemed to go fine and the little "intro" tutorial in iTerm worked with the popups for auto-complete, etc.   However, after that was done and iTerm was restarted I no longer go any auto-completes.  Curiously though, what I type does show now in the debugger under keybuffer, but it just doesn't seem to trigger any auto-complete overlay.

**Comment by mschrage** [comment]
Hmm I think the best way to proceed to is do a debugging call together next week! 

Here is my calendly: https://calendly.com/mschrage/30min

**Comment by Codelica** [comment]
When I launched a terminal this morning FIG was updates, and now seems to work. 👍   

Only quirk I've seen is that Expo/EAS (which added support) doesn't seem to trigger the popup.  That may be something on my end with NVM involved though.

**Comment by mschrage** [comment]
Glad to hear everything is working again :)

> Only quirk I've seen is that Expo/EAS (which added support) doesn't seem to trigger the popup. That may be something on my end with NVM involved though.

Mind opening a new issue for this @Codelica?
