### ISSUE TITLE
No Fig in VS Code

### ISSUE THREAD

**Issue by robcrock** [withfig/fig#560]
### Description:
> I opened VS Code as ran fig source, but I'm not getting the autocomplete in the terminal.

 
### Details:
macOS
|-|-|-|
Version 1.0.51 (B294)
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.51 (B294) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Robert/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 92275/code:79283% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @robcrock - thanks for reporting this. Is VSCode the only terminal where autocomplete does not appear?

**Comment by JulienHe** [comment]
Hey @robcrock got the same issue, I run `fig source` and it fixed it, hope it's helping you.
