### ISSUE TITLE
Fig not detecting git in directory

### ISSUE THREAD

**Issue by justinnoel** [withfig/fig#564]
### Description:
I just installed Fig and am in an iTerm window. The current directory is a git repo. 

When I run `git log` and `git branch`, you clearly see this is a repo.

When I run `fig git`, the fig window opens. However, it is not seeing any of the git info.

macOS: 11.6

### Screenshots

![fig-git-branches-missing](https://user-images.githubusercontent.com/81643826/139887611-0503fc37-141d-492a-b133-ab429f23edd7.jpg)

![fig-git-no-status-of-files](https://user-images.githubusercontent.com/81643826/139887869-f7678496-9478-4416-9c39-5df3f9ccbede.jpg)
 
![fig-debugger](https://user-images.githubusercontent.com/81643826/139888790-108b9dc9-5547-43f1-90fe-2755dfa81816.jpg)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.51 (B294)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.51 (B294) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jn/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/jn/.yarn/bin:/Users/jn/.config/yarn/global/node_modules/.bin:/Users/jn/bin:/Users/jn/.asdf/shims:/Users/jn/.asdf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jn/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/bin/less (9071) - ttys001
Current working directory: /Users/jn/Apps/test/dripsy
Current window identifier: 214884/E2374221-FD59-4DC5-9FC9-D44163FC8BCB% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @justinnoel! `fig git` is actually a legacy Fig app and is not currently supported. We are planning on bring this back soon (and allowing anyone to build their own!).

Sorry that it's not working right now though...

**Comment by justinnoel** [comment]
Thanks for the response @mschrage . Y'all might want to update the walkthrough then. That's what got me to trying Fig with git.
