### ISSUE TITLE
Autocomplete specs install fails

### ISSUE THREAD

**Issue by mpbrown7** [withfig/fig#565]
Running 12.0.1 Mac OS Monterey

mpbrown@yellow ~
╰─$ macOS version: pass                                                                                                                                 21:10:53

Let's see what fig diagnostic tells us...

Compatible shell: pass
Bundle path: pass
Autocomplete enabled: pass
CLI installed: pass
CLI tool path: pass
Accessibility enabled: pass
Autocomplete specs installed: fail

I can fix this!

> /Users/mpbrown/.fig/bin/fig update

Pulling most up-to-date completion specs...
Run fig docs to learn how to contribute your own!

tar: specs: Not found in archive
tar: Error exit delayed from previous errors.

Fix applied!

Let's restart our checks to see if the problem is resolved...

Let's make sure Fig is running...

Fig bin exists: pass
Fig in path: pass
Fig running: pass
macOS version: pass

Let's see what fig diagnostic tells us...

Compatible shell: pass
Bundle path: pass
Autocomplete enabled: pass
CLI installed: pass
CLI tool path: pass
Accessibility enabled: pass
Autocomplete specs installed: fail

**Comment by fwesss** [comment]
Hey @mpbrown7, the autocomplete specs are now automatically installed without the need for `fig update`. `fig tools doctor` will be fixed in the next release so it does not run that command but you shouldn't need to manually update the specs.

Were you running into another issue with getting Fig to work?

**Comment by fwesss** [comment]
`fig update` has been deprecated.
