### ISSUE TITLE
Causes lag / CLI commands to get stuck

### ISSUE THREAD

**Issue by jkarttunen** [withfig/fig#567]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Creates huge lag to some CLI commands, making them stuck for minutes.

Tried this few times. E.g. running firebase CLI takes < 1s without fig, around 60s with fig

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.51 (B294)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.51 (B294) [Finnish] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/<USER>/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/<USER>/Downloads/google-cloud-sdk/bin:/Users/<USER>/.nvm/versions/node/v16.8.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/<USER>/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 266/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
@jkarttunen thanks for letting us know. Is `firebase` the only command where you notice this? Would you mind sharing a screen recording of the behavior?

Also would love to jump on a call with you to do some debugging: https://calendly.com/mschrage/30min

**Comment by waxidiotic** [comment]
This may be what's been happening for me too. I've noticed it on some commands from the Github CLI `gh` and Vercel's CLI (`vercel`). I don't remember exactly which command for `gh` was causing me issues but `vercel env pull` has been the latest for me for Vercel.



macOS | Fig | Shell
-- | -- | --
12.0 | Version 1.0.51 (B294) | /bin/zsh
