### ISSUE TITLE
Cannot continue with onboarding after "Customize Theme" page

### ISSUE THREAD

**Issue by YuKongEr** [withfig/fig#569]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Click the Continues button and there is no reaction

![image](https://user-images.githubusercontent.com/23350349/140483576-52be6e2e-ad51-4868-b095-d680abd71ceb.png)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.51 (B294)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.51 (B294) [搜狗拼音] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/qianshen/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/qianshen/Documents/gospace/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/qianshen/.fig/bin:/usr/local/Cellar/maven@3.5/3.5.4_1/libexec/bin:/Users/qianshen/flutter/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

![image](https://user-images.githubusercontent.com/23350349/140483472-125ef943-4fdf-442b-9642-86cf788ac421.png)

**Comment by mschrage** [comment]
Hey @YuKongEr! Are you still experiencing this issue?

**Comment by mschrage** [comment]
Hey @YuKongEr! The underlying issue here is that users could not continue to the next page if they were not connected to the internet.

As of v1.0.54, there is an error message that explains what's happening.
