### ISSUE TITLE
Fig unable to install autocomplete specs

### ISSUE THREAD

**Issue by terpenes** [withfig/fig#571]
Fix applied!

Let's restart our checks to see if the problem is resolved...

Let's make sure Fig is running...

Fig bin exists: pass
Fig in path: pass
Fig running: pass
macOS version: pass

Let's see what fig diagnostic tells us...

Compatible shell: pass
Bundle path: pass
Autocomplete enabled: pass
CLI installed: pass
CLI tool path: pass
Accessibility enabled: pass
Autocomplete specs installed: fail

Looks like we've already tried this fix before and it's not working.

❯ fig issue
→ Opening GitHub...

**Comment by mschrage** [comment]
@terpenes this was actually just an issue with our CLI. The autocomplete engine now bundles all the necessary completion specs and they do not need to be downloaded by the macOS app.
