### ISSUE TITLE
VPN prevents autocomplete-engine from loading

### ISSUE THREAD

**Issue by SladtheLad** [withfig/fig#573]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Since reinstalling, I don't see any errors when running Fig, but popup doesn't seem to be working. When I go to 'Force popup' this is all I see.
![Screen Shot 2021-11-08 at 9 49 49 AM](https://user-images.githubusercontent.com/27019598/140773806-52a50dd6-b675-403a-8fb2-09e18f29b717.png)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.51 (B294)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.51 (B294) [Debug] [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/nsladden/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/nsladden/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @SladtheLad, so sorry you're running into issues! Can you right click on the red box, open "Inspect Elements" and then take a screenshot of the console.

**Comment by SladtheLad** [comment]
@mschrage 
![Screen Shot 2021-11-08 at 1 25 00 PM](https://user-images.githubusercontent.com/27019598/140804964-39c76410-a7ec-4287-9bc8-628272ceeb27.png)

Looks like it's a connection issue. 

I am on a VPN at work, and I guess it blocks cdn modules? 

Works if I am off VPN:
![Screen Shot 2021-11-08 at 1 29 25 PM](https://user-images.githubusercontent.com/27019598/140805548-116c6bd6-db4a-4fb9-9b0e-e3fdb1d7c1e8.png)


Will there ever be a way to use this locally?

**Comment by mschrage** [comment]
Yes! You can run Fig locally by cloning [withfig/autocomplete](https://github.com/withfig/autocomplete) and following the instructions in the readme.

This will put Fig in "Developer mode" and specs will be loaded locally from the repo.

**Comment by SladtheLad** [comment]
This makes sense now as to why it continued to work for a while when I went out of the office then back on VPN. Interesting. I apologize if this is explained somewhere and I must have missed this.
