### ISSUE TITLE
Settings UI is broken on Catalina

### ISSUE THREAD

**Issue by fransouwap** [withfig/fig#576]
### Description:

![image](https://user-images.githubusercontent.com/9249809/140908202-d1209c02-e022-4452-a34d-f695a463b682.png)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.51 (B294)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.51 (B294) [French] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Franz/.fig/bin/fig
Accessibility: true
Number of specs: 211
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/Franz/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @fransouwap! Thanks for reporting this. 

This is a rendering issue that only occurs on Catalina. We'll get this fixed up asap.

**Comment by mschrage** [comment]
This is fixed as of the latest build. Thanks again for letting us know about the issue @fransouwap
