### ISSUE TITLE
iTerm session exits immediately 

### ISSUE THREAD

**Issue by anledehai** [withfig/fig#577]
### Description:
> Hi, 
<img width="544" alt="1636458287068" src="https://user-images.githubusercontent.com/38025570/140921084-1f093ea5-64fc-4512-b835-36b96f6772b8.png">

When I click OK, the window disappears;
After I quit fig iterm2 still doesn't work, I have to uninstall fig to get iterm2 back to normal.

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.51 (B294)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.51 (B294) [搜狗拼音] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/zhongyongwei/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by anledehai** [comment]
> ### Description:
> > Hi,
> 
> <img alt="1636458287068" width="544" src="https://user-images.githubusercontent.com/38025570/140921084-1f093ea5-64fc-4512-b835-36b96f6772b8.png">
> 
> When I click OK, the window disappears
> After I quit fig iterm2 still doesn't work, I have to uninstall fig to get iterm2 back to normal

> ### Details:
> macOS	Fig	Shell
> 12.0.1	Version 1.0.51 (B294)	/bin/zsh
> `fig diagnostic`
> Version 1.0.51 (B294) [搜狗拼音] 
> UserShell: /bin/zsh
> Bundle path: /Applications/Fig.app
> Autocomplete: true
> Settings.json: true
> CLI installed: true
> CLI tool path: /Users/zhongyongwei/.fig/bin/fig
> Accessibility: true
> Number of specs: 1
> SSH Integration: false
> Tmux Integration: false
> Keybindings path: 
> iTerm Integration: true [Authenticated]
> Hyper Integration: false
> VSCode Integration: true
> Docker Integration: false
> Symlinked dotfiles: false
> Only insert on tab: false
> Installation Script: true
> PseudoTerminal Path: 
> SecureKeyboardInput: false
> SecureKeyboardProcess: 
> Current active process: ??? (???) - ???
> Current working directory: ???
> Current window identifier: ???

**Comment by mschrage** [comment]
@anledehai this looks like a very frustrating bug. I'm sorry you ran into it. 

Are you free to do a quick debugging call with me so we can get to the bottom of this? Here is my scheduling link: https://calendly.com/mschrage/30min.

Would love to figure out what's going on here.
