### ISSUE TITLE
Get superfluous warning message about "fig Tmux Integration: Enabled does not exist"

### ISSUE THREAD

**Issue by alasdairtran** [withfig/fig#578]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Issue Details

When I start tmux, an annoying window pops up saying `fig Tmux Integration: Enabled does not exist`. There's no way to suppress this warning message. See screenshot. Despite the warning, Fig autocomplete still works well inside tmux.

<img width="349" alt="tmux warning" src="https://user-images.githubusercontent.com/10582768/140919345-b03e460f-27eb-4e7e-90be-237622b0cd89.png">

I can see that the following lines were added to the end of my `~/.tmux.conf.local`:

```
# Fig Tmux Integration: Enabled
source-file ~/.fig/tmux
# End of Fig Tmux Integration
```

Interesting, when running `fig diagnostic`, it says `Tmux Integration: false`.

### Environment

```bash
Version 1.0.51 (B294) [ABC – Extended]
UserShell: /usr/local/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/$MY_USERNAME/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/zsh/5.8_1/bin/zsh (66118) - ttys005
FIG_INTEGRATION_VERSION: 5
```

**Comment by alasdairtran** [comment]
After some investigation, I think there's some conflict between fig and TMUX plugin manager. The problem was fixed when I moved the `source-file ~/.fig/tmux` up a bit in my `~/.tmux.conf.local`, like this:

```
# Fig Tmux Integration: Enabled
source-file ~/.fig/tmux
# End of Fig Tmux Integration

# ================================================

# Load tmp plugins. tpm has a known issue when using custom config file with
# -f option. The solution is to use alternative plugin definition syntax.
# See https://github.com/tmux-plugins/tpm/blob/master/docs/tpm_not_working.md
set -g @tpm_plugins '             \
  tmux-plugins/tpm                \
  nhdaly/tmux-better-mouse-mode   \
'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

So I think if you'd like to fix this in your code, when adding the tmux integration, you might want to ensure that the sourcing line comes before the tmux plugin initialization line if there is one.

Otherwise it would be useful to add a note in your documentation to tell other tmux users the manual fix.

**Comment by mschrage** [comment]
Hey @alasdairtran! Thanks for reporting this. Seems like this can be a small tweak to our installation script. 

Can you look into this @grant0417?

**Comment by grant0417** [comment]
This should be fixed!
