### ISSUE TITLE
Not seeing autocomplete

### ISSUE THREAD

**Issue by gopalraman** [withfig/fig#579]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

![image](https://user-images.githubusercontent.com/75338857/141001258-c25e67df-5ab1-4f55-89ae-1eeee60ad950.png)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.51 (B294)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.51 (B294) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/gopalraman/.fig/bin/fig
Accessibility: true
Number of specs: 208
SSH Integration: false
Tmux Integration: false
Keybindings path: /Users/gopalraman/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/gopalraman/go/bin:/usr/local/go/bin:/Users/gopalraman/.local/share/solana/install/active_release/bin:/Users/gopalraman/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/gopalraman/.cargo/bin:/usr/ucb:/Users/gopalraman/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (73122) - ttys001
Current working directory: /Users/gopalraman
Current window identifier: 6075/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @gopalraman! So sorry that you are running into issues.

Can you type `git ` and then take a screenshot of the Fig debugger (in the menubar)?

**Comment by omares** [comment]
Hey, i have the same issue. The autocomplete popup is not showing for me. `fig tools doctor` highlights that autocomplete is off. Executing the suggested command does solve the issue. Restarting or turning autocomplete off/on via UI also does not help.

![image](https://user-images.githubusercontent.com/1375307/142188862-66df3689-b6ae-4923-b934-dda1a45ddabd.png)

![image](https://user-images.githubusercontent.com/1375307/142188998-3b0a0201-0287-4dc1-bc20-a963235d41e5.png)

```
❯ fig tools doctor

Let's make sure Fig is running...

Fig bin exists: pass
Fig in path: pass
Fig running: pass
macOS version: pass

Let's see what fig debug diagnostic tells us...

Compatible shell: pass
Bundle path: pass
Autocomplete enabled: fail
```

```
❯ fig diagnostic
Fig Version: Version 1.0.52 (B311) [U.S. With Umlauts via Option Key]
UserShell: /usr/local/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: unknown
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: Could not read Hyper settings file (/Users/otamares/.hyper.js)
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/otamares/Library/Android/sdk/platform-tools:/usr/local/opt/findutils/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:/Users/otamares/.zinit/polaris/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/otamares/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/zsh/5.8_1/bin/zsh (9303) - /dev/ttys005
Current working directory: /Users/otamares
Current window identifier: 239/0F5DC2B3-FC7C-4743-B6F9-1B4257E5AF7F% (com.googlecode.iterm2)
Path: /Users/otamares/.zinit/snippets/sdkman:/Users/otamares/.asdf/shims:/Users/otamares/.zinit/plugins/asdf-vm---asdf/bin:/Users/otamares/.zinit/plugins/junegunn---fzf/bin:/Users/otamares/.zinit/plugins/junegunn---fzf-bin:/Users/otamares/Library/Android/sdk/platform-tools:/usr/local/opt/findutils/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:/Users/otamares/.zinit/polaris/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/otamares/.fig/b

```

**Comment by mschrage** [comment]
Hey @omares, it looks like the the keybuffer is not getting updated correctly. 

Can you open a new terminal window and run:

1. `ps`
2. `env | grep FIG`

**Comment by omares** [comment]
sure! Here you go

```
❯ ps
  PID TTY           TIME CMD
 3567 ttys000    0:00.03 /bin/bash --norc --noprofile --noediting
12142 ttys001    0:00.00 /bin/bash --norc --noprofile --noediting
34604 ttys002    0:00.03 /usr/local/Cellar/zsh/5.8_1/bin/zsh (figterm)
 8682 ttys003    0:00.00 /bin/bash --norc --noprofile --noediting
34619 ttys004    0:00.65 /usr/local/Cellar/zsh/5.8_1/bin/zsh --login
34628 ttys004    0:00.01 /usr/local/Cellar/zsh/5.8_1/bin/zsh --login
34675 ttys004    0:00.00 /usr/local/Cellar/zsh/5.8_1/bin/zsh --login
34677 ttys004    0:00.00 /usr/local/Cellar/zsh/5.8_1/bin/zsh --login
34679 ttys004    0:00.00 /Users/otamares/.cache/gitstatus/gitstatusd-darwin-x86
34858 ttys004    0:00.00 (zsh)
31559 ttys009    0:00.00 /bin/bash --norc --noprofile --noediting

❯ env | grep FIG
FIG_INTEGRATION_VERSION=5
FIG_TERM=1
FIG_TERM_VERSION=3
```

**Comment by mschrage** [comment]
Hmm it looks like Fig's zsh integration isn't being set up correctly.

This is what my output looks like:
```
FIG_INTEGRATION_VERSION=5
FIG_TERM=1
FIG_TERM_VERSION=3
FIG_ENV_VAR=1
FIG_CHECKED_PROMPTS=1
```

The output you shared is missing `FIG_ENV_VAR` and `FIG_CHECKED_PROMPTS` which means `~/.fig/fig.sh` isn't being sourced.

Do you mind sharing your `zshrc` and your `zprofile`?

**Comment by mschrage** [comment]
Sorry for the slow response! I'd recommend uninstalling and redownloading the latest version of the app.

We've spent a lot of time on improving stability and this issue is most likely resolved.
