### ISSUE TITLE
Add WezTerm support

### ISSUE THREAD

**Issue by raguay** [withfig/fig#58]
**Is your feature request related to a problem? Please describe.**

Not a problem, just new integration with a new terminal program: WezTerm https://wezfurlong.org/wezterm/

**Describe the solution you'd like**

Currently, fig says that it doesn't support WezTerm.

**Comment by mattschrage** [comment]
Any idea if Wezterm offers any plugin functionality? In order to add support for a terminal emulator, we need to be able to...
1. locate the cursor position
2. determine which tab/pane the user is typing in

**Comment by raguay** [comment]
It does have a way to add functionality using Lua, but I just found this
myself and haven't had the time to invest in it much. But, it looks very
promising and is available on every OS. So, it would be worth it for fig to
be compatible with it if it wants to be in the other ecosystems as well.

**Comment by amjerm** [comment]
+1. I have been using Wezterm for a while and love it. It would be great to be able to use Fig with it.

**Comment by WingofaGriffin** [comment]
Helpful Links (just installed WezTerm today and so far I'm impressed (Alacritty with tab support!?!)

* Config Docs - https://wezfurlong.org/wezterm/config/files.html
* GitHub Discussion Page - https://github.com/wez/wezterm/discussions
* Window Object Docs - https://wezfurlong.org/wezterm/config/lua/window/index.html?highlight=windows#window-object
* Window Event Docs - https://wezfurlong.org/wezterm/config/lua/window-events/index.html
* Pane Object Docs - https://wezfurlong.org/wezterm/config/lua/pane/index.html
* Shell Integration - https://wezfurlong.org/wezterm/shell-integration.html
* Determining Cursor position - https://wezfurlong.org/wezterm/escape-sequences.html?highlight=cursor%20location#other-escape-sequences

Seems overall like it should be doable with some Lua scripting, and is encouraged by the maintainer.

**Comment by mschrage** [comment]
@wez pushed an updated that improves Wezterm's IME support on macOS! 

(It also _seems_ like it is now turned [on by default](https://wezfurlong.org/wezterm/config/lua/config/use_ime.html) as well, but the docs have conflicting information.)

<img width="572" alt="Screen Shot 2022-03-26 at 6 02 07 PM" src="https://user-images.githubusercontent.com/3155109/160262216-84b4d1c4-edf3-41ad-a1fa-e922106f9fc9.png">

I've added experimental support which should be go out in the next release of Fig.

**Comment by wez** [comment]
Nice!  Yes, IME is default enabled on all platforms since the most recent release.  I've updated the docs on that page to make them clearer and internally consistent!

**Comment by SeparateRecords** [comment]
Positioning seems a little broken for me - is there an easy fix?

<img width="606" alt="image" src="https://user-images.githubusercontent.com/52195359/160754562-802f19f4-ba61-40a4-8a78-5f9964007f35.png">

**Comment by mschrage** [comment]
Hmm that is interesting! I wonder if this is based on the version (notice how you have native tabs and I don't).

**Comment by wez** [comment]
@mschrage: FWIW, the version number in Cargo.toml isn't used for wezterm: `wezterm --version` has the correct version info.
Is the caret location taken directly from what wezterm sends to the IME?

**Comment by cocoonkid** [comment]
Awesome! Came here to suggest this. Wezterm is the only one supporting Ligatures through all platforms and I tried them all, was in love with alacritty for a looooong time but Wezterm beats them all.

Thanks so much for adding support!

**Comment by mschrage** [comment]
@wez sorry I missed your response. We take it the cursor position directly from the ime (the offset @SeparateRecords  mentioned has been resolved).

WezTerm is officially supported! To enable it, run `fig install --input-method` and follow the instructions.

**Comment by cocoonkid** [comment]
Amazing ! Thanks!
