### ISSUE TITLE
Prompt to enable 3rd party input method on macOS Monterey

### ISSUE THREAD

**Issue by XiNiHa** [withfig/fig#580]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description
<img width="780" alt="Screen Shot 2021-11-11 at 9 50 35 AM" src="https://user-images.githubusercontent.com/8155259/141217222-519decf1-382c-475d-87bc-0f66c99394af.png">
When launching `Fig.app`, running `fig launch`, or opening a new terminal window, this pops up after few seconds and prevents launching. (Menu bar icon disappears)

### Environment

`fig diagnostic` doesn't work as it's impossible to launch `Fig.app`.

```bash
OS: macOS Monterey (12.0.1)
Chip: Apple M1
Shell: zsh
```

**Comment by mschrage** [comment]
Hey @XiNiHa, this issue should be resolved in v1.0.52. Try redownloading the app.

(Let me know if you need another invite)
