### ISSUE TITLE
Autocomplete stops working in VSCode

### ISSUE THREAD

**Issue by shaylinRVW** [withfig/fig#583]
### Description:

Upon initial install, fig was working and I was able to use it within the integrated terminal in VSCode. 

The following day (same VSCode session) the autocomplete feature fails to work in VSCode. fig commands work but the autocomplete does not. 

I checked iTerm (where i tested it upon initial install as well) and it still works. The iterm session was also left open overnight. So overall, fig is running but the autocomplete feature seems to have ceased only in the VSCode terminal (which is the main reason i installed fig)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.51 (B294)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.51 (B294) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/redvan/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/redvan/.nvm/versions/node/v10.19.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/redvan/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 79671/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
This should be fixed now - we've made a lot of improvements since this issue was made. If it's still broken, let us know and we'll reopen 🙂
