### ISSUE TITLE
Fig adds space to commands with '=' that require no space between '=' and arg

### ISSUE THREAD

**Issue by ShawnCockburn** [withfig/fig#584]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

when using jest I noticed '--' options add a space on auto complete.
not sure if this is intended but the command fails with the space added.

[Youtube video link showing issue](https://youtu.be/ZZ_fFpHgwII)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B305) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: unknown
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 204
SSH Integration: false
Tmux Integration: false
Keybindings path: /Users/Work/.fig/user/keybindings
iTerm Integration: application is not present.
Hyper Integration: installed!
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/Work/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (883) - /dev/ttys002
Current working directory: /Users/Work/Projects/evs2021
Current window identifier: 212/% (co.zeit.hyper)
Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/Work/.fig/bin</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @ShawnCockburn, this is a great catch. Thanks for reporting.

This looks like a small bug in the Fig autocomplete engine. We'll get this fixed.

**Comment by ShawnCockburn** [comment]
No problemo @mschrage :)

**Comment by ShawnCockburn** [comment]
this seems to be fixed
