### ISSUE TITLE
Error: unknown command "bg:ssh" for "fig"

### ISSUE THREAD

**Issue by l-mbert** [withfig/fig#585]
### Description:

I'm running some SSH Commands through `make` and I'm getting the Error:

```
Error: unknown command "bg:ssh" for "fig"
Run 'fig --help' for usage.
unknown command "bg:ssh" for "fig"
```

The Command I'm trying to run is:
`ssh -p 22  [REDACTED]@[REDACTED] "cd /var/www/vhosts/[REDACTED]/httpdocs/current; FLOW_CONTEXT=Production /opt/plesk/php/7.4/bin/php ./flow configuration:show --type Settings --path Neos.Flow.persistence.backendOptions;"`

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Error: EOF
Fig Version:  [?] 
UserShell: /bin/zsh
Bundle path: 
Autocomplete: unknown
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: 
Number of specs: 198
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: 
Hyper Integration: 
VSCode Integration: 
Docker Integration: 
Symlinked dotfiles: 
Only insert on tab: 
Installation Script: 
PseudoTerminal Path: 
SecureKeyboardInput: 
SecureKeyboardProcess: 
Current active process: 
Current working directory: /Users/lambert/Documents/_arbeit/NEOS/[REDACTED]
Current window identifier: 
Path: /Users/lambert/.local/share/solana/install/active_release/bin:/usr/local/opt/php@7.4/bin:/usr/local/opt/php@7.4/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/Users/lambert/.local/share/solana/install/active_release/bin:/usr/local/opt/php@7.4/bin:/usr/local/opt/php@7.4/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/Users/lambert/.nvm/versions/node/v16.6.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/lambert/.cargo/bin:/Users/lambert/.fig/bin</pre>
</p>
</details>

**Comment by JannieT** [comment]
I'm getting this when i do `git pull` for example in iTerm. Same macOS and Fig versions as OP

**Comment by mschrage** [comment]
This is fixed in the latest version of Fig. You can get this update by running `fig update` in your terminal. 

And please let me know if you're still running into issues!
