### ISSUE TITLE
cd command not working

### ISSUE THREAD

**Issue by kadorrna** [withfig/fig#586]
Hi, I have fig and when I do cd there is no popup, it is working with other commands.
Maybe a plugin is making this not to work?

**Comment by nitinprakash96** [comment]
Same is the case for me as well. I'm on MacOS though.

**Comment by mschrage** [comment]
Thanks for letting us know @kadorrna @nitinprakash96. There was a regression that impacted shell suggestions in the previous. 

Try updating to the latest version by running `fig update` and let me know if this resolves the issue for you.

**Comment by nitinprakash96** [comment]
Oh it's back to working again. Thank you so much! Cheers!

**Comment by kadorrna** [comment]
didn't do the update, but it started working!
Thanks
