### ISSUE TITLE
`rm -rf` does not autocomplete directories

### ISSUE THREAD

**Issue by JoeScho** [withfig/fig#587]
### Description:

When attempting to remove a directory using `rm -rf path/to/directory`, fig auto-completes with more flags instead of suggesting paths (after inserting a space after `rf`.

![image](https://user-images.githubusercontent.com/12475501/141498144-4b5e2011-52c3-4a3c-aac6-064312292a8c.png)
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.1|Version 1.0.52 (B305)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B305) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/JSchofield/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/JSchofield/.nvm/versions/node/v12.14.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin:/Users/JSchofield/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (72889) - ttys001
Current working directory: /Users/JSchofield/Documents/projects/projects/example.mfe/app1
Current window identifier: 10318/6DF55352-04A8-4392-8B3D-5ECCD93EC1B6% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @JoeScho! Thanks for reporting this. I can reproduce the bug as well and it does not look like an issue with the [rm](https://github.com/withfig/autocomplete/blob/master/src/rm.ts) completion spec.

Seems like potentially an issue with the autocomplete-engine when using chained options with variadic arguments. 👀

We'll get this fixed up for you.
