### ISSUE TITLE
Tab auto-complete not working

### ISSUE THREAD

**Issue by asafpelegcodes** [withfig/fig#590]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

when I turn on the setting that only shows fig when I hit tab nothing happens. I hit tab and it does not show the fig UI and in addition the regular tab shortcut native to bash/zsh is not working either.

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.52 (B305)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B305) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/asafpeleg/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/asafpeleg/.nvm/versions/node/v16.11.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/asafpeleg/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by brendanfalk** [comment]
Yes can confirm this bug is reproducible on v1.0.52 and above. We will fix

**Comment by asafpelegcodes** [comment]
is this closed because it has been released or some other reason?

**Comment by grant0417** [comment]
I believe this should have been fixed a long time ago and we are cleaning up old issues.

**Comment by asafpelegcodes** [comment]
Thank you!
