### ISSUE TITLE
Getting "fig_hide:1: file exists: ~/fig/logs/zsh.log" when pressing arrow up in zsh

### ISSUE THREAD

**Issue by alasdairtran** [withfig/fig#592]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Issue Details

This seems to be a new problem after fig just updated itself to 1.0.52. In zsh, when I press the arrow up key to go back to the previous command, the message `fig_hide:1: file exists: ~/.fig/logs/zsh.log` is printed out in the terminal. 

The problem was fixed if I changed line 40 in `~/.fig/shell/zle.zsh` from 

```sh
  command -v fig 2>"$HOME"/.fig/logs/zsh.log 1>/dev/null && fig hook hide 2>&1 1>/dev/null
```

to

```sh
  command -v fig 2>>"$HOME"/.fig/logs/zsh.log 1>/dev/null && fig hook hide 2>&1 1>/dev/null
```

(this is the same solution proposed in #524 but now on a different line)

**Comment by mschrage** [comment]
Hey @alasdairtran! Sorry that this issue has popped up again. Thanks for reporting. I'll push a fix tomorrow.

**Comment by mschrage** [comment]
This issue has been fixed as of the latest build. Run `fig update` to get the latest version.

cc @alasdairtran
