### ISSUE TITLE
Can not find folder in directories

### ISSUE THREAD

**Issue by Hurleywflow** [withfig/fig#594]
Hi,

I have found some bugs here, please see the attached files below, at this directory, I can not find the Dev folder in my directories.

kind regards,

Hurley

![Screen Shot 2021-11-14 at 14 15 52](https://user-images.githubusercontent.com/86563399/141666148-4ca9fd0a-90cb-4891-88de-d3897ec4e0a7.png)

![Screen Shot 2021-11-14 at 14 16 23](https://user-images.githubusercontent.com/86563399/141666151-4f57b608-4de8-4979-86a2-67ade73f11c8.png)
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B310)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B310) [Australian] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/hurleynguyen/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hurleynguyen/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
It looks like the Fig did not determine the working directory correctly. Restarting your terminal should resolve this issue. 

Please let me know if this persists.

**Comment by Hurleywflow** [comment]
Thanks, It was help.
