### ISSUE TITLE
output of scripts that run on shell startup gets included in pseudoterminal settings.json value

### ISSUE THREAD

**Issue by chadlavi-casebook** [withfig/fig#597]
### Description:

output of a script that runs when I start a zsh shell gets copied into the pseudoterminal key in my fig settings.json file, corrupting it.

I have manually fixed it by deleting that output as reflected in the diagnostic below.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B310)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B310) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Chad/.fig/bin/fig
Accessibility: true
Number of specs: 207
SSH Integration: false
Tmux Integration: true
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/Chad/.nvm/versions/node/v12.22.1/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/Chad/.rvm/bin:/Users/Chad/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @chadlavi-casebook! Thanks so much for reporting this. I have updated our install script so this will no longer occur.
