### ISSUE TITLE
Aliases and shortcuts for often used commands

### ISSUE THREAD

**Issue by rickardw** [withfig/fig#60]
Great tool and it has already improved my workflow!

**Is your feature request related to a problem? Please describe.**
One feature I’m missing would be to help me suggest more complete commands then just the next part. If I start writing “git”, very often I write "git commit -m" and not just show "commit".

**Describe the solution you'd like**
If I have added a alias it could be displayed as a separate list or in the same box (like top suggestion).

In my case it’s mostly usable for really long and more complex commands I run and want to be able to quickly run. Saving them in another document etc is where Fig is such a good idea. Because I want them visible in a list exactly where I’m working, in the Terminal.

**Comment by mattschrage** [comment]
We definitely want to support this kind of behavior! Stay tuned.

**Comment by SeparateRecords** [comment]
Personal shortcuts and mixins are now available for this! https://fig.io/docs/guides/personal-shortcuts
