### ISSUE TITLE
Autocomplete doesn't show directories and files

### ISSUE THREAD

**Issue by adlermedrado-mb** [withfig/fig#602]
### Description:
After installing, fig doesn't executed the script .fig/fig.sh and then I executed it manually, but when I'm typing the command cd, it just show a litte square with 3 colored balls and doesn't show the options in autocompletion box.
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B313)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B313) [U.S. International – PC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/medrado/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: true
Keybindings path: <none>
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @adlermedrado-mb! Are you free to jump on a call quickly?

**Comment by mschrage** [comment]
Any updates @adlermedrado-mb?

**Comment by 1xyz** [comment]
I have a similar issue, however when I run within `tmux`

```shell
$ fig app set-path

  Setting $PATH variable in Fig pseudo-terminal...

Error:  could not determine terminal bundle
```
