### ISSUE TITLE
Split terminals with autocomplete

### ISSUE THREAD

**Issue by bzuker** [withfig/fig#603]
### Description:
When using split terminals, the autocomplete is adding the input in a terminal that is not currently focused.

<img width="1348" alt="Screen Shot 2021-11-18 at 19 33 37" src="https://user-images.githubusercontent.com/8533385/142507546-6c4df3f1-09e8-4989-a982-065c88aab678.png">
<img width="1431" alt="Screen Shot 2021-11-18 at 19 34 00" src="https://user-images.githubusercontent.com/8533385/142507575-be820a5e-a1c9-4162-899f-4088566b3b38.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.52 (B315)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B315) [U.S. International - PC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/my-user/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: false
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (44225) - /dev/ttys003
Current working directory: /Users/my-user
Current window identifier: 100909/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @bzuker! Thanks for reporting this and sorry for the slow response. We've fixed this issue. Fig will insert into the correct terminal session even when you use multiple panes.

To update to the latest version either run `fig update`. You can also redownload the app [here](https://fig.io/welcome).
