### ISSUE TITLE
bash: __bp_sanitize_string: command not found

### ISSUE THREAD

**Issue by destari** [withfig/fig#604]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

All commands show the error seen in the subject line above.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B315)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B315) [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/anderson/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/bash (15150) - /dev/ttys006
Current working directory: /Users/anderson
Current window identifier: 97129/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @destari, thanks so much for letting us know! We just made some changes to our `bash` integration.

Would you mind sharing your .bash_profile and your .bashrc?

**Comment by mschrage** [comment]
This issue has been fixed! Please update to the latest version of fig by running `fig update` or redownload the app [here](https://fig.io/welcome).
