### ISSUE TITLE
Autocomplete not in the chosen tmux session

### ISSUE THREAD

**Issue by linxuyalun** [withfig/fig#605]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hi, I am using fig in iterm, and I found a bug when I am using it with tmux multi-session

for example, I divide item into three tmux session

When I type something in one session, Fig gave me the prompt, it's cool.

However, when I chose one given option, and then I pressed the 'enter' button, the rest contents were not printed in the focused session. Instead, they were printed into another session. In my case, it was the right one.

For example:

![image](https://user-images.githubusercontent.com/25969296/142615686-b09c8c21-a7dd-4c47-96fb-9a540d847201.png)

And then I pressed the enter button and what I saw was:

![image](https://user-images.githubusercontent.com/25969296/142615811-e086aae5-a92b-4fb4-a4f4-e3e636abed96.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B315)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B315) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/linxuyalun/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: true
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by linxuyalun** [comment]
any suggestions or any progess? @mschrage

**Comment by mschrage** [comment]
How do you launch your `tmux` session? Are all three panes created in quick succession?

**Comment by linxuyalun** [comment]
> 1. fig diagnostic
ok I use this method in different panes and they print the same Current window identifier

```
Current window identifier: 40820/90B4E38A-AC53-4143-A5E8-04EDD5793F1B% (com.googlecode.iterm2)
```

**Comment by linxuyalun** [comment]
`fig source` does resolve the issue but it seems that it has another issue

if I run `fig source` in the focused window, I can get the right current window identifier. However when I change my current window, the Current window identifier doesn't change, which means I have to run `fig source` again.

Some snapshots:

Now my focused window is this:

![image](https://user-images.githubusercontent.com/25969296/142803394-ed4569aa-9c14-4c14-a582-e929517459d9.png)

and then I change my session to another ( BTW, I try changing my session both in the mouse mode and keyboard mode and get the same results)

![image](https://user-images.githubusercontent.com/25969296/142803526-b67639ab-2922-4b1a-8c88-e1382440f7de.png)


again the current window identifier doesn't change

![image](https://user-images.githubusercontent.com/25969296/142803613-a039f033-0809-4ccb-bee7-df5fa1e70a71.png)

**Comment by linxuyalun** [comment]
@mschrage any suggestions?

**Comment by linxuyalun** [comment]
after new fig version released, this issue seemed to be fixed.

Thx for you guys effort 👍🏼
