### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by AlexNodex** [withfig/fig#606]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Issue Details

Your installation claims it can "Sign in Without Password", however, attempting this yeilds "invalid input" (see screenshot
![Screenshot 2021-11-19 at 12 32 22](https://user-images.githubusercontent.com/17162626/142623389-470ccebf-1e55-4b90-8024-ae8ac39d434d.png)
)

### Environment

```bash
M1 Mac OS Monterey - Although I don't expect this matters as it's down to input validation!
```

**Comment by fedeci** [comment]
Are you inserting the email? I am quite surprised to see such a bug 🤔

**Comment by AlexNodex** [comment]
Hi

The button says "Sign in without password" which suggests that I don't need an email to use the app!

**Comment by fedeci** [comment]
No, it suggest you don't need a password but you need to add an email.😃

**Comment by AlexNodex** [comment]
Why do you need an email for the app to work?

**Comment by mschrage** [comment]
Hey @AlexNodex, this is the expected behavior. We ask people to login with an email in order to provide support and enable collaboration features (http://fig.io/teams).

**Comment by skratchdot** [comment]
> Hey @AlexNodex, this is the expected behavior. We ask people to login with an email in order to provide support and enable collaboration features (http://fig.io/teams).

@mschrage - Will there ever be an option for guest sign-in? I see it was hinted at here:
withfig/autocomplete#42 (comment)

This app looks awesome, but I'd love a way to use it without giving out my work email :)

**Comment by wieland-s** [comment]
> This app looks awesome, but I'd love a way to use it without giving out my work email :)

Same here. Don't want to "login", but the apps look nice.

**Comment by mschrage** [comment]
Hey @skratchdot @wieland-s! No immediate plans to add a guest login - having people sign in with their email has been incredibly helpful for providing support and getting in touch with users when things are breaking.

FYI you can use your personal email instead, if that would make you feel more comfortable.

**Comment by DiegoKrupitza** [comment]
> > Hey @AlexNodex, this is the expected behavior. We ask people to login with an email in order to provide support and enable collaboration features (http://fig.io/teams).
> 
> @mschrage - Will there ever be an option for guest sign-in? I see it was hinted at here: [withfig/autocomplete#42](https://github.com/withfig/autocomplete/issues/42) (comment)
> 
> This app looks awesome, but I'd love a way to use it without giving out my work email :)

Totally agree. I think the tool is really cool but I do not want to supply me email for a terminal tool. 
I hope that in the near future there is a way to use this tool without providing an email.

**Comment by AlexNodex** [comment]
> +1 Don't want to login to an app that claims to run only locally and is private by design... The features itself are really cool (after a quick first look) but the need to sign up is a downer for me.

It's also a bit of a pain to uninstall afterwards, it leaves lots of scripts lying about after you remove it from Applications!

**Comment by mschrage** [comment]
Yeah, you can’t just move the app to Trash which is unusual. 

If you’re still running into issues fully uninstalling, check out this guide: https://fig.io/support/other/uninstall

**Comment by ikoruk** [comment]
Really not normal to require an email to install. If you don't use collaboration features it shouldn't be necessary.

**Comment by ikoruk** [comment]
It honestly feels like those reasons are just excuses, and the real reason is that this is more of a start-up than a useful tool and VC/start-up mentality calls for having quantifiable users and as much data as possible.

**Comment by misolori** [comment]
[Comment](https://github.com/withfig/fig/issues/1234#issuecomment-1085528770) from @SeparateRecords:

> We don't have immediate plans to skip entering an email, but I totally get that not everyone wants to (or can) use their actual email address

Just in case if people were waiting around for this to change

**Comment by notstephen** [comment]
Really no excuse for putting the non-cloud features behind a login. Thankfully a painless uninstall.

**Comment by pavelkornev** [comment]
+1 
```
brew uninstall fig
```

**Comment by sparr** [comment]
I had no idea this was a requirement, I just reported the program wasn't working when I uninstalled it. Requiring an email address and login just to do things like autocomplete shell commands is not reasonable.
