### ISSUE TITLE
Fig integration breaks iTerm 

### ISSUE THREAD

**Issue by Stvad** [withfig/fig#607]
### Description:

After installing Fig integration - iTerm won't start anymore

<img width="586" alt="image" src="https://user-images.githubusercontent.com/81347/142649409-3af3b2e8-9c8e-4d8c-8bf0-ba10e72e5637.png">

And I'm not really clear on how to fix that 😅. Disabling iTerm integration in Fig settings does not seem to help. 

Seems potentially similar to #542 though in this case I don't see any specific errors =\

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B315)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B315) [Colemak] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/vlad/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/vlad/.toolbox/bin:/Users/vlad/.nvm/versions/node/v16.2.0/bin:/Users/vlad/opt/miniconda3/bin:/Users/vlad/perl5/bin:/Users/vlad/.rbenv/shims:/Users/vlad/.toolbox/bin:/apollo/env/SDETools/bin/:/usr/local/bin:/Users/vlad/bin::/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/bin:/usr/local/bin:/Users/vlad/.local/bin:/Users/vlad/.cargo/bin:/usr/local/smlnj/bin:/usr/local/bin:/usr/local/opt/fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by Stvad** [comment]
Ok, I think actually disabling integration helped, but I needed to fully restart iTerm

**Comment by mschrage** [comment]
Hey @Stvad, is this issue resolved now? Does Fig work in iTerm (or the native Terminal.app)?

This is potentially the result of a conflict with our shell integration and some other plugin for `zsh`. Do you use any tools like oh-my-zsh or zim:fw?

I think the linked issue (#542) is unrelated.

**Comment by aredridel** [comment]
For me it's `antigen bundle softmoth/zsh-vim-mode` in my `.zshrc` that breaks my shell.

**Comment by Stvad** [comment]
@mschrage in the prev message I was talking about making iTerm work at all after Fig broke it. But now upon re-enabling the integration it seems to work and does not break the iTerm anymore 🤔
