### ISSUE TITLE
Unable to complete setup

### ISSUE THREAD

**Issue by abnerey** [withfig/fig#608]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When reaching the last step of the setup Fig is not letting me sign-in or continue due to a network issue:

![image](https://user-images.githubusercontent.com/11546757/142656541-89d247e3-bfa1-4783-8c02-84ecf503d12b.png)

I'm not using a VPN or any network trackers, it's a clean laptop.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.0|Version 1.0.52 (B315)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B315) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/aajuarezd/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @abnerey, we've investigated this and it looks like it was the result of a brief Google Cloud outage earlier that took our 3rd party login provider down. 

If you go through the login flow again, everything should be working but please let me know if you are still running into this issue and I will reopen.
