### ISSUE TITLE
Terminal session freezes and does not further new input

### ISSUE THREAD

**Issue by lordpengwin** [withfig/fig#611]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I don't know if this is related to fig or not but has started since i installed Fig. Sometimes when running a command line in a zsh shell in iTerm, the entire iTerm tab just freezes up. ^C, ^Z and ^D do nothing and if the command line tool is killed in a separate window nothing happens. The only thing I can do is to kill the iTerm tab.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.1|Version 1.0.52 (B315)|/usr/local/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B315) [U.S.] 
UserShell: /usr/local/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/stephen/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @lordpengwin! Thanks so much for reporting this. I'm not 100% sure this is a Fig issue, but either way we will investigate this as it sounds like a pretty serious bug.

Do you mind sharing your dotfiles?

**Comment by lordpengwin** [comment]
Sorry I can’t really share my dot files due to company policy. I’m not sure it is a Fig problem either, maybe more of a data point if anyone else complains.

**Comment by mschrage** [comment]
No worries. Any ideas on how to reproduce the behavior?

Could you go to `~/.zprofile` or `~/.profile` (whichever exists) and add `export FIG_LOG_LEVEL=DEBUG` to the top of the file. This will let increase the amount of logging that occurs and will help us figure out if something is breaking with Fig.

**Comment by mschrage** [comment]
Hey @lordpengwin! This definitely was a Fig issue and we have fixed it in the latest build.

You can update by running `fig update` or re-download the app [here](https://fig.io/welcome).

**Comment by lordpengwin** [comment]
Great to hear thanks!
