### ISSUE TITLE
bash: __bp_sanitize_string: command not found error on Mac

### ISSUE THREAD

**Issue by ospatil** [withfig/fig#612]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

First of all, thank you for fig. I just installed it today and it looks amazing 👏🏼.

I use iTerm. After installation, I see the following error message `bash: __bp_sanitize_string: command not found` whenever I open a new terminal or after running any command in the terminal:

```sh
❯ time

real	0m0.047s
user	0m0.012s
sys	0m0.019s
bash: __bp_sanitize_string: command not found

❯ uname
Darwin
bash: __bp_sanitize_string: command not found
```

Am I missing something?

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.1|Version 1.0.52 (B315)|/usr/local/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B315) [Canadian English] 
UserShell: /usr/local/bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/e1082265/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: true
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: ]1337

**Comment by mschrage** [comment]
Hey @ospatil are you free to jump on a call quickly? We are actively looking into this issue right now. cc @sullivan-sean

**Comment by ospatil** [comment]
@mschrage sure. Let me know how.

**Comment by c0** [comment]
I also started having this issue a few days ago (it wasn't in earlier versions). LMK what info you need and how I can help.

**Comment by mschrage** [comment]
Hey @c0! What build are you on? Can you `fig diagnostic` and share the output here?

**Comment by nlindroos** [comment]
Same issue here. Concerns all bash shell instances regardless of if they are run through iTerm, VS Code or the Terminal app.

<details>
<summary>
<i>fig diagnostic<i>
</summary>

```bash
Fig Version: Version 1.0.52 (B317) [Finnish]
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 199
SSH Integration: false
Tmux Integration: false
Keybindings path: /Users/nili/.fig/user/keybindings
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: true
Installation Script: true
PseudoTerminal Path: <REDACTED>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
```
</details>

**Comment by mschrage** [comment]
Can you share your dotfiles @c0 @ospatil @nlindroos? Do you use `starship` or any other custom prompt or theme?

**Comment by ospatil** [comment]
@mschrage, indeed, I use `startship`.
<details>
<summary>.bashrc</summary>

```sh
#### FIG ENV VARIABLES ####
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# for direnv, so that .envrc files can set up local environment properly
eval "$(direnv hook bash)"

export PATH="/usr/local/sbin:$PATH"

# for golang
export PATH=$PATH:~/go/bin

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# for pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"

# bash autocomplete
export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# enable k8s autocompletion
source <(kubectl completion bash)

# set shortcut to kubectl and allow code completion for it
alias k=kubectl
# run bash in vi mode and reinstate keys for clearing screen
set -o vi
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'

# Volta node envrionment manager
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# Rust cargo
source "$HOME/.cargo/env"

# Starship prompt
eval "$(starship init bash)"

# Add GNU make installed using brew to path
PATH="/usr/local/opt/make/libexec/gnubin:$PATH"

#### FIG ENV VARIABLES ####
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
```

</details>

**Comment by ospatil** [comment]
@mschrage, I narrowed it further. It seems fig doesn't like iTerm shell integration. If I comment out the following line in my `.bashrc`: 
```sh
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
```
The error goes away. Hope this helps.

**Comment by mschrage** [comment]
Thank you so much @ospatil! This is tremendously helpful :)

**Comment by mschrage** [comment]
The issue here is a conflict between the version of the `bash_prexec` library used in previous versions of iTerm's shell integration and the version that Fig uses currently.
