### ISSUE TITLE
I'm unable to select the suggestion fig provide using tab nor intro.

### ISSUE THREAD

**Issue by juanjogramo** [withfig/fig#614]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I'm getting this error after running fig doctor

➜  ~ fig doctor

Let's make sure Fig is running...

✅ Fig bin exists
✅ Fig in PATH
✅ Fig is running

Let's check your dotfiles...

✅ Fig ENV variables are in ~/.profile
✅ Fig ENV variables are in ~/.bashrc
✅ Fig ENV variables are in ~/.zshrc

Let's check your if your system is compatible...

✅ Running macOS
✅ macOS version is 11.x or higher

Let's check what fig diagnostic says...

✅ Installation script
✅ Shell /bin/zsh is compatible
✅ Fig is installed in /Applications/Fig.app
✅ Autocomplete is enabled

❌ CLI tool path
   The Fig CLI must be in /Users/juanjogramo/.fig/bin/fig

✅ Accessibility is enabled
✅ PATH and PseudoTerminal PATH match
✅ Secure keyboard input

Let's check your your integration statuses...

✅ iTerm integration is enabled
✅ VSCode integration is enabled

Fig still not working?
Run fig issue to let us know!
Or, email us at hello@fig.io!

I'm unable to select the suggestion fig provide using tab nor intro.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B317) [Spanish] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/juanjogramo/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (2652) - /dev/ttys004
Current working directory: /Users/juanjogramo
Current window identifier: 288/% (com.googlecode.iterm2)
Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/juanjogramo/.fig/bin</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @juanjogramo! There was a regression in the last build that caused insertion to sometimes stop working depending on your terminal environment. We've fixed it in the most recent version of the up. 

You can upgrade by running `fig update` or by re-downloading the app [here]( https://fig.io/welcome).
