### ISSUE TITLE
Programmatic generation of PATH

### ISSUE THREAD

**Issue by ryanccn** [withfig/fig#615]
### Description:

> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When using tools such as [`fnm`](https://github.com/Schniz/fnm) that generate a different `PATH` value for each shell, the `PATH` of the shell and the pseudoshell never match.

```bash
$ fnm env
export PATH="/var/folders/1d/mqqn5cvn7h566bjq41m_pjf00000gp/T/fnm_multishells/2060_1637460631688/bin":$PATH
...
$ fnm env
export PATH="/var/folders/1d/mqqn5cvn7h566bjq41m_pjf00000gp/T/fnm_multishells/2078_1637460632264/bin":$PATH
...
```

It would be better if there were an option to **programmatically generate the PATH** like how the environment variables are set in the pseudo-shell instead of being a static configuration.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B317) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/[redacted]/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/[redacted]/.deno/bin:/var/folders/1d/mqqn5cvn7h566bjq41m_pjf00000gp/T/fnm_multishells/99479_1637459526297/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/[redacted]/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (1305) - /dev/ttys002
Current working directory: /Users/[redacted]
Current window identifier: 42067/% (com.googlecode.iterm2)
Path: /Users/[redacted]/.deno/bin:/var/folders/1d/mqqn5cvn7h566bjq41m_pjf00000gp/T/fnm_multishells/1376_1637460423505/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/[redacted]/.fig/bin</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @ryanccn! This is definitely an interesting case. Does this impact any of the completions specs you use? (eg. they attempt to run shell commands to provide dynamic suggestions, but since the PATH is incorrect the executable is not found).

The long term solution is probably to **keep track of all environment variables that are associated with each terminal session** and then allow the autocomplete engine to specify the value of the PATH variable when running a command on behalf of the user.

Does that make sense? How do you imagine "programmatically generate the PATH" working? Would love to hear your thoughts :)

**Comment by ryanccn** [comment]
I think that Fig can somehow **inherit** the PATH from the current shell in `.fig/shell/pre.sh` or `.fig/fig.sh` (probably the latter since it’s at the end, after all the other stuff that sets dynamic PATHs have run).

**Comment by SeparateRecords** [comment]
I think this is fixed now? @grant0417 can you confirm?
