### ISSUE TITLE
"Could not link with terminal. Error listening on port ..."

### ISSUE THREAD

**Issue by FengZhiyuan** [withfig/fig#619]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

![image](https://user-images.githubusercontent.com/11424669/142792815-95b63c22-caa7-4721-8562-909b7b9c527c.png)

Restart app has no effect

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.3.19D76|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>
It looks like Fig is not running.
Try running: fig restart

</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @FengZhiyuan! So sorry you're running into this.

Can try restarting your computer? That might fix the issue. Otherwise, is is possible that your `/etc/hosts` has been edited in some way that would prevent localhost from being assigned?

**Comment by FengZhiyuan** [comment]
> Hey @FengZhiyuan! So sorry you're running into this.
> 
> Can try restarting your computer? That might fix the issue. Otherwise, is is possible that your `/etc/hosts` has been edited in some way that would prevent localhost from being assigned?

I have tried restarting the computer, the /etc/hosts file is emptied, and other apps are quit. But it still has no effect, and the same error is reported.

**Comment by mschrage** [comment]
Very strange. Either way, we are deprecating the websocket server and switching to UNIX sockets, which should resolve this issue. Should go live in the next release.

**Comment by shiran565** [comment]
I encountered the same phenomenon

**Comment by mschrage** [comment]
Also I think I've figured out what causes this @shiran565 @FengZhiyuan:

You must have this in your `/etc/hosts` file since Fig uses `localhost` internally and if these values aren't set the address can't be resolved.

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

**Comment by shiran565** [comment]
Indeed! Fig can work normally by add an `localhost` to `/etc/hosts` file.
Thank you @mschrage. You're awesome！

**Comment by FengZhiyuan** [comment]
> Also I think I've figured out what causes this @shiran565 @FengZhiyuan:
> 
> You must have this in your `/etc/hosts` file since Fig uses `localhost` internally and if these values aren't set the address can't be resolved.
> 
> ```
> ##
> # Host Database
> #
> # localhost is used to configure the loopback interface
> # when the system is booting.  Do not change this entry.
> ##
> 127.0.0.1	localhost
> 255.255.255.255	broadcasthost
> ::1             localhost
> ```

Can be used normally.Thank you!
