### ISSUE TITLE
Conflict between zsh-autosuggest and Fig

### ISSUE THREAD

**Issue by mattschrage** [withfig/fig#62]
> So basically, let’s say that I have a folder called “Photos” and inside that folder I have another one called “Wallpapers”.
> If I previously opened that path with the command:
>```
>	$ cd Desktop
>	$ cd Photos/Wallpapers
>```
> The next time that I type “cd Photos”, zsh-completions/zsh-autosuggestions automatically suggest the following path:
>```
>	$ cd Desktop
>	$ cd Photos/Wallpapers
>```
> while Fig displays the dropdown list where I press Enter to access to /Desktop/Photos.
>
> So what happens is that iTerm successfully access to /Desktop/Photos while the command autosuggested is Photos/Wallpapers.

![bug1](https://user-images.githubusercontent.com/3155109/116353574-dd5c6c00-a7ab-11eb-8e21-1202d19871f9.png)
![bug2](https://user-images.githubusercontent.com/3155109/116353579-df262f80-a7ab-11eb-875e-f05cc96805e6.png)
![bug3](https://user-images.githubusercontent.com/3155109/116353583-dfbec600-a7ab-11eb-886e-1bed64931a8a.png)

**Comment by EliasGcf** [comment]
Hey!

Is there any news about this issue?
Some workaround to solve the problem?

Thanks!

**Comment by mattschrage** [comment]
The only workaround right now is to disable `zsh-autosuggest`, which is a bummer.

I will spend some more time looking into this.

**Comment by mattschrage** [comment]
This will be fixed in the next release (v1.0.44)! 🙌

**Comment by mattschrage** [comment]
Fix is live! Closing the ticket.

**Comment by fretwellian** [comment]
When I open my iTerm I get 
```
/.fig/shell/zle.zsh:cd:110: too many arguments
fig_precmd:cd:81: too many arguments
```
Posting here because it pointing to this fix. Not sure where to even start to debug I'm afriad :-(
