### ISSUE TITLE
Expose environment variables to generators

### ISSUE THREAD

**Issue by clo4** [withfig/fig#620]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
This is _similar_ to #225, but does not require the shell to have the same variables - just to give generators access to them.

I'd like some way to use the user's environment variables in a generator.
My primary use case for this is for `deno run --allow-env=var1,var2,etc...`. It would be nice to suggest the user's actual environment variables.

Here are my ideas for how this could look in a spec:

```typescript
// 1. "env" template
const A: Fig.Generator = {
  getQueryTerm: ",",
  template: "env",
};

// 2. ShellContext function (explicitly request a Map<string, string>, or maybe just a plain object?)
const B: Fig.Generator = {
  getQueryTerm: ",",
  custom: async (tokens, executeShellCommand, shellContext) => {
    return (await shellContext.getEnvironment())
      .entries()
      .map(([name, value]) => ({ name, description: value }));
  },
};
```

Of course, I don't know the internals of the autocomplete engine - I'd imagine copying the environment is easy enough but keeping it up to date would be more challenging.

(I asked about this on Discord a while ago, just wanted to bring it up on GH to track it 😊)

**Comment by mschrage** [comment]
This is supported in the latest version of Fig.
```ts
  custom: async (_, _, context) => {
    /// context.environmentVariables: Record<string, string>
   
  },

```
