### ISSUE TITLE
Uninstall does not remove 00_fig_pre.fish and 99_fig_post.fish

### ISSUE THREAD

**Issue by alex-grover** [withfig/fig#622]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:

After uninstalling, empty `~/.config/fish/conf.d/00_fig_pre.fish` and `99_fig_post.fish` in the same directory are left behind. I noticed because the JetBrains IDEs try to source these files and print some errors when opening the terminal in the IDE. Nothing is printed when opening a normal shell, unless you run `source .../99_fig_post.fish` yourself.

### Environment

```bash
Intel mac on 12.0.1, default macOS terminal app, fish installed via Homebrew
```

**Comment by mdmuaj13** [comment]
Same here
![Screenshot 2021-11-23 at 10 30 31 AM](https://user-images.githubusercontent.com/20964899/142971601-1322d52b-f524-428d-9ea9-2f9cd56883ab.png)
.

**Comment by mdmuaj13** [comment]
Facing same issue here.

> fig_zsh_redraw:8: command not found: fig

**Comment by mschrage** [comment]
Thanks for reporting this issue @alex-grover and @mdmuaj13! Definitely want to get this fixed up. 

First question: how did you uninstall Fig?
