### ISSUE TITLE
Random characters appear when creating new terminal

### ISSUE THREAD

**Issue by jasonlong** [withfig/fig#624]
### Description:

When I open a new terminal, I get some seemingly random characters both before fish's welcome text and at the prompt. I use vim mode and to correct this state, I need to hit <kbd>esc</kbd> and then delete those characters. I don't see this behavior w/o Fig installed.

https://user-images.githubusercontent.com/6104/143032392-8f9e836b-b5c3-42c5-ac00-a8cdf381c743.mp4

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B317)|/usr/local/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B317) [U.S.] 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jason/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: true
Keybindings path: <none>
iTerm Integration: true 
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/fish/3.3.1/bin/fish (6974) - /dev/ttys006
Current working directory: /Users/jason
Current window identifier: 105/% (co.zeit.hyper)</pre>
</p>
</details>

**Comment by jasonlong** [comment]
I was able to work around this for now by commenting out the line inside this `if` (from `~/.fig/shell/post.fish`):

```sh
  # Prevents weird interaction where setting the title with ANSI escape
  # sequence triggers prompt redraw.
  if [ -d /Applications/Fig.app -o -d ~/Applications/Fig.app ] && command -v fig 2>&1 1>/dev/null
    # fig settings autocomplete.addStatusToTerminalTitle false &; disown
  end
```

**Comment by mschrage** [comment]
Thanks for sharing your fix @jasonlong! This should be pushed live now.
