### ISSUE TITLE
Suggestion & suggestion selection issues

### ISSUE THREAD

**Issue by ArthurGoupil** [withfig/fig#628]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I can't select a suggestion (enter or tab key) + i looks like sometimes, when I manually enter a folder, list of suggestions is not updated.
https://www.loom.com/share/e7607883fcf74051aa3dbce78e5a65dd

I'm using Oh-my-Zsh

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.4.0|Version 1.0.52 (B315)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B315) [Dev] [French] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/arthurgoupil/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (72486) - ttys005
Current working directory: /Users/arthurgoupil/Documents
Current window identifier: 16977/7465D15A-88B5-4A17-8761-F04E3CAEAFD7% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @ArthurGoupil!  Thanks for letting us know. This issue is resolved in the latest version of Fig!

You can update by running `fig update` or redownload the app [here](https://fig.io/welcome).

**Comment by adrianbrowning** [comment]
@mschrage Just wanted to say I had the same issue, and re-loading sorted the problem.
Thank you for such an amazing product!
