### ISSUE TITLE
Suggestions not inputted on enter

### ISSUE THREAD

**Issue by Aransh** [withfig/fig#631]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

While suggestions appear, often they are not inputted when tapping enter while a suggestion is selected.
This happens several times a day, and persists until I restart fig

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B317)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B317) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/aransh/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/opt/homebrew/opt/libpq/bin:/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/aransh/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Aransh @slorenzo @amit-carrotsense! So sorry about this issue. We had a regression in the last build to broke insertion in certain terminal environments.

This is fixed in the latest version of the Fig. You can update by running `fig update` or redownload the app [here](https://fig.io/welcome).
