### ISSUE TITLE
Paste not available with dropdown open

### ISSUE THREAD

**Issue by zidadrtl** [withfig/fig#632]
### Description:
The most recent version of fig has some issues for me:
- paste doesn't work when the autocomplete dropdown is open
- even when there is no autocompletion needed (so I typed the entire command) I have to press enter twice to run the command

I use bash, not sure why the details down here show zsh.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.1|Version 1.0.52 (B317)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B317) [Dutch] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/**/.fig/bin/fig
Accessibility: true
Number of specs: 207
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/wtijsma/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: **
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/bash/5.1.8/bin/bash (47491) - /dev/ttys012
Current window identifier: 80088/D48793CD-0A0A-4637-AA68-9512A0993D68% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @zidadrtl thanks so much for reporting this. I'm not sure I understand exactly what's going on.

Are you saying that you cannot paste text into your terminal from your clipboard while Fig is open? Or that inserting text using Fig does not work?

**Comment by zidadrtl** [comment]
It seems it was intermittent, so after a restart it would work again as expected. 

Unfortunately now I uninstalled fig because it was more often not working than working (so enter didn't autocomplete at all or I had to press enter 2x even though what I typed already exactly matched the autocomplete suggestion). 

If it was working it was great, but it caused too much "noise" because it only worked briefly for me before breaking.

**Comment by fedeci** [comment]
Let's keep this open because maybe the bug still need to be fixed.

**Comment by zidadrtl** [comment]
sure, I just think there might be something strange with my setup if no one else is experiencing this instability.

**Comment by mschrage** [comment]
Hey @zidadrtl! Would you be open to doing a debugging call together: https://calendly.com/mschrage/30min ?

**Comment by zidadrtl** [comment]
yes sure!

**Comment by zidadrtl** [comment]
In the end a clean reinstall of fig (instead of running updates) has fixed the issues for me, thanks for the call @mschrage!
