### ISSUE TITLE
Fig is introducing latency when typing

### ISSUE THREAD

**Issue by vernak2539** [withfig/fig#633]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig causes my terminal to hang. I've attached a video. When there are long pauses, it means that I've typed something but it's just not appearing. I can see fig is the process that's happening via the tab

**Note**: I quit Fig, opened a new terminal, and the issues is still happening (fig seems to be doing work)

https://user-images.githubusercontent.com/521270/143474812-c8aa79e9-eb3b-4118-8c7f-f1e9871cfbb0.mov

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.52 (B317)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B317) [Dev] [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/alexvernacchia/.fig/bin/fig
Accessibility: true
Number of specs: 213
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/alexvernacchia/.gvm/bin:/Users/alexvernacchia/google-cloud-sdk/bin:/Users/alexvernacchia/.avn/bin:/Users/alexvernacchia/bin:/Users/alexvernacchia/deliveroo/executables:/Users/alexvernacchia/.rbenv/shims:/usr/local/opt/gettext/bin:/usr/local/opt/qt/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/alexvernacchia/.fig/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/alexvernacchia/go/bin:/Users/alexvernacchia/deliveroo/deliveroo-local/delos/exe:/Applications/Postgres.app/Contents/Versions/9.6/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (59627) - /dev/ttys001
Current working directory: /Users/alexvernacchia/deliveroo/create-deliveroo-tool
Current window identifier: 81929/D25A1C39-F967-4D6D-B97F-AA2CAEFEA22C% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @vernak2539 (and @bpartridge83)! So sorry you are running into this. We have pushed a hot fix that resolves this bug. 

You can update to the latest version by running `fig update`.

Let me know if you still experience this behavior after updating and I will reopen this issue.

**Comment by vernak2539** [comment]
@mschrage This is still happening to me. I think it happens more so when using git alias'. I've also just updated iTerm to Build 3.4.14

**Comment by mschrage** [comment]
@vernak2539 sorry that this wasn't resolved. Can you run `fig diagnostic` and share the output here?

**Comment by vernak2539** [comment]
I've since uninstalled it. But, I'll try to install it again and see what happens

**Comment by mschrage** [comment]
Thanks! If you want to debug this together, please grab some time on my calendar: https://calendly.com/mschrage/30min

**Comment by vernak2539** [comment]
It just started happening again. Usually happens when interacting with git and trying to use backspace a lot to remove the command I previously typed.

```
Fig Version: Version 1.0.52 (B328) [U.S.]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: Extension is not installed.
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path:
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (34389) - ttys006
Current working directory: /Users/alexvernacchia/deliveroo/js-common
Current window identifier: 33028/% (com.googlecode.iterm2)
Path: /Users/alexvernacchia/.gvm/bin:/Users/alexvernacchia/google-cloud-sdk/bin:/Users/alexvernacchia/.avn/bin:/Users/alexvernacchia/bin:/Users/alexvernacchia/deliveroo/executables:/Users/alexvernacchia/.rbenv/shims:/usr/local/opt/gettext/bin:/usr/local/opt/qt/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/alexvernacchia/.fig/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/alexvernacchia/go/bin:/Users/alexvernacchia/deliveroo/deliveroo-local/delos/exe:/Applications/Postgres.app/Contents/Versions/9.6/bin
Fig environment variables:
  - TERM_SESSION_ID=w1t1p0:424E4F65-623A-4085-AC77-D80B360B07D5
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
```

**Comment by mschrage** [comment]
Hey @vernak2539! This may have been related to the switch to our new go CLI tool to send editbuffer events from the shell. In the latest version (v1.0.53), this process run in the background and *should* no longer introduce any latency to typing 🤞.

Can you let me know if you are still running into this behavior?

**Comment by grant0417** [comment]
We have since changed how we handle editbuffer events, this should be significantly quicker in recent version of Fig.
