### ISSUE TITLE
Fig incorrect directory and file suggestions | Hyper | ZSH 

### ISSUE THREAD

**Issue by ShawnCockburn** [withfig/fig#636]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

when using fig on multiple accounts (personal & work) suggestions will suggest the other accounts previous auto complete.
I.E. on work account im in `work/project/aproject` and I type any file auto complete command eg `cd build/` it'll work but if I then switch to my personal account and type `cd` in any directory, the suggestions for `work/project/aproject` will show.

and restart of fig does not fix.

[Youtube video showing the issue](https://youtu.be/0JaX7vEvLRk)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B317) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 200
SSH Integration: false
Tmux Integration: false
Keybindings path: /Users/shawn/.fig/user/keybindings
iTerm Integration: application is not present.
Hyper Integration: installed!
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/shawn/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (61396) - ttys001
Current working directory: /Users/shawn/projects
Current window identifier: 119374/% (co.zeit.hyper)
Path: /Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/shawn/.fig/bin</pre>
</p>
</details>

**Comment by DRenaud** [comment]
Same here with the same configuration.
I have oh-my-zsh on my config.

**Comment by ShawnCockburn** [comment]
I'm closing this issue, seems to be fixed.

@DRenaud is this still borked for you?

**Comment by DRenaud** [comment]
It's fixed for me :)
