### ISSUE TITLE
launch on Start option in fig doesnt work.

### ISSUE THREAD

**Issue by myodan** [withfig/fig#637]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description

``launch on Start`` option in fig doesnt work.

of course, I know that putting it in the user startup list solves it, but I'm curious why this option doesn't work.

if you turn off this option in the settings, it will be removed from the manually added startup list. but if you re-enable the option, it will not be added to the startup list.

there is no problem in the ``fig doctor`` log.

i installed it via brew. use install command: ``brew install --cask fig``

### Environment

```bash
Fig Version: Version 1.0.52 (B317) [ABC]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/hongjongho/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/hongjongho/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (3211) - /dev/ttys001
Current working directory: /Users/hongjongho
Current window identifier: 340/% (com.googlecode.iterm2)
Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/hongjongho/.fig/bin
```

**Comment by mschrage** [comment]
Thanks for reporting this. I will investigate. @myodan @danielehrhardt

**Comment by SeparateRecords** [comment]
@danielehrhardt @myodan can either of you confirm if this is fixed on v1.0.55?

**Comment by mschrage** [comment]
There definitely is a fix for this. Would be good to get confirmation, but I'm pretty confident that everything is working now.

**Comment by myodan** [comment]
I've checked the troubleshooting. I will close this issue.
