### ISSUE TITLE
Specify options that are not prefixed with a hypen

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#638]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
> Please include a detailed description of the feature (and an image or screen recording, if applicable)

While writing the spec for `just` (https://github.com/casey/just) I hit a limitation of fig.

Say we have the following "justfile":

```just
test FILTER:
    deno test --no-check --unstable --allow-read=./data --filter {{FILTER}}

bundle:
    deno run scripts/bundle.ts

render:
    deno run scripts/render.ts
```

We can run multiple "recipes" from that file at once.

```bash
just bundle render
```

That's fine, Fig can handle that!
Where we hit a problem, however, is with `test`, because it takes an argument.

This is a valid command that I can't model with a spec:
```bash
just test API bundle render
```

In this case, one of the arguments (test) takes an argument itself (API).

I'd like to be clear first off, these _aren't_ subcommands. They're arguments provided to `just` to tell it which recipes to run and with what arguments.

## What I've tried

1. This can't be done using generateSpec + options, because Fig gets very confused by options that don't start with dashes (even with `parseDirectives.flagsArePosixNoncompliant` set to false). On top of that, because the justfile can be changed with `-f/--justfile` the suggestions would be inaccurate some of the time, and that's not super ideal

2. This can't be done with subcommands, because subcommands are exclusive. If generateSpec creates a spec with subcommands, you can use _one_, sure, but you won't get autocomplete for any additional recipes.

3. This can't be done with `args` because they can't take `args` themselves.

I hope I'm just missing something! Any help is appreciated of course 😊

**Comment by mschrage** [comment]
This is an interesting edge case. I think the solution is providing a way to specify options that aren't prefixed with a dash. cc @sullivan-sean

**Comment by SeparateRecords** [comment]
> This is an interesting edge case. I think the solution I like best is providing a way to specify options that aren't prefixed with a dash.

I agree, options that aren't dash-prefixed is probably the best _actual_ solution. This is basically something that only task runners will ever need, so it's worth tracking but IMO it should be low priority. In the case of `just`, the "recipes" essentially _are_ options.

> This _could_ be handled by writing a custom generator that is triggered on every space. This essentially is an escape hatch that lets a completion spec have complete control over what suggestions are displayed.
> 
> [...]
> 
> Obviously this is not ideal, but at least it's possible.

That's exactly what I've done to implement `just`! I'll edit this comment once the PR is up, in case anyone stumbles across this issue looking for an example of said generator.

**Comment by sullivan-sean** [comment]
This should be working on prod -- no more need for hyphens as prefixes for options, which allows workarounds for some cases like this as well as tools that actually have options without hyphens.
