### ISSUE TITLE
Running Terminal Commands from Apple Script fails

### ISSUE THREAD

**Issue by kaisky89** [withfig/fig#639]
### Description:

First of all, thank you guys for such a revolutionary tool. You are amazing 🎉

I just realized that I think starting from the installation of fig, some apple scripts that are running commands in the terminal don't work any more. A simple reproduction apple script is:

```
tell application "Terminal"
	do script "echo 'hello world'"
end tell
```

The result of that looks like so:

![image](https://user-images.githubusercontent.com/4417778/143849919-894e47a9-7b6a-4702-aefc-de6c2321218d.png)

It seems that the first character of the script is skipped (and some weird stuff is added to the input of the terminal after the command execution).

My current workaround is simply adding a whitespace as the first character of the command:

```
tell application "Terminal"
	do script " echo 'hello world'"
end tell
```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B315)|/usr/local/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B315) [German] 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/kaisky89/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: Reverting to default Node version
/Users/kaisky89/.nvm/versions/node/v10.21.0/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/Library/TeX/texbin:/usr/local/opt/python/libexec/bin:/Applications/MAMP/bin/php/php7.1.6/bin:/usr/local/sbin:/Users/kaisky89/.scripts/:/Users/kaisky89/.scripts/userscripts:/Users/kaisky89/.scripts/optimize:/Users/kaisky89/.scripts/render-description:/usr/local/opt/ruby/bin:/usr/local/opt/node@8/bin:/Users/kaisky89/.go/bin:/usr/local/opt/gettext/bin:/usr/local/bin:/Users/kaisky89/.yarn/bin:/Users/kaisky89/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/fish/3.3.1/bin/fish (35874) - /dev/ttys002
Current working directory: /Users/kaisky89
Current window identifier: 3667/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @kaisky89! Thanks for the kind words - I'm sorry that you're running into issues.

We've resolved the bug that was causing the weird ANSI characters to appear, but don't have a fix for the AppleScript issues just yet. I am glad there is a workaround that you can use in the meantime while we investigate.

**Comment by mschrage** [comment]
It seems like this issue is only effects `fish` as far as I can tell. Can you confirm that for me @kaisky89 ?

**Comment by kaisky89** [comment]
@mschrage Running on **1.0.52 B315**, I can confirm that this doesn't happen if I use `zsh`:

![image](https://user-images.githubusercontent.com/4417778/144385642-23c0f970-50ea-4a1d-9e64-4d1305fa8f6d.png)

But I see the same problem in `bash`:

![image](https://user-images.githubusercontent.com/4417778/144385764-b285d014-c284-460d-8580-62f85bd0f86e.png)

After updating to **1.0.52 B326**, the problem in `fish` seems to be resolved on my side as well:

![image](https://user-images.githubusercontent.com/4417778/144387344-7d3328aa-b42d-4590-90d7-b39c532992ca.png)

Thanks for the quick response 🎉
