### ISSUE TITLE
Show custom aliases in autocompletion

### ISSUE THREAD

**Issue by reintroducing** [withfig/fig#64]
**Is your feature request related to a problem? Please describe.**
Given an alias defined as such:

```
alias gc="git commit -m" # make a commit with a message (gc [message])
```

**Describe the solution you'd like**

* I'd love to see the comment parsed and turned into the suggestion at the bottom of the autocomplete window.
* I'd also love to see all my aliases listed out in the autocomplete window, so when I start to type `g` they are selectable.

**Describe alternatives you've considered**
The only one I can think of is defining the rules around my aliases separately in the fig autocompletion settings. This is not ideal because then I'd be managing them in two spots.

**Additional context**
N/A

**Comment by falky97** [comment]
We have been looking into adding support for suggesting aliases (and every other CLI command). Adding this extra support for descriptions is definitely something we can do too

**Comment by mschrage** [comment]
@sullivan-sean this seems like something what would be much easier to do now that we've refactored! 👀
