### ISSUE TITLE
Can not type anything randomly when a new session is created.

### ISSUE THREAD

**Issue by Leask** [withfig/fig#641]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

You cannot type anything randomly when a new session is created.

But after a while, it will restore automatically.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.0|Version 1.0.52 (B322)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B322) [Beta] [Canadian English] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/leask/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/bash (76949) - /dev/ttys023
Current working directory: /Users/leask/dotfiles
Current window identifier: 4163/% (com.apple.Terminal)</pre>
</p>
</details>

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3sccs)

**Comment by mschrage** [comment]
Hey @Leask! Thanks so reporting - we actually just pushed a fix for this. Run `fig update` to pull the latest version.

**Comment by Leask** [comment]
Cool! Thanks! I will try it out.
