### ISSUE TITLE
SecureKeyboardInput: true while false

### ISSUE THREAD

**Issue by GaspardC** [withfig/fig#642]
### Description:

keeps telling Secure Keyboard is enabled while is not.
<img width="643" alt="Capture d’écran 2021-11-30 à 20 26 27" src="https://user-images.githubusercontent.com/9252579/144114313-71041b40-5ec8-4ce9-a178-4784b38139c9.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B322)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B322) [Swiss French] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/gaspardc/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true

SecureKeyboardInput: true
SecureKeyboardProcess: Terminal - com.apple.Terminal 
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 80887/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Do you have any password managers running? Try  quitting and restarting them and that might resolve the issue.
