### ISSUE TITLE
It's still doesn't working

### ISSUE THREAD

**Issue by aaronyyan** [withfig/fig#643]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.21C5039b|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B322) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/yanlixing/.yarn/bin:/Users/yanlixing/.config/yarn/global/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/yanlixing/.fig/bin:/Users/yanlixing/.rvm/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (6985) - ttys002
Current working directory: /Users/yanlixing
Current window identifier: 1080/0471DA23-358E-4438-AE8D-A677C9283EB5% (com.googlecode.iterm2)
Path: /Users/yanlixing/.yarn/bin:/Users/yanlixing/.config/yarn/global/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/yanlixing/.fig/bin:/Users/yanlixing/.rvm/bin</pre>
</p>
</details>

**Comment by aaronyyan** [comment]
when i use fig.., it has no effect

**Comment by mschrage** [comment]
Can you type `git ` in your terminal and then take a screenshot of the Fig debugger. (Click the Fig icon in the menu bar to open it)?
