### ISSUE TITLE
Bash: Fig shows random escape codes plus prevents user input

### ISSUE THREAD

**Issue by kusor** [withfig/fig#646]
### Description:
If a user is using bash, whenever a new shell session is spawned, it is displaying random escape codes and asci characters. Then after hitting return a few times, Fig is preventing any input from going into the terminal/shell blocking all use of the shell.

The output can look something like this

```bash
Fig Jonass-MacBook-Pro:~ jonas$ bash: 11: command not found bash: rgb:1e1e/1e1e/1e1e: No such file or directory bash: 
1Rnslnsl: command not found Jonass-MacBook-Pro:~ jonas$ Jonass-MacBook-Pro:~ jonas$ Jonass-MacBook-Pro:~ jonas$ 
Jonass-MacBook-Pro:~ jonas$ Jonass-MacBook-Pro:~ jonas$ Jonass-MacBook-Pro:~ jonas$ Jonass-MacBook-Pro:~ 
jonas$ Jonass-MacBook-Pro:~ jonas$ Jonass-MacBook-Pro:~ jonas$ Jonass-MacBook-Pro:~ jonas$ Jonass-MacBook-
Pro:~ jonas$
````

Commenting out the "pre" section added to the bash profile file fixes the problem, but fig completion remains not working.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|/usr/local/Cellar/bash/5.1.8/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B324) [Spanish] 
UserShell: /usr/local/bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/pedropc/flutter/bin:/Users/pedropc/Library/Python/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/pedropc/bin:/usr/local/texlive/2019basic/bin/x86_64-darwin:/Users/pedropc/work/node-triton/bin:/Users/pedropc/Library/Python/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/pedropc/.nvim/pack/bundle/start/fzf/bin:/Users/pedropc/.cargo/bin:/Users/pedropc/javascriptlint/build/install:/Users/pedropc/jsstyle:/Users/pedropc/work/node-manta/bin:/usr/local/bin:/usr/local/git/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/opt/pivy/bin:/opt/pkg/sbin:/opt/pkg/bin:/Library/Apple/usr/bin:/Users/pedropc/Library/Android/sdk/tools:/Users/pedropc/Library/Android/sdk/platform-tools:/Users/pedropc/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/bash/5.1.8/bin/bash (10198) - ttys006
Current working directory: /Users/pedropc
Current window identifier: 1606/429DA610-5406-42B4-B25C-960A083654AB% (com.googlecode.iterm2)
Path: /Users/pedropc/flutter/bin:/Users/pedropc/Library/Python/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/pedropc/bin:/usr/local/texlive/2019basic/bin/x86_64-darwin:/Users/pedropc/work/node-triton/bin:/Users/pedropc/Library/Python/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/pedropc/.nvim/pack/bundle/start/fzf/bin:/Users/pedropc/.cargo/bin:/Users/pedropc/javascriptlint/build/install:/Users/pedropc/jsstyle:/Users/pedropc/work/node-manta/bin:/usr/local/bin:/usr/local/git/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/opt/pivy/bin:/opt/pkg/sbin:/opt/pkg/bin:/Library/Apple/usr/bin:/Users/pedropc/.fig/bin:/Users/pedropc/Library/Android/sdk/tools:/Users/pedropc/Library/Android/sdk/platform-tools</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @kusor! We just pushed a fix for this! Run `fig update` to download the latest version.

**Comment by kusor** [comment]
Like a charm, thanks!!!
