### ISSUE TITLE
Fig shows suggestions, but won't complete them when I press return

### ISSUE THREAD

**Issue by brandongit2** [withfig/fig#647]
### Description:
Fig suggestions pop up and are interactive, but do nothing when I press return. Issue is present on iTerm2, but not the built-in terminal.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B317) [Canadian English] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/brandontsang/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/brandontsang/.rvm/gems/ruby-2.7.2/bin:/Users/brandontsang/.rvm/gems/ruby-2.7.2@global/bin:/Users/brandontsang/.rvm/rubies/ruby-2.7.2/bin:/Users/brandontsang/.nvm/versions/node/v17.1.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/brandontsang/.fig/bin:/Users/brandontsang/.rvm/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (81026) - ttys005
Current working directory: /Users/brandontsang/projects/mintbean-hiring
Current window identifier: 79/06F4970C-DCDB-443D-A74A-2DB7670AE3AD% (com.googlecode.iterm2)
Path: /Users/brandontsang/.rvm/gems/ruby-2.7.2/bin:/Users/brandontsang/.rvm/gems/ruby-2.7.2@global/bin:/Users/brandontsang/.rvm/rubies/ruby-2.7.2/bin:/Users/brandontsang/.nvm/versions/node/v17.1.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/brandontsang/.fig/bin:/Users/brandontsang/.rvm/bin</pre>
</p>
</details>

**Comment by mschrage** [comment]
This issue should be fixed as of the latest build. Run `fig update` to download the most recent version.

I'm going to close this issue, but let me know if you're still running into the same behavior after the update and I will reopen it.
