### ISSUE TITLE
Autocomplete works in VS Code but not iTerm

### ISSUE THREAD

**Issue by conor-odro** [withfig/fig#652]
### Description:
Fig's autocomplete seems to be unable to insert text in my iTerm terminal when pressing `enter`, but the same installation works fine in the VS Code terminal. The two videos below showcase the issue.

https://user-images.githubusercontent.com/70513663/144400854-40bf398e-37ba-41de-91f5-0284eb01d3b5.mov

https://user-images.githubusercontent.com/70513663/144400876-35eb766f-3d59-4a61-ae51-dd63c4017683.mov

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B326) [British (PC 105 alt)] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/mongodb-community@4.0/bin:/Users/conor/.nvm/versions/node/v14.16.1/bin:/usr/local/opt/helm@2/bin:~/Android/cmdline-tools/latest/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/conor/.fig/bin:/usr/local/opt/fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: <Unknown Process> (???) - 
Current working directory: /Users/conor
Current window identifier: 46408/3743C704-AE39-494A-89C4-5347470B770B% (com.googlecode.iterm2)
Path: /usr/local/opt/mongodb-community@4.0/bin:/Users/conor/.nvm/versions/node/v14.16.1/bin:/usr/local/opt/helm@2/bin:~/Android/cmdline-tools/latest/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/conor/.fig/bin:/usr/local/opt/fzf/bin</pre>
</p>
</details>

**Comment by mschrage** [comment]
Thanks for reporting this @conor-odro! That's very strange.

Can you run `env | grep FIG` in your iTerm terminal session and share the output here?

**Comment by conor-odro** [comment]
Hey @mschrage, thanks for looking into this 😃 

Here's the output below
![image](https://user-images.githubusercontent.com/70513663/144575757-0912190e-35fb-4ae4-90c3-0b1562ab1796.png)

Very bizarrely it seems to be working this morning! 🙈  I did restart my laptop yesterday so it's possible that that fixed it.

**Comment by mschrage** [comment]
We've been pushing a bunch of bug fixes for issues that came to light after we launched publicly. It's possible that when you restarted your computer, Fig was updated to the latest version. 

I'll close this issue but let me know if it comes back!
