### ISSUE TITLE
Please make sure this file is valid JSON.

### ISSUE THREAD

**Issue by pknobloch** [withfig/fig#653]
### Description:

I ran the command `fig app set-path` and received a popup error that said:

> An error occured while reading the Fig settings file stored at ~/.fig/settings.json
> Please make sure this file is valid JSON.

Here is the output of the terminal:
![image](https://user-images.githubusercontent.com/1839309/144413705-63f5acb2-951e-418b-9b0b-cf076eb36fb6.png)

I opened `~/.fig/settings.json` and found the contents to be:
```
{
  "autocomplete.addStatusToTerminalTitle": false,
  "autocomplete.disable": false,
  "autocomplete.theme": "dracula",
  "pty.path": "/Users/pknobloch/.nvm/versions/node/v16.13.0/bin:/Users/pknobloch/.dotnet/tools:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/pknobloch/.fig/bin"
}
```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.52 (B326)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B326) [Dutch] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/pknobloch/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by grant0417** [comment]
We have change the whole underlying implementation here when moving to Rust, should be less likely to happen.
