### ISSUE TITLE
Can't read iTerm plist file to determine version.

### ISSUE THREAD

**Issue by randallwstanford** [withfig/fig#655]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:

- Fig can not read iTerm's plist file to determine iTerm's version.
- Fig -> Integrations -> iTerm -> [  "Could not read... ", "Attempt to install" ] 
![image](https://user-images.githubusercontent.com/83252804/144503304-ac6a7443-52a0-4b01-a11e-f166db6e2a7f.png)

### Environment

```bash
Unknown
```

**Comment by harisarang** [comment]
@brendanfalk or @randallwstanford Is there any update on this I am facing this issue now
