### ISSUE TITLE
Stress testing quitting / opening Fig produces weird results

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#656]
Running the following produces weird CLI errors and potentially weird results
```
for i in $(seq 1 50); do fig quit; fig launch; done
```
**Expected**
Fig should able to handle weird crazy stress testing like this

**Actual**
Weird error messages and connection errors
![CleanShot 2021-12-02 at 13 46 53](https://user-images.githubusercontent.com/4949076/144511089-b3bc28d4-029c-49ad-aeab-837832a22604.png)

The most worrisome is this one:
![CleanShot 2021-12-02 at 14 07 28](https://user-images.githubusercontent.com/4949076/144511112-f067fa29-1bf0-4f7b-ab8e-eb9821ec02d2.png)

**Comment by grant0417** [comment]
Fixed by B327
