### ISSUE TITLE
Path suggestions will stop working if folder name contains non-english characters

### ISSUE THREAD

**Issue by edisonlee55** [withfig/fig#658]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Path suggestions will stop working if the folder name contains non-english characters.
Maybe related to #451 and #635

Screenshot:
<img width="450" alt="Screenshot 2021-12-03 AM 9 25 40" src="https://user-images.githubusercontent.com/5277788/144528920-031a7575-25d0-4670-81be-59799646fad3.png">

Screen Recording:
https://user-images.githubusercontent.com/5277788/144528758-bb98fad4-c82a-4266-974e-d28c54081945.mp4

### Details:

|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B326)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B326) [ABC]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path:
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (73074) - ttys008
Current working directory: /Users/edisonlee55
Current window identifier: 50672/FB6A027C-6053-4B77-A33C-2BF18270D809% (com.googlecode.iterm2)
Path: /usr/local/opt/gettext/bin:/usr/local/opt/sphinx-doc/bin:/usr/local/sbin:/Users/edisonlee55/perl5/bin:/usr/local/opt/qt/bin:/usr/local/opt/curl/bin:/usr/local/opt/openssl/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/sqlite/bin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/python/libexec/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/openssl/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/edisonlee55/.fig/bin:/Users/edisonlee55/bin</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @edisonlee55! Thanks so much for reporting this. 

Can you run `echo $LANG` in your terminal and share the output here? I've seen this issue before and it *was* fixed at one point, but possible you've stumbled across a regression.

**Comment by edisonlee55** [comment]
Sure, the character that triggers this error is `猫` (Cat in Japanese).

<img width="542" alt="Screenshot 2021-12-03 AM 9 40 31" src="https://user-images.githubusercontent.com/5277788/144530371-7b76cd57-0e7e-4169-ae64-f9869ab3f443.png">

**Comment by mschrage** [comment]
Just found the fix @edisonlee55! Turns out we were handling unicode characters incorrectly when writing them to the pseudoterminal that runs shell commands.

I'll push this fix ASAP. :)
