### ISSUE TITLE
Typing lag in VS Code file editor when Fig is installed

### ISSUE THREAD

**Issue by Chriscbr** [withfig/fig#66]
### Description:
Not sure when this started happening, but typing in the main file editor part of VS Code lags significantly when Fig is running. This is most noticeable if I hold and press down a single key, e.g. "a".

In the clip above, I'm holding down the "a" key and then hold backspace. Then I quit Fig, and I again hold down the "a" key and then hold backspace (this time there is no lag).

https://user-images.githubusercontent.com/5008987/116776649-8a96e480-aa37-11eb-9e9c-0375a9190a67.mov

This happens regardless of:

* whether I have the VS Code integrated terminal opened or not
* whether the fig VS Code extension is installed or not

Behavior within the integrated terminal is completely normal (no lag, and Fig autocomplete works as expected).

For now I've had to stop using Fig until this is fixed

### Details:
|macOS|Fig|Shell|
|----|----|----|
|11.3|Version 1.0.40 (B188)|/usr/local/bin/zsh|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.40 (B188)
UserShell: /usr/local/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/rybickic/.fig/bin/fig
Accessibility: true
Number of specs: 80
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/rybickic/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/zsh/5.8_1/bin/zsh (20798) - ttys001
Current working directory: /Users/rybickic
Current window identifier: 5771/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by mattschrage** [comment]
Thanks so much for reporting this @Chriscbr! This should be fixed in the next release (v1.0.41).

**Comment by Chriscbr** [comment]
Hmm - I think I narrowed down the problem a little further. I updated to v1.0.41 today and still was encountering the typing lag, but then noticed it goes away if I have the VS Code terminal open. So I'm able to reproduce (and turn on/off the lag) by opening/closing the VS Code terminal.

**Comment by Chriscbr** [comment]
Here is an extended clip of the bug (with Fig v1.0.41 (B206)):

https://user-images.githubusercontent.com/5008987/119239499-6fd7fd00-bb17-11eb-84f5-b90db1b7b392.mov

**Comment by falky97** [comment]
Okay. This is really helpful. 

So a **summary**: VSCode's main editor lags when Fig is open and VSCode's integrated terminal is closed.

This is fixable and hopefully we will be able to get to it in the next version. Will keep you posted.

**Comment by mattschrage** [comment]
This is fixed as of version 1.0.44!

**Comment by Chriscbr** [comment]
@mattschrage thank you! 👍
