### ISSUE TITLE
Appearance settings not working/persistent

### ISSUE THREAD

**Issue by aparajita** [withfig/fig#660]
### Description:

Fig never remembers my font or window size settings. Try the following:

1. `fig settings`
2. Change the font and font size, close settings.
3. Trigger autocomplete. The font and size have changed.
4. Restart Fig from the menu bar menu.
5. `fig settings`. The previous settings are there.
6. Trigger autocomplete. The font settings are the defaults.
7. `fig settings`
8. Set the window height and width to 400. Close settings.
9. Trigger autocomplete. The window size is the default.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.1.20G224|1.0.52|/usr/local/Cellar/zsh/5.8_1/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B325) [Dvorak] 
UserShell: /usr/local/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /var/folders/1z/fl90zpnx2v36z32z255pf8z80000gn/T/fnm_multishells/42981_1638464747058/bin:/usr/local/opt/openssl/bin:/Users/aparajita/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Little Snitch.app/Contents/Components:/opt/X11/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/aparajita/.fig/bin:/Users/aparajita/go/bin:/usr/local/opt/fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/zsh/5.8_1/bin/zsh (42863) - ttys006
Current working directory: /Users/aparajita/jot/jot-vue
Current window identifier: 6371/% (com.googlecode.iterm2)
Path: /var/folders/1z/fl90zpnx2v36z32z255pf8z80000gn/T/fnm_multishells/42981_1638464747058/bin:/usr/local/opt/openssl/bin:/Users/aparajita/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Little Snitch.app/Contents/Components:/opt/X11/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/aparajita/.fig/bin:/Users/aparajita/go/bin:/usr/local/opt/fzf/bin</pre>
</p>
</details>

**Comment by Stolzio** [comment]
I came to report a very similar issue and noticed yours. I change the font for the autocompletions to Roboto Mono and after a while I notice it has changed back to Monaco, even though Roboto Mono still stays written in the options. During this time I haven't even quit Fig, it's on all the time and I use it almost all of the time. It's not like I quit the app and then it resets - it does that mid-working

**Comment by aparajita** [comment]
One more data point: after restarting Fig, when I open settings, if I **click** in the window height/width field and try to backspace, the default setting briefly appears and then the custom setting reappears, disabling editing. Only if I **tab** into the field can it be edited.

**Comment by mschrage** [comment]
@aparajita @Stolzio I am investigating this now.

**Comment by phendan** [comment]
The appearance settings also don't seem to persist for me (I've set font size, font family, and a theme). If I open settings and choose another theme, then revert it, the settings take effect for a while again.

Overall it's a great tool though, keep up the good work!

**Comment by fedeci** [comment]
Fixed it yesterday, it will go live in the next beta!

**Comment by SeparateRecords** [comment]
Was the window height also fixed? It's not working for me (1.0.54)

**Comment by brendanfalk** [comment]
This should be fixed!
