### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ff-frida** [withfig/fig#662]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

![image](https://user-images.githubusercontent.com/18607031/144560550-1169de2c-dc6e-4cf5-896c-2297eb836644.png)

### Environment

```bash
mac os 10.15.6
x86
```

**Comment by mschrage** [comment]
Hey @ff-frida! I know what's going on here! It seems like your `/etc/hosts` file does not specify the address for localhost.

The fix can be found [here](https://github.com/withfig/fig/issues/619).
