### ISSUE TITLE
Keys combination [esc] + [o] in mc https://midnight-commander.org/ froze terminal

### ISSUE THREAD

**Issue by shalom-aviv** [withfig/fig#663]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.52 (B317)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B317) [U.S.]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path:
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (69766) - /dev/ttys003</pre>
</p>
</details>

Steps:
- launch terminal
- install  [mc](https://midnight-commander.org) `brew install mc`
- **run>** mc
- Try to use keys combination [esc] + [o]

This bug appeared after installing the **fig**

**Comment by mschrage** [comment]
Hey @shalom-aviv! Try upgrading to the latest version of Fig by running `fig update` (you can also redownload [here](https://fig.io/welcome).

We just fixed the bug that caused the terminal to hang when executing certain OSC sequences, similar to an [issue](https://github.com/charmbracelet/lipgloss/issues/5) Alacritty ran into, and this might be related.

**Comment by grant0417** [comment]
Seems like an old figterm bug, this should be fixed!
