### ISSUE TITLE
CLI tools like `nano` cause fig's pseuodterminal to crash

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#664]
**Summary**
Execute `nano`. Then exit `nano`. Then type `cd[space]`

This causes Fig's pseudoterminal to crash.

![CleanShot 2021-12-03 at 11 00 06](https://user-images.githubusercontent.com/4949076/144658129-5ea66c20-2366-48b6-9c40-3d2d816b6485.png)

We have fixed this issue for `nano`, however, this may happen elsewhere.

The issue is specifically due to pipelining. Running the following will cause an entire terminal crash
```bash
nano | fig_callback 220
```

This does not cause a crash when piping just about any other CLI tool like `bash`, `git`. 

Question is: what is so special about `nano` and why does it break our pty!!

**Comment by grant0417** [comment]
Just bumping this issue, it seems like nano breaks Figterm in a weird way still, will investigate

**Comment by grant0417** [comment]
`nano | ...` seems to break all terminals actually, i don't think this breaks the internal psudoterminal any more though, closing because stale
