### ISSUE TITLE
iterm does not start any more

### ISSUE THREAD

**Issue by flypenguin** [withfig/fig#665]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
i installed fig, ran "fig doctor", re-started iterm, and now i see a flicker of a black iterm window and it immediately terminates itself.

terminal has no issues.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B328)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B328) [German] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/tm/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/usr/local/bin:/opt/homebrew/Cellar/gnu-which/2.21/libexec/gnubin:/opt/homebrew/Cellar/findutils/4.8.0_1/libexec/gnubin:/opt/homebrew/Cellar/gnu-time/1.9/libexec/gnubin:/opt/homebrew/Cellar/make/4.3/libexec/gnubin:/opt/homebrew/Cellar/gnu-sed/4.8/libexec/gnubin:/opt/homebrew/Cellar/gnu-tar/1.34/libexec/gnubin:/opt/homebrew/Cellar/coreutils/8.32/libexec/gnubin:/opt/homebrew/Cellar/libtool/2.4.6_4/libexec/gnubin:/Users/tm/bin:/Users/tm/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/tm/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (17109) - ttys002
Current working directory: /Users/tm
Current window identifier: 62235/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by flypenguin** [comment]
after updating iterm iterm2 3.4.3 -> 3.4.14 and restarting everything (again) it started working again. so close it if you want (i'm happy now), or have a look at what that might be with iterm v3.4.3 :)

**Comment by mschrage** [comment]
Hey @flypenguin! I'm glad that everything is working for you again. That is a very strange issue. I'll see if I can reproduce. 

We've just pushed a bunch of fixes for bugs we've found after we launched publicly so it's possible that's why the crash went away.
