### ISSUE TITLE
Fig autocompletes when navigating through fish history

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#668]
**Summary**

When navigating history in fish, the autocomplete window appears. When autocomplete appears, it eats the up arrow keystroke meaning you can't smoothly navigate through history.

https://user-images.githubusercontent.com/4949076/144696476-cb49ef95-ad21-470e-8a51-e05b5eb105d6.mp4

Expected:
It should not appear until the user has started typing something.

**Comment by mschrage** [comment]
This issue has been resolved!
