### ISSUE TITLE
Could not link with terminal

### ISSUE THREAD

**Issue by liutao62** [withfig/fig#670]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Fig is not running
error message:
Could not link with terminal 
Error listening on port 50697: Error code: -9989(0x-2705), Unknown error.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>
It looks like Fig is not running.
Try running: fig restart

</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @liutao62! Thanks for letting us know. Luckily, there is an easy fix: https://github.com/withfig/fig/issues/619#issuecomment-983942619

**Comment by liutao62** [comment]
Hey @mschrage @brendanfalk,  I received an email from @brendanfalk. Thank you for helping me solve this problem, Fig is working normally.
