### ISSUE TITLE
about fig short duration failure

### ISSUE THREAD

**Issue by GnaixEuy** [withfig/fig#671]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B328) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/libpq/bin:/usr/local/Caskroom/flutter/2.5.0/flutter/bin/cache/dart-sdk/bin:/usr/local/opt/curl/bin:/usr/local/opt/m4/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/gnaixeuy/.fig/bin:/Users/gnaixeuy/Library/apache-tomcat-8.5.69/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (51958) - ttys002
Current working directory: /Users/gnaixeuy
Current window identifier: 31324/% (com.googlecode.iterm2)
Path: /usr/local/opt/libpq/bin:/usr/local/Caskroom/flutter/2.5.0/flutter/bin/cache/dart-sdk/bin:/usr/local/opt/curl/bin:/usr/local/opt/m4/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/gnaixeuy/.fig/bin:/Users/gnaixeuy/Library/apache-tomcat-8.5.69/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:95ECA9BA-EAA4-4DE4-B604-3F8C8C568D00
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @GnaixEuy! I’m not totally sure I understand the issue you’re running into. Can you elaborate (or share a screen recording) of what is going wrong?

**Comment by GnaixEuy** [comment]
After I start fig, my terminal sometimes does not display a prompt. I wait for his response, but it seems to be invalid. Every time I need to restart fig and itrem2, can you tell me the possible reasons？ :( This is a great product, but it sometimes falls off the chain

**Comment by mschrage** [comment]
Hmm this sounds very frustrating @GnaixEuy. I’m not exactly sure what’s happen.

Can you take a screenshot the next time this happens?

Also are you able to type commands or is the terminal session completely unresponsive?

**Comment by GnaixEuy** [comment]
Emmm, I'm sorry he always showed no signs. It seems that when I wake up mac it may appear that I can't record a video to you and I think he's unpredictable. But it's strange that my terminal works, and my combination is omz and iterm2, fig seems to completely lose its role :(

**Comment by mschrage** [comment]
I'm still somewhat confused about the issue you are running into.

Does Fig not appear at all? Or does your terminal not let you run commands?

**Comment by GnaixEuy** [comment]
So, I recreated the problem today, when I woke up my Mac.
<img width="884" alt="err" src="https://user-images.githubusercontent.com/78402118/145393733-eeba7653-cb6b-4d78-afd0-cc485101b9fc.png">
<img width="854" alt="errro" src="https://user-images.githubusercontent.com/78402118/145393757-65139bc3-7dd3-4f21-912e-ceebb385dbeb.png">
When I used the terminal, there wasn't any graphical interface about fig, but he seemed to be working.

**Comment by mschrage** [comment]
@GnaixEuy this is **very** helpful! Thanks for sharing.

This rules out a bunch of issues. Fig is accurately getting the text you've typed in the terminal. The macOS app is running and thinks that everything is working correctly.

Can you run: 
- `fig debug debug-mode on`? You should see a red window appear. 
- Right click the window and then click "Inspect elements"
- Type `git commit` in your terminal and share the output from the Web Inspector Console.

**Comment by SeparateRecords** [comment]
Should be fixed now!
