### ISSUE TITLE
PATH and PseudoTerminal PATH do not match

### ISSUE THREAD

**Issue by admapop** [withfig/fig#672]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.21A344|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B328) [Italian] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/admapop/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (63110) - ttys004
Current working directory: /Users/admapop
Current window identifier: 65289/A557CF3B-1EAD-4FD2-AC91-D743C8EA333E% (com.googlecode.iterm2)
Path: /opt/homebrew/opt/ruby/bin:/usr/bin/ruby:/opt/homebrew/opt/openssl@1.1/bin:/Users/admapop/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/Users/admapop/.nvm/versions/node/v16.13.0/bin:/opt/homebrew/Cellar/zplug/2.4.2/bin:/Users/admapop/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/admapop/.fig/bin:/Users/admapop/Library/Android/sdk/emulator:/Users/admapop/Library/Android/sdk/tools:/Users/admapop/Library/Android/sdk/tools/bin:/Users/admapop/Library/Android/sdk/platform-tools
Fig environment variables:
  - TERM_SESSION_ID=w1t0p0:A557CF3B-1EAD-4FD2-AC91-D743C8EA333E
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @admapop! Is this causing any specific issues? 

Try running `fig app set-path` and let me know if that helps :)

**Comment by admapop** [comment]
Hi @mschrage !

It seems I managed to fix the issue by running with higher privileges!
Can be closed thanks!
