### ISSUE TITLE
Error listening on port 50697: Error code: -9992(0x-2708), Can't assign requested address.

### ISSUE THREAD

**Issue by QuentinHsu** [withfig/fig#673]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

In recent versions of the software, every time you launch the fig app, you are likely to be prompted with the following screenshot message

<img width="260" alt="Snipaste_2021-11-27_17-21-06" src="https://user-images.githubusercontent.com/21162238/144773680-b9d45ac5-a999-4eca-ae41-aa6e7cd5185e.png">

Restarting the software does not work.

I checked the corresponding port and it was not occupied.

![image](https://user-images.githubusercontent.com/21162238/144773730-c6f1fa8f-f547-4ccb-97f9-2edf2d3f3d93.png)

I don't know what to do about this.

### Environment

```bash
MacBook Pro (13-inch, M1, 2020)
macOS Monterey 12.0.1
fig: 1.0.52,328
```

**Comment by chenyuhu** [comment]
Has the problem been solved?

**Comment by QuentinHsu** [comment]
> Has the problem been solved?

No.

**Comment by mschrage** [comment]
Would you mind sharing the contents of your `/etc/hosts` file @QuentinHsu?

**Comment by QuentinHsu** [comment]
> Would you mind sharing the contents of your `/etc/hosts` file @QuentinHsu?

![image](https://user-images.githubusercontent.com/21162238/144947677-015e6ef9-d56f-40ca-8d38-9e1137d8d5cb.png)
The current contents of /etc/hosts are empty. Although I know there will be some default content. But at the moment it doesn't seem to affect the network communication of other programs on my computer.

But just now after my computer started up, fig is working again ...... very confusing ...... I didn't bother to change the hosts content, it's still empty ......

**Comment by mschrage** [comment]
Any program which uses `localhost` will be effected by this. I would recommend restoring the default:
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```
