### ISSUE TITLE
no auto login

### ISSUE THREAD

**Issue by yysofiyan** [withfig/fig#674]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7.19H1519|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B328) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/yysofiyan/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (2504) - ttys006
Current working directory: /Applications/MAMP/htdocs/webservice-ionic
Current window identifier: 1041/% (com.microsoft.VSCode)
Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/yysofiyan/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=7C59ACC5-55BA-4338-BC94-2187323DFB00
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
</pre>
</p>
</details>

**Comment by fedeci** [comment]
Please explain

**Comment by mschrage** [comment]
Hey @yysofiyan! We don't have any information to understand what's going on. I'm going to close this issue, but will reopen if if you can share any more details or screenshots.

**Comment by yysofiyan** [comment]
@mschrage Thanks solved 👋
