### ISSUE TITLE
Feature request: Fig on non-mac linux OS's

### ISSUE THREAD

**Issue by caleb15** [withfig/fig#675]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
I have a Ubuntu OS through WSL (using [windows terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab)) and I'm sure there are many other developers with ubuntu or fedora or what have you.

Even though I have windows I would actually prefer Ubuntu support to be added first because I mainly use WSL.

Note that implementing fig on Ubuntu would basically add Windows support for free, because Windows users could use WSL to operate in Ubuntu.

**Comment by caleb15** [comment]
related issue: https://github.com/withfig/autocomplete/issues/254

**Comment by mschrage** [comment]
Bring Fig cross platform is definitely on the roadmap. I'm closing this in favor of #34.
