### ISSUE TITLE
Not able to insert suggestions in iTerm.

### ISSUE THREAD

**Issue by Lunchb0ne** [withfig/fig#677]
### Description:
Hi, I've been struggling with a bug in fig lately, sometimes it just stops being able to accept suggestions in iTerm2.  
The popup and everything still works, but the suggestion acceptance just doesn't work at all. It works when I use something like vscode or terminal.app but not on iterm2.

https://user-images.githubusercontent.com/22198661/144924906-cd0963e7-cbe4-4d8c-bacb-ad5aa62a8049.mov

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|/opt/homebrew/Cellar/zsh/5.8_1/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B328) [ABC] 
UserShell: /opt/homebrew/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/lunchb0ne/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/lunchb0ne/.volta/bin:/opt/homebrew/Caskroom/mambaforge/base/bin:/opt/homebrew/Caskroom/mambaforge/base/condabin:/Users/lunchb0ne/bin:/Users/lunchb0ne/.cache/zsh4humans/v5/zsh4humans/zb:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/Library/Apple/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/lunchb0ne/.cache/zsh4humans/v5/fzf/bin:/Users/lunchb0ne/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /opt/homebrew/Cellar/zsh/5.8_1/bin/zsh (15642) - ttys004
Current working directory: /Users/lunchb0ne
Current window identifier: 2608/% (com.googlecode.iterm2)
Path: /Users/lunchb0ne/.volta/bin:/opt/homebrew/Caskroom/mambaforge/base/bin:/opt/homebrew/Caskroom/mambaforge/base/condabin:/Users/lunchb0ne/bin:/Users/lunchb0ne/.cache/zsh4humans/v5/zsh4humans/zb:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/Library/Apple/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/lunchb0ne/.cache/zsh4humans/v5/fzf/bin:/Users/lunchb0ne/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:228DC751-3893-4AF7-9240-14D9BAFB6D43
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Lunchb0ne, thanks for reporting this. This is very strange (from the `diagnostic` output everything looks fine, did you run it in the effected Terminal session?)

What version of iTerm are you on? Are you free to jump on a debugging call? https://calendly.com/mschrage/30min

**Comment by Lunchb0ne** [comment]
Yeah, sorry for the late reply, I wasn't able to recreate the issue for sometime, as it randomly happens. Just got the bug again. Here's the rest of the information you requested.

When I run diagnostic, this is the part that gives an error.

```
❌ PATH and PseudoTerminal PATH do not match
```

I'm using [romkatv/zsh4humans](https://github.com/romkatv/zsh4humans). And [here's](https://gist.github.com/Lunchb0ne/0ca6399af3baf66f431571f88336f222) my `~/.zshrc` file

iTerm2 Version: `3.5.0beta3`

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|/opt/homebrew/Cellar/zsh/5.8_1/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B328) [ABC] 
UserShell: /opt/homebrew/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/lunchb0ne/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/Caskroom/mambaforge/base/bin:/opt/homebrew/Caskroom/mambaforge/base/condabin:/Users/lunchb0ne/.volta/bin:/Users/lunchb0ne/bin:/Users/lunchb0ne/.cache/zsh4humans/v5/zsh4humans/zb:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/Library/Apple/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/lunchb0ne/.cache/zsh4humans/v5/fzf/bin:/Users/lunchb0ne/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /opt/homebrew/Cellar/zsh/5.8_1/bin/zsh (56374) - ttys006
Current working directory: /Users/lunchb0ne
Current window identifier: 15937/228DC751-3893-4AF7-9240-14D9BAFB6D43% (com.googlecode.iterm2)
Path: /opt/homebrew/Caskroom/mambaforge/base/bin:/opt/homebrew/Caskroom/mambaforge/base/condabin:/Users/lunchb0ne/.volta/bin:/Users/lunchb0ne/bin:/Users/lunchb0ne/.cache/zsh4humans/v5/zsh4humans/zb:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/Library/Apple/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/lunchb0ne/.cache/zsh4humans/v5/fzf/bin:/Users/lunchb0ne/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:228DC751-3893-4AF7-9240-14D9BAFB6D43
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Lunchb0ne! Is this still happening as of v1.0.53? We've rewritten the logic that links the current window to the active terminal session and this might resolve the issue.

Otherwise, next time this happens, ping me on [Discord](https://fig.io/community) and we can debug together in real-time.

**Comment by mschrage** [comment]
This will be fixed as of v1.0.54. 

There is temporary workaround: Go to System Preferences > General and make sure the "Close windows when quitting an app" checkbox is checked.

<img width="780" alt="Screen Shot 2022-01-12 at 4 14 48 PM" src="https://user-images.githubusercontent.com/3155109/149243227-f41f1821-57f4-4d41-8901-f04f203bba6e.png">
