### ISSUE TITLE
Change login text

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#678]
Currently Fig's login asks users to login to connect with teammates. This is true, however, teammate connection is not available yet.

We primarily ask for email so we can ask our users for feedback. We should make this more explicit in the onboarding.

**Comment by renjujose-testsigma** [comment]
Appreciate the quick action on feedback @brendanfalk 👍

**Comment by SeparateRecords** [comment]
Also, given some upcoming features, signing in with a personal email is likely a better choice?

**Comment by grant0417** [comment]
We now have teams!
