### ISSUE TITLE
Cannot get Fig working in iTerm2 after re-installation

### ISSUE THREAD

**Issue by Gray-Wind** [withfig/fig#68]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Cannot get suggestions from fig. Freshly installed Fig.app. Previously I've uninstalled Fig, now I'm trying to restore it.
<img width="266" alt="image" src="https://user-images.githubusercontent.com/4902794/116792305-6e8f5380-aac8-11eb-85d5-ec4a2c0dab33.png">

I tried to remove `~/.fig` folder completely and run install script again, it didn't help.

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.16.0|Version 1.0.40 (B188)|/bin/sh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.40 (B188)
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/user/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: true
Tmux Integration: false
Keybindings path: /Users/user/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: true
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: false
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 32130/36C418501-3DB7-443F-9025-6E7C29B43DE9% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by wand3r** [comment]
It looks like I have the same issue after fresh install today. Also clicking on Re-run seems to do nothing.

<img width="432" alt="image" src="https://user-images.githubusercontent.com/18244232/116795403-f4b19700-aad4-11eb-88f5-c066940a38a5.png">

**Comment by mattschrage** [comment]
Hey @Gray-Wind and @wand3r! Thanks so much for reporting. We prematurely pushed an update to the installation script that was meant for the next release. 

Re-running the install script should fix the issue. If not, fully uninstalling the app and then reinstalling it will. Ping me in the [Fig community](https://withfig.com/community) if you need any help with this.

**Comment by Gray-Wind** [comment]
I've run script `~/.fig/tools/install_and_upgrade.sh` manually and Fig begun work.

**Comment by falky97** [comment]
Yes, that is the fix! Sorry, was a temporary bug we since fixed
