### ISSUE TITLE
Autocomplete app displaying window in wrong monitor

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#680]
**Summary**
The autocomplete window is showing up in the wrong monitor

https://user-images.githubusercontent.com/4949076/145119389-404b285f-0a1b-4786-9ede-bceecb55e013.MOV

**Diagnostics**
`UNKNOWN`

**Comment by Exaper** [comment]
I'm seeing similar thing when autocomplete empty pop up shows up in IntelliJ/Android Studio

**Comment by brendanfalk** [comment]
Some extra info related to this issue
![image](https://user-images.githubusercontent.com/4949076/149414548-1af18592-f1d6-418f-9b37-8381d8b31d73.png)

<img width="529" alt="CleanShot 2022-01-13 at 13 50 47@2x" src="https://user-images.githubusercontent.com/4949076/149414598-eb43fd0a-7009-407d-b153-4b90d97080b1.png">

**Comment by grant0417** [comment]
This should be fixed a long time ago
