### ISSUE TITLE
Nothing happens when you click the [continue] button.

### ISSUE THREAD

**Issue by CodeChangingMe** [withfig/fig#681]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Nothing happens when you click the button.

![image](https://user-images.githubusercontent.com/15611059/145203976-258460f6-1188-4e74-9646-08e399336d2c.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B328)|/usr/local/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B328) [搜狗拼音] 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/wulei/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: true
Keybindings path: <none>
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @CodeChangingMe, this might happen if you are using a VPN or otherwise can’t connect to the internet.

Is that possible?

**Comment by CodeChangingMe** [comment]
> Hey @CodeChangingMe, this might happen if you are using a VPN or otherwise can’t connect to the internet.
> 
> Is that possible?

Yes, I'm in China. It may be a network problem. But the FIG had better have some hint or I don't know what to do with it.

**Comment by mschrage** [comment]
This is fixed as of v1.0.53.
