### ISSUE TITLE
Suggestion not accepted on confirming with ENTER

### ISSUE THREAD

**Issue by odrotbohm** [withfig/fig#684]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Issue Details

I use fig and get completions suggested like that:

![Bildschirmfoto 2021-12-09 um 15 34 46](https://user-images.githubusercontent.com/128577/145416240-8006d11c-e415-4d5f-9ab2-b4a83b0e3ca8.png)

If I select a suggestion using ENTER, it is not applied. I.e. the current command line stays:

![Bildschirmfoto 2021-12-09 um 15 34 56](https://user-images.githubusercontent.com/128577/145416357-05642874-52f8-465b-99e4-4df1d33506e7.png)

It doesn't seem to be related to the tool I trigger suggestions for. A simple `cd` shows folder suggestions but they are not getting applied either.

### Environment

```bash
Fig Version: Version 1.0.52 (B328) [German] 
UserShell: /usr/local/bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 202
SSH Integration: false
Tmux Integration: false
Keybindings path: /Users/odrotbohm/.fig/user/keybindings
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/odrotbohm/.rvm/gems/ruby-2.6.6/bin:/Users/odrotbohm/.rvm/gems/ruby-2.6.6@global/bin:/Users/odrotbohm/.rvm/rubies/ruby-2.6.6/bin:/opt/local/bin:/opt/local/sbin:/Users/odrotbohm/.jbang/bin:/Users/odrotbohm/.rbenv/shims:/usr/local/lib/ruby/gems/3.0.0/bin:/Users/odrotbohm/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Little
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/bash/5.1.12/bin/bash (24723) - ttys008
Current working directory: /Users/odrotbohm/Documents/workspace/spring-restbucks/server
Current window identifier: 26694/% (com.apple.Terminal)
Path: /Users/odrotbohm/.rvm/gems/ruby-2.6.6/bin:/Users/odrotbohm/.rvm/gems/ruby-2.6.6@global/bin:/Users/odrotbohm/.rvm/rubies/ruby-2.6.6/bin:/opt/local/bin:/opt/local/sbin:/Users/odrotbohm/.jbang/bin:/Users/odrotbohm/.rbenv/shims:/usr/local/lib/ruby/gems/3.0.0/bin:/Users/odrotbohm/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Little Snitch.app/Contents/Components:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/git/bin:/Users/odrotbohm/.fig/bin:/Users/odrotbohm/Documents/workspace/spring-data-build/etc/scripts:/Users/odrotbohm/scripts::/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin::/Users/odrotbohm/.rvm/bin
Fig environment variables:
  - TERM_SESSION_ID=7E5C3784-B8D8-4FB2-A714-74A55304C5F2
  - FIG_ENV_VAR=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_CHECKED_PROMPTS=1
```

**Comment by asgeissler** [comment]
Hi Oliver,

I had a similar issue right now for a fresh first time user install
After a bit of testing, I have noticed that my anaconda environment messed the paths for the setup routine.
I fixed it by temporarily deactivating my conda and running `fig app set-path` and checked that `fig doctor` was happy.

Maybe that also works for you?

**Comment by mschrage** [comment]
Hey @odrotbohm! Sorry you're running into this issue. Do you have anything unusual about your terminal environment (eg. using `conda`)?

If you are free, I'd love to set up some time to debug this together: https://calendly.com/mschrage/30min

**Comment by odrotbohm** [comment]
All good, folks. @asgeissler's hint pointed me into the right direction. Indeed some other skript had added something post the fig environment settings at the end of my `.bashrc`. `fig doctor` helped me diagnose and it was a quick fix. Restarting the terminals made this work finally.

Thanks for everyone's assistance! 🙇

**Comment by mschrage** [comment]
Glad to hear that everything is working now, @odrotbohm! 

If you have an extra minute, would you mind sharing the script that was causing the issue (if it's not something internal)? I'm curious what it's doing that results in this behavior!

Let me know if there is anything else we can do to make Fig work better for you :)

**Comment by odrotbohm** [comment]
I've installed RVM after I had installed Fig and it had added an extra

```bash
export PATH="$PATH:$HOME/.rvm/bin"
```

to the end of the file.

**Comment by mschrage** [comment]
Interesting. I'm surprised that this would cause the insertions not to work. Moving that line above the `fig.sh` script fixed the issue?
