### ISSUE TITLE
Autocomplete window does not appear

### ISSUE THREAD

**Issue by fengjinlong** [withfig/fig#688]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B328) [搜狗拼音] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/node_global:/Users/fjl/.npm-global/lib/node_modules/iteam-cli/bin:/Users/fjl/.npm-global/lib/node_modules/iteam-cli/bin:/Users/fjl/.npm-global/bin:/usr/local/opt/node@10/bin:/usr/local/opt/node@10/bin:/usr/local/node_global:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/fjl/.fig/bin:/Users/fjl/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/MongoDB/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (39822) - ttys017
Current working directory: /Users/fjl/Documents/github/vue-next
Current window identifier: 142181/% (com.googlecode.iterm2)
Path: /usr/local/node_global:/Users/fjl/.npm-global/lib/node_modules/iteam-cli/bin:/Users/fjl/.npm-global/lib/node_modules/iteam-cli/bin:/Users/fjl/.npm-global/bin:/usr/local/opt/node@10/bin:/usr/local/opt/node@10/bin:/usr/local/node_global:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/fjl/.fig/bin:/Users/fjl/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/MongoDB/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:27F1E668-5256-4288-8A86-A2B4A332597B
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
</pre>
</p>
</details>

**Comment by fengjinlong** [comment]
![image](https://user-images.githubusercontent.com/19486973/145525578-a9329826-39f0-4fca-8c92-6391676e5c8d.png)

**Comment by fengjinlong** [comment]
![image](https://user-images.githubusercontent.com/19486973/145526567-3a03163a-2885-4e67-954a-3e1de4682f85.png)

**Comment by fengjinlong** [comment]
![image](https://user-images.githubusercontent.com/19486973/145528842-47e544da-2ab8-45c9-ac68-b8a688112569.png)
fig still not working

**Comment by mschrage** [comment]
Hey @fengjinlong! Sorry that Fig isn't working for you - let's see if we can figure out what's going on!

1. Can you type `git ` in your terminal and then take a screenshot of the Fig debugger (It is the first option when you click the the Fig icon in the menu bar).

2. Are you potentially on a CDN? To check, see if you can load `https://app.withfig.com/autocomplete/v8` in a normal browser?

3. Run `fig debug debug-mode on` in a terminal. You should see a red window appear above your cursor. Right click the window, click the "inspect elements" and then share the logs here.

**Comment by fengjinlong** [comment]
Hey，
Thank you very much, now fig is working properly, a pleasant experience。🌹
