### ISSUE TITLE
Fig does not work on my terminal

### ISSUE THREAD

**Issue by RickJ7959** [withfig/fig#690]
### Description:
> Fig does not work on my terminal. It does work in my VSS terminal, but not on my terminal window. After I did a fig doctor I get the following:

$ fig doctor
                                 
Let's make sure Fig is running...
                                 
✅ Fig bin exists
✅ Fig in PATH
✅ Fig is running
                            
Let's check your dotfiles...
                            
✅ Fig ENV variables are in ~/.profile
✅ Fig ENV variables are in ~/.bash_profile
✅ Fig ENV variables are in ~/.bashrc
✅ Fig ENV variables are in ~/.zshrc
                                                
Let's check **_your_** if your system is compatible...
                                                
✅ Running macOS
✅ macOS version is 11.x or higher
                 
Let's check what fig diagnostic says...
        
✅ Installation script
✅ Shell /bin/bash is compatible
✅ Fig is installed in /Applications/Fig.app
✅ Autocomplete is enabled
✅ CLI tool path
✅ Accessibility is enabled
✅ PATH and PseudoTerminal PATH match

❌ Secure keyboard input
   Secure keyboard input is on
   Secure keyboard process is Terminal - com.apple.Terminal (via Settings)

                                             
Let's check your **_your_** integration statuses...
                                             
✅ VSCode integration is enabled

I see the ❌ Secure keyboard input I assume this is the issue. How do I fix it?

BTW you have a few too many "your" in the doctor output. I marked them in **bold** _italic_.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.1.20G224|1.0.52|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B328) [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/rjones7/.nvm/versions/node/v14.15.5/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/rjones7/mybin:/Users/rjones7/bin:/Users/rjones7/bin/devscripts:/usr/local/bin/pkg-config:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/bin:/Users/rjones7/apache-maven-3.6.3/bin/:/Users/rjones7/apache-ant-1.10.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/rjones7/.fig/bin:/Users/rjones7/temp
SecureKeyboardInput: true
SecureKeyboardProcess: Terminal - com.apple.Terminal (via Settings)
Current active process: /bin/bash (86934) - ttys002
Current working directory: /Users/rjones7
Current window identifier: 58763/% (com.apple.Terminal)
Path: /Users/rjones7/.nvm/versions/node/v14.15.5/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/rjones7/mybin:/Users/rjones7/bin:/Users/rjones7/bin/devscripts:/usr/local/bin/pkg-config:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/bin:/Users/rjones7/apache-maven-3.6.3/bin/:/Users/rjones7/apache-ant-1.10.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/rjones7/.fig/bin:/Users/rjones7/temp
Fig environment variables:
  - TERM_SESSION_ID=84233395-FF79-4D26-9CB0-BBC328FC1936
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM_VERSION=3
  - FIG_TERM=1
</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @RickJ7959! This guide should help resolve the issue: https://fig.io/docs/support/secure-keyboard-input

Thanks for catching the typos. cc @grant0417
