### ISSUE TITLE
Fig seems to not work

### ISSUE THREAD

**Issue by xtuer** [withfig/fig#692]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
The **fig tools doctor** reports everything ok, but nothing happen after **typing cd and space** in $Home or typing such as **git**.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B328) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/biao/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/opt/mysql@5.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/biao/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/biao
Current window identifier: ???
Path: /opt/homebrew/opt/mysql@5.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/biao/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:3DC73EAB-714D-4217-9E05-3979A58BACCD
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by xtuer** [comment]
Additional, I have installed **iTerm Build 3.5.0beta3** and **oh my zsh** which using the theme POWERLEVEL9K.

**Comment by mschrage** [comment]
Hey @xtuer, thanks for reporting this. Fig should work on Monterey, so I think that something else is going on.

Can you type `git ` in your terminal and the take a screenshot of the Fig debugger (can be found by clicking the Fig icon in the menu bar).

**Comment by xtuer** [comment]
> Hey @xtuer, thanks for reporting this. Fig should work on Monterey, so I think that something else is going on.
> 
> Can you type `git ` in your terminal and the take a screenshot of the Fig debugger (can be found by clicking the Fig icon in the menu bar).

Hi @mschrage, thank you very much.
Fig works well (Do not anything else) now, after upgrading to Monterey 12.1 and reinstall Fig.

**Comment by xtuer** [comment]
Fig works in Monterey 12.1.
