### ISSUE TITLE
Multiple panels open, then autocomplete sends completion to wrong panel

### ISSUE THREAD

**Issue by Vednus** [withfig/fig#695]
### Description:
When I open a second split panel in the same window and then refocus on the first panel. Fig autocompletes whatever I'm typing into the second panel. I can avoid this issue by opening all panels I need, then restarting Fig. I'm using iTerm2. 

![image](https://user-images.githubusercontent.com/2602014/145724969-b5d804cb-2f0e-4749-94e7-77c47cfd321f.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.52 (B315)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B315) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/sundevlohr/.fig/bin/fig
Accessibility: true
Number of specs: 108
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/sundevlohr/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/sundevlohr/.yarn/bin:/Users/sundevlohr/.config/yarn/global/node_modules/.bin:/usr/local/bin/OpenMVS:/usr/local/Cellar/node/11.10.0/bin:/usr/local/opt/mysql@5.7/bin:/Users/sundevlohr/go/bin:/usr/local/go/bin:/Users/sundevlohr/.yarn/bin:/Users/sundevlohr/.config/yarn/global/node_modules/.bin:/usr/local/Cellar/node/10.7.0/lib/node_modules/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/sundevlohr/.fig/bin:/Users/sundevlohr/Library/Android/sdk/emulator:/Users/sundevlohr/Library/Android/sdk/tools:/Users/sundevlohr/Library/Android/sdk/tools/bin:/Users/sundevlohr/Library/Android/sdk/platform-tools:/usr/local/Cellar/watchman
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (2623) - ttys009
Current working directory: /Users/sundevlohr/Sites/pebble
Current window identifier: 388/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Vednus! This issue is fixed as of v1.053.

You can run `fig update` to automatically download the latest version.

**Comment by Vednus** [comment]
Oops. Sorry about that. Duh, should have tries to upgrade first.

**Comment by mschrage** [comment]
No worries! Glad to hear that everything is working :)
