### ISSUE TITLE
Fig doesn't complete options after an option starting with -opt and does after --opt

### ISSUE THREAD

**Issue by a7med-mahmoud** [withfig/fig#696]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session

### Description:
I'm working on a spec for `keytool` and almost all its commands start with `-` instead of `--` like for example `-help`, `-alias`, and `-file`, when Fig sees something like this it thinks they should by like `-r` and `-f` and it should join them as `-rf` for example and that's not the case with `keytool`.

### Environment

```bash
Fig Version: Version 1.0.53 (B339) [Dev] [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (84147) - /dev/ttys003
Current window identifier: 4292/% (com.microsoft.VSCode)
Fig environment variables:
  - TERM_SESSION_ID=D2894510-C54A-408F-92F0-CE54EDE1D485
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
```

**Comment by fedeci** [comment]
I honestly think that has became a standard that long option start with a double dash🤔. This is a super edge case and I wonder if we should create some new parser option.
/cc @sullivan-sean

**Comment by mschrage** [comment]
Hey @a7med-mahmoud! This is actually supported already by the autocomplete engine. Check out the [`parserDirectives`](https://fig.io/docs/reference/subcommand#parserdirectives) field.
