### ISSUE TITLE
Cannot run commands in terminal after macOS has been asleep

### ISSUE THREAD

**Issue by kirill-reva** [withfig/fig#697]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
When going back from sleep on macbook fig slows down the terminal, can't run any commands, especially git commands until I restart Fig

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.52 (B328)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B328) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/kirillreva/.fig/bin/fig
Accessibility: true
Number of specs: 207
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/postgresql@12/bin:/Users/kirillreva/.nvm/versions/node/v14.16.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/kirillreva/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @kirill-reva, so sorry that you are running into performance issues. 

The next time that this happens, can you run `fig debug logs` in a new terminal window and record your screen as you try to type in the slow terminal session.

Thanks so much!

**Comment by ank1traj** [comment]
All settings are marked but still not working on the mac

<img width="1440" alt="Screenshot 2021-12-29 at 10 18 06 AM" src="https://user-images.githubusercontent.com/32160084/147628284-8ac6af72-b8f0-4bc5-9082-97e53081d91b.png">

**Comment by mschrage** [comment]
Hey @ank1traj! Are you free to jump on a debugging call now?

In the meantime, can you share a screen recording of the behavior?

**Comment by ank1traj** [comment]
@mscharge currently I am facing some network issues. Once, it will be back we can jump on a debugging call. 

Behavior is like nothing is happening after typing anything on the terminal.

**Comment by SeparateRecords** [comment]
Should be fixed now!
