### ISSUE TITLE
Keybuffer context is lost!

### ISSUE THREAD

**Issue by dipakparmar** [withfig/fig#7]
Keybuffer context is lost while working in root directories like `/var/lib` ... autocomplete doesn't work. After entering to new line it works but after starting with the`var` directory it again loses the context

**Comment by mattschrage** [comment]
I think this may have been fixed in more recent build. Are you still running into this @dipakparmar?

**Comment by dipakparmar** [comment]
Thanks, @mattschrage! This issue is resolved. Tested in Fig v1.0.32(B80)
