### ISSUE TITLE
breaking terminal ascii art when running fig wrapped

### ISSUE THREAD

**Issue by takashimamorino** [withfig/fig#700]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [x] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Thank you awesome product.

breaking terminal ascii art when running fig wrapped.
![image](https://user-images.githubusercontent.com/44386888/145961790-7d5bbc73-fc62-49dd-8e18-8338ea73d211.png)

### Environment

```bash
run fig diagnostic

$ fig diagnostic
Fig Version: Version 1.0.53 (B339) [ABC]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
```

terminal: iTerm2 3.4.14
OS: macOS Monterey 12.0.1 (M1)

**Comment by mschrage** [comment]
Hey @takashimamorino! Thanks for reporting this.

The workaround for this issue is running `export LANG=en_US.UTF-8` before running `fig wrapped`.

**Comment by takashimamorino** [comment]
@mschrage 
oh. thank you!
I've confirmed that it's displayed correctly.
