### ISSUE TITLE
Autocomplete stops working when mac is offline

### ISSUE THREAD

**Issue by yurakruhlyk** [withfig/fig#701]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
When mac just reloaded or comes out of sleep, sometimes fig autocomplete just stops working.
And it looks like this issue about internet connection because when I got the issue again and opened debug console I saw that some modules didn't load. After off/on to autocomplete in fig menu we got new logs in the console and everything works fine. So I think probably the module doesn't have time to load and do this before mac is online.
<img width="1250" alt="Screenshot 2021-12-14 at 19 55 49" src="https://user-images.githubusercontent.com/16261471/146059179-ae50bc62-3f69-4b75-baab-b2d0bd7f244d.png">
<img width="1436" alt="Screenshot 2021-12-14 at 20 07 12" src="https://user-images.githubusercontent.com/16261471/146059191-3da50fec-74bb-4825-8204-d88fb483809d.png">
<img width="1436" alt="Screenshot 2021-12-14 at 20 07 23" src="https://user-images.githubusercontent.com/16261471/146059199-3d01f84e-5ffa-4099-90e2-bf598d3ef672.png">

terminal: iTerm2 3.4.14
OS: macOS Monterey 12.0.1 (M1 Pro, 14-inch)

### Environment

```bash
Fig Version: Version 1.0.53 (B339) [Debug] [U.S.]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/user/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path:
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current window identifier: 601/% (com.googlecode.iterm2)
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:2E6FD260-7103-4810-812E-1A729D0747A9
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
```

**Comment by mschrage** [comment]
See also #714.

**Comment by SeparateRecords** [comment]
Maybe in the case that it's unable to connect, it should try again after 5 seconds, then again after another 5?

This would probably help in the case that Fig launches (or invalidates a cache?) before the network interface is up, which would be my guess for what's happening here

**Comment by yurakruhlyk** [comment]
@SeparateRecords Maybe there is possible to check when the device goes offline and after that load all needed files?

**Comment by brendanfalk** [comment]
Seems to be issue with internet connection not being established on mac load. Fig is trying to load autocomplete but because there is no internet, we can't. Fig tries to reconnect to the internet just once.

**Proposed solution**
We should attempt to reconnect to the internet multiple times but with an exponential back off. This should be done from the autocomplete app. 

We should also indicate to the user that autocomplete didn't load. The autocomplete app should notify the desktop app that there was an error with the internet and should put this in the debugger

**Comment by brendanfalk** [comment]
We implemented the solution discussed above except do not yet have a notification telling users that their wifi is enabled.

We still need to enable users to download the specs locally so it can work offline

**Comment by brendanfalk** [comment]
We will likely enable users to download specs locally by running `npm install -g @fig/autocomplete`

**Comment by brendanfalk** [comment]
This should be fixed! Please comment below if not :)
