### ISSUE TITLE
Popup window shows up over IntelliJ Idea

### ISSUE THREAD

**Issue by Exaper** [withfig/fig#704]
### Description:
Fig's popup window shows up in IntelliJ Idea. I can dismiss it only by closing out the IDE.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.2|Version 1.0.53 (B339)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.53 (B339) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/paul/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/paul/flutter/bin:/Users/paul/android-sdk/tools:/Users/paul/android-sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/paul/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Exaper! This is strange since Fig does not currently support any IntelliJ terminals. 

Would you mind sharing a screenshot next time this happens?

**Comment by fedeci** [comment]
It was happening on xCode to me too, I have opened an issue in Linear a while ago.

**Comment by mschrage** [comment]
Potentially Fig is not hiding the window correctly when the user switches to an unsupported application.

**Comment by Exaper** [comment]
This happens to me when I bring up a popup from IntelliJ/Android Studio while Fig is running in background. 

Usually command like "Find Usages" will trigger this. One shown, empty popup stays open until I close the IDE. It almost feels like Fig is not the reason why this issue occurs, but I can attest that it only happens when Fig is running.

**Comment by mschrage** [comment]
Was the Fig window visible before in a different application (eg. you're using Fig in iTerm and then you switch to IntelliJ)? Or does it go from being hidden to being visible?

Also is this behavior reproducible for you @Exaper? If so, mind sharing a screen recording while running `fig debug logs` in a separate terminal window?

**Comment by brendanfalk** [comment]
According to a user, this happens in Android studio after hitting cmd+b. Could be a separate issue though!

**Comment by Exaper** [comment]
It's not cmd+b, it's ctrl+space or shift+F6 (or other commands that bring up floating window in Android Studio). Once that window is up it's empty and stays on the screen even when I minimize everything. I understand that this seems like a not a Fig's issue, but this never happened before and does not occur if I quit Fig.

**Comment by mschrage** [comment]
Hey @Exaper, would you mind sharing a screenshot/video so I can get a better sense of what this looks like?

**Comment by brendanfalk** [comment]
@Exaper Yes understand - another user seems to be facing a similar issue but with cmd+b. I commented it there just to add that extra info as it seems related.

As Matt suggested, if you could comment a video of the issue that would be super helpful!

**Comment by Exaper** [comment]
Sure. Happened to me again after starting Fig. Here's what is looks like after everything is minimized:

![image](https://user-images.githubusercontent.com/2935045/148609742-776db4a4-ac20-4f7e-b679-597146e04010.png)

**Comment by mschrage** [comment]
Is this the type of popup window you're referring to? (Triggered by pressing ctrl+space) I'm not especial familiar with Android Studio or IntelliJ, so am not sure what you mean by floating window?

<img width="638" alt="Screen Shot 2022-01-07 at 4 00 34 PM" src="https://user-images.githubusercontent.com/3155109/148621901-d8384470-00ac-4df5-8a83-351195eeaf31.png">

**Comment by mschrage** [comment]
> with Fig on, if I press cmd + b, I encountered an empty box like a video.
I think it occurs when cmd + b is pressed on a variable that has only one usage.
It can't be delete, It will remain until you quit Android Studio.
my Android Studio Version is 2020.3.1 Patch 1 


https://user-images.githubusercontent.com/3155109/149847044-fc552a81-2a2d-4c66-a476-f5d86142265a.mov

**Comment by grant0417** [comment]
We should support intellij now and this issue seems quite old.
