### ISSUE TITLE
Disable autocompletion when moving through command history (after up or down arrows)

### ISSUE THREAD

**Issue by Ronserruya** [withfig/fig#706]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
Very often I use the up or down arrows to navigate my recent command history, when using fig, each of those commands opens the autocomplete window. 
When I use the up arrow, I need to double-tap it to close the autocomplete window then continue,
with the down arrow I need to scroll all of the autocomplete options, and even when you reach the end of the list, pressing down again doesn't close it. So I need to first click ESC to close it then I can continue.

When you navigate through a lot of commands this becomes really bothersome, I think the solution can be to not show the autocomplete window if the key-press before it was up or down.

Video (the key-presses UI doesn't show it, but I'm repeatedly pressing down):
https://user-images.githubusercontent.com/21235163/146185094-7dad4bd0-5a5a-4fb3-8b93-9512fcd72a6a.mov

git debugger pic:
![Screen Shot 2021-12-15 at 13 17 25](https://user-images.githubusercontent.com/21235163/146178935-07737b67-f505-4aff-9cb8-89668a7f313c.png)

### Environment

```bash
Fig Version: Version 1.0.53 (B339) [ABC]
UserShell: /usr/local/bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/ron/.sdkman/candidates/java/current/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/grep/libexec/gnubin:/Users/ron/.nvm/versions/node/v12.13.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/ron/.fig/bin:/Users/ron/Library/Python/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: bash (75986) - /dev/ttys001
Current working directory: /Users/ron
Current window identifier: 143483/% (com.googlecode.iterm2)
Path: /Users/ron/.sdkman/candidates/java/current/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/grep/libexec/gnubin:/Users/ron/.nvm/versions/node/v12.13.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/ron/.fig/bin:/Users/ron/Library/Python/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:E995D2D3-A995-48E0-84B5-F05A0D5F5915
  - FIG_ENV_VAR=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_CHECKED_PROMPTS=1
```

**Comment by mschrage** [comment]
Hey @Ronserruya, thank so much for reporting this. I can reproduce in both `bash` and `fish.

I think we'll be able to get a fix out soon.

**Comment by brendanfalk** [comment]
@Ronserruya this fix should be live! Let us know what you think :)

**Comment by Ronserruya** [comment]
Looking good, thanks!
I encountered another bug while updating, but I'll open a separate issue for this
