### ISSUE TITLE
Fig "Not linked to TTY" issue with the debugger on iTerm. `fig doctor` is not solving the problem

### ISSUE THREAD

**Issue by chrissshan** [withfig/fig#708]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

<img width="384" alt="Screen Shot 2021-12-15 at 10 38 08 AM" src="https://user-images.githubusercontent.com/86078021/146245576-1388bb65-464c-4094-b7c4-ae2ae67333d2.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.53|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>
It looks like Fig is not running.
Try running: fig restart

</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @chrissshan! So sorry that Fig isn't working for you.

Would you mind sharing the output of `fig diagnostic` when the app is running? This will help narrow down where the issue is occurring.

**Comment by chrissshan** [comment]
Resolved with computer restart
