### ISSUE TITLE
Grammatical error in initial onboarding

### ISSUE THREAD

**Issue by teancom** [withfig/fig#71]
**Summary:**
I skimmed the prompt and typed the wrong thing (fig settings instead of just fig or continue) but the error message has a grammatical error. Possibly missing the words ‘than the’, as in ‘other than the Fig command’?

**Steps to Reproduce:**
1. Go through initial setup
2. Type something other than `fig` or `continue` when prompted to type one of those things.

**Expected Results:**
The sentence should say something like: `Whoops. Looks like you tried something other than the Fig command.`

**Actual Results:**
`Whoops. Looks like you tried something other Fig command`

**System information:**
OS: MacOS Big Sur 11.1
Terminal: iTerm2
Version of Fig: 1.0.40

**Additional Notes:**

<img width="813" alt="Screenshot 2021-05-05 at 13 09 36@2x" src="https://user-images.githubusercontent.com/609527/117195964-2a8b9f80-ada3-11eb-861e-4e39c658c7f6.png">

**Comment by falky97** [comment]
Fixed in v1.0.41!
