### ISSUE TITLE
Settings app does not restore default values

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#710]
>  The font size setting when emptied does not always return to default, and instead makes the box very small. I would expect if I delete the value from the font size setting (ie the input box is empty) that it returns to a sensible default.

**Comment by edhgoose** [comment]
Here's what it looks like if I empty the box:

<img width="439" alt="CleanShot 2021-12-16 at 09 35 04@2x" src="https://user-images.githubusercontent.com/1108173/146345978-1745dfe1-01c0-4694-9746-2fc16565419a.png">

Manually restoring the font size to 12px sorts it out:

<img width="446" alt="CleanShot 2021-12-16 at 09 35 45@2x" src="https://user-images.githubusercontent.com/1108173/146346152-41874fab-bf22-40dd-870d-227022af9322.png">

**Comment by grant0417** [comment]
We have a new settings app, this should be fixed!
