### ISSUE TITLE
[zplug] Paths suggestions with the cd command not working

### ISSUE THREAD

**Issue by timohubois** [withfig/fig#713]
### Description:
When i run `cd` autocomplete will not suggest anything. The loader will be shown for a few seconds and after that I disappears.

<img width="445" alt="Screenshot 2021-12-16 at 00 20 11" src="https://user-images.githubusercontent.com/46505685/146279965-ee5d08cb-daeb-424a-b903-dc0620a102fc.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.21C52|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B328) [German] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/node@14/bin:/usr/local/sbin:/usr/local/Cellar/zplug/2.4.2/repos/zplug/zplug/bin:/usr/local/opt/zplug/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/XXX/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (1011) - ttys002
Current working directory: /Users/
Current window identifier: 119/A7B02FF2-B387-4A93-B15C-D546EDCF76B8% (com.googlecode.iterm2)
Path: /usr/local/opt/node@14/bin:/usr/local/sbin:/usr/local/Cellar/zplug/2.4.2/repos/zplug/zplug/bin:/usr/local/opt/zplug/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/XXX/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:A7B02FF2-B387-4A93-B15C-D546EDCF76B8
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @timohubois! Thanks for reporting this. There is a known compatibility issue when using `zplug` with Fig. 

We have a fix coming out in the next build, but as a temporary workaround replace `zplug` with `[ -z $FIG_PTY ] && zplug load` in your zshrc.

This will ensure that`zplug load` is only run when **not** inside of Fig's pseudo-terminal.

**Comment by timohubois** [comment]
Hi @mschrage, thank you for the quick response. I have added your suggestion to my `.zshrc` but this did solve the issue. Do you have any other suggestions?

**Comment by timohubois** [comment]
Command back! After restarting Fig works like a charm. Thank you!

**Comment by mschrage** [comment]
This should be resolved as of v1.0.54 (which is live now)!
