### ISSUE TITLE
Onboarding not appearing after installation

### ISSUE THREAD

**Issue by BaiMingxu** [withfig/fig#715]
MacOS12.1
After installation, only these will be displayed. The permission has been granted
<img width="269" alt="截屏2021-12-16 09 47 47" src="https://user-images.githubusercontent.com/22886455/146293047-77452c6b-25bc-4e8d-a122-a76e741860e2.png">

**Comment by mschrage** [comment]
Hey @BaiMingxu! You should see a window like this appear on your screen. Is that not showing up anywhere?

<img width="719" alt="Screen Shot 2021-12-15 at 3 27 24 PM" src="https://user-images.githubusercontent.com/3155109/146295753-8cb070d4-d972-4ecf-8e51-80cdafebbff4.png">

**Comment by BaiMingxu** [comment]
Yeah, that's what it looks like after the installation，How can I use it in Iterm2? For help




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Matt ***@***.***&gt;; 
发送时间: 2021年12月16日(星期四) 上午10:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [withfig/fig] Nothing after installation (Issue #715)






嘿@白明旭你应该看到这样的一个窗口出现在你的屏幕上。它没有显示在任何地方吗？



—
你收到这个是因为你被提到了。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by mschrage** [comment]
You need to go through the entire onboarding flow and then Fig will work in iTerm! Once you have granted Accessibility permission and logged in, Fig will automatically open a new terminal session for you that will look like this:

<img width="682" alt="Screen Shot 2021-12-15 at 6 26 49 PM" src="https://user-images.githubusercontent.com/3155109/146296682-bfad70fe-aa0d-4972-ab0c-30c161f70707.png">
