### ISSUE TITLE
Fig doesn't "notice" a read-only ~/.ssh/config

### ISSUE THREAD

**Issue by teancom** [withfig/fig#72]
**Summary:**
My ~/.ssh/config file was read-only (0400) and Fig claimed that it successfully added the integration when asked to do so during the onboarding process. It also shows a checkmark in the Fig Menu -> Settings -> SSH Integration.

**Steps to Reproduce:**

1. chmod 0400 ~/.ssh/config
1. Install fig
1. Ask it to enable the SSH integration

**Expected Results:**
Fig should display an error (hopefully a helpful one!) if it is unable to modify the SSH config file. It should also check (somehow?) that the integration was successful before showing the checkmark in the menu.

**Actual Results:**
The SSH integration can be broken/not-actually-set, with no user-visible errors or indication.

**System information:**
OS: MacOS Big Sur 11.1
Terminal: iTerm2
Version of Fig: 1.0.40

**Comment by mattschrage** [comment]
Thanks for reporting this bug. Is it common to make ~/.ssh/config read-only?

**Comment by teancom** [comment]
Probably not! In my case, it was read-only due to a bug in a script that I use to sync my configs across computers.

**Comment by teancom** [comment]
This bug is more around checking that installing the ssh integration worked and alerting if it doesn't (other possible problems: ~/.ssh/ itself is readonly, owned by a different user, the file looks writable but has the immutable extended attribute set, the file system is full so it's unable to write, and probably more that I'm not thinking of right now 😄)

**Comment by mschrage** [comment]
@fwesss this would be an interesting check to add to `fig doctor`!

**Comment by mschrage** [comment]
Closing this issue as we are reworking the SSH integration. See #709.
