### ISSUE TITLE
Fig zsh history issue

### ISSUE THREAD

**Issue by Apollorion** [withfig/fig#721]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [ ] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
I use ZSH and I love the ability to type partial commands and then press the up arrow to only show recent commands starting with what I've typed.

For example:
1. `kubectl get pods`
2. `kubectl get ds`
3. Now if I type `kubectl get p` then press the up arrow, it will skip the `get ds` part of my history and go straight to `kubectl get pods`

With fig, this is broken. Using the above example, if I type `kubectl get p` and press the up arrow it will go to `kubectl get ds`.

### Environment

```bash
Mac OSx big Sur Intel processor using iterm and tmux
```

**Comment by mschrage** [comment]
Hey @Apollorion! This is a known issue that should be fixed in the next release (v1.0.54)

In the meantime, @dannysteenman found a [workaround](https://github.com/withfig/fig/issues/502#issuecomment-993306970):
> As a workaround for now, I've explicitly added the bindkeys again in the `.zshrc` file to make zsh-history-substring-search work together with fig:
>
> ```
> bindkey '^[[A' history-substring-search-up
> bindkey '^[[B' history-substring-search-down
> ```

For more details, see https://github.com/withfig/fig/issues/502
