### ISSUE TITLE
`optionsCanBreakVariadicArg` not working in custom spec

### ISSUE THREAD

**Issue by jazanne** [withfig/fig#722]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [ ] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:

I am trying to create a Project Spec with a variadic option.

Here is my relevant spec:

```ts
{
  name: ["-p", "--project-key"],
  description: "Project key",
  icon: ICON_PROJECT,
  priority: 800,
  args: {
    name: "string",
    description: "Project key",
    debounce: true,
    generators: apiGenerators.listProjects,
  }
},
{
      name: ["-T", "--tag"],
      description: "Sync flags with the specified tag(s). Only flags with all tags will sync.",
      icon: ICON_TAG,
      args: {
        name: "string",
        description: "Tag name",
        isVariadic: true,
        optionsCanBreakVariadicArg: true,
        debounce: true,
        generators: apiGenerators.listFlagTags,
      },
    },
```

Here is a screenshot of the issue - you can see that the new -p option isn't breaking the -T option:

<img width="331" alt="CleanShot 2021-12-16 at 11 14 42@2x" src="https://user-images.githubusercontent.com/4053924/146408500-849af757-bebf-498e-b46f-5990adc9c037.png">

### Environment

```bash
Last login: Thu Dec 16 10:29:49 on ttys001
jwhite@Jazs-MBP sync-ld-flags % fig diagnostic
Fig Version: Version 1.0.53 (B339) [Dev] [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 203
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/jwhite/.nvm/versions/node/v16.3.0/bin:/Users/jwhite/.goenv/versions/1.17.3/bin:/Users/jwhite/.goenv/shims:/Users/jwhite/.goenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/jwhite/.fig/bin:/Users/jwhite/go/1.17.3/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (55438) - /dev/ttys006
Current working directory: /Users/jwhite/code/mine/sync-ld-flags
Current window identifier: 27461/% (com.apple.Terminal)
Path: /Users/jwhite/.nvm/versions/node/v16.3.0/bin:/Users/jwhite/.goenv/versions/1.17.3/bin:/Users/jwhite/.goenv/shims:/Users/jwhite/.goenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/jwhite/.fig/bin:/Users/jwhite/go/1.17.3/bin
Fig environment variables:
  - TERM_SESSION_ID=7CED4D04-468E-4B18-A772-F1B88AA4CD5A
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
```

**Comment by mschrage** [comment]
Hey @jazanne! Thanks so much for letting us know. We'll investigate what's going on here! 🐛

Also how is the experience of building a custom spec? 

We have a contributors channel in our [Discord](https://fig.io/community) and would love to help if you run into any issues!

**Comment by sullivan-sean** [comment]
Hi @jazanne - Currently our `optionsCanBreakVariadicArg` option only works for variadic subcommand args (poorly named, and worth given better examples and clarifying in our docs). We haven't seen any CLI tools that allow users to pass variadic options argument lists that are broken by other options, but would love to understand more about this use case.

This `optionsCanBreakVariadicArg` was originally introduced to handle the case of `echo` which can take something like `echo hello -n world` where the variadic args for `echo` continue after breaking with an option. 

Wondering how the CLI tool you're writing the spec for would handle parsing these options after you've entered a project name, e.g. is `-T tag1 tag2 -p project tag3` valid? or does the `-p project` terminate the list of arguments to `-T`?

**Comment by jazanne** [comment]
Ah ok - thanks for the info.

My script is built with the [commander npm pkg](https://www.npmjs.com/package/commander)

option for tags in code ([variadic option](https://www.npmjs.com/package/commander#variadic-option))

```js
.option('-T, --tag <tags...>', 'Sync flags with the given tag(s). Only flags with all tags will sync.')
```

`-p project` DOES terminate the tag list so `-T tag1 tag2 -p project tag3` is **invalid**

General feedback - so far I've had a great time developing a spec! The docs have been pretty easy to follow

**Comment by sullivan-sean** [comment]
This should be fixed -- you might need to restart Fig or right click on the autocomplete window to reload though! Also [our docs](https://fig.io/docs/reference/arg#optionscanbreakvariadicarg) are updated to reflect the new behavior for variadic option arguments.

I corrected my above description of `echo` -- `echo` is actually an exception where `optionsCanBreakVariadicArgs` is `false`, the default behavior for most cli tools (e.g. `git add`, `ls`, etc.) is to allow options to break variadic subcommand arguments, which is reflected in the docs as our `Default: true` for `optionsCanBreakVariadicArgs`.

Let me know if the documentations is still unclear at any point and I can clarify or reword!

**Comment by jazanne** [comment]
thanks for fixing this so quickly! The updated doc examples look great and make sense to me
