### ISSUE TITLE
Skip shell onboarding (tutorial) for existing/returning users

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#723]
Users that already know how to use Fig should still have the tutorial as an option (possibly presented during GUI onboarding) but it should be opt-in instead of opt-out with ctrl+c

**Comment by mschrage** [comment]
Which are you referring to here @SeparateRecords? The GUI onboarding or the shell onboarding.

**Comment by SeparateRecords** [comment]
Good point, I'll clarify in the issue body and title

**Comment by grant0417** [comment]
The revamped onboarding will only show once per user!
