### ISSUE TITLE
Version check window disappears before it can be read.

### ISSUE THREAD

**Issue by mikebronner** [withfig/fig#73]
### Description:
When running a version check, the pop-up window disappears before I can read it.

### Details:
|macOS|Fig|Shell|
|----|----|----|
|11.4.0|Version 1.0.41 (B206)|/bin/zsh|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.41 (B206)
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/mike/.fig/bin/fig
Accessibility: true
Number of specs: 92
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/mike/.fig/user/keybindings
iTerm Integration: false
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/mike/.yarn/bin:/Users/mike/.config/yarn/global/node_modules/.bin:/opt/homebrew/bin/brew:/Users/mike/bin:/usr/local/bin:/usr/local/php5/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Little
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
This has been fixed as of v1.0.45!
