### ISSUE TITLE
Enter not working for auto-complete

### ISSUE THREAD

**Issue by iamsahilsonawane** [withfig/fig#730]
### Description:
I am not able to auto-complete pressing `ENTER`, this issue has hit me later in this period, without auto-completing with `ENTER` press, it's not really much of use then. Initially, all was good! but I think there was some issue when I started experiencing this issue mentioned and also fig not starting up on startup (I suspect any update made this change). 

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.1.20C69|1.0.52|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.52 (B317) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 204
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/sahilsonawane/Library/Android/sdk/tools:/Users/sahilsonawane/Library/Android/sdk/tools/bin:/Users/sahilsonawane/Library/Android/sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/sahilsonawane/.fig/bin:/Users/sahilsonawane/Developer/flutter/bin:/usr/local/opt/fzf/bin:/Users/sahilsonawane/Developer/flutter/.pub-cache/bin:/Users/sahilsonawane/Developer/flutter/bin/cache/dart-sdk/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (38588) - /dev/ttys009
Current working directory: /Users/sahilsonawane/Projects/DevStory/betting_app_cloudfunction/functions
Current window identifier: 26473/26BD70DF-6C71-4B93-A6F7-00813BF27387% (com.googlecode.iterm2)
Path: /Users/sahilsonawane/Library/Android/sdk/tools:/Users/sahilsonawane/Library/Android/sdk/tools/bin:/Users/sahilsonawane/Library/Android/sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/sahilsonawane/.fig/bin:/Users/sahilsonawane/Developer/flutter/bin:/usr/local/opt/fzf/bin:/Users/sahilsonawane/Developer/flutter/.pub-cache/bin:/Users/sahilsonawane/Developer/flutter/bin/cache/dart-sdk/bin</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @iamsahilsonawane! It looks like you are not on the latest version.

Run `fig update` to upgrade to the latest version (v1.0.53) or `brew install fig` to reinstall the macOS app.

**Comment by iamsahilsonawane** [comment]
Hii @mschrage, thanks for the reply. I'm on the latest version now (1.0.53). I am now able to work with fig at the incipiently, but still facing the issue of auto-completing by pressing enter. I'm attaching a screen recording of the same for reference.

https://user-images.githubusercontent.com/47249618/147226245-fc368510-fc98-480d-9167-1b680ec6624e.mov

Thanks!

**Comment by mschrage** [comment]
Hey @iamsahilsonawane, if you open a new terminal session, will insertion work there?

Also can you run `fig diagnostic` the next time you have a terminal session that is effected?

**Comment by iamsahilsonawane** [comment]
@mschrage, I tried running the overall terminal with the new session and it's working now. Actually, I think it was the previous session still having the issue state cached. Thanks mate it works great as expected now :)
