### ISSUE TITLE
Strange behaviour of icon in menu bar in OSX 10.13.6

### ISSUE THREAD

**Issue by jpcmf** [withfig/fig#732]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:

I've sent this to e-mail this issue but someone of fig team asked to me to open the issue here. So when the dark menu and dock is abled in General configuration in OSX the behaviour of the icon is not good enough. See the prints below :) Thank you.

![Screen Shot 2021-12-12 at 21 25 42](https://user-images.githubusercontent.com/1216136/146914250-854b1e16-621c-4cbd-94e1-a6fd917be843.png)
![Screen Shot 2021-12-12 at 21 24 52](https://user-images.githubusercontent.com/1216136/146914265-23fda649-0cb5-4313-b8bf-e8e2c5c020ac.png)

### Environment

```bash
❯ fig diagnostic
Fig Version: Version 1.0.53 (B339) [Brazilian - Pro]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/joaopaulofricks/.zinit/polaris/sbin:/Users/joaopaulofricks/.zinit/polaris/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/joaopaulofricks/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (12162) - /dev/ttys012
Current working directory: /Users/joaopaulofricks/www
Current window identifier: 65/% (com.googlecode.iterm2)
Path: /Users/joaopaulofricks/.zinit/polaris/sbin:/Users/joaopaulofricks/.zinit/polaris/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/joaopaulofricks/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t1p3:4B2BF215-D92E-475A-98E9-8289941FB4E3
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
```

**Comment by mschrage** [comment]
Hey @jpcmf! Thanks for opening the issue. What version of macOS are you using?

**Comment by jpcmf** [comment]
> Hey @jpcmf! Thanks for opening the issue. What version of macOS are you using?

@mschrage Hey no problem ;) I'm using macOS High Sierra Version 10.13.6. If you need some feedback when fix it drop me a line. All the best ;)

**Comment by mschrage** [comment]
Hey @jpcmf - the oldest version of macOS that we guarantee support for is Mojave. I'd recommend upgrading your OS, if you can.
