### ISSUE TITLE
Menubar icon cannot be reenabled

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#734]
**Summary**
> I turned off the menu bar icon in settings (I don't know why), but I cannot get it to re-appear and to change settings. When running the app now, it fires up in the background but no interface opens, nor an app icon in the dock or menu bar.

**Expected**
Reenabling the menubar icon should work.

**Comment by olivernybroe** [comment]
A solution that we had to do because I had accidentally enabled debugging while disabling the menu, was to go into ~/.fig/settings.json and change the settings 👍  No issues with doing that at all

**Comment by grant0417** [comment]
This should be fixed!
