### ISSUE TITLE
fig settings open blank dialog

### ISSUE THREAD

**Issue by wafer-li** [withfig/fig#736]
### Description:

`fig settings` open a blank dialog
<img width="803" alt="截屏2021-12-22 13 53 38" src="https://user-images.githubusercontent.com/12459199/147042669-aad09b98-037c-4d24-9b39-18b4e6db16b6.png">

Sometimes it shows things, and sometimes it remains empty.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.0|Version 1.0.53 (B339)|/opt/homebrew/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.53 (B339) [ABC] 
UserShell: /opt/homebrew/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/wafer-li/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/Users/wafer-li/Library/Android/sdk/platform-tools:/opt/homebrew/bin/brew:/Users/wafer-li/.fig/bin:/opt/homebrew/opt/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @wafer-li! The settings app is hosted remotely so this likely means that your internet connection wasn't working. 

We should make this more clear in the UI.

Next time this happens can you control+click the window and open "Inspect Elements". I would love to see what is in the console.

**Comment by wafer-li** [comment]
@mschrage 

Thanks for your reply, I currently live in China, and I believe the issue is caused by Internet connection indeed.

But I still wonder, why you guys make the "settings" page hosted on the Internet? 

Why not just host all the settings page just locally? 

The settings should follow the version of the app, and if settings need to be changed, the app will need to upgrade.

Therefore, it is usually the settings page comes with the app locally.
