### ISSUE TITLE
Every time I open it, I will quit after a while I don’t know why, and then I have to manually start it myself.

### ISSUE THREAD

**Issue by fariellany** [withfig/fig#737]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.2.2|Version 1.0.52 (B322)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B322) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/sushi/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @fariellany! It looks like you are in an old version. 

Try updating to the latest version and see if this resolves the issue!

**Comment by fariellany** [comment]
> Hey @fariellany! It looks like you are in an old version.
> 
> Try updating to the latest version and see if this resolves the issue!

Thank you very much for your reply. I upgraded it and it solved the problem. Thank you very much for your help.
