### ISSUE TITLE
there are something wrong in oh-my-zsh af-magic theme

### ISSUE THREAD

**Issue by dofy** [withfig/fig#739]
### Description:

When using the af-magic theme of oh-my-zsh, the interface characters will be misplaced

![image](https://user-images.githubusercontent.com/344197/147258292-7eff7b50-af9e-412d-b94a-b4dc22bf13ab.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.0|Version 1.0.53 (B339)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.53 (B339) [ABC – Extended] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/seven/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/opt/gettext/bin:/opt/homebrew/opt/bison/bin:/opt/homebrew/sbin:/opt/homebrew/opt/libpq/bin:/opt/homebrew/opt/libxml2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/ruby/bin:/Users/seven/Works/_flutter/bin:/Users/seven/.nvm/versions/node/v14.16.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/Users/seven/.fig/bin:/Users/seven/.fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 12377/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @dofy! We're looking into this. We've seen it before and if I recall correctly this is actually an issue with the `af-magic` theme.

**Comment by dofy** [comment]
Hi @andyfleming, can you please take a look at this question?

**Comment by mschrage** [comment]
Hey @dofy @rickdoesburg! I figured out what's going wrong here. There *was* a problem with the af-magic theme (see https://github.com/withfig/config/pull/59) but the [fix](https://github.com/ohmyzsh/ohmyzsh/commit/c172624398918577bcb212d07b0036f4058cb5c6
) has been upstreamed.

Now our workaround is out of date and is causing issues. You can fix this by opening `~/.fig/shell/post.zsh` and removing the selected text.

<img width="674" alt="Screen Shot 2022-01-06 at 10 42 17 PM" src="https://user-images.githubusercontent.com/3155109/148503100-5ed75343-9606-47ad-8f81-72bcd03bb5e5.png">

I will fix this in the next release.

**Comment by dofy** [comment]
@mschrage Pretty cool !!! Thanks a lot 👏

**Comment by mschrage** [comment]
This is fixed as of v1.0.54. You can update by running `fig update` in your terminal.
