### ISSUE TITLE
Improve support for argument ordering

### ISSUE THREAD

**Issue by MKorostoff** [withfig/fig#740]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
In certain situations, fig will suggest command line arguments in the wrong order. For instance, if I type `chmod 644 -` fig will suggest `chmod 644 -R`.

<img width="717" alt="Screen Shot 2021-12-23 at 11 42 52 AM" src="https://user-images.githubusercontent.com/1197335/147269383-3fc704c2-c746-404e-9a1f-745f584629b0.png">

The trouble is, -R does not go in that spot. It should go `chmod -R 644` with the R flag coming immediately after the main command. If you attempt to run the command as suggested, it will not work, and you'll receive the error "chmod: -R: No such file or directory." This is compounded by the fact that, once you have made this error one time, the erroneous suggestion will float to the top of your suggestion list.

Ideally, fig would insert the argument at the appropriate location. For instance, in the above example, someone typing `chmod 644 -` would still see -R as a suggestion, but when they accept the suggestion, the -R flag would be inserted between "chmod" and "644."

Possibly related: https://github.com/withfig/fig/issues/463

**Comment by mschrage** [comment]
Interesting! I think by default the autocomplete-engine will continue to suggest options even after arguments are passed to the command/subcommand. For another example, type `cp -r ./folder -`. Options will be suggested.

<img width="468" alt="Screen Shot 2021-12-25 at 11 38 18 PM" src="https://user-images.githubusercontent.com/3155109/147399009-b150802e-deaa-4596-b072-b1ee1b4023e3.png">

Whether this is valid or not, depends on how the executables parses the command line input. We should probably allow completion specs to specify what behavior they prefer, potentially by adding a new `optionsMustProceedArguments` field to the [`parserDirectives`](https://fig.io/docs/reference/subcommand#parserdirectives) object.

```ts
parserDirectives: {
   optionsMustProceedArguments: true
}
```

**Comment by SeparateRecords** [comment]
> This could potentially be done by adding a new `optionsMustProceedArguments` field to the [`parserDirectives`](https://fig.io/docs/reference/subcommand#parserdirectives) object:

This would actually be useful for `deno` too - with `deno run [options] <file>`, options _must_ precede the file name. Can't think of another CLI right now but I'm sure there are plenty with this behaviour, especially script runners!

**Comment by fedeci** [comment]
I have just opened a PR internally to support it in the engine, will go live in the next update.
I have also already updated the types package, so if you rerun `npm install` in the autocomplete repo you should be able to add:
```js
parserDirectives: {
  optionsMustPrecedeArguments: true,
}
```

**Comment by mschrage** [comment]
Closing this issue since we've added support for specifying if options must precede arguments!
