### ISSUE TITLE
Populate environment variables

### ISSUE THREAD

**Issue by benzid-wael** [withfig/fig#741]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
Is there a way how to pass specific environment variables when running a script?

My main problem is that the command that I need to run to get suggestions requires `USER` or `SUDO_USER` environment variables, while none of them is passed to the shell when running the provided script

### Environment

```bash
Fig Version: Version 1.0.53 (B339) [Dev] [ABC]
UserShell: /usr/local/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/wbenzid/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/wbenzid/.asdf/shims:/usr/local/Cellar/asdf/0.8.1_1/libexec/bin:/Users/wbenzid/bin:/usr/local/bin:/Users/wbenzid/.zprofile:/Users/wbenzid/Library/Python/3.8/bin/:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/CPE/bin/FBSKSAgent.app/Contents/MacOS:/opt/homebrew/bin:/usr/local/munki:/Users/wbenzid/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/zsh/5.8_1/bin/zsh (49548) - /dev/ttys010
Current working directory: /Users/wbenzid/autocomplete
Current window identifier: 31059/% (com.googlecode.iterm2)
Path: /Users/wbenzid/.asdf/shims:/usr/local/opt/asdf/libexec/bin:/Users/wbenzid/bin:/usr/local/bin:/Users/wbenzid/.zprofile:/Users/wbenzid/Library/Python/3.8/bin/:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/opt/homebrew/bin:/usr/local/munki:/Users/wbenzid/.cargo/bin:/Users/wbenzid/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t1p0:39535FEB-3C62-4F8E-AEB4-3E7E91FBE052
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
```

**Comment by SeparateRecords** [comment]
At the moment there isn't a way to do this. You're correct - Fig spawns another shell and runs commands in that, so sadly it doesn't inherit the your environment variables. This would be very useful though!

Out of curiosity, what's the CLI you're trying to spec? Maybe we can come up with a workaround 🙂

---

This is a separate issue to #225 and #620, but they're all sort of circling around the same idea of "inheriting environment variables". Would it be good to create a single issue for it, or maybe close the other two in favor of this one?

**Comment by benzid-wael** [comment]
Unfortunately, it's a company internal CLI, which uses ssh and other tools underneath.

**Comment by SeparateRecords** [comment]
This is resolved now!
