### ISSUE TITLE
Fig not work with Terminal

### ISSUE THREAD

**Issue by xcetos** [withfig/fig#744]
### Description:
Fig does not work with the Terminal. The `fig doctor` indicates that everything is fine, but the status of fig debugger shows something wrong. To reproduce this issue, I keep a minimal `.zshrc` file, and the issue still happened.

![image](https://user-images.githubusercontent.com/45086830/147387770-3bcc9a76-cd17-4268-88bd-dd0ab432692b.png)

```sh
#### FIG ENV VARIABLES ####
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
#### END FIG ENV VARIABLES ####

eval "$(/opt/homebrew/bin/brew shellenv)"

#### FIG ENV VARIABLES ####
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.21C52|1.0.53|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.53 (B339) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jiezhu/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/jiezhu/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (3865) - /dev/ttys001
Current working directory: /Users/jiezhu
Current window identifier: 374/% (com.apple.Terminal)
Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/jiezhu/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=FD10086F-FB07-4948-9B1C-78EF533DFF0A
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @xcetos! It looks like you've turned on the 'only show on tab' setting. 

Does the autocomplete window appear when you press tab?

Could you also try disabling this setting by running `fig settings autocomplete.onlyShowOnTab false` and then restart the app.

**Comment by xcetos** [comment]
Thank you! It works well now! Sorry for bothering you.
