### ISSUE TITLE
Fig stops working after a few minutes

### ISSUE THREAD

**Issue by JTaurus19** [withfig/fig#745]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
I start Fig in a the iTerm session. It works good for a few minutes. Then Fig tips disappear until Fig re-lunch.

iTerm
MacBook Pro M1 Max

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.21C52|1.0.53|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.53 (B339) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/ivan/.pyenv/shims:/Users/ivan/.pyenv/bin:/opt/homebrew/bin:/usr/local/bin:/opt/homebrew/opt/openjdk@11/bin:/Users/ivan/.jenv/shims:/Users/ivan/.jenv/bin:/Users/ivan/.jenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/ivan/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (32715) - /dev/ttys001
Current working directory: /Users/ivan/projects/hobo/hobo-backend
Current window identifier: 3096/% (com.googlecode.iterm2)
Path: /Users/ivan/.pyenv/shims:/Users/ivan/.pyenv/bin:/opt/homebrew/bin:/usr/local/bin:/opt/homebrew/opt/openjdk@11/bin:/Users/ivan/.jenv/shims:/Users/ivan/.jenv/bin:/Users/ivan/.jenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/ivan/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:BE2D1D06-44A3-4160-A5BF-6E110728568D
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @JTaurus19! So sorry to hear that you're running into issues.

Can you run `fig doctor` next time that autocomplete stops appearing? This may give some additional insight into what's going on.

If that doesn't fix the issue, can you run `fig debug logs` in a separate terminal session and share a screen recording of the output while you type characters in the broken session.

**Comment by JTaurus19** [comment]
Thank you @mschrage 

`fig doctor` says that fig is not running in that case.

```
fig doctor

Let's make sure Fig is running...

✅ Fig bin exists
✅ Fig in PATH
❌ Fig is not running

I can fix this!
Running > fig launch


→ Launching Fig...


Fix applied!
Rerunning fig doctor to see if the problem is resolved.....
```
I will try to catch the bug with `fig debug logs` later.

**Comment by raldred** [comment]
This happens to me quite a bit, if I just open the tray menu, auto complete in terminals starts working again.

**Comment by mschrage** [comment]
@raldred if the Fig icon appears in the menu bar, then the app is still running so it seems like you’re running into a different issue!

Next time Fig stops working can you open a new terminal session and run `fig debug logs`?

Ideally, you could take a screen recording that includes both the logs and you typing some commands into the original terminal session!

**Comment by raldred** [comment]
Thanks, Sure thing. Ill make a separate issue when it happens again.

**Comment by JTaurus19** [comment]
I don't have more detailed logs but the issue is reproducible only if application icon is hidden in a menu bar.

**Comment by mschrage** [comment]
@JTaurus19 are you intentionally hiding the menu bar icon? Otherwise, this means that the app is crashing.

**Comment by mschrage** [comment]
Hmm thanks for letting me know. I will see if I can reproduce.
