### ISSUE TITLE
Not working properly when I have multiple terminals in VSCode

### ISSUE THREAD

**Issue by ayrtonbsouza** [withfig/fig#749]
### Description:
When I have two terminals open in VSCode and I type a command in the second instance of the terminal, when I select a suggestion from Fig and hit "Enter", the suggestion is filled in the first instance of the terminal instead of the second.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.0|Version 1.0.52 (B315)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B315) [Brazilian] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ayrtonsouza/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/ayrtonsouza/.zinit/polaris/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/ayrtonsouza/.fig/bin://Users/ayrtonsouza/go/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (14927) - /dev/ttys006
Current working directory: /Users/ayrtonsouza/Documents/sambatech/faber-castell-admin
Current window identifier: 1313/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @ayrtonbsouza! It looks like you aren't on the latest version of Fig. 

Try updating to v1.0.53 and let me know if you still experience this issue.

**Comment by ayrtonbsouza** [comment]
Hey, @mschrage. Just updated fig and now everything is working good. Thanks for the heads up. 👍
