### ISSUE TITLE
Issue with git index.lock 

### ISSUE THREAD

**Issue by ajsmth** [withfig/fig#75]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I regularly get this error when trying to run git operations: 
```
fatal: Unable to create 'my-project/path/.git/index.lock': File exists.
```

I don't have a good idea of what is going on, but I know turning fig off fixes the issue every time!

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.0.1|Version 1.0.41 (B206)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.41 (B206)
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/andy/.fig/bin/fig
Accessibility: true
Number of specs: 96
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/andy/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: false
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/andy/google-cloud-sdk/bin:/Users/andy/.yarn/bin:/Users/andy/.nvm/versions/node/v15.9.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/andy/.fig/bin:/Users/andy/Library/Android/sdk/emulator:/Users/andy/Library/Android/sdk/tools:/Users/andy/Library/Android/sdk/tools/bin:/Users/andy/Library/Android/sdk/platform-tools
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mattschrage** [comment]
Hey @ajsmth. Thanks for reporting. I haven't seen this one before. The `git` completion spec does run `git` commands in the background in order to provide suggestions for branches, remotes, etc. It's certainly possible that something is going wrong there. 

If you delete the file (`rm -f ./.git/index.lock`), does the warning return?

**Comment by ajsmth** [comment]
Hi! Yes it returns after removing - I suspect its running the create command twice or not checking if the file exists or something?

**Comment by mattschrage** [comment]
Does Fig show successfully show suggestions for git branches?

If not, maybe the `git` process is hanging. Does Fig still provide suggestions when you experience this issue?
<img width="590" alt="Screen Shot 2021-05-22 at 6 28 58 PM" src="https://user-images.githubusercontent.com/3155109/119245132-a6b80e00-bb2b-11eb-964e-c02ab0d07814.png">

**Comment by ajsmth** [comment]
it looks like the suggestions still work afterwards, and then the issue goes away? It's quite difficult to tell what is happening, sorry! but it definitely shows the prompt again after that warning shows up!

**Comment by ajsmth** [comment]
I've updated to the latest version and it seems to be gone - I'm not sure what happened but I'll close this as I think its clearly happening just on my end!

**Comment by mattschrage** [comment]
Another user has reported this so I am going to reopen the issue!

**Comment by fwesss** [comment]
Fixed with https://github.com/withfig/autocomplete/pull/410
