### ISSUE TITLE
Fig freezes

### ISSUE THREAD

**Issue by Loovemaker** [withfig/fig#752]
### Description:

Freezes just after running Fix.app or `fig launch`
With ~50% CPU used

![image](https://user-images.githubusercontent.com/24351107/148389810-b8bb8b45-48d2-4be1-933b-260f8a447934.png)

Seems related to external displays.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.21C52|1.0.53|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>
It looks like Fig is not running.
Try running: fig restart

</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Loovemaker! Can you open Activity Monitor and then click "Sample Process" and share the output here

<img width="926" alt="Screen Shot 2022-01-06 at 12 29 29 PM" src="https://user-images.githubusercontent.com/3155109/148447388-2d4c326b-eb2b-41cd-9957-59673d860951.png">

**Comment by Loovemaker** [comment]
Here is one sampled during Fig **still uses ~50% CPU,** which may be helpful. But I **can't see it freezing** any longer however.

[sample file](https://github.com/Loovemaker/public-storage/raw/master/“fig”的取样.txt)

**Comment by grant0417** [comment]
Seems like this should be fixed!
