### ISSUE TITLE
Fig does not start on system startup

### ISSUE THREAD

**Issue by teziovsky** [withfig/fig#753]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Like in the title of the issue, fig does not start on system startup. Also, the setting wrap-around doesn't work at a startup.

![Zrzut ekranu 2022-01-6 o 14 58 01](https://user-images.githubusercontent.com/36273653/148393898-e1406f38-a176-4519-8e20-29f92922a445.jpg)

![Zrzut ekranu 2022-01-6 o 14 55 16](https://user-images.githubusercontent.com/36273653/148393531-1b935e82-2438-4fd0-aea8-160e859cdec5.jpg)

![Zrzut ekranu 2022-01-6 o 14 56 39](https://user-images.githubusercontent.com/36273653/148393726-9149519d-e141-4e35-b35e-ac8ea23dc916.jpg)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.0|Version 1.0.53 (B339)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.53 (B339) [Polish] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/kuba/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (1610) - /dev/ttys003
Current working directory: /Users/kuba
Current window identifier: 245/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by teziovsky** [comment]
It's starting work when I manually restart the Fig from the status bar.

**Comment by mschrage** [comment]
This is should be working as of v1.0.54. ✨

You can update by running `fig update`
