### ISSUE TITLE
Support configuring the fig checkbox title

### ISSUE THREAD

**Issue by Tyriar** [withfig/fig#76]
**Is your feature request related to a problem? Please describe.**

The checkbox in the title `[x] fig - blah` is handy, but it's very verbose:

![](https://user-images.githubusercontent.com/2193314/118810949-4b52fb00-b861-11eb-9ebd-5eb23b68f71f.png)

**Describe the solution you'd like**

I'd like to be able to configure it, perhaps using some format similar to the `window.title` setting in VS Code:

```
"window.title": "${rootName}${separator}${activeEditorShort}${separator}${appName}"
```

I think ideally I would like to have only the checkbox, either as a prefix or a suffix to the actual title like `[x] bash`

**Comment by mattschrage** [comment]
Totally makes sense to give the user more flexibility here. The VS Code `window.title` API is a great model. I think this can make it into the next build!

In the meantime, you can turn this off entirely by running `fig settings autocomplete.addStatusToTerminalTitle false`.
