### ISSUE TITLE
Fig Autocomplete Not Showing

### ISSUE THREAD

**Issue by albertlai431** [withfig/fig#760]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hi! The fig autocomplete popup isn't showing up for me, even though `fig doctor` runs fine. For example, when I type `cd` or `git`, nothing shows up. Fig was working well maybe around a month ago so I'm a bit confused...

https://user-images.githubusercontent.com/44041989/148688653-bb9fe550-a533-4b94-aa81-6f3b02778024.mov

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.53|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.53 (B339) [Canadian English] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/albertlai/.nvm/versions/node/v16.13.0/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Racket v8.3/bin:/Users/albertlai/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (21705) - /dev/ttys005
Current working directory: /Users/albertlai
Current window identifier: 8983/% (com.apple.Terminal)
Path: /Users/albertlai/.nvm/versions/node/v16.13.0/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Racket v8.3/bin:/Users/albertlai/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=2ED669B1-FE87-4A45-B340-3EB086515B38
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @albertlai431!  Really appreciate the bug report. It sounds like #761 might be a similar issue.

Would you mind running `fig debug logs` in a separate terminal window and take a screen recording of the output while typing in the original terminal session?

Could you also just type `git ` and then take a screenshot of the debugger (which can by found by clicking on the Fig icon in the menu bar)?

Thanks so much!

**Comment by albertlai431** [comment]
Hey @mschrage! For some reason today, everything started working again! Would you still like me to take those screenshots & recordings?

**Comment by mschrage** [comment]
Hey @albertlai431! Glad to hear that everything is working - if it happens again can you please send over recordings, otherwise no worries!

**Comment by brendanfalk** [comment]
Hey @albertlai431 - next time this happens, could you please confirm if restarting fig instantly fixes it?

Our suspicion is this could be an internet related issue...

**Comment by albertlai431** [comment]
@brendanfalk restarting fig worked :)
