### ISSUE TITLE
Fig just stopped showing up

### ISSUE THREAD

**Issue by thecodingcrow** [withfig/fig#761]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig is running, fig is recognized as command, fig doctor didnt recognize an issue
Updating, restarting fig, restarting terminal, etc didnt solve the issue

See details below for more information

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1.21A559|1.0.53|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.53 (B339) [Austrian] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/thedoc/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/thedoc/.sdkman/candidates/java/current/bin:/opt/homebrew/Caskroom/miniconda/base/bin:/opt/homebrew/Caskroom/miniconda/base/condabin:/Users/thedoc/.nvm/versions/node/v16.13.0/bin:/Users/thedoc/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/thedoc/.fig/bin:/Users/thedoc/Library/Android/sdk/emulator:/Users/thedoc/Library/Android/sdk/tools:/Users/thedoc/Library/Android/sdk/tools/bin:/Users/thedoc/Library/Android/sdk/platform-tools
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (16509) - /dev/ttys003
Current working directory: /Users/thedoc/LC/mlm-base
Current window identifier: 775/% (com.apple.Terminal)
Path: /Users/thedoc/.sdkman/candidates/java/current/bin:/opt/homebrew/Caskroom/miniconda/base/bin:/opt/homebrew/Caskroom/miniconda/base/condabin:/Users/thedoc/.nvm/versions/node/v16.13.0/bin:/Users/thedoc/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/thedoc/.fig/bin:/Users/thedoc/Library/Android/sdk/emulator:/Users/thedoc/Library/Android/sdk/tools:/Users/thedoc/Library/Android/sdk/tools/bin:/Users/thedoc/Library/Android/sdk/platform-tools
Fig environment variables:
  - TERM_SESSION_ID=6DD4EA0E-6C67-4946-847D-4496F1E4D525
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @thecodingcrow! Thank you so much for reporting this.

Would you mind running `fig debug logs` in a separate terminal window and take a screen recording of the output while typing in the original terminal session?

**Comment by thecodingcrow** [comment]
Actually this issue I had was resolved by removing and reinstalling fig

BUT now its the case that fig doesnt respond to my enter key input

I can navigate up and down between suggestions but when hitting enter nothing happens, the suggestion does not get typed

I will attach the debug logs asap

**Comment by mschrage** [comment]
Are you free to jump on a debugging call right now? @thecodingcrow 

If you join the community Discord (https://fig.io/community), we can do some live debugging together!

**Comment by thecodingcrow** [comment]
> Are you free to jump on a debugging call right now? 

Actually yes, I just joined the discord

**Comment by mschrage** [comment]
Ping me there! (You'll need to leave an introduction before the server unlocks)

**Comment by thecodingcrow** [comment]
When I wanted to get the debug logs but all of a sudden fig works just as expected again. I will close this issue
