### ISSUE TITLE
When input text and autofill text are identical, enter should execute the command instead of selecting the autofill text

### ISSUE THREAD

**Issue by smfoote** [withfig/fig#762]
### Description:
When I type short commands, Fig is less important to me. For instance, `yarn start` is so ingrained in muscle memory that it's faster to just type the whole thing than to select a suggestion. However, when I type `yarn start` and hit enter, Fig interprets that "enter" as me wanting to select the option instead of allowing the shell to execute the command. I would expect when I type out a full command (i.e. the input text and the suggestion text are identical) and I hit enter, my intent is to execute the command.

I could be missing important cases where my expectation here is wrong, or maybe I changed a setting I shouldn't have. Please feel free to tell me I'm wrong :)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.1|Version 1.0.52 (B317)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B317) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/sfoote/.fig/bin/fig
Accessibility: true
Number of specs: 207
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/sfoote/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/sfoote/.volta/bin:/Users/sfoote/.yarn/bin:/Users/sfoote/.config/yarn/global/node_modules/.bin:/Users/sfoote/.gem/ruby/X.X.0/bin:/Users/sfoote/.rbenv/shims:/usr/local/linkedin/bin:/usr/local/git/bin:/Users/sfoote/.nvm/versions/node/v10.13.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/export/content/linkedin/bin:/export/content/granular/bin:/Users/sfoote/.fig/bin:/Users/sfoote/Library/Android/sdk/platform-tools:/Users/sfoote/Library/Android/sdk/tools:/Users/sfoote/.rvm/bin:/export/content/linkedin/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (48004) - /dev/ttys030
Current working directory: /Users/sfoote/segments/spectrum-web_trunk/spectrum-web-fe
Current window identifier: 18817/% (co.zeit.hyper)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @smfoote! This sounds like a bug or maybe an issue with latency depending on how fast you type. When the suggestion matches the text that is already in the terminal, the icon will change to a red arrow and pressing enter should execute the command immediately.

<img width="478" alt="Screen Shot 2022-01-10 at 3 13 28 PM" src="https://user-images.githubusercontent.com/3155109/148853439-03314ada-1d61-4f19-8962-a2df5c71f9be.png">

Can you run `fig settings autocomplete.keybindings.enter` and share the output here?

Also if this is reproducible for you, would you mind sharing a screen recording of the behavior? Thanks so much :)

**Comment by smfoote** [comment]
Here is my output from `fig settings autocomplete.keybindings.enter`:

```
No value associated with 'autocomplete.keybindings.enter'.
<nil>
```
Here is a screen recording. As you can see, the icon changes to a red arrow. I press enter and the suggestion box disappears. Then, I press enter again and the command executes.

https://user-images.githubusercontent.com/452458/148946682-4deb92a1-0bad-4d41-8e89-7a056ac9d7aa.mov

**Comment by mschrage** [comment]
@smfoote would you mind sharing your zshrc file?

Also it looks like you aren’t using the latest version of Fig — try updating and see if that resolves the issue!

**Comment by smfoote** [comment]
I've updated Fig and the problem appears to be resolved. Thanks!
