### ISSUE TITLE
Toggle to select verbose flag when given an option.

### ISSUE THREAD

**Issue by Shy** [withfig/fig#765]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
> When given a flag that has multiple ways of being triggered, I would like fig to utilize the verbose version when selected. 

For example with docker you could use -a or --attach. Currently it selects -a, but I would prefer to utilize the longer --attach. 

![Screen Shot 2022-01-11 at 1 38 22 PM](https://user-images.githubusercontent.com/1316340/149002563-c7b71b29-dd56-48ce-9d83-2c23b5186b9c.png)

Similar example with git. 
![Screen Shot 2022-01-11 at 1 45 12 PM](https://user-images.githubusercontent.com/1316340/149002810-45fa1cb7-dda5-4629-a167-611143131121.png)

For context I do a lot of coding video creation. For viewers seeing the verbose flag is clearer than a single letter flag.

**Comment by fedeci** [comment]
@mschrage should I work on this?

**Comment by mschrage** [comment]
Yeah that would be great @fedeci

**Comment by fedeci** [comment]
Exactly, but I would always keep the short option as first in the specs

**Comment by mschrage** [comment]
This is available as of v1.0.55 (`autocomplete.preferVerboseSuggestions`).
