### ISSUE TITLE
FIG paste command in different window

### ISSUE THREAD

**Issue by hstemplewski** [withfig/fig#768]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When I spit screen in terminal (CMD+D) FIG completes only in most recently opened after I hit `enter` it paste completion in another window. The workaround is to restart FIG after changing the main focused window. 

https://user-images.githubusercontent.com/25898331/149127686-94ce5473-dbae-4dcc-ab21-0d5486c63017.mov

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.0|Version 1.0.52 (B317)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B317) [Polish] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/username/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: true
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/username/.nvm/versions/node/v16.13.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/username/.fig/bin:/Users/username/Library/Android/sdk/emulator:/Users/username/Library/Android/sdk/tools:/Users/username/Library/Android/sdk/tools/bin:/Users/username/Library/Android/sdk/platform-tools
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /Users/username/.nvm/versions/node/v16.13.0/bin/node (92247) - /dev/ttys016
Current working directory: /Users/username/Documents/someProject
Current window identifier: 49293/% (co.zeit.hyper)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @hstemplewski! This bug should be fixed if you update to the latest version of Fig. 

Try running `fig update` or click on the Fig icon in the menubar and then "Check for updates...".

I'm going to close this for now but I will reopen if the issue persists once you've updated to v1.0.53.

**Comment by hstemplewski** [comment]
Yes it's fixed tanks @mschrage 🎉
