### ISSUE TITLE
Installed Fig, but suddenly not working anymore.

### ISSUE THREAD

**Issue by TofuTseng** [withfig/fig#769]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7.19H1217|1.0.53|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.53 (B339) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/cengfujun/Desktop/google-cloud-sdk/bin:/Users/cengfujun/.nvm/versions/node/v14.15.4/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/cengfujun/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (4140) - /dev/ttys002
Current working directory: /Users/cengfujun/Desktop
Current window identifier: 263/% (com.googlecode.iterm2)
Path: /Users/cengfujun/Desktop/google-cloud-sdk/bin:/Users/cengfujun/.nvm/versions/node/v14.15.4/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/cengfujun/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:3FB67A93-01B8-43CF-86BC-E8BC6F4CD76B
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @TofuTseng @dev-olly! I'm sorry you're running into issues.

Can you follow these steps for me?
1. Run `fig debug debug-mode on`
2. Control+click the red popup window and press "Inspect Elements"
<img width="410" alt="Screen Shot 2022-01-13 at 10 22 43 AM" src="https://user-images.githubusercontent.com/3155109/149387336-7c46ce61-4b2b-4b96-8769-c8febe414b84.png">

3. Take a screenshot of the Console tab
<img width="1112" alt="Screen Shot 2022-01-13 at 10 23 19 AM" src="https://user-images.githubusercontent.com/3155109/149387421-b023bdde-7406-4a58-848d-58d259cadb40.png">

**Comment by TofuTseng** [comment]
Sorry, it work fine again today, after I restart my mac this morning.
But I still don't know why fig suddenly not working, or triggered by some reason or bad operation.
If it happens again, I will try the method provided by @mschrage, and report it in a new issue.
Thank you for reply immediately.


Here is my operation below
https://user-images.githubusercontent.com/75705724/149430210-b52b387e-ee5f-40b1-8a27-9bce0ecfb57a.mp4

**Comment by mschrage** [comment]
We push a bug this morning that caused the autocomplete engine to crash on older versions of macOS. #773 

@fedeci released a fix a few hours later, so that is why everything is working now :)
