### ISSUE TITLE
Popover regularly showing on-screen when it has nothing to show

### ISSUE THREAD

**Issue by orta** [withfig/fig#77]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

https://user-images.githubusercontent.com/49038/118976571-116f1b00-b96d-11eb-9169-89653cce09fc.mov

I end up turning it off after this for a while

### Details:
|macOS|Fig|Shell|
|----|----|----|
|10.15.7|Version 1.0.41 (B206)|/bin/zsh|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.41 (B206)
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ortatherox/.fig/bin/fig
Accessibility: true
Number of specs: 99
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/ortatherox/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/ortatherox/.rbenv/shims:/Users/ortatherox/.nvm/versions/node/v14.5.0/bin:/Users/ortatherox/.gem/bin:/Users/ortatherox/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/ortatherox/.fig/bin:/Users/ortatherox/dev/js/depot_tools:/Users/ortatherox/.deno/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mattschrage** [comment]
Hey @orta! Thanks for reporting this. Do you have "Debug Mode" enabled? I think turning this off should fix the issue. 

<img width="517" alt="Screen Shot 2021-05-21 at 11 23 36 AM" src="https://user-images.githubusercontent.com/3155109/119181976-31fbab80-ba27-11eb-8195-62a8ec466e54.png">

**Comment by falky97** [comment]
@orta alternatively if debug mode is not on, does restarting Fig fix this?

**Comment by brendanfalk** [comment]
@orta Closing this issue as we haven't heard from you in a while and I am almost 99% certain you had "Debug Mode" on, now renamed "Force Popup to Appear"

**Comment by orta** [comment]
Oops! That makes sense
