### ISSUE TITLE
[visual-glitch] Prompt overlay

### ISSUE THREAD

**Issue by manutero** [withfig/fig#770]
### Description:

A video worth thousand words:

https://user-images.githubusercontent.com/2211052/149289712-8a0d87e0-33b6-4800-8ef8-a6ec88486133.mov

In the video we can chek:

1. `fig doctor` tells that everything is fine :)
2. we may check that fig is overlay my prompt

Is it possible to fix this visual overlay?

If helpful, this is my theme (I use zsh - oh-my-zsh to be specific) 

```bash
# af-magic.zsh-theme
# Repo: https://github.com/andyfleming/oh-my-zsh
# Direct Link: https://github.com/andyfleming/oh-my-zsh/blob/master/themes/af-magic.zsh-theme

function git_current_repo() {
    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
        return
    fi
    basename $(git rev-parse --show-toplevel)
}

if [ $UID -eq 0 ]; then NCOLOR="red"; else NCOLOR="green"; fi
local return_code="%(?..%{$fg[red]%}%? ↵%{$reset_color%})"

# primary prompt
PROMPT='
$FG[237]--------------------           %~%{$reset_color%}
$FG[032]$(git_current_repo)\
$(git_prompt_info) \
$FG[105]%(!.#.$»)%{$reset_color%} '
# PROMPT2='%{$fg[red]%}\ %{$reset_color%}'
RPS1='${return_code}'

# color vars
eval my_gray='$FG[237]'
eval my_orange='$FG[214]'

# right prompt
# if type "virtualenv_prompt_info" > /dev/null
# then
# 	RPROMPT='$(virtualenv_prompt_info)$my_gray%~%{$reset_color%}%'
# else
# 	RPROMPT='$my_gray%~%{$reset_color%}%'
# fi

# git settings
ZSH_THEME_GIT_PROMPT_PREFIX="$FG[075]($FG[078]"
ZSH_THEME_GIT_PROMPT_CLEAN=""
ZSH_THEME_GIT_PROMPT_DIRTY="$my_orange*%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="$FG[075])%{$reset_color%}"
```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.1.20G224|1.0.53|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.53 (B339) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/cx01885/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/sbin:/Users/cx01885/.nvm/versions/node/v14.18.2/bin:/Users/cx01885/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/cx01885/.fig/bin:/Users/cx01885/workspace/go/bin:/usr/local/opt/go/libexec/bin:/Users/cx01885/Workspace/vpnbridge
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (33155) - /dev/ttys003
Current working directory: /Users/cx01885/Workspace
Current window identifier: 9158/% (com.googlecode.iterm2)
Path: /usr/local/sbin:/Users/cx01885/.nvm/versions/node/v14.18.2/bin:/Users/cx01885/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/cx01885/.fig/bin:/Users/cx01885/workspace/go/bin:/usr/local/opt/go/libexec/bin:/Users/cx01885/Workspace/vpnbridge
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:2A483D17-5874-498F-AEC2-BC21161D73B1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by manutero** [comment]
Extra: this is what I see when moving to a folder:

![Captura de pantalla 2022-01-13 a las 9 20 30](https://user-images.githubusercontent.com/2211052/149292482-67236c89-ce0b-4a34-b349-bda679f1f269.png)

**Comment by mschrage** [comment]
Thanks for reporting! There is a known compatibility issue with at-magic that will be fixed in the next release.

See #739 for a temporary fix.

**Comment by manutero** [comment]
Just want to say that, `v1.0.54` does fix this and now works like a charm with `af-magic` 👍 👍 👍
