### ISSUE TITLE
ls -ll cannot be fired immediately

### ISSUE THREAD

**Issue by Bringoff** [withfig/fig#771]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:

I'm used to running `ls -ll` if I want to check a dir I'm in right now. But at the moment I can't type this exact command and run it with Enter, because Fig doesn't have it as an immediate action. It suggests `ls -ll@` first. So I need to press Enter two times to run `ls -ll@` or press Esc first and then Enter to get rig of Fig popup first.

![image](https://user-images.githubusercontent.com/5401536/149312259-c3bbc7b3-4951-4887-a6df-663a09a14d64.png)

### Environment

```bash
Fig Version: Version 1.0.53 (B339) [U.S.]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/artemkalachyan/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/artemkalachyan/.gem/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/artemkalachyan/.fig/bin:/Users/artemkalachyan/.pub-cache/bin:/Users/artemkalachyan/Library/Android/sdk/platform-tools:/Users/artemkalachyan/fvm/versions/stable/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (4587) - /dev/ttys002
Current working directory: /Users/artemkalachyan/Developer/.../.git/hooks
Current window identifier: 4189/% (com.googlecode.iterm2)
Path: /Users/artemkalachyan/.gem/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/artemkalachyan/.fig/bin:/Users/artemkalachyan/.pub-cache/bin:/Users/artemkalachyan/Library/Android/sdk/platform-tools:/Users/artemkalachyan/fvm/versions/stable/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:47EBC287-C7A6-4990-8171-0228076B285A
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
```

**Comment by mschrage** [comment]
Hey @Bringoff. Thanks for letting us know.

What exactly do you expect `ls -ll` to do? As far as I can tell, this is not a valid set of options for `ls`. You're just doubling up the `-l` flag, which has no effect. You could also type `ls -lllll` and the output of `ls` would remain the same!

The autocomplete-engine doesn't understand what you're trying to do here, so it does not provide an immediate insert suggestion. Perhaps we could change this behavior? cc @sullivan-sean

**Comment by Bringoff** [comment]
@mschrage sorry, forgot to mention the main thing 🙂 I have a function declared in my `.zprofile`:
```
function ls() {
  case $2 in
    -ll* ) echo "gotcha\n"; command ls -AFgoh ;;
    * ) command ls "$@" ;;
  esac
}
```

**Comment by mschrage** [comment]
Ah that makes more sense. Fig doesn't attempt to parse shell functions when providing autocomplete, so from the perspective of the autocomplete engine, `-ll` is just an invalid flag.

I think a workaround here could be to create a ["mixin"](https://fig.io/docs/guides/personal-mixins) for the `ls` command that adds `-ll` as a suggestion.

```
const completionSpec: Fig.Spec = {
  name: "git",
  additionalSuggestions: [
      {
      name: "-ll",
      description: "Custom flag added via function to ls",
      type: "shortcut"
    }
 ]
}

export default completionSpec;
```

Check out [this guide](https://fig.io/docs/guides/personal-mixins) for more details on how to get started!

**Comment by mschrage** [comment]
I'm going to close this issue for now. 

But please let me know if the mixin approach doesn't work for you or if you have trouble getting it set up.

**Comment by Bringoff** [comment]
@mschrage well, it almost works 🙂 Now I see the suggestion, but it does not run on enter. It just inserts `-ll`, and I cannot run it immediately, because suggestion with `-ll@` pops up

**Comment by sullivan-sean** [comment]
If you always execute the command with the `-ll` flag (and don't add any other options afterwards) you could set the `insertValue` for the `additionalSuggestion` to be `-ll\n` instead of the default `-ll`, i.e. change Matt's snippet above to 

```
const completionSpec: Fig.Spec = {
  name: "git",
  additionalSuggestions: [
      {
      name: "-ll",
      description: "Custom flag added via function to ls",
      type: "shortcut",
      insertValue: "-ll\n"
    }
 ]
```

This would make sure the command is run on enter instead of just being inserted.
