### ISSUE TITLE
Dark mode issue

### ISSUE THREAD

**Issue by magidmroueh** [withfig/fig#772]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
Theme set to dark but autocomplete shows light mode colors.
![image](https://user-images.githubusercontent.com/1893444/149368207-095bf180-6c40-48e6-8183-39560fede7dc.png)

**Comment by mschrage** [comment]
Hey @magidmroueh! Thanks for reporting this. Can you run `fig settings autocomplete.theme` in your terminal and share the output here?

**Comment by magidmroueh** [comment]
> fig settings autocomplete.theme

![image](https://user-images.githubusercontent.com/1893444/149388690-e397cc00-3d8e-453c-ac62-675e33b14d5a.png)

**Comment by fedeci** [comment]
I have B340 and everything is working fine @mschrage, have we fixed something between the two versions?

**Comment by fedeci** [comment]
🤔

**Comment by magidmroueh** [comment]
wouldn't setting it to default to system or terminal settings be better?

**Comment by magidmroueh** [comment]
> We figured it out! `Settings.current()` doesn't return anything on older versions of Fig. The fix will be to default to dark mode rather than light mode.

wouldn't the default to system or terminal setting be a better option here?

**Comment by fedeci** [comment]
It is currently set tot the system theme, do you have light system theme?

**Comment by magidmroueh** [comment]
> It is currently set tot the system theme, do you have dark system theme?

yes

**Comment by fedeci** [comment]
On which version of macOS are you on?

**Comment by fedeci** [comment]
I don't think B339 is an old version that still has that caveat. I wonder if he is using an old macOS version and is related to this issue https://github.com/withfig/fig/issues/773

**Comment by magidmroueh** [comment]
> I don't think B339 is an old version that still has that caveat. I wonder if he is using an old macOS version and this is related to #773

Latest macos Monterey 12.1
and the Fig app also is latest version, I tried to update it.

**Comment by fedeci** [comment]
🤔 Can you check if the new Fig `system` theme is working correctly in the latest beta version?
`fig update && fig theme system`

**Comment by grant0417** [comment]
This should be fixed on stable now
