### ISSUE TITLE
Autocomplete window is no longer working

### ISSUE THREAD

**Issue by scottwestover** [withfig/fig#773]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig autocomplete window is no longer working in iTerm or in terminal. When I try use the `cd` or `git` commands, the popup no longer appears. Fig was working fine earlier today, and all of sudden stopped working. I tried restarting Fig and the terminal, and I tried doing a fresh install, but get the same issue.

This might be related to https://github.com/withfig/fig/issues/769.

![example](https://user-images.githubusercontent.com/9931822/149394660-4e27c1b6-cdaf-4402-988e-9f3176841ddf.gif)

I enabled the debug mode, and here is a screenshot of the console output:

<img width="993" alt="Screen Shot 2022-01-13 at 2 16 42 PM" src="https://user-images.githubusercontent.com/9931822/149394936-b17a3f16-dcc7-46d3-8ccb-0070de79cf69.png">

<img width="687" alt="Screen Shot 2022-01-13 at 2 16 06 PM" src="https://user-images.githubusercontent.com/9931822/149394932-fa6b20e1-dd19-4485-bf0b-34eb444907c0.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.14.6.18G9323|1.0.53|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.53 (B339) [Debug] [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/swestover/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: bash (34139) - /dev/ttys002
Current working directory: /Users/swestover/Documents/maven
Current window identifier: 68313/% (com.googlecode.iterm2)
Path: /Users/swestover/.volta/bin:/Users/swestover/.poetry/bin:/Users/swestover/.pyenv/shims:/sbin:/Users/swestover/.platformsh/bin:/Users/swestover/go/bin:/Users/swestover/anaconda/bin:/Users/swestover/.platformsh/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/swestover/.fig/bin:/usr/local/opt/go/libexec/bin:/Users/swestover/Documents:/Users/swestover:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono:/Users/swestover/Downloads/butler
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:92616CD0-CF59-4863-B2D8-9C251E3D4C16
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM_VERSION=3
  - FIG_TERM=1
</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @scottwestover! Thank you so much for reporting this.

Are you free to jump on a debugging call https://calendly.com/mschrage/30min ?

**Comment by mschrage** [comment]
Also we just pushed a tentative fix live. Can you press command+r in the Web Inspector and share the output with me?

**Comment by scottwestover** [comment]
@mschrage Here is the latest output:

<img width="1438" alt="Screen Shot 2022-01-13 at 3 08 38 PM" src="https://user-images.githubusercontent.com/9931822/149401842-10ba60c3-efed-489b-9939-ef9998d609a6.png">


<details>
  <summary>Copied output from console</summary>
  
```
[Log] [fig] declaring constants... (user-script:1, line 39)
[Info] Successfuly preconnected to https://cdn.skypack.dev/@withfig/autocomplete/specs/
[Log] [fig] setting up event listeners... (vendor.524ec2bd.js, line 27)
[Log] [fig] unsubscribing any existing notifications... (vendor.524ec2bd.js, line 27)
[Log] Setting Skypack URL to  – "https://unpkg.com/@withfig/autocomplete@^2.0.0/build/" (index.072dc9fd.js, line 1)
[Log] About to run the following command defaults read com.mschrage.fig access_token – {options: undefined} (index.072dc9fd.js, line 1)
[Log] {suggestions: [], interceptKeystrokes: false} (index.072dc9fd.js, line 1)
[Log] There was an error parsing the theme. Using default system theme (index.072dc9fd.js, line 1)
[Log] applying update: setFuzzySearchEnabled (index.072dc9fd.js, line 1)
[Log] {tokens: undefined} (index.072dc9fd.js, line 1)
[Log] About to run the following command defaults read com.mschrage.fig access_token – {options: undefined} (index.072dc9fd.js, line 1)
[Error] TypeError: t.addEventListener is not a function. (In 't.addEventListener("change",e)', 't.addEventListener' is undefined) — index.072dc9fd.js:1:72375
	Ni (vendor.524ec2bd.js:27:82902)
	callback (vendor.524ec2bd.js:27:85021)
	Eg (vendor.524ec2bd.js:27:49163)
	Yi (vendor.524ec2bd.js:27:86757)
	dk (vendor.524ec2bd.js:27:102913)
	dk
	unstable_runWithPriority (vendor.524ec2bd.js:18:3780)
	Uj (vendor.524ec2bd.js:27:99693)
	Lj (vendor.524ec2bd.js:27:95738)
	Lj
	(anonymous function) (vendor.524ec2bd.js:27:45670)
	unstable_runWithPriority (vendor.524ec2bd.js:18:3780)
	jg (vendor.524ec2bd.js:27:45616)
	ig (vendor.524ec2bd.js:27:45551)
	fk (vendor.524ec2bd.js:27:104633)
	unstable_runWithPriority (vendor.524ec2bd.js:18:3780)
	(anonymous function) (vendor.524ec2bd.js:27:103827)
	L (vendor.524ec2bd.js:18:2840)
	onmessage (vendor.524ec2bd.js:18:1563)
[Log] applying update: error (index.072dc9fd.js, line 1)
[Warning] Error: Invalid token array — index.072dc9fd.js:1:33469 (index.072dc9fd.js, line 1)
[Log] {tokens: undefined} (index.072dc9fd.js, line 1)
[Error] TypeError: t.addEventListener is not a function. (In 't.addEventListener("change",e)', 't.addEventListener' is undefined) — index.072dc9fd.js:1:72375
	Z (index.072dc9fd.js:1:4237)
	onerror (index.072dc9fd.js:1:80861)
[Error] TypeError: t.addEventListener is not a function. (In 't.addEventListener("change",e)', 't.addEventListener' is undefined)
	onmessage (vendor.524ec2bd.js:18:1640)
[Error] Unhandled Promise Rejection: Error: No key provided with request
	(anonymous function) (vendor.524ec2bd.js:27:309942)
	promiseReactionJob
[Error] Unhandled Promise Rejection: Error: Could not find cursor rect
	(anonymous function)
	rejectPromise
	promiseReactionJob
[Log] Loaded specs – {result: Set} (index.072dc9fd.js, line 1)
{result: Set}Object
[Error] SyntaxError: Unexpected token '.' — fig.js:5
	(anonymous function) (index.072dc9fd.js:1:81604)
	promiseReactionJob
[Log] About to run the following command bash -lic 'compgen -c' – {options: {pipelined: true, backgroundJob: false}} (index.072dc9fd.js, line 1)
[Error] SyntaxError: Unexpected token '?' — npm.js:1
	(anonymous function) (index.072dc9fd.js:1:81604)
	promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 404 () (artisan.js, line 0)
[Error] TypeError: Importing a module script failed.
	(anonymous function) (index.072dc9fd.js:1:81604)
	promiseReactionJob
[Error] SyntaxError: Unexpected token '?' — yarn.js:1
	(anonymous function) (index.072dc9fd.js:1:81604)
	promiseReactionJob
[Log] Got fig history – {entries: Array, historyValueIndex: Object, time: 1184} (index.072dc9fd.js, line 1)
{entries: Array, historyValueIndex: Object, time: 1184}Object
[Log] About to run the following command zsh -lic 'fc -R; fc -ln 1' – {options: {pipelined: true, backgroundJob: false}} (index.072dc9fd.js, line 1)
[Log] Could not determine exit code of pipelined command: bash -lic 'compgen -c' (index.072dc9fd.js, line 1)
[Log] Could not determine exit code of pipelined command: zsh -lic 'fc -R; fc -ln 1' (index.072dc9fd.js, line 1)
[Log] Got history entries – {entries: [{text: "", commands: [], context: {}}], historyValueIndex: {}, key: "zsh", …} (index.072dc9fd.js, line 1)
{entries: [{text: "", commands: [], context: {}}], historyValueIndex: {}, key: "zsh", time: 0}Object
[Log] About to run the following command bash -lic 'fc -ln 1' – {options: {pipelined: true, backgroundJob: false}} (index.072dc9fd.js, line 1)
[Error] Failed to load resource: the server responded with a status of 404 () (autocomplete, line 0)
[Error] SyntaxError: The string did not match the expected pattern. — index.072dc9fd.js:1:78341
	Z (index.072dc9fd.js:1:4237)
	promiseReactionJob
[Log] Could not determine exit code of pipelined command: bash -lic 'fc -ln 1' (index.072dc9fd.js, line 1)
[Log] Got history entries – {entries: [{text: "", commands: [], context: {}}], historyValueIndex: {}, key: "bash", …} (index.072dc9fd.js, line 1)
{entries: [{text: "", commands: [], context: {}}], historyValueIndex: {}, key: "bash", time: 0}Object
[Log] About to run the following command fish -lic 'history search' – {options: {pipelined: true, backgroundJob: false}} (index.072dc9fd.js, line 1)
[Log] Could not determine exit code of pipelined command: fish -lic 'history search' (index.072dc9fd.js, line 1)
[Log] Got history entries – {entries: [{text: "", commands: [], context: {}}], historyValueIndex: {}, key: "fish", …} (index.072dc9fd.js, line 1)
{entries: [{text: "", commands: [], context: {}}], historyValueIndex: {}, key: "fish", time: 0}Object
```
</details>

Yes, I would be able to join a debugging call. Let me take a look at your available times and see when I can join.

**Comment by fedeci** [comment]
Can you try another command+r to see if the event listener error is gone?

**Comment by scottwestover** [comment]
@fedeci Yes the error is gone and the autocomplete window is showing and working for me again.

**Comment by fedeci** [comment]
Great!
