### ISSUE TITLE
Better keybinding documentation

### ISSUE THREAD

**Issue by sullivan-sean** [withfig/fig#775]
We have pretty solid documentation for most settings at https://fig.io/docs/support/settings but the options that are available for keybindings are not clear. We should probably
1. Document the keybinding options that are supported for the autocomplete app on the website
2. Offer autocompletion for keybindings (e.g. suggest actions for `fig settings autocomplete.keybindings.tab ___`)

**Comment by mschrage** [comment]
We've made significant improvements to the discoverability and in-app documentation around the different keybindings.

<img width="942" alt="Screen Shot 2022-03-11 at 11 46 34 AM" src="https://user-images.githubusercontent.com/3155109/157947772-d47d79ea-b01d-4c5e-84a0-bbb0fc9f46d1.png">
