### ISSUE TITLE
Allow uninstall without registration

### ISSUE THREAD

**Issue by RoddeRodRod** [withfig/fig#777]
### Description:
The recommended way to uninstall fig is not possible, when the user has not entered his mail adress.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.53 (B339)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.53 (B339) [German] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jwessels/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Fixed!
