### ISSUE TITLE
Autocomplete suggestions never finish loading [unpkg]

### ISSUE THREAD

**Issue by cartfisk** [withfig/fig#779]
### Description:
Autocomplete list never populates.

https://user-images.githubusercontent.com/8764375/149586610-32dd56b6-5346-4230-9ac1-572a93b17abd.mov

<img width="592" alt="Screen Shot 2022-01-14 at 3 18 28 PM" src="https://user-images.githubusercontent.com/8764375/149586617-934e772f-780a-4bce-811a-4bb192812484.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.53 (B339)|/usr/local/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.53 (B339) [U.S.] 
UserShell: /usr/local/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/carterkonz/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /var/folders/mt/4v2p3kn1569_tg7gkc4nm6gh0000gn/T/fnm_multishells/3831_1642194816670/bin:/usr/local/opt/openssl/bin:/usr/local/opt/mariadb@10.3/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/bin:/usr/local/sbin:/Users/carterkonz/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin:/Users/carterkonz/.fig/bin:/Users/carterkonz/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zpm-zsh-SLASH-colorize/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by brendanfalk** [comment]
Yes, fully aware of this issue. Not your fault, appears to be an error with our CDN: https://twitter.com/fig/status/1482095684970946560

**Comment by cartfisk** [comment]
Got it. I encountered this just after initial setup on this machine so I assumed it was related to my configuration.
Thanks for the update.

**Comment by mschrage** [comment]
As @brendanfalk mentioned, Fig was not working earlier in the day due to latency and internal server errors from [unpkg](https://mobile.twitter.com/search?q=unpkg&src=typed_query&f=live).

We have switched to a different CDN provider. **Restarting the Fig app should resolve this issues.**

<img width="267" alt="Screen Shot 2022-01-14 at 2 29 59 PM" src="https://user-images.githubusercontent.com/3155109/149593646-12ebdccb-e72c-42c8-863b-40c564bec89e.png">

Please let us know if you are still experiencing issues loading completions.
