### ISSUE TITLE
Enter to choose the autocomplete from pop does not work , i have to restart the app for it to work again 

### ISSUE THREAD

**Issue by avsavani** [withfig/fig#782]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.52 (B326)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B326) [Dev] [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ashish/.fig/bin/fig
Accessibility: true
Number of specs: 209
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/ashish/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/ashish/google-cloud-sdk/bin:/Users/ashish/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ashish/Downloads/:/usr/local/go/bin:/opt/X11/bin:/Library/Apple/usr/bin:/opt/ImageMagick/bin:/Users/ashish/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 783/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
This is resolved as of v1.0.54. See #428 for more details and a temporary workaround.
