### ISSUE TITLE
Fig causing high CPU usage

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#786]
We will use the canonical issue for CPU related issues. Some users have been facing them, however, we have no observability or ability to reproduce

**If you use Fig and see it causes high CPU** 
Please comment:
* a screenshot of activity monitor
* the output of `fig diagnostic` below
* your computer specs
* any reproducible steps

We have some hypotheses as to how to fix it:
1. Try restarting Fig entirely - `fig restart`
2. Try reloading the autocomplete app - right click the window and hit "reload"

**Comment by brendanfalk** [comment]
This will hopefully be fixed in fig's next build (v1.0.55) when we replace our pseudoterminal code with rust

**Comment by SeparateRecords** [comment]
> Caused massive slowdowns while working in VS Code, activity monitor showing 35%+ CPU usage.

Seems like there's still a bug with this.

**Comment by grant0417** [comment]
No more placeholders!
