### ISSUE TITLE
Aliases not being recognised by Fig

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#792]
Users have aliases defined like `alias gcd=git checkout develop`.

Fig should be picking up aliases (we have worked hard over the past several months to make sure we do). e.g. if someone had `alias g=git` in their dotfiles and then typed `g[space]`, Fig should offer suggestions as if the user had typed `git[space]`.

However, sometimes Fig is not capturing the fact that you have aliases. We either don't offer suggestions at all or we do but they are the wrong suggestions...

Some reason this could happen 
* When sourcing your dotfiles there is an error meaning Fig sources them they fail and we presume there are no aliases
* When sourcing your dotfiles there is a hanging process like heroku or ohmyzsh asking to upgrade!
* A timing error on Fig's end

**Temporary Fix**
Restarting Fig (`fig quit; fig launch`) usually fixes this issue. If not, please comment your bashrc/zshrc and any other relevant dotfiles so we can investigate and fix!

**Comment by paulrostorp** [comment]
@brendanfalk Just discovered fig and loving it ! The suggested workaround doesn't work for me for my `kubectl` alias

I am using zsh with iterm2 on macOS. Autocompletion might be interfering, this is my config related to `kubectl` and my `k` alias. From my `.zshrc` file:
```sh
source <(kubectl completion zsh)
alias k=kubectl
compdef __start_kubectl k
```

**Comment by brendanfalk** [comment]
@paulrostorp Glad it's working now. We just pushed a fix. Am going to close this issue but will re-open if this is still occuring.

**Comment by mwvd** [comment]
I'm also still having the same issue for aliases configured in my `.zshrc`

Running `fig restart` doesn't seem to fix it for me, but `fig quit; fig launch` _does_ fix it. Not sure why that might be the case
