### ISSUE TITLE
Fig directory misconfigured

### ISSUE THREAD

**Issue by enbee81** [withfig/fig#80]
### Description:
I get the "Fig directory misconfigured" error. Running the command `~/.fig/tools/install_and_upgrade.sh` does not help either. There is no folder named "tools".  I only have folders named `bin` and `users`. 

### Details:
|macOS|Fig|Shell|
|----|----|----|
|11.3.1|Version 1.0.42 (B207)|/bin/sh|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.42 (B207) 
UserShell: /bin/sh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/nilsbinder/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: true
Tmux Integration: false
Keybindings path: /Users/nilsbinder/.fig/user/keybindings
iTerm Integration: false
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: false
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by yogevyuval** [comment]
Same here

**Comment by yogevyuval** [comment]
@enbee81 Run `fig update` and then `source ~/.fig/tools/install_and_upgrade.sh `.

**Comment by mattschrage** [comment]
@enbee81 did this resolve the issue for you?

If not try running, `fig util:install-script`.

**Comment by enbee81** [comment]
Yep. Everything works perfect right now.
