### ISSUE TITLE
Autocomplete window stays visible after executing command

### ISSUE THREAD

**Issue by jonas-zebari** [withfig/fig#800]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

This is more apparent for commands that wouldn't necessarily complete immediately. In the video I am trying to `git pull` and the autocomplete window jumps to the bottom left (where the cursor is) until the pull is completed.

https://user-images.githubusercontent.com/38041304/150162280-b50cdee2-a13d-40bf-bd5a-f3a9cb8b2071.mov

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.54 (B359)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.54 (B359) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jonaszebari/.fig/bin/fig
Accessibility: true
SSH Integration: true
Tmux Integration: true
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/jonaszebari/.rvm/gems/ruby-2.6.5/bin:/Users/jonaszebari/.rvm/gems/ruby-2.6.5@global/bin:/Users/jonaszebari/.rvm/rubies/ruby-2.6.5/bin:/Users/jonaszebari/.nvm/versions/node/v12.22.1/bin:/usr/local/opt/ruby/bin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/jonaszebari/.fig/bin:/Users/jonaszebari/fvm/default/bin:/Users/jonaszebari/.rvm/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (6015) - /dev/ttys004
Current terminal session: 1B2E52F0-36D3-44BC-A7B6-3C5116DFC9A9
Current working directory: /Users/jonaszebari/Documents/dev/GitHub/bracket
Current window identifier: 437/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @jonas-zebari! Thank you for reporting this. I can't seem to reproduce on my machine.

Could you make another screen recording where you have one terminal running `fig debug logs` and then reproduce it this behavior in a different terminal session?

**Comment by jonas-zebari** [comment]
@mschrage No problem. Unfortunately the issue has mysteriously disappeared :( If I encounter it again soon I will update this issue.

**Comment by brendanfalk** [comment]
![image](https://user-images.githubusercontent.com/4949076/157141851-f581d6d0-d19a-4572-884e-8dc60b09025c.png)

I can also consistently reproduce this.
