### ISSUE TITLE
Autocomplete popping up noticeably slowly

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#803]
For certain users the autocomplete window pops up perceptibly slowly. The small lag breaks their workflow and is a bad experience.

We haven't been able to reproduce. If you have this issue, could you please comment your dotfiles (.zshrc/.bashrc etc) and your mac specs (ram,cpu, year)

**Comment by brendanfalk** [comment]
One user experienced this issue with these specs
> MacBook Pro 15-Inch "Core i7" 2.6 Touch/2019                2.6 GHz Core i7 (I7-9750H)

**Comment by grant0417** [comment]
No placeholders!
