### ISSUE TITLE
fish shell is very slow to run any command and prompt also very slow to appear after the command run output

### ISSUE THREAD

**Issue by montaro** [withfig/fig#804]
### Description:
fish shell is very slow to run any command and prompt also very slow to appear after the command run output
Trying to comment the `~/.config/fish/conf.d/99_fig_post.fish` made everything fast again!

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.54|/usr/local/Cellar/fish/3.3.1/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.54 (B359) [U.S.] 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Ahmed.Refaey/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installed via Brew: true
Installation Script: true
PseudoTerminal Path: /Users/Ahmed.Refaey/.pyenv/shims:/usr/local/opt/mysql-client/bin:/Users/Ahmed.Refaey/.pyenv/bin /usr/local/opt/mysql-client/bin /Users/Ahmed.Refaey/.fig/bin:/Users/Ahmed.Refaey/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: fish (74677) - /dev/ttys002
Current working directory: /Users/Ahmed.Refaey
Current window identifier: 145936/% (com.googlecode.iterm2)
Path: /Users/Ahmed.Refaey/.pyenv/shims:/usr/local/opt/mysql-client/bin:/Users/Ahmed.Refaey/.pyenv/bin /usr/local/opt/mysql-client/bin /Users/Ahmed.Refaey/.fig/bin:/Users/Ahmed.Refaey/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:07BFCF9B-376C-4100-9536-6DADEAD261D2
  - FIG_TERM=1
  - FIG_CHECKED_PROMPTS=1
  - FIG_TERM_VERSION=3
  - FIG_INTEGRATION_VERSION=5
  - FIG_ENV_VAR=1
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 64 GB</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hey hey! Same Robert from the email. Let's look into what's going on here 🙂

I'd like to try and reproduce your setup as close as I can - are you able to share your fish config? Can also email us if you're not able to share it publicly.
