### ISSUE TITLE
fig auto complete list directories and files after choosing one from list issue

### ISSUE THREAD

**Issue by ShawnCockburn** [withfig/fig#807]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

when using a terminal command that uses a path to a directory or file (eg. `cd`) the auto complete does not load on pressing enter on the initial directory.

### example:

I would like to `cd` to `Desktop/somefolder/` but when I type `cd ` and then select the Desktop folder from the fig menu. fig enters the selected directory so it looks like this `cd Desktop/` but the menu does not show for any sub directories.

[here is YouTube video of issue](https://youtu.be/-ydOqPWXJi4)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.54|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.54 (B359) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 204
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: installed!
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/Work/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (697) - /dev/ttys001
Current working directory: /Users/Work
Current window identifier: 124/% (co.zeit.hyper)
Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/Work/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=33CEE1D4-5AA3-4F0E-8737-37E30E276892
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,4
  - Chip: 
  - Cores: 8
  - Memory: 32 GB</pre>
</p>
</details>

**Comment by ShawnCockburn** [comment]
@mschrage I just updated to `1.0.55 B365` and it's still broken.

**Comment by mschrage** [comment]
Hmm, we thought we'd pushed a fix for this. Can you open up the web inspector (right click on the autocomplete window) and the share the output of the console when you insert something using Fig?

 cc @sullivan-sean

**Comment by mschrage** [comment]
@ShawnCockburn I've pushed a fix for this to the beta channel of the macOS app.

`fig setting app.beta true`

**Comment by ShawnCockburn** [comment]
> @ShawnCockburn I've pushed a fix for this to the beta channel of the macOS app.
> 
> `fig settings app.beta true`

this fixed my issue

**Comment by ShawnCockburn** [comment]
> Hmm, we thought we'd pushed a fix for this. Can you open up the web inspector (right click on the autocomplete window) and the share the output of the console when you insert something using Fig?
> 
> cc @sullivan-sean

I didn't see this comment until after I did the _fig beta true..._ and setting it to false does not downgrade. 

let me know if you still want the screenshot

**Comment by mschrage** [comment]
^^ That was in reference to a similar, but unrelated bug. 

If everything is working on the beta, then the new fix worked.

**Comment by ShawnCockburn** [comment]
thanks @mschrage ❤️
