### ISSUE TITLE
Improve `fig doctor` UX if shell integration is not set up correctly. 

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#808]
Currently, this is the output from `fig doctor` if the shell integration is not sourced correctly:

<img width="648" alt="Screen Shot 2022-01-20 at 4 22 45 PM" src="https://user-images.githubusercontent.com/3155109/150443360-f2c962a5-e085-4d77-bb8b-b3fa344097ca.png">

Also `fig doctor` continues with other diagnostic checks and this this message isn't visible when the script finishes.

**Fix:**
Communicate more clearly that this warning **_must_** be resolved for Fig to work. 

I think the UX here could be to stop the flow and wait for the user to confirm that they've made changes. Then check again.

**Motivation:**
Since we've switched to `figterm` for getting the edit buffer, Fig's shell integration _must_ be sourced last. Popular plugins, most notably `p10k`, break Fig with their default installation. 

A lot of new "autocomplete isn't popuping up" or "insertion isn't working" support requests are due to misconfigured dotfiles. Giving these users a self-serve support option is high priority.

**Comment by grant0417** [comment]
Fixed, made this more clear in wording and wait for user to confirm.
