### ISSUE TITLE
Path suggestion still not working

### ISSUE THREAD

**Issue by NoirJ0e** [withfig/fig#809]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Path suggestion for whatever `cd` or [z](https://github.com/ajeetdsouza/zoxide) is not working, the loading icons appear first but keep loading and then just disappear.

[Video link here](https://youtu.be/IvxDVuSwiQE)
### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7 19H1615|1.0.54|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.54 (B359) [Squirrel] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/noirjoe/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/qt@5/bin:/usr/local/opt/curl/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/Cellar/zplug/2.4.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/noirjoe/.cargo/bin:/Users/noirjoe/.fig/bin:/usr/local/opt/zplug/repos/unixorn/fzf-zsh-plugin/bin:/Users/noirjoe/.fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (72840) - /dev/ttys004
Current working directory: /Users/noirjoe
Current window identifier: 38846/% (com.googlecode.iterm2)
Path: /usr/local/opt/qt@5/bin:/usr/local/opt/curl/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/Cellar/zplug/2.4.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/noirjoe/.cargo/bin:/Users/noirjoe/.fig/bin:/usr/local/opt/zplug/repos/unixorn/fzf-zsh-plugin/bin:/Users/noirjoe/.fzf/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t1p0:21BB9CFB-81C8-4152-A0BE-C0FC4E6414E9
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
MacOS Version: 10.15.7 19H1615
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,4
  - Chip: 
  - Cores: 4
  - Memory: 8 GB</pre>
</p>
</details>

**Comment by brendanfalk** [comment]
Hi @NoirJ0e could you please try running `fig app set-path`, then restarting Fig and see if it works? Thanks for the video!

**Comment by eIiot** [comment]
Also getting this issue

**Comment by eIiot** [comment]
I've been troubleshooting this a bit, and here's what I've found:

This error shows up in the console:
```[Error] template suggestion did not work for folders/filepaths
    (anonymous function) (index.2735c543.js:1:54634)
    asyncFunctionResume
    (anonymous function)
    promiseReactionJobWithoutPromise
    promiseReactionJob```
    
Reinstalling, Restarting, etc. did not fix the problem in any capacity.

**Comment by NoirJ0e** [comment]
> Hi @NoirJ0e could you please try running `fig app set-path`, then restarting Fig and see if it works? Thanks for the video!

Sadly no, the problem still exist.

**Comment by brendanfalk** [comment]
@eIiot @NoirJ0e could you please confirm if `git`, `docker`, and `ls` are suggestions?

**Comment by NoirJ0e** [comment]
> @eIiot @NoirJ0e could you please confirm if `git`, `docker`, and `ls` are suggestions?

yes, they have.

git: 
![image](https://user-images.githubusercontent.com/60462008/150715652-30346406-c976-4c19-bb09-8cda6b6daa3b.png)

docker:
![image](https://user-images.githubusercontent.com/60462008/150715673-ab8f779a-b321-4b14-8808-634052162d2b.png)

ls:
![image](https://user-images.githubusercontent.com/60462008/150715691-cd813ee4-5517-4044-91e2-43ce754c7fce.png)

**Comment by mschrage** [comment]
@NoirJ0e can you run `fig debug logs c_pty unix pty` and take a screen recording of this output while you type `ls ` in a separate terminal session?

**Comment by NoirJ0e** [comment]
> @NoirJ0e can you run `fig debug logs c_pty unix pty` and take a screen recording of this output while you type `ls ` in a separate terminal session?

[Here's the video link](https://youtu.be/RThZ_o7gb5w)

**Comment by webdevnerdstuff** [comment]
Following as I'm also having this issue. So far I've done all the suggested and get the same results. One thing I didn't see mention, and I'm not sure if it matters, but I'm using iterm2.

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>
Fig Version: Version 1.0.55 (B365) [U.S.]
UserShell: /usr/local/bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path:
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/foobar/.nvm/versions/node/v14.16.1/bin:/Users/foobar/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/git/bin:/Users/foobar/.fig/bin:/Users/foobar/.rvm/bin:/usr/local/bin/
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: bash (70371) - /dev/ttys002
Current working directory: /Users/foobar/
Current window identifier: 599064/% (com.googlecode.iterm2)
Path: /Users/foobar/.nvm/versions/node/v14.16.1/bin:/Users/foobar/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/git/bin:/Users/foobar/.fig/bin:/Users/foobar/.rvm/bin:/usr/local/bin/
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:D90373D5-FD80-42FA-9813-631F92773449
  - FIG_ENV_VAR=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 10.15.7 19H1519
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro11,3
  - Chip:
  - Cores: 4
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
@NoirJ0e from the video I can see that commands aren't being run in the pty.
```
pty: [SEND-0] Wrote -1 bytes
```

I am not 100% sure why this is happening. Could you share your bashrc/zshrc with me?

---

@webdevnerdstuff can you run `fig debug logs c_pty unix pty` and share the output!

**Comment by webdevnerdstuff** [comment]
@mschrage 

<details><summary><code>fig debug logs c_pty unix pty</code></summary>
<p>
<pre>
unix: buffer =
unix: Recieved hook message!
unix: {"editBuffer":{"context":{"pid":20345,"ttys":"/dev/ttys004","processName":"bash","sessionId":"w0t0p1:4214086F-ED3A-4FE4-9621-AD36717282FF","integrationVersion":5,"hostname":"somename@some-computer.local"},"text":"c","cursor":"1"}}
unix: Recieved hook message!
unix: {"editBuffer":{"context":{"pid":20345,"ttys":"/dev/ttys004","processName":"bash","sessionId":"w0t0p1:4214086F-ED3A-4FE4-9621-AD36717282FF","integrationVersion":5,"hostname":"somename@some-computer.local"},"text":"cd","cursor":"2"}}
unix: Recieved hook message!
unix: {"editBuffer":{"context":{"pid":20345,"ttys":"/dev/ttys004","processName":"bash","sessionId":"w0t0p1:4214086F-ED3A-4FE4-9621-AD36717282FF","integrationVersion":5,"hostname":"somename@some-computer.local"},"text":"cd ","cursor":"3"}}
unix: Recieved hook message!
unix: {"editBuffer":{"context":{"pid":20345,"ttys":"/dev/ttys004","processName":"bash","sessionId":"w0t0p1:4214086F-ED3A-4FE4-9621-AD36717282FF","integrationVersion":5,"hostname":"somename@some-computer.local"},"text":"cd c","cursor":"4"}}
unix: Recieved hook message!
unix: {"editBuffer":{"context":{"pid":20345,"ttys":"/dev/ttys004","processName":"bash","sessionId":"w0t0p1:4214086F-ED3A-4FE4-9621-AD36717282FF","integrationVersion":5,"hostname":"somename@some-computer.local"},"text":"cd cs","cursor":"5"}}
unix: Recieved hook message!
unix: {"editBuffer":{"context":{"pid":20345,"ttys":"/dev/ttys004","processName":"bash","sessionId":"w0t0p1:4214086F-ED3A-4FE4-9621-AD36717282FF","integrationVersion":5,"hostname":"somename@some-computer.local"},"text":"cd csp","cursor":"6"}}
</pre>
</p>
</details>

**Comment by mschrage** [comment]
@webdevnerdstuff that is helpful information. Can you share your zshrc/bashrc here?

Does autocomplete work for other commands, like `git`?

**Comment by NoirJ0e** [comment]
> @NoirJ0e from the video I can see that commands aren't being run in the pty.
> 
> ```
> pty: [SEND-0] Wrote -1 bytes
> ```
> 
> I am not 100% sure why this is happening. Could you share your bashrc/zshrc with me?
> 
> @webdevnerdstuff can you run `fig debug logs c_pty unix pty` and share the output!

No problem, this is it.

```zsh
#### FIG ENV VARIABLES ####
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
#### END FIG ENV VARIABLES ####
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# alias

#alias cd="z"
alias tree="exa --tree --icons"
#alias ls="exa --icons"
alias REPO="cd ~/Repos"
alias py3="python3"
alias cc="clear"
alias pluginstall='source ~/.zshrc && zplug install && zsh && zplug load'
alias vi="nvim"
alias vim="nvim"
alias ra="ranger"
alias backup="brew bundle dump --describe --force --file="~/Documents/Brewfile""
#alias tree="tree -N"
# 防止 copy 的时候覆盖已存在的文件, 带上 i 选项，文件已存在的时候，会提示，需要确认才能 copy
# alias cp="cp -I"
# 把rm变成放进回收站
alias rm="trash"
# Spotify
alias spp="spotify pause"
alias sps="spotify play"
alias zip='zip -r -9'


# start zplug (from homebrew)
eval $(thefuck --alias)
export ZPLUG_HOME=$(brew --prefix)/opt/zplug
source $ZPLUG_HOME/init.zsh
# zplug plugs
zplug "zsh-users/zsh-autosuggestions"
zplug "zdharma-continuum/fast-syntax-highlighting"
# configuration framework
zplug "sorin-ionescu/prezto"
# zsh-vi-mode
zplug "jeffreytse/zsh-vi-mode"
# colorful ls results
zplug "zpm-zsh/ls"
# better completion
zplug "zsh-users/zsh-completions"
# fzf zsh
zplug "unixorn/fzf-zsh-plugin"
# p10k theme
zplug romkatv/powerlevel10k, as:theme, depth:1
# extract
zplug "plugins/extract",   from:oh-my-zsh
# sudo
zplug "plugins/sudo",   from:oh-my-zsh
# osx controls
# zplug "plugins/macos",   from:oh-my-zsh

# Share history from multiple zsh instances

HISTFILE=/Users/noirjoe/.zshrc-history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# Sources

# fzf
source /usr/local/opt/fzf/shell/key-bindings.zsh
source /usr/local/opt/fzf/shell/completion.zsh
#export FZF_DEFAULT_COMMAND='if [ -f cscope.files ]; then cat cscope.files; else find ./ -type f ; fi'
export FZF_COMPLETION_TRIGGER='\'
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# Startup commands
zplug load
# exports
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export EDITOR="nvim"
export PATH="/usr/local/opt/curl/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/curl/lib"
export CPPFLAGS="-I/usr/local/opt/curl/include"
export PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PATH="/usr/local/opt/qt@5/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/qt@5/lib"
export CPPFLAGS="-I/usr/local/opt/qt@5/include"
export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export CXX=/usr/local/bin/clang++
# prompt
autoload -U promptinit; promptinit
# tab completion case-insensitive
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'
# starup
#tmux
#typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
eval "$(zoxide init zsh)"


#### FIG ENV VARIABLES ####
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
```

**Comment by webdevnerdstuff** [comment]
@mschrage yes it does work for things like git, npm, and similar. I even created some personal shortcuts, and those work as well.

My iTerm2 uses bash-profile instead of bashrc and I don't source zshrc/bashrc. I also decided to try testing in the default iTerm, as well as VSCode but ran into the same problems. So at the very least I don't think it's an issue with any of the terminals apps.

To help to eliminate anything else conflicting I reduced my bashrc/bash-profile down to the following.

```
#### FIG ENV VARIABLES ####
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
#### END FIG ENV VARIABLES ####

#### FIG ENV VARIABLES ####
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
```

But even though I don't source zshrc I decided to try something out. In that file was:
```
#### FIG ENV VARIABLES ####
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
#### END FIG ENV VARIABLES ####

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

#### FIG ENV VARIABLES ####
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
```

So I commented out the export path, and all of a sudden the `cd` autocomplete was working. So I added that back and it stopped working. But when I removed it again... it did not work. I have tried to recreate what I did, and nothing is making it work again. I have no idea why it was working out of nowhere, and now I can't get it back. I don't even source that file so I have no idea what happened.

I then deleted everything from the zshrc/bashrc and ran "Rerun Install Script" which added the base FIG ENV VARIABLES back. Still no changes. 

I then had all three files have just the FIG ENV VARIABLES and still, does not work.

Then after typing all this out I tried something else while messing around and ran `brew install bash-completion` when it was done, the cd autocomplete was working. But as soon as I shut down iTerm2 and opened it back up again, it stopped working again. I hadn't made any changes to anything in between.

I'm not sure if related, but I am also experiencing the problem from this Issue. https://github.com/withfig/fig/issues/806 which I checked after making the three files above to just fig variables, and that problem was still there also.

**Comment by SeparateRecords** [comment]
Looks like this could also be #920 actually - zplug breaks fig on my machine and someone else's too.

**Comment by NoirJ0e** [comment]
> Looks like this could also be #920 actually - zplug breaks fig on my machine and someone else's too. For now, try replacing `zplug load` with `if [[ -z $FIG_SOCKET ]]; then zplug load; fi`

I tried to switch the `zplug load` to the snippet you mentioned, but sadly it still not working for me

**Comment by mschrage** [comment]
@NoirJ0e did you restart Fig?

**Comment by webdevnerdstuff** [comment]
@mschrage I am not using zplug, and never got a response to my last comment. This does not solve the path suggestion problem, so please open this ticket back up. I'd rather not open a new Issue for the same exact reason and have to copy paste everything over.

**Comment by webdevnerdstuff** [comment]
@mschrage My fig diagnostic is in this comment: https://github.com/withfig/fig/issues/809#issuecomment-1024521154

For the bash_profile I tested with bare bones and removed anything I had it in, the info is in this comment: https://github.com/withfig/fig/issues/809#issuecomment-1024986196

After making changes, I restarted fig multiple times when I was testing things out.

**Comment by mschrage** [comment]
Hmm then can you schedule sometime get on a call? https://calendly.com/mschrage/30min

**Comment by SeparateRecords** [comment]
@webdevnerdstuff is this working for you in the latest release? (v1.0.56 B414)

**Comment by webdevnerdstuff** [comment]
@mschrage Sorry I've been busy lately so haven't had the time for a call.

Here is the video you requested:
https://www.youtube.com/watch?v=7S4D3p5tQI8

**Comment by SeparateRecords** [comment]
Hopefully this is resolved now! We've made a lot of changes + stability improvements. Please let us know if you're still having the same problem 🙂
