### ISSUE TITLE
Feature request: Status bar like VSCode

### ISSUE THREAD

**Issue by Milo123459** [withfig/fig#81]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. (e.g. I'm always frustrated when [...])
N/A
**Describe the solution you'd like**
A status bar like VSCode's! With a plugin API, etc!
**Describe alternatives you've considered**
I tried integrating to alacrity but it proved to be a challenge!
**Additional context**
n/a

**Comment by mschrage** [comment]
Closing this issue as stale.
