### ISSUE TITLE
"Unix socket does not exist" after sleep

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#810]
> After restarting my computer it always works, until it goes into sleep mode

This is on 1.0.54:

<img width="738" alt="CleanShot 2022-01-20 at 09 20 43@2x" src="https://user-images.githubusercontent.com/52195359/150459719-24845d98-5dfc-42f8-a679-4eb657b71150.png">

Could possibly be related to power settings - on a Mac mini so I can't test that.

**Comment by ankitbrahmbhatt1997** [comment]
Any update on this ? facing the same issue
@SeparateRecords

**Comment by SeparateRecords** [comment]
@mschrage @grant0417 do we know if this fixed in the beta?

**Comment by mschrage** [comment]
@ankitbrahmbhatt1997 have you changed the setting that hides the Fig from your menubar?

**Comment by ankitbrahmbhatt1997** [comment]
@mschrage Fig remains in my menu bar all the time

**Comment by grant0417** [comment]
Seems to be fixed in 1.0.56
