### ISSUE TITLE
11;rgb:0000/0000/0000 after Fig Executes a Command

### ISSUE THREAD

**Issue by eIiot** [withfig/fig#812]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Whenever fix executes a command (like when the red box pops up), I get a strange output in the terminal after the command completes:
```
 ▲ ~ 11;rgb:0000/0000/0000

 △ ~ ;1R
```
 
Video (Google Drive): https://drive.google.com/file/d/1y_rnLt46-dbJANfBcaHubEI3uubswZ4B/view?usp=sharing

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.21D48|1.0.53|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.53 (B339) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/eliot/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: application is not present.
Hyper Integration: installed!
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/eliot/.zplug/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/eliot/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (4941) - /dev/ttys005
Current working directory: /Users/eliot
Current window identifier: 186/% (co.zeit.hyper)
Path: /Users/eliot/.zplug/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/eliot/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=5FD6CDBE-0537-4954-8774-68287737E9C6
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by eIiot** [comment]
See #806

**Comment by mschrage** [comment]
Thanks for reporting @eIiot! We're investigating this today.

**Comment by grant0417** [comment]
This will be fixed in 1.0.56
