### ISSUE TITLE
`npm run` shows no autocomplete

### ISSUE THREAD

**Issue by Sufiane** [withfig/fig#815]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

npm scripts autocomplete not working even though i followed the tutorial on fig.io

nothing is showed when typing: npm run 

might be related to the use of volta in the project

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6 20G165|1.0.54|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.54 (B359) [French] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/sufianeakadiego/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (35517) - /dev/ttys003
Current working directory: /Users/sufianeakadiego/Development/api
Current window identifier: 149589/% (com.googlecode.iterm2)
Path: /Users/sufianeakadiego/.volta/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/sufianeakadiego/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:3D46ED6E-DAED-4206-9605-4E858202C9C4
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
MacOS Version: 11.6 20G165
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by fedeci** [comment]
Do you have a `package.json` in your project directory?

**Comment by mschrage** [comment]
@Sufiane do other dynamic completions work? eg. If you type `cd `, does Fig show folder suggestions?

**Comment by Sufiane** [comment]
> Do you have a `package.json` in your project directory?

I do have a `package.json` with the same scripts name avec the one in fig (even tried with only one script)

**Comment by Sufiane** [comment]
> @Sufiane do other dynamic completions work? eg. If you type `cd `, does Fig show folder suggestions?
> 
> Would you mind sharing the contents of your `package.json` file here?

when i type `cd ` fig works properly yes !

`{
  "name": "api",
  "version": "3.1.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "test": "jest --runInBand"
  },
  "fig": {
    "test": {
      "description": "Run all tests",
      "icon": "🧪",
      "priority": 100
    }
  },
  "lint-staged": {
    "*.ts": [
      "eslint --fix",
      "prettier --check"
    ]
  },
  "volta": {
    "node": "14.18.2",
    "npm": "6.14.15"
  }`
  
  i left only one script as i tested
  
  (i just removed the dependencies, devdependencies and jest config)

**Comment by Sufiane** [comment]
> @Sufiane do other dynamic completions work? eg. If you type `cd `, does Fig show folder suggestions?
> 
> Would you mind sharing the contents of your `package.json` file here?

@mschrage 
when i type cd fig works properly yes !

```json
{ "name": "api", "version": "3.1.1", "description": "", "author": "", "private": true, "license": "UNLICENSED", "scripts": { "test": "jest --runInBand" }, "fig": { "test": { "description": "Run all tests", "icon": "🧪", "priority": 100 } }, "lint-staged": { "*.ts": [ "eslint --fix", "prettier --check" ] }, "volta": { "node": "14.18.2", "npm": "6.14.15" }
```

i left only one script as i tested

(i just removed the dependencies, devdependencies and jest config)

**Comment by mschrage** [comment]
@Sufiane can you right click on the autocomplete window and bring up the web inspector, then go to Console and share the logs that appear when you type `npm run ` in your project directory.

**Comment by Sufiane** [comment]
@mschrage the thing is the autocomplete window is not shown.

here is a video:

https://user-images.githubusercontent.com/10711632/151142456-144fa9fe-cdef-4f0f-890b-b41e26a13fb0.mov

**Comment by fedeci** [comment]
What happens if you remove the `fig` property from your package.json?

**Comment by mschrage** [comment]
@Sufiane can you run `which npm`?

**Comment by Sufiane** [comment]
> What happens if you remove the `fig` property from your package.json?

nothing happens

**Comment by Sufiane** [comment]
> @Sufiane can you run `which npm`?

@mschrage oh you might have got something here, i forgot that i use `npq-hero`: https://github.com/lirantal/npq
which will alias my npm to run some tests before installs and then let the rest to "npm"

the npm version i use is: 6.14.15 as stated in the volta configuration

**Comment by Sufiane** [comment]
@mschrage the issue is resolved now, i feel like its related to the latest release (better recognition of shell aliases maybe ?)

Thank for you help guys, i'll close the issue :)

**Comment by mschrage** [comment]
Hmm I'm not sure why this would have been resolved. I think the underlying issue is that Fig attempts to expand the alias before providing completions. Since we have no completion spec of `npq-hero`, no suggestions will appear.

One fix is to use a **shell function instead of an alias**, like this` npm() { npq-hero }`. Fig does not expand shell functions.

Another fix would be to add a completion spec for `npq-hero` that just mirrors the `npm` spec.

**Comment by Sufiane** [comment]
the thing is, it now works perfectly and I couldn't be happier 😅

I'll se if I can squeeze a PR about duplicating the npm spec to npq-hero.
if it's good with you ?

Le ven. 4 févr. 2022 à 17:13, Matt Schrage ***@***.***> a
écrit :
