### ISSUE TITLE
Fig doctor says PATH is broken but then doesn't fix it

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#821]
The below is showing up every time a user runs fig doctor (this is recreate from Brendan's computer)
![CleanShot 2022-01-25 at 15 34 46](https://user-images.githubusercontent.com/4949076/151077556-4a2328b9-3ef5-4eee-8e88-1881f4f24ab0.png)

**Comment by grant0417** [comment]
This is really not an issue and fig doctor is giving bad output. A fix should be going out soon though!
