### ISSUE TITLE
Typing the full command suggested by Fig no longer causes the suggestion selector to disappear

### ISSUE THREAD

**Issue by jakemalachowski** [withfig/fig#822]
### Description:

Until recently, typing the full command would cause the suggestion options to disappear, so pressing enter once executed the command. The suggestion now remains after finishing the command.  This means that I need to press enter once to select the option, with no effect, then a second time to execute the command. 

Example:
![image](https://user-images.githubusercontent.com/5766239/151089397-8fb228b0-fd7e-4e33-9a86-50fae7bce1cb.png)

Once I finish typing `pull`, I expect the suggestion to disappear.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.54 (B359)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.54 (B359) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jacobmalachowski/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (31285) - /dev/ttys000
Current terminal session: w0t0p0:1442436D-4A9F-4568-89AA-B6CF98E8A0E7
Current working directory: /Users/jacobmalachowski/go/src/github.com/renderinc/api
Current window identifier: 5701/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @jakemalachowski, pressing enter in this case should still cause the command to execute. If the red arrow icon is visible, Fig will execute the command immediately if you pressed enter.

Does this not happen?

**Comment by jakemalachowski** [comment]
I see. I was misremembering what the behavior was from before the issue occurred.

When I pressed enter with the red arrow icon, the selection would disappear but the command would not execute. Strangely I reproduced the issue, selected `Web Inspector > Console`, and immediately tried to reproduce again but couldn't. I'm not sure why that triggered a change in behavior, but I suppose that makes it difficult to debug now. I will report back here if the issue resurfaces.

**Comment by jakemalachowski** [comment]
After upgrading to 1.0.55, the issue briefly resurfaced for a few commands before returning to normal.

**Comment by jakemalachowski** [comment]
I managed to capture a reproduction with the logs.

https://user-images.githubusercontent.com/5766239/151248415-f0093c06-4fa7-498b-bec2-7b5af6614f10.mov

**Comment by jakemalachowski** [comment]
I managed to capture a reproduction with the logs.

https://user-images.githubusercontent.com/5766239/151248732-8e2571d6-26e3-46e3-8424-00d8636fdf53.mov

**Comment by brendanfalk** [comment]
@jakemalachowski have you seen this issue occur in the last 3 weeks?

**Comment by mschrage** [comment]
In that case, I'll close this issue for the time being. Please let us know if you experience this bug again, I will reopen it.
