### ISSUE TITLE
Unable to complete fig setup

### ISSUE THREAD

**Issue by Mgotya** [withfig/fig#823]
### Description:
> I cannot complete the signup step of the app setup flow due to missing sign in form on the app
> It looks like a captcha issue from the console log but i do not see the way to solve it.

![image](https://user-images.githubusercontent.com/5673032/151168087-0ca462a0-d0f9-4c59-a573-ab6ec77bf14d.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.0|Version 1.0.55 (B365)|/usr/local/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B365) [ABC] 
UserShell: /usr/local/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/michael/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: false
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Mgotya, so sorry that you're running into issues here. If you restart Fig and go through the onboarding flow again, is this reproducible?

**Comment by david-moskovitz** [comment]
Having the same issue 
@mschrage I tried restarting but with no success

This is the output:
```
[Error] Origin https://app.withfig.com is not allowed by Access-Control-Allow-Origin.
[Error] Fetch API cannot load https://www.cotter.app/api/v0/verify/get_identity?oauth_token=true due to access control checks.
[Error] Failed to load resource: Origin https://app.withfig.com is not allowed by Access-Control-Allow-Origin. (get_identity, line 0)
[Error] Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=TypeError%3A%20Load%20failed for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
	Ni (vendor.a7f585ad.js:27:82900)
	(anonymous function) (vendor.a7f585ad.js:27:85019)
	Eg (vendor.a7f585ad.js:27:49161)
	Yi (vendor.a7f585ad.js:27:86755)
	dk (vendor.a7f585ad.js:27:102911)
	dk
	(anonymous function) (vendor.a7f585ad.js:18:3780)
	Uj (vendor.a7f585ad.js:27:99691)
	Lj (vendor.a7f585ad.js:27:95736)
	Lj
	(anonymous function) (vendor.a7f585ad.js:27:45668)
	(anonymous function) (vendor.a7f585ad.js:18:3780)
	jg (vendor.a7f585ad.js:27:45614)
	ig (vendor.a7f585ad.js:27:45549)
	Jg (vendor.a7f585ad.js:27:93135)
	Oh (vendor.a7f585ad.js:27:65021)
	Oh
	(anonymous function) (index.c743fcaf.js:1:1217)
	promiseReactionJob
[Error] Unhandled Promise Rejection: Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=TypeError%3A%20Load%20failed for the full message or use the non-minified dev environment for ful...
	jg (vendor.a7f585ad.js:27:45757)
	ig (vendor.a7f585ad.js:27:45549)
	Jg (vendor.a7f585ad.js:27:93135)
	Oh (vendor.a7f585ad.js:27:65021)
	Oh
	(anonymous function) (index.c743fcaf.js:1:1217)
	promiseReactionJob
	
```

**Comment by grant0417** [comment]
Should be fixed
