### ISSUE TITLE
Problem installing Fig in iterm2

### ISSUE THREAD

**Issue by CKrevan** [withfig/fig#824]
I´m a noob and I just installed Fig and I get an error and I don't know why...

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [Spanish] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/kevindlrm/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (1629) - /dev/ttys002
Current working directory: /Users/kevindlrm
Current window identifier: 166/% (com.googlecode.iterm2)
Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kevindlrm/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:C68F063B-2588-49F3-A3CC-46A7A6C5E4FA
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @CKrevan can you share the error that you get?

**Comment by CKrevan** [comment]
> Hey @CKrevan can you share the error that you get?

Well... I just solved it. Sorry for wasting your time and thanks for your reply.

**Comment by mschrage** [comment]
No worries! And I'd still love to understand what was going on - maybe we can make the UX better?
