### ISSUE TITLE
Auto reported

### ISSUE THREAD

**Issue by matiaspan** [withfig/fig#825]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2 20G95|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/matiaspan/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (38638) - /dev/ttys007
Current working directory: /Users/matiaspan
Current window identifier: 107548/% (com.apple.Terminal)
Path: /Users/matiaspan/Library/Android/sdk/platform-tools:/Users/matiaspan/Library/Android/sdk/tools:/Users/matiaspan/.rvm/gems/ruby-2.7.2/bin:/Users/matiaspan/.rvm/gems/ruby-2.7.2@global/bin:/Users/matiaspan/.rvm/rubies/ruby-2.7.2/bin:/Users/matiaspan/.yarn/bin:/Users/matiaspan/.config/yarn/global/node_modules/.bin:/Users/matiaspan/.nvm/versions/node/v12.22.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/matiaspan/.fig/bin:/Users/matiaspan/.rvm/bin:/Users/matiaspan/Library/Android/sdk/emulator:/Users/matiaspan/Library/Android/sdk/tools:/Users/matiaspan/Library/Android/sdk/tools/bin:/Users/matiaspan/Library/Android/sdk/platform-tools:/Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home:/Users/matiaspan/.rvm/bin
Fig environment variables:
  - TERM_SESSION_ID=5FF9295B-2D91-434E-8AB4-428CB99E1E2E
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 11.5.2 20G95
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @matiaspan, what seems to be the issue? Is Fig not working for your?

**Comment by matiaspan** [comment]
It's absolutely working, but the installer/onboarding seemed to think there
was an error with the PATH right at the end of the process.
Reporting in case you guys want to take a look.

**Comment by mschrage** [comment]
Ah okay! Thanks for letting us know. This is actually expected.
