### ISSUE TITLE
`fig doctor` complains that "iTerm integration fail" in iTerm2

### ISSUE THREAD

**Issue by DKroot** [withfig/fig#827]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I'm using iTerm2 with its Shell Integration as my terminal. I've installed Fig OK and auto-complete is working.
`fig doctor` though produces this:

```
❌ iTerm integration fail
   Could not get iTerm API status

❌ Doctor found errors. Please fix them and try again.
```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.2 20G314|1.0.55|/usr/local/Cellar/bash/5.1.12/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /usr/local/bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/korobskd/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: iTerm's Python API is not enabled.
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/node@14/bin:/usr/local/opt/miniconda3/bin:/usr/local/opt/miniconda3/condabin:/Users/korobskd/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/korobskd/.fig/bin:/usr/local/opt/mlcp/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: bash (16805) - /dev/ttys002
Current working directory: /home
Current window identifier: 4172/% (com.googlecode.iterm2)
Path: /usr/local/opt/node@14/bin:/usr/local/opt/miniconda3/bin:/usr/local/opt/miniconda3/condabin:/Users/korobskd/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/korobskd/.fig/bin:/usr/local/opt/mlcp/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:1FD89853-B1C2-4518-8C76-831D8EE34165
  - FIG_ENV_VAR=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 11.6.2 20G314
Hardware:
  - Model Name: iMac
  - Model Identifier: iMac15,1
  - Chip: 
  - Cores: 4
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @DKroot! Thanks for reporting this. I think that restarting iTerm may resolve this issue. Either way, if Fig is working for you, then something is wrong with our diagnostic.

**Comment by DKroot** [comment]
Tried to restart, of course: it was not working. I fixed the issue by uninstalling Fig then installing via Homebrew. Somehow it fixed the issue.

**Comment by mschrage** [comment]
Hmm interesting. So previously you'd installed directly from the website?

**Comment by DKroot** [comment]
Yes, correct.
