### ISSUE TITLE
Iterm2 integration is not working 

### ISSUE THREAD

**Issue by Lurrobert** [withfig/fig#83]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

This is my zshr 

    ZSH_THEME="powerlevel10k/powerlevel10k"
    source ~/powerlevel10k/powerlevel10k.zsh-theme
    
    # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
    
    source /Users/rob/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    
    source ~/powerlevel10k/powerlevel10k.zsh-theme
    source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zshFirst session iterm2 opens it works. Then I open hot key window and run fig source it reconnects but not showing hints. Later I restarted everything and it is not working at all.  Not showing anything. I turned off zsh completion and no changes.

![image](https://user-images.githubusercontent.com/40468118/119564956-058eb900-bdb2-11eb-9421-3eec5da3261b.png)

### Details:
|macOS|Fig|Shell|
|----|----|----|
|11.3.0|Version 1.0.42 (B207)|/bin/zsh|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.42 (B207) 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/rob/.fig/bin/fig
Accessibility: true
Number of specs: 107
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/rob/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: false
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/rob/.fig/bin:/usr/local/sbin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (10332) - ttys001
Current working directory: /Users/rob/Programming/LoonaCat
Current window identifier: 1488/14C76954E-D0EE-4C33-B1FD-B282950B48E1% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by Lurrobert** [comment]
I found out that hint is showing but on the background. It is a rendering problem. Still not solved
![image](https://user-images.githubusercontent.com/40468118/119575551-e8f97d80-bdbf-11eb-9396-e37bf55bbee3.png)

**Comment by Lurrobert** [comment]
If I uncheck "floating window" in the "hot key window" when hints are present. But still looks like a minor bug

**Comment by mattschrage** [comment]
Thanks for reporting! Seems like this is the same issue as #84. 

Do you mind sharing your iTerm profile. (See the other issue for instructions on how to export this).

Also let me know if this [post](https://forum.withfig.com/t/iterm2-make-autocomplete-work-in-hotkey-visor-floating-quake-mode-terminal/61) solves the problem for you?
