### ISSUE TITLE
PATH and PseudoTerminal PATH do not match

### ISSUE THREAD

**Issue by mmoncera** [withfig/fig#831]
![Screen Shot 2022-01-26 at 5 38 40 PM (2)](https://user-images.githubusercontent.com/67080126/151275980-451edf8b-40fa-46bb-aa83-d81040bb4f1e.png)
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.55|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/mmoncera/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: bash (64086) - /dev/ttys004
Current working directory: /Users/mmoncera
Current window identifier: 12655/% (com.apple.Terminal)
Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/mmoncera/.fig/bin:/Users/mmoncera/.local/bin
Fig environment variables:
  - TERM_SESSION_ID=7E35FC03-FF42-4217-A4CF-EC1C1D478783
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM_VERSION=3
  - FIG_TERM=1
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @mmoncera, can you try running `fig settings pty.path "$PATH"` then run `fig doctor` again. Also are you having any issues other than `doctor`?

**Comment by mmoncera** [comment]
@grant0417 Thank you, that worked!

**Comment by grant0417** [comment]
@mmoncera Let us know if you have any other issues!
