### ISSUE TITLE
[Secure Keyboard] fig is not giving any suggestions

### ISSUE THREAD

**Issue by wallie-pl** [withfig/fig#835]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

https://user-images.githubusercontent.com/2690349/151379161-0ca37598-21d4-4799-852b-8a397fd439d8.mov

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.2 20G314|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [Polish - Pro] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/slawek.wala/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: true
SecureKeyboardProcess: Terminal - com.apple.Terminal (via Settings)
Current active process: zsh (32962) - /dev/ttys003
Current working directory: /Users/slawek.wala
Current window identifier: 48101/% (com.apple.Terminal)
Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/slawek.wala/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=0906A0BF-EB4D-4C6A-A3AE-4DC923F263EE
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 11.6.2 20G314
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @wallie-pl it looks like you have [Secure Keyboard Entry](https://fig.io/docs/support/secure-keyboard-input) enabled. I think if you disable it for Terminal.app, Fig will start working for you :)

**Comment by wallie-pl** [comment]
Yes, but I cannot turn it off. So far I have found that this is not an Terminal.app issue and some other apps might be blocking this option. Will be looking for a solution.

**Comment by mschrage** [comment]
Try running through the debugging steps outlined [here](https://fig.io/docs/support/secure-keyboard-input).

**Comment by wallie-pl** [comment]
Thanks, Guys! I have managed to make it work in VS Code Terminal. Which is enough for me.
