### ISSUE TITLE
Socket does not exist

### ISSUE THREAD

**Issue by kubahasek** [withfig/fig#836]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
When I tried to use Fig today it wouldn't work, when I ran fig doctor I got:
❌ Fig socket does not exist at /var/folders/_f/4srdmrkx13105vzysbz3ctgh0000gn/T/fig.socket
❌ Unable to get diagnostics
   Try restarting Fig by running: fig restart

Restarting it from the menubar helped, but this same message is still there when I run fig doctor

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2 21D49|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>
It looks like Fig is not running.
Try running: fig restart

</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @kubahasek, this might have been in a terminal session that you launched before installing Fig? Try restarting your terminal emulator and let me know if the problem goes away.

**Comment by kubahasek** [comment]
I ended up having to uninstall FIG because I couldn't figure out the issue, now it works fine

**Comment by mschrage** [comment]
Did reinstalling Fix this issue @kubahasek ?

**Comment by kubahasek** [comment]
Yes it did.
