### ISSUE TITLE
[Q&A] Intergrate with Alacritty + Tmux

### ISSUE THREAD

**Issue by harrytran998** [withfig/fig#837]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
Currently, I cannot found any guide for this! Hope your team can make this sooner 😆. I fuc*** love this tool! Thanks your team <3

**Comment by mschrage** [comment]
Hey @harrytran998 currently Alacritty has experimental support. See this issue for more details: https://github.com/withfig/fig/issues/28#issuecomment-1023706180

Fig should support `tmux` out of the box. Please open another issue if autocomplete isn't working inside of tmux sessions.
