### ISSUE TITLE
Autocomplete menu showing behind dropdown terminal in iTerm.

### ISSUE THREAD

**Issue by ncfausti** [withfig/fig#84]
**Summary:**
Autocomplete is occasionally nonresponsive.

**Steps to Reproduce:**

1. Start iTerm 2 and configure it to open with a hot key.
1. Press the hot key to toggle iTerm 2.
1. type 'cd<space>'.

**Expected Results:**
Autocomplete suggestion box should always pop up on top of the terminal.

**Actual Results:**
Autocomplete suggestion box displays behind the terminal. See screenshot below.

https://imgur.com/a/yYJEkuI

**System information:**
OS: MacOS Big Sur 11.2
Terminal: Term2
Version of Fig: 2.0

**Additional Notes:**

**Comment by mattschrage** [comment]
Can you share your iTerm profile?
<img width="1060" alt="Screen Shot 2021-05-25 at 10 44 43 PM" src="https://user-images.githubusercontent.com/3155109/119608499-e6d8f400-bdaa-11eb-8ae3-b57b2bf02450.png">

**Comment by ncfausti** [comment]
`{
  "Working Directory" : "\/Users\/nick",
  "Prompt Before Closing 2" : false,
  "Selected Text Color" : {
    "Red Component" : 0,
    "Color Space" : "sRGB",
    "Blue Component" : 0,
    "Alpha Component" : 1,
    "Green Component" : 0
  },
  "Rows" : 25,
  "Ansi 11 Color" : {
    "Red Component" : 0.79118255174822139,
    "Color Space" : "sRGB",
    "Blue Component" : 0.19504483323544264,
    "Alpha Component" : 1,
    "Green Component" : 0.904632568359375
  },
  "Use Italic Font" : true,
  "HotKey Characters" : "'",
  "Foreground Color" : {
    "Red Component" : 0.90952491760253906,
    "Color Space" : "sRGB",
    "Blue Component" : 0.26184981208507452,
    "Alpha Component" : 1,
    "Green Component" : 0.52260862888350179
  },
  "HotKey Window Floats" : true,
  "Right Option Key Sends" : 0,
  "Character Encoding" : 4,
  "Selection Color" : {
    "Red Component" : 0.73688169941306114,
    "Color Space" : "sRGB",
    "Blue Component" : 0.906982421875,
    "Alpha Component" : 1,
    "Green Component" : 0.81534571965376912
  },
  "Blend" : 0.26106883570091011,
  "Mouse Reporting" : true,
  "Ansi 4 Color" : {
    "Green Component" : "0.3960784",
    "Blue Component" : "0.6431373",
    "Red Component" : "0.2039216"
  },
  "Non-ASCII Anti Aliased" : true,
  "Sync Title" : false,
  "Disable Window Resizing" : true,
  "Description" : "Default",
  "Close Sessions On End" : 1,
  "Jobs to Ignore" : [
    "rlogin",
    "ssh",
    "slogin",
    "telnet",
    "cis557"
  ],
  "Scrollback Lines" : 1000,
  "HotKey Window Reopens On Activation" : false,
  "Flashing Bell" : false,
  "Cursor Guide Color" : {
    "Red Component" : 0.70213186740875244,
    "Color Space" : "sRGB",
    "Blue Component" : 1,
    "Alpha Component" : 0.25,
    "Green Component" : 0.9268307089805603
  },
  "BM Growl" : true,
  "Ansi 3 Color" : {
    "Green Component" : "0.627451",
    "Blue Component" : "0",
    "Red Component" : "0.7686275"
  },
  "Use Non-ASCII Font" : false,
  "Link Color" : {
    "Red Component" : 0,
    "Color Space" : "sRGB",
    "Blue Component" : 0.73423302173614502,
    "Alpha Component" : 1,
    "Green Component" : 0.35916060209274292
  },
  "Shortcut" : "",
  "Background Image Location" : "\/Users\/nick\/Pictures\/figure_3-e1441856837800.jpeg",
  "Bold Color" : {
    "Green Component" : "1",
    "Blue Component" : "1",
    "Red Component" : "1"
  },
  "Use Cursor Guide" : false,
  "Unlimited Scrollback" : false,
  "Custom Command" : "No",
  "HotKey Key Code" : 39,
  "Keyboard Map" : {
    "0xf700-0x260000" : {
      "Text" : "[1;6A",
      "Action" : 10
    },
    "0x37-0x40000" : {
      "Text" : "0x1f",
      "Action" : 11
    },
    "0x32-0x40000" : {
      "Text" : "0x00",
      "Action" : 11
    },
    "0xf709-0x20000" : {
      "Text" : "[17;2~",
      "Action" : 10
    },
    "0xf70c-0x20000" : {
      "Text" : "[20;2~",
      "Action" : 10
    },
    "0xf729-0x20000" : {
      "Text" : "[1;2H",
      "Action" : 10
    },
    "0xf72b-0x40000" : {
      "Text" : "[1;5F",
      "Action" : 10
    },
    "0xf705-0x20000" : {
      "Text" : "[1;2Q",
      "Action" : 10
    },
    "0xf703-0x260000" : {
      "Text" : "[1;6C",
      "Action" : 10
    },
    "0xf700-0x220000" : {
      "Text" : "[1;2A",
      "Action" : 10
    },
    "0xf701-0x280000" : {
      "Text" : "0x1b 0x1b 0x5b 0x42",
      "Action" : 11
    },
    "0x38-0x40000" : {
      "Text" : "0x7f",
      "Action" : 11
    },
    "0x33-0x40000" : {
      "Text" : "0x1b",
      "Action" : 11
    },
    "0xf703-0x220000" : {
      "Text" : "[1;2C",
      "Action" : 10
    },
    "0xf701-0x240000" : {
      "Text" : "[1;5B",
      "Action" : 10
    },
    "0xf70d-0x20000" : {
      "Text" : "[21;2~",
      "Action" : 10
    },
    "0xf702-0x260000" : {
      "Text" : "[1;6D",
      "Action" : 10
    },
    "0xf729-0x40000" : {
      "Text" : "[1;5H",
      "Action" : 10
    },
    "0xf706-0x20000" : {
      "Text" : "[1;2R",
      "Action" : 10
    },
    "0x34-0x40000" : {
      "Text" : "0x1c",
      "Action" : 11
    },
    "0xf700-0x280000" : {
      "Text" : "0x1b 0x1b 0x5b 0x41",
      "Action" : 11
    },
    "0x2d-0x40000" : {
      "Text" : "0x1f",
      "Action" : 11
    },
    "0xf70e-0x20000" : {
      "Text" : "[23;2~",
      "Action" : 10
    },
    "0xf702-0x220000" : {
      "Text" : "[1;2D",
      "Action" : 10
    },
    "0xf703-0x280000" : {
      "Text" : "0x1b 0x1b 0x5b 0x43",
      "Action" : 11
    },
    "0xf700-0x240000" : {
      "Text" : "[1;5A",
      "Action" : 10
    },
    "0xf707-0x20000" : {
      "Text" : "[1;2S",
      "Action" : 10
    },
    "0xf70a-0x20000" : {
      "Text" : "[18;2~",
      "Action" : 10
    },
    "0x35-0x40000" : {
      "Text" : "0x1d",
      "Action" : 11
    },
    "0xf70f-0x20000" : {
      "Text" : "[24;2~",
      "Action" : 10
    },
    "0xf703-0x240000" : {
      "Text" : "[1;5C",
      "Action" : 10
    },
    "0xf701-0x260000" : {
      "Text" : "[1;6B",
      "Action" : 10
    },
    "0xf702-0x280000" : {
      "Text" : "0x1b 0x1b 0x5b 0x44",
      "Action" : 11
    },
    "0xf72b-0x20000" : {
      "Text" : "[1;2F",
      "Action" : 10
    },
    "0x36-0x40000" : {
      "Text" : "0x1e",
      "Action" : 11
    },
    "0xf708-0x20000" : {
      "Text" : "[15;2~",
      "Action" : 10
    },
    "0xf701-0x220000" : {
      "Text" : "[1;2B",
      "Action" : 10
    },
    "0xf70b-0x20000" : {
      "Text" : "[19;2~",
      "Action" : 10
    },
    "0xf702-0x240000" : {
      "Text" : "[1;5D",
      "Action" : 10
    },
    "0xf704-0x20000" : {
      "Text" : "[1;2P",
      "Action" : 10
    }
  },
  "Ansi 14 Color" : {
    "Red Component" : 0.21587523818016049,
    "Color Space" : "sRGB",
    "Blue Component" : 0.67995185263043822,
    "Alpha Component" : 1,
    "Green Component" : 0.90933424234390259
  },
  "Ansi 2 Color" : {
    "Green Component" : "0.6039215999999999",
    "Blue Component" : "0.02352941",
    "Red Component" : "0.3058824"
  },
  "Background Image Is Tiled" : true,
  "Send Code When Idle" : false,
  "ASCII Anti Aliased" : true,
  "Tags" : [

  ],
  "Ansi 9 Color" : {
    "Red Component" : 0.96001332998275757,
    "Color Space" : "sRGB",
    "Blue Component" : 0.20832169055938723,
    "Alpha Component" : 1,
    "Green Component" : 0.20832169055938723
  },
  "Use Bold Font" : true,
  "Silence Bell" : false,
  "Ansi 12 Color" : {
    "Green Component" : "0.6235294",
    "Blue Component" : "0.8117647",
    "Red Component" : "0.4470588"
  },
  "Window Type" : 2,
  "Use Bright Bold" : true,
  "Has Hotkey" : true,
  "HotKey Modifier Activation" : 0,
  "Cursor Text Color" : {
    "Red Component" : 0,
    "Color Space" : "sRGB",
    "Blue Component" : 0,
    "Alpha Component" : 1,
    "Green Component" : 0
  },
  "HotKey Window Dock Click Action" : 1,
  "Default Bookmark" : "No",
  "Cursor Color" : {
    "Green Component" : "1",
    "Blue Component" : "1",
    "Red Component" : "1"
  },
  "Ansi 1 Color" : {
    "Green Component" : "0",
    "Blue Component" : "0",
    "Red Component" : "0.8"
  },
  "Name" : "Console",
  "Blinking Cursor" : false,
  "Guid" : "79702DF8-953C-4AD1-B906-B5AE058EB916",
  "Idle Code" : 0,
  "Ansi 10 Color" : {
    "Green Component" : "0.8862745",
    "Blue Component" : "0.2039216",
    "Red Component" : "0.5411764999999999"
  },
  "Ansi 8 Color" : {
    "Green Component" : "0.3411765",
    "Blue Component" : "0.3254902",
    "Red Component" : "0.3333333"
  },
  "Badge Color" : {
    "Red Component" : 0,
    "Color Space" : "sRGB",
    "Blue Component" : 0,
    "Alpha Component" : 0.5,
    "Green Component" : 0
  },
  "Ambiguous Double Width" : false,
  "Ansi 0 Color" : {
    "Green Component" : "0",
    "Blue Component" : "0",
    "Red Component" : "0"
  },
  "Blur" : false,
  "Normal Font" : "Monaco 18",
  "Vertical Spacing" : 1,
  "Use Underline Color" : true,
  "Ansi 7 Color" : {
    "Green Component" : "0.8431373",
    "Blue Component" : "0.8117647",
    "Red Component" : "0.827451"
  },
  "Space" : 0,
  "HotKey Window AutoHides" : true,
  "Command" : "",
  "Terminal Type" : "xterm-256color",
  "Horizontal Spacing" : 1,
  "Underline Color" : {
    "Red Component" : 1,
    "Color Space" : "sRGB",
    "Blue Component" : 1,
    "Alpha Component" : 1,
    "Green Component" : 1
  },
  "Option Key Sends" : 2,
  "Minimum Contrast" : 0.28835227272727271,
  "HotKey Window Animates" : false,
  "HotKey Modifier Flags" : 1048576,
  "Ansi 15 Color" : {
    "Green Component" : "0.9333333",
    "Blue Component" : "0.9254902",
    "Red Component" : "0.9333333"
  },
  "Open Toolbelt" : true,
  "Ansi 6 Color" : {
    "Green Component" : "0.5960785",
    "Blue Component" : "0.6039215999999999",
    "Red Component" : "0.02352941"
  },
  "Transparency" : 0.10843477975293465,
  "HotKey Activated By Modifier" : false,
  "Background Color" : {
    "Red Component" : 0.0029458864592015743,
    "Color Space" : "sRGB",
    "Blue Component" : 0.040618896484375,
    "Alpha Component" : 1,
    "Green Component" : 0.015075105690328883
  },
  "Screen" : -1,
  "HotKey Characters Ignoring Modifiers" : "'",
  "Bound Hosts" : [

  ],
  "Non Ascii Font" : "Monaco 12",
  "Ansi 13 Color" : {
    "Red Component" : 0.49772330893392791,
    "Color Space" : "sRGB",
    "Blue Component" : 0.668609619140625,
    "Alpha Component" : 1,
    "Green Component" : 0.36916562914848333
  },
  "Columns" : 80,
  "HotKey Alternate Shortcuts" : [

  ],
  "Visual Bell" : true,
  "Custom Directory" : "No",
  "Thin Strokes" : 0,
  "Ansi 5 Color" : {
    "Green Component" : "0.3137255",
    "Blue Component" : "0.4823529",
    "Red Component" : "0.4588235"
  }
}`

**Comment by ncfausti** [comment]
[Console.json.txt](https://github.com/withfig/fig/files/6550252/Console.json.txt)

**Comment by mattschrage** [comment]
Thanks! I'll try to reproduce. 

Also try following the instructions here to [resolve](https://forum.withfig.com/t/iterm2-make-autocomplete-work-in-hotkey-visor-floating-quake-mode-terminal/61) the issue.

**Comment by ncfausti** [comment]
> Thanks! I'll try to reproduce.
> 
> Also try following the instructions here to [resolve](https://forum.withfig.com/t/iterm2-make-autocomplete-work-in-hotkey-visor-floating-quake-mode-terminal/61) the issue.

Cool, the instructions linked fixed it. Thanks!
