### ISSUE TITLE
Could not get iTerm version

### ISSUE THREAD

**Issue by tonysorensen** [withfig/fig#840]
![Screenshot 2022-01-27 at 2 19 46 PM](https://user-images.githubusercontent.com/63228541/151453250-0e1c987d-8ae0-4448-bdc2-37f1e3c962bb.png)

Fig Doctor can't get iTerm version because it's checking for /Appllications/iTerm.app and on my machine it's /Applications/iTerm2.app

**Comment by ZilvinasKucinskas** [comment]
Same issue, but my iTerm is located at `$HOME/Applications/iTerm.app`. I believe `~/Applications` is the default brew cask directory.

**Comment by grant0417** [comment]
Fixed in 1.0.56
