### ISSUE TITLE
[website] [ux] email field is almost unreadable when the screen rendering has a little bit of contrast 

### ISSUE THREAD

**Issue by bobTheHands** [withfig/fig#841]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Issue Details

<codebase:website>, <usability>
As stated, an easy way to reproduce is:
  - open the website,
  - fill up email field

With some sensible default color settings, (contrast / saturation) , its already hard to see. But a slight bump in any of those settings and the text quickly disappears to the eyes.

![unknown](https://user-images.githubusercontent.com/71857389/151475553-e9ea6d8c-3ad1-4c8b-80ac-bd4de7d06f0f.png)

I also ran a quick&dirty lighthouse test, and the results tell the same, about this particular issue:

![image](https://user-images.githubusercontent.com/71857389/151476076-c79f43b5-a122-4305-b4a6-88ed3a8d69b0.png)

### Environment

```bash
Not relevant, it may happen on any screen
```

**Comment by grant0417** [comment]
We have a redesigned site so this should be resolved!
