### ISSUE TITLE
Doctor found errors. Please fix them and try again.

### ISSUE THREAD

**Issue by aPinix** [withfig/fig#843]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2 21D49|1.0.55|/usr/local/Cellar/zsh/5.8_1/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [Portuguese] 
UserShell: /usr/local/bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/apinix/.gem/ruby/3.0.0/bin:/usr/local/opt/ruby/bin:/Users/apinix/.avn/bin:/Users/apinix/.nvm/versions/node/v14.17.4/bin:/Users/apinix/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/apinix/.fig/bin:/Users/apinix/.fzf/bin:/Users/apinix/.rvm/bin:/Users/apinix/Library/Android/sdk/tools:/Users/apinix/Library/Android/sdk/platform-tools
SecureKeyboardInput: true
SecureKeyboardProcess: iTerm2 - com.googlecode.iterm2 
Current active process: zsh (74546) - /dev/ttys002
Current working directory: /Users/apinix
Current window identifier: 18001/% (com.googlecode.iterm2)
Path: /Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/apinix/.gem/ruby/3.0.0/bin:/usr/local/opt/ruby/bin:/Users/apinix/.avn/bin:/Users/apinix/.nvm/versions/node/v14.17.4/bin:/Users/apinix/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/apinix/.fig/bin:/Users/apinix/.fzf/bin:/Users/apinix/.rvm/bin:/Users/apinix/Library/Android/sdk/tools:/Users/apinix/Library/Android/sdk/platform-tools
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:5A7BD5F0-8688-40DE-AD03-3DD86F5EFE44
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
MacOS Version: 12.2 21D49
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: 
  - Cores: 10
  - Memory: 32 GB</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @aPinix , can you try running `fig settings pty.path "$PATH"` then run `fig doctor` again. Also are you having any issues other than `doctor`?

**Comment by mschrage** [comment]
It looks like @aPinix has [Secure Keyboard Entry](https://fig.io/docs/support/secure-keyboard-input) enabled. Try following [this guide](https://fig.io/docs/support/secure-keyboard-input) to turn it off.

**Comment by grant0417** [comment]
@aPinix Looks like this issue is stale, please open another issue if you have any others.
