### ISSUE TITLE
❌ PATH and PseudoTerminal PATH do not match

### ISSUE THREAD

**Issue by soundsystems** [withfig/fig#844]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2 21D49|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jguala/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (1598) - /dev/ttys003
Current working directory: /Users/jguala
Current window identifier: 250/% (com.googlecode.iterm2)
Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/jguala/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w1t0p0:71DAD394-8B0C-416E-9D49-3484BFD3D05C
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2 21D49
Hardware:
  - Model Name: iMac
  - Model Identifier: iMac19,1
  - Chip: 
  - Cores: 8
  - Memory: 44 GB</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @soundsystems, can you try running `fig settings pty.path "$PATH"` then run `fig doctor` again. Also are you having any issues other than `doctor`?

**Comment by Glacier-Luo** [comment]
> 

It's useful.Thank you!

**Comment by grant0417** [comment]
@Glacier-Luo 

Glad that worked! Let us know if you run into any other issues.

**Comment by soundsystems** [comment]
the command `fig settings pty.path "$PATH"` did nothing for me. 

doctor is my only issue so far. Is this a breaking error or will i be able to use it fine with the Path being unmatched?

**Comment by grant0417** [comment]
@soundsystems 

This shouldn't be a breaking error if everything else works, if you could send me the output of `fig diagnostics` I could help diagnose if there are any other issues though.
