### ISSUE TITLE
Turn off "hello from figrc" on load message

### ISSUE THREAD

**Issue by webdevnerdstuff** [withfig/fig#845]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
The ability to turn off the `hello from figrc` welcome message, without having to edit the (managed.bash, managed.fish, managed.zsh) files to remove it.

I already have my own custom setup, so I don't really like other things or messages added.

Alternatively, if I delete it from managed.bash will it get added back automatically when the app updates next?

**Comment by grant0417** [comment]
Hey @webdevnerdstuff, sorry about this, you must have ran `fig alpha sync` which currently is not complete but soon will sync you dotfiles. Currently this overwrites the "managed" dotfiles with that message. Just be sure not to runs `fig alpha sync`.

**Comment by webdevnerdstuff** [comment]
Thank you @grant0417 . I think I ran that command when trying to debug a problem I was having. That was suggested as one of the things to try in the Issue that is already open and being problem solved.

**Comment by grant0417** [comment]
> Thank you @grant0417 . I think I ran that command when trying to debug a problem I was having. That was suggested as one of the things to try in the Issue that is already open and being problem solved.

Do you remember what issue? Definitely don't want more people running that right now.

**Comment by webdevnerdstuff** [comment]
@grant0417 I just checked the two Issues, and that command wasn't in there.

I just checked my hist, and it looks like I did run `fig alpha source` when I was just messing around seeing what things did.

Here are the tickets for reference anyway, just in case you need them for whatever reason:
https://github.com/withfig/fig/issues/809
https://github.com/withfig/fig/issues/806

**Comment by grant0417** [comment]
@webdevnerdstuff 

Glad everything is working now, let us know if you run into any other issue!
