### ISSUE TITLE
"Could not get iTerm version" error

### ISSUE THREAD

**Issue by drKaramazin** [withfig/fig#846]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.6 19G2021|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/nikolajgriskin/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/Cellar/gettext/0.20.1/bin:/usr/local/Cellar/libpq/11.1/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/nikolajgriskin/.fig/bin:/Users/nikolajgriskin/Library/Android/sdk/tools/bin:/Users/nikolajgriskin/Library/Android/sdk/platform-tools:/Users/nikolajgriskin/Library/Android/sdk/emulator
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (3614) - /dev/ttys002
Current working directory: /Users/nikolajgriskin
Current window identifier: 899/% (com.googlecode.iterm2)
Path: /usr/local/Cellar/gettext/0.20.1/bin:/usr/local/Cellar/libpq/11.1/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/nikolajgriskin/.fig/bin:/Users/nikolajgriskin/Library/Android/sdk/tools/bin:/Users/nikolajgriskin/Library/Android/sdk/platform-tools:/Users/nikolajgriskin/Library/Android/sdk/emulator
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:B798FA74-18CE-4CD0-A085-3E9A54D1F557
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 10.15.6 19G2021
Hardware:
  - Model Name: iMac
  - Model Identifier: iMac13,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @drKaramazin, was this an issue with `fig doctor`?
