### ISSUE TITLE
init install and running of fig doctor

### ISSUE THREAD

**Issue by crellisonii** [withfig/fig#849]
### Description:
This is an issue when running thru the initial install process. Was recommended to run fig doctor and then this issue came up

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/charlesellisonii/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (3261) - /dev/ttys002
Current working directory: /Users/charlesellisonii
Current window identifier: 474/% (com.googlecode.iterm2)
Path: /Users/charlesellisonii/.nvm/versions/node/v14.8.0/bin:/bin:/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/charlesellisonii/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:6327EE67-1200-4EA4-977A-B3EDFE622C74
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
This is should be resolved in the latest version!
