### ISSUE TITLE
❌ PATH and PseudoTerminal PATH do not match

### ISSUE THREAD

**Issue by sabbirahmed007** [withfig/fig#855]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6 20G165|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/itsa1/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (48057) - /dev/ttys004
Current working directory: /Users/itsa1
Current window identifier: 210741/% (com.googlecode.iterm2)
Path: /Users/itsa1/oracledb/instantclient_19_8::/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/itsa1/.fig/bin:/Applications/MySQLWorkbench.app/Contents/MacOS:/Users/itsa1/.antigen/bundles/zsh-users/zsh-autosuggestions
Fig environment variables:
  - TERM_SESSION_ID=w1t0p0:23757979-FCF8-4F9E-B7D7-0A928382FB70
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 11.6 20G165
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by crebuh** [comment]
Same for me

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)



### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/crebuh/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (81135) - /dev/ttys009
Current working directory: /Users/crebuh
Current window identifier: 86122/% (com.googlecode.iterm2)
Path: /Users/crebuh/.fastlane/bin:/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/bin:/Users/crebuh/google-cloud-sdk/bin:/Users/crebuh/.fastlane/bin:/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/bin:/Users/crebuh/.nvm/versions/node/v17.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/crebuh/flutter/bin:/Library/Apple/usr/bin:/Users/crebuh/.fig/bin:/Users/crebuh/flutter/.pub-cache/bin:/Users/crebuh/Library/Android/sdk/build-tools/30.0.2:/Users/crebuh/Library/Android/sdk/tools/bin:/Users/crebuh/Library/Android/sdk/platform-tools:/Users/crebuh/Library/Android/sdk/emulator:/Users/crebuh/Library/Android/sdk/build-tools/29.0.0:/Applications/Android Studio.app/Contents/gradle/gradle-5.1.1/bin:/Users/crebuh/Library/Android/sdk/tools/bin:/Users/crebuh/Library/Android/sdk/platform-tools:/Users/crebuh/Library/Android/sdk/emulator:/Users/crebuh/Library/Android/sdk/build-tools/29.0.0:/Applications/Android Studio.app/Contents/gradle/gradle-5.1.1/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p1:DA0569BD-5D03-48D4-845E-B1430CA9CC05
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by aleksanderwalczuk** [comment]
Same,

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)



### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7 19H1323|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [Polish - Pro] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/alexander/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/alexander/.poetry/bin:/usr/local/opt/php@7.4/sbin:/usr/local/opt/php@7.4/bin:/usr/local/sbin:/Users/alexander/.nvm/versions/node/v14.16.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alexander/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (24176) - /dev/ttys009
Current working directory: /Users/alexander
Current window identifier: 24921/% (com.googlecode.iterm2)
Path: /Users/alexander/.poetry/bin:/usr/local/opt/php@7.4/sbin:/usr/local/opt/php@7.4/bin:/Users/alexander/.nvm/versions/node/v14.16.1/bin:/usr/local/sbin:/Users/alexander/.nvm/versions/node/v14.16.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alexander/.poetry/bin:/usr/local/opt/php@7.4/sbin:/usr/local/opt/php@7.4/bin:/usr/local/sbin:/Users/alexander/.nvm/versions/node/v14.16.1/bin:/Users/alexander/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:7EBD441D-7BC2-494D-A888-9DAC5E65E9EE
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 10.15.7 19H1323
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro13,3
  - Chip: 
  - Cores: 4
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by astrobound** [comment]
same issue.

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)



### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/brandonthomas/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (48716) - /dev/ttys002
Current working directory: /Users/brandonthomas
Current window identifier: 17133/% (com.apple.Terminal)
Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components:/Users/brandonthomas/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=422278D5-359E-4ED2-BEE1-BA145555855D
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hey everyone! Sorry about this bug. Can you try running this command and let me know if it fixes it for you?

```
fig settings pty.path "$PATH"
```

**Comment by lobatolais** [comment]
It didn't work for me 😔
I'm still getting the same error when running `fig doctor`

**Comment by crebuh** [comment]
Solved it for me 👍

**Comment by grant0417** [comment]
@sabbirahmed007 @crebuh @aleksanderwalczuk @astrobound @lobatolais @crebuh 

This is really not an issue and `fig doctor` is giving bad output. A fix should be going out soon though!
