### ISSUE TITLE
Path was not updated correctly

### ISSUE THREAD

**Issue by Gr8Gatsby** [withfig/fig#856]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/kevinhill/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (86517) - /dev/ttys004
Current working directory: /Users/kevinhill
Current window identifier: 31403/% (com.apple.Terminal)
Path: /usr/local/opt/node@16/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kevinhill/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=5752E0AF-A161-4550-A97E-EE8CEF1A55E0
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: iMac
  - Model Identifier: iMac17,1
  - Chip: 
  - Cores: 4
  - Memory: 32 GB</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @Gr8Gatsby, this is really not an issue and fig doctor is giving bad output. A fix should be going out soon though!
