### ISSUE TITLE
Spotlight indexing is triggered after each macOS restart

### ISSUE THREAD

**Issue by yackinn** [withfig/fig#861]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Issue Details
On every startup spotlight indexing is triggered by figterm.
It should be indexed once unless there are changes to the file system.
The issue is gone when fig is commented out in .zshrc and .zprofile.
It's a major performance issue as it tasks the cpu heavily on each os startup.

### Description:
![Bildschirmfoto 2022-01-31 um 08 02 53](https://user-images.githubusercontent.com/61085055/151751972-f4d2080b-7df2-4098-a850-b4ee71294b51.png)

Run `sudo fs_usage` to inspect the spotlight indexing.
It seems the indexing is in an infinite loop. The processes are reocurring.
`.fig/insertion-lock ... .fig/insertion-lock `
![Bildschirmfoto 2022-01-31 um 07 53 35](https://user-images.githubusercontent.com/61085055/151752049-af6df3da-defa-46a6-a846-2ff209b42390.png)

This is the activity monitor after each startup
![Bildschirmfoto 2022-01-31 um 07 51 17](https://user-images.githubusercontent.com/61085055/151752126-5c6d9ea6-0c29-4768-bf69-2663a51ede27.png)

### Environment

```bash
Fig Version: Version 1.0.55 (B365) [German] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/yannick.boetzkes/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/yannick.boetzkes/.nvm/versions/node/v17.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/yannick.boetzkes/.fig/bin:/Users/yannick.boetzkes/.yarn/bin:/Users/yannick.boetzkes/.config/yarn/global/node_modules/.bin:/usr/local/bin:/opt/homebrew/bin:/Users/yannick.boetzkes/.yarn/bin:/Users/yannick.boetzkes/.config/yarn/global/node_modules/.bin:/usr/local/bin:/opt/homebrew/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (4043) - /dev/ttys001
Current working directory: /Users/yannick.boetzkes
Current window identifier: 379/% (com.apple.Terminal)
Path: /Users/yannick.boetzkes/.nvm/versions/node/v17.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/yannick.boetzkes/.fig/bin:/Users/yannick.boetzkes/.yarn/bin:/Users/yannick.boetzkes/.config/yarn/global/node_modules/.bin:/usr/local/bin:/opt/homebrew/bin:/Users/yannick.boetzkes/.yarn/bin:/Users/yannick.boetzkes/.config/yarn/global/node_modules/.bin:/usr/local/bin:/opt/homebrew/bin
Fig environment variables:
  - TERM_SESSION_ID=E2EAA3D2-B663-402C-A26A-15290009EA43
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
```

**Comment by mschrage** [comment]
Hmm thanks for reporting this @yackinn. Is it possible for you to kill the Jamf daemon? I have a suspicion there might be some conflict between Fig and Jamf that triggers Spotlight search re-indexing.

**Comment by yackinn** [comment]
Unforunately not. The system restarts the daemon immediately after shutting it down.

**Comment by yackinn** [comment]
I think this issue is resolved.

**Comment by mschrage** [comment]
Great! Thank you so much for letting us know :)
