### ISSUE TITLE
Path and Pseudoterminal Path Do Not match

### ISSUE THREAD

**Issue by MBAiBake** [withfig/fig#862]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1 21A559|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/taylorbaker/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (43116) - /dev/ttys002
Current working directory: /Users/taylorbaker
Current window identifier: 36169/% (com.apple.Terminal)
Path: /Users/taylorbaker/opt/anaconda3/bin:/Users/taylorbaker/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/taylorbaker/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=27A522D2-74EF-4A99-AF7A-B8928A4CD0A3
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.0.1 21A559
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 32 GB</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @MBAiBake, this is really not an issue and fig doctor is giving bad output. A fix should be going out soon though!
