### ISSUE TITLE
iTerm integration fail

### ISSUE THREAD

**Issue by advania-tomi** [withfig/fig#866]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

![image](https://user-images.githubusercontent.com/61293271/151885417-dd1d9be6-98dc-4ae3-8d1c-058b7890f960.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.1 20G224|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [Finnish] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/tpaivaa/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/tpaivaa/.nvm/versions/node/v16.13.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Applications/Wireshark.app/Contents/MacOS:/Users/tpaivaa/.fig/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/tpaivaa/Library/Python/2.7/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (16617) - /dev/ttys007
Current working directory: /Users/tpaivaa
Current window identifier: 18913/% (com.apple.Terminal)
Path: /usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/tpaivaa/.nvm/versions/node/v16.13.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Applications/Wireshark.app/Contents/MacOS:/Users/tpaivaa/.fig/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/tpaivaa/Library/Python/2.7/bin
Fig environment variables:
  - TERM_SESSION_ID=31E97D77-E37F-4B4A-8F12-06CF690526DB
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 11.6.1 20G224
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hi @advania-tomi - sorry for the issue! Does this still happen after re-running the install script?

<img width="768" alt="CleanShot 2022-02-04 at 12 17 37@2x" src="https://user-images.githubusercontent.com/52195359/152456460-b3745a41-270c-4d4c-a2c3-b515a2e7b198.png">

**Comment by advania-tomi** [comment]
Hi @SeparateRecords  
Apart from that fail on fig doctpr fig seems to work fine.

That re-running did not have noticeable difference. I still get that same indication...

I noticed that on my integrations menu there is no iTerm 
and that's because I don't think I have that app installed...

![image](https://user-images.githubusercontent.com/61293271/152529092-ea670b27-3906-47ec-9797-6f4b9012d1cc.png)

So I believe thats just cosmetic and I might not need to worry... Unless I need to have that iTerm...
