### ISSUE TITLE
Add support for Hyper on linux

### ISSUE THREAD

**Issue by LifeIsStrange** [withfig/fig#868]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Feature Details

The Readme says:
> Does Fig work on Windows or Linux?
Currently, Fig is only available on MacOS.

But at the same times it says:
> Fig works with iTerm, the native MacOS Terminal app, **[Hyper](https://hyper.is/)** and the integrated terminal in VSCode.

Hyper is a cross platform electron based terminal so if your amazing library works on Hyper, it should work on Hyper on every OSes out of the box. Is that the case? If so fig do supports linux at least with Hyper. Can you clarify that point as currently the Readme seems contradictory.

**Comment by mschrage** [comment]
This is unfortunately not the case. While Hyper (and VSCode) are both cross-platform, Fig only works with these applications on macOS.

I am going to close this issue in favor of #34.

**Comment by LifeIsStrange** [comment]
Hmm strange, I guess adding support for it on hyper on linux would be easier to achieve than adding support for it on linux native terminals but OK no problem, good luck with the port :)
BTW out of curiosity I was reading comments that autocomplete was initially written in swift and then planned to be rewrotten in Rust. Have those plans been canceled in favor of typescript or will there be two implementations?
