### ISSUE TITLE
Unexpected behavior when click on "Install Hyper Integration"

### ISSUE THREAD

**Issue by EliasGcf** [withfig/fig#87]
**Summary:**
"Install Hyper Integration" not complete successfully.

**Steps to Reproduce:**

1. Install Fig and Hyper
1. Try to add the Hyper Integration

**Expected Results:**
When click on "Install Hyper Integration", should download the plugin, add to `~/.hyper.js` on `localPlugins` and not show this message anymore.

![image](https://user-images.githubusercontent.com/50633599/119575807-f7c73c80-bd8d-11eb-969a-f1dc1432bcd1.png)

**Actual Results:**
The plugin (`fig-hyper-integration`) was downloaded, but was not added to `~/.hyper.js` on `localPlugins`.

**System information:**
OS: MacOS Big Sur 11.1
Terminal: Hyper
Version of Fig: 1.0.42

**Additional Notes:**
Important information is that even without this plugin on `localPlugins` the autocomplete suggestion works.

**Comment by mattschrage** [comment]
When setting up the Hyper Integration, Fig will attempt to naively parse the `hyper.js` file and add "fig-hyper-integration" to the `localPlugins` array.  

if it fails, you just need to add it manually:
```
  localPlugins: [
     "fig-hyper-integration"
  ],
```
While Fig may continue to prompt you you to install the Hyper integration, once you have done this, everything will be set up.

We are reworking the integrations flow and UI in an upcoming build.

Note: The extension is required if you use multiple tabs or panes with Hyper.

**Comment by mschrage** [comment]
New integrations UI that reports errors like this is landing in the next release! (v1.0.49)
