### ISSUE TITLE
Fig stopped working after OH-MY-ZSH

### ISSUE THREAD

**Issue by DjDeepDive** [withfig/fig#873]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

After installing OH-MY-ZSH, fig integration stopped working.  I even embedded the ZSH .zshrc script in between the proper fig pre/post setup.

fig doctor gave me this:

```
❌ PATH and PseudoTerminal PATH do not match

I can fix this!
Running > fig app set-path


Setting $PATH variable in Fig pseudo-terminal...

Fig will now use the following path to locate the fig executable:
/Users/me/.pyenv/shims:/Users/me/.pyenv/bin:/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/me/.fig/bin

            
Fix applied!
Rerunning fig doctor to see if the problem is resolved.....

❌ PATH and PseudoTerminal PATH do not match

Looks like we've already tried this fix before and it's not working.

Run fig issue to let us know about this error!
Or, email us at hello@fig.io!
```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B366) [Beta] [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/me/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/me
Current window identifier: 35385/% (com.apple.Terminal)
Path: /Users/me/.pyenv/shims:/Users/me/.pyenv/bin:/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/me/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=F9561E93-10F5-4515-9987-2FBF3DDE7F70
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @DjDeepDive! To confirm, does autocomplete no longer appear in `zsh`? What if you switch to `bash`?

Would you mind sharing your `zshrc` file?

**Comment by DjDeepDive** [comment]
For clarity: the popup completion window on Fig no longer shows up in my `zsh` Mac Terminal, but if I hit <tab>, it shows all completion possibilities, including command flag options.  It was working great before installing OH-MY-ZSH.

When I typed "`bash`" in the zsh, Fig stopped working entirely in that window.  Even after manually running the pre.sh and fig.sh, and typing `fig restart`.  Fig said it was running, but no completion happened at all, not even with <tab>.

Here's my `.zshrc`:

```
#### FIG ENV VARIABLES ####
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
#### END FIG ENV VARIABLES ####
source ~/.zshrc.ohmyzsh

# disable special creation/extraction of ._* files by tar, etc. on Mac OS X
COPYFILE_DISABLE=1; export COPYFILE_DISABLE

export PYENV_ROOT="$HOME/.pyenv"
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

### SNIP: custom aliases for my system ###

#### FIG ENV VARIABLES ####
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
```

The source for the `.zshrc.ohmyzsh` calls `~/.oh-my-zsh/oh-my-zsh.sh ` which does a bunch.  I had a previous Mac with Oh My Zsh! and Fig worked.... I just installed this Mac fresh and new with the latest, so it's possible something new in Oh My Zsh! is conflicting with Fig.

**Comment by mschrage** [comment]
Hmm interesting. If you comment out the line `source ~/.zshrc.ohmyzsh` and open a new terminal, does Fig start working again?

**Comment by DjDeepDive** [comment]
After commenting that out, and restarting Terminal altogether, nothing from Fig worked.  `fig doctor` said all was good, but it lied to me.  So I put the `source ~/.zshrc.ohmyzsh` back in, quit Terminal and relaunched.... and what do you know... Fig works perfectly.

So I'm not sure what happens in the Oh My Zsh! configuration, or how it butchers Fig.... but now it seems everything is working fine, as long as I stick with Oh My Zsh!.  If I remove it... seems to break Fig again.

I suppose we can close this issue for now.  If you want to do a deeper dive on Oh My Zsh! interaction, you can ping me anytime.
