### ISSUE TITLE
Support for oh-my-zsh

### ISSUE THREAD

**Issue by tyler-austin** [withfig/fig#874]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I was wondering if there was planned support for oh-my-zsh? I haven't used `cd` in a long time, I don't need it to change directories but I would like some intelisense when I start typing.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.2|Version 1.0.55 (B365)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/austyle/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/austyle/.rvm/gems/ruby-2.7.1/bin:/Users/austyle/.rvm/gems/ruby-2.7.1@global/bin:/Users/austyle/.rvm/rubies/ruby-2.7.1/bin:/Users/austyle/bin:/Users/austyle/.toolbox/bin:/Users/austyle/.toolbox/bin:/usr/local/opt/rsync/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/grep/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:/Users/austyle/.nvm/versions/node/v14.17.0/bin:/Users/austyle/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/austyle/.fig/bin:/Users/austyle/.rvm/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @tyler-austin! Fig should automatically work with oh-my-zsh. Could you elaborate on the behavior that is missing for you?

**Comment by SeparateRecords** [comment]
Quickly following this up - Fig should really be working fine with OMZ. Is it only the folder completions you're after? Is there something else broken?

I think #908 might be more precise for this request - would love if you could add some additional context to it! (and also suggest a better title 😅)
