### ISSUE TITLE
Fig "not linked to terminal session"

### ISSUE THREAD

**Issue by craigz** [withfig/fig#876]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

fig was not providing autocomplete at all, so i ran `fig doctor` and everything looked fine, then quit and restarted fig, however it remained not working. i then rebooted and when fig wasn't working, quit and restarted fig. still no luck. i've also both restarted iTerm and tried again with a new window, as well as firing up the stock macOS `terminal.app` however the results were the same.

- entering `fig source` reports fig to be connected to the terminal session, however fig remains inactive and the menubar item suggests fig not to be connected.  
- `fig source` output:
<img width="526" alt="figMehTerm" src="https://user-images.githubusercontent.com/1929275/152039488-e6fad901-7935-4404-b3ca-0183c52ca700.png">
- viewing the menubar:
<img width="419" alt="figMehMenu" src="https://user-images.githubusercontent.com/1929275/152039586-e0393afa-c40b-492f-853d-8f2d28f3f77b.png">

as of the latest update, things were working well, i'd last been playing with the new themes and had things looking pretty neat.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2 21D49|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B366) [staging] [Beta] [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/craigz/.fig/bin/fig
Accessibility: true
Number of specs: 198
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/craigz/.yarn/bin:/Users/craigz/.config/yarn/global/node_modules/.bin:/Users/craigz/.deta/bin:/Users/craigz/.local/bin:/Users/craigz/perl5/bin:/Users/craigz/Library/Caches/fnm_multishells/5087_1643744076878/bin:/Users/craigz/Library/Caches/fnm_multishells/5047_1643744076860/bin:/opt/homebrew/opt/openssl@1.1/bin:/Users/craigz/.pyenv/plugins/pyenv-virtualenv/shims:/Users/craigz/.pyenv/shims:/Users/craigz/.rbenv/shims:/Users/craigz/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/craigz/.new_local/bin:/Users/craigz/.fig/bin:/Users/craigz/.kit/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/craigz/Dropbox (Maestral)/transfer/dev
Current window identifier: 71/% (com.googlecode.iterm2)
Path: /Users/craigz/.yarn/bin:/Users/craigz/.config/yarn/global/node_modules/.bin:/Users/craigz/.deta/bin:/Users/craigz/.local/bin:/Users/craigz/perl5/bin:/Users/craigz/Library/Caches/fnm_multishells/5087_1643744076878/bin:/Users/craigz/Library/Caches/fnm_multishells/5047_1643744076860/bin:/opt/homebrew/opt/openssl@1.1/bin:/Users/craigz/.pyenv/plugins/pyenv-virtualenv/shims:/Users/craigz/.pyenv/shims:/Users/craigz/.rbenv/shims:/Users/craigz/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/craigz/.new_local/bin:/Users/craigz/.fig/bin:/Users/craigz/.kit/bin
Fig environment variables:
  - TERM_SESSION_ID=w2t3p0:DD76E4DE-8516-44CE-A455-A01989B08F29
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2 21D49
Hardware:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Can you run `FIG_LOG_LEVEL=DEBUG` in one terminal session, then run `fig debug logs` in another and take a screen recording of the output while typing in the first terminal?

**Comment by mschrage** [comment]
Potentially related to #819

**Comment by craigz** [comment]
here's a movie with the requested sequence of events. btw, after the test/recording, i changed `FIG_LOG_LEVEL` from `debug` to `info`. is the the best 'default' setting? 

https://user-images.githubusercontent.com/1929275/152229701-41a49419-b6be-4645-a70e-7c8f5749c212.mp4

**Comment by mschrage** [comment]
It seems like unix socket events aren't being sent on each keystroke - this is why the debugger says that the terminal is not linked.

However, it seems like the unix socket connection is working. When you run `fig doctor`, we could see in the logs that a connection was made (see at 0:22).

This makes me think that the issue might be related to your dotfiles. Would you mind sharing your zshrc?

**Comment by craigz** [comment]
i've just tidied up my .zshrc and have shared it here as a gist:
[.zshrc](https://gist.github.com/craigz/67b06aaa36c40f0ac08f004cf6b9e519)

i've removed a lot of the commented out config notes and unset options for a degree of clarity.

**Comment by craigz** [comment]
shortly after updating this issue, `fig` sprung back to life in the terminal.
perhaps 'cleaning' .zshrc (basically migrating aliases & functions to separate files) seems to have changed something enough to restore functionality to `fig`.

**Comment by brendanfalk** [comment]
Hey @craigz - I know you have since fixed it, but this sounds potentially similar to https://github.com/withfig/fig/issues/987. 

If this happens again, could you please check if the `~/.fig/insertion-lock` file exists? If yes, 
1. Please share the contents of the file here
2. Run `~/.fig/insertion-lock` to remove the file. This should solve the issue!

If the file doesn't exist, then it sounds like this is another bug!

**Comment by craigz** [comment]
@brendanfalk indeed, all is working now.  

i've just checked and currently have no such file in my `~/.fig` directory. 
if the issue crops up again, i'll check for it and share the file's contents prior to deleting it.
