### ISSUE TITLE
VsCode Powershell Extension stalls

### ISSUE THREAD

**Issue by grant0417** [withfig/fig#881]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Issue Details

PowerShell 7.2.1 and tested both the Release and Preview versions of the PowerShell Extension.

The PowerShell extension stalls on load and never completes.

**Comment by cabneydp** [comment]
Adding additional information on the same bug below.

### Description:
When I attempt to load the PowerShell extension on macOS it says "Loading PowerShell extension is taking longer than expected" and will eventually time out. I uninstalled Fig and it immediately worked. Tried this on multiple machines and can reproduce the issue. If Fig is installed, VSCode's PowerShell Extension won't run. If Fig's removed, it works. No issues found in Fig Doctor.

Seems to cause the issue even when VSCode integration is disabled from inside of Fig. Can replicate the issue on 2 different machines. Install Powershell, VSCode, Fig from Brew. Try running the Powershell extension in VS Code and it fails. Uninstall Fig, restart VSCode, it works.

Running the latest version of macOS, VSCode, Powershell, Fig, etc. I've only tried it on M1 Mac's, not sure if that really would matter though.

### Screen Recordings
This is a screen recording showing the Powershell Extension never loading. This is with Fig installed.
https://user-images.githubusercontent.com/97906386/160477544-f70f19b9-8866-4297-be77-0faed9c13f35.mov

This is a screen recording showing the Powershell Extension loading properly without Fig installed. 
https://user-images.githubusercontent.com/97906386/160477679-f6c341fe-da0b-4ba7-9126-1544221696fa.mov

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B416) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/Users/chris/.local/bin:/Users/chris/.fig/bin:/Users/chris/.local/bin:/Users/chris/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: Mac mini
  - Model Identifier: Macmini9,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/chris
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 1453/% (com.googlecode.iterm2)
  - Active Process: zsh (18805) - not a tty
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:CC04CC3D-61DB-4C87-A896-C0E7D0503183
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/Users/chris/.local/bin:/Users/chris/.fig/bin:/Users/chris/.local/bin:/Users/chris/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
  
</p>
</details>



<details><summary><code>powershell and vscode diagnostics and info</code></summary>
<p>

## OS & Device
M1 Mac Mini
macOS Monterey 12.3

## PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Darwin 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```


## Visual Studio Code Version

```console
1.65.2
c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
arm64
```


## Extension Version

```console
ms-vscode.powershell@2021.12.0
```


## Steps to Reproduce

Attempt to load PowerShell Extension in VSCode

## Visuals

![image](https://user-images.githubusercontent.com/97906386/160459307-528aac08-3b43-4865-90ce-a8550bd90352.png)

![image](https://user-images.githubusercontent.com/97906386/160459347-eff5f015-1865-473f-aa59-1bbc667f2180.png)


## Logs

3/28/2022 1:46:51 PM [NORMAL] - Visual Studio Code v1.65.2 64-bit
3/28/2022 1:46:51 PM [NORMAL] - PowerShell Extension v2021.12.0
3/28/2022 1:46:51 PM [NORMAL] - Operating System: MacOS 64-bit
3/28/2022 1:46:51 PM [NORMAL] - Language server starting --
3/28/2022 1:46:51 PM [NORMAL] -     PowerShell executable: /usr/local/bin/pwsh
3/28/2022 1:46:51 PM [NORMAL] -     PowerShell args: -Login -NoProfile -NonInteractive -EncodedCommand SQBtAHAAbwByAHQALQBNAG8AZAB1AGwAZQAgACcALwBVAHMAZQByAHMALwBjAGgAcgBpAHMALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADEALgAxADIALgAwAC8AbQBvAGQAdQBsAGUAcwAvAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC8AUABvAHcAZQByAFMAaABlAGwAbABFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBwAHMAZAAxACcAOwAgAFMAdABhAHIAdAAtAEUAZABpAHQAbwByAFMAZQByAHYAaQBjAGUAcwAgAC0ASABvAHMAdABOAGEAbQBlACAAJwBWAGkAcwB1AGEAbAAgAFMAdAB1AGQAaQBvACAAQwBvAGQAZQAgAEgAbwBzAHQAJwAgAC0ASABvAHMAdABQAHIAbwBmAGkAbABlAEkAZAAgACcATQBpAGMAcgBvAHMAbwBmAHQALgBWAFMAQwBvAGQAZQAnACAALQBIAG8AcwB0AFYAZQByAHMAaQBvAG4AIAAnADIAMAAyADEALgAxADIALgAwACcAIAAtAEEAZABkAGkAdABpAG8AbgBhAGwATQBvAGQAdQBsAGUAcwAgAEAAKAAnAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBkAGkAdABvAHIAUwBlAHIAdgBpAGMAZQBzAC4AVgBTAEMAbwBkAGUAJwApACAALQBCAHUAbgBkAGwAZQBkAE0AbwBkAHUAbABlAHMAUABhAHQAaAAgACcALwBVAHMAZQByAHMALwBjAGgAcgBpAHMALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADEALgAxADIALgAwAC8AbQBvAGQAdQBsAGUAcwAnACAALQBFAG4AYQBiAGwAZQBDAG8AbgBzAG8AbABlAFIAZQBwAGwAIAAtAFMAdABhAHIAdAB1AHAAQgBhAG4AbgBlAHIAIAAnAD0APQA9AD0APQA+ACAAUABvAHcAZQByAFMAaABlAGwAbAAgAEkAbgB0AGUAZwByAGEAdABlAGQAIABDAG8AbgBzAG8AbABlACAAdgAyADAAMgAxAC4AMQAyAC4AMAAgADwAPQA9AD0APQA9AAoAJwAgAC0ATABvAGcATABlAHYAZQBsACAAJwBOAG8AcgBtAGEAbAAnACAALQBMAG8AZwBQAGEAdABoACAAJwAvAFUAcwBlAHIAcwAvAGMAaAByAGkAcwAvAC4AdgBzAGMAbwBkAGUALwBlAHgAdABlAG4AcwBpAG8AbgBzAC8AbQBzAC0AdgBzAGMAbwBkAGUALgBwAG8AdwBlAHIAcwBoAGUAbABsAC0AMgAwADIAMQAuADEAMgAuADAALwBsAG8AZwBzAC8AMQA2ADQAOAA0ADgAOQA2ADEAMQAtADkAOQA3ADcAZQA3ADkAOAAtADIAZABmAGMALQA0AGUANgBiAC0AYgA5AGQAYwAtAGQAMwA0ADgAMgAzADYANgA0ADUAMABiADEANgA0ADgANAA4ADkANgAwADMANwA1ADQALwBFAGQAaQB0AG8AcgBTAGUAcgB2AGkAYwBlAHMALgBsAG8AZwAnACAALQBTAGUAcwBzAGkAbwBuAEQAZQB0AGEAaQBsAHMAUABhAHQAaAAgACcALwBVAHMAZQByAHMALwBjAGgAcgBpAHMALwAuAHYAcwBjAG8AZABlAC8AZQB4AHQAZQBuAHMAaQBvAG4AcwAvAG0AcwAtAHYAcwBjAG8AZABlAC4AcABvAHcAZQByAHMAaABlAGwAbAAtADIAMAAyADEALgAxADIALgAwAC8AcwBlAHMAcwBpAG8AbgBzAC8AUABTAEUAUwAtAFYAUwBDAG8AZABlAC0AMwAzADMAOAAtADQAOAAyADEAMQA2ACcAIAAtAEYAZQBhAHQAdQByAGUARgBsAGEAZwBzACAAQAAoACkAIAA=
3/28/2022 1:46:51 PM [NORMAL] -     PowerShell Editor Services args: Import-Module '/Users/chris/.vscode/extensions/ms-vscode.powershell-2021.12.0/modules/PowerShellEditorServices/PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.12.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/chris/.vscode/extensions/ms-vscode.powershell-2021.12.0/modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.12.0 <=====
' -LogLevel 'Normal' -LogPath '/Users/chris/.vscode/extensions/ms-vscode.powershell-2021.12.0/logs/1648489611-9977e798-2dfc-4e6b-b9dc-d3482366450b1648489603754/EditorServices.log' -SessionDetailsPath '/Users/chris/.vscode/extensions/ms-vscode.powershell-2021.12.0/sessions/PSES-VSCode-3338-482116' -FeatureFlags @() 
3/28/2022 1:46:51 PM [NORMAL] - pwsh started.
3/28/2022 1:46:51 PM [NORMAL] - Waiting for session file
3/28/2022 1:50:51 PM [NORMAL] - Timed out waiting for session file to appear.
3/28/2022 1:50:51 PM [NORMAL] - Language server startup failed.
3/28/2022 1:50:51 PM [ERROR] - The language service could not be started: 
3/28/2022 1:50:51 PM [ERROR] - Error: Timed out waiting for session file to appear.
</p>
</details>

**Comment by SeparateRecords** [comment]
Thanks so much for adding the videos @cabneydp !

I spent some time looking into this today.

* The powershell extension launches pwsh with `-Login`
* [`pwsh -Login` makes powershell run zsh in emulation mode](https://github.com/PowerShell/PowerShell/blob/9f722ef95072fddd975b1b7b584bf11b2e857a69/src/powershell/Program.cs#L336-L340), causing it to source your `/etc/profile` and `~/.profile`
* Fig **correctly** detects that you're in zsh, and launches figterm

**Workaround:** remove the fig lines from your `~/.profile`

**Comment by mschrage** [comment]
Nice sleuthing @SeparateRecords - I looked into this briefly and was super confused about what was going on.
