### ISSUE TITLE
Stuck at white screen after confirming email adress

### ISSUE THREAD

**Issue by yechielw** [withfig/fig#883]
### Description:

<img width="703" alt="Screen Shot 2022-02-02 at 9 24 44" src="https://user-images.githubusercontent.com/41305372/152111371-430f8945-9b24-4008-b20d-8d6c99d2f81a.png">
<img width="222" alt="Screen Shot 2022-02-02 at 9 24 56" src="https://user-images.githubusercontent.com/41305372/152111392-1239c37e-8b0d-472c-9d9d-247b3fb11faf.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.0|Version 1.0.55 (B365)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B365) [Beta] [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/yechielworenklein/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: true
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/yechielworenklein/.fig/bin:/opt/homebrew/opt/fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @yechielw, can you check your internet connection? If you are using a firewall or on a VPN, there might be issues. Try using a different network or cellular hotspot.
