### ISSUE TITLE
How do we uninstall Fig?

### ISSUE THREAD

**Issue by ubolonton** [withfig/fig#89]
# Improve documentation
## Link 
https://fig-1.gitbook.io/fig/

## Describe the problem
There is no uninstallation instruction. The links in https://github.com/withfig/fig/issues/2 are 404'ed.

## Describe the improvement
Clearly documented uninstallation process.

## Additional context
This is especially terrible because of issues like #88.

---
**EDIT**

Here is the most up to date uninstall instructions: https://github.com/withfig/fig/discussions/140

**Comment by falky97** [comment]
Apologies - we updated our docs and domain all within the past week. Clearly missed a few things. 

Here is how to uninstall:
![image](https://user-images.githubusercontent.com/4949076/119606278-256caf80-bda7-11eb-8a9c-e35fff95ca88.png)

**Comment by falky97** [comment]
Also, that gitbook link is now old. Please use https://fig.io/docs

**Comment by brendanfalk** [comment]
Unsure why this was never closed. Please use this link to learn how to uninstall Fig with the recommended way or manually: https://github.com/withfig/fig/discussions/140
