### ISSUE TITLE
fig seems to not work after I restart 

### ISSUE THREAD

**Issue by jithinlalpr** [withfig/fig#893]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2 21D49|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [ABC – India] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jithin/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/Users/jithin/.nvm/versions/node/v16.8.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jithin/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (3758) - /dev/ttys001
Current working directory: /Users/jithin
Current window identifier: 396/% (com.apple.Terminal)
Path: /opt/homebrew/bin:/Users/jithin/.nvm/versions/node/v16.8.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jithin/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=9292CC2F-BBF1-4F4C-9E2A-A48872E61B79
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2 21D49
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hi @jithinlalpr - so to confirm what's happening, after you restart does the ◧ menu item show up? Or is it just the autocomplete popup that doesn't show?

**Comment by jithinlalpr** [comment]
Menu did show up. And it started working when I did something inside it. But not sure what. But at the first time the auto complete wasn't working

**Comment by jithinlalpr** [comment]
It happens from time to time
