### ISSUE TITLE
❌ PATH and PseudoTerminal PATH do not match

### ISSUE THREAD

**Issue by ubmit** [withfig/fig#895]
### Description:
> `fig doctor` tries to fix it, but then, when I open another tab or a new window, the same error appears after running `fig doctor`

![image](https://user-images.githubusercontent.com/8797405/152419697-d5c60446-a80e-4cca-b843-7f14f2922c05.png)

![image](https://user-images.githubusercontent.com/8797405/152419790-7b79df0f-46c6-4dab-9c98-704c53f3da0c.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.55|/opt/homebrew/Cellar/fish/3.3.1/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [Brazilian] 
UserShell: /opt/homebrew/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/guilherme/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/guilherme/Library/Caches/fnm_multishells/85426_1643918277534/bin:/opt/homebrew/bin:/Users/guilherme/.oly/bin:/Users/guilherme/Library/Python/2.7/bin:/Users/guilherme/.local/bin:/opt/homebrew/opt/ruby/bin:/Users/guilherme/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: fish (85384) - /dev/ttys002
Current working directory: /Users/guilherme
Current window identifier: 23248/% (com.googlecode.iterm2)
Path: /Users/guilherme/Library/Caches/fnm_multishells/85426_1643918277534/bin:/opt/homebrew/bin:/Users/guilherme/.oly/bin:/Users/guilherme/Library/Python/2.7/bin:/Users/guilherme/.local/bin:/opt/homebrew/opt/ruby/bin:/Users/guilherme/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:12164A8D-65F8-49DF-A45B-E8B7D535D2B5
  - FIG_TERM=1
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
  - FIG_TERM_VERSION=3
  - FIG_INTEGRATION_VERSION=5
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @ubmit, this is really not an issue and fig doctor is giving bad output. A fix should be going out soon though!

**Comment by ubmit** [comment]
thank you! @grant0417
