### ISSUE TITLE
autocomplete window not working after the tutorial

### ISSUE THREAD

**Issue by afmsavage** [withfig/fig#896]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig not working on M1 MacOS laptop.  Have tried to install it via `brew` and by downloading the latest `.dmg`.  Each time I have uninstalled and reinstalled, it works in the tutorial terminal that opens, but as soon as I close that and try to open my own, it never works.  

Have tried the dev mode instructions from the `autocomplete` repo, have tried terminal, iterm2, vscode's terminal.  None of them work.  I so very much want this to work!

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2 21D49|1.0.55|/opt/homebrew/Cellar/bash/5.1.16/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /opt/homebrew/bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installed via Brew: true
Installation Script: true
PseudoTerminal Path: /opt/homebrew/opt/gnupg@2.2/bin:/Users/tony/.wasmer/bin:/Users/tony/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/tony/go/bin:/Users/tony/.local/share/solana/install/active_release/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/tony/.nvm/versions/node/v16.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tony/.fig/bin:/Users/tony/bin:/Users/asavage/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/tony/.krew/bin:/Users/tony/Library/Python/3.9/bin:/Users/tony/.zokrates/bin:/Users/tony/.wasmer/globals/wapm_packages/.bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/tony
Current window identifier: 974/% (com.apple.Terminal)
Path: /opt/homebrew/opt/gnupg@2.2/bin:/Users/tony/.wasmer/bin:/Users/tony/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/tony/go/bin:/Users/tony/.local/share/solana/install/active_release/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/tony/.nvm/versions/node/v16.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tony/.fig/bin:/Users/tony/bin:/Users/asavage/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/tony/.krew/bin:/Users/tony/Library/Python/3.9/bin:/Users/tony/.zokrates/bin:/Users/tony/.wasmer/globals/wapm_packages/.bin
Fig environment variables:
  - TERM_SESSION_ID=F4242613-BDBA-4381-8999-44475251EA2C
  - FIG_ENV_VAR=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2 21D49
Hardware:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
@afmsavage thanks for reporting this. The fact that Fig works in the onboarding but then fails afterwards suggests to me that there is a conflict with something in your dotfiles.

Would you mind sharing your `bashrc` & `bash_profile` here?

Also try running `exec zsh` to see if Fig works in zsh.

**Comment by afmsavage** [comment]
When I run `fig doctor` for the first time, I always get this fix from it:

```
$ fig doctor
❌ PATH and PseudoTerminal PATH do not match

I can fix this!
Running > fig app set-path


Setting $PATH variable in Fig pseudo-terminal...

Fig will now use the following path to locate the fig executable:
/opt/homebrew/opt/gnupg@2.2/bin:/Users/tony/.wasmer/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/tony/go/bin:/Users/tony/.local/share/solana/install/active_release/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/tony/.nvm/versions/node/v16.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tony/.fig/bin:/Users/tony/bin:/Users/asavage/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/tony/.krew/bin:/Users/tony/Library/Python/3.9/bin:/Users/tony/.zokrates/bin:/Users/tony/.cargo/bin:/Users/tony/.wasmer/globals/wapm_packages/.bin
```

Gist with my dotfiles (sanitized).  The other few files at the top that are imported are just secret token env vars being imported so no logic being imported.

https://gist.github.com/afmsavage/7a212d0e7c0c8305cc4a70d122ebcece

**Comment by afmsavage** [comment]
Been messing around with changing up and removing different pieces of my `~/.bash_profile` and `~/.bashrc`.  I think it may have something to do with the fact that fig is trying to reference `~/.bashrc` on a Mac, but bash uses `~/.bash_profile` on a mac when opening a new terminal.  And then if I try to source `~/.bashrc` somewhere in the middle of my `~/.bash_profile`, the fig scripts run but are processed in the middle of `~/.bash_profile` instead of at the start and end.  

I also tested out removing both the `.bashrc` and `.bash_profile` files so that my terminal used the `~/.profile` file with the fig sourcing and fig works fine.

**Comment by mschrage** [comment]
This issue should be resolved on more recent versions of Fig! Please updating by running `fig update`. 

If you're still running into issues, let me know!
