### ISSUE TITLE
"Insert common prefix" keybinds with fuzzy search feels wrong

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#897]
Everything here is working correctly but the end result doesn't feel good.

Easy reproduction: type this, then hit tab.
```bash
fig settings auto
```

To me, it feels and looks like it should have inserted "autocomplete." but because some fuzzy search matches weren't at the beginning of the name, the only common prefix was "a" so it actually _removed_ the "uto" instead of inserting anything.

What I think should happen: insert common prefix should only consider suggestions that already start with the token, instead of the common prefix of _all_ the suggestions.

**Comment by brendanfalk** [comment]
This is happening because insert-common prefix is turned on. When a user types a short string, then inserts, it will insert the common prefix, which may be nothing...

**Comment by SeparateRecords** [comment]
This is fixed now - common prefix now filters for suggestions that start with the search term. Feels _way_ better to use with fuzzy search!
