### ISSUE TITLE
Completions don't work when in paths with CJK characters

### ISSUE THREAD

**Issue by goranmoomin** [withfig/fig#90]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

As the title says, some completion doesn't interact well with CJK character paths. Below is a video that demonstrates that when once I try to use completion in a CJK character path, completion doesn't work until after I go to a non-CJK path and execute a command.

Some command completion do work, e.g. `git` completion sometimes does work if I don't trigger `ls`/`cd` commands and break the whole thing.

https://user-images.githubusercontent.com/37990858/119625635-60252500-be45-11eb-8bbf-5f1fb7372e93.mp4

### Details:
|macOS|Fig|Shell|
|----|----|----|
|11.4.0|Version 1.0.42 (B207)|/bin/zsh|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.42 (B207) 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/josungbin/.fig/bin/fig
Accessibility: true
Number of specs: 107
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/josungbin/.fig/user/keybindings
iTerm Integration: false
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (15791) - ttys000
Current working directory: /Users/josungbin/Documents/SNU/자료구조
Current window identifier: 3407/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mattschrage** [comment]
Thanks so much for reporting this. I investigated just now and it looks like Fig's pseudo-terminal implementation chokes when running commands that contain CJK characters. Will try to fix this ASAP!

**Comment by mattschrage** [comment]
Finally figured out what was going on. The `LANG` environment variable wasn't being set. This will be fixed automatically in the next build.

**A quick fix:** If you create `~/.fig/user/ptyrc` and add `export LANG=en_US.UTF-8` (or another locale)

My apologies again for the wait @goranmoomin! Thanks again for reporting this issue!
