### ISSUE TITLE
Fig not loading in sync with Terminal

### ISSUE THREAD

**Issue by Brendonjhawkins** [withfig/fig#905]
### Description:

Lately when I open my terminal, if my computer has been sleep for some time, fig does not load, and I have to restart fig and my terminal for them to sync. 

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.0|Version 1.0.52 (B315)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B315) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/1000010hawk/.fig/bin/fig
Accessibility: true
Number of specs: 212
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/1000010hawk/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (8648) - /dev/ttys001
Current working directory: /Users/1000010hawk
Current window identifier: 23775/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Brendonjhawkins! You're on an old version of Fig. Try running `fig update` to download the latest build. 

I'm going to close this issue for now, but will reopen it you're still running into problems on v1.0.56.
