### ISSUE TITLE
'PATH and PseudoTerminal PATH do not match' Fig Doctor after reinstall

### ISSUE THREAD

**Issue by ClaudiusSeibt** [withfig/fig#906]
### Description:
> Ran 'Fig Doctor' right after reinstall of Fig and got Error: 'PATH and PseudoTerminal PATH do not match'. Im running iTerm2.
<img width="1904" alt="Screenshot 2022-02-07 at 18 15 56" src="https://user-images.githubusercontent.com/57871362/152847603-f0669fe7-a642-49ab-8fa5-d852f94a283e.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2 21D49|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [German] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (14696) - /dev/ttys001
Current working directory: /Users/claudi
Current window identifier: 1148/% (com.googlecode.iterm2)
Path: /Applications/Sublime Text.app/Contents/SharedSupport/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/claudi/.cargo/bin:/Users/claudi/.fig/bin:/Users/claudi/.rvm/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:098481B3-BD36-40F3-B0E8-FE3B411D1F96
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2 21D49
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @ClaudiusSeibt, this is really not an issue and fig doctor is giving bad output. A fix should be going out soon though!
