### ISSUE TITLE
Just installed on 10.13 (High Sierra) and here I am. 

### ISSUE THREAD

**Issue by speciale** [withfig/fig#907]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.13.6 17G14042|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [French - Numerical] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/speciale/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (22334) - /dev/ttys002
Current working directory: /Users/speciale
Current window identifier: 485/% (com.googlecode.iterm2)
Path: /Users/speciale/bin:/usr/local/bin:/usr/local/mysql:/usr/local/opt/ruby/bin:/usr/local/opt/php@8.0/bin:/usr/local/opt/php@8.0/sbin:/usr/local/opt/php@8.0/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/speciale/.cargo/bin:/Users/speciale/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:F5F31450-5BA8-4638-B1DD-58DD1783CDCF
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 10.13.6 17G14042
Hardware:
  - Model Name: iMac
  - Model Identifier: iMac12,1
  - Chip: 
  - Cores: 4
  - Memory: 12 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @speciale! What seems to be the issue?

**Comment by speciale** [comment]
When I run doctor I get this

```
❯ fig doctor
❌ macOS version lower than 10.14 is incompatible with Fig
❌ PATH and PseudoTerminal PATH do not match

I can fix this!
Running > fig app set-path


Setting $PATH variable in Fig pseudo-terminal...

Fig will now use the following path to locate the fig executable:
/Users/speciale/bin:/usr/local/bin:/usr/local/mysql:/usr/local/opt/ruby/bin:/usr/local/opt/php@8.0/bin:/usr/local/opt/php@8.0/sbin:/usr/local/opt/php@8.0/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/speciale/.cargo/bin:/Users/speciale/.fig/bin


Fix applied!
Rerunning fig doctor to see if the problem is resolved.....

❌ macOS version lower than 10.14 is incompatible with Fig
❌ PATH and PseudoTerminal PATH do not match

Looks like we've already tried this fix before and it's not working.

Run fig issue to let us know about this error!
Or, email us at hello@fig.io!
```

**Comment by mschrage** [comment]
Does Fig show autocomplete suggestions for you?

**Comment by speciale** [comment]
Yes, it works.
![Screen Shot 2022-02-08 at 11 59 39](https://user-images.githubusercontent.com/1444636/152977036-cdb750cf-1307-45e8-8694-b4c01d2e1018.png)

I just did as I was told, I did run `fig issue` and here we are.

**Comment by grant0417** [comment]
Hey @speciale, this is really not an issue and fig doctor is giving bad output. Sorry about the confusion! A fix should be going out soon though!

**Comment by ellizonn** [comment]
> Yes, it works. ![Screen Shot 2022-02-08 at 11 59 39](https://user-images.githubusercontent.com/1444636/152977036-cdb750cf-1307-45e8-8694-b4c01d2e1018.png)
> 
> I just did as I was told, I did run `fig issue` and here we are.

I'm using 10.13 too.
Can you gently describe how do you solve the problem with Fig?
Your help would be extremely important, thanks.
