### ISSUE TITLE
PATH and PseudoTerminal PATH do not match after installation

### ISSUE THREAD

**Issue by jtexi001** [withfig/fig#912]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2 21D49|1.0.55|/usr/local/Cellar/bash/5.1.4/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /usr/local/bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jorge/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: bash (6113) - /dev/ttys004
Current working directory: /Users/jorge
Current window identifier: 585/% (com.apple.Terminal)
Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jorge/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=C98E89FF-EE39-446A-AF4B-C2CE5F26BF2A
  - FIG_ENV_VAR=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2 21D49
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,3
  - Chip: 
  - Cores: 6
  - Memory: 32 GB</pre>
</p>
</details>

**Comment by cori-afs** [comment]
Here to open the same issue

### Description:
> `fig doctor` says it can't find my shell

```
corischlegel@CQ4N6YKGR2 ~ % fig doctor
🟡 Could not get current user shell

❌ Default shell  is not compatible
   You are not using a supported shell.
   Only zsh, bash, or fish are integrated with Fig.

❌ PATH and PseudoTerminal PATH do not match

I can fix this!
Running > fig app set-path


Setting $PATH variable in Fig pseudo-terminal...

Fig will now use the following path to locate the fig executable:
/usr/local/opt/avr-gcc@8/bin:/Users/cori/.nvm/versions/node/v12.22.10/bin:/Users/cori/.zplug/bin:/Users/cori/.cargo/bin:~/dotfiles/scripts/:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/cori/.fig/bin:/Users/cori/bin


Fix applied!
Rerunning fig doctor to see if the problem is resolved.....

🟡 Could not get current user shell

❌ Default shell  is not compatible
   You are not using a supported shell.
   Only zsh, bash, or fish are integrated with Fig.

❌ PATH and PseudoTerminal PATH do not match

Looks like we've already tried this fix before and it's not working.

Run fig issue to let us know about this error!
Or, email us at hello@fig.io!
```

but I think my shell is perfectly parseable

```
corischlegel@CQ4N6YKGR2 ~ % ps -p $$
  PID TTY           TIME CMD
21769 ttys006    0:00.39 /bin/zsh --login                                                                                                                                    /0.0s
corischlegel@CQ4N6YKGR2 ~ % echo "$SHELL"
/bin/zsh
```


### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 

Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/cori/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installed via Brew: true
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (21769) - /dev/ttys006
Current working directory: /Users/cori
Current window identifier: 494/% (com.googlecode.iterm2)
Path: /usr/local/opt/avr-gcc@8/bin:/Users/cori/.nvm/versions/node/v12.22.10/bin:/Users/cori/.zplug/bin:/Users/cori/.cargo/bin:~/dotfiles/scripts/:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/cori/.fig/bin:/Users/cori/bin
Fig environment variables:
  - TERM_SESSION_ID=w1t0p0:CF6E22B2-79E4-4C64-90BD-55C3627A690A
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @jtexi001, this is really not an issue and `fig doctor` is giving bad output. A fix should be going out soon though!

**Comment by grant0417** [comment]
@cori-afs that is weird, could you try running `dscl . -read $HOME UserShell` and see what the output is.

**Comment by SeparateRecords** [comment]
@cori-afs is it working for you now? I think this should be fixed.
