### ISSUE TITLE
Fig is disabled in Terminal.app

### ISSUE THREAD

**Issue by tommasoperitoree** [withfig/fig#913]
### Description:
When running terminal, none of the settings from fig appear, while on the fig menu from the mac menu bar it says terminal not supported (see picture)

### Details:
<img width="660" alt="Screenshot 2022-02-08 at 22 12 20" src="https://user-images.githubusercontent.com/91907382/153076467-e13a0699-0200-4b3c-a00b-e81e7d53fa7a.png">

|macOS|Fig|Shell|
|-|-|-|
|12.2 21D49|1.0.55|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [Italian] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/tommasoperitore/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/tommasoperitore/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/tommasoperitore/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/tommasoperitore
Current window identifier: ???
Path: /Users/tommasoperitore/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/tommasoperitore/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=9F350EDE-6818-47C8-B5E0-F112CD34B0FD
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM_VERSION=3
  - FIG_TERM=1
MacOS Version: 12.2 21D49
Hardware:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
It looks like you've disabled autocomplete for Terminal.app!

You can check by running `fig settings integrations.terminal.disabled`. If this returns `true`, then you can resolve this issue by `fig settings integrations.terminal.disabled --delete`.

Try this and then let me know if you're still running into issues!

**Comment by tommasoperitoree** [comment]
It returns false
  
  
  
  
  
  
  

  
  
>

**Comment by mschrage** [comment]
Can you run `cat ~/.fig/settings.json` and share the output here?

**Comment by tommasoperitoree** [comment]
{
  "app.hideMenubarIcon": false,
  "autocomplete.disable": false,
  "autocomplete.theme": "dark",
  "pty.path": "/Users/tommasoperitore/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/tommasoperitore/.fig/bin"
}

**Comment by mschrage** [comment]
Hmm interesting. Can you run `defaults read com.mschrage.fig` and share the output?

**Comment by tommasoperitoree** [comment]
Here the results from running

defaults read com.mschrage.fig


{
    " 2022-02-09T00:00:00+0100#terminalUsage" = 391;
    "NSWindow Frame Main Window" = "400 400 300 300 0 0 1440 875 ";
    "NSWindow Frame NSSpellCheckerSubstitutionsPanel2" = "692 407 425 137 0 0 1440 875 ";
    SUAutomaticallyUpdate = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2022-02-08 21:58:47 +0000";
    "access_token" = "eyJraWQiOiJVTFRuVEZaNjdSeHF0NEh6XC84ZUx1T1wvYlA3TnpBV1MxT2JWS1hBN2I2eDA9IiwiYWxnIjoiUlMyNTYifQ.eyJvcmlnaW5fanRpIjoiMTE3NDE2ODAtYzQ0My00Mzk2LThlZGQtOTk3MzI4ZWZhZWNhIiwic3ViIjoiNTk1MjZiZmQtNWZjOS00YzU4LThhZjYtZDRmNTM3ZTMxZmU5IiwiZXZlbnRfaWQiOiIwNzY0YTNhMS0wOTc4LTQxNDItYTZlZC02NmVlMTE1NjBhZTMiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjQ0MzQ0MjU4LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9iWW4zRGlwR3kiLCJleHAiOjE2NDQzNDc4NTcsImlhdCI6MTY0NDM0NDI1OCwianRpIjoiNzllYzFhMmEtOTgzYy00YWIyLTk4OGMtODc5YTIzMDc1MWJjIiwiY2xpZW50X2lkIjoiaGtpbmNpb2hkcDFpN2gwaW1kazYzYTRidiIsInVzZXJuYW1lIjoiNWY5NzEzYjgtY2NhNC00ODQyLWI5NTktMTliMTlhOWNlYzI5In0.hMWLB4GRiRtIOtnIzzN7tYhWnE_eIGGbhqPq8pM3OP_Y5TT-_wcfUylfLUMuOZQ8xmyrodyPd7tYaHVT4BDZAJzicUE5z4VM6IFMmLYwFmFyEQEwA5ubBzxUXdKQCkDWJrIn_s-GtmpM_eMvaUKz3100wvyzfXG1vxRXxr56G6yr7LNeyALxpwqHzJ69NOngW_rhz_Nw3-TwWsd4bdvhb7CEfqfhK828AHZpHVRlVmQaNTog2Qaz6nEMUAe3DOrg6EKZD8S77UA5LyhoEsFRkupHp8e9D00Tc-erarRM5hqRtCrIWPRRIqykPkRinrHwqOTJtGjgBXL0_yMJUOH5QQ";
    accessibilityEnabledOnPreviousLaunch = 1;
    autocompleteVersion = v9;
    autocompleteWidth = 250;
    build = prod;
    clearExistingLineOnTerminalInsert = 1;
    "co.zeit.hyper.integration" = {length = 32, bytes = 0x7b226170 706c6963 6174696f 6e4e6f74 ... 64223a74 7275657d };
    "com.apple.Terminal.integration" = {length = 18, bytes = 0x7b22696e7374616c6c6564223a747275657d};
    "com.googlecode.iterm2.integration" = {length = 32, bytes = 0x7b226170 706c6963 6174696f 6e4e6f74 ... 64223a74 7275657d };
    "com.microsoft.VSCode.integration" = {length = 18, bytes = 0x7b22696e7374616c6c6564223a747275657d};
    "com.microsoft.VSCodeInsiders.integration" = {length = 32, bytes = 0x7b226170 706c6963 6174696f 6e4e6f74 ... 64223a74 7275657d };
    "com.visualstudio.code.oss.integration" = {length = 32, bytes = 0x7b226170 706c6963 6174696f 6e4e6f74 ... 64223a74 7275657d };
    "expires_in" = 3600;
    hasLaunched = 1;
    "id_token" = "eyJraWQiOiJ3VHJTSDY3SjVCMUp5QTNPMk9tVk16UVwvNjV0dnJpbW5YU0ZEa09mMUZWcz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI1OTUyNmJmZC01ZmM5LTRjNTgtOGFmNi1kNGY1MzdlMzFmZTkiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfYlluM0RpcEd5IiwiY29nbml0bzp1c2VybmFtZSI6IjVmOTcxM2I4LWNjYTQtNDg0Mi1iOTU5LTE5YjE5YTljZWMyOSIsIm9yaWdpbl9qdGkiOiIxMTc0MTY4MC1jNDQzLTQzOTYtOGVkZC05OTczMjhlZmFlY2EiLCJhdWQiOiJoa2luY2lvaGRwMWk3aDBpbWRrNjNhNGJ2IiwiZXZlbnRfaWQiOiIwNzY0YTNhMS0wOTc4LTQxNDItYTZlZC02NmVlMTE1NjBhZTMiLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTY0NDM0NDI1OCwiZXhwIjoxNjQ0MzQ3ODU3LCJpYXQiOjE2NDQzNDQyNTgsImp0aSI6ImI3NjQ0YjY0LTEwMGMtNGI0Yy1hNmYyLTA1MDQyMTlkOWFkNSIsImVtYWlsIjoidG9tbWFzb3Blcml0b3JlZUBnbWFpbC5jb20ifQ.oqe49Ux7DJALGydAm3Xlb4S92GtBwb1Wnh1o4fJL2VXH5gztWI3UUaqAiwKVDyZNbhlOC_RqfuQfKH3F6cxJy0iy4vY92BD_DKTgtVs_gAl49oSYBn1_I6LZyleFtu5H4e0xAWOeIDdfwz0S6Z1jDCQaJVvYcTQrC2QM8ozwGZbI0A3Ghr1iBTEC9IIlxlEgrcepQ8Sb30pNm3mVHaT50w5qaNAUZf-LWUVj1qqH-BkndF907Al6dk7q2Mafax1hWggpba2sZQ8wNshcfcVXxbd-DaHFT4NXBTGtx_VIMsWDqNb--xeK2mTM-nWhMFKnkpZMdEb3h9o2K_CHL9kJkA";
    ignoreProcessList = "figcli,gitstatusd-darwin-x86_64,gitstatusd-darwin-arm64,nc,fig_pty,starship,figterm";
    launchedFollowingCrash = 1;
    "org.tabby.integration" = {length = 32, bytes = 0x7b226170 706c6963 6174696f 6e4e6f74 ... 64223a74 7275657d };
    pendingTelemetryUpload =     (
        " 2022-02-09T00:00:00+0100"
    );
    "refresh_token" = "eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.ksed4Cdrh6KiX65m8NdVIilasKPF1oJUPr4QASfgftiFURAjakGpANLAzXJuatI048UiYFsVAxTWLcJY3WNtRHRN_V85ecpPMcWoBWTqt1JNcIvi-l9BT8vV6WVTCp4ZUdoTso4xLsLvXb677hgv6Q_X6cg8-m5QLzEk7AZ6jDCKu52DNkFIsky_CF2se0XPaomoLDRQFapekvcPKjCq3SxmFOec1lzSj96X6merwEEgTPDQLuMPenNVfFK-TDdyGUIfvU2Z8pwTvcpYuMSdBV4zzzV-t3xndjYsi3WSaNyH8Ve-G3gHydaFxfTu2guefbR6DlZdfTZ5TJvyjv46Aw.TK7yjTti1lkfVX0n._IVB9akShldgYdPosvTRyAFRNbsPRG0nPbQZkn29A5xOdgrlZTcEUS1HVBxQX3xvWTqcNNE1A3X2P8NF1JjJQLdAyrPT0gGROUAdmfW_-bCLSLHSY8J-LWFlgpdq-axs2BomAgremaLImwMCwXhvOGnsnbTxZ1SALQHL6UoptoC25muyNyzqwfsyaUWWFa0ZvgnBgm9RcOvjk4Q1xuK1EblCSUPFv0PaSuj34yXdpTBJMtBiIn0chxwokSmvawrZsU4oENYlVWXtih6MBdIIqEzwffLIM6inktbdjcdFVneZKSjLVUg54lkN5Xt47mXOTSE31FWhqwQY59KCLQOP0k91jCzbH3bgXBWkqEmPZRfcpzKbT0hix4csnOuhPGGC9ZXQ4AlfeLM3aJxC_aIywuzaWMRA3ljTTKVX9D69pIcIHW_dawlLFOMirOKrMrR7rrYdZwglC_Gk_iknfZ5XqupFocCg6iVsKnbcXmJAXqMoVKLj42rZGwpHzNy0RPBnuacHDyRsPJESiRrBiXbmU1TETx0FcBpA7BPHDDYHG6uwTN8BOqUMadOFgGMHjGmPNst8YhjRoXcZdjNfb64IXqoWHFJbeiEsA9CIePtgLJN7oKx7EgaTlBP2R6w2-kwoPNWV93Di1wPvhzO6xKhmiEL1NO97bpKoLkDoRIO351PtHYHS41PEJYAETN8GvdJEMptNZm7z8IyI3fcDVfM8QgVtmaCLXRzOPDeknii3msoKWteC0gSd6rOCB8uszhwgKXB99aN52XYP3s2X84l8DoIPFrC8qkEFjPDVM1hdyLz5NmUMK55sO1vs93CTp7WGcPH2dx6kvCtRERA6acf9YKWwaJB-SwEHjnGlqjvhuyAvHSQcTB8r4dSdT1QSUJfm2osCG23MC-pwoE90cO5dShSTjJqZyb93h_cAq0eYFyrhM2TKEbuc5n4UPd6PBHcS6EgrtLqmQXdCBfHtJw3SSDNxoBOgh0E3yP7qcP5UNv3ckHQqlo0dAtEF_MJGUKVetN8y5a6sFkBuYYwFJKqGTL2-0S_cbxbjW6PuLauq8TFFTXa_SeDBcFa5E-WWNefthy69cTnKui2mO5V4kiceYwTCAoHIYBMv9ku-_2hGYVC7AitGkBab02bdbgwvaVVxgGSlBmq_YRJCG5ZkNPMQ-nl8gKaFXeBynXGJrITBbofOZJzcPkvKG7NHImKZ_YxtrbhHxpWHQqcwvcpicdd4rAoAD78zOblX-BSVoS8v3Tk-D_TGJAeVqzNZVjR0X32vjKMKB75cjjENqIH1_OAbm-rJ_eIEtaL5S3mPsuUukXIwPziZHaYxuIwP.DW-guAk1X6r7UsoMS7QELQ";
    sidebar = hidden;
    useAutocomplete = 1;
    userEmail = ***@***.***";
    userShell = "UserShell: /bin/bash";
    "using_cognito" = 1;
    uuid = "554A3632-93BF-4E1F-B602-ED6551EFD482";
    versionAtPreviousLaunch = "1.0.55,365";
}

**Comment by mschrage** [comment]
This is very strange. The "Terminal is disabled" text only appears if a setting has been changed to prevent Fig from appearing when using Terminal.app. 

However, it looks like you don't have that setting enabled. 

Does Fig work in other terminals? eg. iTerm or VSCode?

**Comment by tommasoperitoree** [comment]
Yup, says the same thing with VSCode as well.
Do you suggest manually uninstalling and cleaning all related files?

**Comment by mschrage** [comment]
@tommasoperitoree - yeah, try a fresh install. Also make sure you follow these instructions when uninstalling: https://fig.io/support/other/uninstall
