### ISSUE TITLE
Not linked to terminal session

### ISSUE THREAD

**Issue by tommasoperitoree** [withfig/fig#914]
### Description:
Not sure what setting I didn't set correctly
<img width="662" alt="Screenshot 2022-02-08 at 22 15 08" src="https://user-images.githubusercontent.com/91907382/153076937-160799c0-f516-4646-bca5-44c4ed9a9dc1.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2 21D49|1.0.55|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [Italian] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/tommasoperitore/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/tommasoperitore/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/tommasoperitore/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/tommasoperitore
Current window identifier: 97/% (com.apple.Terminal)
Path: /Users/tommasoperitore/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/tommasoperitore/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=5B712163-9801-4C68-A08A-8E4F03E74ECE
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM_VERSION=3
  - FIG_TERM=1
MacOS Version: 12.2 21D49
Hardware:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB</pre>
</p>
</details>

**Comment by brendanfalk** [comment]
This is a duplicate of https://github.com/withfig/fig/issues/819
