### ISSUE TITLE
error when performing cd command immediately after connecting to remote server

### ISSUE THREAD

**Issue by justindantzer** [withfig/fig#92]
### Description:
An issue I've noted when first connecting to a remote server, and starting to type a `cd` command, I will sometimes see something like this:

`cd /some/path/'ls: cannot access '"'"'/home/username/some/path'"'"': No such file or directory'`

I've not been able to intentionally recreate the issue, with it occurring intermittently. Unsure if it is related to a slow connection, or perhaps fig has not fully initiated in some cases.

### Details:
|macOS|Fig|Shell|
|----|----|----|
|11.4.0|Version 1.0.42 (B207)|/bin/zsh|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.42 (B207) 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jdantzer/.fig/bin/fig
Accessibility: true
Number of specs: 109
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/jdantzer/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/jdantzer/.rvm/gems/ruby-2.4.0/bin:/Users/jdantzer/.rvm/gems/ruby-2.4.0@global/bin:/Users/jdantzer/.rvm/rubies/ruby-2.4.0/bin:/Users/jdantzer/Sites/spark-installer:/Users/jdantzer/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/X11/bin:/Users/jdantzer/.rvm/bin:/Users/jdantzer/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 13554/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by mattschrage** [comment]
Where does this error text appear? In the terminal itself or inside the Fig popup window?

**Comment by justindantzer** [comment]
In the terminal. I'll be typing the command and the window will popup, and I hit tab or enter, and then the text gets appended to the command, starting at the `'ls: ...`

**Comment by mschrage** [comment]
Closing this as stale. We have completely rewritten our SSH integration. For more details, see #709.
