### ISSUE TITLE
Not working with zplug

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#920]
With zplug loaded, fig does not work

<img width="256" alt="image" src="https://user-images.githubusercontent.com/52195359/153128314-8b5e5ba2-945c-411d-aa4e-890f36c71663.png">

I replaced `zplug load` with this snippet, then restarted Fig, and it resumed working for me.

```bash
[[ -z $PROCESS_LAUNCHED_BY_FIG ]] && zplug load
```

**Comment by SeparateRecords** [comment]
Oldest email I've been able to confirm is this bug is from December 1st

**Comment by kevinjalbert** [comment]
I wanted to add that this also made my `git` aliases work.

**Comment by brendanfalk** [comment]
Fix: use new Fig.js API to launch login shells in a separate process

**Comment by thiagorp** [comment]
@brendanfalk is that documented somewhere?

**Comment by SeparateRecords** [comment]
@thiagorp currently not implemented - this is how we'll go about fixing it 🙂

**Comment by brendanfalk** [comment]
This issue is partially solved

Right now, if you use Zplug, Fig will work however the following won't:
* Suggestions for first token or of a command (e.g. git, brew, etc)
* Aliases
* History
* Private completion specs

**To make it fully work, you must do the following manually:**

Add the following to your `.zshrc`
```bash
[[ -z $PROCESS_LAUNCHED_BY_FIG ]] && zplug load
```

**Comment by SeparateRecords** [comment]
Also, [this line](https://github.com/zplug/zplug/blob/c4dea766566b168a32dbfa8d10335e525ce39fcc/base/core/load.zsh#L3) is the one that causes the problem. I don't know that this line _is_ the problem (possibly triggers another bug), but commenting it out and restarting fig makes it start working again.

**Comment by SeparateRecords** [comment]
This should be fixed now!
