### ISSUE TITLE
PATH and PseudoTerminal PATH do not match

### ISSUE THREAD

**Issue by gumerovk** [withfig/fig#921]
### Description:
PATH and PseudoTerminal PATH do not match

I can fix this!
Running > fig app set-path

Setting $PATH variable in Fig pseudo-terminal...

Fig will now use the following path to locate the fig executable:
/usr/local/opt/python@3.10/bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/python@3.10/bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Users/gumerov/.fig/bin

            
Fix applied!
Rerunning fig doctor to see if the problem is resolved.....

❌ PATH and PseudoTerminal PATH do not match

Looks like we've already tried this fix before and it's not working.
<img width="849" alt="image" src="https://user-images.githubusercontent.com/97335095/153157995-23aadf4a-e35b-4bc4-980a-f22b09d6fd7c.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.14.6 18G9323|1.0.55|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installed via Brew: true
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: bash (55579) - /dev/ttys002
Current working directory: /Users/gumerov
Current window identifier: 767/% (com.apple.Terminal)
Path: /usr/local/opt/python@3.10/bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/python@3.10/bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Users/gumerov/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=BD5B2BD7-29CD-418F-95DB-BE5AD4B7646A
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM_VERSION=3
  - FIG_TERM=1
MacOS Version: 10.14.6 18G9323
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro13,1
  - Chip: 
  - Cores: 2
  - Memory: 8 GB</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @gumerovk and @lobatolais, this is really not an issue and `fig doctor` is giving bad output. A fix should be going out soon though!
