### ISSUE TITLE
not working from phpstorm terminal

### ISSUE THREAD

**Issue by gr1ng0wf** [withfig/fig#922]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
i use zsh terminal from my phpstorm and fig not working. 
PhpStorm version: 2021.3.1

My ~/.zshrc code:

#### head code:
```
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
export ZSH="/Users/gr1ng0wf/.oh-my-zsh"
ZSH_THEME="agnoster"
```

#### bottom code:
```
export PATH="/usr/local/opt/php@7.4/bin:$PATH"
export PATH="/usr/local/opt/php@7.4/sbin:$PATH"
alias sail=vendor/bin/sail

export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home"

[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2 21D49|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/opt/php@7.4/sbin:/usr/local/opt/php@7.4/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/gr1ng0wf/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/gr1ng0wf/Documents/dev/web/meet-market/back-api
Current window identifier: ???
Path: /usr/local/opt/php@7.4/sbin:/usr/local/opt/php@7.4/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/gr1ng0wf/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=8e98a26c-2606-46e2-8ced-737d7543433f
MacOS Version: 12.2 21D49
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @gr1ng0wf! Currently JetBrains IDEs aren't supported yet. See #49 for more details.
