### ISSUE TITLE
How to configure secure keyboard input for Hyper on MacOS?

### ISSUE THREAD

**Issue by btmurrell** [withfig/fig#924]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

`fig doctor` diagnoses no secure keyboard input.  [This document](https://fig.io/docs/support/secure-keyboard-input) explains how to configure secure input for terminals other than Hyper.  The details included in my generated issue content below show this, which is misleading:
```
SecureKeyboardInput: true
SecureKeyboardProcess: Hyper - co.zeit.hyper 
```

Why is doctor telling me there's a problem with secure keyboard input?

```
fig doctor

❌ Secure keyboard input
   Secure keyboard input is on
   Secure keyboard process is Hyper - co.zeit.hyper 

FYI, looks like your dotfiles are symlinked.
If you need to make modifications, make sure they're made in the right place.

❌ Doctor found errors. Please fix them and try again.
```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7 19H1419|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: hyper.js must include `fig-hyper-integration` in localPlugins.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/Cellar/python/2.7.8_2/bin:/usr/local/opt/openssl/bin:/Users/brianmurrell/bin:/bin:/Users/brianmurrell/.local/bin::/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/GE/bin:/Users/brianmurrell/.fig/bin:/usr/local/go/bin:/Users/brianmurrell/go/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Python/2.7/site-packages:/Users/brianmurrell/n/bin
SecureKeyboardInput: true
SecureKeyboardProcess: Hyper - co.zeit.hyper 
Current active process: zsh (30491) - /dev/ttys034
Current working directory: /Users/brianmurrell
Current window identifier: 43635/% (co.zeit.hyper)
Path: /usr/local/Cellar/python/2.7.8_2/bin:/usr/local/opt/openssl/bin:/Users/brianmurrell/bin:/bin:/Users/brianmurrell/.local/bin::/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/GE/bin:/Users/brianmurrell/.fig/bin:/usr/local/go/bin:/Users/brianmurrell/go/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Python/2.7/site-packages:/Users/brianmurrell/n/bin
Fig environment variables:
  - TERM_SESSION_ID=D22AB0E3-681C-4070-BC82-189019E49F2C
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 10.15.7 19H1419
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 8
  - Memory: 32 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @btmurrell! Check out this support guide: https://fig.io/docs/support/secure-keyboard-input

Hyper might not be responsible - it could be a password manager.
