### ISSUE TITLE
fig not integrating into terminal

### ISSUE THREAD

**Issue by Rcwynter** [withfig/fig#925]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When I run fig doctor it return the following:
**
❌ PATH and PseudoTerminal PATH do not match

Looks like we've already tried this fix before and it's not working.
**

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/rolandwynter/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (17767) - /dev/ttys002
Current working directory: /Users/rolandwynter
Current window identifier: 38392/% (com.apple.Terminal)
Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/rolandwynter/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=317AA197-17CB-426A-A6E6-2ECB63126EF4
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 8
  - Memory: 32 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @Rcwynter, besides this warning is Fig working for you?

**Comment by grant0417** [comment]
Hey @Rcwynter , this is really not an issue and fig doctor is giving bad output. A fix should be going out soon though!

If you are still having any other issues with Fig please open another issue!
