### ISSUE TITLE
Autocomplete not working on macOS with zsh

### ISSUE THREAD

**Issue by mivanov** [withfig/fig#93]
### Description:

Nothing is happening, either in the onboarding process or otherwise, where I would expect autocomplete to be invoked, such as `cd` Tested in Terminal app as well as iTerm. Also installed the iTerm integration, including Python runtime, but this did not fix the issue. Fig does have the accessibility permission. Also tried quitting other programs which may be monitoring keyboard input such as Alfred, Dash, and Rocket. This also did not help. Fig's debugger reports that everything should be working.

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.3.1|Version 1.0.42 (B207)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.42 (B207) 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/mivanov/.fig/bin/fig
Accessibility: true
Number of specs: 124
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/mivanov/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mivanov** [comment]
More helpful fig diagnostic:

```
Version 1.0.42 (B207)
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/mivanov/.fig/bin/fig
Accessibility: true
Number of specs: 124
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/mivanov/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (28028) - ttys001
Current working directory: /Users/mivanov
Current window identifier: 4621/1D5702D73-5433-478B-A276-1C2E5446F437% (com.googlecode.iterm2)
```

**Comment by mivanov** [comment]
Both the cwd and the keybuffer are correct.

**Comment by mattschrage** [comment]
If you type `git` and then add a space does anything show up? If suggestions appear for `git` but not `cd`, this would suggest the issue might have to do with the `$PATH` set in the psuedoterminal.

Try running `fig set:path` and see if this resolves the issue?

**Comment by mivanov** [comment]
No, nothing shows up after typing `git` and a space, either.

**Comment by mattschrage** [comment]
And to clarify, Fig also doesn't work in the default Terminal app?

**Comment by mivanov** [comment]
Correct

**Comment by mattschrage** [comment]
For future reference, the issue was that the `.ts` version of the completion specs had been downloaded.

To debug:
1. Run `ls ~/.fig/autocomplete`
2. If you see files ending in `.ts`, delete them.
3. Run `fig update`
