### ISSUE TITLE
Fig is not working for Iterm2

### ISSUE THREAD

**Issue by jtexi001** [withfig/fig#931]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2 21D49|1.0.55|/usr/local/Cellar/bash/5.1.4/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /usr/local/bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jorge/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: bash (8818) - /dev/ttys002
Current working directory: /Users/jorge
Current window identifier: 508/% (com.googlecode.iterm2)
Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jorge/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:5683D9E8-31B9-4861-AAB1-86F4FC7A901C
  - FIG_ENV_VAR=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2 21D49
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,3
  - Chip: 
  - Cores: 6
  - Memory: 32 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @jtexi001! So sorry that Fig isn't working for you.

Can you do the following debug steps?

1. Run `fig doctor` and share the output here.

2. Upload your `~/.bashrc` file

3. Take a screen recording with two terminals open. In the first, run `fig debug logs`. In the second, type "git commit" & "cd ".
