### ISSUE TITLE
Docker Integration

### ISSUE THREAD

**Issue by grant0417** [withfig/fig#932]
Currently docker is not integrated with Fig, the integration needs to be updated to work again.

**Comment by brendanfalk** [comment]
likely coming in v1.0.57 or v1.0.58 - will be pretty simple once SSH is live

**Comment by mschrage** [comment]
Autocomplete is now fully supported in Docker containers. 

See "[Autocomplete in Docker Containers](https://fig.io/user-manual/autocomplete/docker)" for instructions on how to set it up!
