### ISSUE TITLE
Prints "\033]697;DoneSourcing" when using `ssh -J` in Fish

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#937]
Report from emails (unable to follow up)

> Something is printing "\033]697;DoneSourcing" when it shouldn't, which is interfering with ssh -J (I'm using fish)

**Comment by mschrage** [comment]
This seems to be related to #854. cc @sullivan-sean

**Comment by macintacos** [comment]
Just noting that I see a roughly-similar thing with `kubectx` (commented on #854 as well https://github.com/withfig/fig/issues/854#issuecomment-1048023933)

**Comment by mschrage** [comment]
This issue has been resolved in more recent version. To make sure you're on the latest build, run `fig update`!
