### ISSUE TITLE
Fig crashes Zsh with Zim:Fw

### ISSUE THREAD

**Issue by yavko** [withfig/fig#94]
### Description:
Whenever running Zsh with Zim:FW it crashes on start.

I fixed by making

```
#### FIG ENV VARIABLES ####
 [ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
```

into

```
#### FIG ENV VARIABLES ####
# [ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
```

All it is making t a comment, which removes integration.

Hopes it gets fixed!

### Details:
|macOS|Fig|Shell|
|----|----|----|
|11.3.1|Version 1.0.42 (B207)|/bin/zsh|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.42 (B207) 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/yavor/.fig/bin/fig
Accessibility: true
Number of specs: 107
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/yavor/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (65324) - ttys001
Current working directory: /Users/yavor
Current window identifier: 63403/6A32F30E4-ED72-408F-906E-6DE89F4E8F4B% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by yavko** [comment]
Also Btw here is the link for Zim:Fw
[https://github.com/zimfw/zimfw](url)
and
[https://zimfw.sh/](url)

**Comment by sullivan-sean** [comment]
This seems to be an issue with `ZLE` which is used by both zimfw and fig. It seems like this line in the Fig config repo: https://github.com/withfig/config/blob/main/shell/zle.zsh#L53 conflicts with two lines that are added by zimfw. In particular in the `~/.zim/init.zsh` file added on install, the last two lines, something like the following, conflict:

```
source ~/.zim/modules/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zim/modules/zsh-history-substring-search/zsh-history-substring-search.zsh
```

These are likely coming from https://github.com/zsh-users/zsh-syntax-highlighting and https://github.com/zsh-users/zsh-history-substring-search 

Either of these lines together with the linked Fig ZLE line causes crash on startup. The links for these modules suggest this could be an ordering thing: both Fig and these ZLE modules would like to be sourced last. I don't have enough bandwidth to debug what the ideal ordering of these lines are/if theres an ordering where both Fig and zim work, but this is a starting point if you'd like to take a stab at debugging @yavko

**Comment by albertehc** [comment]
same problem for me, instacrash and event comment your line iterm dont start

**Comment by yavko** [comment]
The problem is a zle compat issue, I am trying to figure it out, for now just comment out this line in your zshrc
```zsh
#### FIG ENV VARIABLES ####
 [ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####

```

**Comment by yavko** [comment]
> This seems to be an issue with `ZLE` which is used by both zimfw and fig. It seems like this line in the Fig config repo: [https://github.com/withfig/config/blob/main/shell/zle.zsh#L53](https://github.com/withfig/config/blob/main/shell/zle.zsh?rgh-link-date=2021-07-29T20%3A02%3A45Z#L53) conflicts with two lines that are added by zimfw. In particular in the `~/.zim/init.zsh` file added on install, the last two lines, something like the following, conflict:
> 
> ```
> source ~/.zim/modules/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
> source ~/.zim/modules/zsh-history-substring-search/zsh-history-substring-search.zsh
> ```
> 
> These are likely coming from [zsh-users/zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) and [zsh-users/zsh-history-substring-search](https://github.com/zsh-users/zsh-history-substring-search)
> 
> Either of these lines together with the linked Fig ZLE line causes crash on startup. The links for these modules suggest this could be an ordering thing: both Fig and these ZLE modules would like to be sourced last. I don't have enough bandwidth to debug what the ideal ordering of these lines are/if theres an ordering where both Fig and zim work, but this is a starting point if you'd like to take a stab at debugging @yavko

I don't know how to debug stuff like this so maybe you can give me some tips? @sullivan-sean

**Comment by yavko** [comment]
FINALLY

**Comment by fwesss** [comment]
Fix was reverted due to side effects with history-substring-search on other zsh frameworks. Reopening until we have a better solution.

**Comment by mschrage** [comment]
This is finally resolved! Thanks for your patience.

**Comment by yavko** [comment]
how

**Comment by samtsai** [comment]
> Just want to add the message users with zimfw will see for easier issue searching:
> 
> ```
> /Users/satsai/.fig/shell/zle.zsh:4: no such file or directory: /Users/satsai/.fig/logs/zsh.log
> ```

I still see this.

```
% fig diagnostics
Fig Version: Version 1.0.52 (B326) [U.S.]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /var/folders/_0/45_t9l7x63nfp001b6vbcmlh0000gn/T/fnm_multishells/90977_1638474161053/bin:/Users/satsai/.jenv/shims:/Users/satsai/.jenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/satsai/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/satsai
Current window identifier: 15730/% (com.googlecode.iterm2)
Path: /var/folders/_0/45_t9l7x63nfp001b6vbcmlh0000gn/T/fnm_multishells/51336_1638540801081/bin:/Users/satsai/.jenv/shims:/Users/satsai/.jenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/satsai/.fig/bin
```

Also `fig doctor` seems to continue endlessly find then fix this issue:

```
❌ PATH and PseudoTerminal PATH do not match

I can fix this!
Running > fig app set-path


Setting $PATH variable in Fig pseudo-terminal...
``

**Comment by hirakujira** [comment]
If the error still occurs, try the following steps:

1. `zimfw update`
2. `zimfw upgrade`, then open a new terminal window
3. Uninstall Fig & reinstall Fig again
4. `touch ~/.fig/logs/zsh.log`

This fixed the error messages for me
