### ISSUE TITLE
Fig Accessibility Warning won't go away

### ISSUE THREAD

**Issue by jeregrine** [withfig/fig#940]
### Description:
Run fug:
See popup about fig accessbility, check and uncheck. No change popup stays. Doctor says Accessibility is disabled. 

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3 21E5206e|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: false
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: Extension is not installed.
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/jasonstiebs
Current window identifier: ???
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:C5125D25-9A43-4B90-A1D8-3FECC55F9954
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.3 21E5206e
Hardware:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Does this persist even after running `fig restart`? Is this on a personal computer?

**Comment by mschrage** [comment]
Hey @jeregrine. Try deleting Fig from the Accessibility pane by clicking the "-" button. Then add it back by pressing the "+" button.

Sometimes the macOS database that manages this gets locked in a weird state.

**Comment by jeregrine** [comment]
@mschrage that seems to have worked.
