### ISSUE TITLE
Emoji characters mess with fig

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#947]
### Bug 1

quits fig app
https://user-images.githubusercontent.com/4949076/153948453-0f10c9e4-042a-4203-a6d4-d3991d762b3d.mp4

### Bug 2 and bug 3
emoji insertion messes up backspace + figterm and/or autocomplete

https://user-images.githubusercontent.com/4949076/154142102-bd520b0f-7dd0-4972-98ea-35d09122a6f5.mp4

helpful note: javascript uses utf-16

**Comment by grant0417** [comment]
All of these should be fixed in v1.0.56.
