### ISSUE TITLE
Fig doctor error: PATH and PseudoTerminal PATH do not match

### ISSUE THREAD

**Issue by Rockgecko** [withfig/fig#949]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
Error found by fig doctor, which created this issue.

```
Rerunning fig doctor to see if the problem is resolved.....

❌ PATH and PseudoTerminal PATH do not match

Looks like we've already tried this fix before and it's not working.
```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.14.6 18G9323|1.0.55|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [British - PC] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Sirius/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: bash (73113) - /dev/ttys002
Current working directory: /Users/Sirius
Current window identifier: 11637/% (com.apple.Terminal)
Path: /Users/Sirius/opt/miniconda3/bin:/Users/Sirius/opt/miniconda3/condabin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/Users/Sirius/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=5B00442D-A13D-49E4-AB88-AA2595FDCA52
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM_VERSION=3
  - FIG_TERM=1
MacOS Version: 10.14.6 18G9323
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro11,1
  - Chip: 
  - Cores: 2
  - Memory: 8 GB</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @Rockgecko, this is really not an issue and `fig doctor` is giving bad output. A fix should be going out soon though!
