### ISSUE TITLE
Select suggestion by tab

### ISSUE THREAD

**Issue by ReinBentdal** [withfig/fig#951]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
I often that I have to press esc to prevent Penc from selecting suggestion instead of executing command. My suggestion is to add an option to select suggestion with the tab key instead of the enter key.  This makes it easier to run a command without accidentally selecting suggestion. The tab key is also commonly used as the key to accept suggestion when typing, which in this context would make sense as an alternative to the enter key.

**Comment by SeparateRecords** [comment]
Hey @ReinBentdal! This is already something you can configure - run `fig settings`, click on the Keybindings tab. Sounds like you want to set tab to "insert selected" and enter to "execute"?

Give that a go and let me know if it's what you're looking for. Would love to discuss UX improvements for this use case.

**Comment by ReinBentdal** [comment]
wow that did the trick! setting tab to "insert selected" and enter to "ignore" did the trick. 

Tested enter with "execute" with `cd` command. However after inserting suggestions with tab a few times and then pressing enter did not work. It did not. execute with the path I had set, but only the `cd` keyword.

Fig is such a nice program which greatly simplifies my terminal experience! Thanks!

**Comment by SeparateRecords** [comment]
That's super strange, glad you got it working though!

I think keybindings has a discoverability problem at the moment. To fix, maybe we could have "⌘ Keybindings" underneath "⚙️ Settings" in the dropdown, and a `fig keybindings` subcommand.

Thoughts? @ReinBentdal @brendanfalk @mschrage 

---

@fedeci is that what "execute" should be doing? Seems like it's executing everything up to the _previous_ token.
```
cd|         -> cd
cd abc|     -> cd
cd abc |    -> cd abc
```

**Comment by ReinBentdal** [comment]
I think leaving it as a separate tab is ok. Not quite sure why I didn't recognize it straight away. Might be because I was looking for a specific checkbox😅

All though I think it would make more sense to just have listed all commands and which key they are assigned to, instead of having the keys listed and to which command they run.
Maybe show the commands which are assigned to a key oat the top and the ones which are not assigned to a key below (under a title which says "Unassigned" or something). And then have an edit-icon to the right of a row to change which key which runs command. Makes sense?

I think it is not obvious that when creating a new custom keybinding, the default disappears.

**Comment by fedeci** [comment]
> @fedeci is that what "execute" should be doing? Seems like it's executing everything up to the _previous_ token.
> 
> ```
> 
> cd|         -> cd
> 
> cd abc|     -> cd
> 
> cd abc |    -> cd abc
> 
> ```
> 
> 
> 
> The default behaviour of enter is to execute the command anyway, so ignore works fine for this at least.

Definitely not what we want. Execute should behave accordingly to what enter does in a "normal" shell.

**Comment by SeparateRecords** [comment]
Going to close this issue and move it to a new one for the execute bug 🙂
