### ISSUE TITLE
PATH and PseudoTerminal PATH do not match

### ISSUE THREAD

**Issue by jiteshdhamaniya** [withfig/fig#952]
### Description:
> 
<img width="972" alt="Screenshot 2022-02-17 at 8 53 11 AM" src="https://user-images.githubusercontent.com/46275049/154398762-ff040357-e7a9-4caa-b412-74537de71b52.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2 21D48|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [ABC – India] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jiteshdhamaniya/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (54849) - /dev/ttys004
Current working directory: /Users/jiteshdhamaniya
Current window identifier: 27268/% (com.googlecode.iterm2)
Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/sbin:/sbin:/usr/bin:/bin:/Users/jiteshdhamaniya/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:89190F61-EA72-4887-A09D-D39DC3ED4944
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2 21D48
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB</pre>
</p>
</details>

**Comment by rootsongjc** [comment]
I just submitted a same issue https://github.com/withfig/fig/issues/955

**Comment by grant0417** [comment]
Hey @jiteshdhamaniya, this is really not an issue and `fig doctor` is giving bad output. A fix should be going out soon though!
