### ISSUE TITLE
❌ PATH and PseudoTerminal PATH do not match

### ISSUE THREAD

**Issue by rootsongjc** [withfig/fig#955]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [搜狗拼音] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/jimmy/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (88270) - /dev/ttys005
Current working directory: /Users/jimmy
Current window identifier: 20673/% (com.googlecode.iterm2)
Path: /Users/jimmy/.rvm/gems/ruby-2.4.1/bin:/Users/jimmy/.rvm/gems/ruby-2.4.1@global/bin:/Users/jimmy/.rvm/rubies/ruby-2.4.1/bin:/Users/jimmy/Workspace/google-cloud-sdk/bin:/Users/jimmy/.getistio/bin:/Users/jimmy/Workspace/go/bin:/usr/local/protoc/bin:/usr/local/opt/openjdk/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin:/usr/bin/:/usr/local/bin:/usr/sbin:/opt/local/bin:/Users/jimmy/Library/Python/2.7/bin/:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/usr/local/aria2/bin:/Library/Ballerina/ballerina-0.970.1/bin:/Users/jimmy/.cargo/bin:/Users/jimmy/.fig/bin:/Users/jimmy/.fzf/bin:/usr/local/Cellar/hadoop/3.1.2/libexec/sbin:/usr/local/Cellar/hadoop/3.1.2/libexec/bin:/usr/local/Cellar/hadoop/3.1.2/libexec/sbin:/usr/local/Cellar/hadoop/3.1.2/libexec/bin:/usr/local/Cellar/scala@2.11/2.11.12/bin:/usr/local/spark/bin:/Users/jimmy/Anaconda3/anaconda3/bin:/Users/jimmy/.rvm/bin
Fig environment variables:
  - TERM_SESSION_ID=w1t0p0:66DE353C-2A0E-4E4A-B6C8-1FAFF4F99C64
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by xty1992a** [comment]
+1

got same error

**Comment by brendanfalk** [comment]
@SeparateRecords could you please make a canonical issue with all the ❌ PATH and PseudoTerminal PATH do not match issues (all of [these](https://github.com/withfig/fig/issues?q=is%3Aissue+is%3Aopen+PATH+and+PseudoTerminal+PATH+do+not+match)) and then link to all of these + use that for user association.

One hunch here is that package manager version managers are causing this issue (e.g. ruby version manager, node version manager, `fnm`...). These adjust the path and are causing it to fail.

In saying that, in some cases, the path is never being set in the first place. 

@grant0417 Could you please investigate?

**Comment by grant0417** [comment]
Hey @rootsongjc and @xty1992a, this is really not an issue and `fig doctor` is giving bad output. A fix should be going out soon though!

**Comment by rootsongjc** [comment]
@grant0417 Thanks for the notice, and it really doesn't seem like this issue is affecting my usage at the moment either.
