### ISSUE TITLE
`fig_zsh_redraw`: zsh fork failed

### ISSUE THREAD

**Issue by abstractalgo** [withfig/fig#957]
### Description:
While using zsh terminal inside of VS Code, these errors started appearing. It takes the control away from me and other keyboard shortcuts don't work. Some time needs to pass until something gets unblocked and terminal starts being responsive again.

It has happened a few times, and with quits/restarts of Fig in between.

Not sure how to repro, I wasn't doing anything out of the ordinary.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/1355455/154719365-48c15bf1-8e9e-489a-beea-63b91524ab9e.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.3.0|Version 1.0.55 (B365)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B365) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/draganokanovic/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/draganokanovic/google-cloud-sdk/bin:/Users/draganokanovic/.nvm/versions/node/v14.16.1/bin:/usr/local/bin:/Users/draganokanovic/.pyenv/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/draganokanovic/.cargo/bin:/usr/ucb:/Users/draganokanovic/.fig/bin:/usr/local/mysql/bin:/Users/draganokanovic/code/aalgo//bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: 44845/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @abstractalgo, I haven't seen this before. We have recently changes out zsh integration to remove most of the shell specific code like `fig_zsh_redraw`.

Can you try updating to the latest version by running `fig update` or reinstalling the app from this [link](https://fig.io/download)?

**Comment by abstractalgo** [comment]
It hasn't happened again so far, but I also don't have a clear repro steps, so it's quite uncertain if the core issues was fixed or it still lurks and waits for the opportunity to appear again.

If it happens again, I'll reopen or so, but so far, so good. Thanks!
