### ISSUE TITLE
PATH and PseudoTerminal PATH do not match Unresolved by Fig Doctor

### ISSUE THREAD

**Issue by tmvanetten** [withfig/fig#958]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C51|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/todd/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (21665) - /dev/ttys004
Current working directory: /Users/todd
Current window identifier: 1105/% (com.apple.Terminal)
Path: /usr/local/sbin:/Users/user/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/Users/todd/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=56816AC1-671D-4438-9F68-A036BE9E4010
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.1 21C51
Hardware:
  - Model Name: iMac
  - Model Identifier: iMac18,3
  - Chip: 
  - Cores: 4
  - Memory: 64 GB</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @tmvanetten, this is really not an issue and `fig doctor` is giving bad output. A fix should be going out soon though!
