### ISSUE TITLE
fig.sh:9: parse error near `pathadd'

### ISSUE THREAD

**Issue by pannous** [withfig/fig#96]
Plain installation on mac M1 with zsh. 

When opening new Terminal.app tab:
`fig.sh:9: parse error near 'pathadd'`

**Comment by mschrage** [comment]
Hey @pannous! Can you share your `.zshrc`? I'd love to get this figured out. cc @fwesss

**Comment by fwesss** [comment]
@pannous Still running into this?
We've added a bunch of bug fixes in recent versions. If you're still seeing this, run `fig update`. If that fixes, great! If not, let us know and we'll look into this.

**Comment by pannous** [comment]
Works flawlessly now, thanks
