### ISSUE TITLE
Autocomplete in initial walkthrough not working, works fine after that

### ISSUE THREAD

**Issue by vordenken** [withfig/fig#960]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [ ] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Installed fig via Homebrew on my MacBook Air m1 - installation worked fine but the autocomplete-feature did not work in the initial walkthrough. I use iterm2 by default, even after restarting it the autocomplete menu didn't show up. After "skipping" the walkthrough it worked afterwards.
The command fig doctor doesn't work too, it just runs without an output...

### Environment

```bash
~ fig diagnostic
Fig Version: Version 1.0.55 (B381) [German]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/julian/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path:
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installed via Brew: true
Installation Script: true
PseudoTerminal Path:
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (69292) - /dev/ttys004
Current working directory: /Users/julian
Current window identifier: 14763/% (com.googlecode.iterm2)
Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/Users/julian/Library/Python/3.8/bin/:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin:/Users/julian/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t1p0:9395CEAB-CA85-43E3-A627-93DADB11E3F9
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM=1
  - FIG_TERM_VERSION=4.0.10
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
```

**Comment by mschrage** [comment]
I believe this has been fixed! @vordenken thanks for reporting and sorry for the delayed response.
