### ISSUE TITLE
fig thinks Accessibility is not enabled.

### ISSUE THREAD

**Issue by pwkeyser** [withfig/fig#966]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Accessibility is enabled, but fig doctor shows it's not ...

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B381) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: false
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/wouter/Progs/python/sb_backend/bin:/usr/local/opt/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Library/Apple/usr/bin:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/usr/local/opt/openjdk/bin:/usr/local/sbin:/Users/wouter/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/wouter/Progs/python/sb_backend/src
Current window identifier: ???
Path: /Users/wouter/Progs/python/sb_backend/bin:/usr/local/opt/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Library/Apple/usr/bin:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/wouter/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=47D1EDDC-25D8-4B01-BB01-8EEC3768F3EA
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro11,5
  - Chip: 
  - Cores: 4
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by mschrage** [comment]
Open System Preferences > Privacy & Security > Accessibility, then toggle the checkbox next to the Fig icon off and in again.

Usually this resets any problems with permissions, but let me know if you’re still running into issues.

**Comment by pwkeyser** [comment]
Thanks for the feedback. I tried what you suggest at the time without success. Problem is resolved after reboot. Many thanks 


Wouter Keyser

**Comment by mschrage** [comment]
Good to know! Glad to hear that everything is working now.
