### ISSUE TITLE
Potential issue with Fig?

### ISSUE THREAD

**Issue by tomgreenhill** [withfig/fig#967]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B381) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/tomgreenhill/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installed via Brew: true
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tomgreenhill/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/tomgreenhill/Sites/mugo/_and_beyond/cassius
Current window identifier: 64/% (com.googlecode.iterm2)
Path: /Users/tomgreenhill/.nvm/versions/node/v14.13.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin:/Users/tomgreenhill/.fig/bin:/Applications/MAMP/Library/bin/
Fig environment variables:
  - TERM_SESSION_ID=w0t4p0:C0203300-E44D-4765-A744-369C3763D109
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: 
  - Cores: 10
  - Memory: 32 GB</pre>
</p>
</details>

**Comment by fedeci** [comment]
Hi @tomgreenhill, could you explain what's the issue?

**Comment by tomgreenhill** [comment]
Hi @fedeci, apologies that got posted without my addition! I have since resolved things by running `fig doctor` - worked perfectly, thank you!
