### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by alwwwd** [withfig/fig#970]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.13.6 17G14042|1.0.55|-bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B381) [Beta] [Dev] [U.S.] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installed via Brew: true
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/alex/Desktop/my-blog-ru/master
Current window identifier: 3709/% (com.apple.Terminal)
Path: /Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
Fig environment variables:
  - TERM_SESSION_ID=BD9F2909-E040-4F8E-A247-8127762FF0F2
MacOS Version: 10.13.6 17G14042
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro7,1
  - Chip: 
  - Cores: 2
  - Memory: 6 GB</pre>
</p>
</details>

**Comment by fedeci** [comment]
Hi!
