### ISSUE TITLE
Issue with my terminal 

### ISSUE THREAD

**Issue by Anis1988** [withfig/fig#972]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.55 (B381)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B381) [Beta] [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/anismedini/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/anismedini/.rbenv/shims:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/anismedini/.fig/bin:/Users/anismedini/.dotnet/tools:/Applications/Postgres.app/Contents/Versions/11/bin:/Users/anismedini/Desktop/bin
SecureKeyboardInput: true
SecureKeyboardProcess: fig - com.mschrage.fig 
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
Hello! What was the problem with your terminal? Was it crashing? Fig not showing up?

**Comment by Anis1988** [comment]
Hi ,
First of all let me say this is one of the best tool I’ve ever used , it’s just amazing Thank you for your hard work 
 
Sometime when I log out from my computer and log in later, Fig doesn’t work on my terminal (like I said sometime not all the time )

To be honest it’s not a big deal if you have any tip from I could try it ,otherwise I’m still happy !! 


Thanks again for this amazing tool :)

**Comment by mschrage** [comment]
Hey @Anis1988! Thanks so much for the kind words.

Next time this happens can you run `fig debug logs` in one terminal sesson, then type 'git commit' in another and share the output here?

**Comment by Anis1988** [comment]
Hi There ,
Thank you so much for your speedy reply 
Everything is working properly now, it turns out the "Secure Keyboard Entry" was enabled causing Fig not to work 

Again Thank you so much, and have a blessing day / night

**Comment by mschrage** [comment]
Great to hear! I don't know how I missed that in the diagnostic output.
