### ISSUE TITLE
`cd` autocomplete freezes on loading spinner

### ISSUE THREAD

**Issue by thiagorp** [withfig/fig#973]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Issue Details

It might or might not be a coincidence, but ever since I started using `nix-darwin` and `home-manager` to manage my macbook pro, the autocomplete for `cd` hangs on the loading spinner and then fails. I tried looking here for issues that would solve my problem but couldn't find any.

Screenshot:

https://user-images.githubusercontent.com/571864/155034578-c78bc977-f90c-4a57-bc86-c9a724a2b0fb.mov

This is the debugger:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/571864/155034750-ef1270a4-6a8d-4a73-b167-3ed255e8d962.png">

### Environment

```bash
Fig Version: Version 1.0.55 (B381) [U.S. International – PC] 
UserShell: /run/current-system/sw/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /nix/store/z9954nxn3p9ryjvjvhpsrclbqr7w7w2n-zplug-2.4.2/bin:/Users/thiago/.nix-profile/bin:/etc/profiles/per-user/thiago/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:/Users/thiago/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (58386) - /dev/ttys004
Current working directory: /Users/thiago/.config/nixpkgs/darwin
Current window identifier: 15240/% (com.microsoft.VSCode)
Path: /nix/store/z9954nxn3p9ryjvjvhpsrclbqr7w7w2n-zplug-2.4.2/bin:/Users/thiago/.zplug/bin:/Users/thiago/.nix-profile/bin:/etc/profiles/per-user/thiago/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:/Users/thiago/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=3CCCED4F-9B2B-4D9C-B51A-2017EBC2FE30
  - FIG_TERM_VERSION=4.0.10
  - FIG_INTEGRATION_VERSION=6
  - FIG_CHECKED_PROMPTS=1
  - FIG_TERM=1
  - FIG_ENV_VAR=1
MacOS Version: 12.0.1 21A559
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB
```

**Comment by SeparateRecords** [comment]
Looks like zplug is in your path - do you use zplug? I think this might be #920 🙂

**Comment by thiagorp** [comment]
Oh wow I would have never imagined it was zplug! Thank you.

**Comment by SeparateRecords** [comment]
Yeah, it's super weird! If I hadn't spent time looking into before, it I would never have guessed it was zplug either.

The goal is that you shouldn't have to make _any_ changes to your config to use Fig, and _quite a lot of people use zplug_, so hopefully we can get this fixed very soon.

**Comment by thiagorp** [comment]
Just for the record, fig was also breaking non-interactive shells, and that was preventing me to run commends like `sudo -u thiago -i {command}` because it would load an interactive shell instead of running `{command}` as `thiago`.

To fix it I had to add this to my zsh's `.profile`:  https://github.com/thiagorp/nix-config/blob/main/home/thiago/zsh.nix#L77
