### ISSUE TITLE
Fig doctor does not output anything

### ISSUE THREAD

**Issue by simonbohnen** [withfig/fig#975]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

fig doctor never completes, does not output anything, and cannot be canceled using Control+D or Control+C. I am using the experimental Alacritty integration.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.55 (B381)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B381) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/simon/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by harisarang** [comment]
Even I am facing this issue 😢

**Comment by grant0417** [comment]
@simonbohnen @harisarang Sorry about this issue, a fix should be going out soon!
