### ISSUE TITLE
Fig blocks Chrome omnibox input for a second when creating a new tab

### ISSUE THREAD

**Issue by vjpr** [withfig/fig#98]
**Summary:**

When opening a new Chrome tab and immediately typing, input is blocked for a second or two - it varies.

If I kill the Fig process the issue goes away, but it comes back again after restarting and triggering an autocomplete.

Reproduce:

* Restart the Fig process.
* Trigger the autocomplete in iTerm (by typing `git ` for example)
* Open a new tab in Chrome and try to start typing. 

**Best guess:**

I wonder if there is some expensive blocking code in the Accessibility UI key logger hook, as this api is synchronous.

**System information:**

OS: MacOS Big Sur 11.2.1
Terminal: (MacOS Terminal, iTerm2, etc)
Version of Fig: 2.0

**Comment by falky97** [comment]
Understood - hoping to fix this in our next build (v1.0.44).

Cause is likely legacy code running errant processes when you are outside of a terminal app

**Comment by mschrage** [comment]
We've removed the legacy code as of v1.0.44 and Fig should only intercept keystrokes that take place in a supported terminal. 

I'm closing this issue but will reopen it if anyone else is experiencing this bug!
