### ISSUE TITLE
Can't ⌘V paste into the sign in screen

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#981]
Right click -> paste still works. 

@phuctm97 did this change recently? Is it intentional?

**Comment by brendanfalk** [comment]
@phuctm97 any updates?

**Comment by phuctm97** [comment]
Can confirm the issue is only happening on macOS app due to WKWebView specific configuration/limitation. It is working on app.fig.io. Finding solution to workaround this on macOS.
