### ISSUE TITLE
Press up arrow to go to history

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#982]
If the user has the top most suggestion in a list selected, they should be able to press the up arrow to go to history. This will then show history in Fig rather than in the shell.

This is likely a setting we should have turned on.

<img width="410" alt="CleanShot 2022-02-22 at 16 52 29@2x" src="https://user-images.githubusercontent.com/4949076/155244796-92ac29aa-f12b-43c1-87c3-228068d02fbd.png">

**Comment by brendanfalk** [comment]
Love it @fedeci

**Comment by fedeci** [comment]
Out!
