### ISSUE TITLE
Not linked to terminal sessions

### ISSUE THREAD

**Issue by schmurfy** [withfig/fig#984]
### Description:
I installed fig successfully by downloading the app and following the setup to the end but fig is not enabled for my terminal (iTerm2) (even within the setup tutorial), all I have is this (with iTerm2 in focus):

<img width="425" alt="screenshot_799" src="https://user-images.githubusercontent.com/2983/155277633-31d0f82f-9a0b-43f7-ba9a-ecd1d60cc08a.png">

And when trying to run `fig doctor` it just hangs doing nothing and I have to kill the process.

I am using iTerm2 Build 3.5.0beta2

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.55 (B381)|/usr/local/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B381) [French] 
UserShell: /usr/local/bin/bash
Bundle path: /Applications/_Apps/Dev/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Schmurfy/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: 27778/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by grant0417** [comment]
@schmurfy Can you try updating to the latest version? It should be Version 1.0.55 (B383)

**Comment by mschrage** [comment]
Hey @schmurfy, this is potentially similar to #987. Could you run `file ~/.fig/insertion-lock` and share the output here?

If a file exists, running `rm ~/.fig/insertion-lock` will resolve the issue.

**Comment by schmurfy** [comment]
No lock file:
```
file ~/.fig/insertion-lock
/Users/Schmurfy/.fig/insertion-lock: cannot open `/Users/Schmurfy/.fig/insertion-lock' (No such file or directory)
```

I updated to the latest version and restarted iTerm to be sure, now if I run `fig doctor` it no longer hangs and I get some output:
```
❌ Fig is installed in /Applications/_Apps/Dev/Fig.app
   You need to install Fig in /Applications.
   To fix: uninstall, then reinstall Fig.
   Remember to drag Fig into the Applications folder.

❌ Could not get iTerm version
🟡 You have iTerm's Bash Integration installed, but we could not check the version in ~/.iterm2_shell_integration.bash. Integration may be out of date. You can try updating in iTerm's menu by selecting "Install Shell Integration"

❌ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

it's annoying but I moved `Fig.app` anyway, reinstalled the iterm integration which had issues and now I am left with:

```
❌ Could not get iTerm version

❌ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!

```

Here is the new diagnostic:

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.55 (B383)|/usr/local/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B383) [French] 
UserShell: /usr/local/bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Schmurfy/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/Schmurfy/.cargo/bin:/Users/Schmurfy/.platformio/penv/bin:~:~/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/Schmurfy/.fig/bin:/opt/local/bin:/opt/local/lib/rabbitmq/bin:/usr/local/lib/luarocks/bin:/usr/local/share/npm/bin:/Users/Schmurfy/go/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: 33362/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by schmurfy** [comment]
After noticing a weird issue preventing me from pasting text in an ssh session I realized that having the fig script loaded from my `.bash_profile` was the culprit, after removing it I can now paste text again in ssh sessions, is that a know issue ?

I really starting to wonder if fig is for me...

**Comment by brendanfalk** [comment]
I believe we have fixed the "not linked to terminal session" issue

**Comment by schmurfy** [comment]
Thanks but the weird behaviour inside ssh session is a stopper for me.

**Comment by mschrage** [comment]
Hey @schmurfy! Can you share additional details on how to reproduce the behavior you're experiencing over ssh? For instance, things like:
- ssh version
- your local bashrc/zshrc as well as those on the remote machine
- the shell you're using - both local and remote
- 
 Also would you be open to jumping on a call to debug this together? https://calendly.com/withfig/debugging

**Comment by mschrage** [comment]
This should be fixed on more recent versions of Fig. Please update and see if you still experience this issue.
