### ISSUE TITLE
fig alpha command opens blank window

### ISSUE THREAD

**Issue by jwbackhouse** [withfig/fig#985]
### Description:

When running `fig alpha` it opens up a Fig application window, but it is blank. Same behaviour using both Alacritty and Terminal 
![Menubar_and_jamesbackhouse____documents_tmx_sh_and_Slack_____Unread_messages___eduMe___1_new_item](https://user-images.githubusercontent.com/42476198/155292730-dff3050a-699c-41f2-9a0a-f06be563c8da.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B383) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/jamesbackhouse/.rvm/gems/ruby-2.7.1/bin:/Users/jamesbackhouse/.rvm/gems/ruby-2.7.1@global/bin:/Users/jamesbackhouse/.rvm/rubies/ruby-2.7.1/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/jamesbackhouse/.rvm/gems/ruby-2.7.1/bin:/Users/jamesbackhouse/.rvm/gems/ruby-2.7.1@global/bin:/Users/jamesbackhouse/.rvm/rubies/ruby-2.7.1/bin:/Users/jamesbackhouse/.fig/bin:/Users/jamesbackhouse/Library/Android/sdk/emulator:/Users/jamesbackhouse/Library/Android/sdk/tools:/Users/jamesbackhouse/Library/Android/sdk/tools/bin:/Users/jamesbackhouse/Library/Android/sdk/platform-tools:/Users/jamesbackhouse/Library/Android/sdk/platform-tools@amplitude/react-native@latest:/Users/jamesbackhouse/.rvm/bin:/Users/jamesbackhouse/Library/Android/sdk/emulator:/Users/jamesbackhouse/Library/Android/sdk/tools:/Users/jamesbackhouse/Library/Android/sdk/tools/bin:/Users/jamesbackhouse/Library/Android/sdk/platform-tools:/Users/jamesbackhouse/Library/Android/sdk/platform-tools@amplitude/react-native@latest:/Users/jamesbackhouse/.rvm/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (2439) - /dev/ttys017
Current working directory: /Users/jamesbackhouse/codebase/beekeeper
Current window identifier: 84/% (io.alacritty)
Path: /Users/jamesbackhouse/.rvm/gems/ruby-2.7.1/bin:/Users/jamesbackhouse/.rvm/gems/ruby-2.7.1@global/bin:/Users/jamesbackhouse/.rvm/rubies/ruby-2.7.1/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/jamesbackhouse/.rvm/gems/ruby-2.7.1/bin:/Users/jamesbackhouse/.rvm/gems/ruby-2.7.1@global/bin:/Users/jamesbackhouse/.rvm/rubies/ruby-2.7.1/bin:/Users/jamesbackhouse/.fig/bin:/Users/jamesbackhouse/Library/Android/sdk/emulator:/Users/jamesbackhouse/Library/Android/sdk/tools:/Users/jamesbackhouse/Library/Android/sdk/tools/bin:/Users/jamesbackhouse/Library/Android/sdk/platform-tools:/Users/jamesbackhouse/Library/Android/sdk/platform-tools@amplitude/react-native@latest:/Users/jamesbackhouse/.rvm/bin:/Users/jamesbackhouse/Library/Android/sdk/emulator:/Users/jamesbackhouse/Library/Android/sdk/tools:/Users/jamesbackhouse/Library/Android/sdk/tools/bin:/Users/jamesbackhouse/Library/Android/sdk/platform-tools:/Users/jamesbackhouse/Library/Android/sdk/platform-tools@amplitude/react-native@latest:/Users/jamesbackhouse/.rvm/bin
Fig environment variables:
  - TERM_SESSION_ID=727EF5AC-F401-4F1D-BCAD-C1BF9A0610D6
  - FIG_CHECKED_PROMPTS=1
  - FIG_ENV_VAR=1
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM=1
  - FIG_TERM_VERSION=4.0.10
  - FIG_TERM_TMUX=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by fedeci** [comment]
It should take a couple seconds to load, is it not loading at all for you?

**Comment by mschrage** [comment]
Hey @jwbackhouse, can you right click the window and click "Inspect Elements" - there might be some clues as to what is going wrong in the console or network tab?

**Comment by jwbackhouse** [comment]
Hey @mschrage . Nothing that I can see unfortunately. Here's the console and network tabs following a reload:

![Web_Inspector_—_app_withfig_com_—_mission-control_and_jamesbackhouse____documents_tmx_sh](https://user-images.githubusercontent.com/42476198/155468907-8cd1d73c-e088-4f47-8abe-47cbbc6f5261.png)

![Web_Inspector_—_app_withfig_com_—_mission-control](https://user-images.githubusercontent.com/42476198/155468959-0310a326-1922-498d-aad8-9a9d497ea997.png)

**Comment by jwbackhouse** [comment]
Ah, well it turns out that right-clicking and hitting reload solves the issue 🎉. 
I noticed that the network tab had additional content after the reload, which I've circled for you. This wasn't visible when I first opened the inspector 🤔

![Web_Inspector_—_app_withfig_com_—_mission-control](https://user-images.githubusercontent.com/42476198/155469388-71724e22-6c08-4770-bea0-9947f9f3299c.png)

**Comment by mschrage** [comment]
Glad that everything is working now. I feel like I have run into this as well @phuctm97. Any ideas what might be happening here?
