### ISSUE TITLE
Fig has completely stopped working after updating. 

### ISSUE THREAD

**Issue by ShawnCockburn** [withfig/fig#987]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

updated to `1.0.55 (B383)` and fig has completely stopped working.

`fig doctor` detects no issues.

is it possible to downgrade???

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B383) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 204
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: installed!
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/Work/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/Work
Current window identifier: 251/% (co.zeit.hyper)
Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/Work/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=79FEB9C8-3252-4C7D-A52D-D7C27B069A4D
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM=1
  - FIG_TERM_VERSION=4.0.10
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,4
  - Chip: 
  - Cores: 8
  - Memory: 32 GB</pre>
</p>
</details>

**Comment by ShawnCockburn** [comment]
I will add computer restart does not fix and this: https://github.com/withfig/fig/issues/476#issuecomment-934680931 does not fix

**Comment by ShawnCockburn** [comment]
interestingly fig works on my personal account but not my work account (same fig version, same computer).

what could be causing this, @mschrage any ideas?

**Comment by mschrage** [comment]
@ShawnCockburn want to jump on a debugging call right now?

**Comment by ShawnCockburn** [comment]
sure!

**Comment by mschrage** [comment]
https://zoom.us/j/96871404279?pwd=R0RqaCt6ME1BMGhJaDJIOVl6RUxLdz09

**Comment by ShawnCockburn** [comment]
was fixed by running: `rm ~/.fig/insertion-lock`

thanks @mschrage
