### ISSUE TITLE
Own custom autocompletion spec not loaded on startup

### ISSUE THREAD

**Issue by Sillium** [withfig/fig#988]
### Description:
I wrote a custom completion spec in ~/Source/private/github.com/fig-autocomplete which is my fork of https://github.com/withfig/autocomplete.git. I have a file /src/awshelper.ts and after running `npm run build` I have a file /build/awshelper.js.

When I run `npm run dev`, I get the desired autocompletion in iTerm2 for `awshelper` (one of my own shell scripts). Even when I abort this with CTRL+C, the autocompletion continues to work.

However, after restarting fig, my custom autocompletion spec does not work anymore until I run `npm run dev` and abort it again.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1 21D62|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B383) [German] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/hstoerk/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installed via Brew: true
Installation Script: true
PseudoTerminal Path: /Users/hstoerk/.pip-apps/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hstoerk/.fig/bin:/usr/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/hstoerk/bin:/Users/hstoerk/.zgenom/unixorn/jpb.zshplugin/___/bin:/Users/hstoerk/.zgenom/unixorn/warhol.plugin.zsh/___/bin:/Users/hstoerk/.zgenom/unixorn/tumult.plugin.zsh/___/bin:/Users/hstoerk/.zgenom/unixorn/git-extra-commands/___/bin:/Users/hstoerk/.zgenom/unixorn/fzf-zsh-plugin/___/bin:/opt/homebrew/opt/fzf/bin:/Users/hstoerk/.zgenom/unixorn/bitbucket-git-helpers.plugin.zsh/___/bin:/Users/hstoerk/.zgenom/skx/sysadmin-util/___:/Users/hstoerk/.zgenom/StackExchange/blackbox/___/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (13961) - /dev/ttys004
Current working directory: /Users/hstoerk/Source/private/github.com/fig-autocomplete
Current window identifier: 258/% (com.googlecode.iterm2)
Path: /Users/hstoerk/.pip-apps/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hstoerk/.fig/bin:/usr/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/hstoerk/bin:/Users/hstoerk/.zgenom/unixorn/jpb.zshplugin/___/bin:/Users/hstoerk/.zgenom/unixorn/warhol.plugin.zsh/___/bin:/Users/hstoerk/.zgenom/unixorn/tumult.plugin.zsh/___/bin:/Users/hstoerk/.zgenom/unixorn/git-extra-commands/___/bin:/Users/hstoerk/.zgenom/unixorn/fzf-zsh-plugin/___/bin:/opt/homebrew/opt/fzf/bin:/Users/hstoerk/.zgenom/unixorn/bitbucket-git-helpers.plugin.zsh/___/bin:/Users/hstoerk/.zgenom/skx/sysadmin-util/___:/Users/hstoerk/.zgenom/StackExchange/blackbox/___/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p1:B33CCDA4-0882-4A67-8154-2590F0557236
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM=1
  - FIG_TERM_VERSION=4.0.10
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB</pre>
</p>
</details>

**Comment by Sillium** [comment]
I was not aware that I have to create an `autocomplete` folder inside `~/.fig` and copy the `awshelper.js` file there.

**Comment by fedeci** [comment]
Exactly, you figured out the solution! However it's strange that after ctrl+c the `npm run dev` process fig continues to show those suggestions🤔
