### ISSUE TITLE
I can't see suggestions in the tutorial

### ISSUE THREAD

**Issue by Palanx** [withfig/fig#989]
### Description:
I can't see suggestion in the tutorial, I restarted the service and nothing happens.
I'm using right now a Macbook Pro 14 M1 A2442

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.0|Version 1.0.55 (B381)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B381) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/palanx/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: 8547/% (com.apple.Terminal)</pre>
</p>
</details>

**Comment by grant0417** [comment]
Hey @Palanx, this is a known issue on the version you are on, please update to the latest version `v1.0.55 (B383)` and it should be fixed!
