### ISSUE TITLE
Fig is opening Activity Monitor

### ISSUE THREAD

**Issue by vfonic** [withfig/fig#99]
### Description:
I use `zsh-autosuggestions` in Oh my ZSH to autocomplete past shell commands (it autocompletes the command from my history with the command that has the same prefix).

Screenshot:
![](https://user-images.githubusercontent.com/67437/119949635-5bbe5080-bf9a-11eb-89ac-9a7cfed7ed9f.png)

At this point, if I press "right arrow" followed by "Enter", the command runs, but Activity Monitor gets open as well. 🤷‍♂️ 

![](https://user-images.githubusercontent.com/67437/119949639-5cef7d80-bf9a-11eb-85e6-0b5e1c71ecf0.png)

This basically made me disable the tool.

Thanks!

### Details:
|macOS|Fig|Shell|
|----|----|----|
|10.15.7|Version 1.0.42 (B207)|/bin/zsh|

<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.42 (B207) 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/viktor/.fig/bin/fig
Accessibility: true
Number of specs: 107
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/viktor/.fig/user/keybindings
iTerm Integration: true
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mattschrage** [comment]
This is so strange. To clarify, this only occurs when you first accept a suggestion from `zsh-autosuggestion` and then press enter?

Would you mind sharing a screen recording of this behavior, so I can see if anything stands out?

**Comment by vfonic** [comment]
Sorry for unnecessary intro/delay in the video:
https://www.dropbox.com/s/ioljlq767emeybm/Screen%20Recording%202021-05-29%20at%2009.18.01.mov?dl=0

All I did was type `cd Dow`, right arrow, enter

<details>
<summary>This is my .zsrhc with minimal changes (removed GITHUB_NOTIFICATIONS_TOKEN and comments)</summary>

```sh
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="viktor"

DISABLE_UPDATE_PROMPT="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
  autojump
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh
source $HOME/.rvm/scripts/rvm

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

eval "$(hub alias -s)"

export PATH="$PATH:$HOME/Dropbox/scripts"
if [ -f /usr/local/bin/trash ]; then alias rm="/usr/local/bin/trash"; fi

. ~/.aliases

export BUNDLER_EDITOR='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl -n -w'
export EDITOR='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl -n -w'

export PATH="/usr/local/opt/node@14/bin:$PATH"

export PATH="/usr/local/sbin:$PATH"

export PATH="$HOME/.rvm/gems/ruby-2.6.6/bin:$PATH"

[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
```
</details>

**Comment by mattschrage** [comment]
Sorry for my delay in responding! This is so bizarre. Would you be open to reinstalling Fig and seeing if this behavior still exists in the newest build (v1.0.45).

I think we'll need to debug this synchronously. Wanna grab some time on my calendar: https://calendly.com/mschrage/30min

**Comment by vfonic** [comment]
None of these times work for me @mattschrage. :(

The bug is still there in 1.0.45.

This is how I can reproduce the issue every time:
1. Type something that shows up Fig, for example: `cd `
2. Press "Right arrow"; Press "Enter"

**Comment by mattschrage** [comment]
Can you run `fig diagnostic` for me again? There is a chance this could happen if you initially launched the app directly from the DMG, rather than dragging it into /Applications.

Otherwise, we should find a time to chat that works for you because I'm struggling to reproduce this.

**Comment by vfonic** [comment]
<details>

<summary>~ > fig diagnostic</summary>

```
Version 1.0.45 (B218) [Viktor keyboard layout]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/viktor/.fig/bin/fig
Accessibility: true
Number of specs: 133
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/viktor/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/viktor/.rvm/gems/ruby-2.6.6/bin:/usr/local/sbin:/usr/local/opt/node@14/bin:/Users/viktor/.rvm/gems/ruby-2.6.7/bin:/Users/viktor/.rvm/gems/ruby-2.6.7@global/bin:/Users/viktor/.rvm/rubies/ruby-2.6.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/viktor/.fig/bin:/Users/viktor/.rvm/bin:/Users/viktor/Dropbox/scripts
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (55519) - ttys002
Current working directory: /Users/viktor
Current window identifier: 8662/% (com.googlecode.iterm2)
PATH: /Users/viktor/.rvm/gems/ruby-2.6.7/bin:/Users/viktor/.rvm/gems/ruby-2.6.7@global/bin:/Users/viktor/.rvm/rubies/ruby-2.6.7/bin:/usr/local/sbin:/usr/local/opt/node@14/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/viktor/.fig/bin:/Users/viktor/Dropbox/scripts:/Users/viktor/.rvm/bin
FIG_INTEGRATION_VERSION: 3
```

</details>

**Comment by mschrage** [comment]
Hmm still not sure what's going on. Can you try uninstalling and then reinstalling the app? Also @fwesss might be able to jump on a call with you and help debug!

**Comment by vfonic** [comment]
I already reinstalled it. I'm on holidays until the end of July. I'd love to jump on a call in August.

**Comment by mschrage** [comment]
Hey @vfonic! How your vacation was relaxing! Are you still open to a debugging call with me and @fwesss?

**Comment by vfonic** [comment]
Hey @mschrage! I just tested this again today and it doesn't seem to be happening again. I don't know what could have fixed it.

I'm on v1.0.45 (B218).

I see I wrote this before:
> The bug is still there in 1.0.45.

I'm not sure if the build number changed in the meantime. 🤷‍♂️
