### ISSUE TITLE
Fig does not work when logged into account via command line

### ISSUE THREAD

**Issue by ShawnCockburn** [withfig/fig#990]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

**Steps to reproduce:**

1. have two or more accounts on computer
2. login to an account from another account via the `login` command. (eg logged into work then `login` to personal).
3. try use fig auto complete, the dialog will show up but will not insert.

this did work before **fig** version `1.0.55 (B385)`.

https://user-images.githubusercontent.com/60285801/155528203-08d7d2a6-b818-47e6-bc0f-ff3d256cf5fa.mov

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.55 (B383)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B383) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Work/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: true
iTerm Integration: false 
Hyper Integration: true
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/Work/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by ShawnCockburn** [comment]
`login -p` fixes this issue, thanks @SeparateRecords  ❤️

**Comment by SeparateRecords** [comment]
We're changing how fig handles temp directories in the next update, so this workaround might not be necessary for much longer!
