### ISSUE TITLE
Fig is not working since ~1 week

### ISSUE THREAD

**Issue by pierretoure** [withfig/fig#993]
### Description:

Fig is **not working** for me since approximately one week.
Before that, it was working perfectly fine.

✅ Fig is correctly attached to iTerm2 terminal. 
✅ `Fig doctor` returns `Everything looks good!`

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.0|Version 1.0.55 (B383)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B383) [French] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/pierre.toure/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/pierre.toure/Downloads/google-cloud-sdk/bin:/Users/pierre.toure/.nvm/versions/node/v14.18.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pierre.toure/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (4987) - /dev/ttys002
Current terminal session: w0t0p0:7E2D38B8-64B3-45F3-9352-5FEB1AFD46EB
Current working directory: /Users/pierre.toure/Workspace/vitrine
Current window identifier: 887/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @pierretoure! So sorry to hear that Fig stopped working for you - I’d love to figure out what’s going on.

Can you take a screen recording of two terminal sessions. In the first, run `fig debug logs` and in the second, type `git commit`
