### ISSUE TITLE
tab with autocomplete.onlyShowOnTab when there's one suggestion should immediately insert it

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#995]
```
.
|- abc
|- def
```

If we typed `cd a` and hit tab, there's only one option for completion, this should be inserted

**Comment by qubist** [comment]
^ Inspired by an email I sent to fig. The motivation is to have the fig autocomplete tool not appear when it's not needed :)

Here's a video of what I mean:

https://user-images.githubusercontent.com/3607279/155812609-24584801-969c-4cf4-bb95-dbaf71371f1a.mov

> I have fig turned on to autocomplete only when I press tab. In `cd` when I’ve typed enough of a path for only one option to be autocompleted, and I press tab, fig still opens up the autocomplete window and makes me type tab again to select that option. I think this should only happen when there’s two or more autocomplete items that fig would show me.

> You can’t see when I’m pressing tab, but I’m sure you can see when I’m pressing Tab.

**Comment by qubist** [comment]
This bug/feature only occurs/makes sense when the `Show on Tab` setting is turned on. If this it's turned off, the fig window is constantly updating and once I've typed enough of the path to have an unambiguous tab-completion ready, fig is only displaying one suggestion, which is filled with the press of Tab.

**Comment by SeparateRecords** [comment]
@qubist this is now resolved! Fig now inserts the suggestion if there's only one.
