### ISSUE TITLE
Fig socket missing

### ISSUE THREAD

**Issue by j-f1** [withfig/fig#996]
### Description:
Fig doesn’t work. `fig doctor` outputs:

```
Checking dotfiles...

Let's make sure Fig is running...
✅ Fig bin exists
✅ Fig in PATH
✅ Fig is running
✅ Fig socket exists
✅ Daemon is running
❌ Figterm socket: No file at path /tmp/figterm-0453D969-B048-4DE7-A054-953485DCE615.socket


❌ Doctor found errors. Please fix them and try again.
```

`fig restart` does nothing.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.55|-fish|
<details><summary>Fig Diagnostic</summary>
<p>

# Fig Diagnostics

## Fig details:

  - Fig version: Version 1.0.55 (B388) [Beta] [U.S.]

  - Bundle path: /Applications/Fig.app

  - Autocomplete: true

  - Settings.json: true

  - Accessibility: true

  - Number of specs: 203

  - Symlinked dotfiles: false

  - Only insert on tab: false

  - Keybindings path: 

  - Installation Script: true

  - PseudoTerminal Path: 

  - SecureKeyboardInput: false

  - SecureKeyboardProcess: <none>

## Hardware Info:

  - Model Name: MacBook Pro

  - Model Identifier: MacBookPro18,3

  - Chip: Apple M1 Pro

  - Cores: 10 (8 performance and 2 efficiency)

  - Memory: 32 GB

## OS Info:

  - macOS 12.2.1 (21D62)

## Environment:

  - User Shell: /opt/homebrew/bin/fish

  - Current Directory: /Users/jed/Documents/github-clones/Forks/neeva-ios

  - CLI Installed: true

  - Executable Location: /Users/jed/.fig/bin/fig

  - Current Window ID: 5871/% (com.apple.Terminal)

  - Active Process: ??? (???) - ???

  - Environment Variables:

    - PATH=/Users/jed/.swiftenv/shims:/Users/jed/.asdf/shims:/opt/homebrew/Cellar/asdf/0.9.0/libexec/bin:/opt/homebrew/bin:/usr/sbin:/Users/jed/.fig/bin:/Users/jed/.yarn/bin:/Users/jed/.local/bin:/usr/local/bin:/usr/bin:/bin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/Applications/Racket v7.3/bin:/Applications/Wireshark.app/Contents/MacOS

    - TERM_SESSION_ID=0453D969-B048-4DE7-A054-953485DCE615

    - TERM=xterm-256color

## Integrations:

  - SSH: false

  - TMUX: false

  - iTerm: application is not present.

  - Hyper: application is not present.

  - Visual Studio Code: application is not present.

  - Docker: false

</p>
</details>

**Comment by th-m** [comment]
I am seeing this same issue

**Comment by th-m** [comment]
After moving some stuff around in my rc file the issue was resolved.  Interesting thing was, both fig commands where correctly placed at the top and bottom of the file.

**Comment by mschrage** [comment]
@j-f1 are you still experiencing this bug?

**Comment by j-f1** [comment]
Fig sometimes works for me, but I’m still seeing this happen frequently.

**Comment by mschrage** [comment]
Hmm @j-f1 Based on the diagnostic output you shared, Fig wasn't sourced in your terminal.

Can you open a new terminal session, run `fig diagnostic` and share the output here?

**Comment by j-f1** [comment]
Ok, it looks like new terminal windows do work OK. However, some (or all? not sure) terminal windows restored upon restarting macOS don’t properly connect to Fig.

**Comment by SeparateRecords** [comment]
Going to close this now since it seems to be working, definitely create another issue if it breaks again.
